### ISSUE TITLE
Form Fields | Descriptions

### ISSUE THREAD

**Issue by JBubs** [MicrosoftDocs/powerapps-docs#100]
Many of my fields had descriptions when I configured them in Sharepoint, but they disappeared when I customized the form. How do I bring back the descriptions?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Thanks for the feedbac, @JBubs! PowerApps doesn't support showing descriptions of SharePoint fields. We're working to update [this list](https://docs.microsoft.com/connectors/sql/#known-issues-and-limitations of known issues).
