### ISSUE TITLE
Test Suites included in Canvas App package

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#1000]
Are the Test Suites and Cases we create included in the xml and json in our Canvas Apps Package when we export to another environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb6392fe-8157-6760-00e7-b9ca3dc3b51d
* Version Independent ID: a2eb8009-1c13-1eb6-b716-f5afea70de60
* Content: [Test Studio for testing canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/test-studio)
* Content Source: [powerapps-docs/maker/canvas-apps/test-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/test-studio.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **aheaney**

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. Yes, test cases and suites are included when canvas app is exported and imported. Content has been added with this information; please allow some time for changes to reflect.
