### ISSUE TITLE
Excel Edit PowerApps Entity Data Add-in Help

### ISSUE THREAD

**Issue by sngoh55** [MicrosoftDocs/powerapps-docs#1001]
Hello All,

I want to create a button to launch the Excel that connects the PowerApps Entity data I want to edit. Basically I don't want to go through PowerApps, clicking Entities and then clicking the Edit Data in Excel button.

Is there a known way to do this or do I need to create a gallery edit form as the only way to edit the data through the app?

Best Regards,

**Comment by iangpgh** [comment]
in-progress

**Comment by iangpgh** [comment]
@sngoh55 This looks like a question about canvas apps. Can you tell me which topic or topics you are referring to? Thanks.

**Comment by sngoh55** [comment]
Hi,

Wanted to see if I could open the edit in excel of a custom cds entity
within canvas. I know you can in model driven and the regular powerapps
home site but wanted to add it in my actual canvas application.

**Comment by iangpgh** [comment]
@sngoh55 It looks as if a Gallery control would be the only way to accomplish this. I will pass this feedback along to the feature PM. Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. 
Closing this issue.

**Comment by iangpgh** [comment]
close

**Comment by iangpgh** [comment]
@mattp123 - Closes #1001
