### ISSUE TITLE
What is a "connection"

### ISSUE THREAD

**Issue by timrobinson33** [MicrosoftDocs/powerapps-docs#1004]
Since the Web API uses HTTP, it is inherently connectionless, so it is not at all clear what constitutes a "connection" in the context of this document. Does each API call count as a separate connection, or is it the lifetime of the bearer access token, or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd657fb-b2cb-a85a-7243-41d7cc30dc87
* Version Independent ID: 4ed6833a-668b-ff05-97da-286fb6d68394
* Content: [Service Protection API Limits (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/api-limits.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by osekodk** [comment]
I would like to know this too.

**Comment by hazbark** [comment]
On Friday, April 3, 2020, 12:55:10 AM CDT, Oliver Kogut <notifications@github.com> wrote:  
 
 


I would like to know this too.

**Comment by JimDaly** [comment]
@timrobinson33 , @osekodk , and @hazbark 
This topic has been totally re-written to be (hopefully) clearer, more specific, and offer samples to demonstrate how to achieve the recommendations.

It no longer refers to 'connections'.
I'm going to close this, but welcome any questions you may have.
