### ISSUE TITLE
This information doesn't help if you are about to create a ticket for an issue with Power Portals

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/powerapps-docs#1005]
The ticket creation page https://powerapps.microsoft.com/en-us/support/pro/ticket/ provides a link to this page, but for portals you cannot see App ID in that way as described here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7b75ec-2194-9cbb-d321-71ba81990643
* Version Independent ID: 5ed344a8-55e7-385a-9298-7f587e213b86
* Content: [Get a session ID or a canvas-app ID - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/get-sessionid#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/get-sessionid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/get-sessionid.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. Please use https://admin.powerplatform.microsoft.com/support link instead for creating support service request and select **New support request**.
