### ISSUE TITLE
Please clarify IP usage versus Required Services

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/powerapps-docs#1006]
We use Microsoft InTune for mobile device management.  Intune enforces network access policies via a allowed/disallowed list of network addresses (e.g. Web site URLs such as DISALLOW: http://*.youtube.com).  InTune does NOT allow IP addresses for network whitelisting or blocking.  It is not clear from this article if we need to add ONLY the Required Services entries to our devices' allowed/whitelist network addresses OR if we need both the IP Addresses and Required Services entries in that whitelist.  Our PApps use a mixture of MSFT connectors such as SQL Server (Azure and via OnPrem Gateway) and O365 (e.g. OneDrive, SharePointOnline).  Please expand this article to more clearly explain what network targets MUST be accessible from a device running either the PowerApps IOS/Android app or a Web browser using the PowerApps Web Player.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e8858f-ee37-b1f0-2ad1-a52416f58d0d
* Version Independent ID: 23c5799a-0e3a-bd52-8f8c-ce586c93e632
* Content: [System requirements, limits, and configuration values for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#ip-addresses)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. IP list and required services are not alternatives. Both are listed separately and required. As documentation states, IP address listing is because we don't publish fully qualified domain names available for Power Apps scenarios. And the required services lists all services to which Power Apps Studio talks and their usages that shouldn't be blocked.
