### ISSUE TITLE
Power Apps Portals in Community Plan

### ISSUE THREAD

**Issue by mikewaretena** [MicrosoftDocs/powerapps-docs#1007]
Is it possible to have Power Apps Portals included in the Community plan? I added one to mine but I still get a 30 day trial portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d27942c-51fc-c2dc-9857-bcbfbadba145
* Version Independent ID: 832089db-9a05-9d52-7529-429e3a6648f8
* Content: [Power Apps Community Plan -- a free development environment for individual use - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @ImadYanni
* Microsoft Alias: **iyanni**

**Comment by ImadYanni** [comment]
Can you please not assign something to me without my directly discussing with me first?
Please unassign. I am not sure why you thought this is something I would own.
Please explain.

**Comment by KumarVivek** [comment]
This issue is too old. Please see Power Pages licensing for the latest info: https://learn.microsoft.com/en-us/power-pages/go-live/assign-licensing
