### ISSUE TITLE
How to submit bugs in the tool (not the documentation)

### ISSUE THREAD

**Issue by jlundstocholm** [MicrosoftDocs/powerapps-docs#1008]
It is really hard to figure out where to submit details about a bug in the PowerApps Build tools. Is it through GitHub (and where, then?), through Twitter? Somewhere else? I could ask a question on the Azure DevOps Market place, but it is not really suited for this.

Thanks :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a4bd57a-00f9-4e94-9273-d53094720f32
* Version Independent ID: e589dc8c-11a4-27dd-835d-f0ecff880d1b
* Content: [Build tools for Azure DevOps overview - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-overview?source=docs#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-overview.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by KumarVivek** [comment]
@jlundstocholm To report issues and provide feedback about Power Apps Build Tools, please visit https://ideas.powerapps.com/.

cc: @mikkelsen2000 

Closing the issue.
