### ISSUE TITLE
I can't submit comments when i use es-es language

### ISSUE THREAD

**Issue by danielftk** [MicrosoftDocs/powerapps-docs#1010]
I can't submit an error using es-es language nor see the existing ones. There is an error message. Thanks Microsoft Team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca396f1f-9063-203c-5663-bc1750ac0d7f
* Version Independent ID: 639bd566-335e-b107-d60d-ba158b29c908
* Content: [Filtering - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/filtering)
* Content Source: [powerapps-docs/developer/component-framework/reference/filtering.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/filtering.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@danielftk Thanks for the feedback. Are you trying to raise a GitHub issue on the doc or do you have issue with localization?

**Comment by danielftk** [comment]
yes, first I found a typo using the page on es-es lang (green highlighted). Then I tried to raise an issue using the same es-es page but it returns me an error on the GitHub/issues section (Aqua highlighted
![Issues using es-es](https://user-images.githubusercontent.com/3487413/74366113-ffc7bc80-4d94-11ea-8177-27646987362e.PNG)
). Finally, I post the issue using the en-us page. The issue: https://github.com/MicrosoftDocs/powerapps-docs/issues/1011#issue-561416052

**Comment by Nkrb** [comment]
@danielftk Thanks for the details. This is a localization issue and will be fixed in the next update.

**Comment by mhogan73** [comment]
I will investigate and fix.

**Comment by mhogan73** [comment]
Assigning to @jowilco

**Comment by jowilco** [comment]
Hello @danielftk - I believe that you should now be able to create issues in the future. Please let us know if you are still having issues.

I will address #1011 shortly.
