### ISSUE TITLE
Error on string using es-es language

### ISSUE THREAD

**Issue by danielftk** [MicrosoftDocs/powerapps-docs#1011]
There is a "0x%08x" string instead of getFilter using es-es language.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca396f1f-9063-203c-5663-bc1750ac0d7f
* Version Independent ID: 639bd566-335e-b107-d60d-ba158b29c908
* Content: [Filtering - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/filtering)
* Content Source: [powerapps-docs/developer/component-framework/reference/filtering.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/filtering.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by mhogan73** [comment]
Investigating.

**Comment by mhogan73** [comment]
Assigning to @jowilco

**Comment by jowilco** [comment]
@danielftk This has now been fixed and the change is live. Thank you for identifying the issue.

**Comment by danielftk** [comment]
Thank you :D
