### ISSUE TITLE
Forms as a modal dialog

### ISSUE THREAD

**Issue by RicLund** [MicrosoftDocs/powerapps-docs#1012]
When will this doc be updated to include opening a single record form as a modal dialog per the preview feature? https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave1/microsoft-powerapps/enable-creating-editing-data-forms-displayed-as-modal-dialog-without-navigating-away

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by RamanathanCT** [comment]
@Riclund : Documentation updated in https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/customize-entity-forms

**Comment by RicLund** [comment]
Looks great - love the examples and screenshots! Thanks a lot @KumarVivek @bishalgoswami
