### ISSUE TITLE
Missing event-property

### ISSUE THREAD

**Issue by nilsvbconxion** [MicrosoftDocs/powerapps-docs#1013]
No mention about the OnChange-event and the difference between the OnSelect-event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c73d9b9-7cb5-f7ee-8c70-227309c9b18b
* Version Independent ID: 5276fa3a-3cf9-70e5-5324-85e0ebc24c56
* Content: [Date Picker control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-date-picker#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-date-picker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-date-picker.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated. Please allow some time for changes to reflect.
