### ISSUE TITLE
How to get the powerapp env url that can be used in Export solution task ?

### ISSUE THREAD

**Issue by AnkitGirgas** [MicrosoftDocs/powerapps-docs#1015]
I've created a generic service connection in my devops and tried using the env url where my powerapp is hosted, but it doesnt work. Error below,

##[error]Failed to connect to instance: https://make.powerapps.com/environments/<env-guid>. Please verify your credentials for *** and instance url.

Not sure if I'm using the right url

**Comment by phecke** [comment]
@AnkitGirgas I have contacted several PMs and asked them to respond to your question. Hopefully, you will get an answer soon.

**Comment by AnkitGirgas** [comment]
@phecke Its resolved now, one needs to get the dynamics crm env url to make it work.
Thanks.
