### ISSUE TITLE
There should be a Best Practices page

### ISSUE THREAD

**Issue by 365lyf** [MicrosoftDocs/powerapps-docs#1018]
I think there should be a best practices page, where I can add the following:

"Keep the control generic, and do not build controls that access the XRM API (e.g. Xrm.Page.getAttribute("name")).  Instead create an input variable and pass the value in as a parameter."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92b265c-b3a2-913b-438c-a7ff73377430
* Version Independent ID: f229173f-aa51-23d3-1092-37655bc59625
* Content: [Power Apps component framework overview - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/overview#feedback)
* Content Source: [powerapps-docs/developer/component-framework/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/overview.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@365lyf Thanks for the feedback. We are in the process of adding best practice page soon. May be in a  couple of weeks. After that people can start providing more information.

**Comment by Nkrb** [comment]
Closing this issue for now.
