### ISSUE TITLE
Is this outdated? [sharing CDS for Apps]

### ISSUE THREAD

**Issue by cjh15hub** [MicrosoftDocs/powerapps-docs#102]
I'm trying to share a power app that uses the CDS of a new environment I created. I shared the app successfully, but he is unable to work with (edit or use) the app because there is some problem with the his connection to the data. My understanding is this article is supposed to show how this is done, but the advanced customization menu looks different, and when I click security roles, this fails with an error on the next screen and then redirects me to Settings &gt; Processes in Dynamics 365 after I close the error modal. What should I do to resolve this permissions issue with the power app I shared?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fb8dba-da1c-6845-d301-c3b18a6b98ef
* Version Independent ID: a5d1fd66-fe5b-f52d-47de-6af3c71928f7
* Content: [Share a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#manage-entity-permissions)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by linhtranms** [comment]
Hi, 

This is likely because you shared the app with your coworker but haven't shared the CDS data with him/her. This is done via assigning him/her a security roles to the appropriate data entities. Can you please let us know the specific error you received when clicking on security roles or whether this issue is resolved?

**Comment by AFTOwen** [comment]
@cjh15hub If this is still a problem, can you please let us know the specific error you received? Thanks.
