### ISSUE TITLE
ComboBox's Search incompatible with numerical data

### ISSUE THREAD

**Issue by Slaverty6** [MicrosoftDocs/powerapps-docs#1020]
Hi,
ComboBoxes don't seem to be able to search if the data source are numbers.  Converting the numbers to text allows search to work.  I don't see this mentioned anywhere here, really should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8bf3d3-12e3-5b55-8713-221cf5f5a30c
* Version Independent ID: 5a050d01-6ef6-97d6-07de-d5cac82dea06
* Content: [Combo box control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-combo-box)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated. Please allow some time for changes to reflect.
