### ISSUE TITLE
Multi-factor authentication (MFA)

### ISSUE THREAD

**Issue by tdutch1** [MicrosoftDocs/powerapps-docs#1021]
Can this common login control connect to a CDS environment if multi-factor authentication (MFA) is enabled for the account or tenant? I'm getting the following error with MFA enforced: "An unsecured or incorrectly secured fault was received from the other party." The control works fine in other environments/tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62e76f4-65f7-052a-79cb-d6381c7424f2
* Version Independent ID: 462fa6bc-8277-9b09-3516-52bdce21f8d3
* Content: [Use the XRM tooling common login control in your client applications (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-xrm-tooling-common-login-control-client-applications#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-xrm-tooling-common-login-control-client-applications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-xrm-tooling-common-login-control-client-applications.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by MattB-msft** [comment]
Yes, this can be done, 
In the login control you need to add your own AppID and Redirect URI for it to work. 
if you used the samples. 
For example: 
            // Client ID to use for oAuth.  ID: 51f81489-12ee-4a9e-aaae-a2591f45987d is a sample ID that should be replaced by a ID created for your use. 
            mgr.ClientId = "51f81489-12ee-4a9e-aaae-a2591f45987d";
            // Redirect URI required for oAuth.
            mgr.RedirectUri = new Uri("app://58145B91-0C36-4500-8554-080854F2AC97");

which is added to the CrmConnectionManager object..

there is a full sample here;
https://github.com/microsoft/PowerApps-Samples/blob/master/cds/LoginUX/ExampleLoginForm.xaml.cs

**Comment by Nkrb** [comment]
@tdutch1 Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
