### ISSUE TITLE
Loading components fails

### ISSUE THREAD

**Issue by martynlesbirel-axon** [MicrosoftDocs/powerapps-docs#1022]
Apparently as documented at this page https://docs.microsoft.com/en-us/power-platform/admin/doc-management-known-issues opening a component within an iframe under certain circumstances fails. It would be nice if such limitations were listed on this page as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc52e199-1265-9879-665b-ade576488422
* Version Independent ID: 53e02cfd-ba49-c931-3e44-f8fc762480be
* Content: [setSrc (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setsrc#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setSrc.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setSrc.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Done. Closing the issue.
