### ISSUE TITLE
"Show text, dates, and times in Power Apps" is misleading

### ISSUE THREAD

**Issue by wygoodin** [MicrosoftDocs/powerapps-docs#1023]
[This article](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/show-text-dates-times) implies an inaccurate interpretation of the `DateTimeValue` and `DateValue` functions. In "Format dates and times by using `DateTimeValue`", at the third step, the article implies that running `DateTimeValue(..., "fr")` converts the date into a French date. The reverse is true: that function is parsing the input text as if it's a French date, which is why it flips the date in the output in the example. You can see the issue if you run `DateValue("12/20/2020", "fr")`, which will output "8/12/2021" if formatted, because it's interpreting `20` as a really large month number in French.

I was going to submit a PR myself, but a enough of the article is predicated on the idea that `DateTimeValue` and `DateValue` are what's doing the formatting, rather than the parsing, that I wasn't sure how to maintain the original purpose of the article while using `Text` for formatting, instead of the date parsing functions.

**Comment by tapanm-MSFT** [comment]
Discussed internally and closing this task without documentation changes.
