### ISSUE TITLE
Does this work in Unified Interface?

### ISSUE THREAD

**Issue by skoofy5** [MicrosoftDocs/powerapps-docs#1024]
I've been trying to add this to a lookup for a United Interface app but it doesn't seem to be working there - has this been deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900de2ab-7892-7c8c-014e-9acacfba265d
* Version Independent ID: ab0e41ac-7b93-8253-2a6c-5a0b3fac9bb0
* Content: [addCustomView (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addcustomview#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addCustomView.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addCustomView.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by DigitalFlow** [comment]
@skoofy5:
Works for us in latest Online Org and in UCI.

```js
lookup.addCustomView("{deadbeef-0000-0000-0000-000000000000}", "account", "Custom View Name", "<fetch>...", "<grid>...", true);
```

Kind Regards,
Florian

**Comment by KumarVivek** [comment]
Closing this issues as this works in Unified Interface.
