### ISSUE TITLE
Can we capture user roles as well?

### ISSUE THREAD

**Issue by gladiatorAsh** [MicrosoftDocs/powerapps-docs#1025]
It's not clear from the page, if we can capture additional information about the user apart from just Name , Email and Picture. If not, is that a feature that is currently being worked on?

I see there are other issues open, related to this,which are not closed yet 
https://github.com/MicrosoftDocs/powerapps-docs/issues/685
https://github.com/MicrosoftDocs/powerapps-docs/issues/767

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f089624-6d21-fdf3-9579-7babefe6ff3e
* Version Independent ID: db6f23d1-044b-4562-85dd-2aac925d4bb4
* Content: [Show details about the current user in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/show-current-user)
* Content Source: [powerapps-docs/maker/canvas-apps/show-current-user.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/show-current-user.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
At this time, we only expose the Name, Email, and Picture directly.  There is a request to make Roles information more readily available that you may want to vote on: https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Form-Roles-For-Conditional-Logic/idi-p/4485.  An option is to use Power Automate to check the Roles and return that information to the Canvas app.
