### ISSUE TITLE
Incorrect Field type

### ISSUE THREAD

**Issue by jasonaalmeida** [MicrosoftDocs/powerapps-docs#1026]
Under the types of fields table, there is a language datatype that is a whole number in the solution explorer. This does not seem consistent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d193924-c732-6c92-721b-348baede9d54
* Version Independent ID: c871720f-64d4-66e7-7b6d-1c555e4e32e1
* Content: [Field data types in Common Data Service - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/types-of-fields)
* Content Source: [powerapps-docs/maker/common-data-service/types-of-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/types-of-fields.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@jasonaalmeida yes the Language data type is specified as a whole number. You can view this from an existing field on the Details tab, then select Edit. 
![image](https://user-images.githubusercontent.com/21203819/105543278-dd356780-5cb6-11eb-9c04-35c148fd939b.png)
Closing issue.
