### ISSUE TITLE
Attachments in Show Email Messages

### ISSUE THREAD

**Issue by avsrot** [MicrosoftDocs/powerapps-docs#1028]
Is there an option of also shoing the email attachments besides the messages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbce0fbc-150d-5a31-2096-2f36eea12a26
* Version Independent ID: 13bb945a-845b-fbe2-c65a-a944a92ea368
* Content: [Overview of the Office 365 Outlook connection - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-outlook?source=docs#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-office365-outlook.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-office365-outlook.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Connector documentation lists all methods and properties supported by the connector - see [Office 365 Outlook](https://docs.microsoft.com/connectors/office365/). For example, GetEmailsV3 includes property named *includeAttachments*.
