### ISSUE TITLE
Xrm.Navigation.navigateTo Successcallback is being called before opening dialog

### ISSUE THREAD

**Issue by KK1674** [MicrosoftDocs/powerapps-docs#1029]
You can give callback method when when model dialog is closed. It is no longer working. It was working fine. Now it is calling even before the model dialog is opened. Please fix this ASAP. Microsoft recommends to use supported methods and apis. Why customers are not being informed if you guys are changing anything?

Xrm.Navigation.navigateTo(pageInput,navigationOptions).then(successCallback,errorCallback);

**Comment by adamweeg** [comment]
We can also confirm this change in behavior. Please advise.

**Comment by anshdeepsharma** [comment]
We are also facing the same issue . Is there and alternate to this , Handling the close of the dialog on the parent window?

**Comment by pldrosa** [comment]
Hello guys -

I don't think it is a bug, the documentation is as follow:

successCallback | function | No | A function to execute on successful navigation **to the page when navigating inline** and on **closing the dialog when navigating to a dialog**.

In my tests, I was able to verify that it works as described. Success is invoked when inline is used and success is invoked when dialog is used.

See sample code below:

<html>
<head>
</head>
<body style="word-wrap: break-word;">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="ClientGlobalContext.js.aspx"></script>

<script>
    function openNewPageInline() {
        openNewPage(1);
    }

    function openNewPageDialog() {
        openNewPage(2);
    }

    function openNewPage(target) {
        debugger;
        try {
            var pageInput = {
                pageType: "webresource",
                webresourceName: "dev_samplepage.html"
            };

            var navigationOptions = {
                target: target,
                width: 400,
                height: 300,
                position: 1
            };

            Xrm.Navigation.navigateTo(pageInput, navigationOptions).then(
                function success() {
                    // Handle dialog closed
                    alert("Success");
                },
                function error() {
                    // Handle errors
                    alert("Error");
                }
            );
        } catch (err) {
            alert(err);
        }
    };
</script>
    <p><button type="button" onclick="openNewPageInline()">Open Page Inline</button></p>
    <p><button type="button" onclick="openNewPageDialog()">Open Page Dialog</button></p>
</body>
</html>

**Comment by Nkrb** [comment]
@KK1674 @adamweeg Thanks for the feedback. This issue is fixed. Can you guys confirm if it has got resolved from your end.
