### ISSUE TITLE
Case not reflecting AM/PM vs am/pm format

### ISSUE THREAD

**Issue by csteelatgburg** [MicrosoftDocs/powerapps-docs#103]
I am trying to output an hour as ham/pm, but it returns in hAM/PM, e.g. 3:00am is displaying as 3AM instead of 3am.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f30da2a-1b9d-9d31-c59e-494314144b2f
* Version Independent ID: abe8de4e-2ed5-aedc-d2b3-a819bdf40587
* Content: [Text function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-text)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-text.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-text.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
@csteelatgburg Or even this?
**Text(Now(), "[$-en-US]ha/p")**
