### ISSUE TITLE
Policy-Signin-URL

### ISSUE THREAD

**Issue by rpeters-gom** [MicrosoftDocs/powerapps-docs#1033]
A) The paragraph about Policy-Signin-URL is outdated. The mask changed.
B) Is it possible to explain how to add the Policy-Signin-URL of an Custom SignIn Policy? We have one policy for SAML connected apps and want to use this policy to have just one page for account creation and sign in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d71e01-9651-365a-0fc0-b0017d3866ca
* Version Independent ID: 507be630-f013-10d1-00dc-c57aa949f0cb
* Content: [Azure AD B2C provider settings for portals - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/azure-ad-b2c)
* Content Source: [powerapps-docs/maker/portals/configure/azure-ad-b2c.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/azure-ad-b2c.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by Stanzarectah** [comment]
I tried the steps to customise Azure AD B2C login page but I am getting login failed.

It works normally if I use the default Azure AD B2C login page and I can sign up.

How do I restrict users so that only contacts that exsits in Dynamics 365 are able to sign up? Do I need to use custom policies?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. 

A) is updated.
B) is under consideration for future updates.

For restricting users to only contacts from Dynamics 365, turn [open registration](https://docs.microsoft.com/powerapps/maker/portals/configure/configure-portal-authentication#open-registration) off to disable user registration. Only Dynamics 365 users can login. And send out invitation using [redeem an invitation](https://docs.microsoft.com/powerapps/maker/portals/configure/set-authentication-identity#redeem-an-invitation). 

For any issues, please feel free to reach out with a [support service request](https://admin.powerplatform.microsoft.com/support). You can also submit feature ideas or vote for submitted ideas through [Power Apps Community forum](https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas).

**Comment by tapanm-MSFT** [comment]
Follow up B) - IssuerFilter is used to have multiple users from different tenants login to a particular portal in a tenant. For example, a single tenant supporting users from multiple tenants to login. Generally, a custom policy is applied in the IDP to identify the user flow for sign in, sign ups and the claims associated which is then associated with a reply URL.
