### ISSUE TITLE
Get MAC address for a Canvas App using formulas

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#1034]
I have a requirement pull the MAC address for a device using my App.

Is this something supported or in the works for the formula APIs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84c57493-fcba-2e20-8386-ee5ae2d65dd9
* Version Independent ID: 75eff919-9848-b592-52fc-069f5c9bc4ea
* Content: [Get started with formulas in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-formulas)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-formulas.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-formulas.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
We are working on exposing more information about the app and the app's device.  I don't yet know if MAC address will be included.  You may want to add a comment to [this community forum idea](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Published-Version-Number/idc-p/464912#M29522) or add a forum idea specifically about this.
