### ISSUE TITLE
Why is this article under client scripting best practices ?

### ISSUE THREAD

**Issue by satishreddyv** [MicrosoftDocs/powerapps-docs#1036]
Not sure why this article is under client scripting best practices when it has nothing to do with it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fa7be73-8aad-c0fb-8b54-a2acdfadeebd
* Version Independent ID: a4bfe99f-d6b3-6857-c1bd-5cc67c325dac
* Content: [Remove deactivated or disabled customizations - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/best-practices/business-logic/remove-deactivated-disabled-configurations)
* Content Source: [powerapps-docs/developer/model-driven-apps/best-practices/business-logic/remove-deactivated-disabled-configurations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/best-practices/business-logic/remove-deactivated-disabled-configurations.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by Nkrb** [comment]
@satishreddyv We want all the best practices for model-driven apps in single TOC. We will come up with different strategy so that topics will be under appropriate nodes.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
