### ISSUE TITLE
Why is there no name collision between Entity Name and the Primary Name (Field Name)?

### ISSUE THREAD

**Issue by eschmitt** [MicrosoftDocs/powerapps-docs#104]
Why is there no name collision between cr2fb_ProductReview (Entity Name) and cr2fb_ProductReview (Field Name), used for the Primary Name? The documentation shows these as the same name.  I've been getting name collisions if I try to reuse a field name, even if it's in another entity. It seems that the field names are environment-wide. So, why is this acceptable for the Primary Name (field name)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11bacb37-4743-1d0e-d13e-1d9b656c661f
* Version Independent ID: 7b4d6192-4282-c5c1-01a2-a3ba065ed6e6
* Content: [Create a custom entity - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-create-entity#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-create-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-create-entity.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by eschmitt** [comment]
Is this a documentation error or am I misunderstanding some name-spacing that's obfuscated, but occurring in the underlying code?

**Comment by eschmitt** [comment]
Oh, this is referring to the documentation for steps 3 and 4, btw.

**Comment by Mattp123** [comment]
@eschmitt If they were the same object type there would be an issue. Notice that the maker portal won't let you name two entities (or for that matter any other object) the same. However, since these **_aren't the same objects_** (entity vs field) it's fine to use the same value for the name property. 
Closing issue.
