### ISSUE TITLE
Missing Command in Step no.7 

### ISSUE THREAD

**Issue by gunjanbr** [MicrosoftDocs/powerapps-docs#1041]
Missing Command in Step no.  7  To generate a zip file from your solution project, you need to cd into your solution project directory and build the project using the following command:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b01e51-8d80-08b1-2bd5-564c4756ad8a
* Version Independent ID: 750ea5e8-1325-2593-024d-68e926488076
* Content: [How to use the sample components? (Power Apps Component Framework) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/use-sample-components#feedback)
* Content Source: [powerapps-docs/developer/component-framework/use-sample-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/use-sample-components.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@gunjanbr 
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
