### ISSUE TITLE
relationships

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/powerapps-docs#1042]
Is it possible to relate rows using this feature? I might want to load in projects from a separate datasource, and relate those to my accounts during the dataflow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e6f1eb-1ed8-c4f0-6a8f-3e252e65f499
* Version Independent ID: 82b18731-40b0-bc10-6d7c-9ebe5c07b726
* Content: [Add data to an entity in Common Data Service by using Power Query - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-cds-newentity-pq)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-cds-newentity-pq.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-cds-newentity-pq.md)
* Service: **powerapps**
* GitHub Login: @mllopis
* Microsoft Alias: **millopis**

**Comment by iangpgh** [comment]
@Ballzer0 Have you received a response to your question? Have you contacted Support with your question (https://powerapps.microsoft.com/support/)? Let me know if you still need help with this question.

**Comment by iangpgh** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

@Mattp123 - Closes #1042

**Comment by fvandillen** [comment]
I would like to know the same. We have a relational on-prem database and would like to load records into a custom entity that has a relationship with the Account entity. In the on-prem database, we have a FK that does this. How should we map the lookup field?

**Comment by bthompson-365** [comment]
I'm not Microsoft so take this as just my advice.

Download Kingswaysoft and use that to create an SSIS integration to perform the upload.
