### ISSUE TITLE
authorization or access to datalake

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerapps-docs#1043]
This document doesnt specify which user need to be given access to the datalake to make this work. in our organization we already have a datalake and should the user logged into powerapp portal need to have access to the storage account(ADLS2) as data contributor?

if that is the case, then what happens when the user who configured this left the organization.

also what about these scenarios:
1. will the other users be able to see export settings done by a single user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771a2696-1d5a-88c0-299e-320d03a536c3
* Version Independent ID: 0b729e37-ce56-6d84-f44b-a22666776cec
* Content: [Export to data lake - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by artiefischer** [comment]
The required Storage Account permissions are listed in the 'Prerequisites' section.

> 'You must be granted an owner role on the storage account.'

'You' meaning the account that is currently logged in to the service, and attempting to set-up the export.

I would be interested in the answer to the leaving the org question.

**Comment by iangpgh** [comment]
@mganeshphani From PM: We use SPNs (service principal name) for auth and as part of linking your environment to the data lake you grant the Export to Data Lake Service access to your storage account.

**Comment by iangpgh** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue. 

@Mattp123 - Closes #1043
