### ISSUE TITLE
Troubleshooting Tips page in See Also section does not exists 404.

### ISSUE THREAD

**Issue by JannyM85** [MicrosoftDocs/powerapps-docs#1045]
Troubleshooting Tips page in See Also section does not exists 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0949367-dc3e-ba70-b494-8945530a6fed
* Version Independent ID: 93472f86-1b45-0421-2e1e-7e2857e64534
* Content: [Create extensions for the code generation tool (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/extend-code-generation-tool#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/extend-code-generation-tool.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/extend-code-generation-tool.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@phecke Can you fix please?

**Comment by phecke** [comment]
@JannyM85 Removed the link as I could not find the document page the link refers to..
