### ISSUE TITLE
Custom Help Pane Links

### ISSUE THREAD

**Issue by KASharpe** [MicrosoftDocs/powerapps-docs#1047]
On this page it makes mention that "The ability to link to an existing help page is not yet enabled.". Is there a release date for when this will be made available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca73ad14-c514-cbff-8be2-f9e36ebf395a
* Version Independent ID: 38f4187d-582a-551c-d65c-3374d4d74ce6
* Content: [Create custom help pages - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-custom-help-pages#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/create-custom-help-pages.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-custom-help-pages.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **matp**

**Comment by CoreySutton** [comment]
Any update on the availability of this feature?

**Comment by Mattp123** [comment]
@KASharpe and @CoreySutton, Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. 

Closing this issue.
