### ISSUE TITLE
defaultViewId required when using filters property

### ISSUE THREAD

**Issue by KrisSevenants** [MicrosoftDocs/powerapps-docs#1049]
When using the filters property the defaultViewId should be filled in as we noticed inconsistent behavior of the control on initial load if it's left empty.

filtering entity: documenttemplate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@KrisSevenants I tried to reproduce the issue in UCI and i can use filter parameter without defining defaultViewId parameter. Are you using web client or UCI? Here is the code i have used
```JavaScript
function sampleoperations(){
var lookupOptions = {defaultEntityType: "account",
	entityTypes: ["account"],
        allowMultiSelect: true,
	filters: [{filterXml: "<filter type='or'><condition attribute='name' operator='like' value='A%' /></filter>",
		entityLogicalName: "account"
	}]
};
 
Xrm.Utility.lookupObjects(lookupOptions)
	.then(function(result){
	})
	.fail(function(error){
	});
}
```
And in the output i see 11 records.

![image](https://user-images.githubusercontent.com/34038327/77582637-eab67100-6e9c-11ea-9e7a-6cac98a2268b.png)

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
