### ISSUE TITLE
maxPageSize is not respected if higher than 5000

### ISSUE THREAD

**Issue by geriremenyi** [MicrosoftDocs/powerapps-docs#1050]
Current description about the maxPageSize does not describe that if you pass a value higher than 5000 then the value won't be respected and will fallback to the default 5000.

Example scenario:
Number of entites: 10 000
maxPageSize in the call: 10 000
The call will return a promise with 5000 entries and with the nextLink attribute for the remaning 5000.

Might be a product bug if it should be respected and there is no such limitation which I am missing from the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c196bb-4bbb-80e2-0bba-42d130621024
* Version Independent ID: 56d1575c-1868-34c6-992d-e3797024e413
* Content: [retrieveMultipleRecords (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by satishreddyv** [comment]
Yes, The current description implies that we can pass any value in maxPageSize and does not say the maximum allowed limit is 5000.
