### ISSUE TITLE
All Connectors link does not provide a list of connectors

### ISSUE THREAD

**Issue by TashasEv** [MicrosoftDocs/powerapps-docs#1052]
The sentence under the Popular Connectors header has a link to take you to "all connectors," but the linked page does not have any list of connectors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df61b9fd-18b0-49c7-03f3-8b97aa67a601
* Version Independent ID: cc848247-8142-08bc-08c7-9ee11b55face
* Content: [Connectors overview for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by lancedMicrosoft** [comment]
The link takes you to page that is the summary page for the list of all the connectors.

**Comment by TashasEv** [comment]
Thanks for the response Lance - could you clarify? I'm linked to https://docs.microsoft.com/en-us/connectors/ from the referenced link in this issue, and that page contains links off to documentation for Power Automate, Power Apps, and Logic Apps, and Custom Connectors.  The Power Automate and Power Apps sections contains link to Manage Connections, but those pages don't contain lists of all the connectors either. If there's a link on the summary page that links to all the connectors and I've missed it please let me know, but the only link I know of that contains a list of connectors is in the Flow documentation (and I had to go hunting to find this): https://us.flow.microsoft.com/en-us/connectors/.

**Comment by lancedMicrosoft** [comment]
Hi Tasha,  This is the page that is the summary level of all connectors.  If you look you can see that on the left, in the nav bar, is the list of all of the connectors.  This page is the top level heading for the entire list.


[cid:image001.png@01D5E897.142989F0]

**Comment by TashasEv** [comment]
Ah, I see, thank you. I didn't anticipate the entire left nav changing from where I navigated to this page from. I think it would be helpful to point this out on the page. Thanks for the assistance!
