### ISSUE TITLE
Outdated document

### ISSUE THREAD

**Issue by sngoh55** [MicrosoftDocs/powerapps-docs#1053]
Sidebar picture is outdated. Get More apps is to the right side of the screen next to the filter button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba282f83-c663-8fd5-aa60-f76eb1c74adc
* Version Independent ID: 049cb45a-4dc0-0731-9357-d256eb793d44
* Content: [Discover apps via AppSource - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/app-source#feedback)
* Content Source: [powerapps-docs/user/app-source.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/app-source.md)
* Service: **powerapps**
* GitHub Login: @mkaur
* Microsoft Alias: **matp**

**Comment by mduelae** [comment]
@sngoh55 Thank you for the feedback. I will look into this and update the help topic with the latest info.

Thank you,
Mints

**Comment by mduelae** [comment]
I have updated the topic. The changes will go live at the end of day today.

Thanks,
Mints
