### ISSUE TITLE
Bound property-set of type FP does not show valid options

### ISSUE THREAD

**Issue by clurdish** [MicrosoftDocs/powerapps-docs#1057]
The documentation on this page says the of-type option "FP" is supported for property-set. When creating a data-set component with a property-set item of-type "FP", valid field options within the dynamics 365 view editor do not appear.

See below for an example manifest snippet.

```xml
<data-set name="primaryDataSet" display-name-key="Dataset_Display_Key">
    <property-set name="latitude" display-name-key="Latitude" description-key="lat desc" of-type="FP" usage="input" required="true" />
    <property-set name="longitude" display-name-key="Longitude" description-key="lon desc" of-type="FP" usage="input" required="true" />
</data-set>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf0a2b0-63d8-ab62-e8a4-f383344e779c
* Version Independent ID: 4093dc5b-4cb7-b3f8-5bfa-7d40e02eafa9
* Content: [Property Set Element - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property-set)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property-set.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/property-set.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@clurdish Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
