### ISSUE TITLE
Cant find attachemt field

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/powerapps-docs#1060]
cant find attachment field when i create a form with a sharepoint folder as a datasource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e663e437-2bc9-980f-9ba6-6eeab01ee9a4
* Version Independent ID: ae7da14b-2234-2815-9fd1-272a0984f129
* Content: [Attachments control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-attachments)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-attachments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-attachments.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there, attachments are only allowed on SharePoint lists.
