### ISSUE TITLE
Is content still accurate?

### ISSUE THREAD

**Issue by TashasEv** [MicrosoftDocs/powerapps-docs#1067]
I'm not certain this statement from this page is still accurate: "App makers can work around these limitations by including PDF documents as media resources in the app." If so, a pointer is needed on how to include the PDF as a media resource, as it seems not straightforward with the 3 available media choices being Image, Video, and Audio (image did not work for me). Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29176e76-ee98-6a28-826a-a94a8f44aa25
* Version Independent ID: 0671ed96-1eb8-92aa-a29b-4c8fe3f9a895
* Content: [PDF viewer control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-pdf-viewer)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-pdf-viewer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-pdf-viewer.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated. Please allow some time for changes to reflect.
