### ISSUE TITLE
Double quotes verses single quotes

### ISSUE THREAD

**Issue by Logix365** [MicrosoftDocs/powerapps-docs#1068]
I noticed when using this expression the "" in the expression does not work. For example: split("James Bond", " ") the expected result should be ["James", "Bond"] instead you are getting an error saying, "Invalid Expression". Instead use split('James Bond', ' ') for some reason using single quotes return a single string to an array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c28165a-b79a-d821-5260-bdb2baaa8ca0
* Version Independent ID: da9f62f6-e30d-7617-a418-a45357b75f35
* Content: [Split function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-split#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-split.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-split.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the report.  But I wasn't able to replicate the behavior you saw.  `Split("James Bond", " ")` (which has a single space in the second argument) returns a table with "James" and "Bond" as separate records:

![2020-02-25_07h38_09](https://user-images.githubusercontent.com/15149773/75263065-4f00ea80-57a2-11ea-96b8-b014b1686ddb.png)

`Split("James Bond", "")` (no space in the second argument) returns a table with each character in a different record:

![2020-02-25_07h39_17](https://user-images.githubusercontent.com/15149773/75262863-f7fb1580-57a1-11ea-89ca-fdf7177dfdb5.png)

[Single quotes are used to delimit identifiers](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/operators#identifier-names) and will result in an error in this context as there is no 'James Bond' variable or other object:

![2020-02-25_07h40_15](https://user-images.githubusercontent.com/15149773/75263022-3b558400-57a2-11ea-80ec-b100e842ed08.png)

If I misunderstood your comment please let me know.

**Comment by Logix365** [comment]
Hi Greg Your response is very interesting, you are applying the formula in a Power App while is was using the same formula in a Flow Expression which is where I was having the issue with the double quotes. Regards Byron Sent from my Huawei phone-------- Original Message --------Subject: Re: [MicrosoftDocs/powerapps-docs] Double quotes verses single quotes (#1068)From: Greg Lindhorst To: MicrosoftDocs/powerapps-docs CC: Byron Dittberner ,Author Thanks for the report.  But I wasn't able to replicate the behavior you saw.  Split("James Bond", " ") (which has a single space in the second argument) returns a table with "James" and "Bond" as separate records:

Split("James Bond", "") (no space in the second argument) returns a table with each character in a different record:

Single quotes are used to delimit identifiers and will result in an error in this context as there is no 'James Bond' variable or other object:

If I misunderstood your comment please let me know.

**Comment by gregli-msft** [comment]
Thanks Byron, that explains the disconnect.  Your original comment was logged against Power Apps documentation, you may want to [review the Power Automate docs for Split](https://docs.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference#split) and comment there..

**Comment by Logix365** [comment]
My bad, thank you
