### ISSUE TITLE
Could it be that OnSelect on a Gallery is not supported yet?

### ISSUE THREAD

**Issue by jmeijering** [MicrosoftDocs/powerapps-docs#1069]
When I record the selection of a gallery record, during test play back it gives the following error

Select 'Image1_2' in row 2 in 'galPurchOrderHeadersV2'
Row or column passed to the Select function is outside the bounds of the gallery items.

**Comment by Nkrb** [comment]
@jmeijering Can you point us to the doc page you're talking about. It helps us to identify the right owner and triage the issue.

**Comment by jmeijering** [comment]
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/test-studio

and here the state:

Known limitations
While work to provide full control coverage in Power Apps Test Studio is in progress, following functionality is currently unavailable:
·         Components.
·         Code components written in the Power Apps Component Framework.
·         Nested galleries.
·         Media controls.
·         Formula-level-error management experimental feature needs to be turned on for the app.
·         Support for controls not listed in the Select<https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-select> and SetProperty<https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-setproperty> functions.
·         Person type columns.

**Comment by tapanm-MSFT** [comment]
@jmeijering selecting a gallery record like in example you shared works:

Example: Select 'Image1' in row 3 in 'Gallery1'

Limitation section mentions nested galleries as not supported among others. However, it is unclear how this error is reported for you. 

Can you please check and share the formula listed in action for the case order # that fails?

**Comment by jmeijering** [comment]
This is the action mentioned on the step that fails: Select(galPurchOrderHeadersV2, 2, Image1_2)

[cid:image001.png@01D5F7AD.2AFFAEA0]

**Comment by aengusheaney** [comment]
@jmeijering I think i will need to offline with you to research your issue further. Could you email me on aheaney@microsoft.com and we will set up time to connect on your scenario.

**Comment by tapanm-MSFT** [comment]
Closing since this is being discussed offline.
