### ISSUE TITLE
Add to Known Issue

### ISSUE THREAD

**Issue by tpmeredith** [MicrosoftDocs/powerapps-docs#1071]
Can you add a known issue that for Date Filtering you can no longer filter a date range as you could before 2020 update 1? Pre-grid UUI you could filter "on or after" and "on or before" as two filter options and filter a date range. I really wish it just had a "between" option, and it would be perfect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e9258f-4c21-9d52-9940-cada6c70db50
* Version Independent ID: 1f5619dd-aea0-d0d4-34a9-a7e0e036faf8
* Content: [Filter data on grids - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/grid-filters#feedback)
* Content Source: [powerapps-docs/user/grid-filters.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/grid-filters.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@tpmeredith Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. 

I will check with our internal team to see if this needs to added a known issue.

Thanks,
Mints

**Comment by mduelae** [comment]
@tpmeredith 
I just tested this and  **On or after** and **On or before** are still there.
For between (multiple filters), we have shipped the capability. It is slowly rolling out now.

Thanks,
Mints

**Comment by tpmeredith** [comment]
@mduelae yes they are both still there, however you cannot do BOTH at the same time as you could pre-grid update, now it only lets you pick one so effictively you can not do a date range. 

That is awesome news about between, can you advise what exact dynamics server version it takes to get that functionality?

**Comment by tpmeredith** [comment]
@mduelae when you can, can you guys please reply with documentation showing the new feature in the powerapps grid filters? I can't see anywhere that references that between is an option and is rolling out.
