### ISSUE TITLE
File size limit

### ISSUE THREAD

**Issue by CraigHumphrey** [MicrosoftDocs/powerapps-docs#1072]
You should probably mention there's a 2000000 byte file size limit for Excel files.
And the Excel file support doesn't include CSV files.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01e57c82-f30c-72cd-2cf2-391454cc162b
* Version Independent ID: 94f874ae-c20c-f46b-427e-bc6f08c9a4d0
* Content: [Overview of the Excel connection - PowerApps](https://docs.microsoft.com/en-nz/powerapps/maker/canvas-apps/connections/connection-excel?source=docs)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-excel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-excel.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Excel supportability for file size/formats is out of scope for Power Apps documentation.
