### ISSUE TITLE
Power Platform Admin Center

### ISSUE THREAD

**Issue by scottemoore** [MicrosoftDocs/powerapps-docs#1074]
You can bulk delete data from CDS by access the Environment's Settings page via admin.powerplatform.microsoft.com where you will find a "Data Management" section which has a sub-menu "Bulk Deletion".  This will take you into the original CRM interface for this task where you can build an advanced find to construct a bulk deletion job

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a461ed-af8a-e87f-9487-e03194eacf69
* Version Independent ID: 6791cc45-1bef-7fa3-ace3-2748b0eef682
* Content: [Delete data in bulk (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/delete-data-bulk?source=docs#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/delete-data-bulk.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/delete-data-bulk.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@scottemoore  Thanks for the feedback,.
