### ISSUE TITLE
List of required URL should also contains http://127.0.0.1:*

### ISSUE THREAD

**Issue by hoangpham95** [MicrosoftDocs/powerapps-docs#1075]
Power Apps had a local server running to serve static contents, and it can be specified as both:
- localhost
- 127.0.0.1
Some customers behind their companies' proxies have raised ICMs about this, and adding 127.0.0.1 resolves the issue for them, so I suggest we add this IP address to the VPN list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdf0872-929b-e44a-dedd-eb6a759915f2
* Version Independent ID: 0b65b025-62f8-fc2a-0026-3cb96b7b4554
* Content: [System requirements, limits, and configuration values for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The documentation has been updated. Please see the latest documentation.
