### ISSUE TITLE
"About group teams" link at the bottom is 404

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/powerapps-docs#1076]
"About group teams" link at the bottom is 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4549b49b-30e8-c879-39a4-dab18142c213
* Version Independent ID: 8a4a64ea-979f-c4e2-94f0-dd7311b660a4
* Content: [Share a model-driven app with Power Apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/share-model-driven-app#about-predefined-security-roles)
* Content Source: [powerapps-docs/maker/model-driven-apps/share-model-driven-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/share-model-driven-app.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@repton-infinity - Thank you for helping improve our documentation. The link is fixed and will be published live in about an hour. Closing issue.
