### ISSUE TITLE
Updates Needed

### ISSUE THREAD

**Issue by bedgren** [MicrosoftDocs/powerapps-docs#1077]
AppSource no longer lists "Sales Analytics for Dynamics 365" as a service to "Get".

Dynamics 365 no longer uses OData connection, the instructions should be updated to at least include, or be changed to, REST.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93095016-4515-14d5-c61f-14b619f6b0d7
* Version Independent ID: dfa48a66-4539-db25-3e53-62e664cb1220
* Content: [Use Power BI with model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/use-power-bi#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/use-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/use-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@bedgren - Apologies for the delay. This topic and https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/use-powerbi-with-cds have been updated recently to reflect the current connectivity options for Power BI. 
Closing issue.
