### ISSUE TITLE
Missing validaton for new app for outlook

### ISSUE THREAD

**Issue by danielftk** [MicrosoftDocs/powerapps-docs#1078]
Hello MSFT Team, we are developing a js that validates the value clientContext.getClient() returns. I realized that for those users that are using the new app for outlook the clientContext.getClient() function is returning a 'web' value. I think you must consider to add 'outlook' value for those cases when the user is using CRM with the new app for outlook! Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d301dc-c412-afb3-e205-dcb3d2c936e8
* Version Independent ID: dc454fd1-a390-1662-1cb3-af693478d458
* Content: [getGlobalContext.client (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/client)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/client.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/client.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KendalBond007** [comment]
Document has been updated to reflect the existence of an "Outlook" return value. Issue will be closed.
