### ISSUE TITLE
Customizing label In different Regional Languages

### ISSUE THREAD

**Issue by samikshashetty** [MicrosoftDocs/powerapps-docs#1079]
Can we Custome label names to different Regional Languages ( Hindi Script) for the user to understand while filling the forms in the canvas app? If so, Can you share any related docs regarding the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde021b1-2aa0-b8ca-7ca9-3889d9a34a57
* Version Independent ID: 438b1685-d3eb-a8d5-7813-8a1423f92598
* Content: [Customize a form in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-forms-sharepoint)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-forms-sharepoint.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-forms-sharepoint.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can create source text table with language variations, and change the context based on the user's language. An example of this is the [Crisis Communication](https://docs.microsoft.com/powerapps/maker/canvas-apps/sample-crisis-communication-app) app. For more help, please reach out to support team with a [ticket](https://admin.powerplatform.microsoft.com/support).
