### ISSUE TITLE
Save after refresh?

### ISSUE THREAD

**Issue by EHulburd** [MicrosoftDocs/powerapps-docs#1080]
Is the description for the save parameter correct? What use would a save after a refresh be? Surely refreshing the data means there is nothing to save?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15ceb029-d6be-0391-c7ae-99f209cf9286
* Version Independent ID: d58d7a85-3881-e653-f24e-6da42aa8dc7e
* Content: [refresh (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data/refresh)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/refresh.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/refresh.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@EHulburd Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
