### ISSUE TITLE
A 1 is missing in the array of numbers in step 2

### ISSUE THREAD

**Issue by harzicn** [MicrosoftDocs/powerapps-docs#1081]
I've spotted a small omission. In step 2 of the instructions for display a character map, there is a 1 missing in the array.
Your instructions show: ForAll( [0,2,3,4,5,6,7,8,9,10,11,12,13,14,15], Value + ThisItem.Value * 16 )
I think this should be: ForAll( [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], Value + ThisItem.Value * 16 )
Just thought you might like to make that small correction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5973db7-626d-9be3-31b1-7f41668ae41a
* Version Independent ID: 8d1279ca-77f6-ec61-b701-7527854b5954
* Content: [Char function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-char#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-char.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-char.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the bug report!  The article has been updated.
