### ISSUE TITLE
IOS Microphone only returns the location not the data itself

### ISSUE THREAD

**Issue by cagrimunyas** [MicrosoftDocs/powerapps-docs#1082]
When I try to store the output data from the mic input in a JSON with JSONFormat.IncludeBinaryData, in Android and web I can see the payload, however in IOS it only returns the path of the payload in IOS' local system (e.g. tmp/recording_{{ - seperated LongHash}}.aac). How can I retrieve the audio data generated by a microphone on IOS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 258f140b-bc82-47a7-e915-79bebbd9b3b9
* Version Independent ID: d8a732b6-53b4-b161-3ff8-14de5fda89b3
* Content: [Microphone control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-microphone)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-microphone.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-microphone.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there, when I set OnStop of the microphone to:
`Set(AudioJSON, JSON(Microphone1.Audio, IncludeBinaryData))`

And then display this this as the value of a label, it works for me.

![image](https://user-images.githubusercontent.com/22963239/79244694-311c4180-7e45-11ea-9f17-d26ab8df837b.png)

Hope this helps.
