### ISSUE TITLE
Missing timeout Parameter

### ISSUE THREAD

**Issue by daryllabar** [MicrosoftDocs/powerapps-docs#1083]
When using this in the Canvas App Studio, there is a timeout parameter that is not documented:
    timeout: Number of milliseconds to display the notification before it is automatically dismissed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afc532c2-42d1-d2d3-8631-25eac6aea36e
* Version Independent ID: 5ae36459-fcf9-bfa9-a715-2990de54e3ba
* Content: [ShowError function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-showerror)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-showerror.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-showerror.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks Daryl.  The docs have been updated.  The timeout feature was only added last week and we were waiting for all regions to deploy it.
