### ISSUE TITLE
Please update the (odata@bind) formation for associate entities in case of entities of type activity. 

### ISSUE THREAD

**Issue by srikanth-paladugula** [MicrosoftDocs/powerapps-docs#1084]
In case of entities of type Activity( ex: task,email.. ) the @odata.bind formation is different than given in above example of associations to the related entities.

Example : Consider we have a custom lookup field to opportunity on task entity.
Entity: Task
DisplayName : Task
SchemaName : Task
LogicalName : task
Custom field(on Task):
DisplayName : Parent Opportunity
LogicalName : hsl_parentopportunityid
SchemaName : hsl_ParentOpportunityId
Type : Lookup to opportunity

To update Parent Opportunity field on task, the format should be like below
var data={};
data["{LookupField.SchemaName}_{Task.SchemaName}@odata.bind"] =
"/opportunities(216d7c95-5d3c-ea11-a812-000d3a3ab486)";
In our case, it should be like
data["hsl_ParentOpportunityId_Task@odata.bind"]="/opportunities(216d7c95-5d3c-ea11-a812-000d3a3ab486)";

To update Regarding on task, the format should be like below
var data={};
data["{regardingobjectid}_{TargetEntity.LogicalName}_{Task.LogicalName}@odata.bind"] =
"/TargetEntityPluralName(216d7c95-5d3c-ea11-a812-000d3a3ab486)";
Support if our target is account, it should be like
data["regardingobjectid_account_task@odata.bind"]="/accounts(316a7c95-5d3c-ea11-a812-000d3a3ab486)";

**Comment by Nkrb** [comment]
@srikanth-paladugula Can you point us to the doc page you're talking about, so that we can assign it to right owner to triage the issue.

**Comment by srikanth-paladugula** [comment]
@Nkrb , this issue is about Xrm.WebApi.updateRecord method.

Docs Page.
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/updaterecord

**Comment by Nkrb** [comment]
@srikanth-paladugula Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
