### ISSUE TITLE
Question regarding combining $top and $count parameters

### ISSUE THREAD

**Issue by jlilja** [MicrosoftDocs/powerapps-docs#1086]
Commit: https://github.com/MicrosoftDocs/powerapps-docs/commit/16811bfd605e9e396557bc352590e6f6b63ba8d4#diff-4ee995be785461803ae8194ef89c8ac9R96

Commiter: @susikka

>  You should not use `$top` with `$count`.

The documentation mentions that you should not combine the $top and $count parameters together. Please elaborate on why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#retrieve-a-count-of-entities)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
@jlilja The `$count` query option is used to retrieve the number of records for an entity, while `$top` is used to retrieve the top limited number of records.

If you try the following queries:

```http
GET [Organization URI]/api/data/v9.1/accounts/$count
```
or 
```http
GET [Organization URI]/api/data/v9.1/accounts/$count?$top=3
```
they return the same result, i.e. the total number of Account entity records.

Can you please mention the scenario for which you wish to use these two together?

**Comment by jlilja** [comment]
Hi Sushant!

Thank you for the explanation. The reason I was asking, I now understand, might not be applicable to power apps because I am using the same documentation for Navision Business Central.

The scenario where I want to use $count=true is because of the enormous set of records I receive back when asking without a $top query makes the request timeout. If I combine the two I will receive one record and the count of all records for the entire entity. And my question is that I want to use these two query params together but the documentation says I shouldn't, can the documentation be expanded as to why I shouldn't?

**Comment by JimDaly** [comment]
This is the documentation for the Common Data Service OData v4 implementation, known as Web API.
If you have questions related to Navision Business Central OData endpoint, you should refer to the documentation for that product.

As @susikka  called out. For CDS, you should not use both together. It is redundant because the values are the same. There is no reason to use both.

**Comment by jlilja** [comment]
Hi Jim. Thanks for the help.

Could you please provide me with an link to this documentation? I'm having a hard time finding an equivalent chapter to the one linked in my issue.

**Comment by JimDaly** [comment]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/odata-web-services
