### ISSUE TITLE
Migrate component libraries across environments

### ISSUE THREAD

**Issue by anshulgupta1992** [MicrosoftDocs/powerapps-docs#1087]
The article initially states that component libraries make it easier to publish updates across environments. But there are no details or steps mentioned in the article on how to move component libraries across environments (like dev to test to prod).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0224ad-fdbb-c741-98a7-3ec0764b10cf
* Version Independent ID: dfbaaa9e-b902-70de-49d8-9d6c5328b6d2
* Content: [Create a component library for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/component-library#difference-between-an-app-and-a-component-library)
* Content Source: [powerapps-docs/maker/canvas-apps/component-library.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/component-library.md)
* Service: **powerapps**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by m3ngi3** [comment]
Up until now:
1) it seems we cannot export / import a Component Library App on itself because there is no Export button
2) when we create a Component Library App from scratch in a brand new Solution, we can export the Solution as unmanaged. However after importing the unmanaged Solution, the Component Library App cannot be changed and saved in the imported unmanaged solution: 
> {"error":{"code":"AppTypeImmutable","message":"The type of the app being saved is different from the existing type and cannot be changed."}}

Session ID: 9926bac9-116c-4d44-a228-41ddba3b5c12<
We are then allowed to **Save to Computer** but the .msapp file

**Comment by yifwang** [comment]
Update libraries allow makers to publish changes to libraries in the environment. Moving to different environment scenarios is coming where dependency can remain after exporting to new environment. The wording causes confusion.  Adding @alaug to share the feedback.

**Comment by tapanm-MSFT** [comment]
Component libraries can't be exported from [Power Apps](https://make.powerapps.com). The support for moving component libraries from one environment to another is through solutions.

**Comment by DForlen** [comment]
> The support for moving component libraries from one environment to another is through solutions.
@tapanm-MSFT 

How can we do this ?
When I create a Component library in a solution, then export the solution to my production environment, I can't use it as a component library.

**Comment by philippschaefer4** [comment]
Same question here. I need to migrate a Component Library from one environment to another. I exported a solution with a Component Library and imported it to another environment, but couldn't access the imported library in the editor. It didn't matter if I export managed or unmanaged as far as I could see it. Also the library is not listed in the "Component Library (preview)"-tab but as a simple Canvas App under "Apps".

**Comment by Jaco-Campher** [comment]
You can sort of do this now.

1. Open your source component library and then File > Save As.
2. Save the file to your computer.
3. Create a new app or open your exiting app on the destination tenant.
4. File > Open > Browse.
5. Select the file you saved in step 2.
6. Now save and publish. It will give you an option to override if it is an existing app.

**Comment by RenatoMunozTC1** [comment]
https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/component-library-alm#creating-and-exporting-component-library-in-a-solution
