### ISSUE TITLE
Manifest contains the same information twice

### ISSUE THREAD

**Issue by psyduck101** [MicrosoftDocs/powerapps-docs#1089]
The child elements section seems to show the same section twice.

![image](https://user-images.githubusercontent.com/7466236/75679895-c34ef880-5c90-11ea-9ae5-ced32908bae2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24a8dcfa-d75f-b8d1-c020-e3fa6b74eb28
* Version Independent ID: c5389f9a-25a0-6cd5-f542-fa49a3625314
* Content: [Manifest Element - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/manifest#feedback)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/manifest.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/manifest.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@psyduck101 
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
