### ISSUE TITLE
Considering that Power Apps were enabled for Document Libraries, should we update the note?

### ISSUE THREAD

**Issue by AnatolN** [MicrosoftDocs/powerapps-docs#1090]
This feature was released earlier: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=57303 (https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=57303), thus making the note "Support for generic document libraries is coming soon" incorrect. Also, a clarification would need to be done on what "generic" means here (libraries without specific fields, without content types, etc.)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback, content is updated. Please allow some time to reflect the changes. For custom lists and libraries, Power Apps option inside SharePoint allows customizing form. For lists such as Announcements, Tasks or templates, form customization using Power Apps is not available/supported.
