### ISSUE TITLE
How to launch an android app using powerapps?

### ISSUE THREAD

**Issue by fmoghaddampoor** [MicrosoftDocs/powerapps-docs#1091]
Well, I am a newbie in powerapps. Recently I had this task to run an external Android application (A type of NFC reader) which is currently not supported on powerapps.

So I researched and understood there is a method for lunching in powerapps: You can launch a url like this:

Launch("https://www.bing.com")

You can launch skype like this:

Launch("skype:")

The syntax is like this: Launch( Address [, ParameterName1, ParameterValue1, ... ] )

Address - Required. The address of a webpage or the ID of an app to launch.

ParameterName(s) - Optional. Parameter name.

ParameterValue(s) - Optional. Corresponding parameter values to pass to the app or the webpage.

But how about a specific unknown application?

I want to for example load app at address below in google play:

https://play.google.com/store/apps/details?id=com.ssaurel.nfcreader&hl=en

I know that I can navigate user to address below, but Is there a way to run application directly? Launch("https://play.google.com/store/apps/details?id=com.ssaurel.nfcreader&hl=en")

**Comment by Nkrb** [comment]
@fmoghaddampoor Can you point us to the doc page you're talking about, so that we can assign it to right owner to triage the issue.

**Comment by fmoghaddampoor** [comment]
Dear NKrb here is the link to microsoft reference>
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-param

In reference clearly is talking about Id of an App, no example is provided, but It would be amazing if its possible to launch the app directly.

**Comment by gregli-msft** [comment]
Sorry, unfortunately there is no way to launch a native app directly.  When the article talks about an app and an app id, it is referring to only a canvas app.  We have updated the docs to make this clearer:

_Native apps on a device cannot be directly launched.  There may be indirect options available on some platforms, such as a native app installing a custom URL scheme or registering with the web browser to offer an option for specific web sites._

(You won't see this in the docs immediately, it is pending a doc publish that should happen in the next day or so).
