### ISSUE TITLE
Tablet layout not available in Component Library

### ISSUE THREAD

**Issue by anshulgupta1992** [MicrosoftDocs/powerapps-docs#1092]
When editing components libraries, we do not have the option to change the layout to tablet. Only options are portrait and landscape. When the component library is saved, published and edited again; the orientation/layout is again defaulted back to Portrait.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0224ad-fdbb-c741-98a7-3ec0764b10cf
* Version Independent ID: dfbaaa9e-b902-70de-49d8-9d6c5328b6d2
* Content: [Create a component library for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/component-library#working-with-component-library)
* Content Source: [powerapps-docs/maker/canvas-apps/component-library.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/component-library.md)
* Service: **powerapps**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It doesn't apply to component libraries as libraries aren't meant to be used as the apps that you can play. The component libraries are used for reusing components.
