### ISSUE TITLE
Why I got a list of Fields automatically

### ISSUE THREAD

**Issue by jingweihaha** [MicrosoftDocs/powerapps-docs#1094]
I followed the documents step-by-step but after provisioning is done, I got a list of fields automatically, also, the primary field has a name Subject and it is unchangeable.
![entity not working properly](https://user-images.githubusercontent.com/16979214/75823779-56ab2b00-5d70-11ea-9ae9-d870f26d45aa.png)

**Comment by Nkrb** [comment]
@jingweihaha 
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by jingweihaha** [comment]
Hi, Thanks for the reply, yes it relates to PowerApp Create custom Entity, developer question, the URL is here:

https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-create-entity

The main problem is that I'm not able to create my own custom Entity, no matter the activity entity or standard entity,  when provisioning, lots of unexpected fields are auto-generated for me. 

Also, when creating an activity entity based on the below list item:
**d. Select Activity entity option from the Choose entity type drop-down list to enable an entity as an activity.**
But once I choose the Activity entity, then the primary field Display name and name automatically changed to Subject and it's read-only. See the below screenshot.

The above behavior isn't aligned up with what document saying.

![not able to change primary field name](https://user-images.githubusercontent.com/16979214/75831335-3c2d7d80-5d81-11ea-9cc9-36fd2e25b080.png)

**Comment by Mattp123** [comment]
@jingweihaha - Thanks for your feedback. The entity you're creating is an activity entity, which is different than a standard entity. The article you are referencing covers creating a standard entity. For information about the ownership and fields for activity entities, see https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/types-of-entities. 

Closing issue.
