### ISSUE TITLE
I am not able to play recorded sounds from the microphone

### ISSUE THREAD

**Issue by melzoghbi** [MicrosoftDocs/powerapps-docs#1095]
Hi,
I implemented steps 1-4, but in step 5, i do not see the gallery updated with sounds to play since it is not showing on the form after i hit stop on the microphone.  What would be the problem here? I had the gallery set to pull from my collection name, but it seems the microphone is not storing the file to be picked up by the gallery control. any help is appreciate it.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 258f140b-bc82-47a7-e915-79bebbd9b3b9
* Version Independent ID: d8a732b6-53b4-b161-3ff8-14de5fda89b3
* Content: [Microphone control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-microphone#)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-microphone.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-microphone.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there, I was able to get this working properly.  Are you sure you're using Collect() and not ClearCollect() in your save function?  ClearCollect will clear the collection where Collect will add to the collection.

I added ClearCollect in my App OnStart
![image](https://user-images.githubusercontent.com/22963239/76446547-9e980680-639d-11ea-804d-cd5b6aa226d6.png)

Here is my Collect on Microphone OnStop
![image](https://user-images.githubusercontent.com/22963239/76446613-b7082100-639d-11ea-8c83-1e9dcb69f005.png)

Here is a video adding more items
![Microphone-Audio-Gallery](https://user-images.githubusercontent.com/22963239/76446785-f0409100-639d-11ea-8a44-3ce753dc25f7.gif)

Hope this helps.
