### ISSUE TITLE
How can i use ClearCollect for Microphone and Audio Controls

### ISSUE THREAD

**Issue by melzoghbi** [MicrosoftDocs/powerapps-docs#1096]
Hi,
How can i used this for capturing audio from Microphone control and being able to play the stored/saved audio into Audio control. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c8e63a-856f-c7f7-9553-d2564c1e25e4
* Version Independent ID: 29037222-286c-8fc0-79e5-4bb599ad7c70
* Content: [Collect, Clear, and ClearCollect functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-clear-collect-clearcollect)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
We've added more examples to the [Microphone control documentation](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-microphone#examples) that specifically show how to use collections to record and playback audio clips.
