### ISSUE TITLE
Method getQueryStringParameters

### ISSUE THREAD

**Issue by timothybohte** [MicrosoftDocs/powerapps-docs#1097]
Could you please add a page dedicated to method getQueryStringParameters ? This works in the latest version of Dynamics both classic and unified interface, but it's not documented here. Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbd23ccf-3f1a-9e76-f702-1c6bbf53692d
* Version Independent ID: 8f0e77d5-e1c8-6427-8966-df05a2f53e8c
* Content: [getGlobalContext (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@timothybohte Thanks for the feedback. I'll check with the dev team if this is the case and then update accordingly.

**Comment by Nkrb** [comment]
@timothybohte Thanks for the feedback. getQueryStringParameters() method is deprecated and it is recommended to use formContext.data.attributes method.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
