### ISSUE TITLE
Integration of Powerapps in Power BI doc is very unclear and confusing

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerapps-docs#1098]
- Integration of Powerapps in Power BI doc is very unclear and confusing and doesn't guide customers in properly implementing this feature

- Please see this official Power BI video (Microsoft official) on integration of Powerapps - https://www.youtube.com/watch?v=us0hPFwQ4Zs

- In the video above, it clearly says that the "Powerapps visuals should be added only after the Power BI report has been published to the Service" This is not reflected in the documentation

- Please make the documentation more clear and educational

**Comment by phecke** [comment]
@haider392 Please provide the documentation web page address that you are referring to.

**Comment by haider392** [comment]
https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide

**Comment by haider392** [comment]
Haider Hazrat would like to recall the message, "[MicrosoftDocs/powerapps-docs] Integration of Powerapps in Power BI doc is very unclear and confusing (#1098)".

**Comment by haider392** [comment]
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This is listed in step 2: 

You can choose an existing app or create one, but the report must be published to the Power BI service and opened in Microsoft Edge or Google Chrome.
