### ISSUE TITLE
To make the example work 

### ISSUE THREAD

**Issue by andypicking** [MicrosoftDocs/powerapps-docs#1099]
To make the example work I additionally had to select the image in the image gallery and then set the Image property (under the Data section) to ThisItem.Value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158a7bb6-99a9-f3d3-a31b-a9ed075e4627
* Version Independent ID: f6fd9679-bd5b-3699-b8b6-a7a697041199
* Content: [Add picture control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-add-picture#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-add-picture.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-add-picture.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Thanks - I've submitted an update to account for the new gallery types.
