### ISSUE TITLE
Clearer statements around what is delegable and what is not, by product

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/powerapps-docs#1100]
Hi,
I think you might need some kind of grid, to show which functions/operators are delegable in which connectors.  E.g. I know that currently Search() is not delegable for the SharePoint connector.
Additionally, I'm aware that while StartsWith() is delegable for the SharePoint connector, it's not if the SharePoint field is a Multiline text box - only some field types are supported.

Thanks
Craig

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad97e638-1f17-ffb2-452f-8073a2bffa63
* Version Independent ID: 7ade66f5-aab6-0627-6d3b-914006718930
* Content: [Understand delegation in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview?source=docs)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-overview.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. As the documentation lists, the complete delegation information is connector-dependent and can be found from the specific [connector](https://docs.microsoft.com/connectors/) being used.
