### ISSUE TITLE
Different screen capture from step by step guide

### ISSUE THREAD

**Issue by h3rdy4n** [MicrosoftDocs/powerapps-docs#1101]
Part: Update the request flow (https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app?source=docs#update-the-request-help-flow)

Step 5 and 6 shows to extract Teams ID and Channel ID, picture on Step 13 shows a different value entered. Which one should be the correct information? 

![image](https://user-images.githubusercontent.com/40159365/75946719-01972280-5ef2-11ea-80c3-969cea41715c.png)

![image](https://user-images.githubusercontent.com/40159365/75946761-1d9ac400-5ef2-11ea-9c15-9f753f3ad18b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by matthewbolanos** [comment]
The image was incorrect and we have since fixed it :)
