### ISSUE TITLE
Small typo in the sample date output

### ISSUE THREAD

**Issue by 0x4kgi** [MicrosoftDocs/powerapps-docs#1102]
In the documentation, the output of this code: 

`Text(DateTimeValue(Start.Text), "dddd, mmmm dd, yyyy hh:mm:ss.fff AM/PM")` 

is Saturday, October 11, 2014 ***01:50:24:765*** PM.

Although this is correct, the last colon should be a dot since the formula is formatted that way. Really minor, I know. :)

Then the sample should be:

Saturday, October 11, 2014 ***01:50:24.765*** PM

Confirmed via Power Apps:
`hh:mm:ss.fff` with a dot
![image](https://user-images.githubusercontent.com/17591127/75955412-bd575280-5ef0-11ea-80a8-d6c44a02f70e.png)

`hh:mm:ss:fff` with a colon
![image](https://user-images.githubusercontent.com/17591127/75955590-20e18000-5ef1-11ea-813a-1d355163ea0b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fda4c41-0a11-d2f5-8424-d79fa32c6103
* Version Independent ID: 5b21c7e2-cd5a-0d81-e9a3-97a65266aa17
* Content: [DateValue, TimeValue, and DateTimeValue functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-datevalue-timevalue#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-datevalue-timevalue.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-datevalue-timevalue.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the bug report!  It has been fixed.
