### ISSUE TITLE
Does not work on a subgrid

### ISSUE THREAD

**Issue by Miesjh** [MicrosoftDocs/powerapps-docs#1104]
I try to use this on a subgrid to indicate that child records are required, but I get an error:
setNotification is not a function.

Code: formContext.getControl(Subgridname).setNotification(message);

Control types supported: All????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc26bb9c-dde5-cf97-9ea0-2d6940299088
* Version Independent ID: 944219c6-532e-ed19-3e05-d012e3b716c7
* Content: [setNotification (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setnotification)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setNotification.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setNotification.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@Miesjh Thanks for the feedback. Yes this method is not supported to work on subgrids. We have updated the docs accordingly with the list of supported controls Closing the issue.
