### ISSUE TITLE
Date format server response error, records not being written to CL_Employee Status

### ISSUE THREAD

**Issue by oex-pbi** [MicrosoftDocs/powerapps-docs#1106]
I have observed a couple of bugs with the date format submission, and the records not being written to the CI_Employee Status table. Please see photos added to:

https://powerapps.microsoft.com/en-us/blog/crisis-communication-a-power-platform-template/

NOTE: I am in the UK - so perhaps the date format is not compatible with US format?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by johnsideserf** [comment]
Having the same issue here - any suggestions?

**Comment by matthewbolanos** [comment]
There appears to be a mismatch on how the date is written and the calendar component treated dates.

A new version is updated in GitHub that resolves this issue, but can you let me know if it resolved the issue for you as well?

**Comment by tapanm-MSFT** [comment]
Please feel free to respond if the new version doesn't resolve this issue; and we'd be glad to reopen this issue and assist.
