### ISSUE TITLE
channel id and team id

### ISSUE THREAD

**Issue by sobordia** [MicrosoftDocs/powerapps-docs#1107]
there are correct steps to get team id and channel id
but in screen shot you interchange value
so change the screen shot and have correct value

**Comment by phecke** [comment]
@sobordia Please provide a link to the documentation web page that you are referring to.

**Comment by sobordia** [comment]
> @sobordia Please provide a link to the documentation web page that you are referring to.

13. Paste the Channel ID into the Value field.
On page : https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content is updated. Please allow some time for changes to reflect.
