### ISSUE TITLE
The "searchText" parameter does not work.

### ISSUE THREAD

**Issue by mazd9** [MicrosoftDocs/powerapps-docs#1109]
This method totally ignores the "searchText" parameter, so it's not working in the Unified Interface. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by polshgiant** [comment]
Agreed, Unified seems to completely ignore the parameter.

**Comment by Nkrb** [comment]
@mazd9 @polshgiant I have tried using the searchText parameter in UCI  and i can get the results as desired. 
Please let us know if you're still facing the issue from your end.
Here is the code i'm using 
```JS
function sampleoperations(){
var lookupOptions = {defaultEntityType: "account",
	entityTypes: ["account"],
        allowMultiSelect: true,
		defaultViewId:"65FFAF9A-E8C5-432D-860B-32F841B00D87",
		viewIds:["65FFAF9A-E8C5-432D-860B-32F841B00D87","00000000-0000-0000-00AA-000010001001"],
		searchText:"Adventure",
	filters: [{filterXml: "<filter type='or'><condition attribute='name' operator='like' value='A%' /></filter>",
		entityLogicalName: "account"
	}]
};
 
Xrm.Utility.lookupObjects(lookupOptions)
	.then(function(result){
	})
	.fail(function(error){
	});
}
```
And in the out put i can see the records that has Adventure
![image](https://user-images.githubusercontent.com/34038327/77684877-cec3d580-6f57-11ea-9cc1-f20e21d544e5.png)

**Comment by polshgiant** [comment]
When I run this exact code in my org, the lookup dialog opens but the search text is not there.  
Wave 2 enabled
Server version  9.1.0000.14448
Client version 1.4.284-2002.3

**Comment by Nkrb** [comment]
@polshgiant  Can you confirm if  you are still facing this issue. We don't find any issues using the search parameter in the method and always gets the desired results.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
