### ISSUE TITLE
Create a plugin-in project param typo

### ISSUE THREAD

**Issue by anasufovic** [MicrosoftDocs/powerapps-docs#1111]
#3 should say `pac auth create --url &lt;https://xyz.crm.dynamics.com&gt;` not `pac auth create –url &lt;https://xyz.crm.dynamics.com&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c487a-6048-5ed1-d3b3-f15756f0f953
* Version Independent ID: 35502302-bdf4-6a02-11cb-dea21d9fa7ff
* Content: [Import components - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls#create-a-plug-in-project-and-add-a-reference-to-it-in-your-solution)
* Content Source: [powerapps-docs/developer/component-framework/import-custom-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/import-custom-controls.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@anasufovic The import components doc says exactly what you have mentioned. Are you referencing to any other topic?

**Comment by Nkrb** [comment]
@anasufovic  Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by anasufovic** [comment]
The problem is still there. Under "Create a plug-in project and add a reference to it in your solution", number three has a single dash -url instead of a double dashed param like --url.

Please note that this exact same command is in the doc two times, it is the second entry that has the typo, not the first.

https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls#create-a-plug-in-project-and-add-a-reference-to-it-in-your-solution

**Comment by Nkrb** [comment]
We have updated the docs with the correct information and pushed to live.
