### ISSUE TITLE
Error Opening File

### ISSUE THREAD

**Issue by bibinbastian** [MicrosoftDocs/powerapps-docs#1112]
After importing Powerapps, when trying to edit the app, I am getting the error saying "This application xx could not be found in the tenant"

Similar to the ticket opened before.
<img width="283" alt="2020-03-06 13_43_01-Window" src="https://user-images.githubusercontent.com/7856373/76124847-7466d300-5fb0-11ea-847a-3137c9156358.png">

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
