### ISSUE TITLE
Teams Notification Using the Connector UserID instead of logged in user

### ISSUE THREAD

**Issue by wisc75** [MicrosoftDocs/powerapps-docs#1113]
I'm trying to figure out why when I test the "Request Help" the adapative card is coming through with the connector's userID instead of the userID of the logged in user.

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by KendalBond007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/. Closing this issue.
