### ISSUE TITLE
Text References an Image, but no Image is Visible?

### ISSUE THREAD

**Issue by pritchie99** [MicrosoftDocs/powerapps-docs#1115]
In the last section a paragraph starts off with the text "The following image shows an arbitrary contact assigned to a filter condition..." however no image is visible for me between that point and the end of the article.  Potentially the heading for that paragraph "Example View Filter Criteria" is not formatted as intended as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eb3ed13-9665-518f-7cc5-eec5e279708f
* Version Independent ID: 8a7aefa4-b9e0-ef52-7832-83c23cc790b1
* Content: [Add a webpage to render a list of records on a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/entity-lists#feedback)
* Content Source: [powerapps-docs/maker/portals/configure/entity-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/entity-lists.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. Documentation has been corrected, please allow some time to reflect the changes.
