### ISSUE TITLE
CommunicationCrisisInformation and CrisisCommunicationApp

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#1116]
Hi
In the Create SharePoint Site step the site is called CrisisInformation in the Run Flow to create lists it is CrisisCommunicationApp and the download it  is ../teams/CrisisCommunicationApp

Regards

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content image is being updated.
