### ISSUE TITLE
Incorrect page link

### ISSUE THREAD

**Issue by steverhall** [MicrosoftDocs/powerapps-docs#1117]
From the left-side navigation panel, "Apply business logic using code" does not link to the correct page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdeda855-04fc-a145-873d-63569f18fbf5
* Version Independent ID: fd9ae462-da2f-e292-9579-85c68b458fe2
* Content: [Developers: Best practices and guidance regarding plug-in and workflow development for the Common Data Service - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/business-logic/)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/business-logic/index.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/business-logic/index.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment]
@steverhall Thanks for pointing it out. Fixing now.
