### ISSUE TITLE
Issue with Post your own adaptive card as the Flow bot to a channel in CrisisCommunication.RequestHelp flow

### ISSUE THREAD

**Issue by manojreddybandi** [MicrosoftDocs/powerapps-docs#1119]
When User is not having access to teams , it is giving me Unauthorized error

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by mr-dang-msft** [comment]
Hi @manojreddybandi ,
Please find versions of the app after 2020-03-12 for an updated flow for requests:
aka.ms/CrisisCommunicationSolution
