### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/powerapps-docs#1123]
The step 14 of setting up the CrisisCommunication.Request flow is refering to actions that are not in the flow anymore (Current time & Convert TimeZone).

**Comment by Nkrb** [comment]
@Nicokirr 
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by Nicokirr** [comment]
I have made the change directly in the documentation page file (https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app) , please review it.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated.
