### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/powerapps-docs#1124]
When setting up the admin parameters, the app has more parameters than the documentation (Teams Channel name, Teams Channel ID)

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by Nicokirr** [comment]
I have made the change directly in the documentation page file (https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app) , please review it.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This issue has been resolved in the latest app. Please feel free to reach out using the [issues link](https://aka.ms/crisis-communication-issues) for any additional issues.
