### ISSUE TITLE
Can't turn features off/on - Small error in the Crisis Communications App - OnStart up

### ISSUE THREAD

**Issue by gsheeley** [MicrosoftDocs/powerapps-docs#1126]
The OnStart in the Communications App has this logic for each of the features that can be turned on and off, i.e. 

// Check if feature flag is enabled for Request Help
If(
    !IsBlank(varConfig.Feature3),
    Collect(colNav,
        {
            Id: 1, 

Which is fine on first set up, but if you then used the Admin App to turn these Features on and off then the above logic will always evaluate to True and hence show the feature, even if you have set the features value to Off

Recommend this minor update in the logic
// Check if feature flag is enabled for Request Help
If(
    Coalesce(varConfig.Feature2,true),
    Collect(colNav,
        {
            Id: 1, 

The coalesce will evaluate the first value and if it is not blank or empty then it will return its value of true of false, otherwise it will return true and have it on by default, i.e. until set otherwise

Hope this helps others.
Happy to be advised of a better way.

PS - Don't forget you might need to refresh the apps data source to the CL_configAdminSetup SharePoint list if you have made recent change to the configuration and turned say the "Request for Help" feature off.

Refs: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-isblank-isempty

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Your feedback is under consideration.

**Comment by tapanm-MSFT** [comment]
This has been fixed in the latest version so that varConfig.Feature checks for true and instead of checking for blank. Thank you!
