### ISSUE TITLE
For the "Import and set up the notification flow" what is the Azure AD Connection needed for?

### ISSUE THREAD

**Issue by DS2019** [MicrosoftDocs/powerapps-docs#1127]
We'll need to get permission to use this connector, seems like it gives a lot of access to Azure AD - can you please let us know why it is needed for the notifications? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by SeaDude** [comment]
Hm. I was able to get around this by:
- Click Get Data
- Search for Sharepoint
- Add the same CI_Employee Status table (shows as EI_Employee Status(2))
- Remove all columns except Id, Title, Presence Status, RawLongitude, RawLatitude, Date, Latitude, Longitude
- Save and Apply
- The graphic then loaded correctly
- Then I deleted the Sharepoint list I just added
- Graphic stays loaded with original list
Not sure why or how it worked, but it did!

**Comment by SeaDude** [comment]
Sorry. This was a comment for the PowerBI issue above.

**Comment by Merel84** [comment]
I have the same question, thanks for letting us know! (and for this amazing initiative!)

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The Azure AD connection is used to convert the Azure AD ID into an email address. You can remove this card and simply hard coding the email address instead.

**Comment by Merel84** [comment]
Great! Thanks! If I might ask an additional question related to this, if I want to do the same for the Teams notification, I run into a little trouble as I can only indicate individuals in the Recipients field, no groups. Could you point me to where I can find information on solving this?

Many thanks in advance,
Merel

**Comment by tapanm-MSFT** [comment]
Please read updated section for [sending notifications to larger set of users](https://docs.microsoft.com/powerapps/maker/canvas-apps/sample-crisis-communication-app#optional-sending-notifications-to-more-than-999-users) that might help.
