### ISSUE TITLE
Raw data html value is not converting to htmltext control 

### ISSUE THREAD

**Issue by parthkarry** [MicrosoftDocs/powerapps-docs#1128]
In the company detail news screen we have htmltext control to display html formatted data in text area . But it is not converting into html and displaying as plane text  with html code . 
It is using global variable of selectedNews.Details .  

Have any one encounter this issue . 

I also followed standard way of datacard but on this screen layout not found datacard 

Followed this :
https://powerusers.microsoft.com/t5/Webinars-and-Video-Gallery/Handling-SPO-Rich-Text-Columns-in-PowerApps/td-p/138498

When I am directly putting the html data in text property it is getting converted properly .
I have made my own form with keyvalue and card and their it is converting .

**Comment by parthkarry** [comment]
Their is one issue very frequently I am coming across causing me we reset the limit or even redo the app . Issue is of  Delegation error and data source might process the data . as in given url 
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview

I have just few records but this failing so frequently . I am using trail version of PowerApps is it something of issue .

**Comment by gregli-msft** [comment]
Thanks for your comments.  But we require a little more detail though before we can follow up.  Can you give examples of the formulas you are using?  We also need to split your concerns into two threads, one for HTML text and one for Delegation.

But before we proceed further here in the docs, you may want to direct your questions to the [Power Apps community](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1).  Somebody may have already asked your question or there may be an expert there that can answer.

If you'd like to continue here, please open up new comments at the bottom of these pages with examples of the formulas you are working with:

- [HTML Text Control](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-html-text)
- [Delegation](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview)
