### ISSUE TITLE
pcf push Deploying code components size limit

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#1129]
Is there a limit to the size of a component we are allowed to push to CDS. The `bundle.js` for my control is 5.2 MB.

Is it recommended I create multiple different components in this case?

```
D:\GitHub\pcf>pac pcf push -pp grdegr -v minimal
Connected to...OpenHack
Checking if the control 'grdegr_MrUniverse.AuthenticationComponent' already exists in the current org.
The control exists in the current org, loading the control's details.
Comparing the manifest in the current org to the manifest at \AuthenticationComponent\ControlManifest.xml.The control manifests are the same.
Using incremental update.
Locating the web resources used by the 'grdegr_MrUniverse.AuthenticationComponent' control.
Checking for any changes to each resource.
Updating 'cc_MrUniverse.AuthenticationComponent/bundle.js'.

Error: Webresource content size is too big.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c487a-6048-5ed1-d3b3-f15756f0f953
* Version Independent ID: 35502302-bdf4-6a02-11cb-dea21d9fa7ff
* Content: [Import components - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls)
* Content Source: [powerapps-docs/developer/component-framework/import-custom-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/import-custom-controls.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by rajyraman** [comment]
@gregdegruy - This is a known issue. There is a size limit of 5MB. https://docs.microsoft.com/en-us/powerapps/developer/component-framework/issues-and-workarounds#web-resource-size-is-too-big

**Comment by Nkrb** [comment]
@gregdegruy Please try the workaround provided in the official doc. Closing the issue. 
 If you need further help, please reopen the issue or open a new issue.
