### ISSUE TITLE
Typo in PowerApps for developers section: "connetors"

### ISSUE THREAD

**Issue by shellyhaverkamp** [MicrosoftDocs/powerapps-docs#113]
FYI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a87d70-1f25-0a75-bc11-f2c079f2083c
* Version Independent ID: 7b1e729a-d4b6-2786-2ac7-c9e1c516a815
* Content: [What is PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/powerapps-overview#feedback)
* Content Source: [powerapps-docs/powerapps-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/powerapps-overview.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Fixed.
