### ISSUE TITLE
No tab is shown on the Teams mobile app. 

### ISSUE THREAD

**Issue by giertz** [MicrosoftDocs/powerapps-docs#1130]
I can add the powerapp and see the tab using a browser or the Teams desktop client. There is however no tab visible if you are using the Teams for Android or iOS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db05e68d-8708-9ed3-53bc-da3f1781def5
* Version Independent ID: f550b297-89a5-98c0-2fd6-0e6a95204436
* Content: [Add an app to Microsoft Teams - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/open-app-embedded-in-teams#clean-up-resources)
* Content Source: [powerapps-docs/user/open-app-embedded-in-teams.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/open-app-embedded-in-teams.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by giertz** [comment]
I now see the tab. It however just redirects me to the web url of the powerapp. 
Is it possible to make is so it tries to open the PowerApp instead?

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ 

Closing this issue
