### ISSUE TITLE
"Solution Explorer"

### ISSUE THREAD

**Issue by covandemMS** [MicrosoftDocs/powerapps-docs#1131]
Being new to the product, I was following through these guides and I got lost as step 1. "Solution explorer". Can you add information on how to get to the "solution explorer"? Screenshots would be great if possible so that there's context. I appreciate the work on these guides!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34647a0-dfdf-23da-c656-158a1eae14f9
* Version Independent ID: e2a795ee-c8ba-b757-194b-19ecf4b6d398
* Content: [Add code components to a field or entity - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/add-custom-controls-to-a-field-or-entity#feedback)
* Content Source: [powerapps-docs/developer/component-framework/add-custom-controls-to-a-field-or-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/add-custom-controls-to-a-field-or-entity.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@covandemMS You need to navigate to **Settings** > **Customizations** > **Customize the System** to get the solution explorer. I have updated the docs and will be live EOD today.
