### ISSUE TITLE
More clear instruction

### ISSUE THREAD

**Issue by covandemMS** [MicrosoftDocs/powerapps-docs#1132]
Being new to this, I got lost a bit during "implementing the manifest". It was not clear to me that those instructions were directly saying verbatim what to enter. I very much appreciate the breakdown of each field with explanation. Is it possible to break apart the breakdown from the instruction? What I mean is saying exactly what to type in and what the final manifest should look like, followed by a clear breakdown of each field. 

I had read the explanations and changed the fields as per the explanations, not realizing it had to be exact. It was not clear to me that it was asking for exact values to by typed in as opposed to just documentation on the formatting. Later on in the guide all of my builds were failing from mismatches. Hopefully it's clear what I'm asking for, but if not, just let me know. Again, I appreciate the time taken to make this tutorial. It's very helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript#feedback)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@covandemMS Thanks for the feedback. We have written the tutorial keeping in mind the sample code that we shipped. Yes, you need to do exactly what it says in order to create a linear slider component.

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks
