### ISSUE TITLE
PowerBI Section: "Id column missing"

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#1133]
Thank you for this tool. Directly after changing the Sharepoint list name and ID in the Power BI section, I get the error:
```
Expression.Error: The column 'Id' of the table wasn't found.
Details:
    Id
```
If I click "Go to error", "Removed Other Columns" in Applied Steps is highlighted. Tried removing Id and Title columns. Error then reads: "Can't find Latitude column". Its like Power BI can't really see my Sharepoint list even though I've changed the URL and list id's. 
Any thoughts on how to get beyond this error?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by SeaDude** [comment]
Hm. I was able to get around this by:

Click Get Data
Search for Sharepoint
Add the same CI_Employee Status table (shows as EI_Employee Status(2))
Remove all columns except Id, Title, Presence Status, RawLongitude, RawLatitude, Date, Latitude, Longitude
Save and Apply
The graphic then loaded correctly
Then I deleted the Sharepoint list I just added
Graphic stays loaded with original list
Not sure why or how it worked, but it did!

**Comment by Tim-2Mayos** [comment]
I found that if I add 1 "test" record to the CI_Employee Status list in SharePoint it started working properly for me.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. We are reviewing your feedback.

**Comment by mr-dang-msft** [comment]
Hi @SeaDude ,
It is likely in your steps, you had changed your login. By default, the Power BI is set to anonymous. Once you login with your Microsoft account, it will access the correct content.
![image](https://user-images.githubusercontent.com/39354102/76841665-555d1200-67f6-11ea-8185-b61d50f31421.png)

**Comment by carlosfigueira** [comment]
I can confirm that the report will only work if there is at least one entry in the SharePoint list; if the list is empty you will see the 'Id column missing' error.

**Comment by tapanm-MSFT** [comment]
This is correct, doc is being updated to have some data as a prerequisite to start Power BI report. Thank you for reaching out with your feedback.
