### ISSUE TITLE
New/Edit Form Height in Sharepoint when using PowerApps edit

### ISSUE THREAD

**Issue by birchenall** [MicrosoftDocs/powerapps-docs#1134]
I've hit an minor issue but its a bit annoying.

I want to add some fields to my New/Edit form in a sharepoint list.

I open the Customise in PowerApps link and make the adjustments to my form as needed.

When I return to sharepoint and try to add a New/Edit list item the form no long formats to the height of the browser, it is not the default mobile size, meaning more scrolling.

Is there a solution to fix this in PowerApps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
@birchenall thank you for reaching out. Can you please elaborate on the scenario? Is the form wider? Can [further customization](https://docs.microsoft.com/powerapps/maker/canvas-apps/customize-list-form#further-customize-your-form) help?
