### ISSUE TITLE
Patch works with shema name only in Dynamics 365

### ISSUE THREAD

**Issue by MaTeMaTuK** [MicrosoftDocs/powerapps-docs#1135]
When I use retrieve methods(LookUp, Filter, etc) I able to use Display Name only.
However, Patch works with schema only.
`Patch(Invoices, Invoice, {billto_fax: "" })
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b39cb78-75da-5e8c-f105-1f0b9ea1b830
* Version Independent ID: 28bfec67-a78a-4a0d-cfc6-e95a560f7092
* Content: [Patch function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Patch works with both logical and display names.  This [section in the docs](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/operators#display-names-and-logical-names) gives more details.

For example, here are two button OnSelect properties that use with both logical and display names to update the standard CDS Contacts entity:

![image](https://user-images.githubusercontent.com/15149773/77832187-585adb00-70f1-11ea-96a1-b7737b785e46.png)

![2020-03-28_12h33_27](https://user-images.githubusercontent.com/15149773/77832084-aae7c780-70f0-11ea-90b4-f126c374a357.png)

![2020-03-28_12h33_35](https://user-images.githubusercontent.com/15149773/77832086-acb18b00-70f0-11ea-93de-4cc505bacdf2.png)

All that said, it is a shame that Patch does not support intellisense for field names.  A request to make this work has been filed and we'll see if we can get that done soon.

Take another look at your app and see if you can use the display name.  If not, please let us know and we'll get to the bottom of it.
