### ISSUE TITLE
URLs missing

### ISSUE THREAD

**Issue by nickp85** [MicrosoftDocs/powerapps-docs#1136]
Seeing additional URLs when accessing admin portal of Power Apps not included here.
api.businessappdiscovery.microsoft.com
api.bap.microsoft.com

I am getting 401 error to those and I believe proxy is getting in the way.  Do they need to be set to SSL bypass?

**Comment by jimholtz** [comment]
@nickp85 
Sorry for the delay. Can you let us know which topic you're referring to? Thanks.
