### ISSUE TITLE
Crisis Management Variable Names

### ISSUE THREAD

**Issue by jordanmcdougall** [MicrosoftDocs/powerapps-docs#1138]
For the Crisis Management PowerApp, when [enabling location updates](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#enable-location-updates) you are asked to copy and paste code from the docs to PowerApp for the OnSelect on the btnDateRange control. The variables in the code for `CalanderComponent` and `WorkerStatusComponent` do not exist on the PowerApp form that was imported from the .zip file. 

PowerApp could not be saved + published until the error was resolved.

The error seems to have been resolved by changing the code to match the names in the PowerApp form.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The documentation has been updated. The current code snippet works correctly.

Additional observations for the given scenario in this issue:

1. CalanderComponent and WorkerStatusComponent are misspelled.
1. Documentation calls out to use code snippet with solutions older than 2020-03-16. With newer versions, only a few comments need to be removed from the code as documentation explains.

- For feedback about the Crisis Communication sample template, go to https://aka.ms/crisis-communication-feedback.
- To report an issue with the Crisis Communication app, go to https://aka.ms/crisis-communication-issues.
