### ISSUE TITLE
Does the "central crisis management Teams team" need to be an org-wide team?

### ISSUE THREAD

**Issue by DmitryVorobyov** [MicrosoftDocs/powerapps-docs#1141]
If so, this needs to be reflected in the documentation. 
If not, additional communication to users will be needed, requesting them to join the team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by henryed07** [comment]
It does not require or use the Org Wide Team. This team is only for those who are the Crisis Management Team and no one else. So it will not require additional communication - only to those who are part of the team

**Comment by DmitryVorobyov** [comment]
"Send a request" functionality will not work for people who are not members of the team - last step of the notification workflow throws an error for non-members.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. We are reviewing your feedback.

**Comment by tapanm-MSFT** [comment]
This has been fixed with the latest updates. The app now sends an email and another flow responds to the email and sends a notification to the Teams channel so users don’t have to be members. Thank you!

**Comment by DmitryVorobyov** [comment]
Thank you very much for your response. Is this update out yet? 

Also: 
1. Which components of the app would need to be updated? 
2. Will there be any new components that will need to be deployed (e.g. the flow you mentioned that would be triggered by emails being sent? 

Thanks again!

**Comment by mr-dang-msft** [comment]
Hi @DmitryVorobyov ,
The request flow has been updated as of the 2020-03-12 version, though you'll always want the most up-to-date version from aka.ms/CrisisCommunicationSolution.

**Comment by DmitryVorobyov** [comment]
Thank you for the clarification! I was able to test the updated version and I can confirm it works as described.
