### ISSUE TITLE
Submit button does nothing when sharing status in CC app

### ISSUE THREAD

**Issue by dgillespie-adf** [MicrosoftDocs/powerapps-docs#1143]
Share status takes me through: _select where you will be _working__ and the calendar but when I select a date and hit submit, nothing happens.

**Comment by phecke** [comment]
@dgillespie-adf 
Is this an issue with the documentation, an application, or a developer tool? If it is with the documentation, please provide a documentation link. For a developer tool, let me know which one.

For an application, you will need to file a support ticket. We're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

**Comment by dgillespie-adf** [comment]
@phecke where specifically would I find the action for the submit button like I described above?  Thank you for replying.

**Comment by phecke** [comment]
@dgillespie-adf 
There is not enough details here about what you are doing for me to understand that nature of the problem. What is the CC app? Issues filed here should be related to the published PowerApps documentation. If you provide me a link to the related doc page, I might be able figure out who might be able to help you.

**Comment by dgillespie-adf** [comment]
@phecke I was able to figure it out.  There was something that didn't copy over on the code for **Optional: Enable location updates** but when I re-pasted it in it worked.

Thank you.
