### ISSUE TITLE
Crisis Communication GCC - Import Error

### ISSUE THREAD

**Issue by LEIDT** [MicrosoftDocs/powerapps-docs#1146]
I get the following Error when trying to import the App. Could not find API 'shared_rss'.
![image](https://user-images.githubusercontent.com/62208091/76704784-5a607b00-66a9-11ea-974d-74f3d868b093.png)

**Comment by tapanm-MSFT** [comment]
This is likely related to Data Loss Policies. If an Organization has all Data Loss Policies blocking access to connectors, they'd have to enable the RSS Feed connector on a policy. For more information, go to [Create DLP Policy](https://docs.microsoft.com/power-platform/admin/create-dlp-policy).

- For feedback about the Crisis Communication sample template, go to https://aka.ms/crisis-communication-feedback.
- To report an issue with the Crisis Communication app, go to https://aka.ms/crisis-communication-issues.
