### ISSUE TITLE
Crisis app - failure to import outlook 365 connection

### ISSUE THREAD

**Issue by yoramrotbach** [MicrosoftDocs/powerapps-docs#1147]
Hi,

While attempting to import the CrisisCommunication app, it is require to create an Office 365 Outlook connection (doesn't show in the documentation). 
This will fail if your company isn't using the Office 365 Outlook but rather the on premise Exchange account. There is an error that claiming that the API doesn't support it.

I can't bypass this.

What should I do?

Regards

Yoram

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and apologies for delayed response. If the issue still persists, please contact support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) for help.
