### ISSUE TITLE
Carousel on world and company news not working

### ISSUE THREAD

**Issue by LisaJo48** [MicrosoftDocs/powerapps-docs#1148]
The arrow that should move the view to the left or right to see more articles doesn't. When I click on it, nothing happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app?source=docs#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by rvanluttikhuisen** [comment]
I'm seeing similar issue. On Company News:

- Right arrow DOES NOT scroll right through the news cards when using a desktop browser
- Left arrow DOES scroll left through the news cards when using a desktop browser
- Clicking on the whitespace of a card then using left and right keyboard arrows does scroll the news cards left and right.
- Left and right work fine on mobile devices

**Comment by rvanluttikhuisen** [comment]
Seems this might be a powerApp gallery control issue: [https://powerusers.microsoft.com/t5/Building-Power-Apps/ShowNavigation-does-not-work-Horizontal-gallery/td-p/420188](https://powerusers.microsoft.com/t5/Building-Power-Apps/ShowNavigation-does-not-work-Horizontal-gallery/td-p/420188)

**Comment by mr-dang-msft** [comment]
Hi @LisaJo48,
We've change the gallery to use scrollbars in the version released on 2020-03-16:
aka.ms/CrisisCommunicationSolution

If you would still like the navigation arrows, we've included a configuration in the OnVisible property of the Home Screen. You can scroll down to the colStyles collection and change the "show_gallery_scrollbars" and "show_gallery_nav" values to either "true" or "false".

**Comment by LisaJo48** [comment]
@mr-dang-msft  Thank you. How do I update the version that I am currently using?

**Comment by mr-dang-msft** [comment]
Hi @LisaJo48,
Here's some steps you can follow to update the Crisis Communiation app:

1. Download the latest package at aka.ms/CrisisCommunicationSolution
2. Extract the files that you want to update (not all of them change, and you only import what you need)
3. Go to make.powerapps.com.
4. From the left pane, click Apps.
5. At the top menu, click Import app.
6. Browse and select the CrisisCommunication.zip file to update the main app.
7. Choose Update app and select the existing app if you want to overwrite it. (Or keep that setting as Create New if you want to make a separate file. Note that all apps have version history and you can roll back at any time.
8. Open the app in the studio. Remove the connectors to SharePoint and add your own.
9. Save and publish the app so its changes are reflected in the live copy.

Let me know which part may need clarification.

**Comment by LisaJo48** [comment]
Sorry to be such a newbie. Everything is working find on my current version except the nav for the company and world news. Which zip file should I reimport from the zip file?

**Comment by mr-dang-msft** [comment]
CrisisCommunication.zip is the zip you want for the main app 👍

**Comment by devwheel** [comment]
So to be clear, there are no schema changes to the underlying SP lists? Updating the Apps are all we need to do?
