### ISSUE TITLE
Error: Sorry, we didn’t find that app.

### ISSUE THREAD

**Issue by ankjain30** [MicrosoftDocs/powerapps-docs#1151]
Hi Team, I get the error "**Sorry, we didn’t find that app**." while adding this application in Microsoft teams.

![image](https://user-images.githubusercontent.com/62277260/76827123-1786da80-6844-11ea-824c-b3d95ec5d6bc.png)

**Comment by mr-dang-msft** [comment]
Hi @ankjain30 ,
Can you share more information? The error indicates the app is not on the tenant. Did you remove the app?

**Comment by ankjain30** [comment]
Hi @mr-dang-msft, I believe Since my app was on another tenant and team user was on an another one, that's why I was getting that error.
