### ISSUE TITLE
Make a request notification not landing on Teams Channel, coming via email

### ISSUE THREAD

**Issue by articodes** [MicrosoftDocs/powerapps-docs#1152]
I have configured this app as instructed but when user submits request, it comes to email rather than posting to the teams Channel.

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
