### ISSUE TITLE
Rationale for Many to Many

### ISSUE THREAD

**Issue by jordaniza** [MicrosoftDocs/powerapps-docs#1154]
This page would be better updated with justification as to WHY you would use a many to many relationship within CDS. Users should be aware that there are still a large number of use cases where a traditional junction table approach will be needed, given the limits of many to many exposure in PowerApps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c89994a-1148-39cb-71d6-dde3e36d3242
* Version Independent ID: 4a9eaf90-9191-d243-38ed-c4f0e00ec815
* Content: [Create many-to-many entity relationships in Common Data Service overview - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-edit-nn-relationships#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/create-edit-nn-relationships.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-edit-nn-relationships.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@jordaniza - Added the following second paragraph in the topic, which will be published by end of day (PST). Closing issue. 
One example of a many-to-many relationship is defined between two standard entities included with the Dynamics 365 Sales app. The opportunity entity has an N:N relationship with the competitor entity. This allows for multiple competitors to be added to the opportunity and multiple opportunities associated with the same competitor.
