### ISSUE TITLE
Scheduling Auto-Reply Always returns error

### ISSUE THREAD

**Issue by weeksaustin** [MicrosoftDocs/powerapps-docs#1155]
I'm not sure as to why this keeps happening as there is no error in the code, but every time I push submit it returns the error that the settings couldn't be updated. I am wondering what I am missing with this... Any thoughts? It seems that I can't update the automatic replies no matter what I change.

**Comment by weeksaustin** [comment]
So the Automatic Replies work when you want to send them to those outside the organization. It doesn't work if you uncheck that box. I wonder if it has something to do with this part of the code?
**externalAudience: "None",** // Specify Known or All
externalReplyMessage: "",

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by weeksaustin** [comment]
This is in regard to the Crisis Communication app setup doc. [https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#import-and-set-up-the-crisis-communication-app](url)

**Comment by mr-dang-msft** [comment]
Hi @weeksaustin ,
The issue occurs when no timezone is declared and you are not in UTC, which is the fallback.

We've corrected this behavior in the latest version of the app. You can download and import it at aka.ms/CrisisCommunicationSolution

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
