### ISSUE TITLE
Missing description of the "PowerApps Who Am I" task

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftDocs/powerapps-docs#1156]
There is currently a new task type in the package called "PowerApps Who Am I". Needs to be added to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e92c215-b337-b864-3fee-b9542e4e30c8
* Version Independent ID: 8f26538c-5863-6746-8c2c-ee4438165da4
* Content: [Build tools tasks - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tasks#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tasks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@RobertRybaric Yes, thanks. I did update the documentation for all the tasks recently.
