### ISSUE TITLE
Crisis Communicator App - Change menu option names

### ISSUE THREAD

**Issue by Alexp2019** [MicrosoftDocs/powerapps-docs#1158]
Hi All,

Is it possible to update the Menu Item names? i.e. Change 'Company News'? 

Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by Alexp2019** [comment]
Hi All,

I have solved this:
To update the Icon Names: 
Open the CrisisCommunication.Translations Spreadsheet:
Update your chosen language and Variable (i.e. MakeRequest) 

Remove the colTranslations data source:
![image](https://user-images.githubusercontent.com/38928645/77283404-fa587d00-6d17-11ea-9c75-60a6f2c3bf8d.png)

Re-Add:
![image](https://user-images.githubusercontent.com/38928645/77283424-0a705c80-6d18-11ea-803f-f3d5a0647784.png)

Select the file and then check the following option:
![image](https://user-images.githubusercontent.com/38928645/77283446-178d4b80-6d18-11ea-9fd6-e63f14159d1e.png)

Save and refresh.

**Comment by tapanm-MSFT** [comment]
Thank you for the update. Please feel free to reach out on the feedback & issues topic listed in the article for additional help.

**Comment by JoaoNBMoreira** [comment]
> Thank you for the update. Please feel free to reach out on the feedback & issues topic listed in the article for additional help.

Hi,
how can change language app ?
Thanks,
Joao

**Comment by JoaoNBMoreira** [comment]
> Hi All,
> 
> I have solved this:
> To update the Icon Names:
> Open the CrisisCommunication.Translations Spreadsheet:
> Update your chosen language and Variable (i.e. MakeRequest)
> 
> Remove the colTranslations data source:
> ![image](https://user-images.githubusercontent.com/38928645/77283404-fa587d00-6d17-11ea-9c75-60a6f2c3bf8d.png)
> 
> Re-Add:
> ![image](https://user-images.githubusercontent.com/38928645/77283424-0a705c80-6d18-11ea-803f-f3d5a0647784.png)
> 
> Select the file and then check the following option:
> ![image](https://user-images.githubusercontent.com/38928645/77283446-178d4b80-6d18-11ea-9fd6-e63f14159d1e.png)
> Hi,
how can change language app ?
Thanks,
Joao
> Save and refresh.
