### ISSUE TITLE
Clarify solution limitations

### ISSUE THREAD

**Issue by jordaniza** [MicrosoftDocs/powerapps-docs#1160]
Please adjust limitations for PowerAutomate to reflect that MDAs support button driven flows:

https://docs.microsoft.com/en-us/business-applications-release-notes/april19/microsoft-powerapps/improved-solution-support-canvas-apps-flows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6262cac-ae0b-3729-2a9e-0e7ab11d6934
* Version Independent ID: 57c92838-bc87-cbb1-481c-d00df8077bfb
* Content: [Use solutions in Power Apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/use-solution-explorer)
* Content Source: [powerapps-docs/maker/common-data-service/use-solution-explorer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/use-solution-explorer.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@jordaniza - the topic has been updated to reflect that with an exception, instant (button) flows are supported with solutions. Closing issue.
