### ISSUE TITLE
typo: this IS type of connection IS not very secure

### ISSUE THREAD

**Issue by JeroenTournierSubotic** [MicrosoftDocs/powerapps-docs#1162]
SQL User name and password authentication
This is type of connection is not very secure
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7c89a8f-b16f-2896-faae-efbb438c7a89
* Version Independent ID: 8ce453b3-7e57-c80a-7ca0-9b122ad4796b
* Content: [Connectors overview for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is being updated. Please allow some time for changes to reflect.
