### ISSUE TITLE
Clarity on Monitor office absences with Power BI

### ISSUE THREAD

**Issue by AndrePageot** [MicrosoftDocs/powerapps-docs#1165]
When following the instructions under point 3 "Ensure the Credentials type is set to Organizational account, and use the credentials to access the SharePoint list." after clicking edit on the permission dialogue you will be presented with another window, make sure you select "Microsoft account" this sometimes says Organisational account and login with your company MS 365 account

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#monitor-office-absences-with-power-bi)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The 'use the credentials to access the SharePoint list' implies to use the organizational account that has access to the SharePoint list created.
