### ISSUE TITLE
conflicting description/defaults for site setting

### ISSUE THREAD

**Issue by jamesnovak** [MicrosoftDocs/powerapps-docs#1167]
contradictory descriptions for Authentication/Registration/LocalLoginEnabled
this page description: 
"Enables or disables local account sign-in based on a username (or email) and password. **Default: false**"

this page has different default: 
[AD B2C Related site settings](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/azure-ad-b2c#related-site-settings)
"Specifies whether local sign-in is required. **By default, it is set to true.**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6313f348-4130-74f5-320d-b5bd270060c6
* Version Independent ID: de470e06-c2d3-354e-ba80-75691a5d8bd4
* Content: [Set authentication identity for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/set-authentication-identity#feedback)
* Content Source: [powerapps-docs/maker/portals/configure/set-authentication-identity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/set-authentication-identity.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The content is updated. Please allow some time for changes to reflect.
