### ISSUE TITLE
Issue : Impersonate another user using the Web API

### ISSUE THREAD

**Issue by VenkattaPidikiti** [MicrosoftDocs/powerapps-docs#1168]
Hello,

We have upgraded Microsoft Dynamics 365 On-Premises Cumulative Updates to 9.013.11 version from 9.0.6 version. 
After this we are unable to using the feature Impersonate another user using the Web API

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/impersonate-another-user-web-api#feedback

We have tested at postman and patch method failing to "impersonate user using the WebAPI"

Venkatta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b8abf1-8c08-7dc3-8a7d-6cf860a51dfc
* Version Independent ID: 8ec6cf6b-218e-e1d9-751b-492577534fb4
* Content: [Impersonate another user using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/impersonate-another-user-web-api#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/impersonate-another-user-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/impersonate-another-user-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Which method documented on this page are you using?

- **Preferred**: Impersonate a user based on their Azure Active Directory (AAD) object id by passing that value along with the header `CallerObjectId`. 

- **Legacy**: To impersonate a user based on their systemuserid you can leverage `MSCRMCallerID `with the corresponding guid value.

Sounds like you are saying that the impersonation behavior is just not happening. There is no error.

Documentation feedback is for documentation feedback. As far as I can tell, the docs correctly describe the behavior you should expect.

I'm not aware of any change here. If you aren't seeing the behavior documented, you should contact technical support.

**Comment by VenkattaPidikiti** [comment]
Hello,

As mentioned ,we are using On-Premise CRM Version 9.0.13 with ADFS integration. OK. we will connect Technical support

Venkatta

**Comment by sebastiensapet** [comment]
Hello all, We get same probleme with 9.0.14 On-Premise.
Do you find a fix ?

Thanks,
Sebastien.

**Comment by AbhisekBhansali** [comment]
Hi @VenkattaPidikiti  and @sebastiensapet 

Have you got a solution on this? I am also did similar. please share your experience. Appreciate your effort.

Thanks,
Abhishek

**Comment by sebastiensapet** [comment]
Hi, 

I create a ticket on Microsoft. They reproduce the issue but i'm wainting for a fix since 3 months...

Regards

**Comment by ilazarevski** [comment]
Hi,

Do you have any news regarding the impersonation of user when using Web API for D365 on-premise? We are facing with the same situation on v9.0.18.12.

Thank you in advanced.

Kind regards,
Ilija.
