### ISSUE TITLE
Query syntax error if alternate key contains slash or backslash

### ISSUE THREAD

**Issue by dmognaschi** [MicrosoftDocs/powerapps-docs#117]
In a POST or PATCH, if the request content contains a lookup attribute and the value of the attribute uses the alternate key syntax and almost an attribute of the parent entity used to compose the key contains '/' or '\', the operation fails due to  query syntax error.

Example: POST /accounts
{
...
"parentaccountid":"/accounts(attribute_used_in_altkey='abc/def')"
...
}

OData specs  requires url encoding of '/' in URI component values (http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#_Toc505773188), but 'abc%2Fdef' doesn't work.

I've found this doc (about Common Data Service) https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/define-alternate-keys-entity
See: 'Unicode characters in key value'

However with D365 webapi chars *, &lt;, &gt;, %, &, : are usable without error. Only / and \ are not.

There is a way to overcome the query syntax error?

Thank you for your kind help,
best regards
Davide Mognaschi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d869f063-f292-aef8-70fe-e165c65a74bd
* Version Independent ID: ff0b5a9f-b085-9223-3df5-ad5b5f196498
* Content: [Create an entity using the Web API (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/create-entity-web-api?view=dynamics-ce-odata-9)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/create-entity-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/create-entity-web-api.md)
* Service: **crm-online**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by brandonsimons** [comment]
This is a current limitation in the web api, but something that we are aware of.  Updates to documentation is pending, and will be updated here: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/define-alternate-keys-reference-records#limits-in-creating-alternate-keys

**Comment by JimDaly** [comment]
I discovered this open issue and know that the docs were updated since then.

See 

[Unicode characters in key value](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/define-alternate-keys-reference-records#unicode-characters-in-key-value)
If the data within a field that is used in an alternate key will contain one of the following characters <,>,*,%,&,:,/,\\ then patch or upsert actions will not work.
