### ISSUE TITLE
Crisis Communication App - Rank of FAQ

### ISSUE THREAD

**Issue by stpsupp2** [MicrosoftDocs/powerapps-docs#1170]
My understanding is that the rank of the FAQ in the admin portal can change the order of the question in the user portal. But I have set the Rank 1 - 5. But the order just follow the order of which question I set first. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by mr-dang-msft** [comment]
Hi @stpsupp2 ,
Please make sure you are using the most recent version of the Crisis Communication app. Versions V2.20200323 and higher have a fix for the Rank:
[aka.ms/CrisisCommunicationSolution](aka.ms/CrisisCommunicationSolution)

Note that the gallery in the admin app itself does not sort by rank, but that will be in the next version.
