### ISSUE TITLE
Crisis Communication App -  The Sending notifications to more than 999 users setting

### ISSUE THREAD

**Issue by stpsupp2** [MicrosoftDocs/powerapps-docs#1171]
If I set the flow to " sending notifications to more than 999 users setting" followed the instruction above, anything different when user receive notification? They can still receive notification by teams? or just email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#optional-sending-notifications-to-more-than-999-users)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. In this case, they'll only receive emails.
