### ISSUE TITLE
Crisis Communication App - 'Chat' Button on 'New Request' Adaptive Card is mapped Incorrectly

### ISSUE THREAD

**Issue by srgopal** [MicrosoftDocs/powerapps-docs#1173]
Hi,
The 'Chat' button within the 'New Request' adaptive card inside of the MS Teams team chat, redirects to the Flow BOT in 1:1 scope. Is this by design? I was expecting it would initiate an 1:1 chat with the end-user who raised the request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by mr-dang-msft** [comment]
Hi @srgopal ,
Microsoft Teams does not allow you to start a chat with yourself. So when you click the chat button while testing, it brings you to your chat screen. It will work when you click it for another user's request.
