### ISSUE TITLE
500 Error when requesting download for chunked file (> 16 MB)

### ISSUE THREAD

**Issue by a2dad** [MicrosoftDocs/powerapps-docs#1174]
Hi, I have implemented a chunked upload/download based on your example in typescript. Uploading works fine for both small (< 16 MB) and large files. Downloading small files also works. However downloading large files (> 16 MB) in chunks throws an 500 error. I'm getting the error on the initial request, which should give me the location to follow. Unfortunately, there is no error message in the response, so I cannot make out what's wrong. 
Please note, the chunked download works fine for files smaller that 16 MB. I get the location and can follow up, no problem.

Is this a preview issue or do you have any advice on what to check?

![image](https://user-images.githubusercontent.com/62538339/77295060-8dc48a80-6ce5-11ea-9290-7c4c85c44258.png)

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by a2dad** [comment]
This is regarding the following article: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/file-attributes 
It is a developer question, as the example on the page does not seem to work properly.

**Comment by phecke** [comment]
@a2dad It looks like you are not performing the first request to get the file continuation token.

See [Example: REST upload with chunking (first request)](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/file-attributes#example-rest-upload-with-chunking-first-request)

The next (and subsequent requests) must include that token.

**Comment by a2dad** [comment]
Hi @phecke, thx for the quick reply!

Yes, I am getting the file continuation token. Uploading large files (>16MB) works just fine. The following example shows an upload of a 30 MB pdf file. 
1. I request the location token (200)
2. I pass that token to chunk requests (206)
3. The last chunk request returns 204 => All good up to here

![image](https://user-images.githubusercontent.com/62538339/77820329-b7b0ef00-70e1-11ea-854c-a3bfaacdf110.png)

The problem I have occurs, if I try to download the file. Requesting the chunked download returns a 500 and not file name, size and location as specified here: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/file-attributes#retrieve-file-data

![image](https://user-images.githubusercontent.com/62538339/77820481-ed0a0c80-70e2-11ea-9fa0-a8316b08a5e5.png)

The exact same code works fine for files <16 MB. I guess this is because no chunked download is required, and everything can be handled in one request. Example below shows downloading a pdf with 7 MB.

![image](https://user-images.githubusercontent.com/62538339/77820618-e0d27f00-70e3-11ea-9983-55bd0f3a7494.png)

Any help is much appreciated!

**Comment by a2dad** [comment]
Hi @phecke 
do you have any feedback on this? Help would be appreciated!
Regards

**Comment by abhinavms987** [comment]
As per documentation, please use Range header instead of Content-Range while downloading the file.

**Comment by phecke** [comment]
@a2dad  Please follow @abhinavms987 advice.
