### ISSUE TITLE
roles isn't actually array of object.

### ISSUE THREAD

**Issue by sergeytunnik** [MicrosoftDocs/powerapps-docs#1176]
roles is some XRM collection wrapper object and not directly array of object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999537e5-d7fd-6e16-207a-b7c7c31fdc9e
* Version Independent ID: 48ac9b62-a8b5-3bab-11b5-c0bbc5fde88c
* Content: [getGlobalContext.userSettings (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings#roles)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by sergeytunnik** [comment]
This is how it look in browser console. It isn't array and not iterable object.
![online-9-1-0-14754](https://user-images.githubusercontent.com/512079/77336745-a0b07c80-6d30-11ea-9723-4a970f286d39.PNG)

**Comment by hazbark** [comment]
![JPEG image](https://user-images.githubusercontent.com/62172718/77402242-5ce36480-6d7c-11ea-90dc-baee01bda351.jpeg)


![4F779444-18B8-450D-B41D-BB2A400D4144](https://user-images.githubusercontent.com/62172718/77402363-8c926c80-6d7c-11ea-81c8-9910b05ba9f9.jpeg)

**Comment by Nkrb** [comment]
@sergeytunnik Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
