### ISSUE TITLE
Push Noticications not sent to all users

### ISSUE THREAD

**Issue by russgove** [MicrosoftDocs/powerapps-docs#1177]
Hi, We tried using the feature to send push notifications to users of the Mobile app. That feature uses the Azure AD connector to get members of the group setup in the admin app.

The Azure AD connector  is only getting  the first 100 users in the group., so not everyone is getting notified. Any way around this?

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
