### ISSUE TITLE
Start a Flow From a PowerApp in Different Environments

### ISSUE THREAD

**Issue by marcofortin** [MicrosoftDocs/powerapps-docs#1180]
From the documentation provided here: [https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/using-logic-flows] 
It must be that 
"[...] Power Apps is set to the environment in which you created the flow."
Is there any way you can trigger a Flow from a PowerApp which is in a different environment?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please review flow export/import to move across environments - https://flow.microsoft.com/en-us/blog/import-export-bap-packages/. Once the flow is available in environment with canvas app, you can add it to the app.
