### ISSUE TITLE
Documentation of possible values for Authentication/OpenIdConnect/[provider]/IssuerFilter

### ISSUE THREAD

**Issue by latsyn** [MicrosoftDocs/powerapps-docs#1181]
Dear Team,

the documentation says "A wildcard-based filter that matches on all issuers across all tenants. In most cases, use the value: https://sts.windows.net/*/". 

Is there any documentation for the other possible values?
For example are the following values valid:
https://sts.window.net/{TenantId}/
or
https://sts.window.net/({TenantIdOne})({TenantIdTwo})/

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f13d76-335f-6c2b-f674-7a5c6de3ca54
* Version Independent ID: c024348a-cc2e-61b2-95b2-3ab6c52d28e3
* Content: [Configure OpenID Connect provider settings for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-openid-settings)
* Content Source: [powerapps-docs/maker/portals/configure/configure-openid-settings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/configure-openid-settings.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
The documentation has been updated, please use the updated steps and documentation.
