### ISSUE TITLE
Unified Interface scheduling portal - date format

### ISSUE THREAD

**Issue by lesley-w** [MicrosoftDocs/powerapps-docs#1182]
Can't find anywhere else to raise this, so logging it against the documentation..

All dates displayed in the portal should be in a clear, unambiguous format e.g. 12 Apr 2020.

Shouldn't have to look at each date and convert from US to UK format in your head - just creates confusion and the possibility of errors.

I have rescheduled our upgrade to 4 Dec 2020, but when I see 12/04/2020 I automatically think 12 April 2020!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6baca2c-2716-dab9-da1f-9290d5c94d5f
* Version Independent ID: 081682e5-b125-22fc-04c9-1e784ea306f5
* Content: [FAQs: Transition to Unified Interface - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/faqs-transition-unified-interface)
* Content Source: [powerapps-docs/maker/model-driven-apps/faqs-transition-unified-interface.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/faqs-transition-unified-interface.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **haybass**

**Comment by Mattp123** [comment]
@lesley-w - Is your question about dates displayed with Portals or UCI apps?

**Comment by lesley-w** [comment]
@Mattp123 
It's on this page: https://runone.powerappsportals.com/my-environments/

![Portal](https://user-images.githubusercontent.com/23325280/78724118-ddab7e80-7980-11ea-9ddc-9a0d7dc37579.png)

I know the column header specifies the date format, but being non-American, I automatically read the date as 12 Apr 2020 instead of 4 Dec 2020

**Comment by Mattp123** [comment]
@lesley-w, For product-related feedback, visit https://ideas.powerapps.com. 

Closing this issue.
