### ISSUE TITLE
Guest users

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/powerapps-docs#1184]
Do Guest Users in Teams require a Power Apps license to run the app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0367a42-3b99-3362-2ea7-1a821d66d4eb
* Version Independent ID: 5bda16c0-b231-29f6-9da1-766ddd72b374
* Content: [Embed an app in Teams - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-teams-app)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-teams-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/embed-teams-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by SeaDude** [comment]
My guess is Guest Users will not see the app if its embedded in Teams

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The answer is Yes.
