### ISSUE TITLE
Locator service issue on a Goverment PC

### ISSUE THREAD

**Issue by t0642k8** [MicrosoftDocs/powerapps-docs#1185]
Hello, 
  I have set the Crisis Communications Management on my Developer account, But my production environment is in the GCC and I can seem to get around the Power Automate script that creates the SharePoint Lists. I get locator services must be on error.  When I refresh the page after I ensure they are on It doesn't seem to do anything after select the button.  I have a government PC that is highly modified for security and a lot of ports blocked.   Is there a workaround?

<Email address scrubbed as PII data>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Looking into the question. Please note the email address shared in initial question is scrubbed as it's part of PII data.

**Comment by tapanm-MSFT** [comment]
It's possible the browser may not share location with the app. Can you please try using Chrome browser and check again?

**Comment by t0642k8** [comment]
Unfortunately I cannot get Chrome loaded on my workstation, Government regulations etc.  I have successfully installed this at home on my home PC.  Was there a workaround or a list of
Manually steps?

**Comment by tapanm-MSFT** [comment]
Please try the following steps:

1)	Open the flow
2)	Delete the trigger
3)	Add it the trigger back

If the issue persists, please report it using the [issues link](https://aka.ms/crisis-communication-issues) since this may need additional resources to investigate or research.

**Comment by t0642k8** [comment]
Hey Jim,

It sounds like another reason for there not being anything in the drop down could be because you may have to update the SharePoint list connections. Try this step-by-step https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#update-the-sharepoint-connections to update SharePoint connections, it says to do this for the main app and admin app.

Let me know if this works.

Best,
Sierra

From: Flaherty, James A <James.Flaherty@fletc.dhs.gov>
Sent: Thursday, April 30, 2020 9:07 AM
To: MicrosoftDocs/powerapps-docs <reply@reply.github.com>
Cc: Sierra Brandenburg <Sierra.Brandenburg@microsoft.com>; Adam Frazier <Adam.Frazier@microsoft.com>; Miller, Maureen B <maureen.b.miller@fletc.dhs.gov>
Subject: [EXTERNAL] RE: [MicrosoftDocs/powerapps-docs] Locator service issue on a Goverment PC (#1185)

This seems to work, But I am at another issue.   Configuring the Admin app I get to the the notification Dropdown and its not working.
There is nothing in Drop Down and so I type Email (remember I am GCC),
I get an error stating I have to fill the required inputs, the only one required is the Notification Method.

I found this article  https://github.com/microsoft/powerapps-tools/issues/152<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpowerapps-tools%2Fissues%2F152&data=02%7C01%7CSierra.Brandenburg%40microsoft.com%7Ce836e079efea440cb55a08d7ed075d27%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637238488199333088&sdata=ITpXEK7nel95PnmhpqdAD5fvW2eb2d0T%2FJx1ZtJC7Ww%3D&reserved=0>
I look at the form it has Two SharePoint connections going to the same site and same lists.
I didn’t finish the article , yet but I am getting frustrated.
