### ISSUE TITLE
Enabling MFD

### ISSUE THREAD

**Issue by rksharma24** [MicrosoftDocs/powerapps-docs#1186]
Can this be configured at the entity level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de4d4b3d-d009-0f07-606f-1a28615a5154
* Version Independent ID: d6a79659-8d64-7aa6-3ac1-fac8322307ae
* Content: [Customize entity forms (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/customize-entity-forms#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/customize-entity-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/customize-entity-forms.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by mspilde** [comment]
Not at this time, it is a pro-dev scenario that requires coding to invoke a main form in a dialog (MFD).  The ability to enable it via an entity configuration is on our roadmap.  I don't have an eta on a release date yet but we will announce via our normal channels with release notes, blogs and docs when it is available.

**Comment by rksharma24** [comment]
Thank you Mark.
