### ISSUE TITLE
Resource ID is incorrect

### ISSUE THREAD

**Issue by ananthagithub** [MicrosoftDocs/powerapps-docs#1187]
The Resource URI (https://discovery.crmreplication.azure.net/crm/exporter/aad/challenge) used in the sample code is incorrect. It should instead be the Application Id of the Data Export Service SPN ("Data Export Service for Microsoft Dynamics 365") created during the installation of the Data Export Service App

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b78e7a4-a539-c230-0a8c-454f1f69201a
* Version Independent ID: 777f3fea-cd80-9233-715f-4947cb1077f9
* Content: [Data export service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/data-export-service#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/data-export-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/data-export-service.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
Need to change the authentication code to use MSAL instead of ADAL.

**Comment by phecke** [comment]
@ananthagithub The Data Export Service has reached end-of-support and end-of-life in November 2022. The topic will not be updated. Thanks for your feedback.
