### ISSUE TITLE
Error in Importing Crisis Communication News Notifications

### ISSUE THREAD

**Issue by AyeChan1309** [MicrosoftDocs/powerapps-docs#1188]
Hi,
When I import   Crisis Communication News Notifications zip file, it show this error message.
[The pagination policy of workflow run action 'Get_group_members' of type 'ApiConnection' at line '1' and column '5677' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.]
Please give me help or advice for this error. Thank you.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This issue has been resolved in the latest app. Please feel free to reach out using the [issues link](https://aka.ms/crisis-communication-issues) for any additional issues.
