### ISSUE TITLE
Example to delete selected record on browse screen 

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#1189]
Would be nice to expand to include delete top row, delete this record from browse screen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6704bc7c-5ecf-e7d6-9c9b-9b017792f7e0
* Version Independent ID: 33afbceb-000b-3b44-89fe-7e8195c75ed3
* Content: [Remove and RemoveIf functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-remove-removeif#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-remove-removeif.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-remove-removeif.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Good suggestion.  We created two new examples, one for [deleting an item from outside a gallery](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-remove-removeif#examples---remove-button-outside-a-gallery), and one from [inside the gallery](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-remove-removeif#examples---trash-can-icon-inside-a-gallery).
