### ISSUE TITLE
Gateway management

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#119]
please add some cmdlets for managing the on-premises data gateway

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell#powerapps-cmdlets-for-administrators-preview)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
@DeanGross 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
