### ISSUE TITLE
Crisis Communication App

### ISSUE THREAD

**Issue by stpsupp2** [MicrosoftDocs/powerapps-docs#1191]
Crisis Communication App
Issue description
I am testing the Crisis Communication App package provided by ms . I follow this website and install the app with following website: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app . But I found some problems when testing the app.
1) My understanding is that the rank of the FAQ in the admin portal can change the order of the question in the user portal. I have set the Rank 1 - 5. But the order did not re-arrange.
2)If I set the flow to " sending notifications to more than 999 users setting" followed the instruction above, anything different when user receive notification? They can still receive notification by teams? or just email.
3) When I test on this Tuesday. I found that when I change the work status of the app, the work status should appear on the right corner of my screen. But now it disappear. Other is that , I can set a auto replay of my email after update my work status. It work on Tuesday but I found failed now.

Would you contact me by email? my email is stpsupp2@oocl.com and I could provide more detail.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This is fixed in latest app. For any additional issues, please feel free to reach out using [issues](https://aka.ms/crisis-communication-issues) link.
