### ISSUE TITLE
Prefill attributes when creating new entity

### ISSUE THREAD

**Issue by Miesjh** [MicrosoftDocs/powerapps-docs#1193]
Is there a way to prefill attributes on the entity form? Just like the entityFormOptions in Xrm.Navigation.openForm. I use the dialog to create a new record. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by avishesh-shrestha** [comment]
Please provide parameter similar to openForm - formParameters so that the fields can be prefilled when creating a new record.

**Comment by Miesjh** [comment]
In issue 1194 I asked for more info for the pageType entityrecord. Now this is added, I can see how to prefill a form. The createFromEntity and data attributes can now be used.

**Comment by Nkrb** [comment]
@Miesjh Thanks for the feedback. I hope you got the issue resolved. Closing the issue. Please re-open the issue if you need to have any information on this.
