### ISSUE TITLE
Known issue closed but not resolved.

### ISSUE THREAD

**Issue by tpmeredith** [MicrosoftDocs/powerapps-docs#1195]
The issue "Add to Known Issue #1071" was closed and is no longer being responded to.

The "solution" they said is not a solution as they did not read the issue entirely. The issue is unlike pre-grid filter improvement you cannot have 2 different filters at once. This means you cannot have "on or before" AND "on or after" dates AT THE SAME TIME to have a date range. This is a big deal for many orgs like ours working with records that have date fields.

She mentioned "Between" has been implemented and is being rolled out, but there is zero documentation anywhere to back that up either. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e9258f-4c21-9d52-9940-cada6c70db50
* Version Independent ID: 1f5619dd-aea0-d0d4-34a9-a7e0e036faf8
* Content: [Filter data on grids - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/grid-filters#feedback)
* Content Source: [powerapps-docs/user/grid-filters.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/grid-filters.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@tpmeredith Apologize for delayed replay. I have forwarded your question to my internal PM contact.

Thanks,
Mints

**Comment by mduelae** [comment]
@tpmeredith does this help: https://powerapps.microsoft.com/en-us/blog/create-personal-views-in-unified-interface-through-advanced-filtering-for-grids/

Thanks,
Mints

**Comment by tpmeredith** [comment]
Thanks this is awesome!
