### ISSUE TITLE
Crisis Communication App - Connection not configured for this data source

### ISSUE THREAD

**Issue by Alexp2019** [MicrosoftDocs/powerapps-docs#1197]
Hi,

We have an issue when a new user opens the app they sometimes receive the following on mobile.
This only occurs on the first load. Once the user has successfully loaded the app, the issue goes away.  

![image](https://user-images.githubusercontent.com/38928645/77708352-908bec00-7013-11ea-9f83-9cc2db15b26f.png)

If they restart the app, the issue goes away.
This occurrs on iOS devices.

**Comment by MDRooks** [comment]
I had this same issue. I was able to resolve it by deleting the data sources in the app and then re-adding them. I'm not sure why it resolved the issue though.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This is resolved in latest version. Please download latest Power App mobile from the store.
