### ISSUE TITLE
Is note correct

### ISSUE THREAD

**Issue by ARGMeyer** [MicrosoftDocs/powerapps-docs#1198]
The purple note on this page says "Signing out is not supported while running the app in a web browser."

Would it be more accurate to say that THE EXIT FUNCTION is not supported? It's not just use of the optional Signout parameter that doesn't work. If I'm right, then this clarification would have saved me a lot of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bebfbe35-2e12-a134-2ab6-94435adc43d2
* Version Independent ID: 8807c8b1-ab9b-4c36-0c56-fc238f0e7c00
* Content: [Exit function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-exit#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-exit.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-exit.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Exit, in general, does work fine in a web browser.  Create a new app, add a button, OnSelect = Exit(), save, publish, and run the app in the web player.  Pressing the button will take you to the Power Apps home page where another app can be selected.

There are two web caveats: 
- It won't exit the app when authoring, but will stop the remainder of the formula from running.  We obviously don't want to close the authoring experience.  This is noted in the documentation.
- The sign out parameter is not supported (the subject of the note).  I've added some more detail to the note to make that a little clearer, which is making its way through the publishing pipeline.

Please try again and if it isn't working as you expected please reopen this issue.
