### ISSUE TITLE
Is this function checking if all required field have a value ?

### ISSUE THREAD

**Issue by Dremor** [MicrosoftDocs/powerapps-docs#1199]
Is this function checking if all required field have a value ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0d7b297-f64d-b276-a932-707e8fd0c731
* Version Independent ID: df24bcdb-694c-9ce5-bed2-724e4e90dc85
* Content: [isValid (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data/isvalid)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/isValid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/isValid.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@Dremor Yes it checks for required fields have values.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
