### ISSUE TITLE
Screenshots out of date [Flow]

### ISSUE THREAD

**Issue by PhilStollery** [MicrosoftDocs/powerapps-docs#120]
This content is out of date with the current PowerApp and Flow UI. Also it would be useful to add details on passing data to and from a Flow from within a PowerApp.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6f3757-df76-e952-195f-2cad83db28ff
* Version Independent ID: 3e00ab9d-7920-7211-5c9e-b1be77b9cac2
* Content: [Start a flow in a canvas app - PowerApps](https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/using-logic-flows)
* Content Source: [powerapps-docs/maker/canvas-apps/using-logic-flows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/using-logic-flows.md)
* Service: **powerapps**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **sharik**

**Comment by AFTOwen** [comment]
Text and screenshots updated to reflect current UI. Thanks, @PhilStollery!
