### ISSUE TITLE
Value Colum Width Is Incorrect 

### ISSUE THREAD

**Issue by MaTeMaTuK** [MicrosoftDocs/powerapps-docs#1202]
Hi Guys,
These pages 
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property-set 
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property
have same problems as https://github.com/MicrosoftDocs/powerapps-docs/issues/1066

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b2e635-6c60-0efc-d894-e43216dca90e
* Version Independent ID: 9828125d-c061-465e-d486-b4ea609190e1
* Content: [Property Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property#feedback)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/property.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@MaTeMaTuK Thanks for the feedback. We have informed the engineering team to look into this issue. Closing the issue.
