### ISSUE TITLE
Community Plan and Common Data Services 

### ISSUE THREAD

**Issue by ecueva253** [MicrosoftDocs/powerapps-docs#1203]
Hello, 

I am unable to create a database with the individual developer environment provided by community plan. 

When I try to create a database it says 

"A self-service signup plan is required to successfully complete this request." 

Then when I try to signup for the trial going through admin center for PowerApps in create my database, it relinks me to get started and the following message 

"Sorry...
We can't finish signing you up.

Your IT department has turned off signup for Microsoft PowerApps. Contact them to complete signup.
Learn about other ways to get Office"

I am using a student email. The process to try out the environment in order to learn is becoming a loop of issues. 

I have also tried my own business email but it asks me to "verify your identity" then the following message 

"Sorry, we need additional information to verify your identity. Please contact Office 365 Support.
Enter your phone number and we'll send a verification code. Microsoft won't use this phone number for other purposes without your permission." 

With the link to a page that returns "Not Found" 

I had to end up creating a github account in order to request for help and/or provide feedback. 

Can someone please assist so I can test the entire environment before I make a recommendation to the director of my company to transition a whole department of analyst to the power platform.  

E

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d27942c-51fc-c2dc-9857-bcbfbadba145
* Version Independent ID: 832089db-9a05-9d52-7529-429e3a6648f8
* Content: [Power Apps Community Plan -- a free development environment for individual use - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan#feedback)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.
