### ISSUE TITLE
Portal Side of functionality is not working, the control does not render

### ISSUE THREAD

**Issue by bambooo310** [MicrosoftDocs/powerapps-docs#1204]
This documentation needs an update e.g.  the CORS part requires to mention that the URL is of the CDS/Dynamics instance, and also the web resource control for adx/annotation does not render or load properly on the portal page when configured, the functionality is broken.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdd598f-2269-05e7-25e8-f014bef0ff6e
* Version Independent ID: 8b9996ad-708b-f5dc-3df2-d0d7e8b1a8bf
* Content: [Add azure storage web resource to a form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/add-web-resource#feedback)
* Content Source: [powerapps-docs/maker/portals/add-web-resource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/add-web-resource.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content is being updated. Please allow some time to reflect the changes. For issues with the functionality, please reach out with a [support service request](https://admin.powerplatform.microsoft.com/support) for further investigation.
