### ISSUE TITLE
Select appears to be Async and no way to influence that.

### ISSUE THREAD

**Issue by strattonn** [MicrosoftDocs/powerapps-docs#1208]
It's important to understand Select is Async and there doesn't appear to be a way to change that when calling Select.

If I have the following code.
Set(varMsg,"Start");
//The output of the this Select to varMsg is "Long task started" and "Long task ended" when complete.
Select(SomeLongRunningSelect);  
//The output of the next Select to varMsg is "Short task started" and "Short task ended" when complete.
Select(SomeShortSelect); 
Set(varMsg,"End");

The final output will be 
Start
End
Long task started
Short task started
Short task ended
Long task ended

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582a8f8d-1f70-b2f8-cdcd-2c4f03b82ca8
* Version Independent ID: b8dbb751-54db-efbb-0de3-ed5d006c0d97
* Content: [Select function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-select#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-select.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-select.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Yes, Select is indeed asynchronous.  The documentation calls this out:

_Select queues the target OnSelect for later processing, which may happen after the current formula has finished being evaluated. Select doesn't cause the target OnSelect to evaluate immediately, nor does Select wait for OnSelect to finish being evaluated._

If you were using a button OnSelect as a workaround for creating a user defined function, we are working on features to better address this scenario.

**Comment by jrkager** [comment]
@gregli-msft Hi, are there any news on the features you were working on to address the scenario of creating and calling user defined functions?

**Comment by jonnymop5** [comment]
Hi Greg.  Has there been any progress on this feature to better address the issue?

> Yes, Select is indeed asynchronous. The documentation calls this out:
> 
> _Select queues the target OnSelect for later processing, which may happen after the current formula has finished being evaluated. Select doesn't cause the target OnSelect to evaluate immediately, nor does Select wait for OnSelect to finish being evaluated._
> 
> If you were using a button OnSelect as a workaround for creating a user defined function, we are working on features to better address this scenario.
