### ISSUE TITLE
Missing documentation on Mscrm.OpenRecordItem

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#1209]
I can find no documentation other than this page on the Mscrm.OpenRecordItem command - it used to be located at https://docs.microsoft.com/en-us/dynamics365/release-plans/#override-the-default-open-behavior-of-data-rows-in-an-entity-bound-grid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74252232-bb80-d603-bc46-4c1bdaabb0c4
* Version Independent ID: e5c12903-cf4d-5ec7-ffe8-a2272abb00b1
* Content: [openDatasetItem - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/dataset/opendatasetitem#feedback)
* Content Source: [powerapps-docs/developer/component-framework/reference/dataset/opendatasetitem.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/dataset/opendatasetitem.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@scottdurow Do you think that the specified doc is missing from the location you have pasted?

**Comment by scottdurow** [comment]
No, I wouldn't expect that to still be there because it's from the previous release notes - rather this is the only mention of Mscrm.OpenRecordItem - there should be another docs page describing how Mscrm.OpenRecordItem is meant to be used to change the record open behaviour in grids (as was described in the release notes).

**Comment by rajyraman** [comment]
I wasn't aware about this feature until I read Andrew's blog today. This is the only official documentation I could find (apart from PCF's tsds) https://github.com/MicrosoftDocs/testing-preset/blob/cb24f458d94f5ae28ef0158fdaaa949a50c31cc2/samplefiles/get-started/whats-new/customer-engagement/new-in-version-9-for-developers.md#override-the-default-open-behavior-of-data-rows-in-an-entity-bound-grid

**Comment by Nkrb** [comment]
@scottdurow @rajyraman Here is the link to the [topic](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/override-default-open-behavior-grids). Closing the issue.

**Comment by danosagi** [comment]
I know this is old but the current working URL is: 
[https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/override-default-open-behavior-grids](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/override-default-open-behavior-grids)
