### ISSUE TITLE
Cannot create template for SQL server source

### ISSUE THREAD

**Issue by chrisewallace** [MicrosoftDocs/powerapps-docs#121]
We are wanting to integrate a SQL Server source.  To Dynamics 365 online destination. We can create a connection set specifying SQL Server and Dynamics connections. When we try to create a new template following the guidance above we do not see a base template matching our connection set. If we attempt to use any of the base templates our connection set never appears in the connection set drop down. Does not appear integration with anything other than AX or SalesForce is supported. A bit limiting!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6352172-89dc-9489-2271-6397e9302c6d
* Version Independent ID: db401145-b8b7-55a2-f829-a63d538cf7f0
* Content: [Integrate data into Common Data Service for Apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/data-integrator#how-to-customize-or-create-your-own-template)
* Content Source: [powerapps-docs/administrator/data-integrator.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/data-integrator.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by wauters** [comment]
Agree! Any update on this?

**Comment by KumarVivek** [comment]
@chrisewallace @wauters Looks like the template/feature you are looking for is currently available only to customers in the North America region.

We'll update the docs with this information soon.

cc: @sabinn-msft @jimholtz

**Comment by jimholtz** [comment]
Closing this. Please reopen if this is still a question.
