### ISSUE TITLE
Missing step in the tutorial lab documentation

### ISSUE THREAD

**Issue by lokiRT** [MicrosoftDocs/powerapps-docs#1210]
The hands on lab is missing a pipeline task for step 6 above "Import the unmanaged solution to a build environment."  A publish customizations is needed after the unmanaged solution import in order for changes to be available for step 7 "Generate a build artifact (managed solution)." Skipping it has varying results with regard to model apps, forms, and views from what we have seen so far.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ec2747-81eb-32df-8120-0215a2b8543d
* Version Independent ID: 674f07e3-f3a7-9a90-2df2-7582cdabedef
* Content: [Build tools tutorial and FAQ - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tutorial-faq)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tutorial-faq.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tutorial-faq.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment]
@lokiRT I have passed your issue on to the team that owns the lab. Thanks for the feedback.
