### ISSUE TITLE
Embedding canvas app on a form in different environment should maintain access to context on record

### ISSUE THREAD

**Issue by SoleDevv** [MicrosoftDocs/powerapps-docs#1212]
If I have a canvas app that was created in my development environment and I've embedded on a contact form in the same environment then the context of the record where it is embedded works as expected. If I move that form in a solution to a higher environment and keep the canvas app in the original environment then the context of the record where my app is embedded is lost when opening the same app in the higher environment.

Layout:
Dev1
    -Canvas app
    -Contact Form w/ App (Loads context as expected)

UAT
    -Contact Form w/ app that is in Dev1 still (Context is blank)

... and so on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d72044c0-7486-402e-4ad0-cd488f6356e0
* Version Independent ID: 3b762213-c234-14b3-7f11-cde507cced78
* Content: [Add an embedded canvas app on a model-driven form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-add-classic-designer)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by iangpgh** [comment]
@NunezJr  Thanks for your feedback. For product-related feedback, visit https://experience.dynamics.com/ideas/.
I have forwarded this issue to product management as a suggestion for documenting the behavior.  Closing this issue.

**Comment by iangpgh** [comment]
@Mattp123 - Closes #1212
