### ISSUE TITLE
Please update links for defining calculated and rollup fields

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1213]
The links on this page for :

- Define calculated fields: https://technet.microsoft.com/library/dn832103.aspx
- Define rollup fields: https://technet.microsoft.com/library/dn832103.aspx

Send people to topics on technet that are then routed to previous version docs.
We have topics about how to do this here:

- https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/define-calculated-fields
- https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/define-rollup-fields

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 076b411d-471c-03c6-c3a6-7dac875e7146
* Version Independent ID: 9a3ceec1-f0b8-59f4-24bb-047b5119a5f7
* Content: [Calculated and rollup attributes (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/calculated-rollup-attributes#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/calculated-rollup-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/calculated-rollup-attributes.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by mayadumesh** [comment]
@Nathan<mailto:nhelgren@microsoft.com> – can you please review..
~Maya

**Comment by mayadumesh** [comment]
Yup on it.

From: Maya Dumesh <Maya.Dumesh@microsoft.com>
Sent: Tuesday, March 31, 2020 10:25 PM
To: MicrosoftDocs/powerapps-docs <reply@reply.github.com>; MicrosoftDocs/powerapps-docs <powerapps-docs@noreply.github.com>; Nathan Helgren <nhelgren@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerapps-docs] Please update links for (#1213)

@Nathan<mailto:nhelgren@microsoft.com> – can you please review..
~Maya

**Comment by KumarVivek** [comment]
This is fixed and will go live EOD today.
