### ISSUE TITLE
How to know the type of attributes when retrieve records using web api.

### ISSUE THREAD

**Issue by Flex-Xuan** [MicrosoftDocs/powerapps-docs#1214]
when using Organization Service, we use [RetrieveRequest ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.messages.retrieverequest?view=dynamics-general-ce-9) to get a record, in the returned record ([Entity](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.entity?view=dynamics-general-ce-9)), there is an [AttributeCollection ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.attributecollection?view=dynamics-general-ce-9) property, we can easily to know what the attribute type is. for example 
```
if (value is OptionSetValue)
{
   //do something
}
else if (value is OptionSetValueCollection)
{
   //do somthing
}
else if (value is Money)
{
   //do something
}
```
but how this can be done in web api? for example, below is piece of response

> 	"exchangerate": 1.0000000000,
> 	"name": "projec",
> 	"opendeals@OData.Community.Display.V1.FormattedValue": "1",
> 	"opendeals": 1,
> 	"modifiedon@OData.Community.Display.V1.FormattedValue": "2/6/2020 3:10 AM",
> 	"modifiedon": "2020-02-06T03:10:24Z",
> 	"_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
> 	"_owninguser_value": "4f6d8e24-09eb-43c6-919d-7c9091c080f4",
> 	"_primarycontactid_value@OData.Community.Display.V1.FormattedValue": "project",

how to know opendeals is an Integer or an OptionSet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3c595b-8fd1-9093-ba63-ab54cf4802d6
* Version Independent ID: 21f4822a-c0c9-885f-0c02-9cb5de024dd1
* Content: [Web API types and operations (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/web-api-types-operations)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/web-api-types-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/web-api-types-operations.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **susikka**

**Comment by JimDaly** [comment]
The difference between using the .NET SDK assemblies and the WebAPI is that there are no SDK assemblies with the Web API.

Therefore at run-time you won't find typed classes detect this type dynamically. 
Everything is reduced to [simple types](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/web-api-types-operations#primitive-types). 

Your question seems to be "_How do I know which values are valid to set?_". That depends on the context of your app. It is expected that you have knowledge of the fields your app is working with. 

You can refer to the application metadata at design time if you need to look this up.

If this doesn't answer your question, please advise the scenario where you are blocked by this.

**Comment by Flex-Xuan** [comment]
Yes, I know the difference between .NET SDK assemblies and the WebAPI.

we have a tool to query data and sync the values to another platform, something we want to is :
1. for option set , we get the data from formatted values
2. for string, int, bool, money type of values, we get the data from value

It's impossible to know all the fields type because some entities are custom entity, we need auto discover the value's type at run-time.

**Comment by phecke** [comment]
@Flex-Xuan Thanks for the feedback.
