### ISSUE TITLE
GA Timeline

### ISSUE THREAD

**Issue by rajagops** [MicrosoftDocs/powerapps-docs#1215]
Please provide information on when this is expected to be GA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b93a524-63ec-8b9c-cabf-042e38ccf5bd
* Version Independent ID: 5a3b40cc-8c0a-2a25-1ec6-cec49f7f8f69
* Content: [addGlobalNotification (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-app/addglobalnotification#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-App/addGlobalNotification.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-App/addGlobalNotification.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@rajagops Unfortunately we can't provide the GA dates for the features. They tend to be changed because of numerous factors. Closing the issue.

**Comment by LinnZawWin** [comment]
@Nkrb how can we know if the feature is still in preview or GA?
E.g. For the **Environment variables**, it is mentioned in [the documentation](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/environmentvariables) that the feature is still in preview.
But in the [documentation for addGlobalNotification](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/environmentvariables), there is nothing mentioned about the feature being still in preview.

**Comment by Nkrb** [comment]
@LinnZawWin Generally we add a tag at the top of the article when the feature is in preview, We remove the tag when the feature enters GA.

**Comment by LinnZawWin** [comment]
@Nkrb  I really appreciate your response.
Currently, I do not see any tag at the top of the addGlobalNotification article. Does that mean the feature is already GA or did I miss out the tag?
![image](https://user-images.githubusercontent.com/14156926/84881690-539b3700-b0e2-11ea-83e4-7b0ff6066d4b.png)
