### ISSUE TITLE
Unclear whether SaveData/LoadData works on a Windows Tablet

### ISSUE THREAD

**Issue by aianta** [MicrosoftDocs/powerapps-docs#1216]
I'm building some offline functionality for an app running on Microsoft Surface Go tablets. Each tablet has PowerApps downloaded from the Microsoft Store through which they run the application. 

I'm noticing that my calls to SaveData & LoadData do not seem to be doing anything. I call SaveData throughout the app and have LoadData called in the App.onStart formula. 

Any ideas on what may be amiss?

I'm worried this is because I'm not running through Power Apps mobile on an Android or Apple device.

**Comment by aianta** [comment]
In case anyone else is having trouble using SaveData/LoadData on a Surface tablet. 

This thread suggested that it should be possible: https://powerusers.microsoft.com/t5/Building-Power-Apps/Offline-Capability-Surface-Tablet-Pro/m-p/446678#M132727

After some messing around I was able to get SaveData & LoadData to work on the tablet. My problem was that I had a `.` in the name parameter. So changing:

`SaveData(data, "offline.data")` to `SaveData(data, "data")` 
and
`LoadData(data, "offline.data")` to `LoadData(data, "data")` 

was the fix.

**Comment by gregli-msft** [comment]
The SaveData and LoadData functions do work in the Windows client.   The Windows client has not been updated for a while, so it is lacking some of the performance and reliability improvements we have made for iOS and Android, but the basic functionality is there.

I'm sorry about the behavior with the `.` in the name.  We're looking into it.  If that character can't be supported we should be throwing an error.  Note that the name parameter is not an actual filename but really just a key to be used with LoadData.

**Comment by aianta** [comment]
Thanks, it makes sense, I'm guessing the Android and iOS clients have a significantly larger userbase, I apologize for the negative tone of my initial posting, it was a very long day. 

If there are logs or anything else I can provide to help please let me know!

**Comment by gregli-msft** [comment]
The product has been changed to return an error if an illegal character is used, one of `*".?:\<>|/`.  The documentation has also been updated and is in the process of rolling out.
