### ISSUE TITLE
Time zones?

### ISSUE THREAD

**Issue by dacoach01** [MicrosoftDocs/powerapps-docs#1219]
What about when the system clock is in a different time zone than the users entering data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c53077bc-20f5-318d-b5f3-e9a7065f59d8
* Version Independent ID: a62307d1-3297-0c41-118e-6771c55eee23
* Content: [Now, Today, and IsToday functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-now-today-istoday#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-now-today-istoday.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-now-today-istoday.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Entered date/time values are in the time zone of the user's browser.  When stored to a database, these are typically converted to UTC but not always.  This is a complex area, I recommend reading through the [date/time information in the data types documentation](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types#date-time-and-datetime).
