### ISSUE TITLE
To whom may get trouble with invalid argument

### ISSUE THREAD

**Issue by YangHongshen** [MicrosoftDocs/powerapps-docs#1220]
Spent a week to find the solution for "invalid argument" error:

1. Create a Media Import Button
2. Write functions without test
3. DON'T CLICK DURING EDIT!
4. Publish straight away
5. Test on the desktop version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68da6b4c-82dc-8526-480d-c09c70bcfa1e
* Version Independent ID: d7edd51f-c3e0-dd47-1012-80c606e2dc74
* Content: [Export control and Import control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-export-import)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-export-import.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-export-import.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there, can you elaborate more what you were trying?

**Comment by YangHongshen** [comment]
@chmoncay Hi, the issue was
If add an media-import button in Canvas app, and coincidentally clicked during web editing, this button breaks. only fix is delete and re-add.
