### ISSUE TITLE
"crete" typo

### ISSUE THREAD

**Issue by ElizabethWolfe** [MicrosoftDocs/powerapps-docs#1223]
f. Expand Create and update settings and select the Enable quick create forms check box. This option ensures, you can use the quick create form to **crete** a record.

This should read as **create**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11bacb37-4743-1d0e-d13e-1d9b656c661f
* Version Independent ID: 7b4d6192-4282-c5c1-01a2-a3ba065ed6e6
* Content: [Create a custom entity - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-create-entity)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-create-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-create-entity.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@ElizabethWolfe - thank you for helping to improve the documentation. The typo has been fixed and will be published live by the end of the day (PST). Closing issue.
