### ISSUE TITLE
= Blank() Invalid Argument type

### ISSUE THREAD

**Issue by Paul-VZ** [MicrosoftDocs/powerapps-docs#1225]
If (**field from data-source [Share Point List]** = Blank(), false, true)

= <-  Invalid Argument type ?

This is in the Visible property for a shape.

**Comment by phecke** [comment]
@Paul-VZ 

Please provide a link to the documentation that needs clarification or modification. I cannot assign the issue to a writer until I know what documentation is causing you trouble and more details on what the problem is. Thanks.
