### ISSUE TITLE
Publication Date

### ISSUE THREAD

**Issue by bthompson-365** [MicrosoftDocs/powerapps-docs#1226]
Given that this document now includes MFD information could you update the publication date of the document to reflect that these changes were made in April 2020 rather than October 2018..

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de4d4b3d-d009-0f07-606f-1a28615a5154
* Version Independent ID: d6a79659-8d64-7aa6-3ac1-fac8322307ae
* Content: [Customize entity forms (model-driven apps) - Power Apps](https://docs.microsoft.com/en-gb/powerapps/developer/model-driven-apps/customize-entity-forms#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/customize-entity-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/customize-entity-forms.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@bthompson-365 Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
