### ISSUE TITLE
Plural name for entities and the complexity

### ISSUE THREAD

**Issue by imranakram** [MicrosoftDocs/powerapps-docs#1227]
Could you also add some information on how to sort out these plural names for entities (both custom and system). Are there any helpful third party tools to help deal with this complex format? Why does this have to be so complex? I mean this whole necessity to add `@odata.bind` and plural names for entities instead of simple schema names?

`"new_relatedopportunities_task@odata.bind": "/opportunities(61a0e5b9-88df-e311-b8e5-6c3be5a8b200)"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736633bc-d0f6-0665-c487-dab6c36a677f
* Version Independent ID: b83eba0e-908d-a1bc-5e81-a642afb9276c
* Content: [updateRecord (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/updaterecord#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/updateRecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/updateRecord.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
