### ISSUE TITLE
Create input.xml file Package Term Link

### ISSUE THREAD

**Issue by ugreg** [MicrosoftDocs/powerapps-docs#1228]
Is it possible to provide a full https link here instead of an html file?

Instead of this:
```xml
<Terms>
    <PackageTerm File="TermsOfUse.html" />
</Terms>
```

We'd use:
```xml
<Terms>
    <PackageTerm File="https://www.example.com/TermsOfUse.html" />
<Terms>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2af3070-30b8-395e-ea51-86e954e3b006
* Version Independent ID: c1e95af9-6261-7da1-07ce-1b8986ef3738
* Content: [Step 3: Create an AppSource package for your app (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-package-app-appsource#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/create-package-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/create-package-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
As discussed earlier, it isn't. Closing the issue.
