### ISSUE TITLE
Please use full hex value error code

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1229]
Today, the hex values look like this: 80040265 for an error like -2147220891
But when this value is returned as an error in the Web API, the actual JSON returned will be this:

{
    "error": {
        "code": "0x80040265",
        "message": "Business logic on the server cancelled this operation."
    }
}

Someone searching the internet (or even this page) for '0x80040265' will not match with '80040265'

We should use the  '0x80040265' hex format instead of '80040265'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223aafba-8d35-a232-ab10-d3aac99d85f2
* Version Independent ID: 2ec5626c-56f5-abd6-d458-1d8f9e33b4b0
* Content: [Web service error codes (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/web-service-error-codes)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/web-service-error-codes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/web-service-error-codes.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@phecke Can you do this next time you generate this doc?

**Comment by phecke** [comment]
@phecke Done.
