### ISSUE TITLE
The url for Pass data from a page as a parameter to Ribbon Actions is wrong.

### ISSUE THREAD

**Issue by luoyong0201** [MicrosoftDocs/powerapps-docs#1230]
Please set it correctly.  The correct url is https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/pass-data-page-parameter-ribbon-actions 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25c896b1-85b8-9abe-c79a-880e764e30b9
* Version Independent ID: 21a4ff22-6afb-ae7a-99c5-8b8cc5342c3b
* Content: [Define ribbon actions (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/define-ribbon-actions?source=docs)
* Content Source: [powerapps-docs/developer/model-driven-apps/define-ribbon-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/define-ribbon-actions.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@luoyong0201 Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
