### ISSUE TITLE
Conflicting licensing information

### ISSUE THREAD

**Issue by PekkaSahlsten** [MicrosoftDocs/powerapps-docs#1233]
The sentence "Complex entities are only applicable for Power Apps Plan 1 and Plan 2 licenses and not for Power Apps per app and Power Apps per user plans. " conflicts with the linked Power Apps licensing guide. No Power Apps Plans are not required or even mentioned in the guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87257a9a-36dd-e791-8240-c52f35e9f44d
* Version Independent ID: fee3775a-17ff-2d33-dd05-ba385360515d
* Content: [Complex entities requiring Power Apps Plan 2 licenses - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-complex-entities#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-complex-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-complex-entities.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bthompson-365** [comment]
Power Apps Plan 1 and Plan 2 were discontinued back in September / October 2019.

**Comment by KumarVivek** [comment]
Closing the issue.
