### ISSUE TITLE
PowerApps Checker throwing error: "You cannot call a method on a null-valued expression"

### ISSUE THREAD

**Issue by skyovi** [MicrosoftDocs/powerapps-docs#1235]
I am trying to user PowerApps Checker task in Azure Build pipeline to perform solution checker on our D365 solution. 

the task is throwing the following errro:
**You cannot call a method on a null-valued expression**

Authentication: Service Principal authenticaiton (client id and secret)
Endpoint: https://unitedstates.api.advisor.powerapps.com/
Ruleset: Solution Checker

However, I am able to perform checker using Power Shell cmdlets (Invoke-PowerAppsChecker) using same authentication mechanism

**Comment by KumarVivek** [comment]
@skyovi For product-related feedback, please visit <https://powerusers.microsoft.com/t5/Get-Help-with-Power-Apps/ct-p/PA_General>

For Power Apps Support, visit <https://powerapps.microsoft.com/en-us/support/>

Closing the issue.
