### ISSUE TITLE
Unable to run tests within the Power Apps host app

### ISSUE THREAD

**Issue by craig-blowfield** [MicrosoftDocs/powerapps-docs#1236]
As my app uses offline caching (SaveData/LoadData), I can not test these aspects from the browser.

How can I run these tests within the Power App host application? If not, when will this capability be added?

Or should I just use UI Flow or similar technology?

**Comment by Nkrb** [comment]
Is this in regard to some Microsoft docs article? Please provide its URL. Is this a developer,admin, or end-user question? Thanks

**Comment by KumarVivek** [comment]
Thanks for your question. For product-related question, please visit <https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1>.  

Closing this issue.
