### ISSUE TITLE
Power App visual only supports apps from your tenant?

### ISSUE THREAD

**Issue by leinoaa** [MicrosoftDocs/powerapps-docs#1237]
It seems that by default the Power App visual refers to your tenant. The app gives an error message saying that the app can't be found in tenant B. However the user can open the Power app from the powerapp service site. And of course the app works normally in the report in tenant A.

So if the report was created in tenant A, with a Power App in tenant A. Quests users from tenant B can't use the Power App in the report which is published in the Power Bi of tenant B. Even though they have necessary quest access' (and licenses) to tenant A and can open the Power app online. So they can access the app in the Power App -service but it doesn't work in the visual in Power BI, whether it is PBI desktop or the service. So in short does the visual only support the use of Power apps from your own tenant? At least based on our testing this would seem to be the case. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f94c3-694a-6d09-3a4f-e4b741684822
* Version Independent ID: c952e698-a2bf-a47d-acbd-a96a8a922636
* Content: [Power Apps visual for Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual#limitations-of-the-power-apps-visual)
* Content Source: [powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Power Apps visual doesn't support [guest users](https://docs.microsoft.com/powerapps/maker/canvas-apps/powerapps-custom-visual#limitations-of-the-power-apps-visual).
