### ISSUE TITLE
Formatting errors

### ISSUE THREAD

**Issue by josiahvinson** [MicrosoftDocs/powerapps-docs#1239]
There are apostrophe characters all over this page and in the code sample that break the formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16e7478f-bfd9-607d-c5fa-2e9af28302ab
* Version Independent ID: d8e1b97b-301d-9353-b279-a72354ffa8f2
* Content: [Global Discovery Service Sample (C#) (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/samples/global-discovery-service-csharp)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/samples/global-discovery-service-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/samples/global-discovery-service-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@josiahvinson The page seems to be good now.
