### ISSUE TITLE
How do I reference an file that is about to be attached in the OnAttach event?

### ISSUE THREAD

**Issue by git-gone** [MicrosoftDocs/powerapps-docs#124]
It would be useful to be able to access the file name of the incoming attachment to check if the file extension is acceptable to the application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e663e437-2bc9-980f-9ba6-6eeab01ee9a4
* Version Independent ID: ae7da14b-2234-2815-9fd1-272a0984f129
* Content: [Attachments control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-attachments)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-attachments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-attachments.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
Thanks for your feedback, @git-gone. For product-related feedback, please visit [the forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.
