### ISSUE TITLE
pie chart

### ISSUE THREAD

**Issue by Nandeep94** [MicrosoftDocs/powerapps-docs#1240]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da79f77c-99a2-2f45-027f-5460b64f6545
* Version Independent ID: af5b7158-a1e1-3f78-2bb4-6b2571452334
* Content: [Create a chart in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/use-line-pie-bar-chart)
* Content Source: [powerapps-docs/maker/canvas-apps/use-line-pie-bar-chart.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/use-line-pie-bar-chart.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by Nandeep94** [comment]
how to add rows  for columns chart

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please add more rows to the table source for the chart.
