### ISSUE TITLE
How make $batch execute continue on errors

### ISSUE THREAD

**Issue by Flex-Xuan** [MicrosoftDocs/powerapps-docs#1241]
Hi there,

How make $batch to execute continue when error occurred? 
for example. 
I want to use $batch to get 2 account and 3 contact  in one request.
so I built the requests in turn. e.g.

_account-1
account-2
contact-1
contact-2
contact-3_

 if all records exists in environment, it works perfect. but if there is one record does not exist, let's say contact-1 does not exist. then I only got 3 response (account-1,account-2 and a "404 not found response" for contact-1)

what I want is to get all responses for the 5 records, how this can be done in WEB API. I know it can be done in Organization Service through [ExecuteMultipleRequest](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.messages.executemultiplerequest?view=dynamics-general-ce-9)  and set [ContinueOnError ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.executemultiplesettings.continueonerror?view=dynamics-general-ce-9#Microsoft_Xrm_Sdk_ExecuteMultipleSettings_ContinueOnError)to true

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af14071e-83a5-8dde-6346-d158b4d5d66a
* Version Independent ID: 8fb0f4fb-17ff-7491-d057-a1edf9242bc8
* Content: [Execute batch operations using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api?view=dynamics-ce-odata-9)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by bthompson-365** [comment]
@Flex-Xuan If you want a quick answer would be better asking your question in the community forums at https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum .

**Comment by Flex-Xuan** [comment]
@bthompson-365  Okay, thank you.

**Comment by Flex-Xuan** [comment]
I found the answer at https://docs.microsoft.com/en-us/odata/webapi/batch 
close this.

**Comment by JimDaly** [comment]
Re-opening this because people should be able to find this information here.

**Comment by phecke** [comment]
@Flex-Xuan Thanks for the feedback. I added a link to the topic that provides more information about continuing on batch errors
