### ISSUE TITLE
Incorrect details on availability

### ISSUE THREAD

**Issue by akaskela** [MicrosoftDocs/powerapps-docs#1242]
The Note section is incorrect. 

The form selector methods (like formContext.ui.formSelector.getCurrentItem() ) do work on the Dynamics 365 App for phone. However, it does not work on quick create forms (Web or Phone) even if there are multiple QC forms. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669dbde5-7411-0527-1187-9a0ba08cba6e
* Version Independent ID: d3445cc2-1963-971a-fa75-c3933935b2e8
* Content: [formContext.ui.FormSelector (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-formselector#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-formSelector.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-formSelector.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@akaskela The formSelector method doesn't work for the Quick create forms. For the Note part, do you mean to say the `formContext.ui.formSelector.getCurrentItem()` is working on phones?

**Comment by akaskela** [comment]
@Nkrb, it was 6 months ago so I don't have my testing environment anymore, but I believe the getCurrentItem() method did work on a main form on Dynamics 365 mobile app for Android.

Could you please update the Note to also include that it doesn't support the Quick Create form?

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
