### ISSUE TITLE
Same code in UCI resulting different ReadableStream body instead of result.responseText JSON like classic web UI

### ISSUE THREAD

**Issue by arunvinoth** [MicrosoftDocs/powerapps-docs#1243]
When Xrm.WebApi.online.execute is used to execute a custom action in classic UI, we used to get result.responseText JSON.

But the same code break in UCI. Because the responseText is no more, instead we are getting ReadableStream body.

Is this expected?

Read more - https://www.thrives.be/dynamics-365-ce/javascript-callback-not-working-after-uci-upgrade/

**Comment by Nkrb** [comment]
@arunvinoth Thanks for  the feedback. Yes, this is expected behavior in UCI.

**Comment by Nkrb** [comment]
@arunvinoth Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
