### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Arghyadeep2412** [MicrosoftDocs/powerapps-docs#1244]
[Enter feedback here]
Please correct the spelling of "offline"
![image](https://user-images.githubusercontent.com/58265542/78977746-4425cd80-7b36-11ea-9171-8519b0df3b18.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736633bc-d0f6-0665-c487-dab6c36a677f
* Version Independent ID: b83eba0e-908d-a1bc-5e81-a642afb9276c
* Content: [updateRecord (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/updaterecord)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/updateRecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/updateRecord.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@Arghyadeep2412 Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
