### ISSUE TITLE
Where to add this JS Code ?

### ISSUE THREAD

**Issue by makarandkeer** [MicrosoftDocs/powerapps-docs#1246]
Can you please give details as where should this JS code added in Dynamics 365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b93a524-63ec-8b9c-cabf-042e38ccf5bd
* Version Independent ID: 5a3b40cc-8c0a-2a25-1ec6-cec49f7f8f69
* Content: [addGlobalNotification (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-app/addglobalnotification?source=docs#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-App/addGlobalNotification.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-App/addGlobalNotification.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bthompson-365** [comment]
Surely it's the same as any other piece of Javascript within Dynamics 365 / Power Apps - within a webresource script triggered on pageload / page save as appropriate. See the client-side events listed in https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference

**Comment by makarandkeer** [comment]
@bthompson I our App, Dashboard is default page and we wanted to show Global Notification when default page is loaded. As far I know we cannot have JS injected on Dashboard page load or for that matter same is the case for views like Account View, Case View etc.

**Comment by bthompson-365** [comment]
If you look at all the images shown they all from an entity detail page

**Comment by Nkrb** [comment]
@makarandkeer Thanks for the feedback. Currently we do not support adding JavaScript actions on Dashboards and charts.

**Comment by bthompson-365** [comment]
In which case could you modify all the examples to use pages on which you can run Javascript.

**Comment by mmcguinness** [comment]
This is great, but how do we send user-specific global notifications (i.e. User A and User B need to globally see their "Working Year", which is different.

**Comment by LinnZawWin** [comment]
@makarandkeer and @mmcguinness 
As a workaround, we can use the Custom Enable Rule of the hidden button in Global Tab to show Global Notification when the default page is loaded no matter if the default page is Dashboard or the entity view.
Please refer to my blog post for more details.
http://linnzawwin.blogspot.com/2020/05/show-global-notification-on-load-of.html

**Comment by Nkrb** [comment]
@bthompson-365 Global notifications will appear in an app everywhere irrespective of where the user is.

**Comment by bthompson-365** [comment]
@Nkrb - but that wasn't my question, the question was how do you initialise a global notification if you are on a dashboard or entity list page where JavaScript is not available except via tricks within a ribbon button.

**Comment by Nkrb** [comment]
@bthompson-365 Global notifications cannot be initialized from Dashboards and entity list pages where you cannot add a JavaScript code to perform actions.

**Comment by Nkrb** [comment]
@mmcguinness @bthompson-365 Thanks for contacting us.  I am closing this issue. If you need further help, please reopen the issue or open a new issue.
