### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by salvoroni** [MicrosoftDocs/powerapps-docs#1247]
In the "SQL User name and password authentication" section. Update OF to OR.
Change:
Your users cannot see the user name of password,

To:
Your users cannot see the user name or password,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df61b9fd-18b0-49c7-03f3-8b97aa67a601
* Version Independent ID: cc848247-8142-08bc-08c7-9ee11b55face
* Content: [Connectors overview for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list#sql-user-name-and-password-authentication)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. The content is being updated.
