### ISSUE TITLE
There is no example and full working details

### ISSUE THREAD

**Issue by mdhruv1** [MicrosoftDocs/powerapps-docs#1248]
Will be great if we can a full details showing step by step. This does not have enough details .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edbd7c88-66b5-0776-251e-49293324b930
* Version Independent ID: 4364fe0e-c13d-afaa-a0b3-1e5803e1d9e8
* Content: [Download, Launch, and Param functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-param#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-param.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-param.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated. Please allow sometime for changes to reflect.
