### ISSUE TITLE
Plug-in registration tool is showing NOT valid messages

### ISSUE THREAD

**Issue by robertoilidio** [MicrosoftDocs/powerapps-docs#1249]
Regarding this statement: "The Plug-in registration tool will filter this information to only show valid messages.". Using Plug-in Registration Tool version 9.0.0.9517 32 bits ( which I guess it is the current latest public version , please correct if I am wrong),  I am not verifying this behavior. The Plug-in registration tool is showing valid and not valid messages. 

For example, PRT is showing message "CreateAttribute", which is not a valid message because there is no valid primaryEntity and we will not be able to register the step, it also can be verified using the web api query suggested in this documentation to confirm that message is not valid, we will not be able to find such message in the results: https://&lt;YourOrg&gt;/api/data/v9.1/sdkmessages?$select=name&$filter=isprivate eq false and (name ne 'SetStateDynamicEntity' and name ne 'RemoveRelated' and name ne 'SetRelated' and name ne 'Execute') and sdkmessageid_sdkmessagefilter/any(s:s/iscustomprocessingstepallowed eq true and s/isvisible eq true)&$expand=sdkmessageid_sdkmessagefilter($select=primaryobjecttypecode;$filter=iscustomprocessingstepallowed eq true and isvisible eq true)&$orderby=name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbf0dbd-40c9-b1a0-3f21-b98c20bc49d7
* Version Independent ID: 9232684b-31ab-a4ba-f48e-3170e38b5beb
* Content: [Event Framework (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/event-framework#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/event-framework.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/event-framework.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@robertoilidio 
Thanks for reporting this.  I can confirm what you see and am following up with the PRT owners to see if this is expected.

**Comment by JimDaly** [comment]
This is a bug in the PRT. Owners of that app are aware of the issue and should fix it soon.
