### ISSUE TITLE
Removing a pinned PowerApp icon from iPhone home screen

### ISSUE THREAD

**Issue by whitelc** [MicrosoftDocs/powerapps-docs#125]
Can you add instructions on how to remove a pinned PowerApp icon from an iPhone home screen. I have an icon for an obsolete PowerApp that I cannot get rid of.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57cd2416-a498-8a28-e2d5-04077a89c73f
* Version Independent ID: 2efc22d7-62c7-754c-a8a7-c9aa0a72a140
* Content: [Run a canvas-based app on a mobile device - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/run-app-client)
* Content Source: [powerapps-docs/user/run-app-client.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/run-app-client.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by mduelae** [comment]
@whitelc You should be able to remove it like any other short cut on your phone.

Closing the issue. Feel free to reopen it if you have further questions.

Thanks,
Mints
