### ISSUE TITLE
Failure of POST requests

### ISSUE THREAD

**Issue by shaurya58** [MicrosoftDocs/powerapps-docs#1250]
I tried the POST request for creating an incident with the following JSON body:

{
        "caseorigincode": "2",
	"casetypecode": "1",
	"createdon": "2020-04-09",
	"customercontacted": true,
	"customersatisfactioncode": "5",
	"description": "test incident",
	"emailaddress": "abc@xyz.com",
	"followupby": "2020-04-10",
	"incidentid": "8aa021b9-c8e3-4138-8d87-e28ce9bd7526",
	"incidentstagecode": "1",
	"prioritycode": "1",
	"processid": "cae3b594-4f4d-411e-8805-5ce212aaf784",
	"primarycontactid@odata.bind": "/contacts(fb2ea09c-117b-ea11-a811-000d3a3e11d7)",
	"customerid_accountcustomerid_contact": "46b7dfb0-207b-ea11-a811-000d3a3e11d7",
	"resolveby": "2020-04-14",
	"statecode": "0",
	"statuscode": "1",
	"ticketnumber": "tckt1",
	"title": "inc-title"	
}

I get the following error which isn't specific for this request only, I've encountered it with other requests also:

{
    "error": {
        "code": "0x0",
        "message": "An error occurred while validating input parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type.
.
.
.
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d869f063-f292-aef8-70fe-e165c65a74bd
* Version Independent ID: ff0b5a9f-b085-9223-3df5-ad5b5f196498
* Content: [Create an entity record using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/create-entity-web-api#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/create-entity-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/create-entity-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by Nkrb** [comment]
@shaurya58 Can you try by not setting the **createdon** and other system values and see if you can run the code.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
