### ISSUE TITLE
Needs updated

### ISSUE THREAD

**Issue by brodiekrause** [MicrosoftDocs/powerapps-docs#1251]
I noticed a property for this control, AutoDisableOnSelect, and came here to read up on it, but this documentation is not current.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42d62420-0871-9ee5-ec03-df09c17dde3e
* Version Independent ID: 4a97f73f-221c-2a74-d70f-b95b8f6d2acd
* Content: [Shape controls and icon controls: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-shapes-icons#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-shapes-icons.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-shapes-icons.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This is documented in all properties section - https://docs.microsoft.com/powerapps/maker/canvas-apps/reference-properties#all-properties.
