### ISSUE TITLE
Error on hreference link

### ISSUE THREAD

**Issue by danielftk** [MicrosoftDocs/powerapps-docs#1253]
on the Quick form control Methods table the "getcontrol" and "getcontroltype" has the same hreference link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba409176-ddca-d985-291a-35782fa66e21
* Version Independent ID: c3719607-83fc-78cf-559e-ab2eb09b2ce7
* Content: [formContext.ui.quickForms (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-quickforms)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-quickForms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-quickForms.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by danielftk** [comment]
![image](https://user-images.githubusercontent.com/3487413/79241001-12fc1480-7e38-11ea-863c-ac3be58e300f.png)

**Comment by Nkrb** [comment]
@danielftk Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
