### ISSUE TITLE
telemetry?

### ISSUE THREAD

**Issue by nik-gloy** [MicrosoftDocs/powerapps-docs#1257]
What does the telemetry function do? I can see that I can enable and disable it, but what effect does it have? When/where is telemetry collected, and where is it being sent to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46d11001-a078-60f0-19d9-357f9397c7a7
* Version Independent ID: 395e7245-8c1d-d168-ee6e-cc18b79bd789
* Content: [Install Power Apps CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/powerapps-cli?source=docs#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/powerapps-cli.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@nik-gloy If you enable telemetry option, it allows you to send logs and error information to Microsoft to help improve the product. If choose to disable telemetry, then you won't send any information to Microsoft. Status tells you whether you have enabled or disabled the telemetry.

**Comment by Nkrb** [comment]
@nik-gloy Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
