### ISSUE TITLE
Default case since `arg` is optional

### ISSUE THREAD

**Issue by imranakram** [MicrosoftDocs/powerapps-docs#1258]
What happens when `arg` is not provided in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e183d1-17d6-0879-f8bd-eda1cadfebbf
* Version Independent ID: 2b99142b-a211-fe10-e16d-e68c818fe45f
* Content: [getControl (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getcontrol)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getControl.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getControl.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@imranakram When you don't pass any value to the formContext.getControl(), it returns an array of all controls in the form.

**Comment by imranakram** [comment]
@Nkrb The point was that the documentation is not provided for the default behavior

**Comment by Nkrb** [comment]
@imranakram Sure, will add it to the documentation. Thanks for the feedback. Closing the issue.
