### ISSUE TITLE
Set-FlowDefaultEnvironment -EnvironmentID and SetPowerAppsDefaultEnvironment -EnvironmentID

### ISSUE THREAD

**Issue by firooztnt** [MicrosoftDocs/powerapps-docs#126]
As Admins, we are unable to change the default Flow or PowerApps environments. This is a big show stopper because we don't want users to create resources in the production environment by default. It's pretty much useless now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell#installation)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jamesol-msft** [comment]
Sorry can you clarify your scenario?  Which cmdlets are you referring to?

**Comment by AFTOwen** [comment]
@jamesol-msft Any updates?

cc: @jimholtz

**Comment by jimholtz** [comment]
@firooztnt 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Please reopen if this issue still exists.
