### ISSUE TITLE
img node in ControlManifest.Input.xml cause PCF component fail to import to PowerApps

### ISSUE THREAD

**Issue by alexchx** [MicrosoftDocs/powerapps-docs#1262]
We added few img tags in ControlManifest.Input.xml in our PCF component, but after that, the component fail to import to PowerApps, this is the error message in the JSON response `Sequence contains no matching element`.

The img tags are added in this way.
```xml
    <resources>
      <code path="index.ts" order="1"/>
      <css path="IntlTelInputLib/css/intlTelInput.css" order="2" />
      <css path="css/IntlTelInputComponent.css" order="3" />
      <img path="IntlTelInputLib/img/flags.png" />
      <img path="IntlTelInputLib/img/flags2x.png" />
    </resources>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177968b6-1cef-9f9a-10f1-f64fb9de160a
* Version Independent ID: d4675c4a-3c1c-83c4-1ec6-ba482244ae72
* Content: [Image Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/img#feedback)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/img.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/img.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@alexchx Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
