### ISSUE TITLE
Valid file path shouldn't be restricted in resources

### ISSUE THREAD

**Issue by alexchx** [MicrosoftDocs/powerapps-docs#1263]
Some valid file paths are restricted in PCF component because of the error below, but characters @-
_ might occur in third-party packages, with this limitation we'll have to create duplicate file copies with different file path/name or using CDN path which appears unreasonable, so is that possible to accept all characters valid in a file path?

> CustomControl with name XXXXXX.YYYYYYYYYY failed to import with error: Web resource names may only include letters, numbers, periods, and nonconsecutive forward slash characters.

An example which will repro the error above.
```xml
    <resources>
      <code path="index.ts" order="1"/>
      <css path="../node_modules/intl-tel-input/build/css/intlTelInput.css" order="2" />
      <css path="css/IntlTelInputComponent.css" order="3" />
      <img path="../node_modules/intl-tel-input/build/img/flags.png" />
      <img path="../node_modules/intl-tel-input/build/img/flags@2x.png" />
    </resources>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177968b6-1cef-9f9a-10f1-f64fb9de160a
* Version Independent ID: d4675c4a-3c1c-83c4-1ec6-ba482244ae72
* Content: [Image Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/img#feedback)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/img.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/img.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@alexchx Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
