### ISSUE TITLE
Register an external .js file (not .ts file) in “ControlManifest.Input.xml”

### ISSUE THREAD

**Issue by alexchx** [MicrosoftDocs/powerapps-docs#1264]
Is that possible to register an external .js file (not .ts file) in “ControlManifest.Input.xml”? In some scenarios, we might need to load a .JS file separately (e.g. third-party libraries like code snippet below), but the [code](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/code) config accepts .ts file only, any advice?

```javascript
window.intlTelInput(input, {
  utilsScript: "build/js/utils.js",
});
```
Also the example in the [documentation ](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/code#example) doesn't work.
```xml
<code path="TS_IncrementControl.js" order="1" />
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177968b6-1cef-9f9a-10f1-f64fb9de160a
* Version Independent ID: d4675c4a-3c1c-83c4-1ec6-ba482244ae72
* Content: [Image Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/img#feedback)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/img.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/img.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by bthompson-365** [comment]
This would be a question better asked on the power platform forum at https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/bd-p/pa_component_framework

The quick answer is that the content manifest only documents what files should be included in the component as a whole when it is deployed. For a Javascript script / library to be included within the bundle.js file you need to import it within the index.ts file and then call it from there.

Looking at the code my advice would be to look at a variation such as the Angular version at https://www.npmjs.com/package/ng2-tel-input and follow the advice on there.

**Comment by Nkrb** [comment]
Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
