### ISSUE TITLE
Entity record cannot opened in a dialog?

### ISSUE THREAD

**Issue by luoyong0201** [MicrosoftDocs/powerapps-docs#1265]
The documents says it can be opened in a dialog, but I tried, it opened inline. why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bthompson-365** [comment]
I blogged about this yesterday - you may find https://www.processpower.dev/opening-entity-records-with-xrm-navigation-navigateto/ helpful.

By the sounds of it you need to ensure that your navigationOptions object is vaild. Something like {target:2, width:{value:500, unit:"px"}} should work

**Comment by KumarVivek** [comment]
@luoyong0201 It works fine as documented. For example, I used example 3, and it open a blank form in a dialog:

![image](https://user-images.githubusercontent.com/1670116/80163946-86b2c580-858c-11ea-86b1-7a3d52967f66.png)

If you are using example 2, make sure you replace the ID in the **entityId** parameter as per your environement:

`entityId: "5a57f2c3-5672-ea11-a812-000d3a339706" //replace with actual ID `

Closing the issue.

**Comment by TuomasNummelin** [comment]
I just encountered this same behaviour, it seems to open inline only if the environment is still running the 2019 release wave 2. In other environment with 2020 release wave 1, opening in dialog worked as documented.
