### ISSUE TITLE
Editing and publishing a canvas app in managed solution

### ISSUE THREAD

**Issue by rohannevrikar** [MicrosoftDocs/powerapps-docs#1266]
According to the documentation's (link below) limitations, "If a canvas app is packaged in a managed solution, it can't be edited and re-published in the target environment. Use unmanaged solutions if the apps require editing in the target environment".
I have imported a managed solution in my target environment. I can see that edit button is disabled in this screen.
![image](https://user-images.githubusercontent.com/26645175/79444945-7da87e00-7ff9-11ea-8c57-549072af97b0.png)

But I can edit the same canvas app if I click on the app and go to next screen:
![image](https://user-images.githubusercontent.com/26645175/79445058-a6c90e80-7ff9-11ea-8bd2-71c3f56cec26.png)

I can make changes and re-publish the app. Changes are done and saved successfully. 
This same behavior is seen with flow too. I guess any edits turns it into an unmanaged customization, and I can maintain or overwrite any unmanaged customization during me next import of the same solution. 
But again, the docs say that it cannot be edited and re-published. Am I missing something here? If it cannot be edited, then why is edit button disabled in the first screen but enabled on the next one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6262cac-ae0b-3729-2a9e-0e7ab11d6934
* Version Independent ID: 57c92838-bc87-cbb1-481c-d00df8077bfb
* Content: [Use solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/use-solution-explorer#known-limitations)
* Content Source: [powerapps-docs/maker/common-data-service/use-solution-explorer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/use-solution-explorer.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by rohannevrikar** [comment]
Update: Seems like this is the knowledge that I was missing: 

1. Owners of resources can edit flow and powerapps in managed solution.
2. If a user has access to the environment but that user is not an owner of resources of a solution, then the user can edit flow, but not PowerApps. 

Can someone please confirm if I got this right? Also, some of the limitations are working for me. For example: I'm able to use sharepoint connectors in flow which is created in solution, I'm able to use canvas app button triggered flow in an unmanaged solution. However it throws error at runtime in case of managed solution. Maybe the document and release notes isn't up to date, or again am I missing something here?

**Comment by Mattp123** [comment]
@rohannevrikar - Yes the two limitations you mentioned that previously weren't supported now are. The article has been updated to reflect that. 

Closing issue.
