### ISSUE TITLE
Incorrect information about gateways and environments

### ISSUE THREAD

**Issue by willdrobins** [MicrosoftDocs/powerapps-docs#1267]
This was changed in late Oct. 2019.  "Gateways and on-premises connections can only be created and used in the user's default environment."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042aa853-3571-5081-a83b-25235a4949fa
* Version Independent ID: d4049a41-6d7e-0ebd-8c17-68223a8e327b
* Content: [Manage an on-premises data gateway for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-management)
* Content Source: [powerapps-docs/maker/canvas-apps/gateway-management.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/gateway-management.md)
* Service: **powerapps**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content has been updated; please allow some time to reflect the changes.
