### ISSUE TITLE
 PowerApps Portals admin center accesible without having access on Auzre AD App

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/powerapps-docs#1268]
Please see the steps below to reproduce the issue, so not sure if this is an issue or need to change the documentation.

1) Created a new environment "Env-1" for Power Apps Portal using ID XYZ
2) Tried to create Power Apps Portal with ID XYZ, but failed as XYZ does not have rights for App Registration on Azure AD
3) Created the Power Apps Portal on "Env-1" using my Global Tenant Admin ID ABC
4)Power Apps Portal created successfully, though it is showing owner as XYZ only for that.
5)Login with XYZ and able to access PowerApps Portals Admin center without performing any other steps.

Cheers,
Dhawal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c33206-a8f7-cce4-d663-894874c0ae98
* Version Independent ID: 72de507b-3eec-6433-1c0a-462b98ef1a91
* Content: [Overview of Power Apps Portals admin center - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/admin-overview)
* Content Source: [powerapps-docs/maker/portals/admin/admin-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/admin-overview.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can resubmit the failed provisioning as an owner, as explained in [this](https://docs.microsoft.com/powerapps/maker/portals/admin/admin-overview#add-yourself-as-an-owner-of-the-azure-ad-application) article.

**Comment by dhawal16** [comment]
Hello Tapan,

Not sure why this has been closed without confirming with me.

Can i request you to please read the issue i have mentioned again. It did not failed for me but issue is something as mentioned below. I am mentioning the steps again here.

Please see the steps below to reproduce the issue, so not sure if this is an issue or need to change the documentation.

Created a new environment "Env-1" for Power Apps Portal using ID XYZ
Tried to create Power Apps Portal with ID XYZ, but failed as XYZ does not have rights for App Registration on Azure AD
Created the Power Apps Portal on "Env-1" using my Global Tenant Admin ID ABC
4)Power Apps Portal created successfully, though it is showing owner as XYZ only for that.
5)Login with XYZ and able to access PowerApps Portals Admin center without performing any other steps.

Cheers,
Dhawal

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out again. When a user has no access for Azure App Registration, the portal creation shows [an error](https://docs.microsoft.com/powerapps/maker/portals/faq#im-getting-an-error-that-i-dont-have-required-permissions-to-create-azure-active-directory-applications). Please reach out with a [support service request](https://admin.powerplatform.microsoft.com/support) to investigate issue with your environment.
