### ISSUE TITLE
HelpDesk Tickets - unable to see tickets created ( Help Desk Sample )

### ISSUE THREAD

**Issue by GPZAR** [MicrosoftDocs/powerapps-docs#127]
Hi 

I'm unable to see the tickets I created, on my ticket screen what could causes this?

**Comment by AFTOwen** [comment]
Closing as duplicate of [this forum post](https://powerusers.microsoft.com/t5/General-Discussion/HelpDesk-Tickets-unable-to-see-tickets-created-Help-Desk-Sample/m-p/183040).
