### ISSUE TITLE
Overloading of the "context variable" term in Power Apps

### ISSUE THREAD

**Issue by ghurlman** [MicrosoftDocs/powerapps-docs#1270]
In the section labeled ["Use context from Teams"](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-teams-app#use-context-from-teams), there are references to a term "context variables" but then refers to incoming parameters from Teams, even showing using the Params() function to retrieve the values.

In Power Apps, "context variables" already refers to screen-local variables, and calling these incoming params the same thing will lead to maker confusion.

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0367a42-3b99-3362-2ea7-1a821d66d4eb
* Version Independent ID: 5bda16c0-b231-29f6-9da1-766ddd72b374
* Content: [Embed an app in Teams - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-teams-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-teams-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/embed-teams-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The context in this reference used is the 'Teams context' for clarity.
