### ISSUE TITLE
Error en el flujo

### ISSUE THREAD

**Issue by jgarciacam1** [MicrosoftDocs/powerapps-docs#1271]
Send_an_HTTP_request_to_SharePoint_Logo_Library
Detalles del error: BadGateway

**Comment by phecke** [comment]
@jgarciacam1 This GitHub repo is for issues related to the product documentation. If there is an issue with the documentation for a product feature that you are using, please provide the related documentation link so that I can assign the issue to a appropriate writer.

**Comment by KumarVivek** [comment]
Closing the issue.
