### ISSUE TITLE
How about environments and solutions?

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/powerapps-docs#1272]
Any info on adding Components to an unmanaged solution and then moving the solution as a managed solution to another environment?

I have created two environments:
**Environment A** has two unmanaged solutions: 
Solution 1 containing a Component Library.
Solution 2 containing a Power App using a component from the Component Library in Solution 1.
In this environment everything behaves as expected.
**Environment B** has managed versions of these solutions.
When updating the Component Library in the Unmanaged Solution of Environment A, the Power App in Environment B alerts me about an update. Is the Power App in Environment B linked to the Component library in Environment A or Environment B??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93230c47-e5a5-15ad-9320-2f9671fdebb5
* Version Independent ID: dc5050e4-7243-b861-4c97-3bfb0165ade5
* Content: [Create a component for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-component#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/create-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-component.md)
* Service: **powerapps**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The app in environment B has a dependency on the component library in environment B. With respect to canvas apps and component libraries, there can't be dependencies across environments. For any issues, please reach out to our support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) to help you with the investigation.
