### ISSUE TITLE
Missing PowerShell Step

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#1273]
Hi
I cannot find instructions for the step Create JSON File with Test URLs - have I missed something ?
Regards
Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 513096fe-dce9-70cc-4891-13ffdf2447ca
* Version Independent ID: 29cdb9ce-32e4-2cc5-522b-76587872d8ab
* Content: [Automate tests with Azure Pipeline using classic editor - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/test-studio-classic-pipeline-editor#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/test-studio-classic-pipeline-editor.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/test-studio-classic-pipeline-editor.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **aheaney**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please see the prerequisites, and particularly the [step 2](https://docs.microsoft.com/powerapps/maker/canvas-apps/test-studio-classic-pipeline-editor#step-2---create-test-url-json-file).

**Comment by NPrice99** [comment]
Hi step 2 you reference us not a powershell script.  How do I include the powershell script ?

**Comment by tapanm-MSFT** [comment]
PowerShell script related step is [here](https://docs.microsoft.com/powerapps/maker/canvas-apps/test-studio-classic-pipeline-editor#step-1---configure-screen-resolution-using-powershell).

**Comment by NPrice99** [comment]
If you look at the screenshots there is a PowerShell script called “create Json file with...”

It is not documented in the list of instructions.  So either the screenshots are wrong or the instructions are wrong.

Regards

Nigel

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aengusheaney** [comment]
Thanks Nigel for spotting the mistake. The “create Json file with...” is not required and i will update the screenshots asap to remove the confusion.

thanks!
Aengus

**Comment by NPrice99** [comment]
- Thanks Aengus
