### ISSUE TITLE
Invoke SELECT with button control EXPORT

### ISSUE THREAD

**Issue by joseabadg** [MicrosoftDocs/powerapps-docs#1274]
When invoke SELECT button control EXPORT the windows for save doesnt appear at all, its suppossed that all controls have hadlers ONSELECT can support all functionalities.

**Comment by phecke** [comment]
@joseabadg This GitHub repo is for issues related to the product documentation. If there is an issue with the documentation for a product feature that you are using, please provide the related documentation link so that I can assign the issue to a appropriate writer.

**Comment by joseabadg** [comment]
> @joseabadg This GitHub repo is for issues related to the product documentation. If there is an issue with the documentation for a product feature that you are using, please provide the related documentation link so that I can assign the issue to a appropriate writer.

there it is: [](https://docs.microsoft.com/es-es/powerapps/maker/canvas-apps/functions/function-select )   thank you

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The export control is not supported in a [web browser](https://docs.microsoft.com/powerapps/maker/canvas-apps/controls/control-export-import#limitations). You can try using mobile device. If the issue persists, please reach out with a [support service request](https://admin.powerplatform.microsoft.com/support) for issue investigation by support teams and help you fix the problem.
