### ISSUE TITLE
Size cannot be changed?

### ISSUE THREAD

**Issue by charrington2** [MicrosoftDocs/powerapps-docs#1275]
Hi, changing size (step 3) is not available, even though I am using a tablet App. I don't see custom. Is the doc outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43398b6a-6bc2-0f39-f78b-59f9997d77a6
* Version Independent ID: 138f2ed6-bb71-eccc-8446-22262ecba72c
* Content: [Change screen size and orientation of a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/set-aspect-ratio-portrait-landscape#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/set-aspect-ratio-portrait-landscape.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/set-aspect-ratio-portrait-landscape.md)
* Service: **powerapps**
* GitHub Login: @evchaki
* Microsoft Alias: **evchaki**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content is current but also recently updated to reflect updates in the UI. If the issue persists, please feel free to reach out with a [support service request](https://docs.microsoft.com/power-platform/admin/get-help-support) for deeper investigation.
