### ISSUE TITLE
Don't see any specific value at current implementation

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/powerapps-docs#1276]
The reason we use Environment specific values is that application should automatically detect the current environment and take the appropriate values. If these are just configuration values which in general all developers use, I don't see any value addon

I Suggest since multiple values are possible for a variable ; A Environment record (OrgName) should be created and against it the values should be created and once deployed the values should be read from destination orgname. This way it removes the overhead of verifying the values in each environment post deployment .

for eg :  
Orgurl -&gt; 
devorg: https://devorg.crm.dynamics.com
sitorg : https://sitorg.crm.dynamics.com
prodorg: https://prodorg.crm.dynamics.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad70fa7e-a9df-e2c0-4482-a140ca1c4b4f
* Version Independent ID: 8071aca4-f51a-a53e-0e04-c2a64164eb32
* Content: [Preview: Use environment variables in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/environmentvariables)
* Content Source: [powerapps-docs/maker/common-data-service/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/EnvironmentVariables.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@pavansarma93 - Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
