### ISSUE TITLE
Number of docs shown in the SharePoint

### ISSUE THREAD

**Issue by sohailrazarizvi** [MicrosoftDocs/powerapps-docs#1277]
Hi,
Why only document is shown in the subgrid. 

Under Portal Management Model-Driven App --&gt; Entity --&gt; Form --&gt; Subgrid configuration; it is set 4 documents but in portal it is only shown one document

Please advise

admin@bhmconsultings.com.au

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd70bb46-8651-365b-7a25-215b921f55b6
* Version Independent ID: f628a69a-04c8-901a-832f-b867aff68603
* Content: [Manage SharePoint documents on a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/manage-sharepoint-documents#feedback)
* Content Source: [powerapps-docs/maker/portals/manage-sharepoint-documents.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/manage-sharepoint-documents.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Please reach out using a [support channel](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with investigating your issue.
