### ISSUE TITLE
Power Apps Data Integrations doesn't exist

### ISSUE THREAD

**Issue by DennisGaida** [MicrosoftDocs/powerapps-docs#1278]
"**Specifiy the data source**

- Step 2. is wrong. You can't tap on "Data Integrations" since it doesn't exist. You need to tap on **Entities > Get Data**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e6f1eb-1ed8-c4f0-6a8f-3e252e65f499
* Version Independent ID: 82b18731-40b0-bc10-6d7c-9ebe5c07b726
* Content: [Add data to an entity in Common Data Service by using Power Query - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-cds-newentity-pq)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-cds-newentity-pq.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-cds-newentity-pq.md)
* Service: **powerapps**
* GitHub Login: @mllopis
* Microsoft Alias: **millopis**

**Comment by iangpgh** [comment]
@DennisGaida Thanks for reporting this. This issue is now corrected.
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-cds-newentity-pq

**Comment by iangpgh** [comment]
resolved
@Mattp123 - Closes #1278
