### ISSUE TITLE
Common Data Service Odata calls taking 20-30 seconds on first call

### ISSUE THREAD

**Issue by SainiAshish** [MicrosoftDocs/powerapps-docs#128]
We are making odata calls using S2S authentication and it is taking 20-30 seconds sometimes more on first call. After that it takes 1-2 seconds or less.

Why is it taking time on first call and how we can improve this?

**Comment by KumarVivek** [comment]
Can you please post this question on the Common Data Service for Apps forum: https://powerusers.microsoft.com/t5/Common-Data-Services/ct-p/PA_CommonDataServices

Closing the issue.
