### ISSUE TITLE
Html WebResource in form, is reloades randomly when ejecute Xrm.Navigation.navigateTo

### ISSUE THREAD

**Issue by dga205** [MicrosoftDocs/powerapps-docs#1282]
Hi.
I have this problem.

I have a Html WebResource in an entity form.
It has a button, that execute Xrm.Navigation.navigateTo to open another html webresource in a modal.

var datos = {
                ClientId: 123,
                ProductId: 123
            };

            var jsonString = JSON.stringify(datos);
            var pageInput = {
                pageType: "webresource",
                webresourceName: "axx_/Html/SelectorCuentasBancarias/CuentasBancarias.html",
                data: jsonString
            };
            var navigationOptions = {
                target: 2,
                width: { value: 80, unit: "%" },
                height: { value: 80, unit: "%" },
                position: 1
            };

            Xrm.Navigation.navigateTo(pageInput, navigationOptions).then(
                function success() {
                    console.log("ok");
                },
                function error() {
                    console.log("err");
                }
            );

This work Ok, but, randomly, the WebResource in the Form is reloades, without the parameters thar de form pass to the webresouce, such as id, i don´t know why

**Comment by Nkrb** [comment]
@dga205 Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit https://powerapps.microsoft.com/support/. Closing the issue.
