### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by APDKarl** [MicrosoftDocs/powerapps-docs#1285]
"Result" was not a choice in the Parent drop down so I chose ID - Didn't work. I have a feeling it is something to do with my simple data being in the one Sharepoint List. It would be great if there was a link that elaborated more on the second paragraph on this page about why two seperate sets of data is better. All I am trying to do is have the user select their name from a dropdown and for the app to populate their supervisors name from that row of data. (It still needs to be editable though as sometimes Supervisors can be away).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. There are 2 benefits of the documented approach - (1) If you take this approach, you can use the same parent and child data in more than one app, (2) and you can update that data without republishing the app or apps that use them. However, if you have any issues, please reach out with a [support service request](https://powerapps.microsoft.com/support/pro/) for detailed investigation.
