### ISSUE TITLE
Working but not saving Child data

### ISSUE THREAD

**Issue by DuckySpud** [MicrosoftDocs/powerapps-docs#1288]
I have a "Locations" list which has columns for "Building" and "Room".  I then have another list where this data needs to be added.

I followed this guide and the tips in the previous closed questions and thought I had this working, the options in the drop downs seem to filter as they should and there are no errors on PowerApps.

However, after saving the new list item, the "All Items" view of the list does not display the correct information.  It shows the selected building in both the Building and Room columns.  If I open the list item, it still displays the Building correctly, and the Room changes to a room, but it is just the first room in the list, not the one which was selected when the item was created.

Can anybody help out with getting it to correctly save the "child" drop down selection please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please raise a [support service request](https://powerapps.microsoft.com/support/pro/) to investigate the issue in detail.
