### ISSUE TITLE
This method doesn't seem to work when the control is in another tab on the form...

### ISSUE THREAD

**Issue by Oztrea** [MicrosoftDocs/powerapps-docs#1289]
I never enter in the then callback function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4c796e-ad9f-1929-f530-f088462522f9
* Version Independent ID: 40e67735-ac26-30a4-3191-0a86fd7b4b50
* Content: [getContentWindow (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getcontentwindow#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by MaTeMaTuK** [comment]
I updated CRM to 2020 wave 1 and It works for me.

**Comment by Nkrb** [comment]
@MaTeMaTuK Thanks for the update. Closing the issue.
