### ISSUE TITLE
MicrosoftTranslator.Translate(Source.Text, TargetLang.Selected.Value) doesn't work, what works is MicrosoftTranslator.Translate(Source.Text, TargetLang.Selected.Code)

### ISSUE THREAD

**Issue by JoshuaOkafor** [MicrosoftDocs/powerapps-docs#1290]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470d67f4-13bc-a313-b03b-1c5c0976a2f2
* Version Independent ID: b49ad3de-6331-c439-b28a-ebe0f83523dd
* Content: [Overview of the Microsoft Translator connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-microsoft-translator)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-microsoft-translator.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-microsoft-translator.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Only target language, and text are required - please see [connector documentation](https://docs.microsoft.com/connectors/translatorv2/#translate-text) for more information. If you need any further help, please feel free to reach out using [Help+Support](https://docs.microsoft.com/power-platform/admin/get-help-support).
