### ISSUE TITLE
Example of Patch or Collect inside a ForAll function not available.

### ISSUE THREAD

**Issue by jdearaujo** [MicrosoftDocs/powerapps-docs#1292]
At the time of writing, I see no example of using Patch or Collect with the ForAll function. It is mentioned very early in the page with no guidance as to how it will behave inside the ForAll formula section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cec09a3-057a-a581-fdb8-50d8039d5643
* Version Independent ID: 9e7aea5b-8f87-cfb9-709a-dd1ae409ab40
* Content: [ForAll function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-forall)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-forall.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-forall.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
There is an example at the end of the article titled [Collect within ForAll](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-forall#collect-within-forall).

We have some enhancements coming soon that will make it easier to reference the entire record at a time.  When they arrive we'll add some more examples.
