### ISSUE TITLE
Flow isnt working for Helpdesk

### ISSUE THREAD

**Issue by j0hnnyma** [MicrosoftDocs/powerapps-docs#1294]
When i load the flow in there is a 
ID eq get items_filter under the get items in sharepoint step and it seems to need an odata filter query in order to be run ? 

i got the app to work and it loads the issues into the sharepoint list. 

just not getting any emails for new cases because of the flow
can someone help ? thanks

**Comment by j0hnnyma** [comment]
![flow (1)](https://user-images.githubusercontent.com/64175872/80046693-2f472380-84c0-11ea-9373-e63ff2077571.PNG)

**Comment by tapanm-MSFT** [comment]
@j0hnnyma can you please share the link for the content page that this feedback is for?

**Comment by j0hnnyma** [comment]
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install

**Comment by j0hnnyma** [comment]
I see the sharepoint list i created logging the issues. The case not started email doesnt send due to the flow being broken.

**Comment by j0hnnyma** [comment]
any insights to this? the powerapp is supposed to work without much configuration. should be import and slight changes but flow isnt working for me.  when i try to run the flow it prompts me to input the get_item filter query.

**Comment by j0hnnyma** [comment]
please update template it doesnt work. 
Had to replace the update button in the app with the following code:


original

SubmitForm(EditTicketForm);HelpDeskFlow.Run("'" & SelectedTicket.ID & "'"); ResetForm(EditTicketForm); Navigate(MyTicketsScreen,None)



revised:



SubmitForm(EditTicketForm);HelpDeskFlow.Run(SelectedTicket.ID); ResetForm(EditTicketForm); Navigate(MyTicketsScreen,None)

**Comment by rttombs** [comment]
@j0hnnyma I am still getting the Odata error even after using the revised. Any ideas? 
![image](https://user-images.githubusercontent.com/70494165/101413200-b2bf5480-3898-11eb-91d4-05f245dda35c.png)

**Comment by tapanm-MSFT** [comment]
Please reach out to the support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) to help investigate and fix this issue.
