### ISSUE TITLE
fetchxml Documentation Location

### ISSUE THREAD

**Issue by nhayduk** [MicrosoftDocs/powerapps-docs#1295]
Great to see that the fetchxml tag is documented, but wouldn't it make more sense to put it on the Common Data Service entity tags page (https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/portals-entity-tags)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0220f6a2-1624-e4fa-3ae9-783bc33125c8
* Version Independent ID: 062d3f8e-b586-9840-ca4f-91697b7da89b
* Content: [Use template tags for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/template-tags)
* Content Source: [powerapps-docs/maker/portals/liquid/template-tags.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/liquid/template-tags.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This article documents template tags and Common Data Service entity tags are also linked in the *See also* section.
