### ISSUE TITLE
addOnSave not working as expected

### ISSUE THREAD

**Issue by dipushrestha** [MicrosoftDocs/powerapps-docs#1298]
Description for addOnSave function states that:
Adds a function to be called when the record is saved. However, from my experience it seems that function added to addOnSave is invoked before record is saved on save event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d248d63-09eb-6744-cb2c-89f147521d3f
* Version Independent ID: 3cfe5c12-0b4e-aceb-4b47-e16008a91476
* Content: [addOnSave (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-entity/addonsave)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/addOnSave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/addOnSave.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@dipushrestha Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
