### ISSUE TITLE
Format Markers

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#130]
Needs info on how to format Markers (eg.  ,"[$-en-US]$ #,###")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e0b8b-2685-cb5c-2165-25d6eef14bdc
* Version Independent ID: e4398f0d-f1fa-4110-b032-24c53f142d14
* Content: [Column chart control and Line chart control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-column-line-chart)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-column-line-chart.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-column-line-chart.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
Thanks for your feedback, @akmiecik. For product-related feedback, please visit [the forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.
