### ISSUE TITLE
More Clarification on Limitations

### ISSUE THREAD

**Issue by drinklikachamp** [MicrosoftDocs/powerapps-docs#1300]
The following statement is too general and thus misleading: "Flows that connect to SharePoint are not available in solutions." This no longer seems to be the case except for the trigger "SharePoint - For A Selected Item". I have verified that you can import flows with SharePoint triggers created outside of solutions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6262cac-ae0b-3729-2a9e-0e7ab11d6934
* Version Independent ID: 57c92838-bc87-cbb1-481c-d00df8077bfb
* Content: [Use solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/use-solution-explorer#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/use-solution-explorer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/use-solution-explorer.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@drinklikachamp - Yes flows that connect to SharePoint are supported with solutions. The article has been updated to remove the former limitation.

Closing issue.
