### ISSUE TITLE
All Connectors link on this page should point to a different page

### ISSUE THREAD

**Issue by TashasEv** [MicrosoftDocs/powerapps-docs#1301]
Hi there - I found this recently updated beautiful page (https://docs.microsoft.com/en-us/connectors/connector-reference/ ) and I think this updated page best represents what a docs user would expect to see if they clicked on the "All Connectors" link above.
Right now the link takes you to the Connector documentation home.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df61b9fd-18b0-49c7-03f3-8b97aa67a601
* Version Independent ID: cc848247-8142-08bc-08c7-9ee11b55face
* Content: [Connectors overview for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. The content is being updated.
