### ISSUE TITLE
Another example for countdown using Timer.Duration

### ISSUE THREAD

**Issue by eflamm** [MicrosoftDocs/powerapps-docs#1302]
It might be appropriate to include/replace the Countdown example with 
[code]Text(Time(0, 0, (Timer1.Duration-Timer1.Value)/1000), "hh:mm:ss")[/code]
since it makes use of the Duration property rather than the "magic number" 10 in the example provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11a9f1d-da5c-f25b-2b48-eddc4c4a6cc5
* Version Independent ID: 1c0f1c98-8bf0-320d-74e8-434e816a4222
* Content: [Timer control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-timer)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-timer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-timer.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The examples are starter and easy to use. Once understood, can certainly be manipulated and used with additional functions. In given example, the formula with Duration value ends up counting from 10 to lower, giving an easy to use and visualize example. Will certainly consider for additions in future content updates.
