### ISSUE TITLE
Microsoft Teams Connector limitation: Out of call volume quota

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/powerapps-docs#1304]
Great work guys: it would be wise to mention the Microsoft Teams Connector limitation?
It only allows 100 calls in 60 secs so if the communication method is Teams for new News Posts --&gt; the flow will fail with: Out of call volume quota. Quota will be replenished in 00:40:11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The latest information about connector specific limitations can be found directly in connector documentation.

**Comment by JuFigueiredo** [comment]
Hey guys, I need some help.

How can I do if I have 2000 items to send through teams connectors? I'm using the 'Create a chat' and 'Post card in a chat or a channel' connectors.
I just created a logic to send 100 items, wait 60s and then send another 100 items but it doesn't work.
