### ISSUE TITLE
 Examples result may be wrong, please check.

### ISSUE THREAD

**Issue by Min-Rao** [MicrosoftDocs/powerapps-docs#1307]
In docs, following example's result is indicate as "1"
 IfError( 1/0, Notify( "There was an internal problem", NotificationType.Error ) )
but when I try following in onselect of button , it prompt up "0" to me.
 Notify(Text(IfError(1/0, Notify("test", NotificationType.Error))), NotificationType.Error)
which means result of the above example should be 0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e0983e-5863-d1eb-43e5-e6e9546c4e2b
* Version Independent ID: cc7abb21-14fd-04de-e1bd-2605697adcd3
* Content: [IfError function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-iferror#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-iferror.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-iferror.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
In order for this to work properly, you need to turn on the experimental feature **Formula-level error management** under the File menu, Settings, Advanced settings:

![image](https://user-images.githubusercontent.com/15149773/80891294-f2292100-8c77-11ea-9a64-b1e043d97dc2.png)

We will be turning this feature on by default soon.

![image](https://user-images.githubusercontent.com/15149773/80891316-1553d080-8c78-11ea-99b4-77dc8489a70f.png)
