### ISSUE TITLE
Release Notes Lagging and Lacking

### ISSUE THREAD

**Issue by wjhepworth** [MicrosoftDocs/powerapps-docs#131]
PowerApps team.  Any chance you all can standardize how you are release notes on updates?  From a configuration management point of view PowerApps is becoming high risk and new features are slip streamed right into the code base with no discernible way for us to know we need to test.  Back in the spring you all were doing great but since then it is hard to figure out where the release notes are.. here?  blog?  where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f986a43-d702-b23e-70c2-e1b0a01ff040
* Version Independent ID: d6c9ac62-83b1-17e1-65eb-c2cefa45a71a
* Content: [What's new - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/release-notes#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/release-notes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/release-notes.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Thanks, @wjhepworth for your feedback! @shpareek, can you please provide a status here?

**Comment by shpareek** [comment]
Thanks @AFTOwen  for looping me. @wjhepworth thanks for raising your very valid concern. Over the last few weeks our team has been working hard to come up with a Weekly Release Notes process that will summarize the latest fixes and enhancements we've rolling out for the product. In the next 2 weeks we're looking at rolling out the weekly release notes, along with some backfilled notes as well. Please stay tuned. (Tagging @evchaki @stepsic-microsoft-com for viz)

**Comment by AFTOwen** [comment]
@wjhepworth You can find a link in this topic to the [weekly release summaries](https://aka.ms/PAWeeklyReleaseNotes). Cheers!

cc: @shpareek

**Comment by GiantCrocodile** [comment]
I just clicked on the weekly release summaries you did mention and there's zero information provided @AFTOwen, @shpareek. I followed the link to the changelog in the Android app store description for Power Apps and I think this doesn't help me at all. I clicked on several versions and none of them were maintained regarding new features or solved issues.

**Comment by evchaki** [comment]
We will be making a larger effort in 2020 to make sure we have more details in the weekly release notes ( https://docs.microsoft.com/en-us/business-applications-release-notes/powerplatform/released-versions/powerapps ) outside of just the major features shipping in a release.
