### ISSUE TITLE
Not synchronous?

### ISSUE THREAD

**Issue by radevic** [MicrosoftDocs/powerapps-docs#1313]
This doesn't seem to be synchronous. I have a pre-stage plugin which is throwing an exception, but this operation succeeds. I would expect to be able to catch the exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3feace00-c6c9-b19a-fa69-9a04cf4ade0e
* Version Independent ID: ede57b39-3180-7ff3-dfe2-4b5eb86439bb
* Content: [save (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-entity/save#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/save.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/save.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@radevic Thanks for contacting us. Yes the save method saves the record asynchronously. please follow this doc https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data/save to get more information. Closing the issue.
