### ISSUE TITLE
Link doesn't exist

### ISSUE THREAD

**Issue by wilsonsilva80** [MicrosoftDocs/powerapps-docs#1315]
"Replace the Main method with the following code. The supported values for AuthType are listed in Connection string paramters."
Connection string parameters is wrongly written and is linked to a uri that doesn't exist anymore, apparently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa0f3c47-59e9-8adf-3df1-307b4916b4e1
* Version Independent ID: 45357d09-689c-ac9a-78b7-1bc4a2d22771
* Content: [Quick Start: Organization service sample (C#) (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/quick-start-org-service-console-app#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/quick-start-org-service-console-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/quick-start-org-service-console-app.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by Nkrb** [comment]
@wilsonsilva80 Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
