### ISSUE TITLE
What exactly does choices return?

### ISSUE THREAD

**Issue by snowburnt** [MicrosoftDocs/powerapps-docs#1317]
I'm using choices to create a collection from a sharepoint choice column, and it appears to create an object that looks like this:
[ { '@odata.type':"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference",
Id:IdOfOption,Value:ValueOfOption}]
However, when I use this in a ForAll functions, and I try to insert the Id field I get an error, identifier not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70491d54-3aae-1104-bbe2-4162b34e4fb2
* Version Independent ID: 52ed1d09-e95f-4bb4-ac9e-cc3481cb7c93
* Content: [Choices function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-choices#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-choices.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-choices.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
As the docs state: The Choices function returns a table of the possible values for a lookup column.

I'm not sure where you are seeing the @odta.type column, perhaps a network trace of Monitor.  That column is internal only and shouldn't be visible when authoring an app and won't be available as a column when writing a formula.

Here's an example of looking for the possible values for a Choices field in SharePoint using `Collect( a, Choices( 'My List'.'Choices Column' ) )`:

![image](https://user-images.githubusercontent.com/15149773/80892854-299ccb00-8c82-11ea-96e3-a284a33fde05.png)

And the SharePoint list definition:

![image](https://user-images.githubusercontent.com/15149773/80892831-f9552c80-8c81-11ea-9c36-e8fc839bf8fc.png)

When collecting the SharePoint list with `Collect( b, 'My List' )`, the value for the column will appear as a record or table, depending on if supports multi-select or not (this example does not):

![image](https://user-images.githubusercontent.com/15149773/80892875-57820f80-8c82-11ea-92ca-89c1d4e10f71.png)

And we can read the first value:

![image](https://user-images.githubusercontent.com/15149773/80892995-56051700-8c83-11ea-8230-546ce453f4fa.png)
