### ISSUE TITLE
Can support be added for formatInfoCultureName?

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#1318]
There is a property called formatInfoCultureName which contains the current culture name  (e.g. en-GB) which can be useful for localisation instead of using the LanuageID  - it saves looking the code from the languagelocale entity.

Can this property be documented?

**Comment by phecke** [comment]
@scottdurow Is this a developer question? Are you looking at the Web API or SDK assemblies and see this property which is not public? I do not have enough information.
