### ISSUE TITLE
Excel Connector deprecated?

### ISSUE THREAD

**Issue by NK-debug** [MicrosoftDocs/powerapps-docs#1322]
There is no Excel Connector for PowerApps.
There is an Excel Online (OneDrive) Connector for PowerApps, but the Excel file has to be on OneDrive, not SharePoint.
The Excel Online (Business) connector which works with SharePoint is only available in Microsoft Flow/Automate, not PowerApps (4/2020).
Please indicate that in the docs here so that people don't keep looking for it.
Better yet, make it available in PowerApps too.
Because not everybody wants to use an Excel file in OneDrive; sometimes the Excel file is in SharePoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01e57c82-f30c-72cd-2cf2-391454cc162b
* Version Independent ID: 94f874ae-c20c-f46b-427e-bc6f08c9a4d0
* Content: [Overview of the Excel connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-excel#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-excel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-excel.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content mentions Excel as not a direct 'connector', but rather having different alternatives with unique capabilities. For a feature ask, please go to [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) to submit an idea or vote.
