### ISSUE TITLE
SharePoint cloud?

### ISSUE THREAD

**Issue by NK-debug** [MicrosoftDocs/powerapps-docs#1323]
Will Microsoft SharePoint Cloud (sp-cloud) be included for the cloud storage connections?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff364788-3a3b-9e31-8100-2768aa6faac8
* Version Independent ID: 01897422-f8c7-1138-7cd6-9eefd69e606f
* Content: [Overview of the cloud-storage connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/cloud-storage-blob-connections)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/cloud-storage-blob-connections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/cloud-storage-blob-connections.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please go to the [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) for this capability question/idea or vote for it.
