### ISSUE TITLE
Can't connect to Excel files in SharePoint?

### ISSUE THREAD

**Issue by NK-debug** [MicrosoftDocs/powerapps-docs#1324]
A PowerApp can only connect to Excel files on OneDrive. (4/2020)
When can we have an ability for a PowerApp to connect to an Excel file on SharePoint? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f32ea1-9e25-c4db-b8c8-df8194517bee
* Version Independent ID: c040bfac-c0df-e1d9-70da-39be48c79209
* Content: [Overview of the SharePoint connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-sharepoint-online)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-sharepoint-online.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-sharepoint-online.md)
* Service: **powerapps**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Though not possible today, there has been discussion ongoing for this feature ask. Please feel free to submit this as an idea (or vote for existing ones) using [Power Apps Community Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas). Upcoming release notes are available at [release plans documentation](https://docs.microsoft.com/dynamics365/release-plans/).
