### ISSUE TITLE
Incomplete Documentation (April 2020)

### ISSUE THREAD

**Issue by henry-royan** [MicrosoftDocs/powerapps-docs#1325]
This documentation is incomplete. It leaves out a lot of properties/attributes that are unique to the Combo Box. However, it acknowledges that they exist under the "Color contrast" subheading under "Accessibility". It makes it hard to make this accessible, when most of the properties required to do so, are left off this page, or aren't explained. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8bf3d3-12e3-5b55-8713-221cf5f5a30c
* Version Independent ID: 5a050d01-6ef6-97d6-07de-d5cac82dea06
* Content: [Combo box control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-combo-box#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Properties are grouped based on the capabilities. Will look into additional properties missing for documentation update.
