### ISSUE TITLE
Remove time value from date field

### ISSUE THREAD

**Issue by Papithasekar** [MicrosoftDocs/powerapps-docs#1326]
Hi,
Date value is getting updated along with time in excel data source and that makes some other issue with calculation. I want only date not with time. Is there any possibility to remove hours and minutes ?
Note:¨
I have made visibility to false for hours and minutes field and set default value as 00, after submitting the form it takes 22:00 automatically and that leads to display selected date + 1 day in another field, not exact selected date.

**Comment by phecke** [comment]
@Papithasekar Can you please provide more details about what you are doing. Are we talking about the maker experience, model-driven or canvas apps? It would be very helpful if you provided a link to the documentation that you were following.

**Comment by Papithasekar** [comment]
Hi, 
Am attaching some image please have a look.[
![date field](https://user-images.githubusercontent.com/44681255/80919601-2df0e300-8d6b-11ea-8bec-b23665be2530.png)
![source](https://user-images.githubusercontent.com/44681255/80919608-32b59700-8d6b-11ea-9047-794b50032066.png)

](url)

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can set Excel table column with data type of only date. And then, use sample such as the following:
```Patch(DateTime,Defaults(DateTime),{'DateTime (DateTime)':DatePicker1.SelectedDate})``` 
where DateTime is the data source, 'DateTime (DateTime)' is the column, DatePicker1 is the date picker and SelectedDate is the date selected. You can still update Excel column to list date in date & time format to see time value, but with just date format, Excel only shows date and no time. If the issue persists, please reach out with a [support service request](https://admin.powerplatform.microsoft.com/support) for investigation.
