### ISSUE TITLE
Deprecated.

### ISSUE THREAD

**Issue by filcole** [MicrosoftDocs/powerapps-docs#1327]
https://docs.microsoft.com/en-us/power-platform/important-changes-coming#some-client-apis-are-deprecated mentions that:

"formContext.data.entity.save" has been deprecated,
and that "formContext.data.save" should be used.

This page does not state that this method has been deprecated.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3feace00-c6c9-b19a-fa69-9a04cf4ade0e
* Version Independent ID: ede57b39-3180-7ff3-dfe2-4b5eb86439bb
* Content: [save (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-gb/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-entity/save)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/save.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/save.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@filcole Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
