### ISSUE TITLE
Setting the label of the timelinewall control does not seem to work

### ISSUE THREAD

**Issue by MitchMilam** [MicrosoftDocs/powerapps-docs#1328]
This should work: 
            formContext.getControl("attachments").setLabel("ATTACHMENTS");

But it still appears at Timeline in the UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d0b4de1-1a28-4998-9055-e354e64d2cca
* Version Independent ID: edb9da16-8b79-18ff-239e-f3af444ff31f
* Content: [setLabel (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setlabel#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setLabel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setLabel.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@MitchMilam Thanks for contacting us. I tried to set the label for the Timeline control and changed it to Activities and it worked. Can you confirm if you're still facing the issue.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
