### ISSUE TITLE
Issue for adding users 

### ISSUE THREAD

**Issue by Farzad-Jalali** [MicrosoftDocs/powerapps-docs#133]
In past, I've built many environments, I know how to add users into them and grant them permission.
so I know EXACTLY what to do! as I done it.

But it (the add user feature) stops working in all environments of my company, No longer I can add my colleagues into any of them.

I think someone needs to fix the bug!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64f39a1a-8a60-994a-44f5-ea0c9fd70562
* Version Independent ID: 6c28a2f5-6962-3a5f-1cf3-81d023aa11a8
* Content: [Configure environment security - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/database-security)
* Content Source: [powerapps-docs/administrator/database-security.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/database-security.md)
* Service: **powerapps**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by jimholtz** [comment]
@Farzad-Jalali 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. If this issue still exists, please contact support.
