### ISSUE TITLE
Problem with Xrm.Utility.getGlobalContext().userSettings.roles when User is member of Team

### ISSUE THREAD

**Issue by makarandkeer** [MicrosoftDocs/powerapps-docs#1330]
If User is member of any non-default team and that team has Security Role assigned to it, then Team level Security Role name is coming as empty/undefined. Following is how it looks in Developer Tool

14f05073-428e-4f7e-97cf-68ec53f3d1e6: {id: "14f05073-428e-4f7e-97cf-68ec53f3d1e6", name: undefined}
81b32792-2837-e811-a950-000d3a3101b9: {id: "81b32792-2837-e811-a950-000d3a3101b9", name: "Test Read-Only"}
671b35da-d81c-42ae-a78d-07bca686c544: {id: "671b35da-d81c-42ae-a78d-07bca686c544", name: undefined}
c7847b65-5530-4a58-a9a4-756d47da194f: {id: "c7847b65-5530-4a58-a9a4-756d47da194f", name: undefined}
e0c84036-8339-e811-a95e-000d3a10877d: {id: "e0c84036-8339-e811-a95e-000d3a10877d", name: "Queue Manager"}
e6e13b17-8339-e811-a95e-000d3a10877d: {id: "e6e13b17-8339-e811-a95e-000d3a10877d", name: "Support Engineer"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999537e5-d7fd-6e16-207a-b7c7c31fdc9e
* Version Independent ID: 48ac9b62-a8b5-3bab-11b5-c0bbc5fde88c
* Content: [getGlobalContext.userSettings (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@makarandkeer Thanks for the feedback. We have fixed the issue and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
