### ISSUE TITLE
isLoaded() returns false on the create form

### ISSUE THREAD

**Issue by dynamicscode** [MicrosoftDocs/powerapps-docs#1331]
When is the data binding complete on _create_ forms? I waited more than a minute and it still returns _false_. But, it works fine on _edit_ forms.

**Comment by phecke** [comment]
@dynamicscode Are you talking about the maker experience, model-driven or canvass apps?

**Comment by Nkrb** [comment]
@dynamicscode Thanks for the feedback. It shouldn't take more than a minute for data binding to complete. Can you verify again and let us know if you are still having the issue.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
