### ISSUE TITLE
Able to Update the App and Flows Imported through Managed Solution

### ISSUE THREAD

**Issue by M-SGFx** [MicrosoftDocs/powerapps-docs#1332]
On the doc, it is mentioned "You cannot edit the components of a managed solution" - However, I have been successfully able to update the PowerApps and PowerAutomate components in TEST environment. This solution was exported from DEV as Managed solution and imported to TEST. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb108dd-66c5-1901-8ee9-9636dd251044
* Version Independent ID: 2c811eaa-92a6-5934-05ef-2398968a89ff
* Content: [Introduction to solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/introduction-solutions)
* Content Source: [powerapps-docs/developer/common-data-service/introduction-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/introduction-solutions.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@M-SGFx  Editing the components of a managed solution is not supported regardless of whether you can presently get it to work. You should only edit an unmanaged solution.
