### ISSUE TITLE
Cannot install the Hospital Emergency Response App by adding it to Dynamics 365

### ISSUE THREAD

**Issue by v-etzha** [MicrosoftDocs/powerapps-docs#1336]
Hi experts,

I followed the steps in the tutorial, however, I was unable to install the sample app when attempting to add the application to Dynamics 365 at the section https://docs.microsoft.com/en-us/powerapps/sample-apps/emergency-response/deploy-configure#option-b-install-the-app-from-microsoft-appsource and step 4. Maybe it's something related to my account. It said "Sorry, we couldn’t find a Dynamics 365 organization connected to the signed-in user. Please use different credentials or sign up for a free trial and try again." But what should I do to my account next? Please help! 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d57c5c3d-2fa4-c2cb-94c9-bac11db9b77a
* Version Independent ID: 2f434aea-9b32-1470-4928-3d4ddd8e2227
* Content: [Deploy the Hospital Emergency Response app - Power Apps](https://docs.microsoft.com/en-us/powerapps/sample-apps/emergency-response/deploy-configure)
* Content Source: [powerapps-docs/sample-apps/emergency-response/deploy-configure.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/sample-apps/emergency-response/deploy-configure.md)
* Service: **powerapps**
* GitHub Login: @pankajarora-msft
* Microsoft Alias: **pankar**

**Comment by dvidvic** [comment]
Hi v-etzha, hope you are very well.

I had this situation as well. I found a quick work around was to use Power BI Pro/Premium and create a workspace then click the **Add Content** button. You'll get the screen shown next, choose the **discover content from my organization** option highlighted in the red rectangle shown next. 

![image](https://user-images.githubusercontent.com/64831620/81045153-8a5c1b80-8ead-11ea-8b0b-8d223f89c901.png)


You should then see lots of Apps, type in "emergency" as your search term. You should see the 2 Apps as shown next, Notice there are no apps from "my organization" returned, but 2 that meet the criteria we searched for. Choose the left one which is the one you want. 

![image](https://user-images.githubusercontent.com/64831620/81045912-233f6680-8eaf-11ea-89a7-63a8ccec1930.png)

You should see the next screen. Just follow the on screen instructiions of "GET IT NOW" which are easy to follow, it installs very fast.

![image](https://user-images.githubusercontent.com/64831620/81046895-38b59000-8eb1-11ea-9de8-73fb74781071.png)

You end up with the final app shown next. You can customize it as you wish and change or remove the organisation branding. Note that you must be in edit mode to do that.

![image](https://user-images.githubusercontent.com/64831620/81048879-0b6ae100-8eb5-11ea-8efa-6ca730b64681.png)


I also found a way to reconstruct the app in Power BI Desktop which is where numerous people seem to want to see it working as shown next. 

![image](https://user-images.githubusercontent.com/64831620/81046264-e2941d00-8eaf-11ea-8905-e1211e4f55fc.png)

Obviously Power BI and Power BI Desktop are two different products whereby you cannot download the Power BI Emergency Response App as a .pbix file, the option is greyed out (shown next). Hence the need for the work around to reconstruct it in Power BI. The template option which Microsoft themselves don't recommend to use was a non-starter for me. Also I wanted to create a pure .pbix file that would work in any version of Power BI Desktop and display correctly. Bypassing the incompatibility of Power Apps and Power BI in certain areas. This is why you get warnings when you try to open certain files in BI Desktop explaining certain elements may not display correctly etc etc.

![image](https://user-images.githubusercontent.com/64831620/81048400-2db02f00-8eb4-11ea-8497-263eeeab04bb.png)

**Comment by v-etzha** [comment]
Thanks for the help! Close this since I have no question for now.
