### ISSUE TITLE
The global apps currency sample is not working for prices with 00 decimal

### ISSUE THREAD

**Issue by Amysno** [MicrosoftDocs/powerapps-docs#134]
Hey there !
Under SPO, I have set a Currency column with : "Number of decimal places"= 2 and "Currency format"=123,456.00 € (France) (which is wrong too, because officially a number is as such : 1 500,50€ is "thousand five hundred €uros and 50cents" - but that is another question)
So, in my list, if a user enters "150€" as a price, it will be converted to "150.00€" (so with two zeros after the point).
Under Powerapps, with the following formula :
Text(ThisItem.Prix,"[$-fr-FR]€ #,###","fr-FR")
I get "€ 150," : after the comma, it is empty.
Please fix the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f30da2a-1b9d-9d31-c59e-494314144b2f
* Version Independent ID: abe8de4e-2ed5-aedc-d2b3-a819bdf40587
* Content: [Text function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-text)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-text.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-text.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Thanks, @Amysno, for your feedback. Does this formula give you the result that you expect?
Text(ThisItem.Prix, "[$-fr-FR]€ # ###,00", "fr-FR")

**Comment by AFTOwen** [comment]
Hi, @Amysno: I played around with it, and this example gave me what I think you want.
Text(ThisItem.Prix, "[$-en-US] # ###,## €", "fr-FR")

We're looking into this issue but, if you still have concerns, please submit [product feedback](https://powerusers.microsoft.com/t5/PowerApps-Ideas/idb-p/PowerAppsIdeas). Thanks.
