### ISSUE TITLE
Don't forget to use /p:NuGetInteractive=true in case you face any 401 issue

### ISSUE THREAD

**Issue by oiluis** [MicrosoftDocs/powerapps-docs#1341]
Not exactly a bug, but on my case, every time I needed to run the following command:

`msbuild /t:build /restore` 

I faced a 401 (Unauthorized) error as below:

![image](https://user-images.githubusercontent.com/2482647/81099043-a5944e80-8ee0-11ea-8803-f41269d6f6ba.png)

My solution to overcome this was adding the /p:NuGetInteractive=true so the final command is:

`msbuild /t:build /restore /p:NuGetInteractive`

This will ask you to authorize the device through a web link. After the login, you should be able to execute the command.

**Comment by phecke** [comment]
@oiluis What is this related to: PowerApps Component Framework, PowerApps build tools and DevOps, or something else. I cannot tell what you are talking about without more details. It would be best if you provide a link to the developer documentation that is related to this issue. Thanks,

**Comment by oiluis** [comment]
This is related to the command to build PCF  :) ... executing the msbuild command on the visual studio dev prompt can produce this error

**Comment by Nkrb** [comment]
@oiluis Thanks for the feedback. This issue is because you are trying to access the non-public nuget packages. We recommend end users to access publicly available nuget packages. Closing the issue.

**Comment by oiluis** [comment]
Sorry @Nkrb  but I think you didn't get it or I wasn't clear enough ... I am using the plan old "msbuild /t:build /restore" command on my machine and the error is a 401 ... I didn't change anything on my machine to access the non-public nuget packages. What is even worse is that now the msbuild compiler doesn't recognize the p:NuGetInteractive param
