### ISSUE TITLE
Xrm tooling connector WPF control throwing error

### ISSUE THREAD

**Issue by shashankgwl** [MicrosoftDocs/powerapps-docs#1345]
I'm using the latest WPF control, it throws error on following.

1. When I switch from online to onprem.

2. When I enter my login credentials and click login.

![image](https://user-images.githubusercontent.com/2750603/81203370-83d0bf80-8fe5-11ea-87fd-24a4b312196c.png)

Also, there's no `ConnectionCompletedEvent` on this control.

![image](https://user-images.githubusercontent.com/2750603/81203563-baa6d580-8fe5-11ea-9bb6-8a8e8468232b.png)

**Comment by phecke** [comment]
@shashankgwl Can you  please provide the version of the Microsoft.CrmSdk.XrmTooling.WpfControls NuGet package that you are using. Also, you will get a quicker response if you select the "Contact owners" link on the XrmTooling NuGet package page.

**Comment by phecke** [comment]
@shashankgwl 

Thanks for the feedback.
