### ISSUE TITLE
Authentication and Usage options

### ISSUE THREAD

**Issue by joepurnell88** [MicrosoftDocs/powerapps-docs#1347]
Is it possible to use an app registration to access the DB structure in SSMS?  Also, can this be used to run queries in angular web resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@joepurnell88 It is not possible to use Azure AD app registration for authentication in the preview release. No word yet with regard to the final release.

**Comment by phecke** [comment]
@joepurnell88 Thanks for the feedback.
