### ISSUE TITLE
How can I call a component from a JavaScript WebResource?

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#1348]
Can also pass a data payload to the component using this method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfca439f-2902-4e1c-47b2-e96c1fe6d78f
* Version Independent ID: a0406aa3-5035-a4db-3706-ee3b5dd908a5
* Content: [FAQs | MicrosoftDocs - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/faq)
* Content Source: [powerapps-docs/developer/component-framework/faq.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/faq.md)
* Service: **powerapps**
* GitHub Login: @ghurlman
* Microsoft Alias: **grhurl**

**Comment by Nkrb** [comment]
@gregdegruy Not the component directly. But if it is a field component,  you can use `clientAPI` methods to access and then bound attribute to Power Apps component framework, so `setValue` and `getValue` for attributes will work for the component bound to that field.

**Comment by Nkrb** [comment]
@gregdegruy I hope you got the answer you got it internally. Closing the issue.
