### ISSUE TITLE
availability regions?

### ISSUE THREAD

**Issue by mrrandall40** [MicrosoftDocs/powerapps-docs#1351]
Will you confirm if or when this will be available in the US or how to enroll in the preview, if necessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query?source=docs#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by sergioreyero** [comment]
Same interest for Europe (crm4)

**Comment by keijiinoue** [comment]
Same interest for Japan (crm7)

**Comment by josi4** [comment]
And again, for NZ/AU crm6

**Comment by mayadumesh** [comment]
The current way to understand availability is at [https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi) . We are working on adding capability to admin portal soon.

**Comment by phecke** [comment]
@mrrandall40

Thanks for the feedback.
