### ISSUE TITLE
loadExactPage is not documented

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#1352]
The function loadExactPage is not documented - is it supported? 
See Anqi's info here -https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Issue-using-Dataset-Paging/m-p/405587/highlight/true#M1273

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d40f22d-3206-3b47-5cbe-0e557fa0bd07
* Version Independent ID: 1d5b0fbd-9b5d-d605-6553-138d0f7e2316
* Content: [Paging - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/paging#feedback)
* Content Source: [powerapps-docs/developer/component-framework/reference/paging.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/paging.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@scottdurow Thanks for the feedback. This function is still not supported yet. Closing the issue.

**Comment by scottdurow** [comment]
When is this function going to be supported since Anqi is recommending it being used?
