### ISSUE TITLE
'Add screen context variables' link needs to be fixed

### ISSUE THREAD

**Issue by lfinman** [MicrosoftDocs/powerapps-docs#1353]
Under 'See also', the link to screen context variables does not link to a page mentioning screen variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9b5e7f-c7a3-4530-11dc-d3655e0c77d4
* Version Independent ID: 10b605d6-f30a-aef9-c69a-ebc267089fd2
* Content: [Back and Navigate functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-navigate#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-navigate.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-navigate.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the report.  The link now points to a discussion on context variables.
