### ISSUE TITLE
BusinessPhones returns a Table not a String

### ISSUE THREAD

**Issue by henry-royan** [MicrosoftDocs/powerapps-docs#1354]
Using "Office365Users.MyProfile().BusinessPhones" as described on this page actually returns a Table. You can't use this particular property with this function as you would with the other properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9434b232-2bf5-14f0-9861-6726dc216b96
* Version Independent ID: d073f002-01ac-541b-d365-60affab50cae
* Content: [Overview of the Office 365 Users connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-users)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, documentation has been updated. Please allow some time to reflect the changes.
