### ISSUE TITLE
IT Systems Support

### ISSUE THREAD

**Issue by GBauer1833** [MicrosoftDocs/powerapps-docs#1355]
It would be nice if we could "pause" your demo animations so beginners could see what is being selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a8c4146-101d-7ba2-7ae0-d7138b743154
* Version Independent ID: 1f752762-0809-a2fb-4a03-b490547ee7f1
* Content: [Customize a SharePoint list form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. Though GIFs can't be paused, the ones on the article are only several seconds long for ease of consumption. And the GIFs can be viewed again to repeat the steps. Will consider more screenshots in addition to GIFs and possibly embedded videos that can be paused. Appreciate your suggestions.
