### ISSUE TITLE
totalResultCount not documented

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#1356]
totalResultCount is defined in node_modules\@types\powerapps-component-framework\componentframework.d.ts - but not documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d40f22d-3206-3b47-5cbe-0e557fa0bd07
* Version Independent ID: 1d5b0fbd-9b5d-d605-6553-138d0f7e2316
* Content: [Paging - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/paging)
* Content Source: [powerapps-docs/developer/component-framework/reference/paging.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/paging.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@scottdurow We have documented this in our official docs [here](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/paging#totalresultcount).

**Comment by Nkrb** [comment]
@scottdurow Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by scottdurow** [comment]
Thank you for the updates!
