### ISSUE TITLE
Now available in Canvas Apps

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#1357]
This page says 'Model-driven apps' only - but Dataset PCF controls are now available in Canvas - https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/data-set-component-canvas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d40f22d-3206-3b47-5cbe-0e557fa0bd07
* Version Independent ID: 1d5b0fbd-9b5d-d605-6553-138d0f7e2316
* Content: [Paging - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/paging)
* Content Source: [powerapps-docs/developer/component-framework/reference/paging.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/paging.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@scottdurow Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
