### ISSUE TITLE
An OData error occurred

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#1358]
How can I resolve this error?

![Annotation 2020-05-07 134422](https://user-images.githubusercontent.com/8151045/81342934-eae38800-9068-11ea-87ae-02f07e440f38.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaee10a3-558f-55f5-4c7c-e3d6d7567d19
* Version Independent ID: 5c21acb1-6336-23b2-1025-e6f69e2115d8
* Content: [Virtual entity walkthrough using the OData Data Provider in Common Data Service - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/virtual-entity-walkthrough-using-odata-provider)
* Content Source: [powerapps-docs/maker/common-data-service/virtual-entity-walkthrough-using-odata-provider.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/virtual-entity-walkthrough-using-odata-provider.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@gregdegruy - Thanks for contacting us. Unfortunately, we're unable to handle support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/. 

Closing this issue.
