### ISSUE TITLE
Limitations and comparision with FetchXml

### ISSUE THREAD

**Issue by codes4pizza** [MicrosoftDocs/powerapps-docs#1359]
This is really interesting but FetchXml is also a readonly data access mechanism. Is this SQL connection just layered on top of FetchXml so it suffers from the same limitations as FetchXml or is it really a direct read-only sql connection? FetchXml has a limit of 10 entities. Are there similar limits for the sql connection? FetchXml can only aggregate at most 50,000 records. Does the sql connection have any such limits?

The section on supported operations provides some info but its not yet detailed enough. What would be really useful is a table providing a side by side comparision of FetchXml limits and sql connection limits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by smgtreker** [comment]
Excellent point and question; I was wondering the same thing.

**Comment by phecke** [comment]
@codes4pizza I will send your documentation enhancement request to the Program Manager for the feature.

**Comment by mayadumesh** [comment]
It is a new endpoint for CDS. It does not have same functionality as FetchXML. 
As you are building your queries they are run through CDS and return results. Your constrains are based on performance of your query not enforced number of rows returned.
