### ISSUE TITLE
ITokenService always retruns null

### ISSUE THREAD

**Issue by PawelHaracz** [MicrosoftDocs/powerapps-docs#136]
Hi, I tried to use a service ITokenService and I always get a null object. I tried to use as a plugin (sync/async), workflow (sync, async), these two ways what I used I registered as a calling user and as an application user (this user has a clienId and secretId) 

Please explain to me how it's work or confirm if it a bug

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd963191-3f2c-d3be-8eec-78fedeeda8c3
* Version Independent ID: 63ff825f-4f7c-7da3-b514-9b5ec962b2f8
* Content: [Work with data using code in Common Data Service for Apps (PowerApps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/work-with-data-cds?view=dynamics-general-ce-9)
* Content Source: [powerapps-docs/developer/common-data-service/work-with-data-cds.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/work-with-data-cds.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@PawelHaracz 
I've confirmed that this interface is for internal use only. Asking @Nkrb  to update the reference topics at [Microsoft.Xrm.Sdk.ITokenService Interface](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.itokenservice?view=dynamics-general-ce-9) and [RetrieveAADAccessToken method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.itokenservice.retrieveaadaccesstoken?view=dynamics-general-ce-9)

This should help make sure others don't go down this path.
@Nkrb , please close this when those changes are done.

**Comment by PawelHaracz** [comment]
Thanks for Your answer. I thought that is a new crm service to generate OAuth token and we can use it in plugins and workflows.

**Comment by Nkrb** [comment]
Updated the reference topic.

**Comment by davidyack** [comment]
@Nkrb @JimDaly  I don't think it  got marked internal only - I just researched it from [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.itokenservice.retrieveaadaccesstoken?view=dynamics-general-ce-9#Microsoft_Xrm_Sdk_ITokenService_RetrieveAADAccessToken_System_String_System_String_System_String_) and didn't see anything about internal only - would be a good update

**Comment by JimDaly** [comment]
@phecke & @Nkrb 
Please update the reference topic for this to show it as for internal use only. Perhaps this was overwritten?

**Comment by phecke** [comment]
@PawelHaracz ITokenService is internal use only.
