### ISSUE TITLE
The Flow of  CrisisCommunication.Request is not charging well

### ISSUE THREAD

**Issue by JanieVi** [MicrosoftDocs/powerapps-docs#1362]
When I import the Crisis Communication app automatically creates a flow of
CrisisCommunication.Request but does not appear as a power app but has the outlook logo. And when yo go to the edit page of this flow the first step said "when a new mail arrives" instead of "PowerApps"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by Angelakw12** [comment]
I get the same issue which is why the flow is not working.

**Comment by tapanm-MSFT** [comment]
Please reach out to the [issue/feedback](https://docs.microsoft.com/powerapps/maker/canvas-apps/sample-crisis-communication-app#issues-and-feedback) hyperlinks documented in the article for help with this app.
