### ISSUE TITLE
Is there a manifest.cdm.json file in Export to Data Lakes at present or planned?

### ISSUE THREAD

**Issue by dmaxwe22** [MicrosoftDocs/powerapps-docs#1363]
Is there or will there be support for CDS relationship metadata between entities. From what I understand this should be found in the manifest.cdm.json file in folders in the storage location. All I see now is a model.json file and I have to create relationships when using Power BI or if trying to use Azure Data Bricks to transfer to an Azure SQL database. 

What is the best way at present to show relationships between entities in the Data Lake CDM?

It seems like it is not quite right to state that the export to Azure Data Lake is a true CDM compatible export. See this link for terminology. 

https://docs.microsoft.com/en-us/common-data-model/data-lake#terminology 

Am I possibly missing something or is this a feature to come soon, hopefully?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771a2696-1d5a-88c0-299e-320d03a536c3
* Version Independent ID: 0b729e37-ce56-6d84-f44b-a22666776cec
* Content: [Export to data lake - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by subashsivaji** [comment]
Is there a ETA of when Dataverse Export to Data Lake will support *.manifest.cdm.json?

**Comment by sabinn-msft** [comment]
Our current target is April 21 release. We will reconfirm this by end of Jan 21

**Comment by Mattp123** [comment]
Closing issue.
