### ISSUE TITLE
TDS protocol endpoint is disabled for this organization

### ISSUE THREAD

**Issue by eromerof** [MicrosoftDocs/powerapps-docs#1365]
Hi, I cannot connect my mssms with dynamics because I have this error. Do I have to enable something in my organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by VinnyDyn** [comment]
Same problem...

**Comment by phecke** [comment]
@eromerof I have just updated the topic note with a link to instructions on how to enable the preview feature.

**Comment by eromerof** [comment]
Thank @phecke !!

**Comment by levchr** [comment]
@phecke : seems to be enabled for me as the button is visible, but still no connection possible with the mentioned error....

**Comment by levchr** [comment]
@phecke - problem in front of the screen - forgot to enable the feature with this: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi
works now perfectly - thanks

**Comment by VinnyDyn** [comment]
Thank @levchr for share the link! It worked 👍
