### ISSUE TITLE
Incorrect word used... pls fix

### ISSUE THREAD

**Issue by hoodlumj3** [MicrosoftDocs/powerapps-docs#1366]
"the" used instead of "then"
"If you cannot move files outside, the ensure that all the files are not loaded along with home page"
should be 
"If you cannot move files outside, then ensure that all the files are not loaded along with home page"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb68e1d-5c5a-fe4d-bfe0-324744299f6f
* Version Independent ID: c8b2432d-a350-824c-222b-cd8911d1af8b
* Content: [Frequently asked questions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/faq)
* Content Source: [powerapps-docs/maker/portals/faq.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/faq.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. The content is being updated. Please allow some time to reflect the changes.
