### ISSUE TITLE
IP ranges should use CIDR

### ISSUE THREAD

**Issue by gjbdebug** [MicrosoftDocs/powerapps-docs#1367]
Here's the US list with ranges expressed using CIDR notation:

13.89.171.80/28,52.173.245.164,40.71.11.80/28,40.71.249.205,40.70.146.208/28,52.232.188.154,52.162.107.160/28,52.162.242.161,40.112.243.160/28,104.42.122.49,127.0.0.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdf0872-929b-e44a-dedd-eb6a759915f2
* Version Independent ID: 0b65b025-62f8-fc2a-0026-3cb96b7b4554
* Content: [System requirements, limits, and configuration values for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gjbdebug** [comment]
US "early access":
13.71.195.32/28,52.161.102.22,13.66.140.128/28,52.183.78.157,127.0.0.1

**Comment by tapanm-MSFT** [comment]
Content has been updated with latest changes. Please use the updated documentation.
