### ISSUE TITLE
Missing visibility methods

### ISSUE THREAD

**Issue by clurdish** [MicrosoftDocs/powerapps-docs#1368]
Unless they are explicitly unsupported, this document is missing methods getVisible and setVisible to control visibility. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7448eb2-774a-b6f7-9f21-6119211619d4
* Version Independent ID: f6b3b802-fc1d-9a09-a542-9a6d29468032
* Content: [GridControl (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/grids/gridcontrol)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridControl.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridControl.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@clurdish Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
