### ISSUE TITLE
Port 5558?

### ISSUE THREAD

**Issue by dibutil** [MicrosoftDocs/powerapps-docs#1369]
Port 5558 does not respond on any of my instances (various orgs, all in NA zone), cannot explore or discover the possibilities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by FrankFenneran** [comment]
Same for us

**Comment by phecke** [comment]
@dibutil
Did you verify that you have the feature available in your environment?

1.	Sign into Power Apps, on the left navigation pane expand Data, and then select Entities. 
2.	On the command bar, you should see a button "Analyze in Power BI". If you do not see this button, your environment does not yet have the feature.

I have no information as to when the feature will be available in the different tenants. The feature is in preview and being rolled out over time.

**Comment by phecke** [comment]
@dibutil  Thanks for the feedback.
