### ISSUE TITLE
Needs list of examples

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#137]
at least a list of several built-in formats

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cf200f9-bbdc-edb4-79e2-f08839d2457b
* Version Independent ID: ca13a0df-20a7-c0f5-9597-1be7c2c7b042
* Content: [Show text, dates, and times in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/show-text-dates-times)
* Content Source: [powerapps-docs/maker/canvas-apps/show-text-dates-times.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/show-text-dates-times.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@akmiecik, thanks for your feedback. The second tip in the topic discusses how to review a list of built-in options. Were you looking for something else?
