### ISSUE TITLE
DataCardValue Format property

### ISSUE THREAD

**Issue by rrkushner** [MicrosoftDocs/powerapps-docs#1371]
How do I format a DataCardValue? How do I use the Format property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b20a4da-a604-73e1-cade-77b2cd2b917e
* Version Independent ID: ad343c70-310b-e409-72ac-2a59a9041732
* Content: [Card control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-card#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-card.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-card.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
DataCardValue(n) are the card value text boxes and Format allows selecting between available type of formats for the field. All formatting related options are available on the properties pane on the right side.
