### ISSUE TITLE
Script not in the ClientApiFrame_[n] with highest value [n] for the new Unified Interface forms

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#1372]
The Unified Interface form scripts are not in the ClientApiFrame_[n] frame with the highest value [n] when I debug the script in the DevTools of the Chrome browser or Edge based on Chromium

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61cf532-f935-772c-a80d-5310767ffbdc
* Version Independent ID: 8eca9f5e-ebd1-5d6b-0e5e-3d42777b1390
* Content: [Debug your JavaScript code for model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/debug-javascript-code)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/debug-JavaScript-code.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/debug-JavaScript-code.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by JimDaly** [comment]
@LinnZawWin 
Thank you for your feedback. Apologies for the **very** late reply. This was just assigned to me.
Based on what you reported (2 years ago) it seems the details described in the topic are not accurate in terms of where the code can be found when debugging. 

I also see that you opened 2589 with the answer. Thank you very much. I've assigned that issue to me and will close this one.
