### ISSUE TITLE
Quick Find

### ISSUE THREAD

**Issue by AbdulWahabWarind** [MicrosoftDocs/powerapps-docs#1373]
Functionality: Searchable fields = All searchable fields but in my case I can not add Decimal Number field in a quick find view. Can you please expain why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53b21b6-a371-2b0d-0fee-2f77fa645b66
* Version Independent ID: 55864e5c-128a-ccbd-10bc-84daf3c847bb
* Content: [Search options in Common Data Service - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/search)
* Content Source: [powerapps-docs/user/search.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/search.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
@AbdulWahabWarind You will need to contact support to figure this out. 

To contact Support, see here: https://powerapps.microsoft.com/support/ 

Closing this issue
