### ISSUE TITLE
Crisis Communicator App - Change language app to Portuguese

### ISSUE THREAD

**Issue by JoaoNBMoreira** [MicrosoftDocs/powerapps-docs#1375]
Hi,

How can change language app to portuguese?

Thanks,
Joao

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The Crisis Communication app package (aka.ms/CrisisCommunicationSolution) comes with an Excel file for language translation of app text; and lists the languages it supports. For more help with the app, please reach out to aka.ms/crisis-communication-feedback for feedbacks and aka.ms/crisis-communication-issues for issues.
