### ISSUE TITLE
Async Task.Result

### ISSUE THREAD

**Issue by FlorianGrimm** [MicrosoftDocs/powerapps-docs#1376]
using Task.Result is documented as anti-pattern. e.g.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/async-return-types

Please use async in the correct way

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da4c6b5-4ca0-0138-ea99-47e40feaf908
* Version Independent ID: 6bd64a3c-bdf4-a8dd-a6d0-a607a444a30f
* Content: [Enhanced quick Start(Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/enhanced-quick-start#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/enhanced-quick-start.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/enhanced-quick-start.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
It is an anti-pattern if you are building an app that depends on multiple threads and you need to avoid blocking. 
But for this simple introductory console app, it adds additional complexity that conflicts with the goal of this sample.

Our goal is to focus on our APIs, not trying to teach general .NET programming practices.
