### ISSUE TITLE
can't update value to sharepoint list

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerapps-docs#1378]
I moved this from here: https://github.com/MicrosoftDocs/powerapps-docs.zh-cn/issues/4

@limfoo commented 10 hours ago — with docs.microsoft.com
using this approach I can't update value to sharepoint list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please contact the support team to help with the issue investigation using a [support ticket](https://admin.powerplatform.microsoft.com/support).
