### ISSUE TITLE
Does this need an updated clientid?

### ISSUE THREAD

**Issue by douggriffin-leavitt** [MicrosoftDocs/powerapps-docs#1379]
I have used these settings previously--about  a year ago--and they worked well. Now, I get this error when attempting to finalize auth:

> AADSTS700016: Application with identifier '{{clientId}}' was not found in the directory '49c34ae3-8d5f-4eb0-be9f-ec69a65850c2'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by tapanm-MSFT** [comment]
@douggriffin-leavitt can you please share the content article link that the feedback is for?

**Comment by douggriffin-leavitt** [comment]
The article "Set up a Postman environment" can be found here:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/setup-postman-environment#connect-with-your-common-data-service-environment

Thank you

**Comment by RedsGT** [comment]
@dougelliott Just tested this with the latest version of Postman and a test CDS instance from scratch and it works fine for me.  Based on your error message it looked like something is is wrong with your clientId variable expansion, but Postman support would be a better place for that.

**Comment by phecke** [comment]
@douggriffin-leavitt  Thanks for the feedback.
