### ISSUE TITLE
Should include which screen comes first

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#138]
Title is "Screen control in PowerApps" therefor it should include how to control which screen comes first

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e39cd04-aed7-f85c-52cc-7db8ad277f2b
* Version Independent ID: a6d85143-d08b-5746-1d45-9f23ff62e2f0
* Content: [Screen control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-screen)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-screen.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-screen.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
Thanks, @akmiecik, for your feedback. Not sure whether you're asking which screen appears by default when you open the app (the one at the top of the left navigation bar in PowerApps Studio) or how to move a screen to the top of that bar (select ellipsis and then select **Move up**). Can you please clarify your question?

**Comment by akmiecik** [comment]
1) Something like your comment "when you open the app (the one at the top of the left navigation bar in PowerApps Studio) or how to move a screen to the top of that bar (select ellipsis and then select Move up" should be included in a help screen titled "Screen control in PowerApps".

**Comment by AFTOwen** [comment]
@akmiecik Added a link to the procedural topic for screens and a second optional step in the example. Resolving as fixed.
