### ISSUE TITLE
Link to Sample: Query Metadata and Detect Changes is broken

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1380]
The link goes to https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/org-service/sample-query-metadata-detect-changes, but it redirects to https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/metadata-option-sets

It should go here: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/samples/query-metadata-changes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fccbc62-5a81-6b35-b133-f1ad2974045b
* Version Independent ID: eb9c593b-6655-a49d-d754-c77f5d891ebc
* Content: [Retrieve and detect changes to metadata (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/metadata-retrieve-detect-changes)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/metadata-retrieve-detect-changes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/metadata-retrieve-detect-changes.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@phecke Can you fix this link please?

**Comment by phecke** [comment]
Link seems to have been fixed.
