### ISSUE TITLE
Editing User Status

### ISSUE THREAD

**Issue by T-Benny** [MicrosoftDocs/powerapps-docs#1381]
I noticed when editing the PowerApp there should be a button for users to edit their status once set (working from home/ out of office), but in my testing I am unable to edit status after it has been set. Additionally while reloading the page, the status text always returns to "Let others know where your are working" until you enter the Set Status menu again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For issues/feedback with this app, please reach out to using the hyperlinks as mentioned in [Feedback/Issues](https://docs.microsoft.com/powerapps/maker/canvas-apps/sample-crisis-communication-app#issues-and-feedback).
