### ISSUE TITLE
Purpose of Default vs DefaultSelectedItems and Selected vs SelectedItems

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/powerapps-docs#1387]
Its unclear and confusing what the difference is between them. I'm assuming that Selected is simply First(SelectedItems), and DefaultSelectedItems is {Value: Default} depending on the SelectMultiple property. 
Edit: 
Found existing closed issue #285
> Default isn't mentioned because it shouldn't be used.

Then it should not be there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8bf3d3-12e3-5b55-8713-221cf5f5a30c
* Version Independent ID: 5a050d01-6ef6-97d6-07de-d5cac82dea06
* Content: [Combo box control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-combo-box)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For help with updating feature experience (including removal of any existing properties not in use), please reach out to [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas), or support teams with a [ticket](https://admin.powerplatform.microsoft.com/support) to help you out further.
