### ISSUE TITLE
Can't get the form to remember the Card Form

### ISSUE THREAD

**Issue by paulhasell** [MicrosoftDocs/powerapps-docs#1388]
Followed the advise on this page and still can't get the form to accept the card form settings, it keeps reverting :(

I have noted that the Card Form is not listing as a form in the App Designer for the custom activity either :((

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f8feb33-5440-75cb-a822-df28594faa5d
* Version Independent ID: c59421c6-9f9c-ae4e-f624-d025b4b8df48
* Content: [Set up the timeline control (section) in PowerApps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/set-up-timeline-control#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/set-up-timeline-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/set-up-timeline-control.md)
* Service: **powerapps**
* GitHub Login: @kabala123
* Microsoft Alias: **kabala**

**Comment by Mattp123** [comment]
@paulhasell - thank you for your feedback. Can you send me the steps to reproduce the issue you're experiencing? Thanks

**Comment by Mattp123** [comment]
Closing issue.
