### ISSUE TITLE
non functional work in progress functionality in documentation

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/powerapps-docs#1389]
Command bar – Displays available actions such as Save, Publish, Undo, and Redo.

[UNDO and REDO does not work and are supposedly a work in progress](https://powerusers.microsoft.com/t5/Building-Power-Apps/Bug-report-Undo-and-redo-not-working-on-build-v642/m-p/39479/highlight/false#M16379]), non functional buttons are even visible in the current version is really awful and false advertising that gives users a lot of grief. And functions known not to be working, yet found in the documentation is even worse than no documentation at all, its indicating that the documentation can't be trusted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e57bedc-b88b-e428-613d-72fd8184df32
* Version Independent ID: 0b66fa51-c3de-612d-de15-c17b249b0c77
* Content: [Overview of the model-driven form designer - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/form-designer-overview)
* Content Source: [powerapps-docs/maker/model-driven-apps/form-designer-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/form-designer-overview.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Hjaf - What app design interface are you experiencing issues with using the undo/redo buttons? The article you reference in this issue is for the Model-driven form designer, but the link you've added in your comment appears to be for the Canvas app studio (https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/keyboard-shortcuts#editing).

**Comment by Mattp123** [comment]
Closing issue.
