### ISSUE TITLE
Adding user to the environment is no longer working:

### ISSUE THREAD

**Issue by Farzad-Jalali** [MicrosoftDocs/powerapps-docs#139]
[Enter feedback here]
Adding user to the environment is no longer working:
![image](https://user-images.githubusercontent.com/3695669/49787568-ee150000-fd1e-11e8-9738-f44a032cc0d5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5959fac9-f65c-0c09-14ca-1824a167997f
* Version Independent ID: 30ccfc1f-f76a-8750-02ab-2ceb1fe07344
* Content: [Administer environments - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/environments-administration)
* Content Source: [powerapps-docs/administrator/environments-administration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/environments-administration.md)
* Service: **powerapps**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by jimholtz** [comment]
@Farzad-Jalali 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. If this issue still exists, please contact support.
