### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by TobyJH-gs** [MicrosoftDocs/powerapps-docs#1390]
Still does not save data back to source, even with the solutions above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by Ruokiri** [comment]
Hi Toby, this solution works for me:

Click on Location DataCard:

1.Go to advanced;
2. Change update field by this: ddLocation.Selected_Text_.Result
3. Change allowed value to: Distinct(Locations, Location)

Click on Department DataCard:
1. Go to advanced;
2. Change Update field to: ddDepartment.Selected**Text**.Result
3. Change allowed value field to: Distinct(Filter(Locations, Location = ddDepartment.Selected.Result),Department)

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please contact the support team to help with the issue investigation using a [support ticket](https://admin.powerplatform.microsoft.com/support).
