### ISSUE TITLE
Outdate Info

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerapps-docs#1391]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/powerapps-docs.es-es/issues/8

@JoseAntonioBarriga commented 19 hours ago — with docs.microsoft.com
This is an excellent paper. Really good. Unfortunately is outdated. Please update it.

------

Hello, @JoseAntonioBarriga&lt;https://github.com/JoseAntonioBarriga&gt;

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

Kind regards,

Microsoft DOCS International Team

-----

Of course.!  What I meant regarding updating was that some information published in this Power App documentation is outdated, for example, https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-cards. This page is part of a complete Power App Tutorial

As you can verify, that doc was updated three years ago (4/26/2016). Maybe that date is wrong, but if you go through all the screens, there are outdate. Let point that this documentation is excellent, so it is a pity that such a work has left behind. Power Apps I something that is evolving every date, so updating documentation is essential so that everybody will be able to use the new feature.

Looking forward,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f886011-a79a-8fa9-bb7c-f0adbb61b8d3
* Version Independent ID: 997f29d5-e836-fc31-647e-eb6a916afae4
* Content: [Understand data cards - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-cards#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-cards.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-cards.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@CeciAc Thanks for the feedback. Docs are updated and pushed live. Closing the issue. If you need further help, please reopen or create a new issue.
