### ISSUE TITLE
Org Unique Name missing in call to Microsoft.Crm.SE.OrgDBOrgSettingsTool (Prerequisite step 6)

### ISSUE THREAD

**Issue by mjfjesus** [MicrosoftDocs/powerapps-docs#1393]
Correct syntax of above command is:
Microsoft.Crm.SE.OrgDBOrgSettingsTool Update /u &lt;ORG_UNIQUE_NAME&gt; EnableTDSEndpoint true
where ORG_UNIQUE_NAME can be obtained in Dynamics 365 Advanced Settings (or PPAC legacy settings), Settings --&gt; Customizations --&gt; Developer resources, field Unique Name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d27f9-66bc-5cd2-d8b5-9defc8eddfb0
* Version Independent ID: c45841f0-1488-8c30-8a7c-3a522ec63266
* Content: [View entity data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi#prerequisite)
* Content Source: [powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by mayadumesh** [comment]
Thank you! we will update the doc soon.

**Comment by phecke** [comment]
@mjfjesus The change has been published. Thanks for the feedback.
