### ISSUE TITLE
Power Apps Client Application for Windows PC: premium trial popup

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/powerapps-docs#1394]
With some customers that are still using the local Power Apps client installed on PC (I know 🙄 we already advised them to "go browser") --&gt; suddenly a premium license popup comes up. When the user opens the app in browser the premium license popup does not come up and app works fine... somehting changed or something to clarify in the Note above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdf0872-929b-e44a-dedd-eb6a759915f2
* Version Independent ID: 0b65b025-62f8-fc2a-0026-3cb96b7b4554
* Content: [System requirements, limits, and configuration values for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. As mentioned in the [note](https://docs.microsoft.com/powerapps/maker/canvas-apps/limits-and-config#supported-platforms-for-running-canvas-apps-using-the-power-apps-mobile-app), we currently don't support new features on Windows platform. Hence, changes in mobile apps or web player may not appear in Windows app. Content will be updated depending on updates to Windows platform app.
