### ISSUE TITLE
Update to use built-in map component

### ISSUE THREAD

**Issue by rbrundritt** [MicrosoftDocs/powerapps-docs#1395]
Should this be updated to use the built-in map component? https://powerapps.microsoft.com/en-us/blog/new-geospatial-features-in-power-apps/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 981881ff-889a-2b0c-515e-c0e2af8e4357
* Version Independent ID: 9e9eaa4b-0743-eb5c-2e23-2bd437de733c
* Content: [Map component - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/map-control#feedback)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/map-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/map-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@rbrundritt The map sample is more for a demo purpose on how to build such type of component.

**Comment by rbrundritt** [comment]
Can we update it to us a Microsoft mapping platform? We have two to choose from.

**Comment by Nkrb** [comment]
@rbrundritt Closing this issue. Following up with you internally.
