### ISSUE TITLE
Can't find: Add an Image only control (Insert tab > Gallery)

### ISSUE THREAD

**Issue by madiepev** [MicrosoftDocs/powerapps-docs#1396]
I try to follow the steps to add images from OneDrive by using the Excel Table. Nothing happens after I set Items = Jackets. I've tried it with different kinds of galleries (e.g. vertical or blank) but also noticed I see no "Image only control". Is there a step in the tutorial missing? Should it work with all galleries? Should we set it to image only in some way? Or specify the paths in the Excel table to the exact path of the Assets_images folder within OneDrive? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4ec8d3-8f91-d970-3722-133114c62f4a
* Version Independent ID: 5cae347b-2a12-f0f4-95e6-35abaa23cb8c
* Content: [Embed multimedia files into a canvas app and upload - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-images-pictures-audio-video#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/add-images-pictures-audio-video.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-images-pictures-audio-video.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your reaching out and your feedback. The content is updated. Please allow some time for changes to reflect.
