### ISSUE TITLE
How can you check if a global notification is visible on the screen?

### ISSUE THREAD

**Issue by bthompson-365** [MicrosoftDocs/powerapps-docs#1398]
With Form notifications, the notification is kept there until logic on the form removes the notification.

With global notifications it is possible for a user to dismiss the global notification but there is no method by which any business logic can identify whether a notification has been dismissed or not. Could you either:

add an event handler on notification close 
or add a getGlobalNotifications method to allow code to identify if a notification is still visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8176318c-56b8-7786-0d6c-29c1cf364c5a
* Version Independent ID: 657f9677-4861-7a29-4230-03a0301850e2
* Content: [Xrm.App (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-app)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-app.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@bthompson-365 Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
