### ISSUE TITLE
Please add a picture of the advanced find button 

### ISSUE THREAD

**Issue by denisem-msft** [MicrosoftDocs/powerapps-docs#1401]
New users will not know what the advanced find button looks like since it's just a filter icon. Please add a picture of the button as an example so new users can locate this and learn.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349c57f6-1804-db23-3c38-f4c9dc5adaf2
* Version Independent ID: 11943f1c-46af-e0ec-c834-fb796e31f844
* Content: [Advanced Find - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/advanced-find#feedback)
* Content Source: [powerapps-docs/user/advanced-find.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/advanced-find.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
@denisem-msft Thanks for the feedback. Topic has been updated and changes will go live within the hour.

Thanks,
Mints
