### ISSUE TITLE
fetchxml Results attribute

### ISSUE THREAD

**Issue by jamesnovak** [MicrosoftDocs/powerapps-docs#1402]
https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/template-tags#results-attribute
this section defines several additional attributes available from the Results attribute:
`Entities, EntityName, ExtensionData, MinActiveRowVersion, MoreRecords, PagingCookie, TotalRecordCount, TotalRecordCountLimitExceeded`
Only Entities seems to return any data.  I have tried the following example and cannot retrieve any of the Results attribute details:
```
{%- fetchxml contacts -%}
<fetch returntotalrecordcount="true">
  <entity name="contact" >
    <attribute name="firstname" />
    <attribute name="lastname" />
    <attribute name="contactid" />
    <filter type="and" >
      <condition attribute="statecode" operator="eq" value="0" />
    </filter>
  </entity>
</fetch>
{%- endfetchxml -%}
{%- if user -%}
    EntityName: {{-contacts.results.entityname-}}<br/>
    ExtensionData: {{-contacts.results.ExtensionData-}}<br/>
    MinActiveRowVersion: {{-contacts.results.MinActiveRowVersion-}}<br/>
    MoreRecords: {{-contacts.results.MoreRecords-}}<br/>
    PagingCookie: {{-contacts.results.PagingCookie-}}<br/>
    TotalRecordCount: {{-contacts.results.TotalRecordCount-}}<br/>
    TotalRecordCountLimitExceeded: {{-contacts.results.TotalRecordCountLimitExceeded-}}<br/>
    XML: {%-assign e=contacts.XML-%}{{-e | escape-}}
{%- endif -%}
```
I've tried changing the case of the attributes and even changing scope back to the contacts object, but no luck.  I tried assigning each to a variable then rendering the variable value, but no luck.

In the above example, only `contacts.XML` and `contacts.results.entities.size` render any information.

Do these attributes actually serve up data?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For issues, please contact support with a [support ticket](https://admin.powerplatform.microsoft.com/support) to help with the investigation/fix.
