### ISSUE TITLE
SQL queries return different result sets to FetchXML

### ISSUE THREAD

**Issue by bthompson-365** [MicrosoftDocs/powerapps-docs#1403]
It seems that plugins and rules are not being applied when I query data via TSQL rather than using a FetchXML report. As a test I have a preoperation plugin on multiple retrieve that is guaranteed to return zero results.

When that plugin is enabled a FetchXML request returns zero results, the TSQL request returns all records.

I can provide plenty of use cases where consistency is essential here - happy to provide them if needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by mayadumesh** [comment]
Yes, plugins are not part of current preview.  Making sure that plugins run will be a part of this endpoint at some point in the future. Today this is read-only access to the data as it exists without application of additional business processes that will change the data returned.

**Comment by bthompson-365** [comment]
@mayadumesh Could you add a short note to the current documentation to highlight the fact plugin support is currently missing but will appear at a later date?
