### ISSUE TITLE
Clarification of incremental terminology

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/powerapps-docs#1404]
Does this tool generate a full snapshot for each change? Or is it just changes? If it's just changes, how do you represent a deleted record in the T2 file? How frequently does this actually happen the document mentions "1 hour" but it's not specific. The another part says "Changes are pushed to the destination without you needing to set up refresh intervals.". If all I do is delete two records 5 minutes apart, what do I see in the data lake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771a2696-1d5a-88c0-299e-320d03a536c3
* Version Independent ID: 0b729e37-ce56-6d84-f44b-a22666776cec
* Content: [Export to data lake - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sama-zaki** [comment]
The answers to these questions are in the updated documentation.

**Comment by Mattp123** [comment]
@ElectricLlama - see the following article for information. 
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/azure-synapse-link-advanced-configuration

Closing issue.
