### ISSUE TITLE
Can we PLEASE have examples that don't include putting a password in the CODE???

### ISSUE THREAD

**Issue by jazmatician** [MicrosoftDocs/powerapps-docs#1405]
You really ought to be embarrassed making code samples that are so *horrifically* bad. NO ONE for any reason, at any time EVEN FOR AN EXAMPLE should put their password into the code. You should be demonstrating how to pop the AD Auth window and let the user provide their credentials at runtime!!!!! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62419bb8-985c-cb11-ac8d-2d018868c2a6
* Version Independent ID: db669ed7-d87b-c359-f5fb-3f2f1052281d
* Content: [Use OAuth with Common Data Service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth)
* Content Source: [powerapps-docs/developer/common-data-service/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/authenticate-oauth.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by TheShihan** [comment]
I too want to see an example, where no password credentials are used. Is there an example that shows us, how the already logged in user can access CRM data (Common Data Services Entities) by fetching his access token? Or is this not supported at all?

**Comment by phecke** [comment]
@jazmatician 

Yes, I agree. We are slowly updating our samples with code that prompts the user for credentials.
