### ISSUE TITLE
is .execute supported ?

### ISSUE THREAD

**Issue by xairrick** [MicrosoftDocs/powerapps-docs#1407]
The standard Xrm.WebApi  has .execute https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi and from the browser it appears like this method is available.  Can clarification be added as to whether or not the .execute method is supported in the PCF  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647866b2-563e-ffdd-ce84-f20feb839ca8
* Version Independent ID: 2397c27b-056e-de5b-0195-defdeff90718
* Content: [WebAPI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/webapi)
* Content Source: [powerapps-docs/developer/component-framework/reference/webapi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/webapi.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@xairrick Only API methods that are officially documented are only supported, even though you see them for the client API.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
