### ISSUE TITLE
Quick Create Form ID

### ISSUE THREAD

**Issue by logandersen** [MicrosoftDocs/powerapps-docs#1408]
When I set ["useQuickCreateForm"] to true, the ["formId"] parameter is ignored. Is this the expected behavior. I would love to be able to specify which quick create form when I have an entity with multiple quick create forms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b204ee0a-69a2-e52d-f110-2291be66c1af
* Version Independent ID: 8ac980df-6b5f-2b33-707f-11efb597ba6a
* Content: [openForm (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openform)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@logandersen Thanks for the feedback, we have a active bug for tracking this issue. Will update when we have a fix for it.

**Comment by Nkrb** [comment]
@logandersen The code should honor the `formId` parameter. The `openForm` methods when `QuickCreateForm` is set to` true` and `formId` value is passed, it should open up the desired form. Closing the issue.
