### ISSUE TITLE
Custom Command Bar Buttons on Dashboard in Unified Interface

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#1410]
For Custom Command Bar Buttons from Dashboard Homepage tab to be shown on the Dashboard in Unified Interface, we need to have FCB.DashboardCustomizableRibbon in the clientfeatureset and otherwise, the built-in UCI command bar will render regardless of customizations applied to the ribbon XML version.

Is there any particular reason why it is not documented and raising a support ticket is the only way to get it done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c87e100-fe6b-a001-31e6-5e29b82a4937
* Version Independent ID: 65f5f4e8-f4b7-0457-e449-000e7b8ccd1e
* Content: [Ribbons available in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/ribbons-available)
* Content Source: [powerapps-docs/developer/model-driven-apps/ribbons-available.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/ribbons-available.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@LinnZawWin The team didn't anticipate to get this error for most of the people and hence they came up with the idea to raise a support ticket. The team is now figuring it out and will update the docs accordingly. Closing the issue.
