### ISSUE TITLE
Update SAML 2.0 Azure AD 

### ISSUE THREAD

**Issue by nadgw** [MicrosoftDocs/powerapps-docs#1411]
Are the instructions for SAML 2.0 for Azure AD up to date ? After step 2 it takes me to App Registration blade then from there I can't find the fields to update in steps 4 onward. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15b7df3-dd92-cef2-f0cd-9a4274a9c5fc
* Version Independent ID: 6818fbbc-7255-3a2f-9d0e-d486b4f7d8af
* Content: [Configure SAML 2.0 provider settings for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings#feedback)
* Content Source: [powerapps-docs/maker/portals/configure/configure-saml2-settings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/configure-saml2-settings.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by nadgw** [comment]
Any update on this documentation ?

**Comment by tapanm-MSFT** [comment]
Please see the [updated documentation](https://docs.microsoft.com/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad).
