### ISSUE TITLE
Return only time value to Sharepoint list

### ISSUE THREAD

**Issue by Papithasekar** [MicrosoftDocs/powerapps-docs#1412]
how to return only time value to SharePoint list. 

Note: 
I have created 2 drop down list for hrs & mins and used formula 
Update = Hrs_dropdown1.selected value & ":" & Mins_dropDown2.Selected.Value  under time datacard. 
When submitting its not returning any value to SharePoint list, Tried only with hours drop down, then it works. But i need both hours and mins value in the format (HH:MM). 

Can you please help me to solve this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cf200f9-bbdc-edb4-79e2-f08839d2457b
* Version Independent ID: ca13a0df-20a7-c0f5-9597-1be7c2c7b042
* Content: [Show text, dates, and times in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/show-text-dates-times)
* Content Source: [powerapps-docs/maker/canvas-apps/show-text-dates-times.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/show-text-dates-times.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please contact support teams with a [ticket](https://admin.powerplatform.microsoft.com/support) to help with this investigation and resolution.
