### ISSUE TITLE
Can you have multiple Quick Create forms attached to the same entity?

### ISSUE THREAD

**Issue by bthompson-365** [MicrosoftDocs/powerapps-docs#1413]
This is connected to https://github.com/MicrosoftDocs/powerapps-docs/issues/1408 which asks about selecting a quick create form using NavigateTo. I always thought that although it's not imposed only 1 quick create form per entity was supported but that limitation doesn't seem to be mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7bb073-a27d-bddc-8366-aa101629fbbe
* Version Independent ID: 58052931-caec-f117-6246-cd1618993e43
* Content: [Create or edit model-driven app quick create forms in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-edit-quick-create-forms)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-edit-quick-create-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/create-edit-quick-create-forms.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@bthompson-365 - As per the topic, you can define multiple quick create forms but only one form can actually be implemented via the form order in your app. https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-edit-quick-create-forms#create-a-quick-create-form

Closing issue.
