### ISSUE TITLE
Consider changing screenshot in step 3

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/powerapps-docs#1414]
In step 3 under Create an application registration, the screenshot initially confused me.

I read the option **Accounts in this organizational directory only (Microsoft)** as meaning granting permissions to Microsoft rather than my own tenant. 

It might be clearer to replace the screenshot or edit this one to show wording such (Customer tenant - Single tenant) or (Contoso - Single Tenant)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40006b60-8da2-47ad-c86f-97c584b75b47
* Version Independent ID: 4cb0e004-092c-3da7-8c7f-306ee2f1f2df
* Content: [Walkthrough: Register an app with Azure Active Directory (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-register-app-azure-active-directory)
* Content Source: [powerapps-docs/developer/common-data-service/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@feridunkadir Thanks for the feedback. The image is being updated.
