### ISSUE TITLE
Updated List of Restricted Entities

### ISSUE THREAD

**Issue by PeteW-S365** [MicrosoftDocs/powerapps-docs#1415]
I have raised this Microsoft online Support (Dynamics 365 Team).
They have confirmed that the Restricted Entities above have been updated as per the latest release notes. Although the notice at the top of the page, stating that the document is out of date has not been removed yet in error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted entities requiring Dynamics 365 licenses - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Closing as this has been addressed.
