### ISSUE TITLE
More examples please

### ISSUE THREAD

**Issue by ianmckay-pmail** [MicrosoftDocs/powerapps-docs#1416]
More examples please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8bf3d3-12e3-5b55-8713-221cf5f5a30c
* Version Independent ID: 5a050d01-6ef6-97d6-07de-d5cac82dea06
* Content: [Combo box control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-combo-box)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Will consider the feedback for additional examples. Would also request to review [community forum](https://powerusers.microsoft.com/t5/Forums/ct-p/PA_Comm_Forums) for additional help or a [support ticket](https://admin.powerplatform.microsoft.com/support) for any issues that might need investigation.
