### ISSUE TITLE
Delegable Examples with Network Impact

### ISSUE THREAD

**Issue by JohnBJones** [MicrosoftDocs/powerapps-docs#1417]
It would be very useful to provide an example illustrating a delegable formula and showing the network traffic for both SQL and SharePoint when dealing with a data source which contains thousands of records and for which the formula will return hundreds of records and with tabular controls such as gallery.

In this example should the first n records be returned to populate the gallery then as the user scrolls through the gallery, the second batch of n records is returned with a further http request - effectively providing a mechanism for pagination?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e0bc1-6e4b-28ce-ba2f-00de8fcc6a86
* Version Independent ID: c670fff1-17d4-abf1-b2df-1da9250e552c
* Content: [Understand delegation in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-overview.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Your feedback is being considered for future updates. You can use [Monitor](https://docs.microsoft.com/powerapps/maker/monitor-canvasapps) to debug apps and review the network traffic.
