### ISSUE TITLE
openUrl Client API

### ISSUE THREAD

**Issue by PranjaliShetty** [MicrosoftDocs/powerapps-docs#1418]
Users need to add "openInNewWindow: true" to URLOptions for height and width to be respected.
Please clarify this on the article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db17acbe-9556-ab39-0963-b3d3856714de
* Version Independent ID: 569f08a4-26d1-696b-cdd0-822ffa948f17
* Content: [openUrl (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openurl#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openUrl.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openUrl.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@PranjaliShetty Thanks for contacting us. You don't need to specify the `openInNewWindow` parameter in order to honor the height and width. The height and width properties will be honored without the `openInNewWindow` parameter. Closing the issue.
