### ISSUE TITLE
ease of understanding...

### ISSUE THREAD

**Issue by gitralf** [MicrosoftDocs/powerapps-docs#1419]
GDPR requires in Art 12: concise, transparent, intelligible and easily accessible form, using clear and plain language. I don't think that this page is (in some parts) in clear and plain language, for example for adx-notification or __RequestVerificationToken. Also some of the cookies are labeled as only session-persistent, others are not labled like isDST* or timezone*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da589be-388b-95a2-1be0-d3d3de31d45a
* Version Independent ID: 795e86de-7b53-aebe-c63a-0280b1a57a42
* Content: [Cookies in Power Apps portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-cookies#feedback)
* Content Source: [powerapps-docs/maker/portals/admin/portal-cookies.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/portal-cookies.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **nenandw**

**Comment by gitralf** [comment]
Is anybody working on this? If you don't want to fix it, just say it and close the issue...

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content is being updated and will be published with the changes soon.
