### ISSUE TITLE
Cannot login as admin [Helpdesk sample app]

### ISSUE THREAD

**Issue by brodie90** [MicrosoftDocs/powerapps-docs#142]
I cannot login as an admin after putting my email address in the right section as per the guide. I checked that I had the correct format as some people have suggested and I've saved and reopened the app, but the issue still occurs. I've also tried with different accounts to no avail. Is there something I could be missing?

**Comment by AFTOwen** [comment]
@brodie90: What are you trying to sign in to? PowerApps? A particular sample app? Something else?

**Comment by brodie90** [comment]
Hi there, sorry I must have posted this in the wrong space. I was referring to the PowerApps Helpdesk canvas app (https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install). I can't seem to get the admin list to work at all and I'm confident I'm using the correct formatting.

**Comment by AFTOwen** [comment]
@brodie90 Thanks for your feedback, which is outside the scope of this documentation. Please post troubleshooting questions about the app itself in [the forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.” 

cc: @mr-dang-msft
