### ISSUE TITLE
Enum property definition is missing

### ISSUE THREAD

**Issue by lsuhadolnik** [MicrosoftDocs/powerapps-docs#1422]
There are no instuctions on how the Enum properties are defined. I found an explanation here: https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/How-declare-the-key-value-of-the-property-type-enum/td-p/285447

This should be added here somewhere.

By the way, is there an XSD schema for the manifest? Can you provide a link to it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b2e635-6c60-0efc-d894-e43216dca90e
* Version Independent ID: 9828125d-c061-465e-d486-b4ea609190e1
* Content: [Property Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/property.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@lsuhadolnik Thanks for the feedback, you should define the Enum data type as you do it for other data types as described in the doc. There is no Public XSD file available to the users. Closing the issue.
