### ISSUE TITLE
Please include domain *.azure-apihub.net should not block

### ISSUE THREAD

**Issue by srinivasdandu** [MicrosoftDocs/powerapps-docs#1424]
This is domain also used in the test connection while using the connector. Please added in the document.

**Comment by phecke** [comment]
@srinivasdandu Can you provide a link to the documentation that you were following when you came across this problem. Thanks

**Comment by tapanm-MSFT** [comment]
Closing the issue for now due to no response. Please respond when possible with the content link that this feedback is for, or feel free to create a new GitHub issue.
