### ISSUE TITLE
CDS for Code

### ISSUE THREAD

**Issue by CloudSmithBrandon** [MicrosoftDocs/powerapps-docs#1427]
Version 0.9 of CDS for Code - a VSCode extension for working with CDS assets is on the way.  Many from the CDS/PowerApps community have asked about a VSCode add-in, and may not know about this tool.

This extension brings:

- Full solution and app management capabilities to VS Code
- Code templating specific to CDS artifacts (plugins, PCF controls, web resources)
- Solution/control packing and unpacking, and soon Canvas App pack/unpack
- Web Resources and Plugin projects
- Data generation and testing framework
- Data export/import to/from CDS entities through VSCode

Current release (0.8.14) is here https://marketplace.visualstudio.com/items?itemName=CloudSmithConsulting.cds-for-code

New insider preview is expected to post by early June.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa856346-9a0f-9773-0faa-6dfacdb19d74
* Version Independent ID: 9bc4641c-49a4-d596-e39d-5ad5c2990cca
* Content: [Community tools for Common Data Service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/community-tools)
* Content Source: [powerapps-docs/developer/common-data-service/community-tools.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/community-tools.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Closing the issue.
