### ISSUE TITLE
By-Design behavior in Unified Interface

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/powerapps-docs#1430]
The Hierarchy Form "Account Hierarchy Tile form" on Account Entity loads only 3 fields in UCI whereas in Classic Web Client it loads 4 fields. 

The Hierarchy details are retrieved from form "Account Hierarchy Tile form" which contains 4 fields in it. In Classic Web Client, it shows up these 4 fields correctly when loading Hierarchy.

Repro steps (if it will be helpful for the audience to follow article, please add): 

1. Setup Hierarchy in Dynamics 365 Online Organization as stated in https://docs.microsoft.com/en-us/power-platform/admin/hierarchy-security#set-up-hierarchy-security.  

2. In Sales Hub, navigate to Account &gt; Open Account record "A Datum Corporation" &gt; In command bar, click on button "View Hierarchy".  

Cause: 

By-Design behavior in Unified Interface.  

 

Explanation:  

As per the current UCI behavior, this is by-design. However, this is a gap between UCI and legacy web client. UCI is not fully parity to web client yet.  

I understand, there is a feature request raised on this internally, but can we get this documented as well on this page, that is above behavior for now is by - design on UCI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97939d77-ee12-f8d2-8904-822c8130f303
* Version Independent ID: 863d3744-d5a0-6bd4-ab0d-03aeb66dabab
* Content: [Visualize hierarchical data with model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/visualize-hierarchical-data#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/visualize-hierarchical-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/visualize-hierarchical-data.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@HinaMS - Revised topic to state in the Important things to remember section: 
- The maximum number of fields that can be displayed in a tile is three with the Unified Interface and four with the legacy web client. If you add more fields to the Quick Form that is used for the tile view, only the first three fields will be displayed.

Also, in the example procedure further down the topic, which uses four fields in the tiles, I added a mention of the legacy web client: 
- In this form that will be used in a legacy web client app, we added four fields to display in each tile. 

Closing issue.
