### ISSUE TITLE
Preview.Error: The type of the current preview value is too complex to display.

### ISSUE THREAD

**Issue by Sudheerreddyn14** [MicrosoftDocs/powerapps-docs#1431]
Hi, encountered below error while reviewing Account data in Power BI desktop

![image](https://user-images.githubusercontent.com/37790033/82550628-776b6b80-9b7c-11ea-9a4b-53d91c31f25d.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d27f9-66bc-5cd2-d8b5-9defc8eddfb0
* Version Independent ID: c45841f0-1488-8c30-8a7c-3a522ec63266
* Content: [View entity data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi)
* Content Source: [powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Sudheerreddyn14 - You can post your issue with the TDS endpoint preview in the Common Data Service for Apps community forum: https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1 
Closing issue.
