### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by pratapladhani** [MicrosoftDocs/powerapps-docs#1433]
The link to image capture pro tips in the For more information section : https://powerapps.microsoft.com/blog/image-capture-pro-tips/ is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4ec8d3-8f91-d970-3722-133114c62f4a
* Version Independent ID: 5cae347b-2a12-f0f4-95e6-35abaa23cb8c
* Content: [Embed multimedia files into a canvas app and upload - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-images-pictures-audio-video#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/add-images-pictures-audio-video.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-images-pictures-audio-video.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated, please allow some time for changes to reflect.
