### ISSUE TITLE
Liquid group_by

### ISSUE THREAD

**Issue by garethcheyne** [MicrosoftDocs/powerapps-docs#1434]
Would be fantastic if you could inject a filterby field = value in to en entity list via liquid, to hard limit results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46dc750-10f1-6755-5ff0-86156b9db110
* Version Independent ID: d1335f42-fabb-61c0-5d38-a718b28d7a65
* Content: [Render the entity list associated with the current page in a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/render-entity-list-current-page#feedback)
* Content Source: [powerapps-docs/maker/portals/liquid/render-entity-list-current-page.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/liquid/render-entity-list-current-page.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please submit an idea on the Power Platform [ideas forum](https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas) about this feature ask.
