### ISSUE TITLE
On Lookup Click is great - is there an On Lookup Create Click? 

### ISSUE THREAD

**Issue by pritchie99** [MicrosoftDocs/powerapps-docs#1435]
Intercepting this event is great as it has been shown elsewhere that we can use addOnLookupTagClick to view/edit the selected record in a modal popup form instead of the default action which is to navigate away from the current form.  I can even leave the entityId undefined in the javascript and the form will allow me to create a new record rather than edit the existing record as shown here:-
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/customize-entity-forms#open-main-form-in-a-dialog-using-clientapi

I would really like to intercept the "New xxx" create link on the lookup drop down, which by default also navigates away to a new Create form, and replace that with a modal popup Create form.  Is this On Lookup Create Click event also able to be overridden? It seems logical that it could be, as it is complementary to this event which views the same form but for an existing record.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70e1590-7bc4-49c6-ed38-cca923430876
* Version Independent ID: 6eeec58b-d7b6-072f-9a6b-b4b6687ee3a8
* Content: [OnLookupTagClick Event (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/onlookuptagclick)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/onlookuptagclick.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/onlookuptagclick.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@pritchie99 Thanks for contacting us. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
