### ISSUE TITLE
Option to show or hide header on confirm dialog

### ISSUE THREAD

**Issue by imranakram** [MicrosoftDocs/powerapps-docs#1437]
Hi,
I'd like to suggest a feature to add option to Show/Hide header in the confirm dialog. Without title text the white space above looks quite ugly.

![image](https://user-images.githubusercontent.com/13014005/82677451-55d7b600-9c48-11ea-9c67-10557b584996.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77b84ce4-88fc-464e-4105-5cb9dde039ca
* Version Independent ID: 89d24260-1a80-e032-702e-b5ffa46d76af
* Content: [openConfirmDialog (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openConfirmDialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openConfirmDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openConfirmDialog.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@imranakram Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.

**Comment by imranakram** [comment]
Thanks @Nkrb, here's my post on ideas portal.
https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Bring-option-to-hide-header-in-Xrm-Navigation-openConfirmDialog/idc-p/587223#M30930
