### ISSUE TITLE
AuthValue missing format documentation

### ISSUE THREAD

**Issue by vcb-xrmvision** [MicrosoftDocs/powerapps-docs#1439]
I'm trying to update a webhook registration using Http Query String and I'm unable to find any documentation how can we update the query string of a web hook registration? 

ex. [appservicename].azurewebsites.net/api/[functionnmame]?code=[functionKey varies on each envir]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1c52b5-7ce7-4c40-fa51-e0ae06f20689
* Version Independent ID: a78001dc-865e-959b-73b9-4f1172a6727a
* Content: [ServiceEndpoint Entity Reference (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/reference/entities/serviceendpoint#BKMK_AuthType)
* Content Source: [powerapps-docs/developer/common-data-service/reference/entities/serviceendpoint.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/reference/entities/serviceendpoint.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.
 
Closing this issue.
