### ISSUE TITLE
Please add Q&A for SharePoint Site Address Update Effect on Custom Forms Created in Power Apps

### ISSUE THREAD

**Issue by yashpatel22** [MicrosoftDocs/powerapps-docs#1440]
Q: What happens to my Custom Form if I update my SharePoint Site Address?
A: You need to recreate the Custom Form after the site address change.
https://docs.microsoft.com/en-us/sharepoint/change-site-address#effects-of-changing-a-site-address

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated, please allow some time to reflect the changes.
