### ISSUE TITLE
No traces or Logs visible in Application Insights

### ISSUE THREAD

**Issue by shrikantdatke** [MicrosoftDocs/powerapps-docs#1441]
Hello,

I have followed all the steps given in this document, but I see no traces or Logs visible in Application Insights. I am sure I have properly added Instrumentation Key in the Power Apps, App Object.

I have been waiting for more than 2 hours, but no logs or events visible. I even don't see the Users in Usage instead I see "Your app needs to send custom events or page views to Application Insights to use these tools."

What I am really missing here? Can you please help?

Thanks,
Shrikant
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93af67a-9f3c-97fd-2899-2045c9f7e349
* Version Independent ID: 1cb12077-eec7-45cd-fe7e-fb10fa5c1936
* Content: [Analyze app telemetry using Application Insights - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/application-insights)
* Content Source: [powerapps-docs/maker/canvas-apps/application-insights.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/application-insights.md)
* Service: **powerapps**
* GitHub Login: @aengusheaney
* Microsoft Alias: **aheaney**

**Comment by aengusheaney** [comment]
Hi Shrikant, 

Did you publish your app after updating the App Insights key? Also, the events will only get logged to App Insights when you play the published app. If you have already done this, could you provide the appid which you have associated your App Insights key to, and also we can set up a quick call to discuss further. 

Thanks!
Aengus

**Comment by shrikantdatke** [comment]
Hello Aengus,

Thanks for writing me back. Yeah I am 100% sure that I have updated the correct App Insight key. So is the reason I am bit confused about why it doesn't work, and yes even after Publishing and playing the app. And my is very simple, has a "Hello World" label on the screen. Whereas following your article I have   written a simple code on the App Start 

_/*Configuration variables */
Set(
    gbluserinfo,
    {
        userName:User().FullName,
        userEmail:User().Email
    }
);

Trace(
    "User Login",
     Information,
    {
        UserName: gbluserinfo.userName,
        UserEmail: gbluserinfo.userEmail,
        Screen:App.ActiveScreen.Name,
        Control: "App.Onstart"
    }
    );

Trace("Demo",TraceSeverity.Information);

I am definitely missing something and if you can please help me to identify the same. I can share more details over the call if you can connect me on my number +91-9822516026

**Comment by aengusheaney** [comment]
It looks good. Can you email me on aheaney@microsoft.com and i will schedule a teams call. Thx, Aengus

**Comment by shrikantdatke** [comment]
Hi Aengus,

I have sent you the meeting invite. Ready when you are.

**Comment by aliyoussefi** [comment]
I'm interested in following this one @aengusheaney. @shrikantdatke I believe you opened a similar issue in my github repo. Did you resolve your issue?

**Comment by shrikantdatke** [comment]
Thanks Aengus, for helping to sort this out and some other great tips with Monitoring. Waiting for more excited PowerApps - Monitoring releases.
