### ISSUE TITLE
OnSelect function Export button doesn't work 

### ISSUE THREAD

**Issue by joseabadg** [MicrosoftDocs/powerapps-docs#1442]
OnSelect function Export button doesn't work  on Android and before and after save the package, the code not executed at all.

https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-export-import

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please contact support with a [ticket](https://admin.powerplatform.microsoft.com/support) to investigate the problem.
