### ISSUE TITLE
Information on ADAL is outdated

### ISSUE THREAD

**Issue by timrobinson33** [MicrosoftDocs/powerapps-docs#1443]
the information on ADAL seems out of date. According to this link: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet ADAL v2 is no longer supported at all, and ADAL generally has been superseded by MSAL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62419bb8-985c-cb11-ac8d-2d018868c2a6
* Version Independent ID: db669ed7-d87b-c359-f5fb-3f2f1052281d
* Content: [Use OAuth with Common Data Service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth)
* Content Source: [powerapps-docs/developer/common-data-service/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/authenticate-oauth.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@timrobinson33  The documentation has been updated to use the latest ADAL and MSAL authentication libraries.
