### ISSUE TITLE
Wrong Information on step 6 under "Step 1: Add or update search site settings"

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/powerapps-docs#1444]
In the step 6 under the step "Step 1: Add or update search site settings", from your sample it looks like we have to use the entity collection name, but this would lead the the error "Error getting EntityMetadata for <entitycollectionname>". We have to use the entity logical name instead. Please clarify what is the proper metadata to use here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fc0169-247f-15d5-44ee-be841d655127
* Version Independent ID: a08847b8-e801-987f-1288-2d1acb9f7ef7
* Content: [Global search for additional entities in Power Apps portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/search-additional-entities)
* Content Source: [powerapps-docs/maker/portals/configure/search-additional-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/search-additional-entities.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The walkthrough tip at the [beginning](https://docs.microsoft.com/powerapps/maker/portals/configure/search-additional-entities#walkthrough---configure-search-for-additional-entities-with-sample-database) mentions:

*You can follow the walkthrough with an entity of your choice by replacing the nwind_products entity name with your **entity's logical name**.*
