### ISSUE TITLE
What if enable MR is not available?

### ISSUE THREAD

**Issue by MMT0905** [MicrosoftDocs/powerapps-docs#1446]
When I first tried this, the feature was not available in my Power Apps tenant. After removing the subscriptions and then adding back my subscriptions, it appeared to update my tenant, and this feature is now available. It may be useful to make a note for others to do the safe if they don't see the MR under experimental features. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48c259a6-5278-3c22-6a02-37b594b1ab05
* Version Independent ID: 27b64d6f-9ced-7137-d419-9ba0143d4fa6
* Content: [Use mixed reality components in Power Apps (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/mixed-reality-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/mixed-reality-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/mixed-reality-overview.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Closing as this MR features are now GA and no longer require the experimental feature to be turned on.
