### ISSUE TITLE
Needed to change the OrgDBOrgSettingsTool_SKU node to 'Online' for it to work for me.

### ISSUE THREAD

**Issue by CRMconsultUK** [MicrosoftDocs/powerapps-docs#1447]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d27f9-66bc-5cd2-d8b5-9defc8eddfb0
* Version Independent ID: c45841f0-1488-8c30-8a7c-3a522ec63266
* Content: [View entity data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi)
* Content Source: [powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by CRMconsultUK** [comment]
Following the instructions still caused an error, but changing OrgDBOrgSettingsTool_SKU to 'Online' worked for me.
Also adding my credentials in to OrgDBOrgSettingsTool_UserName
Neither are mentioned in the documentation.

**Comment by Mattp123** [comment]
@CRMconsultUK - Thank you for your feedback. The procedure to opt in to the feature has been significantly simplified as per the recently updated topic referenced in this issue. Closing issue.
