### ISSUE TITLE
Please add an example showing how to download File data using OrganizationService

### ISSUE THREAD

**Issue by fberasategui** [MicrosoftDocs/powerapps-docs#1448]
As the title suggests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c3eac9-b083-b974-0938-3e8fd19bbb58
* Version Independent ID: 2c6dfac6-25b8-876c-2b94-fa9d466007df
* Content: [File attributes (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/file-attributes)
* Content Source: [powerapps-docs/developer/common-data-service/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/file-attributes.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@fberasategui The File column topics have been updated with new content. Please take a look again.

[File columns](https://learn.microsoft.com/power-apps/developer/data-platform/file-attributes?tabs=sdk)
