### ISSUE TITLE
Instructions unclear/incorrect 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/powerapps-docs#145]
the instructions to use the advanced editor for CDS are unclear 

    Within the Advanced customizations panel, choose one of the following options:
    To work in your Common Data Service default solution, select Open solution explorer below Customize.

following the instruction I am able to open the 'Advanced Customizations Panel' but no matter in what context I try this , there is no 'Open Solution Explorer'

Can you please clarify ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b49ff2-7bd7-fcb8-0e27-6768f69eeecc
* Version Independent ID: dc9fa852-e27a-b037-80fe-f1192b2b4348
* Content: [Create and edit entities using solution explorer - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-edit-entities-solution-explorer)
* Content Source: [powerapps-docs/maker/common-data-service/create-edit-entities-solution-explorer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-edit-entities-solution-explorer.md)
* Service: **crm-online**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Thank you for your feedback. The steps to open solution explorer have changed. Below are the steps. PowerApps topics that include the old steps have been updated.
Navigate to an unmanaged solution
1. From the PowerApps portal select Solutions, and then on the toolbar, select Switch to classic.
2. In the All Solutions list select the unmanaged solution you want.
