### ISSUE TITLE
should mention XRM

### ISSUE THREAD

**Issue by timrobinson33** [MicrosoftDocs/powerapps-docs#1450]
Its says "we don't provide assemblies for a specific developer experience", but as far as I can tell, the XRM SDK is exactly this. Maybe the "we" who authored this section is different from the group that developed the XRM Libraries but it would certainly be useful to many readers to at least indicate the existence of the XRM at this point.

**Comment by Nkrb** [comment]
@timrobinson33 Can you point us to the doc you're talking about, so that we can assign it to appropriate person.

**Comment by timrobinson33** [comment]
Sorry I thought I clicked to leave feedback on the specific page. it's this one

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/overview

the third paragraph in the top section

**Comment by phecke** [comment]
@timrobinson33  The Xrm Tooling capability in our SDK is for use with the 2011 SOAP endpoint. Web API applications do not use the SDK assemblies. Thanks for your feedback.
