### ISSUE TITLE
Include information about columns that may contain unicode characters

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1451]
See https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/define-alternate-keys-entity

> Unicode characters in key value
> If the data within a field that is used in an alternate key will contain one of the following characters /,<,>,*,%,&,:,\\ then get or patch actions will not work. If you only need uniqueness then this approach will work, but if you need to use these keys as part of data integration then it is best to create the key on fields that won't have data with those characters.

I think you should include something about this within this topic. Otherwise people may be surprised that they can't retrieve or update entities with these alternate keys.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a85bf2-05d9-12a9-1b62-71efe01d06eb
* Version Independent ID: a0dde9ac-af6a-2235-f7a2-9acbf514611c
* Content: [Define alternate keys using Power Apps portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/define-alternate-keys-portal)
* Content Source: [powerapps-docs/maker/common-data-service/define-alternate-keys-portal.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/define-alternate-keys-portal.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@JimDaly - Thanks for your feedback. I added this to the _Define alternate keys using Power Apps portal topic and it will be published live within a few hours. Closing issue.
