### ISSUE TITLE
Should the API Permissions be updated to "PowerApps Runtime Service?"

### ISSUE THREAD

**Issue by HarryGifford** [MicrosoftDocs/powerapps-docs#1453]
There is a PowerApps API with prefix `http://rts.powerapps.com/`, which contains a `user_impersonation` permission for the Common Data Service. Is it a drop in replacement for the Dynamics CRM API? I noticed that the `docs` link points to the newer [PowerApps CDS Overview](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/overview) page.

Should the docs be updated to use the PowerApps API permission?

Here's what it looks like in the Azure Portal:
![image](https://user-images.githubusercontent.com/21968002/82942568-009feb00-9f4d-11ea-9604-8f4251ff6308.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40006b60-8da2-47ad-c86f-97c584b75b47
* Version Independent ID: 4cb0e004-092c-3da7-8c7f-306ee2f1f2df
* Content: [Walkthrough: Register an app with Azure Active Directory (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-register-app-azure-active-directory)
* Content Source: [powerapps-docs/developer/common-data-service/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@HarryGifford  We have no information on such an endpoint. You should follow the instructions in our developer documentation.

Thanks
