### ISSUE TITLE
List of connectors supporting Guest Access

### ISSUE THREAD

**Issue by hitendra72** [MicrosoftDocs/powerapps-docs#1454]
Hi

In the document ref sharing apps with guests (https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#share-with-guests), there is a table of connectors supporting Guest Access

In this table, CDS is marked as "No", i.e. CDS does not support guest access

But in actual practice, it is found CDS does support guest access. Here's a blog which talks of this. https://powerplatform.se/azure-guest-accounts-in-cds-dyn365/

Can we update the table in the documentation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c12582-519a-606c-1f2e-8fe1f6ac5d2a
* Version Independent ID: 537b3097-4aa4-f3e5-b252-ffb832ecb1dc
* Content: [Share a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#share-with-guests)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. Documentation is updated. Please allow some time for changes to reflect.
