### ISSUE TITLE
Power Apps Component Library Share Issue

### ISSUE THREAD

**Issue by unlimitedduck** [MicrosoftDocs/powerapps-docs#1455]
I've created a Brand Color Component library in Power Apps for work and then shared via the "Everyone" option set as a user.  Come to find out that is not working.  I thought maybe something work did and I tried it out on my personal developer account and same thing.  @yifwang do you have any insight since you have written and co-shared on the Power Apps Component piece why share with "Everyone" is not working.  Can this also be fixed any time soon?

Thank you.

**Comment by yifwang** [comment]
Hi @unlimitedduck, do they not show when you open "Get more components" and try to insert to your apps? I'm still seeing components shared with me. Please provide some details such as your app ID and App session. It will help with debug. Thanks!

**Comment by unlimitedduck** [comment]
@yifwang thank you for responding.  I won't be able to share app id and app session for my company will not allow.  I could possible share later my developer account app id and app session.  Do explain further.  When a user creates a canvas app and then when they go into the insert pane and at bottom select "Get more components" the pop up opens for components but the library component that is shared with "Everyone" does not show.  What's interesting if you go to the apps screen and click the components library they do see it there, but not when they try to access via an app they built.  Also, when I change the permission to the person directly and not "Everyone" then it does show in the pop up for that person(s).  This is not ideal for really not ideal to have to add 14K+ for access.  Let me know if this helps or still need more info.  I'm willing to do a teams meeting if you are willing to meet.  Thank you

**Comment by phecke** [comment]
@unlimitedduck Please provide a link to the documentation that is related to what you are trying to do. Thanks

**Comment by unlimitedduck** [comment]
@phecke here is the link to the white paper:  [https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/component-library#component-library-permissions] 
 and link to what is on github: [https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/component-library.md]

I have also added a document showing what is taking place.
[Component Library issue.docx](https://github.com/MicrosoftDocs/powerapps-docs/files/4705150/Component.Library.issue.docx)

Please let me know if this issue could be remedy soon.  If possible what type of time frame we could be looking at.  Thank you for your time in this matter.

**Comment by yifwang** [comment]
@unlimitedduck That's odd and thanks for the detail. It's something new, we haven't seen similar behavior. Do you see this in one tenant or multiple tenants? Also, when you share the library, does it work if instead of "Everyone" add a few specific email alias? I think Everyone in sharing is supposed to be Everyone in an alias group, what does it do if you try Everyone in different alias groups? Trying to gather some info here. And yes when it works, libraries should be the easy place you can create and publish updates to components and other makers can receive the updates.

**Comment by unlimitedduck** [comment]
@yifwang I found that on work tenant and my personal developer tenant is the same.  That's how I tested my theory for work tends to have more restrictions than a full access developer tenant account.  If I just put in someones name than it works.  This is both in work tenant and developer tenant account.  Tried to see if would pick up on O365 Teams Groups but Power Apps doesn't recognize them.  I'm hoping everyone helping on this can resolve this soon for as stated before such an awesome addition and time saver for all.

**Comment by yifwang** [comment]
Hi @unlimitedduck , it's probably something with sharing. Here is my screenshot of sharing. Type everyone gives a list of groups to share. Does this look similar? I will report your case to the team and they will investigate and get in touch with you. Thanks!

![image](https://user-images.githubusercontent.com/23063489/83693543-252e3f80-a5ab-11ea-8c77-58978fa3b3e7.png)

**Comment by unlimitedduck** [comment]
@yifwang this is what it looks like for both developer account and work account:

![DeveloperAcctIconViewEveryone](https://user-images.githubusercontent.com/65996048/83701356-43ea0180-a5be-11ea-8808-2f018ba1d2fd.png)
![WorkAcctIconViewEveryone](https://user-images.githubusercontent.com/65996048/83701366-4cdad300-a5be-11ea-88c1-a1d9b34d87c0.png)

Let me know if this sheds extra light on the situation since the icons are different but the rest is the same.  Will look to your reply if will need support ticket.  Thank you for all your time on this for just really want to be able to share across my organization wonderful solutions in Power Apps.

**Comment by unlimitedduck** [comment]
Update -  Seems currently the only way a Library Component can be utilized by others is you have to share it individually.  It is acting the same way as a canvas app.  The "Everyone" only allows one to share it for use.  Hopefully there could be a future update where one could share it with a group membership so you wouldn't have to keep giving individual permissions on a Component Library build.  Especially if you have a company 14K+ and don't know could utilize it vs. opening it up.
