### ISSUE TITLE
The RequestHide function is not documented

### ISSUE THREAD

**Issue by gregli-msft** [MicrosoftDocs/powerapps-docs#1458]
No mention in the function list [https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/formula-reference](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/formula-reference) and no corresponding reference article.  What does it do?  Does it only work in a SharePoint form?  Does it error outside of this context?  Why isn't it on the SharePoint integration object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc8c866-e0da-7e25-7419-43ece1ff6b6e
* Version Independent ID: 918ae4ef-a2b4-6542-6df0-6f3d3d6ed1e5
* Content: [Understand SharePoint forms integration - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-form-integration)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-form-integration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sharepoint-form-integration.md)
* Service: **powerapps**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The documentation has been updated and [RequestHide()](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-requesthide) function details are added. Please allow some time for the content to reflect the added topic.
