### ISSUE TITLE
Multi-language support for external-facing entities on Portals? 

### ISSUE THREAD

**Issue by davenull311** [MicrosoftDocs/powerapps-docs#1459]
It is my understanding that separate translated webpages can be displayed based on the user's preferred language selections, but because an external user does not have a license for the system, the labels/views/etc. that would be translated for users within the system still display as the default language to those external users. 

Does the DTS translation apply to external Portals users, or is there a way to turn that on? 

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67340585-2c0a-3d95-780a-0233412f4ee1
* Version Independent ID: 71fedbf9-60fd-4b92-1356-3f72698029e9
* Content: [Enable multiple-language portal support - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/enable-multiple-language-support)
* Content Source: [powerapps-docs/maker/portals/configure/enable-multiple-language-support.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/enable-multiple-language-support.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by davenull311** [comment]
Hi - just wanted to follow up on this and see if there was any additional info that I could provide to help get a resolution. Thanks!

**Comment by tapanm-MSFT** [comment]
Hi @davenull311, thank you for reaching out. [Additional language](https://docs.microsoft.com/powerapps/maker/portals/configure/enable-multiple-language-support) and [localized content](https://docs.microsoft.com/powerapps/maker/portals/configure/enable-multiple-language-support#create-content-in-multiple-languages) can work for both internal and external users. If this doesn't work, it needs to be investigated. Please reach out to the support team with a [service request](https://admin.powerplatform.microsoft.com/support) for investigation.
