### ISSUE TITLE
Sorry we didn't find that app error

### ISSUE THREAD

**Issue by mjohnsonebecs** [MicrosoftDocs/powerapps-docs#146]
I get the following error when following the steps provided here. "Sorry we didn't find that app" Session ID: 9a39aba4-57de-4d19-b927-eda41ceff77e
When creating the Canvas app I can see the data from the entity in Dynamics which leads me to believe up to the point of publishing, it is all working as expected. After save and publish of the app and the form in D365 I get this after about 2 seconds of the app trying to load in the section on the form.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d21a753e-4f2f-941f-8ec9-40891a5ebbe6
* Version Independent ID: 63740fcb-c081-6225-9fc5-8600c03125fb
* Content: [Pass the current record as data context with an embedded canvas app - PowerApps](https://docs.microsoft.com/en-gb/powerapps/maker/model-driven-apps/pass-current-embedded-canvas-app)
* Content Source: [powerapps-docs/maker/model-driven-apps/pass-current-embedded-canvas-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/pass-current-embedded-canvas-app.md)
* Service: **crm-online**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by aneesmsft** [comment]
Were you using the same user/account to see at run time as authoring? If you were, can you check to see if the app was created in the right solution (same as the form it is embedded in)?

**Comment by mjohnsonebecs** [comment]
>           Were you using the same user/account to see at run time as authoring? If you were, can you check to see if the app was created in the right solution (same as the form it is embedded in)?

When I came to investigate this today it has started to work as expected. I didn't change anything. Thanks for your suggestion anyway but I guess it just sorted itself out with some time.
