### ISSUE TITLE
Information in wrong place

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1460]
This section, about working with Attribute metadata should include information about, well, 'working with attribute metadata'.

Instead, it includes information about how to work with file data...a very different thing.

Data operations (Retrieve, Upload, and Delete) should be split and put along with other similar content.

SDK examples should be here: 
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/entity-operations

Web API information should be here:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/perform-operations-web-api

Same is true for other (to a different degree) for other topics in this area:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/image-attributes
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/multi-select-picklist

At a minimum, there should be sections in the respective navigation topics to guide people to these examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c3eac9-b083-b974-0938-3e8fd19bbb58
* Version Independent ID: 2c6dfac6-25b8-876c-2b94-fa9d466007df
* Content: [File attributes (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/file-attributes)
* Content Source: [powerapps-docs/developer/common-data-service/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/file-attributes.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@JimDaly Fixed, by you.
