### ISSUE TITLE
Input.xml have to be with capital letter

### ISSUE THREAD

**Issue by JannyM85** [MicrosoftDocs/powerapps-docs#1463]
Hi, i published new product, and I got error about missing file Index.xml. On this page is file name with lower letter but it has to be with capital letter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2af3070-30b8-395e-ea51-86e954e3b006
* Version Independent ID: c1e95af9-6261-7da1-07ce-1b8986ef3738
* Content: [Step 3: Create an AppSource package for your app (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-package-app-appsource)
* Content Source: [powerapps-docs/developer/common-data-service/create-package-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/create-package-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
This is fixed now; closing the issue.
