### ISSUE TITLE
getNamedReference does not return EntityReference shape

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#1465]
The shape of the response from getNamedReference does not appear to be of EntityReference.
The Id is a simple string and there is no etc property - instead, it is LogicalName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bf4fead-c302-ba17-c36c-785976c2df87
* Version Independent ID: 19655865-7c82-8d37-ccda-6d60436f5528
* Content: [getNamedReference - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/entityrecord/getnamedreference)
* Content Source: [powerapps-docs/developer/component-framework/reference/entityrecord/getnamedreference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/entityrecord/getnamedreference.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by scottdurow** [comment]
It is worth noting that the PCF Samples use `dataset.openDatasetItem(dataset.records[event.recordId].getNamedReference())` - so the dataset.openDatasetItem also expects the shape {Id:string, LogicalName: string}

**Comment by scottdurow** [comment]
Any progress on this?

**Comment by Nkrb** [comment]
@scottdurow Closing this issue. If you need further help, please reopen or create a new issue.

**Comment by ziacik** [comment]
Wow.
