### ISSUE TITLE
Why has DetailForm screen been removed?

### ISSUE THREAD

**Issue by glenr4** [MicrosoftDocs/powerapps-docs#1466]
Hi,
I am trying to follow this tutorial but it looks like the DetailForm screen has been removed. The only option for a Form is an Edit form. Is there any reason for this? The Edit form takes quite a bit of customisation to be readonly.

Is this a mistake? Am I missing something?

![image](https://user-images.githubusercontent.com/15870389/83339901-8937d600-a315-11ea-8a5c-5a5edf5c0ba4.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde021b1-2aa0-b8ca-7ca9-3889d9a34a57
* Version Independent ID: 438b1685-d3eb-a8d5-7813-8a1423f92598
* Content: [Customize a form in a canvas app - Power Apps](https://docs.microsoft.com/en-au/powerapps/maker/canvas-apps/customize-forms-sharepoint)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-forms-sharepoint.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-forms-sharepoint.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please follow the [prerequisites](https://docs.microsoft.com/powerapps/maker/canvas-apps/customize-forms-sharepoint#prerequisites) for this tutorial first. The DetailForm1 is available in the tree view on the left inside the DetailScreen1 (after following prerequisites).
