### ISSUE TITLE
Canvas apps integrated into websites and other services cannot be accessed in Firefox and Chrome

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerapps-docs#1468]
The comments below were machine translated
Moved from: https://github.com/MicrosoftDocs/powerapps-docs.zh-cn/issues/5

@Risin9 commented 21 hours ago 

Canvas apps integrated into websites and other services cannot be accessed in Firefox and Chrome

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 559b4613-fbe0-45dc-f8bf-ff3a70b5f66e
* Version Independent ID: 36921b82-2295-8d26-9be0-d2d23ee11ab7
* Content: [Integrate canvas apps into websites and other services - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-apps-dev)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-apps-dev.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/embed-apps-dev.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Risin9** [comment]
Thank you very much for your help. 
It's my problem. I used this in the local development environment. The local development environment can't be displayed. It's OK in the test / production environment
Thank you for your attention！

**Comment by Risin9** [comment]
But it's strange,
It's OK in IE11 in my local development environment, but Firefox and Chrome can't work normally. which is why I didn't realize it was the development environment at first and mistakenly thought it was the browser

**Comment by Nkrb** [comment]
Closing the issue. If you need further help, please reopen or create a new issue.
