### ISSUE TITLE
Outdated information on the page

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/powerapps-docs#1471]
Hi,

following section seems to be outdated. The read operations are supported (s. section "User and support-related events" in https://docs.microsoft.com/en-us/power-platform/admin/enable-use-comprehensive-auditing)

Not supported for auditing
The following lists what cannot be audited for Common Data Service:
Audit of read operations
Audit of metadata changes

Regards,
Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7eca476-edd9-e73e-fd07-7e000b9a6ef8
* Version Independent ID: e69062b0-f865-7cdf-be53-a1db50af5d05
* Content: [Auditing Overview (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/auditing-overview)
* Content Source: [powerapps-docs/developer/common-data-service/auditing-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/auditing-overview.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@soutchilin The developer topic has been changed to show how to query for the tables and columns that can be audited.

[Detect which tables are enabled for auditing](https://docs.microsoft.com/power-apps/developer/data-platform/auditing/configure?tabs=webapi#detect-which-tables-are-enabled-for-auditing)
