### ISSUE TITLE
Custom list form download issue in Chromium 83

### ISSUE THREAD

**Issue by Stevef1** [MicrosoftDocs/powerapps-docs#1474]
Is there any update on the first issue - problems downloading custom list form attachments in Chromium 83? The workaround of changing the list form is cumbersome for the use case of my users.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b83052-49f1-5a09-7aba-9f0d5046d850
* Version Independent ID: 0289a85b-fc50-bf14-4474-31d434e16e20
* Content: [Common issues and resolutions for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/common-issues-and-resolutions)
* Content Source: [powerapps-docs/maker/canvas-apps/common-issues-and-resolutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/common-issues-and-resolutions.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The issue has been updated as of 6/21 with fix available for Microsoft Edge based on Chromium with version 85.
