### ISSUE TITLE
Context should have recordId to represent GUID of the record showing in a form for model driven app

### ISSUE THREAD

**Issue by keijiinoue** [MicrosoftDocs/powerapps-docs#1475]
[Enter feedback here]
Context should have recordId property to represent GUID of the record showing in a form for model driven app.
Some components listed in PCF Gallery are using hidden or unofficial property in order to identify the recordId. Official property should be provided for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f219919-646d-18e5-2766-365f34aea315
* Version Independent ID: de311f39-0493-955f-d3fb-7b38071b5ab9
* Content: [Context - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/context)
* Content Source: [powerapps-docs/developer/component-framework/reference/context.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/context.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by keijiinoue** [comment]
This is same thinking of the following idea:
https://powerusers.microsoft.com/t5/Power-Apps-Ideas/GUID-type-support-for-PCF-controls/idi-p/353093

**Comment by Nkrb** [comment]
@keijiinoue Thanks for the suggestions. Please log your request [here](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas/label-name/powerapps%20component%20framework%20(pcf)/tab/most-kudoed). Closing the issue.
