### ISSUE TITLE
What happens when calling `addPreSearch` multiple times?

### ISSUE THREAD

**Issue by skfd** [MicrosoftDocs/powerapps-docs#1478]
Could you clarify in docs what happens when calling `addPreSearch` multiple times?
Does previous callback gets overwritten? Are they get stacked somehow?

Also is there a way to do `removeAllPreSearch`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b467682f-01ec-4b4f-7949-9119d4c5c3da
* Version Independent ID: bd678329-b0c1-a298-0597-efa3d18bd849
* Content: [addPreSearch (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addpresearch)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addPreSearch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addPreSearch.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@skfd There is a `removePreSearch` method, but not the `removeAllPreSearch`.  It's like any other event, if you call the `addPreSearch`  multiple times then there will be multiple handlers.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
