### ISSUE TITLE
GetAccessToken method definition is not present

### ISSUE THREAD

**Issue by niagrawa** [MicrosoftDocs/powerapps-docs#1479]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16e7478f-bfd9-607d-c5fa-2e9af28302ab
* Version Independent ID: d8e1b97b-301d-9353-b279-a72354ffa8f2
* Content: [Global Discovery Service Sample (C#) (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/samples/global-discovery-service-csharp)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/samples/global-discovery-service-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/samples/global-discovery-service-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by RedsGT** [comment]
Hi @niagrawa 

These are just snippets that call out main parts of the code.  The actual sample code has the definition.

**Comment by JimDaly** [comment]
Correct. 
The code focuses on the use of the discovery service. The GetAccessToken method is mostly about authentication, so it isn't the focus of the sample. The method is available in the sample code. It is actually quite a bit larger than the code to use the discovery service, so it isn't included in the snippet.
