### ISSUE TITLE
OLEDB Connection Error

### ISSUE THREAD

**Issue by HarpreetHans** [MicrosoftDocs/powerapps-docs#1480]
I am not able to connect SQL endpoint for CDS using Oledb Connection. I am getting following Error:
![image](https://user-images.githubusercontent.com/57860361/83962821-f2cd5c80-a8a0-11ea-9baa-19e065d66a3b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by mayadumesh** [comment]
TDS endpoint over CD is not available for the Oledb connection. the error is expected for this access point.
