### ISSUE TITLE
Getting not a function error when using code snippet in Document 

### ISSUE THREAD

**Issue by manishdvmske** [MicrosoftDocs/powerapps-docs#1481]
Hi ,
Greetings, 
I was using below js given on the page to restrict create from BPF but was getting "formContext.data.process.getActiveStage.getNavigationBehavior is not a function"

Then I debugged and found below, 

Instead of  "formContext.data.process.getActiveStage.getNavigationBehavior()"  I tried using "formContext.data.process.getActiveStage().getNavigationBehavior()" and it worked

Although I am getting formContext.data.process.getActiveStage().getNavigationBehavior().allowCreateNew as undefined  May be due to cross -- entity.

Please let me know if any suggestion. thanks 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5d070a-1149-83b5-1168-abbb358f8a35
* Version Independent ID: 54688bb7-47b9-36f1-29ef-b303e1763b39
* Content: [getNavigationBehavior (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/stage/getnavigationbehavior)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/stage/getNavigationBehavior.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/stage/getNavigationBehavior.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@manishdvmske 
Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
