### ISSUE TITLE
Document Templates

### ISSUE THREAD

**Issue by AbdulWahabWarind** [MicrosoftDocs/powerapps-docs#1483]
Documentation we receive from the organization often uses different logos and fonts. I need branding for all internal Microsoft Word documents.
Which two templates can I use?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41509cd6-cd9c-aaf4-787b-d86c5d7bdba6
* Version Independent ID: 2468f38b-cc54-ea77-4298-daa91e9ed3b3
* Content: [Work with Excel and Word templates - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/templates-overview)
* Content Source: [powerapps-docs/maker/model-driven-apps/templates-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/templates-overview.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@AbdulWahabWarind  - The templates feature is for populating Word and Excel documents with CDS or Dynamics 365 Customer Engagement apps data. If you want to pre-populate your Word template with other kinds of data you can try adding definitions for them in your Word template as described here: https://support.office.com/en-us/article/save-a-word-document-as-a-template-cb17846d-ecec-49d4-82ea-a6f5e3e8b9ae and then add the additional definitions for the CDS/Dynamics 365 data. 

Closing issue.
