### ISSUE TITLE
View collection

### ISSUE THREAD

**Issue by Papithasekar** [MicrosoftDocs/powerapps-docs#1484]
Is it possible to view collected data in collection in display form? or we should only Gallery form to view collected data from Collection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b41c74e-0619-2d16-694d-f2be4b594e1b
* Version Independent ID: acd46b62-b793-1bbf-dbfc-2fea6d1ce1b6
* Content: [Create and update a collection in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-update-collection)
* Content Source: [powerapps-docs/maker/canvas-apps/create-update-collection.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-update-collection.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by Nkrb** [comment]
@Papithasekar Thanks for contacting us. Display forms only shows one record at a time. If your collection has multiple records, it always a best option to use the gallery. Closing the issue. If you need further help, please reopen or create a new issue.
