### ISSUE TITLE
Incorrect word - classes instead of functions

### ISSUE THREAD

**Issue by once** [MicrosoftDocs/powerapps-docs#1487]
Incorrect: 
_When you open the index.ts file in the Visual Studio Code, you'll notice that the four essential **classes** are predefined._ 

Instead it should be:
_When you open the index.ts file in the Visual Studio Code, you'll notice that the four essential **functions** are predefined._ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@once Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
