### ISSUE TITLE
Incorrect code line

### ISSUE THREAD

**Issue by once** [MicrosoftDocs/powerapps-docs#1488]
There is a code line, that leads to an error (appendChild error, as container cannot contain itself), so this should be removed:

`container.appendChild(this._container);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by ghurlman** [comment]
`this._container` and the locally scoped `container` variable are not the same; the code should work as it is.
