### ISSUE TITLE
Missing parameter attrinute in windowOptions 

### ISSUE THREAD

**Issue by maeg02** [MicrosoftDocs/powerapps-docs#1489]
It seems that the parameter windowOptions is missing the attribute
 - openInNewWindow: (Optional) Boolean

If hight and width optional, could there be an example with:
Xrm.Navigation.openWebResource("new_webResource.htm", { openInNewWindow: true });

Regards Markus
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef001b56-f366-7866-693b-c403f84dbab3
* Version Independent ID: e3d1fbdc-84a5-ce3c-af1e-11e98b14418f
* Content: [openWebResource (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openwebresource)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@maeg02 Thanks for the feedback. The `openInNewWindow` is not a supported parameter for this API. Please use the parameters that are officially documented. Closing the issue.
