### ISSUE TITLE
is it valid for External users using Power Apps Portal? 

### ISSUE THREAD

**Issue by aarohbits** [MicrosoftDocs/powerapps-docs#1493]
is it valid for External users using Power Apps Portal? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8601a9f-ca1e-49e0-bdf8-383431829997
* Version Independent ID: 488d4db7-a2de-b47e-5c1c-a28a5f8e046f
* Content: [Xrm.WebApi (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-webapi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-webapi.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@aarohbits See the [Portal Web API](https://docs.microsoft.com/en-us/powerapps/maker/portals/web-api-overview) to know more about what you can achieve using the web API. Closing the issue.
