### ISSUE TITLE
Screenshots are out of date which is causing confusion

### ISSUE THREAD

**Issue by bthompson-365** [MicrosoftDocs/powerapps-docs#1497]
https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Publishing-canvas-app-to-appSource/m-p/593283 is an example of the questions and issues people have.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b114a56-32d4-983c-b78e-28b38e655d2a
* Version Independent ID: 26932936-58ec-02bd-d866-c30d341e8731
* Content: [Step 2: Create a managed solution for your app (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-solution-app-appsource)
* Content Source: [powerapps-docs/developer/common-data-service/create-solution-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/create-solution-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment]
@bthompson-365 If this is still a problem, file a new issue. The topic has been updated since you filed this issue.
