### ISSUE TITLE
ASP.Net errors 

### ISSUE THREAD

**Issue by alesergithub** [MicrosoftDocs/powerapps-docs#1498]
Some customers request to add to the documentation that ASP.Net errors is not a security threat that no customer data will ever be exposed by such an error scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb68e1d-5c5a-fe4d-bfe0-324744299f6f
* Version Independent ID: c8b2432d-a350-824c-222b-cd8911d1af8b
* Content: [Frequently asked questions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/faq)
* Content Source: [powerapps-docs/maker/portals/faq.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/faq.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. ASP.NET error contains stack trace with the error. For more information, please refer to [Custom error](https://docs.microsoft.com/powerapps/maker/portals/admin/view-portal-error-log)
