### ISSUE TITLE
Typo in Model driven Sample Apps

### ISSUE THREAD

**Issue by OnshoreOutsourcing-dev** [MicrosoftDocs/powerapps-docs#1499]
Deploy is spelled depoly under the section Get Sample Apps. Wouldn't be quite so annoying if it wasn't also in bold text lol.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecbf56cc-ec02-2294-f98e-ade06b4fc3ec
* Version Independent ID: 7baf1d08-8689-1965-83cf-9c2a3615693f
* Content: [Model-driven sample apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/overview-model-driven-samples)
* Content Source: [powerapps-docs/maker/model-driven-apps/overview-model-driven-samples.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/overview-model-driven-samples.md)
* Service: **powerapps**
* GitHub Login: @mr-dang-msft
* Microsoft Alias: **brdang**

**Comment by Mattp123** [comment]
This has been fixed. Closing issue.
