### ISSUE TITLE
Error on solution installation

### ISSUE THREAD

**Issue by eromerof** [MicrosoftDocs/powerapps-docs#1502]
Hi, I have an error in the step on solution instalation, When I'm going to install the solution from the package deployer. The error is: 

errorDetails - Message  - Error while importing workflow {9977f8ed-8189-ea11-a812-000d3a3b478b} type ModernFlow name Portal User Request: Send Email to Admins on Request Creation: String or binary data would be truncated.......The statement has been terminated.

I try to install to US environment it's correctly but when I try to install to EMEA environment throw this error. Please, can anyone help me? We want to use this application in hospitals, but we need it to be installed in a tenant in europe

Thanks!!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f563b0-b40f-3359-14bc-f26ea846ed62
* Version Independent ID: 3b1df36e-47d8-18bf-8037-cd45ec53b7b0
* Content: [Deploy the Regional Government Emergency Response and Monitoring solution - Power Apps](https://docs.microsoft.com/en-us/powerapps/sample-apps/regional-emergency-response/deploy#issues-and-feedback)
* Content Source: [powerapps-docs/sample-apps/regional-emergency-response/deploy.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/sample-apps/regional-emergency-response/deploy.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Denaly777** [comment]
Hello, I informed Microsoft technical support about this problem and the response received is this:
"Contact the solution publisher to fix your solution. The locations of the Spanish flow display name are above the 100 character limit that is causing the problem and should fix it. 
https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/create-solutions-support-multiple-languages"
Thnx

**Comment by KumarVivek** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.
 
Closing this issue.
