### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by pratapladhani** [MicrosoftDocs/powerapps-docs#1503]
There is a broken link on this line - For model-driven apps, see: **Supported web browsers and mobile devices** linking to [https://docs.microsoft.com/dynamics365/customer-engagement/admin/supported-web-browsers-and-mobile-devices](https://docs.microsoft.com/dynamics365/customer-engagement/admin/supported-web-browsers-and-mobile-devices)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8fbf2eb-d0a2-3f2e-651b-bbec8cfe4d2c
* Version Independent ID: 0e271da6-8cea-f9d1-376e-2432b6a63759
* Content: [Run apps in a web browser - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/run-app-browser)
* Content Source: [powerapps-docs/user/run-app-browser.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/run-app-browser.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@pratapladhani thanks for catching this. I have updated the link and republished the topic - which will go live in about an hour.

Thanks,
Mints
