### ISSUE TITLE
Documents should mention this!

### ISSUE THREAD

**Issue by luoyong0201** [MicrosoftDocs/powerapps-docs#1504]
If your code activity don't have any input parameters, you cannot select the step for debug!

![image](https://user-images.githubusercontent.com/13193386/84588779-bbd8e700-ae5c-11ea-9c4b-174fe5cdee35.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae2bca0-76de-3f98-b0e7-65a137baafa2
* Version Independent ID: eb803d04-bddc-0c43-3dcb-110187fbf379
* Content: [Debug Workflow Activities (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/workflow/debug-workflow-activites)
* Content Source: [powerapps-docs/developer/common-data-service/workflow/debug-workflow-activites.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/workflow/debug-workflow-activites.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Fair enough. 
But let me ask you: Why create a custom workflow activity with no input parameters?
Wouldn't a plug-in serve the same purpose?

**Comment by KumarVivek** [comment]
As there is no further response, closing this issue.
