### ISSUE TITLE
Create a solution publisher needs an update?

### ISSUE THREAD

**Issue by apoloduvalis** [MicrosoftDocs/powerapps-docs#1505]
At the section [Create a solution publisher and solution](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/introduction-solutions#create-a-solution-publisher-and-solution) from powerapps.com it puts:

1. Select the Waffle icon at the top left corner
2. In the fly out, select All apps.
3. Look for the Common Data Service - custom app. You may want to click the ellipses (...) and choose Pin this app so it will be easier to navigate to next time.
4. Click the Common Data Service - custom app app and select it.
5. Navigate to Settings > Customization > Customizations. 

However, it did not work (at least for me). In my experience, the right procedure should be:

1. At the bottom of the left menu, select "Solutions".
2. At the top tools ribbon, click on "+ New Solution".
3. At the "New solution" form, in the Publisher field, select the "+ Publisher" option. A new window will open.
4. At the new window "Publisher: New Publisher / Information" fill the required fields and click in "Save and Close".  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb108dd-66c5-1901-8ee9-9636dd251044
* Version Independent ID: 2c811eaa-92a6-5934-05ef-2398968a89ff
* Content: [Introduction to solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/introduction-solutions)
* Content Source: [powerapps-docs/developer/common-data-service/introduction-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/introduction-solutions.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@apoloduvalis 

There are updated instructions here: [Solution publisher](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-solution#solution-publisher)
