### ISSUE TITLE
Localizations only on unmanaged soutions

### ISSUE THREAD

**Issue by topness-msft** [MicrosoftDocs/powerapps-docs#1506]
#2: select the _unmanaged_ solution you want 
(the translations menu is disabled on managed solutions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2b9c0a-bb7a-2f37-c4cf-95ee42870c16
* Version Independent ID: f7340cd3-de8d-0ea7-089f-c15648f5af73
* Content: [Export customized entity and field text for translation with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-customized-entity-field-text-translation?source=docs)
* Content Source: [powerapps-docs/maker/common-data-service/export-customized-entity-field-text-translation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-customized-entity-field-text-translation.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@topness-msft - Thanks for your feedback. Your request has been checked in for publishing and will be live before or near 6pm Pacific Time. 

Closing issue.
