### ISSUE TITLE
Need alternate GOV links

### ISSUE THREAD

**Issue by junterpfe** [MicrosoftDocs/powerapps-docs#1508]
should be updated to show URLs for gov portals as well if a GCC user tries to use this as-is it will ask them to login and create an account in commercial.

https://apps.gov.powerapps.us/play

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 559b4613-fbe0-45dc-f8bf-ff3a70b5f66e
* Version Independent ID: 36921b82-2295-8d26-9be0-d2d23ee11ab7
* Content: [Integrate canvas apps into websites and other services - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-apps-dev)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-apps-dev.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/embed-apps-dev.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@junterpfe Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
