### ISSUE TITLE
Import / Export Apps and custom connectors

### ISSUE THREAD

**Issue by sebastianzolg** [MicrosoftDocs/powerapps-docs#151]
Hi all, 
it would be great to have the possibility to import/export Apps and custom connectors so they can be shared between tenants, either between development, staging and production or as a provider between various customer tenants. In addition it would allow to track everything with source control and integrate into continues delivery pipeline.
Any plans for this? 
- thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell#questions)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
@sebastianzolg 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
