### ISSUE TITLE
Overly complicated to disable auto-save for a particular form

### ISSUE THREAD

**Issue by GBauer1833** [MicrosoftDocs/powerapps-docs#1511]
I would like to disable auto-save while I am learning how to develop powerapp forms.  Why can't you just have a simple checkbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cea415f-d8c4-93a8-e2ed-51164eeb6ca0
* Version Independent ID: 54be91e7-1cf8-f19c-6099-2407c4bd5ba4
* Content: [Disable auto-save in a model-driven app with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/manage-auto-save)
* Content Source: [powerapps-docs/maker/model-driven-apps/manage-auto-save.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/manage-auto-save.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@GBauer1833 -vThanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. 

Closing this issue.
