### ISSUE TITLE
Help Desk Template

### ISSUE THREAD

**Issue by JerryH1975** [MicrosoftDocs/powerapps-docs#1514]
Hi
I’m positive I have downloaded two different versions of Help Desk Template.
Is this possible? When on the community, people ask which template? 

2. Where in the instructions / video does it instruct me to to change ‘TicketList’ to a new DataSource?... so that it starts saving tickets and we can use the app.
Currently I add tickets, after a bit of time it defaults to the default tickets.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The template is only available in one version for [download](https://docs.microsoft.com/powerapps/maker/canvas-apps/help-desk-install#download-the-app).

The steps to remove SharePoint connection from the template and add connection that you create can be found in the [Configure the app to use SharePoint list](https://docs.microsoft.com/powerapps/maker/canvas-apps/help-desk-install#configure-the-app-to-use-the-sharepoint-list) section.

If you run into any issues, please reach out to the support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) for further investigation.
