### ISSUE TITLE
How many APIs does batch count, in regards of licensing/costing of API

### ISSUE THREAD

**Issue by anarchitect** [MicrosoftDocs/powerapps-docs#1516]
[Enter feedback here]

Can you please clarify, if 5 calls within this batch call, will this batch will be counted as 1 API call?  Or counted as 6 calls (number of requests within the batch + the batch request itself)  ? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af14071e-83a5-8dde-6346-d158b4d5d66a
* Version Independent ID: 8fb0f4fb-17ff-7491-d057-a1edf9242bc8
* Content: [Execute batch operations using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Which type of limit are you asking about?
 - Service Protection limits?
 - Entitlement limits?

See [Common Data Service API limits overview](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview) overview for more information.

More information about service protection limits: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits

**Comment by anarchitect** [comment]
Thanks for bring the attention of Service protection limit, can we talk about both?  Because we have cater both from NFR perspective, as well as costing of API add on perspective.

**Comment by JimDaly** [comment]
Simple answer:
Every entity CRUD operation is counted against the Entitlement limit, whether included in $batch or not. $batch is not a way to get around Entitlement limits.

Every incoming request is considered part of the service protection limits. So in that respect, each $batch is one. But service protection limits have 3 facets:

- Number of requests
- Duration time of requests
- Number of concurrent requests

The total duration of the the $batch operation is counted against the duration limit.

Look to the docs I linked to for more information. If you have more specific questions, please open new issues against those respective topics.

This topic is about how to Execute batch operations, so I'm going to close this issue.
