### ISSUE TITLE
incorrect link- should redirect to the power platform 

### ISSUE THREAD

**Issue by anapereiCRMSE** [MicrosoftDocs/powerapps-docs#1517]
in:
Prepare the environment
First, select a non-production environment and enable Use Unified Interface only mode, which will use the Unified Interface for all model-driven apps in the environment. This also includes any Dynamics 365 application modules originally configured for the legacy web client.

Sign in to Power Apps, select Environment, and then select a sandbox environment.

Select Settings > Behavior and then turn on Use Unified Interface only.

the link to powerapps should be the link to the Power Platform, https://admin.powerplatform.microsoft.com/

thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dba9985-89f9-5c4d-84e4-f5825683a6c5
* Version Independent ID: 2de67ad8-df27-064e-28fc-7536e6326390
* Content: [Quick start for transitioning your legacy web client application to Unified Interface - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/transition-web-app)
* Content Source: [powerapps-docs/maker/model-driven-apps/transition-web-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/transition-web-app.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@anapereiCRMSE - thank you for your feedback. The link and text has been updated to point to the Power Platform admin center. 
Closing issue.
