### ISSUE TITLE
Production Portals in Sandbox environments

### ISSUE THREAD

**Issue by Sinha-Abhisek** [MicrosoftDocs/powerapps-docs#1518]
The documentation has provided no reference to sandbox environments. The scenario is a typical lifecycle of DEV->TEST->PROD. I would like to maintain PowerApps Portals corresponding to my sandbox environments.

In that case, I can create production portals in each of my sandbox environments and then create another production portal in my production environment, provided I have storage capacity. Correct?
That also begs the question, why don't we have sandbox portals? Isn't this a very common question from any enterprise with proper ALM process? Or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7444d166-6678-7ecc-2c33-4c54d4d67ac3
* Version Independent ID: a815c5f8-3ab4-d30a-5098-0d865947bdbb
* Content: [About the Power Apps portals lifecycle - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-lifecycle)
* Content Source: [powerapps-docs/maker/portals/admin/portal-lifecycle.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/portal-lifecycle.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Environment types are detailed in Power Platform environments documentation. Including [Sandbox environments](https://docs.microsoft.com/power-platform/admin/sandbox-environments). For feature asks related to Power Apps portals, please reach out to [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) to submit ideas and vote.
