### ISSUE TITLE
Does the fiel "Environment" on Package Export screen have any impact?

### ISSUE THREAD

**Issue by sebastianzolg** [MicrosoftDocs/powerapps-docs#152]
When exporting an App, the field "Environment" is set to the source environment name. Should this value be cleared out when exporting to another tenant not having the same environment? 
In other words: Is there any logic behind this value? 

Reason I'm asking is that I saw an error message when starting the app after an export saying that the environment is not found. The error message also pointed out the environment name of the source tenant which is not available in the target tenant. 

- Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29c5da4-511c-c13f-6c98-c3ad07a389e7
* Version Independent ID: d83ac9f1-3c07-3a15-f212-df944f769d30
* Content: [Migrate apps between environments and tenants - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/environment-and-tenant-migration)
* Content Source: [powerapps-docs/administrator/environment-and-tenant-migration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/environment-and-tenant-migration.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
@sebastianzolg 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. If this issue still exists, please contact support.
