### ISSUE TITLE
Microphone Control 

### ISSUE THREAD

**Issue by alanhamid** [MicrosoftDocs/powerapps-docs#1520]
With regards to the doc, https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-microphone 
Is there a Start and Stop recording based on the User's Pause or start speaking, without touching the buttons?  Can Microphone sense if someone speaking or stop speaking? Thanks.

**Comment by chmoncay** [comment]
Hi there, unfortunately no.  There is no way to detect when a recording should start / end.  We also don't have this feature on our radar in the short term.  Sorry for any inconvenience.

**Comment by alanhamid** [comment]
Thanks for answering.
