### ISSUE TITLE
Patch to modify multiple records with a single call

### ISSUE THREAD

**Issue by caglata** [MicrosoftDocs/powerapps-docs#1522]
It is stated that Patch can also be used to create or modify multiple records with a single call. Instead of passing a single base record, a table of base records can be provided in the second argument.
Can you please provide an example?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5786697f-ee29-1b61-c59a-955086201d55
* Version Independent ID: d2130620-9767-c72f-5bd7-8417e48cf65d
* Content: [Patch function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can use `ClearCollect(mycol,Table( { Value: "1" }, { Value: "2" } ))` and then `Patch(mycol,mycol,Table({ Value: "3" }, { Value: "4" })  )` to change from initial 1 and 2 values to 3 and 4 using Patch().
