### ISSUE TITLE
Refreshing BPF UI

### ISSUE THREAD

**Issue by honzakostejn** [MicrosoftDocs/powerapps-docs#1523]
[Enter feedback here]
I was trying to call this method from one of my scripts and it seems it's not working?
`formContext.ui.process.reflow(true, "203d2ab8-f558-4ab1-88fa-94f700651f75", "fb80b008-3846-41af-a6f9-9831b6ea2b86");`

Could you maybe improve the documentation? Or describe how to refresh BPF on client? My use case I'm triggering action from client which updates BPF server side and I need to refresh UI for the client. Is there some better option without refreshing the whole form?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c2d033-e865-6f35-f80e-170cc5412ae7
* Version Independent ID: 9dc26b99-18c9-5127-5990-fd1fce2c1234
* Content: [reflow (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-process/reflow)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-process/reflow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-process/reflow.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by LinnZawWin** [comment]
I tried the script below and it is working
`formContext.ui.process.reflow(true);`

Why are parentStage and nextStage parameters required to refresh BPF?
If they are really required, what is the ID of the parent stage and how to get it? Can you please explain with the sample code?

**Comment by Nkrb** [comment]
@honzakostejn Can you confirm, if you're still facing the issue?

**Comment by honzakostejn** [comment]
Hi, I'm not able to test it right now. I've had to do a release and solved it by refreshing the whole form. 

But as @LinnZawWin stated, it seems like the parameters in the documentation aren't needed?

**Comment by Nkrb** [comment]
@honzakostejn As per the development team, all the three parameters are optional and are not required. Will update the docs ASAP and publish it live.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
