### ISSUE TITLE
Sample for Next-month chevron is wrong - 2228779

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerapps-docs#1526]
@MscrmTools commented on [Wed Jun 17 2020](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/issues/9)

Hi,
The sample code for [Next-month chevron](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/screen-templates/calendar-screen-reference#next-month-chevron) is wrong (and so the calendar template screen is wrong too, I don't know if you can handle this part too, apart from documentation).

The `Collect` method has an invalid argument of type `Date` instead of a `String`. 

```Collect( MyCalendarEvents, 
        'Office365'.GetEventsCalendarViewV2( _myCalendar.Name, 
            Text( DateAdd( _maxDate, 1, Days ), UTC ), 
            DateAdd( _firstDayInView, 40, Days )
        ).value
);
```
The error that occurs is that third argument is considered as before the second argument making a search for a start date higher that the end date.

The correct code is as below (tested and validated) 

```Collect( MyCalendarEvents, 
        'Office365'.GetEventsCalendarViewV2( _myCalendar.Name, 
            Text( DateAdd( _maxDate, 1, Days ), UTC ), 
            Text( DateAdd( _firstDayInView, 40, Days ))
        ).value
);
```

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 95dceb94-5142-17e4-ef8a-53fab1966ece
* Version Independent ID: a2c84e18-8581-6816-bc01-3f5761c92021
* Content: [Référence pour le modèle d’écran de calendrier pour les applications Canvas - Power Apps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/screen-templates/calendar-screen-reference#next-month-chevron)
* Content Source: [powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-reference.md](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/blob/live/powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-reference.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

---

@srvbpigh commented on [Wed Jun 17 2020](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/issues/9#issuecomment-645468095)

Hello, @MscrmTools
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been updated and the changes will be visible soon.
