### ISSUE TITLE
Errata

### ISSUE THREAD

**Issue by dominicgrayDHG** [MicrosoftDocs/powerapps-docs#1529]
Office365.* should be changed to Office365Outlook.*
as of this time
6/21/2020 3:33:48 AM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbce0fbc-150d-5a31-2096-2f36eea12a26
* Version Independent ID: 13bb945a-845b-fbe2-c65a-a944a92ea368
* Content: [Overview of the Office 365 Outlook connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-outlook)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-office365-outlook.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-office365-outlook.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated; please allow some time for the content to reflect the changes.
