### ISSUE TITLE
Section "Types of variables" references to MyColor as MyVar

### ISSUE THREAD

**Issue by hikmatune** [MicrosoftDocs/powerapps-docs#153]
In "Types of variables" there is a typo it should say MyColor instead of MyVar, in the last paragraph in this section "you can simply use MyVar anywhere a color value can be used ...."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb9294a0-cdd8-91d5-0102-c0412a21f540
* Version Independent ID: 77841b4e-08a9-1177-e18c-b428ef930c1c
* Content: [Understand variables in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-variables)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-variables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-variables.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Fixed. (Thanks for the feedback, @hikmatune!)

cc: @gregli-msft
