### ISSUE TITLE
Object Reference Error

### ISSUE THREAD

**Issue by Shiva145** [MicrosoftDocs/powerapps-docs#1530]
I copied everything exactly changed the configurations.
I got error at 

var authParameters = AuthenticationParameters.CreateFromResourceUrlAsync(new Uri(webApiUrl)).Result;

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3da25ded-6c89-69ba-7351-0f04f1c07f79
* Version Independent ID: 6923f7c2-0856-f91f-b17e-e1bef131c5f3
* Content: [Quick Start: Web API sample (C#) (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
- Visual Studio 2015?
- Microsoft.IdentityModel.Clients.ActiveDirectory Version 2.29.0? 

Sample is a bit old b/c it depends on the older version of ADAL.
There is a known issue (mentioned in the doc) about VS 2015.

Can you confirm that the above have been accounted for?

**Comment by Shiva145** [comment]
> * Visual Studio 2015?
> * Microsoft.IdentityModel.Clients.ActiveDirectory Version 2.29.0?
> 
> Sample is a bit old b/c it depends on the older version of ADAL.
> There is a known issue (mentioned in the doc) about VS 2015.
> 
> Can you confirm that the above have been accounted for?

I am using VS 2017.
I followed the given steps exactly. Please find below screenshot.

![ErrorApi](https://user-images.githubusercontent.com/56927457/85234760-5f824400-b3d5-11ea-8e0f-c9c9b0deaf31.JPG)

**Comment by JimDaly** [comment]
I see that you replaced the provided clientid value:
```
    // Azure Active Directory registered app clientid for Microsoft samples
    string clientId = "51f81489-12ee-4a9e-aaae-a2591f45987d";
```

You are expected to use the value provided for this quick start sample.
If you want to use your own appid, you will need to register the app using instructions here:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-register-app-azure-active-directory

This simple sample doesn't include code to manage consent because the sample clientid is pre-approved.

Please try with the provided clientid and see if it doesn't work then.

**Comment by Shiva145** [comment]
> I see that you replaced the provided clientid value:
> 
> ```
>     // Azure Active Directory registered app clientid for Microsoft samples
>     string clientId = "51f81489-12ee-4a9e-aaae-a2591f45987d";
> ```
> 
> You are expected to use the value provided for this quick start sample.
> If you want to use your own appid, you will need to register the app using instructions here:
> https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-register-app-azure-active-directory
> 
> This simple sample doesn't include code to manage consent because the sample clientid is pre-approved.
> 
> Please try with the provided clientid and see if it doesn't work then.

Just wondering. Error is nothing to do with ClientId. Because I am just passing URL.
Please guide

**Comment by JimDaly** [comment]
OK. I see it hasn't gotten to that part yet.
What is the structure of your URL?
It is supposed to be something like:
`https://yourorg.crm.dynamics.com`

But if you are in a different geography, it could be 
`https://yourorg.crm4.dynamics.com`

Can you paste in in a browser and connect to your environment with the URL you are using?
