### ISSUE TITLE
limitation of 1 canvas app pr. form is not accurate any longer

### ISSUE THREAD

**Issue by iiu-dk** [MicrosoftDocs/powerapps-docs#1534]
this is true now: "You have more than one canvas app with Phone form factor, the maximum is one for this form factor. The number of canvas apps are limited to three for Web and one for Tablet and Phone form factors."  - Information popup within Dynamics/PowerApps when adding more canvas apps.

**Comment by Nkrb** [comment]
@iiu-dk  Can you link us to the doc page you're talking about.

**Comment by iiu-dk** [comment]
I did not find this in docs... I tried it in powerapps and the text is copied from live environment. Did test and found it to be true

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by tapanm-MSFT** [comment]
Is this related to [embedding canvas app on model-driven app](https://docs.microsoft.com/powerapps/maker/model-driven-apps/embedded-canvas-app-guidelines)?

**Comment by iiu-dk** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Mattp123** [comment]
@iiu-dk - The article with the information you mentioned is here: https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-guidelines

It states: 
You can only enable three embedded canvas apps for each form with Web, and one for Tablet and Phone client types.

Closing issue.
