### ISSUE TITLE
Incorrect Manifest Child elements

### ISSUE THREAD

**Issue by Power-Maverick** [MicrosoftDocs/powerapps-docs#1535]
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/
Control Manifest file has manifest element but the child elements are incorrect. It only has one element called "control" and control has all the child elements mentioned in manifest child elements.

**Comment by Nkrb** [comment]
@Power-Maverick The document you mentioned has all the elements regardless of parent or child elements. Individual element document mentions about child and parent elements. This page is like an index page. Any specific concerns on this?
