### ISSUE TITLE
`Twitter.Tweet` method missing first parameter.

### ISSUE THREAD

**Issue by shuheydev** [MicrosoftDocs/powerapps-docs#1537]
[Enter feedback here]

In this document, It looks missing first parameter(file:) of `Twitter.Tweet` method.

It is written as below in the document. But, this occur error. 

```
Twitter.Tweet({tweetText: MyTweet.Text})
```

 This need first parameter.

```
Twitter.Tweet("",{tweetText: MyTweet.Text})
```

![image](https://user-images.githubusercontent.com/43431002/85367390-19a7b600-b564-11ea-9a09-adbd16e30ed0.png)

thanks 😊

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf3c34b7-6b32-a007-0a5f-ab36a30568ce
* Version Independent ID: d7d8e088-e725-1625-48df-f7cea00a201a
* Content: [Overview of the Twitter connection - Power Apps](https://docs.microsoft.com/en-ca/powerapps/maker/canvas-apps/connections/connection-twitter#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-twitter.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-twitter.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been updated, please allow some time to reflect the changes.
