### ISSUE TITLE
The documentation regarding inviting contacts to powerapps portals is old

### ISSUE THREAD

**Issue by JbKarlsson** [MicrosoftDocs/powerapps-docs#1538]
The documentation regarding inviting contacts to powerapps portals is old.
Microsoft is now reffering to PowerAutomate (Microsoft Flow) instead of the Workflow functionality. The parts with workflow should be replaced with a proper guide how to utilize the flow for the invitations and maybe some links to how to set up the flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97927ddf-353e-98e9-8e30-f1f2267c6f0b
* Version Independent ID: d728ae3e-9b17-8254-3e72-4cda2a006c1d
* Content: [Invite contacts to your portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/invite-contacts)
* Content Source: [powerapps-docs/maker/portals/configure/invite-contacts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/invite-contacts.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Power Apps portals uses classic Common Data Service workflows. More information: [Classic Common Data Service workflows](https://docs.microsoft.com/power-automate/workflow-processes)
