### ISSUE TITLE
404ing link on Community Plan page

### ISSUE THREAD

**Issue by dougelliott** [MicrosoftDocs/powerapps-docs#1539]
The link for `Environment and tenant app migration` is currently pointing to `https://docs.microsoft.com/en-us/power-platform/admin/environment-and-tenant-migration`, which 404s. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d27942c-51fc-c2dc-9857-bcbfbadba145
* Version Independent ID: 832089db-9a05-9d52-7529-429e3a6648f8
* Content: [Power Apps Community Plan -- a free development environment for individual use - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by Mattp123** [comment]
@dougelliott - I don't believe that link exists in the article anymore. 
Closing issue.
