### ISSUE TITLE
Editing Section Titles

### ISSUE THREAD

**Issue by NCMculpepper** [MicrosoftDocs/powerapps-docs#1540]
Hello!

We have decided to implement custom help panes to our Dynamics 365 environment and although I have read your article regarding how to implement, I can't find information on editing the name of a section once created and saved.  Can you help? 

Thanks!

**Comment by phecke** [comment]
@NCMculpepper Please provide the link to the article you were following.

**Comment by NCMculpepper** [comment]
Here you go! https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-custom-help-pages

**Comment by yifwang** [comment]
Hi @NCMculpepper Sorry for the inconvenience. Unfortunately, the walkaround is to copy and paste your content of the section and create new onw. We're aware of the experience lacking of edit experience and the development is ongoing to add the edit experience to each of the elements. The update will be announced publicly. Please stay tuned with the blogs or other channels. Thanks.

**Comment by Mattp123** [comment]
Closing issue.
