### ISSUE TITLE
Remarks or reference missing for EntityMetadata

### ISSUE THREAD

**Issue by Power-Maverick** [MicrosoftDocs/powerapps-docs#1543]
The object returned is _EntityMetadata_ but there is no reference to the definition of that object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f77a4a9a-21da-579b-52c7-f546f937f868
* Version Independent ID: e65fae40-0e11-d131-7eff-04be124a39ce
* Content: [getEntityMetadata - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/utility/getentitymetadata)
* Content Source: [powerapps-docs/developer/component-framework/reference/utility/getentitymetadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/utility/getentitymetadata.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@Power-Maverick Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
