### ISSUE TITLE
When will parent.Xrm start NOT working on free standing Web Resources?

### ISSUE THREAD

**Issue by potsiemj** [MicrosoftDocs/powerapps-docs#1545]
Hi, this page says:

_parent.Xrm. will work if the HTML web resource is loaded in a form container. However, for other places, **such as loading an HTML web resource as part of the SiteMap, parent.Xrm. also won’t work**._

When exactly won't parent.Xrm work in free standing web resources?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f2e23f-87e2-62be-f107-08c2e99b97e5
* Version Independent ID: 03aa8ec3-a827-95cf-d7cf-f0a014c3484b
* Content: [GetGlobalContext function and ClientGlobalContext.js.aspx in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx#clientglobalcontextjsaspx)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@potsiemj Thanks for contacting us. Please contact support or ideas forum.  To contact Support, visit https://powerapps.microsoft.com/support/ and for ideas forum, visit https://ideas.powerapps.com. Closing this issue.
