### ISSUE TITLE
Unable to install Microsoft.PowerApps.Administration.PowerShell & Microsoft.PowerApps..PowerShell modules

### ISSUE THREAD

**Issue by lapr0ct0r** [MicrosoftDocs/powerapps-docs#1546]
PowerShell version: 5.1.17134.858
Get-PSRepository: 
Name                      InstallationPolicy   SourceLocation                     
----                      ------------------   --------------                     
PSGallery                 Untrusted            https://www.powershellgallery.co...

Execution policy set to unrestricted.  When trying to run:
Install-Module -Name Microsoft.PowerApps.Administration.PowerShell
Install-Module -Name Microsoft.PowerApps.PowerShell -AllowClobber

Get the following errors:

WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2
'.
PackageManagement\Install-Package : No match was found for the specified search 
criteria and module name 'Microsoft.PowerApps.Administration.PowerShell'. Try 
Get-PSRepository to see all available registered module repositories.
At C:\Users\laproctor\Documents\WindowsPowerShell\Modules\PowerShellGet\2.2.2\PSMo
dule.psm1:9683 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage: 
   InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.Packag 
   eManagement.Cmdlets.InstallPackage

WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2
'.
PackageManagement\Install-Package : No match was found for the specified search 
criteria and module name 'Microsoft.PowerApps.PowerShell'. Try Get-PSRepository 
to see all available registered module repositories.
At C:\Users\laproctor\Documents\WindowsPowerShell\Modules\PowerShellGet\2.2.2\PSMo
dule.psm1:9683 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage: 
   InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.Packag 
   eManagement.Cmdlets.InstallPackage

**Comment by lapr0ct0r** [comment]
I tried the instructions in both these articles:
https://devblogs.microsoft.com/powershell/powershell-gallery-tls-support/
https://dev.to/darksmile92/powershell-disabled-support-for-tls-1-0-for-the-gallery-update-module-and-install-module-broken-1oii
Still will not install

**Comment by jimholtz** [comment]
Just found this assigned to me. Closing. Please reopen if still an issue.
