### ISSUE TITLE
Send push notification from external client

### ISSUE THREAD

**Issue by pgkdev** [MicrosoftDocs/powerapps-docs#1547]
It's possible to send push notification from outside power apps using some API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f754f6-4b2b-b1c8-6b84-f74f578821c8
* Version Independent ID: 20df624c-87eb-0347-89f5-ef1d84b395af
* Content: [Send a push notification - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-notifications)
* Content Source: [powerapps-docs/maker/canvas-apps/add-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-notifications.md)
* Service: **powerapps**
* GitHub Login: @Kavishi
* Microsoft Alias: **kaagar**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Available services for Power Apps Notifications:  Power Automate and Power Apps. More information: https://docs.microsoft.com/connectors/powerappsnotification/. For more help or to investigate an issue, please use [Power Apps community forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1) or reach out with a [support ticket](https://admin.powerplatform.microsoft.com/support).
