### ISSUE TITLE
Explicit warning in docs to use the Apply button for Screen size + orientation settings changed

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/powerapps-docs#1549]
[Enter feedback here]

Please add an explicit warning on this doc page (_and maybe on the followup one I actually search-resulted into to start: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout#known-limitations_ )  which makes clear that before you'll see the results of changing these settings, you MUST hit the easily overlooked "Apply" button and THEN do a Save&Publish of your app.  

I.e. changing the settings and doing countless Save&Publishes, swearing, PApps Forum crawls, and sacrifices of chickens to the demons and gods of NoCodeLoCode will NOT show any change in app behavior.  But after you finally notice and click that Apply button and THEN S&P,  BOOM! It works.  Or maybe it was that special all black rooster we loved so much?  Anyways.....

Fried chicken's ready!  DINNER, Kids!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cece2730-2d0d-98d6-3c94-d63e58fab63a
* Version Independent ID: 3187bddd-93e9-d1e3-450f-9cb6abe73853
* Content: [Change screen size and orientation of a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/set-aspect-ratio-portrait-landscape)
* Content Source: [powerapps-docs/maker/canvas-apps/set-aspect-ratio-portrait-landscape.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/set-aspect-ratio-portrait-landscape.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. And apologies for your experience. The content has been updated, please allow some time to reflect the changes.
