### ISSUE TITLE
Unix Time

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#155]
Hello,
Please consider adding the following to the Text Function docs. [Big thanks to @timl in the PowerApps Community](https://powerusers.microsoft.com/t5/General-Discussion/Convert-Unix-Time-to-Human-Readable-Time/m-p/198594/highlight/false#M64216).

- To convert Unix Time (example: 1546271859) to human readable **date**: 
    - UnixTime / 86400 + Date(1970,1,1)
- To convert Unix Time to human readable **date and time**: 
    - Text(UnixTime * 1000,"[$-en-US]ddd, dd mmm yyyy hh:mm:ss")

**Comment by gregli-msft** [comment]
@SeaDude, good suggestion.  We've added [UNIX specific information in a new data types article](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types#converting-unix-times) and [an example in the Text function](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-text#datetime)

**Comment by SeaDude** [comment]
Thank you for the follow through!
