### ISSUE TITLE
Information about entity icons is missing

### ISSUE THREAD

**Issue by rappen** [MicrosoftDocs/powerapps-docs#1550]
Since we do not like our sitemap to look like a box of puzzle pieces, we always want to specify an icon for the entities.
But there seems to be no information at all about this in the docs!

See also: https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/issues/1863

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11bacb37-4743-1d0e-d13e-1d9b656c661f
* Version Independent ID: 7b4d6192-4282-c5c1-01a2-a3ba065ed6e6
* Content: [Create a custom entity - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-create-entity)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-create-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-create-entity.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@rappen - that's described in this topic: [Change model-driven app custom entity icons](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/change-custom-entity-icons) 
Closing issue

**Comment by rappen** [comment]
Got it, thanks.
But I **definitely don't agree** it should be under "Advanced customization", having a representative icon is a vital part of basic entity customizations so users won't have to guess with the pieces of puzzle like this:

![image](https://user-images.githubusercontent.com/2572253/88455344-deefb100-ce74-11ea-868f-bdf7b7e0b728.png)
