### ISSUE TITLE
Example code uses ILMerged assemblies

### ISSUE THREAD

**Issue by cchannon** [MicrosoftDocs/powerapps-docs#1551]
Example code uses dropbox API in plugin context, which assumes ILMerged assemblies. This is not supported. The example code should probably use HTTP requests instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38df8a3-58d1-6cd9-2dac-4ea6c857f01e
* Version Independent ID: 7bb3e8c6-067d-321b-375b-c1f9752e91b8
* Content: [Sample: Generic virtual entity data provider plug-in (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/virtual-entities/sample-generic-ve-plugin)
* Content Source: [powerapps-docs/developer/common-data-service/virtual-entities/sample-generic-ve-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/virtual-entities/sample-generic-ve-plugin.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@cchannon 

You are correct. I have updated the sample with a note, which will be published by tomorrow morning. A future revision of the sample will remove the need for ILMERGE.

Thanks
