### ISSUE TITLE
Incorrect header and additional information at the top of page.

### ISSUE THREAD

**Issue by sethtbacon** [MicrosoftDocs/powerapps-docs#1552]
The header of the page is incorrect along with the first part of the page which looks like webpage metadata.

![image](https://user-images.githubusercontent.com/20324113/85938575-5efd1800-b8c3-11ea-83be-a751539342d2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92b265c-b3a2-913b-438c-a7ff73377430
* Version Independent ID: f229173f-aa51-23d3-1092-37655bc59625
* Content: [&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/overview)
* Content Source: [powerapps-docs/developer/component-framework/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/overview.md)
* GitHub Login: @Nkrb

**Comment by Nkrb** [comment]
@sethtbacon Thanks for the feedback. We have fixed the issue and pushed it live. Closing the issue.
