### ISSUE TITLE
Layout option has no link

### ISSUE THREAD

**Issue by SighlentNite** [MicrosoftDocs/powerapps-docs#1555]
Layout option has no link.
Also the details to edit in the advanced option changed from Horizontal to Layout.Horizontal.

My app look like it bugged out heavily because It just changed to vertical even though I had not touched that section for weeks. Must be a fairly recent change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff9e431-4f75-a61c-bacc-fd904bf5bdde
* Version Independent ID: 3f88278f-a036-882f-f520-853ebca1bbff
* Content: [Radio control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-radio)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-radio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-radio.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Layout as mentioned is only Horizontal or Vertical, hence no hyperlink. While the formula changes to `Layout.Horizontal` or `Layout.Vertical` during edit, the formula remains `Horizontal` or `Vertical` post edit. And can be selected using the properties drop down in the formula bar.
