### ISSUE TITLE
Error in page formatting / content / layout

### ISSUE THREAD

**Issue by RichWK** [MicrosoftDocs/powerapps-docs#1557]
Hello — it looks like this page has some unintended text and formatting at the very top. 🙂

It also looks like the page content is repeated twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92b265c-b3a2-913b-438c-a7ff73377430
* Version Independent ID: f229173f-aa51-23d3-1092-37655bc59625
* Content: [&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/overview)
* Content Source: [powerapps-docs/developer/component-framework/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/overview.md)
* GitHub Login: @Nkrb

**Comment by Nkrb** [comment]
@RichWK Thanks for the feedback. We have fixed the issue and pushed it live. Closing the issue.
