### ISSUE TITLE
Documentation requires review

### ISSUE THREAD

**Issue by sdieken** [MicrosoftDocs/powerapps-docs#1559]
Can we get this documentation reviewed for accuracy?  There is no mention of the CRM Outlook client being required for the Dynamic Worksheets to work correctly.  We have this included in our OnPremise documentation (https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/basics/export-excel-dynamic-worksheet), but not for the Online documentation.

Also, the "Refresh from PowerApps" button doesn't seem to exist anymore.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 168295f7-0ceb-8996-611f-e5538da2d3bb
* Version Independent ID: 09f8ed1c-2c2c-8ea6-e0a3-398396858e65
* Content: [Export to an Excel dynamic worksheet in model-driven Powerapps - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/export-excel-dynamic-worksheet)
* Content Source: [powerapps-docs/user/export-excel-dynamic-worksheet.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/export-excel-dynamic-worksheet.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
@sdieken Thank you for the feedback. I'm working on this and will update the topic as appropriate. 

Thanks,
Mints

**Comment by mduelae** [comment]
@sdieken I updated the topic with instructions on how the current model-driven Power Apps user interface works. I also checked with our internal team and Outlook client is not required for Export to Excel options to work in Power Apps.

Hope this helps. 

Thanks,
Mints
