### ISSUE TITLE
Improvement suggestion [Expense Report sample]

### ISSUE THREAD

**Issue by Rpeters1977** [MicrosoftDocs/powerapps-docs#156]
On the form NewExpenseFormsucces on the NewExpense screen: use this Set(SelectedReport,NewExpenseForm.LastSubmit);
Navigate(ViewReport,None)

This will increase performance and also you will not be able to retrieve the wrong expanse. Before a refresh and the last function was used. 

Kind regards,
Raymond Peters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by AFTOwen** [comment]
@Rpeters1977 Thanks for your feedback. For product-related feedback, visit [the forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1a).  
Closing this issue.

**Comment by caburk** [comment]
@mr-dang-msft
