### ISSUE TITLE
Wrong directions

### ISSUE THREAD

**Issue by LXHeinze** [MicrosoftDocs/powerapps-docs#1562]
Even though the instructions state

"Set the name of the section to section_map or a name that ends with section_map, for example contoso_section_map."

it only worked for me with "section_map", but not with "asset_section_map"

alheinz@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b6f5c0-06ea-6234-b4ef-aabd11a127fc
* Version Independent ID: 3d4bcfcc-290c-d084-422e-e8ed8192ca4f
* Content: [Add geolocation to a managed form in a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/add-geolocation)
* Content Source: [powerapps-docs/maker/portals/configure/add-geolocation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/add-geolocation.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please create a [support ticket](https://admin.powerplatform.microsoft.com/support) and the support teams can help investigate this issue.
