### ISSUE TITLE
Broken link to developer documentation

### ISSUE THREAD

**Issue by pratapladhani** [MicrosoftDocs/powerapps-docs#1566]
Broken Link in bullet 8 

If you want to add JavaScript events, select the Events tab, and then select the appropriate entities, fields, and events. More information: **Developer Documentation: Use editable grids** <-- Link points to  https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/customize-dev/use-editable-grids-dynamics-365.md currently, which gives **404 error**.

I think it should point to **https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/use-editable-grids** maybe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 323651bd-11de-71da-9a79-21293995f529
* Version Independent ID: 6d59ef2e-2072-ac62-b62c-04c84eb04b91
* Content: [Make model-driven app grids (lists) editable by using the Editable Grid custom control with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/make-grids-lists-editable-custom-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/make-grids-lists-editable-custom-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/make-grids-lists-editable-custom-control.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@pratapladhani - apologies for the delay. This has been fixed in the master branch and will be published live in 3-4 hours. Closing issue.

**Comment by pratapladhani** [comment]
Thanks, @Mattp123 !
