### ISSUE TITLE
Broken link about listing PowerApps on AppSource

### ISSUE THREAD

**Issue by Lee-Myhre** [MicrosoftDocs/powerapps-docs#1569]
Under "Canvas apps for ISVs and Microsoft partners", the Learn More link for "List your solution on AppSource" is not working, and redirects back to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5900fe4-4399-9b09-3e42-4ff71f3a8fb9
* Version Independent ID: 16e8e4eb-6e63-620e-3811-cd6265aca1fa
* Content: [Power Apps for enterprise developers, partners, and ISVs - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dev-enterprise-intro)
* Content Source: [powerapps-docs/maker/canvas-apps/dev-enterprise-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dev-enterprise-intro.md)
* Service: **powerapps**
* GitHub Login: @ImadYanni
* Microsoft Alias: **iyanni**

**Comment by Lee-Myhre** [comment]
The page linked to is https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dev-appsource-test-drive however opening this page anywhere just redirects back to the above page instead. Is this no longer a recommended model for demo'ing your PowerApps?

**Comment by ImadYanni** [comment]
Hi Vivek,
I don’t think I own this doc I think this should be owned by someone in Maker team.
Thanks!
Imad

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, the link has been updated. Please allow some time for the content to reflect the changes.
