### ISSUE TITLE
Cost Center is not being populated

### ISSUE THREAD

**Issue by eggy116** [MicrosoftDocs/powerapps-docs#1570]
Cost Center is not populated with the items from the list on the Create New Expense Report form

**Comment by Nkrb** [comment]
@eggy116 Can you point us to the doc you're talking about, so that we can assign it to proper writer to verify the issue.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Looks like this is related to the [Expense Report sample app](https://docs.microsoft.com/powerapps/maker/canvas-apps/expense-report-install). Please reach out to the support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) to investigate this issue.
