### ISSUE TITLE
See Also Link returns a 404

### ISSUE THREAD

**Issue by agoll** [MicrosoftDocs/powerapps-docs#1577]
This link in your "See Also" section returns a 404. 
Create Early-Bound Entity Classes with the Code Generation Tool (CrmSvcUtil.exe)

I found the working page at this link: 
https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/org-service/create-early-bound-entity-classes-code-generation-tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0949367-dc3e-ba70-b494-8945530a6fed
* Version Independent ID: 93472f86-1b45-0421-2e1e-7e2857e64534
* Content: [Create extensions for the code generation tool (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/extend-code-generation-tool)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/extend-code-generation-tool.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/extend-code-generation-tool.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@phecke 
Can you fix please?

**Comment by phecke** [comment]
@agoll Thanks for letting us know. Fixed.
