### ISSUE TITLE
How to clear a lookup value with this

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/powerapps-docs#1578]
Hi Team,

Though it is mentioned [here](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/update-delete-entities-using-web-api#delete-a-single-property-value) how to clear lookup value but how to use that with Xrm.WebApi.deleteRecord ? as the request only intakes the entityname and id.

Also the ability to clear the lookup values ideally should be in updateRecord only. This is very challenging in scenarios where we update the values and clear some values together.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b711f247-6325-9f62-49bb-d592beb3c4c2
* Version Independent ID: 10af3d59-a841-bb74-123a-d7c6a85b550a
* Content: [deleteRecord (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/deleterecord)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/deleteRecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/deleteRecord.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@pavansarma93 We cant delete a lookup value using the Xrm.WebApi.deleteRecord method. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
