### ISSUE TITLE
Out of date but links to a document that links back to this

### ISSUE THREAD

**Issue by cloudthingmike** [MicrosoftDocs/powerapps-docs#1579]
This page states it is out of date and links to the Licencing Guide for more detail. In turn the licencing guide states:

`Restricted entities: Entities that requires a Dynamics 365 license for full access. Examples: Case, SAL,
Knowledge Articles. For list of restricted entities click here`

Which is a link back to this page. As it stands it appears either there are **no** restricted entities any more or there is - at least - no guidance on what they are?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted entities requiring Dynamics 365 licenses - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
This is resolved so closing the issue.
