### ISSUE TITLE
Unable to install the Microsoft.PowerApps.PowerShell module

### ISSUE THREAD

**Issue by jabcoco** [MicrosoftDocs/powerapps-docs#158]
Unable to install the Microsoft.PowerApps.PowerShell module.

PS C:\WINDOWS\system32&gt; Install-Module -Name Microsoft.PowerApps.Administration.PowerShell
PS C:\WINDOWS\system32&gt; Install-Module -Name Microsoft.PowerApps.PowerShell -AllowClobber
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'Microsoft.PowerApps.PowerShell'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS C:\WINDOWS\system32&gt; Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Trusted              https://www.powershellgallery.com/api/v2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell#flow-commands)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jamesol-msft** [comment]
+ @denisemoran , @MattB-msft -> Have you see this issue before?

**Comment by jamesol-msft** [comment]
@MattB-msft  + @denisemoran  -> Have you see this error before?

**Comment by jamesol-msft** [comment]
@jabcoco - We just pushed an update that should have fixed this issue, please let me know if you can still repro,

**Comment by jcr5999** [comment]
I'm trying to install the PowerApp modules and I get the warning and unable to resolve package source https://www.powershellgallery.com/api/v2.

**Comment by Paul-Lees** [comment]
Im also getting this message

**Comment by jcr5999** [comment]
It was a proxy issue for me.

**Comment by jimholtz** [comment]
@jabcoco 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Please reopen if this issue still exists.
