### ISSUE TITLE
Business Required fields are not enforced by the API

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1580]
You can configure an attribute to be Business Required (aka ApplicationRequired), but this won't cause an error when using the API.
While both model-driven apps and canvas apps will enforce this by default, there are also ways to override it, So the API doesn't throw errors if these attributes don't have values. The API only enforces when the setting is SystemRequired, but this can only be set for system attributes.

Please make sure this is mentioned for this topic AND the other one using the maker portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2e79c6a-ef3f-502a-177d-db239641ed95
* Version Independent ID: a8f78eb8-7f1e-9b12-a815-0213df109a0e
* Content: [Create and edit fields for Common Data Service using Power Apps solution explorer - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-edit-field-solution-explorer)
* Content Source: [powerapps-docs/maker/common-data-service/create-edit-field-solution-explorer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-edit-field-solution-explorer.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@JimDaly - Thanks, Jim. This has been merged with master in https://github.com/MicrosoftDocs/powerapps-docs-pr/pull/3164. Closing issue.
