### ISSUE TITLE
Need help with this demo for cascading drop down lists

### ISSUE THREAD

**Issue by jennparker2001** [MicrosoftDocs/powerapps-docs#1582]
Hi,
I followed all steps and it seemed to work but the Location and Department that I select from the dropdown in the incidents List do not get updated.  Can you tell me how to let the selections be included in the incident list as part of the list?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by jennparker2001** [comment]
PS I'm fairly new to PowerApps so very detailed help would be much appreciated.  Hoping to be able to fix the error soon. Thank you!

**Comment by Ruokiri** [comment]
Hi Jenn, try this:

Click on Location DataCard:
1. Go to advanced;
2. Change update field by this: ddLocation.Selected_**Text**_.Result
3. Change allowed value to: Distinct(Locations, Location)

Click on Department DataCard:
1. Go to advanced;
2. Change Update field to: ddDepartment.Selected**_Text_**.Result
3. Change allowed value field to: Distinct(Filter(Locations, Location = ddDepartment.Selected.Result),Department)

**Comment by jennparker2001** [comment]
Thanks I’ll let you know if this works.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. If the problem continues, please reach out to support team with a [support ticket](https://admin.powerplatform.microsoft.com/support) for investigation.
