### ISSUE TITLE
Retired feature

### ISSUE THREAD

**Issue by formsandflows** [MicrosoftDocs/powerapps-docs#1584]
This feature is not available anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395dd469-19c0-7e60-ec4d-036418a280f6
* Version Independent ID: a7dfb7c7-2bfe-dd9e-a700-de396afd2ae8
* Content: [Use the Entity form control - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/entity-form-control)
* Content Source: [powerapps-docs/maker/canvas-apps/entity-form-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/entity-form-control.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **aneesa**

**Comment by Mattp123** [comment]
Tapan, added you as owner since this appears to be a canvas app topic.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The entity form control was experimental feature and has been deprecated. Please see an announcement [here](https://powerapps.microsoft.com/en-us/blog/deprecating-the-entity-form-control-experimental-feature-for-common-data-service/). This article will be updated accordingly.
