### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by Davago17** [MicrosoftDocs/powerapps-docs#1585]
The link to MS Learn is not working

At the bottom of the page, there is a link to Microsoft learn.
if you click on it, you get a 404

page with issue:
https://docs.microsoft.com/en-us/powerapps/maker/portals/overview
pointing to the url
https://docs.microsoft.com/en-us/earn/paths/get-started-power-apps-portals/

**Comment by tapanm-MSFT** [comment]
Thank you for reporting, the link has been fixed. Please allow some time for changes to reflect. In the meantime, you can use this link to go to Microsoft Learn path - https://docs.microsoft.com/learn/paths/get-started-power-apps-portals/
