### ISSUE TITLE
Telerik updated the Fiddler interface

### ISSUE THREAD

**Issue by naveedmcp** [MicrosoftDocs/powerapps-docs#1586]
Telerik has changed the Fiddler interface. Kindy make updates to the contents based on the latest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27f90c84-7f4a-12d3-2ddb-2bd8bb6b4aee
* Version Independent ID: b1942ba1-6e9e-6981-7862-5d11d7b51565
* Content: [Script web resource development using Fiddler AutoResponder (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/streamline-javascript-development-fiddler-autoresponder)
* Content Source: [powerapps-docs/developer/model-driven-apps/streamline-javascript-development-fiddler-autoresponder.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/streamline-javascript-development-fiddler-autoresponder.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by JimDaly** [comment]
3rd party tools will change their UI over time.
As long as it doesn't block people from understanding the steps, we won't change the screenshots.

If there is some specific item that blocks people from following the steps, please advise.
