### ISSUE TITLE
Entity Specific Help URL doesn't override the customized Global Help URL

### ISSUE THREAD

**Issue by mansimg** [MicrosoftDocs/powerapps-docs#1587]
Hi,

We have created a Model Driven App in a PowerApps Environment. The Global Help is set to custom Sharepoint URL.

The Custom entity specific URL doesn't override the Global Help URL as mentioned here.

https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/use-customizable-help

Regards
Manish

**Comment by Mattp123** [comment]
I just tested this and it works as documented. Not sure why yours isn't. You shouldn't even have to republish the app and the ? in the upper right hand of your model-driven apps will use the global help URL under system settings. Only thing I can suggest is to make sure you not enabling any of the other help settings (in the same area of System Settings) in conjunction with the global help URL. Closing issue.

**Comment by Mattp123** [comment]
@mansimg - please see my previous comment regarding this issue.
