### ISSUE TITLE
Tenant Application Identities

### ISSUE THREAD

**Issue by melody-universe** [MicrosoftDocs/powerapps-docs#1588]
How are DevOps engineers intended to use Tenant Application Identities? There are several references to them in the documentation, enough to figure out how manage them, but nothing on how to authenticate with them in order to manage environments, an essential component of healthy DevOps practices. This article seems to be the most we have on defining them, and at the time of writing, it's almost a year old.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76bcd3c2-8885-8b2b-ba2a-76dfff4ad12c
* Version Independent ID: f710837c-8ce7-c4c0-507f-f1668840d4b4
* Content: [Operations supported by Online Management API for Common Data Service - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/online-management-api/operations-supported)
* Content Source: [powerapps-docs/developer/common-data-service/online-management-api/operations-supported.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/online-management-api/operations-supported.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by tyler-hogsett-microsoft** [comment]
To clarify, the only other place in our documentation I've seen on Tenant Application Identities is in the Online Management API Reference: [https://docs.microsoft.com/en-us/rest/api/admin.services.crm.dynamics.com/tenantapplicationidentities](https://docs.microsoft.com/en-us/rest/api/admin.services.crm.dynamics.com/tenantapplicationidentities).

**Comment by KumarVivek** [comment]
@melody-universe This API is no longer available. Closing the issue.
