### ISSUE TITLE
Wrong URL in doc

### ISSUE THREAD

**Issue by laandermsft** [MicrosoftDocs/powerapps-docs#159]
The link (https://go.microsoft.com/fwlink/?LinkId=761108) in bullet 3 in the section "Sign up for the Text Analytics API" (https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/cognitive-services-api#sign-up-for-the-text-analytics-api) is not pointing to the correct location. I believe the correct URL is: https://ms.portal.azure.com/#create/Microsoft.CognitiveServicesTextAnalytics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58cccc6-9234-ec33-b4b0-3303ebe282ef
* Version Independent ID: a556f95f-240d-206b-6dd0-c2fc47b1bf11
* Content: [Use Cognitive Services in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/cognitive-services-api)
* Content Source: [powerapps-docs/maker/canvas-apps/cognitive-services-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/cognitive-services-api.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Fixed (Thanks for the feedback, @laandermsft!)
