### ISSUE TITLE
Broken page link

### ISSUE THREAD

**Issue by d7235j** [MicrosoftDocs/powerapps-docs#1590]
Additional Resource link to CRM, Accessibility and 508 is a dead/broken link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88835328-13bb-7edf-50fe-7bd5f4c4f39a
* Version Independent ID: 04e24def-7367-fa93-b9e9-9ba105c8bf62
* Content: [Create accessible web resources (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/create-accessible-web-resources)
* Content Source: [powerapps-docs/developer/model-driven-apps/create-accessible-web-resources.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/create-accessible-web-resources.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
