### ISSUE TITLE
Please add some examples with sample code

### ISSUE THREAD

**Issue by Prashant4787** [MicrosoftDocs/powerapps-docs#1591]
I can see only informative description for the fields like validation summary, validation summary css  or Custom Javascript.
It would be better if you can add some samples , code (like Adx portal documentation ) to understand it better.

Specially add a code to validate fields dynamically on the form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4c99d3-65e9-9be5-70af-9cb9d3fcda29
* Version Independent ID: cedbcc2e-1cf8-7397-ac76-1324d0b8a735
* Content: [Define entity forms - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/entity-forms)
* Content Source: [powerapps-docs/maker/portals/configure/entity-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/entity-forms.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. This is being considered for documentation updates.
