### ISSUE TITLE
Need example of how to return > 500/2000 records

### ISSUE THREAD

**Issue by ericthomas1** [MicrosoftDocs/powerapps-docs#1593]
We're left dangling a bit at the end of this doc with:

```
If the table contains more than 500 records, the formula won't return record 501 or higher, even if it matches the criteria.
```

Please provide an example for how to return more records than the delegable limit. There are ways to do this, we need to see them here. 

**Rationale:**
- When a Sharepoint data source grows beyond 2000 records, the NEWEST records (2001th, 2002nd, etc.) are the ones dropped from the query, NOT the oldest ones. 

Please provide some strategies at the end of this doc rather than a limitation. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e0bc1-6e4b-28ce-ba2f-00de8fcc6a86
* Version Independent ID: c670fff1-17d4-abf1-b2df-1da9250e552c
* Content: [Understand delegation in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-overview.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Please make use of the connectors and the respective functions when working with delegation. 

For example, a scenario in this example can have the following formula in a gallery for *Items* property that only shows records created today:

`Sort(Filter(Fruit,Created>Today()),Created,Descending)`

The example elaborates on the concept and the effects of delegation. One formula for one connection such as SharePoint for a specific function in a delegation situation may not help in all possible scenarios of connector/function combination. However, an understanding of the delegation concept helps decide the best course of action for the app maker.

Additional help:

- [Power Apps Ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas)
- [Power Apps Community forum](https://powerusers.microsoft.com/t5/Forums/ct-p/PA_Comm_Forums)
- [Help and support](https://admin.powerplatform.microsoft.com/support)
