### ISSUE TITLE
What attribute types are supported by column comparison

### ISSUE THREAD

**Issue by bthompson-365** [MicrosoftDocs/powerapps-docs#1594]
It's clear that string and numeric attributes are supported but are any other attribute types (such as datetime) supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caf1bf18-4777-bcf1-9962-2691b2ae3b37
* Version Independent ID: 875e9444-eb0e-d6f6-07a5-b0de8322392e
* Content: [Use column comparison in queries (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/column-comparison)
* Content Source: [powerapps-docs/developer/common-data-service/column-comparison.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/column-comparison.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by NHelgren** [comment]
You can use any primitive data type, that excludes things like Image and File and a few complex types. Additionally, virtual fields cannot be compared.
