### ISSUE TITLE
PowerApps Sql Azure Connector Doc Marked as Preview instead GA

### ISSUE THREAD

**Issue by LouMM** [MicrosoftDocs/powerapps-docs#1596]
https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/app-from-azure-sql-database.md

The documentation needs to be updated for the GA version of the connector and explain, or have pointers, to the new pricing model.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The feature - the ability to create apps from Azure portal for SQL Database - is currently in preview. Licensing is out of scope for this feature. For licensing, please refer to the following:
- [Licensing guide](https://go.microsoft.com/fwlink/?linkid=2085130)
- [Power Platform licensing](https://docs.microsoft.com/power-platform/admin/pricing-billing-skus)

More on the connector can be found at [SQL Server Connector reference](https://docs.microsoft.com/connectors/sql/). You can also refer to [Connect to SQL Server from Power Apps](https://docs.microsoft.com/powerapps/maker/canvas-apps/connections/connection-azure-sqldatabase) to create app using SQL Server connector.
