### ISSUE TITLE
Flows that connect to SharePoint are not available in solutions.

### ISSUE THREAD

**Issue by GarryPope** [MicrosoftDocs/powerapps-docs#1599]
Hello,

I don't think this issue is still a known issue, unless I'm misunderstanding it. I can create a Flow, within a solution and connecto to SharePoint.

Thanks,

Garry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a7715a-2b1b-29ed-99ac-0003429d5b4d
* Version Independent ID: be31d36c-9be0-cc62-1ea3-b8514fe569d9
* Content: [Solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview#known-limitations)
* Content Source: [powerapps-docs/maker/common-data-service/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/solutions-overview.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@GarryPope - yes they work now so the article has been updated to remove the limitation.
Closing issue.
