### ISSUE TITLE
Attachment feature to email forms

### ISSUE THREAD

**Issue by hyderit** [MicrosoftDocs/powerapps-docs#160]
I'm kinda new to PowerApps, however I was trying to build an email form in my app. I'm using an Excel file shared on OneDrive as a backend. I'm unable to add attachments. Here's what I tried and failed.
1- Adding a button and using the LoadData( ) fuction. 
2- Adding an Attachment control. This is supposed to show the files names of the attached files, but I can't add an attachment in the first place.
I would appreciate any help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e663e437-2bc9-980f-9ba6-6eeab01ee9a4
* Version Independent ID: ae7da14b-2234-2815-9fd1-272a0984f129
* Content: [Attachments control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-attachments)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-attachments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-attachments.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
Hey, @hyderit: As the topic says, you can use this feature with SharePoint lists and Common Data Service for Apps, not Excel. Cheers!

cc: @fikaradz
