### ISSUE TITLE
Usage clarification for Microsoft Translator

### ISSUE THREAD

**Issue by Eddcakes** [MicrosoftDocs/powerapps-docs#1600]
Hi,

On this page it states that the usage limits for using the Microsoft Translator in PowerApps is:
`This connector is limited to 150 calls per user per day.`

On the connector reference page is says there is a limit on 55,000 characters and 100 requests per minute

https://docs.microsoft.com/en-us/connectors/microsofttranslator/

Is anyone able to clarify which is the limit when using on a Power App?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470d67f4-13bc-a313-b03b-1c5c0976a2f2
* Version Independent ID: b49ad3de-6331-c439-b28a-ebe0f83523dd
* Content: [Overview of the Microsoft Translator connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-microsoft-translator)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-microsoft-translator.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-microsoft-translator.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by lancedMicrosoft** [comment]
@Sameer Chabungbam<mailto:sameerch@microsoft.com>  Who owns the translator connector?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated. For connector limitations, please visit the [connector documentation](https://docs.microsoft.com/connectors/microsofttranslator/).
