### ISSUE TITLE
Form Not Displaying List values

### ISSUE THREAD

**Issue by MarkPolaris** [MicrosoftDocs/powerapps-docs#1601]
Hi,

Firstly many thanks for this solution, which works :) However when I edit and existing record the form displays the values at the top of the Parent and Child List rather than the Value that has previously being saved. Does anyone have any advice on where i'm going wrong ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It appears that this needs to be investigated as an issue; please raise a [support ticket](https://admin.powerplatform.microsoft.com/support) so that the support teams can help you fix this issue.
