### ISSUE TITLE
Is it possible to change the layout from Phone to Tablet?

### ISSUE THREAD

**Issue by dhtoran** [MicrosoftDocs/powerapps-docs#1602]
When an app is created, is it possible to change the base layout? (from phone to tablet or viceversa)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cece2730-2d0d-98d6-3c94-d63e58fab63a
* Version Independent ID: 3187bddd-93e9-d1e3-450f-9cb6abe73853
* Content: [Change screen size and orientation of a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/set-aspect-ratio-portrait-landscape?source=docs)
* Content Source: [powerapps-docs/maker/canvas-apps/set-aspect-ratio-portrait-landscape.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/set-aspect-ratio-portrait-landscape.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. No. However, you can change the orientation and the size of the app to match as appropriate.
