### ISSUE TITLE
3-parameter operating mode missing in documentation: Concat(source, formula, separator)

### ISSUE THREAD

**Issue by BrazilianJoe** [MicrosoftDocs/powerapps-docs#1603]
DOcumentation is missing the operating mode with 3 parameters:

Concat(source, formula, separator)

This mode of operation makes the whole "Trimming the end"  - Left(Concat(...), Len(Concat...) - 2) unnecessary. 

In this mode, Concat can just pick a column and join the values with the separator, without a trailing separator to be removed with "Left() ... Len()-2" gymnastics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9b476a-3acc-3ba3-49ad-25411c4619d4
* Version Independent ID: 87fb2164-bdfc-c724-8fcd-9ae588bca62d
* Content: [Concat and Concatenate functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-concatenate)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-concatenate.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-concatenate.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
