### ISSUE TITLE
Wrong extra section

### ISSUE THREAD

**Issue by daimaukr** [MicrosoftDocs/powerapps-docs#1604]
Hello, this section - https://docs.microsoft.com/en-us/powerapps/maker/portals/web-api-perform-operations#change-the-reference-in-a-single-valued-navigation-property - is not a full example, and it repeated later with proper data. So it can be safely removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ac38ff-c39e-ef03-49e0-510544460b8f
* Version Independent ID: 4603058c-212d-8546-9d6c-69ba5e11b958
* Content: [Perform portals Web API operations - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/web-api-perform-operations)
* Content Source: [powerapps-docs/maker/portals/web-api-perform-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/web-api-perform-operations.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been updated, please allow some time to reflect the changes.
