### ISSUE TITLE
結果列が翻訳されすぎています。計算式の結果を翻訳せずに記載するべきです。

### ISSUE THREAD

**Issue by karuakun** [MicrosoftDocs/powerapps-docs#1605]
`Match および MatchAll の例`の節にある結果列が翻訳されすぎています。計算式の結果を翻訳せずに記載するべきです。

例えば

```
Match( "Bob Jones <bob.jones@contoso.com>", "<(?<email>" & Match.Email & ")>"
```

の結果は下記のように記載されるべきです。

```
{
email:   "bob.jones@contoso.com",
FullMatch: "<bob.jones@contoso.com>",
SubMatches: ["bob.jones@contoso.com" ],
StartMatch: 11
}
```

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e6e283fb-c5fa-c598-0544-002fbe025cb8
* Version Independent ID: db44c0ee-3dde-07e7-c074-d5183bb95fa2
* Content: [IsMatch、Match、および MatchAll 関数 - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/function-ismatch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-ismatch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-ismatch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jowilco** [comment]
Thank you for your feedback. We have updated the translations, and the updated translations are live. Closing this issue.

**Comment by jowilco** [comment]
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。

**Comment by bishalgoswami** [comment]
reopening for loc issue assignment test
