### ISSUE TITLE
Like operand is not correct

### ISSUE THREAD

**Issue by iChrisJ** [MicrosoftDocs/powerapps-docs#1606]
https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/add-conditional-step
In the table, we can see operands of Like are =*, ==*, **_-=_**. However, -= is not correct, should be **_~=_**

![image](https://user-images.githubusercontent.com/6956871/88155363-95b41d00-cc3a-11ea-9bd0-7f9332f141b2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 394f7d81-e547-3873-13de-80621e1f4eda
* Version Independent ID: ae841628-e071-0859-a1dc-cfff682f0930
* Content: [Configure a conditional step type for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/add-conditional-step)
* Content Source: [powerapps-docs/maker/portals/configure/add-conditional-step.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/add-conditional-step.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by iChrisJ** [comment]
#1607

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. The content has been fixed.
