### ISSUE TITLE
Gov solution package short link redirects to Microsoft homepage

### ISSUE THREAD

**Issue by sbglr** [MicrosoftDocs/powerapps-docs#1609]
The link https://aka.ms/rtw-solution currently redirects to Microsoft.com rather than to the described deployment package available on GitHub. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47c1b746-5757-5988-e5d2-d876c8a221d5
* Version Independent ID: 85b048a1-6985-6a20-bd42-d6ece4d88349
* Content: [Deploy the Return to Workplace solution - Power Apps](https://docs.microsoft.com/en-us/powerapps/sample-apps/return-to-workplace/deploy#step-1-download-the-latest-deployment-package)
* Content Source: [powerapps-docs/sample-apps/return-to-workplace/deploy.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/sample-apps/return-to-workplace/deploy.md)
* Service: **powerapps**
* GitHub Login: @wbakker-11
* Microsoft Alias: **garybird**

**Comment by narpad** [comment]
This issue has been resolved now. Sorry for the inconvenience

**Comment by KumarVivek** [comment]
Closing the issue.
