### ISSUE TITLE
Step 4 in customized formatting, the formula did not seem to work

### ISSUE THREAD

**Issue by kepacek** [MicrosoftDocs/powerapps-docs#161]
Please revise the formula, since the toggle did not work. I tried another one, which had the desired effect: If(DataCardValue2.Selected.Value= "Yes", true). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Hey, @kepacek: the formula in the doc works for me, and your formula doesn't. Are you using the default toggle control, or did you swap it for a different control? Thanks.

**Comment by kepacek** [comment]
Hi, I'm using the visible property here, as in instructions.

**Comment by AFTOwen** [comment]
Hey, @kepacek. I asked about the control, not the property. When you created the **Details** column in SharePoint, did you choose the **Yes/No** column type (which PowerApps implements as a toggle), or a **Choice** column type (which PowerApps implements as a list)?

**Comment by kepacek** [comment]
Hi Anne,

I checked, and it seems that the control was choice after all!

Best regards
Katri

Anne Frances Owen <notifications@github.com> kirjoitti su 20. tammik. 2019
klo 19.43:

**Comment by AFTOwen** [comment]
Cheers, @kepacek!
