### ISSUE TITLE
unadm

### ISSUE THREAD

**Issue by calderaramon** [MicrosoftDocs/powerapps-docs#1610]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ce5043e-e805-ac74-042b-e8600c377e04
* Version Independent ID: c521ee05-23dd-f99d-9a96-cc1b0f953206
* Content: [Average, Max, Min, StdevP, Sum, and VarP functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-aggregates)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-aggregates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-aggregates.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. There's no text in feedback. Assuming this was a typo. If not, please feel free to submit a new feedback, or update here and will reopen.
