### ISSUE TITLE
syntax error on sample code

### ISSUE THREAD

**Issue by robertoilidio** [MicrosoftDocs/powerapps-docs#1611]
Hi team, 

In the sample code provided, I would add a comment that it will return the first attribute of the Form:
`var myValue = quickViewControl.getControl(0).getAttribute().getValue();`

Alternatively, we could share a sample on how to get a value of a specific Attribute of the Quick View Form:

`var myAttributeFullNameValue =  quickViewControl.getControl().find(control => control.getName() == "fullname").getAttribute().getValue();`

Ex,:

`function getAttributeValue(executionContext) {

    var formContext = executionContext.getFormContext();
    var quickViewControl = formContext.ui.quickForms.get("MyQuickViewForm");
    if (quickViewControl != undefined) {
        if (quickViewControl.isLoaded()) {

            // Access the value of the **first** attribute bound to the constituent control
         var myValue = quickViewControl.getControl(0).getAttribute().getValue(); 
		

		// search by a specific attributename          
		var myValue3 =  quickViewControl.getControl().find(control => control.getName() == "internalemailaddress").getAttribute().getValue();

		alert (myValue3);

            return;
        }
        else {
            // Wait for some time and check again
            setTimeout(getAttributeValue, 10, executionContext);
        }
    }
    else {
        console.log("No data to display in the quick view control.");
        return;
    }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6410f3ff-5919-8af3-6529-33f4d2bc8a37
* Version Independent ID: d4da4fce-f866-f543-866f-49be97ad2cce
* Content: [isLoaded (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-quickforms/isloaded)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-quickForms/isLoaded.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-quickForms/isLoaded.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@robertoilidio 
Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
