### ISSUE TITLE
Max items in a Batch

### ISSUE THREAD

**Issue by jason-russell** [MicrosoftDocs/powerapps-docs#1612]
Just wondering what the max number of CRUD requests I can include in a batch (non-transactional)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8819d006-36f1-dc98-b866-0b13cc607e43
* Version Independent ID: 6981cff1-ab06-7cfb-45cb-e5e1f6d1b3f3
* Content: [Xrm.WebApi.online.executeMultiple (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online/executemultiple)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/executeMultiple.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/executeMultiple.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by jason-russell** [comment]
It seems to be 1000, because I get an error if I try to do more

**Comment by Nkrb** [comment]
@jason-russell 
Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
