### ISSUE TITLE
In a consideration section

### ISSUE THREAD

**Issue by AbdulWahabWarind** [MicrosoftDocs/powerapps-docs#1613]
What do you mean by 'Saved queries'? Id it saved view / entity view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc68035d-2e2e-7701-e9d4-3d0231a8bb4b
* Version Independent ID: 353c3166-8dda-a6fb-e33b-473c6c26a270
* Content: [Define calculated fields in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/define-calculated-fields)
* Content Source: [powerapps-docs/maker/common-data-service/define-calculated-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/define-calculated-fields.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@AbdulWahabWarind - Please see [Saved queries](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/saved-queries) for and explanation. The topic has been updated with a link to the aforementioned topic, which describes saved queries. Closing issue.
