### ISSUE TITLE
Not helpful.   

### ISSUE THREAD

**Issue by rayjacob** [MicrosoftDocs/powerapps-docs#1616]
Just try to add a Sql connection to azure sql server   THEN try to give it a name other than what is declared by PowerApps name (like your sign on name).  Really?  What if someone has more than one SQL connection to manage or multiple db's on same instance of SQL Server instance?  I can 'pick' the db sometimes but am looking for a SIMPLE NAME CHANGE to the displayed sql connection in list of connections.  Go to edit it and the change either CANNOT be made or doesn't reflect after the change is made.  V frustrating to use product -- what is it I'm missing?  What is it that would actually HELP in the GUI to make this work ?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5df5f2bb-1e4d-ce52-0478-19fc7a16f9b3
* Version Independent ID: fc072fdb-3e49-5e12-e8ce-ddfebca0963f
* Content: [Add and manage connections from canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-manage-connections)
* Content Source: [powerapps-docs/maker/canvas-apps/add-manage-connections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-manage-connections.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Since this is a product feedback, please raise the feedback at the [Product feedback section](https://ideas.powerapps.com/).
