### ISSUE TITLE
Northwinds Solution needs to be updated by July 31st

### ISSUE THREAD

**Issue by jwillisrose** [MicrosoftDocs/powerapps-docs#1617]
FYI - the Northwinds solution - specifically the Northwind Sample Data App - apparently uses a soon-to-be retired CDS connector:

![image](https://user-images.githubusercontent.com/12347531/88488714-19347d80-cf5d-11ea-9c01-a416708ce4a5.png)

For more: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/use-native-cds-connector

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5475653-e112-f407-b0de-ecad06bac5bf
* Version Independent ID: 9f109131-06e3-5f88-1205-233d2b6c4bf0
* Content: [Install Northwind Traders database and apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/northwind-install)
* Content Source: [powerapps-docs/maker/canvas-apps/northwind-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/northwind-install.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For sample solution and feature updates/changes, please reach out to [Power Apps Community Forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1).
