### ISSUE TITLE
Supporting Power BI Embedded Playground features in Portal Embedded Reports

### ISSUE THREAD

**Issue by oex-pbi** [MicrosoftDocs/powerapps-docs#1618]
Is there any short term plans to encorporate the features that can be used for custom embedding of reports within Portals from the Embedded Playground?

The ability to embed a Power BI report in the wave 1 release is excellent, but for my clients I need the ability to amend the settings of the embedded report - such as hiding the Pages, Filter Page, background and Edit features etc. 

Is this possible already, as there is litte guidance as to how these could be incorporated without being able to hand-craft web templates - just being able to drop in code snippets would really make this beneficial to 'super citizen developers' such as myself and my clients

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15411392-e791-a6f2-990e-e46f07c2c7cd
* Version Independent ID: 929a4c75-03be-5125-369d-9a36aae92d09
* Content: [Set up Power BI integration with your portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/set-up-power-bi-integration#enable-power-bi-embedded-service)
* Content Source: [powerapps-docs/maker/portals/admin/set-up-power-bi-integration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/set-up-power-bi-integration.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please submit an idea in the Power Platform Community - [Ideas forum](https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas) for a feature ask; and the idea can be voted for this request.
