### ISSUE TITLE
Always use LOOKUP to find the first matching record in a table, not FIRST + FILTER

### ISSUE THREAD

**Issue by yourekittenme** [MicrosoftDocs/powerapps-docs#1619]
I suggest this usage example for the PATCH function should be replaced.

`Patch( IceCream, First( Filter( IceCream, Flavor = "Chocolate" ) ), { Quantity: 400 } )`

The LOOKUP function should be used to get the first record with matching criteria from a table.  Once the first matching record is found LOOKUP stops searching the datasource.   FIRST + FILTER offers far worse performance by comparison because the FILTER function is performed on the entire datasource before the FIRST function is applied.

I'd like to have this example shown instead in the documentation instead.

`Patch( IceCream, LookUp( IceCream, Flavor = "Chocolate" ), { Quantity: 400 } )`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b39cb78-75da-5e8c-f105-1f0b9ea1b830
* Version Independent ID: 28bfec67-a78a-4a0d-cfc6-e95a560f7092
* Content: [Patch function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@yourekittenme Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
