### ISSUE TITLE
Incorrect title meta setting

### ISSUE THREAD

**Issue by georged** [MicrosoftDocs/powerapps-docs#162]
Metadata is not set correctly for this document.

&lt;meta property="og:title" content="&lt;Topic Title&gt; (Common Data Service for Apps) - PowerApps" /&gt;

As a result, page title is also wrong:
&lt;title&gt;&lt;Topic Title&gt; (Common Data Service for Apps) - PowerApps | Microsoft Docs&lt;/title&gt;

And this title shows up in the search results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de3cedad-1a27-18c2-13e2-7bd3efbf3917
* Version Independent ID: 564bf539-85db-63f0-d592-ac4cfcf27611
* Content: [&lt;Topic Title&gt; (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/developer-tools)
* Content Source: [powerapps-docs/developer/common-data-service/developer-tools.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/developer-tools.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
@phecke Can you pls take care of this.

**Comment by phecke** [comment]
@george Fixed in the next doc release.

**Comment by george** [comment]
I think you got the wrong George  😄

**Comment by KumarVivek** [comment]
@georged Closing this as its fixed.
@george Sorry about the bother :-)
