### ISSUE TITLE
Different behavior in UCI vs classic

### ISSUE THREAD

**Issue by arunvinoth** [MicrosoftDocs/powerapps-docs#1621]
Xrm.WebApi.retrieveMultipleRecords("account", "?$select=name", 3) is working differently in UCI, actually buggy. It is not limiting the results to just 3 in a page.

But it is working as expected in classic UI.  Refer this thread for more details - https://stackoverflow.com/q/63113699/7920473

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c196bb-4bbb-80e2-0bba-42d130621024
* Version Independent ID: 56d1575c-1868-34c6-992d-e3797024e413
* Content: [retrieveMultipleRecords (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords#specify-the-number-of-entities-to-return-in-a-page)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by awaisa** [comment]
I am having same issue in my PCF control while webapi to retrieve records. Looks like maxPageSize parameter is not working.

**Comment by Nkrb** [comment]
@arunvinoth Can you please confirm if this is happening now. When i run the sample code and set the maxPazeSize i just see the number of records that i have set. I'm having the 9.1.0000.2165.3 version. 

![image](https://user-images.githubusercontent.com/34038327/92813309-ce888c80-f375-11ea-8ee6-dc22fbc84938.png)

**Comment by Nkrb** [comment]
Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
