### ISSUE TITLE
[Wrong] Business process flows are currently only supported for Model driven apps

### ISSUE THREAD

**Issue by ahmedsaid313** [MicrosoftDocs/powerapps-docs#1623]
[Enter feedback here]
Business process flows are currently only supported for Model driven apps
this is an old statement, we support now both model driven and canvas app as listed in below announcement
https://powerapps.microsoft.com/en-us/blog/using-business-process-flows-in-a-canvas-app/ 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab497f2-57e7-2992-7286-d8032b6308ea
* Version Independent ID: 276b8930-20f7-8157-a983-5d0bfb6c302b
* Content: [What is Common Data Service? - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-intro.md)
* Service: **powerapps**
* GitHub Login: @clwesene
* Microsoft Alias: **matp**

**Comment by KumarVivek** [comment]
@Mattp123 Pls fix this.

@ahmedsaid313 : Thanks for your feedback.

**Comment by Mattp123** [comment]
@ahmedsaid313 - Although the blog post describes a rather complicated way to use business process flows in a canvas app, business process flows are still not considered as supported in canvas apps. Closing issue.
