### ISSUE TITLE
HTML Markup is missing all the double quotes (")

### ISSUE THREAD

**Issue by araver** [MicrosoftDocs/powerapps-docs#1624]
HTML Markup is missing all the double quotes (")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d71e01-9651-365a-0fc0-b0017d3866ca
* Version Independent ID: 507be630-f013-10d1-00dc-c57aa949f0cb
* Content: [Azure AD B2C provider settings for portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/azure-ad-b2c)
* Content Source: [powerapps-docs/maker/portals/configure/azure-ad-b2c.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/azure-ad-b2c.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. Documentation has been updated, please allow some time to reflect the changes.
