### ISSUE TITLE
Couple of environments are not listed while deploying an app

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [MicrosoftDocs/powerapps-docs#1625]
Hello,

Thank you for this solution!

As an MPP Admin, I am trying to install in the desired environment which is sandbox environment with CDS database, however that environment is not listed in the drop-down to install the package, similarly, couple of other environments including default environment are not listed in the drop-down as indicated in the following screen:

![image](https://user-images.githubusercontent.com/13658386/88775215-6d548300-d152-11ea-8da0-e85fdd574347.png)

What could be missing? Can you please clarify what type of environments would be listed here?

Thanks and Regards,
Dipti

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47c1b746-5757-5988-e5d2-d876c8a221d5
* Version Independent ID: 85b048a1-6985-6a20-bd42-d6ece4d88349
* Content: [Deploy the Return to Workplace solution - Power Apps](https://docs.microsoft.com/en-us/powerapps/sample-apps/return-to-workplace/deploy)
* Content Source: [powerapps-docs/sample-apps/return-to-workplace/deploy.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/sample-apps/return-to-workplace/deploy.md)
* Service: **powerapps**
* GitHub Login: @wbakker-11
* Microsoft Alias: **garybird**

**Comment by Mattp123** [comment]
@DiptiC-InsightRun - Unfortunately, we're unable to handle Support requests for the product here. If you're still experiencing this issue, contact Support here: https://powerapps.microsoft.com/support/

Closing issue.
