### ISSUE TITLE
Limitação

### ISSUE THREAD

**Issue by LAPSTEC** [MicrosoftDocs/powerapps-docs#1629]
Existe alguma limitação de itens dentro do recurso?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 57642536-b4f2-4a73-4fbf-a6e084aaf4bd
* Version Independent ID: 946306ff-1045-052e-6ec0-5df3cef4a236
* Content: [Controle Drop down: referência - Power Apps](https://docs.microsoft.com/pt-br/powerapps/maker/canvas-apps/controls/control-drop-down)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-drop-down.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-drop-down.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
If there are any issues, please reach out to support with a [ticket](https://admin.powerplatform.microsoft.com/support) to help with the investigation and resolve a problem.
