### ISSUE TITLE
Concurrent function in Customized SharePoint Forms

### ISSUE THREAD

**Issue by jerryyasir** [MicrosoftDocs/powerapps-docs#1631]
Hello Team,
Can you please add some reference to if we can use Concurrent function in Customized Power Apps forms for a SharePoint Lists? Is it available as preview or not available at all?

Thanks,
Jerry

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e1e231-1d0e-a328-9395-196e57086f25
* Version Independent ID: 2c862aaf-c581-aa03-0e2e-60b0fd11b769
* Content: [Concurrent function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-concurrent)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-concurrent.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-concurrent.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@jerryyasir As per the dev team suggestion, you can use concurrent function in customized SharePoint forms. Closing the issue. If you need further help, please reopen or create a new issue.
