### ISSUE TITLE
How to display images in HTML text control

### ISSUE THREAD

**Issue by peterwiensspc** [MicrosoftDocs/powerapps-docs#1633]
Please add an sample how to display an image inside the HTML text control. Tried img and a base64 encoded src. That does not worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cfe3517-9a9f-f2e7-1fe4-eb0626f95b54
* Version Independent ID: 9e1f1f35-3732-ed52-480a-2c734de4e113
* Content: [HTML text control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-html-text)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-html-text.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-html-text.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
For embedding images, please refer to [Embed multimedia files into a canvas app](https://docs.microsoft.com/powerapps/maker/canvas-apps/add-images-pictures-audio-video).
