### ISSUE TITLE
ITs seems that Comma should be replaced by semicolon for Norwegian power apps

### ISSUE THREAD

**Issue by mcmurali** [MicrosoftDocs/powerapps-docs#1634]
[Skriv inn tilbakemeldingen her]
I use Norwegian power app and wasted some hours with these code.
Later found that I should use ";" not "," as in the documentation.

Example:

If(
    IsBlank(ThisItem.'Kunde');
    "";
    IsType(
        ThisItem.'Kunde';
        [@Forretningsforbindelser]
    );
    "Firma: " & AsType(
        ThisItem.'Kunde';
        [@Forretningsforbindelser]
    ).'Navn på forretningsforbindelse';
    "Priv:  " & AsType(
        ThisItem.'Kunde';
        [@Kontakter]
    ).'Fullt navn'
)

- [ ] 

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: c9f9b1b9-dca2-1c08-fede-af21520c13cf
* Version Independent ID: 00ed57b8-11aa-81b5-3abe-a31a8d5bdc62
* Content: [AsType- og IsType-funksjoner i lerretsapper - Power Apps](https://docs.microsoft.com/nb-no/powerapps/maker/canvas-apps/functions/function-astype-istype)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-astype-istype.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-astype-istype.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@mcmurali Thanks for the feedback. Please read this article to understand more about when to use comma and semicolon https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/global-apps#formula-separators-and-chaining-operator. Closing the issue. If you need further help, please reopen or create a new issue.
