### ISSUE TITLE
The USING statements are missing

### ISSUE THREAD

**Issue by dtate22** [MicrosoftDocs/powerapps-docs#1635]
[Enter feedback here]
The reason for posting this, is as follows:
- Depending on how you create your project, you can get AMBIGUOUS references.
- This takes additional time to resolve when you just simply including the references could alleviate the problem.

Thanks for you continued good documentation!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62419bb8-985c-cb11-ac8d-2d018868c2a6
* Version Independent ID: db669ed7-d87b-c359-f5fb-3f2f1052281d
* Content: [Use OAuth with Common Data Service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth)
* Content Source: [powerapps-docs/developer/common-data-service/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/authenticate-oauth.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@dtate22  The topic has been updated and the complete VS solution made available.
