### ISSUE TITLE
Test Harness Fires updateView Twice.

### ISSUE THREAD

**Issue by ryanperrymba** [MicrosoftDocs/powerapps-docs#1637]
To illustrate, here is an example using about the most basic control one can make: a text box input. Code is below.

**init** creates a simple input box with an onChange handler to notify the system when the value is changed. It doesn't set any values. I've confirmed the onChange handler isn't firing multiple times.
**updateView** simply sets the value of the inputBox from the context parameter it receives.
**notifyOutputChanged** just sends the value from the input field. 
 
When first, loaded the framework fires the init, then updateView functions,  This populates the initial value. It does not cause the onChange handler to fire.  All OK here. 
 
But, when the user updates the value, the onChange handler fires, which calls notifyOutputChanged. In response, the framework calls getOutputs, which returns the value from the input field.  After this, the framework calls the updateView method TWICE.  The first time, it passes the old value, causing the updateView function to set the input value back to what it was. The 2nd Time, it passes the new value, causing it to set the correct value.

For a simple text field, this brief oscillation of value back to the old value, before settling on the new isn't a big problem, but causes erratic behavior on more complicated controls with multiple bindings, where it fires 10 or more times.   

This is not an issue once published to a CDS environment. It is specific to the Test Harness. 

The Code:

```
import { IInputs, IOutputs } from "./generated/ManifestTypes";

export class TextControl implements ComponentFramework.StandardControl<IInputs, IOutputs> {

    private notifyOutputChanged: () => void;
    //private currentValue: string;
    private inputField: HTMLInputElement;

    /**
     * Empty constructor.
     */
    constructor() {

    }

    /**
     * Used to initialize the control instance. Controls can kick off remote server calls and other initialization actions here.
     * Data-set values are not initialized here, use updateView.
     * @param context The entire property bag available to control via Context Object; It contains values as set up by the customizer mapped to property names defined in the manifest, as well as utility functions.
     * @param notifyOutputChanged A callback method to alert the framework that the control has new outputs ready to be retrieved asynchronously.
     * @param state A piece of data that persists in one session for a single user. Can be set at any point in a controls life cycle by calling 'setControlState' in the Mode interface.
     * @param container If a control is marked control-type='standard', it will receive an empty div element within which it can render its content.
     */
    public init(context: ComponentFramework.Context<IInputs>, notifyOutputChanged: () => void, state: ComponentFramework.Dictionary, container: HTMLDivElement) {
        //Make passed in functions available to other methods.
        this.notifyOutputChanged = notifyOutputChanged;

        //Build the control UI
        this.inputField = document.createElement("input");
        container.appendChild(this.inputField);

        //Add Change Event Listener.
        this.inputField.addEventListener("change", () => {
            console.log("fieldOnChange Fired.");
            debugger;
            this.notifyOutputChanged();
        });

    }

    /**
     * Called when any value in the property bag has changed. This includes field values, data-sets, global values such as container height and width, offline status, control metadata values such as label, visible, etc.
     * @param context The entire property bag available to control via Context Object; It contains values as set up by the customizer mapped to names defined in the manifest, as well as utility functions
     */
    public updateView(context: ComponentFramework.Context<IInputs>): void {
        debugger;
        this.inputField.value = context.parameters.value.raw || "";
    }

    /** 
     * It is called by the framework prior to a control receiving new data. 
     * @returns an object based on nomenclature defined in manifest, expecting object[s] for property marked as "bound" or "output"
     */
    public getOutputs(): IOutputs {
        debugger;
        return {
            //value: this.currentValue
            value: this.inputField.value
        };
    }

    /** 
     * Called when the control is to be removed from the DOM tree. Controls should use this call for cleanup.
     * i.e. cancelling any pending remote calls, removing listeners, etc.
     */
    public destroy(): void {
        // Add code to cleanup control if necessary
    }
}
```
​​​
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32072f2d-5d1b-0ef5-beed-2799a11e9c38
* Version Independent ID: 63ae3eba-383c-a973-dbbd-8b14fed83a81
* Content: [Common issues and workarounds (Power Apps Component Framework) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/issues-and-workarounds)
* Content Source: [powerapps-docs/developer/component-framework/issues-and-workarounds.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/issues-and-workarounds.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ryanperrymba Thanks for the feedback. This is a known issue and we are working on it.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
