### ISSUE TITLE
The website is unable to show the content as the example said

### ISSUE THREAD

**Issue by v-etzha** [MicrosoftDocs/powerapps-docs#1638]
[Enter feedback here]
I followed the sample and attempted to show one of my entity record in the web page. It showed up when in edit mode, but it didn't show up after browsing website. Any suggestion for this problem? Here is the screenshot:
![image](https://user-images.githubusercontent.com/34734408/89142994-adb16800-d57b-11ea-8d15-f17396119602.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0b55a3-c138-c07f-c500-4ce5e6277cb7
* Version Independent ID: 171e50f8-946e-16c9-586f-8e457129bc9e
* Content: [Customize content by using content snippets on a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/customize-content-snippets#example)
* Content Source: [powerapps-docs/maker/portals/configure/customize-content-snippets.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/customize-content-snippets.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by sandhangitmsft** [comment]
I see that you are not signed-in to the portal. Have you made sure that you have read access to Account entity? Otherwise please create appropriate entity permissions on account entity and assign to a web role that you want to use

**Comment by v-etzha** [comment]
Thanks for the help. Close this since no question for now.
