### ISSUE TITLE
Calendar.WeekdaysLong() & Calendar.WeekdaysShort()  descriptions

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerapps-docs#164]
Calendar.WeekdaysLong() and Calendar.WeekdaysShort() are both saying "each month" in the description - should be "each weekday" instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36db63d2-2df1-2412-02d1-bf6bd41c07b8
* Version Independent ID: 5beacc2d-a0d2-1621-c9b6-47603bb60d87
* Content: [Calendar and Clock functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-clock-calendar)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-clock-calendar.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-clock-calendar.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @ashlega!

cc: @gregli-msft
