### ISSUE TITLE
retrivemultiple is not supporting fetchXml query option ...

### ISSUE THREAD

**Issue by harshadaju** [MicrosoftDocs/powerapps-docs#1640]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b78efa0d-09e0-ebac-cce2-19362bdfb602
* Version Independent ID: 000cbd45-8d9a-bb1e-8d9a-a685fe9907b2
* Content: [Web API component - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/webapi-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/webapi-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/webapi-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by harshadaju** [comment]
I am trying to call the wepApi retrieve Multiple from updateView() life cycle method of PCF.. 

errorCode: 2147951872
message: "The query parameter $fetchXml is not supported"
![error](https://user-images.githubusercontent.com/20344059/89261968-92625d80-d64c-11ea-8f24-f444b39e345d.png)


![image](https://user-images.githubusercontent.com/20344059/89261644-07816300-d64c-11ea-9371-593407d88694.png)

**Comment by Nkrb** [comment]
@harshadaju Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
