### ISSUE TITLE
Need updated guidance for Chromium based Edge

### ISSUE THREAD

**Issue by edhans** [MicrosoftDocs/powerapps-docs#1641]
This doesn't address the new Chromium based Edge browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a250f13-0809-8505-022a-cdd001dd9af1
* Version Independent ID: 1e160456-4cdd-d220-e3c4-53fe83b911fa
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/troubleshooting-startup-issues)
* Content Source: [powerapps-docs/maker/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content is being updated; please allow some time to reflect the changes.
