### ISSUE TITLE
Notice no longer valid

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/powerapps-docs#1642]
The notice related to this section [https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-custom-help-pages#moving-content-via-solutions](url) about the possibility to add help panes only through the old solution explorer is no longer valid at least for version 9.1.0.21034 (2020 wave 1). For this version, it's the other way around: you can only add Help Pages from the new solutions area.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca73ad14-c514-cbff-8be2-f9e36ebf395a
* Version Independent ID: 38f4187d-582a-551c-d65c-3374d4d74ce6
* Content: [Create custom help pages - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-custom-help-pages)
* Content Source: [powerapps-docs/maker/common-data-service/create-custom-help-pages.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-custom-help-pages.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@nickbrandl - Thank you for your feedback. The article has been updated to remove the notice and reflect the maker portal steps for adding a help page to an unmanaged solution. Closing issue.
