### ISSUE TITLE
Alternatives to deprecated ClientGlobalContext are not (really) explained

### ISSUE THREAD

**Issue by KimBon** [MicrosoftDocs/powerapps-docs#1643]
Article explains that parent.Xrm won't work outside of a form container. Then what's the alternative for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f2e23f-87e2-62be-f107-08c2e99b97e5
* Version Independent ID: 03aa8ec3-a827-95cf-d7cf-f0a014c3484b
* Content: [GetGlobalContext function and ClientGlobalContext.js.aspx in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@KimBon ClientGlobalContext is not deprecating until Oct 1, 2021, you can still use it. Alternative methods will be available before April 1, 2021. Closing the issue. If you need further help, please reopen the issue or open a new issue.

**Comment by surfarri** [comment]
@Nkrb I believe an alternative method was supposed to be available by this date.  Is there some documentation?  We need to know we can transition our WebResources that depend on ClientGlobalContext.js.aspx.
