### ISSUE TITLE
I saw that this license is about to expire

### ISSUE THREAD

**Issue by narismadz** [MicrosoftDocs/powerapps-docs#1644]
[Enter feedback here]
https://dynamics.microsoft.com/en-us/mixed-reality/layout-transition/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b43a390f-03b4-88d9-64f9-bb4cc03b68f2
* Version Independent ID: 0f26dc6e-b6f8-2d79-b13b-ca0978927357
* Content: [Use the View in 3D component in Power Apps (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/mixed-reality-component-view-3d)
* Content Source: [powerapps-docs/maker/canvas-apps/mixed-reality-component-view-3d.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/mixed-reality-component-view-3d.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Hi, thanks for your question - however comments here are for documentation related to mixed reality components in Power Apps. For issues with Guides/Layout you'll need to follow the instructions on the page there about contacting your account manager or the Guides forum.

Thanks!
