### ISSUE TITLE
Issue with example

### ISSUE THREAD

**Issue by kurouka** [MicrosoftDocs/powerapps-docs#1645]
The example "Add images to an Image gallery control" has a mistype in point 6 "vertical gallery" and "MyPix" is not defined but comes out of nowhere without explanation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7e7fde-01ce-ca75-ce62-c93b7d53401c
* Version Independent ID: f23d9749-76cf-5fa2-ee0f-509d14944b85
* Content: [Add picture control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-add-picture)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-add-picture.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-add-picture.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The example for MyPix includes creating a collection and then the gallery control. The collection link below step 3 includes more information related link to collection documentation.
