### ISSUE TITLE
Target Parameter "Replace" and "New" are available. Please update the page.

### ISSUE THREAD

**Issue by baxist** [MicrosoftDocs/powerapps-docs#1646]
Target Parameter "Replace" and "New" are available. Please update the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69fd8dc0-ad38-444f-8a2a-ce3e4617db16
* Version Independent ID: cc0a738b-1f7e-8ad4-8dc7-d3d04697b270
* Content: [Launch and Param functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-param)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-param.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-param.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@baxist Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
