### ISSUE TITLE
Error message are not localized

### ISSUE THREAD

**Issue by Ezeckiel2517** [MicrosoftDocs/powerapps-docs#1648]
[Enter feedback here]
The section suggest that we should be able to localize error message put in business rule. My environment has 2 languages : french and english. I have exported several times my solution translation, at differents days, and the business rule error message are not there at all. I've only seen the business rule name and description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5133a12f-c678-9e84-1bb7-84d66192b2ad
* Version Independent ID: efcbf000-8b95-727b-1cf2-8d7e27bf3d95
* Content: [Create a business rule in Common Data Service - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-create-business-rule)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-create-business-rule.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-create-business-rule.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by Mattp123** [comment]
@Ezeckiel2517 - Not sure why your error message text isn't being exported as a label. Here's an example of how it works. 
1. Include an error message with a business rule. (Fig1)
![fig1](https://user-images.githubusercontent.com/21203819/95137873-d8f03900-071d-11eb-9ed9-ee6815e0a009.png)

2. Export translations. Notice the "You must do something" text included as part of the error message in the translation xlsx. (Fig2)
![fig1](https://user-images.githubusercontent.com/21203819/95137880-dbeb2980-071d-11eb-81fa-152ae8eb2f9f.png)

Closing issue.

**Comment by Ezeckiel2517** [comment]
Tested again and still no translation.
New solution.
New entity.
New business rule, add an error message.
![image](https://user-images.githubusercontent.com/15835320/96454964-8f5a2080-11ea-11eb-9760-457b4ad4ff0e.png)
Save. Activate.
Publish solution customization.
Export translation.
Open the xml, search for "something". Nothing found at all.

Have you chekc in an environment with 2 languages like I mention?
