### ISSUE TITLE
Error on Add-PowerAppsAccount

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/powerapps-docs#165]
I successfully installed using Install-Module -Name Microsoft.PowerApps.Administration.PowerShell

I tried to connect with the Add-PowerAppsAccount cmdlet with and without passing credentials, but I don't get a pop-up to enter credentials, and both methods come out with the same error. 

I get the following error: 
Add-PowerAppsAccount : Method invocation failed because [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named 'AcquireToken'.
At line:1 char:1
+ Add-PowerAppsAccount
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Add-PowerAppsAccount], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,Add-PowerAppsAccount

Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by KumarVivek** [comment]
@jimholtz Can you please follow up with James on this.

**Comment by ferrety2006** [comment]
I've since tried again and the error message has stopped...I don't know what is different, but this can be closed.

**Comment by scottdurow** [comment]
This is usually caused by there being a GAC-ed version of Microsoft.IdentityModel.Clients.ActiveDirectory.dll

After you get the error, in PowerShell run the following:
```
 [System.AppDomain]::CurrentDomain.GetAssemblies() | 
  Where-Object Location -match "Microsoft.IdentityModel.Clients.ActiveDirectory" |
  Sort-Object -Property FullName |
  Select-Object -Property Name, FullName, Location, Version |
  Out-GridView
```

You should only see a single version of the Assembly - and no location that includes GAC. If you do see a version lower than 2.19.208020213 then you'll need to uninstall the module or the assembly from the GAC.

**Comment by martincyr** [comment]
I have the same issue but not GAC assemblies and all are > 2.20.

```powershell
 [System.AppDomain]::CurrentDomain.GetAssemblies() |
>>   Where-Object Location -Match "Microsoft.IdentityModel.Clients.ActiveDirectory" |
>>   Sort-Object -Property FullName | select -First 2 |
>>   Select-Object -Property FullName, Location |fl


FullName : Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.29.0.1078, Culture=neutral,
           PublicKeyToken=31bf3856ad364e35
Location : C:\Users\me\Documents\WindowsPowerShell\Modules\Microsoft.PowerApps.Administrati
           on.PowerShell\2.0.112\Microsoft.IdentityModel.Clients.ActiveDirectory.dll

FullName : Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.7.16602, Culture=neutral,
           PublicKeyToken=31bf3856ad364e35
Location : C:\Users\me\Documents\WindowsPowerShell\Modules\AzureAD\2.0.2.130\Microsoft.Iden
           tityModel.Clients.ActiveDirectory.dll
```
