### ISSUE TITLE
"Generate Shared Access Signature" - must be activated too!

### ISSUE THREAD

**Issue by dibutil** [MicrosoftDocs/powerapps-docs#1650]
Current documentation is missing a process that is required for Azure Blob storage to operate properly - **Generate Shared Access Signature** - must be activated too!

Please, correct documentation:

"During migration, the processes may get deactivated. This may cause attachments to upload to Common Data Service instead of Azure Storage after you follow steps to add web resource. Ensure these two processes are activated to upload attachments to Azure Storage."

Must read:

"During migration, the processes: **"Azure Blob Storage Url", "AzureBlobStorageEnabled", "Generate Shared Access Signature"**,  may get deactivated. This may cause attachments to upload to Common Data Service instead of Azure Storage after you follow steps to add web resource. Ensure these two processes are activated to upload attachments to Azure Storage."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdd598f-2269-05e7-25e8-f014bef0ff6e
* Version Independent ID: 8b9996ad-708b-f5dc-3df2-d0d7e8b1a8bf
* Content: [Add Azure storage web resource to a form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/add-web-resource)
* Content Source: [powerapps-docs/maker/portals/add-web-resource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/add-web-resource.md)
* Service: **powerapps**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The documentation has been updated. Please allow some time to reflect the changes.
