### ISSUE TITLE
A is disabled to clicm

### ISSUE THREAD

**Issue by hpkeong** [MicrosoftDocs/powerapps-docs#1651]
The list is excellent from A to Z. 

But A is disabled to click. 
Please check. 

Tq

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed900e9-0ac8-8914-2bee-b04e4ebd725d
* Version Independent ID: 0ef1f99f-00f3-8344-9bd7-6cbfd96a789a
* Content: [Functions, signals, and enumerations - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/formula-reference)
* Content Source: [powerapps-docs/maker/canvas-apps/formula-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/formula-reference.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@hpkeong Thanks for the feedback. This issue is now fixed and pushed to live. Closing the issue.

**Comment by hpkeong** [comment]
Hi I have been using ForAll + Collect and ForALl + Patch without problem.But for the last 48 hours, I have been struggling on whyCollection is OK to collect, say 3 rows of dataBut, Patch will save 6 rows (double of Collection). After 48 hours of redoing and testing, finally I found thatCombination of Formula Level prefetching, Keep Recently visited screen in memory and Dynamic schemaAre creating this ISSUES – Duplicate data and Patched )Saved) when using ForAll. Please investigate. Moreover,  you have to save, publish and test then only this issue will surface. In Studio you cant see the different. BIG PROBLEM for me. Thanks   Sent from Mail for Windows 10 From: Nava KiranSent: Thursday, August 13, 2020 11:47 PMTo: MicrosoftDocs/powerapps-docsCc: hpkeong; MentionSubject: Re: [MicrosoftDocs/powerapps-docs] A is disabled to clicm (#1651) Closed #1651.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
