### ISSUE TITLE
Can "[@Value]" access Context Variable?

### ISSUE THREAD

**Issue by a49703** [MicrosoftDocs/powerapps-docs#1652]
As a result of my test, "[@Value]" can access only **_global variable_**(which is made by Set function).
**_context variable_** which is made by UpdateContext cannot be accessed by "[@Value]"
 
![image](https://user-images.githubusercontent.com/54522062/89849809-42434800-dbc4-11ea-9527-86732dca63cc.png)

**### PowerApps Document**

Chapter: Understand canvas-app tables and records in Power Apps
...
[Disambiguation](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-tables#disambiguation)

In addition, define a context variable named Value with this formula: UpdateContext( {Value: "!"} )

Let's put it all together. In this context, the following formula:

<pre>
Ungroup(
   ForAll( X,
        ForAll( Y,
            Y[@Value] & Text( X[@Value] ) & [@Value]
        )
    ),
    "Value"
)
</pre>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3bbdac7-e2a6-a187-3850-8ab94faa5f76
* Version Independent ID: e03e103f-e41a-5916-19ec-15371c80102d
* Content: [Understand tables in canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-tables)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-tables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-tables.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@a49703 Thank you for reaching us. [@Value] cannot access the Context variable. Closing the issue. If you need further help, please reopen or create a new issue.
