### ISSUE TITLE
SQL Server database - connectivity issue

### ISSUE THREAD

**Issue by picdba** [MicrosoftDocs/powerapps-docs#1653]
[Enter feedback here]
 I am able to connect when I put my CRM URL, but when I add “5558” – it fails with the message
Details: “Microsoft SQL: The target principal name is incorrect. Cannot generate SSPI context.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d27f9-66bc-5cd2-d8b5-9defc8eddfb0
* Version Independent ID: c45841f0-1488-8c30-8a7c-3a522ec63266
* Content: [View entity data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi)
* Content Source: [powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@picdba - If this is still an issue for you contact Microsoft Support. More information: https://powerapps.microsoft.com/support/ 

Closing this issue.
