### ISSUE TITLE
Cannot find Snap property in actual gallery control.

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/powerapps-docs#1655]
This page mentions the Snap property, but when using a vertical blank gallery, I am not seeing that property.  My app is PApp release 3.20071.24.

Am I missing something or should the docs provide more info (e.g. not available for vertical galleries)?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51b1efea-d75c-b595-a9a1-14dec901ab48
* Version Independent ID: 9b1b0a35-35ad-8359-e1ab-daa80ab58c19
* Content: [Gallery control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-gallery#additional-properties)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-gallery.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-gallery.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been updated and the property is removed from the documentation as no longer available.
