### ISSUE TITLE
Microsoft 365 Sku

### ISSUE THREAD

**Issue by darrengore** [MicrosoftDocs/powerapps-docs#166]
Hi There, is Power Apps Plan 2 included on the Microsoft 365 E3 or E5 plan? these were not listed in the article.

**Comment by AFTOwen** [comment]
@darrengore Which article were you looking at?

**Comment by darrengore** [comment]
Hi Anne

I could not see a response, I was looking for an answer on power apps plan 2, if it was included in M365 E3 or E5?


________________________________

**Comment by darrengore** [comment]
> @darrengore Which article were you looking at?

Hi Anne, it was https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus, the article talks only about the office 365 skus and not the Microsoft 365 skus. I am trying to find out if Power App plan 2 comes in Microsoft 365 E5?

**Comment by AFTOwen** [comment]
Thanks, @darrengore! Just confirming that was the topic; @jamesol-msft and @jimholtz are best positioned to answer your question.

**Comment by darrengore** [comment]
Thanks, if I can get an answer as soon as possible that would be great.


________________________________

**Comment by jimholtz** [comment]
@darrengore
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. The topic has been significantly rewritten since February. Please let me know if the updated content or links do not answer your question.
