### ISSUE TITLE
Fail in formula 

### ISSUE THREAD

**Issue by bobnerland** [MicrosoftDocs/powerapps-docs#1662]
This section: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-formulas#change-a-color-based-on-user-input

This formula: RGBA( Slider1.Value, Slider2.Value, Slider3.Value, 1 ) is wrong. I had to use: RGBA( Slider1.Value; Slider2.Value; Slider3.Value; 1)

Also semicolon 

R 
Bob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89cc191d-b193-c888-8d4f-04c7d01ca3d5
* Version Independent ID: 45635f6f-78a1-581b-f895-bb83b86e18f2
* Content: [Get started with formulas in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-formulas)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-formulas.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-formulas.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@bobnerland This depends on the language used. See the topic [Build global support in canvas apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/global-apps#formula-separators-and-chaining-operator) to learn more about how we use different operators in formulas.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
