### ISSUE TITLE
Started getting following error: Unable to connect to the remote server

### ISSUE THREAD

**Issue by shalabhgupta1985** [MicrosoftDocs/powerapps-docs#1664]
Hi Team,

Recently, I have started getting the following error while connecting to my D365 instance by following the step mentioned in this post.

Please refer the troubleshooting performed to isolate this issue to be something related to MS endpoint:

**In-house troubleshooting performed:**
1. Tried connecting plugin registration tool to same D365 instance with same credentials - Worked
2. Same SDK Code worked before for same D365 instance with same credentials. 
3. Similar error encountered while connecting to same D365 instance using XRM ToolBox. (which previously worked)
4. Similar error encountered while connecting to other D365 instance using XRM ToolBox. (which previously worked)

Please advise if there is some updated guidance on XRM Toolking which is been missed.

Regards,
Shalabh

While connecting to DynaXRM Toolkit

**Error Stack Trace:**
Unable to connect to CRM: Unable to connect to the remote server
Metadata contains a reference that cannot be resolved: 'https://corp.sts.microsoft.com/adfs/services/trust/mex?xsd=xsd2'. => Unable to connect to the remote server => No connection could be made because the target machine actively refused it XXX.XX.XXX.XX:XXX Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM************ NullReferenceException - WhoAmI : Execute (WhoAmI) request to CRM from IOrganizationService |=> Object reference not set to an instance of an object.
Object reference not set to an instance of an object.[TerminalFailure] Failed to Execute Command - WhoAmI : RequestID=XXXXXXXXXXXXXXXXXX : Execute (WhoAmI) request to CRM from IOrganizationService duration=00:00:00.0058175 ExceptionMessage = Object reference not set to an instance of an object.
Object reference not set to an instance of an object.OrganizationWebProxyClient is null
OrganizationWebProxyClient is nullOrganizationWebProxyClient is null
OrganizationWebProxyClient is null

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa0f3c47-59e9-8adf-3df1-307b4916b4e1
* Version Independent ID: 45357d09-689c-ac9a-78b7-1bc4a2d22771
* Content: [Quickstart: Organization service sample (C#) (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/quick-start-org-service-console-app?source=docs#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/quick-start-org-service-console-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/quick-start-org-service-console-app.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@shalabhgupta1985 Try removing the latest XrmTooling NuGet package and installing the previous or some earlier version. See if that helps.

If it does then send a message to the owner of the package (link on the NuGet package [page](https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly)) and notify them of the issue.

**Comment by shalabhgupta1985** [comment]
Hi @phecke 
Thanks for your reply.
I've followed your suggestion and still get the same error with older versions of XRMTooling Nuget packages. 
Tried following versions:
1. 9.0.2.4
2. 9.1.0.13
3. 9.1.0.51 (latest stable)

I'll reach out to owners as advised.

Thanks,
Shalabh

**Comment by MattB-msft** [comment]
There are a few issues that cause this,  and it will likely increase in frequency for existing customers over the next year or 2. 
those issues are: 

1. You acquired a new tenant and are trying to use a connection string login using AuthType=Office365. 
      -  this will fail for new tenants by default as new tenants are provisioned by AAD with MFA enabled by default and legacy authentication disabled. 
2. Your AAD admin applied "default security policies" to your tenant.  this also disables legacy authentication and enables MFA by default. 
3. Your using an instances of CDS / PowerPlatform created after October 2020 ( in the future as of this writing ) and WS-TRUST auth is disabled ( this has the same effect as disable legacy authentication ) 

Your options are as follows: 
1) Switch to use OAuth Authentication flows with Interactive login.  ( if your using connection strings you can see that here : https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect ) 
2) Use S2S login flows for non interactive users 
3) Update AAD security policy to either enabled legacy authentication, or selectively disable MFA for users ( not recommended ) 


for this particular issue.
- XrmToolbox = Use the SDK Login control option. 
in DynaXRM Toolkit - I do not know this app directly, you will need to contact the owner of this tool and ask them to update and use oAuth based flows.

**Comment by shalabhgupta1985** [comment]
Hi @MattB-msft 
Thanks for your reply. That was perfect and my issue is resolved after moving my connectionstring from O365 to OAuth.

Appreciate your help.
