### ISSUE TITLE
Get Data into CDS Date Only Field with Date Only Behavior Difficulties

### ISSUE THREAD

**Issue by PrometheanHeir** [MicrosoftDocs/powerapps-docs#1667]
I've been trying to enter data into a CDS entity that has a Date Only field which has the behavior Date Only using "Get data with Excel" but I have been encountering errors.
The error message I receive is as follows:

> Reason: Bad Request,   Error code: 0x0, Message: An error occurred while validating input   parameters: Microsoft.OData.ODataException: Cannot convert the literal   '2001-01-01T00:00:00.000Z' to the expected type 'Edm.Date'. --->   System.FormatException: String '2001-01-01T00:00:00.000Z' was not recognized   as a valid Edm.Date.   at   Microsoft.OData.PlatformHelper.ConvertStringToDate(String text)   at Microsoft.OData.ODataPayloadValueConverter.ConvertStringValue(String   stringValue, Type targetType)   at   Microsoft.OData.ODataPayloadValueConverter.ConvertFromPayloadValue(Object   value, IEdmTypeReference edmTypeReference)     --- End of inner exception stack trace ---   at   Microsoft.OData.ODataPayloadValueConverter.ConvertFromPayloadValue(Object   value, IEdmTypeReference edmTypeReference)     at   Microsoft.Crm.Extensibility.ODataV4.CrmPrimitivePayloadValueConverter.ConvertFromPayloadValue(Object   value, IEdmTypeReference edmTypeReference)     at Microsoft.OData.JsonLight.ODataJsonLightReaderUtils.ConvertValue(Object   value, IEdmPrimitiveTypeReference primitiveTypeReference,   ODataMessageReaderSettings messageReaderSettings, Boolean validateNullValue,   String propertyName, ODataPayloadValueConverter converter)   at   Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadPrimitiveValue(Boolean   insideJsonObjectValue, IEdmPrimitiveTypeReference expectedValueTypeReference,   Boolean validateNullValue, String propertyName)   at   Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String   payloadTypeName, IEdmTypeReference expectedTypeReference,   PropertyAndAnnotationCollector propertyAndAnnotationCollector,   CollectionWithoutExpectedTypeValidator collectionValidator, Boolean   validateNullValue, Boolean isTopLevelPropertyValue, Boolean   insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)   at   Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadEntryDataProperty(IODataJsonLightReaderResourceState   resourceState, IEdmProperty edmProperty, String propertyTypeName)   at   Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithValue(IODataJsonLightReaderResourceState   resourceState, String propertyName, Boolean isDeltaResourceSet)   at   Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.<ReadResourceContent>b__0(PropertyParsingResult   propertyParsingResult, String propertyName)     at   Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector   propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2   handleProperty)   at   Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState   resourceState)   at   Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()   at   Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(PropertyAndAnnotationCollector   propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)   at   Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector   propertyAndAnnotationCollector)   at   Microsoft.OData.ODataReaderCore.ReadImplementation()   at   Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)   at   System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader   reader)   at   System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader   messageReader, Type type, ODataDeserializerContext readContext)   at   System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type,   Stream readStream, HttpContent content, IFormatterLogger formatterLogger)

I've only been using the default date value that Excel uses when entering the literal value '1/1/1' (without single quotations).

I have very little experience with advanced configurations of CDS fields so I would appreciate any help with what I should be doing instead of what I have been doing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd7f723-13ae-4f83-2659-4db20fc425ec
* Version Independent ID: c1d52aee-fdc0-ea0c-2fea-414dc2942248
* Content: [Behavior and format of the Date and Time field in Common Data Service - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/behavior-format-date-time-field#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/behavior-format-date-time-field.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/behavior-format-date-time-field.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
If this is still and issue for you contact the Power Apps community or Support. 

More information: 

- https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1
- http

s://powerapps.microsoft.com/support/ 

Closing this issue.
