### ISSUE TITLE
Please add Clarification and Sample Code for File Attribute Deletion/Clear File Field

### ISSUE THREAD

**Issue by joenewstrom** [MicrosoftDocs/powerapps-docs#1669]
Hello, 2 questions on clearing/deleting file attribute values:
1. Is clearing the File Attribute Value == Deleting the File Data? Unclear from the description.
2. Is it possible to put together some Sample Code with an Example for DeleteFileRequest?

Thanks in advance,

Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c3eac9-b083-b974-0938-3e8fd19bbb58
* Version Independent ID: 2c6dfac6-25b8-876c-2b94-fa9d466007df
* Content: [File attributes (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/file-attributes#delete-file-data)
* Content Source: [powerapps-docs/developer/common-data-service/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/file-attributes.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@joenewstrom No, clearing the file attribute value does not delete the file data. This works the same as any of our other types such as attributes (DeleteAttributeRequest), entities (DeleteEntityRequest), etc.

DeleteFileRequest request = new DeleteFileRequest()
{
  FileId = new GUID(); // Put the real file ID here
};
svc.Execute(request);

**Comment by phecke** [comment]
@joenewstrom I will create a task to add a File attribute Web API sample. We do not have any at the moment. The sample should show creation, upload with chunking, and deletion. Thanks for the feedback!
