### ISSUE TITLE
Can't locate Sales Order Entity.

### ISSUE THREAD

**Issue by GeorgeWinters** [MicrosoftDocs/powerapps-docs#167]
Is this tutorial still valid? I cannot locate the 'Sales Order' entity when connecting PowerApps to the CDS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e4a709-4cf4-5e0a-fafd-d6e531cdfba2
* Version Independent ID: d68ff8b8-3694-a8a7-2ad9-9119f7666167
* Content: [Understand data-form layout for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-form-layout)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-form-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-form-layout.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
@GeorgeWinters That entity no longer exists in Common Data Service for Apps, but the principles of the topic are still valid. We've made the topic more generic so that customers can focus on the principles instead of specifics. Thanks!

**Comment by AFTOwen** [comment]
@GeorgeWinters We didn't create another topic; we updated [this topic](https://docs.microsoft.com/powerapps/maker/canvas-apps/working-with-form-layout), on which you left this comment. Cheers!

**Comment by GeorgeWinters** [comment]
It's a lot of set-up for a 14 minute read IMHO



Cordially,

George Winters
Technical Lead
Jericho IT
Kintetsu World Express USA, Inc.
1 Jericho Plaza, Suite 100
Jericho NY 11753

Tel: 516 544 7445 * NEW !
EMail: George.Winters@am.kwe.com<mailto:George.Winters@am.kwe.com>
