### ISSUE TITLE
Sorting is Disabled

### ISSUE THREAD

**Issue by AbdulWahabWarind** [MicrosoftDocs/powerapps-docs#1670]
[Enter feedback here]

If I used rollup field in a calculated field then what happens? still sorting is disabled. If Yes please mentioned this in this document.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc68035d-2e2e-7701-e9d4-3d0231a8bb4b
* Version Independent ID: 353c3166-8dda-a6fb-e33b-473c6c26a270
* Content: [Define calculated fields in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/define-calculated-fields)
* Content Source: [powerapps-docs/maker/common-data-service/define-calculated-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/define-calculated-fields.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@AbdulWahabWarind - what makes you believe that any calculated field that includes a rollup field in the calculation can't be sorted? And by sorted I believe it means it can't be sorted when added as a column in a view?

**Comment by Mattp123** [comment]
Closing issue.
