### ISSUE TITLE
Missing Advanced menu and debug Monitor tool in PowerApps

### ISSUE THREAD

**Issue by pamjustice** [MicrosoftDocs/powerapps-docs#1672]
I don't have the Advanced Tools option in my PowerApps environment therefore I can't use the Debug Monitor tool.
I am in Gov- E3 subscription.  How do I make this tool available to debug my custom apps.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c239311-eae8-f8da-a6ac-99a54f3edcd8
* Version Independent ID: d644ccf9-30b0-8f55-54a9-1ccdc029a0b4
* Content: [Debugging an app with canvas app Monitor - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/monitor)
* Content Source: [powerapps-docs/maker/canvas-apps/monitor.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/monitor.md)
* Service: **powerapps**
* GitHub Login: @aengusheaney
* Microsoft Alias: **aheaney**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The Monitor feature is still in preview and not yet available on the Government and DoD clouds. Documentation will be updated once feature is available generally, including Govt/DoD clouds.
