### ISSUE TITLE
Step by Step Example doesn't actually refer to UpdateContext function

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerapps-docs#1673]
The Step by Step Example doesn't actually refer to the UpdateContext function, maybe a better example could be created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f87513f-7937-3ed5-4586-8d94cea02238
* Version Independent ID: ca699316-4519-2448-4803-3253b642482b
* Content: [UpdateContext function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-updatecontext)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-updatecontext.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-updatecontext.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@HairyDrumroll Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
