### ISSUE TITLE
Wrong explanation for multiple-column-sort

### ISSUE THREAD

**Issue by veithflo** [MicrosoftDocs/powerapps-docs#1675]
The whole logic with sorting multiple columns is wrong on this page.

> To sort first by one column and then by another, you embed a Sort formula within another. For example, you can use this formula to sort a Contacts table first by a LastName column and then by a FirstName column: Sort( Sort( Contacts, LastName ), FirstName )

When using _Sort(Sort(Tab;ColA);ColB)_ the outer Sort() will happen after and therefore overwriting the inner Sort(). In the Quote above it's the exact opposite. Your output table will be sorted primary by the FirstName and secondary by the LastName.

> The parameter list for SortByColumns provides the names of the columns to sort by and the sort direction per column. Sorting is performed in the order of the parameters (sorted first by the first column, then the second, and so on).

Same wording as in quote above, but this times it's correct. See example below.

> Sort( Sort( IceCream, OnOrder ), Quantity )
> SortByColumns( IceCream, "OnOrder", Ascending, "Quantity", Ascending )

This is one line of the examples on the bottom of the page. For both ways of sorting, the same example with same result. But when i do both methods on the same table, i get different results due to the hierarchically processing of sub-functions.

Here my test example:
```
ClearCollect(colDEBUG;Sort(Table(
    {RowNum:1;ColA:1;ColB:1};
    {RowNum:2;ColA:1;ColB:2};
    {RowNum:3;ColA:2;ColB:2};
    {RowNum:4;ColA:3;ColB:3};
    {RowNum:5;ColA:1;ColB:3}
);RowNum;Descending))

_SortByColumns(colDEBUG;"ColA";Ascending;"ColB";Ascending)_ ==> Output order: 1,2,5,3,4
_Sort(Sort(colDEBUG;ColA;Ascending);ColB;Ascending)_ ==> Output order: 1,2,3,5,4
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e858d5-dbbb-9200-d867-a8b597de4df3
* Version Independent ID: d45b98b2-e452-c295-39ed-90468f40a0c1
* Content: [Sort and SortByColumns functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-sort)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-sort.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-sort.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Apologies for late response, not sure if you're still facing same problem anymore. Documentation shows results based on sorting as depicted, and the above example provided shows different results than what you provided. If there's any issues, please reach out through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for investigation and help.
