### ISSUE TITLE
What is the purpose of the 'Default' filter on the fields that I can add to the view?

### ISSUE THREAD

**Issue by Customery** [MicrosoftDocs/powerapps-docs#1681]
I spent 5 minutes trying to add Owner to the Active Accounts view, but it wasn't there because the Owner field is hidden when the Default field filter is applied. I had to change the filter to All so that the Owner field could be selected.

'Default' appears to include almost all, but not quite all, of the fields. It's useless.

If it's going to remain, then the documentation should be updated to tell users to switch to 'All' when trying to add a field that appears hidden in the selector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d187e12-7791-3ece-5b32-0964272eed82
* Version Independent ID: 35ade74f-cb15-9197-5187-c45ba72932f9
* Content: [Create and edit public or system model-driven app views with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-edit-views-app-designer)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-edit-views-app-designer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/create-edit-views-app-designer.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Customery - thanks for your feedback. The topic section has been updated to provide a Tip to select All when you can't find the column you're looking for. Closing issue.

**Comment by Customery** [comment]
Hi Matt, thanks for letting me know about the update. I’ve never met a user who found the ‘Default’ filter useful since it appears to exclude often used fields. A better resolution (because the attribute search feature works so well) would be to remove the filters altogether.


Neil Benson
Managing Director
Brisbane, QLD, Australia
Tel: +61 484 322 232
Email: neil.benson@customery.com
Web: customery.com
Brisbane (AEST) is UTC+10
Become a Customery Insider
