### ISSUE TITLE
Links not working in documentation

### ISSUE THREAD

**Issue by StevenRasmussen** [MicrosoftDocs/powerapps-docs#1682]
2 of the 3 links at the bottom of the page are not working:

- Create Early-Bound Entity Classes with the Code Generation Tool (CrmSvcUtil.exe)
- Use the Early Bound Entity Classes for Create, Update and Delete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0949367-dc3e-ba70-b494-8945530a6fed
* Version Independent ID: 93472f86-1b45-0421-2e1e-7e2857e64534
* Content: [Create extensions for the code generation tool (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/extend-code-generation-tool)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/extend-code-generation-tool.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/extend-code-generation-tool.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@StevenRasmussen Thanks for reporting this.
@phecke 
There should be valid targets within the Power Apps CDS documentation for all three links at the bottom of this page.
Can you update these?

**Comment by phecke** [comment]
@StevenRasmussen @JimDaly 

This has been fixed and will be published by EOD today. Thanks for notifying us.

I removed the broken links from the _extend_ topic and added new links to the related  _generate_ topic.
