### ISSUE TITLE
Looking for sample js on how to call ExternalWebApiController Ping / Who Am I calls

### ISSUE THREAD

**Issue by andrewbackway** [MicrosoftDocs/powerapps-docs#1683]
Looking for sample js on how to call ExternalWebApiController Ping / Who Am I calls
The other included JS samples are great on getting tokens etc... looking for guidance on how to hook up to power portal.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b13c93b-4010-8d18-2d23-6d1ccf31400d
* Version Independent ID: a2910c25-ea1a-6373-d242-2c17f8886cf7
* Content: [Use OAuth 2.0 implicit grant flow within your portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/oauth-implicit-grant-flow)
* Content Source: [powerapps-docs/maker/portals/oauth-implicit-grant-flow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/oauth-implicit-grant-flow.md)
* Service: **powerapps**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can try this:

```Request
GET [Organization URI]/api/data/v9.0/WhoAmI() HTTP/1.1
 Accept: application/json
 OData-MaxVersion: 4.0 
OData-Version: 4.0 
```

```
Response 
HTTP/1.1 200 OK  
Content-Type: application/json; odata.metadata=minimal  
OData-Version: 4.0  
{  
"@odata.context": "[Organization URI]/api/data/v9.0/$metadata#Microsoft.Dynamics.CRM.WhoAmIResponse",  
"BusinessUnitId": "GUID",  
"UserId": "GUID",  
"OrganizationId": "GUID"  
}
```
More information: [Use Web API functions](https://docs.microsoft.com/powerapps/developer/data-platform/webapi/use-web-api-functions)
