### ISSUE TITLE
RetrieveTotalRecordCount inaccuracy

### ISSUE THREAD

**Issue by MarkMpn** [MicrosoftDocs/powerapps-docs#1685]
This page indicates that `RetrieveTotalRecordCount` should be used to get the total record count for > 5000 records. However, the result of this function can be slightly inaccurate when compared to either an aggregate query or simply retrieving and counting the records.

It would be helpful to have some description on the `RetrieveTotalRecordCount` page that describes the limits within which the returned value is accurate (e.g. within *x*%, cached for *x* minutes or whatever the system is doing that leads to this discrepancy) in order for the consumer to make an informed decision on when it is appropriate to use this function or when it might be necessary to use another method to get the more accurate result.

The `RetrieveTotalRecordCount` page (https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/retrievetotalrecordcount?view=dynamics-ce-odata-9) and `RetrieveTotalRecordCountRequest` page (https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.retrievetotalrecordcountrequest?view=dynamics-general-ce-9) would probably be the most appropriate places for this information, but they do not seem to offer leaving feedback so raising this issue here instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by RobHess05** [comment]
Any update on this bug @JimDaly @mayadumesh ?  My count does not update, even after executing a publishXML action. 
For example:  https://mysite.crm.dynamics.com/api/data/v9.2/RetrieveTotalRecordCount(EntityNames=['asyncoperation'])

**Comment by MarkMpn** [comment]
The docs have been updated at some point to clarify that the count is taken from a cached view created at some point in the past 24 hours, so it appears that there isn't a way to force this to update any longer.

**Comment by RobHess05** [comment]
Thank you @MarkMpn , you are correct.
Documentation ref for anyone who stumbles across this:  https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/retrievetotalrecordcount?view=dataverse-latest 

@JimDaly @mayadumesh This limitation makes it incredibly difficult for us to bulk load \ validate data when migrating new customers onto your product.  I'm sure there's a resource hit when this is called, but it would be nice if we could pass in an additional parameter to get a live number, and not a cached number.

**Comment by JimDaly** [comment]
Seems I forgot to close this after updating the docs, or someone else updated them.
From a documentation perspective, I have to say this issue is closed.
From a feature perspective, I don't find any ideas mentioning `RetrieveTotalRecordCount` on the [ideas site](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
