### ISSUE TITLE
There is so no ability for tenant admins to delete developer environments (August 2020) from the user interface.  PowerShell works.

### ISSUE THREAD

**Issue by readyxrm** [MicrosoftDocs/powerapps-docs#1687]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ec6689-7baa-94ad-65b2-a7635daf277e
* Version Independent ID: f076de06-b509-f686-f334-18891a1a6cda
* Content: [Power Apps Community Plan -- a free development environment for individual use - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan#can-i-delete-my-individual-environment)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by KumarVivek** [comment]
@readyxrm Let's follow up internally on what needs to be done for this issue. Closing this issue.
