### ISSUE TITLE
getIsDirty (Client API reference)I want to know whether any fields in the form have been modified? 

### ISSUE THREAD

**Issue by seared2008** [MicrosoftDocs/powerapps-docs#1688]
[Enter feedback here]
I want to know whether any fields in the form have been modified? 
i want get the value of modified before.

example
  Account main form field name 
    Account Name
  Now:
   DB record Value：xxx1
   Account main form  account name value: xxx2
quetions:
now i want to get the Account name value:xxx1
what can i do?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09222be-5bb2-6600-2435-2bbffbcdd64f
* Version Independent ID: f73b4119-b2a0-54e9-d5ce-6e4f2d90c9ae
* Content: [getIsDirty (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-entity/getisdirty)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/getIsDirty.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/getIsDirty.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@seared2008 Did you try using the [getDataXml](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-entity/getdataxml) method, this method returns the list of fields with modified values. Let me know if that worked for you.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
