### ISSUE TITLE
Unclear scope of function RequestHide()

### ISSUE THREAD

**Issue by SpinnerWebs** [MicrosoftDocs/powerapps-docs#1689]
The note at the top of the page currently states that RequestHide "only works with SharePoint forms." However, later on in the page, under "Considerations", it says "using RequestHide() outside the context of a SharePointIntegration control [...] won't have any effect". This implies that RequestHide() can be used in SharePointIntegration controls as well as SharePoint forms.

It also says that it is "not required when using SharePointIntegration control actions such as OnCancel". It is not clear whether this means all SharePointIntegration control actions, or just a subset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4fc0b9-cb92-b37b-d569-af363efefdf7
* Version Independent ID: 3a9ece6e-eb3b-2b9c-1afb-51525058be78
* Content: [RequestHide function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-requesthide)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-requesthide.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-requesthide.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content has been updated. Please allow some time to reflect the changes.
