### ISSUE TITLE
Incomplete information [Sys reqs, limits, etc.]

### ISSUE THREAD

**Issue by JS2Code** [MicrosoftDocs/powerapps-docs#169]
There are other limitations like camera control image and resolution size, max size of media and Storage limits for offline apps etc are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdf0872-929b-e44a-dedd-eb6a759915f2
* Version Independent ID: 0b65b025-62f8-fc2a-0026-3cb96b7b4554
* Content: [System requirements, limits, and configuration values for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
@JS2Code, we've added a new article on data types that [covers size limitations](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types#size-limits).  In short, there are no built in limitations, however the memory available to an app especially on older devices can be problematic, requiring apps to be tested with those configurations if there is a concern.

**Comment by gregli-msft** [comment]
@aftowen, please close this issue.

**Comment by AFTOwen** [comment]
@JS2Code We've also added a link from this topic to the new information. Cheers.
@gregli-msft FYI.
