### ISSUE TITLE
Iframe doesn't load the app

### ISSUE THREAD

**Issue by danilomm1** [MicrosoftDocs/powerapps-docs#1691]
[Insira comentários aqui]
I've used this instructions to set a sharepoint 2010 page in January and it worked fine, but now after powerapps API release on Aug 21st is not working anymore. 

What adjustments do I need to do on my iframe?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5aa66ed7-7906-598f-ab43-bec289e1ccd3
* Version Independent ID: 1a73b184-050a-26be-b362-4cab5328c541
* Content: [Integrar aplicativos de tela em sites e em outros serviços - Power Apps](https://docs.microsoft.com/pt-br/powerapps/maker/canvas-apps/embed-apps-dev)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-apps-dev.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/embed-apps-dev.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by danilomm1** [comment]
I believe the problem is between Sharepoint 2010 and powerapps, I've tested another iframe with other pages and works good. 
I see that Powerapps is maybe requiring a token that my sharepoint site cannot respond.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please contact support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) to help with investigating the issue.
