### ISSUE TITLE
Restrict Provisioning Developer Environment

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/powerapps-docs#1693]
[Enter feedback here]
Hello team,

Kindly update the document about the Developer Environment type:

_Developer | Developer environments are created by users who have the Community Plan license. They're special environments intended only for use by the owner, and they can't be shared with other users. Provisioning developer environments can't be restricted **unless through a support ticket.** | Only a single user account with the Community Plan has access._
-- | -- | --

From:
https://docs.microsoft.com/en-us/power-platform/admin/environments-overview#types-of-environments

And also in this current article:
https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan#can-i-delete-my-individual-environment

UPDATE:
To restrict provisioning the Developer environment, tenant-level admin needs to block "internal consent plans"

1. First install the latest version of the module:
    Install-Module -Name Microsoft.PowerApps.Administration.PowerShell -Force
2. Now internal plans can be removed using the command:
    Remove-AllowedConsentPlans -Types "Internal" 
3. To allow a particular type of plan, you can use the command:
    Add-AllowedConsentPlans -Types "Internal"
4. Review the currently allowed consent plan types within the tenant:
    Get-AllowedConsentPlans

In addition, to block self-service sign up, the tenant admin can turn off the AAD setting "AllowAdHocSubscriptions". 
More information about this topic can be found here: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-self-service-signup.

References:
https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell
https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/remove-allowedconsentplans?view=pa-ps-latest

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ec6689-7baa-94ad-65b2-a7635daf277e
* Version Independent ID: f076de06-b509-f686-f334-18891a1a6cda
* Content: [Power Apps Community Plan -- a free development environment for individual use - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan#can-i-delete-my-individual-environment)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by Mattp123** [comment]
@DavidPaf - Thanks for your feedback. The article has been updated to link to the Power Platform admin center article that describes how to restrict the creation of developer environments.
Closing issue.
