### ISSUE TITLE
Should Intellisense work for this?

### ISSUE THREAD

**Issue by KarlaK-fl** [MicrosoftDocs/powerapps-docs#1695]
I've followed the instructions, and I don't get any intellisense features, and I get the red squiggly lines under each table and field I reference. Is that how it's supposed to work or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by mayadumesh** [comment]
No, intellisense is not provided for connections to CDS as you are not collecting to database but the service with logical data structures it is not something that we could provide yet. Stay tuned!

**Comment by phecke** [comment]
@KarlaK-fl See response from Maya above.
