### ISSUE TITLE
gif is distracting

### ISSUE THREAD

**Issue by onetalltree** [MicrosoftDocs/powerapps-docs#1696]
you have a gif that keeps changing, but it's not pausable so I can't actually  look at it. Very distracting.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709f9e54-c965-5dc4-b64f-3d90037626be
* Version Independent ID: 45011eec-04a4-01b4-2ab8-70677e910f3b
* Content: [What are code components? - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/custom-controls-overview)
* Content Source: [powerapps-docs/developer/component-framework/custom-controls-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/custom-controls-overview.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@onetalltree Unfortunately, we don't have a way to pause the Gifs in between. I have made changes to slow it down and put a long pause at the end. Will push the changes live by EOD. Closing the issue.
