### ISSUE TITLE
TileURL Syntax Bug?

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/powerapps-docs#1698]
Opened a case with Microsoft and they came back with a correction on the TileURL. Microsoft Support said that the TileURL should be in this format:
`<TileUrl>https://app.powerbi.com/reportEmbed?reportId=_{ReportGUID}_&amp;groupId=_{GroupGUID}_</TileUrl>`

Updated the syntax and it fixed the issue on two different Tenants.

Not sure if this is always required or only sometimes required, but this fix is undocumented. Microsoft Case #120072224005634.

Joel
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715bc26c-2ccd-a040-3c96-d73cde4b982b
* Version Independent ID: c793e872-29e4-2e04-b9f4-973c01d4a123
* Content: [Embed a Power BI report in a model-driven system form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embed-powerbi-report-in-system-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by JoelLeichty** [comment]
Any further thoughts on this?

The other key point on this is that the GUID for reportId and for groupId must be lowercase, same as they appear in the Power BI URL.

**Comment by Mattp123** [comment]
@JoelLeichty - sorry for the delay in my response. Adding the group Id to the tileurl shouldn't be necessary to get this to work (as per the article). You do need the correct group ID (which you can get from the PBI service URL for the report) in the PowerBIGroupId element block, as you've indicated (as well as the correct report ID that gets added to the PowerBIReportId element block and TileUrl element block -- as per the article).

I tried this myself and the main form section where I made the customizations.xml changes did display the PBI report as expected for me. The article has been updated to hopefully make it more clear what is needed to get this working. 

Closing issue.
