### ISSUE TITLE
TokenCacheStorePath Bad Example

### ISSUE THREAD

**Issue by paul-interdyn** [MicrosoftDocs/powerapps-docs#1699]
In the section titled, "OAuth using current logged in user with fall back UX to prompt for authentication," the example value for TokenCacheStorePath is "c:\MyTokenCache" but that doesn't actually work. The path needs to be a file, so it should be "c:\MyTokenCache\msal_cache.data"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8213b8-93bc-dee0-5b82-973db16f03fa
* Version Independent ID: 161512ac-81c1-4163-20e1-e440497d2e24
* Content: [Use connection strings in XRM tooling to connect to Common Data Service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@paul-interdyn Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
