### ISSUE TITLE
"Move between apps" feature is a set back

### ISSUE THREAD

**Issue by YahyaManasrah** [MicrosoftDocs/powerapps-docs#1700]
For that it has cancelled the navigation menu which is very very important for users..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46216c83-4fb2-1be0-b3ad-a909be419e32
* Version Independent ID: c287a530-09df-f62c-c30e-a8ec2e051973
* Content: [Basic navigation in a model-driven app - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/navigation)
* Content Source: [powerapps-docs/user/navigation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/navigation.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@YahyaManasrah the menu is still there. When you move between apps in the current release you click the drop-down menu and then choose an app. In Preview, you select app name and then you can choose the app you want to use.

https://docs.microsoft.com/en-us/powerapps/user/navigation#move-between-app

If you product feedback, visit https://ideas.powerapps.com.

Thanks,
Mints
