### ISSUE TITLE
Updates required

### ISSUE THREAD

**Issue by zbacalhau** [MicrosoftDocs/powerapps-docs#1701]
I tried to follow the instructions on the page however became stuck on the PowerApps connections required. I was able to connect for M365 and Teams however had an additional requirement for Content Convertor which I couldn't connect to, find in the list etc. 
Thanks - Zanna.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication app - sample template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Please reach out to support teams with a [support service ticket](https://admin.powerplatform.microsoft.com/support) to investigate this issue.
