### ISSUE TITLE
Clicking Edit.. on Power BI does not opening the PowerApp. Only goes to the PowerApp main page

### ISSUE THREAD

**Issue by SamRockX** [MicrosoftDocs/powerapps-docs#1702]
**Uploaded Video showing the below problem**
I followed the article faithfully and ensure I have all steps right. I added all my columns to the Power App visuals in Power BI and clicked "Create App". A new App was created for me and I was able to Cross Filter from Power BI to Power App. All Good!

But when I closed my PBIX file on my Power BI Desktop and reopened it the next day, no matter how many times I click "Edit", I am not directed to the App Edit page,  Power BI shows up the URL Alert,  but after clicking OK, it only takes me to Power BI main page. Not the actual App.

This is preventing me from Adding new column to the PA visual or test the functionality like Gallery becuase there is not PowerBIIntegration.Data available.

Please help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f94c3-694a-6d09-3a4f-e4b741684822
* Version Independent ID: c952e698-a2bf-a47d-acbd-a96a8a922636
* Content: [Power Apps visual for Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual)
* Content Source: [powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **ropur**

**Comment by SamRockX** [comment]
I have recorded the steps to show that Edit doesnt open the app. I have tried on Two different browsers and it the sam problem
[Power BI to Power App- Edit Not opening the App.zip](https://github.com/MicrosoftDocs/powerapps-docs/files/5133678/Power.BI.to.Power.App-.Edit.Not.opening.the.App.zip)

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Looks like this should be investigated as an issue by our support teams. Please create a [support ticket](https://admin.powerplatform.microsoft.com/support) and the support teams can help you investigate the problem.
