### ISSUE TITLE
Broken link to synchronization sample

### ISSUE THREAD

**Issue by Chielus** [MicrosoftDocs/powerapps-docs#1703]
The link "Synchronize data with external systems using change tracking" seems to be broken, redirects to the homepage of the samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58ecc49-fb0d-9b63-ad2b-fd2134e7bd72
* Version Independent ID: 6f1a2c83-46b7-e8d8-4057-fa9660c9eef6
* Content: [Use change tracking to synchronize data with external systems (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-change-tracking-synchronize-data-external-systems#retrieve-changes-for-an-entity-using-the-organization-service)
* Content Source: [powerapps-docs/developer/common-data-service/use-change-tracking-synchronize-data-external-systems.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-change-tracking-synchronize-data-external-systems.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by Nkrb** [comment]
@Chielus Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
