### ISSUE TITLE
Datatable, "Order" property

### ISSUE THREAD

**Issue by hpkeong** [MicrosoftDocs/powerapps-docs#1707]
I found there is new property called Order but not mentioned in documentation. Tried several times but no specific effect and can't guess what is this for. 
Please add into documentation or would be better to have hint text over the property inside powerapps. 

Tq

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af82396d-69f1-daf7-be8c-15c1a841bd19
* Version Independent ID: d97646e7-abe7-51f3-6d06-0eb86a441d5d
* Content: [Data table control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-data-table)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-data-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-data-table.md)
* Service: **powerapps**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The **Order** property is available for the the order of the columns, not for entire data table. For example, selecting a second column from the left will have a column **Order** of 2. First column will have it as 1. And changing this order changes the order of columns from left to right. In this example, if we change column with order of 1 to 2, and the other one from 2 to 1, the order of columns is reversed for a two-column data table. Documentation will be updated in some time.

**Comment by hpkeong** [comment]
Hi Tapan Maniar Appreciate your reply.Will follow up closely.TQ Sent from Mail for Windows 10 From: Tapan ManiarSent: Wednesday, September 2, 2020 12:49 PMTo: MicrosoftDocs/powerapps-docsCc: hpkeong; AuthorSubject: Re: [MicrosoftDocs/powerapps-docs] Datatable, "Order" property (#1707) Thank you for reaching out. The Order property is available for the the order of the columns, not for entire data table. For example, selecting a second column from the left will have a column Order of 2. First column will have it as 1. And changing this order changes the order of columns from left to right. In this example, if we change column with order of 1 to 2, and the other one from 2 to 1, the order of columns is reversed for a two-column data table. Documentation will be updated in some time.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
