### ISSUE TITLE
pageSize is not available from TS

### ISSUE THREAD

**Issue by MaTeMaTuK** [MicrosoftDocs/powerapps-docs#1709]
Docs contains information about pageSize property and I may see it from debugger.
However It is not available from TS.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d40f22d-3206-3b47-5cbe-0e557fa0bd07
* Version Independent ID: 1d5b0fbd-9b5d-d605-6553-138d0f7e2316
* Content: [Paging - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/paging)
* Content Source: [powerapps-docs/developer/component-framework/reference/paging.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/paging.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
