### ISSUE TITLE
Dated! [Office 365 Outlook connector]

### ISSUE THREAD

**Issue by mnelson10000** [MicrosoftDocs/powerapps-docs#171]
This article needs updating and expanding.  Some info about adding and removing contacts would be nice!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbce0fbc-150d-5a31-2096-2f36eea12a26
* Version Independent ID: 13bb945a-845b-fbe2-c65a-a944a92ea368
* Content: [Overview of the Office 365 Outlook connection - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-outlook)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-office365-outlook.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-office365-outlook.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by AFTOwen** [comment]
Thanks for your feedback, @mnelson10000. You can find information about adding and removing contacts in the [reference topic for this connector](https://docs.microsoft.com/connectors/office365connector/#actions).

cc: @lancedMicrosoft
