### ISSUE TITLE
Wrong formula in "Set conditional formatting"

### ISSUE THREAD

**Issue by ediordna** [MicrosoftDocs/powerapps-docs#1710]
The formular written in the support page in the section "Set conditional formatting": `If(DataCardValue2.Value = true, true)`
is wrong (now). It has to be:
`If(DataCardValue2.Value = true; true)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a8c4146-101d-7ba2-7ae0-d7138b743154
* Version Independent ID: 1f752762-0809-a2fb-4a03-b490547ee7f1
* Content: [Customize a SharePoint list form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Looks like the formula `If(DataCardValue2.Value=true,true)` works fine. If there are any issues, please reach out to our support teams to help you investigate by creating a [support ticket](https://admin.powerplatform.microsoft.com/support).
