### ISSUE TITLE
GlobalContext.isOnPremises() title has typo, says isOnPremise

### ISSUE THREAD

**Issue by calvinmit** [MicrosoftDocs/powerapps-docs#1713]
The title is inconsistent with the content and the implementation.  The title says isOnPrremise, but the actual function has an 's' at the end.  This may have been the cause for a bug in DefinitelyTyped types/xrm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8be3313-bb71-2fb5-abbb-7ac19c07bd3a
* Version Independent ID: b0339386-edd6-1e05-367d-ea0a294aa34e
* Content: [isOnPremise (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/isonpremises)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/isOnPremises.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/isOnPremises.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@calvinmit 
Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
