### ISSUE TITLE
page contains link to deprecated build tool

### ISSUE THREAD

**Issue by onetalltree** [MicrosoftDocs/powerapps-docs#1715]
page links to: https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerApps-BuildTools
PowerApps BuildTools - DEPRECATED (0.3.7)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c487a-6048-5ed1-d3b3-f15756f0f953
* Version Independent ID: 35502302-bdf4-6a02-11cb-dea21d9fa7ff
* Content: [Import components - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls)
* Content Source: [powerapps-docs/developer/component-framework/import-custom-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/import-custom-controls.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@onetalltree Thanks for the feedback. We have updated the docs and pushed live. Closing the issue.
