### ISSUE TITLE
unclear language

### ISSUE THREAD

**Issue by onetalltree** [MicrosoftDocs/powerapps-docs#1716]
Language like this is unclear: "Navigate to the root directory where the code component project is created."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c487a-6048-5ed1-d3b3-f15756f0f953
* Version Independent ID: 35502302-bdf4-6a02-11cb-dea21d9fa7ff
* Content: [Import components - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls)
* Content Source: [powerapps-docs/developer/component-framework/import-custom-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/import-custom-controls.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@onetalltree Thanks for the feedback. How about changing the line like this "Go in to the folder where you have created the code component project"? Does it makes sense and is understandable?

**Comment by onetalltree** [comment]
Here's what I wrote in my personal documentation:

"Navigate to the directory where the **.cdsproj** file is located (_Solution_). In this project the directory is source/Solution/..."

and 

"Navigate to directory where the **.pcfproj** file is located"

I found this by issuing the various build commands and reading the error messages that told me what file it was looking for.

**Comment by Nkrb** [comment]
@onetalltree Sure, it makes sense. Will update the docs. Thanks for the suggestion.

**Comment by Nkrb** [comment]
Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
