### ISSUE TITLE
PowerApps Push Notifications: Is this a Standard Connector or a Premium Connector?

### ISSUE THREAD

**Issue by schneika** [MicrosoftDocs/powerapps-docs#1718]
PowerApps Push Notifications: Is this a Standard Connector or a Premium Connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f798dd89-a068-3237-795e-5afe0de7dded
* Version Independent ID: 63dbbfb6-11dc-d7be-3f4b-53417e9c5246
* Content: [Send a push notification - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-notifications)
* Content Source: [powerapps-docs/maker/canvas-apps/add-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-notifications.md)
* Service: **powerapps**
* GitHub Login: @Kavishi
* Microsoft Alias: **kaagar**

**Comment by mduelae** [comment]
For canvas apps it is standard. Though, sending push notifications to model-driven apps will only work if you have a model-driven app, which is premium.

Hope this helps.

Thanks,
Mints
