### ISSUE TITLE
Missing Dashboard Navigation Documentation

### ISSUE THREAD

**Issue by clurdish** [MicrosoftDocs/powerapps-docs#1719]
This page is missing documentation regarding navigation to a dashboard. It should include the following documentation of the API.

<p>----------------------------------------------------------------</p>
<p><strong>dashboard</strong>
<p>The object contains the following attributes:</p>
<ul>
<li><strong>pageType</strong>: String. Specify "dashboard".</li>
<li><strong>dashboardId</strong>: (Optional) String. The ID of the dashboard to load. If you don't specify it, navigates to the default dashboard.</li>
</ul>
<p>----------------------------------------------------------------</p>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@clurdish Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
