### ISSUE TITLE
Wrong odata.bind name?

### ISSUE THREAD

**Issue by dwcai** [MicrosoftDocs/powerapps-docs#172]
Don't think "customerid_account@odata.bind" is right in the document, it should be "customerid@odata.bind". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6444b56-0e82-a336-244d-67e4c3aeed05
* Version Independent ID: cb15df8b-5ef7-25b4-24cb-a48a4ec14e9d
* Content: [Associate and disassociate entities using the Web API (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **crm-online**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by kjetilroe** [comment]
The documentation is correct. The odata.bind for customerid is: "customerid_account@odata.bind" for account and "customerid_contact@odata.bind" for contact binding.

**Comment by phecke** [comment]
@dwcai The documentation is correct.
