### ISSUE TITLE
Need Real Example for Feedback and Ratings

### ISSUE THREAD

**Issue by MSIH** [MicrosoftDocs/powerapps-docs#1720]
I was expecting to find out how to support ratings and feedback in my power app with CDS. Instead you provide the vague design suggestion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abe133be-0d0e-832d-3047-f62769ae4bec
* Version Independent ID: 076bfdf5-7e8e-f5d6-5409-160254c16667
* Content: [Configure an entity for feedback with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/configure-entity-feedback)
* Content Source: [powerapps-docs/maker/common-data-service/configure-entity-feedback.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/configure-entity-feedback.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@MSIH - The article has been significantly updated to include procedures for how to enable a table for feedback, how to add the subgrid configured for feedback, and an example of a rollup column that uses feedback records for aggregation. 
Closing issue.
