### ISSUE TITLE
Image is missing

### ISSUE THREAD

**Issue by LeApFr0g** [MicrosoftDocs/powerapps-docs#1721]
[Enter feedback here]
Document reads "The dashboard components are displayed in model-driven apps based on the values specified in the FormXML. The following image shows an example of a dashboard"

However, there is NO image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f0c3fb-446c-4da2-4578-a3f6bbb21bb9
* Version Independent ID: d09fd695-3937-3c51-32f0-9e825e8de159
* Content: [Understand dashboards: Dashboard components and FormXML (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/understand-dashboards-dashboard-components-formxml)
* Content Source: [powerapps-docs/developer/model-driven-apps/understand-dashboards-dashboard-components-formxml.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/understand-dashboards-dashboard-components-formxml.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@LeApFr0g Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
