### ISSUE TITLE
Is the Power Apps CLI open source?

### ISSUE THREAD

**Issue by onetalltree** [MicrosoftDocs/powerapps-docs#1722]
It's a nice start but has several limitations that would be nice to fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46d11001-a078-60f0-19d9-357f9397c7a7
* Version Independent ID: 395e7245-8c1d-d168-ee6e-cc18b79bd789
* Content: [Install Power Apps CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/powerapps-cli)
* Content Source: [powerapps-docs/developer/common-data-service/powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/powerapps-cli.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@onetalltree Power Apps CLI is not an open source tool. You can share your ideas for the features at https://ideas.powerapps.com. Closing this issue.
