### ISSUE TITLE
URL link does not "Specify a URL for the main page of the application to show"

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/powerapps-docs#1724]
Instead, it opens the URL in the main window.  Please clarify, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f08a1b-c1b7-5594-fb59-73d3c3301399
* Version Independent ID: 044312ff-219d-85c5-d4d3-80043886ffad
* Content: [Create a model-driven app site map in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-site-map-app)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-site-map-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/create-site-map-app.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@dialedin2014 - the article has been revised to state the following about the subarea URL property: 

URL: Specify a URL to a web page. The URL text displays from this subarea and, when selected, a new browser window opens that displays the page. This column is disabled if you've selected Entity in the Type drop-down list.

Closing issue.
