### ISSUE TITLE
Docs should note that User().Email returns the user's UPN and not their email address

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/powerapps-docs#1725]
Yes, conventionally the UPN matches a user's (primary) email address but that is not required and thus not always the case.

Please update the docs to warn users that User().Email actually returns the user's UPN (and thus will match Office365Users.MyProfileV2().userPrincipalName but may or may NOT match Office365Users.MyProfileV2().mail

We run an onPrem AD an sync with Azure AD.  We have multiple email domains but run all users in a single AD Domain.  Here is an example test user who has a primary email address using a different domain than its UPN:
![image](https://user-images.githubusercontent.com/49466287/92421148-bb3eac80-f13c-11ea-848e-890490e06bb6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629906e1-4e16-f342-6c5c-541f1a456e68
* Version Independent ID: 65ea7c7c-ae17-fe3a-bbc6-2efb72590380
* Content: [User function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-user)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-user.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-user.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by binaryjam** [comment]
Come on MS,   its not a difficult decision or even up for debate.
The function returns the UPN and for companies that do not use the email address here, which is not common but a valid scenario, the Citizen developers who aint technical   NEED SOME WARNING and suggest in the Docs, to use Office365Profile email   if no one is going to fix what this function returns.

**Comment by m3ngi3** [comment]
"This may not match the current user's information in Office 365 or other services." --> why not more specific?

Something like:
User().Email | Email address of the current user. -- | --
[!NOTE] The information returned is for the current Power Apps user. It will match the "Account" information that is displayed in the Power Apps players and studio, which can be found outside of any authored apps. This may not match the current user's information in Office 365 or other services.
to
User().Email | UPN of Azure Active Directory Profile. -- | --
[!NOTE] The information returned is for the current Power Apps user. It will match the User Record information that coming from the User Table of the Power Platform Environment. This may not match the current user's information in Office 365 or other services (especially when the Primary Email Address in Office 365 is different from the original UPN of the User Profile).

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
