### ISSUE TITLE
How to make it really work?

### ISSUE THREAD

**Issue by dibyanugraha** [MicrosoftDocs/powerapps-docs#1726]
[Enter feedback here]
Are there any other specific requirements to make it work?

I've done these steps https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/geospatial-overview#prerequisites

I then build a simple app just consist of the address input component. I set its properties:
1. Enable autofill: ON
1. Set within radius: ON
1. Radius: 100
1. Language: Indonesia (Indonesia)
1. Country set: ID

I keep the search result limit and both latitude and longitude to the default values, which is 4, 0, 0 respectively.

I have allowed location access to my browsers (Chrome, Edge) and in my android phone, yet none of them return anything when I typed some address nearby.

Then I tried changing the latitude and longitude to some point near my office, it also didn't work - still showing nothing.

I'd appreciate any kind of help of what did I missed/wronged. Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9eb3724-e178-4a84-11d3-06fc40046516
* Version Independent ID: a9bad591-e77d-10bc-0c1a-2e4f49f0bf85
* Content: [Address input component (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/geospatial-component-input-address)
* Content Source: [powerapps-docs/maker/canvas-apps/geospatial-component-input-address.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/geospatial-component-input-address.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by dibyanugraha** [comment]
These are the screenshots:
<details>
  <summary>Location access from web</summary>
![msedge_0WFVzYg1ub](https://user-images.githubusercontent.com/11976855/92548869-483f4e00-f282-11ea-9cdf-bb5a0cf2ce3b.png)
</details>

<details>
  <summary>Address input properties</summary>
![explorer_Yt5HltOSva](https://user-images.githubusercontent.com/11976855/92549012-93596100-f282-11ea-833c-1bf8becc187d.png)
</details>

The button was supposed to retrieve the selected result from user

<details>
  <summary>Button code</summary>
![vivaldi_qBgofXDZof](https://user-images.githubusercontent.com/11976855/92549102-c56ac300-f282-11ea-8916-9c4469adf1d9.png)
</details>

It is very basic, yet somehow it didn't work.

My AppID: c36a0d5f-9944-433d-a5f7-75e2e270459e

**Comment by dibyanugraha** [comment]
Hi, is any progress in here?

I know this is an experimental feature, but is there anything I do to help to speed up the process? I do not see any logs can be pulled from the apps, no debugging available. Or does it only work in the US?

**Comment by iaanw** [comment]
Are you able to get a sessionID?  https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/get-sessionid

I've forwarded your messages to the engineers and we're seeing if we can find a fix.

**Comment by dibyanugraha** [comment]
Thank God, finally a reply! Here is my session id, run in my phone cause it's past midnight in here.

48e50c9b-5d31-4ee9-983f-9f0643a0ccd4

I really hope someone can shed some lights on this particular case.

**Comment by iaanw** [comment]
Sorry for the delay, but we are looking into it now!

**Comment by anuitz** [comment]
Hello! It looks like the address search is working, but returns zero results. Looking at the address input control parameters, it appears that it is looking for addresses within 100 meters of (-6.185, 106.76876). What characters are you typing into the address input component and what are the addresses you expect it to return?

**Comment by dibyanugraha** [comment]
Jl. Panjang (the biggest and longest road nearby - with all combination of it "panjang", "panjang st."), duri kepa. Even if I extend the radius to 100000 meters, it still yields nothing. Searching nearby places also yields zero results.

**Comment by anuitz** [comment]
The address input control requires a numeric character before it will return results. So if I type something like "panjang 2" I will get the results below when using radius 100000 meters and the control properties you shared earlier. The address control will only return point addresses (not points of interest or streets or geographic points). Let me know if adding a number to your search does not return suggestions. 

![image](https://user-images.githubusercontent.com/51683688/92992254-86b15480-f49e-11ea-872a-24aa1d4de013.png)

**Comment by dibyanugraha** [comment]
Alright, it works. Thank you for the explanation. May I ask, why it wasn't being mentioned at all that it needs at least one numeric character in the manual? And why in several results contains double numeric characters just like your screenshot?

![Screenshot_20200912-162905_Power_Apps (1)](https://user-images.githubusercontent.com/11976855/92992453-44772a00-f515-11ea-8a42-8420345c480b.jpg)

**Comment by anuitz** [comment]
We are updating the documentation to include that requirement. For the double characters, I'm not particularly familiar with international addresses, but the full form address seems to be broken down as:
- streetNumber: 3
- streetName: Jalan Utan Panjang 3
- municipality: Jakarta
- etc

Which is combined to be [Jalan Utan Panjang 3] [3], [Jakarta], [etc]. If this is wrong, the address search is backed by azure maps and you can provide feedback using their tool: https://feedback.azuremaps.com/

**Comment by dibyanugraha** [comment]
Alright, thank you so much, I really appreciate the help and the thorough explanation. I will close this issue.
