### ISSUE TITLE
Does not work when ADLS public access is disabled

### ISSUE THREAD

**Issue by pratimvengurlekar** [MicrosoftDocs/powerapps-docs#1727]
Both environment and storage account are in west europe region. However, the reason connection not happening is that in Azure side I am not allowing public internet access i.e., selecting "Selected Networks" and not selecting "Allow All Networks".

If the connection was happening over the private network then connection should have happened but it is refused. When I open it for public access the connection happens and service works.

"Allowing all Networks" is not recommended. Please have a look at the service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771a2696-1d5a-88c0-299e-320d03a536c3
* Version Independent ID: 0b729e37-ce56-6d84-f44b-a22666776cec
* Content: [Export to data lake - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sabinn-msft** [comment]
We have documented this issue - Currently, you can't provide public IPs for Export to data lake service that can be used in Azure Data Lake firewall settings. Public IP network rules have no effect on requests originating from the same Azure region as the storage account. Services deployed in the same region as the storage account use private Azure IP addresses for communication. Thus, you can't restrict access to specific Azure services based on their public outbound IP address range. More information: Configure Azure Storage firewalls and virtual networks

We are working on adding support for VNETs and/or private network

**Comment by subashsivaji** [comment]
@sabinn-msft is there an ETA on when will the support for VNET will be available?

**Comment by sabinn-msft** [comment]
We are trying to make this happen as part next semester, Apr 21 release or sooner.

**Comment by Mattp123** [comment]
Closing issue.
