### ISSUE TITLE
description of manifest property attribute "usage" is incomplete

### ISSUE THREAD

**Issue by onetalltree** [MicrosoftDocs/powerapps-docs#1728]
Current description: _The usage attribute identifies if the property is meant to represent an entity attribute that the component can change (bound) or read-only values (input)_

The usage attribute can also be set to "output". This is not mentioned, but what also isn't mentioned is what the difference between "bound" and "output" is, if there is a difference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b2e635-6c60-0efc-d894-e43216dca90e
* Version Independent ID: 9828125d-c061-465e-d486-b4ea609190e1
* Content: [Property Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/property.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@onetalltree Thanks for contacting us. The `usage` attribute set to `output` works, but there are minor things that needs to be done to make the property publicly available. Closing the issue. If you need further help, please reopen or create a new issue.
