### ISSUE TITLE
How do admins enable relevance search

### ISSUE THREAD

**Issue by Customery** [MicrosoftDocs/powerapps-docs#1732]
I'm a system administrator trying to enable relevance search. I landed on this page through a Bing search, but I think it's aimed at end users and no guidance for enabling relevance search is found on this page. A link for admins would be great. I'll probably spend the next 10 minutes looking for the admin page.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67dbb451-d5ad-1fec-4b3e-1b6971e8c066
* Version Independent ID: 3de49ecc-31f3-58ad-5cb2-b0c17e32514d
* Content: [Relevance Search - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/relevance-search)
* Content Source: [powerapps-docs/user/relevance-search.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/relevance-search.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
Thank you for the feedback. I will add the link to the topic and he's the link: https://docs.microsoft.com/power-platform/admin/configure-relevance-search-organization

Thanks,
Mints
