### ISSUE TITLE
Relationship cardinality explanation needs correction

### ISSUE THREAD

**Issue by phasedephase** [MicrosoftDocs/powerapps-docs#1733]
In the Relationships section, the one-to-many and many-to-one relationship types are explained incorrectly. 

"Many-to-one: In this type of relationship, each record in entity A can match more than one record in entity B....
One-to-many: In this type of relationship, each record in entity B can match more than one record in entity A...."

one-to-many:  1 customer (A) has many different orders (B).  So your explanation should state instead:

"each record in entity A can match more than one record in entity B. and not "each record in entity B can match more than one record in entity A."

many-to-one: many different devices (A) are made in one and the same factory (B).  Similarly:

"many records in entity A can match only one record in entity B" and not "each record in entity A can match more than one record in entity B."

or as explained here: https://en.wikipedia.org/wiki/One-to-many_(data_model)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110a4840-fbbe-f889-2de5-f2d2d00d9556
* Version Independent ID: 252c7c8a-9c8a-30d5-7ff2-c7d17ba9069c
* Content: [Work with any data - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/why-cds-work-with-data)
* Content Source: [powerapps-docs/maker/common-data-service/why-cds-work-with-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/why-cds-work-with-data.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@phasedephase - the article has been updated to better describe one-to-many and many-to-one table relationships. 
Closing issue.
