### ISSUE TITLE
Experimental/preview features not marked as experimental.

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/powerapps-docs#1734]
Table re-arrangement is not possible unless experimental feature is enabled
[Section 8](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-data-table#examples)

This should be marked as experimental/preview to avoid further confusion.

Discussed [here](https://powerusers.microsoft.com/t5/Building-Power-Apps/Unable-to-rearrange-columns-in-data-table/m-p/683584/highlight/false#M218514)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af82396d-69f1-daf7-be8c-15c1a841bd19
* Version Independent ID: d97646e7-abe7-51f3-6d06-0eb86a441d5d
* Content: [Data table control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-data-table#examples)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-data-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-data-table.md)
* Service: **powerapps**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, documentation has been updated.
