### ISSUE TITLE
Need to update the document

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/powerapps-docs#1735]
Hello team,

The Power Bi Tile control is now placed under the Charts tab.

![image](https://user-images.githubusercontent.com/61499598/92835795-e3acfc00-f405-11ea-9330-76ae9b035bb3.png)

Source:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile#example

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, content has been updated. Please allow some time for the changes to reflect.
