### ISSUE TITLE
Customer want some clarification of lookup behavior difference between legacy web and UCI

### ISSUE THREAD

**Issue by mobeenmohsin** [MicrosoftDocs/powerapps-docs#1736]
[Enter feedback here]
Hi, 

In legacy web client, we have Lookup Record but in UCI it is not available, can you please mention that in this page that Lookup Record window of legacy web client is not available in UCI. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c392ce52-689a-f50c-f985-6f8ae7d1a128
* Version Independent ID: c3c7e767-f99c-b5e4-8bb6-1875004726c3
* Content: [Use the lookup field on a record - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/lookup-field)
* Content Source: [powerapps-docs/user/lookup-field.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/lookup-field.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
Per our conversion in Teams. This was added to the topic.

https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/lookup-field.md#record-type-selection-list

Thanks,
Mints
