### ISSUE TITLE
Barcode Scanner Control in a web browser.

### ISSUE THREAD

**Issue by grabear** [MicrosoftDocs/powerapps-docs#174]
I'm trying to figure out how to use the barcode scanner.  I can't get it to work using the phone barcode scanner or the  web-barcode scanner..

My use case is that I am scanning barcodes , and I'm trying to store the values in a collection so that I can subset another table.  The subset of data is then being used in a gallery.  This works perfectly when I just use a text input, but it doesn't work at all with either of the barcode scanners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7944b4d0-c3be-afa0-4af1-21c9c27b56e2
* Version Independent ID: c2ca93fd-9817-8300-fcc4-a6999659e0a2
* Content: [Barcode-scanner control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-new-barcode-scanner)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by grabear** [comment]
Additionally, the collection created with barcode scans will correctly display the collection fields.  It just can't be used to filter the other data source for some reason.

Is this have something to do with the data type used in the filter?

**Comment by mobaky** [comment]
That's a good question so we've just implemented a new OnScan property for the Barcode Scanner which allows you to set a behavior that will be triggered as soon as a barcode is scanned. You can use that to add the barcode to a collection. As far as I know the web barcode scanner doesn't have a similar property so you would have to use a textbox to display the barcode value and a button to add barcode to a collection.

**Comment by grabear** [comment]
@mobaky 
That's what I've been using :
```python3
# I have a table in an excel file called "Saliva"

# In the OnScan property for the barcode scanner:
Collect(BarcodeData, {SN: BarcodeScanner2.Value})

# In the Items property of the gallery:
Filter(Saliva, Sample_Number in BarcodeData.SN)

# In the title's text property:
ThisItem.Sample_Name

# In the subtitle's text property:
ThisItem.Sample_Number
```
In this example my barcode data relates to my "Sample_Number" column in the Saliva table.  However, I've tried this with several other columns as well.  The gallery will display my filtered table perfectly when I use a Text Input, but the Barcode Scanner never works..

**Comment by mobaky** [comment]
I would maybe try to use the Text function to insure that BarcodeScanner2.Value is a string. So your formula would look like this:
 ```
# In the OnScan property for the barcode scanner:
Collect(BarcodeData, {SN: Text(BarcodeScanner2.Value)})
```

**Comment by grabear** [comment]
I will try that shortly

**Comment by grabear** [comment]
This is also not working :slightly_frowning_face:..

I can share the app with you if you want?

**Comment by grabear** [comment]
> I can share the app with you if you want?

Actually, I'm not sure you'd be able to view it without the proper credentials.

**Comment by mobaky** [comment]
I think I understand the reason why it's not work for you, can you contact me on the powerapps forum [@mobaky](https://powerusers.microsoft.com/t5/user/viewprofilepage/user-id/38178)?

**Comment by mobaky** [comment]
Issue resolved: [Forum Post](https://powerusers.microsoft.com/t5/General-Discussion/Barcode-scanner-control-values-in-my-collection-are-not/m-p/213047#M67939)
