### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by BSeidali** [MicrosoftDocs/powerapps-docs#1741]
Hi,
Please be advised that below link in the article is broken and not working:
Build Windows client applications using the XRM tools.(https://docs.microsoft.com/en-us/xrm-tooling/build-windows-client-applications-xrm-tools)

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd657fb-b2cb-a85a-7243-41d7cc30dc87
* Version Independent ID: 4ed6833a-668b-ff05-97da-286fb6d68394
* Content: [Service Protection API Limits (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits#how-to-maximize-throughput)
* Content Source: [powerapps-docs/developer/common-data-service/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/api-limits.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Link should go to https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/build-windows-client-applications-xrm-tools

**Comment by Nkrb** [comment]
@BSeidali Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
