### ISSUE TITLE
Does Virtual entities support create, updates and delete of data in the external system?

### ISSUE THREAD

**Issue by kthirapatpibul** [MicrosoftDocs/powerapps-docs#1742]
Is it true that "Virtual entities support create, updates and delete of data in the external system."? 

The limitation on this page says that it's read-only. https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/customize/create-edit-virtual-entities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f90ab1-ccb0-faab-e37a-d2d6d4f73ac9
* Version Independent ID: 41811cb6-a06e-65ef-2873-5e893d097de9
* Content: [Get started with virtual entities (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/virtual-entities/get-started-ve#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/virtual-entities/get-started-ve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/virtual-entities/get-started-ve.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by Mattp123** [comment]
@kthirapatpibul - Yes for Dynamics 365 Customer Engagement (on-premises) versions virtual entity data is read-only. For Power Platform environments using virtual tables, read, update, and delete operations are supported. 
https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-virtual-entities#virtual-table-benefits

Closing issue.
