### ISSUE TITLE
Sharepoint connection in Flow hosted in Solutions.

### ISSUE THREAD

**Issue by SigurdurJ95** [MicrosoftDocs/powerapps-docs#1744]
I am very interested in the microsoft flow api. We are creating and packaging whole systems in Sharepoint with flows to automate some parts of our solutions.

As is, when we are deploying our solutions to new clients, we have to manually Import every single flow and update the connectors, list connections etc. I have had my eye on using the Power Automate solutions to make packaging and deploying flows relating to our products easier. Until now this has not been possible because flows within Power Automate solutions that use sharepoint connectors have not supported. 

Today I had a look over the options available in with Power Automate solutions and was delighted to find that I could now both create and import flows that use sharepoint connectors. The documentation however still states that this is not supperted.

Is the documentation outdated? Can we start using solutions to package flows that use sharepoint connections?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a7715a-2b1b-29ed-99ac-0003429d5b4d
* Version Independent ID: be31d36c-9be0-cc62-1ea3-b8514fe569d9
* Content: [Solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-gb/powerapps/maker/common-data-service/solutions-overview#known-limitations)
* Content Source: [powerapps-docs/maker/common-data-service/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/solutions-overview.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@SigurdurJ95 - thanks for your feedback. Yes, flows that include SharePoint are no supported in solutions. The limitation has been removed from the article. Closing issue.
