### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by beziyo** [MicrosoftDocs/powerapps-docs#1745]
When I run a large query I get this message:

Msg 40000, Level 16, State 1, Line 1
The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
RequestId: TDS;1d9a2629-06d4-47f0-ac84-ca126cc4d016;12
Time: 2020-09-16T14:48:08.4446581Z

**Comment by Mattp123** [comment]
@beziyo Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: https://docs.microsoft.com/dynamics365/get-started/support/ 
Closing this issue
