### ISSUE TITLE
Mention here that we can not update or delete application User once created. 

### ISSUE THREAD

**Issue by maykul** [MicrosoftDocs/powerapps-docs#1746]
We should mention these as important while creating an application user. 

You will not be able to change primary email address or username once the application user is created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f87a0a-9dd9-5188-7347-d910423902ca
* Version Independent ID: 9f532b04-f9c5-cbdd-a2bd-666b55ee942e
* Content: [Use Single-Tenant server-to-server authentication (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication)
* Content Source: [powerapps-docs/developer/common-data-service/use-single-tenant-server-server-authentication.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-single-tenant-server-server-authentication.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **pehecke**

**Comment by KumarVivek** [comment]
@paulliew @phecke If this is true, we should update the docs article accordingly.

**Comment by phecke** [comment]
@maykul 

Done. Will be published later today.
Thanks for the suggestion.

**Comment by maykul** [comment]
Thank you Peter & Kumar
