### ISSUE TITLE
Ambiguity Around Authentication/ApplicationCookie/ExpireTimeSpan

### ISSUE THREAD

**Issue by tyler-hogsett-microsoft** [MicrosoftDocs/powerapps-docs#1747]
This setting is listed twice on this page:

1. **User account lockout settings** - Default: 24 hours
2. **Cookie authentication site settings** - Default: 14 days

Based on the grouping of the other settings, I'm guessing that for **User account lockout settings**, the setting name should be Authentication/UserManager/ExpireTimeSpan. Just need to confirm that and update the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6313f348-4130-74f5-320d-b5bd270060c6
* Version Independent ID: de470e06-c2d3-354e-ba80-75691a5d8bd4
* Content: [Set authentication identity for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/set-authentication-identity#cookie-authentication-site-settings)
* Content Source: [powerapps-docs/maker/portals/configure/set-authentication-identity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/set-authentication-identity.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It's 24 hours - 1 day. The documentation has been updated and will be visible after some time.
