### ISSUE TITLE
can you please attach pictures to understand how it looks ?

### ISSUE THREAD

**Issue by Kaviarasi** [MicrosoftDocs/powerapps-docs#1748]
[can you please attach pictures to understand how it looks ? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237cc665-0041-6374-bd81-56dcad94926f
* Version Independent ID: cfddf72f-0ee5-df62-3c29-3e8af4e6b26c
* Content: [addNotification (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addnotification)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addNotification.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addNotification.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@Kaviarasi This is how it looks on model-driven app forms when you try the sample code provided in the docs. We have also updated the docs with the image. Closing the issue. If you need further help, please reopen or create a new issue.

 
![image](https://user-images.githubusercontent.com/34038327/93621634-b675c600-f990-11ea-8b8e-7e4c8f606dcf.png)
