### ISSUE TITLE
How do I add a card or control INSIDE my EditForm?

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/powerapps-docs#175]
I have a simple screen with an EditForm which contains two text cards. One needs to be converted to a DropDown Y/N. I don't think I can CHANGE the card type like you can in Access, so the only path I see is to delete it and add a new one. But when I try to add a new Control of type DropDown, it adds it to the base EditScreen, NOT INSIDE the EditForm. 

Any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f886011-a79a-8fa9-bb7c-f0adbb61b8d3
* Version Independent ID: 997f29d5-e836-fc31-647e-eb6a916afae4
* Content: [Understand data cards - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-cards)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-cards.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-cards.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by pamjustice** [comment]
I found that if you click on the main form that surrounds all the cards, then look on the Properties tab on the right hand side and there will be an option under "Data Source" called "Fields".  To the right of that option is a command "Edit Fields".  Click on that, then click on "Add Field".  This will allow you to add other missing fields from your data source as cards to your form.

**Comment by AFTOwen** [comment]
Thanks, @pamjustice! @ToddChitt, please reopen this issue if it didn't answer your question.
