### ISSUE TITLE
Connection Reference Limts

### ISSUE THREAD

**Issue by don-matese** [MicrosoftDocs/powerapps-docs#1751]
The limits section is not entirely clear regarding a references limitations to being used 16 times in flows.  Does the statement mean it can be 

- Used in any number of steps across 16 flows, or
- Used in sixteen steps in one flow, or 
- Used in sixteen steps per flow, for any number of flows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6296f1c9-8505-cca0-3b3c-50fbf988d663
* Version Independent ID: a5bf3054-8a46-39d0-9c3f-3270080d8fbc
* Content: [Connection references in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-connection-reference)
* Content Source: [powerapps-docs/maker/common-data-service/create-connection-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-connection-reference.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@don-matese - Sorry for the delay. As per the article one connection reference can only be used within a maximum of 16 flows.
