### ISSUE TITLE
Please remove Windows from the supported platforms table

### ISSUE THREAD

**Issue by PiebePost** [MicrosoftDocs/powerapps-docs#1752]
Please remove Windows from the "supported platforms" table. The app hasn't seen a decent update in years and is lagging far behind Android and iOS, and when my clients read that Windows is actually supported I have a hard time to explain that they really should buy Galaxy Tab's instead of Surfaces because the barcodescanner is'nt supported or that they should use the webclient as he apps doesn't run multiple powerapps at once. It's very annoying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e8858f-ee37-b1f0-2ad1-a52416f58d0d
* Version Independent ID: 23c5799a-0e3a-bd52-8f8c-ce586c93e632
* Content: [System requirements, limits, and configuration values for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#supported-platforms-for-running-canvas-apps-using-the-powerapps-app)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **gregli**

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.
