### ISSUE TITLE
Missing "License Requirements"

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/powerapps-docs#1754]
The feature if very limited to those who have a Power BI Pro license when viewing. Documentation can be misleading/frustrating for an individual (who does have Power BI Pro) to set up a tile and publish the app, only to have their users get an "no content to display" message, or a "sign up for a pro trial" message.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 551096c3-6bef-bd2b-9254-4fceac6315da
* Version Independent ID: 6aaee99a-f244-17ca-cb48-408436a2ad92
* Content: [Power BI tile control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile#sharing-and-security)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Power Apps Power BI tile control uses Power BI tile with license requirements from Power BI. The topic mentions this at the top:

Don't have Power BI? [Sign up](https://docs.microsoft.com/power-bi/service-self-service-signup-for-power-bi).
