### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by babakdanyal** [MicrosoftDocs/powerapps-docs#1759]
[Enter feedback here]

There is a typo in the documentation i.e. **search team**, but I think you meant **search term**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad97e638-1f17-ffb2-452f-8073a2bffa63
* Version Independent ID: 7ade66f5-aab6-0627-6d3b-914006718930
* Content: [Understand delegation in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-overview.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content has been updated. Please allow some time to reflect the changes.
