### ISSUE TITLE
No docs on GraphQL Support?

### ISSUE THREAD

**Issue by phil-lgr** [MicrosoftDocs/powerapps-docs#1760]
I was suprised to discover that certain features of Powerapps are already built with GraphQL

See https://www.sergevandenoever.nl/powerapp_portals_the_graphql_story/

Do I understand that GraphQL support is coming to powerapps / common data service?

Thanks!

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please go to [Power Apps Community Forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1) for discussions about upcoming features and capabilities.
