### ISSUE TITLE
Before and after options for real-time workflows

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1761]
See https://github.com/MicrosoftDocs/power-automate-docs/issues/129
Now that the content has been moved from the Power Automate docs, it now applies to this doc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31dd4993-51e7-e348-841c-61ef3bb6fff2
* Version Independent ID: 1f94b2ba-5aaa-fab8-ee61-aa7f5c07857c
* Content: [Configure real-time workflow stages and steps in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/configure-workflow-steps#initiating-real-time-workflows-before-or-after-status-changes)
* Content Source: [powerapps-docs/maker/common-data-service/configure-workflow-steps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/configure-workflow-steps.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@JimDaly - Added table with your descriptions for start when options per each record status change. Also, moved that subsection up under the Setting conditions section.  Merged with master via https://github.com/MicrosoftDocs/powerapps-docs-pr/pull/3550. Closing issue.
