### ISSUE TITLE
no "SharePoint Form" type found. the screenshot and description might be out of date. 

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/powerapps-docs#1762]
It seems like the answer for question "As an administrator, how do I get a list of all customized forms in my organization?" is out of date. there is no "SharePoint Form" type at "Resources"->"Power Apps" page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a8c4146-101d-7ba2-7ae0-d7138b743154
* Version Independent ID: 1f752762-0809-a2fb-4a03-b490547ee7f1
* Content: [Customize a SharePoint list form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content has been updated.
