### ISSUE TITLE
Possible typo in Power Apps Update() function documentation

### ISSUE THREAD

**Issue by e-gallis** [MicrosoftDocs/powerapps-docs#1764]
When describing the **Remove()** function, the documentation says that the **All** parameter allows to _**remove** all copies of the record_, while it should say _**update** all copies of the record_.
![image](https://user-images.githubusercontent.com/32480338/93862042-c4de1d80-fcc1-11ea-829f-d64845e45c32.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7f89e38-f935-5ffa-195d-7c3775313a22
* Version Independent ID: 4a6c1325-1ce8-81c5-451b-c66225c7fad1
* Content: [Update and UpdateIf functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-update-updateif)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-update-updateif.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-update-updateif.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@e-gallis Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
