### ISSUE TITLE
Cannot use data source instead of Choices()

### ISSUE THREAD

**Issue by VeeRochet** [MicrosoftDocs/powerapps-docs#1765]
The Choices() function only return the record id (GUID) from the CDS entity, so filtering this list based on the selection of another field doesn't work.
The article says that to filter the choices displayed in the combo box, you should add the data source (Lookup table) instead of choice and apply the filter.
Problem with that if that if you do that, it looks like it works when creating the item, but when viewing or editing an existing item, the selected value is not displayed.
This actually behaves differently with different data source.
My current project uses CDS and when using the source entity, the selected value is saved in the record. However, when editing or viewing an existing item in PowerApps, the value is not displayed in the form.
In SharePoint, the value is simply not saved.
Has anyone looked into this issue and found a solution?

Thanks

**Comment by Nkrb** [comment]
@VeeRochet Are you talking about this document https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-choices

**Comment by VeeRochet** [comment]
@Nkrb Yes I am. the article say: "Because Choices returns a table, you can use Filter, Sort, AddColumns, and all the other table-manipulation functions to filter, sort, and shape the table."
And then continues with: "At this time, you can't delegate Choices. If this limitation poses a problem in your app, add the foreign entity as a data source, and use it directly."
My issue is not exactly the delegation.
I need to filter the choices displayed in the combo box based on the selection in another field. So I do use the data source and used it directly in the combo items. The filter works, even saving the record. However once submitted the "Parent.Default" is not displayed in the combo box.
I created a function in the DefaultSelectedItem property, as a workaround. But according to this document, using the data source directly should work just as well and i should have to do that.
Also from previous experience, if my data source was a SharePoint list, the selected value would not be saved in the first place.
Thanks

Just wanted to find out if somebody had a better solution.

**Comment by VeeRochet** [comment]
Sorry I meant I shouldn't have to do that, meaning the workaround.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and apologies for late response. It's been long time and perhaps you would have had the issue already resolved. If not, please reach out through a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help and investigation of your problem.
