### ISSUE TITLE
Read Auditing Now Available Via Activity Logging

### ISSUE THREAD

**Issue by topness-msft** [MicrosoftDocs/powerapps-docs#1767]
The portion about read auditing should now redirect to this procedure: https://docs.microsoft.com/en-us/power-platform/admin/enable-use-comprehensive-auditing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7eca476-edd9-e73e-fd07-7e000b9a6ef8
* Version Independent ID: e69062b0-f865-7cdf-be53-a1db50af5d05
* Content: [Auditing Overview (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/auditing-overview#not-supported-for-auditing)
* Content Source: [powerapps-docs/developer/common-data-service/auditing-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/auditing-overview.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@topness-msft  Thanks for the suggestion. The auditing topic has been updated.
