### ISSUE TITLE
SharePoint integration for Power App Solutions

### ISSUE THREAD

**Issue by BeigeBadger** [MicrosoftDocs/powerapps-docs#1768]
The documentation states that "Flows that connect to SharePoint are not available in solutions."

Yet I am able to create a flow within my solution that connects to SharePoint (triggered off a new item being added to a list).

It would be great to get further details about what exactly is and isn't supported regarding SharePoint and Power App Solutions (e.g. the Flow will not be exported) as it determines whether we use Solutions or a standalone app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a7715a-2b1b-29ed-99ac-0003429d5b4d
* Version Independent ID: be31d36c-9be0-cc62-1ea3-b8514fe569d9
* Content: [Solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview#known-limitations)
* Content Source: [powerapps-docs/maker/common-data-service/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/solutions-overview.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by LastGunslinger** [comment]
No response yet on this issue?

**Comment by Mattp123** [comment]
@BeigeBadger - It appears Power Automate flows that connect to SharePoint are now supported to add to a solution. The line item has been removed from the article. 

Closing issue.
