### ISSUE TITLE
Not able to install NuGet packages

### ISSUE THREAD

**Issue by D365BI** [MicrosoftDocs/powerapps-docs#1769]
NuGet packages were not installed automatically when opening the solution file. When trying to add packages from https://commondatamodel.pkgs.visualstudio.com/_packaging/CDM/nuget/v3/index.json we receive an error: 
[CDM] Unable to load the service index for source https://commondatamodel.pkgs.visualstudio.com/_packaging/CDM/nuget/v3/index.json.
  Response status code does not indicate success: 401 (Unauthorized).

Should we have access to https://commondatamodel.pkgs.visualstudio.com/ or how to proceed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5790f0a1-fa32-c315-a56f-77cd8489a0ed
* Version Independent ID: 1e1d579f-f858-b084-86d6-0b1a8257a27f
* Content: [Ingest Common Data Service data with Azure Data Factory - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake-data-adf)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake-data-adf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake-data-adf.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by ajrauhala** [comment]
I'm experiencing exactly the same issue.

**Comment by ajrauhala** [comment]
Any update on this issue?

**Comment by KumarVivek** [comment]
@sabinn-msft Can you pls address this issue?

@ajrauhala @D365BI The best way to address or report these issues is by contacting Power Apps support: <https://powerapps.microsoft.com/support/>

**Comment by ajrauhala** [comment]
@KumarVivek If PowerApps support is the correct way to address or report the issues, why does it say on the documentation page to give feedback here on GitHub?

**Comment by sabinn-msft** [comment]
We are closely working with the ADF team. There no longer seems to be a need to convert model.json to manifest.json since there is native support for model.json from ADF. However, there are a few underlying issues that we are working out after which it would be much easier to consume via ADF

**Comment by Mattp123** [comment]
Closing issue.
