### ISSUE TITLE
Blog Link 404s

### ISSUE THREAD

**Issue by topness-msft** [MicrosoftDocs/powerapps-docs#1772]
The blog link at the bottom of the article is 404ing: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-powershell-cmdlets-xrm-tooling-connect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddd37e9-994b-9f10-5e51-e6d243289b8b
* Version Independent ID: 29932cfd-62b7-3c25-09be-970979ebcf5c
* Content: [Use PowerShell cmdlets for XRM tooling to connect to Common Data Service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-powershell-cmdlets-xrm-tooling-connect)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-powershell-cmdlets-xrm-tooling-connect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-powershell-cmdlets-xrm-tooling-connect.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by KumarVivek** [comment]
@topness-msft The blog link has been fixed, and the changes will be live by EOD Pacific Time. Thanks for reporting the issue.
