### ISSUE TITLE
Missing quote on connectionString

### ISSUE THREAD

**Issue by ajvg94** [MicrosoftDocs/powerapps-docs#1773]
In the section "Edit the application configuration file"
The code:
```

<add name="Connect"
      connectionString="Url=https://yourorg.api.crm.dynamics.com;Username=yourname@yourorg.onmicrosoft.com;Password=y0urp455w0rd; />
```
is missing " at the end, it should be:
```
    <add name="Connect"
         connectionString="Url=https://yourorg.api.crm.dynamics.com;Username=yourname@yourorg.onmicrosoft.com;Password=y0urp455w0rd;" />
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da4c6b5-4ca0-0138-ea99-47e40feaf908
* Version Independent ID: 6bd64a3c-bdf4-a8dd-a6d0-a607a444a30f
* Content: [Enhanced quick Start(Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/enhanced-quick-start)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/enhanced-quick-start.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/enhanced-quick-start.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@phecke Can you fix please?

**Comment by phecke** [comment]
@ajvg94 @JimDaly Fixed. Will be published by end of day.

Thanks for catching that.
