### ISSUE TITLE
I have been using TDS Endpoint for several weeks, now I cannot make a connection with either PowerBi or SSMS. Database version: 9.1.0000.22845

### ISSUE THREAD

**Issue by gjross14** [MicrosoftDocs/powerapps-docs#1776]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d27f9-66bc-5cd2-d8b5-9defc8eddfb0
* Version Independent ID: c45841f0-1488-8c30-8a7c-3a522ec63266
* Content: [View entity data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-gb/powerapps/maker/common-data-service/view-entity-data-power-bi)
* Content Source: [powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by gjross14** [comment]
Has there been a recent update, as my users cannot access their PBI reports for download?

**Comment by Bryand13** [comment]
Hello there,

Same problem here...active for several weeks in our org.
![image](https://user-images.githubusercontent.com/50946094/94398777-779cf880-0166-11eb-96b9-44ea1f3dde2e.png)

Greetings

**Comment by Mattp123** [comment]
@gjross14 - An issue has been determined with TDS. Subsequently, the TDS service has been disabled. The engineering team is working to resolve the issue as soon as possible. More information: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi

Closing issue.
