### ISSUE TITLE
Please update the information on the "Connect to SQL Server from Power Apps" page.

### ISSUE THREAD

**Issue by AsamiKondo** [MicrosoftDocs/powerapps-docs#1778]
[Enter feedback here]
We are aware that the on-premises gateway is currently supported in a non-default environment too.
However, the following public information states that it is only supported in the default environment.
Please update this information to be correct.

<blog>
https://flow.microsoft.com/en-us/blog/supporting-on-premises-data-gateways-in-non-default-environments/

<Target Page>
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-azure-sqldatabase
==================================================================
 Note
Gateways and on-premises connections can only be created and used in the user's default environment.
==================================================================

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbcbf308-e9b9-d59d-5b1b-ba224dcc1aa9
* Version Independent ID: 5959353c-ab28-1bc6-8c21-3b186c1bf61d
* Content: [Overview of the SQL Server connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-azure-sqldatabase)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-azure-sqldatabase.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-azure-sqldatabase.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content has been updated. Please allow some time to reflect the changes.
