### ISSUE TITLE
Custom Connectors vs APIM

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/powerapps-docs#1779]
Custom Connectors is listed as not supported. But, is this relevant, considering APIM is being pitched for Oakdale? Should APIs currently being used as custom connector, be re-added once again in APIM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c830299-300a-39dc-b1ab-6a3a0428901c
* Version Independent ID: d0a364b2-2692-32fe-a657-40edf8b13009
* Content: [Known issues and limitations for Project Oakdale - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/known-issues-limitations)
* Content Source: [powerapps-docs/teams/known-issues-limitations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/known-issues-limitations.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The current documentation is accurate. If anything changes, the documentation will be updated accordingly.
