### ISSUE TITLE
It seems showBarcodeScanner is not working on mobile client. Even though, I pass true for this parameter, the barcode scanner does not appear on the lookup for mobile. Could you please add more details on how to make this work?

### ISSUE THREAD

**Issue by vaibhav21791** [MicrosoftDocs/powerapps-docs#1781]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by KumarVivek** [comment]
@vaibhav21791 
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.
 
Closing this issue.
