### ISSUE TITLE
Should the example be updated? CdsDataTypeWrapper vs CrmDataTypeWrapper

### ISSUE THREAD

**Issue by perskute** [MicrosoftDocs/powerapps-docs#1782]
[Enter feedback here]
Maybe the example should have been updated to this?

            CdsServiceClient svc = new CdsServiceClient("connectionstring");
            // Verify that you are connected  
            if (svc != null && svc.IsReady)
            {
                // Create an account record  
                Dictionary<string, CdsDataTypeWrapper> inData = new Dictionary<string, CdsDataTypeWrapper>();
                inData.Add("name", new CdsDataTypeWrapper("Sample Account Name", CdsFieldType.String));
                inData.Add("address1_city", new CdsDataTypeWrapper("Redmond", CdsFieldType.String));
                inData.Add("telephone1", new CdsDataTypeWrapper("555-0160", CdsFieldType.String));
                var accountId = svc.CreateNewRecord("account", inData);
              
                // Verify if the account is created.  
                if (accountId != Guid.Empty)
                {
                    Console.WriteLine("Account created.");
                }
            }
            else
            {
                // Display the last error.  
                Console.WriteLine("An error occurred: {0}", svc.LastCdsError);

                // Display the last exception message if any.   
                Console.WriteLine(svc.LastCdsException.Message);
                Console.WriteLine(svc.LastCdsException.Source);
                Console.WriteLine(svc.LastCdsException.StackTrace);

                return;
            }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af307f45-0c94-5930-c4a3-96be201fd86f
* Version Independent ID: b6e637ae-0b59-afbb-5bbc-6622b1a4572b
* Content: [Use XRM tooling to create data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-xrm-tooling-create-data)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-xrm-tooling-create-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-xrm-tooling-create-data.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@perskute Thanks for the feedback. Since the [Microsoft.Powerplatform.Cds.Client](https://www.nuget.org/packages/Microsoft.PowerPlatform.Cds.Client/0.2.23-Alpha) is still in Alpha, we don't want to update the existing docs until it is generally available. Closing the issue. If you need further help, please reopen the issue or create a new one.
