### ISSUE TITLE
Additional Predefined Pattern - tab

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/powerapps-docs#1783]
\t is also a Predefined Pattern and matches the tab character.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c394b4cd-a8bf-c167-86f7-3a3690a78ba7
* Version Independent ID: 1c106efe-e4b2-f296-9caf-c372aab3b2d7
* Content: [IsMatch, Match, and MatchAll functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-ismatch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-ismatch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-ismatch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@Craig-Humphrey  Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
