### ISSUE TITLE
Can I adjust the total of the teams idea on powerapps?

### ISSUE THREAD

**Issue by koenlaan** [MicrosoftDocs/powerapps-docs#1784]
[Enter feedback here]
Can I adjust the total of the teams idea on powerapps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f4b0e0-b911-c3e5-9086-a81727275fb3
* Version Independent ID: 427cd16b-293b-3776-fe11-8ab9bed63c8a
* Content: [Use Employee Ideas and Manage Campaigns apps from teams store - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/employee-ideas)
* Content Source: [powerapps-docs/teams/employee-ideas.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/employee-ideas.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
@koenlaan thank you for reaching out. Can you please elaborate on the ask?

**Comment by koenlaan** [comment]
I would like to adjust names and functions in the Employee Ideas app 
Now I only can adjust a couple of things and add ideas. 
Is this answer clear to you?

**Comment by tapanm-MSFT** [comment]
Please see [Customize sample apps](https://docs.microsoft.com/powerapps/teams/customize-sample-apps).
