### ISSUE TITLE
How can I use tables from other environments

### ISSUE THREAD

**Issue by MSIH** [MicrosoftDocs/powerapps-docs#1785]
How can I use tables from other environments with Project Oakdale?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d8238b-0234-3ca5-2168-f023afb0e0a3
* Version Independent ID: 30c834e4-90bd-2b6e-0503-2ef410574041
* Content: [FAQs for Project Oakdale - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/data-platform-faqs)
* Content Source: [powerapps-docs/teams/data-platform-faqs.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/data-platform-faqs.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@MSIH - See the below article that describes how to import a solution (that can contain the tables you want). https://docs.microsoft.com/en-us/powerapps/teams/import-solution-in-teams
