### ISSUE TITLE
How to update the portal solutions

### ISSUE THREAD

**Issue by mikkoberg** [MicrosoftDocs/powerapps-docs#1786]
Please add steps how to update the portal solutions.

I've been searching for the right place in Power Platform admin center but can't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04cc0b33-3121-9e3e-a023-b8dd2163a33c
* Version Independent ID: f6b5f40a-deb2-e209-2cb2-3a1ae7f98a67
* Content: [Upgrade a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/upgrade-portal#enable-a-portal-for-new-release)
* Content Source: [powerapps-docs/maker/portals/admin/upgrade-portal.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/upgrade-portal.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Please see [Update the Power Apps portal solution](https://docs.microsoft.com/powerapps/maker/portals/admin/power-platform-admin-center#update-the-power-apps-portal-solution)
