### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/powerapps-docs#1787]
Hi,
At the end of the page there is a link "Use actions" that points to [https://docs.microsoft.com/en-us/flow/actions]( https://docs.microsoft.com/en-us/flow/actions) which is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7d3b75-d3e9-32f5-dbf2-09c81a6d5813
* Version Independent ID: 13395c8a-ff09-2b07-778e-75331afde941
* Content: [Create your own actions (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/custom-actions)
* Content Source: [powerapps-docs/developer/common-data-service/custom-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/custom-actions.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by Nkrb** [comment]
@nickbrandl Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
