### ISSUE TITLE
More Examples?

### ISSUE THREAD

**Issue by anbhar** [MicrosoftDocs/powerapps-docs#1788]
Where are the examples for the other functions?
Thanks,
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e43da3bc-6516-181b-5401-4468078aded2
* Version Independent ID: 63a5f459-e8a3-2aca-9c1f-24de6ea4aa9b
* Content: [Average, Max, Min, StdevP, Sum, and VarP functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-aggregates)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-aggregates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-aggregates.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@anbhar Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
