### ISSUE TITLE
Incorrect return type

### ISSUE THREAD

**Issue by stoutg** [MicrosoftDocs/powerapps-docs#1789]
The documentation for getWeekOfYear shows a return value of type String.  It appears that this method actually returns a number/integer.  
The toString() method or the formatting.formatInteger() method have to be used to convert the integer result of getWeekOfYear to a String.

The documentation also states that the range is 1-53.  The result I am getting, using Microsofts own example code is '0'.  The line of code I am using is:
```
let value: string = "";
value = this._context.formatting.getWeekOfYear(new Date()).toString();
```

This is from a Microsoft tutorial on [using the formatting API in a Power Apps component](https://docs.microsoft.com/en-us/learn/modules/component-framework-advanced-topics/2-formatting-api).

Their [example output](https://docs.microsoft.com/en-us/learn/modules/component-framework-advanced-topics/media/html-table.png) shows getWeekOfYear returning 0 in February.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30815a16-ff2c-554e-a104-21fbec3de16e
* Version Independent ID: 2960eee2-a673-c3ce-ba3b-311338af85d0
* Content: [getWeekOfYear - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/formatting/getweekofyear)
* Content Source: [powerapps-docs/developer/component-framework/reference/formatting/getWeekOfYear.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/formatting/getWeekOfYear.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@stoutg Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

We are still looking in to the issue on the range. Will update it once we have an update from the team.
