### ISSUE TITLE
Doesn't seem to work when device is offline.

### ISSUE THREAD

**Issue by mmcguinness** [MicrosoftDocs/powerapps-docs#1791]
WebApi returning no data when client is offline. Can documentation be updated to clarify if this works/is broken/is not supported?  In PCFs, "this._context.webAPI.offline" is not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647866b2-563e-ffdd-ce84-f20feb839ca8
* Version Independent ID: 2397c27b-056e-de5b-0195-defdeff90718
* Content: [WebAPI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/webapi)
* Content Source: [powerapps-docs/developer/component-framework/reference/webapi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/webapi.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@mmcguinness Thanks for the feedback, the offline property should work when the device is offline, we have raised a bug with the team and will update you once we hear back from them.

**Comment by Nkrb** [comment]
@mmcguinness Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit https://powerapps.microsoft.com/support/. Closing the issue.
