### ISSUE TITLE
Doesn't work as written

### ISSUE THREAD

**Issue by tshinkle** [MicrosoftDocs/powerapps-docs#1795]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcc0b068-6ab1-f38e-e320-bb67a517278f
* Version Independent ID: 906ccc1d-a1dd-0f21-0a8b-9bcbc8499c50
* Content: [Create a relationship between SharePoint lists via a lookup field in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-lookup-fields)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-lookup-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sharepoint-lookup-fields.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tshinkle** [comment]
The example given does not work.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The documented steps help achieve the illustrated setup. Please elaborate if the feedback is for any specific step. If there's any issue, please feel free to reach out to the support team with a [support ticket](https://admin.powerplatform.microsoft.com/support) to investigate the problem.
