### ISSUE TITLE
The Note on TDS Endpoint page says T-SQL Queries aren't supported?

### ISSUE THREAD

**Issue by EvilDevilCuckoo** [MicrosoftDocs/powerapps-docs#1797]
I realize it's a Preview feature, but isn't ostensibly the biggest feature of it? That you can write SQL Queries?  I get that many features such as parameters aren't supported, is that what's meant?  If so, ok, but it might make sense to add "But Standard SQL Queries are".  Unless as a preview its not supported at all in which case, I'm totally off base here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d27f9-66bc-5cd2-d8b5-9defc8eddfb0
* Version Independent ID: c45841f0-1488-8c30-8a7c-3a522ec63266
* Content: [View entity data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi)
* Content Source: [powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@EvilDevilCuckoo - Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. 

Closing this issue.
