### ISSUE TITLE
Limit of IN operator

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#1798]
I couldn't find any documentation for the max. amount of values for the IN operator. After testing, it seems the limit is 2000.
I've also had a look at https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.query.conditionoperator?view=dynamics-general-ce-9, but there is no limit mentioned. Is there an other place where this limit is mentioned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55426bf-e3ed-2d4f-d2e9-1edf60ebe6c6
* Version Independent ID: d26739ec-4b1e-77da-7ba3-fa87e7723300
* Content: [Use FetchXML to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-fetchxml-construct-query)
* Content Source: [powerapps-docs/developer/common-data-service/use-fetchxml-construct-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-fetchxml-construct-query.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by NHelgren** [comment]
Hi @darshSWL, you are correct that the In value is limited to 2000 values. I have added this detail to the warning in the Fetch XML Example in this article. It should appear shortly.

**Comment by phecke** [comment]
@darshSWL The issue was resolved by NHelgren (see above).
