### ISSUE TITLE
The Control slider always in the center even after changing the Value. BE it 100 / 10 / or any custom value, Slider goes back to center

### ISSUE THREAD

**Issue by crmtraining365** [MicrosoftDocs/powerapps-docs#1800]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/72556580/95457254-37235300-098e-11eb-9ca0-a781e80feb81.png)

![image](https://user-images.githubusercontent.com/72556580/95457278-40142480-098e-11eb-8d1a-f0923249f2a7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript#creating-a-new-component-project)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@crmtraining365 Thanks for contacting us, by default if you don't set any values, the slider will be in the middle, however, if you set a value for the slider and save the record, the slider will stay at the value you have saved.  Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
