### ISSUE TITLE
Issue with description - broken or missconfigured link?

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/powerapps-docs#1801]
It looks there is an issue with the description for the setting **Authentication/Registration/LoginButtonAuthenticationType** under the section [enable-aspnet-identity-authentication](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/set-authentication-identity#enable-aspnet-identity-authentication)

This is how it looks from my chrome browser:
 ![image](https://user-images.githubusercontent.com/16178171/95489615-64283380-0997-11eb-9a7e-fff60b01972e.png)

I want to configure this setting to enable SSO with our AAD, but not sure which value should I use in the setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6313f348-4130-74f5-320d-b5bd270060c6
* Version Independent ID: de470e06-c2d3-354e-ba80-75691a5d8bd4
* Content: [Set authentication identity for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/set-authentication-identity)
* Content Source: [powerapps-docs/maker/portals/configure/set-authentication-identity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/set-authentication-identity.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by sandhangitmsft** [comment]
This value of **Authentication/Registration/LoginButtonAuthenticationType** site setting will be the same value that you have used for your **AuthenticationType** site setting e.g. if you are using a SAML Provider then this will be a site setting such as Authentication/SAML2/[provider]/AuthenticationType.
For AAD this is the value of the **entityID** attribute defined in the federationmetadata.xml and looks like https://sts.windows.net/<your AAD tenant ID>/
