### ISSUE TITLE
PowerBI PowerApp publish, failed to create or join session.

### ISSUE THREAD

**Issue by l8rpeace** [MicrosoftDocs/powerapps-docs#1804]
I am following this tutorial: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual

I follow the steps for a report that is published to my personal workspace (that is backed by excel data). I make sure Edge is the default browser so that, in step 3, the new power app will open in edge. I am met with this error message:

_Failed to create or join session (API: JoinSession)xhr error. Status: 401, response: Invalid join token

Session ID: 0b3cf553-d6ea-497f-b6f1-2bcbc7a21bb7_

Is this because I am using Excel as the backend? Can and should the data source be something different to make this tutorial work? Is it because I use my personal workspace in my own tenant? Thank you in advance for any information you can provide me and other best practices you can add to the Power Apps custom visual tutorial for PowerBI.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please read the documentation about Excel and Power BI for more information. 

- [Tutorial: From Excel workbook to stunning report in Power BI Desktop](https://docs.microsoft.com/power-bi/create-reports/desktop-excel-stunning-report)
- [Tutorial: From Excel workbook to a report in the Power BI service to Microsoft Teams](https://docs.microsoft.com/power-bi/create-reports/service-from-excel-to-stunning-report]

Power Apps visual is available for Power BI Service and Power BI Desktop. You may try with different data sources. If the problem persists, please reach out to the support team with a [ticket](https://admin.powerplatform.microsoft.com/support) to investigate the issue.
