### ISSUE TITLE
Problem publishing form after

### ISSUE THREAD

**Issue by skilrane** [MicrosoftDocs/powerapps-docs#1805]
Unable to publish form post implementing this change in XML.

Message: The dependent component EntityRelationship (Id=new_site_SharepointDocuments) does not exist.  Failure trying to associate it with SystemForm (Id=9b96f1d9-da4d-4b22-a684-4b65667f13da) as a dependency. Missing dependency lookup type = PrimaryNameLookup.Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>cc8f9ebd-521f-4f06-999f-1b8fad5afc2d</ActivityId>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 772dad73-84e3-4afb-ed0f-7937aa0771e2
* Version Independent ID: 5136382e-ef93-f0bf-5e9c-595b935909b7
* Content: [Add the Documents tab to the main form for an entity - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-documents-tab-entity-main-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-documents-tab-entity-main-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/add-documents-tab-entity-main-form.md)
* Service: **crm-online**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@skilrane Thanks for contacting us. Unfortunately, we're unable to handle support requests here. To contact Support, see here: https://powerapps.microsoft.com/support/ 

Closing this issue.
