### ISSUE TITLE
onchange event tutorial does not work for power apps model driven

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/powerapps-docs#1807]
Hello,

I've tried this tutorial but the onchange event does not work using the classic interface. My web ressource does not trigger. Using the modern interface it works correctly, an update on the pictures would be good,

Thank you,

Jeff ANGAMA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd626b7-e922-eecd-983c-3823afff4e04
* Version Independent ID: 376d0fc1-294a-660a-ea09-7de12f6dbe18
* Content: [Tutorial: Write your first client script in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@jeffangama Thanks for the feedback. From our testing, I see that the sample code s till works good on web client. We don't see any issues.

**Comment by jeffangama** [comment]
The code might work, but when you register the function on OnChange Field, using the classic interface, it doesn't trigger the function for me. Though using the modern UI it does.

**Comment by Nkrb** [comment]
@jeffangama I tried to register the function on OnChange field (AccountName) in the web client, and I still see it updates the Phone number and website address. The sample codes works as expected both on Unified Interface and Legacy web client.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
