### ISSUE TITLE
How to Save Combobox values into Dynamics 365 Multi Picklist

### ISSUE THREAD

**Issue by ChetanProgrammer** [MicrosoftDocs/powerapps-docs#181]
I have a power app (canvas) where Combobox list items should be stored into Dynamics crm custom multi picklist field. I tried with Concat function but no luck    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8bf3d3-12e3-5b55-8713-221cf5f5a30c
* Version Independent ID: 5a050d01-6ef6-97d6-07de-d5cac82dea06
* Content: [Combo box control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-combo-box#example)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
Are you using the CDS connector or the Dynamics one?  I would post this question on the forums, as it is related to the data-end, not the controls specifically.

**Comment by AFTOwen** [comment]
@ChetanProgrammer Closing this issue as product-specific, not docs-specific. Thanks.
