### ISSUE TITLE
Access to Common Data Service with privileges to perform CRUD operations

### ISSUE THREAD

**Issue by parthrawal** [MicrosoftDocs/powerapps-docs#1815]
there should have been more clear instruction about what do you mean by access. As i do have access to execute odata api to run them in browser but when i am running the code it is not allowing me to run and throws error as mentioned below:
**AADSTS65001: The user or administrator has not consented to use the application with ID** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5228cbcb-419c-8087-68a6-08ce55335f88
* Version Independent ID: 88aca128-e855-65a2-a6bf-8527a38d37b7
* Content: [Web API CDSWebApiService Basic Operations Sample (C#) (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/samples/cdswebapiservice-basic-operations)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/samples/cdswebapiservice-basic-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/samples/cdswebapiservice-basic-operations.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke**

**Comment by JimDaly** [comment]
Are you using the provided application id values or substituting your own?
These should work for every CDS environment:

  ClientId=51f81489-12ee-4a9e-aaae-a2591f45987d;
  RedirectUrl=app://58145B91-0C36-4500-8554-080854F2AC97

Unless your Azure AD administrator has blocked it, it should be available.

**Comment by parthrawal** [comment]
Oh I was supposed to HARD code above IDs..... I was using Client Id of my app which i have created on azure app registration...

**Comment by JimDaly** [comment]
@phecke 
Can you add a small note in this topic to help people understand that they don't need to register an app to run this sample?
We can see here that it is a reasonable assumption that people can make that they need to insert their registered app rather than the one we have provided for them.

**Comment by parthrawal** [comment]
Thanks. I have added a Note. hope that is helpful to others.

**Comment by phecke** [comment]
@parthrawal @JimDaly Article updated with note as requested. Will be published later today
