### ISSUE TITLE
Dynamics CRM v9.1 odata metadata invalid due missing EntitySet

### ISSUE THREAD

**Issue by davidmoten** [MicrosoftDocs/powerapps-docs#1816]
Re metadata at https://PROJECT.crm6.dynamics.com/api/data/v9.1/$metadata?format=xml, in the metadata I see about 600 NavigationPropertyBinding elements that target the EntitySet "owners" but this EntitySet is not defined in the metadata (and there is no import to suggest it is defined elsewhere). 

According to the odata v4.01 [specification](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_BindingTarget) if the target is 'owners' there should be an entity set, singleton, or containment navigation property called 'owners'. 

Can you fix the metadata or at least explain why the service reports invalid metadata against the specification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3c595b-8fd1-9093-ba63-ab54cf4802d6
* Version Independent ID: 21f4822a-c0c9-885f-0c02-9cb5de024dd1
* Content: [Web API types and operations (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/web-api-types-operations)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/web-api-types-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/web-api-types-operations.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **susikka**

**Comment by JimDaly** [comment]
In the CDS metadata there is an 'owner' entity which plays a role similar to the 'principal' entity in the Web API.
'ownerid' property is the only property of the [principal entitytype](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/principal?view=dynamics-ce-odata-9). SystemUser and Team both inherit from this Principal entity and have this ownerid property because of this inheritance.

Agree it is odd that a reference is made to an 'owner' entity type when one doesn't exist. I've asked the dev team if there is an explanation .
AFAIK, it doesn't block the ability to use the API. Our functional tests aren't broken.

Is this blocking you in any way?

**Comment by davidmoten** [comment]
> Is this blocking you in any way?

Not really but it was an annoyance. I'm the author of [*odata-client*](https://github.com/davidmoten/odata-client) which generates Java code based on OData metadata. To get the generation working for Dynamics I had to put in the configurable ability to ignore this exact problem. I think if the service proclaims itself as an OData service it should comply with the spec.

**Comment by arunvinoth** [comment]
This has been explained in https://stackoverflow.com/a/63991650/7920473, looking for official confirmation :)

**Comment by davidmoten** [comment]
@JimDaly @arunvinoth thanks for the explanations about inheritance but I was already aware of how that works in OData metadata (can't generate code without that knowledge!). I'm not really interested in understanding nuances of the Dynamics CRM data model but rather want to fix the metadata to both comply with the OData specification and to reflect what the service reality is.

**Comment by davidmoten** [comment]
Not fixed, shouldn't be closed. Don't you guys actually want to comply with spec?
