### ISSUE TITLE
Api query to retrieve field value translations in CRM

### ISSUE THREAD

**Issue by abhilashmt** [MicrosoftDocs/powerapps-docs#1817]
Help me to create a REST api uri using which i can query the complete fields and field values like every data and its translated value in different languages.

**Comment by tapanm-MSFT** [comment]
Please reference the documentation link that this feedback/query is about for further help.

**Comment by abhilashmt** [comment]
I tried with below queries, still it failed to get all the fields,

- ....api/data/v9.1/EntityDefinitions(LogicalName='account')/Attributes
- ....api/data/v9.1/EntityDefinitions(LogicalName='account')/Attributes/Microsoft.Dynamics.CRM.PicklistAttributeMetadata?$select=LogicalName&$expand=OptionSet,GlobalOptionSet
- ....api/data/v9.1/GlobalOptionSetDefinitions

I am able to get almost half of the fields, field values using these queries

**Comment by phecke** [comment]
@abhilashmt 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.
 
Closing this issue.
