### ISSUE TITLE
Crisis Communications uses Flow, which is now Power Automate, is this now deprecated?

### ISSUE THREAD

**Issue by robertafreese** [MicrosoftDocs/powerapps-docs#1821]
There are a fair number of issues being entered with the tag crisiscommapp at the project, and it looks like it may be abandoned.

https://github.com/microsoft/powerapps-tools/labels/crisiscommapp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6836ad5a-2de5-6223-0514-62c83ac38d17
* Version Independent ID: 8cf9565e-4998-bce4-b319-fedb7e9d835b
* Content: [Crisis communication sample app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sample-crisis-communication-app.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. There may be delay in response due to the volume of requests submitted. Please use the [feedback and issue](https://docs.microsoft.com/powerapps/maker/canvas-apps/sample-crisis-communication-app#issues-and-feedback) links for this app solution related discussions.
