### ISSUE TITLE
Issue with Beta CDM Folder View for Azure Data Lake Storage Gen2

### ISSUE THREAD

**Issue by ralphwest1** [MicrosoftDocs/powerapps-docs#1822]
Unable to access the data through the: Cdm.Contents(AzureStorage.DataLake() connector. It seems to be requiring a "local:" prefix on the entity folder within the datalake.

I get the following error:
![image](https://user-images.githubusercontent.com/23242756/96355187-12209580-109c-11eb-9b6a-35c6c5977945.png)

This error is being cause by: adding "local:" as a prefix to the folder path.
![image](https://user-images.githubusercontent.com/23242756/96355225-6a579780-109c-11eb-831a-278771dd208d.png)

If duplicate the folder in my ADLS and rename the folder from "account"  to "local:account" everything works perfectly.

This is the error if I try to access through the connector gui:
![image](https://user-images.githubusercontent.com/23242756/96355254-ccb09800-109c-11eb-802b-34cb9429d883.png)

Here is the M Code:
![image](https://user-images.githubusercontent.com/23242756/96355286-3a5cc400-109d-11eb-9b67-edce70e5018e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3810fe22-7b24-6bcb-3dd5-21aeb462cdf9
* Version Independent ID: df3d222c-d8b8-38a3-e0c5-4fb1cbef022c
* Content: [Analyze Common Data Service exported to Azure Data Lake Storage Gen2 data with Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake-data-powerbi)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake-data-powerbi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake-data-powerbi.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sabinn-msft** [comment]
We've seen this happen in some cases and have reported the issue to the CDM folder view connector team. In a couple of cases, the issue went away when they upgraded to latest Power BI or reinstalled it. This is however being accomodated in the next fix which should be out soon. If you continue to the face the error, do let us know and we'll happy to bridge you with the connector team.

**Comment by Mattp123** [comment]
Closing issue.
