### ISSUE TITLE
Read auditing is now supported

### ISSUE THREAD

**Issue by PeterSchmidtPerth** [MicrosoftDocs/powerapps-docs#1823]
The document states that Read auditing is not supported. This is now possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7eca476-edd9-e73e-fd07-7e000b9a6ef8
* Version Independent ID: e69062b0-f865-7cdf-be53-a1db50af5d05
* Content: [Auditing Overview (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/auditing-overview)
* Content Source: [powerapps-docs/developer/common-data-service/auditing-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/auditing-overview.md)
* Service: **powerapps**
* GitHub Login: @Bluebear73
* Microsoft Alias: **munzinge**

**Comment by bthompson-365** [comment]
@PeterSchmidtPerth in the context of the Common Data Service Audit functionality read audit isn't available.

Read Audit is part of the Office 365 audit trail that runs outside the internal Common Data Service Audit trail.
