### ISSUE TITLE
Links to sample codes are outdated

### ISSUE THREAD

**Issue by yruss** [MicrosoftDocs/powerapps-docs#1824]
Links to sample code: CrmSvcUtilExtensions and GeneratePickListEnums are outdated. Taken to https://docs.microsoft.com/en-gb/samples/browse/?redirectedfrom=MSDN-samples and can't find the actual codes from the list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0949367-dc3e-ba70-b494-8945530a6fed
* Version Independent ID: 93472f86-1b45-0421-2e1e-7e2857e64534
* Content: [Create extensions for the code generation tool (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/extend-code-generation-tool)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/extend-code-generation-tool.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/extend-code-generation-tool.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@phecke 
Can you take a look at this to see where these samples went?

**Comment by phecke** [comment]
@yruss 

The samples have been moved here:
https://github.com/microsoft/Dynamics365-Apps-Samples/tree/master/samples-from-msdn/BasicFilteringService
https://github.com/microsoft/Dynamics365-Apps-Samples/tree/master/samples-from-msdn/GeneratePicklistEnums

I will update the article links. Thanks
