### ISSUE TITLE
Page references depreciated functions?

### ISSUE THREAD

**Issue by g7cnp** [MicrosoftDocs/powerapps-docs#1826]
This page talks about functions such as Office365Users.SearchUser yet this page https://docs.microsoft.com/en-us/connectors/office365users/ says these are depreciated and replaced by V2 equivalents
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9434b232-2bf5-14f0-9861-6726dc216b96
* Version Independent ID: d073f002-01ac-541b-d365-60affab50cae
* Content: [Overview of the Office 365 Users connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-users?source=docs)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed, please allow some time to reflect the changes.
