### ISSUE TITLE
Retrieved vs Read

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/powerapps-docs#1827]
Typically CRUD is create, read, update, delete.

It there a reason the word '**retrieved**' is used instead of **read**?

For Common Data Service, API requests include all data operations that interact with entity records where records are created, **retrieved**, updated, or deleted (CRUD).

Jerry

**Comment by Nkrb** [comment]
@JerryCRMI Thanks for contacting us. Can you point us to the doc, so that we can redirect the issue to the right people who can look into this.

**Comment by JerryCRMI** [comment]
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview

[cid:image003.jpg@01D6A700.302E2F20]

Jerry Weinstock
Business Technology Strategist
Microsoft Business Applications MVP
CRM Innovation LLC<http://www.crminnovation.com/>
jerry@crmInnovation.com<mailto:jerry@crmInnovation.com>
V: (913) 492.2764
[Description: mvpsig]

**Comment by phecke** [comment]
@JerryCRMI Yes, there is a reason.

I expect it has to do with the message name being Retrieve and RetrieveMultiple rather than Read.
