### ISSUE TITLE
Outdated documentation regarding App ID and App Name

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#1829]
1. This line in the documentation is no longer relevant since it is already supported. "_Support to embed an existing canvas app in a model-driven form using App ID will be provided in a future update_"
Ref: https://linnzawwin.blogspot.com/2019/12/power-apps-new-improvements-in-embedded.html#addusingappid

2. Embed existing canvas apps using App name is not documented anywhere.
Ref: https://linnzawwin.blogspot.com/2019/12/power-apps-new-improvements-in-embedded.html#addusingappname

3. The following line is no longer applicable either.
"_When you view a model-driven form with an embedded canvas app, if you see an error message that reads "Sorry we didn't find that app" make sure that the embedded canvas app is in the same solution as the model-driven form._"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047b94ce-db9f-ad01-5a62-b0539f2433cc
* Version Independent ID: 1a8a9d3c-2d8b-e13c-042b-0a48fc444956
* Content: [Guidelines on working with embedded canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-guidelines)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md)
* Service: **powerapps**
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@LinnZawWin - thank you for your feedback. I've revised the topics per your suggestion to remove the limitations. I also removed the one about no support for existing canvas apps as that doesn't seem to be the case anymore. I've also revised the steps to include that you can add the existing app name and app id for a canvas app. https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-add-classic-designer 

Closing issue.
