### ISSUE TITLE
How to add existing entities in N:N relationship

### ISSUE THREAD

**Issue by almaszaurbekov** [MicrosoftDocs/powerapps-docs#1830]
I replaced the **"add existing" ribbon's** functionality with my JS code (**lookupObjects**). This example shows only how to get the results of the selected entities, but I am interested in how, after selecting all entities, add them to the table if the entity relationship is N:N

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by JimDaly** [comment]
@almaszaurbekov 
Thanks for your feedback. 
I found this issue was open for a very long time. If this is still an issue for you, please update this issue and we can reopen it.

Jim
