### ISSUE TITLE
How and where to provide Common Data Service administrator role?

### ISSUE THREAD

**Issue by subashsivaji** [MicrosoftDocs/powerapps-docs#1831]
_To link the Common Data Service environment to Azure Data Lake Storage Gen2, you must be a Common Data Service administrator._

How and where to provide Common Data Service administrator role? Please add steps or at least link to another doc page that has the steps please.

Regards,
Subash 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771a2696-1d5a-88c0-299e-320d03a536c3
* Version Independent ID: 0b729e37-ce56-6d84-f44b-a22666776cec
* Content: [Export to data lake - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sabinn-msft** [comment]
https://docs.microsoft.com/en-us/power-platform/admin/database-security

**Comment by Mattp123** [comment]
Closing issue.
