### ISSUE TITLE
This "Tutorial" has a problem

### ISSUE THREAD

**Issue by diggetydog** [MicrosoftDocs/powerapps-docs#1832]
I see that this section here:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-users#show-information-about-another-user
Is very confusing. The graphic shows editing the screen while the text says edit a text input box. Then next it asks to put in a users email. This does not work.

I stopped here as it was not useful to continue know that there might be more errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9434b232-2bf5-14f0-9861-6726dc216b96
* Version Independent ID: d073f002-01ac-541b-d365-60affab50cae
* Content: [Overview of the Office 365 Users connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-users)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The graphic has been fixed, please allow some time to reflect the changes.
