### ISSUE TITLE
Another issue with this "Tutorial"

### ISSUE THREAD

**Issue by diggetydog** [MicrosoftDocs/powerapps-docs#1833]
Read this here:

### Search for users

Add a Text input control (Insert menu > Text), and rename it SearchTerm. Enter a name to search. For example, enter your first name.

This is very minimal and I believe needs much more to implement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9434b232-2bf5-14f0-9861-6726dc216b96
* Version Independent ID: d073f002-01ac-541b-d365-60affab50cae
* Content: [Overview of the Office 365 Users connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-users)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The steps work as expected when followed as documented. If there's any issue, please reach out to support team with a [ticket](https://admin.powerplatform.microsoft.com/support) for help with the investigation.
