### ISSUE TITLE
Guest Access Support for Azure DevOps Power Automate connector

### ISSUE THREAD

**Issue by mikefrankland** [MicrosoftDocs/powerapps-docs#1834]
The Azure DevOps Power Automate connector is currently unable to connect with guest accounts.  This reduces flexibility for customers who are undergoing merger and acquisition projects as well as customers who need to integrate with outside directories.   The limitation is noted here:  https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#what-connectors-support-guest-access

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c12582-519a-606c-1f2e-8fe1f6ac5d2a
* Version Independent ID: 537b3097-4aa4-f3e5-b252-ffb832ecb1dc
* Content: [Share a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#what-connectors-support-guest-access)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @alaug
* Microsoft Alias: **alaug**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For feature asks, please submit an idea at the [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) and vote.
