### ISSUE TITLE
Are some of the Solutions limitations still valid?

### ISSUE THREAD

**Issue by JPMHuls** [MicrosoftDocs/powerapps-docs#1835]
Dear,

On the mentioned page on Solutions listing the limititation it states:
      1. Flows that connect to SharePoint are not available in solutions.
      2. Button triggered flows are not available in solutions.

However it seems that this is no longer valid and tests by me and colleagues confirm that this seems to be working after all. Please can you confirm this and if so update the mentioned Limitations section of the page.

Thank you in advance. Kind regards,

Jean-Pierre Huls
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a7715a-2b1b-29ed-99ac-0003429d5b4d
* Version Independent ID: be31d36c-9be0-cc62-1ea3-b8514fe569d9
* Content: [Solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview?source=docs#known-limitations)
* Content Source: [powerapps-docs/maker/common-data-service/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/solutions-overview.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
It appears Power Automate flows that connect to SharePoint are now supported to add to a solution. The line item has been removed from the article. 
Also, the instant (button) flows limitation has been revised as follows. 

You can’t add an instant flow into a solution when the following are true:
- The flow was created outside of a solution.
- The flow trigger is set to manual.

Closing issue.
