### ISSUE TITLE
Links broken on this page

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1836]
I find these links in this topic:

Common Data Service Developer Guide Image attributes
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/image-attributes

Common Data Service Developer Guide Sample: Set and retrieve entity images
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/sample-set-retrieve-entity-images

But these links don't work.
This looks like the correct one for the first one
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/image-attributes

Here is the second one:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/samples/set-retrieve-entity-images

Please fix these links
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d497c807-5338-83e8-bbc9-3a03453cfc9f
* Version Independent ID: 0bac7894-b1c3-28e9-aa6e-e6b24eaa74f3
* Content: [Entity metadata - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/entity-metadata)
* Content Source: [powerapps-docs/developer/common-data-service/entity-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/entity-metadata.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by mayadumesh** [comment]
@Nathan<mailto:nhelgren@microsoft.com> please confirm

**Comment by mayadumesh** [comment]
I’ll take a look!

From: Maya Dumesh <Maya.Dumesh@microsoft.com>
Sent: Wednesday, October 21, 2020 1:53 PM
To: MicrosoftDocs/powerapps-docs <reply@reply.github.com>; MicrosoftDocs/powerapps-docs <powerapps-docs@noreply.github.com>; Nathan Helgren <nhelgren@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerapps-docs] Links broken on this page (#1836)

@Nathan<mailto:nhelgren@microsoft.com> please confirm

**Comment by mayadumesh** [comment]
Submitted A PR with fixed links.

From: Maya Dumesh <Maya.Dumesh@microsoft.com>
Sent: Wednesday, October 21, 2020 1:53 PM
To: MicrosoftDocs/powerapps-docs <reply@reply.github.com>; MicrosoftDocs/powerapps-docs <powerapps-docs@noreply.github.com>; Nathan Helgren <nhelgren@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerapps-docs] Links broken on this page (#1836)

@Nathan<mailto:nhelgren@microsoft.com> please confirm

**Comment by phecke** [comment]
@JimDaly I am not seeing a problem with those links.

If I go to this published [page](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/entity-metadata#entity-images) and click on the two _More information_ links in that section, the links take me to the correct Dataverse topic pages.

Please verify.

**Comment by JimDaly** [comment]
I opened this issue 3 months ago and from the chatter above, I expect Nathan or Maya may have fixed it but not closed this issue.
If all the links look good now, I think that is a safe assumption.
If none of the links go to 'dynamics365/customer-engagement/' please feel free to close
