### ISSUE TITLE
dropdown not showing on edit in grid view

### ISSUE THREAD

**Issue by CarolynChavez** [MicrosoftDocs/powerapps-docs#1837]
Re: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists

I followed everything and it's working. However, when I edit the list in grid view the dropdown is not showing. it only shows when I use the form via +New.

Is there a way to display the dropdown in grid view edit mode? 

![image](https://user-images.githubusercontent.com/73261522/96801694-ed3d7100-1453-11eb-80f2-290b85d64209.png)

![image](https://user-images.githubusercontent.com/73261522/96801731-fb8b8d00-1453-11eb-896d-c1fa085a7fed.png)

Many thanks

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The grid view in the edit mode is inside SharePoint and we can't use a Power Apps app to replace the SharePoint grid view. Though this would be a feature ask for SharePoint, would suggest to please submit an idea in the [Power Apps ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) so it can be upvoted for awareness and consideration.
