### ISSUE TITLE
Power Apps component framework licensing requirements

### ISSUE THREAD

**Issue by v-etzha** [MicrosoftDocs/powerapps-docs#1839]
How to understand the highlighted part? what does it mean "Code components that (or don't ) connect to external services or data directly and not through connectors."
![image](https://user-images.githubusercontent.com/34734408/96817162-57a0e200-1451-11eb-9996-d3fe7b5c5ce3.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92b265c-b3a2-913b-438c-a7ff73377430
* Version Independent ID: f229173f-aa51-23d3-1092-37655bc59625
* Content: [Power Apps component framework overview - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/overview#licensing)
* Content Source: [powerapps-docs/developer/component-framework/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/overview.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@v-etzha If the code components are connected to external data without a connector specified in the connectors list. Then it is considered to be a premium component. Closing the issue.
