### ISSUE TITLE
Error on Get-AdminPowerAppConnectionReferences

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/powerapps-docs#184]
When running this command to get the connections for an app, it errors out as follows:

PS C:\WINDOWS\system32&gt; Get-AdminPowerAppConnectionReferences -EnvironmentName xxx -AppName xxx
Get-PowerAppConnector : The term 'Get-PowerAppConnector' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerApps.Administration.PowerShell\2.0.1\Microsoft.PowerApps.Administration.Powershell.psm1:375 char:21
+                     Get-PowerAppConnector -EnvironmentName $Environme ...
+                     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PowerAppConnector:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

About my copy:
PS C:\WINDOWS\system32&gt; Module -Name Microsoft.PowerApps.Administration.PowerShell

ModuleType Version    Name                                ExportedCommands                                                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                                                    
Script     2.0.1      Microsoft.PowerApps.Administrati... {Add-ConnectorToBusinessDataGroup, Add-CustomConnectorToPolicy, Add-PowerAppsAccount, Clear-AdminPowerAppApisToBypassConsent...}    

Account being used is a Global Admin and has PowerApps Plan 2 trial assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell#flow-commands)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
@ferrety2006 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. If this issue still exists, please contact support: https://powerapps.microsoft.com/support/

**Comment by SAgnihotri200895** [comment]
I think its still not resolved still getting same error

**Comment by ComputerHabit2** [comment]
still an issue... I just came across it...

Maybe I'm missing a module.  The install of the module itself did not work well.  It was delayed and slow.  It didn't finish several times.  

Where do I get the command Get-PowerApConnector?
