### ISSUE TITLE
Invalid FetchXml operator

### ISSUE THREAD

**Issue by StevenRasmussen** [MicrosoftDocs/powerapps-docs#1840]
It appears that there is a typo in one of the FetchXml operators as it gives an error when trying to execute a fetch statement with it.

I believe that the operator currently marked as `eq-owneduseroruserhierarchy` should be `eq-useroruserhierarchy`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9edf02be-b510-588a-8042-8b7ead53b465
* Version Independent ID: ffc9b4de-85b6-c75a-7db6-a7d4849e1fad
* Content: [Query hierarchical data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/query-hierarchical-data)
* Content Source: [powerapps-docs/developer/common-data-service/query-hierarchical-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/query-hierarchical-data.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Looks like you are right.
Looking at[FetchXML schema](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/fetchxml-schema)

I can find these:
```
      <xs:enumeration value="eq-useroruserhierarchy" />
      <xs:enumeration value="eq-useroruserhierarchyandteams" />
```

But I don't find  `eq-owneduseroruserhierarchy`

@phecke 
Can you apply this change?

**Comment by phecke** [comment]
@StevenRasmussen @JimDaly Updated the article with the correct FetchXML operator. Will be published later today.

Thanks Steven
