### ISSUE TITLE
Nuget link not working anymore.

### ISSUE THREAD

**Issue by scosec** [MicrosoftDocs/powerapps-docs#1841]
[Enter feedback here]

Hi guys,

Nuget link on this page is not working anymore. For generating the manifest.json file through visual studio. Repository seems to be taken private.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5790f0a1-fa32-c315-a56f-77cd8489a0ed
* Version Independent ID: 1e1d579f-f858-b084-86d6-0b1a8257a27f
* Content: [Ingest Common Data Service data with Azure Data Factory - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/export-to-data-lake-data-adf)
* Content Source: [powerapps-docs/maker/common-data-service/export-to-data-lake-data-adf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/export-to-data-lake-data-adf.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sabinn-msft** [comment]
There may no longer be a need to convert the file to manifest,json as ADF should understand model.json. We are closely working with the ADF team on some of these items.

**Comment by Mattp123** [comment]
The content referenced appears to be removed from the article. Closing issue.
