### ISSUE TITLE
Looks like the IPs for Europe are not correct

### ISSUE THREAD

**Issue by rsantos00** [MicrosoftDocs/powerapps-docs#1842]
I've created a Power Apps - Model-Driven (Deployed in Europe) which is using the default Email capabilities and need to open the SMTP for specific IPs ranges.

I've got this IP that is not covered by the range that is in the webpage:

SUBNET(13.79.120.0/24))||(client.IP.SRC.IN_SUBNET(52.155.249.0/24)))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e8858f-ee37-b1f0-2ad1-a52416f58d0d
* Version Independent ID: 23c5799a-0e3a-bd52-8f8c-ce586c93e632
* Content: [System requirements, limits, and configuration values for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#ip-addresses)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **gregli**

**Comment by lancedMicrosoft** [comment]
@Austin Laugesen<mailto:alaug@microsoft.com> / @Alan Castellanos Moreno<mailto:alanc@microsoft.com>


Note: My working hours may not coincide with your working hours.  Please do not feel compelled to respond right away if you receive mail from me outside of your normal working hours.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please reach out to the support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) to investigate the issue.
