### ISSUE TITLE
Shortcut info different keyboard

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/powerapps-docs#1843]
Ctrl+Shift+] "bring to front" -> if switch to "US keyboard" work fine, but I use "IT keyboard" everyday and I'm not able to find how invoke the equivalent shortcut or I can do it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955cb34a-35ce-b369-a83b-b68195de2a63
* Version Independent ID: e7503f23-33ab-2a1a-6796-ea6d96b64146
* Content: [Keyboard shortcuts for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/keyboard-shortcuts)
* Content Source: [powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. There are differences between [keyboard layouts](https://docs.microsoft.com/globalization/windows-keyboard-layouts) for different languages. If the key combination as a shortcut is unavailable in a specific keyboard layout, there may not be an alternative to the documented keys. Please reach out to the [Power Apps Ideas Community Forum](https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas) to submit the idea for alternative options, or vote for them.
