### ISSUE TITLE
Probleme datacardvalue powerapps

### ISSUE THREAD

**Issue by viklo** [MicrosoftDocs/powerapps-docs#1845]
Bonjour, 

J'ai crée une application je cherche à récupérer la valeur de ma datacardvalue provenant d'une liste créer sur SharePoint, pour m'envoyer sur une page en fonction de la sélection.

Je vous joins une photo

![image](https://user-images.githubusercontent.com/73283826/96857087-e0724a80-145e-11eb-8a96-cff33545ae0c.png)

Merci a vous  

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3a8c4146-101d-7ba2-7ae0-d7138b743154
* Version Independent ID: 1f752762-0809-a2fb-4a03-b490547ee7f1
* Content: [Personnaliser un formulaire de liste SharePoint - Power Apps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by jowilco** [comment]
@viklo 

https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/connections/connection-sharepoint-online

Merci de nous contacter. Malheureusement, nous ne pouvons pas traiter les demandes de support pour le produit ici. Pour contacter le support, visitez : https://powerapps.microsoft.com/fr-fr/support/. Nous clôturons ce problème.
