### ISSUE TITLE
https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues - 2147847

### ISSUE THREAD

**Issue by quaybj** [MicrosoftDocs/powerapps-docs#1846]
[Enter feedback here]

the sites with the * are not accepted as valid websites when one tries to add them to the list of sites that always accept cookies for Chrome browser:
https://*.create.powerapps.com (the asterisk is part of the address, don't replace it)
https://make.*.powerapps.com (the asterisk is part of the address, don't replace it)
https://apps.*.powerapps.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de7fca-d66b-479c-1570-676ebafa1b78
* Version Independent ID: 70b75562-e755-31cd-c7fd-ef87983698f5
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues)
* Content Source: [powerapps-docs/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Those URLs are to be removed - if already present. Use [*.]powerapps.com as mentioned in the steps to allow exception for just Power Apps (option 2, for Chrome). Alternative is to use option 1 for Chome.
