### ISSUE TITLE
Embedded powerapps in Teams cannot download attachments - 2148051

### ISSUE THREAD

**Issue by russbasiura** [MicrosoftDocs/powerapps-docs#1847]
[Enter feedback here]
Is this working yet?  The attached document does download to the downloads folder but there is no notification given to the user in the browser or letting them know how to open the downloaded document

Problems downloading attachments in embedded Power Apps (May 22, 2020) When using the attachment control to download an attachment, the click won't have any response when using Google Chrome version 83 or the new Microsoft Edge version 83 browser. As a workaround, use another browser. The team is actively working to fix this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa8bb81-3c83-ac01-44a0-f18454ae5d74
* Version Independent ID: fbd864f2-28da-7bfa-68f8-30fd3e0b3d84
* Content: [Common issues and resolutions for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/common-issues-and-resolutions)
* Content Source: [powerapps-docs/maker/canvas-apps/common-issues-and-resolutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/common-issues-and-resolutions.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been updated with the issues already fixed. And the listed ones above are fixed. If there are any issues, please reach out through a [support service request](https://docs.microsoft.com/power-platform/admin/get-help-support).
