### ISSUE TITLE
Spelling mistake on licensing page

### ISSUE THREAD

**Issue by chrolivier** [MicrosoftDocs/powerapps-docs#185]
The mistake is on the following page: [https://docs.microsoft.com/en-gb/powerapps/administrator/pricing-billing-skus](https://docs.microsoft.com/en-gb/powerapps/administrator/pricing-billing-skus)

The fifth bullet point under "**About PowerApps licenses**" contains the phrase "... and _mange_ data."
It should be "... and _manage_ data."

**Comment by jimholtz** [comment]
@chrolivier 
Fixed. Thanks for bringing this to our attention.
