### ISSUE TITLE
Way to get App-ID probably changed. Following the documentation did not help here, because it showed the "old" way

### ISSUE THREAD

**Issue by darkwheel** [MicrosoftDocs/powerapps-docs#1850]
It seems like that the common way to get the App-ID has changed. To click on the three dots next to the app and then "Details" does not show the picture you have in the documentation. Also it does not contain the App ID, but I was able to get the AppID in the end from the URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7b75ec-2194-9cbb-d321-71ba81990643
* Version Independent ID: 5ed344a8-55e7-385a-9298-7f587e213b86
* Content: [Get a session ID or a canvas-app ID - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/get-sessionid#get-an-app-id)
* Content Source: [powerapps-docs/maker/canvas-apps/get-sessionid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/get-sessionid.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been updated and will be visible soon.
