### ISSUE TITLE
Why require all 3rd party cookies instead of allowing just powerapps.com?

### ISSUE THREAD

**Issue by patrick9653** [MicrosoftDocs/powerapps-docs#1852]
[Enter feedback here]

This is not a good user experience.  Having anyone who uses PowerApps to turn off all 3rd party cookies, instead of allowing just powerapps.com.  It worked fine before this change.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de7fca-d66b-479c-1570-676ebafa1b78
* Version Independent ID: 70b75562-e755-31cd-c7fd-ef87983698f5
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues#resolution-4-allow-third-party-cookies)
* Content Source: [powerapps-docs/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please submit an idea for the feature/behavior updates/changes, or vote for an existing one from the [Power Apps Ideas Community Forum](https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas).
