### ISSUE TITLE
Environment Settings with PowerShell

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/powerapps-docs#1853]
Is there a Documentation how to do that with PowerShell?
- Enable the geospatial features for the environment

(I can not see the settings on the bar and would like to use PS as an alternative)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e34915e-ffa9-9a20-55c6-c9e71561f9be
* Version Independent ID: 673a113e-5978-85d2-699a-44e1a5a5fdf7
* Content: [Add Geospatial components to apps made with Microsoft Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/geospatial-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/geospatial-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/geospatial-overview.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Apologies for the delay, unfortunately it's not possible to perform this with PowerShell. Thanks for your question!
