### ISSUE TITLE
GridAttribute Client API support for read-only grids

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#1855]
Is there any change for the supportability of GridAttribute over the last two years?
I tried the code below for the read-only subgrid and it is working in UCI.  Is it now supported for the read-only grids or is it subject to change?
`gridContext.getGrid().getRows().get(0).getData().getEntity().attributes.get("firstname").getValue()`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aea448a-f366-3782-0bbd-86f0748b0169
* Version Independent ID: 0f6737c4-adb1-9c9d-4754-d970c054a347
* Content: [GridAttribute (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/grids/gridattribute)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridattribute.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridattribute.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by dinusc000** [comment]
Hello LinnZawWin,
Please note that the API for getting the attribute value should be supported for both grid types (readonly and edit). I'm not aware about any plans to drop that support. However, the GridAttribute object itself may not be the same between 2 grids types. The value that you can retrieve now from the readonly grid attribute should continue to work in the future.

**Comment by LinnZawWin** [comment]
@dinusc000 thanks for your response. If that's the case, can you please update the documentation for the line below and add more info regarding the read only grid?

> GridAttribute is only supported for editable grids.

**Comment by Nkrb** [comment]
@LinnZawWin 
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
