### ISSUE TITLE
Return Value of context.navigation.openForm(options, parameters)

### ISSUE THREAD

**Issue by rn85apps** [MicrosoftDocs/powerapps-docs#1856]
When using `context.navigation.openForm(options, parameters)` in a PCF control, the return value is expected to be a `Promise<OpenFormSuccessResponse>`

I cannot find documentation on that particular promise.

When testing in browser console for the return value, I see the following is returned:

An array of type `savedEntityReference` with the following key value pairs:

entityType: string
id: Object {guid: string}
name: string

![image](https://user-images.githubusercontent.com/71956109/97217798-2e0fef80-179e-11eb-96a1-a987ad09fc0a.png)

There seems to be a particular issue with the Id key-value because when I attempt to capture the returned Id from the savedEntityReference object, it returns undefined. 

If I wanted to get to the value of the returned Id value (e.g. to perform some logic after the form closes), this is the only thing that I've found that will work.  Is this the recommended pattern?

`				let entityId = response.savedEntityReference[0].id
					.toString()
					.replace("{", "")
					.replace("}", "");
				console.log(entityId);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1584e4c-abec-d444-2fa5-cf84dc3b33fe
* Version Independent ID: 89452bfa-cd47-879c-90f5-64e327942b27
* Content: [openForm - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/navigation/openform)
* Content Source: [powerapps-docs/developer/component-framework/reference/navigation/openform.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/navigation/openform.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@rn85apps Thanks for contacting us. The `savedEntityReference` method returns the parameters defined in the [EntityReference](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/entityreference) doc, I have updated the same and will get the docs published live by EOD. 

Please raise the second issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
