### ISSUE TITLE
Must enable oauth2implicitflow manually in manifest

### ISSUE THREAD

**Issue by stonekw** [MicrosoftDocs/powerapps-docs#1857]
Step 4.c.viii, the instructions require to set Implicit flow using the "ID tokens" option. However, according to this other document: https://docs.microsoft.com/en-us/skype-sdk/websdk/docs/troubleshooting/auth/aadauth-enableimplicitoauth

Implicit flow must be enabled manually in the manifest. Indeed, I was not able to get this working until I updated the manifest. I received AADB2C90057: The provided application is not configured to allow the 'OAuth' Implicit flow. in the portal telemetry logs until set manually in the manifest.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0091f5-8e4c-7ca4-c258-f1d5c03cddec
* Version Independent ID: 28e99ebd-53f6-94f4-1cd9-a8aaca70e7da
* Content: [Configure the Azure Active Directory B2C identity provider for Power Apps portals. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-azure-ad-b2c-provider)
* Content Source: [powerapps-docs/maker/portals/configure/configure-azure-ad-b2c-provider.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/configure-azure-ad-b2c-provider.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated, please try again and check. If the issue persists, please reach out using [Help+Support](https://docs.microsoft.com/power-platform/admin/get-help-support).
