### ISSUE TITLE
Not Unique to User Login?

### ISSUE THREAD

**Issue by jjimenez1389** [MicrosoftDocs/powerapps-docs#186]
Is there a simple way to make this app unique to each user login?
When I submit expenses, these expenses are seen by everyone else this app is shared with. I would like to have it to where each user can submit their own expenses and it not be visible by others that have access to the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @mr-dang-msft
* Microsoft Alias: **brdang**

**Comment by AFTOwen** [comment]
@jjimenez1389 Hi! Your feedback is about how to change the underlying sample app, not the docs for that app. Please submit your input [here](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1).Thanks!

**Comment by jjimenez1389** [comment]
But if I may ask, what good is the sample app if it doesn't allow unique data per user login?
