### ISSUE TITLE
Inaccuracies?

### ISSUE THREAD

**Issue by SolidSoils** [MicrosoftDocs/powerapps-docs#1860]
In the header the Assign message is mentioned. A few years ago MS announced this message would be retired. It's confusing to mention it still.

The last paragraph states: "But the entire workflow cannot run indefinitely.". This should be "...can run indefinitely.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7d3b75-d3e9-32f5-dbf2-09c81a6d5813
* Version Independent ID: 13395c8a-ff09-2b07-778e-75331afde941
* Content: [Create your own messages (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/custom-actions?source=docs)
* Content Source: [powerapps-docs/developer/common-data-service/custom-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/custom-actions.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
No, actually it will eventually fail. That is the point. It won't fail due to a 2 minute time limit, but some other error condition will cause it to fail. We just can't say which error it will be.
