### ISSUE TITLE
Error in the doc about items separators for lists

### ISSUE THREAD

**Issue by biapar** [MicrosoftDocs/powerapps-docs#1865]
You have to change this ["red","green","blue"].  The items must be separated by **;**

![image](https://user-images.githubusercontent.com/661517/97589868-54cc6100-19fe-11eb-93bc-990f14dc76e8.png)

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: eca9b750-b686-4eea-009e-90f7d7a88f8f
* Version Independent ID: 47f0ff15-5438-d8f8-80e7-31739748e2a5
* Content: [Aggiungere una casella di riepilogo, un elenco a discesa o pulsanti di opzione a un'app canvas - Power Apps](https://docs.microsoft.com/it-it/powerapps/maker/canvas-apps/add-list-box-drop-down-list-radio-button)
* Content Source: [powerapps-docs/maker/canvas-apps/add-list-box-drop-down-list-radio-button.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-list-box-drop-down-list-radio-button.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The steps work as per documentation. If you're facing any issue, please reach out using [Help+Support](https://docs.microsoft.com/power-platform/admin/get-help-support).
