### ISSUE TITLE
Unclear instructions for adding owner of app

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/powerapps-docs#1867]
The instructions are unclear for adding an owner for the portal. 

The line below doesn't say if this needs to be done in Enterprise Applications, or App Registrations
_In Azure AD, search for the app registration by using the application ID you copied. You might need to switch from My apps to All apps_

What we have found is that this must be done in "App Registrations", and not "Enterprise Applications". Can you update the page to make it clearer?

![image](https://user-images.githubusercontent.com/42738824/97647089-76345800-1aa5-11eb-85f4-fbac62e38dfe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c33206-a8f7-cce4-d663-894874c0ae98
* Version Independent ID: 72de507b-3eec-6433-1c0a-462b98ef1a91
* Content: [Overview of Power Apps Portals admin center - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/admin-overview)
* Content Source: [powerapps-docs/maker/portals/admin/admin-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/admin-overview.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation mentions to search for app registration, however doesn't reference to enterprise applications.
