### ISSUE TITLE
FetchXML character limit within a batch request

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#1869]
_The length of a URL in a GET request is limited. Including FetchXML as a parameter in the URL can reach this limit. You can execute a $batch operation using a POST request as a way to move the FetchXML out of the URL and into the body of the request where this limit will not apply._

This sounds like there is no limitation. But I still got "Invalid URI: The Uri string is too long." as response. According to this post, the limit is 32kb inside a batch request? https://community.dynamics.com/365/f/dynamics-365-general-forum/389706/invalid-uri-the-uri-string-is-too-long-issue-while-retrieve-data-using-fetchxml-and-batch-request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d385e93-d443-f848-05f6-bdcd6585a9d7
* Version Independent ID: c8fe3dc4-7155-9078-0cf2-383adfcdc6a4
* Content: [Retrieve and execute predefined queries (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries#use-fetchxml-within-a-batch-request)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Sounds like you are unblocked then.
The actionable work to address this in the docs is to clearly specify that the URL limit for GET operations within a $batch is 32768 characters.

This should be added to the docs here:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries#use-fetchxml-within-a-batch-request

Leaving this open until I have time to add this.

**Comment by JimDaly** [comment]
Fixed
