### ISSUE TITLE
Regarding "multioptionset"

### ISSUE THREAD

**Issue by roshangautam** [MicrosoftDocs/powerapps-docs#187]
If you use `formContext.getAttribute(arg).getAttributeType()` on a Multi Select OptionSet it returns `multiselectoptionset` instead of `multioptionset`. Please update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa20929d-c72c-f48c-4af8-85d73179af7b
* Version Independent ID: ae8f1952-671e-f3c9-82da-2fbade4baa06
* Content: [getAttributeType (Client API reference) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/getattributetype)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getAttributeType.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getAttributeType.md)
* Service: **crm-online**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@roshangautam Thanks for the feedback. We have updated the docs and published live. Closing the issue.
