### ISSUE TITLE
How to remove more than one lookup?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#1870]
_Remove a reference to an entity
Use a DELETE request to remove a reference to an entity. The way you do it is different depending on whether you’re referring to a collection-valued navigation property or a single-valued navigation property._

_DELETE [Organization URI]/api/data/v9.0/opportunities(00000000-0000-0000-0000-000000000001)/customerid_account/$ref HTTP/1.1_

Is it possible to remove more than one lookup with one request? For example, if there is an account with 5 lookups and I need to remove the value of those 5 lookups. Do I need 5 requests or one batch request with 5 delete requests?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6444b56-0e82-a336-244d-67e4c3aeed05
* Version Independent ID: cb15df8b-5ef7-25b4-24cb-a48a4ec14e9d
* Content: [Associate and disassociate entities using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api#bkmk_Removeareferencetoanentity)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
This is a known issue we are working on. We want to enable this. But for the time being, the workarounds you mention are the only ways to do this. 5 separate requests or one batch request containing 5 delete requests.

We will update the docs when this work is completed.
