### ISSUE TITLE
This method doesn't seem to work if the Web Resource Control is not visible

### ISSUE THREAD

**Issue by DevMunster** [MicrosoftDocs/powerapps-docs#1871]
Unless I first make sure that the web resource control (or, to be precise, it's containing section) is visible, this method doesn't work for me.
Microsoft Dynamics 365
2020 release wave 2 enabled
Server version: 9.1.0000.24344
Client version: 1.4.1641-2010.1

**Comment by Nkrb** [comment]
Duplicate of https://github.com/MicrosoftDocs/powerapps-docs/issues/1872. Closing the issue.
