### ISSUE TITLE
[BUG] Canvas size wrong

### ISSUE THREAD

**Issue by DEV-PBO-DEV** [MicrosoftDocs/powerapps-docs#1873]
Hi!

when I set the size to 100 * 100 it's displayed in 320 * 320 px.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba2ea78-be6e-2715-7e7d-a18d6a628c86
* Version Independent ID: e9bb4980-2e68-4921-d13c-729e48f03ad3
* Content: [Customize the screen size and orientation of a canvas app embedded on a model-driven form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-customize-screen)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-customize-screen.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-customize-screen.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@DEV-PBO-DEV - Thanks for contacting us. It appears you are experiencing a possible bug with the feature and not with the documentation. We're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ 
Closing this issue.
