### ISSUE TITLE
Recommendation for SharePoint 2019 portal

### ISSUE THREAD

**Issue by nigaur** [MicrosoftDocs/powerapps-docs#1874]
In this article "Migrate Identity Providers to Azure AD B2C", what is Microsoft' recommendation if portal is SharePoint 2019 On-premise server which supports only SAML 1.1 protocol. How can Azure AD B2C return SAML 1.1 token for SP2019 and further how can SP2019 use this token to call an external API which accepts only JWT?

Thanks in advance
-Nitin Gaur
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7179b411-acf4-331d-ac80-89a937904a3f
* Version Independent ID: 4dc3d160-c50b-2642-d411-f16e9e056d47
* Content: [Migrate identity providers to Azure AD B2C. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/migrate-identity-providers)
* Content Source: [powerapps-docs/maker/portals/configure/migrate-identity-providers.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/migrate-identity-providers.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This question is out of scope for Power Apps portals content. Please reach out to the documentation feedback for SharePoint, or Azure AD. Alternatively, you may also contact the support teams for the respective specialty with a support ticket.
