### ISSUE TITLE
Quotes needed in Snippets/Sitemarker/Resx references

### ISSUE THREAD

**Issue by brucebuxton** [MicrosoftDocs/powerapps-docs#1875]
I needed to change:
{{ snippets[links/logout] | default:resx[Sign_Out] | escape }}

to (added quotes):
{{ snippets["links/logout"] | default:resx["Sign_Out"] | escape }}

Otherwise, a liquid error occurred. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 664bbe40-96a7-4542-89c2-714437f679f2
* Version Independent ID: b95d8185-0c05-c92c-3186-5cb7818c8be3
* Content: [Enable header and footer output caching on a portal - Power Apps](https://docs.microsoft.com/en-gb/powerapps/maker/portals/configure/enable-header-footer-output-caching)
* Content Source: [powerapps-docs/maker/portals/configure/enable-header-footer-output-caching.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/enable-header-footer-output-caching.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The content has been updated, please allow some time to reflect the changes.
