### ISSUE TITLE
missing instructions

### ISSUE THREAD

**Issue by dave-jorgensen** [MicrosoftDocs/powerapps-docs#1876]
There's nothing here to say what or where the solution actually is. I downloaded the PowerApps-Samples-Master code, found the app.config, but there is nothing that says which solution in the samples master is the correct one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d0ba405-69d3-bc4b-9824-ec5ebf313e15
* Version Independent ID: 6347a02e-2374-f079-928c-cf983e78ce7b
* Content: [Sample: Detect solution dependencies(Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/samples/detect-solution-dependencies)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/samples/detect-solution-dependencies.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/samples/detect-solution-dependencies.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@dave-jorgensen The topic you mentioned has a link named "here" to the sample under the section _What this sample does_.  There is no Dataverse solution. The sample code creates the solution it needs through the APIs.
