### ISSUE TITLE
Reset Function Not Working Consistently

### ISSUE THREAD

**Issue by brianhamiltonuor** [MicrosoftDocs/powerapps-docs#1877]
The only time I can seem to get the Reset Function to reset a field is if I enter the information, move to another field, come back to the field, and move to another field again.  Even then, it doesn't work consistently. Obviously, that is not very helpful.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 201dd9dc-cea8-6f26-9a37-6d155aa37c5a
* Version Independent ID: 0ef94b8f-8166-2e86-ff48-675bf527aefa
* Content: [Reset function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-reset)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-reset.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-reset.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@brianhamiltonuor Thanks for contacting us. Did you create a button and on the `OnSelect` property of the `TextInput` did you have the Reset function?

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
