### ISSUE TITLE
DataMigration version matters

### ISSUE THREAD

**Issue by losi127** [MicrosoftDocs/powerapps-docs#1879]
[Our customers faced strange behaviours during the data migration when they've used OLD version of the tool. Problem was related with problem of moving (webformstep metadata).

Will be good to add in Note section something like : "it is recommended to use latest version of DataMigration tool. For information on downloading the Configuration Migration tool, see Download tools from NuGet."]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7fa454-57bc-86bf-74cd-c51b622607a4
* Version Independent ID: 3efa0e3c-d9f2-cc50-aa9d-f77f2ca7dc3f
* Content: [Migrate portal configuration - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/migrate-portal-configuration)
* Content Source: [powerapps-docs/maker/portals/admin/migrate-portal-configuration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/migrate-portal-configuration.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated.
