### ISSUE TITLE
Numbering Line Breaks

### ISSUE THREAD

**Issue by CoreySutton** [MicrosoftDocs/powerapps-docs#188]
In the section [Create a custom security role](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/share-model-driven-app#create-a-custom-security-role) points 7-13 are missing line breaks, causing the list to run together as a single paragraph.

This makes the instructions hard to read and follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4549b49b-30e8-c879-39a4-dab18142c213
* Version Independent ID: 8a4a64ea-979f-c4e2-94f0-dd7311b660a4
* Content: [Tutorial for sharing a model-driven app with PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/share-model-driven-app#create-a-custom-security-role)
* Content Source: [powerapps-docs/maker/model-driven-apps/share-model-driven-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/share-model-driven-app.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@CoreySutton Thanks for your feedback. The topic list should be fixed now.
