### ISSUE TITLE
Are CDS Virtual entities Read-only or Create, Update, Delete

### ISSUE THREAD

**Issue by MSIH** [MicrosoftDocs/powerapps-docs#1880]
In the past CDS Virtual entities have been documented as [read-only](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-edit-virtual-entities). 

Do they now support Create, Update, Delete?

Is this this statement on the page accurate? `Virtual entities support create, updates and delete of data in the external system.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f90ab1-ccb0-faab-e37a-d2d6d4f73ac9
* Version Independent ID: 41811cb6-a06e-65ef-2873-5e893d097de9
* Content: [Get started with virtual entities (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/virtual-entities/get-started-ve)
* Content Source: [powerapps-docs/developer/common-data-service/virtual-entities/get-started-ve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/virtual-entities/get-started-ve.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@MSIH Yes, virtual entities support create, retrieve, update, and delete operations in the external system. The documentation is correct.

**Comment by rajyraman** [comment]
@phecke - Is there is any sample code on how this can be done, or is this restricted to only first party apps?

**Comment by rappen** [comment]
If it is true that full CRUD is now available to us - it is probably the best feature ever to have been released without any buzz whatsoever!
But as @rajyraman asks - where can we find any more details and perhaps even samples?
Thanks!

**Comment by Sunil-Garg** [comment]
Hi Jonas—yes, this has been a bit hush hush 😊

Looping @Srinath<mailto:Srinath.Kannan@microsoft.com> who is helping fix a few things we found as gaps during this preview phase and is also working on doc updates. We will circle back with all of you once we have the updates done.

Thanks.

**Comment by Sunil-Garg** [comment]
Hi – As Sunil indicated, I am working through tooling changes to enable full CRUD operation on VE. A quick follow up - is your enquire regarding OData provider or Custom provider?

Thanks,
-Srinath

From: Sunil Garg <sunilg@microsoft.com>
Sent: Thursday, January 21, 2021 11:27 AM
To: MicrosoftDocs/powerapps-docs <reply@reply.github.com>; MicrosoftDocs/powerapps-docs <powerapps-docs@noreply.github.com>; Srinath Kannan <Srinath.Kannan@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerapps-docs] Are CDS Virtual entities Read-only or Create, Update, Delete (#1880)

Hi Jonas—yes, this has been a bit hush hush 😊

Looping @Srinath<mailto:Srinath.Kannan@microsoft.com> who is helping fix a few things we found as gaps during this preview phase and is also working on doc updates. We will circle back with all of you once we have the updates done.

Thanks.

**Comment by rajyraman** [comment]
@sndray - I am interested in both. Is there a private preview for this?

**Comment by rappen** [comment]
Regarding provider - any! 😁
Basically mostly curious to see where we are regarding this area, so we know what kind of tech we can consider for our customers.

**Comment by Sunil-Garg** [comment]
😊

We will plan for a session as well with all of you to demo and engage in future roadmap discussions to get your inputs.

Thanks again.

**Comment by kunaltripathy** [comment]
@sndray , I am interested in both and will love to see a demo. Can you arrange as we are looking to leverage it for an implementation.

**Comment by Sunil-Garg** [comment]
Will do, thanks.
