### ISSUE TITLE
Validity for Power BI Service

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerapps-docs#1881]
Hi, My understanding is that this IP ranges are also valid for Power BI. If so, please add this information as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e8858f-ee37-b1f0-2ad1-a52416f58d0d
* Version Independent ID: 23c5799a-0e3a-bd52-8f8c-ce586c93e632
* Content: [System requirements, limits, and configuration values for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#ip-addresses)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For Power BI, please refer to [Power BI](https://docs.microsoft.com/power-bi/admin/power-bi-whitelist-urls) documentation for help, or to submit a request for feedback/issue.
