### ISSUE TITLE
broken link to Environment lifecycle

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/powerapps-docs#1883]
the below link is broken 
`if the selected Teams team doesn't already have an environment created, a new environment is created at this stage. More information: Environment lifecycle`
broken: https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment.md
correct : https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 887bc09c-a4fe-d836-4532-026e25a875b4
* Version Independent ID: cbd33cd7-6ddd-f912-10fb-eb5e673bc1e0
* Content: [Use sample apps from teams store - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/use-sample-apps-from-teams-store)
* Content Source: [powerapps-docs/teams/use-sample-apps-from-teams-store.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/use-sample-apps-from-teams-store.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The content has been updated and will reflect the changes after some time.
