### ISSUE TITLE
not helpfull

### ISSUE THREAD

**Issue by leonardchamin** [MicrosoftDocs/powerapps-docs#1884]
Document doesn't say if the excel files is connected or not. Mine didnt work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 696b70a6-4354-3497-92f3-ee18a85cc576
* Version Independent ID: c000060b-aa44-ab0f-d9f1-5bf045cd69f5
* Content: [Create a canvas app from scratch based on Excel data - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/get-started-create-from-blank)
* Content Source: [powerapps-docs/maker/canvas-apps/get-started-create-from-blank.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/get-started-create-from-blank.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Can you please elaborate? [Connect to data](https://docs.microsoft.com/powerapps/maker/canvas-apps/get-started-create-from-blank#connect-to-data) section mentions about connecting to a cloud storage data. If there's any issue, please reach out to the support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) for additional help.
