### ISSUE TITLE
Does Xrm.WebApi.offline.retrieveMultipleRecords supports fetchxml?

### ISSUE THREAD

**Issue by Suxsem** [MicrosoftDocs/powerapps-docs#1885]
It's not clear from the docs at https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords if we can use fetchXml parameter with the Xrm.WebApi.offline.retrieveMultipleRecords api.

This is the Javascript code that I'm trying to execute but I'm getting this error: "This operation failed because you're offline. Reconnect and try again."
![fetch](https://user-images.githubusercontent.com/830773/98085832-35aa5500-1e7e-11eb-92b4-be20d520909e.jpg)

No error is thrown if I use the OData syntax instead of fetchXml.
We really need to use offline fetchXml, I hope there is way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c196bb-4bbb-80e2-0bba-42d130621024
* Version Independent ID: 56d1575c-1868-34c6-992d-e3797024e413
* Content: [retrieveMultipleRecords (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@Suxsem Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.

**Comment by Suxsem** [comment]
Dear @Nkrb , thank you for your reply, but why the issue was closed? As I said I think that the documentation is not clear about this feature; we don't need support about implementing the API (this is well explained in the documentation) we just need to know if the platform allows to execute offline fetchxml or not.
We already opened a support ticket through our Dynamics online subscription but even the service representative is having hard time providing a clear answer on that.
Can you please think about editing the documentation page to make it clear?
Thank you

**Comment by Suxsem** [comment]
I think that we figured it out. The fetchXml should NOT be URI encoded. Actually this is noted in the documentation "When you specify a FetchXML query for the options parameter, the query should not be encoded.".
So it seems that FetchXML are available offline indeed, great!
Thank you for your support
