### ISSUE TITLE
Location.Altitude should be in meters, not feet

### ISSUE THREAD

**Issue by hoangpham95** [MicrosoftDocs/powerapps-docs#1887]
[Enter feedback here]
The documentation says that Location.Altitude is returning the elevation above sea level in __feet__. According to our implementation and [web standard](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/altitude), this should be returning in meters. Please amend the documentation so it won't confuse customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68490e51-ae25-ff32-0dd7-9eaf1f5f81d5
* Version Independent ID: 7389a5be-5e77-7238-7eaa-13380ce3908a
* Content: [Acceleration, App, Compass, Connection, and Location signals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/signals)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/signals.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/signals.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@hoangpham95 Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
