### ISSUE TITLE
Environment and tenant app migration URL

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftDocs/powerapps-docs#1888]
Hello,

The URL for [Environment and tenant app migration ](https://docs.microsoft.com/en-us/powerapps/administrator/environment-and-tenant-migration) will get to 404 - Page not found 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ec6689-7baa-94ad-65b2-a7635daf277e
* Version Independent ID: f076de06-b509-f686-f334-18891a1a6cda
* Content: [Power Apps Community Plan -- a free development environment for individual use - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The topic has been updated.
