### ISSUE TITLE
Where do we get full list of language codes?

### ISSUE THREAD

**Issue by AvniBhatt** [MicrosoftDocs/powerapps-docs#1889]
This page talks includes information about the 3rd parameter in Text function but anywhere it does not show the full list of language tags available. How do I determine which language tags are available?

[https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-text](url)

**Comment by Nkrb** [comment]
@AvniBhatt Thanks for contacting us. See the image below on how to get the list of supporting languages. This is already documented in the same doc file you have mentioned under the [Global apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-text#global-apps) section. Closing the issue. If you need further help, please reopen or create a new issue.

![image](https://user-images.githubusercontent.com/34038327/105099257-3e173280-5a60-11eb-84e8-620fed2e257b.png)
