### ISSUE TITLE
Missing required security role - "Model-driven App"

### ISSUE THREAD

**Issue by CoreySutton** [MicrosoftDocs/powerapps-docs#189]
The docs do not explicitly mention users of the app need the  "Model-drive App" role under the "Customization" tab in the Security Role editor. I'm unsure if earlier documents in this section mention the need for this role, but as someone who navigated here from a Google search, I think this requirement should be mentioned on this page in the [Create a custom security role section](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/share-model-driven-app#create-a-custom-security-role).

![image](https://user-images.githubusercontent.com/5017826/52249747-90d1af80-2959-11e9-9d68-29b2a07d6e96.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4549b49b-30e8-c879-39a4-dab18142c213
* Version Independent ID: 8a4a64ea-979f-c4e2-94f0-dd7311b660a4
* Content: [Tutorial for sharing a model-driven app with PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/share-model-driven-app#create-a-custom-security-role)
* Content Source: [powerapps-docs/maker/model-driven-apps/share-model-driven-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/share-model-driven-app.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@CoreySutton Thank you for your feedback. The topic has been updated to include this as step #8.
