### ISSUE TITLE
Batch request limit not always 1000

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#1890]
From the info box: _Batch requests can contain up to 1000 individual requests and cannot contain other batch requests.._

I have to create or update several 1000 records in CRM and used batch requests. Each batch request contains 1000 PATCH requests. Every now and then I get this error message: _The current batch message contains too many parts. Only batch messages with a maximum number of '250' query operations, including changeset operations, are allowed._

Is this a product error or some kind of additional limitation? The limit from the response headers _x-ms-ratelimit-burst-remaining-xrm-requests_ and _x-ms-ratelimit-time-remaining-xrm-requests_ were not reached. ~7500 "burst remaining" and ~960 "time remaining".

I've limited the requests to 250 for the time being.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af14071e-83a5-8dde-6346-d158b4d5d66a
* Version Independent ID: 8fb0f4fb-17ff-7491-d057-a1edf9242bc8
* Content: [Execute batch operations using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Thanks for reporting this.
In [Microsoft.OData.Core/Microsoft.OData.Core.txt](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Microsoft.OData.Core.txt) I see this Error:
[link](https://github.com/OData/odata.net/blob/087d9a8647fe9df75da6052968f1c92b8c8cafc7/src/Microsoft.OData.Core/Microsoft.OData.Core.txt#L148)

`ODataBatchWriter_MaxBatchSizeExceeded=The current batch message contains too many parts. Only batch messages with a maximum number of '{0}' query operations and change sets are allowed.`

So it seems this error is bubbling up from the OData library which we depend on. I'll raise this with the dev team to see if there is any additional guidance we can provide.

I think the `x-ms-ratelimit-burst-remaining-xrm-requests` and `x-ms-ratelimit-time-remaining-xrm-requests` headers are not relevant here.

I think it is wise not to try and push the limits on the number of $batch requests. The service is optimized for concurrent requests and if $batch should be used at all should be considered. The only real benefit that $batch provides is the ability to utilize changesets to group operations in a single transaction. You get better throughput by increasing concurrency with smaller or no batches. See [How to maximize throughput](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits#how-to-maximize-throughput)

**Comment by JimDaly** [comment]
I followed up with the dev team. There is an internal setting that controls the number of items in a batch.
Because you are successfully sending batches of 1000 most of the time, that is what you should be able to send all of the time.
I can't explain why you would occasionally get the error referring to a limit of 250.

That is not expected. If you want to send larger batch sizes and continue to see this error, please contact technical support.
