### ISSUE TITLE
These privileges are not only for model-driven apps

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1893]
This topic applies to privileges defined for the Common Data Service, Not only for model-driven apps.
This topic shouldn't be here

/powerapps/maker/model-driven-apps

It should be here

/powerapps/maker/common-data-service

Also this topic in the on-premises content should be removed and redirected to this topic
https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/customize/privileges-required-customization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c92b4e1-8c8a-6092-11e2-8162c867dc26
* Version Independent ID: 04694159-031b-9124-008a-ef9f05219118
* Content: [Privileges required for model-driven app customizing - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/privileges-required-customization)
* Content Source: [powerapps-docs/maker/model-driven-apps/privileges-required-customization.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/privileges-required-customization.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@JimDaly  Moved in TOC and revised title and article body to reference Dataverse instead of model-driven app where appropriate. 
Closing issue.

**Comment by JimDaly** [comment]
I still think the topic should be moved from

/powerapps/maker/model-driven-apps

to

/powerapps/maker/common-data-service

Privileges belong to Dataverse, model driven apps are built on top of Dataverse.
Model-driven apps are a kind of client, but the privileges apply even when model-driven apps are not used.

**Comment by Mattp123** [comment]
The article content has been revised to explicitly state Dataverse instead of model-driven apps, but will remain in the existing model-driven-apps folder. The customer engagement article will remain as-is since it applies to on-premises versions. 
Closing issue.
