### ISSUE TITLE
How do admins set the default Facets and Filters?

### ISSUE THREAD

**Issue by johnsonwalker** [MicrosoftDocs/powerapps-docs#1894]
The article states "In the Configure Facets and Filters dialog box, specify the facets you'd like to see for an entity. Your system administrator or customizer can set a default experience for all entities, but you can set your own here."

How exactly do admins do this? Is this statement just referring to adding/removing columns from the Quick Find view? It would be useful to hyperlink to the appropriate kb article for admins to 'set the default experience for all entities'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67dbb451-d5ad-1fec-4b3e-1b6971e8c066
* Version Independent ID: 3de49ecc-31f3-58ad-5cb2-b0c17e32514d
* Content: [Relevance Search - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/relevance-search)
* Content Source: [powerapps-docs/user/relevance-search.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/relevance-search.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@johnsonwalker thank you for the feedback. I'm looking into this and will get back to you shortly. 

Thanks,
Mints

**Comment by mduelae** [comment]
@johnsonwalker 

It is not possible for a system customizer to set the default experience. I have removed these two statements from the help topic.
Also, the administrators can make fields available for users to add them into their own list of facets, by adding those fields to the table’s quick find view.

Hope this helps.
Thnaks,
Mints
