### ISSUE TITLE
Encoding special characters

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#1895]
_If the data within a field that is used in an alternate key will contain one of the following characters <,>,*,%,&,:,/,\\ then update or upsert (PATCH) actions will not work._

Is # also such a character?
`"new_test@odata.bind": "/new_tests(new_key='A#000143')"` : Bad Request - Error in query syntax.
`"new_test@odata.bind": "/new_tests(new_key='A%23000143')" `: A record with the specified key values does not exist in new_test entity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf4222a-ca06-70f5-cc49-dfebfc0d2540
* Version Independent ID: ca4f14bd-d0fc-f7e9-0334-8ad13bf74c04
* Content: [Define alternate keys to reference records with Common Data Service - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/define-alternate-keys-reference-records#unicode-characters-in-key-value)
* Content Source: [powerapps-docs/maker/common-data-service/define-alternate-keys-reference-records.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/define-alternate-keys-reference-records.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by darshSWL** [comment]
@Mattp123 @bishalgoswami Any updates on this?

**Comment by darshSWL** [comment]
@Mattp123  @bishalgoswami Could you please have a look at this?

**Comment by NHelgren** [comment]
Yes # is also considered an unsupported special character. I will update the documentation.
