### ISSUE TITLE
The date when the web client of the Japanese version of the article can be accessed is incorrect.

### ISSUE THREAD

**Issue by YoshikaSuzuki** [MicrosoftDocs/powerapps-docs#1896]
[Enter feedback here]
The English version of the original article states that access to the web client is until December 4th, but the Japanese version is December 1st. Please correct it to the correct information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6baca2c-2716-dab9-da1f-9290d5c94d5f
* Version Independent ID: 081682e5-b125-22fc-04c9-1e784ea306f5
* Content: [FAQs: Transition to Unified Interface - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/faqs-transition-unified-interface)
* Content Source: [powerapps-docs/maker/model-driven-apps/faqs-transition-unified-interface.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/faqs-transition-unified-interface.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **haybass**

**Comment by jowilco** [comment]
@Mattp123 I believe that this change was already made to the Japanese files on November 18th. The current Japanese instructions list December 4th as the (correct) date.

**Comment by Mattp123** [comment]
@YoshikaSuzuki - thank you for your feedback. The date has been revised to reflect the correct date. 
Closing issue.
