### ISSUE TITLE
Entity tables vs System tables needs clarity

### ISSUE THREAD

**Issue by donalmc** [MicrosoftDocs/powerapps-docs#1897]
This page needs a better explanation of the differences between Entity and System tables. 
For example:
Entity tables include option set labels, system tables do not
With Entity tables, if the primary name field has the same name as the Entity, it will not display in the entity table, but it will in the system table
System tables include the ability to expand related tables and get values from them, entity tables do not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511b86e6-e806-974b-3989-cbbb6ed0caad
* Version Independent ID: 7b806155-1ca4-36e6-178a-c3506849d765
* Content: [Create a PowerBI report using the Common Data Service connector - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-powerbi-connector)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-powerbi-connector.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-powerbi-connector.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@donalmc - Sorry for the delay. 
In the Data > Tables area of Power Apps, tables are separated into three different Types: Standard, Managed, or Custom. There are Tags that separate the types further for the Standard tables, a few examples are Core, System, and Productivity. When you refer to “entity table” what table type/tag are you referring to? Also, can you expand further on what do you mean by “Entity tables include option set labels?” (E.g. where is this in the entity definition?)

**Comment by donalmc** [comment]
Hi Matt, I think I was talking about how the tables appear when you used the old CDS Connector in PBI.
You used to get System and Entity tables for each table, and there was no real explanation as to when to pick which.
With the Dataverse PBI connector, the confusion no longer exists.
