### ISSUE TITLE
Are rollups and calculated fields counted against entitlement limits ?

### ISSUE THREAD

**Issue by malaker** [MicrosoftDocs/powerapps-docs#1898]
Hi

 Are the Rollup and Calculated fields considered to be initiated by the calling user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b61960df-dcdc-d4e5-749b-0f55e22a385d
* Version Independent ID: baddf389-6252-fe30-1a60-48c18f256ed8
* Content: [API limits overview (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview#entitlement-limits)
* Content Source: [powerapps-docs/maker/common-data-service/api-limits-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/api-limits-overview.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
No they are not.
