### ISSUE TITLE
Explanation of Global Options Sets vs. Local Option Sets using CDS

### ISSUE THREAD

**Issue by kraftwerk15** [MicrosoftDocs/powerapps-docs#190]
As mentioned in this article: https://powerapps.microsoft.com/en-us/blog/new-cds-capabilities-for-canvas-apps-enter-preview/

There are new capabilities with the CDS 2.0 for Canvas Apps when using Options Sets inside of the app instead of declaring values in a different way. There are differences when selecting a local vs. a global option set. The article (including the documentations AFAIK), does not address this distinction.

The article notes: 

> ‘Category (Accounts)’ is the name of the enum for the Category field of the Accounts entity since this is a local option set.

Documenting that a Global Option Set can be addressed without the parenthesis denoting the entity is what is necessary.

For example, if there is a local option set, called Packages to the Entity called Sample, the nomenclature would appear as 'Packages (Sample)' such as the example. If there is a global option set called Envelopes, then that can be accessed like 'Envelopes'.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The blog in reference contains below information to separate local option set:

*‘Category (Products)’ is the name of the enumeration that contains all the possible options for the Category Option Set.  This is a local Option Set defined for this field of this entity only.  **To disambiguate it from other uses of the word Category we add the name of the entity in parenthesis after the field name**.*
