### ISSUE TITLE
Be nice if this worked for subgrids

### ISSUE THREAD

**Issue by bkwaz4** [MicrosoftDocs/powerapps-docs#1900]
[Enter feedback here]

Using this to create a custom view on a uci form for use in a SUBGRID.  I have to add a lookup field to the same form because the custom view cannot be attached to a subgrid.  The view is then available in the subgrid lookup, but cannot be set as the default, because the IsDefault parameter applies to the control that the custom view was created on.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900de2ab-7892-7c8c-014e-9acacfba265d
* Version Independent ID: ab0e41ac-7b93-8253-2a6c-5a0b3fac9bb0
* Content: [addCustomView (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addcustomview)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addCustomView.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addCustomView.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@bkwaz4 Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
