### ISSUE TITLE
Duplicate detection always executed?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#1902]
_The value assigned to MSCRM.SuppressDuplicateDetection header determines whether the Create or Update operation can be completed:_

-  _`true` – Create or update the record, if a duplicate is found._
- _`false` – Do not create or update the record, if a duplicate is found._

It sounds like the duplicate detection is always executed, even if the header is explicitly set to true. Is this correct?

There is also a header mentioned I could find anywhere else in the documentation: `CalculateMatchCodeSynchronously`
It seems this header is not used anymore at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aafb392-328f-398d-4221-f81230f639a1
* Version Independent ID: cd92deef-0bff-62d4-4e7c-89a65eafad86
* Content: [Detect duplicate data using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/manage-duplicate-detection-create-update)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/manage-duplicate-detection-create-update.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/manage-duplicate-detection-create-update.md)
* Service: **powerapps**
* GitHub Login: @susikka
* Microsoft Alias: **susikka**

**Comment by darshSWL** [comment]
@susikka  @phecke  Could you please have a look at this? Thank you.

**Comment by phecke** [comment]
@darshSWL 

_It sounds like the duplicate detection is always executed, even if the header is explicitly set to true. Is this correct?_

Duplicate detection can be enabled for the entire organization. When enabled, then yes the rules will be executed. However, I suspect that setting the header to false will temporarily disable duplicate detection for that particular operation. More info: [Turn duplicate detection rules on or off for the whole organization](https://docs.microsoft.com/power-platform/admin/turn-duplicate-detection-rules-off-whole-organization)

_CalculateMatchCodeSynchronously It seems this header is not used anymore at all?_

Correct. It no longer serves a purpose as the match codes are now calculated synchronously by default.
