### ISSUE TITLE
Specify that there is an option in the modern UI (instead of classic) as well

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/powerapps-docs#1903]
Hi,

It would be good to specify that to modify an existing component, we can also avoid going to the classic page, by using the modern page of it where we can also edit the component id and name 

Refer to my screenshot here : 

![Image 897](https://user-images.githubusercontent.com/6776269/98683698-a44b4f00-2365-11eb-8d72-4a696cd243df.png)

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d72044c0-7486-402e-4ad0-cd488f6356e0
* Version Independent ID: 3b762213-c234-14b3-7f11-cde507cced78
* Content: [Add an embedded canvas app on a model-driven form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-add-classic-designer)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by Mattp123** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.  

Closing this issue.

**Comment by jeffangama** [comment]
It is not product related but it is a request to update the documentation
