### ISSUE TITLE
Broken Link : go to Context interface.

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/powerapps-docs#1904]
there is a broken l ink on the page :
Text : ... about the Teams client SDK, go to Context interface.
incorrect link : https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-teams-app#use-context-from-teams
assumed correct link : https://docs.microsoft.com/en-us/powerapps/teams/embed-teams-app#use-context-from-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea092895-28ba-b64d-33ec-9330ba976696
* Version Independent ID: 7eb1d946-aa8c-8e54-3e25-ecb6a4528fbf
* Content: [Use Teams integration object - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/use-teams-integration-object)
* Content Source: [powerapps-docs/teams/use-teams-integration-object.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/use-teams-integration-object.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Link has been corrected.
