### ISSUE TITLE
Set API doesn't work for PowerApps portals

### ISSUE THREAD

**Issue by si-chan** [MicrosoftDocs/powerapps-docs#1905]
The instructions in step 6 (k) say to "Set an Application ID URI".
However, the default hostname for PowerApps Portals is <tenantname>.powerappsportals.com.
When trying to set this as the Application ID URL, you get an error:
"Failed to update Application ID URI application property. Error detail: The Application ID URI must be from a verified domain within your organization's directory."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755c203-c12c-e673-4654-ddd55d34d46b
* Version Independent ID: 60fa420e-c20c-dd4d-2c23-96f12ec9f10f
* Content: [Configure SAML 2.0 for portals with Azure Active Directory. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad)
* Content Source: [powerapps-docs/maker/portals/configure/configure-saml2-settings-azure-ad.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/configure-saml2-settings-azure-ad.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please work with the support teams by creating a [support ticket](https://admin.powerplatform.microsoft.com/support) to investigate this issue.

**Comment by si-chan** [comment]
Hi

We've worked through the steps again and step 6(l) says "enter the portal URL as the App ID URI".
This will not work, since the portal URL is normally "xxx.powerappsportals.com/yyy" and the App ID URI must be a registered domain in the Azure AD tenant.
In a default Azure AD tenant, the only registered domain is xxx.onmicrosoft.com, so this should be used instead.

Si
