### ISSUE TITLE
JAWS SCREEN READER

### ISSUE THREAD

**Issue by douglasweinberg** [MicrosoftDocs/powerapps-docs#1906]
This documentation does not discuss how to fix screen reader issues using JAWS. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a292fa89-2a43-153c-e2b2-241c11046743
* Version Independent ID: 3dcdadb6-8864-af0b-5d93-9263283dbfdb
* Content: [Use a screen reader in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/screen-reader)
* Content Source: [powerapps-docs/user/screen-reader.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/screen-reader.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@douglasweinberg what issue are you having?

**Comment by mduelae** [comment]
@douglasweinberg Since I haven't heard back I'm closing the issue. If there is an issue with the help topic please open a new request and provide details on what is missing or incorrect in the documentation.

Thanks,
Mints
