### ISSUE TITLE
Missing link to download PluginRegistration.exe

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/powerapps-docs#1907]
Missing link to download PluginRegistration.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccfeadcb-8074-d9de-125a-7353b1597774
* Version Independent ID: 0d857c7c-b943-7d38-b65c-1cb7b71d2cb2
* Content: [Tutorial: Write and register a plug-in (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
IN the PreRequisites:

> Information about downloading the Plug-in registration tool is at : [Download tools from NuGet](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/download-tools-nuget). That topic includes instructions to use a PowerShell script to download the latest tools from NuGet.
