### ISSUE TITLE
testing for Administrator level access to a Common Data Service environment

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/powerapps-docs#1908]
How can I test/verify that I do have "Administrator level access to a Common Data Service environment" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccfeadcb-8074-d9de-125a-7353b1597774
* Version Independent ID: 0d857c7c-b943-7d38-b65c-1cb7b71d2cb2
* Content: [Tutorial: Write and register a plug-in (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@mores  In the Power Apps portal, you can [View your user information](https://docs.microsoft.com/power-apps/user/view-your-user-profile) to find your security role.

You can also find your role by writing code. If you want information about how to do that, file a new issue.
