### ISSUE TITLE
PluginRegistration.exe - needs "Run as administrator"

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/powerapps-docs#1909]
"Click the PluginRegistration.exe to open it." - may not work the first time.
I was getting "You don't have permission to access any of the organizations in the Microsoft Common Data Service region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CDS region and try again. Otherwise check with your CDS administrator."

Once I right clicked on PluginRegistration.exe and "Run as administrator" - then it loaded fine.
Now it seems I can execute with or without "Run as administrator".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccfeadcb-8074-d9de-125a-7353b1597774
* Version Independent ID: 0d857c7c-b943-7d38-b65c-1cb7b71d2cb2
* Content: [Tutorial: Write and register a plug-in (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Did you follow the instructions to use the PowerShell script to download the tools?
Or did you just download the .pkg file and rename it to .zip and extract?

**Comment by mores** [comment]
I used PowerShell script to download the tools?

**Comment by JimDaly** [comment]
The reason I ask is that some people download the package and change the file extension. This isn't recommended and can cause strange behavior unless you 'unblock' the downloaded file. Using the PS script seems to bypass this.

I've never had to run PRT as an administrator, but my user account is typically also a local machine administrator.
I suppose it is possible if the user account you are using is not also a local machine administrator.
Thanks for calling this out. It is worth looking into about whether people should expect this or not.

**Comment by phecke** [comment]
@mores From your description, there are two issues. One deals with access to Dataverse organizations in a specific region, and the other deals with running the tool as admin. The issue with running the tool as admin probably is due to permissions on the folder where you installed the tool. The other issue has to do with the login account that you used to access organizations in the region.

Glad you got past these issues. Closing this GitHub issue.
