### ISSUE TITLE
Specify in the doc where shall the powerapps name and ID be taken (on powerapps page)

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/powerapps-docs#1911]
The documentation would make me  think i cant set the power apps name myself, though we've to use the internal name of the power apps.
Could you specify in the doc where shall the powerapps name and ID be taken (on powerapps page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d72044c0-7486-402e-4ad0-cd488f6356e0
* Version Independent ID: 3b762213-c234-14b3-7f11-cde507cced78
* Content: [Add an embedded canvas app on a model-driven form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-add-classic-designer)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by Mattp123** [comment]
@jeffangama - sorry for the delay. From the article: 
The App Name Static value - Specifies the name of the canvas app to embed. The model-driven form looks for the canvas app with the specified name in the current environment. If a canvas app with that name can't be found in the environment, the canvas app control will use the App ID to load the canvas app. Enter the App Name for an existing canvas app.
The App ID Static value: Enter the app ID for an existing canvas app. The canvas App ID can be found on Power Apps, go to Apps, select the canvas app, and then select Details on the command bar.

Closing issue.
