### ISSUE TITLE
Sample code outdated/not working

### ISSUE THREAD

**Issue by Naitik-Xpertladr** [MicrosoftDocs/powerapps-docs#1912]
The code sample in the section "https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth#connect-using-the-application-secret" is incorrect and needs to be updated. On the line where is says <AuthenticationResult result = authContext.AcquireToken(serviceUrl, credential);> it gives and error saying "AuthenticationContext does not contain a definition for AcquireToken". Please review the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62419bb8-985c-cb11-ac8d-2d018868c2a6
* Version Independent ID: db669ed7-d87b-c359-f5fb-3f2f1052281d
* Content: [Use OAuth with Common Data Service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth)
* Content Source: [powerapps-docs/developer/common-data-service/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/authenticate-oauth.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by RedsGT** [comment]
Were you running the sample with the latest version of ADAL v2?

**Comment by phecke** [comment]
@Naitik-Xpertladr  Since you filed this issue, the topic has been updated to use MSAL instead of ADAL for authentication. Take a look.
