### ISSUE TITLE
increasing the timeout?

### ISSUE THREAD

**Issue by amichalove** [MicrosoftDocs/powerapps-docs#1913]
The timeout is set to 2 minutes -- Is this something that can be increased? Even if on a request-only basis, this is desirable for back-end datalake management.

**Comment by RedsGT** [comment]
Hi @amichalove what timeout are referring too?  Can you reference the page?

**Comment by amichalove** [comment]
When performing a SQL query, there is a 120 second timeout. This appears to be a server-side timeout from the D365 endpoint.

**Comment by phecke** [comment]
@amichalove Are you using the TDS (SQL) endpoint of Common Data Service?

**Comment by tapanm-MSFT** [comment]
Closing due to no response.
