### ISSUE TITLE
Not able to insert/update user lookup datatype in Entity using SingleTenantS2S API

### ISSUE THREAD

**Issue by rpskumar** [MicrosoftDocs/powerapps-docs#1915]
[Enter feedback here]

I have created Custom Entity "Department" and added a Lookup field "BudgetManger" (Related Table : User) for people picker behavior.

I am following SingleTenantS2S approach. Trying to update the Entity using Web API call, But getting The request failed with a status of 'Forbidden'

I am able to create and update other field values in Department Entity, But getting error when I try to create records with user lookup field. 

```
Request body  
	{
							{ "cr0f9_name", "Accounting" },
							{ "cr0f9_company", "XXXXX" },
				            { "cr0f9_BudgetManager@odata.bind", "/systemusers(CE00E812-F720-EB11-A813-000D3A3780DF)" }
						};
        }

```
Reference [](https://github.com/microsoft/PowerApps-Samples/blob/master/cds/webapi/C%23/SingleTenantS2S/Program.cs)

How to add/update user lookup value in custom entity? 

Thanks,
Senthil
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d869f063-f292-aef8-70fe-e165c65a74bd
* Version Independent ID: ff0b5a9f-b085-9223-3df5-ad5b5f196498
* Content: [Create an entity record using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/create-entity-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/create-entity-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/create-entity-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by rpskumar** [comment]
@JimDaly This is working fine if I am not passing user lookup field value to the entity in request. The Application user account has full permission to the custom entity "Department" and Read permission to User Entity

Error Message: StatusCode: 403, ReasonPhrase: 'Forbidden'

I am not sure the format that I am passing user value is the correct. I could not find any resource or sample to set user value to Entity field via Web API

**Comment by rpskumar** [comment]
@JimDaly  This issue is resolved after I assign "Common Data Service User" role to Application user account. Earlier I have created custom role which has full permission on Custom Entity "Department" and "Read permission" on User entity. 

The request  worked when insert/update "Department" entity values without passing user lookup value. When I tried to pass User Datatype to Web API, got Forbidden error. I believe the Application user account needs more permission on user entity than Just "Read permission". Not sure what permission required & why that required just for reading user. Any thoughts?

The issue is resolved after CDS user role assigned.

Thank you.

**Comment by JimDaly** [comment]
It is probably the Append and AppendTo privileges. See [Record-level privileges](https://docs.microsoft.com/en-us/power-platform/admin/security-roles-privileges#record-level-privileges)



Privilege | Description
-- | --
Append | Required to associate the current record with another record. For example, a note can be attached to an opportunity if the user has Append rights on the note. The records that can be appended depend on the access level of the permission defined in your security role.In case of many-to-many relationships, you must have Append privilege for both entities being associated or disassociated.
Append To | Required to associate a record with the current record. For example, if a user has Append To rights on an opportunity, the user can add a note to the opportunity. The records that can be appended to depend on the access level of the permission defined in your security role.
