### ISSUE TITLE
Environment Variables in Managed Solutions

### ISSUE THREAD

**Issue by astanton-crm** [MicrosoftDocs/powerapps-docs#1916]
[Please add more detail to your environment variables documentation. The pieces that are missing include working with environment variables in a managed solutions] If someone wants to update an environment variable in a test environment, this requires a deployment? Can Environment variables be set to configurable even in a managed solution? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad70fa7e-a9df-e2c0-4482-a140ca1c4b4f
* Version Independent ID: 8071aca4-f51a-a53e-0e04-c2a64164eb32
* Content: [Use environment variables in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/environmentvariables)
* Content Source: [powerapps-docs/maker/common-data-service/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/EnvironmentVariables.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@astanton-crm - Sorry for the delay. The article was expanded a few weeks ago to contain more detail for working with environment variables in solutions. 
Closing issue.
