### ISSUE TITLE
Power Automate push notification - cannot pass parameters to the app

### ISSUE THREAD

**Issue by caglata** [MicrosoftDocs/powerapps-docs#1918]
Hi, I cannot pass parameters to the app. Can you please provide a more detailed step-by-step example of how this is done. Power Automate does not give any errors, the notification itself does work, however it does not pass any parameters to the app. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f798dd89-a068-3237-795e-5afe0de7dded
* Version Independent ID: 63dbbfb6-11dc-d7be-3f4b-53417e9c5246
* Content: [Send a push notification from a canvas app. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-notifications)
* Content Source: [powerapps-docs/maker/canvas-apps/add-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-notifications.md)
* Service: **powerapps**
* GitHub Login: @Kavishi
* Microsoft Alias: **kaagar**

**Comment by Kavishi** [comment]
Hey Bishal,

I am no longer the owner for Push notifications. Adding @Anthony Uitz<mailto:Anthony.Uitz@microsoft.com>

**Comment by anuitz** [comment]
Hi @caglata, we've updated the documentation with additional details on how to pass parameters to the app https://docs.microsoft.com/en-us/powerapps/mobile/power-apps-mobile-notification#perform-an-action-when-a-user-taps-the-notification

Please let me know if you have any additional questions.

**Comment by caglata** [comment]
Hi @anuitz, many thanks however I still cannot pass parameters. I have made two tests on my end and neither worked: 
1st Test: A 'Scheduled Flow':
- Flow is triggered on the scheduled date/time => Push Notification works, parameters have not passed

2nd Test: A Manually Triggered Flow from within the Canvas App
- I created a button on the canvas app to trigger the Flow, manually connected the button to the relevant Flow => Push Notification works, parameters have not passed

<img width="591" alt="Screenshot 2020-11-18 at 10 22 46" src="https://user-images.githubusercontent.com/67158260/99518120-0e787b00-2988-11eb-8d61-864a31ae2e82.png">

In both cases, when the notification arrives, I open the App by clicking on the notification. I see that the Label with _Param("ParamID")_ is empty, and the parameter has not been passed.

<img width="415" alt="Screenshot 2020-11-18 at 10 25 04" src="https://user-images.githubusercontent.com/67158260/99518410-6dd68b00-2988-11eb-9367-782f90b6e4d0.png">

Are there specific conditions or limitations for this functionality to work?
Many thanks for your help!

**Comment by anuitz** [comment]
Hi, thank for you catching this, it appears we have a regression in the push notification functionality for the v2 connector so the parameters are not being passed to the app. We will get this fixed as soon as we can.

In the meantime, you can use the original "Send push notification" (not V2 preview) action on the "Power Apps Notification" connector. It will ask you to set up the connection, which will be specific to an app. You can find the app id by going to make.powerapps.com, going to the **Apps** list, click the three dots next to your app, and clicking **Details**. That should take you to a screen including the App ID, Owner, etc. You can put whatever you want for the Connection Name, but I recommend using something identifiable like the name of the app.

**Comment by tapanm-MSFT** [comment]
Please see [sample formulas](https://docs.microsoft.com/powerapps/maker/canvas-apps/add-notifications#sample-formulas). For more help, please contact [help & support](https://docs.microsoft.com/power-platform/admin/get-help-support).
