### ISSUE TITLE
Entity terminology still exists under "Public views" sub-section

### ISSUE THREAD

**Issue by aecarr2** [MicrosoftDocs/powerapps-docs#1919]
The table which exists under the sub-section "Public views" still contains deprecated terminology: entity

The word entity needs to be changed to table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc08be8d-1912-8d97-ff19-4078ef844efd
* Version Independent ID: 7af37edc-e9c1-652a-1d93-2a10e0438dca
* Content: [Create or edit a model-driven app view in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-edit-views)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-edit-views.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/create-edit-views.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@aecarr2 - Thank you for pointing this out. The article has been updated for the new terminology and will be published live in couple of hours. 
Closing issue.
