### ISSUE TITLE
Change Connection Owner

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#192]
When we look at the list of connections on the Connections page in https://web.powerapps.com we see an Owner name that is for a person who is no longer with the company. How can we change this name? it is not discussed in the documentation above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5df5f2bb-1e4d-ce52-0478-19fc7a16f9b3
* Version Independent ID: fc072fdb-3e49-5e12-e8ce-ddfebca0963f
* Content: [Add and manage connections from canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-manage-connections#update-or-delete-a-connection)
* Content Source: [powerapps-docs/maker/canvas-apps/add-manage-connections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-manage-connections.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by AFTOwen** [comment]
Thanks, @DeanGross, for your question. "...we don’t have support for renaming or reparenting custom connectors today if the customer leaves the company.  The only option would be to delete and re-create the resource – which is available today via our PowerApps PowerShell cmdlets.  NOTE: this approach will impact existing apps and flows that use the resource." Closing the issue.
