### ISSUE TITLE
entityFormOptions["openInNewWindow"] = true opens new Tab

### ISSUE THREAD

**Issue by ddevine-msft** [MicrosoftDocs/powerapps-docs#1921]
Please update the documentation. 

Issue:
When specifying entityFormOptions["openInNewWindow"] = true without entityFormOptions["height"] and entityFormOptions["width"] a new Tab will be opened. This seems to have changed in 2020 Wave 2 release. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b204ee0a-69a2-e52d-f110-2291be66c1af
* Version Independent ID: 8ac980df-6b5f-2b33-707f-11efb597ba6a
* Content: [openForm (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openform)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ddevine-msft Even though if i don't set the values of height and width and set `openInNewWindow=true`, Yes a new tab is opened with default height and width. If you specify the height and width long with `openInNewWindow=true`, the new tab takes the values of height and width into consideration and open the window with the specified values. Did anything change?

**Comment by ddevine-msft** [comment]
@Nkrb yes behavior changed in Wave 2. Before when openInNewWindow=true it always opened a new window (not tab). Now a height and width are required for a new window. The reference in this documentation is correct https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/navigation/openform

**Comment by nefertiti-rogers** [comment]
submitted a PR to update this.

**Comment by Nkrb** [comment]
@nefertiti-rogers @nefertiti-rogers Merged the PR. Closing the issue.
