### ISSUE TITLE
Is the Dynamics 365 CE Admin API also deprecated Effective August 26, 2020 

### ISSUE THREAD

**Issue by ugreg** [MicrosoftDocs/powerapps-docs#1922]
Is the Online Management API for Common Data Service the same as the Online Management API for Common Data Service
from this swagger page? https://admin.services.crm.dynamics.com/swagger/ui/index#/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 704d7bb5-0eb4-80ab-fee1-9e8fc744324f
* Version Independent ID: 6eff0877-ac70-1e57-9f3b-4def97e7a3d8
* Content: [Online Management API for Common Data Service - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/online-management-api/overview)
* Content Source: [powerapps-docs/developer/common-data-service/online-management-api/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/online-management-api/overview.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment]
@ugreg  Yes, they are the same. Deprecated.
