### ISSUE TITLE
Occurrences of control element should be maximum 1 in PCF manifest file

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#1923]
The Occurrences for the control element of the manifest is showing as zero or more - but you can only have a single control element per manifest or the pcf control will not build - with the error 'Manifest validation problem: instance.manifest.control does not meet maximum length of 1'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24a8dcfa-d75f-b8d1-c020-e3fa6b74eb28
* Version Independent ID: c5389f9a-25a0-6cd5-f542-fa49a3625314
* Content: [Manifest Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/manifest)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/manifest.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/manifest.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@scottdurow Thanks for the feedback. Docs are updated and pushed live. Closing the issue. If you need further help, please reopen or create a new issue.
