### ISSUE TITLE
Known limitation: CDS does not work with component

### ISSUE THREAD

**Issue by babakdanyal** [MicrosoftDocs/powerapps-docs#1924]
Today I was trying to create a component based on CDS data but component does not recognize any of the CDS entities and keeps giving errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93230c47-e5a5-15ad-9320-2f9671fdebb5
* Version Independent ID: dc5050e4-7243-b861-4c97-3bfb0165ade5
* Content: [Create a component for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-component)
* Content Source: [powerapps-docs/maker/canvas-apps/create-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-component.md)
* Service: **powerapps**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. If referring to the code components created using Power Apps Component Framework, please see [Code components for canvas apps](https://docs.microsoft.com/powerapps/developer/component-framework/component-framework-for-canvas-apps).
