### ISSUE TITLE
Not actual any more

### ISSUE THREAD

**Issue by dimazoin** [MicrosoftDocs/powerapps-docs#1925]
There is no possibility to customize screen size as article says, no screen size selector. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba2ea78-be6e-2715-7e7d-a18d6a628c86
* Version Independent ID: e9bb4980-2e68-4921-d13c-729e48f03ad3
* Content: [Customize the screen size and orientation of a canvas app embedded on a model-driven form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-customize-screen)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-customize-screen.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-customize-screen.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@dimazoin - The screen size configuration is only available with tablet layout canvas apps. The article has been revised to indicate that as well as shortened and links to the primary article that describes in detail how to change the screen and orientation of a canvas app. 
Closing issue.
