### ISSUE TITLE
Spatial Services - Premium or not?

### ISSUE THREAD

**Issue by quasarsnax** [MicrosoftDocs/powerapps-docs#1927]
Will spatial services transition to being a premium feature??

This is important to delineate for people who are building business applications around this feature currently.

**Comment by phecke** [comment]
@quasarsnax 

Thanks for contacting us. Unfortunately, we're unable to handle Support or feature requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.
