### ISSUE TITLE
Editing the AppModule

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#1929]
Is Editing the AppModule (model-driven app) supported? e.g. editing the NavigationType property of an app module to switch the normal one into Multi session app. (please refer to the links below for the property and use case). If it is not supported, can you please list "Model-driven Apps" under **Unsupported tasks**?

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/appmodule?view=dynamics-ce-odata-9#properties:~:text=navigationtype

https://twitter.com/prokytom/status/1290741374480982018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c585e03-a145-2d5b-4aa4-15ea5035b515
* Version Independent ID: 6b6855f5-7522-f5ee-c879-6343a018d71a
* Content: [When to edit customizations file (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/when-edit-customization-file)
* Content Source: [powerapps-docs/developer/model-driven-apps/when-edit-customization-file.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/when-edit-customization-file.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@LinnZawWin Thanks for contacting us. This as not supported for now, however we are looking at supporting it in the future. Closing the issue.
