### ISSUE TITLE
unclear wording using "users" at "entitlement limits"

### ISSUE THREAD

**Issue by iiu-dk** [MicrosoftDocs/powerapps-docs#1930]
it is unclear what the term "users" cover in text regarding "entitlement limits".
Please list "user" types that are counted towards "entitlement limits".
I assumption is that entitlement limit is for "end users/interactive users" of product and not for Application users( non-interactive users), but please clarify in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b61960df-dcdc-d4e5-749b-0f55e22a385d
* Version Independent ID: baddf389-6252-fe30-1a60-48c18f256ed8
* Content: [API limits overview (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview#service-protection-limits)
* Content Source: [powerapps-docs/maker/common-data-service/api-limits-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/api-limits-overview.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@cpdSeattle  Cameron - can you look at this?

**Comment by JonKragh** [comment]
Is there clarification on limits for Application users ( non-interactive users)? We are working on pushing data in Dataverse (from logic apps) and we might have to pull the plug on Dataverse if there is no way to overcome the entitlement limits. We just want to push data nightly into CDS.
