### ISSUE TITLE
Cookies are not always the problem

### ISSUE THREAD

**Issue by eccountable** [MicrosoftDocs/powerapps-docs#1932]
I am using Edge Version 86.0.622.68 and typed "make.powerapps.com" in the URL bar and got the error message:
```
UserInterventionNeeded_CookiesBlocked
Unable to access cookies. Please ensure that you have cookies enabled in your browser.
```
The Troubleshooting links on this page were no help - this is a new install of Edge and cookies and local data were allowed.

When I click the "Try Again" link, I keep getting the same error.
I found the solution was to change the URL to explicitly use HTTPS://make.powerapps.com and then I got the Power Apps home page. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de7fca-d66b-479c-1570-676ebafa1b78
* Version Independent ID: 70b75562-e755-31cd-c7fd-ef87983698f5
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues)
* Content Source: [powerapps-docs/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. make.powerapps.com by default redirects to using HTTPS. There may be a browser-specific or client-specific issue. If the problem persists, please reach out through [Help + Support](https://docs.microsoft.com/power-platform/admin/get-help-support).
