### ISSUE TITLE
The resource contains script errors preventing it from being loaded

### ISSUE THREAD

**Issue by RaoufKamel** [MicrosoftDocs/powerapps-docs#1933]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d71e01-9651-365a-0fc0-b0017d3866ca
* Version Independent ID: 507be630-f013-10d1-00dc-c57aa949f0cb
* Content: [Customize the Azure AD B2C user interface for portals. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/azure-ad-b2c)
* Content Source: [powerapps-docs/maker/portals/configure/azure-ad-b2c.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/azure-ad-b2c.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by KumarVivek** [comment]
@tapanm-MSFT Can you pls look into this issue?

**Comment by RaoufKamel** [comment]
Hi

I want to cancel this issue , because after investigation I’m not sure the solution I gave has resolved the problem , because the problem has appeared again , restarting the portal I think has resolved the problem

Thanks

**Comment by tapanm-MSFT** [comment]
Thank you for the update. The GitHub issue for documentation is closed. If the problem persists, please reach out to the support teams for investigation of the issue with a [support ticket](https://admin.powerplatform.microsoft.com/support).
