### ISSUE TITLE
Dynamics/PowerApp Licensing question! 

### ISSUE THREAD

**Issue by sshashi7** [MicrosoftDocs/powerapps-docs#1934]
Hi,

The Power Apps Licensing guide states that per app and per user licenses allow access to complex entities (Lead, opportunity etc..). Does this mean that in a non-dynamics Dataverse (CDS), organizations can import just complex entities and use them? (Without installing the Dynamics 365 app?)

![image](https://user-images.githubusercontent.com/35941922/99311205-1366ee80-2811-11eb-9b2a-bae68a186237.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted tables requiring Dynamics 365 licenses - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@sshashi7 I believe your query was answered; closing the issue.

**Comment by gregdegruy** [comment]
Hi team, brining the feedback from our email FAQ here in case someone else in the open source community runs into this same issue.

**FAQ**

A
> License is applied at runtime and not during making/creations. i.e. the end user of the app needs to have the appropriate license. So 1 license doesn’t work for the ISV. They need to look for the Dynamics ISV embed license in such cases.

Q
> I the case the end users will be properly licensed with Power Apps per app/per user licenses. However, the environment will need Dynamics 365 sales app as it incudes some of these complex tables (Opportunity & Lead).
> The [document](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Fsales-enterprise%2Fset-up-dynamics-365-sales%23install-the-sales-solution&data=04%7C01%7CGregory.Degruy%40microsoft.com%7C9c7354c6efbb41f65b8708d88b42d2a0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637412466401585756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Jpa136wGCiABI%2FvtgjtaA70swPTk5OzhqGc3gqQQxR4%3D&reserved=0) also suggests that 1 Dynamics 365 sales enterprise license is required at a minimum to install sales app. So, wanted to understand the recommendation and best practice for such a scenario.
![image](https://user-images.githubusercontent.com/8151045/99832519-82945980-2b15-11eb-8abe-e723b5c4142a.png)

A
> The document you are referencing is talking about a pre-requisite for installation of the app; I believe there is a check/ in-product enforcement as well which checks to ensure that you have at least one license before installing the sales app (which also installs these entities into Dataverse (previously called Common Data Service). For **restricted entities** license requirement (as a policy) that end **users of the app would need to have Dynamics 365 license (not the PowerApps license)**, if the app is using the restricted entities.   

Q
> In our use case we are not using any restricted entities. However, during environment creation, it seems to check for Dynamics 365 licenses for enabling Dynamics 365 apps. I believe customers will need at least one license before installing the sales app?
![image](https://user-images.githubusercontent.com/8151045/99832837-064e4600-2b16-11eb-8515-b4ef378b617c.png)

A
> Correct.  However, a small bit of info about that screenshot is that, it is not just about the installation of the app, but while creating the environment, it makes some schema adjustments to Microsoft Dataverse to enable D365 applications which is why we have those checks during environment creation. The schema difference within Microsoft Dataverse would be removed in the coming months.  If they aren’t using the restricted entities, there shouldn’t be a need to enable this schema (use the Enable Dynamics 365 apps) option.

**Comment by gregdegruy** [comment]
@sshashi7 is does the modified thread I included provide the right level of context to answer this question?
