### ISSUE TITLE
delegation?

### ISSUE THREAD

**Issue by KarmaLlama** [MicrosoftDocs/powerapps-docs#1936]
Page does not confirm if this function can be delegated.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfce2c44-971e-0cbb-4470-4512b51a090a
* Version Independent ID: 047b4907-1f3d-79e5-6974-949cd0b94b70
* Content: [Count, CountA, CountIf, and CountRows functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-table-counts)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-table-counts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-table-counts.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have update the docs. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
