### ISSUE TITLE
API permissions screen has changed

### ISSUE THREAD

**Issue by chvollm** [MicrosoftDocs/powerapps-docs#1937]
The API permissions screen has changed. "Grand admin consent" is now on top. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f87a0a-9dd9-5188-7347-d910423902ca
* Version Independent ID: 9f532b04-f9c5-cbdd-a2bd-666b55ee942e
* Content: [Use Single-Tenant server-to-server authentication (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication#azure-application-registration)
* Content Source: [powerapps-docs/developer/common-data-service/use-single-tenant-server-server-authentication.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-single-tenant-server-server-authentication.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **pehecke**

**Comment by KumarVivek** [comment]
@phecke Can you pls look into this.

**Comment by phecke** [comment]
@chvollm Thanks for pointing that out. I am looking into updating the image.

**Comment by phecke** [comment]
@chvollm The page will be updated later today. Thanks.
