### ISSUE TITLE
Missing information for Business rules limitations

### ISSUE THREAD

**Issue by nferdinandova** [MicrosoftDocs/powerapps-docs#1938]
In previous versions of this documentation there was a list of limitations when creating Business rules. It needs to be added to this page. It is frustrating that new documentation has been built without carrying over details from the previous one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5133a12f-c678-9e84-1bb7-84d66192b2ad
* Version Independent ID: efcbf000-8b95-727b-1cf2-8d7e27bf3d95
* Content: [Create a business rule in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-create-business-rule?source=docs)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-create-business-rule.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-create-business-rule.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by Mattp123** [comment]
@nferdinandova - thank you for bringing this missing content to our attention. The common issues section has been added to the article in the Power Apps documentation set. Closing issue.
