### ISSUE TITLE
No template for moving data between CDS and D365 F&O

### ISSUE THREAD

**Issue by PrebenAmilcare** [MicrosoftDocs/powerapps-docs#194]
It would be great if it was possible to use data integration to exchange data between D365 F&O and CDS. This template is missing in the CDS integration project. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6352172-89dc-9489-2271-6397e9302c6d
* Version Independent ID: db401145-b8b7-55a2-f829-a63d538cf7f0
* Content: [Integrate data into Common Data Service for Apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/data-integrator)
* Content Source: [powerapps-docs/administrator/data-integrator.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/data-integrator.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by jimholtz** [comment]
Closing this. Please reopen if this is still relevant.
