### ISSUE TITLE
Code always fails on "Login.MainPage failed to load in 2 minutes using Cloud Identity Login" when trying to login to chrome browser

### ISSUE THREAD

**Issue by SamMilanese** [MicrosoftDocs/powerapps-docs#1940]
Following the instructions here: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/test-studio-classic-pipeline-editor

The step to run the powerapp test via chrome always fails on "Login.MainPage failed to load in 2 minutes using Cloud Identity Login" even though the credentials used within the variables are correct.  I assume the code needs updating somewhere?

Works with Firefox though

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Please reach out to support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support) to investigate the issue with Chrome.
