### ISSUE TITLE
Data Factory

### ISSUE THREAD

**Issue by philipverlinden** [MicrosoftDocs/powerapps-docs#1941]
Are there any examples/samples we can refer to?
Data pipeline examples on Github where Dataverse is a source and/or a target with some example transformations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17a9d12e-d962-7e84-3c67-9fab5ad30c93
* Version Independent ID: 671ef624-33d4-1007-2b03-5811c88620b5
* Content: [Importing and exporting data - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/why-cds-import-export)
* Content Source: [powerapps-docs/maker/common-data-service/why-cds-import-export.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/why-cds-import-export.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@philipverlinden - see these articles for Power Platform build tools and Azure pipeline content: 
- [ALM for developers](https://docs.microsoft.com/en-us/power-platform/alm/alm-for-developers)
- [Tutorial: Get started with GitHub Actions for Microsoft Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-start)

Closing issue.
