### ISSUE TITLE
Are powerapps responsive by default

### ISSUE THREAD

**Issue by karun533** [MicrosoftDocs/powerapps-docs#1944]
https://docs.microsoft.com/en-us/powerapps/powerapps-overview

 Further, apps built using Power Apps have a responsive design, and can run seamlessly in browser or on mobile devices (phone or tablet). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a87d70-1f25-0a75-bc11-f2c079f2083c
* Version Independent ID: 7b1e729a-d4b6-2786-2ac7-c9e1c516a815
* Content: [What is Power Apps? - Power Apps](https://docs.microsoft.com/en-us/powerapps/powerapps-overview)
* Content Source: [powerapps-docs/powerapps-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/powerapps-overview.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by tapanm-MSFT** [comment]
Please read [Build responsive apps](https://docs.microsoft.com/powerapps/maker/canvas-apps/build-responsive-apps).
