### ISSUE TITLE
Parent elements section missing

### ISSUE THREAD

**Issue by mads-lundemann** [MicrosoftDocs/powerapps-docs#1945]
The section describing the correct parent element is missing, so it is not clear which element feature-usage goes into.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5277bf73-4919-d080-ea67-82fffeab5861
* Version Independent ID: 5c9c3114-41c1-1a77-d1d5-13a3830a602f
* Content: [feature-usage - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/feature-usage)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/feature-usage.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/feature-usage.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
