### ISSUE TITLE
New required feature-usage missing in manifest

### ISSUE THREAD

**Issue by mads-lundemann** [MicrosoftDocs/powerapps-docs#1946]
The manifest in the Table sample component is missing the new required feature-usage+uses-feature element (for the Utility feature). This means that the sample no longer works in Dynamics. Also it looks like rendering with npm start actually works now, provided the manifest is updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82b311d5-7863-1d9e-df7b-bf1664df04e8
* Version Independent ID: 32a0ee12-df58-0d6e-f62a-69ff6468107b
* Content: [Table component - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/table-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/table-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/table-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
