### ISSUE TITLE
Whitespace control does not work as described

### ISSUE THREAD

**Issue by dev717** [MicrosoftDocs/powerapps-docs#1947]
I have tried the code listed on a Power Apps Portal web page copy section and it produces the error listed below. 

**** code ****
{% for i in (1..5) --%}

{{ i }}

{%-- endfor %}

**************

**Tag '{%- endfor %}' was not properly terminated with regexp: (?-mix:\%\})**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8951b5ab-22be-4532-ab1a-d4c0e6a59c43
* Version Independent ID: a7f0abbf-038e-04bb-4544-6a17e266d405
* Content: [Use Liquid tags for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/liquid-tags)
* Content Source: [powerapps-docs/maker/portals/liquid/liquid-tags.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/liquid/liquid-tags.md)
* Service: **powerapps**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content has been fixed, please allow some time to reflect the changes.
