### ISSUE TITLE
Local and Global Choices

### ISSUE THREAD

**Issue by Brunanschultz** [MicrosoftDocs/powerapps-docs#1948]
Hi, 

I'm trying to create a choice column and everytime I face the same issue: You are missing the necessary privilege to create global choices in this environment. You may still save this choice locally to your field. I tried to click on View More, but I couldn't pick any option. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00735ecb-5119-6abb-737c-1fbe4e9a68a6
* Version Independent ID: e95c3f61-caf1-b3ac-fa7e-a8ec59f56e42
* Content: [Create a choice - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/custom-picklists)
* Content Source: [powerapps-docs/maker/common-data-service/custom-picklists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/custom-picklists.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by Mattp123** [comment]
@Brunanschultz - What security role(s) do you have in that environment? Following the steps may help you determine what access you have. [Troubleshooting: Common user access issues](https://docs.microsoft.com/en-us/power-platform/admin/troubleshooting-user-needs-read-write-access-organization)

**Comment by Mattp123** [comment]
Closing issue.
