### ISSUE TITLE
InputTextPlaceholder is ignored when IsSearchable is false

### ISSUE THREAD

**Issue by jojocode77** [MicrosoftDocs/powerapps-docs#195]
Expected behaviour: the InputTextPlaceholder should display when no item is selected in the combo-box.
Actual behaviour: If the IsSearchable property is false, the InputTextPlaceholder text disappears from the control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8bf3d3-12e3-5b55-8713-221cf5f5a30c
* Version Independent ID: 5a050d01-6ef6-97d6-07de-d5cac82dea06
* Content: [Combo box control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-combo-box)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
Note that the InputTextPlaceholder is the "ghost text" for the search field, which is shown by default when search is enabled and no selections are made.  

It does not show when search is disabled, which is by design.   We are working on a feature to show hint text for these scenarios.

**Comment by jojocode77** [comment]
Thanks!
