### ISSUE TITLE
500 status or 412

### ISSUE THREAD

**Issue by snvboy** [MicrosoftDocs/powerapps-docs#1951]
The documentation here shows a 500 status is returned when duplicates are detected. Is this correct? I thought it would be returning a 412 "Precondition Failed" status.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aafb392-328f-398d-4221-f81230f639a1
* Version Independent ID: cd92deef-0bff-62d4-4e7c-89a65eafad86
* Content: [Detect duplicate data using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/manage-duplicate-detection-create-update)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/manage-duplicate-detection-create-update.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/manage-duplicate-detection-create-update.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@snvboy Yes, 500 is correct.
