### ISSUE TITLE
Terminology change Table -> Entity

### ISSUE THREAD

**Issue by last72** [MicrosoftDocs/powerapps-docs#1953]
On Step 2:
On the sitemap designer select New Subarea, in the right pane select the Properties tab, and then select the following properties.

Type: Table

Table: Account

Needs to be 

On the sitemap designer select New Subarea, in the right pane select the Properties tab, and then select the following properties.

Type: **Entity**

Table: Account

As per screenshot and as per https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro#terminology-updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf4cad7-a8cd-c1cc-1122-3db6c858b307
* Version Independent ID: 64f2be57-f3c7-595b-b3d7-63621fe4ad81
* Content: [Build your first model-driven app from scratch with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/build-first-model-driven-app)
* Content Source: [powerapps-docs/maker/model-driven-apps/build-first-model-driven-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/build-first-model-driven-app.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@last72 - This has been fixed and will be published live in a few hours. 
Closing issue.
