### ISSUE TITLE
Environment Variables cannot be edited / updated after import of solution

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/powerapps-docs#1955]
I am importing a Managed solution with Current Values removed from the Unmanaged Solution.
How can we update the Environment Variable Value after importing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad70fa7e-a9df-e2c0-4482-a140ca1c4b4f
* Version Independent ID: 8071aca4-f51a-a53e-0e04-c2a64164eb32
* Content: [Use environment variables in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/environmentvariables)
* Content Source: [powerapps-docs/maker/common-data-service/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/EnvironmentVariables.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by m3ngi3** [comment]
Also see https://github.com/microsoft/powerapps-tools/issues/591

**Comment by m3ngi3** [comment]
See https://www.youtube.com/watch?v=ba9uLT4S_7c for extended video

**Comment by caburk** [comment]
If you don't have any value (no default or current value) you'll be prompted to enter a value when using the new solution import experience. Otherwise you'd need to edit it within the default solution or by adding it to an unmanaged solution.

**Comment by Mattp123** [comment]
@m3ngi3 - I believe your question is answered. Closing issue.

**Comment by m3ngi3** [comment]
@caburk that should be the behavior yes but as you will find in my video and related posts this was not the case.
For workarounds however see: https://powerusers.microsoft.com/t5/Microsoft-Dataverse/Updating-Environment-Variables-in-Managed-Solution/m-p/767262#M8591.

Issue can be closed here (the product defect is being picked up by the product team at Microsoft).
