### ISSUE TITLE
DataTable.Selected does NOT work when the DataTable is connected to PowerBIIntegration.Data

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/powerapps-docs#1956]
This looks great, but does not work for me. 
I'm a little new to Power Apps. Previously I created a Power App from an embedded visual in Power BI. That creates a Gallery control, but that is Read Only. I can then add an Edit Form, connect the Form to a SQL table, then set the Item to Galler1.Selected. Works great. When I select an item in the Gallery, OR when Power BI filters the data passed to the Power App Gallery, the data in the Edit Form is filtered accordingly. Last thing is to add a SAVE button and set its OnSelect action to SubmitForm(Form1). Bingo, I now have a full circle where I can edit my Power BI data via Power Apps.

But trying to use a DataTable instead of the initial Gallery does not work: I delete the Gallery and create a DataTable, set its Items to 'PowerBIIntegration'.Data and it displays data from Power BI just like the Gallery did. Great. Now following the directions on this page, I add an Edit Form, connect it to my SQL source (NOT the same Entity as you describe here), then set the Item property to DataTable1.Selected. 

RESULT: Error - Invalid formula. Expected a value compatible with 'DataSource'

I don't get it. Why does it work for a Gallery, but not a Data Table? They both use 'PowerBIIntegration'.Data as their DataSource, and in both cases the Edit Form is connected to a SQL table. (BTW, the SQL table in Power Apps is the SAME SQL Table that supplies Power BI with its data.)

Is this a bug? How do I get it to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af82396d-69f1-daf7-be8c-15c1a841bd19
* Version Independent ID: d97646e7-abe7-51f3-6d06-0eb86a441d5d
* Content: [Data table control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-data-table)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-data-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-data-table.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there,

Data within a DataTable is not the same (equivalent) as your SQL Row.  DataTable is more tightly bound to the original data which is a dynamic schema from PowerBI.  You'll need to do a Lookup() against your SQL Table using the a column from the PBI DataSource. 

Item = Lookup(MySqlData, ID = DataTable.Selected.Id)

Hope this helps.
