### ISSUE TITLE
Auto-number attribute UI is available in maker portal

### ISSUE THREAD

**Issue by bhshastr** [MicrosoftDocs/powerapps-docs#1957]
This page states there's no UI for Auto-number attribute but maker portal gives UI for creating auto number attribute.
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/autonumber-fields 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ed5d32-c7ea-cf1b-4b67-42d220bced10
* Version Independent ID: 809601df-9094-fa16-2aba-f8941c2fd1db
* Content: [Create auto-number attributes (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-auto-number-attributes)
* Content Source: [powerapps-docs/developer/common-data-service/create-auto-number-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/create-auto-number-attributes.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **jdaly**

**Comment by NHelgren** [comment]
Hi @bhshastr, The note in the document indicates that the classic web client does not provide the ability to manage the attribute, which is true. This is available for the UCI though. Once the web client is retired the document will be updated.

**Comment by bhshastr** [comment]
Hi @NHelgren -
The page states "There is no user interface to add this type of attribute" which is misleading.

![image](https://user-images.githubusercontent.com/74993267/100647587-9d748400-32f4-11eb-9fae-e16aec0e5f20.png)

**Comment by NHelgren** [comment]
Ahh I found the issue, this was submitted on the Maker document but the problem was in the Developer document here: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-auto-number-attributes

I have submitted a fix and it should appear shortly.
