### ISSUE TITLE
Dataverse backend database access

### ISSUE THREAD

**Issue by marcelacardenas** [MicrosoftDocs/powerapps-docs#1958]
Hello,
 I´m trying to replicate the data on this [dashboard ](https://docs.microsoft.com/en-us/power-platform/admin/analytics-common-data-service#home-default) (for example: Daily Active Users) via SSMS/SQL for example: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query

More context: I would like to have flexibility on building my own metrics and storing this in my own datawarehouse which will be used as my data source of the reporting tools (i.e. Power BI) 

So far, I was able to connect to this [database ](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/entitytypes?view=dynamics-ce-odata-9 ) but the data model does not clearly show how to get the Daily Active Users, additionally it appears it only has one day of data hence my need of extracting these into my own datawarehouse . 

Is there documentation on how to access to the backend of dataverse analytics data programatically? 

Thank you.

**Comment by saulcruzr** [comment]
I did not find this anywhere in the documentation, I'd be interested to know as well...i.e. how can use Azure Data Factory to build data pipelines and load these data somewhere else? i.e.Azure SQL Database or Datawarehouse and do more transformations on top of it... also definitions on these metrics would really help i.e. how are "Daily Active Users" calculated?

Thanks.

**Comment by phecke** [comment]
@marcelacardenas @saulcruzr 

There is no entity data model or service endpoint that makes that data available via an API.

**Comment by JimDaly** [comment]
I understand this data comes from our internal telemetry and isn't stored in your CDS database.

**Comment by saulcruzr** [comment]
Thanks. I was hoping to build my own "datamart" and have more flexibility on the data. Makes sense, let me know if this becomes available at some point. Much appreciated.
