### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by barlowse** [MicrosoftDocs/powerapps-docs#196]
Would be nice to be able to change the spacing between lines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 492e388f-6f28-4cc4-3897-8a6384e8a466
* Version Independent ID: c3a43927-981d-ad01-969e-285c7a80158a
* Content: [Rich text editor control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-richtexteditor)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-richtexteditor.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-richtexteditor.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
Thanks for your feedback, @barlowse. For product-related feedback, please visit [the forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.
