### ISSUE TITLE
Getting Sign In failed when using custom page for a user flow

### ISSUE THREAD

**Issue by warrenzahra87** [MicrosoftDocs/powerapps-docs#1960]
Using the azure AD B2C login page a user is able to login successfully, however when I Place the Custom page URL in the Sign in user flow, The user is always being redirected to the sign in page with an error saying Sign in failed

**Comment by Nkrb** [comment]
@warrenzahra87 Can you point us to the doc you're talking about. It helps us to assign the issue to the right person.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
