### ISSUE TITLE
Calling custom unbound API function

### ISSUE THREAD

**Issue by MarkMpn** [MicrosoftDocs/powerapps-docs#1963]
If I create a custom API with Binding Type = None and Is Function = Yes, I'd expect to be able to call it with:

```http
GET [Organization URL]/api/data/v9.1/new_MyAPI()
```

but this returns

```http
HTTP/1.1 404 Not Found
Content-Type: application/json; odata.metadata=minimal

{"error":{"code":"0x8006088a","message":"Resource not found for the segment 'new_MyAPI'."}}
```

Is this an error in the preview, or an expected limitation that is not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67348a80-9ef7-d5f4-d945-bb7ef6a6f8c9
* Version Independent ID: 83f7bc1d-17ec-571c-69ba-5b69118872c4
* Content: [Create and use Custom APIs (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/custom-api)
* Content Source: [powerapps-docs/developer/common-data-service/custom-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/custom-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@MarkMpn 
Thanks for reporting this. I can confirm what you report and will update the docs.

Unlike an action, a function needs to return a value before it will work. 
In this case, you MUST provide a Response Property AND set a value in the plug-in.

If you don't set a response property, you will get the error above.
Even with a response property, if you don't actually set any data to return, it will successfully return 204 No Content.

**Comment by rappen** [comment]
Thanks @JimDaly !
Makes sense I guess, and looking forward to the docs update :)
And thanks @MarkMpn for troubleshooting for me... 😉

Happy thanksgiving, if that's a think you do!

**Comment by JimDaly** [comment]
I updated the topic to make it clearer that a response property is required for a function.

Also made the following changes:
 - Fixed the FetchXML and SQL query examples
 - Added an example showing how to use SetLocLabels
-  Updated the reference to include the two new types: StringArray and Guid
-  Called out that private messages cannot be used in plug-ins

Thanks for your attention and feedback!
Now I'm going to eat some turkey.
