### ISSUE TITLE
Calling custom collection-bound function from Web API

### ISSUE THREAD

**Issue by MarkMpn** [MicrosoftDocs/powerapps-docs#1964]
Custom collection-bound APIs can only be created as functions, so I'd expect to be able to call them as a function on the associated entity set, e.g.

```http
GET [Organization URL]/api/data/v9.1/accounts/Microsoft.Dynamics.CRM.new_CollectionBoundFunction()
```

but this gives the error

```http
HTTP/1.1 400 Bad Request
Content-Type: application/json; odata.metadata=minimal

{"error":{"code":"0x8006088a","message":"The request URI is not valid. Since the segment 'accounts' refers to a collection, this must be the last segment in the request URI or it must be followed by an function or action that can be bound to it otherwise all intermediate segments must refer to a single resource."}}
```

Can you please provide an example of how this sort of API should be invoked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67348a80-9ef7-d5f4-d945-bb7ef6a6f8c9
* Version Independent ID: 83f7bc1d-17ec-571c-69ba-5b69118872c4
* Content: [Create and use Custom APIs (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/custom-api)
* Content Source: [powerapps-docs/developer/common-data-service/custom-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/custom-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@MarkMpn 
I believe this is covered in one of the known issues:

[Custom API functions cannot use Entity or EntityCollection Request Parameters](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/custom-api#custom-api-functions-cannot-use-entity-or-entitycollection-request-parameters)

> If you define your Custom API as a function by setting the Is **Function** property to true, you cannot bind the function to an entity or entity collection. You also cannot use any **Entity** or **EntityCollection** request parameters.

This is one of the items we want to fix. Not supported for now.

But I will add the error you report as an example.

**Comment by JimDaly** [comment]
Please re-open if I've misunderstood.
