### ISSUE TITLE
Documentation slight tweak needed

### ISSUE THREAD

**Issue by newzulumaster** [MicrosoftDocs/powerapps-docs#1966]
Had to use the 'selectedtext' property instead of 'selected' when following the example here:   Text(Date(Value(Year.SelectedText.Value), Value(Month.SelectedText.Value), Value(Day.SelectedText.Value)), DateTimeFormat.LongDate)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2548fd17-5e1c-99d3-b7f7-a0b48c56c2bf
* Version Independent ID: f645f526-3e2c-ae5f-965d-a64c6a9094df
* Content: [Show text, dates, and times in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/show-text-dates-times)
* Content Source: [powerapps-docs/maker/canvas-apps/show-text-dates-times.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/show-text-dates-times.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been updated, please allow some time to reflect the changes.
