### ISSUE TITLE
Sample should be updated

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1967]
The Assign message is deprecated [Legacy update messages](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/entity-operations-update-delete#legacy-update-messages)

This sample should show using Update to assign records.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa6845f6-244a-b43b-7012-9a493cb192f2
* Version Independent ID: 5d2ab2d9-215b-222b-8041-d9f26060cb3c
* Content: [Assign a record to a team (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/samples/assign-records-to-team)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/samples/assign-records-to-team.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/samples/assign-records-to-team.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@Nkrb 
Is this something you might do?

**Comment by Nkrb** [comment]
@JimDaly Updated the sample with Update message and removing the use of deprecated message. Closing the issue.
