### ISSUE TITLE
Bad link to sample

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1968]
The link to access this sample goes to the wrong sample: https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/C%23/ValidateandExecuteSavedQuery 

It should go here:
https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/C%23/ValidateAndSetRecordState

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a662245-a9e4-1a9f-4efa-b5f4c66792d5
* Version Independent ID: 834b3801-ad0c-614a-6e53-3ee359dc657b
* Content: [Validate and set record state (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/samples/validate-record-state)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/samples/validate-record-state.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/samples/validate-record-state.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by Nkrb** [comment]
@JimDaly The link is updated to point the right sample. Closing the issue.
