### ISSUE TITLE
Sample uses deprecated message

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1969]
In the sample methods, the SetState method uses the SetStateRequest. This message has been deprecated in favor of Update.
See [Legacy update messages](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/entity-operations-update-delete#legacy-update-messages)

[link to code](https://github.com/microsoft/PowerApps-Samples/blob/6419c2da03ce1e2fb619f5d1fdb150b5f05ae6b7/cds/orgsvc/C%23/ValidateAndSetRecordState/ValidateAndSetRecordState/SampleMethods.cs#L155)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a662245-a9e4-1a9f-4efa-b5f4c66792d5
* Version Independent ID: 834b3801-ad0c-614a-6e53-3ee359dc657b
* Content: [Validate and set record state (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/samples/validate-record-state)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/samples/validate-record-state.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/samples/validate-record-state.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@Nkrb Is this something you can do?

**Comment by Nkrb** [comment]
@JimDaly I can update the sample.

**Comment by Nkrb** [comment]
@JimDaly The sample is updated. Removed the deprecated message and used the update method. Closing the issue.
