### ISSUE TITLE
Power Apps

### ISSUE THREAD

**Issue by rmororo** [MicrosoftDocs/powerapps-docs#1970]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a87d70-1f25-0a75-bc11-f2c079f2083c
* Version Independent ID: 7b1e729a-d4b6-2786-2ac7-c9e1c516a815
* Content: [What is Power Apps? - Power Apps](https://docs.microsoft.com/en-us/powerapps/powerapps-overview)
* Content Source: [powerapps-docs/powerapps-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/powerapps-overview.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by rmororo** [comment]
O que é Power Apps e o que ele pode fazer por você
3 minutos
Você tem processos comerciais ineficientes ou legados que gostaria de modernizar? Você ainda está movimentando informações usando papel ou mesmo uma pasta de trabalho Excel compartilhada? Você quer ser capaz de executar esses processos de negócios a partir de diferentes dispositivos como PCs ou telefones celulares? Então você precisa de Power Apps.

Power Apps é uma plataforma sem código/baixo código para a construção de aplicativos que se baseia em conceitos similares a fórmulas em uma pasta de trabalho Excel como SUM e TEXT. Você pode usar Power Apps para construir soluções simples como formulários de inspeção de veículos e relatórios de status ou soluções comerciais complexas para processos de compras e gerenciamento de inventário. Se você pode visualizar um aplicativo para resolver um problema comercial, então você pode usar suas habilidades existentes para construí-lo. Embora este módulo seja voltado para usuários empresariais com pouca experiência em informática e codificação, o Power Apps oferece funcionalidade avançada e a capacidade para desenvolvedores experientes de projetar aplicações complexas com facilidade.

**Comment by rmororo** [comment]
Adicione inteligência artificial ao seu aplicativo sem código
Antes dos Power Apps, acrescentar funcionalidades como reconhecimento de imagem ou modelos de previsão exigia conhecimentos avançados de informática. Havia código para escrever, modelos de dados para projetar e treinar, e uma grande quantidade de lógica complicada. Power Apps "democratizou" a inteligência artificial, fornecendo uma interface baseada em assistente para construir e treinar seu modelo. Isto desbloqueia o poder do Azure Machine Learning e serviços Cognitivos sem escrever uma única linha de código ou criar modelos complexos de aprendizagem de máquinas.

Um componente de IA pronto para uso é o leitor de cartões de visita. Este componente revisa uma foto ou foto tirada para determinar se é um cartão de visita e posteriormente extrai as informações relevantes. Não é necessária nenhuma configuração.

O leitor de cartão de visita é simplesmente um exemplo pronto que se baseia nos componentes de IA subjacentes que você pode implantar de outras maneiras, construindo primeiro um modelo. A partir do site https://make.PowerApps.com, um assistente o orienta na construção e treinamento do modelo. Atualmente, há quatro modelos de IA disponíveis em Power Apps:

Previsão - Este modelo prevê se algo vai acontecer ou não com base no histórico de dados anteriores. Mais detalhes na seção seguinte.

Processador de formulários - Este modelo extrai texto de uma imagem como o leitor de cartões de visita.

Detector de objetos - Este modelo identifica objetos de uma imagem carregada ou fotografada e depois fornece uma contagem do número de objetos presentes.

Classificação de texto - Este modelo categoriza o texto por seu significado, tornando mais fácil a análise.

**Comment by rmororo** [comment]
O modelo de previsão
O modelo de previsão AI Builder permite criar um modelo que pode prever resultados de sim ou não com base em dados históricos. Você treina o modelo fornecendo dados históricos que incluem o resultado sim ou não e então a inteligência artificial faz o resto.

Você pode construir modelos de previsão para resolver problemas comerciais, como por exemplo:

Será que uma liderança se tornará um cliente?

Um projeto será lucrativo?

A rotatividade de um cliente será baseada na atividade?

Como você pode ver, a IA pode ajudá-lo a responder perguntas comerciais poderosas sem escrever uma única linha de código.

**Comment by rmororo** [comment]
Segurança e Administração
Há muitas ferramentas para os que estão na TI ou são responsáveis pela governança. O Power Apps tem uma infinidade de recursos de segurança, governança e relatórios para permitir que você gerencie o Power Apps. Além disso, as Power Apps não contornam a segurança de forma alguma. Os usuários não podem criar aplicativos para contornar as permissões de acesso atuais. Para gerenciar a segurança para Power Apps, você pode acessar https://admin.powerplatform.microsoft.com/. Aqui você encontrará opções para criar e gerenciar ambientes, monitorar licenças, trabalhar com políticas de prevenção contra perda de dados e gerenciar projetos de integração de dados. Isto permite que você gerencie as Power Apps em todo o seu locatário a partir de um único lugar.

Power Apps também tem seu próprio conjunto de PowerShell cmdlets para criadores, administradores e desenvolvedores de aplicativos que lhe permitem automatizar muitas de suas tarefas administrativas. Um caso de uso comum dos PowerShell cmdlets é automatizar a descoberta e o gerenciamento de permissões de todos os aplicativos em seu inquilino, permitindo que você compreenda e gerencie melhor os aplicativos à medida que eles são criados e espalhados por toda a sua empresa.

Além disso, no módulo de aprendizagem Power Automate, você verá que o Power Automate tem a capacidade de automatizar estas tarefas. Você pode baixar o kit inicial do Centro de Excelência, uma coleção de componentes ou ferramentas que são projetados para ajudar a começar a desenvolver uma estratégia para adotar e apoiar a Plataforma Power, com foco em Power Apps e Power Automate.

**Comment by rmororo** [comment]
Impulsionando o valor comercial
Agora você entende que o Power Apps não requer o "código" tradicional como o C#, fazendo uma barreira de baixa tecnologia para a entrada. Se você conhece seu processo comercial, você pode começar a escrever seu primeiro aplicativo. Para muitas empresas, isto significa que os aplicativos não vêm de TI, mas diretamente dos usuários comerciais da linha de frente. Da mesma forma que a Finance constrói hoje suas próprias pastas de trabalho em Excel, eles podem construir seus próprios aplicativos Power.

Power Apps permite até mesmo aos usuários de nível básico reduzir a burocracia, aumentar a eficiência do processo e garantir uma única fonte de verdade através da combinação de várias fontes de dados em um único aplicativo. Os usuários podem construir aplicativos com facilidade, enquanto permanecem dentro dos guardrails definidos pela TI. Isto permite uma quantidade sem precedentes de inovação e digitalização, eliminando o acúmulo de aplicativos, processos complicados baseados em papel e muito mais.

**Comment by rmororo** [comment]
Power Apps em ação

Agora que você tem uma visão geral das Power Apps e como o Aeroporto Heathrow alavancou esta poderosa aplicação, este vídeo o ajudará a começar. O vídeo mostra um aplicativo de exemplo e depois mostra como criar seu primeiro aplicativo a partir de seus dados existentes ou de um modelo.

https://docs.microsoft.com/en-us/learn/modules/introduction-power-apps/4-power-apps-action

**Comment by Kamilusek2** [comment]
All access
