### ISSUE TITLE
Technet blog link is broken

### ISSUE THREAD

**Issue by deaddepa** [MicrosoftDocs/powerapps-docs#1972]
The TechNet blog link at the bottom of the page is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28ee5be-b508-7de2-f4b0-8da563f35a3a
* Version Independent ID: d8fefdf1-e29e-0c51-a80e-3449271630fd
* Content: [Use the Virtual table OData v4 Data Provider with Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/virtual-entity-odata-provider-requirements)
* Content Source: [powerapps-docs/maker/common-data-service/virtual-entity-odata-provider-requirements.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/virtual-entity-odata-provider-requirements.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Thank you for bringing this to our attention. Unfortunately, the TechNet blog site has been archived and the post has been removed. The link has been removed from the article. 

Closing issue.
