### ISSUE TITLE
Update Form designer screenshot

### ISSUE THREAD

**Issue by aecarr2** [MicrosoftDocs/powerapps-docs#1975]
Screenshot needs to be updated to reflect "Field", etc. terminology changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e57bedc-b88b-e428-613d-72fd8184df32
* Version Independent ID: 0b66fa51-c3de-612d-de15-c17b249b0c77
* Content: [Overview of the model-driven app form designer - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/form-designer-overview)
* Content Source: [powerapps-docs/maker/model-driven-apps/form-designer-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/form-designer-overview.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@aecarr2 - thank you for your feedback. The screenshot has been updated to reflect the current UI and terminology. It will be published live in a few hours. Closing issue.
