### ISSUE TITLE
Theme Options

### ISSUE THREAD

**Issue by jpatrickwright** [MicrosoftDocs/powerapps-docs#1976]
The current theme options do not include a "Global Link Color" as shown in the Gentle Green Theme screenshot. We desperately need this option to achieve our branding objective. The system currently forces us to see the light blue link color.

Please advise on the ability to change the global link color or update the screenshot. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bfa2c4e-b1d4-972e-56f7-250bbeeda910
* Version Independent ID: f7f5c4fc-a9f7-9917-4e24-7f878655cb13
* Content: [Change the color scheme or add a logo to match your brand - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-themes-organization-branding#custom-theme-considerations)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-themes-organization-branding.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/create-themes-organization-branding.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@jpatrickwright - thank you for your feedback. You're correct that the global link color option isn't available with the current themes implementation. The topic has been updated and expanded a bit to provide more detail about how themes work in general (e.g. logo size, use, and that the logo is a web resource). The topic will be published live later today. 

Closing issue.
