### ISSUE TITLE
Incorrect steps to set Text for label - 2162494

### ISSUE THREAD

**Issue by manikandan76** [MicrosoftDocs/powerapps-docs#1977]
I am an absolute beginner for Power App and this is the first tutorial for me.

This step is misleading and took me a hour to figure out the correct way of doing.

> Add a Label control, set its Text property to Total, and then press F5.

It should be "Add a Label control, set Value(Total)  in the formula bar and then press F5
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1567d77-110a-348b-614d-60016845cafd
* Version Independent ID: 0bc34ed1-625f-f681-dcd3-5922d3e62ca8
* Content: [Button control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-button)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-button.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-button.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. Content has been updated. Please allow some time to reflect the changes.
