### ISSUE TITLE
; instead of , in the formula

### ISSUE THREAD

**Issue by SurBerg** [MicrosoftDocs/powerapps-docs#1978]
; instead of, - worked out for me:
If( Value(Text1.Text) < 20; "Viel mehr bestellen!"; Value(Text1.Text) < 40; "Mehr bestellen!"; Text1.Text )

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8161ff43-b9c9-b13d-4401-c0d31e158472
* Version Independent ID: c80fce1d-4a0b-8709-d151-cb54fbbd3c3e
* Content: [Funktionen „If“ und „Switch“ - Power Apps](https://docs.microsoft.com/de-de/powerapps/maker/canvas-apps/functions/function-if)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-if.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-if.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@SurBerg Thanks for contacting us. Based on the authoring language you need to use the separators differently. Please see the document https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/global-apps#formula-separators-and-chaining-operator to know more about when to use different separators. Closing the issue.
