### ISSUE TITLE
More restricted entities?

### ISSUE THREAD

**Issue by Ausnik** [MicrosoftDocs/powerapps-docs#198]
I have seen conversations suggesting there are other restricted entities - such as Product Catalog entities. Is the above a complete list?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted entities requiring Dynamics 365 licenses - PowerApps](https://docs.microsoft.com/en-au/powerapps/maker/common-data-service/data-platform-restricted-entities)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by KumarVivek** [comment]
@Ausnik This article should have the latedt information now; closing the issue.
