### ISSUE TITLE
suggested addition to step 8

### ISSUE THREAD

**Issue by hems-qmrkt** [MicrosoftDocs/powerapps-docs#1980]
[Enter feedback here]
Step 8 requires an additional step ... 

"8. To display the paper tape, insert a Data table control, and set its Items property to this formula:

PaperTape

In the right-hand pane, select the Value column to show it." 

my suggestion to edit the final line "In the right-hand pane, select the Value column to show it" 

and change it to ... 

"In the right-hand pane, select Edit fields next to the fields property, click on the + Add fields and then select the value checkbox"

or something to this effect. 

This missing step stumped me for a while, but I figured it out in the end. I think others would appreciate this change as they might be confused like I was. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f93a150-c9c8-9795-60ea-5888ae895e50
* Version Independent ID: 905345c4-35e1-d37f-12b3-3881f00591e0
* Content: [Understand variables in canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-variables)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-variables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-variables.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@hems-qmrkt Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
