### ISSUE TITLE
Flows that connect to SharePoint do work

### ISSUE THREAD

**Issue by janwillemkeizer** [MicrosoftDocs/powerapps-docs#1982]
[Enter feedback here]

Under [Know Limitations](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview#known-limitations) there's this bullit:

- Flows that connect to SharePoint are not available in solutions.

However it's my experience that these flows work in our environment. **What do you exactly mean by 'not available'?**
We made flows that connect to SharePoint and we moved them into a solution. Combined with a canvas app the flow do give output back to the canvas app. They are however slow - but we thought that was related to our flow design and underlying data model expressed by SharePoint Lists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a7715a-2b1b-29ed-99ac-0003429d5b4d
* Version Independent ID: be31d36c-9be0-cc62-1ea3-b8514fe569d9
* Content: [Solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview)
* Content Source: [powerapps-docs/maker/common-data-service/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/solutions-overview.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@janwillemkeizer - It appears Power Automate flows that connect to SharePoint are now supported to add to a solution. The line item has been removed from the article. 
Closing issue.
