### ISSUE TITLE
The Letter Subtitle is Wrong

### ISSUE THREAD

**Issue by alvaro-cmd** [MicrosoftDocs/powerapps-docs#1983]
![image](https://user-images.githubusercontent.com/63261454/101200364-f457c180-3644-11eb-89a2-2340481a6e57.png)

The letter M was wrongly replaced by letter s in the Brazilian documentation.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2ed900e9-0ac8-8914-2bee-b04e4ebd725d
* Version Independent ID: 0ef1f99f-00f3-8344-9bd7-6cbfd96a789a
* Content: [Funções, sinais e enumerações - Power Apps](https://docs.microsoft.com/pt-br/powerapps/maker/canvas-apps/formula-reference)
* Content Source: [powerapps-docs/maker/canvas-apps/formula-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/formula-reference.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@mhogan73 Can you look into this issue. This is a localization bug.

**Comment by mhogan73** [comment]
@jowilco assigning to you as this is PowerApps

**Comment by jowilco** [comment]
@alvaro-cmd Obrigado pelos seus comentários. Estamos investigando este problema.

**Comment by jowilco** [comment]
@alvaro-cmd Atualizamos e ativamos as traduções. Fechando o problema. Obrigado pelos seus comentários.
