### ISSUE TITLE
Invalid Hyperlink of "Environment and tenant app migration" - 2162507

### ISSUE THREAD

**Issue by dantclee** [MicrosoftDocs/powerapps-docs#1986]
The hyperlink to the page "Environment and tenant app migration" is invalid.  Please replace the link.  URL of the problematic page is as follows:

https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ec6689-7baa-94ad-65b2-a7635daf277e
* Version Independent ID: f076de06-b509-f686-f334-18891a1a6cda
* Content: [Power Apps Community Plan -- a free development environment for individual use - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Link has been fixed, please allow some time to reflect the changes.
