### ISSUE TITLE
power apps geolocation¨

### ISSUE THREAD

**Issue by matsilarsson** [MicrosoftDocs/powerapps-docs#1987]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68490e51-ae25-ff32-0dd7-9eaf1f5f81d5
* Version Independent ID: 7389a5be-5e77-7238-7eaa-13380ce3908a
* Content: [Acceleration, App, Compass, Connection, and Location signals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/signals)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/signals.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/signals.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@matsilarsson Can you let us know what issue are you actually facing.

**Comment by matsilarsson** [comment]
Sorry guys, I enter that by mistake...
