### ISSUE TITLE
Set API doesn't work for PowerApps portals

### ISSUE THREAD

**Issue by si-chan** [MicrosoftDocs/powerapps-docs#1988]
References doc page: 
https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad

Hi

We've worked through the steps again and step 6(l) says "enter the portal URL as the App ID URI".
This will not work, since the portal URL is normally "xxx.powerappsportals.com/yyy" and the App ID URI must be a registered domain in the Azure AD tenant.
In a default Azure AD tenant, the only registered domain is xxx.onmicrosoft.com, so this should be used instead.

Si

_Originally posted by @si-chan in https://github.com/MicrosoftDocs/powerapps-docs/issues/1905#issuecomment-740884886_

**Comment by tapanm-MSFT** [comment]
Please work with the support teams by creating a [support ticket](https://admin.powerplatform.microsoft.com/support) to investigate this issue as mentioned in https://github.com/MicrosoftDocs/powerapps-docs/issues/1905.

**Comment by si-chan** [comment]
Hi

This isn’t a support issue, it’s a documentation issue.
The documentation is misleading in my view and should be corrected.
I note this is the second similar issue you’ve closed on this – perhaps you’d care to engage in further discussion before you close documentation issues?

Si

**Comment by tapanm-MSFT** [comment]
Hello, this has been discussed and reproduced to ensure the documentation accuracy. Internal discussions are not published on public forums such as GitHub issues. Hence, the request to reach out to the support teams. Documentation team doesn't support investigating incidents. As for the 2nd issue, I see both were raised by you. Are there any challenges reaching out to the support team for additional help with the investigation?

**Comment by si-chan** [comment]
Hi

We did raise a Premier case, however upon reviewing the settings, per our findings, the document was not accurate as it is impossible to use a Microsoft-owned domain as an App Identifier URL.

Si

**Comment by tapanm-MSFT** [comment]
Please share the support ticket #
