### ISSUE TITLE
Topic not in TOC

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1990]
This page isn't in the TOC.
please fix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee3ddaad-20dd-34b3-5076-5a5190e5159c
* Version Independent ID: 6ae6edce-4c45-a0f0-b8f7-aaf6ff76efb0
* Content: [Use XRM tooling to execute actions in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-xrm-tooling-to-execute-web-request)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-xrm-tooling-to-execute-web-request.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-xrm-tooling-to-execute-web-request.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@JimDaly  Added the file in the TOC and pushed it live. Changes will be reflected after 6 PM PST. Closing the issue.
