### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by Jgroenouwe** [MicrosoftDocs/powerapps-docs#1991]
Unfortionetly it does not work. the new version of Edge neets [*.] instead of *. in the address. but the https://make.*.microsoft.com I cannot convert to https://make.[*.]microsoft.com. Edge does not accept this one.
how do i add these to Edge?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c6de7fca-d66b-479c-1570-676ebafa1b78
* Version Independent ID: 70b75562-e755-31cd-c7fd-ef87983698f5
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/nl-nl/powerapps/troubleshooting-startup-issues#enable-storage-of-third-party-cookies-and-local-data-in-your-browser)
* Content Source: [powerapps-docs/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You just have to add `[*.]powerapps.com`. Rest are the URLs as listed that should be removed.
