### ISSUE TITLE
Text Properties Not Available in Teams PowerApps

### ISSUE THREAD

**Issue by csteelatgburg** [MicrosoftDocs/powerapps-docs#1992]
When creating apps in the Teams PowerApps app, some of the text properties are not available for the label control. These include Italic, Strikethrough and Underline. This may be an issue with the Teams app and not PowerApps in general.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0aed73-6f92-6bba-f21f-103242514e87
* Version Independent ID: ec6c4452-0541-0afb-cf96-4bcb6c3d99ff
* Content: [Label control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-text-box)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-text-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-text-box.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there,

This was by design.  We'll be adding more style properties to the Fluent UI versions of controls in the near future. Sorry for any inconvenience.

Cheers,
CM

**Comment by samirelassal** [comment]
Why has this issue been closed? Nearly two years passed and those properties are still not available in the Teams version of Power Apps.

**Comment by chmoncay** [comment]
Hi there, I'm in the teams version and I see those properties.

![image](https://user-images.githubusercontent.com/22963239/195616428-71d9fca2-d3d2-44d8-872c-6cab4a3d02b0.png)

Here is a close up

![image](https://user-images.githubusercontent.com/22963239/195616514-22388864-c0ec-40a2-911d-c7d9ed285298.png)

Please advise.
