### ISSUE TITLE
Updating existing reports

### ISSUE THREAD

**Issue by davecope1982** [MicrosoftDocs/powerapps-docs#1997]
Will there be a mechanism for updating existing reports using the import data connector to now use the new direct query connector without the need to rebuild the pbix from scratch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d27f9-66bc-5cd2-d8b5-9defc8eddfb0
* Version Independent ID: c45841f0-1488-8c30-8a7c-3a522ec63266
* Content: [View table data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi)
* Content Source: [powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@davecope1982 - Thanks for your feedback. For product-related feedback and suggestions, visit https://ideas.powerapps.com. 

Closing this issue.
