### ISSUE TITLE
Missing Template

### ISSUE THREAD

**Issue by Mike-EEE** [MicrosoftDocs/powerapps-docs#2]
Hello there,

Looks like there is some missing content here:
https://docs.microsoft.com/en-us/common-data-service/entity-reference/cds-sdk-azure-functions-get-started

It references a template that is no longer found in Azure Functions, so users cannot test out the example solution as prescribed.  It would be more than appreciated to get this documentation updated and pointed in the right direction and start using your product as designed/intended.

Thank you for any assistance and consideration!

**Comment by JasonWHowell** [comment]
@AFTOwen you might not have seen this issue yet. FYI

**Comment by AFTOwen** [comment]
Thanks, @JasonWHowell: I have, in fact, seen this. It refers to a topic in a completely different repo, which @KumarVivek owns. I notified him of this issue in mail.

**Comment by AFTOwen** [comment]
Thanks, @Mike-EEE! I've copied your comment to the topic that you reference, which another team manages from another repo. @KumarVivek should address this. Cheers!
