### ISSUE TITLE
Delegation of 'StartsWith' for SP

### ISSUE THREAD

**Issue by abbygaylejavier** [MicrosoftDocs/powerapps-docs#200]
I've created a gallery that has the following filter formula: Filter(DataSource, StartsWith(ColumnName, Input.Text)).

I've tested it on a List and it's working fine. But when I changed my DataSource to a document library, it doesn't seem to work

According to the above documentation, Filter function and StartsWith predicate is delegable for SharePoint. 

Is it just applicable to a list and not a document library? 

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f7e4f2-fe68-0e4b-9cfd-a303abaa0fd6
* Version Independent ID: f0708033-e29d-5321-0da0-e2c1c2130008
* Content: [Delegable data sources in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-list)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by AFTOwen** [comment]
Thanks, @abbygaylejavier! Per the [known limitations](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-sharepoint-online#known-issues), custom lists are supported in SharePoint but not libraries.
