### ISSUE TITLE
OCM is retired. 2162531

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/powerapps-docs#2004]
Outlook customer manager was retired July 1, 2020.  Please remove this reference to it in this article.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c12582-519a-606c-1f2e-8fe1f6ac5d2a
* Version Independent ID: 537b3097-4aa4-f3e5-b252-ffb832ecb1dc
* Content: [Share a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @alaug
* Microsoft Alias: **alaug**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated.
