### ISSUE TITLE
No mention in the doumentation what licences you need

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#2007]
Article in docs.microsoft.com does not detail what licences you need.  Am I right in assuming you  need a Per App or PerUser PowerApps Licence and you need to licence PowerPortal as well.  Is there anything else that needs a licence ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47c1b746-5757-5988-e5d2-d876c8a221d5
* Version Independent ID: 85b048a1-6985-6a20-bd42-d6ece4d88349
* Content: [Deploy the Return to Workplace solution - Power Apps](https://docs.microsoft.com/en-gb/powerapps/sample-apps/return-to-workplace/deploy#prerequisites)
* Content Source: [powerapps-docs/sample-apps/return-to-workplace/deploy.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/sample-apps/return-to-workplace/deploy.md)
* Service: **powerapps**
* GitHub Login: @wbakker-11
* Microsoft Alias: **garybird**

**Comment by wbakker-11** [comment]
Hey @NPrice99,

You are correct in assuming you need a Per App / Per User license and, depending if you install the portal piece as well, you need licenses for that. You can find these details as well in the licensing requirements on the overview page. (https://docs.microsoft.com/en-us/powerapps/sample-apps/return-to-workplace/overview#licensing-requirements)

Kind regards,
William

**Comment by iangpgh** [comment]
Response provided, customer directed to doc that answers their question
