### ISSUE TITLE
Why do class fields/properties violate thread-safety?

### ISSUE THREAD

**Issue by Martype** [MicrosoftDocs/powerapps-docs#2009]
I understand that it is not a good approach to assign class fields/properties within the constructor of an IPlugin implentation and later make use of these fields/properties during the Execute-method, but why is it also a thread-safety violation when these fields/properties are set within the Execute-method?
In the example at the end of "Execute" the method "AccessViolationProperties" is called, but no other threads were created since the beginning of "Execute". I don't see where the thread-violation is coming from.

We created PluginBase and CodeActivityBase classes to reduce the amount of non-business-logic code inside our implementations of IPlugin and CodeActivity. Therefore our base classes provides multiple class fields such as PrimaryEntityId, a default IOrganizationService instance, a tracer and so on. This appeared to be a good/clean approach since we reduce the amount of copied code. We never experienced issues with this approach so far, but of course potential thread-safety issues makes me nervous.

Would you please explain in detail, why such thread-safety issues may occur and what code design should be chosen to reduce copied code without having thread-safety issues? In a previous version of our base classes we had a context class which provided all the fields/properties we commonly use. The context got created/set during the Execute method of the base class and then was passed to an abstract method "Run", which had to be implented in derived classes of PluginBase and CodeActivityBase. 
Simply calling "Service.Retrieve" is just a little more comfortable than calling "context.Service.Retrieve", so we got rid of the context class and put those fields directly into the base classes. I consider bringing back the context class, but before doing so I'd like to get a confirmation that there really are potential thread-safety issues when setting class fields/properties during the Execute-method. Please explain how such issues can occur.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7c1e71b1-7a82-b4b8-27ad-d1bbb78e3814
* Version Independent ID: 7c28f677-aba1-bd0d-173e-eaf187bf32e9
* Content: [Entwicklung von IPlugin-Implementierungen als zustandslos - Power Apps](https://docs.microsoft.com/de-de/powerapps/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by fowl2** [comment]
The `Execute()` method can be called multiple times simultaneously on a single instance. 

The article now contains an "Additional information" section that contains:

> Because the platform caches plug-in class instances, the constructor is not called for every invocation of plug-in execution. For this reason, IPlugin implementations should not depend on the timing of operations in the constructor apart from obtaining static configuration data.
> 
> Another reason IPlugins should be stateless is that multiple system threads could execute the same, shared, plug-in instance concurrently.

**Comment by phecke** [comment]
@Martype You may want to look at [Develop IPlugin implementations as stateless](https://docs.microsoft.com/power-apps/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless).
