### ISSUE TITLE
Questions regarding Community Plan environments 2162540

### ISSUE THREAD

**Issue by davenull311** [MicrosoftDocs/powerapps-docs#2012]
A few questions come to mind regarding the Community Plan environments:
- Since the environment does fall under my work/school tenant, does it have any effect on the service limits of that tenant? 
- Is there any limit to the number of people in my company that can create an individual environment under this tenant? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ec6689-7baa-94ad-65b2-a7635daf277e
* Version Independent ID: f076de06-b509-f686-f334-18891a1a6cda
* Content: [Power Apps Community Plan -- a free development environment for individual use - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by davenull311** [comment]
Hi, I just wanted to reconnect on this and see if I could get these questions answered. Thanks!

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Apologies for the delay. 
- Dev Community Plan does not affect shared caps or throttle limits of other production environments in a tenant. However, if you have any issues or experience problems, please reach out through [Get Help + Support](https://docs.microsoft.com/power-platform/admin/get-help-support) for an investigation.
- Dev Community Plan is solely for individual use (free development environment for individual use). Anyone with a work or school account can sign up for the Power Apps Community Plan as documented.
