### ISSUE TITLE
Formulas for dynamic layout  2162574 

### ISSUE THREAD

**Issue by mehmoodq** [MicrosoftDocs/powerapps-docs#2015]
The last formula is incorrect. Instead of Height being set to Parent.Height - D.Y, it should be Parent.Height - C.Y. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed. Please allow some time to reflect the changes.
