### ISSUE TITLE
Video not available 2162652

### ISSUE THREAD

**Issue by jahsmurf** [MicrosoftDocs/powerapps-docs#2017]
The embedded video on this page is set to private. I cannot open it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c20ac47d-bc64-6fe0-ce72-cadd90813776
* Version Independent ID: 2237e644-21d7-07a1-eabd-d48866688ad8
* Content: [Publish your app on AppSource (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/publish-app-appsource)
* Content Source: [powerapps-docs/developer/data-platform/publish-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/publish-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by pratapladhani** [comment]
I noticed this today as well - the link https://youtu.be/hpq_Y9LuIB8 opens up YouTube with a "Video unavailable, video is private" error. It looks like the permissions on the video in YouTube aren't set correctly

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Link has been corrected. Please allow some time to reflect the changes.
