### ISSUE TITLE
Edge Option#2 Instructions do not work

### ISSUE THREAD

**Issue by drewski3420** [MicrosoftDocs/powerapps-docs#2018]
The instructions provided for Edge option # 2 do not work. The instructions are listed here:

>1. Go to Power Apps.
>2. Select the cookie icon in the top-right corner of the address bar.
>3. Select Site not working?.
>4. Select Allow cookies.

However, when third party cookies are blocked (which is the issue I am facing and trying to resolve with these instructions), the cookie icon in the address bar referenced in step 2 does not appear. The site is redirected to the error page and the cookie icon is not there.

The only way I am able to resolve this issue is to enable third party cookies. The instructions should be updated to reflect this, or correct steps in Option # 2 should be provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de7fca-d66b-479c-1570-676ebafa1b78
* Version Independent ID: 70b75562-e755-31cd-c7fd-ef87983698f5
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues)
* Content Source: [powerapps-docs/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been updated.
