### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by d7235j** [MicrosoftDocs/powerapps-docs#2019]
Link on this page to entity data reference returns 404 page not found error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b903798-2033-be36-079a-babe7586981e
* Version Independent ID: d588611a-a950-134e-6738-10e8f3899f25
* Content: [Tables and metadata in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-edit-metadata)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/create-edit-metadata.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@d7235j - The link has been fixed and and will be live by within the next 2-3 hours. Thank you for helping improve the documentation! Closing issue.
