### ISSUE TITLE
Unable to get the Approver Field to work

### ISSUE THREAD

**Issue by ababinchak** [MicrosoftDocs/powerapps-docs#202]
The approver field on the New Expense page does not populate at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @mr-dang-msft
* Microsoft Alias: **brdang**

**Comment by AFTOwen** [comment]
@ababinchak Thanks for your feedback, which is outside the scope of this documentation. Please post troubleshooting questions about the app itself in [the forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.” 

cc: @mr-dang-msft
