### ISSUE TITLE
Please Update - Deprecated Functions

### ISSUE THREAD

**Issue by pfuegy** [MicrosoftDocs/powerapps-docs#2020]
This is an excellent example, but it is significantly dated.
Many of the functions you call out have been deprecated and updated and simply changing them to the updated version creates significant issues throughout the example that must be repaired.

> (i.e. Office365.CalendarGetTables().value is now Office365Outlook.CalendarGetTablesV2().value)

I believe the entire community would appreciate an update to this thread.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9451acad-432a-1f11-8204-238de8655846
* Version Independent ID: 16134a5a-2880-4221-32b9-256f0573620b
* Content: [Calendar-screen template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/screen-templates/calendar-screen-overview#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been added to the pipeline for updates. However, this may take some time, hence closing this feedback.
