### ISSUE TITLE
Fix a small typo

### ISSUE THREAD

**Issue by JoeriBlomberg** [MicrosoftDocs/powerapps-docs#2021]
Very small edit:
The content is described as 'Content: [Functional application **sonsultant** learning catalog - Power Apps](https://docs.microsoft.com/en-us/powerapps/learning-catalog/functional-consultant)

Feedback to fix the typo ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef6113b-1e15-8fe4-c6a9-f356f0424197
* Version Independent ID: 241b05ba-5fb1-5afe-884b-0bb20ce06bd5
* Content: [Functional application sonsultant learning catalog - Power Apps](https://docs.microsoft.com/en-us/powerapps/learning-catalog/functional-consultant)
* Content Source: [powerapps-docs/learning-catalog/functional-consultant.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/learning-catalog/functional-consultant.md)
* Service: **powerapps**
* GitHub Login: @loreleishannonmsft
* Microsoft Alias: **margoc**

**Comment by Nkrb** [comment]
@JoeriBlomberg Thanks for contacting us. We have fixed the typo issue and will be live by end of the day. Closing the issue.
