### ISSUE TITLE
Inaccurate functionality description of roles in userSettings

### ISSUE THREAD

**Issue by jodyfarnden** [MicrosoftDocs/powerapps-docs#2024]
For both the roles and securityRoles functions under userSettings the behaviour is described as:
"Returns ... each of the security role or teams that the user is associated with."
This is not an accurate description of the behaviour of these functions.
The return value is any security roles assigned to the user and any security roles assigned to a team the user is a member of. 
The team names are not returned, please consider revising the phrasing of these sections to better reflect the functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999537e5-d7fd-6e16-207a-b7c7c31fdc9e
* Version Independent ID: 48ac9b62-a8b5-3bab-11b5-c0bbc5fde88c
* Content: [getGlobalContext.userSettings (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@jodyfarnden Thanks for contacting us. We have updated the docs and published it live. Closing the issue. If you need further help, please reopen or create a new issue.
