### ISSUE TITLE
the example formula is invalid when used in an Compose step in Power Apps

### ISSUE THREAD

**Issue by donnay** [MicrosoftDocs/powerapps-docs#2025]
the example at the bottom of this page:

<pre>First( Split( Last( Split( "Bob Jones <bob.jones@contoso.com>", "<" ) ).Result, ">" ) ).Result</pre>

returns an error "The expression is invalid." when used within a Power (Flow) Compose operation. See below:

First(Split(Last(Split(triggerOutputs()?['body/body'],"dates(s) ")).Result," to")).Result

Thanks for your help!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dc17706-b063-fd81-634a-2db0a9d8988e
* Version Independent ID: 1ec42eef-5290-2a9c-d207-6e1dcf239472
* Content: [Split function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-split)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-split.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-split.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by donnay** [comment]
RESOLVED:

I replaced the double quotes with single and it works:
<pre>First(Split(Last(Split(triggerOutputs()?['body/body'],'dates(s) ') ).Result, ' to')).Result</pre>

**Comment by donnay** [comment]
CORRECTION: Upon running this Power Automation, I received the following error:

> Unable to process template language expressions in action 'FirstDateSTR' inputs at line '1' and column '29052': 'The template language expression 'First(Split(Last(Split(triggerOutputs()?['body/body'],'dates(s) ') ).Result, ' to')).Result' cannot be evaluated because property 'Result' cannot be selected. Property selection is not supported on values of type 'String'. Please see https://aka.ms/logicexpressions for usage details.'.

**Comment by Nkrb** [comment]
@donnay Looks like this is an Power Automate issue. Closing the issue. If you need further help, please reopen or create a new issue.
