### ISSUE TITLE
Update this documentation 2162665

### ISSUE THREAD

**Issue by makandmozart** [MicrosoftDocs/powerapps-docs#2026]
[Enter feedback here]
This topic is not updated, in Power Apps there is already an option to add a screen with a scrolling element as a template

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40bbed2-800e-a067-431f-ff9562718cb9
* Version Independent ID: cc8205a8-bab2-9bb8-745d-76243ed2989b
* Content: [Add a scrolling screen to a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-scrolling-screen)
* Content Source: [powerapps-docs/maker/canvas-apps/add-scrolling-screen.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-scrolling-screen.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been added to the pipeline for updates. However, this may take some time, hence closing this feedback.
