### ISSUE TITLE
Terrible

### ISSUE THREAD

**Issue by BrianLeFlem** [MicrosoftDocs/powerapps-docs#2031]
No link to the "Power Apps home page".  There are far too many Admin areas:

- Power Platform admin center
- Power Apps portals admin center
- Power Apps home page (wherever that is)
- Power Apps (https://make.powerapps.com/environments)
- Power Apps  |  Portal

It's just a complete and utter labyrinth to navigate.  Even the Help articles can't provide links to the right area.
Just such a mess :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83e291-fd19-f80b-f423-b2f701e5e279
* Version Independent ID: 85df9f5f-602f-af17-fda0-2b24b4627d53
* Content: [Overview of Portal Management app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-portal)
* Content Source: [powerapps-docs/maker/portals/configure/configure-portal.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/configure-portal.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated.
