### ISSUE TITLE
Storage Blob Data Reader

### ISSUE THREAD

**Issue by NickWarner** [MicrosoftDocs/powerapps-docs#2032]
It would have been helpful to know that the user needs to be a Storage Blob Data Reader.  I found out the hard way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1035def6-8f97-9b41-da38-66b3c7a653b9
* Version Independent ID: 4e9f789d-2b26-8cd7-7c3f-a76ded632dbc
* Content: [Analyze Microsoft Dataverse exported to Azure Data Lake Storage Gen2 data with Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake-data-powerbi)
* Content Source: [powerapps-docs/maker/data-platform/export-to-data-lake-data-powerbi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/export-to-data-lake-data-powerbi.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Closing issue.
