### ISSUE TITLE
Please add Login Regional settings to this page

### ISSUE THREAD

**Issue by melkinsco** [MicrosoftDocs/powerapps-docs#2033]
Please add the Login Region settings for troubleshooting mobile apps.  As a GCC customer, we looked all over until we found that info.  Apps wont appear in the mobile app unless the Region is set correctly before login.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de7fca-d66b-479c-1570-676ebafa1b78
* Version Independent ID: 70b75562-e755-31cd-c7fd-ef87983698f5
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues)
* Content Source: [powerapps-docs/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For help with troubleshooting mobile app issues, please refer to [Troubleshoot issues for the Power Apps mobile app](https://docs.microsoft.com/powerapps/user/powerapps_mobile_troubleshoot).
