### ISSUE TITLE
Missing licensing guidance or summary info.  Can there be at least a quick sentence on this? 

### ISSUE THREAD

**Issue by bigpix2000** [MicrosoftDocs/powerapps-docs#2034]
So although it was implied that dataverse through teams means no extra licensing issues, it is not clear and very vague and I am still getting resistance because nothing outright says that the license is the same unless of course they are correct and there is a surprise in that the people "external" to the team must now pay where in the past they simply had no access.    Can we be clear on this?  I promise to include it in the licensing guidance for power platform I am working on as well thanks!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55bd804a-9963-a92d-90f2-e0b4bc17b85a
* Version Independent ID: cd9a2dbb-e2a7-32ae-2cd4-ab81381f2366
* Content: [Publish and share your app using Power Apps app in Teams - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/publish-and-share-apps#share-broad-distribution-apps-with-colleagues)
* Content Source: [powerapps-docs/teams/publish-and-share-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/publish-and-share-apps.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Licensing information about Microsoft Dataverse for Teams is available at [Licensing requirements](https://docs.microsoft.com/powerapps/teams/create-apps-overview#licensing-requirements) that links to the more detailed [licensing restrictions](https://docs.microsoft.com/power-platform/admin/about-teams-environment#licensing-and-restrictions).
