### ISSUE TITLE
Old link

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#2036]
This topic has a link which goes here: https://technet.microsoft.com/library/3fa9c316-9dc9-4b28-9abf-43a3fce5b01d.aspx and it ends up being routed to https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/administering-dynamics-365/dn946903(v=crm.8)?redirectedfrom=MSDN

I think it needs to go to https://docs.microsoft.com/en-us/power-platform/admin/enable-change-tracking-control-data-synchronization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae183946-fb2a-1b2f-e199-273eb9a68d54
* Version Independent ID: 0cf78a90-f63b-af43-8075-c1cd4e934e7d
* Content: [Use change tracking to synchronize data with external systems (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-change-tracking-synchronize-data-external-systems)
* Content Source: [powerapps-docs/developer/data-platform/use-change-tracking-synchronize-data-external-systems.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/use-change-tracking-synchronize-data-external-systems.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@JimDaly  Link updated. Will be re-published later today. Thanks
