### ISSUE TITLE
How to use the exception feature in Plugin

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/powerapps-docs#2038]
The Request is greatly useful but how to enable the exception feature in Plugins ? In **Pre-Operation** stage the parameter `("SuppressDuplicateDetection", false); `is already present but however it is giving a pop-up window for user to suppress the duplicates _(instead of throwing error)_ and save which is OOB feature , but we want the system to throw an error and disallow user to save the record.

How to do the same ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df01da7c-aa94-09ea-9658-3b0014b29a00
* Version Independent ID: 7ab32499-5891-4375-691b-20306b10e6cf
* Content: [Detect duplicate data using the Organization service (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/detect-duplicate-data)
* Content Source: [powerapps-docs/developer/data-platform/org-service/detect-duplicate-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/org-service/detect-duplicate-data.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@pavansarma93 See the plug-in documentation [Handle exceptions in plug-ins](https://learn.microsoft.com/power-apps/developer/data-platform/handle-exceptions)
