### ISSUE TITLE
Proposal of japanese translation, キャンバス アプリでコレクションを作成および更新する 

### ISSUE THREAD

**Issue by sinya77** [MicrosoftDocs/powerapps-docs#2041]
[フィードバックをこちらに入力してください]

以下の翻訳を提案します。

`Rename the Drop down control Colors, `

**ドロップ ダウン** コントロールの**色**の名前を変更し、
**ドロップ ダウン** コントロールの名前を**色**に変更し、

`Add a Button control, set its Text property to "Add"`

**Button** コントロールを追加し、**Text** プロパティを**追加**し

**Button** コントロールを追加し、**Text** プロパティを**追加**に設定し

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f4c8e6a8-4599-e7fe-a4ea-77f20f1fe8f6
* Version Independent ID: ea22047a-d307-21f7-4fce-3f0407f22c24
* Content: [キャンバス アプリでコレクションを作成および更新する - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/create-update-collection)
* Content Source: [powerapps-docs/maker/canvas-apps/create-update-collection.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-update-collection.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by jowilco** [comment]
@sinya77 フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@sinya77 フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
