### ISSUE TITLE
Error - invalid object dbo.FilteredAccountTDS

### ISSUE THREAD

**Issue by Sudheerreddyn14** [MicrosoftDocs/powerapps-docs#2043]
[Enter feedback here]

Getting below error. can you please check.

![image](https://user-images.githubusercontent.com/37790033/104345170-0bcb7980-5524-11eb-9351-4d5d9fe6a998.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6c0eba-9fac-85d1-e9d3-98b9df013b60
* Version Independent ID: 44f4fe02-eb04-0927-4b13-61a9c1ee8fef
* Content: [View table data in Power BI Desktop - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/view-entity-data-power-bi#view-table-data)
* Content Source: [powerapps-docs/maker/data-platform/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Sudheerreddyn14 - Thanks for contacting us. Unfortunately, we're unable to handle Microsoft Support requests for the product here. To contact Microsoft Support, see here: https://powerapps.microsoft.com/support/ 

Closing this issue.
