### ISSUE TITLE
No roles property for userSettings in Microsoft Dynamics 365 on-premise version 1612 (9.0.20.7)

### ISSUE THREAD

**Issue by anilTeke** [MicrosoftDocs/powerapps-docs#2044]
In a Microsoft Dynamics 365 on-premise version 1612 (9.0.20.7 and also 9.0.22.8), user settings can be fetched by the below statement but do not have roles property that is mentioned on the content.
- `var userSettings = Xrm.Utility.getGlobalContext().userSettings` 

The below articles does not mention any fix about it.
- [Service Update 0.23 for Microsoft Dynamics 365 9.0](https://support.microsoft.com/en-us/help/4595459)
- [Service Update 0.24 for Microsoft Dynamics 365 9.0](https://support.microsoft.com/en-us/help/4595460)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999537e5-d7fd-6e16-207a-b7c7c31fdc9e
* Version Independent ID: 48ac9b62-a8b5-3bab-11b5-c0bbc5fde88c
* Content: [getGlobalContext.userSettings (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@anilTeke Thanks for contacting us. For on-premises environments we need to use **Xrm.Utility.getGlobalContext().userSettings.securityRoles** method. We are in process of updating the client API docs for both on-premises and online versions. Closing the issue. IF you need further help, please reopen or create a new issue.
