### ISSUE TITLE
Delegable Column Types would be beneficial to cover - 2228818

### ISSUE THREAD

**Issue by ericthomas1** [MicrosoftDocs/powerapps-docs#2046]
PowerApps delegation is probably one of the toughest things to comprehend and work around. I've been using the toolset for more than 3 years and still get hung up and have to refer to the docs. 

The "Delegable Functions" (StartsWith(), Filter(), etc.) are covered pretty well in this article as are "Delegable Data Sources"(Sharepoint, SQL, etc.). 

**What I find missing is an explanation on Data Source column-types (data types).** 

**Example**: 
- Using a TEXT COLUMN (NVARCHAR(), VARCHAR(), etc.) with the StartsWith() function or 
- Using a NUMERIC COLUMN (DECIMAL(), etc.) with the < and >= operators
- Cannot use a DATE COLUMN with StartsWith(), etc
- The Sharepoint ID column is not a delegable numeric column
- Can't use Sharepoint Calculate Columns, even if they are numeric

This article hasn't been updated in a couple years. Would be nice to expand the Examples section to show some work arounds.

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad97e638-1f17-ffb2-452f-8073a2bffa63
* Version Independent ID: 7ade66f5-aab6-0627-6d3b-914006718930
* Content: [Understand delegation in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-overview.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Delegable functions and operations are connector-specific, and you can refer to the connector documentation for such specific details.

- [Power Apps delegable functions and operations for SharePoint](https://docs.microsoft.com/connectors/sharepointonline/#power-apps-delegable-functions-and-operations-for-sharepoint)
- [Power Apps delegable functions and operations for the CDS for Apps](https://docs.microsoft.com/connectors/commondataservice/#power-apps-delegable-functions-and-operations-for-the-cds-for-apps)
- [Power Apps delegable functions and operations for SQL Server](https://docs.microsoft.com/connectors/sql/#power-apps-delegable-functions-and-operations-for-sql-server)

The delegation documentation mentions connector documentation as a reference for such details.
