### ISSUE TITLE
Point of clarifications for GCC to Commercial Guest Users 2162683

### ISSUE THREAD

**Issue by yashpatel22** [MicrosoftDocs/powerapps-docs#2051]
[Enter feedback here]

CHANGE REQUESTED no. 1:
 Note

Power Apps Per App Plans are scoped to apps in a specific environment, so they cannot be recognized across tenants. **_Power Apps included with Office and Power Apps Per User Plans are not bound to a specific environment so they are recognized across tenants in guest scenarios._**

We need to clarify in this document that this is not the case for Government to Commercial. When a government customer creates a Guest user, they must provision licenses for the guest user from the Government tenant. The Guest user's home tenant's licenses are not recognized by the GCC tenant. 

CHANGE REQUESTED no. 2:
 Note

Guests may only be assigned the User role, and not the Co-owner role, for apps shared with them.
Power Apps canvas app guest access leverages Azure B2B. **_Power Apps recognizes guests outlined by states 1 – 4 in the Azure B2B documentation._** Power Apps can't recognize guests that authenticate using Azure AD direct federation or Email one-time passcode authentication.

In the case of GCC guest users, Stage 2 is not a supported scenario for Mobile apps. When using the Power Apps mobile app, @gmail.com @outlook.com, @msn.com accounts are not supported. This is a very important clarification that needs to be included as a part of this document. 

Please contact yapatel@microsoft.com if you need clarity behind these requested changes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c12582-519a-606c-1f2e-8fe1f6ac5d2a
* Version Independent ID: 537b3097-4aa4-f3e5-b252-ffb832ecb1dc
* Content: [Share a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @alaug
* Microsoft Alias: **alaug**

**Comment by tapanm-MSFT** [comment]
Closing for internal discussions.
