### ISSUE TITLE
Incorrect example of the syntax

### ISSUE THREAD

**Issue by alexdionisio** [MicrosoftDocs/powerapps-docs#2057]
[Enter feedback here]

Syntax is incorrect. The transparency rate uses a comma to the point inconvenience. Example, RGBA (0, 18, 107, 0.8) is incorrect, the correct one in PowerApps is RGBA (0, 18, 107, 0.8)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d513da-e02f-2921-b754-c0b8e4be9dd9
* Version Independent ID: 41d6d319-adf6-a189-2f72-dc6591e605b1
* Content: [Color enumeration and ColorFade, ColorValue, and RGBA functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-colors#syntax)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-colors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-colors.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@alexdionisio Thanks for contacting us. Can you please re confirm what is the mistake in the syntax, from your comment you tried to differentiate the syntax but both looks same.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
