### ISSUE TITLE
Broken Link - More information: UI components: Colors

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/powerapps-docs#2058]
the link in  `More information: UI components: Colors`  is broken 

the url `https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/components/color` 
does not work
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea092895-28ba-b64d-33ec-9330ba976696
* Version Independent ID: 7eb1d946-aa8c-8e54-3e25-ecb6a4528fbf
* Content: [Use Teams integration object - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/use-teams-integration-object)
* Content Source: [powerapps-docs/teams/use-teams-integration-object.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/use-teams-integration-object.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Incorrect link has been removed; please allow some time to reflect the changes.
