### ISSUE TITLE
Topic should disucss muntiplexing

### ISSUE THREAD

**Issue by josbur** [MicrosoftDocs/powerapps-docs#2059]
[Enter feedback here]
Hello,

For this page to become more meaningfull the topic should cover multipexing 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de827382-3030-0e13-f4e6-803ab5a935ce
* Version Independent ID: ab23d1e4-5459-c0a5-1225-789a8ad90d8d
* Content: [Restricted tables requiring Dynamics 365 licenses - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-restricted-entities)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Mattp123** [comment]
@josbur - Multiplexing is a type of usage that has licensing implications beyond the scope of the restricted tables article. Information about multiplexing with Microsoft Dataverse can be found here: [Multiplexing - Overview](https://download.microsoft.com/download/3/D/4/3D42BDC2-6725-4B29-B75A-A5B04179958B/Licensing_Brief_PLT_Multiplexing.pdf)

Closing issue.
