### ISSUE TITLE
Typo "Item" [Create a component]

### ISSUE THREAD

**Issue by hpkeong** [MicrosoftDocs/powerapps-docs#206]
No. In the Display name, Property name, and Description boxes, type or paste "Items".
It should be "Item" to in-line with "Table({Item:"Home"}, {Item:"Admin"}, {Item:"About"}, {Item:"Help"})" so as not to confuse new user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93230c47-e5a5-15ad-9320-2f9671fdebb5
* Version Independent ID: dc5050e4-7243-b861-4c97-3bfb0165ade5
* Content: [Create a component for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-component)
* Content Source: [powerapps-docs/maker/canvas-apps/create-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-component.md)
* Service: **powerapps**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by AFTOwen** [comment]
@hpkeong Thanks for your feedback. "Items" is the name of the property. "Item" is the name of the column in the data source.
