### ISSUE TITLE
Library Resource still supported?

### ISSUE THREAD

**Issue by PaulMcManus23** [MicrosoftDocs/powerapps-docs#2061]
The library element doco is still there, however not linked from the resource page. Is it still supported?

I have a large 3rd party library I need to include external to the bundle, is there a sample around for this resource element?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22c1c03-caf7-8982-1b0a-6d6a11c2d96e
* Version Independent ID: a42c5be8-cf68-9aa3-f983-5bfb62104bb6
* Content: [Library Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/library)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/library.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/library.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@PaulMcManus23 Thanks for contacting us. Library resource is still not supported yet. If you want to implement code components using third-party libraries, see this sample https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/angular-flip-control. If you have more questions you can raise your concerns in the [forum](https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/bd-p/pa_component_framework), our development team will help you resolve your issue. Closing the issue.

**Comment by PaulMcManus23** [comment]
I am fine with using 3rd party libraries, my problem is more specifically that the library I want to use is close to 4mb and makes my bundle exceed the size limit for web resources.

I need to be able to use the library via a cdn or to split out multiple bundles. I will post on the forum.

**Comment by Nkrb** [comment]
@PaulMcManus23 We have a workaround on how to overcome the web resource limit. Please go through the doc https://docs.microsoft.com/en-us/powerapps/developer/component-framework/issues-and-workarounds#web-resource-size-is-too-large

**Comment by PaulMcManus23** [comment]
I am aware of that already.

The 3rd party library I am using is close to 4mb minified and is very complex, I am also using Office Fluent UI which is not small either as I use more components in it.

Unfortunately the production mode is not enough.
