### ISSUE TITLE
What is the actual data output of "Center Location"

### ISSUE THREAD

**Issue by shonto999** [MicrosoftDocs/powerapps-docs#2064]
The data output of the "center location" is unclear. Does it give actual latitude and longitude? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31883ac-ca27-ab3d-44bc-4192fbabefb8
* Version Independent ID: 04558e31-ff6a-9517-862e-125b1614a242
* Content: [Insert interactive maps into apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/geospatial-component-map)
* Content Source: [powerapps-docs/maker/canvas-apps/geospatial-component-map.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/geospatial-component-map.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Apologies for the delay, I've update the docs as follows:

| Property | Description |
| -- | -- |
| CenterLocation | Center location of the map as either `.Latitude` or `.Longitude`. The output will be an integer. For example, calling `Map1.CenterLocation.Latitude` will output a single integer such as `47.60357`.

**Comment by shonto999** [comment]
Thanks! I figured that was the case but wanted to make sure.
