### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Pankaj-Thakur** [MicrosoftDocs/powerapps-docs#2065]
[The following link leads to a 404 error - Import data Synchronize data Virtual entities Azure Integration Webhooks]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee29a2a8-4a67-b835-6b65-498150a04bc6
* Version Independent ID: 661557d8-e672-6884-7885-849a133ef8af
* Content: [Build Windows client applications using the XRM tools (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/build-windows-client-applications-xrm-tools)
* Content Source: [powerapps-docs/developer/data-platform/xrm-tooling/build-windows-client-applications-xrm-tools.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/xrm-tooling/build-windows-client-applications-xrm-tools.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@Pankaj-Thakur Thanks for contacting us. I didn't find any link in the doc that you have mentioned above. I found the blog page link in the **See also** section that errors 404 and i have fixed it.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
