### ISSUE TITLE
Add in limitations that PowerApps tile is not supported in PowerBI embedded app owns data scenario

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/powerapps-docs#2068]
It currently does not seem possible to embed a PowerApp tile in a PowerBI report, and then embed the PowerBI report using app owns data scenario.

When you do this, the PowerApp tile always asks for a login (instead of using the credentials of the application, that is used to generate the embed URL).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f94c3-694a-6d09-3a4f-e4b741684822
* Version Independent ID: c952e698-a2bf-a47d-acbd-a96a8a922636
* Content: [Power Apps visual for Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual)
* Content Source: [powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **pemikkel**

**Comment by w0ut0** [comment]
I added an idea in [PowerApps suggestion forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Support-embedding-in-PowerBI-reports-in-an-app-owns-data/idc-p/799670#M32812), but it seems it's currently not documented that this scenario is not possible.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Once the idea has updates or results in feature updates, documentation will be updated. Current and known capabilities are documented already.
