### ISSUE TITLE
How to update single lookup property?

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/powerapps-docs#2069]
Hi! I'm looking for AssignRequest replacement. Is it possible to update "ownerid" attribute with this API? Will single ownerid change be checked against "Assign" privilege?

Updating whole entity works, but it checks if user have "Write" privilege in given scope. But it my case it's not an option. User must assign record to himself and only then change it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28a23cb-07dc-47c7-df41-18063abd8917
* Version Independent ID: 1b6fef34-9306-3784-87dc-36b3e7d27b0e
* Content: [Update and delete entities using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/update-delete-entities-using-web-api#update-a-single-property-value)
* Content Source: [powerapps-docs/developer/data-platform/webapi/update-delete-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/webapi/update-delete-entities-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
See [Dependencies between access rights](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/security-access-rights#dependencies-between-access-rights)

You need ASSIGN, WRITE, READ privileges to Assign a record.

**Comment by FixRM** [comment]
@JimDaly, thank you. My question was: how can we update single ownerid attribute using that syntax?

```HTTP
PUT [Organization URI]/api/data/v9.0/accounts(00000000-0000-0000-0000-000000000001)/ownerid HTTP/1.1  
Content-Type: application/json  
OData-MaxVersion: 4.0  
OData-Version: 4.0  
  
{"value": "/systemuser(00000000-0000-0000-0000-000000000001)"}  
```

**Comment by JimDaly** [comment]
I was thinking this:

```
PATCH [Organization URI]/api/data/v9.0/accounts(00000000-0000-0000-0000-000000000001) HTTP/1.1  
Content-Type: application/json  
OData-MaxVersion: 4.0  
OData-Version: 4.0  
  
{"ownerid@odata.bind": "/systemuser(00000000-0000-0000-0000-000000000001)"}  
```

It is a single-valued navigation property rather than a simple property you can update using PUT.

**Comment by FixRM** [comment]
Scenario: User1 have the following privileges:
Read: All
Write: User level
Assign: All

He is able to assign any record to himself using AssignRequest which is deprecated. Now we must use WebAPI and PATCH (Update), right? But update doesn't work, as user don't have Write privilege to update other user records.

My guess was what if i changing single owner field will be tracked as old school "assign"? But you say that we can't update navigation properties with PUT. So we don't have alternative to assign record any more?

**Comment by JimDaly** [comment]
Is there a repro for this or just a 'what if'?

My expectation is that this (minor correction from above)

```
PATCH [Organization URI]/api/data/v9.0/accounts(00000000-0000-0000-0000-000000000001) HTTP/1.1  
Content-Type: application/json  
OData-MaxVersion: 4.0  
OData-Version: 4.0  
  
{"ownerid@odata.bind": "systemusers(00000000-0000-0000-0000-000000000002)"} 
```
From a security perspective is the equivalent to this:
```
var svc = new CrmServiceClient(conn);
var assignReq = new AssignRequest { 
  Target = new EntityReference("account",new Guid("00000000-0000-0000-0000-000000000001")),
  Assignee = new EntityReference("systemuser", new Guid("00000000-0000-0000-0000-000000000002"))
 };
svc.Execute(assignReq);
```
And is the equivalent to this:

```
var account = new Entity("Account", new Guid("00000000-0000-0000-0000-000000000001"));
account["ownerid"] = new EntityReference("systemuser", new Guid("00000000-0000-0000-0000-000000000002"));
svc.Update(account);
```
OData doesn't have the concept of Lookup, Owner, or Customer attributes that are found in the Organization Service. So there is no simple property to set with PUT. You have to set the specific single-valued navigation property that corresponds to the relationship(s) that the Lookup, Owner, or Customer attributes represent.

All the Web API operations translate to their equivalent Organization Service operations once they get in the execution pipeline.
Because Assign was one of [several special purpose operations that were deprecated](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/special-update-operation-behavior) and do not exist in Web API, they will always be translated to Update operations. 

As long as the user doesn't attempt to also update any other properties of the record, their Organization Level ASSIGN privileges should allow them to successfully update the record.

But I haven't personally created the scenario you describe to test it. But if it didn't hold true to what I've described I'd like to investigate it.

**Comment by FixRM** [comment]
Thanks @JimDaly, sorry for late reply. Yes, there is a repro. Unfortunately, you are wring. The following request is NOT working without WRITE privileges for target entity, so it is equivalent to Assign request:

```HTTP
PATCH [Organization URI]/api/data/v9.0/accounts(00000000-0000-0000-0000-000000000001) HTTP/1.1  
Content-Type: application/json  
OData-MaxVersion: 4.0  
OData-Version: 4.0  
  
{"ownerid@odata.bind": "systemusers(00000000-0000-0000-0000-000000000002)"} 
```
That's why I'm here :)

**Comment by JimDaly** [comment]
Thanks @FixRM 
I need to understand if this is a general authorization issue or if it is specifically for the Web API endpoint.
Are you saying:

- Update works with SOAP endpoint using SDK AssignRequest and Update, but not with Web API OData Patch
    - Then I need to work with the API team
- Update doesn't work regardless of the endpoint
    - Then I need to work with the security team
- Something else?

Appreciate your patience and persistence with this. 
But if you feel like you have found a bug, then the best thing to do is open a support ticket. This way the issue gets reviewed and escalated to the right team.  Let me know the ticket # and I will follow it through.

**Comment by FixRM** [comment]
I used to think that is was only Web Api issue, but as it turns out it is a product issue (general authorization issue). Update request via SOAP endpoint doesn't work as expected as well.

**Comment by JimDaly** [comment]
Let me check with the Security team.

**Comment by FixRM** [comment]
Hello @JimDaly. Do you have any news? Should I create support ticket?

**Comment by JimDaly** [comment]
I pinged them again. But opening a ticket would help.

**Comment by FixRM** [comment]
Thanks
