### ISSUE TITLE
"Failed to register service '{guid}'" - Using a Flow with PowerApps within solution

### ISSUE THREAD

**Issue by wallissam** [MicrosoftDocs/powerapps-docs#207]
We're having an issue completing a PowerApp solution that uses a Flow within the same solution, as seen in the attached screenshot.

We have never been successful in associating a solution-aware Flow with PowerApp, however no issues with non-solution aware Flows.

Full guid - '979f2e0d-1380-46c9-9d6f-f6981bb434d6'

We've tested it in various clean scenarios to nail down the issue without success. All non-solution-aware Flows work fine.

![failed to register service](https://user-images.githubusercontent.com/23362941/52913370-6f83a280-330d-11e9-8c99-f066a51277ef.png)

**Comment by AFTOwen** [comment]
@wallissam  Thanks for your feedback. For product-related feedback, visit https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1. Closing this issue.
