### ISSUE TITLE
Link for info of virtual tables is not relevant

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/powerapps-docs#2073]
Based on the paragraph "In addition to providing the ability to create data or import it from other systems, Dataverse also supports virtual tables. ... More information: Work with any data" I expect the link to take me to a page with more information on virtual tables. 

The linked page does not contain that information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b499c8-9737-8797-ef78-b7d7e6b7c6e0
* Version Independent ID: 6d45767f-5743-0e80-e58b-4eff4afc2d9c
* Content: [Why choose Microsoft Dataverse? - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/why-dataverse-overview)
* Content Source: [powerapps-docs/maker/data-platform/why-dataverse-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/why-dataverse-overview.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@algattik - thank you for pointing this out. The article link has been changed to point to the virtual tables overview article: https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-edit-virtual-entities. 

Closing issue.
