### ISSUE TITLE
Broken link:  Sample: Audit Entity Data Changes

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/powerapps-docs#2074]
The link "Sample: Audit Entity Data Changes" is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52604d1f-e5b7-ba4a-c853-66b3d6376321
* Version Independent ID: 6cd1039b-6289-87f3-95ec-027a99f249be
* Content: [Configure entities and attributes for auditing (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/configure-entities-attributes-auditing)
* Content Source: [powerapps-docs/developer/data-platform/configure-entities-attributes-auditing.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/configure-entities-attributes-auditing.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@algattik Fixed broken link. Will be re-published later today. Thanks
