### ISSUE TITLE
Error at step 5

### ISSUE THREAD

**Issue by o-utofbounds** [MicrosoftDocs/powerapps-docs#2075]
when entering this command 

`pac solution init --publisher-name <Name of the publisher> --publisher-prefix <Publisher prefix>`

i get this error, is it caused by a missing prerequisite? 

`[ERROR] Unhandled Exception: System.MissingMethodException: Method not found: 'NLog.LogFactory NLog.LogManager.LoadConfiguration(System.String)'.
[ERROR]    at bolt.cli.Session.Run(String[] args, String hostName, IEnvirons environs, IUserSettingsPersistence userSettingsPersistence, IOutputWindow outputWindow, Action errorCallback)
[ERROR]    at bolt.cli.Session.Run(String[] args, String hostName, IOutputWindow outputWindow, Action errorCallback)
[ERROR]    at bolt.Program.Main(String[] args)`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b01e51-8d80-08b1-2bd5-564c4756ad8a
* Version Independent ID: 750ea5e8-1325-2593-024d-68e926488076
* Content: [How to use the sample components? (Power Apps Component Framework) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/use-sample-components)
* Content Source: [powerapps-docs/developer/component-framework/use-sample-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/use-sample-components.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@o-utofbounds Thanks for contacting us. Did you try installing the latest version of the Power Apps CLI. Did you do all the steps provided in the doc. Can you share more information on what you actually did, so that it will be easy for us to find out the issue. You can also raise the issue in [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue.

**Comment by o-utofbounds** [comment]
I followed the steps provided, including latest version of the CLI

**Comment by o-utofbounds** [comment]
it seems it was caused by a old version of NLog being installed in the Global Assembly Cache by some sofwtare, after removing it from the GAC the "pac" command now work as expected
