### ISSUE TITLE
Feedback from aeric regarding last steps

### ISSUE THREAD

**Issue by erical77** [MicrosoftDocs/powerapps-docs#2076]
Hi Uday Guduri,

My name is Alan Ericson, I am an Escalation Engineer for Dynamics 365 CE within CSS. I came across this article recently and I'm glad it was published -- very much needed with the deprecation of the Outlook client, but I did find an issue with the last steps.
The last steps in this article should be updated to avoid editing the connection string with the error URL.

In step 4, the article indicates to select the go button, OK, and then import. However, once the 'Can't complete this action' dialog displays, the issue has been resolved and all that is needed is to close the 'Edit Web Query' window. The issue is in regards to authentication, and the user should experience an authentication prompt when selecting the edit query button. Once the username and password are entered, then the 'can't complete this action' window will display -- this indicates the authentication is complete and the user should close that window and then select refresh in Excel.
If you follow the current steps in the article, it will then update the connection string to the error URL and will break the worksheet.

Change step 4 from:
Select Go.

To:
Enter username and password when prompted.

Change step 5 from:
In the error message that appears, select OK, and then select Import.

To:
![image](https://user-images.githubusercontent.com/53955827/105534643-68146300-5cb3-11eb-94bd-97991965af3c.png)

When the error message appears, select cancel or X to close the window.

Step 6 could just be updated to:
Refresh the data in Excel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5169f65-ceb2-40bb-3fef-1b65956871a4
* Version Independent ID: b27bcee5-e052-47ef-a806-f67d00ee44ae
* Content: [Troubleshoot export to Excel - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/ts-export-to-excel#data-disappears-after-i-refresh-the-exported-dynamic-excel-file)
* Content Source: [powerapps-docs/user/ts-export-to-excel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/ts-export-to-excel.md)
* Service: **powerapps**
* GitHub Login: @udaykirang
* Microsoft Alias: **udag**

**Comment by udaykirang** [comment]
Thanks for the suggestion, Alan. I have updated the procedure accordingly. 
- Uday

**Comment by erical77** [comment]
Hi Uday,

Thank you for the update... That was pretty quick 🙂

Thanks,
Alan Ericson
________________________________
