### ISSUE TITLE
application permissions instead of delegated?

### ISSUE THREAD

**Issue by Chielus** [MicrosoftDocs/powerapps-docs#2077]
When configuring the Azure App Registration, we need to assign delegated permissions to the app. This is strange, because the app service principal can be used on itself when working with D365/Dataverse APIs. It can run as a background service. Client credentials flow can be used, though it has delegated API permissions granted. Shouldn't this be application permissions instead of delegated permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c37834-5349-b2ea-2c40-d6a7b519288f
* Version Independent ID: 610b2eb4-66ac-a221-14d8-b06a3fbc90b0
* Content: [Use Single-Tenant server-to-server authentication (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-single-tenant-server-server-authentication#application-user-creation)
* Content Source: [powerapps-docs/developer/data-platform/use-single-tenant-server-server-authentication.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/use-single-tenant-server-server-authentication.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **pehecke**

**Comment by paulliew** [comment]
Our Dynamics CRM app's service principal is configured and can only accept Delegated permissions which allows user impersonation.

**Comment by phecke** [comment]
@Chielus I hope Paul's response answers your question.

**Comment by fowl2** [comment]
For the background service use case, it seems that no permissions are required - an application user can be created and used for any app id.
