### ISSUE TITLE
adOnLookupTagClick is not available in the latest version of On Premise CRM D365

### ISSUE THREAD

**Issue by JamesHorsley** [MicrosoftDocs/powerapps-docs#2078]
The documents need to make clear which version numbers for Online and On Premise each item was introduced. This one for example does not yet exist for On premise and it would be nice to make that clarer (even better would e to keep On Premise up to date with features!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db6fb00-418e-9599-3895-ec2e9f80536c
* Version Independent ID: 5efd1e98-7335-6938-1a20-4b59a62e9d0f
* Content: [addOnLookupTagClick (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addonlookuptagclick)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOnLookupTagClick.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOnLookupTagClick.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We are in the process of updating docs that differentiate what methods are supported on on-premises and online version. Will be pushed live sometime end of April or first week of May. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
