### ISSUE TITLE
В пункте 5 неверная формула

### ISSUE THREAD

**Issue by y-tver9** [MicrosoftDocs/powerapps-docs#2079]
Правильная формула:
Office365Outlook.SendEmail(Concat(MyPeople;UserPrincipalName & ";" );MessageBody.Text;SubjectLine.Text)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 36f74688-5675-6a39-6003-88aa0048db54
* Version Independent ID: f6073a6a-e1b6-39e2-1ed0-5ebabd69e45a
* Content: [Шаблон экрана 'Люди' - Power Apps](https://docs.microsoft.com/ru-ru/powerapps/maker/canvas-apps/screen-templates/people-screen-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/screen-templates/people-screen-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/screen-templates/people-screen-overview.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, content has been updated as per latest supported [function](https://docs.microsoft.com/connectors/office365/). Please allow some time to reflect the changes.
