### ISSUE TITLE
Link to list of ASCII codes

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#208]
Please add a list of ASCII codes. This one is pretty good: https://www.ascii-code.com/

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5973db7-626d-9be3-31b1-7f41668ae41a
* Version Independent ID: 8d1279ca-77f6-ec61-b701-7527854b5954
* Content: [Char function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-char)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-char.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-char.md)
* Service: **powerapps**
* GitHub Login: @mgblythe
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Topic updated with instructions to build your own chart. Thanks, @SeaDude!
