### ISSUE TITLE
Manifest generated by ConvertModelJsonToManifest  doesn't successfully configure either source or sink

### ISSUE THREAD

**Issue by SweetsNSavories** [MicrosoftDocs/powerapps-docs#2082]
Although the given code sample generates manifest.cdm.json and <entityname>.cdm.json , when configured the source using manifest as described here, the data does not show up in Data Preview. When manifest analyzed it apparently does not have any information related DataPartitions and DataPartitionPatterns as described in manifest documentation.
https://docs.microsoft.com/en-us/common-data-model/cdm-manifest#local-entity-declaration

How to make the generated manifest using https://github.com/sabinn-msft/ConvertModelJsonToManifest that shall contain all the information needed to configure source and sink in DataFlow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c6e7c2-df95-7a57-cbdb-a93a701f8168
* Version Independent ID: 24fb7b46-aef0-98ca-5f36-a59b0f7d7c6a
* Content: [Ingest Microsoft Dataverse data with Azure Data Factory - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake-data-adf)
* Content Source: [powerapps-docs/maker/data-platform/export-to-data-lake-data-adf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/export-to-data-lake-data-adf.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sabinn-msft** [comment]
Export to data lake produces model.json. When we put this together, ADF did not support model.json and so we provided a stop gap to convert model to manifest. Since then ADF seems to be supporting model.json. Can you try consuming model.json with ADF without converting to manifest? Thanks

**Comment by praveenthonda** [comment]
Thanks for the quick response. 

Format Type Tooltip on ADF(dataflow) displays as follows.

Manifest  - Used by applications that are consuming CDM version 1.0 or later. This file name should look like '*.manifest.cdm.json'
Model - Used by applications that are consuming CDM versions earlier than 1.0. This file name should be 'model.json'

Based on below documentation excerpt of "from model json to the future" it infers that model.json would not suffice for insert into data lake. hence want to generate a manifest that is not only compliant with latest CDM v1.0 and later but also helps to configure and source and sink successfully.

https://docs.microsoft.com/en-us/common-data-model/sdk/from-modeljson-to-the-future

"Originally focusing on explaining the structure and relationships between entities, Common Data Model offered a simple metadata format called "model.json". This format, however, was not able to convey the richness of semantics the source systems had on the data they would insert into data lakes, leaving consumers with limited ability to understand it. "

**Comment by sabinn-msft** [comment]
We are working on uptaking latest CDM version to produce manifest.json very soon. That said, please understand that many customers are able to consume model.json in production just fine. We are the largest producers of model.json. I just want to make sure that you don't think there are any shortcomings with model.json.

**Comment by SweetsNSavories** [comment]
Thanks & Much Appreciated, for clarifying that model.json has no short comings for consumption.
