### ISSUE TITLE
Milestones and Bulletin apps not visible in Teams store

### ISSUE THREAD

**Issue by VillePellosniemi** [MicrosoftDocs/powerapps-docs#2085]
I'd like to try out these 2 Teams + Powerapps solutions but I don't know where to install them to my environment. When I enter "Milestones" or "Bulletins" in the search, the apps I'm looking for don't appear. 
![milestones](https://user-images.githubusercontent.com/34025719/105995432-a47c0080-60b1-11eb-8680-643b77a4d3c6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 887bc09c-a4fe-d836-4532-026e25a875b4
* Version Independent ID: cbd33cd7-6ddd-f912-10fb-eb5e673bc1e0
* Content: [Use sample apps from teams store - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/use-sample-apps-from-teams-store)
* Content Source: [powerapps-docs/teams/use-sample-apps-from-teams-store.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/use-sample-apps-from-teams-store.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please try to check again. If the apps don't show up on a consistent basis, please reach out to your org's Teams administrator as the apps might be [blocked in the org settings](https://docs.microsoft.com/microsoftteams/manage-apps#manage-org-wide-app-settings).
