### ISSUE TITLE
英語→日本語化において生じている不要な変換について

### ISSUE THREAD

**Issue by nakamae1983** [MicrosoftDocs/powerapps-docs#2086]
[フィードバックをこちらに入力してください]
英語から日本語への変換の際に引数名および定数名が日本語の漢字に変換されています。
引数名、定数名はPower Apps Studio上では英単語そのままやカタカナで表示されていますので、修正をお願いします。

Launch関数 関連
・対象　→　ターゲット
・LaunchTarget enum の 新規、新着　→　New
・LaunchTarget enum の 置換、交換　→　Replace

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 69fd8dc0-ad38-444f-8a2a-ce3e4617db16
* Version Independent ID: cc0a738b-1f7e-8ad4-8dc7-d3d04697b270
* Content: [Launch および Param 関数 - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/function-param)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-param.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-param.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jowilco** [comment]
@nakamae1983 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@nakamae1983 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
