### ISSUE TITLE
Update sample to use MSAL

### ISSUE THREAD

**Issue by skalahonza** [MicrosoftDocs/powerapps-docs#2087]
Update sample to use MSAL for authentication against web API, because of https://github.com/azure-deprecation/dashboard/issues/60

Link to the corresponding documentation: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows 

The sample should also contain, that when MSAL is used, the scope should be constructed as:
`string[] scopes = new string[] { $"{_options.ServiceUrl}/.default" };`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb27f5b-4110-dcb0-e4da-b4e8e77b4c6d
* Version Independent ID: 33776e00-0543-3001-d2a0-b09148e40625
* Content: [Enhanced quick Start(Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/enhanced-quick-start)
* Content Source: [powerapps-docs/developer/data-platform/webapi/enhanced-quick-start.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/webapi/enhanced-quick-start.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@skalahonza  Thanks for the suggestion. The topic has been updated to use MSAL, and a complete VS solution download has been added.

[https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/enhanced-quick-start](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/enhanced-quick-start)
