### ISSUE TITLE
Scenario for disabling rollback

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#2091]
Please add a note to the part about Enable rollback.
If the operation defined does not change data, but only retrieves data, there are certain situations where performance can be improved by disabling Enable rollback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c886648-4954-ae97-cda2-1e5d7f11af79
* Version Independent ID: 67dc3775-5cc2-b86e-f71a-dcbf9617b14a
* Content: [Configure actions for workflows in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/configure-actions)
* Content Source: [powerapps-docs/maker/data-platform/configure-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/configure-actions.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@JimDaly - completed via https://github.com/MicrosoftDocs/powerapps-docs-pr/pull/4126.
