### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by chaffee007** [MicrosoftDocs/powerapps-docs#2094]
Attributes is spelled wrong.
![image](https://user-images.githubusercontent.com/16105932/106317664-3c095c80-6234-11eb-9341-754e37c9dd35.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae10e81-fc06-bb27-708c-71082460571a
* Version Independent ID: ecf78692-311d-c121-faf7-aaed40f46c6a
* Content: [getValue (Client API reference) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/getvalue)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getValue.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getValue.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@chaffee007 We have fixed the issue and pushed docs live. Closing the issue.
