### ISSUE TITLE
Settings options no longer exist

### ISSUE THREAD

**Issue by cimares** [MicrosoftDocs/powerapps-docs#2098]
The steps shown to get the Instance API URL no longer exist.

**_To get the url value:

From the https://make.powerapps.com site with the appropriate environment selected, select Settings Settings button and choose Advanced Customizations. Then select Developer resources.

In the Developer Resources page, look for the Instance Web API value and copy it._**

The option for these steps does not appear in the settings menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@cimares  Thanks for pointing this out. I have updated the instructions. Should be published after 6:00pm PST today.
