### ISSUE TITLE
No Category und Priority Options

### ISSUE THREAD

**Issue by Frank4All** [MicrosoftDocs/powerapps-docs#2100]
Hi Everybody,
i followed the instructions step by step. When I run the app, I don't have any options when I create a ticket for Category and Priority.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Installieren und Konfigurieren des Beispiels „HelpDesk“ für Canvas-Apps - Power Apps](https://docs.microsoft.com/de-de/powerapps/maker/canvas-apps/help-desk-install)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Looks like there might be a step missed. If need help with the investigation and fix, please reach out using [Help + Support](https://docs.microsoft.com/power-platform/admin/get-help-support).
