### ISSUE TITLE
Mention `Selected.Value` as the replacement for `SelectedText`

### ISSUE THREAD

**Issue by philippw** [MicrosoftDocs/powerapps-docs#2104]
`SelectedText` has been deprecated and can be substituted by `Selected.Value`.

The documentation page should mention this next to the deprecation warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea793a3-0ef8-50a5-351e-15ebcdb77a9f
* Version Independent ID: 17282b67-79f0-fb34-b1e6-d45f905f81e7
* Content: [Drop down control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-drop-down)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-drop-down.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-drop-down.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been updated. Changes will be visible soon.
