### ISSUE TITLE
Impossible to use

### ISSUE THREAD

**Issue by dyderik** [MicrosoftDocs/powerapps-docs#2105]
I subscribed to the free trial of Power Automate. Everything there works fast, fine and smooth. However, with the Power Apps Community Plan it's quite a different story. Everything loads very slow. Worse, some things don't even work at all. Example I click create to create a work flow. I select cloud flows scheduling. Then I click post a tweet to twitter. Then I connect my twitter account. That all works good but very slow. However, after these actions, there immediately is a grayed out retry button. No idea why it says retry. Then I manage to change the retry button in a continue button by clicking on my twitter account name. However, also this continue button is grayed out and cannot be clicked. It makes no difference when I reload, wait forever or start all over again, the same issue comes back and nothing happens. So it's impossible for me to create a Twitter work flow. As said, for the rest everything loads extremely slow while in the free trial of Power Automate everything loads very fast and works there as expected in the browser FireFox (latest version). The same browser and the same internet connection are used for the Community Plan. I think that the Community Plan has slow web servers or wrong server settings or both. I hope somebody can help me. By the way, I also cannot uncheck notifications. And, by accident I connected my Twitter account twice. It's impossible to uncheck one of the 2. The URL where it all happens is https://make.powerapps.com/environments/Default-29fba5f6-7a08-4d55-abe4-42e7828f4a4a/logicflows Thanks for any help!

**Comment by dyderik** [comment]
Here is a screenshot: 
![image](https://user-images.githubusercontent.com/60973056/106733097-6b610480-664c-11eb-9f6d-c8149e6c10eb.png)

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.
