### ISSUE TITLE
Required/recommended browser for portal management app?

### ISSUE THREAD

**Issue by antonburger-advanced** [MicrosoftDocs/powerapps-docs#2106]
Is there a required/recommended browser for using the portal management app? There are several places in the hierarchy of portal entities where you need to select an entity name, and the app seems to have some customisation on the form to support this. See screenshot of a new Entity Permission form below, where the custom entity picker seems to consistently fail to load on the latest version (85) of Firefox, leaving you with just a disabled text field that you can't do anything with.

![image](https://user-images.githubusercontent.com/10885679/106744162-4c944b00-6617-11eb-8052-08fdff4aa041.png)

There are no script errors shown as per the [Browser Considerations](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-portal#browser-considerations) on this doc page, but I do see this error in the browser dev tools, which seems relevant:

![image](https://user-images.githubusercontent.com/10885679/106744445-af85e200-6617-11eb-8dfc-70c1fea16c5e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83e291-fd19-f80b-f423-b2f701e5e279
* Version Independent ID: 85df9f5f-602f-af17-fda0-2b24b4627d53
* Content: [Overview of Portal Management app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-portal)
* Content Source: [powerapps-docs/maker/portals/configure/configure-portal.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/configure-portal.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by antonburger-advanced** [comment]
Although I didn't see any script errors, this problem appears to be resolved by disabling adblockers as per the existing documentation.

**Comment by tapanm-MSFT** [comment]
Closing as resolved.
