### ISSUE TITLE
How to Identify / distinguish between a regular SAML 2.0 and AD FS SAML2.0

### ISSUE THREAD

**Issue by tomerbsentinel** [MicrosoftDocs/powerapps-docs#2107]
The reason I'm asking it, is because I want to work with this Python package:
https://github.com/onelogin/python3-saml
From their docs, I can see  this line:
lowercase_urlencoding - Defaults to false. ADFS users should set this to true.

> The Request
> Building a OneLogin\_Saml2\_Auth object requires a request parameter:
> 
> auth = OneLogin_Saml2_Auth(req)
> This parameter has the following scheme:
> 
> req = {
>     "http_host": "",
>     "script_name": "",
>     "server_port": "",
>     "get_data": "",
>     "post_data": "",
> 
>     # Advanced request options
>     "https": "",
>     "lowercase_urlencoding": "",
>     "request_uri": "",
>     "query_string": ""
> }
> Each Python framework builds its own request object, you may map its data to match what the SAML toolkit expects. Let`s see some examples:
> 
> def prepare_from_django_request(request):
>     return {
>         'http_host': request.META['HTTP_HOST'],
>         'script_name': request.META['PATH_INFO'],
>         'server_port': request.META['SERVER_PORT'],
>         'get_data': request.GET.copy(),
>         'post_data': request.POST.copy()
>     }
> 
> def prepare_from_flask_request(request):
>     url_data = urlparse(request.url)
>     return {
>         'http_host': request.host,
>         'server_port': url_data.port,
>         'script_name': request.path,
>         'get_data': request.args.copy(),
>         'post_data': request.form.copy()
>     }
> An explanation of some advanced request parameters:
> 
> https - Defaults to off. Set this to on if you receive responses over HTTPS.
> 
> lowercase_urlencoding - Defaults to false. ADFS users should set this to true.
> 
> request_uri - The path where your SAML server recieves requests. Set this if requests are not recieved at the server's root.
> 
> query_string - Set this with additional query parameters that should be passed to the request endpoint.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15b7df3-dd92-cef2-f0cd-9a4274a9c5fc
* Version Independent ID: 6818fbbc-7255-3a2f-9d0e-d486b4f7d8af
* Content: [Configure SAML 2.0 provider for portals with AD FS. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings)
* Content Source: [powerapps-docs/maker/portals/configure/configure-saml2-settings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/configure-saml2-settings.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please refer to the Python documentation or report an issue for more explanation. Difference between SAML 2.0 and ADFS SAML 2.0 is out of context for Power Apps portals documentation.
