### ISSUE TITLE
3rd Party Cookies - Allow List Edit - 2228894

### ISSUE THREAD

**Issue by ThePolicy** [MicrosoftDocs/powerapps-docs#2109]
Our company blocks all 3rd party cookies by default and maintains a cookie allow list.  I found that I had to add [*.]azureedge.net to the cookie allow list for Google Chrome and Microsoft Edge in the following location for the site to load correctly.

Chrome:
Computer Configuration/Policies/Administrative Templates/Google/Google Chrome/Content Settings -> Allow cookies on these sites

Edge:
Computer Configuration/Policies/Administrative Templates/Microsoft Edge/Content Settings -> Allow cookies on specific sites

I wanted to mention this as I didn't see it in the list of cookies to allow in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de7fca-d66b-479c-1570-676ebafa1b78
* Version Independent ID: 70b75562-e755-31cd-c7fd-ef87983698f5
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues#resolution-4-allow-third-party-cookies)
* Content Source: [powerapps-docs/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Documentation has been updated since this issue was raised. If the issue still persists, please reopen this issue, or open a new issue for documentation updates. For any help with product issues, please reach out using [Help + Support](https://docs.microsoft.com/power-platform/admin/get-help-support).
