### ISSUE TITLE
Instructions and process to update access key inadequate

### ISSUE THREAD

**Issue by ronsonntag54** [MicrosoftDocs/powerapps-docs#2111]
My organization has HUNDREDS of apps. The current interface does not provide a way to filter the list of apps down so that the specific entry for the admin portal can be found if you do not know its name. There is no search by type and no search by partial names (contains). This makes responding to the email just received that the secure access will expire unless the keys are updated difficult to do.

There should be a completely separate entry (not App) that selects the portal for the selected subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c33206-a8f7-cce4-d663-894874c0ae98
* Version Independent ID: 72de507b-3eec-6433-1c0a-462b98ef1a91
* Content: [Overview of Power Apps portals admin center - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/admin-overview)
* Content Source: [powerapps-docs/maker/portals/admin/admin-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/admin-overview.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please submit this as an idea on the [Power Apps Ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) so the idea can be voted for to be considered.
