### ISSUE TITLE
Unable to edit Help Desk App

### ISSUE THREAD

**Issue by kofrimpong** [MicrosoftDocs/powerapps-docs#2114]
After importing the app, when I try to edit, I get the following error.

Error opening file.
Something went wrong while opening file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by leoespinoza** [comment]
similar problem

**Comment by RonyKDC** [comment]
check that attached error i got when i first opened the app after importing then i got "Something went wrong while opening file" next time i try to open the app  ... any updates?

![power app error](https://user-images.githubusercontent.com/79501321/108809514-adc59380-75b1-11eb-9c4d-f7224ac303b6.png)

**Comment by oeric-A2B** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/79651638/109174035-c20dba00-7784-11eb-9643-bebc631e8c5d.png)

**Comment by mvwright12** [comment]
Same problem here with same error message. Seems like same issue as ticket #2161.

**Comment by mvwright12** [comment]
[SOLUTION - I was able to build a zip file duplicating the original but that doesn't throw an error. All same content just different file structure to work with recent PowerApps changes. It's attached here: 
[HelpDesk(SP_List)UPDATED.zip](https://github.com/MicrosoftDocs/powerapps-docs/files/6118405/HelpDesk.SP_List.UPDATED.zip)

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated, please use updated steps.
