### ISSUE TITLE
   Wrong statement that Virtual Entities support update and delet

### ISSUE THREAD

**Issue by hanslinder** [MicrosoftDocs/powerapps-docs#2117]
[Enter feedback here]
Your article begins stating that 
"Virtual entities support create, updates and delete of data in the external system." 
This is not really true today, only supports "read"

Br,
Hans 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42ae2cb6-ce2a-21c7-cb81-b60e7b026753
* Version Independent ID: 5a3cb7c0-6881-1d96-0dc3-639324a4568c
* Content: [Get started with virtual entities (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/get-started-ve)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by Mattp123** [comment]
True but recently update and delete support has been added with the OData provider. https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/get-started-ve

Closing issue.
