### ISSUE TITLE
Power Apps での日付の選択コントロール

### ISSUE THREAD

**Issue by Hichiriki** [MicrosoftDocs/powerapps-docs#2119]
ドキュメント改善お願いします。

＜現状＞
例
日付の選択 コントロールを追加して、 期限 という名前を付けます。

コントロールの追加、名前付け、構成 についてはこちらをご覧ください。

Label コントロールを追加し、その テキスト プロパティを次の数式に設定します:
DateDiff(今日()、Deadline.SelectedDate) & "残り日数!"

＜改善後＞
例
日付の選択 コントロールを追加して、 DeadLineという名前を付けます。

コントロールの追加、名前付け、構成 についてはこちらをご覧ください。

Label コントロールを追加し、その テキスト プロパティを次の数式に設定します:
"残り日数は" & DateDiff(Today(), DeadLine.SelectedDate) & "日間！"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5c73d9b9-7cb5-f7ee-8c70-227309c9b18b
* Version Independent ID: 5276fa3a-3cf9-70e5-5324-85e0ebc24c56
* Content: [日付の選択コントロール: リファレンス - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/controls/control-date-picker)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-date-picker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-date-picker.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by jowilco** [comment]
@Hichiriki 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@Hichiriki 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
