### ISSUE TITLE
Power Apps でのチェック ボックス コントロール

### ISSUE THREAD

**Issue by Hichiriki** [MicrosoftDocs/powerapps-docs#2120]
ドキュメント改善お願いします。

Power Apps でのチェック ボックス コントロール

＜現状＞
例
チェック ボックス コントロールを追加して chkReserve という名前を付け、その テキスト プロパティを 今すぐ予約する を表示するよう設定します。

コントロールの追加、名前付け、構成 についてはこちらをご覧ください。

Date picker コントロールを追加し、その 表示 プロパティを次の数式に設定します:
If(chkReserve.Value = true, true)

F5 キーを押して、 chkReserve をクリックまたはタップしてその 値 プロパティを true に設定してから、もう一度 chkReserve をクリックまたはタップしてその 値 プロパティを false に設定します。

Date Picker コントロールは、 chkReserve の 値 プロパティが true のときは表示されますが、 false のときは表示されません。

<改善提案>
例
チェック ボックス コントロールを追加して chkReserve という名前を付け、その Textプロパティを "今すぐ予約する" を表示するよう設定します。

コントロールの追加、名前付け、構成 についてはこちらをご覧ください。

日付の選択コントロールを追加し、その Visibleプロパティを次の数式に設定します:
If(chkReserve.Value = true, true)

F5 キーを押して、 chkReserve をクリックまたはタップしてその Valueプロパティを true に設定してから、もう一度 chkReserve をクリックまたはタップしてその Valueプロパティを false に設定します。

Date Picker コントロールは、 chkReserve のValueプロパティが true のときは表示されますが、 false のときは表示されません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 00a64ce1-c6a7-70b7-c037-70a49e04e22f
* Version Independent ID: e10f3307-74eb-a469-aa20-f02a86366cbf
* Content: [チェック ボックス コントロール: リファレンス - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/controls/control-check-box)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-check-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-check-box.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by jowilco** [comment]
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@Hichiriki 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
