### ISSUE TITLE
Power Apps のトグル コントロール

### ISSUE THREAD

**Issue by Hichiriki** [MicrosoftDocs/powerapps-docs#2121]
ドキュメント改善お願いします。

＜現状＞
Power Apps のトグル コントロール

＜改善提案＞「挿入」ー「入力」ー「切り替え」です。「トグル」ではありません。
Power Apps の切り替えコントロール

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b18cbeb7-5fd6-6815-c9ed-bf08db8ae058
* Version Independent ID: e6a9e3d7-73aa-bc33-3fe9-b441a16ef7c9
* Content: [トグル コントロール: リファレンス - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/controls/control-toggle)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-toggle.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-toggle.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by jowilco** [comment]
@Hichiriki 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@Hichiriki 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
