### ISSUE TITLE
Power Apps での評価コントロール

### ISSUE THREAD

**Issue by Hichiriki** [MicrosoftDocs/powerapps-docs#2122]
ドキュメント改善お願いします。

＜現状＞
例
評価 コントロールを追加して Quantitative という名前を付けます。
コントロールの追加、名前付け、構成 についてはこちらをご覧ください。
Text input コントロールを追加し、 質的 という名前を付け、 評価 コントロールの下に移動します。
Text input コントロールの 既定 プロパティを "" に設定し、その HintText を次の数式に設定します:
If(Quantitative.Value > 3, "何が特に気に入りましたか?", "何かご意見がおありですか?")
If 関数または その他の関数 の詳細については各関連記事を参照してください。
F5 キーを押してから、 評価 コントロールの 4 または 5 つの星をクリックまたはタップします。
Text input コントロールのヒント テキストが、高評価を反映して変更されます。
量的 で 4 つより少ない星をクリックまたはタップします。
Text input コントロールのヒント テキストが、低評価を反映して変更されます。
既定のワークスペースに戻るには、Esc キーを押します。

＜改善提案＞
例
評価 コントロールを追加して Quantitative という名前を付けます。
コントロールの追加、名前付け、構成 についてはこちらをご覧ください。
テキスト入力 コントロールを追加し、 Qualitativeという名前を付け、 評価 コントロールの下に移動します。
テキスト入力 コントロールの 既定 プロパティを "" に設定し、その HintText を次の数式に設定します:
If(Quantitative.Value > 3, "何が特に気に入りましたか?", "何かご意見がおありですか?")
If 関数または その他の関数 の詳細については各関連記事を参照してください。
F5 キーを押してから、 評価 コントロールの 4 または 5 つの星をクリックまたはタップします。
テキスト入力 コントロールのヒント テキストが、高評価を反映して変更されます。
 評価 コントロールで 4 つより少ない星をクリックまたはタップします。
テキスト入力 コントロールのヒント テキストが、低評価を反映して変更されます。
既定のワークスペースに戻るには、Esc キーを押します。
以上

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f473a026-0597-caa9-f016-ec6df660f4c2
* Version Independent ID: bc0d60db-03a7-5b9a-faff-89902bb2b245
* Content: [評価コントロール: リファレンス - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/controls/control-rating)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-rating.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-rating.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by jowilco** [comment]
@Hichiriki 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@Hichiriki 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
