### ISSUE TITLE
Power Apps のタイマー コントロール

### ISSUE THREAD

**Issue by Hichiriki** [MicrosoftDocs/powerapps-docs#2123]
ドキュメント改善お願いします。

＜現状＞
カウントダウンの表示
ラベルを追加し、その テキスト プロパティを次の数式に設定します。
「残りの秒数: 」 & RoundUp(10-Countdown.Value/1000, 0)
＜改善提案＞
カウントダウンの表示
ラベルを追加し、その テキスト プロパティを次の数式に設定します。
"残りの秒数: " & RoundUp(10-Countdown.Value/1000, 0)
以上

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e2dbb18d-a612-2986-4e64-a180ba94dbd0
* Version Independent ID: 30e30b75-aa45-b6ec-e5f7-c44cb444a9a9
* Content: [タイマー コントロール: リファレンス - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/controls/control-timer)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-timer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-timer.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by jowilco** [comment]
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@Hichiriki 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
