### ISSUE TITLE
Error: System.NullReferenceException :

### ISSUE THREAD

**Issue by Srav2027** [MicrosoftDocs/powerapps-docs#2124]
[Enter feedback here]
Hi, I am new to this console app coding, I tried to execute from the sample in docs, it says System.NullReferenceException: 'Object ref not set to an instance of obj'
 Its on the line "var svc= new CrmServiceClient(conn), Please help me
the code is:
static void Main(string[] args)
{            
    // e.g. https://yourorg.crm.dynamics.com
    string url = "<your environment url>";
    // e.g. you@yourorg.onmicrosoft.com
    string userName = "<your user name>";
    // e.g. y0urp455w0rd 
    string password = "<your password>";

    string conn = $@"
    Url = {url};
    AuthType = Office365;
    UserName = {userName};
    Password = {password};
    RequireNewInstance = True";

    using (var svc = new CrmServiceClient(conn))
    {

        WhoAmIRequest request = new WhoAmIRequest();

        WhoAmIResponse response = (WhoAmIResponse)svc.Execute(request);

        Console.WriteLine("Your UserId is {0}", response.UserId);

        Console.WriteLine("Press any key to exit.");
        Console.ReadLine();
    }
}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8916bbc-6834-44e1-1354-92ba60eacd0c
* Version Independent ID: ce53ff38-bf6a-9659-5834-aca6a7446cdd
* Content: [Quickstart: Organization service sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/quick-start-org-service-console-app)
* Content Source: [powerapps-docs/developer/data-platform/org-service/quick-start-org-service-console-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/org-service/quick-start-org-service-console-app.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Thanks for reporting this.
This sample had a dependency on WS-Trust which has been deprecated per [Use of Microsoft 365 authentication with the WS-Trust security protocol](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/authenticate-office365-deprecation)

I modified the page. Changing this:

```
    string conn = $@"
    Url = {url};
    AuthType = Office365;
    UserName = {userName};
    Password = {password};
    RequireNewInstance = True";
```
To the following so it uses OAuth and the globally approved application id provided for samples:

```
            string conn = $@"
            Url = {url};
            AuthType = OAuth;
            UserName = {userName};
            Password = {password};
            AppId = 51f81489-12ee-4a9e-aaae-a2591f45987d;
            RedirectUri = app://58145B91-0C36-4500-8554-080854F2AC97;
            LoginPrompt=Auto;
            RequireNewInstance = True";
```

Update should appear in the page this evening.
