### ISSUE TITLE
How to retrieve file size?

### ISSUE THREAD

**Issue by DanielBruckhaus** [MicrosoftDocs/powerapps-docs#2128]
How can the size of the file be retrieved (without actually downloading it)?
Would be especially helpful to determine if a download with chunking is required (i.e. size > 16MB).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File attributes (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/file-attributes)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by fowl2** [comment]
It appears that the [GetFileSasUrl](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/getfilesasurl) Function [returns](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/filesasurlresponse) the file size, and also allows you to download without chunking. :)

**Comment by phecke** [comment]
@DanielBruckhaus You can obtain the file size using the SDK API with InitializeFileBlocksDownloadResponse.FileSizeInBytes. For the Web API, send the GET request and look at the response header. However, do not then download the body contents unless you want to.
