### ISSUE TITLE
Article should also explain how this is done in Teams where there is a Dataverse table

### ISSUE THREAD

**Issue by bigpix2000** [MicrosoftDocs/powerapps-docs#2129]
In general, discussions on features should have a "the teams version will or WILL NOT do this" or a "follow this link to how you can do this in teams dataverse" etc.  otherwise it is teaser information that clutters up in our search results trying to solve the issue thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d61b22-c901-ad09-b9bb-ecfb2bb12f9d
* Version Independent ID: fa41e5c6-8deb-7a92-2699-42db23d1a85c
* Content: [Import or export data from Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-import-export)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-import-export.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/data-platform-import-export.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sama-zaki** [comment]
Thank you for the feedback. You are correct, this does not apply to Dataverse for Teams.

**Comment by Mattp123** [comment]
@bigpix2000 - See this article that describes the various features that are/aren't available with Dataverse for Teams.
https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare#integration

Closing issue.
