### ISSUE TITLE
Error opening file - 2190983

### ISSUE THREAD

**Issue by PTHugoPinto** [MicrosoftDocs/powerapps-docs#2133]
Hello!
I  need help with this issue, please:

I've already created lists in SharePoint, and i've already installed the application (MyExpenses(SP_List).Zip) but when i try to edit i get this message: 

"Error opening file
Something went wrong while opening your app"

I've already deleted browser cookies and opened it in a Incognito window but i still get the same message.

When i press on Play i´m able to run the App
When i press Edit i get the error message

![Error_Message](https://user-images.githubusercontent.com/79216403/108239717-1809ae80-7142-11eb-92db-76c8e7ae3ace.JPG)

**Comment by phecke** [comment]
@PTHugoPinto We are going to need to know the URL (address) of the documentation procedure you were following in order to determine who here can advise you. Please send us the web address of the documentation page that describes the process or feature that you are using. Thanks.

**Comment by PTHugoPinto** [comment]
Thanks for the answer
Link:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation will be updated soon. Please go to [Power Apps](https://make.powerapps.com) > Create > under *Start from template* select **Help Desk** canvas app template > follow the flow to create the Help Desk app from the default templates.
