### ISSUE TITLE
Select Query in SQL not returning a data when Filter is applied

### ISSUE THREAD

**Issue by ajithnairms** [MicrosoftDocs/powerapps-docs#2135]
[Enter feedback here]

When i perform a select query with filters, data is not returned until i write TOP 5 or something similar to fetch the records.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ead09d9-3e51-04ce-dc6e-ac9bb59816ec
* Version Independent ID: 94d19f8d-3c5e-8ed9-53ee-4b6173f49144
* Content: [Use SQL to query data (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#feedback)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/dataverse-sql-query.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@ajithnairms 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.
