### ISSUE TITLE
Description must be prefixed with *WEB* - Info box should be more prominent

### ISSUE THREAD

**Issue by damonfutter** [MicrosoftDocs/powerapps-docs#2136]
At the bottom of the page is a "note" box that tells you:

> Notes description must be prefixed with *WEB* ('WEB' keyword with an asterisk sign (*) before and after) in order to display on the portal.

This is a vital piece of information for anyone trying to show notes on a portal page, otherwise you just get a message to tell you that:

> There are no notes to display.

It should be given more prominence. For example, place it at the top of the page underneath the note that tells you that you need to give explicit entity permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434c988b-243e-0d01-e098-fa9a0300ae31
* Version Independent ID: e7b47bad-3195-2b6d-bef3-8c23b6fb58e8
* Content: [Configure notes as attachments on entity forms and web forms for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure-notes)
* Content Source: [powerapps-docs/maker/portals/configure-notes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure-notes.md)
* Service: **powerapps**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, documentation has been updated.
