### ISSUE TITLE
Add OData operations

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/powerapps-docs#2139]
Please add a link to  (or content of) these pages for achieving this with OData https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/underorequal?view=dynamics-ce-odata-9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6027337c-b613-84bd-bc5a-ed383bb813b7
* Version Independent ID: 4877b58d-6f69-45d2-9192-a04896ba5802
* Content: [Query hierarchical data (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/query-hierarchical-data#condition-operators-for-hierarchical-data)
* Content Source: [powerapps-docs/developer/data-platform/query-hierarchical-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/query-hierarchical-data.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@algattik 
Thanks for your feedback. I've added your note to a workitem to refresh this topic.
