### ISSUE TITLE
Diagram readability

### ISSUE THREAD

**Issue by spearsonwork** [MicrosoftDocs/powerapps-docs#2141]
Please redraw that diagram with better contrast so that it can be read easily. 
The black on red and blue under Authentication are almost unreadable for someone with perfect eyesight.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d4322e1-463a-ac81-32da-036adc71ef24
* Version Independent ID: d05a3e14-1868-2d19-ba02-77e1493af7a4
* Content: [Power Apps portals connectivity to a Microsoft Dataverse environment - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/connectivity)
* Content Source: [powerapps-docs/maker/portals/admin/connectivity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/connectivity.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and the feedback, will update the diagram soon.
