### ISSUE TITLE
entity is now table

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/powerapps-docs#2142]
Based on the fact that "Some terminology in Microsoft Dataverse has been updated. For example, entity is now table and field is now column" it would be great if this page can be updated to reflect the name changes. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eaca9c5-4bd8-edea-a454-8e11602cdd37
* Version Independent ID: 0c75fce8-0717-82a2-2742-9ec7cc35b25e
* Content: [Microsoft Dataverse entities - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/entities)
* Content Source: [powerapps-docs/developer/data-platform/entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/entities.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by Nkrb** [comment]
@MichaelWeberMSFT Thanks for reaching us. We are in the processing of updating the docs with the latest terminology changes. We are updating it in a phased manner. Closing the issue. If you need further help, please reopen or create a new issue.
