### ISSUE TITLE
Powerapps SQL Connection

### ISSUE THREAD

**Issue by excelgenius** [MicrosoftDocs/powerapps-docs#2143]
I have been trying to follow these instructions to connect to a local instance of SQL Server.  However, it only provided the option for a host name (localhost) and database name.

I have installed the local gateway.  I do not get the option to use the gateway or even to put in credentials.  I continue to get a bad gateway error.    Clearly I am missing something here, but unsure of the next steps to correct this problem.   Is there somewhere I need to configure to use the local gateway?  

Thanks for help.  Marc.

![image](https://user-images.githubusercontent.com/7407516/108732510-a17eff00-74fb-11eb-9f5e-b4dafca7aeca.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbcbf308-e9b9-d59d-5b1b-ba224dcc1aa9
* Version Independent ID: 5959353c-ab28-1bc6-8c21-3b186c1bf61d
* Content: [Overview of the SQL Server connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-azure-sqldatabase)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-azure-sqldatabase.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-azure-sqldatabase.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please use [Help&Support](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with investigation of this issue.
