### ISSUE TITLE
Unable to Paste Image from Desktop into Canvas App Rich Text Field using Chromium Based Browser

### ISSUE THREAD

**Issue by JoshFN-T** [MicrosoftDocs/powerapps-docs#2145]
I have a Rich Text field in a Canvas App where users will be able to paste an image from snipping tool (or equivalent).

However, I have come across the problem where it simply doesn't work if the users are using a chromium based browser (i.e edge or chrome); it does work if they are using Mozilla Firefox.

Reproduction Steps:
1: Open Canvas App with Rich Text Field, open one instance of the app in Google Chrome (or Edge) and another instance of the app in Firefox. 
2: Take a screenshot using Windows Snipping Tool and copy it
3: Paste the image into the Canvas app instances (both Chrome and Firefox)

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please use [Help&Support](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with additional investigation and issue fix.
