### ISSUE TITLE
PATCH not honoring SystemRequired metadata definition

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/powerapps-docs#2146]
Using a row using Dataverse api endpoint v9.2 allows setting null values to SystemRequired columns. 
In this same page, there is a note that says 

> "The metadata for attributes includes a RequiredLevel property. When this is set to SystemRequired, you cannot set these attributes to a null value."

Either this doc page is wrong or the enforcement is not yet in place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28a23cb-07dc-47c7-df41-18063abd8917
* Version Independent ID: 1b6fef34-9306-3784-87dc-36b3e7d27b0e
* Content: [Update and delete entities using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/update-delete-entities-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/update-delete-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/webapi/update-delete-entities-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Can you provide an example?
Some system required attributes are read-only, such as modifiedon, createdby. So I expect setting them to null would be ignored.

But if the attribute can be written to AND is system required, then attempting to set it to null would result in an error.

**Comment by nickbrandl** [comment]
Hi @JimDaly, I've tried updating contact lastname (which is mandatory) and also tried with emailaddress1 (after making it mandatory) and the request was accepted.

Here you have part of the request:
`curl --location --request PATCH 'https://xxxx.crm4.dynamics.com//api/data/v9.2/contacts(2a90e22c-ae76-eb11-a812-000d3ab25b1c)' \
--header 'Authorization: Bearer xxxxxBu6Q4JE5BA' \
--header 'Content-Type: application/json' \
--header 'Cookie: ARRAffinity=4cba78deb061bdf4cbf2c19d9c5f7f03ba03966887ab7139651337e843b85150; ReqClientId=fbcb6a84-97d0-4c21-9aa3-699dc3c23003; last_commit_time=2021-02-24 17:57:07Z; orgId=017b058c-dada-4e46-a448-34783a1cf089' \
--data-raw '{
    "firstname":"Nick",
    "lastname":"",
    "emailaddress1":null
}'`

Response to this request was 204.

**Comment by JimDaly** [comment]
There are 4 levels of requirement as described here: [AttributeRequiredLevel EnumType](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/attributerequiredlevel?view=dynamics-ce-odata-9) and here [AttributeRequiredLevel Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.attributerequiredlevel?view=dynamics-general-ce-9). 

As a customizer, you can only set the value to `ApplicationRequired`, which means that the app (canvas or model) will enforce this for you. API assumes you know what you are doing and will not block you here. 

A `SystemRequired` attribute is defined by the system. You can't make an attribute system required. Contact.LastName and Contact.EmailAddress 1 can only be set to `ApplicationRequired`. For contact, `SystemRequired` attributes include ContactId, OwnerId, and StateCode. You cannot set these to null.

**Comment by nickbrandl** [comment]
Thank you @JimDaly . I guess I missed that part of the application required being different than system required :(

Just in case, tried to set ownerid to null and it failed:
`{
    "error": {
        "code": "0x80040203",
        "message": "Attribute: ownerid cannot be set to NULL"
    }
}`
