### ISSUE TITLE
Confusing example

### ISSUE THREAD

**Issue by kowgli** [MicrosoftDocs/powerapps-docs#2147]
Why does it say "Floating Point" in the list of types, but "FP" in the example? Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efe6fa9-da68-6c6e-25db-1845bb901e78
* Version Independent ID: 903e3d32-b517-8ca0-c738-a0af6a55151f
* Content: [Type Group Element - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/type-group)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/type-group.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/type-group.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@kowgli Thanks for reaching us. We have fixed the issue that is confusing and will push docs to live in the next scheduled build. Closing the issue. If you need further help, please reopen or create a new issue.
