### ISSUE TITLE
ButtonType missing from properties

### ISSUE THREAD

**Issue by drinklikachamp** [MicrosoftDocs/powerapps-docs#2148]
While creating an app in Teams, I came across a button property called ButtonType, however I do not see any documentation on this page about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1567d77-110a-348b-614d-60016845cafd
* Version Independent ID: 0bc34ed1-625f-f681-dcd3-5922d3e62ca8
* Content: [Button control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-button)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-button.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-button.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there,

The new Fluent UI controls in teams have their own reference: [https://docs.microsoft.com/en-us/powerapps/teams/use-the-fluent-ui-controls](https://docs.microsoft.com/en-us/powerapps/teams/use-the-fluent-ui-controls)

Hope this helps.

Cheers,
CM

**Comment by chmoncay** [comment]
We've also included a table of changes from the "classic" controls.

[https://docs.microsoft.com/en-us/powerapps/teams/use-the-fluent-ui-controls#difference-between-fluent-ui-and-classic-controls](https://docs.microsoft.com/en-us/powerapps/teams/use-the-fluent-ui-controls#difference-between-fluent-ui-and-classic-controls)

**Comment by drinklikachamp** [comment]
Thank you @chmoncay . I didn't realize the Power Apps for Teams used different controls. Thanks.
