### ISSUE TITLE
The documentation does not tell what minimum privileges are needed for the security role of a Help pane "consumer"

### ISSUE THREAD

**Issue by GiniMendes** [MicrosoftDocs/powerapps-docs#2151]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a092a285-0b74-af20-214d-09409c712bf2
* Version Independent ID: 5cd8e6f2-7c17-2a6b-1584-70584495bca9
* Content: [Create custom help pages - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-custom-help-pages#custom-help-panes-and-learning-path)
* Content Source: [powerapps-docs/maker/data-platform/create-custom-help-pages.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/create-custom-help-pages.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@GiniMendes - thank you for your feedback. The article has been revised to include the below information: 
## Privileges required
- To author help panes, app makers need global create, read, write, delete, append, and append to privileges on the Help Page table. By default, System Administrator and System Customizer security roles both have this privilege.
- To view help panes in an app, users need read privilege on the Help Page table. By default, the Help Page Consumer security role has this privilege. By default, the Basic User security role doesn’t have any privileges on the Help Page table.

Closing issue.
