### ISSUE TITLE
Power BI Embedded Hide Page Navigation

### ISSUE THREAD

**Issue by WinstonHenry** [MicrosoftDocs/powerapps-docs#2153]
Hi everyone,

is it possible to use attribute navContentPaneEnabled=false to hide the pages tab when embedding a report as described [Here](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embed-powerbi-report-in-system-form#embed-with-contextual-filtering), please?

It seems as if we don't have enough control when embedding reports the way it is described in the link, as opposed to using the built-in embedding links and simply appending this attribute to the URL as a parameter, or when constructing our own json config web using javascript API.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715bc26c-2ccd-a040-3c96-d73cde4b982b
* Version Independent ID: c793e872-29e4-2e04-b9f4-973c01d4a123
* Content: [Embed a Power BI report in a model-driven system form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embed-powerbi-report-in-system-form#prerequisites)
* Content Source: [powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by adrianorth** [comment]
Adding @Mark Spilde<mailto:mspilde@microsoft.com> and @Monisha Rochlani<mailto:moroch@microsoft.com> to this question.  I didn't know the answer and it will require some investigation.
________________________________

**Comment by adrianorth** [comment]
We don't currently support setting navContentPaneEnabled, so it will always be enabled.

-m
