### ISSUE TITLE
Suppress Duplicate Detection Not working - API

### ISSUE THREAD

**Issue by culpgrant** [MicrosoftDocs/powerapps-docs#2154]
Hey I am trying to use the 
`
MSCRM.SuppressDuplicateDetection: true
`
the parameter in my code to create a record even if it has a duplicate. It is not working and the response I am getting is the same "A record was not created or updated because a duplicate of the current record already exsists".

Here are my full headers:
`
{
    "Authorization": BEARER,
    "Content-Type": "application/json; charset=utf-8",
    "If-None-Match": "null",
    "OData-MaxVersion": "4.0",
    "OData-Version": "4.0",
    "Accept": "application/json",
    "MSCRM.SuppressDuplicateDetection":"true",
    "return": "representation"
}
`

If anyone can help me that would be helpful because the documentation says this is possible so I must be doing something wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a48217ac-43b9-cefb-70bf-163c82175080
* Version Independent ID: 70af49c3-2b41-bbde-235c-d348b2f47a2d
* Content: [Detect duplicate data using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/manage-duplicate-detection-create-update)
* Content Source: [powerapps-docs/developer/data-platform/webapi/manage-duplicate-detection-create-update.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/webapi/manage-duplicate-detection-create-update.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@culpgrant What type of entity are you creating?

**Comment by culpgrant** [comment]
@phecke I am qualifying a lead to create a new contact.
I have duplicate detection rules on contacts but just trying to suppress them and get through the duplicate detection.

Here is my full code:

```
    api_surpress_dup_detection_headers = {
    "Authorization": BEARER,
    "If-None-Match": None,
    "OData-Version": "4.0",
    "OData-MaxVersion": "4.0",
    "Content-Type": "application/json",
    "Accept": "application/json",
    "MSCRM.SuppressDuplicateDetection": "true"
}

lead_qualify_url = f"{data_url}leads({lead_guid})/Microsoft.Dynamics.CRM.QualifyLead"
data = {
    'CreateAccount': False,
    'CreateContact': True,
    'CreateOpportunity':False,
    'Status':3
}
qualify_lead_response = requests.post(lead_qualify_url, headers=api_surpress_dup_detection_headers, data=json.dumps(data))

```

The return is still:
<Response [412]> '{"error":{"code":"0x80040333","message":"A record was not created or updated because a duplicate of the current record already exists."}}'

**Comment by phecke** [comment]
@culpgrant I will pass this to the product engineering team to see if they have an answer. I cannot see anything wrong with what you are doing. It seems that `MSCRM.SuppressDuplicateDetection: true` is not being honored.

My guess is that there may be an admin level environment setting that is affecting duplicate detection.

**Comment by culpgrant** [comment]
Awesome thank you @phecke I will continue to do more research online. But yeah when I include the `MSCRM.SuppressDuplicateDetection: true` it does not change the response at all

**Comment by JimDaly** [comment]
It also looks like you are using it correctly. Nothing actionable for the documentation. Recommend you open a support ticket. If it is a bug, they can escalate and we will fix it.

**Comment by phecke** [comment]
@culpgrant Perhaps check your environment's duplicate detection settings:
[https://docs.microsoft.com/en-us/power-platform/admin/enable-improved-duplicate-detection](https://docs.microsoft.com/en-us/power-platform/admin/enable-improved-duplicate-detection)

**Comment by culpgrant** [comment]
@phecke 
Hey, so I ended up finding the issue with what I was doing. The parameter needs to be included in both the header and the data you are sending. Here is the [StackOverflow ](https://stackoverflow.com/questions/66389963/python-dynamics-crm-web-api-suppressduplicatedetection-not-working/66482425#66482425) with the answer. 

It might be worth including on the Documentation for the [Qualifying Lead Action](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/qualifylead?view=dynamics-ce-odata-9) or on the [Suppress Duplicate Detection](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/manage-duplicate-detection-create-update)

Thanks for your help!
