### ISSUE TITLE
Please improve warning about apps on by default that might bypass an org's governance

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/powerapps-docs#2155]
Please could Teams admin be alerted to when new apps appears in the Teams app store? Better still if they could appear with a workflow that asked 'allow, block or investigate'. I'm reading online about other IT Pros with a Teams Dataverse problem. We are trying to improve our governance of M365 and some of the changes make a mockery of this. I'm sure it's not malicious but it does undermine our efforts. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 887bc09c-a4fe-d836-4532-026e25a875b4
* Version Independent ID: cbd33cd7-6ddd-f912-10fb-eb5e673bc1e0
* Content: [Use sample apps from teams store - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/use-sample-apps-from-teams-store?s=09#available-sample-apps)
* Content Source: [powerapps-docs/teams/use-sample-apps-from-teams-store.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/use-sample-apps-from-teams-store.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please submit an idea in the [Power Apps ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) so this request can be voted for, and be considered.
