### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by ErickTreetops** [MicrosoftDocs/powerapps-docs#2158]
"Prerequisites
To author custom help panes, you need the following:

Version 9.1.0.10300 or later."

What are you referring to here ?  Is this the version of Microsoft Dynamics, which can be found under the Grear icon ?

**Comment by Nkrb** [comment]
@ErickTreetops We are referring to the version of you environment. Yes, you can select the gear icon and then select **About** to see the version. Closing the issue. If you need further help, please reopen or create a new issue.
