### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by bishalgoswami** [MicrosoftDocs/powerapps-docs#2159]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 923f06c4-5ce1-10c3-e89a-d1bfa8777a5e
* Version Independent ID: 37f9cdfe-8607-d8ee-48f7-8010c069e367
* Content: [Canvas app execution phases and data call flow - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/execution-phases-data-flow)
* Content Source: [powerapps-docs/maker/canvas-apps/execution-phases-data-flow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/execution-phases-data-flow.md)
* Service: **powerapps**
* GitHub Login: @JinManAhn-MSFT
* Microsoft Alias: **jiahn**

**Comment by Mattp123** [comment]
@bishalgoswami - Closing this issue. Reopen if needed or create a new one.
