### ISSUE TITLE
Can't get SearchUserV2 to work! 2649845

### ISSUE THREAD

**Issue by rrkushner** [MicrosoftDocs/powerapps-docs#2160]
I can't get any of these to work:

Office365Users.SearchUserV2({searchTerm: SearchTerm.Text})

Office365Users.SearchUserV2({searchTerm: "MyEmail@gmail.com"})

Office365Users.SearchUserV2({Mail: "MyEmail@gmail.com"})

Office365Users.SearchUserV2({Email: "MyEmail@gmail.com"})

Could you possibly give a real life example how it looks in the code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9434b232-2bf5-14f0-9861-6726dc216b96
* Version Independent ID: d073f002-01ac-541b-d365-60affab50cae
* Content: [Overview of the Office 365 Users connection - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-office365-users)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-office365-users.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Apologies for the delayed response; the documentation has been updated with example. Changes will reflect in the documentation soon.
