### ISSUE TITLE
Importing the app is not working

### ISSUE THREAD

**Issue by workderrek** [MicrosoftDocs/powerapps-docs#2161]
I followed the directions precisely. 

![image](https://user-images.githubusercontent.com/79885324/109585611-6e270c00-7ac9-11eb-9b91-140500ff23bb.png)

When I select Open app, I receive this error:

![image](https://user-images.githubusercontent.com/79885324/109585720-a4fd2200-7ac9-11eb-8d8e-c322efcbcaf8.png)

Interestingly, I am able to play the app:

![image](https://user-images.githubusercontent.com/79885324/109585799-c5c57780-7ac9-11eb-8598-d2942e00c2be.png)

but I am any attempt to edit gives me the previous error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install#download-the-app)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by bradtoune** [comment]
I'm having this problem as well, unable to edit the app at all to point it to my SharePoint list.  Has there been any resolution for this?

**Comment by mvwright12** [comment]
Same problem here with same error message. Seems like same issue as ticket #2114.

**Comment by mvwright12** [comment]
SOLUTION - I was able to build a zip file duplicating the original but that doesn't throw an error. All same content just different file structure to work with recent PowerApps changes. It's attached here:
[HelpDeskUPDATED.zip](https://github.com/MicrosoftDocs/powerapps-docs/files/6118426/HelpDeskUPDATED.zip)

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated recently, please refer to the updated documentation.
