### ISSUE TITLE
New File attribute type is shown as read-only in forms but it's not set as readonly

### ISSUE THREAD

**Issue by Suxsem** [MicrosoftDocs/powerapps-docs#2162]
We just discovered a serious bug with the new "file" attribute type of Dataverse regarding model-driven apps.

If you add a file field in **other tabs of the form other then the first one**, sometimes the field is shown as read-only **also if it is not set as read-only** (just refresh the page a couple of times to see the bug).

![image](https://user-images.githubusercontent.com/830773/109784285-37f1a580-7c0b-11eb-9760-33599403a7a2.png)

![image](https://user-images.githubusercontent.com/830773/109784322-42ac3a80-7c0b-11eb-819b-717a94c4950e.png)

I also noticed that the field is shown as locked in the make.powerapps.com editor (see the first image) but this is not a big deal because it's just the editor. The real issue there is that as I said sometimes the field is shown as read-only also in the CRM itself. (see the second image).

We were able to reproduce the issue in different environments, without any customization added to them.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8f3598c-cd0e-2cd8-fa6b-5663f63c36bf
* Version Independent ID: 656dca2a-e65d-fdb9-545e-b73d906ce4f1
* Content: [Column data types in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/types-of-fields)
* Content Source: [powerapps-docs/maker/data-platform/types-of-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/types-of-fields.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by NHelgren** [comment]
Hi @Suxsem, In the scenario above, is File showing as Read Only on a new record that is being created and not yet saved? Model forms require a record to be saved before a file can be attached.

**Comment by Suxsem** [comment]
@NHelgren no, as you can see from the screenshot the issue happens on already created records too.

**Comment by NHelgren** [comment]
Thanks @Suxsem, in the screenshots I couldn't tell if the record had been saved or not yet.  I will follow up with the teams on this.

**Comment by Suxsem** [comment]
@NHelgren thank you! Please keep us posted, thanks :)

**Comment by Mattp123** [comment]
Closing issue.

**Comment by Suxsem** [comment]
@Mattp123 why it has been closed?
