### ISSUE TITLE
broken link in info box

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/powerapps-docs#2163]
[Scenarios notification box](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/define-calculated-fields#scenarios)
"To create a calculated column you must have the Write privilege on the **Column Security Profile table.**"
linked to https://docs.microsoft.com/en-us/powerapps/developer/data-platform/reference/tables/columnsecurityprofile

Link is broken or not available to me (404 - Page not found)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f212137-6b88-c06c-025d-c05e6b74c10f
* Version Independent ID: 61abe448-2b0d-29bd-90bb-63899f0f92dc
* Content: [Define calculated columns in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/define-calculated-fields)
* Content Source: [powerapps-docs/maker/data-platform/define-calculated-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/define-calculated-fields.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Hjaf - Thanks for bringing this to our attention. The link has been fixed and will be published live in a few hours.
