### ISSUE TITLE
 Common Data Servce (beta) is now called Dataverse?

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/powerapps-docs#2164]
The Data source names in Power BI Desktop have changed, I think Common Data Servce (beta) is now called Dataverse and the right one to pick for connecting to Dataverse for Teams.

![image](https://user-images.githubusercontent.com/55705669/109802410-adfc0980-7c17-11eb-95fe-77ff71519bad.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd540f56-483a-72c0-ec0a-10fd11f25e79
* Version Independent ID: a54faf86-952d-59ad-66a7-0098f54e3234
* Content: [View Dataverse for Teams table data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/view-table-data-power-bi#feedback)
* Content Source: [powerapps-docs/teams/view-table-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/view-table-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by Mattp123** [comment]
@manuelap-msft - yes you are correct and to match the current naming (it took awhile). Closing issue.
