### ISSUE TITLE
Wrong link in "Create a security role for your app" section (loopback)

### ISSUE THREAD

**Issue by luconsta** [MicrosoftDocs/powerapps-docs#2165]
Hello,

I think there is a mistake in the following section:

> Create a security role for your app
> Generally model-driven apps contain custom tables and other custom configuration. It's important to first create a security role with permission for all the components used in your app.

The link provided on text "create a security role" => https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/share-model-driven-app#create-a-security-role-for-your-app is in fact a "loopback" - a better link to use for it, is provided on the end of the document on the "See also" section: [Create users and assign security roles](https://docs.microsoft.com/en-us/power-platform/admin/create-users-assign-online-security-roles)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4549b49b-30e8-c879-39a4-dab18142c213
* Version Independent ID: 8a4a64ea-979f-c4e2-94f0-dd7311b660a4
* Content: [Share a model-driven app using Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/share-model-driven-app#create-a-security-role-for-your-app)
* Content Source: [powerapps-docs/maker/model-driven-apps/share-model-driven-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/share-model-driven-app.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@luconsta - thank you for bringing this to our attention. The link has been revised to point to the section within the article that describes how to create a custom security role.
