### ISSUE TITLE
How to remove Portal configuration records if removed in source?

### ISSUE THREAD

**Issue by KimBon** [MicrosoftDocs/powerapps-docs#2167]
When working in a development portal environment, you might create pages and deploy them to the next environment using Configuration Migration utility.
However, if you remove certain configurations (you remove a web template, or so), how does this get removed in the target environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7fa454-57bc-86bf-74cd-c51b622607a4
* Version Independent ID: 3efa0e3c-d9f2-cc50-aa9d-f77f2ca7dc3f
* Content: [Migrate portal configuration - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/migrate-portal-configuration)
* Content Source: [powerapps-docs/maker/portals/admin/migrate-portal-configuration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/migrate-portal-configuration.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Since it's the data that's updated, it's always add operation. Remove operation needs to be performed manually on the destination.
