### ISSUE TITLE
Byte Data Types?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#2171]
Some connectors require the content to be encoded as `bytes`.
**Example:** [Service Bus Connector](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types)

How do you get data into byte format?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b42181e-8538-95bb-c2f6-233fb545f3fd
* Version Independent ID: 1f1bb49a-5984-e464-c881-013b79328d30
* Content: [Data types - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/data-types.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/data-types.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Lance, looks like the [Content parameter for SendMessage takes a Byte array](https://docs.microsoft.com/en-us/connectors/servicebus/#send-message)
).  I don't know if properly coerce from a string to this type, can you check?

We have no intention of adding a Byte data type.

**Comment by lancedMicrosoft** [comment]
Hi Greg,

Sagar and chatted and Sagar did a quick look at the code.  It looks like, when we get the meta-data if it's a string type we do a check to see if there is a subtype that is coming through and byte is one of those cases we handle.  We 64bit encode it.   Not sure exactly why this would be the case for the message content of a service bus call.

Lance


Note: My working hours may not coincide with your working hours.  Please do not feel compelled to respond right away if you receive mail from me outside of your normal working hours.
