### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sillysod** [MicrosoftDocs/powerapps-docs#2172]
There is a broken link in the following line

After you download the solution, you must install it. For information about how to install a managed solution, see **Import solutions**

Url https://docs.microsoft.com/en-us/powerapps/developer/data-platform/import-update-export-solutions gives a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d70291-28f8-f1d2-35d5-ccce1e24d089
* Version Independent ID: cf1d66c6-aa7e-03ab-3955-d6f41f45a870
* Content: [Browse the metadata for your organization (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/browse-your-metadata)
* Content Source: [powerapps-docs/developer/data-platform/browse-your-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/browse-your-metadata.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@sillysod  Looks like the text has been revised in the latest version of the article and the link removed. Thanks.
