### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by prawinpv** [MicrosoftDocs/powerapps-docs#2174]
The expense app upon installing opens fine. However, if I try to edit its throwing an error "Something went wrong while opening your app". There's no further details.
![Powerapps error](https://user-images.githubusercontent.com/45082396/110387655-2a7b5780-801f-11eb-8e27-c48db0af37d9.JPG)

Regards,
Praveen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install#prerequisites)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated recently, please refer to the updated documentation.
