### ISSUE TITLE
Multiselect fields cascading dropdown values not working

### ISSUE THREAD

**Issue by SagaTeja** [MicrosoftDocs/powerapps-docs#2178]
Hello, I have a requirement that there is cascading dropdown with multiple select fields.
Where I the values of multipleselected field of combobox values are not saving.
My query is the powerapps supports cascading dropdown for multipleselect combobox field

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Please reach out to support teams using [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with the issue investigation.
