### ISSUE TITLE
Create solution patches hyperlink is broken

### ISSUE THREAD

**Issue by subhankars** [MicrosoftDocs/powerapps-docs#2179]
Hyper link for **Create solution patches** is broken under See also section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dda8ad9-01d8-aa29-704a-c8f13868a350
* Version Independent ID: ef98dcae-9534-425c-1e27-7255228af17f
* Content: [Update a solution - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/update-solutions)
* Content Source: [powerapps-docs/maker/data-platform/update-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/update-solutions.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@subhankars - thank you for posting this issue. The link has been fixed in the article and will be published live in a few hours. Closing issue.
