### ISSUE TITLE
The Import Solutions link navigates to a 404

### ISSUE THREAD

**Issue by CalvinQuark** [MicrosoftDocs/powerapps-docs#2180]
The Import Solutions link navigates to a 404 Page Not Found page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d70291-28f8-f1d2-35d5-ccce1e24d089
* Version Independent ID: cf1d66c6-aa7e-03ab-3955-d6f41f45a870
* Content: [Browse the metadata for your organization (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/browse-your-metadata)
* Content Source: [powerapps-docs/developer/data-platform/browse-your-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/browse-your-metadata.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@CalvinQuark I am not seeing that broken link in the article now. Perhaps someone else already removed it. Thanks
