### ISSUE TITLE
There is an prerequisite missing for this integration to work

### ISSUE THREAD

**Issue by gmndrg** [MicrosoftDocs/powerapps-docs#2181]
We have confirmed by testing and calls performed by PowerApps to the management.azure.com endpoint when trying to configure this, that Read permissions are needed also in the Resource Group where the storage account is located, for the storage account(s) to be visible and ready to be selected. Even if the account performing the integration has owner permissions over the storage accounts, they're not visible at the time they have to be selected from PowerApp.

Please correct the documentation to reflect this. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19489d66-04a5-73a7-ed5e-6a7f83290687
* Version Independent ID: f1ad4134-09ed-7683-2715-b6dda1ff8682
* Content: [Export to data lake - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake#prerequisites)
* Content Source: [powerapps-docs/maker/data-platform/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Closing issue.
