### ISSUE TITLE
Unable to add msdyn_purchaseorderbill to Solution package

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#2182]
When trying to add an existing table to my solution package I am unable to add the Bills table to it. The schema name is called msdyn_purchaseorderbill and does not appear in the search either.

![image](https://user-images.githubusercontent.com/8151045/110562063-ac41b280-80fd-11eb-9ba1-5649eb36c540.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b903798-2033-be36-079a-babe7586981e
* Version Independent ID: d588611a-a950-134e-6738-10e8f3899f25
* Content: [Tables and metadata in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-edit-metadata)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/create-edit-metadata.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@gregdegruy - Is the table a managed table? If so, you won't be able to add it to a solution. Closing issue.
