### ISSUE TITLE
errorCode values

### ISSUE THREAD

**Issue by jason-russell** [MicrosoftDocs/powerapps-docs#2184]
What are the available options for `errorCode`?

> If you just set errorCode, the message for the error code is automatically retrieved from the server and displayed in the error dialog. If you specify an invalid errorCode value, an error dialog with a default error message is displyed.

Doesn't have to be on this page, but would be nice to at least have a link in the "Related Topics" section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea3c9c94-1f26-c3a4-8789-3b0cef9f1e6b
* Version Independent ID: fe0311f8-20c5-5ddb-a618-2ead070afb80
* Content: [openErrorDialog (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openerrordialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openErrorDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openErrorDialog.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@jason-russell 
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen the issue or open a new issue.
