### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by devudu** [MicrosoftDocs/powerapps-docs#2185]
Two links under see also section are broken

Developer Documentation: Define alternate keys for a table
Developer Documentation: Use an alternate key to create a row

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c399da5-9b45-328d-bb82-35a523738005
* Version Independent ID: 09e4c277-0c30-6436-0445-c7797c1f0e45
* Content: [Define alternate keys to reference rows with Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/define-alternate-keys-reference-records?WT.mc_id=DX-MVP-5003800)
* Content Source: [powerapps-docs/maker/data-platform/define-alternate-keys-reference-records.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/define-alternate-keys-reference-records.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@devudu - thank you for posting this issue. The links have been fixed and will be live in a few hours.

Closing issue.
