### ISSUE TITLE
Can we have the option to choose what specific fields/columns in an entity can go to Data lake?

### ISSUE THREAD

**Issue by anilvem1** [MicrosoftDocs/powerapps-docs#2188]
It would be a great feature if customer can choose what columns to go to Data lake in an Entity/Table instead of all columns by default? Is this something in the roadmap?
Also what is the roadmap for Data Export Service which exports the data into Azure SQL DB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19489d66-04a5-73a7-ed5e-6a7f83290687
* Version Independent ID: f1ad4134-09ed-7683-2715-b6dda1ff8682
* Content: [Export to data lake - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake)
* Content Source: [powerapps-docs/maker/data-platform/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sabinn-msft** [comment]
Filtering columns is not supported at this time. This is something we could consider for the future. We are encouraging all customers to use Export to data lake.

**Comment by Mattp123** [comment]
Closing issue.
