### ISSUE TITLE
No FetchXml examples and documentation confusing

### ISSUE THREAD

**Issue by KaineVarley** [MicrosoftDocs/powerapps-docs#2190]
Hi,

With regards to the [retrieveMultipleRecords (Client API reference)](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords) page:

1. The page makes 3 references to the use of fetchXml attribute but doesn't provide any examples
2. One reference specifically states: _"When you specify a FetchXML query for the options parameter, the query **should not be encoded**."_, and yet every user post I have found through online searches makes use of **encodeURIComponent(fetchXml)**. This is really confusing.

Please update the documentation. I think that it's been [out of date for some time now](https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/issues/985).

Thanks,

Kaine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c196bb-4bbb-80e2-0bba-42d130621024
* Version Independent ID: 56d1575c-1868-34c6-992d-e3797024e413
* Content: [retrieveMultipleRecords (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
