### ISSUE TITLE
Unable to automatically provision Power Platform environments using PowerShell

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftDocs/powerapps-docs#2193]
In preparation for a MOC training, I have to automatically provision a handful of Power Platform environments in a single Tenant. I am using a specific PowerShell script, which makes use of the "Microsoft.PowerApps.Administration.PowerShell" and "Microsoft.PowerApps.PowerShell" cmdlets. Here I have a permanent issue, which makes it impossible to proceed. In order to locate the root cause, I am using the following set of commands:

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
dir . | Unblock-File
Install-Module -Name Microsoft.PowerApps.Administration.PowerShell
Install-Module -Name Microsoft.PowerApps.PowerShell -AllowClobber
Add-PowerAppsAccount

The last PowerShell command is the one which is always causing the issue in whichever context. Here is the outcome:

![image](https://user-images.githubusercontent.com/35074341/111070634-e7176200-84d2-11eb-8b71-e8e9c72185a1.png)

**Comment by Nkrb** [comment]
@RobertRybaric Can you provide us the link to the doc that you are following to create environments using PowerShell, so that we can assign it to right writer to look into the issue.

**Comment by RobertRybaric** [comment]
> @RobertRybaric Can you provide us the link to the doc that you are following to create environments using PowerShell, so that we can assign it to right writer to look into the issue.

Hi @Nkrb , it is the HOL guidance to the MB-600 training and in particular the tenant setup document: https://github.com/MicrosoftLearning/MB-600-Dynamics-365-Power-Platform-Solution-Architect/blob/master/TenantSetup.md

I tried to use the script Setup.ps1 mentioned in the above guidance, but with no success. I have made a handful of other experiments to find the root cause, and it seems, that the PowerShell command Add-PowerAppsAccount is failing for me in every situation. It is worth mentioning, that I have always installed the latest versions of all the respective cmdlets and used any other hints I could find, always with the same result.

**Comment by Nkrb** [comment]
@RobertRybaric Can you reach out to the authors for that repo. We only handle issues related to the content specified in the docs.

**Comment by RobertRybaric** [comment]
> @RobertRybaric Can you reach out to the authors for that repo. We only handle issues related to the content specified in the docs.

I have done this already, but the authors do not seem to handle the issues. There are 5 open issues in the repo and no one takes care of those issues.

**Comment by tapanm-MSFT** [comment]
Please go to https://cdx.transform.microsoft.com/ -> Help -> Get Help -> Submit request -> Enter information about the issue to get help. Power Apps docs issues are only for Power Apps documentation changes.
