### ISSUE TITLE
Link in the "See Also" section is no longer working

### ISSUE THREAD

**Issue by akill25445** [MicrosoftDocs/powerapps-docs#2194]
[Enter feedback here]
The following link is no longer working 
CRM Team Blog: Thread Safety in Plug-ins
https://blogs.msdn.com/b/crm/archive/2008/11/18/member-static-variable-and-thread-safety-in-plug-in-for-crm-4-0.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46aca615-520e-aa4d-22a4-62a7c3c18db8
* Version Independent ID: b812c8cf-a8d4-153d-5e81-c4b83e14d637
* Content: [Develop IPlugin implementations as stateless - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment]
@akill25445  Fixed broken link. Will be re-published later today. Thanks
