### ISSUE TITLE
Number of environment is incorrect

### ISSUE THREAD

**Issue by JMountainFrame** [MicrosoftDocs/powerapps-docs#2197]
[This page] (https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare) has some outdated info:
...
Whereas Dataverse for Teams focuses on one environment per team for up to 500 teams, Dataverse supports unlimited environments in addition to capabilities that are relevant for multiple environments, such as copy and reset.
...

according to this blogpost:
https://powerapps.microsoft.com/en-us/blog/more-environments-more-places-and-more-capabilities-when-you-need-them/

It should be something like:

Whereas Dataverse for Teams focuses on one environment per team for up to 10 000 teams. Dataverse supports unlimited environments in addition to capabilities that are relevant for multiple environments, such as copy and reset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16e0d50-176d-2c1c-7821-a806efd079e3
* Version Independent ID: d8dc6656-383d-6f1e-8e47-350e4c206d7c
* Content: [Dataverse for Teams vs. Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare)
* Content Source: [powerapps-docs/teams/data-platform-compare.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/data-platform-compare.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@JMountainFrame - the article has been updated to reflect 10,000 teams. https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare#environments

Closing issue.
