### ISSUE TITLE
Wrong reference to example

### ISSUE THREAD

**Issue by BerndKroon** [MicrosoftDocs/powerapps-docs#2198]
[Enter feedback here]
The text says:

>  For an example of delegable functions, consider an ID column defined as the Number data type in a SharePoint list. Formulas in the following example will return the results as expected. However, the **first** formula is non-delegable while the **second** is delegable.

The use of **first** and **second** should be interchanged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7d6ebf-7d17-44ef-4348-354a8332081b
* Version Independent ID: 8427e65c-bf62-86c4-89b8-ecf5f59a890e
* Content: [Tips to improve canvas app performance - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/performance-tips)
* Content Source: [powerapps-docs/maker/canvas-apps/performance-tips.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/performance-tips.md)
* Service: **powerapps**
* GitHub Login: @yingchin
* Microsoft Alias: **yingchin**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. First example is delegable, second is not, as seen in the table below this statement; see **Delegable?** column in the table for values.
