### ISSUE TITLE
"pay wall" limit of Dataverse for Teams to be 500 enviroments, this is not true any longer

### ISSUE THREAD

**Issue by iiu-dk** [MicrosoftDocs/powerapps-docs#2199]
this page list the "pay wall" limit of Dataverse for Teams to be 500 enviroments, this is not true any longer, see here
https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#:~:text=Conceptual%20model%20%20%20%20Feature%20%20,(refer%20to%20Ad%20...%20%20%20Yes

please update this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16e0d50-176d-2c1c-7821-a806efd079e3
* Version Independent ID: d8dc6656-383d-6f1e-8e47-350e4c206d7c
* Content: [Dataverse for Teams vs. Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare)
* Content Source: [powerapps-docs/teams/data-platform-compare.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/data-platform-compare.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@iiu-dk - Sorry for the delay. This was updated last month per the below: 

Whereas Dataverse for Teams focuses on one environment per team for up to 10,000 teams, Dataverse supports unlimited environments in addition to capabilities that are relevant for multiple environments, such as copy and reset.

Closing issue.
