### ISSUE TITLE
Not All GeoJSON geometry types supported.

### ISSUE THREAD

**Issue by bthomas89** [MicrosoftDocs/powerapps-docs#2200]
The documentation references the Wikipedia page for GeoJSON, but fails to mention that the only geometry types supported by this feature is the polygon and point.  LineStrings appear not to be supported, despite valid geoJSON input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24397d08-e58b-0bdc-246d-874fd1f4bd38
* Version Independent ID: fc6d44ce-fcb1-0c60-659a-c295cab5a785
* Content: [Let users draw and insert shapes into maps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/geospatial-map-draw-shapes)
* Content Source: [powerapps-docs/maker/canvas-apps/geospatial-map-draw-shapes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/geospatial-map-draw-shapes.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for the feedback - I'm just confirming with our PMs/devs and will update the docs accordingly.
