### ISSUE TITLE
Backslash used to refer to Forward Slashes

### ISSUE THREAD

**Issue by ChrisGrohHS** [MicrosoftDocs/powerapps-docs#2201]
This documentation page refers to "backslash" but should probably be changed to be "forward slash" or simply "slash". Backslashes `\` are not valid in web resource names. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f2e23f-87e2-62be-f107-08c2e99b97e5
* Version Independent ID: 03aa8ec3-a827-95cf-d7cf-f0a014c3484b
* Content: [GetGlobalContext function and ClientGlobalContext.js.aspx in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ChrisGrohHS Thanks for contacting us. We have updated the docs. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
