### ISSUE TITLE
Describe/Explain the purpose of DataProvider and Data Source is

### ISSUE THREAD

**Issue by shahabhijeet** [MicrosoftDocs/powerapps-docs#2202]
It would be great if we can provide description and explain what is the role of a DataProvider and Data Source.
A section that explains, what is the purpose of Dataprovider and DataSource, why do we need both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42ae2cb6-ce2a-21c7-cb81-b60e7b026753
* Version Independent ID: 5a3cb7c0-6881-1d96-0dc3-639324a4568c
* Content: [Get started with virtual entities (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/get-started-ve)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by Sunil-Garg** [comment]
+ @***@***.***>

From: Abhijeet ***@***.***>
Sent: Monday, March 15, 2021 3:01 PM
To: MicrosoftDocs/powerapps-docs ***@***.***>
Cc: Sunil Garg ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/powerapps-docs] Describe/Explain the purpose of DataProvider and Data Source is (#2202)


It would be great if we can provide description and explain what is the role of a DataProvider and Data Source.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 42ae2cb6-ce2a-21c7-cb81-b60e7b026753
  *   Version Independent ID: 5a3cb7c0-6881-1d96-0dc3-639324a4568c
  *   Content: Get started with virtual entities (Microsoft Dataverse) - Power Apps<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowerapps%2Fdeveloper%2Fdata-platform%2Fvirtual-entities%2Fget-started-ve&data=04%7C01%7Csunilg%40microsoft.com%7C1b9db14d25f14a9fde9808d8e7fdc20c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637514424362709525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LqNctuZJejsDwF6Vi3tT%2BxscRE5J83UiKvJpG4vaDvM%3D&reserved=0>
  *   Content Source: powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerapps-docs%2Fblob%2Flive%2Fpowerapps-docs%2Fdeveloper%2Fdata-platform%2Fvirtual-entities%2Fget-started-ve.md&data=04%7C01%7Csunilg%40microsoft.com%7C1b9db14d25f14a9fde9808d8e7fdc20c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637514424362719518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w%2BXb3zP%2FJRr%2FR4rt1deg1uD8ZiyqZ71ee65r%2FEO9U8E%3D&reserved=0>
  *   Service: powerapps
  *   GitHub Login: @Sunil-Garg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunil-Garg&data=04%7C01%7Csunilg%40microsoft.com%7C1b9db14d25f14a9fde9808d8e7fdc20c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637514424362729509%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2HENU0Z2P7e3wwgLtlI0FaNj3%2BWf%2B9zml2P5qtDHROw%3D&reserved=0>
  *   Microsoft Alias: pehecke

**Comment by fowl2** [comment]
A DataProvider is like a connector, it's something supports connecting to a particular type of system. For example you might have "SQL Server" or "SharePoint List" DataProvider.

A DataSource is like a connection, it's represents a particular instance of a data provider. Eg. a particular database/server, or a specific SharePoint site or list.

**Comment by Sunil-Garg** [comment]
@Srinath ***@***.***>

________________________________

**Comment by srinathkannan** [comment]
The EntityDataSrouce documentation got updated. 
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/api-considerations-ve#new-tables

**Comment by Nkrb** [comment]
@shahabhijeet Closing the issue. If you need further help, please reopen or create a new issue.
