### ISSUE TITLE
page does not call out that the Stream video control is not yet available in GCC instance of Power Apps - 2228907

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerapps-docs#2206]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9192dd77-30e7-4ef4-dbd0-ffcc643747c7
* Version Independent ID: 2d09703c-828f-a8d8-7f3e-4fa9b9f10186
* Content: [Microsoft Stream video control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-stream-video)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-stream-video.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-stream-video.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by chmoncay** [comment]
Added a link to the FAQ.  You can see the supported regions on the Stream FAQ here ->  https://docs.microsoft.com/en-us/stream/faq#which-regions-does-microsoft-stream-host-my-data-in-
