### ISSUE TITLE
Incorrect CLASS attributes in Web Template

### ISSUE THREAD

**Issue by IsolatedStorage** [MicrosoftDocs/powerapps-docs#2209]
Good morning, 

I have noticed the following syntax errors within the sample web template source where the CLASS attribute does not enclose all the classes correctly

![image](https://user-images.githubusercontent.com/19565852/111714579-e4c75600-888c-11eb-9a2f-8257cfed9b7a.png)

![image](https://user-images.githubusercontent.com/19565852/111714539-d0835900-888c-11eb-9e61-40b6bdebc005.png)

Regards

Alistair

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d71e01-9651-365a-0fc0-b0017d3866ca
* Version Independent ID: 507be630-f013-10d1-00dc-c57aa949f0cb
* Content: [Customize the Azure Active Directory B2C user user interface for portals. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/azure-ad-b2c)
* Content Source: [powerapps-docs/maker/portals/configure/azure-ad-b2c.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/azure-ad-b2c.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated. Please allow some time to reflect the changes.
