### ISSUE TITLE
2 minute limit for file attachment upload requests

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#2210]
Portals PM confirmed that there is a hard limit of 2 minutes for the request sent to upload the file;
after this, you will get a generic (http 500) error

If you expect to have many users with slow internet connectivity uploading files,
you may want to reduce the allowed attachment size

or add a warning on the page suggesting to only upload small files on slow connections to not exceed the 2 minute upload time

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434c988b-243e-0d01-e098-fa9a0300ae31
* Version Independent ID: e7b47bad-3195-2b6d-bef3-8c23b6fb58e8
* Content: [Configure notes as attachments on entity forms and web forms for a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure-notes)
* Content Source: [powerapps-docs/maker/portals/configure-notes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure-notes.md)
* Service: **powerapps**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Will be discussing internally for documentation update. Please reach out to the PM you discussed this topic with.
