### ISSUE TITLE
Misleading information regarding private messages in the FAQ section

### ISSUE THREAD

**Issue by LarsBauer** [MicrosoftDocs/powerapps-docs#2212]
I think there is a small error in the answer of the  _How can I use my private messages if they are not included in the Web API $metadata service document?_ question of the FAQ section ([direct link to the question](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/custom-api#q-how-can-i-use-my-private-messages-if-they-are-not-included-in-the-web-api-metadata-service-document))

> [...] However, you should set the CustomAPI.IsPrivate value to false before you ship your solution for others to use. If you later decide that you wish to support other applications to use the message, you can change the CustomAPI.IsPrivate value to true.

Correct me if I am wrong, but according to my understanding of private messages `true` and `false` should be the other way round.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd53494-e9ff-33b0-d857-bcd235233aa5
* Version Independent ID: a362d3d7-3d5c-9222-39e6-dd426f96c4a4
* Content: [Create and use Custom APIs (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/custom-api)
* Content Source: [powerapps-docs/developer/data-platform/custom-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/custom-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Thank you.
I've submitted the change.
