### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by tv505** [MicrosoftDocs/powerapps-docs#2219]
Was sent to this page for information about access requirements to "Manage Portal Authentication Key" (from this source: https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/manage-auth-key) - but this document does not clearly list which task that is.  Is it "reset portal" or "download private key"?    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff0331e6-6c2b-4728-4c3b-3e141c285dc7
* Version Independent ID: 936bdd2f-3b1e-45d9-ed1a-c2c13e45ba46
* Content: [Details about different security roles required to administer Power Apps portals with specific actions. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-admin-roles)
* Content Source: [powerapps-docs/maker/portals/admin/portal-admin-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/portal-admin-roles.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated. Changes will be visible soon.
