### ISSUE TITLE
Sample does not work.

### ISSUE THREAD

**Issue by ChethanT** [MicrosoftDocs/powerapps-docs#2220]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Please provide details about how it doesn't work.
It has been tested and was known to work.

**Comment by ErikL68** [comment]
I too find it doesn't work. 

First it should tell users to install Newtonsoft.Json using NuGet if they don't already have it.

Second, the method to find the URL is outdated. It should be:
---------------------------------------------
a. From the https://make.powerapps.com site with the appropriate environment selected, select Settings <Settings button> and choose Advanced **Settings**. Your browser will be redirected to the Dynamics 365 page.

b. On the Dynamics 365 page, select Settings > Customizations

c. On the Customization page, click "Developer Resources."

d. On the Developer Resources page, look below Instance Web API and copy the Service Root URL value.
---------------------------------------------
Third and (obviously) most critical at least for me: After getting the URL, and using the Client ID included in the sample code, and entering my Login and Password that gets me into the environment in PowerApps, I get an error on the line "var authResult = authContext.AcquireToken(url, clientId, userCredential);", which is line 35 of my project, with the project named "DataverseQuickStart".

Here's the details on the error:
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException
  HResult=0x80131500
  Message=parsing_wstrust_response_failed: Parsing WS-Trust response failed
  Source=Microsoft.IdentityModel.Clients.ActiveDirectory
  StackTrace:
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(String resource, String clientId, UserCredential userCredential)
   at DataverseQuickStart.Program.Main(String[] args) in C:\Users\erik.ledding\source\repos\DataverseQuickStart\Program.cs:line 35

Here's the entire project code. Note I made sure to install v. 2.29.0 of the Microsoft.IdentityModel.Clients.ActiveDirectory NuGet package as well. The Newtonsoft.json version was 13.0.0.0, and I was using VS 2019 Pro.

`using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using System.Net.Http.Headers;
using System.Net.Http;
using Newtonsoft.Json.Linq;

namespace DataverseQuickStart
{
    class Program
    {
        static void Main(string[] args)
        {
            // Set these values:
            // e.g. https://yourorg.crm.dynamics.com
            string url = "https://org4da297b5.crm.dynamics.com";
            // Obviously not including UN & PWD info!
            // e.g. you@yourorg.onmicrosoft.com
            string userName = "Me@Mine.com";
            // e.g. y0urp455w0rd
            string password = "Password123";

            // Azure Active Directory registered app clientid for Microsoft samples
            string clientId = "51f81489-12ee-4a9e-aaae-a2591f45987d";

            var userCredential = new UserCredential(userName, password);
            string apiVersion = "9.0";
            string webApiUrl = $"{url}/api/data/v{apiVersion}/";

            //Authenticate using IdentityModel.Clients.ActiveDirectory
            var authParameters = AuthenticationParameters.CreateFromResourceUrlAsync(new Uri(webApiUrl)).Result;
            var authContext = new AuthenticationContext(authParameters.Authority, false);
            var authResult = authContext.AcquireToken(url, clientId, userCredential);
            var authHeader = new AuthenticationHeaderValue("Bearer", authResult.AccessToken);

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(webApiUrl);
                client.DefaultRequestHeaders.Authorization = authHeader;

                // Use the WhoAmI function
                var response = client.GetAsync("WhoAmI").Result;

                if (response.IsSuccessStatusCode)
                {
                    //Get the response content and parse it.  
                    JObject body = JObject.Parse(response.Content.ReadAsStringAsync().Result);
                    Guid userId = (Guid)body["UserId"];
                    Console.WriteLine("Your UserId is {0}", userId);
                }
                else
                {
                    Console.WriteLine("The request failed with a status of '{0}'",
                                response.ReasonPhrase);
                }

                Console.WriteLine("Press any key to exit.");
                Console.ReadLine();
            }
        }
    }
}

`

**Comment by phecke** [comment]
@ChethanT Thanks for the feedback. The article has been updated and improved.
