### ISSUE TITLE
Step 3 for UI incomplete

### ISSUE THREAD

**Issue by KoenJanssensPD** [MicrosoftDocs/powerapps-docs#2221]
In Step 3 "Associate Script web resource to a form" for Unified Interface, the steps to assign the handlers to the events are missing...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd626b7-e922-eecd-983c-3823afff4e04
* Version Independent ID: 376d0fc1-294a-660a-ea09-7de12f6dbe18
* Content: [Tutorial: Write your first client script in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script?tabs=legacy-ui%2Clegacy-add-web-resource)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@KoenJanssensPD Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.

**Comment by KoenJanssensPD** [comment]
@Nkrb , I don't see the changes?

**Comment by Nkrb** [comment]
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script?tabs=legacy-ui%2Cunified-add-web-resource. Let me know if you can see the changes.

**Comment by KoenJanssensPD** [comment]
Hi @Nkrb , I do see your change. However, if you compare [part 3 for Legacy Interface](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md#legacy-1) versus [part 3 for Unified Interface](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md#unified-interface-1), a lot of steps are missing for UI.
