### ISSUE TITLE
Missing info on iOS privacy settings for Edge browser

### ISSUE THREAD

**Issue by ms-CenFL** [MicrosoftDocs/powerapps-docs#2223]
Please update the documentation to explain how the in-app privacy and tracking settings in Edge for iOS 14 are ignored if the device-level settings for Edge app is not set to "Allow Cross-Website Tracking".

Apple device-level app options for Edge must be set as follows: [Settings > Edge > "Allow Cross-Website Tracking"] flag to TRUE. If this is not enabled, any changes to the Edge app's security settings for exceptions in [Edge | Settings > Privacy and Security > Tracking prevention > Exceptions dialog] are ignored. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de7fca-d66b-479c-1570-676ebafa1b78
* Version Independent ID: 70b75562-e755-31cd-c7fd-ef87983698f5
* Content: [Troubleshooting startup issues for Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues#enable-storage-of-third-party-cookies-and-local-data-in-your-browser)
* Content Source: [powerapps-docs/troubleshooting-startup-issues.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/troubleshooting-startup-issues.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated. For any issue that you might need help with, please feel free to reach out via a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with the investigation.
