### ISSUE TITLE
Badly translated to pt

### ISSUE THREAD

**Issue by jose-farinha** [MicrosoftDocs/powerapps-docs#2226]
This page is lousily translated to Portuguese. This must had been made up of terms that were translated out of context. Or the translator wasn't aware of the original meaning of the terms or perhaps of their usual translation for Portuguese in technical settings.

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: b4a522be-48b5-efc5-0a4d-e716a9469093
* Version Independent ID: 97f52c4e-6062-bff2-4683-b1af26eed2ba
* Content: [Mostrar, editar ou adicionar um registo numa aplicação de tela - Power Apps](https://docs.microsoft.com/pt-pt/powerapps/maker/canvas-apps/add-form)
* Content Source: [powerapps-docs/maker/canvas-apps/add-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-form.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by jowilco** [comment]
@jose-farinha
Thanks for your feedback. We are looking into this issue.

**Comment by jowilco** [comment]
@jose-farinha 
The page has been reviewed and translations have been updated. We hope that you feel that the updates are an improvement.
