### ISSUE TITLE
Add a step by step learn module

### ISSUE THREAD

**Issue by MRowan20** [MicrosoftDocs/powerapps-docs#2227]
It would be great if this example had a step by step walkthrough, since I could only find a few resources regarding hierarchy tables in dataverse.

Perhaps a learn module and exercise would be great too on the topic of hierarchical tables.👍

Thanks for all the useful resources 🙏

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f79d251-708e-4fc5-10a2-81ca34dd1ec3
* Version Independent ID: 63337d76-b08d-4f68-ea5a-d6316fbba99f
* Content: [Query and visualize hierarchical data with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/query-visualize-hierarchical-data)
* Content Source: [powerapps-docs/maker/data-platform/query-visualize-hierarchical-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/query-visualize-hierarchical-data.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@MRowan20 - I've passed on your suggestion for hierarchical Learn content. Also, the article referenced in this issue does include a brief walkthrough: [Visualization walk through](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/visualize-hierarchical-data#visualization-walk-through)

Closing issue.
