### ISSUE TITLE
Allow renaming of a Component Library without a solution - 2228934

### ISSUE THREAD

**Issue by chrispiasecki** [MicrosoftDocs/powerapps-docs#2228]
Currently it does not seem possible to rename a Component Library once you've created it. I've found that if you add it to a solution, then go to edit it,  you'll see the Settings button, which allows you to rename the App from there and save.

Using Solutions requires the environment to have a Dataverse though, which may cause frustration for some without it. Perhaps in the meantime it would be a good idea to mention this limitation in the current doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d076b13-d76b-6562-9af3-bfd1054a8754
* Version Independent ID: 1e078ef8-10eb-e202-5485-4da988f5905f
* Content: [Change app name and icon for a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/set-name-tile)
* Content Source: [powerapps-docs/maker/canvas-apps/set-name-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/set-name-tile.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by yifwang** [comment]
Adding @Hemant ***@***.***> as the PM contact for component topic.

Thanks,
Yifei

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Your feedback is under consideration. You can also submit ideas on the [Power Apps ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) and vote for ideas to be considered.
