### ISSUE TITLE
[Doc-enhancement] PowerApps embedding in teams as App is not working with offline capability - 2228941

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/powerapps-docs#2229]
Trying to create Power app as personal tab app in Teams. Power App is having offline capability functionality. It is working fine in Desktop and android teams. but not working in iOS. If it is known issue, Can you add under known issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c830299-300a-39dc-b1ab-6a3a0428901c
* Version Independent ID: d0a364b2-2692-32fe-a657-40edf8b13009
* Content: [Known issues and limitations for Dataverse for Teams - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/known-issues-limitations)
* Content Source: [powerapps-docs/teams/known-issues-limitations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/known-issues-limitations.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Closed with internal discussions.
