### ISSUE TITLE
adal.js has been deprecated by msal.js

### ISSUE THREAD

**Issue by Vivihung** [MicrosoftDocs/powerapps-docs#2233]
adal.js has been deprecated by msal.js
Please update the example to use msal.js. 
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a51d2ac-2b1c-d708-dd48-3b1ec982f61c
* Version Independent ID: bc3282d9-d484-23d6-6d68-d374d14d2935
* Content: [Walkthrough: Registering and configuring a SimpleSPA application with adal.js (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/walkthrough-registering-configuring-simplespa-application-adal-js)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-registering-configuring-simplespa-application-adal-js.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/walkthrough-registering-configuring-simplespa-application-adal-js.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **nabuthuk**

**Comment by phecke** [comment]
@Vivihung Yes, we are updating our samples. Thanks for the feedback.
