### ISSUE TITLE
Various issues with doc page "Override the default open behavior of data rows in an entity-bound grid"

### ISSUE THREAD

**Issue by nkirstein** [MicrosoftDocs/powerapps-docs#2234]
This sounds very interesting but so far I haven't been able to get it to work. I find the instructions on this doc page very confusing, especially those in the section **"Step 2: Create a custom button"**. I'm not an expert but I think some essential parts might be missing and other steps might be unnecessary. Could you please revise this section thoroughly?

Here are a few things that you might want to take into account (numbers refer to the sub-steps of section "Step 2: Create a custom button"):

* 1: Please mention that it's not necessary to include the entity's components or metadata when adding the entity to the solution.
* 2: I don't understand why it's necessary to add the site map to the solution. We want to add a custom button and custom action to the entity form. Isn't it enough then to just include the entity?
* 3: The screenshot "ACCOUNT INFORMATION" doesn't seem to be related to this topic at all. Or if it is, please explain how.
* 4: Didn't we include the web resource in section "Step 1: Create a web resource" already?
* 12: You might want to mention that we're only supposed to replace the code inside the `<RibbonDiffXml>...</RibbonDiffXml>` tags in the `customizations.xml` file, not the entire contents of that file.
* 12: The function name inside your XML code snippet doesn't coincide with the name of the JavaScript function from the web resource we created earlier. I'm referring to this tag in your XML snippet: `<JavaScriptFunction FunctionName="sampleoperations" Library="$webresource:cr5c1_samplescript" />`. The name of the JavaScript function inside the web resource is `ChangeBehavior`. 
* 12: Also, in the same XML tag, the name of the web resource itself will have to be changed. In your snippet it says `cr5c1_samplescript` but that certainly won't be the right name for everyone.
* 12: I'm not sure about this tag from your code snippet: `<CustomAction Id="cr5c1.Mscrm.OpenRecordItem.CustomAction" Location="Mscrm.SubGrid.contact.MainTab.Management.Controls._children" Sequence="28">`. Do we have to change the solution prefix `cr5c1` to our own publisher prefix?

As I said, I haven't been able to get this to work, so there might be other issues - either with the explanation or with my brain :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55cb1b78-70a4-a97a-c1d3-48ab8efd6c32
* Version Independent ID: cdd45300-f7e1-c515-92a5-d0c31aca3212
* Content: [Override the default open behavior of data rows in grids (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/override-default-open-behavior-grids)
* Content Source: [powerapps-docs/developer/model-driven-apps/override-default-open-behavior-grids.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/override-default-open-behavior-grids.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@nkirstein Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
