### ISSUE TITLE
translation failure

### ISSUE THREAD

**Issue by proxyprochy** [MicrosoftDocs/powerapps-docs#2235]
Hello, I've found that the translation of year format ("dd-mm-**rrrr** hh:mm") isn't correct due to the **rrrr** . (I guess it may be caused thanks to czech pronounce of year - ,,rok".) so instead of yearyearyearyear it does rokrokrokrok.
[Sem napište váš názor.]

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 198e7d8c-10ac-b34c-62e5-e9255fec5f77
* Version Independent ID: d47a7435-58fa-7493-82f2-66fba23ba501
* Content: [Funkce DateAdd, DateDiff a TimeZoneOffset - Power Apps](https://docs.microsoft.com/cs-cz/powerapps/maker/canvas-apps/functions/function-dateadd-datediff)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-dateadd-datediff.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-dateadd-datediff.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jowilco** [comment]
@proxyprochy 
Thanks for your feedback. We are looking into this issue.

**Comment by jowilco** [comment]
@proxyprochy
We have fixed the rrrr -> yyyy. Thank you for bringing this to our attention.
