### ISSUE TITLE
Make an object invisible to sighted users

### ISSUE THREAD

**Issue by lennarthoefer** [MicrosoftDocs/powerapps-docs#2236]
Hi there, if I set the objects width and height to 1 I am still able to see this - even it is just a single dot. I would expect to set both to 0. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb68d37-57a4-a294-34e5-eac97edb5a28
* Version Independent ID: 2404e15c-c2b5-62f5-a9f7-0a2d11df7f5f
* Content: [Show or hide content from assistive technologies in canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/accessible-apps-content-visibility)
* Content Source: [powerapps-docs/maker/canvas-apps/accessible-apps-content-visibility.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/accessible-apps-content-visibility.md)
* Service: **powerapps**
* GitHub Login: @tahoon-ms
* Microsoft Alias: **tahoon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can use one or more of the techniques listed. Documentation has also been updated, and the changes will be visible soon.
