### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#2237]
Link in page goes to [Create early bound table classes with the Code Generation tool](/dynamics365/customer-engagement/developer/org-service/create-early-bound-entity-classes-code-generation-tool)

Returns 404

It should go to https://docs.microsoft.com/powerapps/developer/data-platform/org-service/generate-early-bound-classes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9796507-4a36-b838-c53f-da2619952495
* Version Independent ID: aac9f312-1b41-a2c1-5258-03f6e4137f36
* Content: [Developer tools and resources (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/developer-tools)
* Content Source: [powerapps-docs/developer/data-platform/developer-tools.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/developer-tools.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@JimDaly  Fixed broken link. Will be re-published later today.
