### ISSUE TITLE
Undefined Context Variables

### ISSUE THREAD

**Issue by alpinedelight** [MicrosoftDocs/powerapps-docs#224]
It would be helpful to explain how to deal with variables that don't exist. Imagine a screen passes back a context variable via the navigation command. How do you check that it actually exists? IsBlank() and IsError seem to throw an error if its not previously defined. Would be nice to have logic around an IF statement, do this if variable equals whatever, if variable doesnt exist do something else. How would that work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb9294a0-cdd8-91d5-0102-c0412a21f540
* Version Independent ID: 77841b4e-08a9-1177-e18c-b428ef930c1c
* Content: [Understand variables in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-variables#know-when-to-use-variables)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-variables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-variables.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
@alpinedelight, thanks for your comment.  You've asked a common question and we also get a lot of "how do I remove a variable" too.  We've updated the docs to make this clearer.  All variables and collections are implied by their appearance in one of the functions that sets their value.  They don't actually need to be set to a value to exist, UpdateContext or Navigate does not actually need to be run.  If a single UpdateContext or Navigate exists anywhere on a screen then the context variable will exist whenever the app is running and cannot be removed.  It will start with an initial value of *blank* that is testable with the *isblank* function.  To remove a context variable, simply remove all the references to it from UpdateContext and Navigate.
