### ISSUE TITLE
Add new addOnPostSave method

### ISSUE THREAD

**Issue by filcole** [MicrosoftDocs/powerapps-docs#2242]
A new addOnPostSave method has been documented here (https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/postsave) but is not listed on this page.  I think it should be added below/after addOnSave.

I have tested and the method is available in client script on my crm4 environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5249188f-b583-4adc-4987-af5fe42e880a
* Version Independent ID: fba77804-3237-c925-0aa4-84eea18da1a8
* Content: [formContext.data.entity (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-entity)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
