### ISSUE TITLE
"This article will be updated soon to reflect the latest terminology"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerapps-docs#2243]
This note at the top can be removed as the update has already been made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b903798-2033-be36-079a-babe7586981e
* Version Independent ID: d588611a-a950-134e-6738-10e8f3899f25
* Content: [Tables and metadata in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-edit-metadata)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-metadata.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by KumarVivek** [comment]
@VitalyMCT Thanks for the feedback; we are doing some final sweeps across docs and this will be removed soon.
