### ISSUE TITLE
bootstrap directory structure isn't showing newlines correctly - 2332850

### ISSUE THREAD

**Issue by csobrien** [MicrosoftDocs/powerapps-docs#2245]
The text snipped showing the bootstrap directory structure isn't showing newlines correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc12134-33e6-ef48-6b2a-d832f3c7872f
* Version Independent ID: 7f4534e1-4742-2b7d-c2c2-160f9b8cf846
* Content: [Edit CSS in a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/edit-css)
* Content Source: [powerapps-docs/maker/portals/edit-css.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/edit-css.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated for new lines, please allow some time to reflect the changes.
