### ISSUE TITLE
The process that is defined for using connection references does not work as described. 

### ISSUE THREAD

**Issue by craig-lund** [MicrosoftDocs/powerapps-docs#2246]
With one simple flow using the current environment CDS connector. Connection references from the source environment included in the solution. When deploying, the flow no longer recognized the connection reference and you have to make a new connection reference in the target environment. I have created connections in both environments that have the same name and use the same SPN or username. 

Would appreciate understanding what i am missing and what the road map for this looks like. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8f2fd7c-a516-b3b7-c939-cba62d7836dc
* Version Independent ID: e681d318-9124-05ee-9438-29cfd3c4e732
* Content: [Connection references in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-connection-reference)
* Content Source: [powerapps-docs/maker/data-platform/create-connection-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-connection-reference.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by craig-lund** [comment]
Continued testing seems to show this is due to connection reference owner. When using automated tools the owner is changed to the deployment user.

**Comment by Mattp123** [comment]
@craig-lund - the article has been updated as well as the feature since you posted this issue, which should help resolve your problem. 

Closing issue.
