### ISSUE TITLE
Some of the worst documentation I've ever seen in my entire career.

### ISSUE THREAD

**Issue by malmoore** [MicrosoftDocs/powerapps-docs#2247]
It's almost like Microsoft doesn't care if _anyone_ uses their products. This documentation is so irredeemably, irretrievably bad. And I'm a tech writer who has written some pretty bad documentation in my day. Just out and out horrible in every way, shape, and form.

Where is the "Create and configure SAML 2.0 provider settings" step?
Why do you not provide any information on why users have to set an IdP protocol before they can specify that protocol in their app creation?
Why do you not give any orientation information on where users should start on configuring Azure as a SAML provider?

Just terrible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b755c203-c12c-e673-4654-ddd55d34d46b
* Version Independent ID: 60fa420e-c20c-dd4d-2c23-96f12ec9f10f
* Content: [Configure SAML 2.0 for portals with Azure Active Directory. - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-settings-azure-ad)
* Content Source: [powerapps-docs/maker/portals/configure/configure-saml2-settings-azure-ad.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-saml2-settings-azure-ad.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out.

Where is the "Create and configure SAML 2.0 provider settings" step? 
> Step 1 with "Select Add provider for your portal." includes the hyperlink to the topic to add a provider.

Why do you not provide any information on why users have to set an IdP protocol before they can specify that protocol in their app creation?
> This topic is one amongst the others about configuring different providers. The "Overview" and "Get started" topics are accessible using the TOC on the left, and this topic is not meant to be a complete authentication guide for portals authentication configuration.

Why do you not give any orientation information on where users should start on configuring Azure as a SAML provider?
> 6.a includes hyperlink to Azure portal in "Sign in to the Azure portal." about where to start Azure configuration.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. We'll work on improving content based on your experience.

Where is the "Create and configure SAML 2.0 provider settings" step?
> This is the step seen in the screenshot for #6. Will update text to clarify this is about the in-product experience.

Why do you not provide any information on why users have to set an IdP protocol before they can specify that protocol in their app creation?
> The flow of configuration begins with Power Apps portals since the configuration uses portals reply URL. Hence, step-by-step includes portals configuration at the beginning. Do you have any specific ask, or a question about why would you want to configure app creation before beginning app creation on Azure portal?

Why do you not give any orientation information on where users should start on configuring Azure as a SAML provider?
> Documentation contains link to Azure portal that can be clicked on. Since the topic itself is about Azure AD, can you please elaborate on what orientation is needed beforehand?
