### ISSUE TITLE
Do not understand statement 

### ISSUE THREAD

**Issue by GeorgianaMihaela** [MicrosoftDocs/powerapps-docs#225]
I do not understand this sentence:

"You can apply multiple steps so that your logic about whether to allow a operation to proceed can be in the PreValidation stage and your logic to make modifications to the message properties can occur in the PostOperation stage."

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbf0dbd-40c9-b1a0-3f21-b98c20bc49d7
* Version Independent ID: 9232684b-31ab-a4ba-f48e-3170e38b5beb
* Content: [Event Framework (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/event-framework)
* Content Source: [powerapps-docs/developer/common-data-service/event-framework.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/event-framework.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by GeorgianaMihaela** [comment]
the title should be that I do not understand that statement.

**Comment by JamesStuder** [comment]
It means that you can create a plugin that will run on the prevalidation stage to check the values of the input data, maybe perform some data clean up (formatting), etc.  Then have that same plugin run on the post operation to link up records, set fields that will kick off other plugins, etc.  The way to do that is to check the plugin context to see what stage is being ran.  Then execute the code you want.  Not sure if that helps or not.

**Comment by GeorgianaMihaela** [comment]
It helps.  Thank you for the clarification.
