### ISSUE TITLE
Support for manifest CDM (.manifest.cdm.json)?

### ISSUE THREAD

**Issue by subashsivaji** [MicrosoftDocs/powerapps-docs#2252]
When will the PowerApps and Export to Data Lake feature support the latest Common Data Model format, the manifest (*.manifest.cdm.json)? Any ETA?

**Comment by Mattp123** [comment]
@subashsivaji - the latest upcoming feature announcements can be viewed here: https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/. 
Features that you don't find announced in the release plans can be submitted and voted on here: https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas

Closing issue.
