### ISSUE TITLE
XSD missing

### ISSUE THREAD

**Issue by SolidSoils** [MicrosoftDocs/powerapps-docs#2253]
There is a detailed description available of the Manifest schema, but I cannot find any reference to the actual Manifest.xsd. It would be very helpful to have the xsd so I can have intellisense in VS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24502d6b-ba33-8419-23ed-fa412634bc54
* Version Independent ID: 02aba75a-b1bb-f5aa-4730-85f15d7b0bea
* Content: [Power Apps component framework manifest schema reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/index.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/manifest-schema-reference/index.md)
* Service: **crm-online**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@SolidSoils Thanks for reaching to us. We didn't expose the actual Manifest.xsd file to public. Closing the issue. If you need further help, please reopen or create a new issue.
