### ISSUE TITLE
Unable to view the options to select the Arc Knob or Radial Knob controls for a Whole Number field.

### ISSUE THREAD

**Issue by akhildynamics** [MicrosoftDocs/powerapps-docs#2255]
Hi, I am unable to view the options to select the Arc Knob or Radial Knob controls for a Whole Number field. Slider control is present though. Please instruct.

Regards,
Akhil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5435ffcb-2f82-7513-7ffc-d5ae6529512a
* Version Independent ID: 6e4f6d2a-0ed9-84c9-d680-1c1ddc732454
* Content: [Use custom controls for model-driven app data visualizations in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/use-custom-controls-data-visualizations)
* Content Source: [powerapps-docs/maker/model-driven-apps/use-custom-controls-data-visualizations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/use-custom-controls-data-visualizations.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@akhildynamics - Sorry for the delay but wanted to wait until the fix rolled out before responding. The ability to see the slider control, which has been deprecated along with the other controls you listed, was an oversight that has now been fixed. More information about the deprecation can be found here: [Model-driven app controls deprecation](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#model-driven-app-controls-deprecation)

Closing issue

**Comment by luconsta** [comment]
Hello,
But if that controls are deprecated, the originating document for this issue: https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/use-custom-controls-data-visualizations shouldn't be modified to present only "current controls", or at least add a note besides the need for "classic experience" with the link to "controls deprecation" mentioned above?
Kind Regards,
Lucian

**Comment by iozm** [comment]
Can someone please fix the documentation? Its misleading to use images for controls that are now deprecated. @Mattp123 This is not resolved. We had to go through an endless troubleshooting only to find out this feature has been deprecated for a year but documentation does not reflect it.
