### ISSUE TITLE
Azure Active Directory default security and running the code as written on the page

### ISSUE THREAD

**Issue by rod-microsoft** [MicrosoftDocs/powerapps-docs#2258]
While I was following the instructions step by step, I ran into an Azure issue where I got the error that "Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access"

I ultimately solved the problem following the information found here:
https://docs.microsoft.com/en-us/answers/questions/22998/login-message-says-i-must-use-mfa-but-signupsignin.html

The security setting *I* needed to turn off was located on Azure here:
https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Properties
(Then I clicked on "Manage Security defaults" at the bottom and turned the "Enable Security defaults" from "yes" to "no" (which is not a preferred action I am sure!))

I know that was a very kludgy "fix" to the issue I was having as it greatly reduces the security posture.  I am not sure where the "proper" fix to be found is located.  This does not seem to be a Dynamics problem but it seems to have been an issue related to the default security features of Azure Active Directory and how the Visual Studio code authenticates users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@rod-microsoft The article has been updated and is now current. Give it another try if you like,
