### ISSUE TITLE
Glaring omission

### ISSUE THREAD

**Issue by peteravila** [MicrosoftDocs/powerapps-docs#2259]
There is no explanation for what a standard table is. Where that definition should be is, instead, a discussion of ownership types. Can't seem to find any documentation that explains what the dang thing is, how it's used,... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59399824-5817-ef45-209d-35dab587a406
* Version Independent ID: 322b5820-c559-9a0b-ef66-1c31945ead2e
* Content: [Types of tables - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/types-of-entities)
* Content Source: [powerapps-docs/maker/data-platform/types-of-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-entities.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@peteravila - thank you for your feedback. I've updated the article with the following information in the introduction section. 

Tables appear in Power Apps as one of three different types, which indicate how the table came into the environment, whether the table is managed or unmanaged, and whether it can be customized.

- Standard: Several standard tables, also known as out-of-box tables, are included with a Dataverse environment. Account, business unit, contact, task, and user tables are examples of standard tables in Dataverse. Most of the standard tables included with Dataverse can be customized. Tables that are imported as part of a managed solution and set as customizable also appear as standard tables. Any user with appropriate privileges can customize these tables where the table property has customizable set to true.
- Managed: Are tables that aren’t customizable and have been imported into the environment as part of a managed solution.
- Custom: Custom tables are unmanaged tables that are either imported from an unmanaged solution or are new tables created directly in the Dataverse environment. Any user with appropriate privileges can fully customize these tables.
