### ISSUE TITLE
Link to Sample is borken

### ISSUE THREAD

**Issue by mishra-avi** [MicrosoftDocs/powerapps-docs#2261]
Link to sample is broken :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea2990a-1920-fba9-563d-5ce89768967a
* Version Independent ID: 1f9de889-4ed5-d977-e72e-6af0bc053270
* Content: [Sample: Upload, retrieve and download an attachment(Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/samples/upload-retrieve-download-attachment)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/upload-retrieve-download-attachment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/upload-retrieve-download-attachment.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@mishra-avi  Fixed broken link. Will be re-published later today. Thanks.
