### ISSUE TITLE
"What this sample does" section appears incorrect

### ISSUE THREAD

**Issue by mschoneman** [MicrosoftDocs/powerapps-docs#2263]
It's talking about `BulkDeleteRequest`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09958c27-4f5a-bfcf-34c8-71277b424bb9
* Version Independent ID: 8f4aa97b-3b5b-55c9-457d-8af1417c3d71
* Content: [Sample: Export and import data map (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/samples/export-import-data-map)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/export-import-data-map.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/export-import-data-map.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@mschoneman The sample's topic mentioned above and the README have been updated. Thanks for pointing it out.
