### ISSUE TITLE
Note: On PowerApps Portals, only the Notes (annotation) table/entity fully supports file columns

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#2265]
Note:
While in a PowerApps context file columns are supported on all tables,
PowerApps Portals only fully support file columns and downloads on the Notes (annotation) entity

(Please add a link to https://docs.microsoft.com/en-us/powerapps/maker/portals/configure-notes)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/file-attributes)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@CarstenMS Done. Thanks for the feedback.
