### ISSUE TITLE
Options for the properties? 

### ISSUE THREAD

**Issue by skoofy5** [MicrosoftDocs/powerapps-docs#2268]
There seems to be missing documentation here. For instance does the link type have an option for an outer join?

Would be great to have examples and a list of available options here.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2ad15ae-4d4c-6907-b884-bef6057032e6
* Version Independent ID: 8c22bf57-0d65-abab-72d7-b366fc0edb4c
* Content: [ILinkEntityExposedExpression in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/ilinkentityexposedexpression#linktype?WT.mc_id=BA-MVP-5004107)
* Content Source: [powerapps-docs/developer/component-framework/reference/ilinkentityexposedexpression.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/ilinkentityexposedexpression.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@skoofy5 Thanks for reaching to us. We don't see there are any missing parameters that we missed documenting. Please refer to this [link](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/powerapps-component-framework/componentframework.d.tshttps://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/powerapps-component-framework/componentframework.d.ts) to see for the parameters available for all the APIs. Closing the issue. If you need further help, please reopen or create a new issue.

**Comment by skoofy5** [comment]
So you didn't format your link properly. I think you meant this page: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/powerapps-component-framework/componentframework.d.ts

```
                 * The 'type' of the link, referred by the link-entity attribute
                 */
                linkType: string;
```

This still doesn't give examples of linkType options... Please document the possible link types!
