### ISSUE TITLE
Deactivate certain portal cookies

### ISSUE THREAD

**Issue by latsyn** [MicrosoftDocs/powerapps-docs#2270]
The documentation does not indicate whether individual cookies, e.g. "Dynamics365PortalAnalytics", can be deactivated.

Is it possible to deactivate the "Dynamics365PortalAnalytics" cookie? 

Thank you for your help! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da589be-388b-95a2-1be0-d3d3de31d45a
* Version Independent ID: 795e86de-7b53-aebe-c63a-0280b1a57a42
* Content: [Cookies in Power Apps portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-cookies)
* Content Source: [powerapps-docs/maker/portals/admin/portal-cookies.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/portal-cookies.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It's not possible to deactivate cookies used by Power Apps portals.
