### ISSUE TITLE
Prerequisite to have port 5558 open

### ISSUE THREAD

**Issue by ndocosta** [MicrosoftDocs/powerapps-docs#2271]
To use the Dataverse connector from Power BI Desktop, is also necessary to open the port 5558 besides 443 and enable TDS.
This is not referred on this article, and for companies with restrict security measures this can be an issue.
Can you please update this article with that pre-requisite - Port 5558?

Thanks!
Best regards,
Nuno Costa 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e6e30d-4224-459f-8525-08718d6d77e4
* Version Independent ID: fe075fe5-5d2e-7b96-3608-9ad3138380da
* Content: [Create a Power BI report using the Dataverse connector - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@ndocosta - thank you for submitting your issue. The article has been updated to include the necessary TCP ports. Closing issue.
