### ISSUE TITLE
Microsoft Teams: Employee ideas sample app

### ISSUE THREAD

**Issue by giuleon** [MicrosoftDocs/powerapps-docs#2273]
There is a bug in the App that doesn't permit to download attached files to the idea in the Teams Desktop App, in the web version of Teams works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f4b0e0-b911-c3e5-9086-a81727275fb3
* Version Independent ID: 427cd16b-293b-3776-fe11-8ab9bed63c8a
* Content: [Use Employee Ideas app from teams store - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/employee-ideas)
* Content Source: [powerapps-docs/teams/employee-ideas.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/employee-ideas.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, and apologies for late response. If the issue still persists, please reach out with a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to help investigate the issue.
