### ISSUE TITLE
I would like a description of the "BackEnabled" property. 

### ISSUE THREAD

**Issue by s-kawara** [MicrosoftDocs/powerapps-docs#2274]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bbd1e3-f15f-e855-e4ee-2e10fd22920d
* Version Independent ID: 48aa97f4-bceb-7ac9-b2ce-49cf721519cf
* Content: [App object - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/object-app)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/object-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/object-app.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@s-kawara Thanks for reaching to us. I have searched for the word **BackEnabled** in the doc, but didn't find any reference? Can you share me the exact link to the doc that you have issues with.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
