### ISSUE TITLE
Model-driven support for Dataverse for Teams

### ISSUE THREAD

**Issue by martincyr** [MicrosoftDocs/powerapps-docs#2275]
According to this page,
```
The following components aren't supported:

Model-driven apps
AI Builder
Custom connectors
```

But in [Enable Microsoft Teams Integration for model-driven apps](https://docs.microsoft.com/en-us/power-platform/admin/enable-teams-integration) it seems possible. I verified PPAC and the option is indeed there. 
This information about this limitation seems outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c830299-300a-39dc-b1ab-6a3a0428901c
* Version Independent ID: d0a364b2-2692-32fe-a657-40edf8b13009
* Content: [Known issues and limitations for Dataverse for Teams - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/known-issues-limitations)
* Content Source: [powerapps-docs/teams/known-issues-limitations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/known-issues-limitations.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by Mattp123** [comment]
@martincyr - I believe the limitation still holds as the article you referenced about Teams support for model-driven apps is to embed them in Teams. Dataverse for Teams is a Power Apps environment type that lets you build canvas apps directly from teams but doesn't have the same functionality with model-driven apps. 

Closing issue.
