### ISSUE TITLE
Table with properties has broken layout on the form properties for model driven apps page

### ISSUE THREAD

**Issue by surfen** [MicrosoftDocs/powerapps-docs#2279]
Table with properties has broken layout

![image](https://user-images.githubusercontent.com/5035388/114609789-7618c500-9c9f-11eb-95b5-54049d47c0b2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4817e1be-e1f2-9715-bba2-e16b883f50fb
* Version Independent ID: c73dd8d9-9db1-251d-ad34-e595e55e835f
* Content: [Model-driven app form properties in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/form-properties-legacy)
* Content Source: [powerapps-docs/maker/model-driven-apps/form-properties-legacy.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/form-properties-legacy.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@surfen - thank you for bringing this to our attention. The table has been fixed to display correctly.
Closing issue.
