### ISSUE TITLE
comma or semicolon as paramter seperator ... you never know

### ISSUE THREAD

**Issue by Christian-Me** [MicrosoftDocs/powerapps-docs#2280]
Thank you for this tutorial.

Just a notice: I was stuck on the part : `Distinct(Locations, Location)` as at least in my current version of powerapps it should say `Distinct(Locations; Location)`. The error message given is totally unclear. And it is hard to spot the difference as many tutorials say comma is correct.

My personal opinion, get rid of the old fashion VB / Excel syntax and accept the common sense: Parameters in function calls are separated with commas!  Or accept both. I see no advantage in going back and forth and reinventing the wheel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please submit an idea on the [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) for feature enhancements, ideas or changes.
