### ISSUE TITLE
404 - Content Not Found

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/powerapps-docs#2281]
In section **Add the documents tab in the FormXML** - in point number 2 the Link for **Add an existing component to a solution** gives a 404 - Page not found error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 772dad73-84e3-4afb-ed0f-7937aa0771e2
* Version Independent ID: 5136382e-ef93-f0bf-5e9c-595b935909b7
* Content: [Add the Documents tab to the main form for a table - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-documents-tab-entity-main-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-documents-tab-entity-main-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/add-documents-tab-entity-main-form.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Dlutchy - thank you for bringing this to our attention. The link's been fixed. 
Closing issue.
