### ISSUE TITLE
Table images?

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#2284]
Renaming entities to tables was a too aggressive here
Entity images should remain 'Entity Images'. 'Table images' makes no sense.

Can you un-do some of the changes here where it doesn't make sense?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08cd0714-ecf3-a37e-32da-a336f5402fb6
* Version Independent ID: 9d7be299-ec79-62fd-c3e7-48f6bc23069b
* Content: [Register a plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/register-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/register-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/register-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@JimDaly 'Table image(s)' have been changed to 'entity image(s)'.
