### ISSUE TITLE
A description seems outdated.

### ISSUE THREAD

**Issue by yan0020** [MicrosoftDocs/powerapps-docs#2286]
Hi, the following description in this page seems to be outdated.
 "Support for up to 500 teams."

Please refer following blog.
https://powerapps.microsoft.com/en-us/blog/more-environments-more-places-and-more-capabilities-when-you-need-them/

https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#capacity-limits
![image](https://user-images.githubusercontent.com/56054850/115175169-7e408c80-a105-11eb-8a25-ae48a80c0ed8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffcc4d8-a8f0-83fe-3003-e9f9fcedadbd
* Version Independent ID: 6f4f89a2-fbc8-a2de-f16c-68e3dec4fa8e
* Content: [Microsoft Dataverse for Teams overview - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/overview-data-platform)
* Content Source: [powerapps-docs/teams/overview-data-platform.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/overview-data-platform.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by NHelgren** [comment]
Hi @yan0020 , the line you are referring to is explaining the original limit. Later in this post it mentions the new limit of 10,000.
