### ISSUE TITLE
Project Creation experience in VS 2019 is vastly different

### ISSUE THREAD

**Issue by jazmatician** [MicrosoftDocs/powerapps-docs#2288]
In VS 2019, .NET Framework is *heavily* disincentivised -- you have to scroll waaaay down to create a .NET Framework class library project, but there are several earlier class library types that are for Core and Standard. You need to update your initial startup documentation to reflect the interface in VS 2019. New developers using this documentation will likely be using that software and not 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad2eb047-525a-63b7-2d6e-1536a374d688
* Version Independent ID: 2b8e3e9d-c957-d43e-ceeb-c75da0857d2d
* Content: [Tutorial: Write and register a plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tutorial-write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@jazmatician  .NET Framework is required for plug-in development. However, I will update the article images and instructions to reflect VS 2019.
