### ISSUE TITLE
Modification history of this article

### ISSUE THREAD

**Issue by NicoleLiu924** [MicrosoftDocs/powerapps-docs#2289]
Hi team,

It stated that "Do not include any other NuGet packages or assemblies to the build folder of your project. You cannot include these assemblies when you register the assembly with your logic. You cannot assume that the assemblies other than those included in the Microsoft.CrmSdk.CoreAssemblies NuGet package will be present on the server and compatible with your code." However, the document head says its latest modify date is only 16th March and I have worked with a Microsoft engineer saying it is **ALWAYS** documented so. 

Hence wanted to seek the modificaton history of this article.  I am Customer Success Account Manager from Microsoft and need this information to bring to my customer and convince them to revise the coding on their end and follow Microsoft guidance and best practice. 

Much appreciated your help. 

Cheers
Nicole 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad2eb047-525a-63b7-2d6e-1536a374d688
* Version Independent ID: 2b8e3e9d-c957-d43e-ceeb-c75da0857d2d
* Content: [Tutorial: Write and register a plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tutorial-write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@NicoleLiu924 
You can view the history of this topic here: [https://github.com/MicrosoftDocs/powerapps-docs/commits/main/powerapps-docs/developer/data-platform/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/commits/main/powerapps-docs/developer/data-platform/tutorial-write-plug-in.md) but it doesn't go back very far.
I think something changed and they had to re-set the repo.

I can tell you that I added the part about adding any other NuGet packages relatively recently, in the past year or so I guess.

We update our docs when needed, especially when we discover patterns that are problematic. Whether it has always been documented or not isn't the point. 

The point is that plug-in developers should not take a dependency on any assembly other than the SDK Core assemblies and the assemblies they add. If, for example, they take a dependency on JSON.NET AND they happen to use the same version of the assembly that exists on the server, their plug-in will work as long as we don't change the version of JSON.NET. But we will eventually change the version of JSON.NET on the server with no announcement. If they take a dependency on it, their plug-in will suddenly break.

This has always been true. We have never supported people taking dependencies on any other assemblies on the server. We never documented what assemblies are available or what version they are. We have never guided people to re-use those assemblies.

We ran into a case where someone did this, possibly by accident, so I updated this tutorial to try and help people avoid this error.
