### ISSUE TITLE
Embed Streams - Power Apps Limitation GCC/GCC High

### ISSUE THREAD

**Issue by rocamp** [MicrosoftDocs/powerapps-docs#2290]
Please update this documentation to state that this control is not available for GCC or GCC High customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9192dd77-30e7-4ef4-dbd0-ffcc643747c7
* Version Independent ID: 2d09703c-828f-a8d8-7f3e-4fa9b9f10186
* Content: [Microsoft Stream video control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-stream-video)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-stream-video.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-stream-video.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by chmoncay** [comment]
We added a link in the description to show the region support as it's managed by Stream.  Here is the link again for your reference. https://docs.microsoft.com/en-us/stream/faq#which-regions-does-microsoft-stream-host-my-data-in-
