### ISSUE TITLE
overview is missing capitalization

### ISSUE THREAD

**Issue by Dan1480** [MicrosoftDocs/powerapps-docs#2291]
The "overview" heading is not capitalized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa8d8a05-5c10-ff85-f918-df07db18b72c
* Version Independent ID: 6bad6d9b-312e-0d7d-1259-9946d2b30020
* Content: [Flip component - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/angular-flip-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/angular-flip-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/sample-controls/angular-flip-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
