### ISSUE TITLE
Xrm.Navigation.navigateTo not working in v9 on-premise

### ISSUE THREAD

**Issue by johnphipa-bnppre** [MicrosoftDocs/powerapps-docs#2292]
Hello,

The Xrm.NavigateTo is not working for on-premise deployments, I have confirmed this on version on-premise v9, patch 9.0.23.7 (DB 9.0.23.7).
Please can you let me know when this will be fixed and when the on-premise update for the fix will be released.

**Comment by Nkrb** [comment]
@johnphipa-bnppre This is fixed in the latest on-premises version 9.1 which is scheduled to release in some time May end. Closing the issue. If you need further help, please reopen or create a new issue.
