### ISSUE TITLE
Not Available in GCC High

### ISSUE THREAD

**Issue by rocamp** [MicrosoftDocs/powerapps-docs#2293]
Please include that this is not available in GCC High for Power Apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 551096c3-6bef-bd2b-9254-4fceac6315da
* Version Independent ID: 6aaee99a-f244-17ca-cb48-408436a2ad92
* Content: [Power BI tile control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated will reflect the changes soon.
