### ISSUE TITLE
Dotnet Core

### ISSUE THREAD

**Issue by strada360** [MicrosoftDocs/powerapps-docs#2295]
[Enter feedback here]
Hello

This code doesn't work with dotnet core 5.0.   Is there a plan to update it?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@strada360 Yes, we are working on .NET 5 versions of our Web API samples. I do not have a firm publish date, but the samples are written and being tested/reviewed.
