### ISSUE TITLE
Displaying a view via Site Map does not work

### ISSUE THREAD

**Issue by rmwilkins** [MicrosoftDocs/powerapps-docs#2297]
The method for Displaying a view via Site Map does not work.  Despite adding the specific view for some reason it always goes to the Default public view.  May be this is a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0987eb9-274b-1f4a-f46f-36466e81c119
* Version Independent ID: 8531f5bc-fcf6-ce36-209e-e0dd4137de31
* Content: [Open forms, views, dialogs, and reports with a URL (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/open-forms-views-dialogs-reports-url)
* Content Source: [powerapps-docs/developer/model-driven-apps/open-forms-views-dialogs-reports-url.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/open-forms-views-dialogs-reports-url.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@rmwilkins Thanks for reaching to us. We tried to reproduce the issue and we can still see that we are navigating to the view that we set in the SiteMap. Can you verify that you have privileges to access the view?

**Comment by rmwilkins** [comment]
I have access.  I'm a System Admin.  I can manually change to the view.  Another observation.  The URL field changes the %7b and %7d to {} symbols.  I'm guessing that's normal.  I'll post screen shots when I'm able.

**Comment by rmwilkins** [comment]
Your article leaves out the important element of the app id in the url string.  Adding this makes it work.

**Comment by Nkrb** [comment]
@rmwilkins I will update the docs to have the app ID value in the URL.
