### ISSUE TITLE
Export many to many (N:N) entities to data lake ?

### ISSUE THREAD

**Issue by gsimardnet** [MicrosoftDocs/powerapps-docs#2299]
It is possible to export a many to many (N:N) entity using "Export to data lake" ?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19489d66-04a5-73a7-ed5e-6a7f83290687
* Version Independent ID: f1ad4134-09ed-7683-2715-b6dda1ff8682
* Content: [Export to data lake - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake)
* Content Source: [powerapps-docs/maker/data-platform/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sama-zaki** [comment]
It is possible by using the feature flag. To use the feature flag, please append _?athena.showRelationships=true_ to the end of your link, after selecting your preferred environment. Please note that this feature is still in preview.

**Comment by gsimardnet** [comment]
I have tested the flag and it works as expected.

Thank you
