### ISSUE TITLE
'Batch Patch' Usage Examples - Patch An Entire Collection Of New Records Or Changes All At Once

### ISSUE THREAD

**Issue by matthewdevaney** [MicrosoftDocs/powerapps-docs#2300]
I would like to add two ways to use the PATCH function that are popular in the Power Apps community to the documentation.  They are confirmed to work for SharePoint and Dataverse

#1  Create A New Set Of Records In A Database
Syntax: Patch(Datasource, CreateRecordsTable)

// create new records on local device
ClearCollect(
    colNewRecords,
    Table(
        // No GUIDs means records are NEW and will be CREATED in the datasource
        {firstname: "Matthew", lastname: "Devaney"},
        {firstname: "Reza", lastname: "Dorrani"},
        {firstname: "Sancho", lastname: "Harker"}
    )
);
// store created records in a collection
Patch(
    Contacts,
    colNewRecords
);

#2  Update A Set Of Records In A Database
Syntax: Patch(Datasource, UpdateRecordsTable)

// create new records on local device
ClearCollect(
    colNewRecords,
    Table(
        // Including GUIDs means records are EXIST in datasource and will be UPDATED
        {contactid: GUID("3d105987-1bae-492b-9d7f-ee4676734f10"), firstname: "Matthew", lastname: "Devaney"},
        {contactid: GUID("ac79fc28-546d-407c-ba00-b7dc51c1d155"), firstname: "Reza", lastname: "Dorrani"},
        {contactid: GUID("af794851-a626-4e88-bc55-490ddeb57bee"), firstname: "Sancho", lastname: "Harker"}
    )
);
// store created records in a collection
Patch(
    Contacts,
    colUpdateRecords
);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5786697f-ee29-1b61-c59a-955086201d55
* Version Independent ID: d2130620-9767-c72f-5bd7-8417e48cf65d
* Content: [Patch function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by malkhawaja** [comment]
I am trying your method, but getting this error:
![image](https://user-images.githubusercontent.com/43861985/116152674-e20f1a80-a6ee-11eb-99c9-3d45e166c446.png)

is there any kind of limitation? (I am patching to Dataverse by the way.

**Comment by Nkrb** [comment]
@matthewdevaney Can you verify if the samples you provided are working?

**Comment by matthewdevaney** [comment]
@Nkrb 
Yes, #1 is working perfectly.  I just re-tested.  Here's how you can validate my code:

#1  Create a new canvas app from blank
#2  Add the Contacts datasource
#3  Insert a button onto the screen
#4  Copy and paste my code to create a new record into the OnSelect property
#5  Click the button and verify the result


#2 had the wrong collection name

// create new records on local device
ClearCollect(
colUpdateRecords,
Table(
// Including GUIDs means records are EXIST in datasource and will be UPDATED
{contactid: GUID("96102698-a89f-eb11-b1ac-000d3ae8b563"), firstname: "Matthew", lastname: "Devaney"},
{contactid: GUID("a6443ea5-a89f-eb11-b1ac-000d3ae8b563"), firstname: "Reza", lastname: "Dorrani"},
{contactid: GUID("bbc639b0-a89f-eb11-b1ac-000d3ae8b563"), firstname: "Sancho", lastname: "Harker"}
)
);
// store created records in a collection
Patch(
Contacts,
colUpdateRecords
);

Here's how you can validate it:

#1  Create a new canvas app from blank
#2  Add the Contacts datasource
#3  Insert a button onto the screen
#4  Copy and paste my code to create a new record into the OnSelect property
#5  Replace the GUIDs with 3 GUIDs that already exist in the contactid field of the Contacts table
#6  Click the button and verify the result.

**Comment by matthewdevaney** [comment]
@malkhawaja
Please share your full code so I can reproduce.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. If the issue still persists, please create a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with investigation and resolution.

**Comment by simontgray** [comment]
Is it possible to patch to a Lookup column with this method? For example:

// create new records on local device
ClearCollect(
colNewRecords,
Table(
// No GUIDs means records are NEW and will be CREATED in the datasource
{firstname: "Matthew", lastname: "Devaney", currency: GUID("3240a3d6-1c9c-ec11-b400-0022489cb05d
") },
{firstname: "Reza", lastname: "Dorrani", currency: GUID("3240a3d6-1c9c-ec11-b400-0022489cb05d
")},
{firstname: "Sancho", lastname: "Harker", currency: GUID("3240a3d6-1c9c-ec11-b400-0022489cb05d
")}
)
);
// store created records in a collection
Patch(
Contacts,
colNewRecords
);

I get the attached error

![error](https://user-images.githubusercontent.com/100224051/158645534-fd60ac44-3fa7-4c4c-8fbc-e8ed8c9d79d8.png)

**Comment by rameshmukka** [comment]
@matthewdevaney This is still not working for dataverse. Throwing the same error as mentioned by @simontgray and @malkhawaja

**Comment by gtacchini** [comment]
> 

Hey @rameshmukka I managed to solve it. You need to make sure that you use the GUID function on the IDs. This way, Dataverse detects you're updating a record, if it doesn't detect that, you get that error because it expects a default pattern.

Here is my case:

`


//Hago un collection de los items de la galería. CLAVE: convertir en GUID la cuota para que funcione

ForAll(
    galCuota.AllItems,
    Collect(
        testCuotascoll,
        {
            mero_cuotaid: GUID(Cuota),
            mero_transacciones_proyectadas_front: Value(txtTransProyFront.Value),
            mero_ticket_promedio_proyectado_front: Value( Substitute(txtTpProyFront.Value, "$", "")),
            mero_transacciones_proyectadas_cafe: Value(txtTransProyCafe.Value),
            mero_ticket_promedio_proyectado_cafe:  Value( Substitute(txtTpProyCafe.Value, "$", "")),
            mero_productividad_proyectada: Value(txtProdProy.Value)
                                            }
    )
);

//Hago un bulk update de esos items en dataverse

Patch(Cuotas,testCuotascoll );


Reset(galCuota)`
