### ISSUE TITLE
「You can use your own Excel file, but the data must be formatted as a table.」What is the reason for this design？

### ISSUE THREAD

**Issue by alex-mm** [MicrosoftDocs/powerapps-docs#2301]
Excel can be imported directly into mendix studio, but not at powerapps. 
Why ? What's the rationale for this design ?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 42de6ba6-a4e0-fb79-cd90-b86e9b047e82
* Version Independent ID: e4251860-19f2-817b-bd5a-71d4bb50b6b5
* Content: [在 Excel 中设置表格式 - Power Apps](https://docs.microsoft.com/zh-cn/powerapps/maker/canvas-apps/how-to-excel-tips)
* Content Source: [powerapps-docs/maker/canvas-apps/how-to-excel-tips.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/how-to-excel-tips.md)
* Service: **powerapps**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For product behavior, feature design and changes, please reach out using [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
