### ISSUE TITLE
Typo in DOC

### ISSUE THREAD

**Issue by kobarac** [MicrosoftDocs/powerapps-docs#2302]
Fix "Add code component to an table" -> "Add code component to a table". I assume it's a leftover from the time it was called an entity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34647a0-dfdf-23da-c656-158a1eae14f9
* Version Independent ID: e2a795ee-c8ba-b757-194b-19ecf4b6d398
* Content: [Add code components to a column or table in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/add-custom-controls-to-a-field-or-entity)
* Content Source: [powerapps-docs/developer/component-framework/add-custom-controls-to-a-field-or-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/add-custom-controls-to-a-field-or-entity.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
