### ISSUE TITLE
Form footer deprecation

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/powerapps-docs#2303]
This page needs major updating to remove use of the form footer which is being deprecated. https://docs.microsoft.com/en-us/power-platform/important-changes-coming

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5cfdf2-8c37-5452-0eb1-20a9b4daad45
* Version Independent ID: e1a3dfc5-86c9-0cd3-9952-6c67f1aa43c9
* Content: [Productive main form design in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/design-productive-forms?source=docs)
* Content Source: [powerapps-docs/maker/model-driven-apps/design-productive-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/design-productive-forms.md)
* Service: **powerapps**
* GitHub Login: @mspilde
* Microsoft Alias: **mspilde**

**Comment by Mattp123** [comment]
@JerryCRMI - thanks for your feedback. We added an alert under the form footer bullet list item with a link to the deprecation announcement. Closing issue.
