### ISSUE TITLE
Fetch XML Paging issue

### ISSUE THREAD

**Issue by Antos2310** [MicrosoftDocs/powerapps-docs#2306]
The retrieveMultipleRecords paging does not work as expected for fetchXMLs as the return value is always looking for the constant value
 const n = "@odata.nextLink";
where as fetch xml gives back @Microsoft.Dynamics.CRM.fetchxmlpagingcookie and other return values. Please update the documentation as well as possibly add this feature to retrieveMultipleRecords.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c196bb-4bbb-80e2-0bba-42d130621024
* Version Independent ID: 56d1575c-1868-34c6-992d-e3797024e413
* Content: [retrieveMultipleRecords (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
