### ISSUE TITLE
When will 

### ISSUE THREAD

**Issue by ravesonly** [MicrosoftDocs/powerapps-docs#2308]
### "**_editable_**" DataTable
Just curious when the "editable" grid option will be available? 
Also, Are there any efforts going around in community so as to join and contribute if possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af82396d-69f1-daf7-be8c-15c1a841bd19
* Version Independent ID: d97646e7-abe7-51f3-6d06-0eb86a441d5d
* Content: [Data table control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-data-table)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-data-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-data-table.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**###

**Comment by tapanm-MSFT** [comment]
Thank you for raising GitHub issue for documentation. Please reach out using [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) for feature planning, and contribution.
