### ISSUE TITLE
Deprecated AuthType Office365

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#2310]
In "Named account using Microsoft 365" there is an example on how to use AuthType=Office365.

https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-dataverse tells us, that this AuthType is deprecated and will be finally removed in April 2022 and is already removed for new environments. 

Shouldn't this example be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf4a7bc-1ccb-26e5-f9e8-85c2843e98b7
* Version Independent ID: 64536f0c-1005-cd5c-9fdb-01c301108d46
* Content: [Use connection strings in XRM tooling to connect to Microsoft Dataverse (Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect)
* Content Source: [powerapps-docs/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@darshSWL Thanks for raising this issue. I will add a note that says this AuthType is deprecated. We will continue to have this on docs until this is completely remove. Closing the issue.
