### ISSUE TITLE
How to embed a canvas app without introducing the entity

### ISSUE THREAD

**Issue by abhaybhangale** [MicrosoftDocs/powerapps-docs#2314]
I have a canvas app that i need to host alongside our suite of model driven apps. This app does not need any model driven app wrapper, but i am forced to use one purely because the canvas app cannot be added to a solution, nor deployed alongside my other apps.  As a result my landing page shows data from the selected entity and on selecting any record, leads to the main app.  For as counterintuitive as it may sound, i actually need to get rid of the model driven app part so that my app users land directly on the embedded canvas app. Is there a way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d72044c0-7486-402e-4ad0-cd488f6356e0
* Version Independent ID: 3b762213-c234-14b3-7f11-cde507cced78
* Content: [Add an embedded canvas app on a model-driven form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-add-classic-designer)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by Mattp123** [comment]
@abhaybhangale - I don't believe what you are asking is possible with the embedded canvas app control but probably more what you're looking for is this feature, which doesn't require an entity/form/field per se and should available soon. https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-apps/converging-canvas-into-model-driven-apps-custom-page
