### ISSUE TITLE
Sample links result in 404

### ISSUE THREAD

**Issue by shahabhijeet** [MicrosoftDocs/powerapps-docs#2316]
Sample links on the following page are broken
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/build-queries-with-queryexpression

The following sample links results in 404
1. https://docs.microsoft.com/en-us/org-service/samples/retrieve-multiple-queryexpression-class.md
2. https://docs.microsoft.com/en-us/org-service/samples/retrieve-multiple-querybyattribute-class.md
3. https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/test-null-value

**Comment by phecke** [comment]
@shahabhijeet Fixed the broken links, The article will be re-published today. Thanks
