### ISSUE TITLE
multiple SubmitForm() 

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/powerapps-docs#2319]
Hi,

it is usual to have multiple edit forms on the same page. These are used to improve the user interface.
It would be great if you can document how to use SubmitForm() for submitting multiple forms which update the same Dataverse record at the same time.

Thank you
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5416ca-bb32-49b4-18e1-9c4c8de54a2e
* Version Independent ID: bb2289c0-64cc-bf39-8dc5-f551facdce8f
* Content: [EditForm, NewForm, SubmitForm, ResetForm, And ViewForm functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-form)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-form.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. SubmitForm takes one argument for the form. You can use multiple submit form arguments in repetitions and try. For further assistance, please reach out using a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help and investigation.

**Comment by MichaelWeberMSFT** [comment]
thank you, this is great. Can you please document this on the page so our readers can find this important information?
my apologies if I did not see the information. it does not seem to be so obvious. Thank you very much
