### ISSUE TITLE
Edit form & Dataverse for Teams is unable to clear a lookup field

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/powerapps-docs#2320]
Using an Edit form connected to Dataverse for Teams leads to a strange behavior in following common scenario:
- the Dataverse for Teams table contains a drop Lookup field 
- this Lookup field refers to related Dataverse for Teams table 
- on the Edit form you add the Lookup field
Selecting a Lookup item and patching the records works fine.
When trying to clear this field (and save the form without any entry in this field) you will not get an error, but the empty field is not saved. The Lookup field in the Dataverse for Teams record will remain unchanged with the previous selected record. 

It would be great if you can document any available workaround. 
Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5416ca-bb32-49b4-18e1-9c4c8de54a2e
* Version Independent ID: bb2289c0-64cc-bf39-8dc5-f551facdce8f
* Content: [EditForm, NewForm, SubmitForm, ResetForm, And ViewForm functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-form#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-form.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please create a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to help with investigating this issue.
