### ISSUE TITLE
[LOC] Back-Translation "土"→"S" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerapps-docs#2321]
ja-jp:"https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/formula-reference#s"
![formula-reference_j](https://user-images.githubusercontent.com/40815708/116773787-c317dc00-aa92-11eb-85a0-0fb821c56486.png)

en-us:"https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/formula-reference#s"
![formula-reference_e](https://user-images.githubusercontent.com/40815708/116773791-c8752680-aa92-11eb-92c6-da651aa77d5b.png)

#PingMSFTDocs

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2ed900e9-0ac8-8914-2bee-b04e4ebd725d
* Version Independent ID: 0ef1f99f-00f3-8344-9bd7-6cbfd96a789a
* Content: [関数、シグナル、列挙体 - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/formula-reference#j)
* Content Source: [powerapps-docs/maker/canvas-apps/formula-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/formula-reference.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jowilco** [comment]
@hyoshioka0128 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@hyoshioka0128 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
