### ISSUE TITLE
[LOC] Back-Translation "場所"→"Location" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerapps-docs#2322]
ja-jp:"https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/signals#description-and-syntax"
![signals_j](https://user-images.githubusercontent.com/40815708/116804936-cb891900-ab5d-11eb-8d10-76cfe0822cf5.png)

en-us:"https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/signals#description-and-syntax"
![signals_e](https://user-images.githubusercontent.com/40815708/116804942-d04dcd00-ab5d-11eb-8db2-e95d55dcf4b9.png)

#PingMSFTDocs
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 68490e51-ae25-ff32-0dd7-9eaf1f5f81d5
* Version Independent ID: 7389a5be-5e77-7238-7eaa-13380ce3908a
* Content: [Acceleration、App、Compass、Connection、および Location 信号 - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/signals)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/signals.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/signals.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jowilco** [comment]
@hyoshioka0128 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@hyoshioka0128 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
