### ISSUE TITLE
 [LOC] Back-Translation "完了"→"Complete" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerapps-docs#2324]
ja-jp:"https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/function-ismatch"
![function-ismatch_j](https://user-images.githubusercontent.com/40815708/116846722-eb831000-ac23-11eb-8f3b-767a9f2e5726.png)

en-us:"https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-ismatch"
![function-ismatch_e](https://user-images.githubusercontent.com/40815708/116846731-efaf2d80-ac23-11eb-8762-5cf36d1787d1.png)

#PingMSFTDocs

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c394b4cd-a8bf-c167-86f7-3a3690a78ba7
* Version Independent ID: 1c106efe-e4b2-f296-9caf-c372aab3b2d7
* Content: [IsMatch、Match、および MatchAll 関数 - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/function-ismatch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-ismatch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-ismatch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jowilco** [comment]
@hyoshioka0128 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@hyoshioka0128 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
