### ISSUE TITLE
Set the Guid of the Virtual Entity

### ISSUE THREAD

**Issue by Miesjh** [MicrosoftDocs/powerapps-docs#2325]
Please can you add some comment about setting the Primary Key field of the Entity. In the RetrieveMultiplePlugin.cs is see this example: 

**Your Example:** 
Entity e = new Entity("new_ticket");
**e.Attributes.Add("new_ticketid", reader.GetGuid(0));**

**My First Example:** 
I normally set the ID field like this:
Entity e = new Entity("new_ticket", reader.GetGuid(0));

Or like this:

**My Second Example:**
Entity e = new Entity("new_ticket");
e.Id = reader.GetGuid(0);

Normally in a plugin all three examples give the same result. But with a Virtual Entity only the first one works. 
It took me a while the solve this issue. Please make this clear in the documentation.

Error I got:  Create privilege violation encountered

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edbeb418-f5d9-da8d-7598-d4965f666e50
* Version Independent ID: f28b539d-69f1-5f2e-6f32-4248cb96eedf
* Content: [Sample: Custom virtual table provider with CRUD operations (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/sample-ve-provider-crud-operations)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/sample-ve-provider-crud-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/sample-ve-provider-crud-operations.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@Miesjh Thanks for reaching to us. We will update the docs accordingly. Will update the issue once we publish the docs live.

**Comment by Nkrb** [comment]
@Miesjh In the examples you're trying, I see that you are trying to set the data type to the entity itself which is not you should be doing. The code sample provided creates an entity called `new_ticket` and shows how to set data types for each attribute. Closing the issue. If you need further help, please reopen or create a new issue.
