### ISSUE TITLE
"table" / "entity" mismatch resulting in broken sample code

### ISSUE THREAD

**Issue by birgeravo** [MicrosoftDocs/powerapps-docs#2326]
There seems to be some issues with entity having been replaced with "table" some places in the sample code, but not everywhere, rendering the code partly broken. 

For example, after "Add the contact data in json object", the liquid says "for table in ...", while in the loop, it tries to reference "entity.".

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ac38ff-c39e-ef03-49e0-510544460b8f
* Version Independent ID: 4603058c-212d-8546-9d6c-69ba5e11b958
* Content: [Portals operations using the Web API - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/web-api-perform-operations)
* Content Source: [powerapps-docs/maker/portals/web-api-perform-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/web-api-perform-operations.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The sample code has been fixed, please allow some time to reflect the changes.
