### ISSUE TITLE
What are the limitations or requirements?

### ISSUE THREAD

**Issue by denisem-msft** [MicrosoftDocs/powerapps-docs#2328]
There is no limitations section or requirements. 
* Does the tile need to be in a premium or non-premium workspace? 
* What license does the user need?
* Will reports work? (The answer is yes, but only Tiles are documented)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 551096c3-6bef-bd2b-9254-4fceac6315da
* Version Independent ID: 6aaee99a-f244-17ca-cb48-408436a2ad92
* Content: [Power BI tile control: reference - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated will reflect the changes soon. Please reach out internally for additional discussions and documentation changes.
