### ISSUE TITLE
DES availability

### ISSUE THREAD

**Issue by aledoy** [MicrosoftDocs/powerapps-docs#2330]
Is DES going away soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b32a192-1de7-1c9d-3602-d6e732c8f7a6
* Version Independent ID: d0cb1601-9f48-5ef6-6919-ad3d4e9ee042
* Content: [Data export service (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/data-export-service)
* Content Source: [powerapps-docs/developer/data-platform/data-export-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/data-export-service.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by sama-zaki** [comment]
We have not made any official announcements yet. We are encouraging all our customer to use Azure Synapse Link for Dataverse (formerly Export to Data Lake).

**Comment by Mattp123** [comment]
Closing issue.
