### ISSUE TITLE
Allow comments for an idea (Employee Ideas App for Teams)

### ISSUE THREAD

**Issue by DownToTheBone** [MicrosoftDocs/powerapps-docs#2333]
I'd like to be able to add a comment to an idea that I'm interested in.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For improvements to the features in the sample apps, please submit ideas at the [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas), or vote for existing ideas.
