### ISSUE TITLE
Add phases for an idea (Employee Ideas App for Teams)

### ISSUE THREAD

**Issue by DownToTheBone** [MicrosoftDocs/powerapps-docs#2334]
Like a campaign has phases, I'd like to have an idea assigned to a phase so for example 

- Collect
- Analyze
- Accept
- Reject
- In Progress
- Completed

These are just examples - does not need to be these labels.

**Comment by tapanm-MSFT** [comment]
Thank you for creating GitHub issue for documentation. Please reach out using [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) for suggestions to improve products and features.
