### ISSUE TITLE
Assign a campaign to a reviewer (Employee Ideas App for Teams)

### ISSUE THREAD

**Issue by DownToTheBone** [MicrosoftDocs/powerapps-docs#2335]
I'd like to assign a reviewer to a campaign for them to review all the ideas submitted and manage those ideas through phases (see #2334)

**Comment by tapanm-MSFT** [comment]
Thank you for creating GitHub issue for documentation. Please reach out using [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) for suggestions to improve products and features.
