### ISSUE TITLE
Allow like/unlike of a comment on an idea (Employee Ideas App for Teams)

### ISSUE THREAD

**Issue by DownToTheBone** [MicrosoftDocs/powerapps-docs#2336]
Extension of #2333 - I'd like to like/unlike a comment on an idea.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For improvements to the features in the sample apps, please submit ideas at the [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas), or vote for existing ideas.
