### ISSUE TITLE
Geospatial features are GA?

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/powerapps-docs#2337]
On this page it mentions Geospatial services (preview) as a preview feature (in point 4) but according to this blog they're GA now https://powerapps.microsoft.com/en-us/blog/announcing-the-general-availability-of-geospatial-features-in-power-apps/ - could the docs be updated to reflect that they are GA?

Thank you
Manuela

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e34915e-ffa9-9a20-55c6-c9e71561f9be
* Version Independent ID: 673a113e-5978-85d2-699a-44e1a5a5fdf7
* Content: [Add Geospatial components to apps made with Microsoft Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/geospatial-overview#enable-the-geospatial-features-for-the-environment)
* Content Source: [powerapps-docs/maker/canvas-apps/geospatial-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/geospatial-overview.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
Thanks for picking this up, we're updating the docs now to remove the references to 'Preview'.
