### ISSUE TITLE
Remove System Dashboard supportability statement from the Note

### ISSUE THREAD

**Issue by saviegas** [MicrosoftDocs/powerapps-docs#2342]
[We have now documentation that covers the embed of Power BI on System Dashboards  (https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-edit-powerbi-embedded-page)

However we still have on this page the Note stating that is not supported:
Avoid adding Power BI visualizations to system dashboards; it's not supported.

Can it be removed as it may be confusing for customers?
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 175feec4-5bdf-7fa7-b0e7-7a44c7353c8c
* Version Independent ID: c907ceaa-dbb1-b585-de56-34e6d7f89d1e
* Content: [Add or edit Power BI visualizations on your dashboard - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/add-powerbi-dashboards?source=docs&branch=main)
* Content Source: [powerapps-docs/user/add-powerbi-dashboards.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/add-powerbi-dashboards.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
Thank you for your feedback. I have verified that you can add Power BI visualizations to system dashboards and remove the note.   You should see the changes on the topic by end of day today.

Thank you,
Mints
