### ISSUE TITLE
SAML 2.0 based authorization

### ISSUE THREAD

**Issue by lifissc** [MicrosoftDocs/powerapps-docs#2343]
I want to use a SAML 2.0 based identity provider for my portal. According to the document, I need to create an application to configure settings with the identity provider by Azure AD or AD FS.
Can I use the other external SAML 2.0 based identity provider(not Azure AD ,not AD FS). 
For example, the company's own authorization system(SAML 2.0 based)

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can use SAML 2.0 compliant identity providers in addition to Azure AD and AD FS examples.
