### ISSUE TITLE
The example in this page doesn't work

### ISSUE THREAD

**Issue by traiannemes** [MicrosoftDocs/powerapps-docs#2346]
This doesn't work:
IfError( 1/0, Notify( "Internal error: " & ErrorInfo.Control & "." & ErrorInfo.Property ) )

I did exactly the same as in example provided, trigger it from a button with OnChange()

The whole catch doesn't work, try this: IfError( 2/0, 1 ), it will give you blank instead of 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e0983e-5863-d1eb-43e5-e6e9546c4e2b
* Version Independent ID: cc7abb21-14fd-04de-e1bd-2605697adcd3
* Content: [IfError and IsError functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-iferror)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-iferror.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-iferror.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
