### ISSUE TITLE
Valid OAuth Redirect URIs - 2283164

### ISSUE THREAD

**Issue by ZohaibUddinKhan** [MicrosoftDocs/powerapps-docs#2357]
As per new policy of Facebook, there are an additional steps need to be done:

1. In the left navigation, select Facebook login - settings and set '**Valid OAuth Redirect URIs**' as https://contoso.powerappsportals.com/signin-facebook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49efc37a-7d7b-b47b-2d67-3de803a896d5
* Version Independent ID: 5f9c30be-818f-8981-4213-94850b8c32ca
* Content: [Configure the Facebook provider for portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-oauth2-facebook)
* Content Source: [powerapps-docs/maker/portals/configure/configure-oauth2-facebook.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-oauth2-facebook.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation is updated and will reflect the changes soon.
