### ISSUE TITLE
Capacity for Dataverse for Teams API calls

### ISSUE THREAD

**Issue by mgoto-git** [MicrosoftDocs/powerapps-docs#2360]
[Enter feedback here]
Is capacity for Dataverse for Teams "2000 API Calls /day/user" is correct?

It seems a new limitation because of there is no mention about this limit below.
https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare#environments

If this is correct, please share how to be counted the API call and what happens if the usage is over the limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a7fa1a-8aeb-414a-fe50-ffe4efe4246b
* Version Independent ID: c9051ed9-a131-0f32-4a8b-705830ef2c15
* Content: [Comparing Microsoft Lists, Dataverse for Teams, and Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/compare-data-sources)
* Content Source: [powerapps-docs/teams/compare-data-sources.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/compare-data-sources.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@mgoto-git - The article was updated some time ago to remove the limit and point to this article section for information about [API request limits]( 
https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#request-limits-based-on-user-licenses)

Closing issue.
