### ISSUE TITLE
Broken links in page

### ISSUE THREAD

**Issue by KenHarly-tio** [MicrosoftDocs/powerapps-docs#2373]
[Enter feedback here]
Under the heading **Data sources in Solutions**, there are two link references which return 404 page not found:
If a canvas app is a solution, **connection references** and **environment variables** may be created to store information about the data sources. 

Cheers
/Ken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7c89a8f-b16f-2896-faae-efbb438c7a89
* Version Independent ID: 8ce453b3-7e57-c80a-7ca0-9b122ad4796b
* Content: [Connectors overview for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated. Changes will be reflected soon.
