### ISSUE TITLE
Syntax error on Sdk.filterCustomerAccounts function

### ISSUE THREAD

**Issue by roryd** [MicrosoftDocs/powerapps-docs#2375]
In the `Sdk.filterCustomerAccounts` function, instead of 
`formContext.getControl("parentaccountid").addCustomFilter(customerAccountFilter, "account");`
it should be
`Xrm.Page.getControl("parentaccountid").addCustomFilter(customerAccountFilter, "account");`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01e9b0a-f8c9-97d8-1f9a-47692a365a97
* Version Independent ID: 7b61d02b-ade3-174c-0990-525782f3ee68
* Content: [addCustomFilter (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addCustomFilter)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addCustomFilter.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addCustomFilter.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@roryd Xrm.Page is depreciated and we recommend to use the formContext. Please see the documentation https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/clientapi-form-context. Closing the issue.

**Comment by roryd** [comment]
@Nkrb, I agree that Xrm.Page is deprecated, but your example does not work as documented. You might want to get it working where you pass executionContext to the function, except that was not working for me either. I was able to get my code working using the deprecated version.
