### ISSUE TITLE
Week start on Monday

### ISSUE THREAD

**Issue by leonardus1973** [MicrosoftDocs/powerapps-docs#2378]
Hi,
how can I set (and where) week start on monday?
how can I highlight Weekend days (Saturday, Sunday) in different color?
thank you very much!

(https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/screen-templates/calendar-screen-overview)

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 9451acad-432a-1f11-8204-238de8655846
* Version Independent ID: 16134a5a-2880-4221-32b9-256f0573620b
* Content: [Modello di schermata del calendario - Power Apps](https://docs.microsoft.com/it-it/powerapps/maker/canvas-apps/screen-templates/calendar-screen-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for creating GitHub issue for documentation updates. Please reach out using [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with how to customize your app.
