### ISSUE TITLE
Still having problems

### ISSUE THREAD

**Issue by Hairyjeremy0** [MicrosoftDocs/powerapps-docs#2380]
Having worked through all of the feedback on this guide, which is all very helpful, thanks, I still have two bugs I can't fix (which I think others may have touched upon but no fix has been tendered):
1. Although selectable and dynamic in the app, Department data doesn't seem to be reported to the s/p list. Instead, seemingly as a default it reports a single Location from the Locations list, and this doesn't change.
2. When you select a new Location, and Department, if the Department selected is not top of the List then when you submit the form in the app, the Department changes to the first Department on the list. Because of the first bug, I have no idea if this is just a display issue, or if the wrong data would get submitted.
Appreciate that this is an old thread, but as the guide is still out there, this may be of help to others using it. Thanks

**Comment by Nkrb** [comment]
@Hairyjeremy0 Can you share us the link of the document that you are having issue with, this helps us in assigning the work item to appropriate group.

**Comment by Hairyjeremy0** [comment]
Hi @Nkrb Thanks for your interest in helping. I have managed to solve this now, by modifying the script in the Locations field to report selected items rather than the results.
