### ISSUE TITLE
The save operation is not blocked after 10 seconds

### ISSUE THREAD

**Issue by melamriD365** [MicrosoftDocs/powerapps-docs#2383]
An error is displayed after 10 seconds. However, the save is not blocked. 

![image](https://user-images.githubusercontent.com/36016227/118455310-f1332800-b6f0-11eb-86a2-67e942fbb25f.png)

2021 release wave 1 enabled
Server version: 9.2.21043.00131
Client version: 1.4.2581-2104.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c3168e3-774b-aad1-0cd2-d7e6eb487088
* Version Independent ID: 2fb2edc5-b09d-bfaa-0644-675d29e00598
* Content: [Form OnSave event (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/form-onsave)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@melamriD365 Can you tell us more about what are you trying to do and when does this error occurs. This makes us easily identify the issue.

**Comment by melamriD365** [comment]
@Nkrb, Thanks for your feedback.

I am experimenting the new feature "Async OnSave events" which is included in Wave 1 2021: https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-apps/async-onsave-events

> 
_This new feature provides the ability to create Async OnSave events. Async OnSave events will now wait when they provide a promise, and there is also a new timeout if the promise does not resolve within 10 seconds. If it does not resolve within 10 seconds, the save operation will be blocked._

In my scenario, I execute an asynchronous function when saving a record. My function does not resolve the promise. After 10 seconds an error message is displayed, which is good according to the feature description. However, the save is not blocked by the system as described in the documentation.

**Comment by melamriD365** [comment]
The saving is not cancelled automatically. The following method must be used: preventDefaultOnError()
