### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by RajaSuman** [MicrosoftDocs/powerapps-docs#2388]
1. It would be great to have more details about the procedure/steps to enable the Async feature on the solution, under the section "Enable Async OnSave using app setting".
        The section, currently, only describes on what to add, and in which file. However, has no guidance on where/how to perform this change.
2. It would be great to have a more elaborate code sample on how to use the Async feature on OnSave event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c3168e3-774b-aad1-0cd2-d7e6eb487088
* Version Independent ID: 2fb2edc5-b09d-bfaa-0644-675d29e00598
* Content: [Form OnSave event (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/form-onsave#enable-async-onsave-using-app-setting)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
