### ISSUE TITLE
Is there a removeOnPostSave? It's not documented.

### ISSUE THREAD

**Issue by gitstb** [MicrosoftDocs/powerapps-docs#2389]
This page describes the addOnPostSave API but it does not mention a removeOnPostSave API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b90704-9f77-5452-0f27-716266c3f9f8
* Version Independent ID: 017e70a2-da5e-2504-7c39-728162c7ed7d
* Content: [PostSave Event (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/postsave)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/postsave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/postsave.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@gitstb We have added the `removeOnPostSave` doc and should be live after 6 PM today. Closing the issue. If you need further help, please reopen or create a new issue.
