### ISSUE TITLE
Add-PowerAppsAccount using AcquireToken method instead of AcquireTokenAsync

### ISSUE THREAD

**Issue by nihonjinboy85** [MicrosoftDocs/powerapps-docs#2390]
After running the following commands in PowerShell 5.1.19041.906 (as an administrator):
```
Install-Module -Name Microsoft.PowerApps.Administration.PowerShell
Install-Module -Name Microsoft.PowerApps.PowerShell -AllowClobber
```

I tried to run `Add-PowerAppsAccount` and received the following error message:
```
Add-PowerAppsAccount : Method invocation failed because
[Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named 'AcquireToken'.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerApps.Administration.PowerShell\2.0.125\Microsoft.PowerApps
.AuthModule.psm1:258 char:9
+         Add-PowerAppsAccount
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Add-PowerAppsAccount], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,Add-PowerAppsAccount
```
After reviewing the documentation on `Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext`, sure enough there is no method named `AcquireToken`, but rather `AcquireTokenAsync`.

I need this script to run, and it worked previously, so would rolling PowerShell back to a previous version fix this issue? If so, what version would I need to rollback to?

**Comment by phecke** [comment]
@nihonjinboy85 Did you try the solution posted by Fredrik? It did not work?
[Power Apps forum](https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Add-PowerAppsAccount-fails-because-method-not-found/td-p/267037)

I have assigned the issue to our admin writer. Perhaps he can redirect to the team that maintains the code.

**Comment by nihonjinboy85** [comment]
Hi @phecke , thanks for the quick response. Yes, I tried that solution, but it made no difference. Somehow, however, this issue seemed to resolve itself after a few hours, so it is now working as expected. Very strange, considering my script is now running `Get-AdminPowerAppEnvironment`, which I believe is running `Add-PowerAppsAccount` under the hood, so the command logic is unchanged since the issue first presented itself.
