### ISSUE TITLE
Open table data in Excel

### ISSUE THREAD

**Issue by lifissc** [MicrosoftDocs/powerapps-docs#2391]
I want to edit data using  [Microsoft Power Apps Excel Add-in] .
and I don't want to read all data and want to load data by parameter.
how can I set parameter to add-in？

**Comment by Mattp123** [comment]
@lifissc - I don't believe you can pre-filter the data but you can adjust the tables and columns that are added. More information: 
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-excel-addin#configure-the-add-in-to-adjust-tables-and-columns 

Closing issue.
