### ISSUE TITLE
Table malformed

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/powerapps-docs#2392]
It looks like the section that is listing out the new Canvas app rules are not part of the table. 
![image](https://user-images.githubusercontent.com/43175066/119026538-4aaa8980-b973-11eb-8660-3729048a6173.png)

**Comment by Mattp123** [comment]
@samadane - Thank you for your feedback. The table in Use solution checker to validate your apps article has been fixed. [Use solution checker to validate your apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/use-powerapps-checker#best-practice-rules-used-by-solution-checker) 

Closing issue
