### ISSUE TITLE
Custom Forms SharePoint Mobile

### ISSUE THREAD

**Issue by GreyBravo** [MicrosoftDocs/powerapps-docs#2398]
Will they have information on a solution to the problem with custom forms with List Power Apps in the SharePoint mobile app? These in-app forms don't work, they just load the default SharePoint.

**Comment by Nkrb** [comment]
@GreyBravo Thanks for reaching to us. Can you point us to the doc article you are talking about? It helps us address the issue and assign it to right people.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
