### ISSUE TITLE
Article needs info on sharing/distributing the app. Appears that only users with a Power App licenese are able to view/use it

### ISSUE THREAD

**Issue by skcary77** [MicrosoftDocs/powerapps-docs#2399]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f4b0e0-b911-c3e5-9086-a81727275fb3
* Version Independent ID: 427cd16b-293b-3776-fe11-8ab9bed63c8a
* Content: [Use Employee Ideas app from teams store - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/employee-ideas)
* Content Source: [powerapps-docs/teams/employee-ideas.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/employee-ideas.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For licensing requirements of Dataverse for Teams apps, please go to [License designation of an app](https://docs.microsoft.com/powerapps/maker/canvas-apps/license-designation#:~:text=Power%20Apps%20built%20in%20Microsoft%20Teams%20environments%20that,able%20to%20run%20these%20apps%20in%20Microsoft%20Teams.). If you encounter any issues, please create a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) so the support teams can help with the issue investigation.
