### ISSUE TITLE
Need to document the "type validation" overload of the '@' operator

### ISSUE THREAD

**Issue by CarlosFigueiraMSFT** [MicrosoftDocs/powerapps-docs#2400]
The `@` operator can be used for a few things. We have documentation for the field and global disambiguation, but it can also be used to validate the type of a record object against a data source. For example, with the sample `Accounts` table from Dataverse, this operation works fine:

    Collect(coll, Accounts@{'Account Number':"Acc-001"})

While this one produces a type error (since 'Account Number' should be a string:

    Collect(coll, Accounts@{'Account Number':111})

We should update the documentation to mention this capability as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8597e03e-6579-73b8-79b8-2b873f533d58
* Version Independent ID: aee40493-d15e-5ba9-468a-cdd841f0cb2c
* Content: [Operators and Identifiers - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/operators)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/operators.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/operators.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Added to docs. Closing the issue.
