### ISSUE TITLE
Authentication type is entity Id not table ID

### ISSUE THREAD

**Issue by bhshastr** [MicrosoftDocs/powerapps-docs#2403]
[Enter feedback here]

It mentions:
The Table Id value that specifies a globally unique name for the SAML 2.0 identity provider.
Example (Azure AD): https://login.microsoftonline.com/7e6ea6c7-a751-4b0d-bbb0-8cf17fe85dbb/

Should be:
The Entity Id value that specifies a globally unique name for the SAML 2.0 identity provider.
Example (Azure AD): https://login.microsoftonline.com/7e6ea6c7-a751-4b0d-bbb0-8cf17fe85dbb/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78758a5f-b84d-36ef-07bb-c53732c6a374
* Version Independent ID: 5b0292f5-e236-e84e-f647-d0c46869ae1a
* Content: [Configure a SAML 2.0 provider for portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-saml2-provider)
* Content Source: [powerapps-docs/maker/portals/configure/configure-saml2-provider.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-saml2-provider.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been updated and will reflect the changes in some time.
