### ISSUE TITLE
Cover image requirements

### ISSUE THREAD

**Issue by kcnighsurf** [MicrosoftDocs/powerapps-docs#2405]
[Enter feedback here]
What are requirements for adding cover image? Tried 1000x500 jpg/png neither work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd1a345e-1f7c-3756-d0b4-cf0e83ce39d9
* Version Independent ID: 0eb230e5-28ed-3b56-0462-3414a3f5f7b7
* Content: [Bulletins sample app - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/bulletins)
* Content Source: [powerapps-docs/teams/bulletins.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/bulletins.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by kcnighsurf** [comment]
![comms1](https://user-images.githubusercontent.com/53189318/121086456-68178a00-c7a0-11eb-865c-0ccd1ceadf2d.png)
It's a bug with the add your own image logic. I found a workaround. Edit the PowerApp and data table values so I removed a few standard images and added my own in the base App. 
![image](https://user-images.githubusercontent.com/53189318/121086643-a4e38100-c7a0-11eb-8a90-729a866b41e9.png)

**Comment by navjotm** [comment]
Thanks for sharing. We will research this bug and fix it in the next release.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This issue has been fixed. For any other issue with the app, please feel free to reach out using a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to help with the issue investigation.
