### ISSUE TITLE
What's my Environment Name?

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/powerapps-docs#2406]
Please add detailed instructions on where to find "The unique name that applies to your environment." It's really hard to figure out what the whole URL should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c228177-ace4-9ffc-d8db-1251cc98d228
* Version Independent ID: 864e7cde-7176-241c-992d-9e421bf4d6d3
* Content: [Compose HTTP requests and handle errors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/compose-http-requests-handle-errors)
* Content Source: [powerapps-docs/developer/data-platform/webapi/compose-http-requests-handle-errors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/compose-http-requests-handle-errors.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@samrueby Good point! I will add some instructions to the topic.

You can find the information by going to the Power Apps [portal](https://make.powerapps.com), select the settings (gear) icon in the toolbar, and choose **Developer resources**.
