### ISSUE TITLE
The terminology change has been disastrous for the docs

### ISSUE THREAD

**Issue by AgileXRM** [MicrosoftDocs/powerapps-docs#2408]
We know that "**entity**" was changed to "**table**" and "**field**" was changed to "**column**", but problem is previously "**entities**" also meant "**records**" and "**entity type**" term was used for now called "**tables**". And an "**entity property**" was a "**field**" meaning now a "**column**".

So some texts in this page (and many many other pages) are really messed up.

Some examples in this page:

> "Limits on number of tables returned" trying to say "Limits on number of records returned"
> "a maximum of 5000 entities will be returned" trying to say "a maximum of 5000 records will be returned"
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5424f5-e734-423d-2baf-d7f82d500c96
* Version Independent ID: 4c1116df-37f5-0be4-6c94-3e3939e4cdb2
* Content: [Query data using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
I understand Peter is working on this.
The goal was to adopt new terminology when it makes sense so new people aren't completely lost, but part of that is to then educate them about the terminology differences in the developer space, where entity and attributes are still real things people work with.

**Comment by KumarVivek** [comment]
@AgileXRM Thanks for your feedback; the issues you pointed out have been resolved and we will do another pass to fix these terminology issues. Closing the issue.
