### ISSUE TITLE
Differences regarding Solutions, Publishers and Data functions are not listed here

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/powerapps-docs#2411]
[Enter feedback here]

For both Dataverse and Dataverse for Teams environments, the following page can be accessed by specifying URL or from Teams application.
https://make.powerapps.com/environments/{environment-id}/solutions

However, from the different UI I assumed there are differences in functionality between Dataverse and DfT environments.
(In particular, for a DfT environment you can only access "Data" and "Solutions" panels)

If those differences can be included in the "Environment" section, it will help users understand better what they can or can't do with Dataverse for Teams. For example, from the page above, users can create solutions, as well as assigning a publisher or create a publisher to assign to the solution, which they cannot do if they only use Teams app. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16e0d50-176d-2c1c-7821-a806efd079e3
* Version Independent ID: d8dc6656-383d-6f1e-8e47-350e4c206d7c
* Content: [Dataverse for Teams vs. Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare)
* Content Source: [powerapps-docs/teams/data-platform-compare.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/data-platform-compare.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@user0604 - for solution functionality comparisons between Dataverse and Dataverse for Teams, see [Key considerations and differences between Lists, Dataverse for Teams, and Dataverse](https://docs.microsoft.com/en-us/powerapps/teams/compare-data-sources#key-considerations-and-differences-between-lists-dataverse-for-teams-and-dataverse)

Closing issue.
