### ISSUE TITLE
OrganizationURI should be defined here, etc.

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/powerapps-docs#2412]
[Enter feedback here]

1. "Environment name" is misleading, as I understand it should be called "Organization ID". People might mistake it with the GUID of the environment. If possible please provide info on how to get the ID. contoso is a really bad example.
2. In various articles the term "OrganizationURI" is used without a proper definition. Here is where you should define it.
3. Giving an example of OrganizationURI could clear up a lot of confusion, e.g. "https://org11e5678d.crm.dynamics.com/". Expressing "https" as "Protocol" doesn't help it either (do you support ftp or recommend using http? if not just write "https://")
4. Retrieving different URIs sometimes leads to pages like "https://{orgID}.api.{region}.dynamics.com/api/data/{version}/...". I think it might be helpful if you could add whether or not OrganizationURIs with and without the ".api." part are interchangeable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c228177-ace4-9ffc-d8db-1251cc98d228
* Version Independent ID: 864e7cde-7176-241c-992d-9e421bf4d6d3
* Content: [Compose HTTP requests and handle errors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/compose-http-requests-handle-errors)
* Content Source: [powerapps-docs/developer/data-platform/webapi/compose-http-requests-handle-errors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/compose-http-requests-handle-errors.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke**

**Comment by JimDaly** [comment]
@user0604 
Thanks for your feedback. I'll keep it in mind for future updates.
