### ISSUE TITLE
App property description incomplete

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#2413]
The App object now seems to has additional properties such as OnMessage and BackEnabled which are not mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bbd1e3-f15f-e855-e4ee-2e10fd22920d
* Version Independent ID: 48aa97f4-bceb-7ac9-b2ce-49cf721519cf
* Content: [App object - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/object-app)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/object-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/object-app.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
