### ISSUE TITLE
Calendar Screen Template

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#2414]
Step 1 of the 'Specify the  calendar' section says: 'Set the OnStart property of the default screen in the app'. This is confusing since a screen does not have an OnStart property. I assume it means the OnStart property of the app. Also, I have found that the code provided results in errors on the lines containing the Lookup and ClearCollect functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9451acad-432a-1f11-8204-238de8655846
* Version Independent ID: 16134a5a-2880-4221-32b9-256f0573620b
* Content: [Calendar-screen template - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/screen-templates/calendar-screen-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated and the changes will reflect soon.
