### ISSUE TITLE
Notify Message Character Limits

### ISSUE THREAD

**Issue by andrewbarthva** [MicrosoftDocs/powerapps-docs#2417]
The docs page doesn't indicate the maximum character length for the Notify function Message parameter. Can you please add a note to this entry to indicate the maximum length of the Message parameter? 

It appears in practice that this limit is approximately 500 characters, but I can't find where it is explicitly defined in the docs.

😊
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afc532c2-42d1-d2d3-8631-25eac6aea36e
* Version Independent ID: 5ae36459-fcf9-bfa9-a715-2990de54e3ba
* Content: [Notify function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-showerror)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-showerror.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-showerror.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
