### ISSUE TITLE
Incorrect parameter name in step 3

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerapps-docs#2418]
In the step 3, the parameters used are "--path" and "--id", but, at least as of May 30, it should now be "--path"(same) and "--webSiteId"(instead of "--id").

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4e3c9e-af16-604e-43d7-179252741bdb
* Version Independent ID: ce493d89-9f8c-ac80-6e77-00e5a6f84077
* Content: [Tutorial - Use Power Apps CLI with portals - Power Apps](https://docs.microsoft.com/en-ca/powerapps/maker/portals/power-apps-cli-tutorial#step-3-download-portals-content)
* Content Source: [powerapps-docs/maker/portals/power-apps-cli-tutorial.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/power-apps-cli-tutorial.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For web site ID, you can use `-id`.
