### ISSUE TITLE
layout notice update

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/powerapps-docs#2420]
The restore option is now a button on the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2b1cae-930d-26ee-b8e1-5af3cd304c83
* Version Independent ID: 05ac17c8-e17d-bb3c-1009-9de987b4a64d
* Content: [Restore your canvas app to a previous version - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/restore-an-app)
* Content Source: [powerapps-docs/maker/canvas-apps/restore-an-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/restore-an-app.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation is updated. Changes will be visible soon.
