### ISSUE TITLE
User().Email actually equates to current user's UPN not their primary SMTP email address

### ISSUE THREAD

**Issue by baylosb** [MicrosoftDocs/powerapps-docs#2422]
Please update document to reflect this,> I feel for others who continue to encounter this issue, I know you can't change the property name in Power Apps but you could at least put a warning on this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629906e1-4e16-f342-6c5c-541f1a456e68
* Version Independent ID: 65ea7c7c-ae17-fe3a-bbc6-2efb72590380
* Content: [User function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-user)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-user.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-user.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
