### ISSUE TITLE
Does editable grids support custom filters described in this page? 

### ISSUE THREAD

**Issue by ArvinTheDeveloper** [MicrosoftDocs/powerapps-docs#2423]
Does editable grids support custom filters described in this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01e9b0a-f8c9-97d8-1f9a-47692a365a97
* Version Independent ID: 7b61d02b-ade3-174c-0990-525782f3ee68
* Content: [addCustomFilter (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addcustomfilter)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addCustomFilter.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addCustomFilter.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ArvinTheDeveloper Thanks for reaching to us. Custom filtering is not supported for editable grids yet. Closing the issue. Please reopen or create a new issue if you need  more information.
