### ISSUE TITLE
Custom Help Panes and iOS

### ISSUE THREAD

**Issue by philipverlinden** [MicrosoftDocs/powerapps-docs#2426]
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-custom-help-pages

It seems custom help pages don't work on mobile iOS devices, this is not documented it seems. Can this insight be updated/added somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a092a285-0b74-af20-214d-09409c712bf2
* Version Independent ID: 5cd8e6f2-7c17-2a6b-1584-70584495bca9
* Content: [Create custom help pages - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-custom-help-pages#feedback)
* Content Source: [powerapps-docs/maker/data-platform/create-custom-help-pages.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-custom-help-pages.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@philipverlinden - thank you for your feedback. You are correct and the article has been updated to reflect the limitation. Closing issue.
