### ISSUE TITLE
How to access Azure Blob where images are stored directly?

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#2428]
>Thumbnail images and image metadata are stored in Microsoft Dataverse, which includes the information needed to retrieve the full image. Full images are stored in file storage on the **Azure blob** to reduce data storage consumption.

Is there an endpoint we can use to query this Azure Blob directly using the Azure Blob API or is the only way to access this blob indirectly using [sample like this](https://github.com/microsoft/PowerApps-Samples/blob/1adb4891a312555a2c36cfe7b99c0a225a934a0d/cds/orgsvc/C%23/SetRetrieveImages/SetRetrieveImages/SampleProgram.cs) that uses the Xrm SDK and ImageAttributeMetadata to download images directly from the entity image attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99285656-64cc-d759-debd-fa439c7f0111
* Version Independent ID: 91ec0245-00a2-1de1-dd56-567010ec36df
* Content: [Image columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/image-attributes)
* Content Source: [powerapps-docs/developer/data-platform/image-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/image-attributes.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@gregdegruy  There is no direct access to Blob storage supported as of when the article was written.

@NHelgren  Your thoughts?

**Comment by NHelgren** [comment]
The available SDK and OData APIs are the supported methods for retrieving images from the Dataverse Azure blob.
