### ISSUE TITLE
update wording from "Common Data Service" to "Dataverse"

### ISSUE THREAD

**Issue by partridgetim** [MicrosoftDocs/powerapps-docs#2429]
Please update wording from "Common Data Service" to "Dataverse" in this place:

This data is also available for you to browse using the Power Platform Admin Center. Select Analytics > Common Data Service Dataverse > Plug-ins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec7e9cc6-a519-7fdb-b4ea-ddf6264be0db
* Version Independent ID: ca85afa4-dd67-d413-a0c4-5de79fb9f0b5
* Content: [Write a plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/write-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@partridgetim  Change made and will be published today. Thanks
