### ISSUE TITLE
Authenticated Users role needs to be turned off to make the custom webroles work

### ISSUE THREAD

**Issue by abranjms** [MicrosoftDocs/powerapps-docs#2430]
Based on recent testing performed when the "Authenticated Users role" role setting is set to "Yes" the users with custom web roles still falls back to the Webrole that has this flag set to true which seems to be contradicting the documentation. Below is the snippet i am referring to, can this be validated and corrected?

------------
Authenticated Users Role | Boolean. If set to true, this will be the default web role for authenticated users (see below). Only one Web Role with the Authenticated Users Role attribute set to true should exist for a given website. This will be the default web role for authenticated users that have not been assigned a web role.
-------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb232c20-8b53-8134-efa6-17578a6a03bd
* Version Independent ID: 6036aeff-77be-903a-bb3f-be2858a47e4b
* Content: [Create web roles for portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/create-web-roles?source=docs)
* Content Source: [powerapps-docs/maker/portals/configure/create-web-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/create-web-roles.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. A user can have one or more web roles depending on business requirement. Only one web role with *Authenticated Users Role* can exist for given web site record. See the next section: **Optional default web role for authenticated users:**.
