### ISSUE TITLE
Is it possible to create N:N record after creating two records, all in one web api deep insert ?

### ISSUE THREAD

**Issue by arunvinoth** [MicrosoftDocs/powerapps-docs#2432]
The documentation explains the deep insert to create a parent record (Account), then another 1:N record (Opportunity), then associating the 1:N tasks while creating them.. all these happening in single payload using web api deep insert.

Is the same possible for a N:N relationship ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73bddced-c6d4-2563-25ea-48a6e6305077
* Version Independent ID: 8e78d9f5-d35c-aae7-ed30-9599fb567433
* Content: [Create a table row using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/create-entity-web-api#create-related-entities-in-one-operation)
* Content Source: [powerapps-docs/developer/data-platform/webapi/create-entity-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/create-entity-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by arunvinoth** [comment]
Origin: https://stackoverflow.com/q/67805964/7920473

**Comment by JimDaly** [comment]
@arunvinoth 
Sorry for the delay in responding.
As noted in the SO response, I expect this is possible, but I haven't tested it.
If you test it and get an error, please advise.
