### ISSUE TITLE
OMG

### ISSUE THREAD

**Issue by FanningProducts** [MicrosoftDocs/powerapps-docs#2435]
OMG. the article is 2 major versions old and the most important part (the login) is not even supported anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@FanningProducts  We are working on updating the samples to use MSAL.

**Comment by phecke** [comment]
@FanningProducts the article has been updated and is now current.
