### ISSUE TITLE
step 17 - "Enable app embedding user experience"

### ISSUE THREAD

**Issue by notta-thing** [MicrosoftDocs/powerapps-docs#2436]
17. "Enable app embedding user experience" is no longer there. Is it the same as "Optimize embedding appearance"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d21a753e-4f2f-941f-8ec9-40891a5ebbe6
* Version Independent ID: 63740fcb-c081-6225-9fc5-8600c03125fb
* Content: [Pass the current row as data context with an embedded canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/pass-current-embedded-canvas-app)
* Content Source: [powerapps-docs/maker/model-driven-apps/pass-current-embedded-canvas-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/pass-current-embedded-canvas-app.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@notta-thing - thank you for your feedback. The article has been updated to reflect the current UI. 

Closing issue.
