### ISSUE TITLE
setVisible does not seem available for On Premise D365 even at the latest May 2021 update

### ISSUE THREAD

**Issue by JamesHorsley** [MicrosoftDocs/powerapps-docs#2437]
[Enter feedback here]
Documentation consistently fails to indicate which versions new API functionaility works with - there should be a table per call indicating the first introduced version for all environements (Online and On Premise)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b96278-a939-b802-1bb6-6370dee74503
* Version Independent ID: 4e5cb0c8-c16d-13e4-3364-0fff2535d9f7
* Content: [setVisible (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-formselector/setvisible)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-formSelector/setVisible.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-formSelector/setVisible.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@JamesHorsley Can you update your org with the latest June 2021 release and see if this is method works.

**Comment by JamesHorsley** [comment]
No – because that is a full point version upgrade and it’s KB document is awful – no detail at all about what has changed so no way it could be applied without massive risk.

 

But that misses the point anyway.  The documentation should have a table for each method indicating the minimum and (when deprecated) maximum version numbers for every method so there is no guess work involved (that is what documentation is for after all!). Ideally this would have separate entries for “on premise” on “on cloud” as the versioning is different.

**Comment by dmognaschi** [comment]
I agree with James: an explicit availability table for each method is
definitely important. Nowadays for on premises environments we must test
each method on the target environment to know if and how it works.

Maintaining a private compatibility table is an overkilling effort, prone
to errors.

The number of on premises projects is fading out, as a MS partner, but
there is a bunch of customers unable to migrate online.

If feasible, pls consider this suggestion because is very important.

Ty,
Davide Mognaschi




Il mar 15 giu 2021, 09:50 JamesHorsley ***@***.***> ha
scritto:

**Comment by Nkrb** [comment]
@JamesHorsley @dmognaschi We are in the process of updating docs to include which APIs are supported for online and on-premises environments. According to the dev team, setVisible method should work for on-premises 9.1 version that has been recently released.

**Comment by dmognaschi** [comment]
Ty Nava! This is very appreciated!

Davide

Il ven 18 giu 2021, 23:00 Nava Kiran Buthukuri ***@***.***>
ha scritto:

**Comment by Nkrb** [comment]
@JamesHorsley  @dmognaschi Here is the doc page that list all the unsupported methods. https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/clientapi/reference?view=op-9-1. setVisible is supported for on-premises orgs. Closing the issue. If you need further help, please reopen or create a new issue.
