### ISSUE TITLE
Is there a need for a dataverse license?

### ISSUE THREAD

**Issue by NGseb** [MicrosoftDocs/powerapps-docs#2438]
[Enter feedback here]
The doc says that a powerBI license is needed and it is clear.
Can you clarify the license on the power platform side?
Do users need a Dataverse license when they connect to PowerBi?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd540f56-483a-72c0-ec0a-10fd11f25e79
* Version Independent ID: a54faf86-952d-59ad-66a7-0098f54e3234
* Content: [View Dataverse for Teams table data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/view-table-data-power-bi)
* Content Source: [powerapps-docs/teams/view-table-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/view-table-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by RichdiMSFT** [comment]
Users need to have the correct licensing for Dataverse for Teams along with specific Power BI license. As [documented here:](https://docs.microsoft.com/en-us/powerapps/teams/data-platform-faqs#what-does-dataverse-for-teams-enable-and-how-does-this-impact-microsoft-power-platform-and-teams-users)

**Comment by DCtheGeek** [comment]
@RichdiMSFT I don't own or work in this content outside of fixing some links, so I'm not the right person to assign it to.  Thanks!

**Comment by Mattp123** [comment]
Closing issue as it's been answered.
