### ISSUE TITLE
Broken link for "Portal application registration" - 2318882

### ISSUE THREAD

**Issue by pnwguy** [MicrosoftDocs/powerapps-docs#2439]
Under section "Portal app owner", the link for "portal application registration" returns a 404 for https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-ap.

I think the link has a typo.  it's missing a "p" at the very last letter.  Should be:

https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff0331e6-6c2b-4728-4c3b-3e141c285dc7
* Version Independent ID: 936bdd2f-3b1e-45d9-ed1a-c2c13e45ba46
* Content: [Roles required for portal administration - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-admin-roles)
* Content Source: [powerapps-docs/maker/portals/admin/portal-admin-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/portal-admin-roles.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, fixed. Changes may take a while to reflect globally.
