### ISSUE TITLE
Publish Apps

### ISSUE THREAD

**Issue by oliviadudley** [MicrosoftDocs/powerapps-docs#2440]
Please add CTRL+SHIFT+P, which can be used to publish apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955cb34a-35ce-b369-a83b-b68195de2a63
* Version Independent ID: e7503f23-33ab-2a1a-6796-ea6d96b64146
* Content: [Keyboard shortcuts for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/keyboard-shortcuts)
* Content Source: [powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, it's already listed:

*Ctrl+Shift+P	Save the app and activate the publish dialog*
