### ISSUE TITLE
Advanced Lookup Doc

### ISSUE THREAD

**Issue by jaimieji** [MicrosoftDocs/powerapps-docs#2442]
Can you please also add details if the new advanced lookup support JS code added to the lookup field? Such as added custom view, filtering, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c392ce52-689a-f50c-f985-6f8ae7d1a128
* Version Independent ID: c3c7e767-f99c-b5e4-8bb6-1875004726c3
* Content: [Use the lookup column on a row - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/lookup-field#advanced-lookup)
* Content Source: [powerapps-docs/user/lookup-field.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/lookup-field.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@jaimieji I pinged our internal team to provide more info to see if we can add this info. Soon as I hear back, I'll update this thread and the topic if needed.

Thanks,
Mints

**Comment by mduelae** [comment]
@jaimieji I'm updating the topic and adding with this note.

Advanced lookup supports customizations on lookup control through Client APIs like addCustomView, addCustomFilter, addPreSearch and removePreSearch. 

Ping me back if you have further questions. Closing the request for now.

Thanks,
Mints
