### ISSUE TITLE
Explicit Column Selection preview feature

### ISSUE THREAD

**Issue by csteelatgburg** [MicrosoftDocs/powerapps-docs#2443]
The Explicit column selection feature is not available as an option when using the Teams PowerApps app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8dc20a4-0732-c43c-ec0c-2f56b8149f83
* Version Independent ID: 88bc2af8-df2f-8947-4408-017d2d2f1929
* Content: [Common canvas apps performance issues and resolutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/common-performance-issue-resolutions)
* Content Source: [powerapps-docs/maker/canvas-apps/common-performance-issue-resolutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/common-performance-issue-resolutions.md)
* Service: **powerapps**
* GitHub Login: @JinManAhn-MSFT
* Microsoft Alias: **jiahn**

**Comment by JinManAhn-MSFT** [comment]
@csteelatgburg , thanks for the good point. ECS feature is **on by default for the Teams PowerApps app**. 
Let me know if you have any concerns on ECS feature.

**Comment by JinManAhn-MSFT** [comment]
> The Explicit column selection feature is not available as an option when using the Teams PowerApps app.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: b8dc20a4-0732-c43c-ec0c-2f56b8149f83
> * Version Independent ID: 88bc2af8-df2f-8947-4408-017d2d2f1929
> * Content: [Common canvas apps performance issues and resolutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/common-performance-issue-resolutions)
> * Content Source: [powerapps-docs/maker/canvas-apps/common-performance-issue-resolutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/common-performance-issue-resolutions.md)
> * Service: **powerapps**
> * GitHub Login: @JinManAhn-MSFT
> * Microsoft Alias: **jiahn**

@csteelatgburg , thanks for the good point. ECS feature is on by default for the Teams PowerApps app.
Let me know if you have any concerns on ECS feature.
