### ISSUE TITLE
Typo issue. teh = the ?

### ISSUE THREAD

**Issue by zxs731** [MicrosoftDocs/powerapps-docs#2444]
[Enter feedback here]
Typo issue. teh = the ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18afb70-3a3c-1fc8-7adf-27c430c6001a
* Version Independent ID: 8eaae86e-6f4b-15db-44d8-1b0b3a9bb4cd
* Content: [addOnPostSave (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addonpostsave)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOnPostSave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOnPostSave.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for reaching us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
