### ISSUE TITLE
CrmServiceClient.OrganizationServiceProxy property alternative for checking connection state

### ISSUE THREAD

**Issue by georgir** [MicrosoftDocs/powerapps-docs#2445]
The page that documents how AuthType=Office365 can be replaced with OAuth also explains to not use the CrmServiceClient.OrganizationServiceProxy property, instead to use the CrmServiceClient directly as it implements the same interface. 

But in case a connection error occurs, the two behaved differently with Office365 AuthType. If given an invalid connection string or there is some other connection error, the CrmServiceClient constructor still returns a non-null instance, and the way to detect the failure that I used was to check if its OrganizationServiceProxy property was null.

What is the correct way to check if the connection succeeded with the new AuthType? Is checking the OrganizationWebProxyClient property instead OK? Are any of the EnvironmentId, IsReady or LastCrmError properties or something else that I'm missing a more reliable choice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62040095-4960-ad63-ed12-48400473e95c
* Version Independent ID: 063346b9-99f6-902f-710b-6badbd2a9830
* Content: [Use Microsoft 365 authentication with Microsoft Dataverse (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/authenticate-office365-deprecation)
* Content Source: [powerapps-docs/developer/data-platform/authenticate-office365-deprecation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/authenticate-office365-deprecation.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by RedsGT** [comment]
Best practice is isReady - https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/sample-simplified-connection-quick-start#another-example

**Comment by MattB-msft** [comment]
@RedsGT  is correct,  you want to check IsReady after you have the connection,, if its false, you can find the error in LastException and LastError.  You can also enabled Tracing to see the whole login sequence if your having issues locking down the failure. 

Note: this behavior has been changed in the Dataverse ServiceClient, which is a port of this (CrmSerivClient) client, to throw exceptions of failure.
