### ISSUE TITLE
Named Pipes Provider, error: 40 - Could not open a connection to SQL Server

### ISSUE THREAD

**Issue by Niels-SL** [MicrosoftDocs/powerapps-docs#2446]
Are there any known issues related to error code below I get, when I open the .pbids file to access it in Power BI Desktop.

![image](https://user-images.githubusercontent.com/46558783/121503557-77394a80-c9e1-11eb-9b3b-4da55bc1087e.png)

I can't connect to my environment anymore - even though it has worked for me earlier. I have tried to disable the TDS Endpoint in the Power Platform Admin Center for the environment, waited for 15 minutes, and the re-enabled it again - but I still get the error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6c0eba-9fac-85d1-e9d3-98b9df013b60
* Version Independent ID: 44f4fe02-eb04-0927-4b13-61a9c1ee8fef
* Content: [View table data in Power BI Desktop - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/view-entity-data-power-bi)
* Content Source: [powerapps-docs/maker/data-platform/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Please see the troubleshooting section of the article that is linked to from the article you referenced. Basically, the most common issues are 1) You haven't enabled the TDS endpoint for your environment 2) You have port 1433 blocked via firewall or proxy.
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#troubleshooting-connection-problems
