### ISSUE TITLE
Broken link for Add a data source to use for virtual tables

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/powerapps-docs#2447]
Hello,

in this section under Point 4 in the table, the first link is broken: 
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-edit-virtual-entities#add-a-data-source-to-use-for-virtual-tables

![image](https://user-images.githubusercontent.com/55705669/121506777-f4fa5780-c9db-11eb-8256-87c23fa5b313.png)

Thank you,
Manuela 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 994c6d0a-b4d5-78dc-8151-2b55ef67a977
* Version Independent ID: c508384a-3267-2a24-3136-4f5abbb74d19
* Content: [Create and edit virtual tables with Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-edit-virtual-entities)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-virtual-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-virtual-entities.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@manuelap-msft - thanks for your feedback. The link has been fixed.
Closing issue.
