### ISSUE TITLE
The download of power app is incorrect and leads to a BING page to use as default - 

### ISSUE THREAD

**Issue by kimberlybeaven** [MicrosoftDocs/powerapps-docs#2451]
The download of power app is incorrect and leads to a BING page to use as default browser, nothing to do with the power app nor the download of the mpp fle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8478b126-6c05-2986-b1d0-65f1d2dc0571
* Version Independent ID: 3ee77e79-a9d9-8436-dac6-d8a8b40ab6df
* Content: [Generate a canvas app to handle project requests - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-scenario-generate-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-generate-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/sharepoint-scenario-generate-app.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by navjotm** [comment]
Can we please add Wim Coorevits to the assigned list? I have transitioned this area to him.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated, please allow some time to reflect the changes.
