### ISSUE TITLE
Consider renaming "When an action is performed" trigger

### ISSUE THREAD

**Issue by chrispiasecki** [MicrosoftDocs/powerapps-docs#2453]
I would recommend renaming the new Power Automate Dataverse trigger "When an action is performed" to something like "When a business event is raised" or something that is consistent with the new Business Event name.

Using the word Actions introduces too much ambiguity with Actions (processes) in Dataverse and then Actions in Power Automate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c7c89b5-6d70-0f43-954f-070daaa5f6f3
* Version Independent ID: 12235e60-0f0a-37e2-40bb-e9f5330b9031
* Content: [Microsoft Dataverse business events (preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/business-events#table-events)
* Content Source: [powerapps-docs/maker/data-platform/business-events.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/business-events.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@chrispiasecki 
Thanks for your feedback. Sorry for the long delay in responding.
I like your suggestion and will forward it to PM owners for the area. But it isn't something actionable for the documentation.
Might be best to submit this to the ideas site.
