### ISSUE TITLE
404 following link on page https://docs.microsoft.com/en-us/powerapps/teams/use-teams-integration-object - 2330167

### ISSUE THREAD

**Issue by catalinbm** [MicrosoftDocs/powerapps-docs#2454]
[Enter feedback here]
There's a broken link resolving to a 404. 
On text: For more information about the Teams client SDK, go to Context interface.
Context Interface is a link to this url: 
https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/context?view=msteams-client-js-latest&preserve-view=true

and it results into a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea092895-28ba-b64d-33ec-9330ba976696
* Version Independent ID: 7eb1d946-aa8c-8e54-3e25-ecb6a4528fbf
* Content: [Use Teams integration object - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/use-teams-integration-object)
* Content Source: [powerapps-docs/teams/use-teams-integration-object.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/use-teams-integration-object.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by navjotm** [comment]
Please assign to Sid Gundavarapu, the right owner for these docs.

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. The link has been fixed, please allow some time to reflect the changes.
