### ISSUE TITLE
404 link to deprecated regional Discovery Service

### ISSUE THREAD

**Issue by rmrosen** [MicrosoftDocs/powerapps-docs#2455]
New links, maybe more:
Blog posted Jan 21, 2020 on the deprecation: https://powerapps.microsoft.com/en-us/blog/deprecation-of-the-regional-discovery-service/
or
https://docs.microsoft.com/en-us/power-platform/important-changes-coming#regional-discovery-service-is-deprecated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5fb9c01-72c0-4179-5ebf-969b763dc375
* Version Independent ID: 9b4058e2-26f3-9211-588f-3dd219e4fe3c
* Content: [Discovery Service (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/discovery-service)
* Content Source: [powerapps-docs/developer/data-platform/discovery-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/discovery-service.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@rmrosen Thanks for letting us know. The updated doc link will be published later today.
