### ISSUE TITLE
Use powershell instead of telnet for testing ports

### ISSUE THREAD

**Issue by InstructionSet** [MicrosoftDocs/powerapps-docs#2458]
Instead of using Telnet to test that port 1433 is open you could use powershells Test-NetConnection and avoid having to install redundant software.

Test-NetConnection -ComputerName environmentname.crm.dynamics.com -port 1433

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ead09d9-3e51-04ce-dc6e-ac9bb59816ec
* Version Independent ID: 94d19f8d-3c5e-8ed9-53ee-4b6173f49144
* Content: [Use SQL to query data (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-sql-query.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@InstructionSet Thanks for the tip. I have asked the product team about adding your tip to our SQL documentation.
