### ISSUE TITLE
Broken link to sample apps and tutorial assets

### ISSUE THREAD

**Issue by Windwarrior2021** [MicrosoftDocs/powerapps-docs#2459]
Multiple links throughout tutorial are broken and only lead to a Bing start page.
Should be leading to a download package for excel files used in the tutorial and examples of completed apps. 
Can author please correct/refresh links or provide new links to the required files please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d58efad-c076-c853-dd96-e9e70e50187e
* Version Independent ID: fcb0aa59-c412-d81e-bc9e-89ac3eb339f2
* Content: [Set up lists for SharePoint Online integration with Power Apps, Power Automate, and Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-scenario-setup)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-setup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/sharepoint-scenario-setup.md)
* Service: **powerapps**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by Windwarrior2021** [comment]
Managed to find the full link here: https://www.microsoft.com/en-us/download/details.aspx?id=54846

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated, please allow some time to reflect the changes.
