### ISSUE TITLE
facing an error while unpacking canvas apps 

### ISSUE THREAD

**Issue by karankhosla12** [MicrosoftDocs/powerapps-docs#2460]
Error while unpacking canvas apps when the file has a space between the name for example if the file is box calculator.msapp the unpack CLI will fail. In order to make it run and work properly i need to rename the msapp file to boxcalculator.msapp and then run the steps.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please share the documentation link that this feedback is for.

**Comment by tapanm-MSFT** [comment]
Closing this issue due to no response.
