### ISSUE TITLE
Power App Download package is missing 

### ISSUE THREAD

**Issue by Utkarsh-Parihar** [MicrosoftDocs/powerapps-docs#2463]
[Enter feedback here]

The link under the Tip section for download the package is not working. I recall that I was able to download couple of months ago. If the original link can be restored it will be great help. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f660396f-bb6f-8751-cd72-2897300bdb62
* Version Independent ID: fada7f0c-1054-4456-def0-58838327062a
* Content: [Create a canvas app to manage projects - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-scenario-build-app#:~:text=In%20Power%20Apps%20Studio%2C%20click,in%20the%20lower%20right%20corner)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-build-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/sharepoint-scenario-build-app.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated, please allow some time to reflect the changes.
