### ISSUE TITLE
DES REST-based API and Regional Disco Service

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/powerapps-docs#2466]
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/data-export-service#programming-for-the-data-export-service

Does this discovery service for the DES REST-based API rely on the Regional Discovery service that is being turned off?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b32a192-1de7-1c9d-3602-d6e732c8f7a6
* Version Independent ID: d0cb1601-9f48-5ef6-6919-ad3d4e9ee042
* Content: [Data export service (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/data-export-service#programming-for-the-data-export-service)
* Content Source: [powerapps-docs/developer/data-platform/data-export-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/data-export-service.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by RedsGT** [comment]
DES uses the Global Disco Service.

**Comment by phecke** [comment]
@samadane  The Global Discovery service is used.
