### ISSUE TITLE
Full URL specified in Partial URL field crashes the Portal

### ISSUE THREAD

**Issue by dibutil** [MicrosoftDocs/powerapps-docs#2468]
Apparently, when one inserts the real URL into Partial URL field on the Web File the parent page will fail to render complaining that the Site Map cannot be generated. The exception is generic and does not give a hint of why this happened, it took a lot of resources to find the offending data and understand the impact. Other symptoms of this issue are:
- inability to render the /sitemap page
- sporadic "Liqud Error" and "Liquid Exception" on Redirect type page templates - very misleading.

This issue needs to be fixed ASAP. The content creator can make all sorts of errors but shall never affect the whole Portal operation and be the source of generic exceptions! 

The easiest way to control the issue is to not let Site Map generator to go outside of the domain of the Portal, if the partial URL cannot be mapped it shall be ignored and logged into Azure in comprehensive way, reflecting the entity type, the entity GUID and the field name which content had casued the issue.

I checked the legacy ADX Portal with the same data and there is no issue - the parent page is rendered properly, the web file child shows up on the list of page children and on click it opens the file from external URL as specified. The issue when full URL in place of partial URL confuses the Site Map generator is introduced in the newer Portal versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e65c90-2534-2c89-95e2-81018c677cae
* Version Independent ID: 670ee62a-ca68-a906-6ab5-880550e6daca
* Content: [Create and manage web files - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/web-files)
* Content Source: [powerapps-docs/maker/portals/configure/web-files.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/web-files.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Please reach out using [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with the issue.

**Comment by dibutil** [comment]
Well... I already spent time debugging and fixing the issue, also posting the matter here. Suggesting me to open a ticket on a clearly investigated and stated problem is improper. My client are not going to pay me for running around with MS support for the issue that I have already fixed by altering the data. 
I genuinely thought that MS were interested in this kind of feedbaack and built on GitHub platform to get a chance to clean from such hidden malfunctions and make the system better. 
Apparently not. I am not wasting any more time posting here. 
Cheers!

**Comment by tapanm-MSFT** [comment]
@dibutil GitHub issues for documentation specific topic aren't meant to fix products. For product fixes and support, you can reach out to support channel for help with the issues. Hence, please reach out to support channel for help with product issues.
