### ISSUE TITLE
Misleading information regarding SharePoint custom form and access to organization users

### ISSUE THREAD

**Issue by savelazq** [MicrosoftDocs/powerapps-docs#2470]
[Enter feedback here]
The Q&A documentation states 

Q: Do I need a Power Apps license to create or use custom list forms?

A: Guest users can use custom forms. To create custom forms, you need an Office 365 plan that includes Power Apps.

However this does not explain if organization users require a license to access the forms, here we are seeing an issue with organization users trying to access the form and getting error "you need a current plan or trial to access powerapps" 

the only place where this information can be found is through our forums https://powerusers.microsoft.com/t5/Building-Power-Apps/Powerapps-License-and-Sharepoint/td-p/113203?lightbox-message-images-113671=25396iA8620C10304F2F29

the customer mentioned this is not an acceptable source of information as its misleading and they are expecting the official documentation to clearly outline this

There is no documentation found anywhere detailing this information for the customer to be aware of which licenses they need to have in order to access the custom forms. Also its confusing to the customer why a guest user with no license would have access to the custom form but not a organization user who has at least a 365 license. 

Please add this to documentation and clarify following points per customer request 

1 Organization users, licensing, and permissions needed to access SharePoint custom forms
2 Why guest users are able to access custom forms and organization users without a license cannot
3 Throughout explanation of why licensing is needed for SharePoint custom forms, and update of documentation to explain why licensing is needed
4 Clear comparison of licensing differentiation between guest users and organization users
5 what happens when admins do not want user to have access to create powerApps/flows and need to assign license for access to custom forms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a8c4146-101d-7ba2-7ae0-d7138b743154
* Version Independent ID: 1f752762-0809-a2fb-4a03-b490547ee7f1
* Content: [Customize a SharePoint list form - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
@savelazq  thank you for reaching out. As discussed, taking this for internal discussions to update the documentation, closing this public issue.

**Comment by cathydongGIT** [comment]
Same question here. 
Guest users can access the SP custom form without license. How about organization users without a license?
The documentation has not been updated.

**Comment by tapanm-MSFT** [comment]
Please read the FAQs updated to this topic - [Administer your custom form](https://docs.microsoft.com/powerapps/maker/canvas-apps/customize-list-form#administer-your-custom-form)

![image](https://user-images.githubusercontent.com/48696796/139915943-ba63a5ba-28fc-4467-a719-5e725172c59f.png)

**Comment by cathydongGIT** [comment]
The FAQ only states the license info for guest users. The question is for the organization users. For org users, do they need the power platform license to view the sharepoint custom forms?

**Comment by tapanm-MSFT** [comment]
Thanks for the clarification. Documentation has been updated and the changes will reflect the information soon.
