### ISSUE TITLE
Latest version(1.7.2) of pcf-start and pcf-scripts have different version of dependency uuid.

### ISSUE THREAD

**Issue by Doresimon** [MicrosoftDocs/powerapps-docs#2471]
The pcf-start uses uuid@8.3.2 and pcf-scripts uses uuid@3.3.2, this makes the pcf projects have runtime error:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in C:\_\iv.solution\solutions\components\sample\node_modules\uuid\package.json

**Comment by Cacaci** [comment]
Same problem.

**Comment by Doresimon** [comment]
issue fixed pcf-start@1.7.3. Thanks
