### ISSUE TITLE
Package is missing  - " Microsoft CRM Web API Query Data Sample (Client-side JavaScript)" 

### ISSUE THREAD

**Issue by mso365** [MicrosoftDocs/powerapps-docs#2473]
" Microsoft CRM Web API Query Data Sample (Client-side JavaScript)" package is missing 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3ae32fb-348c-fe39-fc4a-6a4b0680a199
* Version Independent ID: 9c1c528a-ff1e-d02c-5603-3071176ee85b
* Content: [Web API Query Data Sample (Client-side JavaScript) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/samples/query-data-client-side-javascript)
* Content Source: [powerapps-docs/developer/data-platform/webapi/samples/query-data-client-side-javascript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/samples/query-data-client-side-javascript.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@Nkrb 
Nava -
Can you look into this please?
Not sure why these were not moved over to Github.
Could be that the were written before the [Xrm.WebApi.online](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online) API existed.

Everything these samples could do should also be possible using that Xrm.WebApi.online.

These samples could be used in Web resources outside the context of a form.

**Comment by phecke** [comment]
@mso365 Seems to be there now. File another issue if you are still having trouble finding it.

https://github.com/microsoft/PowerApps-Samples/tree/master/cds/webapi/JS/WebAPIQueryData
