### ISSUE TITLE
Local Login Settings / Web Template Source

### ISSUE THREAD

**Issue by abbyltorres** [MicrosoftDocs/powerapps-docs#2475]
Would be helpful to have access to the local login settings, specifically button labels. One frequent request we have from client portal users is 'forgot username.' I have added username in "Password Reset" workflow email, but I would like to also change button label to "Forgot username or password." These settings/code are not accessible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6313f348-4130-74f5-320d-b5bd270060c6
* Version Independent ID: de470e06-c2d3-354e-ba80-75691a5d8bd4
* Content: [Local authentication, registration, and other settings - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/set-authentication-identity)
* Content Source: [powerapps-docs/maker/portals/configure/set-authentication-identity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/set-authentication-identity.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please post your feature request to the [Power Apps Ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas), and others can vote for it too. Depending on the impact, the submitted idea can be considered for product updates/enhancements.
