### ISSUE TITLE
value example provided twice ("make.powerapps.com")

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/powerapps-docs#2476]
make.powerapps.com mentioned twice under [required services](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#required-services)

> create.powerapps.com, **make.powerapps.com**, content.powerapps.com,apps.powerapps.com, and **make.powerapps.com**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e8858f-ee37-b1f0-2ad1-a52416f58d0d
* Version Independent ID: 23c5799a-0e3a-bd52-8f8c-ce586c93e632
* Content: [System requirements, limits, and configuration values for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#required-services)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation will reflect the updates soon.
