### ISSUE TITLE
Visual Studio can't select .NET 4.6.2 as target framework

### ISSUE THREAD

**Issue by snowuyl** [MicrosoftDocs/powerapps-docs#2478]
[Enter feedback here]
I follows the following URL to create C# plugin.
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/tutorial-write-plug-in
But I can't see .NET 4.6.2 in target framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad2eb047-525a-63b7-2d6e-1536a374d688
* Version Independent ID: 2b8e3e9d-c957-d43e-ceeb-c75da0857d2d
* Content: [Tutorial: Write and register a plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tutorial-write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Is it installed?

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by snowuyl** [comment]
Thanks for your reply. I can see .NET Framework 4.6.2 after I install .NET Framework 4.6.2 developer pack from https://dotnet.microsoft.com/download/dotnet-framework/net462
