### ISSUE TITLE
Please add "Important" or "Note" Tag to paragraph regarding multiple policies assigned to a user

### ISSUE THREAD

**Issue by JodyFinch** [MicrosoftDocs/powerapps-docs#2480]
Could you please add the blue "Important" or purple "Note" tag to the following paragraph on this page:

"If a user is defined in multiple policies of the same type, only the policy with the highest priority is applied to them. Any remaining policies of that type are not evaluated for the user (including the default policy)."

There are SEVERAL blogs out in the world with the wrong information on this. Specifically, folks are saying to use multiple polcies to get around the 60 (now 350) limit for Impersonated User Protection. 

As written, this paragraph is perfect, but easy to miss. Please consider calling it out as a note (like the blue one at the top of the page) or important tag (purple).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac02c636-ad3c-0689-22c9-dddf8dac98c6
* Version Independent ID: 5ea6404c-998e-4002-25f5-46701a2d819f
* Content: [Start a flow in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/using-logic-flows)
* Content Source: [powerapps-docs/maker/canvas-apps/using-logic-flows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/using-logic-flows.md)
* Service: **powerapps**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Looks like this is for a [different topic](https://docs.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined?view=o365-worldwide). Please submit the feedback on the topic that the feedback is for. For now, I've submitted this update to the said topic.
