### ISSUE TITLE
Validation errors FormXml.xsd

### ISSUE THREAD

**Issue by GerbenAbbink** [MicrosoftDocs/powerapps-docs#2481]
I get errors when I validate FormXml.xsd in XMLBlueprint XML Editor, using Xerces:

Description: FilterResults and FilterResults (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.
Details: cos-nonambig https://www.w3.org/TR/xmlschema-1/#cos-nonambig
File: FormXml.xsd 417:6
Processor: Xerces 2

Description: Pattern value '(?![cC][rR][mM]_)([A-Za-z0-9])+([_])+([A-Za-z0-9_])*' is not a valid regular expression. The reported error was: 'This expression is not supported in the current option setting.'.
Details: InvalidRegex https://www.w3.org/TR/xmlschema-2/#dt-regex
File: FormXml.xsd 892:4
Processor: Xerces 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8396f7-c76f-ec02-38f3-a04c1bed1a91
* Version Independent ID: 28486176-2a12-872e-7de1-d2a36f5b11a1
* Content: [Edit the customizations XML file with schema validation (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/edit-customizations-xml-file-schema-validation)
* Content Source: [powerapps-docs/developer/model-driven-apps/edit-customizations-xml-file-schema-validation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/edit-customizations-xml-file-schema-validation.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@GerbenAbbink Thanks for reaching to us. Can you provide us with more details what are you trying to do and when validating against the FormXML, what is the error.

**Comment by GerbenAbbink** [comment]
I am just validating FormXml.xsd and I noticed that it contains an error in the regular expression:

	<xs:simpleType name="FormQueryStringParameterNameAttributeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(?![cC][rR][mM]_)([A-Za-z0-9])+([_])+([A-Za-z0-9_])*"/>
		</xs:restriction>
	</xs:simpleType>

It does not follow the rules of [Regular Expressions in XML Schema](https://www.w3.org/TR/xmlschema11-2/#regexs).
