### ISSUE TITLE
FetchXML encoded or not?

### ISSUE THREAD

**Issue by polks71** [MicrosoftDocs/powerapps-docs#2482]
The doc says not to encode in the Parameters section.
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords#feedback

> When you specify a FetchXML query for the options parameter, the query should not be encoded.

But then in the FetchXML example it is encoding the FetchXML

`var fetchXml = "<fetch mapping='logical'><entity name='account'><attribute name='accountid'/><attribute name='name'/></entity></fetch>";
fetchXml = "?fetchXml=" + encodeURIComponent(fetchXml);`

Can the document clarify which is correct?

**Comment by Nkrb** [comment]
We have update the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
