### ISSUE TITLE
Custom API call from Power Automate

### ISSUE THREAD

**Issue by Antos2310** [MicrosoftDocs/powerapps-docs#2483]
The document states that "The Common Data Service (current environment) connector enables calling Custom APIs actions in Power Automate", since that is deprecated, is there plans to add this to the unbound actions as part of the Dataverse connector? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd53494-e9ff-33b0-d857-bcd235233aa5
* Version Independent ID: a362d3d7-3d5c-9222-39e6-dd426f96c4a4
* Content: [Create and use Custom APIs (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/custom-api)
* Content Source: [powerapps-docs/developer/data-platform/custom-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/custom-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
It is just the doc hasn't been updated to reflect the new name 'Common Data Service (Current Environment)' is the former name of the  Dataverse connector.

Submitted #2484 to update the name.
@phecke  can you make this change please?

**Comment by phecke** [comment]
@Antos2310 Document updated. Thanks for catching that.
