### ISSUE TITLE
"Get tooling for Power Apps component framework" doesn't show pre-requirements anymore

### ISSUE THREAD

**Issue by brasov2de** [MicrosoftDocs/powerapps-docs#2485]
The "Get tooling for Power Apps component framework" link doesn't include any pre-requirements anymore, like the versions from the history did.
I cannot find anywhere that npm is required, and which version is recommended.
It creates confusion for the beginners.
Here an example of older docs containing the requirements: https://github.com/MicrosoftDocs/powerapps-docs/blob/3e7c6d20f1b07e98cb105071c2899eefd5bc7c7c/powerapps-docs/developer/component-framework/get-powerapps-cli.md
Kind regards,
Diana

**Comment by Nkrb** [comment]
@brasov2de Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
