### ISSUE TITLE
Suggestions about new preview power apps cli

### ISSUE THREAD

**Issue by roninzr** [MicrosoftDocs/powerapps-docs#2486]
A good tool for manage power apps programlly!
Two suggests:
* About `pac paportal download` could we please link a default website that will be more easily integrate with pipelines.
* About `pac paportal`, shell we generate a new command to create new local file that could link with cloud.

Thanks for the great job!

Thanks,
Ruiwen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fffb76-5378-fe8a-62fc-0c82a6d03d6d
* Version Independent ID: 102ff357-ae01-8222-8c14-64e2a5e78a0b
* Content: [Portals support for Power Platform CLI (Preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/power-apps-cli)
* Content Source: [powerapps-docs/maker/portals/power-apps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/power-apps-cli.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback, and complement. For feature change ideas, suggestions, please reach out using [Power Apps community - Ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
