### ISSUE TITLE
Typo on the page

### ISSUE THREAD

**Issue by danikahil** [MicrosoftDocs/powerapps-docs#2487]
Hi Team,

I think the wrong Entity names are used on the page.
See my screenshot.
https://drive.google.com/file/d/1V3qqq5M1cdGaA7SdEfSmdYhLwtCk-go5/view

Regards,
Dani

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa09a110-d91d-b551-3cc8-5c6885857e65
* Version Independent ID: 3e787680-48f9-a3c6-73be-667be545e562
* Content: [Timeline Overview for Users - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/add-activities)
* Content Source: [powerapps-docs/user/add-activities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/add-activities.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@danikahil Thank you for the feedback. I'm checking in with our internal team to verify this info. Please stay tuned for an update.

Thank you,
Mints

**Comment by mduelae** [comment]
@danikahil The info you provided is correct. Thank you again for the feedback. The topic has been updated. You should see the changes by 2pm PDT.
