### ISSUE TITLE
Powerapp Functions (Sync or Async?)

### ISSUE THREAD

**Issue by vtxrodrickhales** [MicrosoftDocs/powerapps-docs#2488]
Make a note so the user can understand if Patch or any other related Powerapps functions are synchronous or asynchronous. I believe I have been using Patch to send updates in batches and clearing the collection before it finished.

Ex. 

Patch( 'Bank Accounts' colVeryImportantUpdates );
ClearCollect( colVeryImportantUpdates );

// No errors, but also no updates.

Powerapps Monitor tells a different story.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7f89e38-f935-5ffa-195d-7c3775313a22
* Version Independent ID: 4a6c1325-1ce8-81c5-451b-c66225c7fad1
* Content: [Update and UpdateIf functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-update-updateif)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-update-updateif.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-update-updateif.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@vtxrodrickhales Thanks for reaching to us.  Power Apps functions are Asynchronous. From maker perspective it appears that functions are synchronous because we synchronize first and then we do the next step. Closing the issue. If you need further help, please reopen or create a new issue.
