### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#2490]
Globla Discovery Service Endpoints:
s/b Global Discovery Service Endpoints:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e10e742e-cd30-8feb-ddff-c986e54e28dc
* Version Independent ID: 18763bf0-7fa9-6fac-a634-9a0dd584af6e
* Content: [Use the Discovery Service with the SDK Assemblies (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/discovery-service)
* Content Source: [powerapps-docs/developer/data-platform/org-service/discovery-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/discovery-service.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
This issue has been resolved now, and will go live shortly. 

Closing the issue.
