### ISSUE TITLE
Function "Substitute" is not valid

### ISSUE THREAD

**Issue by BigJazzz** [MicrosoftDocs/powerapps-docs#2491]
When trying to use the Substitute function as specified on the below page, I get the following error. If this function is no longer valid, the page needs to be updated.

`InvalidTemplate. Unable to process template language expressions in action 'Compose_2' inputs at line '1' and column '2536': 'The template function 'substitute' is not defined or not valid.'.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0c0cf0-d37b-f4f2-503c-8cbe667c83e6
* Version Independent ID: da1ec688-7d35-e153-2d87-6804ddc6785d
* Content: [Replace and Substitute functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-replace-substitute)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-replace-substitute.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-replace-substitute.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
@BigJazzz Thanks for reaching to us. We didn't find any issue while using the substitute function. can you let us know what you are trying to do. If you can paste the formula that would be helpful.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
