### ISSUE TITLE
Web Service Url Not acessible

### ISSUE THREAD

**Issue by RawishCRM** [MicrosoftDocs/powerapps-docs#2493]
Hi, Please confirm if web service is functioning, because I am getting below error: 
"Entity could not be retrieved from data source. Please try again or contact your system administrator."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b56c32-971a-739d-40b6-5e2a2fb82c65
* Version Independent ID: 219c2bb0-0b17-1af4-7b87-1ea3e9c3f228
* Content: [Virtual table walkthrough using the OData Data Provider in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/virtual-entity-walkthrough-using-odata-provider)
* Content Source: [powerapps-docs/maker/data-platform/virtual-entity-walkthrough-using-odata-provider.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/virtual-entity-walkthrough-using-odata-provider.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by RawishCRM** [comment]
Message: The remote server returned an error: (404) Not Found.

Above is the error from data provider plugin

**Comment by Mattp123** [comment]
@RawishCRM - if you are referring to the example web service URL "https://contosowebservice.azurewebsites.net/odata/" published in the article? As also stated just below it in the article, that URL isn't a functioning web service.
Closing issue.
