### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/powerapps-docs#2494]
Hello,

I am confused by these statements:

1. Capacity-based portals and add-on portals will use the same caching functionality.
2. Capacity-based portals don't have to manually clear the configuration table cache.

#1 seems to contradict the earlier statement "Capacity based portals have more options on <portal_path>/_services/about" .  Also, the use of the word "same".  The same as what?  I think what it's trying to say is "The cache operates the same way for Capacity-based portals and Add-on portals."

#2 A power user says [here](https://powerusers.microsoft.com/t5/Power-Apps-Portals/Saving-changes-in-Portal-Studio-and-Portal-Management-the-cache/m-p/960368#M7748) that config table cache is still subject to the 15 minute SLA.  That sounds like the same functionality prior to version 9.2.6.x.  As a portal developer, I need to know whether or not my config changes are taking effect immediately or are still impacted by the caching.

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5bd87e4-5fa8-0822-2dd8-989e453f2558
* Version Independent ID: 42963b75-3c09-223c-241d-9bc56154ba47
* Content: [Server-side cache in portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/clear-server-side-cache)
* Content Source: [powerapps-docs/maker/portals/admin/clear-server-side-cache.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/clear-server-side-cache.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been updated to address first one. Changes will be reflected soon. For second one, version 9.2.6.x and SLA change, please see this section in the important note:

*No change to SLA for cache refresh (data transfer between Dataverse and portal) mentioned earlier in this article.*
