### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by pratapladhani** [MicrosoftDocs/powerapps-docs#2496]
Broken Link:  Developer Documentation: Get started with virtual tables [https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/virtual-tables/get-started-ve] link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e835c37b-62fb-0ada-5cd7-b759c1e4cd66
* Version Independent ID: d14c2345-5a2a-16d1-d91e-6edcdcd4d04a
* Content: [Use the Virtual table OData v4 Data Provider with Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/virtual-entity-odata-provider-requirements)
* Content Source: [powerapps-docs/maker/data-platform/virtual-entity-odata-provider-requirements.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/virtual-entity-odata-provider-requirements.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@pratapladhani - thank you for your feedback. The link is fixed now and will be published live today.
