### ISSUE TITLE
Example for how to query optionset/choice values

### ISSUE THREAD

**Issue by brettlex** [MicrosoftDocs/powerapps-docs#2499]
Hello,

I have looked all over the place and can't find a single example of how to query entity metadata (choice values) using the Apache Spark pools in Azure Synapse link. One example of how to do or a link to how to configure that would be extremely useful. I see the metadata in the data lake here: Microsoft.Athena.TrickleFeedService/[entityname]-EntityMetadata.json, and I'm sure one could write a function to do that, but I really don't want to do callout functions to look for the text every time I want to write an export query to a non-CDM system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19489d66-04a5-73a7-ed5e-6a7f83290687
* Version Independent ID: f1ad4134-09ed-7683-2715-b6dda1ff8682
* Content: [Azure Synapse Link - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake)
* Content Source: [powerapps-docs/maker/data-platform/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sama-zaki** [comment]
Hi, thank you for your feedback. We are looking to support access the Dataverse choices by the end of 2021. In the interim, we will try to document a way to access the table-entityMetadata.json file from synapse.

**Comment by Mattp123** [comment]
@brettlex - Please see previous comment.
Closing issue.
