### ISSUE TITLE
export PowerAPPS

### ISSUE THREAD

**Issue by farielfly** [MicrosoftDocs/powerapps-docs#25]
hi, I want to know how can I export the PowerAPPS by powershell, is that possible? waiting for your response

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jamesol-msft** [comment]
Hi @farielfly ,

No this is not currently supported, but it is something that we are working on.  There are some platform changes ongoing around ALM that we are working on first before we can expose this functionality.

-James

**Comment by AFTOwen** [comment]
@jamesol-msft and @farielfly Is this issue ready to close? Thanks.

**Comment by farielfly** [comment]
@jamesol-msft ,many thanks for you reply,it is great  @AFTOwen, sure , please close it, thanks~
