### ISSUE TITLE
Need instructions on editing the url

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/powerapps-docs#2504]
This doc refers to the need to edit the URL in the Send Invitation process.  I looked all over and could not find instructions on how to do that.  It is not at all intuitive.  I finally found this video that explains it: [YouTube](https://www.youtube.com/watch?v=AftyWX99OI4&t=402s)

This was another big time-hog, adding to the adoption cost of this tech.  Thanks for taking a look.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97927ddf-353e-98e9-8e30-f1f2267c6f0b
* Version Independent ID: d728ae3e-9b17-8254-3e72-4cda2a006c1d
* Content: [Invite contacts to your portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/invite-contacts)
* Content Source: [powerapps-docs/maker/portals/configure/invite-contacts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/invite-contacts.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and the feedback. This is added for further consideration.
