### ISSUE TITLE
AppSource is no longer at home.dynamics.com

### ISSUE THREAD

**Issue by anotherRedbeard** [MicrosoftDocs/powerapps-docs#2505]
This statement is no longer correct:
Users can now run the app by using Power Apps Mobile on a mobile device or from AppSource on Dynamics 365 in a browser. Co-owners can edit and share the app in Power Apps.

When I navigate to home.dynamics.com, I get an error saying this is not available.  It would be nice to see an update to where this has moved to.

Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c12582-519a-606c-1f2e-8fe1f6ac5d2a
* Version Independent ID: 537b3097-4aa4-f3e5-b252-ffb832ecb1dc
* Content: [Share a canvas app with your organization - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @alaug
* Microsoft Alias: **alaug**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It's been replaced with https://www.office.com/apps, documentation is updated and will reflect this change soon.
