### ISSUE TITLE
Non-existent link for a term

### ISSUE THREAD

**Issue by ifromurgut** [MicrosoftDocs/powerapps-docs#2507]
In the last item of the list in the "Modify a record" section, the term (or a property name) Error does not refer to the desired page of that term.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d3b377-2f9f-67b0-4d7a-87776c96e2ea
* Version Independent ID: 9ba08546-4f01-31ec-dc3f-faa1068525db
* Content: [Understand data sources for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-data-sources)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-data-sources.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/working-with-data-sources.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. That is introduced earlier on in the article - [Working with tables bullet 3, last item](https://docs.microsoft.com/powerapps/maker/canvas-apps/working-with-data-sources#working-with-tables).
