### ISSUE TITLE
"Currency"

### ISSUE THREAD

**Issue by tomasschulkes** [MicrosoftDocs/powerapps-docs#2510]
Did you mean "accuracy" instead of "currency"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c6f95a-36dd-b10f-6aa9-2e26f30cbbb0
* Version Independent ID: fbe8fd48-a5df-9fc8-e1cd-ac647be0b9e6
* Content: [Position - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/position)
* Content Source: [powerapps-docs/developer/component-framework/reference/position.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/position.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@tomasschulkes Thanks for noticing the issue. We will update the docs and push it live. Closing the issue. If you need further help, please reopen or create a new issue.
