### ISSUE TITLE
Adding a DataTable to a Container control doesn't work correctly

### ISSUE THREAD

**Issue by MarrinerDev** [MicrosoftDocs/powerapps-docs#2511]
Adding a DataTable to a Container control (i.e. when the Container is the currently selected control) - either by the Insert menu or Copy/Paste does NOT work correctly. It results in the DataTable being inserted as a sibling of the Container.  As an aside, Gallery controls work correctly.

This problem is also mentioned on the Microsoft PA forum:

https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Allow-adding-DataTable-Control-into-Layout-Container-control/idc-p/973500#M33992

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Since this problem is already submitted through Power Apps Ideas for a fix, it'll go through the review. You can also reach out using [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to report this issue.
