### ISSUE TITLE
Project-details.xlsx workbook is missing in the document 

### ISSUE THREAD

**Issue by KavithaThanubuddi** [MicrosoftDocs/powerapps-docs#2513]
[Enter feedback here]
We don't see the project-details.xlsx workbook in the page to import into list. As there is no workflow with project details, while generating the power bi reports relationships concept is not clear. As these are sample projects for the beginners who are trying to learn power platform, it would be great if you can add the project details workbook with data.

https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-scenario-setup
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d58efad-c076-c853-dd96-e9e70e50187e
* Version Independent ID: fcb0aa59-c412-d81e-bc9e-89ac3eb339f2
* Content: [Set up lists for SharePoint Online integration with Power Apps, Power Automate, and Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-scenario-setup)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-setup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/sharepoint-scenario-setup.md)
* Service: **powerapps**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation includes the sample workbook that can be downloaded to get started in step 2:
https://docs.microsoft.com/powerapps/maker/canvas-apps/sharepoint-scenario-setup#step-2-create-and-review-the-lists
