### ISSUE TITLE
Component TSX has imports at the top that no longer build

### ISSUE THREAD

**Issue by brendon-colburn** [MicrosoftDocs/powerapps-docs#2514]
I was able to fix this and get it to build by changing it to the following:
`import { ChoiceGroup, IChoiceGroupOption } from '@fluentui/react/lib/ChoiceGroup';`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5338bf6-f6c2-fcf9-394f-e30871437de3
* Version Independent ID: 03fed979-b86f-d08b-d0ee-3b83b39c0966
* Content: [Creating a model-driven app field component in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/tutorial-create-model-driven-field-component#code)
* Content Source: [powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by brendon-colburn** [comment]
this approach does seem to eliminate the treeshaking as the file size is now several MBs again.  Probably need a better alternative.

**Comment by brasov2de** [comment]
Hi @brendon-colburn , 
have you seen this in the docs: https://docs.microsoft.com/en-us/powerapps/developer/component-framework/code-components-best-practices?WT.mc_id=BA-MVP-5004107#use-path-based-imports-from-fluent-to-reduce-bundle-size ?
Kind regards,
Diana

**Comment by scottdurow** [comment]
@brendon-colburn What is the error you get when you build? Which version of Fluent UI are you using?

**Comment by brendon-colburn** [comment]
@brasov2de I had not, I just read through that now and it provided some helpful context.  I think that tree-shaking ultimately comes into play more with production builds and may not have an impact on this issue, but I could be wrong.  @scottdurow has me taking on an alternative approach in the other issue thread based on having a older version of fluentui in place.

**Comment by Nkrb** [comment]
@brendon-colburn Closing this issue. If you need further help, please reopen or create a new issue.
