### ISSUE TITLE
More imports aren't building

### ISSUE THREAD

**Issue by brendon-colburn** [MicrosoftDocs/powerapps-docs#2516]
I was able to get it to build by doing this instead:
`import { Dropdown, IDropdownOption } from '@fluentui/react/lib/Dropdown';
import { Icon } from '@fluentui/react/lib/Icon';`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5338bf6-f6c2-fcf9-394f-e30871437de3
* Version Independent ID: 03fed979-b86f-d08b-d0ee-3b83b39c0966
* Content: [Creating a model-driven app field component in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/tutorial-create-model-driven-field-component#code)
* Content Source: [powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by scottdurow** [comment]
Hi @brendon-colburn - Same question as #2514 - What's the error when you build and which version of Fluent UI? The sample uses version 8.20 - see https://github.com/microsoft/PowerApps-Samples/blob/master/component-framework/ChoicesPickerControl/package.json

**Comment by brendon-colburn** [comment]
The error is this: ERROR in C:\repos\ChoicesPicker\ChoicesPicker\ChoicesPickerComponent.tsx(1,29)
      TS2307: Cannot find module '@fluentui/react/lib/components/ChoiceGroup/ChoiceGroup' or its corresponding type declarations.

The template brings in an out of date version:
![image](https://user-images.githubusercontent.com/16350948/124657348-66f57d80-de70-11eb-9fa7-340dcb541127.png)

I will try updating now and report back my findings.  Thanks @scottdurow

**Comment by brendon-colburn** [comment]
Updating the version solved the issue, thanks for the help @scottdurow.  

The documentation could be a bit more clear about the need to update the dependency in package.json and then run npm update.

**Comment by scottdurow** [comment]
Hi @brendon-colburn - glad that worked. The template doesn't actually install fluent - it's the `npm install @fluentui/react` that does that.

Perhaps you had a locally cached version of fluent in your npm cache from a previous install before v8? The install probably should be `npm install @fluentui/react@v8`

**Comment by brendon-colburn** [comment]
That sounds like the most probable cause and the potential documentation change wrapped into one 🙌

**Comment by Nkrb** [comment]
Closing the issue. If you need further help, please reopen or create a new issue.
