### ISSUE TITLE
Error message may have changed

### ISSUE THREAD

**Issue by markdebhailis** [MicrosoftDocs/powerapps-docs#2521]
I think the error message "No Sandbox Worker processes are currently available" has changed to "The plug-in execution failed because no Sandbox Hosts are currently available". Which means that if you search for this error you don't get a link to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9289ed-ac35-9cd1-1197-81e61f5154da
* Version Independent ID: 455f1b05-1d84-8822-8a81-de64529053ca
* Content: [Troubleshoot plug-ins (Microsoft Dataverse for Apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/troubleshoot-plug-in#error-no-sandbox-worker-processes-are-currently-available)
* Content Source: [powerapps-docs/developer/data-platform/troubleshoot-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/troubleshoot-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Thanks. Am updating the doc.
