### ISSUE TITLE
Code: 0x80090477 InnerError: '.

### ISSUE THREAD

**Issue by dipteshbose** [MicrosoftDocs/powerapps-docs#2525]
Dear Jim

Please investigate this new error code - Code: 0x80090477 InnerError: '.

Attached screenshot for your reference.

I encountered this error while authoring a power automate for a Power VA within Teams.

Power Automate Template Name: Send an adaptive card to a Teams channel

Note: 
![Capture](https://user-images.githubusercontent.com/65800453/124900608-df8a4480-dffe-11eb-835c-c47c32e8dbd1.PNG)
Flow checker has Zero errors in the flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 553b1619-3fbe-3f2b-be24-ac5e4810c469
* Version Independent ID: b066efc3-2a64-96af-ec2a-cf8eaf471db7
* Content: [Web service error codes (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/web-service-error-codes#feedback)
* Content Source: [powerapps-docs/developer/data-platform/org-service/web-service-error-codes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/web-service-error-codes.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@dipteshbose 
I believe this is a bug. Please contact technical support.
Dataverse for Teams offers a subset of the messages that are available. Certain deprecated messages available in Dataverse have are not available in Dataverse for Teams. Nothing you can do about it. The calling app should use Update rather than SetState.
