### ISSUE TITLE
Dataverse (D365 CE) Error 429 Too Many Request using Azure Data Factory

### ISSUE THREAD

**Issue by DanielHolth** [MicrosoftDocs/powerapps-docs#2526]
[Enter feedback here]
I'm migrating D365 CE production data into test environment using Data Factory. But at around 14k records at 25.653 KB/s I get this error: "The remote server returned an error: (429) Too Many Requests."
What is best practise to move huge amount of data from one spesific table (account) without replicating the whole environment?

We cant simply copy the whole prod environment because prod sync would start sending data through intergrations from the test environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6c11a1-c9f6-a904-f49a-0fedbe9f511f
* Version Independent ID: 7db20846-7922-23d4-f261-4c54e61b6913
* Content: [Service protection API limits (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/api-limits)
* Content Source: [powerapps-docs/developer/data-platform/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/api-limits.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@DanielHolth This is a support question but I will provide some useful links.

https://docs.microsoft.com/en-us/power-platform/admin/manage-configuration-data
https://docs.microsoft.com/en-us/power-platform/admin/move-environment-tenant

Read that material and then contact support for further assistance.
