### ISSUE TITLE
Get the Id of a Custom Process Action should read use Type =1 (Definition) not Type = 2 (Activation)?

### ISSUE THREAD

**Issue by simes1** [MicrosoftDocs/powerapps-docs#2527]
Under [Get the Id of a Custom Process Action](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/catalog-catalogassignment#get-the-id-of-a-custom-process-action) it says:

> "Make sure you to access the row where Type is **2**. This is the activated workflow."

But when creating a Catalog Assignment for an Action via the UI it looks like it uses **Type=1 (Definition)** not Type = 2 (Activation) because this is the filter used by most of the Process views.

This would appear to make sense because the GUIDs for the definitions should remain constant across instances whereas the activations (I would have thought - not checked) are likely to be different.

Are you sure the statement above under "Get the Id of a Custom Process Action" is correct?

--
Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cbb8766-eef4-4c34-b5ea-b771b8cc7f32
* Version Independent ID: db59bcf8-f0de-a216-3bb2-9b9891c7a26a
* Content: [Catalog and CatalogAssignment tables (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/catalog-catalogassignment)
* Content Source: [powerapps-docs/developer/data-platform/catalog-catalogassignment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/catalog-catalogassignment.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Checking with the developer.

**Comment by JimDaly** [comment]
You are correct. Thank you for reporting this. I'm updating the topic now.
