### ISSUE TITLE
Broken link "Microsoft Power Apps + Dynamics 365 Developer"

### ISSUE THREAD

**Issue by ddevine-msft** [MicrosoftDocs/powerapps-docs#2530]
Hyper link for "Microsoft Power Apps + Dynamics 365 Developer" leads to 404 not found https://docs.microsoft.com/en-us/learn/certifications/courses/mb-400t00

I believe the new link should be for PL-400 https://docs.microsoft.com/en-us/learn/certifications/courses/pl-400t00

**Comment by MargoC** [comment]
Fixed, thanks.
