### ISSUE TITLE
I'll wait

### ISSUE THREAD

**Issue by PeterHale53** [MicrosoftDocs/powerapps-docs#2534]
Think I'll wait until we can do it in the UI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52939b82-7a1e-7320-c0a4-be2ea7f59724
* Version Independent ID: c67af10a-57f8-b450-5e0f-6c3f7d22079a
* Content: [Use multi-table lookup columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/multitable-lookup?branch=pr-en-us-4448)
* Content Source: [powerapps-docs/developer/data-platform/webapi/multitable-lookup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/multitable-lookup.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by NHelgren** [comment]
Thanks for the feedback @PeterHale53 UI functionality is currently being worked on.
