### ISSUE TITLE
"How to switch to OAuth" is unclear

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/powerapps-docs#2536]
[Enter feedback here]
In the "If your code is using CrmServiceClient with the “Office365” authentication type:" section, options to fix the problem included "Switching to OAuth", and an example of a connection string is provided, however the way to set the new connection string is not specified except the general instruction "you are encouraged to create your own application registration in Azure Active Directory (Azure AD) for applications running in your tenant."

It would be more friendly to readers if the page can include URLs to contents that shows detailed steps to register an application in Azure AD and to create the new connection string, such as: 

https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect?view=op-9-1

https://docs.microsoft.com/en-us/powerapps/developer/data-platform/authenticate-oauth#types-of-app-registration

https://docs.microsoft.com/en-us/powerapps/developer/data-platform/walkthrough-register-app-azure-active-directory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62040095-4960-ad63-ed12-48400473e95c
* Version Independent ID: 063346b9-99f6-902f-710b-6badbd2a9830
* Content: [Use Office365 authentication with Microsoft Dataverse (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/authenticate-office365-deprecation#feedback)
* Content Source: [powerapps-docs/developer/data-platform/authenticate-office365-deprecation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/authenticate-office365-deprecation.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@user0604 Agreed. I will add some links.

**Comment by phecke** [comment]
@user0604 Added links to related content. Thanks for the feedback.
