### ISSUE TITLE
Redirect URI format is incorrect

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/powerapps-docs#2537]
[Enter feedback here]
This is what written in the article: 
When you select Native, you must provide a Redirect URI. This is a unique identifier to which Azure AD will redirect the user-agent in an OAuth 2.0 request. This is typically a value formatted like so: `//app:<guid>`.

The format is wrong. It's supposed to be `app://<guid>`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f57df6-59af-6e22-44d2-bc9bb1ee69c7
* Version Independent ID: fdce23ee-733d-bf3a-25c8-2ca6bfa8c852
* Content: [Use OAuth authentication with Microsoft Dataverse (Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/authenticate-oauth#feedback)
* Content Source: [powerapps-docs/developer/data-platform/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/authenticate-oauth.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@user0604 Thanks for catching that. I will update the article.
