### ISSUE TITLE
Azure Synapse Link for Dataverse - Logging and Alerting

### ISSUE THREAD

**Issue by subashsivaji** [MicrosoftDocs/powerapps-docs#2538]
Is there a way to alert if the synchronisation of a table to data lake storage or synapse analytics fails? - Currently apart from checking the User Interface in PowerApps there is no way to monitor the sync or alert when something goes wrong. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19489d66-04a5-73a7-ed5e-6a7f83290687
* Version Independent ID: f1ad4134-09ed-7683-2715-b6dda1ff8682
* Content: [Azure Synapse Link - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake)
* Content Source: [powerapps-docs/maker/data-platform/export-to-data-lake.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/export-to-data-lake.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by sama-zaki** [comment]
Thank you for your feedback. We are working on enhancing the user interface further, and it should be available soon in the next semester. You are correct that currently the best way to track the status is through the user interface in Power Apps

**Comment by Mattp123** [comment]
@subashsivaji  - See the previous comment. Closing issue.
