### ISSUE TITLE
AADB2C90057: The provided application is not configured to allow the 'OAuth' Implicit flow

### ISSUE THREAD

**Issue by hiroakimurata** [MicrosoftDocs/powerapps-docs#2540]
At the step to configure authentication settings for user flow, there is need to select Access tokens as an additional steps undocumented.
The process of login to power portal failed due to miss-configuration.
The error "AADB2C90057: The provided application is not configured to allow the 'OAuth' Implicit flow" has come.

The instruction should be modified as follows.
https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-azure-ad-b2c-provider-manual

* [before] Under Implicit grant, select the ID tokens check box.
* [after]    Under Implicit grant, select the Access tokens and the ID tokens check box.

![image](https://user-images.githubusercontent.com/40493139/125440005-a7641187-e7f4-49f8-9c97-32ee5b154564.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb5611f-dfc2-dab5-536c-b86db008b4bf
* Version Independent ID: db45733d-fcfb-e92b-1107-7a7ed3d57028
* Content: [Configure the Azure Active Directory B2C provider manually - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-azure-ad-b2c-provider-manual)
* Content Source: [powerapps-docs/maker/portals/configure/configure-azure-ad-b2c-provider-manual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-azure-ad-b2c-provider-manual.md)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The documentation has been updated to reflect use of **Access tokens (used for implicit flows)** instead. The changes will be visible soon. If there's any additional issue, please reach out using [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for investigation.
