### ISSUE TITLE
Add note to use msal.js instead

### ISSUE THREAD

**Issue by wlong27** [MicrosoftDocs/powerapps-docs#2542]
Should add a note that msal.js to be used moving forward.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a51d2ac-2b1c-d708-dd48-3b1ec982f61c
* Version Independent ID: bc3282d9-d484-23d6-6d68-d374d14d2935
* Content: [Walkthrough: Registering and configuring a SimpleSPA application with adal.js (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/walkthrough-registering-configuring-simplespa-application-adal-js)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-registering-configuring-simplespa-application-adal-js.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/walkthrough-registering-configuring-simplespa-application-adal-js.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **nabuthuk**

**Comment by phecke** [comment]
@wlong27 Yes, you are correct that is the future path. However, mentioning that now when we do not have example code or other instructions is going to get us more issues filed with no good responses. I would rather wait until we have something useable to show. Thanks for the suggestion.
