### ISSUE TITLE
add licensing and other Teams app data storage options

### ISSUE THREAD

**Issue by DanStevensonMSFT** [MicrosoftDocs/powerapps-docs#2543]
Please add a row to the table about licensing requirements. 

Please also add other data storage options e.g. Azure SQL, COSMOS.

Customers often ask us (Teams engineering) those questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a7fa1a-8aeb-414a-fe50-ffe4efe4246b
* Version Independent ID: c9051ed9-a131-0f32-4a8b-705830ef2c15
* Content: [Comparing Microsoft Lists, Dataverse for Teams, and Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/compare-data-sources)
* Content Source: [powerapps-docs/teams/compare-data-sources.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/compare-data-sources.md)
* Service: **powerapps**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@DanStevensonMSFT - Licensing and integrations (Synapse Link for Dataverse and Data Export Service) are outside the scope of this article and covered in other articles. I've added a link to the location of the Dataverse and Dataverse for Teams licensing FAQs. The article already includes a link to where integration is covered: [Integration](https://docs.microsoft.com/en-us/power-apps/teams/data-platform-compare#integration)

Closing issue.
