### ISSUE TITLE
Broken link. 'Learning catalog'

### ISSUE THREAD

**Issue by Vitalii-Hlushkov** [MicrosoftDocs/powerapps-docs#2554]
https://docs.microsoft.com/en-us/powerapps/learning-catalog/powerapps-docs/learning-catalog/learning-catalog.md

![image](https://user-images.githubusercontent.com/11351037/125781763-9c45b354-2ae2-4126-9022-676d8ca7a5d7.png)

**Comment by MargoC** [comment]
Thanks for the feedback, fixed.
