### ISSUE TITLE
Exampling on how to count values

### ISSUE THREAD

**Issue by atif-hafeez** [MicrosoftDocs/powerapps-docs#2557]
Can you please show an example on how to show the count of values grouped by a certain field. For example, i have a table name site, Status. I would like to know how many sites were assigned a certain status in a tabular format using powerapps

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6475f03b-fa97-7722-ce5d-a98b9d66bcc3
* Version Independent ID: 24ed15d4-5500-ea1b-bdd0-b9b563947ea9
* Content: [GroupBy and Ungroup functions in Power Apps - Power Apps](https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/functions/function-groupby)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-groupby.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-groupby.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It depends on how you want to work with the app. You can reach out to the [Power Apps community forum](https://powerusers.microsoft.com/t5/Forums/ct-p/PA_Comm_Forums) for help.
For example, 
```powerapps-dot
ClearCollect (
    mytable,
    {Site: "SiteA", Status: "StatusA"}, 
    {Site: "SiteB", Status: "StatusB"}, 
    {Site: "SiteC", Status: "StatusC"}, 
    {Site: "SiteA", Status: "StatusA"}, 
    {Site: "SiteB", Status: "StatusB"}
);
ClearCollect(
    siteA,
    Filter(mytable, Site = "SiteA")
);
CountRows(siteA);
Set(Label1Text,CountRows(siteA));
```
Repeat creating collections for SiteB, SiteC likewise, and then use a collection for site/status.
