### ISSUE TITLE
Mistake in "Add Editable table" page under "Step 5: Set up edit and cancel options" on the 6th point. 2369466

### ISSUE THREAD

**Issue by jitheshk79** [MicrosoftDocs/powerapps-docs#2559]
[in "Add Editable table" page under "Step 5: Set up edit and cancel options" on the 6th point.
For Cancel Icon, "Visibility" is set to "galleryDisplayMode = DisplayMode.Disabled".

Cancel icon should be visible when Gallery is editable but here we are saying it should be visible when Gallery Display mode is disabled. Hope this is a mistake.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5761783-eeb8-2a47-bd89-7add589cf4b2
* Version Independent ID: 3f1a4081-70ff-83d9-4f58-87721272986c
* Content: [Add editable tables in canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-editable-tables)
* Content Source: [powerapps-docs/maker/canvas-apps/add-editable-tables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/add-editable-tables.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @denisem-msft
* Microsoft Alias: **denisem**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed and the change will be visible soon.
