### ISSUE TITLE
c# SqlConnection support?

### ISSUE THREAD

**Issue by larlew** [MicrosoftDocs/powerapps-docs#2563]
Can you connect via a .NET Core application, using a Microsoft.Data.SqlClient.SqlConnection and a connection string?

I am trying to use a connection string like:
using SqlConnection conn = new SqlConnection("Server=<serverName>.crm.dynamics.com;Authentication=Active Directory Password; User Id=<userName>;Password=<MyPassword>");
conn.Open();  // Call to open just hangs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ead09d9-3e51-04ce-dc6e-ac9bb59816ec
* Version Independent ID: 94d19f8d-3c5e-8ed9-53ee-4b6173f49144
* Content: [Use SQL to query data (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-sql-query.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@larlew The answer is no, you cannot connect using an API. Only the SSMS application and Power BI are presently supported. 

[Applications support](https://docs.microsoft.com/powerapps/developer/data-platform/dataverse-sql-query#applications-support)

**Comment by RichdiMSFT** [comment]
Hi Peter,

I can't seem to edit the comment. Can you add that this is on the backlog to add more client specifically .net client support.

Thanks,
Rich
