### ISSUE TITLE
Not easy and some quirks

### ISSUE THREAD

**Issue by Plepoutre2019** [MicrosoftDocs/powerapps-docs#2564]
a) step 5 I couldnt get the button to be visible, and so I changed the Visible expression to locVisibleCampaignIdea And 
 locCreateNewIdea. I still dont know if it's a good idea...
b) step 23 In the context I had, the galIdeaResponses_2 was galIdeaResponses_1 
c) changes are done to the table but doesnt show up until I click again on the campaign (first screen needs a refresh)
d) couldnt add a file.... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73fed2c1-db9f-18f7-987c-49bb4c758953
* Version Independent ID: d1233074-038e-e535-564d-43a8f37ac6e0
* Content: [Make ideas editable by original creator - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/make-ideas-editable-by-original-creator)
* Content Source: [powerapps-docs/teams/make-ideas-editable-by-original-creator.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/make-ideas-editable-by-original-creator.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **v-shrutibahl**

**Comment by joel-lindstrom** [comment]
@bishalgoswami @navjotm @sbahl10 
a) The Visible property of the Edit button is correct as it should be visible only when we are viewing an existing idea that was created by the user. Select an idea to open it and then the Edit button should be available on the screen. Please let me know if it still doesn't show.
b) Yes, then yes it should be _1
c) if you are in the studio, you can click on the three dots next to the table and select Refresh to refresh the data
d) need more details about this
