### ISSUE TITLE
pac install latest

### ISSUE THREAD

**Issue by readyxrm** [MicrosoftDocs/powerapps-docs#2565]
"pac install latest" does not work, get a "Error: Not a valid command. Try running 'pac [command] help'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0e3024-713b-e281-1417-21106fda3045
* Version Independent ID: 177d4ac9-7856-cbea-dc61-a7d11a909273
* Content: [Microsoft Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli)
* Content Source: [powerapps-docs/developer/data-platform/powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/powerapps-cli.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@readyxrm Thanks for reaching to us. I tried using the `pac install latest` command it works fine and doesn't show any error. Can you provide us with more information.

**Comment by readyxrm** [comment]
Hi @Nkrb Thank you for the quick response.  I am doing it from the VS Code terminal (maybe that is not the correct way?)  Attached is a screenshot. 
![2021-07-21_14-54-43](https://user-images.githubusercontent.com/18264651/126544471-a980ce8c-8304-4e2e-ae52-0687075a45cc.jpg)

**Comment by scottdurow** [comment]
Hi @readyxrm - If you are using the `pac cli` via the VSCode extension then `pac install` command is not available since the VSCode extensions handles the upgrade process.

**Comment by readyxrm** [comment]
> Hi @readyxrm - If you are using the `pac cli` via the VSCode extension then `pac install` command is not available since the VSCode extensions handles the upgrade process.

Thanks Scott!

**Comment by readyxrm** [comment]
Thanks, I updated vis VSCode extensions and updated to 1.8.5... Thanks everyone for the help!
