### ISSUE TITLE
Not a Canvas App

### ISSUE THREAD

**Issue by xotan135** [MicrosoftDocs/powerapps-docs#2567]
This page doesn't display a canvas app nor describe how to create one. The one featured is the small scale app..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb0d2a4-5d04-386b-932d-abc281602d68
* Version Independent ID: da875c8e-11f3-ccc0-4348-4721933018a2
* Content: [Create a canvas app from a SharePoint list - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/app-from-sharepoint)
* Content Source: [powerapps-docs/maker/canvas-apps/app-from-sharepoint.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/app-from-sharepoint.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The canvas app that gets created in this tutorial is through the default capability. For building app from scratch, see the SharePoint integration scenarios link at the bottom of the topic, and the scenario for building an app from scratch.
