### ISSUE TITLE
App Name changed from "Common Data Service" to "Dataverse"

### ISSUE THREAD

**Issue by jcbrooks92** [MicrosoftDocs/powerapps-docs#2569]
The Application ID now seems to have changed from "Common Data Service" to "Dataverse". For anyone else who may struggle to find the right value try searching the ID "00000007-0000-0000-c000-000000000000"

**Comment by jcbrooks92** [comment]
Reference doc: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/walkthrough-register-app-azure-active-directory#create-an-application-registration

**Comment by phecke** [comment]
@jcbrooks92 Yes, we were expecting that name change. Thanks for letting me know. I will update the documentation.

**Comment by phecke** [comment]
@jcbrooks92 Fixed. Will be published shortly. Thanks
