### ISSUE TITLE
Misspelling in the https://docs.microsoft.com/en-us/powerapps/user/add-activities#add-a-mention-or-reference-a-team-member-in-a-note

### ISSUE THREAD

**Issue by Vitalii-Hlushkov** [MicrosoftDocs/powerapps-docs#2571]
[Enter feedback here]
Switch views using Advanced to display the Lookup Records pane. In the Lookup Records pane, you can switch between the Recent records and All records view to search **rerowscords**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa09a110-d91d-b551-3cc8-5c6885857e65
* Version Independent ID: 3e787680-48f9-a3c6-73be-667be545e562
* Content: [Timeline Overview for Users - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/add-activities)
* Content Source: [powerapps-docs/user/add-activities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/add-activities.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@Vitalii-Hlushkov thank you for the feedback. I updated the topic and changes will go live on the site by noon today.

Thanks,
Mints
