### ISSUE TITLE
Synch calls not possible?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#2574]
We need synch calls to filter lookups (presearch) and to check, if a ribbon button should be visible or not. I guess we still need to rely on other frameworks or own http requests for those scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c196bb-4bbb-80e2-0bba-42d130621024
* Version Independent ID: 56d1575c-1868-34c6-992d-e3797024e413
* Content: [retrieveMultipleRecords (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrievemultiplerecords)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/retrieveMultipleRecords.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by fowl2** [comment]
Ribbon enable rules can return promises. ie. you can use async functions and await:

``` javascript
async function enableRibbonButtonIfThereAreMoreThanThree() {
    const r = await Xrm.WebApi.retrieveMultiple('my_greatentity');
    return r.entities.length > 3;
}
```
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/define-ribbon-enable-rules#custom-rule 

Presearch is a bit harder and I agree it should be enhanced.

Synchronous HTTP calls have been deprecated are in the process of being removed from web browsers.

**Comment by Nkrb** [comment]
@darshSWL We hope that you got the information you're looking for. Closing this issue. If you need further help, please reopen or create a new issue.
