### ISSUE TITLE
BUG REPORT - GeoSpatial Control - ShowShapeLabels

### ISSUE THREAD

**Issue by paulojrech** [MicrosoftDocs/powerapps-docs#2575]
The boolean parameter **ShowShapeLabels** doesn't work. 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9e34915e-ffa9-9a20-55c6-c9e71561f9be
* Version Independent ID: 673a113e-5978-85d2-699a-44e1a5a5fdf7
* Content: [Adicionar componentes geoespaciais a aplicativos feitos com o Microsoft Power Apps - Power Apps](https://docs.microsoft.com/pt-br/powerapps/maker/canvas-apps/geospatial-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/geospatial-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/geospatial-overview.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
I checked with our engineering team and can confirm it's working as described (should show the labels or not). For further troubleshooting you might like to try asking about your issue at the [Power Apps forum](https://powerusers.microsoft.com/t5/Building-Power-Apps/bd-p/PowerAppsForum1).

**Comment by paulojrech** [comment]
Hi. Thanks for the answer.

Here below you can see the issue happening... It happens once... The second time I access this screen, the map doesn’t show the shape labels.

***@***.***


Prof. Paulo J. Rech


De: iaanw ***@***.***>
Enviada em: terça-feira, 27 de julho de 2021 20:18
Para: MicrosoftDocs/powerapps-docs ***@***.***>
Cc: Paulo Jaco Rech ***@***.***>; Author ***@***.***>
Assunto: Re: [MicrosoftDocs/powerapps-docs] BUG REPORT - GeoSpatial Control - ShowShapeLabels (#2575)


I checked with our engineering team and can confirm it's working as described (should show the labels or not). For further troubleshooting you might like to try asking about your issue at the Power Apps forum<https://powerusers.microsoft.com/t5/Building-Power-Apps/bd-p/PowerAppsForum1>.
