### ISSUE TITLE
Licensing Restrictions

### ISSUE THREAD

**Issue by smgtreker** [MicrosoftDocs/powerapps-docs#2576]
Should there not be a section on licensing restrictions? E.g. Do you need a Customer Service License to provision queues?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb65076-22b5-54a1-a2a6-18ac81b89e9b
* Version Independent ID: 60609e68-5ccb-9a9f-f21b-1fdc455bd515
* Content: [Queue tables (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-gb/powerapps/developer/data-platform/queue-entities)
* Content Source: [powerapps-docs/developer/data-platform/queue-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/queue-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@smgtreker There is no licensing information in the developer documentation.

Look here instead: [Power Apps licensing](https://docs.microsoft.com/en-us/power-platform/admin/pricing-billing-skus)
