### ISSUE TITLE
Issue Reporting

### ISSUE THREAD

**Issue by lrjbrual** [MicrosoftDocs/powerapps-docs#2577]
I would like to seek your assistance, on how we can add the custom email address for the issue reporting for instance our customer send an email to support@gmail.com then it will automatically create a issue task for us. but however I cannot find any documentation about it. 

That would be helpful if someone can share the information how to do it. 

Thank you in advance. 

Regards,
Ryan

**Comment by Nkrb** [comment]
Thanks for contacting us. Can you point us to the doc page you're referring. It helps us assign the issue to the correct writer.

**Comment by phecke** [comment]
@lrjbrual  Thanks for contacting us. 

If you have a question about the Power Apps documentation, then provide us a link to the specific topic.

Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ 

This issue will be closed in a few days if we do not hear back from you..

**Comment by KumarVivek** [comment]
Closing the issue.
