### ISSUE TITLE
GCC Availability

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/powerapps-docs#2578]
Dataverse for Teams is now available in GCC. Doc should be updated with the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c830299-300a-39dc-b1ab-6a3a0428901c
* Version Independent ID: d0a364b2-2692-32fe-a657-40edf8b13009
* Content: [Known issues and limitations for Dataverse for Teams - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/known-issues-limitations)
* Content Source: [powerapps-docs/teams/known-issues-limitations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/known-issues-limitations.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The updated content will be visible soon.
