### ISSUE TITLE
日本語訳の誤り

### ISSUE THREAD

**Issue by Vendetta1209** [MicrosoftDocs/powerapps-docs#2579]
> キャンバス アプリを実行するためにサポートされているブラウザーのプラットフォーム
> オペレーティング システム
> 窓

「Windows」が「窓」と日本語に訳されています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d2e8858f-ee37-b1f0-2ad1-a52416f58d0d
* Version Independent ID: 23c5799a-0e3a-bd52-8f8c-ce586c93e632
* Content: [キャンバス アプリのシステム要件、制限、構成の値 - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/limits-and-config)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **gregli**

**Comment by jowilco** [comment]
@Vendetta1209 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@Vendetta1209 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
