### ISSUE TITLE
Missing file to download

### ISSUE THREAD

**Issue by krpoluru** [MicrosoftDocs/powerapps-docs#2581]
project-details.xlsx workbook not available to download

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d58efad-c076-c853-dd96-e9e70e50187e
* Version Independent ID: fcb0aa59-c412-d81e-bc9e-89ac3eb339f2
* Content: [Set up lists for SharePoint Online integration with Power Apps, Power Automate, and Power BI - Power Apps](https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/sharepoint-scenario-setup)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-setup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/sharepoint-scenario-setup.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed, changes will be visible soon.
