### ISSUE TITLE
Receiving an error when try to retrieve an access token using .NET 5.0

### ISSUE THREAD

**Issue by existentialist1888** [MicrosoftDocs/powerapps-docs#2584]
I followed the instructions step by step, the only exception being that I'm using .NET 5.0, since that's the current version and the version we run.  However, when I run the example I'm getting the error below on the authContext.AcquireToken line.  I have not found another way to get the access token for Azure Active Directory and I have a project with a very tight deadline involving this.

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Source=Microsoft.IdentityModel.Clients.ActiveDirectory
  StackTrace:
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(String resource, String clientId, UserCredential userCredential)
   at DynamicsWebAPIQuickStart.Program.Main(String[] args) in C:\Users\shawn.broadhead\source\repos\tutorials\DynamicsWebAPIQuickStart\DynamicsWebAPIQuickStart\Program.cs:line 29

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Sample is using 4.6.2
You can expect different results for different versions of .NET.
Note taken that we should update the sample for .NET 5.0.

**Comment by existentialist1888** [comment]
Is there a working example of this anywhere using .net 5.0?  I've looked everywhere and I can't find one.
