### ISSUE TITLE
An example would be nice

### ISSUE THREAD

**Issue by mattiaspihl** [MicrosoftDocs/powerapps-docs#2586]
"A simple console client application is a good way to familiarize yourself with the Dataverse APIs." 
After a statement like that a code example of (or a link to) said console client application whould be provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd24851b-e898-2acd-dcb5-d35f1aaf2f08
* Version Independent ID: af719f70-dcbc-7ec7-d4b8-1b7343dcd1a9
* Content: [Developers: Get started with Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/get-started-developers)
* Content Source: [powerapps-docs/developer/data-platform/get-started-developers.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/get-started-developers.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@mattiaspihl Take a look at this one.

[Sample: Quick start for XRM Tooling API](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/sample-quick-start-xrm-tooling-api)

The reason the sample uses XRM Tooling is because it makes authentication much simpler.
