### ISSUE TITLE
Select appropriate frame to debug in the new Unified Interface forms

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#2589]
Frame named ClientApiFrame_[n] is not found in the Page tab of the Sources for the new Unified Interface forms.
Instead, it can be found in the screenshot below.
![image](https://user-images.githubusercontent.com/14156926/127421836-c0f49a20-4240-4d5f-aac1-2256db0fbe9b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61cf532-f935-772c-a80d-5310767ffbdc
* Version Independent ID: 8eca9f5e-ebd1-5d6b-0e5e-3d42777b1390
* Content: [Debug your JavaScript code for model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/debug-javascript-code)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/debug-JavaScript-code.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/debug-JavaScript-code.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by LinnZawWin** [comment]
That's correct, @Nkrb. I am suggesting updating the doc on where to find the script to debug because the **ClientAPiFrame_[n] method** is no longer applicable in the current version of Unified Interface forms. (or if it still works, adding a screenshot would be really helpful)

**Comment by JimDaly** [comment]
@LinnZawWin 
Thank you for providing this. I will test this and update the doc as soon as I can.

**Comment by JimDaly** [comment]
@LinnZawWin 
I updated this doc today.  It will go live this afternoon (PST). Replaced everything and added some steps about debugging on mobile devices.

We aren't going to try and teach people how to debug, but we want to highlight anything that is out of the ordinary. 
Please let us know if there is anything more along those lines we might include here.

Thanks for your feedback.
