### ISSUE TITLE
Clearer understanding on "remove value" for current value

### ISSUE THREAD

**Issue by rforster-dev** [MicrosoftDocs/powerapps-docs#2590]
The current documentation is ambiguous around what it means around "Remove the value from your solution".

Does that mean: 

- leave it blank?
- "Remove from solution"

This is unclear and very confusing on what is actually meant. It should be very clear that it means "Click on the 3 dots and click "Remove from solution".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba670cf8-5810-79c4-7a2a-101099ffe1d7
* Version Independent ID: 69b7e1fb-9f56-8c07-b1d5-8480fe6d8e1a
* Content: [Use environment variables in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/environmentvariables)
* Content Source: [powerapps-docs/maker/data-platform/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/EnvironmentVariables.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@rforster-dev - Thank you for your feedback. The article has been updated to include the following procedure: 
To remove the value, follow these steps:
1. In the solution where the environment variable is located select the environment variable to display the properties.
1. Under to the Current Value, select ... > Remove from this solution.
![image](https://user-images.githubusercontent.com/21203819/127896526-bf5217db-abf6-462d-9140-eda46cbf9415.png)

Closing issue.

**Comment by rforster-dev** [comment]
Thanks for the prompt feedback! Looks good and is much clearer now 👍
