### ISSUE TITLE
Please adhere to visualization best practices: remove the pie chart

### ISSUE THREAD

**Issue by jeroenterheerdt** [MicrosoftDocs/powerapps-docs#2592]
Can we please not use a pie chart on this page? It's against data visualization best practices, so please pick anything else, but not the pie.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1035def6-8f97-9b41-da38-66b3c7a653b9
* Version Independent ID: 4e9f789d-2b26-8cd7-7c3f-a76ded632dbc
* Content: [Analyze Microsoft Dataverse exported to Azure Data Lake Storage Gen2 data with Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake-data-powerbi)
* Content Source: [powerapps-docs/maker/data-platform/export-to-data-lake-data-powerbi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/export-to-data-lake-data-powerbi.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@jeroenterheerdt - thank you for your feedback. Can you provide more detail about why a pie chart shouldn't be used for a basic data visualization example? Also, for the basic data visualization example, which chart type would you recommend?

**Comment by jeroenterheerdt** [comment]
@Mattp123 don't take my word on it, but take Stephen Few's word on it (all well-known data visualization guru): https://www.perceptualedge.com/articles/visual_business_intelligence/save_the_pies_for_dessert.pdf.

I'd recommend anything that leverages straight lines, such as a treemap or something else.
