### ISSUE TITLE
Microsoft.PowerPlatform.Dataverse.Client.ServiceClient Throttling

### ISSUE THREAD

**Issue by lwalker-kforce** [MicrosoftDocs/powerapps-docs#2593]
I was unable to find any information on throttling for the Microsoft.PowerPlatform.Dataverse.Client.ServiceClient if any is applicable. Any pointers would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6c11a1-c9f6-a904-f49a-0fedbe9f511f
* Version Independent ID: 7db20846-7922-23d4-f261-4c54e61b6913
* Content: [Service protection API limits (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/api-limits#service-protection-api-limit-errors-returned)
* Content Source: [powerapps-docs/developer/data-platform/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/api-limits.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Microsoft.PowerPlatform.Dataverse.Client.ServiceClient is an alpha release.
See the Github project for support and information: https://github.com/microsoft/PowerPlatform-DataverseServiceClient

**Comment by JimDaly** [comment]
But I understand it will work just the same as the CrmServiceClient mentioned in this topic.
