### ISSUE TITLE
Exporting/cloning solution targetversion parameter

### ISSUE THREAD

**Issue by ramonahyde** [MicrosoftDocs/powerapps-docs#2598]
Hello!

I would like to know when this parameter will be implemented in the commands `pac solution clone` and `pac solution export`. For now (current version: 1.8.6), I've got this message `Exporting to a target version is not supported in this release.`. The doc doesn't mention that.

When it will be added, is it the same as doing this on the interface?

![image](https://user-images.githubusercontent.com/82847159/127635975-2cd2f766-dffb-4b1f-a792-f18c7f79d659.png)

Or does it change the version in the solution project only?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0e3024-713b-e281-1417-21106fda3045
* Version Independent ID: 177d4ac9-7856-cbea-dc61-a7d11a909273
* Content: [Microsoft Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli#install-microsoft-power-platform-cli)
* Content Source: [powerapps-docs/developer/data-platform/powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/powerapps-cli.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ramonahyde The *targetversion* parameter is added to docs for both **Clone** and **Export** command. Closing the issue. If you need further help, please reopen or create anew issue.
