### ISSUE TITLE
There shouldn't be space between '--  name' in export command

### ISSUE THREAD

**Issue by sanjeev40084** [MicrosoftDocs/powerapps-docs#2599]
[Enter feedback here]
In documentation it says to export solution, run this command: 
`pac solution export --path c:\Users\Documents\Solution.zip -- name SampleComponentSolution --managed true --targetversion 10.0.03 --include general`

But if you execute this command with your solution name, it will throw an error. 

It should be this instead (no spaces between ''--" and "name"): 
`pac solution export --path c:\Users\Documents\Solution.zip --name SampleComponentSolution --managed true --targetversion 10.0.03 --include general`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0e3024-713b-e281-1417-21106fda3045
* Version Independent ID: 177d4ac9-7856-cbea-dc61-a7d11a909273
* Content: [Microsoft Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli#solution)
* Content Source: [powerapps-docs/developer/data-platform/powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/powerapps-cli.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
