### ISSUE TITLE
Add Data Integration tab documenation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#26]
Please add some documentation for the Data Integration tab (page) that is shown in the screen shot above. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab497f2-57e7-2992-7286-d8032b6308ea
* Version Independent ID: 276b8930-20f7-8157-a983-5d0bfb6c302b
* Content: [What is Common Data Service for Apps? - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-intro.md)
* Service: **powerapps**
* GitHub Login: @clwesene
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Added link to topic that covers a data integration scenario and placed same topic in TOC. https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro#integrating-data-into-the-common-data-service
