### ISSUE TITLE
Business Rule Scope

### ISSUE THREAD

**Issue by YahyaManasrah** [MicrosoftDocs/powerapps-docs#2600]
Business Rule Scope should be extended to a form tab so i can show/hide a tab based on business rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76443691-3e03-e2ac-53e6-a2af78659435
* Version Independent ID: 3ca3568e-bcab-1892-309e-31be43c9d33f
* Content: [Create a business rule in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-create-business-rule)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-create-business-rule.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-create-business-rule.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by Mattp123** [comment]
@YahyaManasrah - Thanks for your feedback. For feature requests, vote or suggest a feature here [Power Apps community ideas](https://ideas.powerapps.com).  

Closing this issue.
