### ISSUE TITLE
Typo in Content (Page Title)

### ISSUE THREAD

**Issue by skuntze** [MicrosoftDocs/powerapps-docs#2604]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c487a-6048-5ed1-d3b3-f15756f0f953
* Version Independent ID: 35502302-bdf4-6a02-11cb-dea21d9fa7ff
* Content: [Import components into model-driven apps in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls#deploying-code-components)
* Content Source: [powerapps-docs/developer/component-framework/import-custom-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/import-custom-controls.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
