### ISSUE TITLE
Component Library reference left in solution and Model Driven App after removing new command.

### ISSUE THREAD

**Issue by ahmet269** [MicrosoftDocs/powerapps-docs#2605]
I have noticed that after removing a command which was added using new Command Designer, the Canvas Component Library which was created as part of the command cannot be deleted now. It left a model driven app element component in the solution and i am now unable to remove this. plus if i try to delete the component library via apps in power app maker , it does not get deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23305f64-b1e0-b0b8-9198-a509c1507474
* Version Independent ID: 3b67f692-29f8-ab4d-2a56-71528ed96755
* Content: [Manage commands in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/manage-commands-in-solutions)
* Content Source: [powerapps-docs/maker/model-driven-apps/manage-commands-in-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/manage-commands-in-solutions.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by ahmet269** [comment]
Just another update on this after managing to deep down a bit deeper into the issue. When the new command button, the app element record which is created to link the button to the model driven app and then component library is left behind and this is the reason why we cannot delete the component library created. tried to run a delete request to the app element and no luck, and tried to update its parentappid to another app and no luck. the requests execute as expected but the change doesnt take place for some weird reason.

**Comment by Mattp123** [comment]
@ahmet269 - I believe you have to delete the model-driven app element record first, which requires a flow as it can't be deleted directly from any of the maker interfaces. Go to https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/command-designer-limitations#delete-a-model-driven-app-element-record
Closing issue.
