### ISSUE TITLE
File Columns - Download Chunk Size Limit

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#2606]
This document indicates that the chunk size restriction for file uploads has been removed - does it still apply for downloads?

If not, it'd be helpful to mention [GetFileSasUrl](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/getfilesasurl) as an alternative.

`/api/data/v9.0/GetFileSasUrl(FileAttributeName=@FileAttributeName,Target=@Target)?@FileAttributeName='my_attribute'&@Target={"@odata.id":"my_entitys(b8d38747-38f4-eb11-94ef-0022481808c2)"}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/file-attributes)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by NHelgren** [comment]
@fowl2  The ability to download large files without chunking was disabled while we resolved an issue. It has been reenabled and has started to roll back out to all regions. It should be worldwide in the next 2-4 weeks.

**Comment by phecke** [comment]
@fowl2 Thanks for your feedback. Since the download without chunking is being re-enabled, I will not be adding your tip to the docs. Thanks for offering it though.
