### ISSUE TITLE
File Columns - Mime Type

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#2607]
[CommitFileBlocksUploadRequest has a MimeType](https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.commitfileblocksuploadrequest.mimetype) parameter.

1. I'm guessing is equivalent to the `Content-Type` header that's set to `application/octet-stream` in the REST example?
2. Is there any way of retrieving it as a attribute/navigation property, etc?
2. It seems `/$value` is always returned with a `Content-Type` of `application/octet-stream`?

NB: I can see a "MimeType" property in [FileSasUrlResponse](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/filesasurlresponse), but haven't tested it, and this requires an extra request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/file-attributes)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by fowl2** [comment]
[InitializeFileBlocksDownloadResponse](https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.initializefileblocksdownloadresponse) does not have a MimeType property.

**Comment by NHelgren** [comment]
@fowl2   Metadata for the File data type is stored in the FileAttachments table. This query should let you retrieve that information:
api/data/v9.0/<<YourTable>>/<<YourFileAttachmentsTable>>?$select=mimetype

You can find the name of the FileAttachments table for your table by running api/data/v9.0/$metadata against the table that has the file column

**Comment by phecke** [comment]
@fowl2 I hope NHelgren's response helps to answer your question. If not, open a new issue.

**Comment by fowl2** [comment]
Thanks for the response but you only seem to have answered 1 of my 3 questions?

**Comment by fowl2** [comment]
Also thanks for the pointer to https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/fileattachment?view=dynamics-ce-odata-9 - perhaps it could referenced from the article?

**Comment by NHelgren** [comment]
I will review getting that information into the article. As for the other two questions, yes the /$value always returns application/octet-stream details.
