### ISSUE TITLE
Missing documentation for solution commands

### ISSUE THREAD

**Issue by sanjeev40084** [MicrosoftDocs/powerapps-docs#2608]
[Enter feedback here]
The site is missing documentation for solution commands:
The missing command documentation are: version, publish, upgrade, add-license, check.

![image](https://user-images.githubusercontent.com/3292092/128059924-7fa78dcf-7201-4224-8cdf-969acae28fcc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0e3024-713b-e281-1417-21106fda3045
* Version Independent ID: 177d4ac9-7856-cbea-dc61-a7d11a909273
* Content: [Microsoft Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli)
* Content Source: [powerapps-docs/developer/data-platform/powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/powerapps-cli.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by phecke** [comment]
@sanjeev40084 I have added a tip to the documentation that states to use the 'pac' command  or 'pac <subcommand>' to get the complete list. We do not know when CLI commands are added or updated so we only publish a common or subset of commands detailed in the documentation.
