### ISSUE TITLE
Missing Column Types

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#2609]
The "Discover column names and data types" table in this article mapping Dataverse attribute types to .Net types is very useful!

However it seems to be a little incomplete, missing:
* [File columns](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/file-attributes)
* "EntityName", which seems to just be a string (for example [DocumentTemplate.AssociatedEntityTypeCode](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/entities/documenttemplate?view=op-9-1#BKMK_AssociatedEntityTypeCode)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa1a13f-1c93-4691-0e18-10dd64cf1601
* Version Independent ID: bcdde162-15da-371b-dfcc-70f366ec7f82
* Content: [Entity class operations using the Organization service (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/entity-operations)
* Content Source: [powerapps-docs/developer/data-platform/org-service/entity-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/entity-operations.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@fowl2  You can find a list of non-.NET and Dataverse specific attribute types here under **Derived**:
https://docs.microsoft.com/dotnet/api/microsoft.xrm.sdk.metadata.attributemetadata

The current list of supported entity attributes is:
Microsoft.Xrm.Sdk.Metadata.BigIntAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.BooleanAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.DateTimeAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.DecimalAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.DoubleAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.EnumAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.FileAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.ImageAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.IntegerAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.LookupAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.ManagedPropertyAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.MemoAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.MoneyAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.StringAttributeMetadata
Microsoft.Xrm.Sdk.Metadata.UniqueIdentifierAttributeMetadata 

This list is kept up to date. I can add a link to this in the topic.

**Comment by fowl2** [comment]
@phecke Thanks for your response, but those are attribute **meta**data types, I'm looking for attribute **data** types (without the meta).

ie. what should I pass as `T` to [Entity.GetAttributeValue&lt;T&gt;(String)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.entity.getattributevalue) for an attribute of a certain type.

 Unless I'm missing something the documentation pages for the metadata doesn't actually say what the data types are, but thankfully this page does - in the table under "Discover column names and data types":

> Type | Description
> -- | --
> EntityReference | A Lookup attribute. A link to another entity record.
> BooleanManagedProperty | Used only for entities that can be solution components, such as the WebResource table/entity reference. More information: Use managed properties
> Money | A Currency attribute. 
>  ... | ...

But it is incomplete.

**Comment by JimDaly** [comment]
I agree with @fowl2 
I believe that File columns would also return a byte[], but I haven't tested it.
I think this list has value and should be kept up-to-date.
You can leave this open and assigned to me. Not sure when I'll be able to get to it.

**Comment by JimDaly** [comment]
I updated the topic to mention EntityName fields and added a note about how File columns require a special set of messages to upload or download the file.

Don't think any new file types have been added recently.
