### ISSUE TITLE
passing multiple recordids

### ISSUE THREAD

**Issue by malkhawaja** [MicrosoftDocs/powerapps-docs#2610]
[Enter feedback here]
Hi,
Is it possible to pass multiple recordids selected from a grid to the custom page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d5076fa-40a8-fbef-e5a9-1ba9db2ad4e6
* Version Independent ID: f7fb3acd-e8f3-27e8-456e-5a5c79d38997
* Content: [Navigating to and from a custom page in your model-driven app using client API (preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/navigate-to-custom-page-examples)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/navigate-to-custom-page-examples.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/navigate-to-custom-page-examples.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @aorth
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@malkhwaja Thanks for reaching to us. There is no supported way to pass multiple record IDs. We have this feature in backlog and will update the docs when the feature is ready. Closing the issue. If you need further help, please reopen or create a new issue.

**Comment by DavidPaf** [comment]
Easy, just use .map to get all the ID in the object and pass it to the recordId field.

function run(selectedItems) {
      let itemIds = selectedItems.map(({ Id }) => Id)   // new code here
      let selectedItem = selectedItems[0];
      if (selectedItem) {
          let pageInput = {
              pageType: "custom",
              name: "<logical page name>",
              entityName: selectedItem.TypeName,
              recordId: itemIds,  // new code here
          };
          let navigationOptions = {
              target: 2,
              position: 1,
              width: {
                  value: 50,
                  unit: "%"
              },
              title: "Compare"
          };
          Xrm.Navigation.navigateTo(pageInput, navigationOptions)
              .then(
                  function () {
                      // Handle success
                  }
              ).catch(
                  function (error) {
                      // Handle error
                  }
              );
      }
  }
