### ISSUE TITLE
Default template doesn't have option for inserting image in issue reporting screen 2522648

### ISSUE THREAD

**Issue by marcoxcosta** [MicrosoftDocs/powerapps-docs#2617]
**Default template doesn't have option for inserting image in issue reporting screen**

[Enter feedback here]

Default template doesn't have option for inserting image in issue reporting screen
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a528ba87-a92e-427d-1a93-defef5eb2070
* Version Independent ID: b43c4961-45bb-12e2-5eef-85fca7c70244
* Content: [Use Issue reporting app from teams store - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/issue-reporting)
* Content Source: [powerapps-docs/teams/issue-reporting.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/issue-reporting.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been updated and will reflect the changes soon.
