### ISSUE TITLE
[LOC]Back-Translation "VS コード"→"VS Code"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerapps-docs#2618]
ja-jp:"https://docs.microsoft.com/ja-jp/powerapps/maker/portals/vs-code-extension"
![vs-code-extension_j](https://user-images.githubusercontent.com/40815708/128450414-fd003dd1-ce9c-4f36-875d-66bd817e4d26.png)

en-us:"https://docs.microsoft.com/en-us/powerapps/maker/portals/vs-code-extension"
![vs-code-extension_e](https://user-images.githubusercontent.com/40815708/128450424-354e727d-92f0-427d-bd96-b9eac08fd514.png)

#PingMSFTDocs

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 086e066b-b038-5d2d-a20e-788302c2b2ad
* Version Independent ID: 43af4068-2c32-6575-61cb-ab52d2bda192
* Content: [Visual Studio Code 拡張機能を使用する (プレビュー) - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/portals/vs-code-extension#feedback)
* Content Source: [powerapps-docs/maker/portals/vs-code-extension.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/vs-code-extension.md)
* Service: **powerapps**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by jowilco** [comment]
@hyoshioka0128 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@hyoshioka0128 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
