### ISSUE TITLE
Text in some images is unreadable in dark theme

### ISSUE THREAD

**Issue by PurePandemonium** [MicrosoftDocs/powerapps-docs#262]
There's black text with a transparent background in the images in the "Translate Excel into PowerApps" section as well as the "Know when to use variables" section. When using the dark theme, this text is unreadable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb9294a0-cdd8-91d5-0102-c0412a21f540
* Version Independent ID: 77841b4e-08a9-1177-e18c-b428ef930c1c
* Content: [Understand variables in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-variables)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-variables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-variables.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @PurePandemonium!
