### ISSUE TITLE
onload jquery fails to 

### ISSUE THREAD

**Issue by AdamLanc** [MicrosoftDocs/powerapps-docs#2620]
The sample JS code in this page fails to run when the page loads.  This appears to be a race condition - the PBI component loaded by the liquid tag is not fully loaded when the window onload event fires. But if I add a button to the page and call the same code on the click event it always works...

example:
> _$(window).on('load', function (){
>     var embedContainer = $(".powerbi")[0];
>     var report = powerbi.get(embedContainer);_  

fails on powerbi.get() line with the following error message:

> "Error: You attempted to get an instance of powerbi component associated with element: div class="powerbi portal-pbi-embedded" embedconfig="eyJV....IjoiIn0=" id="powerbi51" title="Power BI report"> /div but there was no associated instance".

Is there any other event that can be used to check if the embedded report is ready to be loaded?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc8038da-7c65-d654-ee94-52522513148e
* Version Independent ID: ca92ed24-8197-1e9b-3898-80621e36a336
* Content: [Add a Power BI report or dashboard to a webpage in a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/add-powerbi-report)
* Content Source: [powerapps-docs/maker/portals/admin/add-powerbi-report.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/add-powerbi-report.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This works with the updated snippet in documentation every time.

**Comment by AdamLanc** [comment]
thanks for the update, can you confirm that the snippet was tested in Power Apps portals using liquid tags to embed?  The code  works in a webpage but does not work for me when embedded into a portal page e.g. _{% powerbi authentication_type:"powerbiembedded" path:"https://app.powerbi.com/groups/00000000-0000-0000-0000-000000000000/reports/00000000-0000-0000-0000-000000000001/ReportSection01" %}_
