### ISSUE TITLE
Navigate to your Dataverse environment

### ISSUE THREAD

**Issue by LindaLawton** [MicrosoftDocs/powerapps-docs#2621]
>Navigate to your Dataverse environment (https://[org].crm.dynamics.com).

As someone who has never done this before and just logged into Azure.  This statement is completely unclear.   More info would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c37834-5349-b2ea-2c40-d6a7b519288f
* Version Independent ID: 610b2eb4-66ac-a221-14d8-b06a3fbc90b0
* Content: [Use single-tenant server-to-server authentication (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-single-tenant-server-server-authentication)
* Content Source: [powerapps-docs/developer/data-platform/use-single-tenant-server-server-authentication.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-single-tenant-server-server-authentication.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@LindaLawton Your environment has a name, say it is 'contoso'. You would enter https://contoso.crm.dynamics.com.

A Power Apps _environment_ is the same thing as a Dataverse _organization_. Hence the use of [org] in the URL example.

**Comment by phecke** [comment]
@LindaLawton I did make slight wording change to make the statement more understandable.

1. Navigate to your Dataverse environment (https://*[env-name]*.crm.dynamics.com).
