### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by polks71** [MicrosoftDocs/powerapps-docs#2622]
Link to "https://docs.microsoft.com/en-us/powerapps/developer/data-platform/build-tools-overview" is a 404.
In this sentence "Supported by SolutionPackager and **_DevOp_**s tools enable continuous integration and continuous delivery (CI/CD)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba670cf8-5810-79c4-7a2a-101099ffe1d7
* Version Independent ID: 69b7e1fb-9f56-8c07-b1d5-8480fe6d8e1a
* Content: [Use environment variables in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/environmentvariables#feedback)
* Content Source: [powerapps-docs/maker/data-platform/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/EnvironmentVariables.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by phecke** [comment]
@polks71 Thanks for catching that. The updated topic will be published in a few hours.
