### ISSUE TITLE
Unsupported Scenarios section require clarification

### ISSUE THREAD

**Issue by zhaparoff** [MicrosoftDocs/powerapps-docs#2623]
Hello,

Is it possible to provide an example of mobile player events that are not captured when using App Insights integration in Canvas Apps? 
Or no app level events are captured at all in this case and only custom traces are?
Could you please clarify?

This is a first bullet in the last paragraph https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/application-insights#unsupported-scenarios

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93af67a-9f3c-97fd-2899-2045c9f7e349
* Version Independent ID: 1cb12077-eec7-45cd-fe7e-fb10fa5c1936
* Content: [Analyze telemetry of a canvas app using Application Insights - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/application-insights)
* Content Source: [powerapps-docs/maker/canvas-apps/application-insights.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/application-insights.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @hasharaf
* Microsoft Alias: **hasharaf**

**Comment by tapanm-MSFT** [comment]
In both offline and mobile scenarios, with the current design, it's not possible to capture emitted events. Hence, these scenarios are not supported. And this applies to all events in offline and mobile scenarios.

For additional help with issues, reach out using [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with investigation. To submit feature ideas, change requests or vote for them, use [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
