### ISSUE TITLE
Unsupported scenarios - need more information

### ISSUE THREAD

**Issue by pavelzmitrovich** [MicrosoftDocs/powerapps-docs#2624]
hi , 
can you provide the list of not captured apps/players events ? 

The following description is not very clear: 

Unsupported scenarios
App Insights doesn't support the following scenarios.

- Offline and **mobile apps/player events (both Android and iOS) are not captured.** - need more information. 

Thanks.

**Comment by Nkrb** [comment]
@pavelzmitrovich  Thanks for contacting us. Can you point us to the doc page you're referring. It helps us assign the issue to the correct writer.

**Comment by pavelzmitrovich** [comment]
@Nkrb this page:  https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/application-insights

**Comment by pavelzmitrovich** [comment]
@tapanm-MSFT  @Nkrb, can you please share the expected date when the documentation probably will be updated. 
Our customer wants to make a decision about using or NOT using Application Insights for logging. 
Or if it's possible to share not covered use cases here ? 
thanks for understanding. 
Pavel

**Comment by tapanm-MSFT** [comment]
@pavelzmitrovich In both offline and mobile scenarios, with the current design, it's not possible to capture emitted events. Hence, these scenarios are not supported. And this applies to all events in offline and mobile scenarios.

For additional help with issues, reach out using [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with investigation. To submit feature ideas, change requests or vote for them, use [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
