### ISSUE TITLE
Model Driven App custom icon is removed when app is customized, saved, and published

### ISSUE THREAD

**Issue by james-reinhardt** [MicrosoftDocs/powerapps-docs#2625]
Model driven app icons for custom and Microsoft managed apps frequently are reset to 'Default App Icon'. Appears to happen when saving and publishing app.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42fde9f9-3f4e-7b9d-1ab5-bddb0c6ca7e7
* Version Independent ID: 97039279-b107-bbbb-0af9-4815e73caf82
* Content: [Manage model-driven app properties in the Power Apps app designer - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/manage-app-properties)
* Content Source: [powerapps-docs/maker/model-driven-apps/manage-app-properties.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/manage-app-properties.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@james-reinhardt - can you provide the steps to reproduce the issue you're seeing? And to be clear, the app icon returning to the default is with model-driven apps not canvas apps, right?

**Comment by james-reinhardt** [comment]
Matt-
Thanks for your response
I accessed the App Designer from the ellipsis on the app, from SETTINGS>>Apps.
https://ENVIRONMENT.crm.dynamics.com/main.aspx?settingsonly=true
![image](https://user-images.githubusercontent.com/44588496/130273250-757acaea-4365-433e-86ca-89c6a2bad0ac.png)

From within the App designer, I added a single subarea to the sitemap. Saved and Published. Closed the sitemap designer.
From the App designer, I saved the app, and published it. 

Returning to the App page, the icon is gone.
![image](https://user-images.githubusercontent.com/44588496/130273477-0a23612d-1e7b-4fca-b9ea-a7a2007e027d.png)

The app properties from within the app designer now show the following:
![image](https://user-images.githubusercontent.com/44588496/130273603-73d9493b-2fdc-4df6-9b27-b162d2382bc1.png)

Let me know if there is anything else I can provide.

**Comment by Mattp123** [comment]
@james-reinhardt - I can't reproduce your issue. Have you tried using a different image? For example, I used Error.png, which was already in the list of image resources. Others to try that I know work are any of the Power Apps sample model-driven apps, such as Donation, Fundraiser, etc. If those work for your app than it's probably an issue with the image that you're using. Below is an app "My test" that's using the Error.png image file for the app icon. Setting it in the app properties "sticks" as expected (as well as the other apps you see in the list that are also using images other than the default). 
If you can reproduce it with other images then I recommend contacting Support here: https://powerapps.microsoft.com/support/ 
. 
![image](https://user-images.githubusercontent.com/21203819/132035581-6e21c6da-290e-441b-9116-8d6c18facf91.png)
