### ISSUE TITLE
Power Apps Experimental UI change - doc is old

### ISSUE THREAD

**Issue by bradygaster** [MicrosoftDocs/powerapps-docs#2626]
This doc is out of sync with the published experience. Customers who are trying to enable PCF might have a difficult time finding the right spot as the UI is quite different. 

Screen shot of new UI is below. 

![image](https://user-images.githubusercontent.com/41929050/128767348-52d0d079-e633-49c9-95a0-d0dbba66353d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8124234-fccb-85af-9ee8-13729326c727
* Version Independent ID: d53c2fc1-dd63-eee4-26a7-22715f27b943
* Content: [Code components for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/component-framework-for-canvas-apps)
* Content Source: [powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@bradygaster  Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.

**Comment by bradygaster** [comment]
thank you SO much! this is super helpful to new folks discovering the experience.
