### ISSUE TITLE
Great sample!

### ISSUE THREAD

**Issue by j-klotz** [MicrosoftDocs/powerapps-docs#2627]
Great sample, just two comments:
1. in paragraph 4.6.1 for an improved UX, the value to set should be ThisItem.Title instead of ThisItem.Feed.Description
2. make sure you move Screen2 above Screen1 in the Tree view to make it the startup screen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe271d2b-684a-a863-3f41-1dbe9294a106
* Version Independent ID: 38ad78ae-9ad8-e68f-c6a1-fcafcd88c015
* Content: [Build an app in Teams using Power Apps and Dataverse for Teams to retrieve Power Platform videos for readiness - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/tutorial-buildapp-retrieve-videos#step-4-edit-the-app-to-add-the-video-library-interface)
* Content Source: [powerapps-docs/teams/tutorial-buildapp-retrieve-videos.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/tutorial-buildapp-retrieve-videos.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback and suggestions. Appreciate them. While the how-to topic shows getting started, further improvements and changes can be done based on business requirements, and preferences.
