### ISSUE TITLE
Duplicated Information

### ISSUE THREAD

**Issue by IsolatedStorage** [MicrosoftDocs/powerapps-docs#2628]
Under the blogpost Object the table lists one of the attributes twice. Is there another attribute that should exist for the blogpost?

![image](https://user-images.githubusercontent.com/19565852/128842767-5821cfe4-ca9c-40ad-a618-9a7119f48824.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340faef4-cbf8-d938-8a10-230149b8a591
* Version Independent ID: 88a56df4-b670-4954-832b-955ae94a6501
* Content: [Available Liquid objects - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/liquid-objects)
* Content Source: [powerapps-docs/maker/portals/liquid/liquid-objects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/liquid/liquid-objects.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed, updates will be visible soon.
