### ISSUE TITLE
Could you update "Update date" of document?

### ISSUE THREAD

**Issue by hrfmjp** [MicrosoftDocs/powerapps-docs#263]
I think that reviewer didn't update "ms.date".
Could you update that property every commit it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f7e4f2-fe68-0e4b-9cfd-a303abaa0fd6
* Version Independent ID: f0708033-e29d-5321-0da0-e2c1c2130008
* Content: [Delegable data sources in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-list?fbclid=IwAR0JDZOR8iNHUi0SkN4pLq7EzbAZIbP6iudjP_69NOgQJWfH5_FCV2VHXGg)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by AFTOwen** [comment]
@hrfmjp We have just removed that topic and moved the information that's still relevant to the [delegation overview](https://docs.microsoft.com/powerapps/maker/canvas-apps/delegation-overview#delegable-data-sources) topic. Thanks!

**Comment by hrfmjp** [comment]
@AFTOwen  What reason you delete article?
I want you to edit "UPDATED DATE of article".
![image](https://user-images.githubusercontent.com/28778119/53216891-62620d00-3699-11e9-8fa8-4fb4f579cbce.png)

In the technical document, "updated date" is very important.

**Comment by lancedMicrosoft** [comment]
The article was deleted because the information has been moved to a different article.

**Comment by hrfmjp** [comment]
OK, I could see that,
The topics about Delegation moved to [overview](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview#delegable-data-sources).
And details moved to each connector's article (ex. [SharePoint](https://docs.microsoft.com/ja-jp/connectors/sharepointonline/#powerapps-delegable-functions-and-operations-for-sharepoint)).

**Comment by lancedMicrosoft** [comment]
Yes, and the delegation details are much more complete for CDS, SharePoint, and SQL Server in the specific connector doc locations.
