### ISSUE TITLE
Clarification Needed for Dev Plan if Power Automate Desktop Flows Included

### ISSUE THREAD

**Issue by MontanaIrish** [MicrosoftDocs/powerapps-docs#2632]
[Enter feedback here]

Would be great to include details on Power Automate Desktop Flows and if supported in Power Apps Developer Plan.  This is not clear and suspect that Power Automate with Attended RPA license still required to leverage Power Automate Desktop to create and test these desktop flows.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa958930-fb79-62a4-3f46-c1adf9f8349a
* Version Independent ID: e2f2d173-ca57-6f83-a2d6-ab381846e5b6
* Content: [Power Apps Developer Plan - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/developer-plan)
* Content Source: [powerapps-docs/maker/developer-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/developer-plan.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @evanmlew
* Microsoft Alias: **evlew**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated and will reflect the changes soon.
