### ISSUE TITLE
There is a translation error in the Japanese version of this Microsoft docs.

### ISSUE THREAD

**Issue by momotanaka3** [MicrosoftDocs/powerapps-docs#2634]
There is a translation error in the Japanese version of the Microsoft docs.

https://docs.microsoft.com/en-us/powerapps/maker/portals/manage-sharepoint-documents#step-5-create-appropriate-table-permission-and-assign-it-to-the-appropriate-web-role

https://docs.microsoft.com/ja-jp/powerapps/maker/portals/manage-sharepoint-documents#step-5-create-appropriate-table-permission-and-assign-it-to-the-appropriate-web-role

[Append To] should be translated as [追加先], not [追加].
Due to this translation, the end user was not able to set the proper permissions, which took some time to resolve.
Please correct the translation.

![image](https://user-images.githubusercontent.com/88817227/129144206-a8c418a6-62a6-48e8-95a6-8f554ca41cfc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd70bb46-8651-365b-7a25-215b921f55b6
* Version Independent ID: f628a69a-04c8-901a-832f-b867aff68603
* Content: [Manage SharePoint documents - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/manage-sharepoint-documents#step-5-create-appropriate-table-permission-and-assign-it-to-the-appropriate-web-role)
* Content Source: [powerapps-docs/maker/portals/manage-sharepoint-documents.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/manage-sharepoint-documents.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by jowilco** [comment]
@momotanaka3 
Thank you for your feedback. We are looking into this issue.

**Comment by jowilco** [comment]
@momotanaka3 
Thanks for your feedback. We have updated the translations, and the updated translations are live. Closing this issue.
