### ISSUE TITLE
Adding Component Libraries to Solutions

### ISSUE THREAD

**Issue by DougFMS** [MicrosoftDocs/powerapps-docs#2635]
[Enter feedback here]
The article indicates you can't add a component library to a solution.
"You can't add existing component libraries to a solution. However, you can create new component libraries for solutions using add component library flow."

I believe this feature is now available in Preview.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0224ad-fdbb-c741-98a7-3ec0764b10cf
* Version Independent ID: dfbaaa9e-b902-70de-49d8-9d6c5328b6d2
* Content: [Component library - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/component-library)
* Content Source: [powerapps-docs/maker/canvas-apps/component-library.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/component-library.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated and the changes will be visible soon.
