### ISSUE TITLE
Parameters may be persisted across Navigate() calls to a given screen.

### ISSUE THREAD

**Issue by lonesome-cloner** [MicrosoftDocs/powerapps-docs#2638]
# Strange behaviour  using Navigate with Parameters

I have two screens in a Canvas App; no data connections.

Screen 1 contains 3 buttons to navigate to Screen 2.

- Button1's *OnSelect* formula is Navigate(Screen2, None, {ParamString: "FRED"})
- Button2's *OnSelect*  formula is  Navigate(Screen2,  None);
- Button3's *OnSelect*  formula is Navigate(Screen2, None, {ParamString: Blank() } );

Screen 2 contains a Label that takes ParamString as its default Text.

## On Screen 1
- If I click Button 1, Screen 2 displays "FRED" in its Label.
- If I then click Button 2, Screen 2 displays "FRED" in its Label.
- If I then click Button 3, Screen 2's  Label displays nothing.

I can then press Button 3 and Button 2, and nothing will be displayed on Screen2's Label until I next press Button1.

Is this expected behaviour?
I can supply an Export Package on request

--
_Puzzled of Middlesex_
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9b5e7f-c7a3-4530-11dc-d3655e0c77d4
* Version Independent ID: 10b605d6-f30a-aef9-c69a-ebc267089fd2
* Content: [Back and Navigate functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-navigate)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-navigate.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-navigate.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The behavior is as expected, as documented [here](https://docs.microsoft.com/powerapps/maker/canvas-apps/working-with-variables#types-of-variables).  However, for a deeper investigation with additional scenarios and behavior investigation, please create a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) and support teams can help with investigating the behavior in detail.
