### ISSUE TITLE
Broken example of getSecurityRolePrivilegesInfo()

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#2639]
The example in getSecurityRolePrivilegesInfo() is incorrect.

In the example, these lines:

    console.log("Privilege Id: " + privilege[guid].id);
    console.log("Privilege Name: " + privilege[guid].privilegeName);
    console.log("Privilege Business Unit Id: " + privilege[guid].businessUnitId);
    console.log("Privilege depth: " + privilege[guid].depth);

should be:

    console.log("Privilege Id: " + rolePrivileges[guid].id);
    console.log("Privilege Name: " + rolePrivileges[guid].privilegeName);
    console.log("Privilege Business Unit Id: " + rolePrivileges[guid].businessUnitId);
    console.log("Privilege depth: " + rolePrivileges[guid].depth);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999537e5-d7fd-6e16-207a-b7c7c31fdc9e
* Version Independent ID: 48ac9b62-a8b5-3bab-11b5-c0bbc5fde88c
* Content: [getGlobalContext.userSettings (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings#getsecurityroleprivilegesinfo)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for reaching to us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
