### ISSUE TITLE
Script is incorrect [Cognitive Services]

### ISSUE THREAD

**Issue by ALopes21** [MicrosoftDocs/powerapps-docs#264]
I receive the following runtime error in PowerApps when attempting to call LanguageDetect:
"TextAnalytics.DetectLanguage failed: {"code":"Bad Request", "message":"Invalid request","innerError":{"code":"InvalidRequestQueryString","message":"Request contains a query string. Request content should be placed in the request body, not in the url as a query string."}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58cccc6-9234-ec33-b4b0-3303ebe282ef
* Version Independent ID: a556f95f-240d-206b-6dd0-c2fc47b1bf11
* Content: [Use Cognitive Services in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/cognitive-services-api#sign-up-for-the-text-analytics-api)
* Content Source: [powerapps-docs/maker/canvas-apps/cognitive-services-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/cognitive-services-api.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by ChrRing** [comment]
Also stumbled across this issue. The problem seems to be related to the language detection call. KeyPhrases and sentiment work fine.

**Comment by dipteshbose** [comment]
@Microsoft - Is anybody working on this request. Also, please add codes to clear the collection and fields. Everytime I run the app the labels are prepoluated with information from the previous session.

**Comment by radosopon** [comment]
Use DetectLanguageV2 call:
If( chkLanguage.Value = true,
    ClearCollect( languageCollect, 
        TextAnalytics.DetectLanguageV2({text:tiTextToAnalyze.Text}).detectedLanguages.name
    )
);

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The document is updated. 

Regarding the ask about clearing the collection, please be sure to use [ClearCollect](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-clear-collect-clearcollect#clearcollect) as documented. If problem persists, it may need environmental issue investigation. In such circumstances, please reach out via a [support ticket](https://powerapps.microsoft.com/en-us/support/pro/).
