### ISSUE TITLE
Explain how to work with Date Picker (input) field

### ISSUE THREAD

**Issue by keunes** [MicrosoftDocs/powerapps-docs#2643]
I'm trying to calculate a date based on two user inputs:
* Start date: Date picker field
* Number of weeks: slider (values between 1 & 5)

I would like to understand what the formula for another View only date-field should be like:
![image](https://user-images.githubusercontent.com/11229646/129699389-937bae72-dae4-46c5-9927-e1470bb01e6e.png)

**The "Show text, dates, and times in canvas apps" page, however, only explains how to use `Text` fields. I want to know how to get it working with Date Picker fields**

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2548fd17-5e1c-99d3-b7f7-a0b48c56c2bf
* Version Independent ID: f645f526-3e2c-ae5f-965d-a64c6a9094df
* Content: [Show text, dates, and times in canvas apps - Power Apps](https://docs.microsoft.com/en-au/powerapps/maker/canvas-apps/show-text-dates-times)
* Content Source: [powerapps-docs/maker/canvas-apps/show-text-dates-times.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/show-text-dates-times.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by keunes** [comment]
Actually just found the thing that made my formula work: had to add `.SelectedDate`
I found it on [this page](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-date-picker#basic-date-picker). Would still be helpful for others I assume to have an example with Date Picker.

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out, will update the documentation to include relevant links.
