### ISSUE TITLE
There is no JSON type web resources to create.

### ISSUE THREAD

**Issue by iamchangming** [MicrosoftDocs/powerapps-docs#2645]
There is no JSON type web resources to create

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ecdffd-f6c2-4fc2-2d74-94d16c18108c
* Version Independent ID: cb939451-df9d-23b2-5e98-e2519c3b90db
* Content: [Use the rich text editor control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/rich-text-editor-control#rich-text-editor-control-configuration-options)
* Content Source: [powerapps-docs/maker/model-driven-apps/rich-text-editor-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/rich-text-editor-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **craigm**

**Comment by Mattp123** [comment]
@iamchangming - Actually, the article doesn't state create a web resource of type **JSON** it indicates a type of **JavaScript**. However, there isn't a type _JavaScript_. The type is **Script(JScript)** in UI to use to create the web resource. Updated the article to use the correct type.

Closing issue.
