### ISSUE TITLE
Unclear Documentation: Is Test Studio available in GCC Tenants?

### ISSUE THREAD

**Issue by zknitter** [MicrosoftDocs/powerapps-docs#2647]
The documentation related to the canvas app [Test Studio](https://github.com/MicrosoftDocs/powerapps-docs/blob/38670ef7b0420724823cf083c381f0129d58db51/powerapps-docs/maker/canvas-apps/test-studio.md) does not clarify if this feature is available in GCC tenants. Can you please update the documentation to specify if this feature is available to GCC users?
Thank you very much.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and the question. Currently Test Studio isn't available in GCC tenants.
