### ISSUE TITLE
Copy and pasting code.

### ISSUE THREAD

**Issue by nhuggins1** [MicrosoftDocs/powerapps-docs#2648]
[I am having trouble with step 8. 
"Replace the following code with the removed formula portion earlier."
 I am unclear on what to paste where. Can you please upload a picture detailing step 8?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc8149b-7f53-cf3f-52ab-755fb7c6aceb
* Version Independent ID: e3bb4c6d-4439-56b6-708b-22d77a7b6450
* Content: [Update inspection notification to use an adaptive card - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/inspection-adaptive-card#feedback)
* Content Source: [powerapps-docs/teams/inspection-adaptive-card.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/inspection-adaptive-card.md)
* Service: **powerapps**
* GitHub Login: @sbahl10
* Microsoft Alias: **namarwah**

**Comment by Greybeard1975** [comment]
The instructions are a bit tricky to parse.  The code shown in step 7 needs to be replaced with the code in step 8.  (Basically replacing the entire contents of the IsError() function).  The reference to pasting is from step 4, when you copied the OnSelect code attached to the Submit button ('btnContinueSubmitInspection') to a text editor so you didn't lose it when attaching the flow.  Make the edits in your editor, then copy it back to OnSelect.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated and the changes will be reflected soon.
