### ISSUE TITLE
Visualt Studio States: ClientCredentials are Obsolete use ConfidentialClientApplicationBuilder 

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/powerapps-docs#2655]
The example with ClientCredentials is obsolete. VS states to use ConfidentialClientApplicationBuilder 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f57df6-59af-6e22-44d2-bc9bb1ee69c7
* Version Independent ID: fdce23ee-733d-bf3a-25c8-2ca6bfa8c852
* Content: [Use OAuth authentication with Microsoft Dataverse (Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/authenticate-oauth)
* Content Source: [powerapps-docs/developer/data-platform/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/authenticate-oauth.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@devman2k What version of ADAL are you using?

**Comment by Avinch** [comment]
Not OP, but similar issue.

Moved from MS.IdentityModel.Clients.ActiveDirectory > MS.Identity.Client after warnings mentioning that ClientCredentials were obsolete, as mentioned in the issue.  

After some digging, I found [this doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration-confidential-client?tabs=daemon#migrate-daemon-apps) from the AAD team mentioning a migration path that helped, albiet using the certificate option instead of a secret. 

The below works fine for us to acquire a token for use with Dataverse.

```cs
private async Task<AuthenticationResult> AcquireToken()
        {
            var app = ConfidentialClientApplicationBuilder
                .Create(_cdsConfig.ApplicationUser.ClientId.ToString())
                .WithClientSecret(_cdsConfig.ApplicationUser.ClientSecret)
                .WithAuthority($"https://login.microsoftonline.com/{_cdsConfig.TenantId}")
                .Build();

            var request = app.AcquireTokenForClient(new List<string>()
                { $"{_cdsConfig.BaseUrl}/.default" }); // BaseUrl: "https://env.crmx.dynamics.com"
            
            var result = await request.ExecuteAsync();
            
            return result;
        }
```

**Comment by phecke** [comment]
@devman2k  There is a new QuickStart sample that we published recently. It demonstrates use of both ADAL 5 and MSAL for authentication. Take a look.

[https://github.com/microsoft/PowerApps-Samples/tree/master/cds/webapi/C#/QuickStart](https://github.com/microsoft/PowerApps-Samples/tree/master/cds/webapi/C%23/QuickStart)

A lot of our documentation was written for ADAL v2 and 3. We will have to update it as we are able. Hope the QuickStart sample helps.
