### ISSUE TITLE
Tables in Dataverse for Teams versus Dataverse

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#2656]
Do Dataverse for Teams environments have the same tables as Dataverse environments? I see CDS is marked as coming soon, but just did a side by side comparison of my environments and the tables appear to be the same.

![image](https://user-images.githubusercontent.com/8151045/130277754-450e8d2d-27be-4f99-96c2-7700e7bf5dff.png)

Tables appear to be the same. Dataverse is on the left and Dataverse for Teams is on the right.
![image](https://user-images.githubusercontent.com/8151045/130278127-c24fdcdf-1892-4596-9d2e-2ad77b5c2b69.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16e0d50-176d-2c1c-7821-a806efd079e3
* Version Independent ID: d8dc6656-383d-6f1e-8e47-350e4c206d7c
* Content: [Dataverse for Teams vs. Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare)
* Content Source: [powerapps-docs/teams/data-platform-compare.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/data-platform-compare.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@gregdegruy - Dataverse for Teams has a subset of the tables of that in Dataverse. For example, there's no account or contact table. Are you sure you're looking at a Dataverse for Teams environment? From the Power Apps app in Teams, on the Build tab just below the title select ... > Open in Power Apps. Then, in the Power Apps browser window open a solution (or create one), and Add > Table. See the list of tables to select from the environment. It should look similar to this: 
![image](https://user-images.githubusercontent.com/21203819/132038427-db12dfe6-29d4-4ace-b0c1-54c7f0530f4d.png)

Closing issue.
