### ISSUE TITLE
"Open Form Section" to be updated with new video file

### ISSUE THREAD

**Issue by Pronob1989** [MicrosoftDocs/powerapps-docs#2658]
[Enter feedback here] Under section "_**Open the form**_" all of the options are now updated. It is still showing old dropdown values. Ex: Now "**_Integrate_**" option is available not "**_PowerApps_**" option. We should update it accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a8c4146-101d-7ba2-7ae0-d7138b743154
* Version Independent ID: 1f752762-0809-a2fb-4a03-b490547ee7f1
* Content: [Customize a SharePoint list or library form by using Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form?source=docs#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @wimcoor
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. The animations on the topic are slated for future review and updates. Closing this task for now.
