### ISSUE TITLE
Unable to add feedback to PowerPlatform Admin Center Docs

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#266]
The pages for the new PowerPlatform admin center don't have the Provide Documentation feedback button, e.g, its missing from https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps#review-your-audit-data-using-reports-in-office-365-security-and-compliance-center and many other pages. Could you please enable that functionality so that we can provide feeback

**Comment by jimholtz** [comment]
@DeanGross 
Thanks for the feedback. We're working on adding this.
