### ISSUE TITLE
Can Average be delegated or not?

### ISSUE THREAD

**Issue by art-bjss** [MicrosoftDocs/powerapps-docs#2660]
The page lists Average as a function that can be delegated, but also uses it as an example of a function that can't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad97e638-1f17-ffb2-452f-8073a2bffa63
* Version Independent ID: 7ade66f5-aab6-0627-6d3b-914006718930
* Content: [Understand delegation in a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/delegation-overview.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please read this: 
https://docs.microsoft.com/powerapps/maker/canvas-apps/delegation-overview#aggregate-functions
Sum, Average, Min, and Max can be delegated. **Only a limited number of data sources support this delegation at this time; [check the delegation list](https://docs.microsoft.com/powerapps/maker/canvas-apps/delegation-overview#delegable-data-sources) for details.**

**Comment by art-bjss** [comment]
The page still says

> Aggregate functions can also cause confusion. Take Average over a column of that same million-record data source. Average can't yet be delegated, so only the first 500 records are averaged. If you're not careful, a partial answer could be misconstrued as a complete answer by a user of your app.
