### ISSUE TITLE
Power Bi - utilising Dataverse choices

### ISSUE THREAD

**Issue by Grant-R** [MicrosoftDocs/powerapps-docs#2662]
Information in this section is incorrect; 
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector#choices

The name pairing for each choice is not included when importing data into Power Bi, the name column is imported as _null_.

Information on how to access Dataverse choices can be found on another docs page: https://docs.microsoft.com/en-us/powerapps/maker/data-platform/azure-synapse-link-choices-powerbi. This option is insane as you have to set up Azure storage and have azure subscription just to make use of your data for a Power Bi dashboard. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e6e30d-4224-459f-8525-08718d6d77e4
* Version Independent ID: fe075fe5-5d2e-7b96-3608-9ad3138380da
* Content: [Create a Power BI report using the Dataverse connector - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Grant-R - The article you linked to in your issue for accessing Choice columns is for using Power BI to access the Azure Data Lake Storage Gen 2. The referenced article is for accessing Dataverse using the Dataverse connector, which does display Choice data in an integer / display name (string) form. For example, this is a Power BI report accessing the standard industrycode and industrycodename integer/display name combination for the account main form. In this example industrycode is "14" and industrycodename is "Entertainment Retail". 
![image](https://user-images.githubusercontent.com/21203819/132043204-9c83e8d4-29aa-4d35-97e8-b5dae977332c.png)

Closing issue.
