### ISSUE TITLE
a vulnerability SNYK-JS-HTTPAUTH-471683 is introduced in pcf-start

### ISSUE THREAD

**Issue by ayaka-kms** [MicrosoftDocs/powerapps-docs#2663]
Hi,  a vulnerability [SNYK-JS-HTTPAUTH-471683](https://snyk.io/vuln/SNYK-JS-HTTPAUTH-471683) is introduced in pcf-start via:
●  pcf-start@1.8.6 ➔ live-server@1.2.1 ➔ http-auth@3.1.3

However, **_live-server_** is a legacy package, which has not been maintained for about 3 years.
Is it possible to migrate **_live-server_**  to other package to remediate this vulnerability?

I noticed several migration records in other js repo for **_live-server_**:
1. in yandeu/Web-Development-Essentials-Extension-Pack, replace live server by five server via [commit](https://github.com/jamesqquick/Web-Development-Essentials-Extension-Pack/pull/3) 
2. in aframevr/aframe, replace live server by five server via [commit](https://github.com/aframevr/aframe/commit/404df2cdd5ac8613181f20bd2d440b881cfc60e9) 
3. also in microsoft/vscode-brackets-pack, replace live server by five server via [commit](https://github.com/microsoft/vscode-brackets-pack/pull/1) 
4. in stephenengineer/Project_Local_Library_1, Replaced live-server dependency with http-server via [commit](https://github.com/stephenengineer/Project_Local_Library_1/commit/15139e02bd2c1be8cee9046c35b8d51970a91056) 

Are there any efforts planned that would remediate this vulnerability or migrate ***_live-server_**?

Thanks
 ; )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4b9e58-d9d3-c387-fe6a-258ebe78516d
* Version Independent ID: 22d89b45-e427-1ab9-b456-7d7750585b52
* Content: [Create and build a code component in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/create-custom-controls-using-pcf)
* Content Source: [powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
