### ISSUE TITLE
Export to Excel - no options?

### ISSUE THREAD

**Issue by AdamWGrise** [MicrosoftDocs/powerapps-docs#2665]
When trying to export, I don't have any options to select what kind of export to generate (dynamic vs. static) - it just does dynamic by default and goes straight to downloading the .xlsx file in my browser. Is there a setting to change this default or allow the dialog box to appear?

I'm working with a third party vendor who has built our custom dynamics environment, and they say it's a "Microsoft thing" that cannot be changed - some rudimentary searching led me here. Thanks!

Adam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcd3e610-828d-1afe-4777-ca9e8ed80395
* Version Independent ID: b3ff53e0-b33b-d977-cadc-3f81475ff3c6
* Content: [Export data to Excel in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/export-data-excel)
* Content Source: [powerapps-docs/user/export-data-excel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/export-data-excel.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ 

Closing this issue.

Thanks,
Mints
