### ISSUE TITLE
Importing double-byte characters

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#267]
If you are importing data that includes double-byte characters for east asian languages, make sure the file is encoded as UTF-8 BOM. Plain UTF-8 may not be enough. 

Open the CSV file using Visual Studio Code and In the bottom bar, you'll see the label UTF-8. Click it. A popup opens. Click Save with encoding. You can now pick UTF-8 BOM encoding for that file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46209bf7-62b7-f424-f749-f297c8847e35
* Version Independent ID: ffef7489-39b8-60dd-299b-367e3b694843
* Content: [Import data in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/import-data)
* Content Source: [powerapps-docs/user/import-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/import-data.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
@JimDaly I updated the topic and it should go live by end day.
