### ISSUE TITLE
`getIsDirty` behaviour changed between 9.0 and 9.1 -- please document

### ISSUE THREAD

**Issue by skfd** [MicrosoftDocs/powerapps-docs#2671]
`getIsDirty` behaviour changed between 9.0 and 9.1 -- it used to mean "was value ever touched" in 9.1 it means "does attribute contain new value".

Could not find documentation on this breaking change, or details of the behaviour at all.

An example of script -- 9.1 form on the left; 9.0 form on the right:

![image](https://user-images.githubusercontent.com/159640/130959357-78511f27-350c-4d49-97fc-426d1cbba97b.png)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd5b4b30-e6de-8bb0-3da2-f612765eac2b
* Version Independent ID: 8ed5382e-1604-6d6e-f5ea-7591d1a90894
* Content: [getIsDirty (Client API reference) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/getisdirty)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getIsDirty.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getIsDirty.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
