### ISSUE TITLE
Clarity needed on how to sign up for dev plan

### ISSUE THREAD

**Issue by jimbobbennett** [MicrosoftDocs/powerapps-docs#2673]
The documentation on the dev plan needs more clarity on the requirements to sign up. The docs mention that you need a 'work or school email account', and provides a link to the 30 day plan with an FAQ than mentions Office 365 IDs.

So does 'work or school' mean any work or school? Or just a work or school email from a work or school that uses Office 365?

It also seems you can activate this using a M365 developer account which is free, based on [this video](https://www.youtube.com/watch?v=-H4ljf4FuTE), but I don't see this option mentioned in the docs.

The particular scenario that has lead to this request for more clarification is for students wanting to learn PowerApps for use at hackathons. Based off the docs, all students should be able to sign up for the developer plan as they will all have a school email address, but as far as I understand in reality only those students with a school email address that uses Office 365 will be able to sign up. To docs need to be clearer, and show the path for students without an Office 365 account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa958930-fb79-62a4-3f46-c1adf9f8349a
* Version Independent ID: e2f2d173-ca57-6f83-a2d6-ab381846e5b6
* Content: [Sign up for Power Apps Developer Plan - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/developer-plan)
* Content Source: [powerapps-docs/maker/developer-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/developer-plan.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @evanmlew
* Microsoft Alias: **evlew**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. Content has been updated, and the changes will be visible soon.
