### ISSUE TITLE
Remove Silverlight

### ISSUE THREAD

**Issue by carltoncolter** [MicrosoftDocs/powerapps-docs#2674]
Can we remove the silverlight portions from this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88835328-13bb-7edf-50fe-7bd5f4c4f39a
* Version Independent ID: 04e24def-7367-fa93-b9e9-9ba105c8bf62
* Content: [Create accessible web resources (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/create-accessible-web-resources#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/create-accessible-web-resources.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/create-accessible-web-resources.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
