### ISSUE TITLE
For the love of god, please include a Quick Find view reference in this doc!

### ISSUE THREAD

**Issue by jsh121988** [MicrosoftDocs/powerapps-docs#2676]
I beg of you... This doc seriously needs a highly important note to Quick Find view, which provides the capability to search on multiple fields in a lookup field. In the first screenshot in this doc, it shows a user searching for 'Ad' which brings up multiple records, some based on additional columns. This only works if the Quick Find view on the table is setup with these in the 'Find By' section. It took me hours to figure this out, and I basically guessed and it worked.

What's stupid is that the Quick Find view is seemingly unrelated to the default Lookup view, but it is 100% related when searching a Lookup view.

Here is a link with screenshots: https://stoneridgesoftware.com/improved-search-functionality-dynamics-365-customer-engagement/

There is ABSOLUTELY no reference to this anywhere that I could find in our docs. Please don't even wait for sprint cycles to add this. It was critical to our business need at a CVP level.

I am an MS FTE, please search for my last name "Homiak" in teams for any additional input. I apologize for how strongly this came across. This issue plagued me for hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c392ce52-689a-f50c-f985-6f8ae7d1a128
* Version Independent ID: c3c7e767-f99c-b5e4-8bb6-1875004726c3
* Content: [Use the lookup column on a row - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/lookup-field?source=docs)
* Content Source: [powerapps-docs/user/lookup-field.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/lookup-field.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@jsh121988 I sent you an email. I think this is what you were looking for: https://docs.microsoft.com/en-us/power-platform/admin/configure-relevance-search-organization#configure-searchable-fields-for-relevance-search.

I'll add a link to this in the lookup topic.

Thanks,
Mints
