### ISSUE TITLE
Extra closing bracket in sample formula given

### ISSUE THREAD

**Issue by nijos** [MicrosoftDocs/powerapps-docs#2678]
[Enter feedback here]
 The formula given on the page has an extra closing bracket.

Launch("https://www.bing.com"));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88a817c-546d-a124-4bd6-0f3dd89b53a1
* Version Independent ID: 1334d387-c087-0ed6-3cbb-558f89256d75
* Content: [Use Power Fx with commands - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/commanding-use-powerfx?source=docs)
* Content Source: [powerapps-docs/maker/model-driven-apps/commanding-use-powerfx.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/commanding-use-powerfx.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@nijos - Thank you for your feedback. The additional parenthesis has been removed and will be published in about an hour.

Closing issue.
