### ISSUE TITLE
PowerBIInteractions Property Is Missing

### ISSUE THREAD

**Issue by matthewdevaney** [MicrosoftDocs/powerapps-docs#2679]
The PowerBIInteractions property is not found in the documentation.  PowerBIInteractions requires a true/false value.  When true a user can click on a tile visual to filter it.  When false, a user cannot select anything inside the tile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 551096c3-6bef-bd2b-9254-4fceac6315da
* Version Independent ID: 6aaee99a-f244-17ca-cb48-408436a2ad92
* Content: [Power BI tile control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out with your feedback. Content has been updated, and will reflect the changes soon.
