### ISSUE TITLE
Red image labels are barely readable with dark theme

### ISSUE THREAD

**Issue by birop** [MicrosoftDocs/powerapps-docs#268]
Using the dark theme for the page, the red text on the transparent background next to the screenshots is barely readable on black background.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420ca3f-7920-2e8d-b74b-b4abd6c6e4a7
* Version Independent ID: 2746edf3-cb05-3e25-e544-92b302b251d0
* Content: [Understand canvas-app forms - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-forms)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-forms.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Fixed, Thanks, @birop!
