### ISSUE TITLE
Falsche Übersetzung der "true" und "false" Parameter

### ISSUE THREAD

**Issue by dannybergs** [MicrosoftDocs/powerapps-docs#2682]
Für den Header Parameter "MSCRM.SuppressDuplicateDetection" wird der selbe Text für "true" und "false" verwendet.

`
    true – Den Datensatz **nicht** erstellen oder aktualisieren, wenn ein Duplikat gefunden wird.
`
`
    false – Den Datensatz **nicht** erstellen oder aktualisieren, wenn ein Duplikat gefunden wird.
`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a48217ac-43b9-cefb-70bf-163c82175080
* Version Independent ID: 70af49c3-2b41-bbde-235c-d348b2f47a2d
* Content: [Erkennen von doppelten Daten mit der Web-API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/de-de/powerapps/developer/data-platform/webapi/manage-duplicate-detection-create-update)
* Content Source: [powerapps-docs/developer/data-platform/webapi/manage-duplicate-detection-create-update.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/manage-duplicate-detection-create-update.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by jowilco** [comment]
@dannybergs
Vielen Dank für Ihr Feedback. Wir ermitteln die Ursache für dieses Problem.

**Comment by jowilco** [comment]
@dannybergs 
Vielen Dank für Ihr Feedback. Wir haben die Übersetzungen aktualisiert, und die aktualisierten Übersetzungen sind live. Dieses Problem wird geschlossen.
