### ISSUE TITLE
Can Guest have developping activities 

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/powerapps-docs#2683]
[Enter feedback here]
Hello, 
1 question remains unanswered : as a MS Partner, my customer guests me in its tenant. Can I access make.powerapps.com and admin.powerplatform.com to work on canvas apps, model driven apps?

Thank you

Pierre-Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b79de9-91fd-adc9-2515-d2bb84cfd2b2
* Version Independent ID: 62c9fd03-2d88-475f-c857-75647f263a81
* Content: [Share a canvas app with guest users - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app-guests?source=docs)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app-guests.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/share-app-guests.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @alaug
* Microsoft Alias: **alaug**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your question. Invited guests can't browse to those URLs on guest tenants. More information: [Invite users with Azure Active Directory B2B collaboration - Incompatibilities](https://docs.microsoft.com/power-platform/admin/invite-users-azure-active-directory-b2b-collaboration#incompatibilities)

If you have a feature change/request or an ask, please submit or vote for ideas using the [Power Apps Ideas - community forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
