### ISSUE TITLE
Drop Down Control Properties are incorrect.

### ISSUE THREAD

**Issue by zczaragoza** [MicrosoftDocs/powerapps-docs#2685]
The correct syntax to get the value from Drop Down is "ControlName.SelectedText.Value". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea793a3-0ef8-50a5-351e-15ebcdb77a9f
* Version Independent ID: 17282b67-79f0-fb34-b1e6-d45f905f81e7
* Content: [Drop down control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-drop-down)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-drop-down.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-drop-down.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This is the relevant section with the same syntax as in this issue feedback:

*SelectedText (Deprecated) – A string value that represents the selected item. Use Dropdown1.SelectedText.Value instead, replacing "Dropdown1" with drop-down control name in the app.*

If you meant something else, please elaborate.
