### ISSUE TITLE
More bad documentation

### ISSUE THREAD

**Issue by ErickTreetops** [MicrosoftDocs/powerapps-docs#2689]
[Enter feedback here]
Why would you describe something new to an audience using a single sentence of 45 words and 15 nouns ?
That's what you have done here.  It's obvious that this was written by someone who wanted to cram as much explanation into a single sentence with no regard to it's readability.  

When explaining a new concept you introduce one fact at a time and then build on it.  
Microsoft, repeatedly does this.  Rather than explaining concepts it sounds like a sales brochure of marketing words.

Carefully explain what it is , then explain why I need to use it.

Remember, over decades my organisation has spent hundreds of millions of dollars investing in developers and licences of Visual Studio to "improve productivity".  So why do we need to go back to using a CLI ?  A CLI like Unix programming with  grep, awk etc ?  Those free products that have been around for decades.  Why are we paying for those expensive developer licences ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0e3024-713b-e281-1417-21106fda3045
* Version Independent ID: 177d4ac9-7856-cbea-dc61-a7d11a909273
* Content: [Microsoft Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli)
* Content Source: [powerapps-docs/developer/data-platform/powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/powerapps-cli.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ErickTreetops Thanks for reaching to us. Initially when we documented this, the scope of the project is small, and now since the scope has been increased, we are making changes to the current doc to be more appropriate. Appreciate your feedback.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
