### ISSUE TITLE
This is innacurate...

### ISSUE THREAD

**Issue by VFXpro** [MicrosoftDocs/powerapps-docs#2692]
Page says "Copy and paste of flow actions is currently not supported when creating flows in a solution."  I can copy/paste in all my flows that live inside a solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba673f56-d0c1-6795-c028-5e121fe3cfeb
* Version Independent ID: bb0c60db-d75b-c470-81f9-3414e9b863d5
* Content: [Solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/solutions-overview)
* Content Source: [powerapps-docs/maker/data-platform/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/solutions-overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@VFXpro - thank you for your feedback. The flow designer copy and paste preview feature does appear to work with flows created from within a solution. The article has been updated to remove the limitation. 

Closing issue.
