### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by danieldotskc** [MicrosoftDocs/powerapps-docs#2693]
the links on the description of '**Block Extension by other plug-ins**' are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4426751-4ca5-a0f3-af75-7684739628cc
* Version Independent ID: 1e712c13-01cd-58e7-1406-48abecea5ca9
* Content: [Create your own messages (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/custom-actions?WT.mc_id=BA-MVP-5003861)
* Content Source: [powerapps-docs/developer/data-platform/custom-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/custom-actions.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@danieldotskc  Thanks for catching that. Should be fixed by EOD today.
