### ISSUE TITLE
Maximum Template Size

### ISSUE THREAD

**Issue by henry-royan** [MicrosoftDocs/powerapps-docs#2696]
Is there a maximum Template Size for a Gallery in Portrait Orientation. It looks like it's around 775, but this is omitted from this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51b1efea-d75c-b595-a9a1-14dec901ab48
* Version Independent ID: 9b1b0a35-35ad-8359-e1ab-daa80ab58c19
* Content: [Gallery control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-gallery)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-gallery.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-gallery.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The template size depends on the screen size, and you can also use a container inside gallery to enable scrolling.

**Comment by danwatford** [comment]
Hi @tapanm-MSFT ,

As far as I can tell from an app with nested galleries, the maximum template height for a gallery is 5000.

If one of the gallery item's height exceeds 5000 then it will overflow into the next item.

Please could you confirm if 5000 is indeed the maximum template size for a portrait gallery.
