### ISSUE TITLE
Title field is Required

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/powerapps-docs#27]
AS written, the sample will not work. In a SharePoint List, the Title field is required by default. However, we are instructed to remove the Title field form the Form. As a result, the user is unable to set a value for Title and is therefore unable to save the item.

Consider updating the instructions to have the Title column RENAMED to Product Name (as opposed to creating a new column and hiding Title in the Form).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@sparkitect Per internal testing, the title field is required in that you can't delete it, but you also don't need to put data in it. So you can save an item for which the title is blank. If having a blank column is distracting, you can remove it from the default view, and I've added a sentence to that effect. Thanks!

**Comment by CrackerboxOnline** [comment]
When creating a custom list the Title field is by default set to Required.  This field cannot be left blank and will throw a validation error if left blank on submit.

The documentation asks to remove the field (which is poor practice but ok, better to rename the field to 'Product Name' in this example) but does not ask to set the Title field to 'Not Required'.
