### ISSUE TITLE
AzureChinaCloud support

### ISSUE THREAD

**Issue by SongtaoLin** [MicrosoftDocs/powerapps-docs#2702]
[Enter feedback here]
I'd like to create an authentication profile which targeted to an D365 environment hosting in China Cloud using "pac auth create --url https://xyz.crm.dynamics.cn", and failed, so my question is that this package supports Azure China Cloud? if so, which parameter could i use? If not, could you tell me when it would support it?

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c487a-6048-5ed1-d3b3-f15756f0f953
* Version Independent ID: 35502302-bdf4-6a02-11cb-dea21d9fa7ff
* Content: [Import components into model-driven apps in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls)
* Content Source: [powerapps-docs/developer/component-framework/import-custom-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/import-custom-controls.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by kkanakas** [comment]
Pac CLI support for China Cloud is not currently available. It will be available in the next few months.

**Comment by Nkrb** [comment]
Closing the issue. If you need further help, please reopen or create a new issue.
