### ISSUE TITLE
This is NOT a Teams Model-Driven Integration

### ISSUE THREAD

**Issue by YahyaManasrah** [MicrosoftDocs/powerapps-docs#2703]
REaL integration is same like how Teams integrates with Microsoft List so you can CHAT  View or a Raw by itself so each raw has its own chat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 392a9208-4284-4cdc-33a0-0e320bd57551
* Version Independent ID: 9a625c31-8556-a1ce-2b69-77326a7b9445
* Content: [Embed a model-driven app as tab app - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/embed-model-driven-teams-tab)
* Content Source: [powerapps-docs/teams/embed-model-driven-teams-tab.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/embed-model-driven-teams-tab.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@YahyaManasrah - Thanks for your feedback. If you would like to see more features with Power Apps and Teams integration, visit https://ideas.powerapps.com to submit your suggestions.  

Closing this issue.

**Comment by YahyaManasrah** [comment]
Note I am not asking for a feature. This is a long time ago promised feature and is never delivered. See https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Fteams-integration%2Fteams-install-app&data=04%7C01%7Cy.manasrah%40elite-itc.com%7C7eec3688cb274f56649308d971d941b2%7C477500776955415e87c67ed4205cd23e%7C0%7C0%7C637666000948013359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CPXckY18rViktn9NhoSpz2AqKhY9k%2F3Z5KEd3jpyhSg%3D&reserved=0
