### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by markdebhailis** [MicrosoftDocs/powerapps-docs#2704]
On this page: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/connection-entities?source=docs

Following links are broken:

- https://docs.microsoft.com/en-us/reference/entities/connection.md
- https://docs.microsoft.com/en-us/reference/entities/connectionrole.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4140573-407b-8fb6-684e-c4b3ffe26272
* Version Independent ID: 590125d4-25f4-8344-a876-4b280b0208a2
* Content: [Use connections to link records to each other (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/connection-entities?source=docs)
* Content Source: [powerapps-docs/developer/data-platform/connection-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/connection-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@markdebhailis  Thanks for pointing that out. Should be fixed by EOD today
