### ISSUE TITLE
Updated Forms diagram requires to be changed to reflect the 2021 Release Wave 2

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#2706]
Footers are removed in 2021 Release Wave 2. "Record Primary Name" should be updated to reflect the terminology updates ("Row Primary Name" maybe?).

https://docs.microsoft.com/en-us/power-platform/important-changes-coming#form-footers-in-model-driven-apps-wont-be-supported-with-the-2021-release-wave-2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0964ac34-9b6e-a813-bfb3-f5d7fef0331d
* Version Independent ID: 22f6cc52-0273-8e98-4163-373c5d142e37
* Content: [Model-driven app main form presentations in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/main-form-presentations)
* Content Source: [powerapps-docs/maker/model-driven-apps/main-form-presentations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/main-form-presentations.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@LinnZawWin - The article and diagram have been revised to better reflect the current main form layout. Also, record is not being replaced with row for users or makers to the record primary name is still relevant. 

Closing issue.
