### ISSUE TITLE
Not clear what tests are being here automated

### ISSUE THREAD

**Issue by smapelli** [MicrosoftDocs/powerapps-docs#2708]
[Enter feedback here]
It is not immediately clear unless you dive into the document that this document is talking of automating Test Studio tests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 513096fe-dce9-70cc-4891-13ffdf2447ca
* Version Independent ID: 29cdb9ce-32e4-2cc5-522b-76587872d8ab
* Content: [Automate tests with Azure Pipelines using classic editor - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/test-studio-classic-pipeline-editor)
* Content Source: [powerapps-docs/maker/canvas-apps/test-studio-classic-pipeline-editor.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/test-studio-classic-pipeline-editor.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @aengusheaney
* Microsoft Alias: **aheaney**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The topic is under the table of contents listed as "Test an app with Test Studio", after the topics of "Test Studio Overview", and "Working with Test Studio".
