### ISSUE TITLE
rfc4122 compliance

### ISSUE THREAD

**Issue by mauledbyjesus** [MicrosoftDocs/powerapps-docs#271]
I'm currently generating UUIDv4 GUIDs for my application using a web service but would like to save a few ms using this native function. Are these GUIDs compliant with any rfc in particular, or can we get some info on how they're generated? Are they time-based, random, or fairy dust? I heard v6 will be fairy-based.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970cfd20-b58d-bebe-7853-de14daf2b7a0
* Version Independent ID: 7a49311e-a68f-835d-93ec-4d000cf818eb
* Content: [GUID function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-guid)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-guid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-guid.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
No fairy dust involved.  They are pseudo-random generated RFC 4122 version 4 GUIDs.  We've updated the docs to reflect this.

**Comment by AFTOwen** [comment]
Thanks, @mauledbyjesus!
