### ISSUE TITLE
RequireNewInstance default value

### ISSUE THREAD

**Issue by zzzzz0908** [MicrosoftDocs/powerapps-docs#2710]
Docs say that default value for RequireNewInstance is *false*.
I made some testing using connection string without specified RequireNewInstance and it seems like default is *true*.
Also I decompiled Microsoft.CrmSdk.XrmTooling.CoreAssembly and source code in CrmConnection.cs says that default is *true*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf4a7bc-1ccb-26e5-f9e8-85c2843e98b7
* Version Independent ID: 64536f0c-1005-cd5c-9fdb-01c301108d46
* Content: [Use connection strings in XRM tooling to connect to Microsoft Dataverse (Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect)
* Content Source: [powerapps-docs/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by MattB-msft** [comment]
You are correct @zzzzz0908 ,  
We changed the default behavior of this flag in [Nuget version 8.2.0.1](https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/8.2.0.1) . 

We will get this fixed in the docs.

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
