### ISSUE TITLE
Clarification of the 80MB limit.

### ISSUE THREAD

**Issue by mscottsewell** [MicrosoftDocs/powerapps-docs#2712]
Current Text - "Use this connector for large datasets that are greater than 80 MB. "
Proposed Text - "Use this connector when the individual query results would exceed 80 MB."

My customer understood the existing wording to mean if the data in Dataverse exceeded 80MB, they couldn't use the Dataverse connector - It's just confusion around what the 'dataset' is - I don't think the wording is incorrect, but the reader may not be familiar with the intent.

Reach out if I can assist. - Thanks!

Scott.Sewell@Microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e6e30d-4224-459f-8525-08718d6d77e4
* Version Independent ID: fe075fe5-5d2e-7b96-3608-9ad3138380da
* Content: [Create a Power BI report using the Dataverse connector - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector?source=docs)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@mscottsewell - thank you for your feedback. The article has been updated to change the wording to indicate the query result that should be less than 80 MB. 
Closing issue.
