### ISSUE TITLE
Documentation steps followed but unable to update the format of my Custom field 

### ISSUE THREAD

**Issue by karankhosla12** [MicrosoftDocs/powerapps-docs#2716]
After following the documentation I made a few observations- 
1) while passing the URL we would also need to provide the attribute ID something like xyz.crm.dynamics.com/api/data/v9.0/EntityDefinitions(LogicalName='account')/Attributes(LogicalName='new_someurl')

2) making an update to the labels works fine but not to the format of the fields 

3) There is a mismatch between the POST method that is written above however the code informs us to use PUT 

--------------------------------------------------------------

Some additional findings, I noticed when we use 

GET : 
https://xyz.crm.dynamics.com/api/data/v9.0/EntityDefinitions(LogicalName='account')/Attributes(LogicalName='new_someurl')?$expand=*

The format name and format JSON seems to be null. I am assuming the process to change these values would be by an Unbound action // just an assumption 

API used in PostMan - -

Method -- PUT 
URL - https://omnichanel.crm.dynamics.com/api/data/v9.0/EntityDefinitions(LogicalName='account')/Attributes(a57c3bbe-c311-ec11-b6e6-0022480b3cf5)

Body - 
{
 "AttributeType": "String",
 "AttributeTypeName": {
"Value": "StringType"
},
"Description": {
"@odata.type": "Microsoft.Dynamics.CRM.Label",
"LocalizedLabels": [
{
"@odata.type": "Microsoft.Dynamics.CRM.LocalizedLabel",
"Label": "",
"LanguageCode": 1033
}
]
},
"DisplayName": {
"@odata.type": "Microsoft.Dynamics.CRM.Label",
"LocalizedLabels": [
{
"@odata.type": "Microsoft.Dynamics.CRM.LocalizedLabel",
"Label": "SomeUrl",
"LanguageCode": 1033
}
]
},
"RequiredLevel": {
"Value": "None",
"CanBeChanged": true,
"ManagedPropertyLogicalName": "canmodifyrequirementlevelsettings"
},
"SchemaName": "new_SomeURL",
"@odata.type": "Microsoft.Dynamics.CRM.StringAttributeMetadata",
"FormatName": {
"Value": "Phone"
},
"MaxLength": 100
}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a41f3016-daa4-7f40-0761-f93bcb42a423
* Version Independent ID: 1422d98f-6c84-4ddb-1e42-96ce5849e98a
* Content: [Data type format conversions (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/data-type-format-conversions)
* Content Source: [powerapps-docs/developer/data-platform/data-type-format-conversions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/data-type-format-conversions.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nabuthuk**

**Comment by NHelgren** [comment]
The code to enable this feature is in the process of rolling out and should be available shortly in your region. That is the cause of the error you are seeing in number 2 above.

For 1 and 3 I will modify the document.
