### ISSUE TITLE
Request to specify the upper limit of import file size

### ISSUE THREAD

**Issue by YoshikaSuzuki** [MicrosoftDocs/powerapps-docs#2718]
The file size when importing Excel was 1M. Please specify this in the document.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 46209bf7-62b7-f424-f749-f297c8847e35
* Version Independent ID: ffef7489-39b8-60dd-299b-367e3b694843
* Content: [モデル駆動型アプリでデータをインポートする - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/user/import-data)
* Content Source: [powerapps-docs/user/import-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/import-data.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@YoshikaSuzuki As it states the topic: 

The maximum file size allowed for .zip files is 32 MB. For the other file formats, the maximum file size allowed is 8 MB.

Thanks,
Mints

**Comment by YoshikaSuzuki** [comment]
Please specify that the import will be done as a single if it exceeds 1M.
If it is within 1M, it can be executed in parallel.
