### ISSUE TITLE
2 Issues with Create PCF instructions.  Please help fix.

### ISSUE THREAD

**Issue by Tiffastic** [MicrosoftDocs/powerapps-docs#2719]
Hello, thank you for writing the instructions to create a PCF.

May I suggest the following updates?

I spent an hour trying to figure out why I cannot package my code component and create a solution zip file.

Turns out there are 2 issues with the instructions: 

1) "Create a new folder Solutions inside the LinearInputControl folder and navigate into the folder."

meant create a new folder Solutions inside the ROOT folder called LinearInputControl rather than the subfolder called LinearInputControl.  Following the instructions from top to bottom, you get 2 folders BOTH called LinearInputControl.  This is quite confusing when following the instructions.

May I suggest to update the instructions so that the ROOT folder is called LinearInput while the folder inside of it is called LinearInputControl?  (and update the following instructions according to the new name change).

2) "To generate a zip file from your solution project, when inside the the cdsproj solution project directory, using the following command: msbuild /t:restore"

This is NOT enough.  After running msbuild /t:restore, we also need to run msbuild as well in order to get the zip folder.

Will you also add to run msbuild as well?

Thanks, the updates to the instructions will help future developers.

-Thuy ("twee")-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
