### ISSUE TITLE
Launch() won't work if Powerapp is embedded into iFrame

### ISSUE THREAD

**Issue by alpinedelight** [MicrosoftDocs/powerapps-docs#272]
I think limitations should be mentioned on this document.
If I embed my app using the steps here, I can see and use the app, however launching websites stops working.
If I open the app directly via powerapps portal, launch works again.

Unless the team aren't aware of this, these caveats should be mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 559b4613-fbe0-45dc-f8bf-ff3a70b5f66e
* Version Independent ID: 36921b82-2295-8d26-9be0-d2d23ee11ab7
* Content: [Integrate canvas apps into websites and other services - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-apps-dev)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-apps-dev.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/embed-apps-dev.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
@alpinedelight Thanks for your question. Are you trying to launch a website that has lower security settings than those of the site in which the app is embedded? For example, is the app embedded in a site that's in the Trusted Sites zone but the site is in the Internet zone? Can you launch a site that's in the same zone as the site in which you've embedded the app?

**Comment by alpinedelight** [comment]
If i remember correctly it was due to the way the link is launched in embedded mode and pop-up blockers... well block it

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and updates. Pop-up blocker needs to be disabled or allow the pop-up temporarily for launch() to work from within iFrame. And as you mentioned, it continues to work in app when using app directly. Content will be updated accordingly.
