### ISSUE TITLE
Cannot disassociate a reference by setting null

### ISSUE THREAD

**Issue by trucbinh** [MicrosoftDocs/powerapps-docs#2720]
Cannot disassociate a reference by setting null. Still get the error "An error occurred while validating input parameters: Microsoft.OData.ODataException: The 'odata.bind' instance or property annotation has a null value. In OData, the 'odata.bind' instance or property annotation must have a non-null string value" or "Microsoft.Crm.CrmException: Invalid property 'custom_field_without_odata.bind' was found in entity 'Microsoft.Dynamics.CRM.account'. ---> Microsoft.OData.ODataException: Does not support untyped value in non-open type"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce0b1cd-e7ce-a9b8-6b51-37be0a4dd848
* Version Independent ID: 54eecc75-29fe-29ba-94c9-0ad0b8694d69
* Content: [Associate and disassociate table rows using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/associate-disassociate-entities-using-web-api#remove-a-reference-to-an-entity)
* Content Source: [powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@trucbinh 
Thank you for your feedback. Sorry for the delay in responding.
At the time you submitted your feedback, the ability to disassociate with PATCH by setting the null value to a single-valued navigation property should have been available to you.

We have examples here: [Disassociate with a single-valued navigation property](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/associate-disassociate-entities-using-web-api#disassociate-with-a-single-valued-navigation-property). These examples were all tested, so they represent what you should expect.

If you are not getting these results, please contact technical support.
