### ISSUE TITLE
Video Links not publicly available

### ISSUE THREAD

**Issue by rogerio-barreto** [MicrosoftDocs/powerapps-docs#2721]
Both videos in the bottom of page:

Video: Hierarchical Security Modelling
Video: Hierarchy Visualization

Are showing as private and non publicly available videos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14ab4029-80e9-b009-382c-13902d8fddc8
* Version Independent ID: dade3b22-87bb-62cc-fcdf-620fa4772b10
* Content: [Define and query hierarchical data with Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/define-query-hierarchical-data)
* Content Source: [powerapps-docs/maker/data-platform/define-query-hierarchical-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/define-query-hierarchical-data.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@rogerio-barreto - thank you for your feedback. It appears the videos have been made unavailable so the links have been removed from the article. When the videos become available again, the article will be updated to add the links back. 

Closing issue.
