### ISSUE TITLE
Sample is using a very old version of ADAL

### ISSUE THREAD

**Issue by adrichema** [MicrosoftDocs/powerapps-docs#2724]
This sample is using a very old version of ADAL. It's impossible to update the ADAL lib because the newer versions does have a UserCredential that takes 2 arguments (username and password). Please update this sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by RedsGT** [comment]
I agree.

**Comment by phecke** [comment]
@adrichema The topic has been updated and will be published by EOD today. The code project now uses the latest version of ADAL.

**Comment by adrichema** [comment]
Thanks @phecke  for updating the sample.
