### ISSUE TITLE
No comment on anything to enable access to the Azure SQL DB

### ISSUE THREAD

**Issue by liamgsmith** [MicrosoftDocs/powerapps-docs#273]
Hi,
There's no info here as to any setup required on the Azre SQL DB side of things which doesn't help me figure out why I can connect to the db using SMSS but not via PowerApps.
Cheers,
L

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549f9a62-dfcd-42de-764e-de9dfefe030f
* Version Independent ID: bdb3d897-d921-b4da-3078-4bb05cd9265f
* Content: [Overview of the SQL Server connection - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-azure-sqldatabase#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-azure-sqldatabase.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-azure-sqldatabase.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by matt-debeer** [comment]
I have the same issue.  Did you ever figure it out?

**Comment by liamgsmith** [comment]
Er yes... from memory I had the name wrong or had used an incorrect one. Ie the one I’d used for SQL Server Mgt Studio wasn’t what I was trying in PowerApps.
