### ISSUE TITLE
The webservice url is no longer working

### ISSUE THREAD

**Issue by akill25445** [MicrosoftDocs/powerapps-docs#2733]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b56c32-971a-739d-40b6-5e2a2fb82c65
* Version Independent ID: 219c2bb0-0b17-1af4-7b87-1ea3e9c3f228
* Content: [Virtual table walkthrough using the OData Data Provider in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/virtual-entity-walkthrough-using-odata-provider)
* Content Source: [powerapps-docs/maker/data-platform/virtual-entity-walkthrough-using-odata-provider.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/virtual-entity-walkthrough-using-odata-provider.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@akill25445 - As per the article just following the example web service URL.

 Important
The web service url used for this walkthrough isn't a functioning web service.

Closing issue
