### ISSUE TITLE
Is The odata.continue-on-error preference still not supported by the web API?

### ISSUE THREAD

**Issue by martintoelk** [MicrosoftDocs/powerapps-docs#2735]
Hi Power Platform Team,

In the old D365 (v8.0) docs, there was a hint that  "The odata.continue-on-error preference is not supported by the web API".

Is this still true for v9.1/v9.2 (On-Premises/Cloud)? The new documentation does not indicated that the header is not supported, and it seems to work. A clarifiation would be great :)

![image](https://user-images.githubusercontent.com/24940711/133595764-5dce4b75-be8a-4fde-a19e-e93cb5aadf7d.png)

https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/mt607719(v=crm.8)#batch-requests

BR

Martin
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db53047-327d-6eec-e6a8-4d9dae98f362
* Version Independent ID: 31b3ebbd-9070-db30-cc4e-cec4b41373b8
* Content: [Execute batch operations using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/execute-batch-operations-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by martintoelk** [comment]
To add more confusion from our side:

 It seems that **v8.2 (On-Premises, 8.2.3.8)** is proccessing the whole batch, even when an error occurs,

**v9.1 On-Premises ( 9.1.0001.0914)** will stop the processing of the remainder of the batch, when an error occurs. After setting the "odata.continue-on-error" preference, v9.1 will process the whole batch, even in the event of an error.

We are currently migrating form v8.2 to 9.1 and our interface guy's did stumbled across this issue

**Comment by phecke** [comment]
@JimDaly Can you please respond to this question.

**Comment by JimDaly** [comment]
@phecke & @martintoelk 
I'll look at this .

**Comment by JimDaly** [comment]
I added a new section to the topic to describe this behavior. See [Handling errors](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/execute-batch-operations-using-web-api#handling-errors)

**Comment by socketopp** [comment]
@JimDaly Hi Jim, why isn't this header respected when using Microsoft Business Central and related plugins? The response back from the server indicate that they use OData Web API 4.0. Is the header not respected because it's introduced in 5.7? https://docs.microsoft.com/en-us/odata/webapi/continue-on-error

**Comment by JimDaly** [comment]
@socketopp 
I'm not familiar with Business Central and related plug-ins. Web API doesn't behave differently for different clients.
OData has two current versions: 4.0 and 4.01. Dataverse uses v4.0. The docs you are linking to are about building your own OData service and the OData libraries involve versions like OData Web API V5.7. 

The headers should be respected as documented for Dataverse. If not, please contact technical support.

**Comment by vijendraIntrop** [comment]
Hi Team,
I am trying batch API with "Prefer: odata.continue-on-error" header but its not working as expected for neither v8.2 nor v9.2. Could you please mention which version has support for "odata.continue-on-error". Any error that occurs in the batch it stopping the processing of the remainder of the batch.

**Comment by JimDaly** [comment]
@vijendraIntrop 
The version is irrelevant.
It should work for you. We don't have any sample dedicated to $batch, but it is used in some of our C# samples via the WebApiService class library See [Batch](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/samples/webapiservice#batch) for details.

What language are you using?
Can you capture the HTTP traffic and post examples of the requests here?

**Comment by vijendraIntrop** [comment]
Hi @JimDaly, 
thanks for quick reply.

Here is the example, used "**_Prefer: odata.continue-on-error_**" request header. 
Error occurred for a request within a batch, the error for that request returned for the batch request **and stopped the processing of the remainder of the batch.**

As used continue-on-error it should process remaining changesets but it didnt and retuned only single failed changeset.
I am using .NET 4.6 but even I tried in Postman and got same response.
``
**HTTP Request**

{Method: POST, RequestUri: 'https://ourfoo-test.crm4.dynamics.com/api/data/v9.1/$batch', Version: 2.0, Content: System.Net.Http.ByteArrayContent, 
Headers:
{
  Authorization: Bearer <!============token======================!>
  Accept: application/json
  OData-MaxVersion: 4.0
  OData-Version: 4.0
  Prefer: odata.continue-on-error
  Content-Type: multipart/mixed; boundary=batch_gZNj8h
}}


**Request body**

--batch_kMJv3c
Content-Type: multipart/mixed;boundary=changeset_WwZNCN

--changeset_WwZNCN
Content-Type: application/http
Content-Transfer-Encoding:binary
Content-ID: 1

PATCH https://ourfoo-test.crm4.dynamics.com/api/data/v9.1/accounts(20b7517a-5a52-xxxx-xxxx-000d4aa87do8) HTTP/1.1
Content-Type: application/json;type=entry
Accept: application/json

{"websiteurl":"www.abc.com","emailaddrezz1":"vk@abc.com"}

--changeset_WwZNCN
Content-Type: application/http
Content-Transfer-Encoding:binary
Content-ID: 2

PATCH https://ourfoo-test.crm4.dynamics.com/api/data/v9.1/accounts(cf4fb96b-21a5-xxxx-xxxx-000d4a3a8e9d) HTTP/1.1
Content-Type: application/json;type=entry
Accept: application/json

{"websiteurl":"www.xyz.com","emailaddress1":"vk@xyz.net"}

--changeset_WwZNCN--

--batch_kMJv3c--


**Response**

--batchresponse_d36f7ca6-4a4e-44c8-a0a3-489d7f4c3f5c
Content-Type: multipart/mixed; boundary=changesetresponse_29268a32-305c-4b58-8253-34d275338ab0

--changesetresponse_29268a32-305c-4b58-8253-34d275338ab0
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

HTTP/1.1 400 Bad Request
REQ_ID: aee7bb77-9ac6-4547-b22e-69334c7a34f7
Content-Type: application/json; odata.metadata=minimal
OData-Version: 4.0

{"error":{"code":"0x80048d19","message":"Error identified in Payload provided by the user for Entity :'', For more information on this error please follow this help link https://go.microsoft.com/fwlink/?linkid=2195293  ---->  InnerException : Microsoft.Crm.CrmException: Invalid property 'emailaddrezz1' was found in entity 'Microsoft.Dynamics.CRM.account'. ---> Microsoft.OData.ODataException: Does not support untyped value in non-open type.\r\n   at System.Web.OData.Formatter.Deserialization.DeserializationHelpers.ApplyProperty(ODataProperty property, IEdmStructuredTypeReference resourceType, Object resource, ODataDeserializerProvider deserializerProvider, ODataDeserializerContext readContext)\r\n   at Microsoft.Crm.Extensibility.CrmODataEntityDeserializer.ApplyStructuralProperty(Object resource, ODataProperty structuralProperty, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Crm.Extensibility.CrmODataEntityDeserializer.ApplyStructuralProperty(Object resource, ODataProperty structuralProperty, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyStructuralProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)\r\n   at Microsoft.Crm.Extensibility.CrmODataEntityDeserializer.ApplyStructuralProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)."}}
--changesetresponse_29268a32-305c-4b58-8253-34d275338ab0--
--batchresponse_d36f7ca6-4a4e-44c8-a0a3-489d7f4c3f5c--

**Comment by JimDaly** [comment]
@vijendraIntrop 
Sorry for the delay in responding. Thanksgiving holiday here in the US.

Please see the attached [batch-continue-on-error-test.txt](https://github.com/MicrosoftDocs/powerapps-docs/files/10099526/batch-continue-on-error-test.txt) showing the result of this code using the [WebAPIService BatchRequest class](https://github.com/microsoft/PowerApps-Samples/blob/master/dataverse/webapi/C%23-NETx/WebAPIService/Batch/BatchRequest.cs):

```
Config config = App.InitializeApp();
var service = new Service(config);

List<HttpRequestMessage> changeSet1Requests = new()
{
    new CreateRequest("accounts", new JObject { { "name", "Test Account 1" } }),
    new CreateRequest("accounts", new JObject { { "name", "Test Account 2 name is way too long. Tooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo Loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong" } })
};

List<HttpRequestMessage> changeSet2Requests = new()
{
    new CreateRequest("accounts", new JObject { { "name", "Test Account 3" } }),
    new CreateRequest("accounts", new JObject { { "name", "Test Account 4" } })
};

List<ChangeSet> changes = new()
{
    new ChangeSet(changeSet1Requests),
    new ChangeSet(changeSet2Requests)
};

BatchRequest request = new(service.BaseAddress)
{
    ContinueOnError = true,
    ChangeSets = changes
};

BatchResponse response = await service.SendAsync<BatchResponse>(request);

response.HttpResponseMessages.ForEach(async resp => {

    if (resp.IsSuccessStatusCode)
    {
        Console.WriteLine(resp.As<CreateResponse>().EntityReference.Id);
    }
    else
    {
        ServiceException error = await Service.ParseError(resp);
        Console.WriteLine(error.Message);
    }                
            
});
```
Output is like this:

```
A validation error occurred.  The length of the 'name' attribute of the 'account' entity exceeded the maximum allowed length of '160'.
a4384e07-b56e-ed11-9562-000d3a9933c9
a7384e07-b56e-ed11-9562-000d3a9933c9

```
You can see that `Prefer: odata.continue-on-error` is working here. While the first changeset fails, the second completes.
I also tested by using an invalid property name like you did, and I got the same result.

ChangeSet is a transaction grouping, so if any one of the items fails, all the items in the changeset must fail.

Please take a look at the attached example and let me know if this helps.

**Comment by JimDaly** [comment]
@vijendraIntrop 
Changesets are only required when you need all the operations within them to be performed in a single transaction.
You can send requests without changesets if you don't require them all to succeed as a group.

See attached [continue-on-error-no-changeset.txt](https://github.com/MicrosoftDocs/powerapps-docs/files/10107373/continue-on-error-no-changeset.txt)

Action item for me: Provide some examples in the docs that are not using change sets.

The only limit is 1000 requests per batch.
That old community post seems to be referring to case where you use the OData client libraries.

**Comment by vijendraIntrop** [comment]
Thanks @JimDaly,
Got it, change-set not required if there is not dependent/interrelated entity operation (in a one transaction) and batch request should be without change-set for this scenario.

Your attached sample batch request and response helped me to understand.

**Comment by vijendraIntrop** [comment]
Thanks @JimDaly 
It work as expected.

**Comment by JimDaly** [comment]
I've got my workitem to add examples without changesets, so closing this.

**Comment by JimDaly** [comment]
I have completed the workitem created for this issue. Major changes to [Execute batch operations using the Web API](https://learn.microsoft.com/power-apps/developer/data-platform/webapi/execute-batch-operations-using-web-api) will be published soon.
