### ISSUE TITLE
Action 'Get_user_profile_(V2)_2' failed

### ISSUE THREAD

**Issue by Bluebeemer5** [MicrosoftDocs/powerapps-docs#2736]
I keep the Error
Action 'Get_user_profile_(V2)_2' failed

The previous Get_user_profile_(V2) works fine.

Any suggestions
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 620aee88-efbc-394f-0cbb-79be3f4a6bd2
* Version Independent ID: 632dd319-a22f-a4b7-a2da-f60538b1e4e6
* Content: [How to export Ideas data for reporting - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/export-employee-ideas-for-reporting)
* Content Source: [powerapps-docs/teams/export-employee-ideas-for-reporting.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/export-employee-ideas-for-reporting.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **namarwah**

**Comment by Bluebeemer5** [comment]
The list votes is pulling the data and if I remove Section @Get_user_profile_(v2)_2 and I can write out the file with idea and full name - not using 'Display Name'

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed. Changes will be reflected soon.
