### ISSUE TITLE
Should these guidance be applied to implementing activties via CodeActivity?

### ISSUE THREAD

**Issue by sergeytunnik** [MicrosoftDocs/powerapps-docs#274]
Or activities aren't cached that way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1e71b1-7a82-b4b8-27ad-d1bbb78e3814
* Version Independent ID: 7c28f677-aba1-bd0d-173e-eaf187bf32e9
* Content: [Develop IPlugin implementations as stateless - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by sergeytunnik** [comment]
Hi. Any updates on this?

**Comment by AntoineGauthier** [comment]
It seems so:


> For improved performance, Dynamics 365 for Customer Engagement caches custom workflow activity  instances. The custom workflow activity’s Execute method should be written to be stateless because the  constructor is not called for every invocation of the custom workflow activity. Also, multiple system  threads could execute the custom workflow activity at the same time. All per invocation state information  is stored in the context, so it is not recommended to use global variables or member variables to pass  data from one invocation to the next.

Source: [https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/workflow/create-custom-workflow-activity](url)
