### ISSUE TITLE
Log to App Insights does not contain EnvironmentID and AppName

### ISSUE THREAD

**Issue by guillaume-kizilian** [MicrosoftDocs/powerapps-docs#2743]
Is there any way/configuration needed to make EnvironmentId and AppName appearing in AppInsights logs ?

![image](https://user-images.githubusercontent.com/6792560/134199414-f11b4dff-476c-4140-91ae-297797fc441f.png)

Regards,
Guillaume
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d93af67a-9f3c-97fd-2899-2045c9f7e349
* Version Independent ID: 1cb12077-eec7-45cd-fe7e-fb10fa5c1936
* Content: [Analyser la télémétrie d’une application canevas à l’aide d’Application Insights - Power Apps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/application-insights)
* Content Source: [powerapps-docs/maker/canvas-apps/application-insights.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/application-insights.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **austinj**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It's not possible currently. Documentation will be updated when this it's available.
