### ISSUE TITLE
The Print function for SP forms

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/powerapps-docs#2744]
Documentation lists known limit "The Print function currently doesn't work on mobile devices and on SharePoint custom forms".
Will this be added to SharePoint custom forms in the future?

**Comment by Mattp123** [comment]
Issue appears to be regarding this article and section: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-print#known-limitations

**Comment by Nkrb** [comment]
@samadane Thanks for reaching to us. There is no timeline from the team when this feature is available in SharePoint forms. We will update the docs when we have an update from the team. Closing the issue. If you need further help, please reopen or create a new issue.
