### ISSUE TITLE
HTML sample codes fail

### ISSUE THREAD

**Issue by carlosrsolis** [MicrosoftDocs/powerapps-docs#2745]
All the HTML codes needed in the **Create an app that uses mobile sensors** include "\" Copying them as instructed will produce an error.  A simple find and replace \ with nothing, cleans up the code and works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c835c59-2d7d-450a-4f93-53caac0dcae8
* Version Independent ID: 08dcebb7-733a-1047-9ec8-daca21dc3b55
* Content: [Create an app that uses mobile sensors - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/how-to/mobile-sensors)
* Content Source: [powerapps-docs/maker/canvas-apps/how-to/mobile-sensors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/how-to/mobile-sensors.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **anuitz**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed and will reflect the changes soon.

**Comment by carlosrsolis** [comment]
Awesome

Saludos,


Dr. Carlos Balam-Kuk Solís
Associate VP – Technology Innovation
[Pronouns: he -his - él - mestizo]
Ph.: 512-245-1799
Texas State University
[1483637306080_PastedImage]

________________________________
