### ISSUE TITLE
Error message doesn't link to resolve dependency

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/powerapps-docs#2749]
Step 8 states that a link to install missing dependencies will be provided in the error message.  This isn't my experience: error message simply states which dependencies are missing (example below)

_There are missing dependencies. Install the following solutions before installing this one: "Dynamics365Company (2.2.2.5)", "Dynamics365FinanceAndOperationsCommon (2.2.2.50)", "Dynamics365FinanceExtended (2.2.2.98)", "FieldServiceCommon (1.0.0.134)", "Dynamics365SupplyChainExtended (2.2.2.98)", "HCMCommon (2.2.0.3)"_

Given that the error message simply lists packages, it would be helpful if the documentation included a list that allowed the user to identify the app that contains each package.  A [D365 application idea](https://experience.dynamics.com/ideas/idea/?ideaid=be489a2f-8e1b-ec11-b76a-0003ff45e08b) has been logged suggesting that the content of the error message could be more helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a00b4a6-c147-cffa-92c9-5cb183c4ea67
* Version Independent ID: 83d7d42c-71f3-1138-318f-5bd252a2ab3b
* Content: [Import solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/import-update-export-solutions)
* Content Source: [powerapps-docs/maker/data-platform/import-update-export-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/import-update-export-solutions.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@rrhkpmg - Your issue has been forwarded to the solutions engineering team who is reconsidering what information and links are displayed to the user during import. Unfortunately, keeping an article with the dependency details and links would be difficult to keep current and not as actionable as having that relevant missing dependency information in the import experience. 

Closing issue.
