### ISSUE TITLE
Added one column named PROJECT in Audit location, But saving the field is not saving value

### ISSUE THREAD

**Issue by Bagulhem** [MicrosoftDocs/powerapps-docs#2750]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09b06e-0061-eb85-5852-a11038ddf393
* Version Independent ID: 01757436-d6b0-4ad4-3e96-48a06c0d0949
* Content: [Notify a manager on completion of an inspection - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/notify-manager-inspections)
* Content Source: [powerapps-docs/teams/notify-manager-inspections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/notify-manager-inspections.md)
* Service: **powerapps**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please raise a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) if this issue still persists for help with investigation.
