### ISSUE TITLE
Incorrect Code

### ISSUE THREAD

**Issue by Moyura2017** [MicrosoftDocs/powerapps-docs#2754]
[Enter feedback here]
Incorrect } it should be replaced with )

ClearCollect( NewOrder, 
    ForAll( Products, 
        If( 'Quantity Requested' > 'Quantity Available', 
            { 
                Product: Product, 
                'Quantity To Order': 'Quantity Requested' - 'Quantity Available' 
            } 
        } 
    )
)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cec09a3-057a-a581-fdb8-50d8039d5643
* Version Independent ID: 9e7aea5b-8f87-cfb9-709a-dd1ae409ab40
* Content: [ForAll function in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-forall)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-forall.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-forall.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
