### ISSUE TITLE
No way to rename SQL data source in apps

### ISSUE THREAD

**Issue by LaGallinaTuruleta** [MicrosoftDocs/powerapps-docs#2757]
In this paragraph
" To learn about renaming data sources in an app, and the difference between tabular and action-based data sources, go to Rename Power Apps action-based data sources." It not correct at least for SQL Connections. Here there is an image of my casuistic.

![Imagen](https://user-images.githubusercontent.com/17246362/134475482-ea2483ea-f5b8-4372-af85-aff49181f57c.png)
Thanks in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7c89a8f-b16f-2896-faae-efbb438c7a89
* Version Independent ID: 8ce453b3-7e57-c80a-7ca0-9b122ad4796b
* Content: [Overview of connectors for canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Rename capability has [this limitation](https://docs.microsoft.com/powerapps/maker/canvas-apps/rename-data-source#limitations). More information: [Action-based and tabular data sources](https://docs.microsoft.com/powerapps/maker/canvas-apps/rename-data-source#action-based-and-tabular-data-sources)
