### ISSUE TITLE
Syntax error on page

### ISSUE THREAD

**Issue by davinsgithub** [MicrosoftDocs/powerapps-docs#2758]
The following command mentioned on the page doesn't have the correct syntax (missing appropriate braces).
Set(MyAccount, Patch(Accounts, First(Account), 'Account Name': "Example name");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5786697f-ee29-1b61-c59a-955086201d55
* Version Independent ID: d2130620-9767-c72f-5bd7-8417e48cf65d
* Content: [Patch function in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
