### ISSUE TITLE
Call Out a limitation : DataSourceInfo is not supported with SharePoint

### ISSUE THREAD

**Issue by Zerg00s** [MicrosoftDocs/powerapps-docs#2759]
Can someone, please update the article to call out a limitation? `DataSourceInfo()` does not seem to work with SharePoint. It has never been working for the last 3 years. 

This is what @ebaron from Microsoft said in 2019:

**[v-xida-msft Community Support v-xida-msft Community Support](https://powerusers.microsoft.com/t5/Building-Power-Apps/DataSourceInfo-Does-Not-Work-properly/td-p/320518)**

> Currently, the DataSourceInfo() function is not supported in SharePoint List. The Product Team is investigating this issue, and plan to add support for this function.

## Feedback from other users

**[@WonderLaura](https://wonderlaura.com/2019/04/03/powerapps-with-sharepoint-permissions/)**

> If you watched my SharePoint Power Hour today, you may have noticed that I was surprised when the DataSourceInfo function did not give me accurate permission information about the currently logged in user’s access to a certain list in SharePoint.

**[Michael Glavina](https://www.youtube.com/watch?v=q_Z3ZeNlrhE)**

> Hi Audrie. I am trying to use DataSourceInfo for an Admin screen. The SharePoint Online site (which was created automatically by MS Teams) has a default owners permission group that can edit a DataSource list called Admin (not inherited - custom permissions). The site members can only Read the list (not inherited - custom permissions). OnStart --> Set(IsAdmin, DataSourceInfo(Admin,DataSourceInfo.EditPermission)) always returns true for all users. I have seen comments online about this going back to 2016. Is this a known issue? Am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3184818-d8e7-0d02-924f-55f8a7a34110
* Version Independent ID: 61267e2c-bfb1-9bda-d728-62329f3f535b
* Content: [DataSourceInfo function in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-datasourceinfo)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-datasourceinfo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-datasourceinfo.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
