### ISSUE TITLE
Question: hasEntityPrivilege function

### ISSUE THREAD

**Issue by phuocle** [MicrosoftDocs/powerapps-docs#2760]
I saw this function on the link  
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/utility/hasentityprivilege
with the syntax
```js
context.utils.hasEntityPrivilege(entityTypeName, privilegeType, privilegeDepth)
```
in the ```available for``` section it said: ```Model-driven apps```

But if I look at the reference link and not found the function

https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility

Is this function ```hasEntityPrivilege``` support ? if **yes**, please add it to the docs

**Comment by Nkrb** [comment]
@phuocle Thanks for reaching to us. The `hasEntityPrivilege` method right now only works for Power Apps component framework controls, it doesn't work when used in client API. Closing the issue. If you need further help, please reopen or create a new issue.
