### ISSUE TITLE
Undocumented change of behaviour of Xrm.WebApi.retrieveMultipleRecords in Editable Grid Context with 2021 Release wave 2

### ISSUE THREAD

**Issue by vseykov** [MicrosoftDocs/powerapps-docs#2761]
Hi,
in our organization I have Implemented a JS function activated onSave of a subgrid that performs a Xrm.WebApi.retrieveMultipleRecords query to get the current (Dirty) version of the records before the save so then I can Update the parent with Xrm.WebApi.online.updateRecord.

However the update to Release wave 2 has somehow broken this , as now the retrieveMultipleRecords returns the values from the records before the change and therefore any new data entered is not captured by the function.
Is this a feature or a bug? 
The new Wave is going to be applied relatively soon to our PROD environment automatically and we would need to know in order to adjust our app behavior

Environment details:

DEV:
2021 release wave 2 enabled
Server version: 9.2.21085.00134
Client version: 1.4.3182-2108.5

PROD:
2021 release wave 1 enabled
Server version: 9.2.21085.00134
Client version: 1.4.3182-2108.5

**Comment by ankarm** [comment]
Hi @vseykov. Xrm.WebApi.retrieveMultipleRecords never returned the "dirty" values. It always returns the persisted data that is in saved in CDS. To get dirty field values, you must use the [getValue()](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/getvalue) API.

Could you provide a sample of the code of your JS function with helpful comments? Maybe that will help me understand better.

**Comment by vseykov** [comment]
Hi @ankarm , thank you, here is the full function with short comments on most important steps

`function calculate(executionContext){
    let formContext = executionContext.getFormContext();

//define sum variables
let sumMRR = 0;
let sumNRR = 0;
let sumMRRinc = 0;
let sumNRRinc = 0;
let multMRRsum = 0;
let multMRRinc = 0;
    let lenArr = [];
    let renewalStatus = 0;
    try {
// Obtain the Current Quote and Opportunity ID
      var quoteid = formContext.getAttribute("sen_quote").getValue()[0].id;
      var opportunityid = formContext.getAttribute("sen_opportunity").getValue()[0].id;

//Start the Calculation Function

      setTimeout(function () {
//Retrieve All the Subgrid Lines from the custom Entity
      Xrm.WebApi.retrieveMultipleRecords("sen_productmatrix", "?$select=sen_name,sen_expectedtotalrevenue,sen_expectedrevenueincrease,sen_expectedcontractlengthinmonths,sen_renewal,_sen_quote_value&$filter=_sen_quote_value eq "+quoteid).then(
//on Success Promise return sum the numbers to correct array based on conditions
        function success(result) {
            for (var i = 0; i < result.entities.length; i++) {
              if(result.entities[i].sen_name.includes("(MRR)")){
                sumMRR += result.entities[i].sen_expectedtotalrevenue;
                sumMRRinc += result.entities[i].sen_expectedrevenueincrease;

                multMRRsum += result.entities[i].sen_expectedtotalrevenue*result.entities[i].sen_expectedcontractlengthinmonths;

                multMRRinc += result.entities[i].sen_expectedrevenueincrease*result.entities[i].sen_expectedcontractlengthinmonths;
                if(result.entities[i].sen_expectedcontractlengthinmonths>0){
                     lenArr.push(Number(parseFloat(result.entities[i].sen_expectedcontractlengthinmonths).toFixed(0))); 
                 console.log(lenArr);
                }
                if(result.entities[i].sen_renewal === true){
                    renewalStatus = 1;
            }

            }
              else if(result.entities[i].sen_name.includes(("NRR"))){
                sumNRR += result.entities[i].sen_expectedtotalrevenue;
                sumNRRinc += result.entities[i].sen_expectedrevenueincrease;
              }
            }
//Display results in console
            console.log("Sum MRR " + sumMRR);
            console.log("Sum MRRinc " + sumMRRinc);
            console.log("Summ NRR is "+ sumNRR);
            console.log("Summ NRR INC is "+sumNRRinc);
            console.log("Renewal Status (true/false) is: " + renewalStatus)

//insert the numbers to the parent quote
            var entityQ = {};
// Renewal Status true or false
            entityQ.sen_renewal = Boolean(renewalStatus);

//MRR, NRR Values
            entityQ.sen_mrrvalue = Number(parseFloat(sumMRR).toFixed(4));
            entityQ.sen_nrrvalue = Number(parseFloat(sumNRR).toFixed(4));
//sum of Increases
            entityQ.sen_totalmrrincrease = Number(parseFloat(sumMRRinc).toFixed(4));
            entityQ.sen_totalnrrincrease = Number(parseFloat(sumNRRinc).toFixed(4));
//multiplications Revenue * months
            entityQ.sen_summrrproductrevenue = Number(parseFloat(multMRRsum).toFixed(4));
            entityQ.sen_summrrproductrevenueincrease = Number(parseFloat(multMRRinc).toFixed(4));
// Min of expected Contract lenght which is >0
            if(lenArr.length > 0){

            entityQ.sen_expectedcontractlenght = Math.min.apply(Math, lenArr);
            } else {
              entityQ.sen_expectedcontractlenght = 0;
            }

//UPDATE PARENT QUOTE and then Open the updated record in the same window
            Xrm.WebApi.online.updateRecord("quote",quoteid, entityQ).then(
            function success(result) {
              console.log("quote updated");
              let windowOptions = {
                openInNewWindow: false,
                entityName: "quote",
                entityId: quoteid
                };
                Xrm.Navigation.openForm(windowOptions);

                      },
          function(error) {
          }
        );
        },
        )}, 500);

} catch (error) {
     console.log("Error: " + error.message) 
    }
}`

**Comment by vseykov** [comment]
Somehow the issue was resolved during these 3 weeks by itself, answer is probably somewhere in the changelog of the versions
**Today:**
2021 release wave 2 enabled
Server version: **9.2.21092.00145**
Client version: **1.4.3204-2109.2**

**27 Sept:**
2021 release wave 2 enabled
Server version: **9.2.21085.00134**
Client version: **1.4.3182-2108.5**
