### ISSUE TITLE
Misspelled word changes meaning of sentence.

### ISSUE THREAD

**Issue by fredcicles** [MicrosoftDocs/powerapps-docs#2762]
Authoring custom pages (preview) section states "Model-driven apps are ***not*** getting the ability to use canvas natively with the introduction of the custom page."  I believe that "not" should be "now".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2119255f-281e-11b0-54e1-921115e21a24
* Version Independent ID: 24314dee-2250-33b0-0e4d-66a4ca17f270
* Content: [Overview of building a model-driven app with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/model-driven-app-overview)
* Content Source: [powerapps-docs/maker/model-driven-apps/model-driven-app-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/model-driven-app-overview.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@fredcicles - Thank you for your feedback. The sentence has been corrected and will be published live in a few hours.
Closing issue.
