### ISSUE TITLE
Form Options section has incorrect information stated

### ISSUE THREAD

**Issue by madshaun1984** [MicrosoftDocs/powerapps-docs#2763]
[Enter feedback here]
Under "Form Options > Show Unsupported Fields" the description states,

`"All fields are currently supported. This is reserved for potential changes Dataverse may make to field types."`

This is not true, as at the very least "Choice" and "Choices" based fields are not supported.

This was identified via a portal created this morning using the current "Portal Starter Pack 9.2.2108.4".

I have not investigated any other unsupported field types as this misinformation has already led to hours of lost time!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4c99d3-65e9-9be5-70af-9cb9d3fcda29
* Version Independent ID: cedbcc2e-1cf8-7397-ac76-1324d0b8a735
* Content: [About basic forms - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/entity-forms)
* Content Source: [powerapps-docs/maker/portals/configure/entity-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/entity-forms.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated and will reflect the changes soon.
