### ISSUE TITLE
Newly added Command Button Shows a Error but its Undocumented in the documentation

### ISSUE THREAD

**Issue by nk-gears** [MicrosoftDocs/powerapps-docs#2766]
Error Details. : 
One of the scripts for this record has caused an error. For more details, download the log file.
ExecuteExpressionFunction endpoint is not initialized Session Id

Reference :
1. https://powerusers.microsoft.com/t5/Building-Power-Apps/Any-new-button-in-the-new-commandbar-preview-function-gives/td-p/1236248

2. https://docs.microsoft.com/en-us/powerapps/troubleshooting-startup-issues

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please create a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to investigate this problem for a fix.
