### ISSUE TITLE
Sample code has error in program.cs for PlatformParameters when using .Net 5

### ISSUE THREAD

**Issue by DMaxwell02** [MicrosoftDocs/powerapps-docs#2767]
Error in code provided for program.cs line 33. 

```
 var token = authContext.AcquireTokenAsync(
                resource, clientId, redirectUri,
                new PlatformParameters(
                    PromptBehavior.SelectAccount  // Prompt the user for a logon account.
                ),
                UserIdentifier.AnyUser
            ).Result;
```

PlatformParameters does not have enough parameters. Looking for ICustomWeb customWebUI as second parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@DMaxwell02 Strange. I have tested the sample many times and have never had such an error. What Visual Studio, .NET Framework, and ADAL package version are you using?

**Comment by phecke** [comment]
@DMaxwell02 I see you are using .NET 5. All our code samples and SDK assemblies required .NET Framework 4.6.2. If you come up with a fix for .NET 5, let me know.

**Comment by phecke** [comment]
@DMaxwell02 I just added an EnhancedQuickStart sample that uses MSAL.NET for authentication instead of ADAL.
https://github.com/microsoft/PowerApps-Samples/tree/master/cds/webapi/C#/EnhancedQuickStart

**Comment by DMaxwell02** [comment]
> @DMaxwell02 I just added an EnhancedQuickStart sample that uses MSAL.NET for authentication instead of ADAL. https://github.com/microsoft/PowerApps-Samples/tree/master/cds/webapi/C#/EnhancedQuickStart

I think the C# portion makes the link not open (404 error). Try this one...

https://github.com/microsoft/PowerApps-Samples/tree/master/cds/webapi/C%23/QuickStart/QuickStartMSAL


Anyway, thank you, @phecke. Much appreciated. I will try out soon.
