### ISSUE TITLE
Specify behavior for Choices data types

### ISSUE THREAD

**Issue by v-carlosper** [MicrosoftDocs/powerapps-docs#2771]
The Special column types section does not specify that the expected behavior for the connector displaying in Power BI both unique value and display value is only for 'Choice' data types.

As it is know is confusing and might imply that the behavior is both for 'Choice' and 'Choices' types, and Product Group confirmed that 'Choices' is not supported.

A change to the documentation or a note should be made to specify only 'Choice' is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e6e30d-4224-459f-8525-08718d6d77e4
* Version Independent ID: fe075fe5-5d2e-7b96-3608-9ad3138380da
* Content: [Create a Power BI report using the Dataverse connector - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector#special-column-types)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@v-carlosper - Thank you for your feedback. The article has been updated to state the choices column types aren't fully supported with the Dataverse connector for Power BI. [Choices](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-powerbi-connector#choices-columns)

Closing issue
