### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by nsaga** [MicrosoftDocs/powerapps-docs#2779]
[Enter feedback here]
Hi, please re-check the article written. In place of "a" its written "an" and in place of "an" its written "a".
Doesn't look nice on prestigious platform of microsoft.
regards,
Narinder Sagar
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd70bb46-8651-365b-7a25-215b921f55b6
* Version Independent ID: f628a69a-04c8-901a-832f-b867aff68603
* Content: [Manage SharePoint documents - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/manage-sharepoint-documents#step-5-create-appropriate-table-permission-and-assign-it-to-the-appropriate-web-role)
* Content Source: [powerapps-docs/maker/portals/manage-sharepoint-documents.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/manage-sharepoint-documents.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by tapanm-MSFT** [comment]
Thank you for the feedback. Documentation has been updated.
