### ISSUE TITLE
Sample XML is truncated 

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerapps-docs#278]
Looks like the XML sample presented on this page has been truncated - there is a piece missing between

"Alias": {"$a": "name"

and 

&lt;/PowerBIFilter&gt;

(that remaining XML seems to be presented correctly in the "filter" sample)
	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715bc26c-2ccd-a040-3c96-d73cde4b982b
* Version Independent ID: c793e872-29e4-2e04-b9f4-973c01d4a123
* Content: [Embed a Power BI report in a model-driven system form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embed-powerbi-report-in-system-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md)
* Service: **crm-online**
* GitHub Login: @prsi-msft
* Microsoft Alias: **prsi**

**Comment by KumarVivek** [comment]
@prsi-msft Can you please review this feedback.

**Comment by Mattp123** [comment]
XML sample syntax appears to be fixed. Closing issue.
