### ISSUE TITLE
"Additional licensing requirements might be required to enable this feature"

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/powerapps-docs#2780]
What additional licenses would be required for this feature?  Anything that would cover a premium connector?  Or a license that would cover Dataverse?

**Comment by Nkrb** [comment]
Thanks for contacting us. Can you point us to the doc page you're referring. It helps us assign the issue to the correct writer.

**Comment by samadane** [comment]
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/geospatial-overview

**Comment by iaanw** [comment]
I'm checking with our engineering team now and will let you know.

**Comment by iaanw** [comment]
Hi @samadane I received this reply:

>Geospatial components are premium and they consume [Power Platform requests](https://docs.microsoft.com/power-platform/admin/api-request-limits-allocations). Any license that enables end-users to use an app that is designated as premium will work for the geospatial components.

I'll work on updating the documentation to call this out as a requirement and will reply here when it's published.
Thanks for your feedback!
