### ISSUE TITLE
Missing Pre-Requisites

### ISSUE THREAD

**Issue by jianyu-li** [MicrosoftDocs/powerapps-docs#2781]
The pre-requisites section is no longer on this page. How do I know what fields/tables I need in SharePoint to be able to use this template as my own?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Set up the Expense Report sample app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @norliu
* Microsoft Alias: **norliu**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Downloadable package for sample apps aren't available anymore, and you can use the sample app as available from the product experience. To create the schema, you can review the sample app structure and recreate a similar schema. For specific business needs, you can also try creating and customizing your own app with the inspiration from the sample apps.
