### ISSUE TITLE
Screenshot of table wrong name

### ISSUE THREAD

**Issue by SteveoMS** [MicrosoftDocs/powerapps-docs#2782]
The screenshot of the table to create says "Stores" but the text says "store" . Ypu need to bold the word store in the line with create and fix the screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006ea3e1-916f-fd30-90f1-7787c1459c37
* Version Independent ID: e09165f1-60a8-c746-a0de-3a9d0c6ea0bb
* Content: [Add hierarchy to inspection location - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/inspections-hierarchy-locations)
* Content Source: [powerapps-docs/teams/inspections-hierarchy-locations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/inspections-hierarchy-locations.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. When adding rows to the table, the plural table name shows up. When creating table named "Store", the plural name by default is "Stores". Hence, the image shows "Stores" whereas the table name (singular) is "Store". The table name is updated in double quotes inline.
