### ISSUE TITLE
Error in replacement code 2522720

### ISSUE THREAD

**Issue by Sirgoodman1234** [MicrosoftDocs/powerapps-docs#2785]
The lblInspection_SubmissionDetails replacement code for the Text property has an extra '/ ' causing an error when pasted in the PowerApp.

Line 20

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006ea3e1-916f-fd30-90f1-7787c1459c37
* Version Independent ID: e09165f1-60a8-c746-a0de-3a9d0c6ea0bb
* Content: [Add hierarchy to inspection location - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/inspections-hierarchy-locations)
* Content Source: [powerapps-docs/teams/inspections-hierarchy-locations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/inspections-hierarchy-locations.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed and will reflect the changes soon.
