### ISSUE TITLE
OnVisible not OnSelect 2522723

### ISSUE THREAD

**Issue by Sirgoodman1234** [MicrosoftDocs/powerapps-docs#2786]
Step 17 says "Select the OnSelect" property. Should be OnVisible. Look as the screenshot "ble" shows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006ea3e1-916f-fd30-90f1-7787c1459c37
* Version Independent ID: e09165f1-60a8-c746-a0de-3a9d0c6ea0bb
* Content: [Add hierarchy to inspection location - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/inspections-hierarchy-locations)
* Content Source: [powerapps-docs/teams/inspections-hierarchy-locations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/inspections-hierarchy-locations.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been fixed and will reflect the changes soon.
