### ISSUE TITLE
Please review example code

### ISSUE THREAD

**Issue by carlytos02** [MicrosoftDocs/powerapps-docs#2787]
Please review example code. I'm pretty sure that using external assembies in plugin code (e.g. Dropbox api) is not supported (i'm not sure that async/await pattern should be used). Even if you are writing example code, it should be compliant with microsoft development guidelines (referring dataverse development of course); just think about a junior developer that is reading this code, the first thing will be copy and paste of wrong code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda6e686-e6e6-0a11-43de-69364f91a21f
* Version Independent ID: b07feacf-a474-1ae8-2c88-02de535813ef
* Content: [Sample: Generic virtual table data provider plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/sample-generic-ve-plugin)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/sample-generic-ve-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/sample-generic-ve-plugin.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by Sunil-Garg** [comment]
@***@***.***> can you pls have a look?

Thanks
________________________________

**Comment by phecke** [comment]
@carlytos02 Thanks for the feedback. Yes, use of ILMERGE is not supported. The author @Sunil-Garg has been notified and will hopefully update the sample once a mechanism for dependent plug-in assemblies becomes available.
