### ISSUE TITLE
Name is use defined now

### ISSUE THREAD

**Issue by leo9912** [MicrosoftDocs/powerapps-docs#279]
As per today this documentation is no longer accurate. I have to fill in name and display name, but not plural display name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11bacb37-4743-1d0e-d13e-1d9b656c661f
* Version Independent ID: 7b4d6192-4282-c5c1-01a2-a3ba065ed6e6
* Content: [Create a custom entity - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-create-entity)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-create-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-create-entity.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by leo9912** [comment]
Correction to my previous comment. It seems depends on the environment. After creating new environment this documentation reflects what user experience.

**Comment by KumarVivek** [comment]
@leo9912 Thanks for taking time to provide feedback. Closing this issue now.
