### ISSUE TITLE
Error in Adaptive Code sample

### ISSUE THREAD

**Issue by SteveoMS** [MicrosoftDocs/powerapps-docs#2791]
Need to remove the "\" in front of "\$schema:" line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc8149b-7f53-cf3f-52ab-755fb7c6aceb
* Version Independent ID: e3bb4c6d-4439-56b6-708b-22d77a7b6450
* Content: [Update inspection notification to use an adaptive card - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/inspection-adaptive-card)
* Content Source: [powerapps-docs/teams/inspection-adaptive-card.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/inspection-adaptive-card.md)
* Service: **powerapps**
* GitHub Login: @sbahl10
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been updated and will reflect the changes soon.
