### ISSUE TITLE
Does Microsoft support Sample Apps in the Microsoft Teams store?

### ISSUE THREAD

**Issue by aliyoussefi** [MicrosoftDocs/powerapps-docs#2794]
The documentation is not clear if the Sample Apps located with the Microsoft Teams store are officially supported. What is the guidance to open a support case for any bugs found within the Sample Apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f425241-9d04-b15e-769b-60f6d2a016c9
* Version Independent ID: 92765336-4de4-51ef-65cd-2196709b6766
* Content: [Frequently Asked Questions (FAQs) and answers when using sample apps from Teams store - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/sample-apps-faqs)
* Content Source: [powerapps-docs/teams/sample-apps-faqs.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/sample-apps-faqs.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @navjotm
* Microsoft Alias: **namarwah**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The generally available sample apps in Microsoft Teams store are supported whereas the apps with "Preview" disclaimers are subject to preview and experimental feature terms.
