### ISSUE TITLE
環境変数の条件に関する表記が英語版と異なる。

### ISSUE THREAD

**Issue by yan0020** [MicrosoftDocs/powerapps-docs#2799]
[フィードバックをこちらに入力してください]
環境変数の上限数について英語版との表示内容が異なるようです。
実際には日本語版で表示されている50個以上の環境変数を作成できました。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ba670cf8-5810-79c4-7a2a-101099ffe1d7
* Version Independent ID: 69b7e1fb-9f56-8c07-b1d5-8480fe6d8e1a
* Content: [ソリューションで環境変数を使用する - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/data-platform/environmentvariables#is-there-a-limit-to-the-number-of-environment-variables-i-can-have)
* Content Source: [powerapps-docs/maker/data-platform/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/EnvironmentVariables.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by jowilco** [comment]
@yan0020 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
