### ISSUE TITLE
Key properties - editing error

### ISSUE THREAD

**Issue by mscottsewell** [MicrosoftDocs/powerapps-docs#28]
"Items" is listed 2x - but 'Value' isn't described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57642536-b4f2-4a73-4fbf-a6e084aaf4bd
* Version Independent ID: 946306ff-1045-052e-6ec0-5df3cef4a236
* Content: [Drop down control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-drop-down#key-properties)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-drop-down.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-drop-down.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
@fikaradz I've removed the duplicate entry, but can you provide an entry for Value? Thanks!

**Comment by fikaradz** [comment]
Added description for Value and a better explanation for Items.

**Comment by AFTOwen** [comment]
This change is now live. Thanks @mscottsewell for your feedback!

cc: @fikaradz
