### ISSUE TITLE
Using this command doesn't work on my environment [offline]

### ISSUE THREAD

**Issue by jgonzalezbgc** [MicrosoftDocs/powerapps-docs#280]
Using this steps: Load tweets into a LocalTweets collection on app startup, it tells me the LoadData function has some invalid arguments. Any thoughts as to what else needs to be setup? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6333e478-d29c-d3d9-4ad7-6eb973759fca
* Version Independent ID: ef01a732-ad9a-dc7c-1ce3-78cfaa4432a4
* Content: [Develop offline-capable canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/offline-apps#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/offline-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/offline-apps.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by dibyanugraha** [comment]
Agreed. This tutorial is borked, it needs to be updated. It's quite frustrating finding official resource that doesn't work.

**Comment by gregli-msft** [comment]
@jgonzalezbgc, @dibyanugraha thanks for letting us know, there were a couple of issues with this article that we have now corrected.  It should work properly for you now, please let us know if you run into any further issues.

@AFTOwen, please close this issue.
