### ISSUE TITLE
Invalid link on page

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#2803]
The link titled 'data source that supports delegation for these functions' returns a 404 Page not found error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e43da3bc-6516-181b-5401-4468078aded2
* Version Independent ID: 63a5f459-e8a3-2aca-9c1f-24de6ea4aa9b
* Content: [Average, Max, Min, StdevP, Sum, and VarP functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-aggregates)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-aggregates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-aggregates.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Link is working as expected. Please check again.
