### ISSUE TITLE
FetchXML schema documentation needs more details

### ISSUE THREAD

**Issue by vuciv** [MicrosoftDocs/powerapps-docs#2804]
[The FetchXML schema](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/fetchxml-schema.md) does a good job of telling me each element I can expect to see in a FetchXML query, but it does not explain to me what I can expect those elements to be used for.

### Example:

I have been trying to figure out what the "uitype" will imply from the following code in the schema:

```xml
        <xs:element name="value" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="uiname" type="xs:string" />
                <xs:attribute name="uitype" type="xs:string" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
```

But there is no way I would learn that from the documentation. Comments like this would save me a lot of time, and help me understand FetchXML better:

```xml
        <xs:element name="value" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="uiname" type="xs:string" /> <!-- the display name of the referenced value's record -->
                <xs:attribute name="uitype" type="xs:string" /> <!-- the logical name of the referenced value's entity -->
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
```

I'm sure more expansive documentation will make working with FetchXML a better experience for everyone.

**Comment by phecke** [comment]
@vuciv Thanks for the feedback.
