### ISSUE TITLE
Misspelling on the page--Under recommended content one of the items shows "Learn how to sse" instead of use

### ISSUE THREAD

**Issue by BGarnish2** [MicrosoftDocs/powerapps-docs#2806]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c172d38-8a93-071a-b3e9-ebc81e0523df
* Version Independent ID: 45bff0b2-f7de-710b-b9a0-9a0dc335f292
* Content: [Apply custom business logic with business rules and flows in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/guide-staff-through-common-tasks-processes)
* Content Source: [powerapps-docs/maker/model-driven-apps/guide-staff-through-common-tasks-processes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/guide-staff-through-common-tasks-processes.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@BGarnish2 - The "Recommended content" section is automatically generated via an Azure AI service. Subsequently, I can't find the article that you reference in this issue. Reopen this issue if you can send me a direct link to the Docs article that contains the mispelling.

Closing issue.
