### ISSUE TITLE
Step 5.1: Map tables - Load to Existing Table requires Key Configuration 

### ISSUE THREAD

**Issue by virakones** [MicrosoftDocs/powerapps-docs#2808]
Issue with section Step 5.1: Map tables not as clear as steps outlined.

![image](https://user-images.githubusercontent.com/92550072/137393967-99164bb5-b913-40b8-b242-ca94ee8df99f.png)

Choosing "Delete rows that no longer exist in the query output" prompts with "Please modify the definition of the table to include a key, or disable "Delete rows that no longer exist in the query output" option." but little detail on setting up a key configuration if none are available in the source dataverse table. Stuck at "none". Unable to create a key out of the unique id in the key tab in dataverse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2f8a4d-5b76-0fed-c0cb-6e2f06a4240e
* Version Independent ID: 6b6cf6ec-87c8-f109-98ce-9181cbfb736e
* Content: [Migrate data between Microsoft Dataverse environments using the dataflows OData connector - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-odata-dataflows-migration)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-odata-dataflows-migration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-odata-dataflows-migration.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by denisem-msft** [comment]
@virakones can you please provide more specific repro steps? I am not getting the error you are describing. Does this happen when you check the checkbox for "Delete rows that no longer exist in the query", when you choose the entity, or another step?

**Comment by denisem-msft** [comment]
@virakones Thanks for your feedback!

Please see documentation on defining alternate keys here: https://docs.microsoft.com/en-us/powerapps/maker/data-platform/define-alternate-keys-portal

I have submitted a change to the documentation to provide this guidance.

Please let me know if that doesn't solve your issue.
