### ISSUE TITLE
Can we use Navigate() in components?

### ISSUE THREAD

**Issue by Zoltango** [MicrosoftDocs/powerapps-docs#281]
Is there a way to use Navigate() function to create a navbar component? For example I added Home icon's onSelect: Navigate(HomeScreen,None) but it drops an error message that target "Name is not valid"
Of course Home screen exists in my sample app. 
Thank you,
Zoltan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93230c47-e5a5-15ad-9320-2f9671fdebb5
* Version Independent ID: dc5050e4-7243-b861-4c97-3bfb0165ade5
* Content: [Create a component for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-component#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/create-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-component.md)
* Service: **powerapps**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by yifwang** [comment]
> Is there a way to use Navigate() function to create a navbar component? For example I added Home icon's onSelect: Navigate(HomeScreen,None) but it drops an error message that target "Name is not valid"
> Of course Home screen exists in my sample app.
> Thank you,
> Zoltan
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 93230c47-e5a5-15ad-9320-2f9671fdebb5
> * Version Independent ID: dc5050e4-7243-b861-4c97-3bfb0165ade5
> * Content: [Create a component for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-component#feedback)
> * Content Source: [powerapps-docs/maker/canvas-apps/create-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-component.md)
> * Service: **powerapps**
> * GitHub Login: @yifwang
> * Microsoft Alias: **yifwang**

Hi @Zoltango , component is self-contented, meaning component should work without depending on controls outside of the component. So refering a screen outside of the component is not recommanded, to do this, you will create a "Screen" type input property. This way, this screen property can be used to navigate to diffferent screens and it is generic even in different apps.

**Comment by AFTOwen** [comment]
Thanks, @Zoltango, for the feedback. Closing this issue.

**Comment by plmcgrn** [comment]
@yifwang 

Reading this now, and I'm not following the practical implementation of your reply.  Components would seem to be the ideal way to implement navigation, so that you don't have to re-create the same navigation parts on every screen of the app.  If Navigate() can't be used, that basically means that this feature isn't compatible with building common interface navigation pieces, correct?  

If I'm wrong, can you provide a practical example?  For instance, if I have an app with 4 screens, and I want to build a navigation bar with icons that can navigate to each of those screens, and I want to put that navigation bar on every screen, how is that achieved with this feature?

**Comment by PavlosVas** [comment]
Absolutely agree with @plmcgrn - the whole purpose of the components is to reduce time writing same navigation formulas and increase consistency. I hope this is fixed/added soon

**Comment by yifwang** [comment]
@plmcgrn @PavlosVas Building a common app header with component, the navigate button will be: `Navigate(Parent.CustomProperty, None)` where Parent.CustomProperty is a screen type input property. With this, you can input which screen to navigate to for each component instance. 
Here is an [example of navigate menu](https://powerusers.microsoft.com/t5/Canvas-Apps-Components-Samples/Header-amp-Menu-Component/td-p/328654) that you can directly import to try out in your app!

**Comment by plmcgrn** [comment]
@yifwang , the example you linked to doesn't implement the strategy using ```Navigate(Parent.CustomProperty, None)``` that you describe.  It uses a Table custom Input Property on the Component and a collection generated on app OnStart, with a nested LookUp formula to derive the screen to navigate to based on the Value of the component item (button text property).  I couldn't get the navigation method they use to work after importing that example.

I'll note, I'm already using a gallery + collection to manage the items for my navigation menu, but at this point, I'm having to clone that entire setup to every screen.  So I know it works outside the usage of a Component implementation, but I'm still looking for a functional example of using a component for a navigation menu.

If you could provide an example using the strategy you're noting above, that'd be much appreciated.

**Comment by plmcgrn** [comment]
Actually, got it working.

In the linked example, they set the OnSelect property of the button in the gallery to ```Navigate(LookUp(colScreens,ThisItem.Value = displayName, screen))```

I had better success by using ```Navigate(LookUp(colScreens, Display = galHeader.Selected.Value, Screen))```.

I'm not sure why that was, but I finally got success.

**Comment by sahu0365** [comment]
Navigate([@screenname],cover)
