### ISSUE TITLE
Broken link in the security section of environmental variables overview

### ISSUE THREAD

**Issue by Sealjay** [MicrosoftDocs/powerapps-docs#2811]
In the [security](https://docs.microsoft.com/en-gb/powerapps/maker/data-platform/EnvironmentVariables#security) heading under Environment variables overview, there is a broken link.

The text "user or team owned" links out to page that no longer exists - [https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/types-of-tables](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/types-of-tables)

>The environmentvariabledefinition table is **user or team owned**. When you create an application that uses environment variables, be sure to assign users the appropriate level of privilege to this table. Permission to the environmentvariablevalue table is inherited from the parent environmentvariabledefinition table and therefore does not require separate privileges. More information: Security in Dataverse.

![image](https://user-images.githubusercontent.com/19361656/137486710-8d75f68d-edaa-4782-a1fc-6bf26ac9bf4a.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba670cf8-5810-79c4-7a2a-101099ffe1d7
* Version Independent ID: 69b7e1fb-9f56-8c07-b1d5-8480fe6d8e1a
* Content: [Use environment variables in solutions - Power Apps](https://docs.microsoft.com/en-gb/powerapps/maker/data-platform/EnvironmentVariables#security)
* Content Source: [powerapps-docs/maker/data-platform/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/EnvironmentVariables.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
@Sealjay - The link appears to work now. 

Closing issue.
