### ISSUE TITLE
File attribute type not available on CoreAssemblies below 9.0.2.42

### ISSUE THREAD

**Issue by sucarnei** [MicrosoftDocs/powerapps-docs#2816]
Looking to the documentation it's saying that "File columns are supported in SdkClientVersion 9.0.45.329 or greater and Web API version 9.1 or greater.", however if we select CrmSdk.CoreAssemblies version 9.0.2.34 we get an exception "This attribute:xxx of type:File introduced in version:9.1.0.0 is not available for this client version:9.0.46.3545.".

This does not happen on CrmSdk.CoreAssemblies version 9.0.2.42.

Could you please update the documentation to state this version 9.2.46.5279 instead of 9.0.45.329?

A simple way to reproduce this is using the below sample code with CoreAssemblies version 9.0.2.34 or below:
RetrieveAttributeRequest attributeRequest = new RetrieveAttributeRequest
{
    EntityLogicalName = Account.EntityLogicalName,
    LogicalName = "new_file",
    RetrieveAsIfPublished = false
};
RetrieveAttributeResponse attributeResponse = (RetrieveAttributeResponse)service.Execute(attributeRequest);

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/file-attributes#example-net-c-code-for-download-with-chunking)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@sucarnei  I am seeing that the File attribute is supported in CoreAssemblies v9.0.2.34.

When using the JetBrains dotPeek disassembler, I see Microsoft.Xrm.Sdk.Metadata.FileAttributeMetadata:

![image](https://user-images.githubusercontent.com/10079935/139757308-be6a4d07-a761-4c87-b7d9-6d8a33d22efa.png)

So it sounds like a discrepancy between the CoreAssemblies package and the web service, which is a support issue. Feel free to log a bug with Support. I will contact the Project Manager and let him know of your issue.

I myself have used the File attribute feature with 9.0,2.34 in the past with no problems.
