### ISSUE TITLE
Solution is empty when importing into environment

### ISSUE THREAD

**Issue by BennyHoang** [MicrosoftDocs/powerapps-docs#2817]
Hi,
After going through all [steps with](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript) building the solution and everything, the solution seems empty when i import it into the environment. 

![image](https://user-images.githubusercontent.com/9945918/137972200-983c743a-458f-4c45-9830-1a7c99912aaa.png)

I have retried the msbuild step multiple times, but looks like it is still empty. 

![image](https://user-images.githubusercontent.com/9945918/137972610-e2cc3634-8250-44a8-97d1-0c4d44ba8e22.png)

**Comment by JimDaly** [comment]
Opportunity to improve instructions

**Comment by JimDaly** [comment]
The instructions were re-written since this issue was opened. You shouldn't have this problem any longer.
