### ISSUE TITLE
 OnStart function not visable from Login Screen

### ISSUE THREAD

**Issue by JDSFSA** [MicrosoftDocs/powerapps-docs#282]
Hi was having some trouble in that I cant see the OnStart function on the Login screen, however when I clicked on the app above login screen I could see and amend the list of admin users.

Looks a great app to hit the ground running.

John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @mr-dang-msft
* Microsoft Alias: **brdang**

**Comment by yijw2017** [comment]
Hi John
    Thank you for reporting this issue. We found that there's error in the doc. Instead of saying "Select the **LoginScreen**", it should say "Select the **App**", then you will see OnStart. We are working on updating the doc and the screenshot accordingly.


Best,
Yijun

**Comment by Naveed151214** [comment]
Hello, 
This is really a perfect application just tried works perfectly, only want to ask one question is it possible when a ticket is created and assigned to a user can it be displayed in that user when he/she starts using it.
Like a user login as a helpdesk user and creates a ticket then administrator assigns that ticket to staff to work on it that users should receive notification in application that he has assigned task.

Kind Regards,
Naveed.

**Comment by yijw2017** [comment]
Hi Naveed,
    If you want to send the assignee a notification upon assignment of a ticket, you can add a formula to the Create and Update buttons to let it send out email to the assignee using the existing Office365User connector (https://docs.microsoft.com/en-us/connectors/office365users/#user).

Thanks,
Yijun

**Comment by Naveed151214** [comment]
Hi Yijun,

Thanks for the response, to send a notification to the assignee is already there, what actually i am looking for let me explain:

Once a user creates a ticket and administrator assigns to a staff, the assign staff should be able to see the assigned ticket in his user, like we shared the application to the user he/she installs the power app in the device and provide office365 credentials to login to start using the application once they go ticket view screen they should see there assigned tickets but in the current scenario it's not there. Please see below the scenario:

User A creates ticket
Administrator assigns the ticket to ABCmail@office365.com
ABCmail@office365.com user login in powerapp by providing office365 account ticket should be available as assigned in second step by administrator.

Any help on this will be highly appreciated.
Thanks in advance for your help.
Kind Regards,
Naveed.

**Comment by yijw2017** [comment]
Hi Naveed,
    Did you have a shared SharePoint list or common storage for those tickets? The information from 1 person to another needs to be sync'd from a common data source somehow based on your scenario.

Thanks,
Yijun

**Comment by Naveed151214** [comment]
Hi Yijun,

It's a shared point list.

Kind Regards,
Naveed.

**Comment by yijw2017** [comment]
Hi Naveed,
    In "MyTicketScreen" -> "MyTicketsScreenGallery", the formula for Items is:

   If(isAdmin,Sort(TicketList,Id,Descending),Sort(Filter(TicketList,Author = MyProfile.Mail ),Id,Descending))

   where "TicketList" is a local Collection

   And based on the app's OnStart rule:

   ClearCollect(TicketList,{Id:1,Title:"Fix Mouse",Description:"That is my cat!!!",Category:"Laptop/PC equipment issue",PercentComplete:"0.9",Priority:"HIGH",AssignedTO:"THOMAS ANDERSEN",TaskStatus:"COMPLETED",Author:"ScottK@contoso.com",Editor:"Scott Konersmann",Created:"2/8/2018 3:29 PM",Modified:"2/5/2018 3:29 PM"},{Id:2,Title:"Replace keyboard", Description:"Please do it ASAP",Category:"Laptop/PC equipment issue",PercentComplete:"0.8",Priority:"LOW",AssignedTO:"YVONNE MCKAY",TaskStatus:"IN PROGRESS",Author:"PATRICK SANDS",Editor:"THOMAS ANDERSEN",Created:"2/5/2018 3:29 PM",Modified:"2/5/2018 3:29 PM"});

    Have you made the TicketList to get the data from your SharePoint list where the tickets information are stored, instead of using the hard-coded list from the sample app itself?

Thanks,
Yijun

**Comment by Naveed151214** [comment]
Hi Yijun,

Yes the ticket list is getting populated from the share point list, I didn't change anything in the code yet, trying to understand in which line of code I should make the changes so that the assigned staff should only be able to see his/her tickets only.

Thanks 
Naveed

**Comment by yijw2017** [comment]
Hi Naveed,
    You can change the code in the OnStart to have "TicketList" to get records from SharePoint list directly:

    ClearCollect(TicketList, _**"here are records from your SharePoint list"**_)


    Here is the doc for using ClearCollect: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-clear-collect-clearcollect

Thanks,
Yijun

**Comment by Naveed151214** [comment]
Hi Yijun,

This is the example to amend the record and update it, the records are already coming when I assign them as administrator I think I should design one more screen for the normal users to see there assigned tickets because on current scenarios only administrator can see the tickets and also for all users there is no segregation between the users. Please advise.

Thanks,
Naveed

**Comment by yijw2017** [comment]
Hi Naveed,

"MyTicketScreen" -> "MyTicketScreenGallery" has an explicit rule:

    If(isAdmin,Sort(TicketList,Id,Descending),Sort(Filter(TicketList,Author = MyProfile.Mail ),Id,Descending))

It means if the user is not an admin, the user will only see his/her own ticket.

Thanks,
Yijun

**Comment by Naveed151214** [comment]
Hi Yijun,

Thanks for the quick responses, let me work on this, I will get back with update.

Thanks for your time and great help.

Naveed.

**Comment by yijw2017** [comment]
Just did a quick experiement on the Items formula for "MyTicketScreenGallery"

If(isAdmin,Sort(TicketList,Id,Descending),Sort(Filter(TicketList,AssignedTO = MyProfile.DisplayName ),Id,Descending))

Hope it could help you trouble shoot. :)

**Comment by Naveed151214** [comment]
Hi Yijun,

Currently, this is the formula on "MyTicketScreenGallery"

If(isAdmin,Sort(AllTickets,Created,Descending),Sort(Filter(AllTickets,Author.Email = MyProfile.Mail || Author.Claims = MyProfile.UserPrincipalName ),Created,Descending))

Could you please guide me which changes need to be done, because when i make changes i am getting errors.

Thanks

**Comment by yijw2017** [comment]
When I was playing with the sample, I realize the ticket should show when the name is matching the AssignedTo, instead of the Author.

I am not sure how your schema is on the SPO list, but I only changed from

Sort(Filter(TicketList,Author = MyProfile.Mail )

to

Sort(Filter(TicketList,AssignedTO = MyProfile.DisplayName )

in the formula

**Comment by Naveed151214** [comment]
Hi Yijun,

Thanks for the great help you out me in right direction to fix formula i have figured it out after modifying the formula as below.

If(isAdmin,Sort(AllTickets,Created,Descending),Sort(Filter(AllTickets,AssignedTo.Email = MyProfile.Mail || Author.Claims = MyProfile.UserPrincipalName ),Created,Descending))

Once again thanks for your valuable time and help.

Kind Regards,
Naveed

**Comment by yijw2017** [comment]
Hi Naveed,
    Great to hear your problem is solved! 

Cheers,
Yijun

**Comment by Naveed151214** [comment]
One more thing, on the "EditTicketFormScreen" can we give right to a user who has assigned for the ticket to update the status field and take back ticket deletion right ?

Thanks,
Naveed

**Comment by Naveed151214** [comment]
I have figured out as well the deletion as well just only need guide to give non administrator user right for updating the status and percentage.

Thanks,
Naveed

**Comment by abiodun-ajumobi** [comment]
Hi I am having difficulty on the sample help desk I got most of it working but there are key areas that I need help with 

1 when I create a help desk ticket on the app it doesn't stay on the app when I log out

2 I have two Ipads to test the app on and when I create a ticket as a staff on a staff ipad on the admin Ipad I can't see the ticket (although it has successfully emailed me the ticket)

3 the sharepoint is not being used as a collection for the ticketlist how do I do that?

**Comment by tapanm-MSFT** [comment]
@JDSFSA thank you for your feedback, the doc has been updated. 

@abiodun-ajumobi Please contact [support team](https://powerapps.microsoft.com/en-us/support/pro/) for help with resolving environmental issues.

**Comment by shebeerahammed123** [comment]
> ClearCollect(TicketList, _**"here are records from your SharePoint list"**_)

how to add the sharepoint list?
