### ISSUE TITLE
Sentence makes no sense

### ISSUE THREAD

**Issue by Sirgoodman1234** [MicrosoftDocs/powerapps-docs#2821]
That contains components you have already customized, your customizations will be overwritten by the customizations in the imported unmanaged solution. You can’t undo this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a00b4a6-c147-cffa-92c9-5cb183c4ea67
* Version Independent ID: 83d7d42c-71f3-1138-318f-5bd252a2ab3b
* Content: [Import solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/import-update-export-solutions)
* Content Source: [powerapps-docs/maker/data-platform/import-update-export-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/import-update-export-solutions.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Sirgoodman1234 - The sentence in the article has been revised to make it more clear as follows: 

When you import an unmanaged solution:

That contains customized components, the existing customizations to the component will be overwritten after the unmanaged solution import. You can’t undo this.

Closing issue.
