### ISSUE TITLE
Power Appsのテンプレート「Site Inspection」を立ち上げるとエラーが出る、対処方法のご提案

### ISSUE THREAD

**Issue by Hichiriki** [MicrosoftDocs/powerapps-docs#2825]
Power Appsのテンプレート「Site Inspection」を立ち上げると5ケ所エラーが出ます。以下の対処方法をご提案いたします。

1. 名前が無効です。この識別子は認識されません。Heading1_2.Text = Title           対処方法：ThisItem.Titleに変更
2. 名前が無効です。この識別子は認識されません。TextBox6_14.Text = SubTitle           対処方法：ThisItem.SubTitle に変更
3～5. 名前が無効です。この識別子は認識されません。TextBox3_6.Text = Address&" "&City&" "&State&" "&Zip           対処方法：ThisItem.Address&" "&ThisItem.City&" "&State&" "&ThisItem.Zip に変更

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cc54a953-9f26-f4e8-f892-2d0513a42642
* Version Independent ID: f1001ac6-104a-5029-bf7c-8ae7da1ee4b4
* Content: [テンプレートからキャンバス アプリを作成する - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/get-started-test-drive)
* Content Source: [powerapps-docs/maker/canvas-apps/get-started-test-drive.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/get-started-test-drive.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for submitting the issue. This problem may happen if the control names have been changed. Formula might need to be updated with changed control names.

If the issue persists, please reach out with [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with the issue investigation.

Bing translated:

問題を送信していただきありがとうございます。この問題は、コントロール名が変更されている場合に発生することがあります。変更されたコントロール名で数式を更新する必要がある場合があります。

問題が解決しない場合は、問題の調査に関するヘルプを得るために[サポートチケット](https://docs.microsoft.com/power-platform/admin/get-help-support)を参照してください。
