### ISSUE TITLE
Define if calendar opens as day, week or month by default

### ISSUE THREAD

**Issue by Niels-SL** [MicrosoftDocs/powerapps-docs#2828]
Is there any way to configure if the calendar should open as daily, weekly, or monthly by default? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b9052f-294a-61ec-9b66-79361823db04
* Version Independent ID: 016d8138-8d52-c8fd-5412-a1a198ecedcd
* Content: [Add the calendar control to tables in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-calendar-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-calendar-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/add-calendar-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@Niels-SL - Thanks for contacting us. Yes, we can configure the default view (month, day, or week) for the calendar. The details are at: [Activities tab options](https://docs.microsoft.com/en-us/powerapps/user/set-personal-options#activities-tab-options)

The link to the above topic is mentioned in this topic: [View the calendar by Day, Week, or Month](https://docs.microsoft.com/en-us/powerapps/user/calendar-view#view-the-calendar-by-day-week-or-month)

Closing this issue.
