### ISSUE TITLE
Missing size information

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerapps-docs#2829]
One should not have to watch a video (and some people cannot because of disabilities) to know essential info about datatypes such as their default and maximum length. Please elaborate in the text of this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8f3598c-cd0e-2cd8-fa6b-5663f63c36bf
* Version Independent ID: 656dca2a-e65d-fdb9-545e-b73d906ce4f1
* Content: [Column data types in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/types-of-fields)
* Content Source: [powerapps-docs/maker/data-platform/types-of-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@otravers - The article has been updated recently so that the data types where it makes sense to have a max value (e.g. Text, File, Image, etc) have that information.
Closing issue.
