### ISSUE TITLE
AddColumns Not working in latest version of powerapps

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/powerapps-docs#283]
Please fix documentation to show how to properly use it. Or fix it so it operates according to documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e1f6e9-01be-ec20-e777-643874d92c2a
* Version Independent ID: 6b83ce58-9ea8-5f36-d518-6ef86c07d206
* Content: [AddColumns, DropColumns, RenameColumns, and ShowColumns functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-table-shaping)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-table-shaping.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-table-shaping.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by JohnGGeo** [comment]
![image](https://user-images.githubusercontent.com/7240495/54279817-fbcb6300-4563-11e9-963a-cbef3f64c364.png)
Here's a picture of the function. AddColumns doesn't work in adding the column I labeled TestColumn.
I use the ForAll loop as a workaround to fix this issue.

**Comment by gregli-msft** [comment]
Hi John.  AddColumns does not add a column to a table or collection.  Tables in PowerApps are values just like a number or text string and can be modified as they flow through a function.  As the docs state "The functions that this topic describes don't modify the original table. Instead, they take that table as an argument and return a new table with a transform applied. See working with tables for more details."  

The ForAll you used isn't bad.  You could also use AddColumns with Collect:
```
Collect( 'Sandbox Building', AddColumns( OpenIncidents, "Distance", (IncidentLat-Lat)+(IncidentLon-Lon) ) )
```

**Comment by AFTOwen** [comment]
Tagging @JohnGGeo for visibility. If @gregli-msft answered your question, please let us know so that we can close the issue. Cheers.
