### ISSUE TITLE
Link to video is broken

### ISSUE THREAD

**Issue by silveyjoy** [MicrosoftDocs/powerapps-docs#2830]
At the top of the page, there is a link with the text "Video: Rollup and Calculated columns in Microsoft Dataverse" that points to YouTube. However, YouTube states that the video is unavailable because it is private.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a7083d9-4e5d-be28-f943-699e40d4fff3
* Version Independent ID: 2ca8c470-6883-bc76-5793-04e2fc5c0024
* Content: [Calculated and rollup columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/calculated-rollup-attributes#feedback)
* Content Source: [powerapps-docs/developer/data-platform/calculated-rollup-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/calculated-rollup-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@silveyjoy  I am looking into it.

**Comment by phecke** [comment]
@silveyjoy Thanks for pointing this out. I removed the video link.
