### ISSUE TITLE
Accessing formParameters passed from openForm

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#2832]
This article is linked to as reference for the `formParameters` parameter of [`Xrm.Navigation.openForm`](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openform), but it doesn't actually say how to access those parameters. These at least appear to be available as `input.data`, but I can't find this documented anywhere.

If `input.data` is supported, I'd be more than happy to create a PR updating the docs :), otherwise, how are parameters accessed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ab1a46-e673-1783-7bc5-09725a878c4a
* Version Independent ID: 3e54ebd6-296b-815a-e502-cc9e19726013
* Content: [Configure a form to accept custom querystring parameters (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/configure-form-accept-custom-querystring-parameters)
* Content Source: [powerapps-docs/developer/model-driven-apps/configure-form-accept-custom-querystring-parameters.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/configure-form-accept-custom-querystring-parameters.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by JimDaly** [comment]
I think this was addressed in [#3453](https://github.com/MicrosoftDocs/powerapps-docs/issues/3453)
No documentation about this because it isn't supported.
