### ISSUE TITLE
CRM SDK Template

### ISSUE THREAD

**Issue by vissund** [MicrosoftDocs/powerapps-docs#2835]
Please provide details how the CRM SDK Templates are installed. 
the one available online in the Market Place supports till VS 2015 only and even CRM older version but not D365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd56d90-c7bc-8bbf-8976-3626aa4b3237
* Version Independent ID: c09870ce-3fc6-9e8a-7158-8d03219ba352
* Content: [Use the XRM tooling common login control in your client applications (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/use-xrm-tooling-common-login-control-client-applications)
* Content Source: [powerapps-docs/developer/data-platform/xrm-tooling/use-xrm-tooling-common-login-control-client-applications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/xrm-tooling/use-xrm-tooling-common-login-control-client-applications.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by phecke** [comment]
@vissund It is my understanding that the VS toolkit and the templates have not been supported for some time. Looks like the documentation needs to be updated.

If you are looking for the Xrm Tooling WPF login control, you can find it in one of our samples: [PowerApps-Samples/cds/Xrm Tooling/Quick start for XRM Tooling API/](https://github.com/microsoft/PowerApps-Samples/tree/master/cds/Xrm%20Tooling/Quick%20start%20for%20XRM%20Tooling%20API/C#)

When you open the VS solution, you will see the LoginWindow folder containing the files you seek. We use that control in many of our other code samples, except with a slight name change to ExampleLoginForm.

https://github.com/microsoft/PowerApps-Samples/tree/master/cds/LoginUX

**Comment by phecke** [comment]
@vissund  Let me know if this unblocks you. Thanks.
