### ISSUE TITLE
Power Apps cache file size

### ISSUE THREAD

**Issue by dnourie13** [MicrosoftDocs/powerapps-docs#2837]
[Enter feedback here]
This article describes the file size for browser data to not exceed 1MB. Is there a nifty way to determine the file size of a collection in a Power Apps application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ae4fe7-8801-18c4-7313-af44ffd22f75
* Version Independent ID: 32e03bf6-cbe4-70c9-7d4f-54cd2efbc583
* Content: [SaveData, LoadData, and ClearData functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-savedata-loaddata)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-savedata-loaddata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-savedata-loaddata.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can try using Monitor, or any other network capture; though the limit only applies to Teams or web browser.
