### ISSUE TITLE
Examples - SIngle String

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#284]
Hi
I think the MID example under Single String is incorrect.
The string is E.E.Cummings so the 5th character is "C" not the 7th.
Regards
Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d39284b0-3bb6-b23f-69c8-35756db56710
* Version Independent ID: a8524259-ff1f-3353-b8f4-497b69c24dc1
* Content: [Left, Mid, and Right functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-left-mid-right)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-left-mid-right.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-left-mid-right.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Hey, @NPrice99! Thanks for the feedback. Each space is also a character. :-)

cc: @gregli-msft
