### ISSUE TITLE
Handling errors Continue On Error Not working

### ISSUE THREAD

**Issue by PandaBoy00** [MicrosoftDocs/powerapps-docs#2843]
There seems to be an error with the doc or maybe it is out of date, but the Handling Error for Batch Operation doesn't work using the syntax defined on the doc.

Try using
`prefer: odata.continue-on-error`
`prefer: odata.continue-on-error=true`
`Prefer: odata.continue-on-error`
`Prefer: odata.continue-on-error=true`

I never tried the syntax from [https://github.com/OData/WebApi/blob/7.1.0/src/Microsoft.AspNet.OData.Shared/Batch/ODataBatchHandler.cs](https://github.com/OData/WebApi/blob/7.1.0/src/Microsoft.AspNet.OData.Shared/Batch/ODataBatchHandler.cs)
```
Prefer: PreferenceContinueOnError
prefer: PreferenceContinueOnError
Prefer: PreferenceContinueOnError=true
prefer: PreferenceContinueOnError=true
```

All in all the `$batch` operation from all of the different prefer header fails on the first request that has an issue.  It is a bug but then the document is also listing / mentioning code that isn't working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db53047-327d-6eec-e6a8-4d9dae98f362
* Version Independent ID: 31b3ebbd-9070-db30-cc4e-cec4b41373b8
* Content: [Execute batch operations using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/execute-batch-operations-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
This is an example of the C# code I used when testing this:

```
                HttpRequestMessage request = new HttpRequestMessage
                {
                    Method = HttpMethod.Post,
                    RequestUri = new Uri(service.BaseAddress + "$batch"),
                    Content = batchContent
                };
                if (continueOnError)
                {
                    request.Headers.Add("Prefer", "odata.continue-on-error");
                }
```

Details on the `Prefer` header from the OData spec: [8.2.8 Header Prefer](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752234)

Also see the section **8.2.8.3 Preference odata.continue-on-error** below it.

Also this example: [Prefer odata.continue-on-error](https://docs.microsoft.com/en-us/odata/webapi/continue-on-error#prefer-odatacontinue-on-error-1)

**Comment by PandaBoy00** [comment]
Hi Jim,

I see what you are referring to and the link that you provided the documents for is in relation to OData Web AP v5.7, OData AspNet WebApi v6 and OData AspNet WebApi v7.

My specific reporting of the issue is in regards to Dataverse and titled "Execute batch operation using the Web API".  The link is Execute batch operations using the Web API (Microsoft Dataverse) - Power Apps | Microsoft Docs<https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/execute-batch-operations-using-web-api#handling-errors> which I'm submitting feedback for and not for OData AspNet WebApi.
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/execute-batch-operations-using-web-api#handling-errors>
Execute batch operations using the Web API (Microsoft Dataverse) - Power Apps | Microsoft Docs<https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/execute-batch-operations-using-web-api#handling-errors>
Note. Batch requests can contain up to 1000 individual requests and cannot contain other batch requests. URLs for GET requests sent with a batch are limited to 32768 characters.
docs.microsoft.com
If you try the header prefer: odata.continue-on-error against the Dataverse Web Api, in my specific case I was calling Dynamics 365 Customer Engagement Web API.  It would fail on the first error and would not continue to process even though I specific the prefer header in my batch request.

Regards,
Kengie

________________________________

**Comment by JimDaly** [comment]
Kengie -
The links I provided were for the OData v4.0 specification. The server-side version should not be relevant.
The header name should be `Prefer` and the value is `odata.continue-on-error`

Are you using on-premises?

**Comment by PandaBoy00** [comment]
Hi Jim,

Nope, we are using Dynamics 365 Online and the version we are using is version 9.2

[cid:c710a540-6c40-4629-84e6-f7fdf9cecec8]

Pretty sure the  odata.continue-on-error doesn't work on the Dataverse / Power Apps.  Tried with several different variations (Camel Case, all lower case, include = true).

The result is no matter what you put in the request, the response would always fail / stop on the first error in the batch and stop processing.  We are also specifying OData-Version and OData-MaxVersion in the headers to 4.0

________________________________

**Comment by JimDaly** [comment]
See attached Response Body.
[continue-on-error-example.txt](https://github.com/MicrosoftDocs/powerapps-docs/files/7457153/continue-on-error-example.txt)

Three accounts were sent in two change sets.
The first one had a name that was too long and resulted in an error. But the second changeset succeeded and the Response returned 200.

Sending the same request without `Prefer : continue-on-error` returned 400.

**Comment by PandaBoy00** [comment]
I think the different with our setup is that we are using a unique constraint on our custom field and we don't get an HTTP 400 but rather we get an HTTP 412 Precondition failed. But we are using the prefer:odata.continue-on-error as mentioned on the Handleing Error link from docs.microsoft.com.  Maybe the processing will only continue on HTTP 400 but not HTTP 412?

Below is our testing trying to use the odata.continue-on-error.

[cid:78844946-735b-4439-911b-e70ad4190bd4]

________________________________

**Comment by PandaBoy00** [comment]
Hi Jim,

I also tried your scenrio of using an OOB field (firstname) for attribute too long and it resulted in the same results.

Test Scenerio:
Header = Prefer: odata.continue-on-error
Header = OData-Version: 4.0
Header = OData-MaxVersion: 4.0

5 POST in a batch.
POST #1 Normal Valid Post
POST #2 Normal Valid Post
POST #3 Invalid Post - firstname is too long
POST #4 Invalid Post - Unique Constraint
POST #5 Normal Valid Post

I also double checked if POST #1 and POST #2 was created or not, but no records were created after the batch operation.

It seems like the Dataverse Web Api is using a different version of OData or there is a bug in our version of the online Dynamics 365.

Here is the response:
--batchresponse_6cbc8fc1-8988-4049-8cb8-63dc6b8de399
Content-Type: multipart/mixed; boundary=changesetresponse_d6b175ef-c905-4196-a472-029b109a60cc

--changesetresponse_d6b175ef-c905-4196-a472-029b109a60cc
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 3

HTTP/1.1 400 Bad Request
REQ_ID: cbd53703-aee5-4563-a416-a65dcc268e7b
Content-Type: application/json; odata.metadata=minimal
OData-Version: 4.0

{"error":{"code":"0x80044331","message":"A validation error occurred.  The length of the 'firstname' attribute of the 'contact' entity exceeded the maximum allowed length of '50'."}}
--changesetresponse_d6b175ef-c905-4196-a472-029b109a60cc--
--batchresponse_6cbc8fc1-8988-4049-8cb8-63dc6b8de399--


Thanks,
Kengie

________________________________

**Comment by JimDaly** [comment]
Kengie -

You don't mention anything about the changesets in your batch.
You say you have 5 operations. Are they each in separate changesets, or all in one?
A changeset is a transaction, so if any one of the operations in a changeset fails, all must fail.
But if they are independent separate changesets, then one of them may fail and the rest can continue.

**Comment by PandaBoy00** [comment]
Hi Jim,

Sorry about that on my part about not mentioning the changeset. I will modify 5 operations to be 5 changeset instead and try again.

Thank you for the tip.

Regards,
Kengie

________________________________

**Comment by PandaBoy00** [comment]
Sorry about this.  I had 5 POST operation in one changeset.

I'm doing variation of the raw post body (putting each operation in a changeset, removing the changeset boundary) but the executions just returns 200 OK even though the firstname  exceeds the character limit of 50.

Can you give me a sample of your request POST how you get it to trigger the error?

Thanks in advance.

________________________________

**Comment by PandaBoy00** [comment]
Hi Jim,

I was able to get it working after doing different variations of the changeset and the formatting of the multipart body.

Even a missing newline would try the whole batch process off.  

I think the documentation could be a little bit more specific of the format of the $batch operation with a strict formatting of the body.  Again this is just my opinion to be more clear in the documentation.
