### ISSUE TITLE
PowerApps filtering of PowerBI tile issue

### ISSUE THREAD

**Issue by Gari-sincere** [MicrosoftDocs/powerapps-docs#2845]
URL filtering for PowerBI tile is not working, but the same URL filter works on the source report directly. I set "AllowNewAPI" property to true and the issue persists.

URL fed to PowerApp tile (doesn't work)
"https://app.powerbi.com/embed?dashboardId=30b8359e-9405-4324-a7f1-fb333ca747e7&tileId=e1ec10e9-e3b0-40e3-8738-4b2ff145bffa&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVNPVVRILUNFTlRSQUwtVVMtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQiLCJlbWJlZEZlYXR1cmVzIjp7Im1vZGVybkVtYmVkIjpmYWxzZX19&filter=Table1/DATE_ID eq datetime'2019-05-20T00:00:00'"

Testing URL for report directly (does work)
"https://app.powerbi.com/groups/me/reports/9aad6c9c-3bdd-4296-86a5-dee209cc36d1/ReportSection?filter=Table1/DATE_ID eq datetime'2019-05-20T00:00:00'"

This report is using an excel table in onedrive for its data source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 551096c3-6bef-bd2b-9254-4fceac6315da
* Version Independent ID: 6aaee99a-f244-17ca-cb48-408436a2ad92
* Content: [Power BI tile control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The two links above are different, and ensure to use report ID instead of dashboard ID. If the issue persists, please reach out using a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with the problem investigation.
