### ISSUE TITLE
Time to read this page: 6 minutes?? Seriously?

### ISSUE THREAD

**Issue by GraemeNZ** [MicrosoftDocs/powerapps-docs#2846]
This page takes way longer than 6 minutes to read, and even longer to understand. If you know all these features you can probably read the amount of content in 6 minutes, but if you have to read this page for help, then you don't know what you are doing. I would say it takes AT LEAST 15 minutes to read and understand, but more like 30 minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Minutes to read aren't added manually. And agree that for reading, understanding, testing etc., this would take much longer.
