### ISSUE TITLE
Note regarding download managers and PDF viewer control (experimental)

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftDocs/powerapps-docs#2851]
Just a head up, I have emailed both Microsoft and IDM regarding this, but if an end-user has a download manager installed and active while using an app that uses PDF viewer control (experimental) in Power Apps, the PDF may not display and instead the download manager will pick it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5b06f20-00c5-9824-ecbf-70c03f1858c4
* Version Independent ID: 2270c9fe-bbcb-4cc6-90f1-485ebe8ee094
* Content: [PDF viewer control (experimental) in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-pdf-viewer)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-pdf-viewer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-pdf-viewer.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out with GitHub issue and pull request. Please reach out using a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for any help with a product behavior/issue investigation. We don't document third-party app content and behavior in Microsoft product documentation.
