### ISSUE TITLE
probleme

### ISSUE THREAD

**Issue by hamzaoubouzid** [MicrosoftDocs/powerapps-docs#2853]
So how i can change the user Name to email in page SignIn, when user Sign In idon't like to use his username but hi want use email adresse not username

**Comment by phecke** [comment]
@hamzaoubouzid  Please provide a link to the documentation that you are referring to.

**Comment by hamzaoubouzid** [comment]
@phecke
![signin](https://user-images.githubusercontent.com/69641228/140928158-4138a22d-aee8-4f9d-b9b5-e88abd59cfdc.png)
in This  Sign in page ,
how i can use email not username 
and thank you

**Comment by nickdoelman** [comment]
You will need to change the site setting: **Authentication/Registration/LocalLoginByEmail** to _true_. This setting (and others) are documented here: https://docs.microsoft.com/powerapps/maker/portals/configure/set-authentication-identity#enable-aspnet-identity-authentication

**Comment by hamzaoubouzid** [comment]
but i don't have this athuentication/registraion/localloginbyemail

Le mer. 10 nov. 2021 à 14:34, nickdoelman ***@***.***> a
écrit :

**Comment by nickdoelman** [comment]
If the site setting does not exist, you can add it.  More details on creating and managing site settings can be found here: https://docs.microsoft.com/powerapps/maker/portals/configure/configure-site-settings

**Comment by hamzaoubouzid** [comment]
thank you  so much


‫في الأربعاء، 10 نوفمبر 2021 في 2:39 م تمت كتابة ما يلي بواسطة
‪nickdoelman‬‏ ***@***.***‬‏>:‬
