### ISSUE TITLE
Hyperlink to Process Advisor is broken

### ISSUE THREAD

**Issue by SamBoothDfT** [MicrosoftDocs/powerapps-docs#2854]
The hyperlink to Process Advisor is broken. It has an additional ".md" on the end of the URL, which when removed, works correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c1b531-f161-6063-01cf-6e944a03c2a6
* Version Independent ID: c080c46a-f025-2129-9297-88a6c3e79c68
* Content: [Document the activities in a business process - Power Apps](https://docs.microsoft.com/en-us/powerapps/guidance/planning/what-activities)
* Content Source: [powerapps-docs/guidance/planning/what-activities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/guidance/planning/what-activities.md)
* Service: **powerapps**
* Sub-service: **guidance**
* GitHub Login: @TGrounds
* Microsoft Alias: **thground**

**Comment by Mattp123** [comment]
@SamBoothDfT - Thank you for your feedback. The link has been fixed. 
Closing issue.
