### ISSUE TITLE
Video Link Broken

### ISSUE THREAD

**Issue by William-deGrasse** [MicrosoftDocs/powerapps-docs#2856]
Video link broken at the bottom of the page: "Video: Themes". Leads to "This video is unavailable" on YouTube.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bfa2c4e-b1d4-972e-56f7-250bbeeda910
* Version Independent ID: f7f5c4fc-a9f7-9917-4e24-7f878655cb13
* Content: [Change the color scheme or add a logo to match your brand - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-themes-organization-branding)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-themes-organization-branding.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/create-themes-organization-branding.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@William-deGrasse - Thank you for your feedback. The article has been updated to remove the link because the video has been removed.
Closing issue.
