### ISSUE TITLE
If you use same field more then once on the form, only first will be affected by setVisible

### ISSUE THREAD

**Issue by VLomonovskis** [MicrosoftDocs/powerapps-docs#2857]
I am building a form and for user comfort use same field in 2 places (on the same form). It will save user time for scrolling and makes it more comfortable to reed data together with other relevant data (keep context together).
However, I got an issue, I cannot Hide/Show field in both locations with setVisible. Only the first one will be affected (the one higher on the form).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b96278-a939-b802-1bb6-6370dee74503
* Version Independent ID: 4e5cb0c8-c16d-13e4-3364-0fff2535d9f7
* Content: [setVisible (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-formselector/setvisible)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-formSelector/setVisible.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-formSelector/setVisible.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by skovlund** [comment]
Since you want to show/hide a field then I think the documentation you meant to link to is this:
[https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setvisible](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setvisible)

However, it seem your issue is with the functionality and not the documentation.
Note the `formContext.getControl(arg)` is used and not `formContext.getAttribute(arg)`. Whe a column is added multiple times to the same form then it will only be added as a single attribute, but with multiple controls. This generally allows you customize the controls differently (and in this case to show one and hide the other). The way the form context works is that the second control will have an appended '1', the third an appended '2' and so on...

So your code should look something like:
```
formContext.getControl("new_myfield").setVisible(bool);
formContext.getControl("new_myfield1").setVisible(bool);
```

However if you want the same display value for all your controls for the field you might want to go with the more generic solution:
```
formContext.getAttribute("new_myfield").controls.forEach(control => control.setVisible(bool));
```

**Comment by VLomonovskis** [comment]
> Since you want to show/hide a field then I think the documentation you meant to link to is this: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setvisible
> 
> However, it seem your issue is with the functionality and not the documentation. Note the `formContext.getControl(arg)` is used and not `formContext.getAttribute(arg)`. Whe a column is added multiple times to the same form then it will only be added as a single attribute, but with multiple controls. This generally allows you customize the controls differently (and in this case to show one and hide the other). The way the form context works is that the second control will have an appended '1', the third an appended '2' and so on...
> 
> So your code should look something like:
> 
> ```
> formContext.getControl("new_myfield").setVisible(bool);
> formContext.getControl("new_myfield1").setVisible(bool);
> ```
> 
> However if you want the same display value for all your controls for the field you might want to go with the more generic solution:
> 
> ```
> formContext.getAttribute("new_myfield").controls.forEach(control => control.setVisible(bool));
> ```

Thank you very much. It have sense and I understand much better the structure now! :)

**Comment by Nkrb** [comment]
@VLomonovskis I hope you have found the answer for the issue, Closing the issue. If you need further help, please reopen or create a new issue.

**Comment by VLomonovskis** [comment]
> > Since you want to show/hide a field then I think the documentation you meant to link to is this: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setvisible
> > However, it seem your issue is with the functionality and not the documentation. Note the `formContext.getControl(arg)` is used and not `formContext.getAttribute(arg)`. Whe a column is added multiple times to the same form then it will only be added as a single attribute, but with multiple controls. This generally allows you customize the controls differently (and in this case to show one and hide the other). The way the form context works is that the second control will have an appended '1', the third an appended '2' and so on...
> > So your code should look something like:
> > ```
> > formContext.getControl("new_myfield").setVisible(bool);
> > formContext.getControl("new_myfield1").setVisible(bool);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However if you want the same display value for all your controls for the field you might want to go with the more generic solution:
> > ```
> > formContext.getAttribute("new_myfield").controls.forEach(control => control.setVisible(bool));
> > ```
> 
> Thank you very much. It have sense and I understand much better the structure now! :)

Thank you. This resolved the issue and enlightens me. :)
