### ISSUE TITLE
Update Needed

### ISSUE THREAD

**Issue by GrapeTechHead** [MicrosoftDocs/powerapps-docs#286]
Hello -

The exercise is a nice way to get into learning how to create an app from data.  The issue I have is that some of the functionality for PowerApps has changed so in March 2019 my version is a bit different than the screens in this one. Can someone update this visually or with text so that people who just getting into PowerApps can follow along with the information provided. 

Specifically, this area is not the same:

![image](https://user-images.githubusercontent.com/48532135/54313542-d441be00-4596-11e9-94d8-6683c5248d90.png)

 mine looks like:

![image](https://user-images.githubusercontent.com/48532135/54313593-ec194200-4596-11e9-9a17-2d016ab21036.png)

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74af29d6-96d0-9eab-885d-7cfbc585af9e
* Version Independent ID: 9e8270b3-b238-200a-74ac-10104750d86e
* Content: [Create an canvas app from scratch based on Excel data - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/get-started-create-from-blank)
* Content Source: [powerapps-docs/maker/canvas-apps/get-started-create-from-blank.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/get-started-create-from-blank.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Topic updated. Thanks, @GrapeTechHead!

**Comment by GrapeTechHead** [comment]
I see the thread is closed but where do I go to get a tutorial with updated images so I can follow along with the process?

**Comment by AFTOwen** [comment]
@GrapeTechHead The original topic on which you left this comment has been updated and republished. Please let us know if you are still having trouble. Thanks. 
[Create a canvas app from scratch based on Excel data](https://docs.microsoft.com/powerapps/maker/canvas-apps/get-started-create-from-blank)

**Comment by GrapeTechHead** [comment]
Thank you. There was no mention of this in the original update I was sent.




Orlando Taylor | Help Desk Analyst
Trinchero Family Estates
Office: 1-209-263-3240 | Ext. 6345
otaylor@tfewines.com


________________________________
Confidentiality Notice: This message, and any documents, files or previous e-mail messages attached to it, is the property of Trinchero Family Estates or its affiliates. It is intended only for the use of the individual or entity to which it is addressed and may contain information that is non-public, proprietary, privileged, confidential, and/or exempt from disclosure under applicable law or may constitute attorney work product. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is strictly prohibited. If you have received this communication in error, please notify us immediately by reply e-mail and destroy the original communication and its attachments without reading or saving them to disk or other storage medium. Thank you.
