### ISSUE TITLE
Date format on articles

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#2861]
This is a general comment about all MS articles of this type. The articles are dated, but the date is presented in a US-specific format: eg, 07/14/2021. Although this date is unambiguous, a date such as 01/09/2021 would normally be read by someone in Europe as 1st September, rather than 9th January. I can understand that generating locale-specific date formats may be too complex within an article, I think the date should be presented in an unambiguous way for all. A format such as July 14th 2021 or 14-Jul-2021 would suffice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcd3e610-828d-1afe-4777-ca9e8ed80395
* Version Independent ID: b3ff53e0-b33b-d977-cadc-3f81475ff3c6
* Content: [Export data to Excel in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/export-data-excel)
* Content Source: [powerapps-docs/user/export-data-excel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/export-data-excel.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@biterbit Thank you for your feedback. I will forward your feedback to team that handles our publishing software/tools. 

Thanks,
Mints
