### ISSUE TITLE
Has the max components to add changed?, cause in my OOB environment I can add up to 20 components instead of only 6 

### ISSUE THREAD

**Issue by switchbladesmile** [MicrosoftDocs/powerapps-docs#2865]
In previous versions there were permitted only  6 components to add in a dashboard, and in this doc mentions the same for recent versions https://docs.microsoft.com/en-us/powerapps/user/track-your-progress-with-dashboard-and-charts#create-a-dashboard-with-charts , but  I have tested in my OOB organization and found that i can add up to 20 components.  Have this recently changed?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fbfa51b-42cc-5fad-de26-e5d28724ea16
* Version Independent ID: 759e5d1c-f71e-fb07-5188-e8ebd5bcd76a
* Content: [Track your progress with dashboards and charts in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/track-your-progress-with-dashboard-and-charts#create-a-dashboard-with-charts)
* Content Source: [powerapps-docs/user/track-your-progress-with-dashboard-and-charts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/track-your-progress-with-dashboard-and-charts.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@switchbladesmile thank you for your feedback. I'm going to verify this with our internal team and get back to you.

Thanks,
Mints

**Comment by switchbladesmile** [comment]
OK Thank u

**Comment by mduelae** [comment]
@switchbladesmile, Per our internal team, the limit listed in the topic is correct but it can change if your organization requested an limit increase.

You may want to contact support for more details: https://powerapps.microsoft.com/support/

Thanks,
Mints

**Comment by switchbladesmile** [comment]
Hello, hmm in an online environment how do I request to increase that limit? I have a trial environment an i have not requested anything yet to increase that limit and still can add up to 20 elements.

Thank u
