### ISSUE TITLE
Edited record will not save with this customization

### ISSUE THREAD

**Issue by Greybeard1975** [MicrosoftDocs/powerapps-docs#2868]
I am having problems with a variation on this customization.  I have renamed "Responsible User" as "Fleet Manager" both in the OnSelect code attached to the save/continue button, and in in the Area Inspection Locations table.  However the record is not being saved with the additional line added to the patch function.  I have to edit the table directly to store the name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09b06e-0061-eb85-5852-a11038ddf393
* Version Independent ID: 01757436-d6b0-4ad4-3e96-48a06c0d0949
* Content: [Notify a manager on completion of an inspection - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/notify-manager-inspections#verify-that-a-manager-exists-for-the-responsible-user)
* Content Source: [powerapps-docs/teams/notify-manager-inspections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/notify-manager-inspections.md)
* Service: **powerapps**
* GitHub Login: @josephshum
* Microsoft Alias: **jshum**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please create a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to work with the support teams for investigating and fixing this and any other issues with customization.
