### ISSUE TITLE
Incorrect Text

### ISSUE THREAD

**Issue by matt152153** [MicrosoftDocs/powerapps-docs#2873]
_"Sorts IceCream first by its OnOrder column, and then by its Quantity column. Note that "Pistachio" rose above "Vanilla" in the first sort based on OnOrder, and then together they moved to their appropriate place based on Quantity."__

It is actually sorting first by Quantity then OnOrder.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e858d5-dbbb-9200-d867-a8b597de4df3
* Version Independent ID: d45b98b2-e452-c295-39ed-90468f40a0c1
* Content: [Sort and SortByColumns functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-sort)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-sort.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-sort.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The sorting happens for OnOrder and then Quantity. If there's any issue with the data in the data source you use, please check and verify if the data types for columns is correct. For more help, you can also reach out to support teams using a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) for investigation.

**Comment by matt152153** [comment]
![image](https://user-images.githubusercontent.com/47367468/143938410-d75cbaec-0808-4462-b988-c97e733db1f7.png)
