### ISSUE TITLE
It's only possible to restore app versions that were created in the last six months - why?

### ISSUE THREAD

**Issue by luconsta** [MicrosoftDocs/powerapps-docs#2877]
Hello,
I was reaching this page using the "Versions" tab of an app and there is a notice that say:

It's only possible to restore app versions that were created in the last six months. [Learn more](https://docs.microsoft.com/powerapps/maker/canvas-apps/restore-an-app)

Unfortunately in this page I could not find any reference or other resource that could explain why only "last six months". It's a policy? Could be changed? etc...

Is is possible to add something that explain this "six months"?

Thank you!
L.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2b1cae-930d-26ee-b8e1-5af3cd304c83
* Version Independent ID: 05ac17c8-e17d-bb3c-1009-9de987b4a64d
* Content: [Restore your canvas app to a previous version - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/restore-an-app)
* Content Source: [powerapps-docs/maker/canvas-apps/restore-an-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/restore-an-app.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Six months is the current limit that can't be changed. If you'd like to ask for a feature to change this limit, or have different behavior ask, please feel free to submit an idea through the [Power Apps Community Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
