### ISSUE TITLE
Me

### ISSUE THREAD

**Issue by brandonnathaniel01** [MicrosoftDocs/powerapps-docs#288]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e8de9b3-9764-f91b-6abc-30f21d6047a8
* Version Independent ID: a7fb28d7-bf49-715c-00df-29e6fd6024c9
* Content: [Understand tables in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-tables)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-tables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-tables.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Me too.  :)

If you are asking about a "Me" or "This" identifier like "ThisItem" or "Parent" that is self referential to the current control or record, this is on our development backlog and we hope to add it soon.

**Comment by AFTOwen** [comment]
Thanks, @brandonnathaniel01. Closing this issue.
