### ISSUE TITLE
Function NOW() is undocumented

### ISSUE THREAD

**Issue by thijskuipers** [MicrosoftDocs/powerapps-docs#2880]
In the screenshots under https://docs.microsoft.com/en-us/powerapps/maker/data-platform/define-calculated-fields#provide-the-formula-for-computing-the-difference-in-days the function `NOW()` is used, but it is not documented under https://docs.microsoft.com/en-us/powerapps/maker/data-platform/define-calculated-fields#functions-syntax.

![](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/media/custom-calc-field-diff-days.png)

![](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/media/calc-field-diff-days-complete.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f212137-6b88-c06c-025d-c05e6b74c10f
* Version Independent ID: 61abe448-2b0d-29bd-90bb-63899f0f92dc
* Content: [Define calculated columns in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/define-calculated-fields)
* Content Source: [powerapps-docs/maker/data-platform/define-calculated-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/define-calculated-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@thijskuipers - There's a new feature, formula columns, that is in preview and supports UTCNow as well as many other well documented functions. More information: [Work with formula columns](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/formula-columns)

Closing issue.
