### ISSUE TITLE
How to set SAS key on service enpoint using code?

### ISSUE THREAD

**Issue by jkanschik** [MicrosoftDocs/powerapps-docs#2881]
Hi,

In general it's a good documentation about how to set up the azure integration, however, I would like to see information about how to update the SAS key **without** using the Plugin Registration Tool. Looking at CI/CD and ALM, I would like to add the key automatically, for example:

1. Create the service bus queue with SAS using the azure CLI (or tools like terraform in my case)
2. Use the SAS key during the deployment of the solution

Alternatively, it would be nice to have a hint on how to set this using code (.NET SDK, Powershell, anything).

Best regards,

Jens.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c28b2373-e4fd-9c2c-8962-ca6782c79eca
* Version Independent ID: 41994b3b-b37b-7672-cae9-e9668cd9849b
* Content: [Walkthrough: Update a service endpoint imported from a solution (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/walkthrough-update-service-endpoint-imported-solution)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-update-service-endpoint-imported-solution.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/walkthrough-update-service-endpoint-imported-solution.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@jkanschik 
Sorry for the delay in responding. 
We expect people to use the tooling provided to set the data for the ServiceEndpoint rather than try to do it with code.
This is why we don't include code samples for this. This is by design.

Thanks
