### ISSUE TITLE
co-authoring for dataverse for teams 

### ISSUE THREAD

**Issue by guenthi** [MicrosoftDocs/powerapps-docs#2882]
This feature is vital for team-development. I encourage to add it also to dataverse for teams solutions. Version control of source-code, having a single repository for all source-code is vital for a team and an organization. From developer perspective git-integration and using the git-features for team-development is something I would not like to miss :-)

cool feature - right direction - awesome

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dcec321-a287-a483-241d-69b147737f23
* Version Independent ID: 1dcec321-a287-a483-241d-69b147737f23
* Content: [Co-authoring in canvas apps (experimental) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/git-version-control)
* Content Source: [powerapps-docs/maker/canvas-apps/git-version-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/git-version-control.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. Please visit [Power Apps Community Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) to suggest, submit, and vote for ideas related to feature changes.
