### ISSUE TITLE
Add ability to use Power Platform CLI with WSL2

### ISSUE THREAD

**Issue by codefoster** [MicrosoftDocs/powerapps-docs#2883]
I was able to install the Power Platform CLI, and it works fine in PowerShell, but I can't see a way to use it in WSL2. I primarily use BASH in WSL2 and don't want to have to open PowerShell just to use this utility. If there is a way, it seems it deserves a place in this getting started doc page. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0e3024-713b-e281-1417-21106fda3045
* Version Independent ID: 177d4ac9-7856-cbea-dc61-a7d11a909273
* Content: [Microsoft Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli)
* Content Source: [powerapps-docs/developer/data-platform/powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/powerapps-cli.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@codefoster Thanks for reaching to us. Microsoft Power Platform CLI works in WSL via VS code and not with standalone CLI.

**Comment by JimDaly** [comment]
Closing this as it appears the question was answered. Please re-open if not.
