### ISSUE TITLE
"Maximum path length limitation in Windows" Link Not Found

### ISSUE THREAD

**Issue by khoait** [MicrosoftDocs/powerapps-docs#2884]
"Maximum path length limitation in Windows" Link Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fffb76-5378-fe8a-62fc-0c82a6d03d6d
* Version Independent ID: 102ff357-ae01-8222-8c14-64e2a5e78a0b
* Content: [Portals support for Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/power-apps-cli)
* Content Source: [powerapps-docs/maker/portals/power-apps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/power-apps-cli.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention.  The link has been fixed and will be updated on docs in a few hours.  The link is https://docs.microsoft.com/windows/win32/fileio/maximum-file-path-limitation
