### ISSUE TITLE
Administrators may not have permission to create portals.

### ISSUE THREAD

**Issue by LuHao-007** [MicrosoftDocs/powerapps-docs#2885]
The prerequisite for creating a Portal is that the user has permission to register an app in Azure AD. 
It is possible that the global administrator does not have this permission and one of the following three roles needs to be assigned to the administrator in order for him/her to be able to register the app and thus have permission to register the portal.

- Application administrator
- Application developer
- Cloud application administrator

In short, the prerequisites for creating a portal are not rigorous enough and a conditional branch needs to be added.
Can an administrator create a portal? If not, assign the administrator in Azure AD one of roles "Application administrator", "Application developer" or "Cloud application administrator" .

Could you please add this conditional branch in the Create portal part?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff0331e6-6c2b-4728-4c3b-3e141c285dc7
* Version Independent ID: 936bdd2f-3b1e-45d9-ed1a-c2c13e45ba46
* Content: [Roles required for portal administration - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-admin-roles)
* Content Source: [powerapps-docs/maker/portals/admin/portal-admin-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/portal-admin-roles.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for your feedback.  We have investigated and the Global Administrator has by default all the necessary privileges to register the portal app in Azure AD. If you are experiencing issues regarding the creation of a portal or the app registration process with a user with the Global Administrator role, we suggest you open a support ticket, and our support team can investigate the issue further.

**Comment by LuHao-007** [comment]
Hi Nick, thanks for your input. 
I understand that by default or if Azure is configured correctly, the global administrator should have the permission to register the app. However, a customer from S500 is really missing this permission as a global administrator, and the customer's tenant may have set something incorrectly to cause this issue. 
So can we add this sentence from you to the documentation? _If you are experiencing issues regarding the creation of a portal or the app registration process with a user with the Global Administrator role, we suggest you open a support ticket, and our support team can investigate the issue further._
