### ISSUE TITLE
Column Options only available in Main Grids not Sub Grids. 

### ISSUE THREAD

**Issue by Uggi** [MicrosoftDocs/powerapps-docs#2887]
Hi 

The column options & filter 
![image](https://user-images.githubusercontent.com/4349731/143720818-d6d0bba2-ac7f-44ba-8f03-bd26aef35cd0.png)
are only available for main grids, not sub-grids. (Although I wish they were available for sub-grids already)
I would love to know if I have missed something here! 
>  Additionally, you can add or remove columns in the view or sub-grid.

-- Image of a SubGrid with no column options or filter. 
![image](https://user-images.githubusercontent.com/4349731/143720908-295ca667-c0ee-4bfc-a1e9-ca9eddc6eaaa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e9258f-4c21-9d52-9940-cada6c70db50
* Version Independent ID: 1f5619dd-aea0-d0d4-34a9-a7e0e036faf8
* Content: [Filter data on grids - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/grid-filters#use-the-column-options-in-a-view-or-grid-preview)
* Content Source: [powerapps-docs/user/grid-filters.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/grid-filters.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@Uggi, Let me verify this information with our internal team and I will get back to you.

Thanks,
Mints

**Comment by sriharibs-msft** [comment]
Hello - thank you for the feedback. You have not missed anything. Column options and advanced filters are available only on a table's home page grid. Currently sub grids do not have these, as sub-grids are generally found on a form which already has some context. So, the records that appear on a sub-grid have certain pre-set filters and columns that users generally do not have the need to edit.

**Comment by Uggi** [comment]
@sriharibs-msft : Thanks for the clarification. Its unfortunate, while I get the reasoning, we get lots of customers asking us for this feature all the time. Especially now that it is so easily accessible in the main grid. They are always confused why its not possible in the sub grid as well. I would urge the product team to re-evaluate this.  thanks.
