### ISSUE TITLE
Validate doesn't work as described

### ISSUE THREAD

**Issue by DavidLozzi** [MicrosoftDocs/powerapps-docs#289]
Seeing the documentation for Validate https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-validate, trying to use it with a record, something like this:

`Validate(Events,Defaults(Events),addEventForm)`

But it errors out. The PowerApps editor doesn't recognize the record parameters as documented, it only shows helper text for the single column

![image](https://user-images.githubusercontent.com/3543383/54478132-6e974100-47e5-11e9-8015-76c4cdf989db.png)

**Comment by truespinmice** [comment]
I've got the same issue :/  since a few days. I'm using SPO list as a data source

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please verify whether the error mentions using boolean when expecting text for validation. You can see more about the error moving the mouse cursor over different parameters. 

If the issue persists, please reach out via a [support service request](https://admin.powerplatform.microsoft.com/support).
