### ISSUE TITLE
Portals now supports the ui_locales request parameter

### ISSUE THREAD

**Issue by harrdou** [MicrosoftDocs/powerapps-docs#2892]
Re: "Portals doesn't support acr_values or ui_locales request parameters in authorization requests."

Support for ui_locales was added in [portals version 9.3.8.x](https://docs.microsoft.com/en-us/power-platform/released-versions/portals/portalupdate938x).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855290e-8fbe-9af5-c51f-1ac086547808
* Version Independent ID: 1eba37f7-f58d-b60a-f3c6-a3c7ad923904
* Content: [FAQs for using OpenID Connect in portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-openid-faqs)
* Content Source: [powerapps-docs/maker/portals/configure/configure-openid-faqs.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-openid-faqs.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by nickdoelman** [comment]
Thank you for your feedback. The documentation has been updated.
