### ISSUE TITLE
Confused over Dataverse server architecture reference to SQL

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/powerapps-docs#2893]
The last paragraph makes reference to different functionality depending on whether your Dataverse instance is based upon SQL Server Standard or Enterprise.
Is this right, if so how do you find out?
I'd always understood that Dataverse was based upon Cosmos DB
Thanks, Richard  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a83c156a-38b1-9a21-acca-d5038e8bcf04
* Version Independent ID: ee41927c-89d2-5717-5d49-ad88c23d7fba
* Content: [Retrieve and delete the history of audited data changes (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/retrieve-and-delete-the-history-of-audited-data-changes)
* Content Source: [powerapps-docs/developer/data-platform/retrieve-and-delete-the-history-of-audited-data-changes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/retrieve-and-delete-the-history-of-audited-data-changes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Bluebear73
* Microsoft Alias: **munzinge**

**Comment by Bluebear73** [comment]
Thanks for bringing this up Richard!
Dynamics 365 on-premise is based on SQL and customers can choose their SQL edition. Dataverse for Dynamics 365 online has multiple underlying data stores, one of which is a SQL version that supports partitions. The article refers to both online and on-premise behavior.
In the near future, audit data for the online version will be stored in a new storage solution that doesn't have partitions and the RetrieveAuditPartitionList request as well as partition specific DeleteAuditData behavior will become obsolete. Partitions will continue to be relevant for Dynamics 365 on-premise customers.
I will update the article once these changes are rolling out.

**Comment by JimDaly** [comment]
This topic area was re-written and the referenced topic now redirects to [Retrieve the history of audited data changes](https://docs.microsoft.com/power-apps/developer/data-platform/auditing/retrieve-audit-data).

I believe the part which was contributing to the confusion here was remove. Please re-open if this is not the case.
