### ISSUE TITLE
This flow import limitation is so frustrating and insane..

### ISSUE THREAD

**Issue by VFXpro** [MicrosoftDocs/powerapps-docs#2899]
Microsoft keeps recommending to use solution to build flows.  Then, I "save as" a solution flow to make a copy of it. It now shows outside my solution :(  

Then, I try to import this newly created copied flow into the solution where it should be long, but the import option doesn't even list this flow.  

With so many holes, this product is not ready for prime time and the speed of its development is so slow its crazy...

I'm very frustrated advanced user with nearly 200 hundreds flows under his belt ready to throw it all away.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba673f56-d0c1-6795-c028-5e121fe3cfeb
* Version Independent ID: bb0c60db-d75b-c470-81f9-3414e9b863d5
* Content: [Solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/solutions-overview#known-limitations)
* Content Source: [powerapps-docs/maker/data-platform/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/solutions-overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@VFXpro - Thanks for your feedback. Your feature request has been forwarded to the engineering team for consideration. Also, you can vote or submit your product-related requests at https://ideas.powerapps.com.

Closing issue.
