### ISSUE TITLE
RTE control size on phone layout

### ISSUE THREAD

**Issue by kyleremp** [MicrosoftDocs/powerapps-docs#29]
Great new feature!

+1 for solving: "The control is primarily targeted for use in browsers on large screens. Using the control on a mobile phone can be a frustrating experience."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 492e388f-6f28-4cc4-3897-8a6384e8a466
* Version Independent ID: c3a43927-981d-ad01-969e-285c7a80158a
* Content: [Rich text editor control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-richtexteditor)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-richtexteditor.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-richtexteditor.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
We are addressing this currently.  The mobile experience will be substantially improved when we move the control out of preview and into GA, towards end of November.

**Comment by bargshree** [comment]
Has this control moved to GA already? I still see it as preview? Has there been any changes that happened recently?
