### ISSUE TITLE
Error when register new assembly

### ISSUE THREAD

**Issue by luoyong0201** [MicrosoftDocs/powerapps-docs#290]
The content says user .net framework 4.6.2, but the picture shows 4.5.2.
when register the assembly, it reports, how can I solve this problem?
Microsoft.Crm.CrmException: 此插件程序集使用了版本 4.6.2 的 .NET Framework。目前，Microsoft Dynamics 365 要求插件程序集使用版本 4.5.2 的 .NET Framework。请使用 .NET Framework 版本 4.5.2 重新生成此程序集，然后重试。 ---&gt; Microsoft.Crm.CrmException: 此插件程序集使用了版本 4.6.2 的 .NET Framework。目前，Microsoft Dynamics 365 要求插件程序集使用版本 4.5.2 的 .NET Framework。请使用 .NET Framework 版本 4.5.2 重新生成此程序集，然后重试。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccfeadcb-8074-d9de-125a-7353b1597774
* Version Independent ID: 0d857c7c-b943-7d38-b65c-1cb7b71d2cb2
* Content: [Tutorial: Write and register a plug-in (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-write-plug-in#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/tutorial-write-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
The image was updated to show the correct .NET Framework version (4.6.2)
