### ISSUE TITLE
Add new tables to a managed solution

### ISSUE THREAD

**Issue by manuel-faria** [MicrosoftDocs/powerapps-docs#2900]
It is not possible to add new tables to the Bulletins app (because it is a manage solution, I believe so). For instance, in the scenario "Add "Notify me" settings to category" the step "Create a new table called Bulletin Notifications" is not possible. Can you correct it and provide guidance about how we can add tables to the app templates?

Thank you,
Manuel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7226b221-d8e9-9f72-a15d-aae7152aea55
* Version Independent ID: 5e425441-d8e3-165c-0843-da1f026f95a7
* Content: [Customize the Bulletins app - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/customize-bulletins)
* Content Source: [powerapps-docs/teams/customize-bulletins.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/customize-bulletins.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **jshum**

**Comment by tapanm-MSFT** [comment]
As the steps in the documentation and the video show, you can create table in the Dataverse for Teams environment for the team where the app is installed, and use it in the app customization. For steps to create table, please refer to the referenced Bulletins app documentation, or [Create a table](https://docs.microsoft.com/powerapps/teams/create-table).

**Comment by manuel-faria** [comment]
Hi @tapanm-MSFT, thanks for your response. Nevertheless, the instructions of the section "Create a new table called Bulletin Notifications" are not consistent/updated. The table needs to be created outside of the managed solution and then a relationship with the "Bulletin Category" original table needs to be created. Can you please update these instructions?
