### ISSUE TITLE
Missing mention of requirement to format table name as auto-plural when using Portal Web API

### ISSUE THREAD

**Issue by marnason** [MicrosoftDocs/powerapps-docs#2907]
`GET [Portal URI]/_api/bread` will fail to read data from Dataverse table **_bread_**.
After some investigation it turns out that custom tables in Dataverse get some sort of automatically pluralized version of their name assigned as their handle within the API. 

I truly wish the API would use the actual table name but that is a whole other matter, and that opinion belongs elsewhere than here. 

For now the issue is that this behaviour is completely undocumented, at least in regards to the Portal Web API.

Examples:

- Table name in Dataverse: `bread`
Read operation: `GET [Portal URI]/_api/breads`

- Table name in Dataverse: `hobbits`
Read operation: `GET [Portal URI]/_api/hobbitses`

_To be fair I never tested this second example, it is merely an assumption based on [the comment I found that made me discover this in the first place](https://powerusers.microsoft.com/t5/Power-Apps-Portals/Power-Apps-Portal-Web-API-Lookup-Field/m-p/902770)._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8c4f16-4467-9735-7c8c-b983cd0d4787
* Version Independent ID: 9a8c4f16-4467-9735-7c8c-b983cd0d4787
* Content: [Portals read operations using the Web API - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/read-operations)
* Content Source: [powerapps-docs/maker/portals/read-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/read-operations.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for your feedback. We have updated the topic to provide this information. https://docs.microsoft.com/en-us/power-apps/maker/portals/web-api-overview#using-entitysetname
