### ISSUE TITLE
Enable status tags on activity record types checkbox is missing

### ISSUE THREAD

**Issue by JonnGreaves** [MicrosoftDocs/powerapps-docs#2911]
[Enter feedback here]
Enable status tags on activity record types checkbox is missing in powerapps. I would love an update when/if this is resolved. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f8feb33-5440-75cb-a822-df28594faa5d
* Version Independent ID: c59421c6-9f9c-ae4e-f624-d025b4b8df48
* Content: [Add and configure the timeline control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/set-up-timeline-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/set-up-timeline-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/set-up-timeline-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @lalexms
* Microsoft Alias: **laalexan**

**Comment by MarcTrot** [comment]
Is this issue resolved now as I still do not see the option to enable / disable the status?

**Comment by lalexms** [comment]
Hi @MarcTrot @JonnGreaves - I'm working with the product team to try to understand the issue and they would like to know if you're talking about the status tags on the card layout form. Thanks for any additional details you can provide.

**Comment by lalexms** [comment]
Hi @MarcTrot @JonnGreaves I've not received a reply from either of you so I'm closing this issue. Please reopen if you'd like to continue the discussion and provide more details. Thanks.

**Comment by alexanstree** [comment]
Can this be opened back up?  I am experiencing the same issue with this and looking for a resolution. @lalexms.

**Comment by alexanstree** [comment]
@lalexms @bishalgoswami I opened up a separate ticket here with more information about what im expeiencing: ['Enable Status Tag' option does not show up in Timeline Control #4442](https://github.com/MicrosoftDocs/powerapps-docs/issues/4442)
