### ISSUE TITLE
Incorrect action for button

### ISSUE THREAD

**Issue by Ric-Chang** [MicrosoftDocs/powerapps-docs#2912]
[Enter feedback here]
..._Set **OnChange** property on btnReset to this formula:_...

There is no such "OnChange" action for a button control.
It should be replaced by OnSelect action or else. Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eca9b750-b686-4eea-009e-90f7d7a88f8f
* Version Independent ID: 47f0ff15-5438-d8f8-80e7-31739748e2a5
* Content: [Add a list box, a drop-down list, or radio buttons to a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-list-box-drop-down-list-radio-button#create-a-simple-list)
* Content Source: [powerapps-docs/maker/canvas-apps/add-list-box-drop-down-list-radio-button.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/add-list-box-drop-down-list-radio-button.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated, and will reflect the changes soon.
