### ISSUE TITLE
Why doesn't make.powerapps.com support collaborative editing like other 365 products?

### ISSUE THREAD

**Issue by schindld** [MicrosoftDocs/powerapps-docs#2913]
For all but the most trivial apps, collaboration is essential. When will we be able to edit a canvas app at the same time as a colleague?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2db75bc9-6c9a-05dd-9d33-bc01e40fa010
* Version Independent ID: e1430461-65ea-9a6b-00c6-d9d1f764d6db
* Content: [Edit a canvas app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/edit-app)
* Content Source: [powerapps-docs/maker/canvas-apps/edit-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/edit-app.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by Mattp123** [comment]
@schindld - Collaboration features including coauthoring is available with model-driven apps: https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/coauthoring
For canvas, currently commenting and copresence are the available features: https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/copresence-power-apps-studio

Closing issue.
