### ISSUE TITLE
Does it really support on-premise environments?

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/powerapps-docs#2915]
Hello. Does solution checker really support on-premise environments? I looked into PS module documentation and it seems like it only supports online version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b06e51-1090-87c7-33ff-a19b1c8a8ada
* Version Independent ID: b4a96b9e-62d2-55bf-3585-435474696771
* Content: [Use solution checker to validate your apps in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/use-powerapps-checker)
* Content Source: [powerapps-docs/maker/data-platform/use-powerapps-checker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/use-powerapps-checker.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@FixRM - Thank you for your feedback. You're correct that the Power Apps checker doesn't work with Dynamics 365 Customer Engagement (on-premises) organizations. The article has been revised to correct that.

Closing issue.
