### ISSUE TITLE
Get-IdPInitiatedUrl.ps1 code is wrong

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/powerapps-docs#2916]
the code for creating idpinitiatedsigon is wrong. please correct 

#--------code start-----

<#
.SYNOPSIS
Constructs an IdP initiated SSO URL to access a portal page on the SP.
.PARAMETER path
The path to the portal page.
.PARAMETER rpid
The relying party identifier.
.PARAMETER adfsPath
The AD FS IdP initiated SSO page.
.EXAMPLE
PS C:\> .\Get-IdPInitiatedUrl.ps1 -path "/content/sub-content/" -rpid
"" -adfsPath
""
#>
param
(
[parameter(mandatory=$true,position=0)]
$path,
[parameter(mandatory=$true,position=1)]
$rpid,
[parameter(position=2)]
$adfsPath = ""
)
$state = "ReturnUrl=$path"
$encodedPath = [uri]::EscapeDataString($state)
$encodedRpid = [uri]::EscapeDataString($rpid)
$encodedPathRpid = [uri]::EscapeDataString("RPID=$encodedRpid&RelayState=$encodedPath")
$idpInitiatedUrl = "{0}?RelayState={1}" -f $adfsPath, $encodedPathRpid
Write-Output $idpInitiatedUrl

#--------code end-----

**Comment by phecke** [comment]
@dbona75 Please provide a related documentation link so we can route your issue to the appropriate documentation author.  

Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.
 
Closing this issue. Create a new issue if this is a documentation issue and not a support issue.
