### ISSUE TITLE
Opening sentence is confusing.

### ISSUE THREAD

**Issue by MichelleGorrellUK** [MicrosoftDocs/powerapps-docs#2917]
The opening sentence "Basic form subgrids are configured in an identical fashion to basic form subgrids..." is clearly unhelpful.
There is a corresponding opening statement in the content for _Configure Advanced form subgrids for portals_ that makes better sense. 

So it seems likely that the opening sentence should be: "Basic form subgrids are configured in an identical fashion to **advanced form** subgrids..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89dae0e0-3e3c-fa1f-0a50-e3f7c8fb0da1
* Version Independent ID: 513e79ab-8cb7-1f33-30ed-e582ff866057
* Content: [Configure Basic form subgrids for portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-basic-form-subgrid)
* Content Source: [powerapps-docs/maker/portals/configure/configure-basic-form-subgrid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-basic-form-subgrid.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
Thank you for your feedback. We have updated the document.
