### ISSUE TITLE
Deactivate/Activate vs Turn off/Turn on

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/powerapps-docs#2919]
In all the environments I have access to the wording is **Turn off/Turn on** not **Deactivate/Activate**.

![image](https://user-images.githubusercontent.com/19864267/145864875-221485ca-603a-44c3-8eb5-4c48a0a531b8.png)

Jerry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c89fcf-5a0e-6eac-0fec-5142cb589eed
* Version Independent ID: b79fcb8a-fb5c-dbd4-0d47-ffcd5966c1b8
* Content: [Hide a model-driven app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/deactivate-app?source=docs)
* Content Source: [powerapps-docs/maker/model-driven-apps/deactivate-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/deactivate-app.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @matp
* Microsoft Alias: **ansja**

**Comment by Mattp123** [comment]
@JerryCRMI - Sorry for the delay. The article was updated to reflect the current UI as you indicated.

Closing issue.
