### ISSUE TITLE
Incorrect link to "upload attachments"

### ISSUE THREAD

**Issue by embraces0ul** [MicrosoftDocs/powerapps-docs#292]
In Step 2 &gt; second bullet of "Further customize your form" https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form#further-customize-your-form
*  "upload attach,ents" incorrectly links to -- https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/properties-text
* this should be -- https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-attachments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Thanks, @embraces0ul. Replaced the link; closing issue.
