### ISSUE TITLE
"Preview" tag is no longer needed - 

### ISSUE THREAD

**Issue by mscottsewell** [MicrosoftDocs/powerapps-docs#2920]
In the "View table data in Power BI Desktop (Preview)" link - the "Preview" tag is no longer needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b0624a6-1375-2fa0-8a41-2b049234d9a9
* Version Independent ID: dd507c9c-0273-4b93-5ad6-b68a9ad0b5d4
* Content: [Use Power BI using Microsoft Dataverse data - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/use-powerbi-dataverse?source=docs)
* Content Source: [powerapps-docs/maker/data-platform/use-powerbi-dataverse.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/use-powerbi-dataverse.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@mscottsewell - Thank you for your feedback. The word "preview" has been removed from the link text.

Closing issue.
