### ISSUE TITLE
.shell is not present on web form steps and sample code not working / not needed there

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#2922]
the .shell object from the sample code on
https://docs.microsoft.com/en-us/powerapps/maker/portals/write-update-delete-operations#wrapper-ajax-function
is not present on web form steps

and causes a
shell is not defined
error when used there

and the code does not seem to be needed in a web from step context,
as confirmed by
https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/414980/power-apps-portal-web-api-shell-is-not-defined

please add a note that this code is not needed on web form steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19b6555e-5515-677b-9861-426079ea1110
* Version Independent ID: 19b6555e-5515-677b-9861-426079ea1110
* Content: [Portals Web API write, update, and delete operations - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/write-update-delete-operations#web-api-ajax-samples)
* Content Source: [powerapps-docs/maker/portals/write-update-delete-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/write-update-delete-operations.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for reporting this issue. We are now tracking this bug and hope to have a resolution in a future release.
