### ISSUE TITLE
Rename "Common Data Service" as "Dataverse"

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/powerapps-docs#2923]
There are still references to Common Data Service connector in this page that should be replaced by Dataverse connector

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047b94ce-db9f-ad01-5a62-b0539f2433cc
* Version Independent ID: 1a8a9d3c-2d8b-e13c-042b-0a48fc444956
* Content: [Guidelines and troubleshooting when working with embedded canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-guidelines)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@Nicokirr - Thank you for your feedback. The article has been updated to reflect the current connector name.
Closing issue.
