### ISSUE TITLE
Form access for model driven apps in app designer

### ISSUE THREAD

**Issue by snulph** [MicrosoftDocs/powerapps-docs#2924]
Should this article also discuss where to allow specific forms within the app designer for model driven apps? Customizers could create new forms with the proper security and find that the form is still not available to users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73477021-74da-700a-86d4-6fa4ca484dca
* Version Independent ID: 92ebc6ed-4cb7-234d-2fba-1096f23382a6
* Content: [Control access to model-driven app forms in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/control-access-forms#set-security-roles-for-a-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/control-access-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/control-access-forms.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@snulph - Form management in app designer is a separate configuration and is covered in this article:  [Add or remove forms, views, or charts](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/create-add-remove-forms-views-dashboards)

Closing issue.
