### ISSUE TITLE
Missing section title for Lookup fields

### ISSUE THREAD

**Issue by larmccoy** [MicrosoftDocs/powerapps-docs#2925]
The page is missing a section heading where it discusses how to configure mapping for Lookup Fields. I suggest that the header should occur immediately before the following text in the page:
**If some data in your source file references other existing rows in your app**

The previous section, related to "Option Sets" is clearly demarcated, and the text on lookups is not easily identified.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46209bf7-62b7-f424-f749-f297c8847e35
* Version Independent ID: ffef7489-39b8-60dd-299b-367e3b694843
* Content: [Import data in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/import-data)
* Content Source: [powerapps-docs/user/import-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/import-data.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@larmccoy Thanks for the feedback. I added a new heading for that section. You should see the changes by end of day 1/3/2022.

Thanks,
Mints
