### ISSUE TITLE
Parallal.For / Parallel.ForEach / Task

### ISSUE THREAD

**Issue by philipverlinden** [MicrosoftDocs/powerapps-docs#293]
Would threading be supported in plug-ins and workflows? 
eg. System.Threading.Tasks.Task.Factory.StartNew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f776ff-420c-fbce-5fb0-24f3bc5b0837
* Version Independent ID: 2f374023-3e87-8c7f-9e8f-50167abc9d43
* Content: [Avoid usage of batch request types in plug-ins and workflow activities - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/business-logic/avoid-batch-requests-plugin)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/business-logic/avoid-batch-requests-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/business-logic/avoid-batch-requests-plugin.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by jowells1** [comment]
There will be separate guidance submitted about parallel processing as it is being defined by the sandbox team.

**Comment by phecke** [comment]
@philipverlinden 

See https://docs.microsoft.com/powerapps/developer/data-platform/best-practices/business-logic/do-not-use-parallel-execution-in-plug-ins
