### ISSUE TITLE
how about data sources in power platform

### ISSUE THREAD

**Issue by darklong** [MicrosoftDocs/powerapps-docs#2932]
I have been read docs via link : https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/performance-tips, but i don't sure about **data sources** in sentence "Don't connect to more than 30 data sources from the same app. Apps prompt new users to sign in to each connector, so every extra connector increases the amount of time that the app needs to start. As an app runs, each connector requires CPU resources, memory, and network bandwidth when the app requests data from that source." .

can you explain more about it .

For example: i have 5 list collection in a sharepoint, so One list call One Datasource, is it right ?

Thank for support
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7d6ebf-7d17-44ef-4348-354a8332081b
* Version Independent ID: 8427e65c-bf62-86c4-89b8-ecf5f59a890e
* Content: [Tips and best practices to improve performance of canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/performance-tips#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/performance-tips.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/performance-tips.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @yingchin
* Microsoft Alias: **yingchin**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Connecting to five SharePoint lists is counted as five connections, not one.
