### ISSUE TITLE
Add technical details

### ISSUE THREAD

**Issue by mathiasbl** [MicrosoftDocs/powerapps-docs#2933]
Please provide additional technical information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d329323e-41d1-3073-1203-438fdc0de607
* Version Independent ID: d329323e-41d1-3073-1203-438fdc0de607
* Content: [Use custom connectors with the timeline in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/custom-connectors-timeline-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/custom-connectors-timeline-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/custom-connectors-timeline-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @lalexms
* Microsoft Alias: **laalexan**

**Comment by dleblond312** [comment]
Hi @mathiasbl , I am an engineer on this project, can you provide me more specifics regarding what technical details would help you implement a custom connector successfully?

**Comment by lalexms** [comment]
Hi @mathiabl, were you able to provide details? If this issue is not resolved, please let us know. Thanks!

**Comment by lalexms** [comment]
@mathiasbl we haven't heard back from you so we're closing this ticket. Please open a new one with details if you need further assistance. Thanks!
