### ISSUE TITLE
pac admin create --input-file

### ISSUE THREAD

**Issue by FlorinSander** [MicrosoftDocs/powerapps-docs#2934]
Hello,

Can you please provide more information about the contents of the json file? Is there a possibility to add here also the Security group for the new environment?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7efca47b-bba7-986a-36d0-f62d3044124c
* Version Independent ID: fc3c8f2f-29f1-d632-5c6a-60b10bf98561
* Content: [Microsoft Power Platform CLI Admin command - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/cli/reference/admin-command)
* Content Source: [powerapps-docs/developer/data-platform/cli/reference/admin-command.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/cli/reference/admin-command.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by JimDaly** [comment]
@Laskewitz FYI

**Comment by JimDaly** [comment]
The description for the `--input file` parameter is:

> The verb arguments to be passed in a .json input file. For example: {"name" : "contoso"}. The arguments passed through command-line will take precedence over arguments from the .json input file.


So, instead of this:

```
pac admin create `
  --name "Contoso Marketing" `
  --currency EUR `
  --region europe `
  --type Production `
  --domain ContosoMarketing
```

The equivalent using `--input-file` would be:
`pac admin create -if C:\myconfig.json`

Where myconfig.json contains
```
{
  "name": "Contoso Marketing",
  "currency": "EUR",
  "region": "europe",
  "type": "Production",
  "domain": "ContosoMarketing"
}
```

@snizar007 
Do you know about:

> Is there a possibility to add here also the Security group for the new environment?

**Comment by JimDaly** [comment]
Added the example. See [Create using --input-file](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin#create-using---input-file)
