### ISSUE TITLE
Scope options invalid.

### ISSUE THREAD

**Issue by hugobarona** [MicrosoftDocs/powerapps-docs#2938]
Business rule's scope options should include _Entity_ and not _table_, to be aligned with current options available in the PP portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76443691-3e03-e2ac-53e6-a2af78659435
* Version Independent ID: 3ca3568e-bcab-1892-309e-31be43c9d33f
* Content: [Create a business rule in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-create-business-rule)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-create-business-rule.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-create-business-rule.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by Mattp123** [comment]
@hugobarona - The scope table in step 5 does indicate Entity as the item to select from the business rule editor. Entity is still the term used instead of table because the business rule editor hasn't been updated to reflect the current naming.
Closing issue.
