### ISSUE TITLE
Can a canvas app which is embedded in Opportunity form inside the CDS instance be exported inside a solution? 

### ISSUE THREAD

**Issue by GeorgianaMihaela** [MicrosoftDocs/powerapps-docs#294]
Can an existing canvas app which is embedded in Opportunity form inside the CDS instance be exported inside a solution? 

Repro steps:
1) in a source env: .crm.dynamics.com create a canvas app; 
2) embed it on a form (Opportunity for instance) - reference link https://docs.microsoft.com/en-us/business-applications-release-notes/october18/powerapps/extend-dynamics-365-entity-forms-with-embedded-canvas-apps 
3) Create a solution containing the canvas app 
4) export the solution (as managed preferably); 

5) In the second environment: import the solution created.
The import fails with error that the component type 300 is not present in the target. 

I get an error when importing the solution telling me: Cannot add a Root Component &lt;app name&gt; of type 300 because it is not in the target instance. 

Looking at the solutioncomponent: 300	Canvas App (https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/solutioncomponent?view=dynamics-ce-odata-9). 

Thank you very much for your input and answer to the question: can an existing canvas app which is embedded in Opportunity form be exported into a solution. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d19150a-8fcb-0b77-42a6-c270eedb4abc
* Version Independent ID: 5368606a-3ce7-a15e-749b-18288c5899d2
* Content: [Use solutions in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/use-solution-explorer#known-limitations)
* Content Source: [powerapps-docs/maker/common-data-service/use-solution-explorer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/use-solution-explorer.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by caburk** [comment]
@GeorgianaMihaela This scenario is supported today if you created the canvas app from your solution. Ie: initiate the canvas app creation from the model-driven form. It will get created in the same solution as your entity/form. Support for adding canvas apps that were not originally created from a solution is rolling out soon. @aneesmsft FYI

**Comment by GeorgianaMihaela** [comment]
> @GeorgianaMihaela This scenario is supported today if you created the canvas app from your solution. Ie: initiate the canvas app creation from the model-driven form. It will get created in the same solution as your entity/form. Support for adding canvas apps that were not originally created from a solution is rolling out soon. @aneesmsft FYI

Thank you for letting me know. 
Will you, if possible, have documented this: 
- Support for adding canvas apps that were not originally created from a solution is rolling out soon -- an estimate? 

Thank you.

**Comment by caburk** [comment]
This will be available June 1st or earlier through the UI, with a couple limitations that are documented above. Note, there is a PowerShell cmdlet available today that accomplishes this, we just haven't rolled out UI support. 
PowerShell: https://www.powershellgallery.com/packages/Microsoft.PowerApps.PowerShell/1.0.4

**Comment by GeorgianaMihaela** [comment]
Thank you for your reply and further info.
