### ISSUE TITLE
Broken link in Dataverse Event Framework page

### ISSUE THREAD

**Issue by juanpaez22** [MicrosoftDocs/powerapps-docs#2941]
Broken link in the "Tip" box that points to article "Find Messages and tables eligible for plug-ins using the Dataverse"
Link: https://powerapps.microsoft.com/en-us/blog/find-messages-and-entities-eligible-for-plug-ins-using-the-data-platform/ (results in 404)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2b1d5a-0912-5c6c-fca8-8b121ece9a8d
* Version Independent ID: da11363c-2e5f-d897-b0de-4d8400e3cfb2
* Content: [Event Framework (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/event-framework)
* Content Source: [powerapps-docs/developer/data-platform/event-framework.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/event-framework.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Red fixed it
