### ISSUE TITLE
Resolution Issue

### ISSUE THREAD

**Issue by ddeborja** [MicrosoftDocs/powerapps-docs#2942]
When is the resolution issue going to be fixed? iIs been 3 years and Sharepoint list forms are still barely usable without experimenting for hours for a variety of screen sizes. How is anyone expected to replace Infopath forms with 1/4 of the small screen and brower ZOOM out is the only solution for Large screens while its leaves a huge amount of white space. Flexible screen size needs to be implemented in Sharepoint Lists forms already.

**Comment by phecke** [comment]
@ddeborja Sorry to hear about your frustration. However, we are a documentation team and are not in the loop with regard to such matters. If you have any questions or issues about the documentation, please provide a link to the page. Thanks
