### ISSUE TITLE
it better fits to 'exist' than to 'not in'

### ISSUE THREAD

**Issue by Traenke5** [MicrosoftDocs/powerapps-docs#2946]
Hello, 

I think that this feature of FetchXML doesn't fit to the "not in" operator of SQL. It better fits to "exist" or "not exist", as it only can determine whether or not a row in a joined table exists. 

The "not in" operator in SQL has the capability to compare a (even computed) value of a parent query to a set of results of a child (or even independent) query. This is much more powerful and I already missed this capability in FetchXML pretty often. 

Nevertheless, thank you for your article. It's a good explanation of how to check the existance of a susequent record :)

Kind Regards, 
Uwe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d40ba12-ed87-f428-b1ba-66179bdc19fd
* Version Independent ID: c0840255-6308-d2b2-f17e-e00016bca833
* Content: [Use a left outer join in FetchXML to query for records 	„not in„ (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-fetchxml-left-outer-join-query-records-not-in)
* Content Source: [powerapps-docs/developer/data-platform/use-fetchxml-left-outer-join-query-records-not-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-fetchxml-left-outer-join-query-records-not-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@Traenke5 Thanks for the feedback.
