### ISSUE TITLE
In Limitations section there is a link that leads to 404

### ISSUE THREAD

**Issue by malaker** [MicrosoftDocs/powerapps-docs#2949]
![image](https://user-images.githubusercontent.com/1746427/147925287-ee0fd460-8fc4-40bf-9d02-7cf9e87853ea.png)

In the section link does not work.

(https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/introduction-to-entity-attributes.md#BKMK_LogicalAttributes) does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a7083d9-4e5d-be28-f943-699e40d4fff3
* Version Independent ID: 2ca8c470-6883-bc76-5793-04e2fc5c0024
* Content: [Calculated and rollup columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/calculated-rollup-attributes#limitations)
* Content Source: [powerapps-docs/developer/data-platform/calculated-rollup-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/calculated-rollup-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@malaker The broken link has been fixed. Thanks for the feedback.
