### ISSUE TITLE
Technical Details on PowerApps visual for Power BI

### ISSUE THREAD

**Issue by jdobrzen** [MicrosoftDocs/powerapps-docs#295]
Probably not the best place to reach out with a question like this, but I am giving a presentation at the Power BI World Tour Chicago on April 9-10th where I will be talking about the PowerApps visual for Power BI.

I was hoping I could sync up with someone that could provide some under the hood details about the visual? I think it would be great to provide some content about how the integration works between PowerApps and Power BI is accomplished.

Thank you!

**Comment by AFTOwen** [comment]
Hi, @jdobrzen. I've forwarded your request to the owner of this feature and asked him to respond. Closing this issue.
