### ISSUE TITLE
"Add a toggle control to turn the notifications on and off" code with errors

### ISSUE THREAD

**Issue by manuel-faria** [MicrosoftDocs/powerapps-docs#2952]
The code proposed in the section "Add a toggle control to turn the notifications on and off" is not updated. I'm getting errors in some of the functions, especially with the expression "gblUserRecord.User"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a8652a-8a0c-1ede-a79e-d736f34c4ad2
* Version Independent ID: 05b572ca-7830-5805-9d79-940a41973d71
* Content: [Add 'Notify me' settings to category in Bulletins app (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/bulletins-notify-me)
* Content Source: [powerapps-docs/teams/bulletins-notify-me.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/bulletins-notify-me.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **jshum**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This issue is in discussions internally, and documentation update may take some time. If you have any issues with the app, please don't wait and reach out to the [support teams](https://docs.microsoft.com/power-platform/admin/get-help-support) for an issue investigation and fix.

**Comment by georgesalmon** [comment]
> Thank you for reaching out. This issue is in discussions internally, and documentation update may take some time. If you have any issues with the app, please don't wait and reach out to the [support teams](https://docs.microsoft.com/power-platform/admin/get-help-support) for an issue investigation and fix.

Has there been any update on this? Code still comes up with errors and won't pull through

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please review the latest version of the [app templates and documentation](https://github.com/microsoft/teams-powerapps-app-templates). If the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
