### ISSUE TITLE
IfError incorrect information

### ISSUE THREAD

**Issue by c4g-wv** [MicrosoftDocs/powerapps-docs#2953]
Dear,

When using IfError in Power Apps (Canvas app), the hint shows syntax:
IfError(value, fallback, fallback, fallback, ...)
Hence, there is no replacement value for each value, it is just trying every argument until it finds one that doesn't error.
This contradicts the IfError syntax from this page, where it mentions a value and a replacement for each value.
Many of the examples on this page won't work as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e0983e-5863-d1eb-43e5-e6e9546c4e2b
* Version Independent ID: cc7abb21-14fd-04de-e1bd-2605697adcd3
* Content: [IfError, IsError, and IsBlankOrError functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-iferror)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-iferror.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-iferror.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jorisdg** [comment]
Thank you for reporting this. This is actually not an issue with documentation, but rather an issue with the intellisense showing in Power Apps. The team is working on a product fix for this as we speak.
