### ISSUE TITLE
No lblIssues_Header or lblNoIssues_Header

### ISSUE THREAD

**Issue by ndestates** [MicrosoftDocs/powerapps-docs#2955]
In the section Update Items Screen the command is to "Search for and select lblIssues_Header label in the Tree view".  Unfortunately, this does not appear to exist in the app and nor does lblNoIssues_Header appear.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006ea3e1-916f-fd30-90f1-7787c1459c37
* Version Independent ID: e09165f1-60a8-c746-a0de-3a9d0c6ea0bb
* Content: [Add hierarchy to inspection location (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/inspections-hierarchy-locations)
* Content Source: [powerapps-docs/teams/inspections-hierarchy-locations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/inspections-hierarchy-locations.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **jshum**

**Comment by KozyKoz08** [comment]
Has this issue been resolved as of 2/23/22?

**Comment by ThorAtInvoke** [comment]
Bumping this issue as this does not appear to be resolved. I have escalated this to Microsoft through the product channels. The release of the sample apps and the corresponding documentation is filled with issues that need to be addressed as these apps have been pushed to customers as 1st party apps and only the documentation calls them samples!

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This issue is in discussions internally, and documentation update may take some time. If you have any issues with the app, please don't wait and reach out to the [support teams](https://docs.microsoft.com/power-platform/admin/get-help-support) for an issue investigation and fix.

**Comment by ThorAtInvoke** [comment]
@tapanm-MSFT Thank you for the quick reply. I will reach out to support. To be clear, the main issue we're running into is that the Inspections app review button loads somewhere around the 9-10th item... so checklist with more steps render incorrectly. And keyboard input on notes seems to not work on some devices.

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please review the latest version of the [app templates and documentation](https://github.com/microsoft/teams-powerapps-app-templates). If the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
