### ISSUE TITLE
Where oh where has my little List Feature gone?

### ISSUE THREAD

**Issue by urklnme** [MicrosoftDocs/powerapps-docs#2956]
from the About Lists page:

_Enhanced view filter for lists
You can use Table Permissions if you want to secure records, but if you want to simply provide a filter as part of the set of filter options that is relevant to the current portal user, you can use the List feature._ 

Where is the List feature?  What is it?

the doc goes on to show and example of some sort, how does one get to that?  these are the things that would be HELPFUL.

PLEASE BE EXPLICIT, OVERT, DIRECT

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eb3ed13-9665-518f-7cc5-eec5e279708f
* Version Independent ID: 8a7aefa4-b9e0-ef52-7832-83c23cc790b1
* Content: [About lists - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/entity-lists#feedback)
* Content Source: [powerapps-docs/maker/portals/configure/entity-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/entity-lists.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. We have updated the doc to address this issue and hopefully it will be clearer to how the feature works and how to implement it.

**Comment by urklnme** [comment]
Congratulations on your new job Mr Doleman!   
Thanks for the update.

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 7, 2022 at 9:44 AM, ***@***.***> wrote:   


Thank you for bringing this to our attention. We have updated the doc to address this issue and hopefully it will be clearer to how the feature works and how to implement it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
