### ISSUE TITLE
Uses deprecated authentication

### ISSUE THREAD

**Issue by gordondan** [MicrosoftDocs/powerapps-docs#2957]
I came to this page hoping to learn how to setup oauth authentication because one of my apps using office365 auth broke. The example appears to be out of date.

  connectionString="Url=https://contoso.crm.dynamics.com; Username=someone@contoso.onmicrosoft.com; Password=password; authtype=Office365"/> -->  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 489a9802-ac7a-0809-eaf9-684bc1286be6
* Version Independent ID: ce185321-294f-683e-979b-8046f318800f
* Content: [Sample: Simplified connection quick start (Developer Guide for Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/sample-simplified-connection-quick-start)
* Content Source: [powerapps-docs/developer/data-platform/xrm-tooling/sample-simplified-connection-quick-start.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/xrm-tooling/sample-simplified-connection-quick-start.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by phecke** [comment]
@gordondan Thanks for pointing that out. I will correct it.
