### ISSUE TITLE
for Dataverse

### ISSUE THREAD

**Issue by shiba-hirofumi** [MicrosoftDocs/powerapps-docs#2958]
[フィードバックをこちらに入力してください]

What is the difference between the Dataverse Table and  the Entity ?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: aad05a7c-9a3a-912d-821d-f829e7e25e22
* Version Independent ID: 9b755e0d-24ca-b11f-925a-3ff8d5bbad8c
* Content: [開発者: Microsoft Dataverse の用語を理解する - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/developer/data-platform/understand-terminology)
* Content Source: [powerapps-docs/developer/data-platform/understand-terminology.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/understand-terminology.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment]
@shiba-hirofumi They are the same. The old terminology was "Entity", while the new name is "Table". We are aligning the developer documentation with the terminology used by Power Apps.
