### ISSUE TITLE
Alias Email Address

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#296]
Hi
This does not explain if the user has an alias email address, which email address is returned.
Regards

Nigel

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5ca5a0a-bc28-3938-fb72-bf24deaede99
* Version Independent ID: ade2f96a-f1ce-e96c-422c-a344ea5b0c84
* Content: [User function - PowerApps](https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/functions/function-user)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-user.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-user.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by dawidvanheerden** [comment]
Hi guys. Please note that the User().Email function returns the UPN and not the Email address. This is typically not a problem if the Email and UPN is the same, but it is important to be aware of if these are not the same. Below is a quick video to explain more.
https://youtu.be/6FU1xGxJK5w

**Comment by Nkrb** [comment]
Duplicate of  https://github.com/MicrosoftDocs/powerapps-docs/issues/1725. Closing the issue here. Please follow the other issue for updates
