### ISSUE TITLE
Create APP based on Contoso 2569907

### ISSUE THREAD

**Issue by CarlWilliams** [MicrosoftDocs/powerapps-docs#2960]
No, trying to connect to https://microsoft.sharepoint.com/teams/Contoso only gives you an error. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb0d2a4-5d04-386b-932d-abc281602d68
* Version Independent ID: da875c8e-11f3-ccc0-4348-4721933018a2
* Content: [Create a canvas app from a SharePoint list (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/app-from-sharepoint)
* Content Source: [powerapps-docs/maker/canvas-apps/app-from-sharepoint.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/app-from-sharepoint.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. That's an example URL. Please use your own or organization SharePoint site. Documentation example has been updated to avoid any confusions.
