### ISSUE TITLE
Misspelled error 2569891

### ISSUE THREAD

**Issue by ellix4u** [MicrosoftDocs/powerapps-docs#2963]
Misspelled error in 

```
IsBlankOrErrro( Blank() )
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e0983e-5863-d1eb-43e5-e6e9546c4e2b
* Version Independent ID: cc7abb21-14fd-04de-e1bd-2605697adcd3
* Content: [IfError, IsError, and IsBlankOrError functions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-iferror#isblankorerror)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-iferror.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-iferror.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content has been fixed and will reflect the changes soon.
