### ISSUE TITLE
Doesn't display in preview mode

### ISSUE THREAD

**Issue by dominicfoxy** [MicrosoftDocs/powerapps-docs#2965]
Not sure if I'm doing something incorrectly, or this is by design, but this only functions in the published app, and not the editing preview or "F5" menus. Makes it dang difficult to align text boxes so they work nicely for multiple languages. Also defaults to showing neither selected language, even in the published app, until the toggle is toggled
![EditMode](https://user-images.githubusercontent.com/22807664/148988230-d2fc62c0-b625-4bb0-ae72-f657a8afe933.png)
![Published](https://user-images.githubusercontent.com/22807664/148988231-53e0cd89-88ba-406e-be14-8178e87da2b2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b557d3-7967-698e-38e0-e28ad06df9df
* Version Independent ID: 55105264-7746-12ac-b3db-c34eb96b429f
* Content: [Build a multi-language app - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/multi-language-apps)
* Content Source: [powerapps-docs/maker/canvas-apps/multi-language-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/multi-language-apps.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **lunune**

**Comment by dominicfoxy** [comment]
Doesn't seem to matter if I set the varLanguage variable at runtime, it only changes when I toggle.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. That's right, since the variable is set on check or uncheck properties, toggle has to be used. It might be helpful if you reach out to our support teams using a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to help investigate and fix issues that you're facing.
