### ISSUE TITLE
Suggested fixes/updates for Steps 2 and 3 of the "Walkthrough: Write your first client script" page of the docs

### ISSUE THREAD

**Issue by bobbykemp** [MicrosoftDocs/powerapps-docs#2966]
[Linked step (Step 2)](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script?tabs=unified-interface%2Cunified-add-web-resource#step-2-add-your-javascript-code-in-a-script-web-resource) should be updated to reflect new UI of PowerApps for the "Unified Interface" tab; fix minor typos

Suggested content of linked step:

1. Navigate to [Power Apps](https://make.powerapps.com/).
2. In the left navigation pane, select **Dataverse**, then **Tables**.
3. From the list of tables, select the table where you want to add the JavaScript web resource.
4. Select the **Forms** tab; from the list of forms, select the desired form.
(include image of above steps 1-4)
5. Select **Form libraries** from the left navigation pane, and then select **Add library**.
(include image of above step 5)
6. Select **New Web Resource** to create a new JavaScript web resource.
7. In the **New web resource** pane, specify the **Name** and **Display Name** for your web resource. For example: "sampleScript.js" and "Sample: Walk-through Script".
8. Upload the file containing your JavaScript code by clicking the **Upload file** button. Uploading a JavaScript file should automatically fill the **Type** field to be "JavaScript (JS)".
(include image of New web resource pane, rather than the legacy popup)
9. Select the **Save** button to create the web resource containing your JavaScript code.
10. You should now be able to see your new web resource in the **Add JavaScript Library** modal window (you may need to click the **Refresh the list** link at the bottom of the modal).

[Linked step (Step 3)](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script?tabs=unified-interface%2Cunified-add-web-resource#step-3-associate-script-web-resource-to-a-form) should be updated to reflect new UI of PowerApps for the "Unified Interface" tab; fix minor typos

Suggested content of linked step:

1. Navigate to [Power Apps](https://make.powerapps.com/).
2. In the left navigation pane, select **Dataverse**, then **Tables**.
3. From the list of tables, select the table where you want to add the JavaScript web resource.
4. Select **Forms** tab from the command bar, and then select the form where you want to add a web resource.
(include image of above steps 1-4)
5. Select the **Events** tab. Select **Add library**.
(include image of above step 5)
6. Select the web resource that you just created from the list that appears. Click the **Add** button.
7. The **On Save** and **On Load** event handlers should now be available in the **Events** tab.
8. Select the **On Load** event handler and associate the function you want to achieve.
(**There is a typo in the current image** - the image shows the Function field populated with "SDK.formOnLoad" however in the above sections the namespace was defined as "Sdk". The current implementation will cause an error on browser loading of the form)
9. Select the **On Save** event handler and associate the function you want to achieve.
(**Same typo exists here as in previous image**)
10. If you wish to add the event handler for the **On Change** event, select the column and then select the **Event** tab.
(include image of above step 10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd626b7-e922-eecd-983c-3823afff4e04
* Version Independent ID: 376d0fc1-294a-660a-ea09-7de12f6dbe18
* Content: [Tutorial: Write your first client script in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script?tabs=unified-interface%2Cunified-add-web-resource#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by JimDaly** [comment]
@bobbykemp 
Thanks for your feedback.

Topic has been refreshed and reviewed.
