### ISSUE TITLE
Display Settings for Power BI embedded in Model Driven App

### ISSUE THREAD

**Issue by wh1009evr** [MicrosoftDocs/powerapps-docs#2967]
Hello, 

I have embedded a Power BI dashboard into a Model Driven Power App, but the viewable area of the dashboard is cramped. Can you please advise how to expand the viewable area so the intended UX is not compromised ? 

Thanks
WH

**Comment by Mattp123** [comment]
@wh1009evr - There isn't a way to manually change the viewing area for an embedded Power BI dashboard in an app. However, you can select 
![image](https://user-images.githubusercontent.com/21203819/150220560-41364fd1-308e-4119-bc23-07f2b35db3ac.png)
 (Focus mode button) to increase the viewing area of the embedded dashboard from within the model-driven app. You can also try increasing the browser size or you screen resolution to accommodate larger density dashboards. Otherwise, consider revising the dashboard to fit the app.

Closing issue.

**Comment by wh1009evr** [comment]
Thanks Matt, focus mode is at the individual visual / chart level though right not a full sheet / dashboard ? And I can only do full screen view in Power BI ?
How about the aspect ratio ? There is just a lot of white space in the dashboard screen when embedding PBI and feels like not much can be done about it.

From: Matt Peart ***@***.***>
Sent: Wednesday, January 19, 2022 5:01 PM
To: MicrosoftDocs/powerapps-docs ***@***.***>
Cc: Hong, William ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/powerapps-docs] Display Settings for Power BI embedded in Model Driven App (Issue #2967)



CAUTION: This email originated from outside of Evercore. Do not click links or open attachments unless you recognize the sender and are expecting the attachment or link.



@wh1009evr<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwh1009evr&data=04%7C01%7Cwilliam.hong%40evercore.com%7C9ac3e97be81d41d1d24208d9db972cbe%7Cdf2a9a6be42f47b29ebd6ce7a612e4f5%7C0%7C0%7C637782264601436867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p2H8tz4cNYVRBH515HWNZPTPv3zsyIwnVv9z6cAOZzM%3D&reserved=0> - There isn't a way to manually change the viewing area for an embedded Power BI dashboard in an app. However, you can select
[Image removed by sender. image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F21203819%2F150220560-41364fd1-308e-4119-bc23-07f2b35db3ac.png&data=04%7C01%7Cwilliam.hong%40evercore.com%7C9ac3e97be81d41d1d24208d9db972cbe%7Cdf2a9a6be42f47b29ebd6ce7a612e4f5%7C0%7C0%7C637782264601436867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uJL2CvDNkJhqIV%2FFV3lsinuwo5b9eLHRCKd8Z3DykBA%3D&reserved=0>
(Focus mode button) to increase the viewing area of the embedded dashboard from within the model-driven app. You can also try increasing the browser size or you screen resolution to accommodate larger density dashboards. Otherwise, consider revising the dashboard to fit the app.

Closing issue.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerapps-docs%2Fissues%2F2967%23issuecomment-1016908957&data=04%7C01%7Cwilliam.hong%40evercore.com%7C9ac3e97be81d41d1d24208d9db972cbe%7Cdf2a9a6be42f47b29ebd6ce7a612e4f5%7C0%7C0%7C637782264601446821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zDmxakRoaNSzcNiBtEkt0i5bP2LPUJhnXtiX08Bdo0M%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXIIDDC3QXYAJL4MRDQGAODUW4YBTANCNFSM5LXBEMOA&data=04%7C01%7Cwilliam.hong%40evercore.com%7C9ac3e97be81d41d1d24208d9db972cbe%7Cdf2a9a6be42f47b29ebd6ce7a612e4f5%7C0%7C0%7C637782264601446821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Nm8j82U4S35k5LJUHNyzTI%2BggGUHYxiYHUwf8G%2FhZEw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cwilliam.hong%40evercore.com%7C9ac3e97be81d41d1d24208d9db972cbe%7Cdf2a9a6be42f47b29ebd6ce7a612e4f5%7C0%7C0%7C637782264601456783%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R5%2B5%2F%2Bmu25dIQJ3Da6dxLltaeyeY89yuhvqfL1zhQEo%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cwilliam.hong%40evercore.com%7C9ac3e97be81d41d1d24208d9db972cbe%7Cdf2a9a6be42f47b29ebd6ce7a612e4f5%7C0%7C0%7C637782264601456783%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=53z9O8y6Qknoag3A8J3UoCKsOxgsc85GrByds6v03Xs%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________

The information contained in this email message is intended only for use of the individual or entity named above. If the reader of this message is not the intended recipient, or the employee or agent responsible to deliver it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please immediately notify us by email, and destroy the original message.

The information contained in this email and any attachment, including the names and email address of any and all recipients, is subject to Evercore’s GDPR Privacy Notice, the full context of which can be found here<https://www.evercore.com/gdpr-privacy-notice>. Thank you
