### ISSUE TITLE
Side bar "updatedProperties" reroutes to https://docs.microsoft.com/en-us/

### ISSUE THREAD

**Issue by Anzle** [MicrosoftDocs/powerapps-docs#2968]
When navigating the documentation on https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/
selecting "updatedProperties" from the sidebar redirects to https://docs.microsoft.com/en-us/ instead of a page on updatedProperties which i assume should be: https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/updatedProperties 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f0b7f33-ce10-1049-c8dd-148b58723671
* Version Independent ID: aa703e29-1af1-1bdd-ab83-5898dc8e158b
* Content: [UserSettings - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/usersettings)
* Content Source: [powerapps-docs/developer/component-framework/reference/usersettings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/usersettings.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
