### ISSUE TITLE
Update required?

### ISSUE THREAD

**Issue by alicain** [MicrosoftDocs/powerapps-docs#2970]
[Enter feedback here]
I cannot find the API permissions setting in the portal - is that because the screen shots here need updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11caa291-2e98-ac3a-d5d1-ecd416b93bdf
* Version Independent ID: 4f30cddd-8849-1887-ada0-a83a3d2a0027
* Content: [Tutorial: Register an app with Azure Active Directory (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/walkthrough-register-app-azure-active-directory)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by zkirby** [comment]
Screenshots don't need updating - ensure you're on the right page (app registration).

**Comment by phecke** [comment]
@alicain When editing your registered app, _API permissions_ is in the left navigation pane under _Manage_.
