### ISSUE TITLE
Job failed due to reason: The column in source configuration cannot be found in source data's schema

### ISSUE THREAD

**Issue by lasyan3** [MicrosoftDocs/powerapps-docs#2971]
Hi,

Migrating from Data Export to Azure Data Factory and following the documentation, I get this error:

{"StatusCode":"DF-Executor-InvalidInputColumns","Message":"Job failed due to reason: The column in source configuration cannot be found in source data's schema","Details":""}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc7cb5e-cba5-9e1f-0122-d11de71cc029
* Version Independent ID: 1b512d83-60b5-058a-765e-9602490cb95f
* Content: [Access Copy Dataverse data to Azure SQL - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/azure-synapse-link-copy-sql)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-copy-sql.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-copy-sql.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sama-zaki
* Microsoft Alias: **matp**

**Comment by sama-zaki** [comment]
Hi @lasyan3, will you please share a screenshot of your setup for the Source Settings in the data flow?

**Comment by lasyan3** [comment]
nevermind, azure data factory is a pain to use, I give up and will use a custom solution as a replacement for Data Export.
