### ISSUE TITLE
Incorrect metadata for msdyn_componentlayer msdyn_componentid column

### ISSUE THREAD

**Issue by MarkMpn** [MicrosoftDocs/powerapps-docs#2974]
The metadata for the `msdyn_componentid` column of the `msdyn_componentlayer` table is shown in the metadata to be a string type column. However, when records are retrieved from the table the values are guids rather than strings.

I believe either the metadata for this column should be a UniqueIdentifier or a Lookup column type, or the data provider should return string values to match the advertised metadata.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95ab6dfa-a227-61da-464a-92c8514e264e
* Version Independent ID: 778fa25b-a450-a307-1702-9dd8382d83c3
* Content: [msdyn_componentlayer table/entity reference (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/reference/entities/msdyn_componentlayer#feedback)
* Content Source: [powerapps-docs/developer/data-platform/reference/entities/msdyn_componentlayer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/reference/entities/msdyn_componentlayer.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment]
@MarkMpn The reference has been updated from the latest metadata. Let us know if you still see a problem. Thanks for the feedback.
