### ISSUE TITLE
Does not mention limitation of camera control to 480p 2572850

### ISSUE THREAD

**Issue by RescueWhale** [MicrosoftDocs/powerapps-docs#2975]
The camera control page fails to mention that the controls are limited to 480p. This is a critical bit of info that for us makes it unusable. It should be mentioned here!

https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Camera-Image-Resolution/idi-p/34977

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a452d825-76f2-9599-4431-23e4bc49ec44
* Version Independent ID: 5d9e457c-7096-211f-91bc-756bedd9f96a
* Content: [Camera control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-camera)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-camera.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-camera.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there, 

There was a line that the photos taken are not at full resolution and to use the add picture control.  I've updated the document to make this more clear that the maximum resolution is 640 x 480.

Thanks for calling this out.
