### ISSUE TITLE
is this the correct license if we want to bring back 20 GB of data every day from Dataverse to on-premise data warehouse?

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/powerapps-docs#2976]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf7655c-2fd9-3937-95d7-35d8d1dd4d52
* Version Independent ID: e432c020-de5b-ae94-b42d-e406dd5539ff
* Content: [Importing and exporting data - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/import-export-data)
* Content Source: [powerapps-docs/maker/data-platform/import-export-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/import-export-data.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@jlabustro - For specific user, storage, and licensing questions, contact a [Microsoft Power Apps sales representative](https://powerapps.microsoft.com/en-us/contact-us/?LCID=EN-US).

Closing issue.
