### ISSUE TITLE
REST download with chunking Range header in documentation is wrong

### ISSUE THREAD

**Issue by nageshbhat-msft** [MicrosoftDocs/powerapps-docs#2977]
The request header with chunking format seems to be wrong. it should just be Range: bytes=startByte-endByte

https://docs.microsoft.com/en-us/powerapps/developer/data-platform/file-attributes#example-rest-download-with-chunking 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/file-attributes?source=docs)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@nageshbhat-msft The documentation has been updated and should be correct now. Thanks for the feedback.
