### ISSUE TITLE
Typical Lacking

### ISSUE THREAD

**Issue by CarlWilliams** [MicrosoftDocs/powerapps-docs#2980]
Typically only little examples of things you may know but not real-life examples such as lookups on metadata fields. Nope, has to be about ice cream. That really helped a lot, gee thanks. NOT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c435aad5-5a0b-6070-1138-d80a13606122
* Version Independent ID: d9978c1c-e720-9586-8439-5b030f42794c
* Content: [Filter, Search, and LookUp functions in Power Apps (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-filter-lookup)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-filter-lookup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-filter-lookup.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your comments. Apart from video tutorial on this topic for filter, search and lookup, there are several other examples. If they aren't useful for the scenarios you're looking help for, perhaps the following topics might help with more elaborate scenarios. If they don't, and if there's any specific situation that you need help with, please refer to [Get Help + Support](https://docs.microsoft.com/power-platform/admin/get-help-support) to raise a service request and work with support teams for the issue you need help with.

- https://docs.microsoft.com/powerapps/maker/canvas-apps/sharepoint/scenarios-filter-search-list
- https://docs.microsoft.com/powerapps/maker/canvas-apps/sharepoint/scenarios-choice-to-lookup
- https://docs.microsoft.com/powerapps/maker/canvas-apps/create-update-collection
- https://docs.microsoft.com/powerapps/maker/canvas-apps/dependent-drop-down-lists
- https://docs.microsoft.com/powerapps/maker/canvas-apps/show-current-user
- https://docs.microsoft.com/powerapps/maker/canvas-apps/sharepoint/scenarios-lookup-list-permissions
- https://docs.microsoft.com/powerapps/maker/canvas-apps/power-apps-ideas-transform
- https://docs.microsoft.com/powerapps/maker/canvas-apps/sharepoint-scenario-generate-app
- https://docs.microsoft.com/powerapps/maker/canvas-apps/connections/connection-sharepoint-online
- https://docs.microsoft.com/powerapps/maker/canvas-apps/app-from-sharepoint
- https://docs.microsoft.com/powerapps/maker/canvas-apps/mixed-reality-spatial-test
- https://docs.microsoft.com/powerapps/maker/canvas-apps/multi-language-apps
- https://docs.microsoft.com/powerapps/maker/canvas-apps/sample-crisis-communication-app
- https://docs.microsoft.com/powerapps/maker/canvas-apps/add-editable-tables

**Comment by CarlWilliams** [comment]
Thanks Tapan, those will surely be helpful!!!

If you have anything on using Managed Metadata Fields within PowerApps, that would also be exceptionally helpful. I was able to create a simple list using MMD in PowerApps as the system created everything for me but I was unable to crerate from scratch to see how the system did it. I will likely find if I try to do it the way PowerApps created it, it wont work. Just like when PowerApps creates a Browse/View/Edit screen and uses Select(Parent) from the browse screen. BUT try an d do that manually? FORGET IT. Powerapps just sits there confused (no surprise there). So, where’s that “secret” code?

Tx

Carl Williams
