### ISSUE TITLE
PDF Viewer control with canvas enbedded in a portal?

### ISSUE THREAD

**Issue by urklnme** [MicrosoftDocs/powerapps-docs#2981]
Hello Experts, 

Any chance I could display a PDF in the PDF viewer control in a canvas app AND embed that canvas in my external portal?

for non-azure (no dynamics licenses) users to view?

portals desperately needs the ability to show a PDF in a form.

yes, I am desperate!!!   :D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5b06f20-00c5-9824-ecbf-70c03f1858c4
* Version Independent ID: 2270c9fe-bbcb-4cc6-90f1-485ebe8ee094
* Content: [PDF viewer control (experimental) in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-pdf-viewer)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-pdf-viewer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-pdf-viewer.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This scenario isn't supported. Also, embedding apps in a Power Apps portals page, or a custom website depends on the supportability of the underlining portal/website.
