### ISSUE TITLE
Possibly misconfigured TOC and bread crumb

### ISSUE THREAD

**Issue by rsbuckles** [MicrosoftDocs/powerapps-docs#2984]
If I navigate to https://docs.microsoft.com/en-us/powerapps/developer/data-platform/work-with-data I see the following:
![image](https://user-images.githubusercontent.com/51032818/149636253-5179afd7-614f-4063-8bfb-b2d47b482d5f.png)

Note the bread crumb at the top and note that the link circled in red does *not* have the angle bracket indicator to denote that there are sub-pages beneath it.

Now if I click on the link circled in red https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/overview I see the following:

![image](https://user-images.githubusercontent.com/51032818/149636460-c709ef3c-f1ca-4261-8bc6-4cdab397d408.png)

Possible issues:
(1) Shouldn't the bread crumb on the second page include "Work with data using code"? (red circle 1)
(2) Isn't the link to "Work with data using code" on the second page out of place?  I.e., it should not exist.  (red circle 2)
(3) Shouldn't all the pages on the second page (red circle 3) be listed on the first page under "Use Web API"?

I am not sure if the way it currently is is the way it is supposed to be, but if so, at least one user finds the effect bewildering.  All the pages in red circle 3 at the second link appear out of nowhere (because they are not shown as sub-pages on the first link), and because the bread crumb on the second link skips over where I was in the bread crumb on the first link, I can't tell to where I have been "transported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2bdc591-bc20-56dd-6734-64946b3b43c5
* Version Independent ID: 4a81abf6-a72e-7d4c-7be5-b5231c3ecb4c
* Content: [Work with data using code in Microsoft Dataverse (PowerApps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/work-with-data#feedback)
* Content Source: [powerapps-docs/developer/data-platform/work-with-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/work-with-data.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Thanks for your feedback.
We needed to have all the content related to web api in a separate TOC so that the reference content could be presented with it.
That reference content wasn't being included when you opened this issue, which probably contributed to it being bewildering. But it has been brought back. It was a trade-off, but we feel having the reference content appear together with the related content is a better experience overall.
