### ISSUE TITLE
idtable

### ISSUE THREAD

**Issue by nvythms** [MicrosoftDocs/powerapps-docs#2985]
Security
Dataverse uses Azure Active Directory **idtable** and access management mechanisms to help ensure that only authorized users can access the environment, data, and reports.

what is idtable??
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b499c8-9737-8797-ef78-b7d7e6b7c6e0
* Version Independent ID: 6d45767f-5743-0e80-e58b-4eff4afc2d9c
* Content: [Why choose Microsoft Dataverse? - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/why-dataverse-overview)
* Content Source: [powerapps-docs/maker/data-platform/why-dataverse-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/why-dataverse-overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @mmercuri
* Microsoft Alias: **mmercuri**

**Comment by Mattp123** [comment]
@nvythms - Thank you for your feedback. The word should be "identity." The article has been updated to reflect that.

Closing issue.
