### ISSUE TITLE
How to use 'pac auth create' command for D365 in China region?

### ISSUE THREAD

**Issue by kwkaiwang** [MicrosoftDocs/powerapps-docs#2987]
how to use pac auth create command for D365 in China region?

Below command does not work:
pac auth create -u https://xxxxx.crm.dynamics.cn/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b781f7a0-0e52-20f1-1249-754e4fcbc57e
* Version Independent ID: 03ee6216-36cd-74d6-8934-e307238f9b54
* Content: [Microsoft Power Platform CLI Auth command - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/cli/reference/auth-command)
* Content Source: [powerapps-docs/developer/data-platform/cli/reference/auth-command.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/cli/reference/auth-command.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by kwkaiwang** [comment]
I didn't find available parameter for '--cloud' which can support D365/PowerPlatlform in China region.

**Comment by kkanakas** [comment]
We will be adding China region in the next few months. Support for China cloud is not there.
