### ISSUE TITLE
ILogger object throws error when profiling plugin

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/powerapps-docs#2988]
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/application-insights-ilogger

Following the sample provided works unless profiling a plugin.  When profiling and debugging a plugin if there is an ILogger object the error occurs when trying to log information because it does not exist.

**Comment by phecke** [comment]
@samadane There is presently no support of ILogger within a plug-in profiling/debug scenario. I will add a note to the article.
