### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pkruk-microsoft** [MicrosoftDocs/powerapps-docs#299]
The "Work with XRM Tooling API" on this page points to non-existing location. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5df702-cd2a-fa01-f391-024b0012d2d1
* Version Independent ID: 4aa1b284-7e3b-1b89-d8b2-2e0f0cadb2e0
* Content: [Sample: Quick start for XRM Tooling API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/sample-quick-start-xrm-tooling-api#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/sample-quick-start-xrm-tooling-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/sample-quick-start-xrm-tooling-api.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by susikka** [comment]
@pkruk-microsoft Thanks for highlighting this. The link has been fixed and updated doc is live.

Closing this issue now.
