### ISSUE TITLE
Admin discrepancy around "Create Portal"

### ISSUE THREAD

**Issue by davinsgithub** [MicrosoftDocs/powerapps-docs#2992]
In the article, it is mentioned that "disable portal creation in a tenant by non-administrators", and then mentions non-admins as those those who don't have any of the these Azure roles: "Global Administrator", "Dynamics 365 administrator", "Power Platform admin". 
However on the https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-admin-roles page, permissions to "Create a Portal" section mentions that if the portal creation is disabled in the tenant, then only "Global Administrator" can create a portal. Although the "System Administrator" is mentioned under "Required roles and permissions in Microsoft Power Platform (both are required)", however no mention of the "Power Platform admin", so shouldn't it state that Admin ("Global Administrator", "Dynamics 365 administrator", "Power Platform admin") should be able to create the portal in that scenario, rather than just mentioning "Global Administrator". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3118bb-b0de-fe5d-5f33-03a4ba560da6
* Version Independent ID: 96da694b-38db-34ad-c48f-106dfc2a5f79
* Content: [Control portal creation in a tenant - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/control-portal-creation)
* Content Source: [powerapps-docs/maker/portals/control-portal-creation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/control-portal-creation.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for your feedback. We have updated the topic: https://docs.microsoft.com/power-apps/maker/portals/admin/portal-admin-roles
