### ISSUE TITLE
Issue with data synchronization (last changed value not detected)

### ISSUE THREAD

**Issue by lasyan3** [MicrosoftDocs/powerapps-docs#2993]
Hi,

I try to set up a pipeline for copying a dataverse table into an sql table but I have issues with the data synchronization.
I created the pipeline using the template given by Microsoft (targeting the out-of-the-box entity "contact").
I kept the default parameters generated by the template.

In short, the issue is that when the pipeline runs, it doesn't take the last data from the data lake.
More detailled issue :
When the pipeline executed for the first time, all the lines were in the destination table.
But then I updated the lastname of a contact in Power Apps, then I waited for Azure Synapse Link to detect the change and save it in the Azure Data Lake Storage, and finally I ran second time the pipeline.
But after the successful run, the row in the destination table is still with the old lastname.

Thanks for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc7cb5e-cba5-9e1f-0122-d11de71cc029
* Version Independent ID: 1b512d83-60b5-058a-765e-9602490cb95f
* Content: [Access Copy Dataverse data to Azure SQL - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/azure-synapse-link-copy-sql)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-copy-sql.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-copy-sql.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sama-zaki
* Microsoft Alias: **matp**

**Comment by lasyan3** [comment]
### Screenshots showing the configuration of the pipeline and the data flow:
![az01](https://user-images.githubusercontent.com/7955594/150426739-f10a64c4-7e9d-4367-b5e5-7e889479d5ae.png)
![az02](https://user-images.githubusercontent.com/7955594/150426740-68ac2033-aa29-42f3-be6a-3b10c8d6e0ad.png)
![az03](https://user-images.githubusercontent.com/7955594/150426742-76bb2d16-c37c-4d67-9211-612eaa63d251.png)
![az04](https://user-images.githubusercontent.com/7955594/150426722-7df8fac6-b47d-449d-8f55-5c9cd05c5071.png)
![az05](https://user-images.githubusercontent.com/7955594/150426726-89c03b20-761e-4391-bc3a-97750a85e276.png)
![az06](https://user-images.githubusercontent.com/7955594/150426727-3048b858-d1b1-4548-8c1e-ebd5ac5f9c7a.png)
![az07](https://user-images.githubusercontent.com/7955594/150426728-9d22f408-c198-4677-b102-d86adcae2b90.png)

### The value of the lastname in Dynamics is set to "PaillassetestF":
![az08](https://user-images.githubusercontent.com/7955594/150426730-d31cc3f8-2362-48ab-a015-c7640a56cd0c.png)

### In Azure Data Lake, the data update has been properly detected:
![az09](https://user-images.githubusercontent.com/7955594/150426732-00602c1a-291a-468f-8718-5eb7d6a9cf44.png)

### The content of the last file show the correct value:
![az10](https://user-images.githubusercontent.com/7955594/150426734-075fda38-d6d3-41f0-ada1-999afce392b9.png)

### But finally the row in the sql destination table still show the old value:
![az11](https://user-images.githubusercontent.com/7955594/150426737-8ac41205-7957-424a-bd23-1c61107b136a.png)

**Comment by sama-zaki** [comment]
Hi @lasyan3, thank you for sharing the details. Since the data flow is connecting to you Azure Data Lake directly and not to your Azure Synapse Analytics workspace database, it is using the data files in the snapshot folder. The snapshot folder contains read-only files that are updated on an hourly basis. For more information about snapshots, please read this documentation - https://docs.microsoft.com/en-us/powerapps/maker/data-platform/azure-synapse-link-data-lake#view-your-data-in-azure-data-lake-storage-gen2.

**Comment by lasyan3** [comment]
Hi @sama-zaki thanks for your quick answer.
So, does it mean that to get the most uptodate data at a quicker rate than hourly basis, I should configure the Azure Synapse Link to send the data to Azure Synapse Analytics instead of an Azure Data Lake?

**Comment by sama-zaki** [comment]
Correct! For more information on setting up your synapse link with a Synapse workspace, please read this documentation - https://docs.microsoft.com/en-us/powerapps/maker/data-platform/azure-synapse-link-synapse.

**Comment by lasyan3** [comment]
Ok understood, thanks for the clarification!
