### ISSUE TITLE
Cannot save flow with Dataverse connector if service limit has been exceeded

### ISSUE THREAD

**Issue by cokJon** [MicrosoftDocs/powerapps-docs#2997]
I haven't found any reference to this, but it appears that when you exceed the service limits by some amount, you are stopped from saving flows with Dataverse connectors for a period of time with the following error:

The client 'xxx' with object id 'xxx' has permission to perform action 'Microsoft.Logic/workflows/write' on scope '/subscriptions/xxx/resourceGroups/xxx-xxx/providers/Microsoft.Logic/workflows/xxx'; however, it does not have permission to perform action 'Microsoft.KeyVault/vaults/deploy/action' on the linked scope(s) '/subscriptions/xxx/resourceGroups/tip0-pslacds-cancentr-rg/providers/Microsoft.KeyVault/vaults/tip0-pslacds-cancentr-kv' or the linked scope(s) are invalid.

I wish this had been documented somewhere. My flows were not throttled during this time.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6c11a1-c9f6-a904-f49a-0fedbe9f511f
* Version Independent ID: 7db20846-7922-23d4-f261-4c54e61b6913
* Content: [Service protection API limits (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/api-limits)
* Content Source: [powerapps-docs/developer/data-platform/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/api-limits.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
This topic is specifically about service protection limits for Dataverse APIs.

I don't see any connection between the issue you are reporting.
Recommend you send your feedback regarding this page [Requests limits and allocations](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations), or open a support request.

**Comment by cokJon** [comment]
This error was only happening to flows containing Dataverse connectors. It was not happening with other premium connectors or standard connectors. I verified that I could save other flows as a part of my troubleshooting. The linked article states that there are Dataverse specific limits which I suspect this.
