### ISSUE TITLE
PCF component logic sample has errors

### ISSUE THREAD

**Issue by ApexNDSU** [MicrosoftDocs/powerapps-docs#2999]
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript#implementing-component-logic

On this type script code for updateview function, 'controlValue' - error comes - Property 'controlValue' does not exist on type 'IInputs'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by ArijitCloud** [comment]
@ApexNDSU I was also facing the same issue.

If you modify the property in `ControlManifest.Input.xml`
`<property name="controlValue" display-name-key="controlValue_Display_Key" description-key="controlValue_Desc_Key" of-type-group="numbers" usage="bound" required="true" />`

and then run 
`npm run build`

This will regenerate IInputs with ControlValue property and solve the issue.

**Comment by JimDaly** [comment]
@noazarur-microsoft 
Seems like a problem with the sample code.

**Comment by JimDaly** [comment]
I have reviewed and updated this content since this feedback came in. If this is still an issue, please let us know.
