### ISSUE TITLE
Entity categories and relationships

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#30]
It would be helpful if there was a summary showing the various categories of entities and if there was an actual entity relationship diagram so that we get a visual overview of the numerous entities that are available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c43201-4b30-80e5-26d0-1c89327eaffc
* Version Independent ID: 3b59f9b7-d9e1-7759-965a-1d0efa5fb4e2
* Content: [About Entity Reference (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/reference/about-entity-reference#relationships)
* Content Source: [powerapps-docs/developer/common-data-service/reference/about-entity-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/reference/about-entity-reference.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by Mattp123** [comment]
Thank you for your request to enhance the documentation. This request has been recorded and it will be considered for a future update to the documentation.
Closing issue.
