### ISSUE TITLE
Camera/Barcode Orientation

### ISSUE THREAD

**Issue by csteelatgburg** [MicrosoftDocs/powerapps-docs#300]
When the app opens the camera to scan a barcode, it opens with the red line to center the barcode in the same direction as the screen orientation. 

For example, if I am in portrait mode and click the button to open the barcode scanner, the line will be horizontal. However, if I need to scan a barcode which is vertically aligned rotating the device 90 degrees switches the camera to landscape mode (thus the line becomes horizontal again). 

I am building an app to collect serial numbers and the labels will often be aligned vertically, not horizontally. Is there a way to lock the orientation of the camera? Alternatively, could a control be added to the screen to rotate the scanner's orientation on the screen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7944b4d0-c3be-afa0-4af1-21c9c27b56e2
* Version Independent ID: c2ca93fd-9817-8300-fcc4-a6999659e0a2
* Content: [Barcode-scanner control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-new-barcode-scanner)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
Thanks for your comment, @csteelatgburg. You can lock the orientation of the app by selecting **File** > **App settings** > **Screen size + orientation** > **Lock orientation**.

cc: @fikaradz

**Comment by csteelatgburg** [comment]
Locking the screen orientation of the application does not lock the orientation of the camera when it opens. Please re-open this issue.

**Comment by AFTOwen** [comment]
@csteelatgburg This works for me on an iPhone. Are you using Android?
@fikaradz Does the barcode scanner differ between devices?
Cheers.

**Comment by csteelatgburg** [comment]
My testing has been on Android.

**Comment by fikaradz** [comment]
This is the native barcode scanner, so to prevent orientation you would have to lock the orientation on your device settings (quick swipe from top on Android).

**Comment by csteelatgburg** [comment]
Verified that locking the screen orientation locks the scanner on Android.
Thanks.
