### ISSUE TITLE
link to content cannot be downloaded 2586117

### ISSUE THREAD

**Issue by charlesrugg** [MicrosoftDocs/powerapps-docs#3002]
[
(https://aka.ms/o4ia0f) takes me to bing.com and not to the downloaded content
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbd516b-05bb-575f-93fa-59f1fe5f57ff
* Version Independent ID: c2181b3d-e0b3-a263-d9df-0d46b9ed7b59
* Content: [Integrate Power Apps, Power Automate, and Power BI with SharePoint Online - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-scenario-intro)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/sharepoint-scenario-intro.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, the obsolete reference has been removed. Thank you for your feedback.
