### ISSUE TITLE
Passing Hints in 'options' not supported in the published fetch xsd

### ISSUE THREAD

**Issue by AgileXRM** [MicrosoftDocs/powerapps-docs#3003]
According to this page, SQL Hints can be passed through by using the 'options' attribute. 
But the latest published fetch xsd ([here](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/fetchxml-schema)) does not include 'options'. In our case, we are trying to validate a fetch xml entered by a user against the xsd in code and when it includes 'options', it fails. 
Does this mean that the published xsd is not the latest?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec389848-4dc1-bf26-67ee-29b17c6737ff
* Version Independent ID: 8e79173d-0ad2-7ca5-c58c-a14a59d2d957
* Content: [Improve FetchXML request performance - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/fetchxml-performance)
* Content Source: [powerapps-docs/developer/data-platform/fetchxml-performance.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/fetchxml-performance.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by phecke** [comment]
@AgileXRM I am looking into getting the latest Fetch XSD schema.

**Comment by phecke** [comment]
@AgileXRM The published schema has been updated. 'options' is now there. Thanks for the feedback.
