### ISSUE TITLE
Published Fetch xsd is an old version?

### ISSUE THREAD

**Issue by AgileXRM** [MicrosoftDocs/powerapps-docs#3004]
The fetch xsd published here does not allow include use of 'options' attribute or 'latematerialize' attribute, but according to this other [page](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/fetchxml-performance), it should!
Our requirement is to validate the fetch xml entered by a user against the xsd and it seems the published xsd is older than what is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40fba020-a32b-6e31-9c76-a4226187b059
* Version Independent ID: 70388ff8-9442-84c7-0a56-ff397cb65109
* Content: [FetchXML schema (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/fetchxml-schema)
* Content Source: [powerapps-docs/developer/data-platform/fetchxml-schema.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/fetchxml-schema.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@AgileXRM I am looking into getting the latest schema.

**Comment by phecke** [comment]
@AgileXRM The published schema has been updated.
