### ISSUE TITLE
Workflow doc suggestion

### ISSUE THREAD

**Issue by markflaws-ctl** [MicrosoftDocs/powerapps-docs#3005]
Please consider a clarifying statement that field entry and the form assistant are not available for fields that are set to Read-only in the underlying form.  After a few hours, I finally realized this and once I unlocked the fields in the form, I was able to set them in the workflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40811755-622d-0ed0-da30-2b3d5417263e
* Version Independent ID: c6c2b566-7d17-95f9-9ee4-5075a4714dc4
* Content: [Configure real-time workflow stages and steps in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/configure-workflow-steps)
* Content Source: [powerapps-docs/maker/data-platform/configure-workflow-steps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/configure-workflow-steps.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@markflaws-ctl,
As per the article column properties section of the Add, move, or delete fields article that describes the **Read-only** property: (https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-move-or-delete-fields-on-form#column-properties)

<html>
<body>


Display options | Read-only | When selected, the column value is not editable.
-- | -- | --



</body>
</html>

The form assistant was a feature in the classic forms that is no longer available. [Classic forms](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/main-form-presentations#classic-forms)

Closing issue.

**Comment by markflaws-ctl** [comment]
Thank you Matt.  The form assistant is still required for real-time workflows, which are still supported and have no modern replacement.
