### ISSUE TITLE
Missing essential details.

### ISSUE THREAD

**Issue by simes1** [MicrosoftDocs/powerapps-docs#3006]
I couldn't get this to work with the details in the article.  I think it is missing the following:

1. The value for {{callback}}:
        app://58145b91-0c36-4500-8554-080854f2ac97/
2. To uncheck the option (only available in the Postman windows client) "Authorise using browser"
        
![image](https://user-images.githubusercontent.com/11423243/150929066-d48417f6-9f8f-4bd1-bac6-0347c3c5ea40.png)

It would be even more useful to know how to use Postman _Online_ to talk to D365 but I could not get this to work (Authorize using browser option not present).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Set up a Postman environment (Microsoft Dataverse for Apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@simes1 
Hmm. The value for the {{callback}} variable must literally be `https://callbackurl` for this to work using the provided clientid.
You shouldn't need to register your own Azure AD application, use the provided clientid.`51f81489-12ee-4a9e-aaae-a2591f45987d`, the only variable that is specific to you is the {{url}}.

With the instructions here, I've never had to check the **Authorize using browser** checkbox.

Postman keeps changing the UI, but I think the core parts still work. But we should update the screenshots anyway.

I've heard people say this:

> I find it much easier to use tabbed postman that uses the current browser cookie automatically provided you are logged into the dataverse org in another tab.
>
>https://chrome.google.com/webstore/detail/tabbed-postman-rest-clien/coohjcphdfgbiolnekdpbcijmhambjff?hl=en
