### ISSUE TITLE
Should this image  to be updated?

### ISSUE THREAD

**Issue by bigsnowballhehe** [MicrosoftDocs/powerapps-docs#3007]
Because the formContext have got lot of new feature. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2208a05b-4caf-bf5c-516c-68f88dd6cf7d
* Version Independent ID: 92120838-ee35-30c0-01a6-23408c7f1e26
* Content: [formContext.ui (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by JimDaly** [comment]
This image is for FormContext.ui. 
What new FormContext.ui features are you referring to?

**Comment by JimDaly** [comment]
@bigsnowballhehe 
I discussed this with the feature team, they also weren't clear about any new features that would require this image to be updated. I'm going to close this b/c not actionable. Please let us know what you thought would need to be updated.
