### ISSUE TITLE
Updating Gateway

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#301]
The Troubleshooting section recommends updating the gateway but does not tell us how to do this. Please provide instructions for updating the gateway. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c103d76-66ed-dcb3-4b6c-904e59143932
* Version Independent ID: fccd2495-7ac4-d2ab-dc8e-c08992a6af12
* Content: [Understand on-premises data gateways for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-reference#troubleshooting-1)
* Content Source: [powerapps-docs/maker/canvas-apps/gateway-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/gateway-reference.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@arthiriyer Is there an upgrade process for gateways other than uninstalling and reinstalling? Thanks.

**Comment by AFTOwen** [comment]
From @arthiriyer: Users can upgrade to a newer version of the gateway by downloading the gateway installer and running it on the gateway machine. This process will upgrade the gateway to the newer version. If the same installer is run on a machine where there was no previous gateway install, then this would help with a brand new install or a recover/restore scenario.

@DeanGross As @mgblythe mentioned in [this issue](https://github.com/MicrosoftDocs/powerapps-docs/issues/302), these docs are undergoing a consolidation as tracked in [this issue](https://github.com/MicrosoftDocs/powerbi-docs/issues/938).
