### ISSUE TITLE
version 1.11.3 breaks auth to dataverse

### ISSUE THREAD

**Issue by nickb-ct** [MicrosoftDocs/powerapps-docs#3011]
When creating a connection profile it fails to connect to dataverse.

When using the following command it fails, whereas this worked with version 1.10.4

pac auth create -n Dev -u https://xxxxxxxxxxx.crm4.dynamics.com -id xxxxxxxxxxxxxxxxx-xxxxx-xxxxx-xxx -cs xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -t xxxxxxxxxxxxxxxxxxxxxxx

Authentication successfully created.
Validating connection...
Connected to...Microsoft PowerPlatform CLI
Version: 1.11.3+g1e02241

Error: Failed to connect to Dataverse

**Comment by bher2000** [comment]
We are also getting this same error

`PS C:\Users\jenkins> pac auth create --applicationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --clientSecret xxxxxxxxxxxxxxxxxxxxxx --cloud UsGovHigh --tenant xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --url https://xxxxxxxx.crm.microsoftdynamics.us --name dev
Authentication successfully created.
Validating connection...
Connected to...Microsoft PowerPlatform CLI
Version: 1.11.3+g1e02241

Error: Failed to connect to Dataverse

Usage: pac auth create [--name] [--kind] [--url] [--username] [--password] [--applicationId] [--clientSecret] [--tenant] [--cloud]

  --name                      The name you want to give to this authentication profile (maximum 12 characters) (alias: -n)
  --kind                      The kind of authentication profile you are creating, defaults to Dataverse (alias: -k)
  --url                       The resource URL to connect to (alias: -u)
  --username                  Optional: The username to authenticate with; shows AAD dialog if not specified (alias: -un)
  --password                  Optional: The password to authenticate with (alias: -p)
  --applicationId             Optional: The application id to authenticate with (alias: -id)
  --clientSecret              Optional: The client secret to authenticate with (alias: -cs)
  --tenant                    Tenant id if using application id & secret. (alias: -t)
  --cloud                     Optional: The cloud instance to authenticate with (alias: -ci)
                              Values: Public, Tip1, Tip2, UsGov, UsGovHigh, UsGovDod, Mooncake`

**Comment by kkanakas** [comment]
We pushed out a hotfix yesterday, please update your pac cli instance using pac install latest or update your VScode extension

**Comment by phecke** [comment]
@nickb-ct 

Thanks for contacting us. Note that in the future, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.
 
Closing this issue.
