### ISSUE TITLE
designating data types

### ISSUE THREAD

**Issue by yosoyx** [MicrosoftDocs/powerapps-docs#3012]
This is more of a request for functionality, I guess.
Currently if you include image in the column name the resulting app will assign an image control to the field.
Likewise, it would be useful to have the same for things like hyperlinks and dates, just to name a few.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42de6ba6-a4e0-fb79-cd90-b86e9b047e82
* Version Independent ID: e4251860-19f2-817b-bd5a-71d4bb50b6b5
* Content: [Format a table in Excel and naming tips - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/how-to-excel-tips?source=docs)
* Content Source: [powerapps-docs/maker/canvas-apps/how-to-excel-tips.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/how-to-excel-tips.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For such requests, please reach out to the [Power Apps Ideas community forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) where you can submit functionality asks, or vote for existing asks.
