### ISSUE TITLE
Am I missing some steps?

### ISSUE THREAD

**Issue by cassien808** [MicrosoftDocs/powerapps-docs#3016]
I followed step by step the instructions, but I got stuck where it asked to create the Category column to have a lookup to the Bulletin Category.  Did not see that listed as an item to connect to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a8652a-8a0c-1ede-a79e-d736f34c4ad2
* Version Independent ID: 05b572ca-7830-5805-9d79-940a41973d71
* Content: [Add 'Notify me' settings to category in Bulletins app (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/bulletins-notify-me)
* Content Source: [powerapps-docs/teams/bulletins-notify-me.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/bulletins-notify-me.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **jshum**

**Comment by lawrencezhoujp** [comment]
I had the same problem.
