### ISSUE TITLE
CSV File Data Type Detection 

### ISSUE THREAD

**Issue by szerongtham** [MicrosoftDocs/powerapps-docs#3017]
[Enter feedback here]
Hello, 

I have received a customer's feedback based on inadequate explanation of dataflow based on data types in the Microsoft documentation. The customer was working with a csv file and had 12000 rows of data with different records per row. Not all fields were filled per row. When creating a dataflow and importing data via csv, using the data type detection 'based on first 200 rows' caused her data to break after the first 200 rows. They went back and forth to figure out what is happening, even exported the csv file to plain text but could not find a solution. What she needed to do was to ensure  data type detection 'based on the entire data set'. We should write a word of caution for csv file 'If CSV file does not have consistent data record across the entire data set, please ensure data type detection is 'based on entire data set'.' Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ef5ecf-6d78-d852-f9ec-bf452864f0f5
* Version Independent ID: 9a080f0e-f168-ee88-2b32-22e55e95ae4c
* Content: [Create and use dataflows in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-and-use-dataflows)
* Content Source: [powerapps-docs/maker/data-platform/create-and-use-dataflows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-and-use-dataflows.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@szerongtham - Your feedback has been forwarded to the engineering team for consideration.

Closing issue.
