### ISSUE TITLE
Portal - "Site Settings" have Website as required field by default

### ISSUE THREAD

**Issue by davinsgithub** [MicrosoftDocs/powerapps-docs#3019]
As per the article to set the Global Site Setting, create Site Setting by providing Name, Value and Description, however Website is a required field by default, so there isn't a way to create Global Site Setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a0ce28-b400-f305-888c-22be66dbfdbc
* Version Independent ID: 80079d40-0c02-0768-677f-119c73426565
* Content: [Configure site settings for portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-site-settings)
* Content Source: [powerapps-docs/maker/portals/configure/configure-site-settings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-site-settings.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. We have updated the topic. Global settings are configured using a different table than site settings (and do not have a field for Website).  In the Portal Management app, go to Website -> Settings to update Global Settings.
