### ISSUE TITLE
Multiple, overlapping, inconsistent pages - please consolidate Gateway information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#302]
Please integrate, consolidate or cross-reference all of the content about Data Gateways. There are currently page at https://docs.microsoft.com/en-us/power-bi/service-gateway-getting-started and https://docs.microsoft.com/en-us/flow/gateway-manage. They are similar but different, since the data gateways are shared between Power BI, PowerApps and Flow, the documentation should be shared also. There is different good stuff in all 3 locations, but some inconsistencies in format and topics make it much harder than necessary to get a thorough understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042aa853-3571-5081-a83b-25235a4949fa
* Version Independent ID: d4049a41-6d7e-0ebd-8c17-68223a8e327b
* Content: [Manage an on-premises data gateway for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-management#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/gateway-management.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/gateway-management.md)
* Service: **powerapps**
* GitHub Login: @archnair
* Microsoft Alias: **archanan**

**Comment by mgblythe** [comment]
Thanks @DeanGross, we are currently in the process of consolidating these docs.
