### ISSUE TITLE
Page Link is Inaccurate

### ISSUE THREAD

**Issue by gotoreports** [MicrosoftDocs/powerapps-docs#3020]
The link, Save to OneDrive is not accurate.  What is displayed and demonstrated here is how to save to SharePoint.  The original mixed reality video on YouTube on this topic demonstrates how to save to OneDrive in the demo and references this page to copy and paste the code in for the dynamic file content (to properly format the file contents from Power Apps to OneDrive).  The code doesn't exist.  I reached and out the author of the mixed reality video on Twitter and she responded the code doesn't exist here anymore but try SharePoint demo here.  I have been unable to find anyone that has successfully taken a mixed reality photo in Power Apps and upload it to OneDrive.  Having the steps here would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be6dda1c-852e-7f8b-48b5-e0c2a6e6711a
* Version Independent ID: 19b9ed6c-04dc-5e44-48a6-75ef12f91028
* Content: [How do I find and run apps in Power Apps? - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/)
* Content Source: [powerapps-docs/user/index.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/index.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@gotoreports Thank you for the feedback. The topic that you sent feedback on is this: https://docs.microsoft.com/powerapps/user/. However, from your comments, it seems you're actually referring to a different topic. Which topic are you referring to?

Thanks,
Mints
Power Apps Docs Teams

**Comment by mduelae** [comment]
@gotoreports since I haven't heard back I'm going to close this issue. 

Thanks,
Mints
