### ISSUE TITLE
Custom Entity List - errors

### ISSUE THREAD

**Issue by ulrikkeakerbak** [MicrosoftDocs/powerapps-docs#3021]
Hi.

When using this code to render entity lists with my cases it renders with errors. 

"Status reason" for the case render this error message in the table: "Liquid error: Object of type 'Adxstudio.Xrm.Web.Mvc.Liquid.OptionSetValueDrop' cannot be converted to type 'System.String'."

The pagination renders this error: "Liquid error: Object of type 'System.Int32' cannot be converted to type 'System.String'."
            

![image](https://user-images.githubusercontent.com/11438199/151654728-02aa08d7-d5e1-44dc-8b89-18e356c5bc44.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46dc750-10f1-6755-5ff0-86156b9db110
* Version Independent ID: d1335f42-fabb-61c0-5d38-a718b28d7a65
* Content: [Render the list associated with the current page - Power Apps](https://docs.microsoft.com/en-gb/powerapps/maker/portals/liquid/render-entity-list-current-page)
* Content Source: [powerapps-docs/maker/portals/liquid/render-entity-list-current-page.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/liquid/render-entity-list-current-page.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
Thank you for your feedback. The code did not have a provision to handle status columns. The code has been updated. 

The following lines have been added:

```
{% elsif attr_type == 'status' %}
   {{ attr.label | h }} 
```

Closing the issue.
