### ISSUE TITLE
Incorrect Hyperlink on "Portal templates" Page

### ISSUE THREAD

**Issue by change-agent** [MicrosoftDocs/powerapps-docs#3024]
The below link goes to the wrong page:

>For creating a portal with any of the above templates, go to [Create a portal with an environment containing customer engagement apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/create-portal).

It should point to [this page](https://docs.microsoft.com/en-us/powerapps/maker/portals/create-dynamics-portal).

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6275ab57-197d-4871-7003-9d5dddc0caa2
* Version Independent ID: c2a49e45-ba1d-f1d4-ff52-b9d1fd4466fe
* Content: [Portal templates - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/portal-templates)
* Content Source: [powerapps-docs/maker/portals/portal-templates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/portal-templates.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. I have updated the link and it should be live in a few hours.
