### ISSUE TITLE
Export control does not ask for file name

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerapps-docs#303]
@e-gallis commented on [Sat Mar 30 2019](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/issues/5)

On step 4 in the example above, it says that clicking on the Export control allows one to specify the name of the file into which the data will be exported to.
It's not !
When clicking on the Export control, the data is immediately exported to a zip file with the name of the data collection specified in the Data property of the Export control.
I'd rather have what's described in the example: that the Export control asks me for a file name before exporting the data.
(Tested on Chrome 73.0.3683.86)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: bb525c3c-c019-d110-76dd-1e166b77ba60
* Version Independent ID: 6c1b5220-ee4c-0d91-fae8-ab76b8043a27
* Content: [Contrôles Export et Import : référence - PowerApps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/controls/control-export-import#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-export-import.md](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/blob/live/powerapps-docs/maker/canvas-apps/controls/control-export-import.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by CeciAc** [comment]
Hi team, 
the user is reporting the actual "Export" action doesn't behave as described in the document

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content is updated to reflect updated behavior. Please allow some time to reflect changes.
