### ISSUE TITLE
Can't validate file type in attachment OnAddFile property

### ISSUE THREAD

**Issue by kishore075** [MicrosoftDocs/powerapps-docs#3033]
Hi Team, I am trying to validate file type before uploading file to Dataverse table, but unfortunately OnAddFile property in Attachment control doesn't trigger any actions. My app below for review

![image](https://user-images.githubusercontent.com/63319261/152188339-23b5c9b3-d59f-4441-9eb0-e386f4e18e29.png)
![image](https://user-images.githubusercontent.com/63319261/152188444-48c3a7c5-b1d0-4b5a-b57f-d7f4ad3be6da.png)
![image](https://user-images.githubusercontent.com/63319261/152188661-0c8faa98-65e3-4ec2-bbe0-0dd49e1a23ce.png)
![image](https://user-images.githubusercontent.com/63319261/152188793-df8da348-c47f-4d8c-b92f-bd5383afc8cb.png)

No notification is shown when I upload file. Please help. Tried to trigger textbox change property as well. But still same no notification received on text change in textbox.

Regards,
Kishore Kumar

**Comment by phecke** [comment]
@kishore075 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.
We accept incorrect or missing documentation and sample code issues.
Closing this issue.

**Comment by kishore075** [comment]
Thanks phecke, will try to raise request in link suggested by you.
