### ISSUE TITLE
Git credentials are only accepted after an app is published

### ISSUE THREAD

**Issue by jalodon** [MicrosoftDocs/powerapps-docs#3034]
Wanted to give this new feature a go. Created a new app, saved it, tried to connect to a new test-repo in both azure and github, created PAT's and tried filling in all matter of variations of my email and usernames, to no avail. Only after first publishing the app do the git credentials work and does it start the process of connecting to my repo. Not a big issue as only a percentage will actually connect to git before publishing, but to top off the information here, this specific situation should be described.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dcec321-a287-a483-241d-69b147737f23
* Version Independent ID: 1dcec321-a287-a483-241d-69b147737f23
* Content: [Co-authoring in canvas apps (experimental) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/git-version-control#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/git-version-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/git-version-control.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/

Closing this issue.
