### ISSUE TITLE
Country Code List out of date

### ISSUE THREAD

**Issue by s1m0nj** [MicrosoftDocs/powerapps-docs#3036]
Hi,

The page is now out of date.   The latest supported list of countries is below, the page is missing GG and JE

AD,AE,AF,AG,AI,AL,AM,AO,AQ,AR,AS,AT,AU,AW,AX,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BL,BM,BN,BO,BR,BS,BT,BV,BW,BY,BZ,CA,CC,CD,CF,CG,CH,CI,CK,CL,CM,CN,CO,CR,CV,CW,CX,CY,CZ,DE,DJ,DK,DM,DO,DZ,EC,EE,EG,ER,ES,ET,FI,FJ,FK,FM,FO,FR,GA,GB,GD,GE,GF,GG,GH,GI,GL,GM,GN,GP,GQ,GR,GS,GT,GU,GW,GY,HK,HM,HN,HR,HT,HU,ID,IE,IL,IM,IN,IO,IQ,IS,IT,JE,JM,JO,JP,KE,KG,KH,KI,KM,KN,KR,KW,KY,KZ,LA,LB,LC,LI,LK,LR,LS,LT,LU,LV,LY,MA,MC,MD,ME,MF,MG,MH,MK,ML,MM,MN,MO,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY,MZ,NA,NC,NE,NF,NG,NI,NL,NO,NP,NR,NU,NZ,OM,PA,PE,PF,PG,PH,PK,PL,PM,PN,PR,PS,PT,PW,PY,QA,RE,RO,RS,RU,RW,SA,SB,SC,SE,SG,SH,SI,SJ,SK,SL,SM,SN,SO,SR,ST,SV,SZ,TC,TD,TF,TG,TH,TJ,TK,TL,TM,TN,TO,TR,TT,TV,TW,TZ,UA,UG,UM,US,UY,UZ,VA,VC,VE,VG,VI,VN,VU,WF,WS,YE,YT,ZA,ZM,ZW

If this is not updated many app soruce solutions will not be deployable to Jersey and Guernsey.

These were recently added app source deployment team.

Many thanks
Simon Jackson
si@xrm.je 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2c7898-1e5f-184c-bb89-8acdf96c0023
* Version Independent ID: f46bf08e-14dc-4111-c74e-db374f377566
* Content: [Step 3: Create an AppSource package for your app (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/create-package-app-appsource#create-inputxml-file)
* Content Source: [powerapps-docs/developer/data-platform/create-package-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/create-package-app-appsource.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Fixed!

**Comment by s1m0nj** [comment]
Thank you, as solution authors copy the countries into their App Source packages. More and more App Source solutions can be deployed for tenants registered in Jersey and Guernsey.
