### ISSUE TITLE
Помилка на сторінці "Що таке Power Apps?"

### ISSUE THREAD

**Issue by KostyaTretyak** [MicrosoftDocs/powerapps-docs#3038]
Помилка у фразі:

> а також платформу даних

Правильний варіант:

> а також платформа даних

---
#### Відомості про документ

⚠ *Не змінюйте цей розділ. Він необхідний для зв’язування питань на платформах docs.microsoft.com ➟ GitHub.*

* ID: a5a87d70-1f25-0a75-bc11-f2c079f2083c
* Version Independent ID: 7b1e729a-d4b6-2786-2ac7-c9e1c516a815
* Content: [Що таке Power Apps? - Power Apps](https://docs.microsoft.com/uk-ua/powerapps/powerapps-overview)
* Content Source: [powerapps-docs/powerapps-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/powerapps-overview.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Dealgan12** [comment]
Fixing in latest published files.
