### ISSUE TITLE
Deutsche Version 

### ISSUE THREAD

**Issue by n0kaa** [MicrosoftDocs/powerapps-docs#3039]
Fehler in der Dokumentation in https://docs.microsoft.com/de-de/powerapps/maker/developer-plan
![image](https://user-images.githubusercontent.com/45858125/152322850-370d3002-4e3e-45be-ac79-a308443e9cef.png)
"unddem"
"Kann **die** mich mit meinem persönlichen Konto registrieren?"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: aa958930-fb79-62a4-3f46-c1adf9f8349a
* Version Independent ID: e2f2d173-ca57-6f83-a2d6-ab381846e5b6
* Content: [Für Power Apps-Entwicklerplan registrieren - Power Apps](https://docs.microsoft.com/de-de/powerapps/maker/developer-plan)
* Content Source: [powerapps-docs/maker/developer-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/developer-plan.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @alaug
* Microsoft Alias: **evlew**

**Comment by Dealgan12** [comment]
Fixed in German on latest files
