### ISSUE TITLE
Steps shared to enable experimental or preview features are NOT correct 

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/powerapps-docs#3040]
The steps shared to enable experimental or preview features are NOT correct along with screen shots. 
Below is what we get in  actual UI,

![image](https://user-images.githubusercontent.com/58035849/152330117-8fa2385d-067f-442a-9829-06648202afdf.png)

 and in docs we have below UI:

![image](https://user-images.githubusercontent.com/58035849/152330283-dd9b08ad-66af-4ef1-913c-1ca18ef3c752.png)

Please share the exact steps , how to enable preview, experimental features etc. from Power Apps and entire tenant settings (please share clear steps and screen shots of each )

Greg Lindhorst
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8fa993-1374-0fa3-9a44-b7e88eb93621
* Version Independent ID: 400f9ae3-21f1-e727-c396-1d1e2d6c1296
* Content: [Understand experimental, preview, and retired features in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-experimental-preview#controlling-which-features-are-enabled)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-experimental-preview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/working-with-experimental-preview.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation is updated to reference canvas apps. Power Apps Studio for canvas apps is different from model-driven app designer.
