### ISSUE TITLE
Using Xrm in in standalone web resources loaded from sitemap - Dynamics 365 CE

### ISSUE THREAD

**Issue by noorahmad-code** [MicrosoftDocs/powerapps-docs#3041]
Hello

Please I need input on deprecation of ClientGlobalContext.js.aspx according to the below article. We are using parent.Xrm in standalone web resource for an integration. I am confused about "window.parent.Xrm.WebApi.online.****" will these sort of sdk methods still work. According to: https://docs.microsoft.com/en-us/power-platform/important-changes-coming:

_"Including a reference to ClientGlobalContext.js.aspx does not make the Xrm object available in HTML web resources. Therefore, scripts containing Xrm.* methods aren’t supported in HTML web resources. parent.Xrm.* will work if the HTML web resource is loaded in a form container. However, for other places, such as loading an HTML web resource as part of the SiteMap, parent.Xrm.* also won’t work."_

So parent.Xrm won't work but what about window.parent.Xrm being used in a HTML web resource as part of the SiteMap/standalone html web resource.

https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx

Would appreciate some clarification.

**Comment by mspilde** [comment]
We are moving the timeline out for deprecating this feature.  There is currently no ETA so you can expect to continue to use ClientGlobalContext.js.aspx.  We are in the process of updating the docs to remove the deprecation announcement.

**Comment by noorahmad-code** [comment]
@mspilde so if the plan to deprecate this future is entirely dropped or it is just postponed for now. We are working on a very big implementation of Dynamics 365 and we have few requirements to show information in standalone webresources and we would heavily rely on  ClientGlobalContext.js.aspx. Would appreciate if you can confirm if the plan to deprecate is dropped or just postponed for now.

Thanks

**Comment by mspilde** [comment]
Yes, this will be deprecated in the future, I don't have an ETA on when and we will do our best to make it the least impactful as possible to you and other makers that have or have plans to build solutions using it in current environments and apps.

**Comment by noorahmad-code** [comment]
@mspilde thank you for the response so we hope even when it will be deprecated there Microsoft will give some alternate solution for existing implementation around of ClientGlobalContext.js.aspx because using the standalone webresources is really important for Dynamics 356 integration implementationss

**Comment by phecke** [comment]
@noorahmad-code We will be updating the documentation very soon.
