### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by armanschwarz** [MicrosoftDocs/powerapps-docs#306]
Instructions on where to get / how to install this plugin would be helpful.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ff08bd-922a-f9a7-3db3-d40c59072549
* Version Independent ID: 32afc780-f1a7-7ff6-c5f6-2686781e0931
* Content: [Open entity data in Excel - PowerApps](https://docs.microsoft.com/en-au/powerapps/maker/common-data-service/data-platform-excel-addin#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-excel-addin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-excel-addin.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by iangpgh** [comment]
I have added link to Excel add-in (https://appsource.microsoft.com/en-us/product/office/WA104380330?tab=Overview) and link to Add or remove add-ins in Excel (https://support.office.com/en-us/article/add-or-remove-add-ins-in-excel-0af570c4-5cf3-4fa9-9b88-403625a0b460). Will be published in a few days.

**Comment by Mattp123** [comment]
Closing issue.
