### ISSUE TITLE
Docs の記述訂正について

### ISSUE THREAD

**Issue by WakakoWatanabe** [MicrosoftDocs/powerapps-docs#3063]
この Docs ページに記載の機能は、現在サポートされておりません。
実際に、[フォームのカスタマイズ] セクションから操作を行っても Docs と同じフォームになりません。
結果として、ポータル上には公開情報に記載のような位置情報のついたフォームを表示させることはできません。
サポートされていない機能と明記がないまま公開情報として記載されていると、ユーザー 様は気付かないので利用できる機能と認識してしまいます。

ユーザー 様の混乱を防ぐため、以下の公開情報のお見直し、または削除をご検討ください。
Title : 位置情報の追加
URL : https://docs.microsoft.com/ja-jp/powerapps/maker/portals/configure/add-geolocation

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 28b6f5c0-06ea-6234-b4ef-aabd11a127fc
* Version Independent ID: 3d4bcfcc-290c-d084-422e-e8ed8192ca4f
* Content: [位置情報の追加 - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/portals/configure/add-geolocation)
* Content Source: [powerapps-docs/maker/portals/configure/add-geolocation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/add-geolocation.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by Dealgan12** [comment]
This is not a specific localization issue. The user is mentioning that there are a number of features not supported on the page and following the steps outlined doesn't match what happens in the product.

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. This is a supported feature but there is a bug when rendering the map using a form on a web page. The map will appear when displaying the form in a modal window. The bug has been logged.
