### ISSUE TITLE
About Docs description correction

### ISSUE THREAD

**Issue by WakakoWatanabe** [MicrosoftDocs/powerapps-docs#3064]
The features described in this Docs page are currently not supported.
In fact, operations from the Form customization section will not result in the same form as in Docs.
As a result, we will not be able to display a form with location information on the portal as described in the public information.
If a feature is listed as public article without stating that it is unsupported, users will not notice it and will assume that it is available.

To prevent confusion among users, please consider reviewing or removing the following public article.
Title : Adding location information
URL : https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/add-geolocation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b6f5c0-06ea-6234-b4ef-aabd11a127fc
* Version Independent ID: 3d4bcfcc-290c-d084-422e-e8ed8192ca4f
* Content: [Add geolocation - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/add-geolocation)
* Content Source: [powerapps-docs/maker/portals/configure/add-geolocation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/add-geolocation.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. This is a supported feature but there is a bug when rendering the map using a form on a web page. The map will appear when displaying the form in a modal window. The bug has been logged.
