### ISSUE TITLE
Where is connection data stored?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/powerapps-docs#3066]
When providing access to particular entity record with access team, where is this connection stored? in which table or columns?

Also, if connected, "button Share" web using Web Form, where does it saves the share connection information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e79dc75-29c6-2f8b-1860-1110fc2e6fbf
* Version Independent ID: 8992a69b-30d7-222b-41ee-06ccd0aba949
* Content: [Use access teams and owner teams to collaborate and share information (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information)
* Content Source: [powerapps-docs/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@hkusulja Connection informatiooooooon is stored in the PrincipalObjectAccess table. Customers do not have access to that table.

I cannot comment on the button question as that is not related to developer docs. Try logging an issue in the maker or admin doc feedback.

**Comment by hkusulja** [comment]
@phecke 
Ok, can you please write in documentation that there is (it exists) the PrincipalObjectAccess table, and there is no access.

Thank you
