### ISSUE TITLE
User-created access team, without API call

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/powerapps-docs#3067]
When using "User-created access team" and web Form, how we can trigger the mentioned GrantAccessRequest , without c# / .NET / programming?  Is it possible via some additional "button" or Flow/PowerAutomate, or at least JavaScript / API call ?

Where we can see the information about record what is connected access team to that record? https://github.com/MicrosoftDocs/powerapps-docs/issues/3066

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e79dc75-29c6-2f8b-1860-1110fc2e6fbf
* Version Independent ID: 8992a69b-30d7-222b-41ee-06ccd0aba949
* Content: [Use access teams and owner teams to collaborate and share information (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information)
* Content Source: [powerapps-docs/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@hkusulja You can use any programming language that works with a RESTful service like our Web API. You can also use any application that has that security feature built-in such as a model-driven app or the Power Platform admin center.
 
https://docs.microsoft.com/en-us/powerapps/user/access-team
https://docs.microsoft.com/en-us/power-platform/admin/about-team-templates

**Comment by hkusulja** [comment]
Hello, but is there a way that use a native button in Web Form interface without any programming? or is it mandatory to have a program?
I am talking without team templates, since for my case is user-created access teams.
