### ISSUE TITLE
isDeleted column for append only writes doesn't exist

### ISSUE THREAD

**Issue by joslange** [MicrosoftDocs/powerapps-docs#3069]
The correct column name for deleted rows for the append-only write setting should be **IsDelete**, not isDeleted
![image](https://user-images.githubusercontent.com/57677822/153162278-f5be87b2-5033-4781-a18e-5f57cfe4b44f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1d5f787-fa5e-c749-4414-a8a14309510e
* Version Independent ID: 7d5c052e-dd60-caa8-740e-eb9cf774ed9a
* Content: [Azure Synapse Link Advance Configuration - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/azure-synapse-link-advanced-configuration)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-advanced-configuration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-advanced-configuration.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by JasonHQX** [comment]
Thanks for the feedback. The doc is updating

**Comment by Mattp123** [comment]
PR fixing this merged. Closing issue.
