### ISSUE TITLE
The link for Configuration Migration Tool under item 4. does not work

### ISSUE THREAD

**Issue by dev717** [MicrosoftDocs/powerapps-docs#3072]
The link in item four 'Configuration Migration Tool' does not take you anywhere.  CLI link does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7fa454-57bc-86bf-74cd-c51b622607a4
* Version Independent ID: 3efa0e3c-d9f2-cc50-aa9d-f77f2ca7dc3f
* Content: [Migrate portal configuration - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/migrate-portal-configuration?tabs=CLI)
* Content Source: [powerapps-docs/maker/portals/admin/migrate-portal-configuration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/migrate-portal-configuration.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. The link was supposed to take you to the Configuration Migration tool (CMT) section in the same document, but there is an issue with linking to tabbed sections.  The link has been updated to take you to the section that shows both options (CLI and CMT tabs). Apologies for the confusion.
