### ISSUE TITLE
Scan Code - return to scanner mode

### ISSUE THREAD

**Issue by Tikkanen42** [MicrosoftDocs/powerapps-docs#308]
The scanner should be able to scan a barcode, run the "OnScan" event and then return back to the scanner mode without having to his the scan button again.  Having to hit the "scan" button each time is time consuming when you are scanning multiple items.  Unless i'm missing something.

**Comment by fikaradz** [comment]
This is currently not possible, but we'll consider it as a feature improvement.

**Comment by Tikkanen42** [comment]
I was able to get this to work. I will post my work around tomorrow

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
