### ISSUE TITLE
Is formContext.ui.footerSection.setVisible() deprecated?

### ISSUE THREAD

**Issue by filcole** [MicrosoftDocs/powerapps-docs#3084]
Should formContext.ui.footerSection.getVisible() be deprecated as per https://docs.microsoft.com/en-us/power-platform/important-changes-coming#form-footers-in-model-driven-apps-wont-be-supported-with-the-2021-release-wave-2

`formContext.ui.footerSection.setVisible(true)` no longer does anything

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd04dd6d-bffc-290f-a878-55bcb633f98a
* Version Independent ID: fb4143e0-ceed-54ae-96da-8652189883e9
* Content: [formContext.ui.footerSection item (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-footersection)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-footerSection.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-footerSection.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by JimDaly** [comment]
Yes it is deprecated. Will remove this from the docs.
