### ISSUE TITLE
Links to samples are broken

### ISSUE THREAD

**Issue by SteveGoodman** [MicrosoftDocs/powerapps-docs#3089]
[Enter feedback here]

Under the sample code heading, the links to the "[Insert or update a record using Upsert](https://docs.microsoft.com/en-us/samples/browse/)" and [ProductUpsertSample.cs](https://code.msdn.microsoft.com/Insert-or-update-a-record-aa160870/sourcecode?fileId=136218&pathId=1243320355) are broken.

I think they should be pointing to ultimately to this page -> https://github.com/microsoft/Dynamics365-Apps-Samples/blob/master/samples-from-msdn/Upsert/ProductUpsertSample.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed55813-1248-7edf-c33c-ce7a4783f9e6
* Version Independent ID: 32bc8340-84c9-8114-673f-481b3b09470f
* Content: [Use Upsert to insert or update a record (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/use-upsert-insert-update-record)
* Content Source: [powerapps-docs/developer/data-platform/use-upsert-insert-update-record.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-upsert-insert-update-record.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Agree
@phecke Can you make this change?

**Comment by KumarVivek** [comment]
@SteveGoodman The correct link to the sample is this: https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/C%23/InsertRecordUsingUpsert/InsertRecordUsingUpsert

This is updated in the doc as well.
