### ISSUE TITLE
The description seems outdated: "Support for up to 500 teams."

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/powerapps-docs#3092]
> Support for up to 500 teams.

I believe the latest information is following.
https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#capacity-limits

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffcc4d8-a8f0-83fe-3003-e9f9fcedadbd
* Version Independent ID: 6f4f89a2-fbc8-a2de-f16c-68e3dec4fa8e
* Content: [Microsoft Dataverse for Teams overview - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/overview-data-platform)
* Content Source: [powerapps-docs/teams/overview-data-platform.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/overview-data-platform.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by NHelgren** [comment]
Thank you for the feedback, an update has been made and will appear shortly.

**Comment by Mattp123** [comment]
@MiyukiAmino - The article has been updated to reflect the current capacity. Closing issue.
