### ISSUE TITLE
bad link in page text

### ISSUE THREAD

**Issue by dnagirl** [MicrosoftDocs/powerapps-docs#3094]
This link, https://docs.microsoft.com/en-us/reference/entities/template.md gives a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a85f605d-b018-72d0-5316-8d6e5056d9ca
* Version Independent ID: b1a95941-e2f4-ea50-d79b-f951209957aa
* Content: [Email activity tables (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/email-activity-entities)
* Content Source: [powerapps-docs/developer/data-platform/email-activity-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/email-activity-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed.
