### ISSUE TITLE
Recommend changing the title of this article

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/powerapps-docs#3097]
I recommend changing the title of the article to: 

Navigating to a custom page using client API

dropping the words "and from" because this article doesn't appear to cover navigating **from** a custom page.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d5076fa-40a8-fbef-e5a9-1ba9db2ad4e6
* Version Independent ID: f7fb3acd-e8f3-27e8-456e-5a5c79d38997
* Content: [Navigating to and from a custom page in your model-driven app using client API - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/navigate-to-custom-page-examples)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/navigate-to-custom-page-examples.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/navigate-to-custom-page-examples.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @aorth
* Microsoft Alias: **nabuthuk**

**Comment by adrianorth** [comment]
Approved

**Comment by JimDaly** [comment]
Checked in topic name change
