### ISSUE TITLE
Manager review expense reports?

### ISSUE THREAD

**Issue by kucster** [MicrosoftDocs/powerapps-docs#31]
Hello, I really like this solution but I'm wondering what would be an easy way for approves to review the expense report. The "approve" link takes you to just the "summary page". It would be nice if below we could also see the line items

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by AFTOwen** [comment]
@kucster Thanks for the feedback!
@caburk Any thoughts?

**Comment by caburk** [comment]
There are a couple options here. If you want to continue pointing the "approve" link to SharePoint, you can customize the SharePoint form in PowerApps (click the customize button on the SharePoint "Expenses" list). 

The other option is deep linking to the Expense record directly in the PowerApp. This article describes how to do that. You'd could then pass that parameter to your Flow or send the email directly from the PowerApp like in the blog post: https://powerapps.microsoft.com/en-us/blog/powerapps-deep-linking/

**Comment by kucster** [comment]
Awesome, thank you so much for your continued help!

**Comment by AFTOwen** [comment]
@kucster We're going to close this issue, but please reopen it if we've closed it in error. Cheers!

cc: @caburk
