### ISSUE TITLE
Using Office 365 Groups

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#310]
Please add information about how Office 365 groups can, or cannot, be used. This is not clear from the current instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fb8dba-da1c-6845-d301-c3b18a6b98ef
* Version Independent ID: a5d1fd66-fe5b-f52d-47de-6af3c71928f7
* Content: [Share a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@DeanGross As I responded in [this issue](https://github.com/MicrosoftDocs/powerapps-docs/issues/69), the first paragraph of the topic lists the ways in which you can specify users with whom to share an app. That list doesn't include Office 365 groups. Closing as duplicate.
