### ISSUE TITLE
Javascript of "redirect a user to a default page after signing in" is invalid

### ISSUE THREAD

**Issue by LuHao-007** [MicrosoftDocs/powerapps-docs#3114]
Hello,

The Javascript of "redirect a user to a default page after signing in" is invalid.

https://docs.microsoft.com/en-us/powerapps/maker/portals/faq#how-do-i-redirect-a-user-to-a-default-page-after-signing-in-

{% if user %}
//if any user logs in
<script>
window.location.href='./new-page-1/'
</script>
{% else %}
//Home web page code, if you don't want to display the page when the user is being redirected
{% endif %}
//Home web page code, if you want to display the page when the user is being redirected

I have set it in the Home Web Template, and have sync configuration in the Power Apps portal studio, but after I login the portal, it shows the webpage before login instead of the new-page-1 webpage I set, as if this Javascript is not set at all.
![image](https://user-images.githubusercontent.com/52907759/154879165-55ba2311-e7ab-4948-a969-2f22e64c1a2e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb68e1d-5c5a-fe4d-bfe0-324744299f6f
* Version Independent ID: c8b2432d-a350-824c-222b-cd8911d1af8b
* Content: [Frequently asked questions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/faq#how-do-i-redirect-a-user-to-a-default-page-after-signing-in)
* Content Source: [powerapps-docs/maker/portals/faq.yml](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/faq.yml)
* Service: **powerapps**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by nickdoelman** [comment]
Thank you for your feedback. There was a change to the default page template used for the home page. See https://docs.microsoft.com/en-us/power-apps/maker/portals/liquid/redirect-a-user-homepage for updated instructions.
