### ISSUE TITLE
Need to be updated to framework versions greater than 4.6.2

### ISSUE THREAD

**Issue by boletus151** [MicrosoftDocs/powerapps-docs#3115]
It will be good to update this:

new PlatformParameters(
                    PromptBehavior.SelectAccount   // Prompt the user for a logon account.
                )

with 5.0 and/or 6.0 versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-console-app-csharp?tabs=adal)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@boletus151 
Thanks for your feedback. Sorry for the delay in responding.
There was a .NET 6 version of the sample, but the topic wasn't highlighting it.
Will update this topic.
