### ISSUE TITLE
Search this view detail

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/powerapps-docs#3121]
Hello,
It is not said if "Search this view" would look into any field of the view, or only fields that are "Search fields"
Would it be possible to bring this clarification?
In my case, displaying the Description of email message, search this view is not working to look for key words.

Thank you

P-O
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e9258f-4c21-9d52-9940-cada6c70db50
* Version Independent ID: 1f5619dd-aea0-d0d4-34a9-a7e0e036faf8
* Content: [Explore data in a view on a grid page - Power Apps](https://docs.microsoft.com/en-us/powerapps/user/grid-filters#use-search-on-a-grid)
* Content Source: [powerapps-docs/user/grid-filters.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/grid-filters.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@popujol I've asked our internal team to clarify this. Please stay tuned for an update.

Thanks,
Mints

**Comment by sriharibs-msft** [comment]
Thank you for the feedback. We will consider this enhancement to better clarify "search this view" behavior.
