### ISSUE TITLE
Headning and content not aligned

### ISSUE THREAD

**Issue by Hennie001** [MicrosoftDocs/powerapps-docs#3122]
Heading:
**Transform your InfoPath forms to Power Apps**
Transform is not discussed AT ALL in the article. REBUILD YOUR INFOPATH FORMS would be more accurate.

And GITHub 0 when are you moving to Modern Web? :-)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce87949-54e8-f4ed-5d49-e11758e582b8
* Version Independent ID: 31d52576-021f-cdcf-bb49-c1c5d7ed85b2
* Content: [Transform your InfoPath form to Power Apps - Power Apps](https://docs.microsoft.com/en-za/powerapps/maker/canvas-apps/transform-infopath)
* Content Source: [powerapps-docs/maker/canvas-apps/transform-infopath.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/transform-infopath.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed.
