### ISSUE TITLE
Remove ”on-time-passcode"

### ISSUE THREAD

**Issue by tanimani** [MicrosoftDocs/powerapps-docs#3124]
[English]
In Japanese site, there is still remain content about limitation of on-time-passcode.

[Japanese]
Power Apps は、[Azure AD 直接フェデレーション](https://docs.microsoft.com/ja-jp/azure/active-directory/b2b/direct-federation) または [メールのワンタイム パスコード認証](https://docs.microsoft.com/ja-jp/azure/active-directory/external-identities/one-time-passcode) を使用して認証するゲストを認識できません。

英文サイトでは、メールのワンタイムパスコードの記述が削除されています。
正しくは、以下のとおりです。
Power Apps は、[Azure AD 直接フェデレーション](https://docs.microsoft.com/ja-jp/azure/active-directory/b2b/direct-federation)を使用して認証するゲストを認識できません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b5b79de9-91fd-adc9-2515-d2bb84cfd2b2
* Version Independent ID: 62c9fd03-2d88-475f-c857-75647f263a81
* Content: [キャンバス アプリをゲスト ユーザーと共有する (ビデオを含む) - Power Apps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/share-app-guests#considerations-and-limitations-for-guest-access)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app-guests.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/share-app-guests.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @alaug
* Microsoft Alias: **alaug**

**Comment by Dealgan12** [comment]
There can be two weeks from when English is updated to when translation is complete. This is file is currently out for translation with the latest updates.
