### ISSUE TITLE
Erro de digitação em seção

### ISSUE THREAD

**Issue by CarolineCastro2** [MicrosoftDocs/powerapps-docs#3125]
Olá, o documento está com erro de digitação na seção: "Criar, editar ou salvar uma exibição suando a localização avançada herdada"
https://docs.microsoft.com/pt-br/powerapps/user/advanced-find#create-edit-or-save-a-view-using-legacy-advanced-find
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 349c57f6-1804-db23-3c38-f4c9dc5adaf2
* Version Independent ID: 11943f1c-46af-e0ec-c834-fb796e31f844
* Content: [Localização avançada - Power Apps](https://docs.microsoft.com/pt-br/powerapps/user/advanced-find)
* Content Source: [powerapps-docs/user/advanced-find.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/advanced-find.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by Dealgan12** [comment]
Fixed in latest published version
