### ISSUE TITLE
Use Task.ConfigureAwait(false).GetAwaiter().GetResult()?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3129]
In "Unhandled exception in plugin" it is suggested to use [Task.ConfigureAwait(false)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1.configureawait?view=netframework-4.6.2).[GetAwaiter()](https://docs.microsoft.com/en-us/dotnet/api/system.aggregateexception?view=netframework-4.6.2).[GetResult()](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.taskawaiter-1.getresult?view=netframework-4.6.2)

The documentation for [GetResult()](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.taskawaiter-1.getresult?view=netframework-4.6.2) mentions in "Definition": 

> This API supports the product infrastructure and is not intended to be used directly from your code.

I was wondering why using this was suggested, if developers shouldn't use it. If I use this line of code and press F1 in VS to open the documentation for it, the browser opens a different [GetResult()](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.configuredtaskawaitable-1.configuredtaskawaiter.getresult?view=netframework-4.6.2)

It's a different GetResult(), but there is still the hint in the Remarks.

I'm not sure if it is really okay to use GetResult()?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9289ed-ac35-9cd1-1197-81e61f5154da
* Version Independent ID: 455f1b05-1d84-8822-8a81-de64529053ca
* Content: [Troubleshoot plug-ins (Microsoft Dataverse for Apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/troubleshoot-plug-in#unhandled-exception-in-plugin)
* Content Source: [powerapps-docs/developer/data-platform/troubleshoot-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/troubleshoot-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
If I understand correctly, you are calling out that the link in the docs to `GetResult` is actually to [TaskAwaiter<TResult>.GetResult Method](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.taskawaiter-1.getresult?view=netframework-4.6.2).

It should instead link to [ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult Method](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.configuredtaskawaitable-1.configuredtaskawaiter.getresult?view=netframework-4.6.2)

The object returned is different. This incorrect link in the doc is confusing.

We should change the target of the last part of the link. 
Sound right to you?

**Comment by darshSWL** [comment]
I see two issues.

First issue: 
The link doesn't seem to be correct. Exactly what you are describing.

Second issue: 
The docs for both GetResult methods say that GetResult should not be used.
> "This API supports the product infrastructure and is not intended to be used directly from your code."
> "This type and its members are intended for use by the compiler."

The documentation here (troubleshoot-plugin.md) recommends to use the GetResult method. That's where I see a conflict between both documentations.
If the GetResult documentation tells us to not use it, why is it recommended here as an alternative to Task.Result?

I would love to get rid of Task.Result in my code, because handling AggregateExceptions is no fun at all.

**Comment by JimDaly** [comment]
@darshSWL 

I head back from our dev team and they supported what I said above. HttpClient is primarily designed for use in asynchronous applications. Our use must be synchronous, so it doesn't align with the common use cases, but it is still valid.

I've reached out to the .NET team to see if they can update their guidance so it isn't so absolute.

**Comment by JimDaly** [comment]
Created this: [Guidance for ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult Method is too absolute #7777](https://github.com/dotnet/dotnet-api-docs/issues/7777)

**Comment by JimDaly** [comment]
Final note here.
Worked with the .NET team to update the documentation for GetAwaiter().GetResult so that it no longer says 

>"This API supports the product infrastructure and is not intended to be used directly from your code."
>"This type and its members are intended for use by the compiler."

https://github.com/dotnet/dotnet-api-docs/pull/7968

I've removed the guidance about using ConfigureAwait(false)
