### ISSUE TITLE
Execution Path of SubmitForm()

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#313]
Hi
It is not clear what the execution path is after a SubmitForm(). If the SubmitForm() is successful, then the OnSuccess is executed.  What happens at the end of the OnSuccess code ?  Does the execution revert back to the statement after the SubmitForm() or what ?
Thanks
Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18553a93-0c49-83fe-1cc6-a2df80a21f07
* Version Independent ID: a32bfa21-c35b-8870-55cb-6f02a6394027
* Content: [EditForm, NewForm, SubmitForm, ResetForm, And ViewForm functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-form)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-form.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can use OnSelect property of a button to invoke SubmitForm function. Once button is clicked (kicking off OnSelect), form is submitted (SubmitForm function is executed). Upon SubmitForm submission to data source, the OnSuccess or OnFailure runs depending on whether submission was successful or not. So if you specify any activity OnSuccess or OnFailure, that takes place at this stage. 

The description section on article explains the flow. 

If you need any further help with an issue, please raise a [support service request](admin.powerplatform.microsoft.com/support) for assistance.
