### ISSUE TITLE
Broken link for Rich Text Editor

### ISSUE THREAD

**Issue by correnasergent** [MicrosoftDocs/powerapps-docs#3131]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434c988b-243e-0d01-e098-fa9a0300ae31
* Version Independent ID: e7b47bad-3195-2b6d-bef3-8c23b6fb58e8
* Content: [Set up notes as attachments for basic and advanced forms - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure-notes#notes-created-with-rich-text-editor)
* Content Source: [powerapps-docs/maker/portals/configure-notes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure-notes.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. The link has now been fixed.
