### ISSUE TITLE
Liquid user columns?

### ISSUE THREAD

**Issue by urklnme218** [MicrosoftDocs/powerapps-docs#3133]
Where might one find the columns that are included in the User record, as in the current signed on user on the D365 web portal?

I have portal users with blank user.parentcustomerid.id fields.

What field in the Dataverse does user.parentcustomerid.id correspond to?

Can you assist?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340faef4-cbf8-d938-8a10-230149b8a591
* Version Independent ID: 88a56df4-b670-4954-832b-955ae94a6501
* Content: [Available Liquid objects - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/liquid-objects#user)
* Content Source: [powerapps-docs/maker/portals/liquid/liquid-objects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/liquid/liquid-objects.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
The user record information is stored in the Dataverse contact record.  The available attributes and descriptions can be found here: [https://docs.microsoft.com/common-data-model/schema/core/applicationcommon/contact](https://docs.microsoft.com/common-data-model/schema/core/applicationcommon/contact)
 
The user user.parentcustomerid.id is the GUID of the parent account or contact record that would typically represent objects like the company a contact might be an employee. This is not a mandatory field so it possible to be blank.

I hope that answers the question.
