### ISSUE TITLE
Pap Portal Upload Failed due to subject ID is missing 

### ISSUE THREAD

**Issue by charrisonfuji** [MicrosoftDocs/powerapps-docs#3143]
# Introduction

Hi, just got a error with `pap portal upload` command and thought it would be worth to let you know in case anyone else has had this issue or you have a fix for it. 

## Issue 
Running paportal upload command for some web files where they have subject associated with them it throws the error attached. 

![image](https://user-images.githubusercontent.com/84843401/156195990-03295eb0-7469-46ba-a49e-2e161e6d17e0.png)

## Background:

Using devops pipelines with the pap cli commands to upload code from a developer environment to a build environment. The problem is that the subject ID on the dev environment will be different to the other environment and that's what causes the issue. Now for other tables in dataverse I thought it converts the value but for the subject table it does not seem to convert the ID instead throws the error above. 

## Short term fix:

The web files that were associated with a subject - take this out and leave as empty and rerun the `pap portal upload` command.

**Comment by phecke** [comment]
@charrisonfuji 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.
 
Closing this issue.
