### ISSUE TITLE
Video: Themes Private

### ISSUE THREAD

**Issue by soidevpp** [MicrosoftDocs/powerapps-docs#3144]
When attempting to access the hyperlink at the bottom of the read me the [Video: Themes](https://go.microsoft.com/fwlink/p/?LinkId=529568) page references a private page.

**Comment by phecke** [comment]
@soidevpp Please provide the URL of the README that you are referring to.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been updated.
