### ISSUE TITLE
Invalid filter parameter of 'Type' when using global discovery service

### ISSUE THREAD

**Issue by jzbuaa** [MicrosoftDocs/powerapps-docs#3146]
Hi, I was trying the samples of global discovery service in this doc but got the error below:
![image](https://user-images.githubusercontent.com/35400116/156491205-b2961007-9e86-4b54-8815-a31700bee00e.png)

I'm not sure if I missed anything or this doc should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc577a38-3a6f-98de-28fd-4c352dc3ba07
* Version Independent ID: bfc7ba30-2723-9e4e-45f9-5fa3c1303057
* Content: [Discover the URL for your organization (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/discover-url-organization-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/discover-url-organization-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/discover-url-organization-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@phecke 
The last example in the doc is not correct:
`GET https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances?$select=DisplayName,Description&$filter=Type+eq+0`

The Instances returned have no `DisplayName`, `Description`, or `Type` properties.

The results look like this:

```
{
  "IsUserSysAdmin": true,
  "Region": "NA",
  "Purpose": "Documentation Generation",
  "StatusMessage": 6,
  "TrialExpirationDate": "0001-01-01T00:00:00Z",
  "OrganizationType": 5,
  "TenantId": "<guid redacted>",
  "EnvironmentId": "<guid redacted>",
  "DatacenterId": "<guid redacted>",
  "DatacenterName": null,
  "Id": "<guid redacted>",
  "UniqueName": "org<id>",
  "UrlName": "orgname",
  "FriendlyName": "orgname",
  "State": 0,
  "Version": "9.2.22014.133",
  "Url": "https://orgname.crm.dynamics.com",
  "ApiUrl": "https://orgname.api.crm.dynamics.com",
  "LastUpdated": "2022-03-03T05:02:13.7031911Z",
  "SchemaType": "Full"
}
```

**Comment by JimDaly** [comment]
We should also list what all the `OrganizationType` , `StatusMessage`, and `State` values mean.

**Comment by JimDaly** [comment]
@jzbuaa 
This topic was updated and now has an accurate and complete list of the properties of the Instance EntityType returned by the Global Discovery service. See [Instance EntitySet](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/discovery-service#instance-entityset)
