### ISSUE TITLE
The steps on this page do not align with the Inspections app

### ISSUE THREAD

**Issue by ThorAtInvoke** [MicrosoftDocs/powerapps-docs#3151]
The steps for adding a store to the Inspections app don't go with the actual app inspections app. There are no lblIssue or lblNoIssue objects and other issue with the steps listed!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006ea3e1-916f-fd30-90f1-7787c1459c37
* Version Independent ID: e09165f1-60a8-c746-a0de-3a9d0c6ea0bb
* Content: [Add hierarchy to inspection location (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/inspections-hierarchy-locations)
* Content Source: [powerapps-docs/teams/inspections-hierarchy-locations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/inspections-hierarchy-locations.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **saperlmu**

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please review the latest version of the [app templates and documentation](https://github.com/microsoft/teams-powerapps-app-templates). If the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
