### ISSUE TITLE
Renaming a navigation menu item does not persist after publish

### ISSUE THREAD

**Issue by scottdrichards** [MicrosoftDocs/powerapps-docs#3155]
When I hit publish, the changes are overwritten to the defaults. My guess is this functionality is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35d56f74-5a67-5821-9110-faad2e03a384
* Version Independent ID: c14eca06-effa-cb11-92d0-aaf170d1a01c
* Content: [Change navigation within a model-driven app form in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/use-the-form-editor-legacy)
* Content Source: [powerapps-docs/maker/model-driven-apps/use-the-form-editor-legacy.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/use-the-form-editor-legacy.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@scottdrichards - Thanks for contacting us. If your form navigation changes aren't being committed after selecting Save, and then Publish, contact Support, here: https://powerapps.microsoft.com/support/ 

Closing this issue.
