### ISSUE TITLE
See Also Section has 404 Page Not Found link - 

### ISSUE THREAD

**Issue by piperk** [MicrosoftDocs/powerapps-docs#3159]
404 Page Not Found link in **See Also** section
Link Text: Developer documentation: table relationship eligibility
Link: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/table-relationship-eligibility

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a3a442-7dd0-3da9-66c8-e616a1e0e86b
* Version Independent ID: bb757754-a61d-e231-f48f-f1cfbadf616a
* Content: [Create many-to-many table relationships in Microsoft Dataverse overview - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-edit-nn-relationships)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-nn-relationships.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-nn-relationships.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@piperk - Thank you for bringing this to our attention. The link has been fixed and will be published live today.
Closing issue.
