### ISSUE TITLE
ClientGlobalContext.js.aspx deprecated or not?

### ISSUE THREAD

**Issue by jordanrbaker** [MicrosoftDocs/powerapps-docs#3160]
This article: https://community.dynamics.com/crm/b/dynamics-chronicles/posts/clientglobalcontext-js-aspx-is-deprecated-in-dynamics-365-how-to-replace

appears to state that ClientGlobalContext.js.aspx is being deprecated.  However the doc page, which was updated within the past 30 days does not contain any information regarding the deprecation of this and states to reference it.

Can you provide some elaboration on if this is or is not being deprecated?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f2e23f-87e2-62be-f107-08c2e99b97e5
* Version Independent ID: 03aa8ec3-a827-95cf-d7cf-f0a014c3484b
* Content: [GetGlobalContext function and ClientGlobalContext.js.aspx in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx#clientglobalcontextjsaspx)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by darshSWL** [comment]
It was indeed deprecated, but it seems to be postponed again.

Issue on why the deprecation was removed:
https://github.com/MicrosoftDocs/powerapps-docs/issues/3041

Commits with the removed deprecation notices:
https://github.com/MicrosoftDocs/power-platform/commit/b3ce8db72bbc4a0de38f4dd03d800cf1cb31a0df
https://github.com/MicrosoftDocs/power-platform/commit/7a7afaee848bfa6066f69d6f72e118a46df7d69d
https://github.com/MicrosoftDocs/powerapps-docs/commit/8ede8996f309e9ef2d83a50e697bf6695b37a040

**Comment by jordanrbaker** [comment]
> 

Thanks for the reply.

Would it be a safe assumption that if no ETA for deprecation exists that it would be greater than 365 days before complete deprecation?

What is the standard notification period for deprecation?

**Comment by jordanrbaker** [comment]
Closing as no longer relevant.
