### ISSUE TITLE
See more does not 

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/powerapps-docs#3163]
In the description at https://docs.microsoft.com/en-us/powerapps/teams/bulletins-notify-me#create-a-new-table-called-bulletin-notifications it says to click on See all. This is not shown if there is nothing in this environment yet created. You first must create a dummy app via New. Then See all is displayed and you can add tables. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a8652a-8a0c-1ede-a79e-d736f34c4ad2
* Version Independent ID: 05b572ca-7830-5805-9d79-940a41973d71
* Content: [Add 'Notify me' settings to category in Bulletins app (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/bulletins-notify-me)
* Content Source: [powerapps-docs/teams/bulletins-notify-me.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/bulletins-notify-me.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **saperlmu**

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please review the latest version of the [app templates and documentation](https://github.com/microsoft/teams-powerapps-app-templates). If the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
