### ISSUE TITLE
Ambiguity about how to send authorization data

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerapps-docs#3167]
When generating the token, I found after trial and error that I had to configure Postman like this:
![image](https://user-images.githubusercontent.com/3731532/157735111-23afcb6d-4d2e-4816-9822-8d3ec828cc29.png)

The value by default is "Request URL", I was getting a token but then WhoAmI failed with 401 Unauthorized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Set up a Postman environment (Microsoft Dataverse for Apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@otravers 
Thanks for reporting this. 
I have a workitem to review this content and update the functionality and screenshots.
Will check for this when that work is done.
