### ISSUE TITLE
InvalidPluginExecutionException changes the message

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3169]
We have plugin that sends data via HttpClient to an other system. The plugin is running asynch and works fine so far.

If the other system replies with an error message like "The mandatory property StartDate is undefined", this message gets logged with the ITracingService. We also throw an InvalidPluginExecutionException with this exact same message, so we can find errors more easily.

Output in the Details of the failed asynch opeartion: The mandatory property StartDate is **undefined**.
Output in the exception message: The mandatory property StartDate is **redacted**.

Why was the message changed? 
I've never experienced this behaviour before. Did I miss some update / release wave news?

Is it possible to suppress the redaction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26bcc37-d8d9-ee18-6c2e-0824aca609d5
* Version Independent ID: e2b6035c-4546-e079-dffc-db43115cbfd2
* Content: [Handle exceptions in a plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/handle-exceptions#retry-an-asynchronous-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/handle-exceptions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/handle-exceptions.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke**

**Comment by JimDaly** [comment]
@darshSWL 
I'm not clear about where you see the message with the text `redacted`.
You seem to say that the message does not have this change in:
 - The trace logs
 - The message that is visible in the asynchronous job (system job)

Can you be more specific about what you mean by "Output in the exception message".
 - Is this a message returned to the UI?
 - Or are you talking about the exception logged with the tracing?
 
 Screenshot would help.
 Thanks

**Comment by darshSWL** [comment]
This is the screenshot from the Plug-In Trace Log:
![image](https://user-images.githubusercontent.com/30015318/157925053-c832c0fd-3e1e-4f87-8361-6dfaf5352e01.png)

This is the code for the plugin:

>         public void Execute(IServiceProvider serviceProvider)
>         {
>             var tracing = (ITracingService)serviceProvider.GetService(typeof(ITracingService));
> 
>             var message = "Mandatory property 'StartDate' is undefined.";
> 
>             tracing.Trace(message);
>             
>             throw new InvalidPluginExecutionException(message);
>         }

The Message Block contains the original message.
The Exception Details contains the modified message: "undefined" was replaced with "redacted".

**Comment by JimDaly** [comment]
@divka78 
Please take a look.

**Comment by JimDaly** [comment]
@darshSWL 
Can you comment about how this impacts you?

**Comment by darshSWL** [comment]
@JimDaly Not much at the moment. The exception was intended to be used as a way to find failed executions and/or as a reply to the UI or other plugins.

I was just wondering if I was missing documentation about this redacting feature. Sounds like it is intended as some kind of data protection or compliance feature.

**Comment by phecke** [comment]
@darshSWL As a test, can you change the word _undefined_ in your message to _not defined_, and then see if the problem goes away.

**Comment by JimDaly** [comment]
I've made the dev team aware of this. It isn't by design.
