### ISSUE TITLE
Power Platform Tools won't install on Visual Studio 2022. 

### ISSUE THREAD

**Issue by jahmedhitachi** [MicrosoftDocs/powerapps-docs#3170]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d709296-ee38-4b31-a3b3-2a532ed06908
* Version Independent ID: ef0cedf7-60d7-b0ca-770f-a69759bb59e5
* Content: [Install Power Platform Tools - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/tools/devtools-install)
* Content Source: [powerapps-docs/developer/data-platform/tools/devtools-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tools/devtools-install.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@jahmedhitachi A VS 2022 version of the tools has not been released. VS 2019 is required for now.

See https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatformTools
