### ISSUE TITLE
OnSelect in Gallery is suddenly not working anymore

### ISSUE THREAD

**Issue by EA12** [MicrosoftDocs/powerapps-docs#3176]
Hi Experts, 
today we faced an issue with our App. None of the click events (Select(Parent)) in our gallery are working anymore.
No changes where made to the app and everthing was working fine the last days.

From the Console we see messages like this:
The resource https://content.powerapps.com/resource/webplayer/hashedresources/nmb39rmefkrif/openSource/modified/adal/adaljs.js was preloaded using link preload but not used within a few seconds from the window's load event. 
Please make sure it has an appropriate 'as' value and it is preloaded intentionally.

The resource https://content.powerapps.com/resource/webplayer/hashedresources/pmlea83kufr8d/js/player-loader.js was preloaded using link preload but not used within a few seconds from the window's load event. 
Please make sure it has an appropriate 'as' value and it is preloaded intentionally.

Can you please have a look into it?
Thanks, Ronny

**Comment by phecke** [comment]
@EA12 Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.
 
Closing this issue.
