### ISSUE TITLE
External User in PowerBI Embedded

### ISSUE THREAD

**Issue by ravikvaish** [MicrosoftDocs/powerapps-docs#3188]
External users run into an issue when trying to access a powerapp in a PowerBI report that has been embedded in a web application. The external users get an error saying app was not found in users parent tenant. Web application uses AD authentication. These users can however access the apps through an iframe embedded in the web page. PowerBI reports are not in sovereign cloud. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f94c3-694a-6d09-3a4f-e4b741684822
* Version Independent ID: c952e698-a2bf-a47d-acbd-a96a8a922636
* Content: [Power Apps visual for Power BI - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual#:~:text=Power%20BI%20enables%20data%20insights,make%20changes%20to%20your%20report.)
* Content Source: [powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **hahuber**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please raise a support ticket for investigation of the issue and resolution. The limitations include note about sovereign clouds.

**Comment by ravikvaish** [comment]
Hi Tapan, thanks for your response. Actually the apps and reports are not in sovereign cloud. It's not clear why the listed limitation should apply for Power BI embedded scenario.
