### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by jbakchr** [MicrosoftDocs/powerapps-docs#3191]
The link to "Logical column" (https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/introduction-to-entity-attributes.md#BKMK_LogicalAttributes) doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a7083d9-4e5d-be28-f943-699e40d4fff3
* Version Independent ID: 2ca8c470-6883-bc76-5793-04e2fc5c0024
* Content: [Calculated and rollup columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/calculated-rollup-attributes)
* Content Source: [powerapps-docs/developer/data-platform/calculated-rollup-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/calculated-rollup-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
Resolved; thanks!
