### ISSUE TITLE
A table documentation that does not document the table

### ISSUE THREAD

**Issue by felipe-molina-cashme** [MicrosoftDocs/powerapps-docs#3198]
This is a poor documentation. It doesn't explain the AccessRight column of the Privilege table.

Like what does it mean to have and AccessRight = 2 or an AccessRight = 65536?
It sure looks like a bit mask.

But shouldn't the bit mask meaning be explained in this page, which is the official table documentation???

Please document the tables properly in each table's documentation page.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6505dc5-28a1-fc1a-7577-51f7adbcbb21
* Version Independent ID: 7904c285-f1fb-6246-204f-716bd5ed8e02
* Content: [Privilege table/entity reference (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/reference/entities/privilege)
* Content Source: [powerapps-docs/developer/data-platform/reference/entities/privilege.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/reference/entities/privilege.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by darshSWL** [comment]
You can have a look here: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/accessrights?view=dynamics-ce-odata-9

Or maybe even here: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/security-access-coding

**Comment by KumarVivek** [comment]
Thanks @darshSWL.

@felipe-molina-cashme Hope you have found the information you were looking for. Closing the issue.
