### ISSUE TITLE
Multiple OptionSet with the name contains value ";" cannot select in the UI

### ISSUE THREAD

**Issue by phuocle** [MicrosoftDocs/powerapps-docs#3204]
If the OptionSet name contain value **;** then you cannot select this value in the UI

![2022-03-22_15h28_54](https://user-images.githubusercontent.com/479729/159439344-560a9736-4520-4f3e-b54c-4be1d8403b46.gif)

**Comment by phecke** [comment]
@phuocle Is there something in the documentation that you need clarification on, or some information added? If so, please provide us the doc link.

If you are calling out a bug in the product, please contact Support.

**Comment by phecke** [comment]
@phuocle No response. Closing this issue.
