### ISSUE TITLE
Typo: Missing "s"

### ISSUE THREAD

**Issue by Nils-2m** [MicrosoftDocs/powerapps-docs#3205]
Hi, you're missing an S in "Not for tranferring data" under "Design principles".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17495609-6712-f689-3311-5f58d90242dd
* Version Independent ID: 65c07285-28bf-1581-5f32-0414f0ef2c53
* Content: [Microsoft Dataverse business events - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/business-events?source=docs#design-principles)
* Content Source: [powerapps-docs/developer/data-platform/business-events.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/business-events.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Nils-2m. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
fix checked in
Thanks @Nils-2m
