### ISSUE TITLE
If this occurs aa user must either

### ISSUE THREAD

**Issue by SouthJordanDev2** [MicrosoftDocs/powerapps-docs#3207]
[Enter feedback here]

>> If this occurs aa user must either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a316f906-284c-1bff-ee37-97ded7119a18
* Version Independent ID: a601a5a5-0a4d-4e63-66c1-c90f117460b9
* Content: [Query data using the Organization service (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/entity-operations-query-data)
* Content Source: [powerapps-docs/developer/data-platform/org-service/entity-operations-query-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/entity-operations-query-data.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SouthJordanDev2. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Thank you @SouthJordanDev2 
Fix checked in. s/b live tonight
