### ISSUE TITLE
How to configure further authentication attributes of e.g. Azure Data Factory connection

### ISSUE THREAD

**Issue by fmms** [MicrosoftDocs/powerapps-docs#321]
Hi,

we are trying to add an Azure Data Factory connection to Power App via Flow.
However, when adding the connection in the Power App Portal according to your documentation there is no option to configure the Service Principal. It just pops up an authentication dialog which seems to accept nothing but real users.

How can we pass the parameters of the connector that are described at https://docs.microsoft.com/en-us/connectors/azuredatafactory/ ?

We have tested the same with Logic Apps which allows one to easily configure the necessary parameters:
![image](https://user-images.githubusercontent.com/908734/56029538-e68c5480-5d1a-11e9-85b2-38b05572b538.png)

How to enter parameters for Flow connections?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171e674b-d11d-ee29-abb3-68ebcdaa7318
* Version Independent ID: 155cb306-059f-a86c-9108-54409ea6245b
* Content: [Add a data connection in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-data-connection#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/add-data-connection.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-data-connection.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by MSFTMan** [comment]
@fmms Thank you for using Power Automate. To set the service principal:
1. Add an Azure Data Factory action
2. Select the ... at the top right of the data factory action card.
3. Select Add new connection.
4. Select the "Connect using service principal" link on the new connection card.
5. Enter the service principal info.

Please let us know if you have any other questions.
