### ISSUE TITLE
How to delete Plugin with Managed solution upgrade ?

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/powerapps-docs#3211]
In the section [https://docs.microsoft.com/en-us/powerapps/developer/data-platform/best-practices/business-logic/manage-plug-ins-single-solution#example-2-install-a-new-solution](url)

What should we do if we want to upgrade an assembly with same solution . In here **PluginSolution V2.0.0.0** with Upgrade ? Still its not working.

What is the way to Delete and Old and No longer used Plugin from an assembly on higher environments with Managed Build ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb9484f-d1e7-3434-66cd-832475447603
* Version Independent ID: edb9484f-d1e7-3434-66cd-832475447603
* Content: [Manage plug-ins in a single solution - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/best-practices/business-logic/manage-plug-ins-single-solution)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/business-logic/manage-plug-ins-single-solution.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/best-practices/business-logic/manage-plug-ins-single-solution.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pavansarma93. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@pavansarma93 

Thanks for your feedback. 
Can you clarify a bit more about what you want to achieve?
You say you want to:
 > "Delete and Old and No longer used Plugin from an assembly on higher environments with Managed Build "

So, I understand this to mean that you have a Plug-in type ( a class implementing IPlugin) in your assembly which is no longer used. You want to remove just the **_plug-in type_** using solution upgrade alone.

I don't think you can do this today.

However, you can replace _**the assembly**_ using a solution upgrade and achieve the desired end result.

These are the steps:
1. Update the Major version of the assembly which has the un-used Plug-in Types removed.
    After doing this, you will not be able to update the assembly using PRT.
    But you will be able to register the assembly as a new assembly side-by-side with the old one.
2. Register the new assembly (which doesn’t have the unwanted pluginTypes) side by side with the old one
3. Migrate any steps for the types to the corresponding types in the new assembly
                _Yes, this may be a lot of tedious work…_
4. Delete the old assembly from your dev environment using PRT.
5. Export the managed solution (with new version number)
6. Import the managed solution into an environment with the old assembly
- The Upgrade should delete the old assembly, and the unwanted types with it.

Would this be a satisfactory process to achieve your goal?

**Comment by MSW345** [comment]
That was not me

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by pavansarma93** [comment]
@JimDaly : Thanks for the response. You understood my question correctly. Yes, this looks like a tedious process indeed :) and hopefully improved in upcoming releases. However this is not documented anywhere expect in brief on how assemblies version work [https://docs.microsoft.com/en-us/powerapps/developer/data-platform/workflow/workflow-extensions#to-update-an-assembly](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/workflow/workflow-extensions#to-update-an-assembly) .

Hope this can be documented in this section as the error is same but from a different scenario.

**Comment by JimDaly** [comment]
@pavansarma93 
While I have done a simple test of the mechanic, I'd like to get some validation that this works in a real-world scenario.
Seems like you have a need/desire for the outcome of this procedure. Now that you know it is possible, will you try it?
Or is it so ridiculously tedious that it isn't worth it?

**Comment by JimDaly** [comment]
@pavansarma93 
I didn't hear back from you so I'm going to close this.

**Comment by nbrandl** [comment]
@JimDaly while your solution is the only one available, it's a really tedious one. For custom activities you could live with it, as you only had to select the right version on the workflow designer, but for plug-ins, we need to recreate all steps and images.

Ideal scenario would be the platform to allow removing the plug-in class from the assembly using a managed solution. The steps required would be:

1. Remove the plug-in class from our assembly and increase assembly build or rev version
2. Using PRT, remove any steps related to the plug-in.
3. Using PRT, update the assembly on DEV
4. Export the solution containing the original assembly and steps as Managed and import it in TEST/PROD -> After doing this, the old steps would have been deleted and the assembly updated.

Hope this makes sense.

**Comment by JimDaly** [comment]
@nbrandl 
Thanks for your feedback.

This documentation feedback issue is about whether to document the set of steps we know are required to delete a plug-in type with a managed solution upgrade. This question comes up again and again.

We have a strategy that seems to work, but it is tedious. I'd love to get some validation that it is effective in real world scenarios before we document it as "the solution".

I hear what you are saying about how an ideal solution should work, but this forum is for documentation issues. You are making a feature request.

**Comment by nbrandl** [comment]
Thanks @JimDaly. You are absolutely right! I would love to see a section dedicated to detail what is the appropriate way of updating a plug-in assembly using managed solutions when you remove a plug-in class, i.e., what you have detailed previously.

To make my case as feature request, in case you have dev access to the TEST/PROD environments, you can just use PRT and remove the plug-in, however this is not always true, thus removing the manual steps/images duplication would be an extremely useful addition.

**Comment by janis-veinbergs** [comment]
> However this is not documented anywhere expect in brief on how assemblies version work

This has been documented since. Leaving a link for future generations: https://learn.microsoft.com/en-us/power-platform/alm/plugin-component#delete-a-plug-in-from-a-solution-by-updating-the-assembly

**Comment by pavansarma93** [comment]
@janis-veinbergs @nbrandl @JimDaly Happy to see it documented. Thanks
