### ISSUE TITLE
Missing important settings instructions.

### ISSUE THREAD

**Issue by crismogram** [MicrosoftDocs/powerapps-docs#3214]
[Enter feedback here]
Please add instructions that they need to go to system settings > reporting > Allow Power BI visualization embedding first.
This is coming from someone who started to embed a Power BI on a fresh Environment.
![System Settings   Reporting   Enable Power BI](https://user-images.githubusercontent.com/5903626/159796262-85bb0c19-11f0-4838-bb94-cd50d005dfa0.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9f5db0-dd45-fb70-4527-470a7d7d84c2
* Version Independent ID: bd525508-694e-09e3-26a4-b05f5c9a8bcd
* Content: [Add a Power BI visual in a model-driven app (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-powerbi-visual)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-powerbi-visual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/add-powerbi-visual.md)
* Service: **powerapps**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **v-roryneary**

**Comment by Mattp123** [comment]
@crismogram - The Power BI visualization embedding environment setting prerequisite has been added to the article.

Closing issue.
