### ISSUE TITLE
Map controls will not bind to collection

### ISSUE THREAD

**Issue by clossmans2** [MicrosoftDocs/powerapps-docs#3218]
When entering the property values for the map control binding to the collection, powerapps complains that there is an error in the way the data is entered.

colSelectedAddress.Latitude
colSelectedAddress.Longitude

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4f2719-f80e-80b8-95ec-40cec21cd175
* Version Independent ID: ef4f2719-f80e-80b8-95ec-40cec21cd175
* Content: [Create an app with address input and map controls (contains video) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/how-to/mobile-apps-address-map)
* Content Source: [powerapps-docs/maker/canvas-apps/how-to/mobile-apps-address-map.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/how-to/mobile-apps-address-map.md)
* Service: **powerapps**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **anuitz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @clossmans2. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@clossmans2 Thank you for the feedback. Per our internal team, the name of the column on the dataset needs to be added in quotes.

For example, if you had a Dataverse table named Restaurants with columns named Latitude and Longitude, then it would be "Latitude" as the value for ItemsLatitude.

Hope this helps.

Thanks,
Mints

**Comment by mduelae** [comment]
@clossmans2 I'm closing the request. If you encounter technical issues please contact support, here: https://powerapps.microsoft.com/en-us/support/. 

Thanks,
Mints
