### ISSUE TITLE
May need to clarify if there is any difference between support for regular and paginated Power BI reports?

### ISSUE THREAD

**Issue by RicLund** [MicrosoftDocs/powerapps-docs#3219]
We're having challenges getting paginated reports to work with the liquid tag. This document only speaks to "reports" but there are two types - are they definitely both supported by this tag?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc8038da-7c65-d654-ee94-52522513148e
* Version Independent ID: ca92ed24-8197-1e9b-3898-80621e36a336
* Content: [Add a Power BI report or dashboard to a webpage in a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/add-powerbi-report)
* Content Source: [powerapps-docs/maker/portals/admin/add-powerbi-report.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/add-powerbi-report.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RicLund. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. We can confirm that Paginated Power BI reports are not supported on portals and the documentation has been updated.

**Comment by RicLund** [comment]
Thanks @nickdoelman. Are there any plans to support them in future?

**Comment by RicLund** [comment]
Done. Can I get your vote? :-)

https://ideas.powerpages.microsoft.com/d365community/idea/617c4c1d-f6e0-ec11-b5cf-dc984008ac55

**Comment by nickdoelman** [comment]
Upvoted :)
