### ISSUE TITLE
Response type​ & scope

### ISSUE THREAD

**Issue by ramuvr** [MicrosoftDocs/powerapps-docs#3220]
Hi, 

This document lists how the Portal authentication needs to be configured to use Azure AD B2C as the provider.

1.  when you enter the Authority URL, while following the wizard mentioned here in step 5a, it doesn't accept a custom B2C URL if your B2C uses a custom URL. In production, users will tend to use a Custom B2C URL (setup via a azure front door) 
2.  when you go to Site Settings and change the Authority URL to a custom B2C URL, the type of provider changes to "Other (OpenID Connect)" but in Site Settings the values are still B2C provider related e.g., 'Authentication/OpenIdConnect/AAD-B2C_1/Authority"
3. This is B2C provider, and the step 4>c>ix you are suggested to enable only Access tokens (used for implicit flows). But due to the issue mentioned in step 2, you now have scope, response type to select 
4. Due to step 3 if we then refer https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-openid-settings the step 6>k asks us to select ID token instead of access token. Now you have site settings show the "Authentication/OpenIdConnect/AAD-B2C_1/Authority" settings (instead of "Authentication/OpenIdConnect/OpenId_1/Authority", the portal authentication settings page show OpenIDConnect  as provider type and mismatch between what needs to be selected in app registration.

Could someone clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb5611f-dfc2-dab5-536c-b86db008b4bf
* Version Independent ID: db45733d-fcfb-e92b-1107-7a7ed3d57028
* Content: [Configure the Azure Active Directory B2C provider manually - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-azure-ad-b2c-provider-manual)
* Content Source: [powerapps-docs/maker/portals/configure/configure-azure-ad-b2c-provider-manual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-azure-ad-b2c-provider-manual.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ramuvr. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
If you're still experiencing the issue described here, please reopen or create a new issue.
