### ISSUE TITLE
The page refers to an element named of-type-group but samples and linked documentation are for type-group

### ISSUE THREAD

**Issue by markdebhailis** [MicrosoftDocs/powerapps-docs#3221]
I think there is a typo on this page and `of-type-group` should be `type-group`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @markdebhailis. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
There is no `of-type-group` attribute in the reference content. 
There is only [type-group](https://learn.microsoft.com/power-apps/developer/component-framework/manifest-schema-reference/type-group), and the links to `of-type-group` point to that reference topic.

Yet, the sample doesn't throw an error when `of-type-group` is used. It must be a valid attribute value.

**Comment by JimDaly** [comment]
fixed
