### ISSUE TITLE
bad grammar

### ISSUE THREAD

**Issue by SouthJordanDev2** [MicrosoftDocs/powerapps-docs#3224]
"you will define an table alias" should be "you will define a table alias"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08cd0714-ecf3-a37e-32da-a336f5402fb6
* Version Independent ID: 9d7be299-ec79-62fd-c3e7-48f6bc23069b
* Content: [Register a plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/register-plug-in#add-your-assembly-to-a-solution)
* Content Source: [powerapps-docs/developer/data-platform/register-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/register-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SouthJordanDev2. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed.
