### ISSUE TITLE
ODBC Driver for MS Dataverse

### ISSUE THREAD

**Issue by Lady-Jaye** [MicrosoftDocs/powerapps-docs#3226]
It would be really helpful to have Dynamics 365 available as a Linked Server in SSMS.  Do you have an ODBC Driver available for Dynamics 365?  If not, how soon will it be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ead09d9-3e51-04ce-dc6e-ac9bb59816ec
* Version Independent ID: 94d19f8d-3c5e-8ed9-53ee-4b6173f49144
* Content: [Use SQL to query data (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#feedback)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-sql-query.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Lady-Jaye. This issue has been assigned to the doc author for review.

**Comment by fowl2** [comment]
This *might* be possible with Azure SQL Server Managed Instance, see [Linked Servers Azure AD authentication available now for Azure SQL Managed Instance](https://techcommunity.microsoft.com/t5/azure-sql-blog/linked-servers-azure-ad-authentication-available-now-for-azure/ba-p/2913505).

**Comment by phecke** [comment]
@Lady-Jaye I have forwarded your enhancement request to the product team. Thanks for the feedback.
