### ISSUE TITLE
This example fails System.Net.ProtocolViolationException: 'Cannot send a content-body with this verb-type.'

### ISSUE THREAD

**Issue by ddevine-msft** [MicrosoftDocs/powerapps-docs#3227]
Fails with - System.Net.ProtocolViolationException: 'Cannot send a content-body with this verb-type.'
![image](https://user-images.githubusercontent.com/73505354/160484863-be9ac4ca-22c5-407c-a9ac-02b928189291.png)

There are a **couple issues** that cause this example to fail. 

### Issues:
ExecuteCrmWebRequest(**HttpMethod.Get**, **"accounts?$select=name"**, "{ \"name\":\"Test Account\"}", ODataHeaders, "application/json");

### Fixed Example:

1. Basic Change
ExecuteCrmWebRequest(**HttpMethod.Post**, **"accounts"**, "{ \"name\":\"Test Account\"}", ODataHeaders, "application/json");

2. A bit more of a change with serializing to json
                dynamic account = new { name = "testuserWebAPI", emailaddress1="test@test.com" };
                string jsonAccount= JsonSerializer.Serialize(account);
                HttpResponseMessage response = Service.ExecuteCrmWebRequest(HttpMethod.Post, "accounts", jsonAccount, ODataHeaders, "application/json");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b896fe3f-7db5-b7af-4aad-a6f10cf3d229
* Version Independent ID: 13a43b14-0e13-d778-924d-876b24e53045
* Content: [Use XRM tooling to execute actions in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/use-xrm-tooling-to-execute-web-request)
* Content Source: [powerapps-docs/developer/data-platform/xrm-tooling/use-xrm-tooling-to-execute-web-request.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/xrm-tooling/use-xrm-tooling-to-execute-web-request.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ddevine-msft. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@ddevine-msft 
Thank you for reporting this. Sorry for the delay in responding.
I've updated the topic to fix the issue.
