### ISSUE TITLE
Add Code Examples & Be Clear about Implications

### ISSUE THREAD

**Issue by vuciv** [MicrosoftDocs/powerapps-docs#3236]
It would be helpful to see code examples of how to properly use async onLoad handlers.

Also, when enabling support for async onLoad, it states in the ui that "async onLoad support will be enabled for every onLoad handler." 

Does that mean I need to go and declare each web resource onLoad handler to be an async function in my javascript code? The implications are unclear.

These would really help! Thank you so much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a1a54b-749b-b832-183d-973d6a946336
* Version Independent ID: 23887be8-cbed-71c7-bc90-90add6474e11
* Content: [Form OnLoad event (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/form-onload)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onload.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onload.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vuciv. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Created workitem for team to create these samples.
