### ISSUE TITLE
Enabling experimental search feature does not work

### ISSUE THREAD

**Issue by CodySchrank** [MicrosoftDocs/powerapps-docs#3237]
Enabled experimental search feature according to docs.  The search pane was never available, and the search toggle switch in the settings pane has now disappeared.

Edit:  Cannot open search pane via keyboard shortcuts either
"You can open the Search pane using the Search icon, or shortcut keys. To use the shortcut keys, press Ctrl+F when your cursor is outside the formula bar. When inside the formula bar, press Ctrl+Shift+F to open the Search pane."

<img width="862" alt="image" src="https://user-images.githubusercontent.com/10748482/160934105-49aa90e8-79b2-48f5-a49c-4c0c62ca8a21.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca8e6e0b-38de-bdd6-989e-371542a98541
* Version Independent ID: ca8e6e0b-38de-bdd6-989e-371542a98541
* Content: [Use the Search pane (preview) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/search)
* Content Source: [powerapps-docs/maker/canvas-apps/search.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/search.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @TashasEv
* Microsoft Alias: **tashas**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CodySchrank. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. As documented, this preview feature is being rolled out and will be available in a region after the rollout completes. Hence, this may take a while to reflect. Please try again later.
