### ISSUE TITLE
pac auth create not working in latest version

### ISSUE THREAD

**Issue by WhiteyC** [MicrosoftDocs/powerapps-docs#3238]
V1.13.6 - Trying to create auth just gives error - Authentication successfully created.
Validating connection...
Connected to...Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development 
team, if telemetry has been enabled. Exception Id: 03b43ce1-8559-4fb1-aa0d-1dd7a6c93757, Exception Type: System.TypeLoadException.

No auth profile is created.

**Comment by JimDaly** [comment]
Please use these issues to report issues related to documentation.
Contact support for technical issues.
