### ISSUE TITLE
Typo in sidebar heading

### ISSUE THREAD

**Issue by navzam** [MicrosoftDocs/powerapps-docs#324]
In the navigation sidebar, the heading for this doc is "I**n**personate a user". I'm not sure where the sidebar text comes from, but it doesn't look like it's from this markdown file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d043ee-b190-5fc0-87b1-5d353d969a82
* Version Independent ID: 0482f193-7058-e465-460c-68ec7a453749
* Content: [Impersonate a user (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/impersonate-a-user)
* Content Source: [powerapps-docs/developer/common-data-service/impersonate-a-user.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/impersonate-a-user.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke**

**Comment by susikka** [comment]
@navzam thanks for creating this issue. This will be fixed soon.
