### ISSUE TITLE
file size clarification

### ISSUE THREAD

**Issue by PranjaliShetty** [MicrosoftDocs/powerapps-docs#3246]
Please add the below lines:

When you are trying to upload a file to an annotation, if the file contents is base64 encoded that increases the size by another 33%
There is also a small number of bytes used to construct the request.
The result is while the entity will allow size up to 128MB. If you're doing an odata HTTP request  - the CRM web server will only allow incoming requests to be 128MB long and that limits the annotation file length to around 95-96MB. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 822b23d9-d027-b20d-73fe-8c46cf559704
* Version Independent ID: 6da5946b-f68c-962a-2b53-b0376f041fa8
* Content: [Annotation (note) table (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/annotation-note-entity)
* Content Source: [powerapps-docs/developer/data-platform/annotation-note-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/annotation-note-entity.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PranjaliShetty. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@PranjaliShetty I added a note to the annotation-note-entity.md topic. Thanks for the feedback.
