### ISSUE TITLE
Missing info on how to create client id and cli

### ISSUE THREAD

**Issue by donsvensen** [MicrosoftDocs/powerapps-docs#3247]
In the setup guide

"8. Create a new Virtual Entity Data Source by selecting the Gear icon -> Advanced Setting -> Administration -> Virtual Entity Data Source. Select New. In the pop-up dialog, select the Virtual Connector Data Provider. Enter the connection reference, Tenant ID, environment ID, client ID, and client secret values."

It refers to a client id and client secret values - but there is no description of how you create these.

I think it would b a good idea to have this.

BR
Erik Svensen
Microsoft MVP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b64c8d-3c3d-4e4d-afb1-5e0a54c84046
* Version Independent ID: 8180bdbe-ec98-642e-b7ee-1f57954ee502
* Content: [Create virtual tables using virtual connectors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @donsvensen. This issue has been assigned to the doc author for review.

**Comment by NHelgren** [comment]
Hi @donsvensen, in the prerequisites for the table creation it links to the documentation on registering an application and creating the secret. Following the steps in those documents you will generate the information you need to complete the fields. As indicated in the document you will want to copy that data after creating it for ease of access to complete the process. 

> 
> Create a service principal (Application ID) that will be used to authenticate with the provider. The service principal needs to be created in the tenant of your Dataverse platform. More information: [Creating service principal from Azure portal](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/azure/active-directory/develop/howto-create-service-principal-portal#register-an-application-with-azure-ad-and-create-a-service-principal).
> 
> Create a client secret value for the registered Application ID. You need this information when you create a data source for the external data as part of setting up the virtual connector. More information: [Create a new application secret](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/azure/active-directory/develop/howto-create-service-principal-portal#option-2-create-a-new-application-secret) doc for steps on how to create this.
