### ISSUE TITLE
Datacards with custom y / x properties are reset after removing/adding new datacards

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/powerapps-docs#325]
So I took the time to create the ideal Form Control with custom y and x properties to make sure that some datacards are grouped together on specific rows (even with WidthFit). When I add or remove datacards, the Form Control datacard y / x properties are reset so every previously customized datacard is re-aligned again over the available columns....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e4a709-4cf4-5e0a-fafd-d6e531cdfba2
* Version Independent ID: d68ff8b8-3694-a8a7-2ad9-9119f7666167
* Content: [Understand data-form layout for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-form-layout#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-form-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-form-layout.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by fxvn78** [comment]
I find that my potions are set to coordinate values no matter how many times I manually go back in and set them by hand to use integer x.y values for the potion. this is annoying since I have re-adjust the form every time I toggle the visible property on extra fields I have in the form. I think the bug is either with snap to columns or the forms field list that is used to place the relative position of the cards. It looks like the error got there after I made the cards custom and used the drag up/down method to position the cards. Anyway, is there a fix for this or anyway to put the x/y positions back to integer values. It seems studio gets confused due to pixel coordinated being used for the data card postion

**Comment by m3ngi3** [comment]
I have additional information:
When adding fields to the Forms Control it will add the Datacards in the same order in the Tree view.
In my example I added the Title field, the Created field and the Created by field in that order so in my 2-column Form control I see Title and Created on row 1 with Created by on the next row. 
Title will get X coordinate 0 and Y coordinate 0
Created will get X=1 and Y=0
Created by will get X=0 and Y=1

When I change the Y property of a Created by to 0 it will move the Created by Datacard right of the Title datacard replacing the Created Datacard and moving the Created Datacard to the next row. 
![image](https://user-images.githubusercontent.com/47530580/60969886-0256c500-a321-11e9-86f4-b41a29b4f940.png)
All datacards are now on the same row but because of 2 columns allowed, the last datacard will appear to be on the second row. This is **good**. 
Title still has X coordinate 0 and Y coordinate 0
Created by will get X=0 and Y=0
Created still has X=1 and Y=0
In the Forms Control from upperleft Title -> Created by -> Created
In the Tree view the Datacards still have the same order: Title -> Created -> Created by

When I save the PowerApp, leave it and reopen it to edit --> it seems that PowerApps has reordered the Datacards also in the Tree view to resemble the way we just left it:
Title still has X coordinate 0 and Y coordinate 0
Created by still has X=0 and Y=0
Created still has X=1 and Y=0
In the Forms Control from upperleft Title -> Created by -> Created
In the Tree view the Datacards still have the same order: Title -> Created by -> Created

Now more info on the bug: when I add new or remove existing Datacards it will reorder all items with new coordinates to fill all available spaces from the upperleft:
Title will get X coordinate 0 and Y coordinate 0
Created by will remain its position but X=1 and Y=0
Created will have X=0 and Y=1
Modified by will have X=1 and Y=1
Modified will have X=0 and Y=2
I lose all my X/Y modifications which is very troublesome when I have spent some time on ordering the Datacards in the Form Control with a lot of conditions.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. For issues with the feature, please reach out to investigate the problem with a [support service request](https://admin.powerplatform.microsoft.com/support). The X and Y values are saved and retained upon closing a maker session after saving, and then reopening a new maker session. However, if the issue persists in your environment, please seek help with support team and help resolve the issue.
