### ISSUE TITLE
Hi - I need some help to understand how solution layers work for Choices. I have added Choices to my solution using a managed solution and made some changes outside the managed solution. Doing so, I expected to see an unmanaged layer which I can then remove if needed. But I don't see the unmanaged layer when I check solution layers.     I do see managed solutions listed here in case the same option set is extended from another managed solutions.     Happy to add any screenshots if it helps.

### ISSUE THREAD

**Issue by sandeep-mamidala** [MicrosoftDocs/powerapps-docs#3250]
Basically Unmanaged layer is not getting created for Choices in the Solution after editing the choices field that is part of managed solution

**Comment by phecke** [comment]
@sandeep-mamidala We do not provide support here. We can point you to existing documentation or answer questions about the documentation.

See [Solution layers](https://docs.microsoft.com/en-us/power-platform/alm/solution-layers-alm) for information about solution layers.
