### ISSUE TITLE
Missing Power Platform Tools in the list of extensions

### ISSUE THREAD

**Issue by ddobric** [MicrosoftDocs/powerapps-docs#3253]
The "Power Platform Tools" extension cannot be found.

![image](https://user-images.githubusercontent.com/1756871/161453325-ca442f41-8d54-4572-818c-8fedb1983c9d.png)

Did I miss something in documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d709296-ee38-4b31-a3b3-2a532ed06908
* Version Independent ID: ef0cedf7-60d7-b0ca-770f-a69759bb59e5
* Content: [Install Power Platform Tools - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/tools/devtools-install)
* Content Source: [powerapps-docs/developer/data-platform/tools/devtools-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tools/devtools-install.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ddobric. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@ddobric Requires VS 2019. Not yet supported in VS 2022.
