### ISSUE TITLE
Extension Entity Id - Timeline

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/powerapps-docs#3254]
I wasn't even aware about this docs page until recently. So, is this statement below correct. Is it supposed to be June 2022?

> If you cannot set the Extension Entity Id field in the form, there is a fix being deployed to enable this by the end of **June 2021**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07bccabc-a5e3-bcfc-f86f-a83e184f927b
* Version Independent ID: e02f464c-4fd3-ab91-570c-c993fc49f40d
* Content: [Enable Virtual Tables to support Dataverse events (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/enable-virtual-table-event-support)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/enable-virtual-table-event-support.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/enable-virtual-table-event-support.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rajyraman. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
I tested this and had no problem with the two issues mentioned. Seems they were fixed shortly after the doc was published.
I'll remove the mention to the workarounds.
