### ISSUE TITLE
Xrm.Device.getCurrentPosition() return value

### ISSUE THREAD

**Issue by dmognaschi** [MicrosoftDocs/powerapps-docs#3255]
Hi,

the result of the Promise returned by getCurrentPosition() contains the field 'timestamp', which should be of type [EpochTimeStamp](https://w3c.github.io/hr-time/#the-epochtimestamp-typedef) instead of **DOMTimeStamp**, or better the newer [DOMHighResTimeStamp](https://w3c.github.io/hr-time/#sec-domhighrestimestamp).

Current versions of TypeScript no longer recognize the **DOMTimeStamp** type.

Ty,
D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d484ef-39be-0622-9766-40122a16f6ae
* Version Independent ID: bfb5d24c-e4ed-eab2-f6f7-d0f47cceffdb
* Content: [getCurrentPosition - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-device/getcurrentposition)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Device/getCurrentPosition.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Device/getCurrentPosition.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dmognaschi. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@dmognaschi 
This seems to be a feature request rather than feedback about the documentation.
You can submit ideas to https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas
