### ISSUE TITLE
Additional information on page would help

### ISSUE THREAD

**Issue by sletley** [MicrosoftDocs/powerapps-docs#3268]
It would be great if this page also includes guidance on the operating systems on which the browsers are supported.  The linked page for Studio contains this, but the information on the OS and Browser combinations on this page, for end user access is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95311735-81f8-9c35-333f-97caad86f6f5
* Version Independent ID: eb4c16f2-c43a-282c-b461-d699c2daf0ff
* Content: [Supported web browsers for Power Apps portals - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/supported-web-browsers?source=docs#feedback)
* Content Source: [powerapps-docs/maker/portals/supported-web-browsers.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/supported-web-browsers.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sletley. This issue has been assigned to the doc author for review.
