### ISSUE TITLE
Incorrect Windows service name

### ISSUE THREAD

**Issue by ghRSampei** [MicrosoftDocs/powerapps-docs#327]
The Windows service name is "On-premises data gateway service", not "Power BI Enterprise Gateway Service"

**Comment by phecke** [comment]
@ghRSampei Can you please provide the URL of the documentation that you are following where the service name is incorrect?

**Comment by ghRSampei** [comment]
I’m sorry Peter, but it’s been more than 3 months and I can’t find the page anymore. I tried the History on my browser but it’s only going back to 4/30; I did this on 4/15.

**Comment by mgblythe** [comment]
@phecke @ghRSampei - it looks like it's https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-reference.

**Comment by ghRSampei** [comment]
Yes, thank you. It’s the 3rd question in the FAQ section.

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. The content probably relates to [this](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-faq) article and it's updated. Please reach out to updated appropriate topic feedback if any further feedback.
