### ISSUE TITLE
Documentation on Liquid entities object is confusing

### ISSUE THREAD

**Issue by adedaporh** [MicrosoftDocs/powerapps-docs#3275]
[Enter feedback here]

It seems you guys don't understand the difference between entities, tables and records because what is this?

**Clearly** this is about a PowerApps _record_ in a known table so the statement about loading a powerapps table with an ID is wrong!

![image](https://user-images.githubusercontent.com/33579016/162415450-95891e26-43d3-49f5-82e9-111eca7c1206.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340faef4-cbf8-d938-8a10-230149b8a591
* Version Independent ID: 88a56df4-b670-4954-832b-955ae94a6501
* Content: [Available Liquid objects - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/liquid/liquid-objects)
* Content Source: [powerapps-docs/maker/portals/liquid/liquid-objects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/liquid/liquid-objects.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @adedaporh. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback. The Dataverse name changes (for example, entity to table) do not apply to Liquid objects. The Liquid entities object will continue to be referred to as entities. We have added a note to the topic for clarity.
