### ISSUE TITLE
Request for additional information [RGBA]

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#328]
The Fill property requires 4 values (RGBA). It would be helpful if these were explained in the documentation and if examples of their usage were provided i.e., we should not have to go to another resource to find out how to use the Alpha attribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0144a97-f591-edaa-5866-b6be9fe943a9
* Version Independent ID: 306a0e6b-b97d-048e-6bc9-090c6aba90ba
* Content: [Color and border properties - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/properties-color-border)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/properties-color-border.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/properties-color-border.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
@DeanGross, thanks for your suggestion.  We have added additional information about specifying color to the top of the color properties article.  You don't need to use RGBA, there are other ways to specify color such as by CSS name or hex code.

@AFTOwen, please close this issue.
