### ISSUE TITLE
Rich Text Editor can't be used in gallery

### ISSUE THREAD

**Issue by mic8989** [MicrosoftDocs/powerapps-docs#3280]
On this page a big warning or alert should be added to users that rich text editor CAN'T be used inside a gallery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 492e388f-6f28-4cc4-3897-8a6384e8a466
* Version Independent ID: c3a43927-981d-ad01-969e-285c7a80158a
* Content: [Rich text editor control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-richtexteditor)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-richtexteditor.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-richtexteditor.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mic8989. This issue has been assigned to the doc author for review.

**Comment by chmoncay** [comment]
Hi @mic8989, unfortunately that is a limitation. We'll go ahead and add a note in case others may want to try something similar.

Sorry again for any inconvenience.
