### ISSUE TITLE
Wrap Mobile App (preview) documentation typo

### ISSUE THREAD

**Issue by mathyousee** [MicrosoftDocs/powerapps-docs#3281]
Under **Create an App Center container for your mobile app** step 9, there is a typo in the note. It is showing:

`Platform must be Reactive Native for all apps in App Center.`

But it should be:

`Platform must be React Native for all apps in App Center.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f1562e-3a0f-1be1-3e3a-98b6dd24e768
* Version Independent ID: 66f1562e-3a0f-1be1-3e3a-98b6dd24e768
* Content: [Customize and build your mobile app (preview) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/common/wrap/how-to)
* Content Source: [powerapps-docs/maker/common/wrap/how-to.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/common/wrap/how-to.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @larryk78
* Microsoft Alias: **lknibb**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been fixed, and will reflect the changes soon.
