### ISSUE TITLE
Unable to build wrap package

### ISSUE THREAD

**Issue by last72** [MicrosoftDocs/powerapps-docs#3289]
Unable to build wrap package

I have provided all requied fields but I can save but not build. Is there any field that I missed? See the screenshot below.

![image](https://user-images.githubusercontent.com/30095306/163109128-830b5737-0f1b-4173-9500-b54fcb1b2f9b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f1562e-3a0f-1be1-3e3a-98b6dd24e768
* Version Independent ID: 66f1562e-3a0f-1be1-3e3a-98b6dd24e768
* Content: [Customize and build your mobile app (preview) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/common/wrap/how-to#create-an-app-center-container-for-your-mobile-app)
* Content Source: [powerapps-docs/maker/common/wrap/how-to.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/common/wrap/how-to.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @larryk78
* Microsoft Alias: **lknibb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @last72. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. To submit feedback, or report a problem with this feature, send an email to [pamobsup@microsoft.com](mailto:pamobsup@microsoft.com).
