### ISSUE TITLE
Please provide information about valide values

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#329]
Please provide information about what is acceptable when entering values into the various settings. i.e., what can be entered for Transparency. Let us know if whole numbers, negative numbers, percentages etc for every property that has a text box into which we can type. We should not have to use trial and error to determine what to enter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab57049f-534b-025b-b281-48998277d926
* Version Independent ID: af3b591f-eaca-83cd-c923-d0dea5c5323a
* Content: [Find a property - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/reference-properties)
* Content Source: [powerapps-docs/maker/canvas-apps/reference-properties.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/reference-properties.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by chmoncay** [comment]
Updated in documentation
