### ISSUE TITLE
Calling `getByName` and `getByIndex` on collections

### ISSUE THREAD

**Issue by skovlund** [MicrosoftDocs/powerapps-docs#3294]
I'm not sure if the code example on the page uses unsupported functions or if the [documentation for collections](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/collections) is incomplete.

The code example contains the partial line `formContext.data.entity.attributes.getByName('telephone1');` which uses the function `getByName(...)` on an attribute collection. But the collection documentation only lists `get()`, `getLength()`, and `forEach()` as supported functions. 

The same applies to the partial line `telephoneAttr.controls.getByIndex(0);` which uses `getByIndex(0)` on a control collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3641e60b-3c08-6766-fffd-a298ad84178c
* Version Independent ID: 7f4a0fb8-a78f-6507-2e2b-92a719ce697a
* Content: [getFormContext (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/executioncontext/getformcontext)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/executioncontext/getFormContext.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/executioncontext/getFormContext.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@skovlund 
Thanks for your feedback. 
I've replaced the use of `getByName` and `getByIndex` in the example to use the documented and supported `get` collection method that uses the overloaded parameters.
