### ISSUE TITLE
There is an error in the Container Control example

### ISSUE THREAD

**Issue by sauslash** [MicrosoftDocs/powerapps-docs#3296]
Hello, there is an error in the Container Control example, the width of the Menu and Close controls cannot be Parent.Width.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/create-responsive-layout)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sauslash. This issue has been assigned to the doc author for review.

**Comment by sauslash** [comment]
Sorry for that, the values are correct!
