### ISSUE TITLE
Which wave?

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/powerapps-docs#3297]
Hello 
It is said that the field is in a preview programm, however I couldnt find it in a release note.
Whate is the planned release date? in wich Wave?
Thankyou

Pierre-Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbd6609-e67d-ed97-e346-fbe6e48b46ea
* Version Independent ID: c2724fcf-b682-66b8-dd94-9a87afea09da
* Content: [Work with Dataverse for Teams formula table columns - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/formula-columns)
* Content Source: [powerapps-docs/teams/formula-columns.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/formula-columns.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @revachauhan
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @popujol. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@popujol - Formula columns are currently in preview. For more information about the preview program, go to https://docs.microsoft.com/en-us/power-apps/maker/powerapps-preview-program. General availability for the feature is planned for sometime this month. https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-apps/power-fx-formulas-provide-richer-easier-use-column-calculations-dataverse.

Closing issue.
