### ISSUE TITLE
account requirements

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#33]
In Step 5 above, What type of account should be used to sign in ? please specify the account requirements and recommendations in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c103d76-66ed-dcb3-4b6c-904e59143932
* Version Independent ID: fccd2495-7ac4-d2ab-dc8e-c08992a6af12
* Content: [Understand on-premises data gateways for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-reference)
* Content Source: [powerapps-docs/maker/canvas-apps/gateway-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/gateway-reference.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@DeanGross Thanks for your feedback! We've updated that step to specify that you should use the same account as you use to sign in to PowerApps. Please reopen this issue or create another one if we've misunderstood your question.
