### ISSUE TITLE
View Rollup jobs instruction unclear/incorrect

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/powerapps-docs#3304]
[Enter feedback here]

The section, #rollup-calculations, in which you direct the user to:

> While viewing the Common Data Services Default Solution edit the URL, removing everything after dynamics.com and refresh the page.

This did not bring me to the page you describe in the next step.  Please verify this area of instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7aaa057-dbfa-e5b0-2222-5f59299c4960
* Version Independent ID: c88e45f0-47ec-ab48-66c0-1a13b0aa2ad5
* Content: [Define rollup columns with Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/define-rollup-fields)
* Content Source: [powerapps-docs/maker/data-platform/define-rollup-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/define-rollup-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JeremyVyska. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@JeremyVyska - The article has been updated with steps from the Power Apps home page. 

Closing issue.
