### ISSUE TITLE
Also View Rollup jobs instruction unclear/incorrect

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/powerapps-docs#3305]
[Enter feedback here]

In the #rollup-columns section, the PowerApps admin is directed to look at "Settings > System Jobs".

This is entirely unclear.  Please create a new page about **Viewing System Jobs** and link to that instead, with comprehensive steps, which would also close #3304.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a7083d9-4e5d-be28-f943-699e40d4fff3
* Version Independent ID: 2ca8c470-6883-bc76-5793-04e2fc5c0024
* Content: [Calculated and rollup columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/calculated-rollup-attributes)
* Content Source: [powerapps-docs/developer/data-platform/calculated-rollup-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/calculated-rollup-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JeremyVyska. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@JeremyVyska 
Thank you for your feedback. Sorry for the delay in responding.
I've updated the topic to include a link to the instructions in the /maker content which were added due to the feedback you provided on that topic.
