### ISSUE TITLE
Screenshots of Share a view are outdated

### ISSUE THREAD

**Issue by Ciosull** [MicrosoftDocs/powerapps-docs#3308]
This needs to be updated to align with the Personal view sharing experience described here ([with](https://docs.microsoft.com/en-us/power-apps/user/grid-filters-advanced)), with updated images showing modern UI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349c57f6-1804-db23-3c38-f4c9dc5adaf2
* Version Independent ID: 11943f1c-46af-e0ec-c834-fb796e31f844
* Content: [Advanced find - Power Apps](https://docs.microsoft.com/en-us/power-apps/user/advanced-find)
* Content Source: [powerapps-docs/user/advanced-find.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/advanced-find.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@Ciosull Thanks for the feedback. I'm working on update this topic and will notify you once the update is live.

Thanks,
Mints

**Comment by mduelae** [comment]
@Ciosull This is a overview topic on how advanced find works depending on what you have enabled. I did add note with a link to how to use the modern advanced find experience, here: https://docs.microsoft.com/en-us/power-apps/user/advanced-find#create-edit-or-save-a-view-using-legacy-advanced-find

Thanks,
Mints
