### ISSUE TITLE
例の記載が誤っています

### ISSUE THREAD

**Issue by koruneko** [MicrosoftDocs/powerapps-docs#3309]
例に記載されているWeekNum()の結果が誤っています。
英語ドキュメントに記載されている内容に関しては問題ないように思われますので英語ドキュメントの記載に修正すればよい思います。
また、2021/1/3は日曜日です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e3f7edb3-5ee8-2cb1-4c8c-361b3c941e1f
* Version Independent ID: 4adf124c-84ea-3d99-276a-b0098046ae0b
* Content: [Power Apps の WeekNum 関数と ISOWeekNum 関数 - Power Apps](https://docs.microsoft.com/ja-jp/power-apps/maker/canvas-apps/functions/function-weeknum)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-weeknum.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-weeknum.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Dealgan12** [comment]
This is now reviewed and corrected by our supplier - https://docs.microsoft.com/ja-jp/power-apps/maker/canvas-apps/functions/function-weeknum
