### ISSUE TITLE
Incorrect Example [Concat]

### ISSUE THREAD

**Issue by anotherRedbeard** [MicrosoftDocs/powerapps-docs#331]
Hello,
I would like to point out that your Concat example is incorrect.  The label technically shows "Violin Cello ", with a space at the end.  This is an important distinction if you are using something like a comma (",") to concatenate with because there will be a comma at the end of the string.  It would be wonderful if you could provide an example formula that did not include the last seperator.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf00db59-885f-d764-64b7-21b74fc9f44b
* Version Independent ID: d92490ca-cad7-c82c-e203-3b1809f21991
* Content: [Concat and Concatenate functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-concatenate#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-concatenate.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-concatenate.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
@anotherRedbeard, excellent point.  We've updated the docs to point out the perils of separators and the last item included in a Concat, with some ideas for working around the situation (Left( x, Len( x ) - 2 ), Match( x, ... )).

**Comment by gregli-msft** [comment]
@AFTOwen, please close this issue.
