### ISSUE TITLE
Unable to locate the Wrap feature

### ISSUE THREAD

**Issue by gunavs** [MicrosoftDocs/powerapps-docs#3310]
[Enter feedback here]

Mentioned here - 
![image](https://user-images.githubusercontent.com/20308365/164119328-e03331b4-5502-451b-a1f2-5dc1e467483a.png)
I am in the https://make.preview.powerapps.com/

Where would i select the wrap? Do i have to enable any experimental features in Power Platfrom Admin Center or at app level?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f1562e-3a0f-1be1-3e3a-98b6dd24e768
* Version Independent ID: 66f1562e-3a0f-1be1-3e3a-98b6dd24e768
* Content: [Customize and build your mobile app (preview) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/common/wrap/how-to)
* Content Source: [powerapps-docs/maker/common/wrap/how-to.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/common/wrap/how-to.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @larryk78
* Microsoft Alias: **lknibb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gunavs. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please see below in the documentation:

![image](https://user-images.githubusercontent.com/48696796/164815773-60ca6a7d-9d9a-4f34-9fdd-a932ef7ca8a4.png)
