### ISSUE TITLE
Save Event and PostSaveEvent documentation

### ISSUE THREAD

**Issue by skovlund** [MicrosoftDocs/powerapps-docs#3311]
#### "Save event arguments" page 
This only covers the Save Event and not the PostSave event, even though the subpages covers both. The page is missing an overview of which functions are available for each of the Events' `getEventArgs()` methods' returned objects.

The list of methods is missing `preventDefaultOnError`.

![image](https://user-images.githubusercontent.com/7383967/164262133-aaf14469-772f-4e19-b073-9eb3c9101aaf.png)

#### "getEventArgs" and "getEventSource" pages
[getEventArgs](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/executioncontext/geteventargs)
[getEventSource](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/executioncontext/geteventsource)

Neither page mentions OnPostSave and consequently doesn't document their return types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdff5dae-5cff-59d7-2ddd-7b9287c2a968
* Version Independent ID: 45fd45f9-5976-e172-f2ef-1180d25eef86
* Content: [Save event arguments (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/save-event-arguments)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/save-event-arguments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/save-event-arguments.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @skovlund. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@skovlund 
Thanks for your feedback. I'm discussing how to incorporate your feedback with the dev team.

**Comment by JimDaly** [comment]
@skovlund 
We have pushed out changes to address your feedback.
Thanks for helping make our docs better.
