### ISSUE TITLE
Parameter panelId is actually paneId in AppSidePane class

### ISSUE THREAD

**Issue by phyle** [MicrosoftDocs/powerapps-docs#3313]
Parameter **panelId** is actually **paneId** (no "l") in AppSidePane class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ade424d-c9be-9c91-e40f-f1f0a1900572
* Version Independent ID: 0e680fea-adb3-f241-61ab-c320759344b1
* Content: [AppSidePane (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-app-appsidepane)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-app-appsidepane.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-app-appsidepane.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@phyle 
Thanks for letting us know.
I've fixed this and it will be live by this evening.
