### ISSUE TITLE
1 portal for each language seems wrong

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#3315]
Environment with customer engagement apps | All templates except "Portal from blank" | 1 portal for each other PORTAL TYPE language | For example, 1 portal for "Community portal" template allowed

(I'm not aware of a way to deploy different Community portals in specific language - you deploy the Community portal on a specific portal URL, and it will show with the portal languages configured)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04862aff-2233-c6f6-c8fb-afc641a4a43b
* Version Independent ID: ca7592a9-b006-6521-227f-d23b5205b1f9
* Content: [Create additional portals in an environment - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/create-additional-portals)
* Content Source: [powerapps-docs/maker/portals/create-additional-portals.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/create-additional-portals.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**[Environment with customer engagement apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/portal-templates#environment-with-customer-engagement-apps)	All templates except "Portal from blank"	1 portal for each language	For example, 1 English language portal for "Community portal" template allowed.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CarstenMS. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for the feedback. We have just updated this topic, which should address the question.
