### ISSUE TITLE
Connector Options are outdated

### ISSUE THREAD

**Issue by mscottsewell** [MicrosoftDocs/powerapps-docs#3316]
The Options for Connectors in Power BI is outdated - there is no "Common Data Service (Beta)" anymore - it's now the "Dataverse" connector.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/6276300/164745115-6c25d537-f8f5-43a9-a09c-7ba3200f2f3f.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd540f56-483a-72c0-ec0a-10fd11f25e79
* Version Independent ID: a54faf86-952d-59ad-66a7-0098f54e3234
* Content: [View Dataverse for Teams table data in Power BI Desktop (preview) - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/view-table-data-power-bi?source=docs)
* Content Source: [powerapps-docs/teams/view-table-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/view-table-data-power-bi.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mscottsewell. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@mscottsewell - Thank you for your feedback. The article has been updated to reflect the current connector name. 
Closing issue.
