### ISSUE TITLE
Dataverse service and common data service not available under APIs my organization uses.

### ISSUE THREAD

**Issue by tomRa1** [MicrosoftDocs/powerapps-docs#3318]
Dataverse service and common data service not available under APIs my organization uses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11caa291-2e98-ac3a-d5d1-ecd416b93bdf
* Version Independent ID: 4f30cddd-8849-1887-ada0-a83a3d2a0027
* Content: [Tutorial: Register an app with Azure Active Directory (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/walkthrough-register-app-azure-active-directory)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tomRa1. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@tomRa1 Are you still having this issue?

**Comment by phecke** [comment]
@tomRa1 Closing this issue - no response. If you are still having trouble, I would recommend you open a support ticket.
