### ISSUE TITLE
Video from Stream

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#332]
Can video from Stream be played in this control? if so, please provide an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a2b8fe0-c2ca-635b-0efd-f87fc2d794d3
* Version Independent ID: e351a0d8-db14-c01b-7b56-2569dbe1f442
* Content: [Audio and Video controls: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-audio-video)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-audio-video.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-audio-video.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
Thanks, @DeanGross, for your feedback. This control doesn't support Microsoft Stream videos as of this writing. Closing issue.

cc: @fikaradz

**Comment by fikaradz** [comment]
Note that we are working on Stream support currently, it will be available by summer 2019.
