### ISSUE TITLE
Sort table of Column Types to make easier to read.

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/powerapps-docs#3320]
[Enter feedback here]
There doesn't seem to be an order of Column Types/ (in the first table). This makes it difficult to find a data type. 
My suggestion is to sort the table by Power Apps data type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8f3598c-cd0e-2cd8-fa6b-5663f63c36bf
* Version Independent ID: 656dca2a-e65d-fdb9-545e-b73d906ce4f1
* Content: [Column data types in Microsoft Dataverse (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/types-of-fields#feedback)
* Content Source: [powerapps-docs/maker/data-platform/types-of-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Dlutchy. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@Dlutchy - The table in the article has been revised to sort alphabetically. 

Closing issue.
