### ISSUE TITLE
Add web resource for Azure configuration does not work

### ISSUE THREAD

**Issue by awadbensaleh** [MicrosoftDocs/powerapps-docs#3321]
Hi Team,

Added the web resource for Azure configuration and does not work on Power Portals and gives a page not found error, Are these steps still valid steps ? The same works on CRM but not on Power Portals .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdd598f-2269-05e7-25e8-f014bef0ff6e
* Version Independent ID: 8b9996ad-708b-f5dc-3df2-d0d7e8b1a8bf
* Content: [Add Azure storage web resource to a form - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/add-web-resource)
* Content Source: [powerapps-docs/maker/portals/add-web-resource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/add-web-resource.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by nickdoelman** [comment]
Thank you for your feedback. We have updated the documents which hopefully eliminates the confusion (as well as some needed screenshot updates).  
To summarize: 
- the web resource to view/download file attachments in Azure Blob storage is only meant for a model-driven app. The web resource will not render on basic or advanced forms on portal webpages.
- adding the timeline control and configuring basic or advanced form metadata specifying Azure Blob storage as file attachment location will work on portal pages. It is recommended to create different Dataverse forms for the portals for these purposes.
