### ISSUE TITLE
Unable to connect to Dataverse using CDS connector

### ISSUE THREAD

**Issue by ayumito** [MicrosoftDocs/powerapps-docs#3322]
This document says "Don't include the https:// or ending /." but the connection cannot be made without doing this.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b9e6e30d-4224-459f-8525-08718d6d77e4
* Version Independent ID: fe075fe5-5d2e-7b96-3608-9ad3138380da
* Content: [Dataverse コネクタを使用して Power BI レポートを作成する - Power Apps](https://docs.microsoft.com/ja-jp/power-apps/maker/data-platform/data-platform-powerbi-connector)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-powerbi-connector.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Thank you for your feedback. The English version (master) has been updated to reflect the current experience including using a full URL. The localized versions of the article will be updated within 30 days.
Closing issue.
