### ISSUE TITLE
Redundant paragraph

### ISSUE THREAD

**Issue by pratapladhani** [MicrosoftDocs/powerapps-docs#3324]
There is a redundant and duplicate paragraph in this article, which can be removed:

In this public preview release, we are introducing the virtual connector provider that supports creating virtual tables using the [SQL Server connector](https://docs.microsoft.com/en-us/connectors/sql). We will continue to expand and support other tabular connectors as part of this provider in subsequent releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b64c8d-3c3d-4e4d-afb1-5e0a54c84046
* Version Independent ID: 8180bdbe-ec98-642e-b7ee-1f57954ee502
* Content: [Create virtual tables using virtual connectors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors?tabs=sql)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
@pratapladhani Thanks for your feedback; this is fixed now. Closing the issue.
