### ISSUE TITLE
Request for guidance around app sitemap deletion

### ISSUE THREAD

**Issue by dave-burman** [MicrosoftDocs/powerapps-docs#3326]
Hi

Within the description of the app deletion guidance, we indicate the associated site map should be deleted ("When an app is deleted, you should also delete the associated site map...").  However, there is no guidance available on how this is done as far as I can find.  Can we either explain the process in more detail here, or link to appropriate prescriptive guidance please?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc4ddb97-bb47-4a49-7bda-0b092a6a96ce
* Version Independent ID: 724f0c45-5a7f-8573-d982-fd2cad284cdb
* Content: [Delete a model-driven app - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/delete-model-driven-app?source=docs#delete-or-remove-an-app-in-your-environment)
* Content Source: [powerapps-docs/maker/model-driven-apps/delete-model-driven-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/delete-model-driven-app.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@dave-burman - Thanks for you feedback. You're correct that deleting the site map isn't intuitive so I've added the following steps to the article on how to delete an unmanaged site map from an environment.

1. On the left navigation pane, select Solutions, and then open the Default Solution.
2. On the left navigation pane, select Site maps, select the site map that has the same name of the app that was deleted earlier, and then select Delete from this environment.
3. Select Delete to confirm.

Closing issue.
