### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Suparna-Banerjee** [MicrosoftDocs/powerapps-docs#3329]
The below links are broken
![image](https://user-images.githubusercontent.com/100163213/166161035-70b188b1-f056-4f24-8965-bfd58b44caa2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b36111-f5a4-6006-ea4a-90e353f3993e
* Version Independent ID: 54b36111-f5a4-6006-ea4a-90e353f3993e
* Content: [Contact us sample - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/contact-us-sample)
* Content Source: [powerapps-docs/maker/portals/contact-us-sample.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/contact-us-sample.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @ankitavish
* Microsoft Alias: **avishwakarma**

**Comment by nickdoelman** [comment]
Thank you for bringing this to our attention. The links have been fixed in the doc's article.
