### ISSUE TITLE
".md" in two links

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#333]
Greetings,
".md" should be removed from two links in the "Prerequisites" paragraph:

&gt;&gt; [Environment Maker]
Current link:
https://docs.microsoft.com/power-platform/admin/database-security.md#predefined-security-roles
It should be:
https://docs.microsoft.com/power-platform/admin/database-security#predefined-security-roles

&gt;&gt; [create an environment]
The link should be:
https://docs.microsoft.com/power-platform/admin/environments-administration#create-an-environment
or maybe directly:
https://docs.microsoft.com/power-platform/admin/create-environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927ab39b-2314-f0fb-8a06-6bae6a6f072a
* Version Independent ID: eda6b7a9-7213-e2d7-3d4c-b7c28ef77972
* Content: [Generate a canvas app from Common Data Service - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/data-platform-create-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/data-platform-create-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/data-platform-create-app.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @a-zaf!
