### ISSUE TITLE
Portal upload command to turn off plugins

### ISSUE THREAD

**Issue by craig-lund** [MicrosoftDocs/powerapps-docs#3330]
[Enter feedback here]
Is there or will there be an option to disable plugins on upload of a portal?

Recently, when uploading a portal to an environment with a community portal installed, the upload failed due to a pre-update plugin. This cause the site setting to NOT be associated with the website. 

The plugin is: 
Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate: Update of adx_sitesetting

With the error:
```
Exception Message: Object reference not set to an instance of an object.

ErrorCode: -2147220891
HexErrorCode: 0x80040265

ErrorDetails: 
	ApiExceptionSourceKey: Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService
	ApiStepKey: 41952d10-4e53-ea11-a814-000d3a3b1e97
	ApiDepthKey: 1
	ApiActivityIdKey: 2147f1bc-dc07-48b4-86bf-279b2e74e528
	ApiPluginSolutionNameKey: System
	ApiStepSolutionNameKey: System
	ApiExceptionCategory: ClientError
	ApiExceptionMessageName: IsvAborted
	ApiExceptionHttpStatusCode: 400
	OperationStatus: 0
	SubErrorCode: -2146233088
	Plugin: 
		PluginTrace: [Microsoft.Dynamics.Community.Plugins: Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate]
[68a2d42a-8bf1-eb11-bad6-000d3af6d0a1: Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate: Update of adx_sitesetting]
CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Entered Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.Execute()
CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.ExecuteCrmPlugin(LocalPluginContext context)
   at Microsoft.Dynamics.Community.Plugins.PluginBase.Execute(IServiceProvider serviceProvider)
CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Exiting Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.Execute()

TraceText: 
	[Microsoft.Dynamics.Community.Plugins: Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate]
	[68a2d42a-8bf1-eb11-bad6-000d3af6d0a1: Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate: Update of adx_sitesetting]
	CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Entered Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.Execute()
	CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
	   at Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.ExecuteCrmPlugin(LocalPluginContext context)
	   at Microsoft.Dynamics.Community.Plugins.PluginBase.Execute(IServiceProvider serviceProvider)
	CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Exiting Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.Execute()
```

Turned off the plugin and the upload worked great. 

Would be great to know if turning off plugins is available now or will be in the future. 

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2974aed9-bcf3-eabd-84b0-b83529a408aa
* Version Independent ID: 1ce77952-4d3b-314d-55fe-ee2b8baca91f
* Content: [Microsoft Power Platform CLI paportal command - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/cli/reference/paportal-command)
* Content Source: [powerapps-docs/developer/data-platform/cli/reference/paportal-command.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/cli/reference/paportal-command.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by JimDaly** [comment]
@craig-lund 
Thanks for your feedback, but issues captured here are for feedback on the documentation.
Your question appears to be a feature request.
If @kkanakas wants to respond he can, but I need to close this as there is nothing actionable for the documentation.
You may want to submit your idea to https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas
