### ISSUE TITLE
Version 9.4.4.x adds additional CSS not documented in release notes

### ISSUE THREAD

**Issue by rforster-dev** [MicrosoftDocs/powerapps-docs#3332]
https://docs.microsoft.com/en-us/power-platform/released-versions/portals/portalupdate944x 

On the above page, it is mentioned that "Arabic and Hebrew Language are supported."

I assume this has been implemented by adding the **dir=ltr / dir=rtl** attritubte on the HTML tag which is now present on portals on version 9.4.4.x

However, this has also introduced additional CSS that is not mentioned. When adding the attribute in the browser on portals running on a lower version, this CSS is not present.

![image](https://user-images.githubusercontent.com/70289994/166439679-8086ba43-b5fa-47ff-8728-ab7e988334e9.png)

Can this please be documented? In our scenario we need to update our CSS to remove this.

**Comment by nickdoelman** [comment]
Thank you for reaching out. We informed our support team.
