### ISSUE TITLE
Invalid context stage

### ISSUE THREAD

**Issue by martynlesbirel-ashtoncourt** [MicrosoftDocs/powerapps-docs#3338]
Hello,

In the section labelled [Write a Plug-in for your Custom API](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/custom-api#write-a-plug-in-for-your-custom-api) the sample code refers to _context.Stage.Equals(30)_ but checking the reference page for [IPluginExecutionContext.Stage Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.ipluginexecutioncontext.stage?view=dataverse-sdk-latest#microsoft-xrm-sdk-ipluginexecutioncontext-stage) 30 isn't listed. It is listed in [sdkmessageprocessingstep EntityType](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/sdkmessageprocessingstep?view=dataverse-latest) reference page but labelled as internal use only. 

So what should the value be for customer code?

Thanks,

Martyn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd53494-e9ff-33b0-d857-bcd235233aa5
* Version Independent ID: a362d3d7-3d5c-9222-39e6-dd426f96c4a4
* Content: [Create and use Custom APIs (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/custom-api#feedback)
* Content Source: [powerapps-docs/developer/data-platform/custom-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/custom-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@martynlesbirel-ashtoncourt Stage 30 has been around a long time, but Custom API is new. Stage 30 is for internal use only, except it is also used for Custom API.

It looks like the intent is hide the stage when registering a plug-in using the PRT as documented here [Create a Custom API using the plug-in registration tool](https://docs.microsoft.com/power-apps/developer/data-platform/create-custom-api-prt). The tool does the work for you and hides the stage so you do not attempt to mess with the core processing of Dataverse.
