### ISSUE TITLE
Feedback for .NET API browser / Microsoft.Xrm.Sdk?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3339]
Where can I leave feedback for the documentation for Microsoft.Xrm.Sdk?

The remarks for this method is not entirely correct. Instead of returning null, it returns default<T>. For the example with EntityReference, null is correct. For DateTime it is not null, but DateTime.MinValue.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.entity.getattributevalue?view=dataverse-sdk-latest#remarks

**Comment by phecke** [comment]
@darshSWL Thanks for pointing that out. I will update the page.
