### ISSUE TITLE
Formula Error [responsive layout]

### ISSUE THREAD

**Issue by HilaryStoupa** [MicrosoftDocs/powerapps-docs#334]
The syntax in this line in the table under device orientation:
Upper	Width	If(Parent.Orientation = Layout.Vertical, Parent.Height, Parent.Width, Parent.Width / 2)
Does not resolve, due to having the incorrect number of arguments for an If statement. I'm assuming that the Parent.Height argument needs to be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @HilaryStoupa!
