### ISSUE TITLE
the odata endpoint is not available anyore

### ISSUE THREAD

**Issue by abpanic** [MicrosoftDocs/powerapps-docs#3341]
[Enter feedback here]

navigating to https://contosowebservice.azurewebsites.net/odata/ returns :

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b56c32-971a-739d-40b6-5e2a2fb82c65
* Version Independent ID: 219c2bb0-0b17-1af4-7b87-1ea3e9c3f228
* Content: [Virtual table walkthrough using the OData Data Provider in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/virtual-entity-walkthrough-using-odata-provider)
* Content Source: [powerapps-docs/maker/data-platform/virtual-entity-walkthrough-using-odata-provider.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/virtual-entity-walkthrough-using-odata-provider.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by KumarVivek** [comment]
@abpanic Pls see the important note: 

"The web service url used for this walkthrough isn't a functioning web service."

Attaching the screenshot.

![image](https://user-images.githubusercontent.com/1670116/167211514-5c752be7-7c8a-4d09-8329-367523253c91.png)

Closing the issue.
