### ISSUE TITLE
Clarification of statement "Currently reflection is not allowed"

### ISSUE THREAD

**Issue by josephmcmac** [MicrosoftDocs/powerapps-docs#3342]
Could the statement "Currently reflection is not allowed" in this article be clarified in regards to what specifically is not allowed?

Is it only examples like that cited in the article where another assembly is loaded by name which is not allowed? Or is any form of reflection not allowed? Reflection is commonly used and a fundamental part of .NET which is available on any CLR object using the GetType() method, so stating such a core part of the language is not allowed seems inaccurate

Further to this I have seen loads of plugins written by other developers, and have some myself, which use basic reflection on classes, properties and attributes, which based on the statement "Currently reflection is not allowed" would seem to be at risk of breaking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c23d5760-83d7-50c6-30a6-972368fa7a46
* Version Independent ID: e306e921-a345-dee8-a2af-797e51238ac3
* Content: [Remove unsupported code that uses reflection in custom workflow activities - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/business-logic/remove-unsupported-code-using-reflection-workflow-activities)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/business-logic/remove-unsupported-code-using-reflection-workflow-activities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/best-practices/business-logic/remove-unsupported-code-using-reflection-workflow-activities.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by phecke** [comment]
@josephmcmac The specified article does not seem to exist anymore. Thanks for the feedback.
