### ISSUE TITLE
In the GCC link, you are missing a "/" between play and [Appid] 2702847

### ISSUE THREAD

**Issue by shalabhgupta1985** [MicrosoftDocs/powerapps-docs#3343]
In the GCC link, you are missing a "/" between play and [Appid]
![image](https://user-images.githubusercontent.com/13446757/167026538-1792b4a5-8f49-4718-9901-c3db0082dabd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aa66ed7-7906-598f-ab43-bec289e1ccd3
* Version Independent ID: 1a73b184-050a-26be-b362-4cab5328c541
* Content: [Integrate canvas apps into websites and other services - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/embed-apps-dev#embed-your-app-in-a-website)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-apps-dev.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/embed-apps-dev.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been fixed and will reflect the change soon.
