### ISSUE TITLE
Documentation still correct?

### ISSUE THREAD

**Issue by ackerk** [MicrosoftDocs/powerapps-docs#3347]
[Enter feedback here]
When I look to the Date Picker properties in Power Apps, I do not see all the properties that are described on this page.

I see InitialPickerDate, but not DefaultDate as subscribed, I do not see Format,....

![image](https://user-images.githubusercontent.com/79246760/167111633-73bc2367-f5a9-4840-b3d8-65db70f704f3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c73d9b9-7cb5-f7ee-8c70-227309c9b18b
* Version Independent ID: 5276fa3a-3cf9-70e5-5324-85e0ebc24c56
* Content: [Date Picker control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-date-picker)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-date-picker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-date-picker.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please make sure you're looking at the correct control and are not using an older version of Studio. This is what shows at present:

![image](https://user-images.githubusercontent.com/48696796/167170740-f988bca1-2e8c-4d80-8fab-abaf0d395624.png)

If you still have problems, perhaps using a new or a different environment might help. If the issue persists, please reach out to support with [support ticket](https://docs.microsoft.com/en-us/power-platform/admin/get-help-support).
