### ISSUE TITLE
Removal for deprectaed WS-Trust auth page

### ISSUE THREAD

**Issue by abpanic** [MicrosoftDocs/powerapps-docs#3348]
[Enter feedback here]

Since WS-Trust is undergoing removal, the documentation should be updated accordingly and this page along with references to it should be removed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62040095-4960-ad63-ed12-48400473e95c
* Version Independent ID: 063346b9-99f6-902f-710b-6badbd2a9830
* Content: [Use of Office365 authentication with Microsoft Dataverse (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/authenticate-office365-deprecation)
* Content Source: [powerapps-docs/developer/data-platform/authenticate-office365-deprecation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/authenticate-office365-deprecation.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@abpanic The page is needed to let the reader know about the deprecation and what to do about it in their code. 

Thanks for the feedback.
