### ISSUE TITLE
".md" in link [AFS/CDS]

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#335]
Hello again,
This is similar to issue "333"...
At the end of "Prerequisites" section, there is ".md" in the [Environment Maker] link.
Sorry for repetitive "annoyance" :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5620a24a-1a1d-979e-f585-c50bfb688d46
* Version Independent ID: f4d80828-ebab-abfe-7067-d17809eb9ed5
* Content: [Create a canvas app from scratch using Common Data Service - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/data-platform-create-app-scratch)
* Content Source: [powerapps-docs/maker/canvas-apps/data-platform-create-app-scratch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/data-platform-create-app-scratch.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Fixed. Thanks again, @a-zaf! :-)
