### ISSUE TITLE
Lacking explanation for arg

### ISSUE THREAD

**Issue by autohub7** [MicrosoftDocs/powerapps-docs#3350]
From the example below, there's no example or explanation about arg. What value should it be for 'arg'?

`
var myRow = myRows.get(arg);
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295ad522-be0d-20f2-1132-a11eec201b4f
* Version Independent ID: 59d82fd5-ac81-52a4-e920-b1268b53cc57
* Content: [GridRowData (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/grids/gridrowdata)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridrowdata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridrowdata.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @autohub7. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Please note the sentence directly above the sample:

> See [Collections (Client API reference)](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/collections) for information on the methods available to access data in a collection.
