### ISSUE TITLE
File Column Type is no longer pre-release

### ISSUE THREAD

**Issue by KylieKiser** [MicrosoftDocs/powerapps-docs#3351]
Page: https://docs.microsoft.com/en-us/power-apps/maker/data-platform/types-of-fields#file-columns

Section:
File columns
[This topic is pre-release documentation and is subject to change.]

The phrase "[This topic is pre-release documentation and is subject to change.]" should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99285656-64cc-d759-debd-fa439c7f0111
* Version Independent ID: 91ec0245-00a2-1de1-dd56-567010ec36df
* Content: [Image columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/image-attributes?msclkid=88a95d44cfa411eca045baf6a36e063e)
* Content Source: [powerapps-docs/developer/data-platform/image-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/image-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KylieKiser. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@KylieKiser - Thank you for your feedback. The prerelease indicator has been removed and the article will be published shortly.

Closing issue.
