### ISSUE TITLE
POSTMAN Trouble with name of variable

### ISSUE THREAD

**Issue by grollmus-sl** [MicrosoftDocs/powerapps-docs#3352]
https://docs.microsoft.com/de-de/power-apps/developer/data-platform/webapi/setup-postman-environment#connect-with-your-dataverse-environment

In Point 1 you describe to call one of the variables "callback" and that is not very smart. Getting my token I always got an error with rewrite_url. 

Problem is in Postman "callback" becomes the same value as "authurl" by sending the request. And you will never get your authurl in your App-Registration for Web-URLs the same way (because of ":"). 

Renaming "callback" to "callbackurl" solved all upcoming problems. 

Maybe you can change that in the whole article, thanks!

Cheers

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Einrichten einer Postman-Umgebung (Microsoft Dataverse für Apps) - Power Apps](https://docs.microsoft.com/de-de/power-apps/developer/data-platform/webapi/setup-postman-environment#connect-with-your-common-data-service-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @grollmus-sl. This issue has been assigned to the doc author for review.

**Comment by grollmus-sl** [comment]
oh I am embarassed... had a variable also named "callback" in my globals... sorry about that!
