### ISSUE TITLE
Make the documentation easier to understand

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/powerapps-docs#3357]
**Replace :** 
Create a new folder Solutions inside the LinearInputControl folder and navigate into the folder.

**By :** 
Create a new folder Solutions inside the LinearInputControl folder and navigate into the folder.

Navigate to the folder Solutions
cd "Solutions"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jeffangama. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Changed to:

1. Create a new folder named **Solutions** inside the **LinearInputControl** folder and navigate into the folder. 

   ```CLI
     mkdir Solutions
     cd Solutions
   ```
