### ISSUE TITLE
Not working as described

### ISSUE THREAD

**Issue by LudwigReindl** [MicrosoftDocs/powerapps-docs#3359]
The solution does not work as described:
- would need to define charts first
- however this part is missing -> got stuck here

<img width="341" alt="image" src="https://user-images.githubusercontent.com/42635187/168078084-60b5d9d0-4ef2-4944-8d12-f5e50bf9ec71.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fbfa51b-42cc-5fad-de26-e5d28724ea16
* Version Independent ID: 759e5d1c-f71e-fb07-5188-e8ebd5bcd76a
* Content: [Track your progress with dashboards and charts in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/user/track-your-progress-with-dashboard-and-charts)
* Content Source: [powerapps-docs/user/track-your-progress-with-dashboard-and-charts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/track-your-progress-with-dashboard-and-charts.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LudwigReindl. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@LudwigReindl Thanks for contacting us. Without more information, it's difficult to say what's going on. Do these topics help:

- https://docs.microsoft.com/power-apps/maker/model-driven-apps/create-edit-system-chart
- https://docs.microsoft.com/power-apps/maker/model-driven-apps/create-edit-dashboards

To contact Support, see here: https://powerapps.microsoft.com/support.

Thanks,
Mints

**Comment by mduelae** [comment]
@LudwigReindl Checking in to see if you have further questions or feedback? 

Thanks,
Mints

**Comment by mduelae** [comment]
@LudwigReindl Closing issue since I haven't heard back. If you still find problems with the topic please reopen this or another issue.

Thanks,
Mints
