### ISSUE TITLE
Navigation is now different

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/powerapps-docs#336]
Your documents says to go to Home &gt; Connections
It should say go to Home &gt; Data &gt; Connections

Please also add how this step fits in a bigger scheme: When would you use this, what would you do next.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5df5f2bb-1e4d-ce52-0478-19fc7a16f9b3
* Version Independent ID: fc072fdb-3e49-5e12-e8ce-ddfebca0963f
* Content: [Add and manage connections from canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-manage-connections)
* Content Source: [powerapps-docs/maker/canvas-apps/add-manage-connections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-manage-connections.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and the feedback. Content updated with recent UI changes. For next steps, please read **Create your first app** and **Create an app from scratch** sections that explain in detail all scenarios to work with and create apps.
