### ISSUE TITLE
"npm run refreshTypes" goes after Implementing manifest

### ISSUE THREAD

**Issue by pablolaurin** [MicrosoftDocs/powerapps-docs#3361]
"npm run refreshTypes" goes after Implementing manifest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pablolaurin. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
I have moved the step to run `npm run refreshTypes` to after the manifest is edited.
PR: 3905
