### ISSUE TITLE
Using editable grids on mobile devices

### ISSUE THREAD

**Issue by riblack-microsoft** [MicrosoftDocs/powerapps-docs#3365]
This document is intended for online implementations, but limitations are only documented on the corresponding on-premises page. Limitations such as the inability to use editable grids on phones is documented at https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/customize/make-grids-lists-editable-custom-control?view=op-9-1#why-cant-i-use-editable-grids-on-phones, but should be reflected here also where applicable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 323651bd-11de-71da-9a79-21293995f529
* Version Independent ID: 6d59ef2e-2072-ac62-b62c-04c84eb04b91
* Content: [Make model-driven app views and grids (lists) editable by using the Editable Grid custom control with Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/make-grids-lists-editable-custom-control#make-main-grids-editable)
* Content Source: [powerapps-docs/maker/model-driven-apps/make-grids-lists-editable-custom-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/make-grids-lists-editable-custom-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @riblack-microsoft. This issue has been assigned to the doc author for review.
