### ISSUE TITLE
getAttributeType - File Attachment columns

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#3366]
What does `getAttributeType` return for file attachment fields? What functions are available for the associated control?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa20929d-c72c-f48c-4af8-85d73179af7b
* Version Independent ID: ae8f1952-671e-f3c9-82da-2fbade4baa06
* Content: [getAttributeType (Client API reference) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/attributes/getattributetype)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getAttributeType.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getAttributeType.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @fowl2. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Waiting for response from @chmoncay or @miglisic

**Comment by chmoncay** [comment]
Hi there, is there an image to help me figure out the associated control?  Want to confirm which control you're trying to use.

**Comment by JimDaly** [comment]
We are updating this topic to reflect that getAttributeType returns `file` or `image` for the file and image columns.
We aren't aware of any special methods associated with those types.
