### ISSUE TITLE
Sentence doesn't make sense

### ISSUE THREAD

**Issue by dburnet3** [MicrosoftDocs/powerapps-docs#3369]
[The following sentence doesn't make sense: "
Each column (also known as an attribute) within a table represents a column in that table."
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b903798-2033-be36-079a-babe7586981e
* Version Independent ID: d588611a-a950-134e-6738-10e8f3899f25
* Content: [Tables and metadata in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-metadata)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-metadata.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dburnet3. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed.
