### ISSUE TITLE
Two typos (trivial, unimportant)

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#337]
In "Add data source", Step 5:
" [...] and then select then connection when it appears."
&gt;&gt; should be: " [...] and then select the connection when it appears."

In "Identify or change a data source", first paragraph:
"For example, you might need to identify a data source as you update an app that someone else created or you that you created long ago."
&gt;&gt; should be: " [...] an app that someone else created or that you created long ago."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171e674b-d11d-ee29-abb3-68ebcdaa7318
* Version Independent ID: 155cb306-059f-a86c-9108-54409ea6245b
* Content: [Add a data connection in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-data-connection#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/add-data-connection.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-data-connection.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @a-zaf!
