### ISSUE TITLE
You cannot add PDF viewer control in container.

### ISSUE THREAD

**Issue by last72** [MicrosoftDocs/powerapps-docs#3371]
You cannot add PDF viewer control in container.

![image](https://user-images.githubusercontent.com/30095306/168953437-5140d007-f36b-4096-9055-39c35ffaa577.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 245db0a5-35a8-ea41-7680-1f041dbff03b
* Version Independent ID: 66aa308d-a4e9-3124-1b30-7686d94cd65a
* Content: [Container control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-container)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-container.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-container.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @last72. This issue has been assigned to the doc author for review.

**Comment by last72** [comment]
@bishalgoswami Thank you. Also note that you cannot put datatable in containers either

**Comment by tahoon-ms** [comment]
Thanks for reporting this. We've mentioned the [limitation with Containers and Data tables](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-container#known-limitations) and will be adding the PDF Viewer one shortly.
