### ISSUE TITLE
Content Range in FIle content request not working

### ISSUE THREAD

**Issue by adedaporh** [MicrosoftDocs/powerapps-docs#3375]
[Enter feedback here]

The content range when getting file content from dataverse via the power apps portals is not working properly. Causing the file to only be partially downloaded and the browser seems to be repeatedly downloading the same chunk of data over and over again.

Example: I have a video with src pointing to [Portals url]/_api/[ entity name ]([ entityid ])/[ entitiycolumnname ]/$value
This should allow me stream the content in chunks according to this article. However, what happens is that the request header does not seem to properly format the range (startbyte-endbyte/fullbyte); it uses the same range for all the chunks which causes the first 4mb of data to be downloaded over and over again.

![image](https://user-images.githubusercontent.com/33579016/169150491-ab496bbd-b9c1-43f3-a665-ee5207665780.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/file-attributes)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @adedaporh. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@adedaporh You are supposed to use the continuation token to get the next chunk. We have some code that we are working on that demonstrates downloading. Have a look but know that it has not yet been tech reviewed and finalized.

https://github.com/microsoft/PowerApps-Samples/tree/FileAttributeWebApiSample/cds/webapi/%23/UploadDownloadFiles

in the FileAttributeWebApiSample working branch
