### ISSUE TITLE
How to find out if there is a file to download?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3378]
The documentation tells us how to upload, download and delete files. It doesn't tell us how to check if there is a file which could be downloaded.

We are using the .NET API (SOAP).

If there is no file to download, the InitializeFileBlocksDownloadRequest throws an exception. The error message starts with "No file attachment found for attribute". Using exceptions to find out if is possible to do anything doesn't fit our programming style. So I was trying to find a different method.

The Web API seems to provide a GetFileSasUrl. I'm not sure what the response will look like, if there is no file to download. We are not using the Web API, so I was trying to find this request for the .NET API. I was able to find the FileSasUrlResponse class, but couldn't find a matching request class for it.

I also tried to use Advanced Find, but if I select the file attribute, the Advanced Find buttons break. "Results" and "Download Fetch XML" are not responding anymore.

Is there any way to find out if there is a file to download without relying on exceptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8026a170-f2e5-9d5f-3c7b-0fcfaca0d71c
* Version Independent ID: 7b8e643b-ad4a-2032-ef27-413ed7e8f97a
* Content: [File columns (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/file-attributes)
* Content Source: [powerapps-docs/developer/data-platform/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/file-attributes.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@darshSWL I do not know. I have not tried such a thing.

Are you still wanting to know or have you figured it out by now?

**Comment by darshSWL** [comment]
@phecke Would be nice to know. At the moment we are just handling the exception.

The problem with this approach is the time it takes. The request takes 0.3s - 0.4s and then just returns the exception. I've hoped that the "is there something to download"-request would be faster. Using annotations instead of the file attribute is a bit faster and takes 0.2s - 0.3s. We have to handle ~800k records across all tables. Some tables have more than one file attribute.

I was thinking to move those files to SharePoint, but I didn't have time to test this approach. So I don't know if this would be faster. I'm also not sure if SharePoint would be accepted at all and what the costs would be.

**Comment by phecke** [comment]
@NHelgren Do you know if a File column can be queried for file data before code tries to do a download? Perhaps if app code can check the file size, and if zero, not attempt to do a download.

**Comment by phecke** [comment]
@darshSWL You can simply check the file size = 0.

For the Dataverse SDK, the InitializeFileBlocksDownloadResponse contains a FileSizeInBytes parameter.

For the Web API, issue the GET message and look at file size:
fileSize = int.Parse(response.Headers.GetValues("x-ms-file-size").First());

Do not then call this to get the file content.
var responseContent = await response.Content.ReadAsByteArrayAsync();
