### ISSUE TITLE
Nothing about context variables

### ISSUE THREAD

**Issue by rappen** [MicrosoftDocs/powerapps-docs#338]
Searching for information about context variables in the Navigate method, this page seems like a perfect match with it having hte url: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-screen-context-variables
But that is quite misleading, since there is not a single reference to context variables here...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c6b0e8-945d-50ed-f158-d58a26787151
* Version Independent ID: 843315bc-e19b-b2d4-0425-292983ae274b
* Content: [Add a screen to a canvas app and navigate between screens - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-screen-context-variables#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/add-screen-context-variables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-screen-context-variables.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is being updated, please allow some time to reflect the change.
