### ISSUE TITLE
Azure Synapse Link for Dataverse - near-real-time vs snapshot

### ISSUE THREAD

**Issue by SimonSellickSRA** [MicrosoftDocs/powerapps-docs#3380]
The section on [accessing snapshot data](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-synapse#access-near-real-time-data-and-read-only-snapshot-data-preview) states that two versions of each non-empty table will be created, a near-real-time version called _table-name_ and a snapshot version _table-name_\_partitioned.  That does not seem to happen with our links and I suspect that it has to be enabled, either per table or for the link profile as a whole.  Could you add more detail to this section please, so that we know how to set it up and use it?  Thanks.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a924e8-1757-5b5a-ad6d-930e316c3196
* Version Independent ID: 6fac1727-bb8a-f993-e480-d9bcfc8ef9f7
* Content: [Create an Azure Synapse Link for Dataverse with your Azure Synapse Workspace - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-synapse#access-near-real-time-data-and-read-only-snapshot-data-preview)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-synapse.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-synapse.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SimonSellickSRA. This issue has been assigned to the doc author for review.

**Comment by JasonHQX** [comment]
Hi [SimonSellickSRA](https://github.com/SimonSellickSRA)
The snapshot feature will be automatically enabled after synchronization. May I know your region in advance?

**Comment by SimonSellickSRA** [comment]
Hi @JasonHQX thank you for your reply. We are in UK South region.  The initial sync finished some weeks ago but the _table-name_\_partitioned tables have not appeared (and we do get frequent SQL failures caused by the CSV files being updated at the same time as the query executes).  I can see 'snapshot' folders in the storage containers, one per table.

**Comment by JasonHQX** [comment]
Hi, we are enabling that feature globally for everyone. And I believe we are enabling this region by region by End of this week 05/20. So, it should be available now.

**Comment by SimonSellickSRA** [comment]
Thanks @JasonHQX still no sign of the partitioned tables (or are they views?).  You said above "_The snapshot feature will be automatically enabled after synchronization._" - would a table having reported failures prevent the feature being enabled? The profile contains 33 tables, of which 32 have successfully synchronised and one reports "Completed with failures" - but there is no obvious facility to investigate or correct those failures. I've already unlinked and re-linked it, and it failed again. It's a relatively large table (7 million rows) so it takes a couple of days to sync.

**Comment by SimonSellickSRA** [comment]
Hi @JasonHQX do you mean I should create a new support request asking for UK to be made a priority?  I already have a request open to get the initial sync issues resolved (2205030050002158), and another to sort out the read-during-write contention (2204220050000546).  Also, what ID are you referring to (subscription? org? ...?).  Sorry if I am missing something obvious, and thank you for your advice.

**Comment by SimonSellickSRA** [comment]
@JasonHQX thanks again for your advice. Do you know the target release date for islands migration for UK?

**Comment by JasonHQX** [comment]
@Mattp123 Can you help close this issue? It is not related to documentation. User should submit support ticket for this.

**Comment by Mattp123** [comment]
Closing issue.
