### ISSUE TITLE
I have been trying to follow the instructions to make ideas editable by original creator, but around step 21 the instructions don't seem to be accurate.  The references to copied components/galleries/containers seem to be numbered improperly.  i.e., Step 26 references lbldeaFiles_Header_2, but we have only copied that item once.  So, there is no lbldeaFiles_Header_2.  Have steps been accidentally removed from these directions?  https://docs.microsoft.com/en-us/power-apps/teams/make-ideas-editable-by-original-creator

### ISSUE THREAD

**Issue by EBW3** [MicrosoftDocs/powerapps-docs#3381]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9994f359-441c-53ae-af57-2b8d4af888dc
* Version Independent ID: 201b194c-b42a-d6f0-51ef-51693d1af5fa
* Content: [Screen control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-screen)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-screen.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-screen.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @EBW3. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please review the latest version of the [app templates and documentation](https://github.com/microsoft/teams-powerapps-app-templates). If the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
