### ISSUE TITLE
Editing is not being limited to the idea originator

### ISSUE THREAD

**Issue by EBW3** [MicrosoftDocs/powerapps-docs#3383]
I have the functionality up and running, mostly.  The one issue that I have is that an idea can be edited by any user, not just the creator/originator.  Can you please point me to the portion of the code / formula that should be limiting the edits to the crato/originator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73fed2c1-db9f-18f7-987c-49bb4c758953
* Version Independent ID: d1233074-038e-e535-564d-43a8f37ac6e0
* Content: [Make ideas editable by original creator (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/make-ideas-editable-by-original-creator)
* Content Source: [powerapps-docs/teams/make-ideas-editable-by-original-creator.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/make-ideas-editable-by-original-creator.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **saperlmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @EBW3. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please review the latest version of the [app templates and documentation](https://github.com/microsoft/teams-powerapps-app-templates). If the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
