### ISSUE TITLE
OnSelect formula missing 2726305

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/powerapps-docs#3384]
[Enter feedback here]
Please add a Formula reference for **OnSelect**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed900e9-0ac8-8914-2bee-b04e4ebd725d
* Version Independent ID: 0ef1f99f-00f3-8344-9bd7-6cbfd96a789a
* Content: [Formula reference for Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/formula-reference#o)
* Content Source: [powerapps-docs/maker/canvas-apps/formula-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/formula-reference.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Dlutchy. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. If you're looking for the "Select" function, it's already available in the formula reference. OnSelect whereas a property. 

https://docs.microsoft.com/power-apps/maker/canvas-apps/functions/function-select
