### ISSUE TITLE
Is function in preview?

### ISSUE THREAD

**Issue by vcqn11** [MicrosoftDocs/powerapps-docs#3385]
According to the settings view in the app, the 'In-App Notification' is not in preview (see screenshot).
But the documentation says it is. What is the correct status here?
![image](https://user-images.githubusercontent.com/106057582/169757706-56b96279-956d-48bb-9578-3e847358a1ee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f495f03e-28c9-0ebb-ef03-72e16b267b3a
* Version Independent ID: a9dcec59-8b72-966e-fa53-f4b2e42d325e
* Content: [Send in-app notifications within model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vcqn11. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Looks like the (Preview) markers in the topic were removed but this issue wasn't closed.
