### ISSUE TITLE
Where is the import data button?

### ISSUE THREAD

**Issue by amychaplin** [MicrosoftDocs/powerapps-docs#3386]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1da38d28-fbc3-b3a8-c3d8-c7cd7d2ce39b
* Version Independent ID: e1f69e15-9955-22c2-3364-4ebd6f2b30f6
* Content: [Show, sort, and filter data in a canvas app gallery - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/show-images-text-gallery-sort-filter)
* Content Source: [powerapps-docs/maker/canvas-apps/show-images-text-gallery-sort-filter.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/show-images-text-gallery-sort-filter.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @amychaplin. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@amychaplin Thank you for the feedback, I'm closing out the issue since it's been almost a year since it was opened. However, I will being working with our internal team to review and update this topic as some of the info is out dated.

Thank you,
Mints
