### ISSUE TITLE
Contradicting Time Statement

### ISSUE THREAD

**Issue by polks71** [MicrosoftDocs/powerapps-docs#3387]
[Enter feedback here]
Under Reporting Infrastructure the last sentence of the first paragraph says "We do not place time restrictions on reports."
Then the first bullet point after "Consider these fixed settings:" says "Reports and queries can execute for up to five minutes."

Which statement is true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0bca2c-656a-8797-83c7-bcec85bcbe65
* Version Independent ID: add37b71-e881-75b2-ce79-7698a0e3b4be
* Content: [Reporting considerations - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/reporting-considerations#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/reporting-considerations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/reporting-considerations.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @polks71. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@polks71 - Thank you for your feedback. You are correct that the sentence contradicts the timeout limit so that sentence has been removed from the article. Closing issue.
