### ISSUE TITLE
webFormClientValidate must be declared first

### ISSUE THREAD

**Issue by Nydi23** [MicrosoftDocs/powerapps-docs#3388]
the webFormClientValidator is called, but it seems the first validation needs to be the one that creates the function for example:
` if (window.jQuery) {
    (function ($) {
       if (typeof (webFormClientValidate) != 'undefined') {
          var originalValidationFunction = webFormClientValidate;
          if (originalValidationFunction && typeof (originalValidationFunction) == "function") {
             webFormClientValidate = function() {
                originalValidationFunction.apply(this, arguments);
                // do your custom validation here
                // return false; // to prevent the form submit you need to return false
                // end custom validation.
             };
          }
        }
        else{
            webFormClientValidate = function(){
                // do your custom validation here
                // return false; // to prevent the form submit you need to return false
                // end custom validation.
            }
        }
    }(window.jQuery));`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd59aca-5cd6-54bf-d119-f49b6e0098aa
* Version Independent ID: 95689207-a0b9-8336-595c-8a00f6906dee
* Content: [Add custom JavaScript - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/configure/add-custom-javascript?source=docs)
* Content Source: [powerapps-docs/maker/portals/configure/add-custom-javascript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/add-custom-javascript.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Nydi23. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for the feedback. We have updated the sample code to resolve the issues.
