### ISSUE TITLE
case is incorrect in contents addtabStateChange should be addTabStateChange

### ISSUE THREAD

**Issue by JamesHorsley** [MicrosoftDocs/powerapps-docs#3389]
In the contents on LHS this method is shown ad addtabStateChange but it should be addTabStateChange because case is significant in JavaScript

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c2a4cc8-11ca-0379-445a-ca8cdde8664b
* Version Independent ID: efe6fd94-6494-d278-a935-ca9aa9dc4c03
* Content: [addTabStateChange (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-ui-tabs/addtabstatechange)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-tabs/addTabStateChange.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-tabs/addTabStateChange.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JamesHorsley. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Fixed the table of contents to match. addtabStateChange to be addTabStateChange
