### ISSUE TITLE
Default import setup option in PowerApps package should be "Create as new"

### ISSUE THREAD

**Issue by alexchx** [MicrosoftDocs/powerapps-docs#339]
The package below wasn't exported following the best practice, as the import setup option wasn't set as "Create as new" during the exporting, this is a trap for the PowerApps beginners, and because of this reason, one of my teammate made a mistake to overwrite an app used for client demo, I know your document already mentioned to change the default option, but that would be much better if you could change the default option in the package to "Create as new".

http://pappsfeprodwestuscontent.blob.core.windows.net/sampleapps/myexpenses/docs/MyExpenses(SP_List).zip

**Comment by AFTOwen** [comment]
Thanks for your feedback, @alexchx. For product-related feedback, visit the [forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.
