### ISSUE TITLE
Number of Gateways

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#34]
When should additional gateways be installed? how many gateways are allowed in a tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042aa853-3571-5081-a83b-25235a4949fa
* Version Independent ID: d4049a41-6d7e-0ebd-8c17-68223a8e327b
* Content: [Manage an on-premises data gateway for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-management)
* Content Source: [powerapps-docs/maker/canvas-apps/gateway-management.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/gateway-management.md)
* Service: **powerapps**
* GitHub Login: @archnair
* Microsoft Alias: **archanan**

**Comment by linhtranms** [comment]
Hi Dean, thanks for your questions. 

When should additional gateways be installed? 
A gateway is usually installed on an always on box. Once you have it installed, you can use it to access your on-premise data (SQL, SharePoint, etc.) Currently, a gateway is linked to an environment. I don’t believe you can link a gateway to multiple environments today. So in theory, it’s very less likely you’d need to have multiple gateways installed. 

How many gateways are allowed in a tenant? 
I don’t think there’s restriction on the # of gateways to be installed in a tenant. Pretty much any user in a tenant can install a gateway for their usage.

**Comment by linhtranms** [comment]
Hi Dean, 

In theory, it is unlikely that you'll need to install multiple gateways. Though you can if you wish to. It could be useful for capacity and high availability reasons. If a gateway is heavily utilized, it would make sense to install several to split the load. Note though, you can only install one gateway per a dev box. So if you want multiple gateways, you need several always on computers and install one on each. 

There is no restriction on the number of gateways you can install in a tenant today. Any user in a tenant can install a gateway for their usage is the behavior today. Though in the future, we might allow administrator to control who can install and use gateway.
