### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by msftyehong** [MicrosoftDocs/powerapps-docs#3400]
The page (whose title 'Supported web browsers for Power Apps portals') lists IE as supported browser but says 'Internet Explorer (not recommended)'. The page also says that 'Microsoft Internet Explorer 11 support is deprecated' (and link to the announcement). These statements somewhat contradict each other. 

Is IE supported or not?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95311735-81f8-9c35-333f-97caad86f6f5
* Version Independent ID: eb4c16f2-c43a-282c-b461-d699c2daf0ff
* Content: [Supported web browsers for Power Apps portals - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/supported-web-browsers)
* Content Source: [powerapps-docs/maker/portals/supported-web-browsers.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/supported-web-browsers.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @msftyehong. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for the feedback. To answer the question, Internet Explorer is not supported. The redirection of this link is being fixed. The current guidance for Power Apps (including Power Apps portals) is here: [https://docs.microsoft.com/power-apps/limits-and-config](https://docs.microsoft.com/power-apps/limits-and-config)
