### ISSUE TITLE
This guide is broken by updates

### ISSUE THREAD

**Issue by felicemasi** [MicrosoftDocs/powerapps-docs#3402]
Hi, I found this very useful guide months ago, and implemented it step by step in a small app project I am devving.

It works fine, but since monday 23rd I can't successfully edit the app in which this component is used anymore.
I mean, I can save ignoring the error, but this will break the app (no translations).
An error icon is shown on the component's top left corner, but the error details don't say much, and no variable or property is highlighted when I click "show me the error".

So for now I restored the last version from 2 weeks ago, and until I don't edit it, it works.

I even tried rebuilding the component from scratch, but same error shows up.
My locale is italian (I can't change it, or I would have tried setting it to english) so my code accepts semicolons (;) instead of commas (,).

I fear some backend update broke something with non english locale.

Thanks for any hints!

FM
![PowerApps-translation-1_LI](https://user-images.githubusercontent.com/106332440/170537123-f2853ec1-dde8-489f-a62b-152f72ac196c.jpg)
![PowerApps-translation-2_LI](https://user-images.githubusercontent.com/106332440/170537128-7485f526-8bbd-4e7f-bd77-941ea036be96.jpg)

EDIT: forgot the attachments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b557d3-7967-698e-38e0-e28ad06df9df
* Version Independent ID: 55105264-7746-12ac-b3db-c34eb96b429f
* Content: [Build a multi-language app - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/multi-language-apps)
* Content Source: [powerapps-docs/maker/canvas-apps/multi-language-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/multi-language-apps.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **lunune**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @felicemasi. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please reach out to support teams for investigating this problem using a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support).

**Comment by felicemasi** [comment]
> Thank you for reaching out. Please reach out to support teams for investigating this problem using a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support).

Hi Tapan,

I can't open tickets, and no one in my company seems to know how to do it.

**Comment by felicemasi** [comment]
> Thanks for your comment, @felicemasi. This issue has been assigned to the doc author for review.

Hi Bishal, thanks for your help, but I don't think the guide itself is broken, just that MS backend somewhat started messing up with locales.

I can't open tickets myself, as someone in my company decided so, but no one seems to know who actually can.

I guess I'll have to wait for the corporate IT to figure that out :D

Thanks, regards
