### ISSUE TITLE
Typo in powerapps-docs/powerapps-docs/maker/portals/customer-engagement-apps/manage-blogs.md

### ISSUE THREAD

**Issue by joshua-soto-kitcher** [MicrosoftDocs/powerapps-docs#3408]
Under Manage Blogs, the first line "Learn how to manage blog comments and blog posts both within Portalsand from the portal content editor."

It should be "Learn how to manage blog comments and blog posts both within Portals and from the portal content editor."

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed and the changes will be reflected soon.
