### ISSUE TITLE
Attachment control not getting reset for new powerapp form

### ISSUE THREAD

**Issue by soyebmalek** [MicrosoftDocs/powerapps-docs#341]
Hi Team,

I faced an issue is that after submitting couple of items with attachment in SharePoint List using PowerApp Form . Previous attached file is by default coming new items.

All other fields are reset/clear but attachment control is not getting reset.
Please try to reproduce issue.

Help would appreciated.

**Comment by AFTOwen** [comment]
“Thanks for your feedback, @soyebmalek. For product-related feedback, visit the [forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.
