### ISSUE TITLE
Power-Apps Mobile for Windows doesn't surface Model Driven apps

### ISSUE THREAD

**Issue by rcatbp** [MicrosoftDocs/powerapps-docs#3410]
My model driven apps on a DEV Sandbox environment do not appear.
This is not the Enterprise default environment.

The Apps do appear on the Android version if I click the settings box 'show non-production'

The Settings screen on the Windows 10 version is blank, no settings to change. 

It may be preview but we'd like to test model driven apps 

Thanks, Richard

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1013f138-6f33-1483-b3ff-b58de9c8bf50
* Version Independent ID: 1013f138-6f33-1483-b3ff-b58de9c8bf50
* Content: [Install Power Apps for Windows (preview) - Power Apps](https://docs.microsoft.com/en-gb/power-apps/mobile/windows-app-install)
* Content Source: [powerapps-docs/mobile/windows-app-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/mobile/windows-app-install.md)
* Service: **powerapps**
* Sub-service: **mobile**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@rcatbp Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/.

Closing this issue.
