### ISSUE TITLE
Videos are unavailable

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#3411]
All 3 videos on this page are "Unavailable".

![image](https://user-images.githubusercontent.com/8636973/171207105-3bf7afcf-5773-46b9-876e-a157d5dace05.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b64c8d-3c3d-4e4d-afb1-5e0a54c84046
* Version Independent ID: 8180bdbe-ec98-642e-b7ee-1f57954ee502
* Content: [Create virtual tables using virtual connectors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors?tabs=sql)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by JimDaly** [comment]
Thanks for reporting this.
The change has been checked in and should go live in a few hours.
