### ISSUE TITLE
Rich Text control documentation changes

### ISSUE THREAD

**Issue by kolyapnl** [MicrosoftDocs/powerapps-docs#3412]
We were misled and tried to change the entity's security permissions based on the documentation (https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/rich-text-editor-control#best-practices-for-using-the-rich-text-editor) - _"By default, the rich text editor will upload images to the Azure Blob storage store and they won’t be stored as part of the field. Images will be stored in the same field as base64 when the submitter doesn’t have permissions to the msdyn_richtextfiles entity. Base64 content is large, so you generally don't want to store images as base64."_ 
to change how we want images to be stored. 
 
It took 1+ month to resolve the confusion and we found individual settings (https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/rich-text-editor-control#individual-configuration-settings) - disableDefaultImageProcessing
 
Would it be possible to modify documentation to avoid confusion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ecdffd-f6c2-4fc2-2d74-94d16c18108c
* Version Independent ID: cb939451-df9d-23b2-5e98-e2519c3b90db
* Content: [Use the rich text editor control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/rich-text-editor-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/rich-text-editor-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/rich-text-editor-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **craigm**

**Comment by Mattp123** [comment]
@kolyapnl - Please see above comment from the Power Platform engineering team. 
Closing issue.
