### ISSUE TITLE
[Power Apps Custom Domains] When will support for AES encryption on the SSL certs be added?

### ISSUE THREAD

**Issue by chadsowald** [MicrosoftDocs/powerapps-docs#3414]
This page notes that TripleDES encryption is required for the custom domain SSL cert and that AES encryption is not supported.  However, TripleDES is considered less secure than AES.  Is there a reason for this limitation and/or a timeline for supporting AES?  The document does not mention either way.   A customer ran into this issue and had to do manual work to adjust their newly renewed certificate from AES to TripleDES to make the Power Apps portal happy, but they consider it a security risk and want to avoid it in a year's time when the cert will renew again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8c6740-12c2-5a24-9c67-55f8485fe957
* Version Independent ID: 1225db21-8bd8-ba23-ccb6-e659d92bf40b
* Content: [Add a custom domain name - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/admin/add-custom-domain)
* Content Source: [powerapps-docs/maker/portals/admin/add-custom-domain.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/add-custom-domain.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @chadsowald. This issue has been assigned to the doc author for review.
