### ISSUE TITLE
Quick Start sample uses deprecated library

### ISSUE THREAD

**Issue by jrichview** [MicrosoftDocs/powerapps-docs#3415]
The Quick Start sample app uses Microsoft.IdentityModel.Clients.ActiveDirectory which is deprecated. Would urge you to update the sample to use Microsoft.Identity.Client or at minimum clearly document steps for users to do that update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 489a9802-ac7a-0809-eaf9-684bc1286be6
* Version Independent ID: ce185321-294f-683e-979b-8046f318800f
* Content: [Sample: Simplified connection quick start (Developer Guide for Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/xrm-tooling/sample-simplified-connection-quick-start)
* Content Source: [powerapps-docs/developer/data-platform/xrm-tooling/sample-simplified-connection-quick-start.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/xrm-tooling/sample-simplified-connection-quick-start.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **mbarbour**

**Comment by phecke** [comment]
@jrichview The sample uses a connection string with the CrmServiceClient class for authentication. While ADAL is used behind the scenes by CrmServicveClient, you should not be concerned about that. CrmServiceClient will probably be updated in the future to use MSAL, or everyone will migrate over to the new ServiceClient class which uses MSAL.
