### ISSUE TITLE
Missing verb in paragraph? 

### ISSUE THREAD

**Issue by anjagusev** [MicrosoftDocs/powerapps-docs#3416]
I believe the Data Partioning section starting paragraph has a missing word (https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-advanced-configuration#data-partitioning). 

Currently it reads 👇
"When you Dataverse table data to Azure data lake storage using Azure Synapse Link, the tables are partitioned (instead of a single file) in the lake based on the createdOn value on each row in the source."

I think there is a verb missing there... the following would make more sense 👇
>When you replicate Dataverse table data
instead of 
>When you Dataverse table data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1d5f787-fa5e-c749-4414-a8a14309510e
* Version Independent ID: 7d5c052e-dd60-caa8-740e-eb9cf774ed9a
* Content: [Azure Synapse Link Advance Configuration - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-advanced-configuration)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-advanced-configuration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-advanced-configuration.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed.
