### ISSUE TITLE
ReadPermission, CreatePermission, EditPermission, DeletePermission does not currently work

### ISSUE THREAD

**Issue by 365lyf** [MicrosoftDocs/powerapps-docs#342]
It appears as though ReadPermission, CreatePermission, EditPermission, DeletePermission is not properly implemented at the moment, and always returns true regardless of the permission (at least under CDS that is the case).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88f61718-e69d-1a9d-8785-40b94e06dbe3
* Version Independent ID: d1dac2ee-0857-680a-54c7-57ecf7f7617f
* Content: [DataSourceInfo function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-datasourceinfo)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-datasourceinfo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-datasourceinfo.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Thanks for your feedback, @365lyf . For product-related feedback, visit the [forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.

cc: @gregli-msft
