### ISSUE TITLE
Randomly Getting "You Do Not Have Permission to Commit to This Repository"

### ISSUE THREAD

**Issue by avidNewb** [MicrosoftDocs/powerapps-docs#3421]
Frequently receive the pictured message.  My repo is stored in ado.  This happens to both I and the coworker I am developing with.  Once it happens, you can click "Ok" and it will ask for your git credentials.  The same username and token that you logged in with won't work though.  The fix is to log out of and back in to PowerApps.  Then you can log in and usually will allow you to save for a while.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/59672137/171947510-500041c5-ab56-481e-ad94-a2e7041d508d.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dcec321-a287-a483-241d-69b147737f23
* Version Independent ID: 1dcec321-a287-a483-241d-69b147737f23
* Content: [Co-authoring in canvas apps (experimental) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/git-version-control)
* Content Source: [powerapps-docs/maker/canvas-apps/git-version-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/git-version-control.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/
