### ISSUE TITLE
Delegation List Link Is Broken

### ISSUE THREAD

**Issue by carlilelance** [MicrosoftDocs/powerapps-docs#3422]
The delegation list link is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c435aad5-5a0b-6070-1138-d80a13606122
* Version Independent ID: d9978c1c-e720-9586-8439-5b030f42794c
* Content: [Filter, Search, and LookUp functions in Power Apps (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/functions/function-filter-lookup)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-filter-lookup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/functions/function-filter-lookup.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Content has been fixed and will reflect the changes soon.
