### ISSUE TITLE
Insufficient Information

### ISSUE THREAD

**Issue by ddobric** [MicrosoftDocs/powerapps-docs#3426]
This article describes how to create the Application Package, which is saved as a zip file at the end.
However, to publish the application to the AppSource, the MSIX or APPX packages is required.

![image](https://user-images.githubusercontent.com/1756871/172375657-f471fc70-c975-46e9-9603-fbcc4c769a55.png)

The article seems not to be complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2c7898-1e5f-184c-bb89-8acdf96c0023
* Version Independent ID: f46bf08e-14dc-4111-c74e-db374f377566
* Content: [Step 3: Create an AppSource package for your app (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/create-package-app-appsource)
* Content Source: [powerapps-docs/developer/data-platform/create-package-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/create-package-app-appsource.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by VishalShrivas** [comment]
Hello, I have an issue with this link https://docs.microsoft.com/en-us/power-apps/developer/data-platform/create-solution-app-appsource. How to create a managed file with dll file and package folder, and in this link https://docs.microsoft.com/en-us/power-apps/developer/data-platform/create-package-app-appsource, how to use this managed folder in Offer center. I followed https://docs.microsoft.com/en-us/power-apps/developer/data-platform/publish-app-appsource to publish appsource for the Power App project.

**Comment by KumarVivek** [comment]
@ddobric The app publication on AppSource is documented in the Partner Center: https://learn.microsoft.com/en-us/azure/marketplace/dynamics-365-customer-engage-technical-configuration

If you see the guidance above, it uses the CRM Package from Azure Blob Storage as we explained earlier. If you are facing issues with AppSource, pls raise an issue on the above article.

Closing the issue.
