### ISSUE TITLE
PowerApps is not converting Figma UI Kit files

### ISSUE THREAD

**Issue by javenu** [MicrosoftDocs/powerapps-docs#3428]
When I follow the directions to publish a Canvas App from Figma, the popup in PowerApps consistently gives me invalid failures, both on the Link to Figma page input and the Figma personal access token fields input. 

I have tried links to pages, frames, both using node-ids, to no avail. At the very least the personal access token field should work. I have tried both canvas and phone apps; even tried to publish/import the Sample phone app. All attempts invalid. 

I am an MSFT employee, accessing Figma and PowerApps from behind the company firewall using company hardware.
I see my Figma Design Role is Viewer, not sure if this feature requires Editor, the docs don't specify a required role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a029527d-8a76-d381-41bc-537576271899
* Version Independent ID: a029527d-8a76-d381-41bc-537576271899
* Content: [Troubleshoot common errors when creating app from Figma (preview) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/figma/common-errors)
* Content Source: [powerapps-docs/maker/canvas-apps/figma/common-errors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/figma/common-errors.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **kaagar**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, this issue is being discussed internally and documentation will be updated as needed.
