### ISSUE TITLE
Input Mask (retired)

### ISSUE THREAD

**Issue by IDJordash** [MicrosoftDocs/powerapps-docs#3429]
[This article](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/additional-controls-for-dynamics-365-for-phones-and-tablets) indicates input mask control as being available in classic. The control is indeed available, but now appears retired. Can you please indicate what is expected to replace this control?
![image](https://user-images.githubusercontent.com/104447021/172557365-1c5b7c9e-b887-428d-8dcd-26849caaecb5.png)

**Comment by Mattp123** [comment]
@IDJordash - Thank you for your feedback. The plan is to have text field support regular expression (regex) as part of ongoing work with fluent UI controls, but that has been pushed out to early next year. Expect the "retired" text in the input mask control name to be removed soon in the interim.

[Modern Fluent UI controls in Power Apps (preview)](https://powerapps.microsoft.com/fr-be/blog/modern-fluent-ui-controls-in-power-apps-preview/)

Closing issue.
