### ISSUE TITLE
Minor inconsistency (very low importance)

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#343]
Greetings,
This is quite trivial and unimportant.

In "Add and select a control", at the end of the section, before the note:

"To select the label again, you can click or tap in it, or you can click or tap Label2 in the hierarchical list of controls."

&gt;&gt; The text should say "Label1" instead of "Label2" : all pictures on the page are showing "Label1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53616064-ae0b-0569-4a56-f4cdf8dd2cbf
* Version Independent ID: cf3299c3-6840-c8eb-f820-567951798905
* Content: [Add and configure a canvas-app control - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-configure-controls)
* Content Source: [powerapps-docs/maker/canvas-apps/add-configure-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-configure-controls.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Fixed by changing the reference to "its name" because the numeral at the end of the name changes depending on whether you've added/deleted a control of the same type at least once. Thanks, @a-zaf!
