### ISSUE TITLE
Power Apps does not support the Azure Cognitive Service for Language Connector.

### ISSUE THREAD

**Issue by rickmcguire** [MicrosoftDocs/powerapps-docs#3430]
We should remove this content as Azure Cognitive Service for Language, previously known as 'Text Analytics' connector does not support Power Apps directly. 

The connector does not support Power Apps -
https://docs.microsoft.com/en-us/connectors/cognitiveservicestextanalytics/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94ef556-ce8a-29d7-1839-1c081fdeee3f
* Version Independent ID: d56f35f1-3857-8399-eb79-434b40de0a46
* Content: [Use Cognitive Services in canvas apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/cognitive-services-api)
* Content Source: [powerapps-docs/maker/canvas-apps/cognitive-services-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/cognitive-services-api.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rickmcguire. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been retired.
