### ISSUE TITLE
Should mention that return value could be null

### ISSUE THREAD

**Issue by beyro** [MicrosoftDocs/powerapps-docs#3433]
[Enter feedback here]
The `attribute.getValue` method returns null if the attribute does not have a value, but this is not reflected in the documentation. For example, lookup type says that it will return an array. It should say that it will return an array or null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae10e81-fc06-bb27-708c-71082460571a
* Version Independent ID: ecf78692-311d-c121-faf7-aaed40f46c6a
* Content: [attribute.getValue (Client API reference) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/attributes/getvalue)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getValue.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getValue.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @beyro. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@beyro 
Thanks for your feedback.

I've changed the description of the return value

**Old:**

## Return Value

**Type**: Depends on the type of column.

**New:**

## Return Value

**Type**: Depends on the type of column. The value may be null.
