### ISSUE TITLE
Missing email address in step 10 causing 'Update Vote Detail' step to fail

### ISSUE THREAD

**Issue by aphexer** [MicrosoftDocs/powerapps-docs#3434]
Fetch XML in Step 10:
`<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="true">
   <entity name="systemuser">  
      <attribute name="fullname" />
      <attribute name="systemuserid" />
      <link-entity name="msft_employeeidea_systemuser_vote" from="systemuserid" to="systemuserid" visible="false" intersect="true">
      <link-entity name="msft_employeeidea" from="msft_employeeideaid" to="msft_employeeideaid" alias="aa">
      <filter type="and">
            <condition attribute="msft_employeeideaid" operator="eq" value="@{items('Update_Vote_Detail')?['msft_employeeideaid']}" />
          </filter>    
      </link-entity>
   </link-entity>
   </entity>
</fetch>`

-> There is no output attribute 'internalemailaddress'

This is required however by step 14:
Inside the nested apply to each step added in step 13, add an Office 365 Users Get user profile (V2) step. Select the Primary Email from the list voters step User (UPN) field.

Because of the missing 'internalemailaddress' attribute, updating vote details will fail because the input into 'Get user profile (V2)' will be null.

The fix is to add `<attribute name="internalemailaddress" />`

The corrected fetch XML for step 10 then becomes:

`<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="true">
   <entity name="systemuser">  
      <attribute name="fullname" />
      <attribute name="systemuserid" />
      <attribute name="internalemailaddress" />
      <link-entity name="msft_employeeidea_systemuser_vote" from="systemuserid" to="systemuserid" visible="false" intersect="true">
      <link-entity name="msft_employeeidea" from="msft_employeeideaid" to="msft_employeeideaid" alias="aa">
      <filter type="and">
            <condition attribute="msft_employeeideaid" operator="eq" value="@{items('Update_Vote_Detail')?['msft_employeeideaid']}" />
          </filter>    
      </link-entity>
   </link-entity>
   </entity>
</fetch>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 620aee88-efbc-394f-0cbb-79be3f4a6bd2
* Version Independent ID: 632dd319-a22f-a4b7-a2da-f60538b1e4e6
* Content: [How to export Ideas data for reporting (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/export-employee-ideas-for-reporting)
* Content Source: [powerapps-docs/teams/export-employee-ideas-for-reporting.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/export-employee-ideas-for-reporting.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **saperlmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @aphexer. This issue has been assigned to the doc author for review.

**Comment by jslitzkerttcu** [comment]
Just adding a +1 to this fix.  I also ran into the same issue and correcting the fetchxml fixed the issue.

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please use the latest version of the app templates, and if the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
