### ISSUE TITLE
Does cover Component Libraries Within Teams

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#3436]
This page does not cover what happens with PowerApps Component libraries when imported into Teams.  It should either be here or on a new page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0224ad-fdbb-c741-98a7-3ec0764b10cf
* Version Independent ID: dfbaaa9e-b902-70de-49d8-9d6c5328b6d2
* Content: [Component library - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/component-library)
* Content Source: [powerapps-docs/maker/canvas-apps/component-library.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/component-library.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @NPrice99. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@jorisdg assigning this to you.

**Comment by jorisdg** [comment]
Component libraries for Teams were only just supported and rolled in the Dec22/Jan23 timeframe. We've removed it from the limitations list in the Teams docs, we still need to document the few UI navigation differences still.

**Comment by mduelae** [comment]
Thank you for your feedback. We have added this to our backlog and will try to get the documentation published soon as possible.

Thank you for your patience.
Power App Doc Team
