### ISSUE TITLE
Microsoft PowerApps CLI

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#344]
Hi
Is this not moving away from the PowerApps "NoCode" mantra ?
Regards
Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4b9e58-d9d3-c387-fe6a-258ebe78516d
* Version Independent ID: 22d89b45-e427-1ab9-b456-7d7750585b52
* Content: [Create custom component using PowerApp Component Framework Tooling - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/create-custom-controls-using-pcf)
* Content Source: [powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@NPrice99 Thanks for  your feedback. Please raise your ideas [here](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Closing this issue
