### ISSUE TITLE
Plug-in registration isolation mode

### ISSUE THREAD

**Issue by tdutch1** [MicrosoftDocs/powerapps-docs#3445]
Under Step 1, item 6, the image shows that the isolation mode is set to "None", but since this is an article about Dataverse (online, not on-prem), how were the authors of the article able to select "None"? 

Is it necessary to register a plug-in with isolation mode "None" to connect to Azure SQL from a custom Dataverse plug-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edbeb418-f5d9-da8d-7598-d4965f666e50
* Version Independent ID: f28b539d-69f1-5f2e-6f32-4248cb96eedf
* Content: [Sample: Custom virtual table provider with CRUD operations (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/sample-ve-provider-crud-operations)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/sample-ve-provider-crud-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/sample-ve-provider-crud-operations.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tdutch1. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@tdutch1 Not sure. For online, Sandbox would be checked. Perhaps the author used an existing image he had and did not notice the discrepancy.

@NHelgren Any comments?

**Comment by tdutch1** [comment]
It appears that Dataverse now accepts the use of classes in assembly System.Data.SqlClient, at least for purposes of creating virtual tables. However, there are two problems with the article that I think the authors should resolve. 

First, the selection of "None" for the plug-in isolation mode in the plug-in registration tool screen capture is misleading. 

Second, a Power Platform MVP wrote the following in the book "Microsoft Dynamics 365 Extensions Cookbook": "Even using the System.Data.SqlClient library will throw a security restriction exception. This is due to the sandbox mode limitations that do not permit some classes' instantiations.". In my opinion, the article should mention that Microsoft previously restricted the use of System.Data.SqlClient from plug-ins but has recently allowed it.

The combination of those two issues with the article caused us to believe that the functionality was for on-premises use only.

**Comment by phecke** [comment]
@tdutch1 Unless we document that you can use classes from System.Data.SqlClient in a plug-in, it is not supported - even if it works. I can see from the docs for VE, there may be an exception.

There is a new capability on the verge of being released - [Dependent assemblies support for plug-ins](https://docs.microsoft.com/power-platform-release-plan/2022wave2/data-platform/dependent-assemblies-support-plug-ins). Perhaps that is the solution to issues like this.

**Comment by phecke** [comment]
@NHelgren What is the support for the use of classes from System.Data.SqlClient in VE plug-ins? Is that namespace fully supported or partially? 

In the figure just above this [link](https://docs.microsoft.com/power-apps/developer/data-platform/virtual-entities/sample-ve-provider-crud-operations#step-2-creating-data-provider-and-adding-plug-ins-to-the-provider), why is **None** selected during assembly registration instead of **Sandbox** for the isolation mode? Should this be changed in the topic?

**Comment by tdutch1** [comment]
@phecke Thanks for the warning about using the potentially unsupported System.Data.SqlClient in plug-ins for Dataverse. The "[supported customizations](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/supported-customizations#unsupported-customizations)" page does not indicate that the use of System.Data.SqlClient is supported and it also states that "The use of application programming interfaces (APIs) other than the documented APIs" is unsupported. I think continuing to use OData or creating a custom API to interact with Azure SQL is best until this plugin-base approach is further built out, documented and MS Support is up to speed on it.

**Comment by phecke** [comment]
@tdutch1 Now that dependent assemblies are supported for plug-ins, you can use System.Data.SqlClient if you upload a plug-in package containing its assembly. See [Dependent Assembly plug-ins](https://learn.microsoft.com/power-apps/developer/data-platform/dependent-assembly-plugins).
