### ISSUE TITLE
Link to Office 365 plans is broken

### ISSUE THREAD

**Issue by xerxel** [MicrosoftDocs/powerapps-docs#345]
This link is broken:

Q: Do I need a PowerApps license to create or use custom list forms?

A: You need an Office 365 plan that includes PowerApps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @xerxel!
