### ISSUE TITLE
Korean input bug in PowerApps Windows app

### ISSUE THREAD

**Issue by glittery11** [MicrosoftDocs/powerapps-docs#3450]
When inputting Korean in the Power Apps Windows app(App from Microsoft Store [https://apps.microsoft.com/store/detail/power-apps-preview/9MVC8P1Q3B29](https://apps.microsoft.com/store/detail/power-apps-preview/9MVC8P1Q3B29) ) , consonants and vowels are input separately. This is a fatal issue for every Korean, so this app cannot be used.
Power Apps for Windows 8 App had the same trouble.

In browsers and Teams, it works without any problems.

![1](https://user-images.githubusercontent.com/88357418/173965217-b263a5aa-be8d-4588-8d1b-5a02c8aaf8fa.png)
Teams-WindowsApp-Browser

**Comment by phecke** [comment]
@glittery11 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ Closing this issue.

We do handle issues with the product documentation.
