### ISSUE TITLE
Clarity on where test suites/cases live?

### ISSUE THREAD

**Issue by virakones** [MicrosoftDocs/powerapps-docs#3454]
Was just hoping there could be more clarity on how Tests are stored? Do they travel with apps in solutions in different environments? Followed instructions on the next page for adding a table for test results but would like more detail on best practices managing and handling Test Studio content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb6392fe-8157-6760-00e7-b9ca3dc3b51d
* Version Independent ID: a2eb8009-1c13-1eb6-b716-f5afea70de60
* Content: [Test Studio - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/test-studio)
* Content Source: [powerapps-docs/maker/canvas-apps/test-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/test-studio.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @maustinjones
* Microsoft Alias: **austinj**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @virakones. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Tests are published and stored in the app package, as documented in [Working with Test Studio](https://docs.microsoft.com/power-apps/maker/canvas-apps/working-with-test-studio) topic.

For best practices and known issues, please see the relevant sections on the [Overview](https://docs.microsoft.com/power-apps/maker/canvas-apps/test-studio) topic.

**Comment by virakones** [comment]
hi @tapanm-MSFT 

_>Tests are published and stored in the app package_

Unfortunately, those pages linked do not have this documented. I have read through but does not contain any detail on how to work with test studio with solutions and how solution layers are affected. Please permalink the section that describes this, if I am incorrect. 

It is not clearly documented that saving test suites, test cases one must open the app and edit, therefore one cannot run test studio on a managed solution without creating an unmanaged layer. If that unmanaged layer is removed, it looks like the test cases are as well and so it seems that the Test Studio is best suited only for an unmanaged solution. Though again, this is not entirely clear in the official documentation.
