### ISSUE TITLE
Phan hoi

### ISSUE THREAD

**Issue by duclong09** [MicrosoftDocs/powerapps-docs#3456]
[Nhập phản hồi vào đây]
It's really good, it's really a great experience, I'm practicing with it.

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: a5a87d70-1f25-0a75-bc11-f2c079f2083c
* Version Independent ID: 7b1e729a-d4b6-2786-2ac7-c9e1c516a815
* Content: [Power Apps là gì? - Power Apps](https://docs.microsoft.com/vi-vn/power-apps/powerapps-overview)
* Content Source: [powerapps-docs/powerapps-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/powerapps-overview.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @duclong09. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback!
