### ISSUE TITLE
Near-real-time data tables are not queryable

### ISSUE THREAD

**Issue by acieslik** [MicrosoftDocs/powerapps-docs#3458]
I am referring to this topic in this article:
Access near real-time data and read-only snapshot data (preview)

I setup everything according to your documentation but I figured out that the "Near-real-time" data tables are always not queryable and would get this error:
External table 'dataverse_test_org123456.dbo.msdyn_workorder' is not accessible because content of directory cannot be listed.

The same table with "_partitioned" postfix is working fine and will return all synced records.
So is the "Near-real-time" data table feature still buggy and not working or what's the cause?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a924e8-1757-5b5a-ad6d-930e316c3196
* Version Independent ID: 6fac1727-bb8a-f993-e480-d9bcfc8ef9f7
* Content: [Create an Azure Synapse Link for Dataverse with your Azure Synapse Workspace - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-synapse)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-synapse.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-synapse.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by JasonHQX** [comment]
Hi @acieslik , thanks for pointing this out. you are right and the doc is pending to update.  Near real-time data view is not supported when the view incremental folder feature is enabled. To view real-time data use snapshot data instead. More information: [Access near real-time data and read-only snapshot data](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-synapse.md#access-near-real-time-data-and-read-only-snapshot-data-preview)

**Comment by JasonHQX** [comment]
@Mattp123, can you help close this issue? The doc was updated 3 months ago.

**Comment by Mattp123** [comment]
Closing issue.
