### ISSUE TITLE
Early Bound vs Late Bound - Confusing comparison table entries

### ISSUE THREAD

**Issue by MarkS2145** [MicrosoftDocs/powerapps-docs#3460]
[Enter feedback here]
In "Choose which style" section the last two rows in the comparison table of early bound and late bound do NOT make sense, in English.

Early Bound => "Less, more readable code" - What does this mean? 
Late Bound => "More, less readable code" - What does this mean?

Early & Late Bound => "Very slightly less performant" - Again, what does this mean in English?

</body>
</html>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34293a5-c3f1-d493-e6ee-88f320300869
* Version Independent ID: 7409d221-3c71-df9f-6dec-5980872d5005
* Content: [Late-bound and early-bound programming using the Organization service (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/org-service/early-bound-programming)
* Content Source: [powerapps-docs/developer/data-platform/org-service/early-bound-programming.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/early-bound-programming.md)
* Service: **powerapps**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MarkS2145. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@phecke Can you review this one please?

**Comment by phecke** [comment]
@MarkS2145 Good question. It means:
Using early-bound, there is in general less code to write, and the code is more readable (understandable)

Using late-bound, there is more code to write, and the code is less readable (harder to understand)

Mixing early & late-bound coding in the same app may result in very slightly less app performance.

**Comment by KumarVivek** [comment]
@MarkS2145 Updated the table to the following:

<html>
<body>


Early-bound | Late-bound
-- | --
You can verify entity, attribute, and relationship names at compile time | No compile time verification of entity, attribute, and relationship names
You must generate entity classes | You don't need to generate entity classes
Better IntelliSense support | Less IntelliSense support
Less code to write; code is more readable | More code to write; code is less readable
Very slightly less performant | Very slightly more performant


</body>
</html>

Closing the issue.
