### ISSUE TITLE
How to add a new custom font

### ISSUE THREAD

**Issue by bromero26** [MicrosoftDocs/powerapps-docs#3461]
Hi, The content on the site is well written. However, I need to add a new font to the list of available fonts. For example Roboto. How can I do it??

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ecdffd-f6c2-4fc2-2d74-94d16c18108c
* Version Independent ID: cb939451-df9d-23b2-5e98-e2519c3b90db
* Content: [Use the rich text editor control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/rich-text-editor-control#rich-text-editor-properties)
* Content Source: [powerapps-docs/maker/model-driven-apps/rich-text-editor-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/rich-text-editor-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **craigm**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bromero26. This issue has been assigned to the doc author for review.
