### ISSUE TITLE
Can't add chart, UI has changed too much

### ISSUE THREAD

**Issue by softchris** [MicrosoftDocs/powerapps-docs#3463]
So this page needs to be updated. The menu options aren't the same.

To import data, you go to 

Action / Collect / Choose "collection1" or "New collection", in the second item in the droplist, choose data source
Go to View/Collections to preview it

And don't ask me how to do the rest, cause I can't follow the existing Docs page from here, so yea rewrite of this page is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a73f0a1d-d46b-acad-da96-88d295aa2163
* Version Independent ID: 6b87f264-812d-618c-6e5c-e020d0d3010a
* Content: [Show data in a line, pie, or bar chart in canvas apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/use-line-pie-bar-chart)
* Content Source: [powerapps-docs/maker/canvas-apps/use-line-pie-bar-chart.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/use-line-pie-bar-chart.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @softchris. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@leestott  @leestott - Apologize for the very slow response. I've added this topic to my to-do list. Since this topic is very old I'm working with our internal PM team to get the latest information. 

Thanks,
Mints

**Comment by mduelae** [comment]
The topic has been update. Thank you for your feedback.

Thanks,
Mints
