### ISSUE TITLE
Vagueness around rollup field paragraph

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/powerapps-docs#3464]
I find this paragraph below vague. What does this mean? If a rollup field is not updated for 2 months, does this mean that it won't be updated for 10 years, if the next update happens after 3 months?

> Notice that, when the situation occurs where the rollup column is never updated, the Mass Calculate Rollup Field job won’t run again for that column until after 10 years have passed. This behavior is by design. When there aren’t any updates in the underlying columns associated with the rollup field, there isn’t any reason to run the job more frequently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7aaa057-dbfa-e5b0-2222-5f59299c4960
* Version Independent ID: c88e45f0-47ec-ab48-66c0-1a13b0aa2ad5
* Content: [Define rollup columns with Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/define-rollup-fields)
* Content Source: [powerapps-docs/maker/data-platform/define-rollup-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/define-rollup-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rajyraman. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@rajyraman - No, the Mass Calculate Rollup Field job _will run 12 hours after the change_ whether you make an update to the column today, tomorrow, two months or three months from now. As the article states, when a change occurs the Mass Calculate Rollup Field job runs within 12 hours. If no change occurs, the Mass Calculate Rollup Field job won't run until about 10 years have passed. 

Closing issue.
