### ISSUE TITLE
Wrong step on "Enable Async OnSave using app setting" section

### ISSUE THREAD

**Issue by theobaidur** [MicrosoftDocs/powerapps-docs#3465]
On this [page](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/form-onsave), at [_**"Enable Async OnSave using app setting"**_](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/form-onsave#enable-async-onsave-using-app-setting) section where it says **_"Select the app and then select ... (ellipses). Select Open in preview."_** But, there is no option called **_"Open in preview"_**. This option probably has been replaced with [**_"Edit"_**](https://www.screencast.com/t/kaehyIDphE) option that does the same i.e. open the app in the preview where the settings button can be found. 

The documentation needs to be updated to reflect the change. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c3168e3-774b-aad1-0cd2-d7e6eb487088
* Version Independent ID: 2fb2edc5-b09d-bfaa-0644-675d29e00598
* Content: [Form OnSave event (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/form-onsave)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @theobaidur. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Fixed with [#6583](https://github.com/MicrosoftDocs/powerapps-docs-pr/pull/6583)
