### ISSUE TITLE
staticLocalizationsNewMessages- Where is this coming from?

### ISSUE THREAD

**Issue by anantharamakrishnans** [MicrosoftDocs/powerapps-docs#3467]
[Enter feedback here]
The reference of staticLocalizationsNewMessages is not clear as where this is coming from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40e1d02-821c-372a-6470-4850b5d04417
* Version Independent ID: b7bd4543-5eba-c2b8-944e-be285f4455dc
* Content: [Localize sample apps (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/localizing-sample-apps)
* Content Source: [powerapps-docs/teams/localizing-sample-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/localizing-sample-apps.md)
* Service: **powerapps**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **saperlmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @anantharamakrishnans. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please use the latest version of the app templates, and if the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
