### ISSUE TITLE
unable to access settings

### ISSUE THREAD

**Issue by IsaacPrenticeTePari** [MicrosoftDocs/powerapps-docs#3473]
Power apps studio does not exist as an app, now built into make.powerapps.com but in make.powerapps.com I do not see anywhere to change these settings. 

"Select Settings in Power Apps Studio."

but this page was updated earlier in the month? and I do not understand how to set this up.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dcec321-a287-a483-241d-69b147737f23
* Version Independent ID: 1dcec321-a287-a483-241d-69b147737f23
* Content: [Co-authoring in canvas apps (experimental) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/git-version-control)
* Content Source: [powerapps-docs/maker/canvas-apps/git-version-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/git-version-control.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @IsaacPrenticeTePari. This issue has been assigned to the doc author for review.
