### ISSUE TITLE
Tables exposed by new feature should clarify it's the _partitioned ones, not normal tables

### ISSUE THREAD

**Issue by midomsft** [MicrosoftDocs/powerapps-docs#3476]
The new incremental updates feature in preview refers to this link - https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-incremental for guidance on how to consume the new tables. However that link refers to querying the normal tables ([CONTAINER_NAME].[dbo].[TABLE_NAME]) wherein reality it should [CONTAINER_NAME].[dbo].[TABLE_NAME_Partitioned] as the other table won't work (as the underlying data doesn't exist).

Can the doc be clarified to show this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb9c8f3-c785-1dec-26a0-380e11df5fd0
* Version Independent ID: 7cb9c8f3-c785-1dec-26a0-380e11df5fd0
* Content: [Query and analyze the incremental updates - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-incremental-updates)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-incremental-updates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-incremental-updates.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @JasonHQX
* Microsoft Alias: **jasonhuang**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @midomsft. This issue has been assigned to the doc author for review.

**Comment by JasonHQX** [comment]
Duplicate issue: 
![image](https://user-images.githubusercontent.com/102614732/197256614-bd53b7e6-f76d-44df-9b0b-f8dc28698572.png)
The doc has been updated

**Comment by Mattp123** [comment]
Closing issue.
