### ISSUE TITLE
Customised Sample PowerApp - Publish to multiple teams dataverse environments as managed

### ISSUE THREAD

**Issue by ToddOmya** [MicrosoftDocs/powerapps-docs#3478]
Hi,

https://docs.microsoft.com/en-us/power-apps/teams/customize-sample-apps

This page doesn't have any information regarding publishing a customized sample PowerApp to different Teams environments. It shows how to publish to the teams dataverse environment it currently resides in but not in any other team dataverse environments.

I am trying to find out how to publish my customised sample app inspection to multiple different teams specifically in the different teams dataverse environments not just as a broad distribution app. How is this done in a way that I can manage updates to the app without having to update each individual instance of the app in each team dataverse environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c066188f-f448-6b76-9f32-fdaf9a0bf913
* Version Independent ID: 6340befa-433c-1beb-fbe1-ad2acd00d52d
* Content: [Customize sample apps installed from teams store - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/customize-sample-apps)
* Content Source: [powerapps-docs/teams/customize-sample-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/customize-sample-apps.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @msftsamperl
* Microsoft Alias: **saperlmu**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. If the app is already published to a Teams channel as a tab, you'll have the option to Show tabs.
To publish updated version of an app to an existing active tab, select Save + close without adding a new tab.
See [Publish and add an app to Teams](https://learn.microsoft.com/power-apps/teams/publish-and-share-apps)
