### ISSUE TITLE
Validate function does not exist and has to be created manually

### ISSUE THREAD

**Issue by KoenJanssensPD** [MicrosoftDocs/powerapps-docs#3480]
It seems the "webFormClientValidate" function does not exist. See this post : https://powerusers.microsoft.com/t5/Power-Apps-Portals/webform-javascript-validation/td-p/694546
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd59aca-5cd6-54bf-d119-f49b6e0098aa
* Version Independent ID: 95689207-a0b9-8336-595c-8a00f6906dee
* Content: [Add custom JavaScript to a form - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/configure/add-custom-javascript)
* Content Source: [powerapps-docs/maker/portals/configure/add-custom-javascript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/add-custom-javascript.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KoenJanssensPD. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for the feedback. We have updated the sample code to resolve the issues.
