### ISSUE TITLE
Where do we find the app://<guid>??

### ISSUE THREAD

**Issue by RamblingGeekUK** [MicrosoftDocs/powerapps-docs#3484]
[Enter feedback here]

So the documentation linked in the comments in the example code

``` // Azure Active Directory app registration shared by all Power App samples.
            // For your custom apps, you will need to register them with Azure AD yourself.
            // See https://docs.microsoft.com/powerapps/developer/data-platform/walkthrough-register-app-azure-active-directory
            var clientId = "<guid>";
            var redirectUri = "app://<guid>";   <<<< ---- Where do we get this from, it's never explained, in the link above.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e6ca03-5e73-39aa-c2f0-2df8aa19cad9
* Version Independent ID: 4e6eb61b-e550-a1cb-6862-2ba4e9e07702
* Content: [Quick Start: Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/quick-start-console-app-csharp?tabs=adal)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by RamblingGeekUK** [comment]
We found this! :-) 

In the app registration, click authentication, click the "+ Add a platform" then click Mobile, and desktop applications.

**Comment by RamblingGeekUK** [comment]
Please update the docs to explain this, it's very confusing when you don't know how.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RamblingGeekUK. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@RamblingGeekUK You should read the referred to documentation about Azure AD app registration. The clientId and redirectUri are taken from that registration.

https://docs.microsoft.com/powerapps/developer/data-platform/walkthrough-register-app-azure-active-directory

**Comment by RamblingGeekUK** [comment]
@phecke Thanks for the reply.  I did read the doc and the link you provided, however I feel they are misleading/confusing as the example code has app:<guid> the document has 
![image](https://user-images.githubusercontent.com/7108949/178104623-5252ac0d-71fd-428c-94df-ce6e23b40671.png)

Which isn't in the same format.  That article should explain that you need to click on app registration > Authentication > "+ Add Platform" > Mobile and Desktop applications, which mentions Console, even then it's not clean you can enter "app://<guid>" and nowhere explains that you generate your own or at least that's my understanding as it's never explained from what I have read and seen. 

I found this confusing and frustrating, maybe it does exisit and I missed it, however the documentation imho shouldn't leave yu wondering or confused.  

Thanks for your time.
