### ISSUE TITLE
Connect using the application secret Example is outdated

### ISSUE THREAD

**Issue by RamblingGeekUK** [MicrosoftDocs/powerapps-docs#3485]
[Enter feedback here]

This this code is outdated and no longer works with current versions MSAL

```string serviceUrl = "https://yourorg.crm.dynamics.com";
string clientId = "<your app id>";
string secret = "<your app secret>";

AuthenticationContext authContext = new AuthenticationContext("https://login.microsoftonline.com/<Tenant-ID-here>");
ClientCredential credential = new ClientCredential(clientId, secret);

AuthenticationResult result = authContext.AcquireToken(serviceUrl, credential);

string accessToken = result.AccessToken;```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f57df6-59af-6e22-44d2-bc9bb1ee69c7
* Version Independent ID: fdce23ee-733d-bf3a-25c8-2ca6bfa8c852
* Content: [Use OAuth authentication with Microsoft Dataverse (Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/authenticate-oauth#connect-as-an-app)
* Content Source: [powerapps-docs/developer/data-platform/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/authenticate-oauth.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RamblingGeekUK. This issue has been assigned to the doc author for review.

**Comment by paulliew** [comment]
@peter, please work with Ritesh Pandey (IDC) who is the AuthN PM to validate and correct this comment

**Comment by paulliew** [comment]
+ @Ritesh ***@***.***>/+ @Peter ***@***.***>

@peter<https://github.com/peter>, please work with Ritesh Pandey (IDC) who is the AuthN PM to validate and correct this comment

**Comment by ritesh** [comment]
Think you have the wrong ritesh :)

**Comment by phecke** [comment]
@RamblingGeekUK Most of our complete code samples use a connection string with CrmServiceClient for authentication. There are some code snippets in the docs that still show Azure ADAL code for auth. We will eventually update all our sample snippets to use MSAL or the Dataverse SDK ServiceClient class with a connection string. ADAL is still available through the end of the year. 

You should be using MSAL or ServiceClient for authentication. Here are some samples that demonstrate that:
https://github.com/Microsoft/PowerApps-Samples/tree/master/cds/webapi/%23/QuickStart
https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/%23-NETCore/ServiceClient
