### ISSUE TITLE
what is GUID in Row ID?

### ISSUE THREAD

**Issue by yanyishi** [MicrosoftDocs/powerapps-docs#3487]
[When I Test flow, it required GUID of Row ID, what is that and how can I get that ID?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd679d9-f54f-257b-5c82-a2faa263d067
* Version Independent ID: 9c3a9adc-44c1-c1d5-13f6-a97914e8ba69
* Content: [Replace notification with adaptive card (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/replace-notification-with-adaptive-card)
* Content Source: [powerapps-docs/teams/replace-notification-with-adaptive-card.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/replace-notification-with-adaptive-card.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **saperlmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @yanyishi. This issue has been assigned to the doc author for review.

**Comment by nivloe** [comment]
Am having the same issue when trying to test the adaptive card flow, I'm getting asked  for the row's GUID and the initial value for Card Title and Campaign Value.

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please use the latest version of the app templates, and if the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
