### ISSUE TITLE
Dataverse Web API - x-ms-client-session-id / Session Tracking Id

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#3488]
It'd be great if a mention of `x-ms-client-session-id` AKA [SessionTrackingId](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/0eb8c326bc8e28a6449fd0708574a30353a2cd10/src/GeneralTools/DataverseClient/Client/ServiceClient.cs#L527) could be added here. 

It'd be incredible if a cross-reference to [Telemetry events for Microsoft Dataverse#Dataverse API incoming calls](https://docs.microsoft.com/en-us/power-platform/admin/telemetry-events-dataverse#dataverse-api-incoming-calls) snuck in too ;).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c228177-ace4-9ffc-d8db-1251cc98d228
* Version Independent ID: 864e7cde-7176-241c-992d-9e421bf4d6d3
* Content: [Compose HTTP requests and handle errors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/compose-http-requests-handle-errors#http-headers)
* Content Source: [powerapps-docs/developer/data-platform/webapi/compose-http-requests-handle-errors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/compose-http-requests-handle-errors.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by JimDaly** [comment]
@fowl2 
I got information from the dev team about this.
It looks like the value set in the `x-ms-client-session-id` is the same sent by these properties:

 - [ServiceClient.SessionTrackingId Property (Microsoft.PowerPlatform.Dataverse.Client) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/microsoft.powerplatform.dataverse.client.serviceclient.sessiontrackingid?view=dataverse-sdk-latest#microsoft-powerplatform-dataverse-client-serviceclient-sessiontrackingid)
- [CrmServiceClient.SessionTrackingId Property (Microsoft.Xrm.Tooling.Connector) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.sessiontrackingid?view=dataverse-sdk-latest#microsoft-xrm-tooling-connector-crmserviceclient-sessiontrackingid)

This data should appear within the **session_Id** value of the exported telemetry data that is documented here: [Overview of integration with Application Insights > Common fields](https://learn.microsoft.com/en-us/power-platform/admin/overview-integration-application-insights#common-fields)

I've created a workitem to add these details to the docs, so closing this.
3106327
