### ISSUE TITLE
Include view in app - but hide it in the view selector

### ISSUE THREAD

**Issue by Niels-SL** [MicrosoftDocs/powerapps-docs#3491]
Is there any way to include a view in an app but hide the view in the view selector? 

**Use case:** 
Views that are only accessed from dashboards (from charts and grids) and sub-grids using the 'See all records' and 'View records' functionalities are cluttering the view selector. These views will never be accessed from the view selector, so it would make sense to hide them and declutter the view selector. 

![image](https://user-images.githubusercontent.com/46558783/177545568-ca0cb01e-633a-4d72-9a1e-74ef316727b3.png)
![image](https://user-images.githubusercontent.com/46558783/177546030-cec784fb-0888-4fc5-87f4-afb9c100253d.png)

I have tried:
1. Removing the view from the app: If the user clicks 'See all records' and 'View records' the default view will open.
2. Deactivate/turn off the view: An error message will appear saying that the view is not available.
3. Hide the view using the new ability for users to hide system views: same result as number 1. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee6dacf-35df-fb20-249f-a9fd537a3ee4
* Version Independent ID: eee6dacf-35df-fb20-249f-a9fd537a3ee4
* Content: [Create, add and remove forms, views, or charts in a model-driven app using the app designer - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/create-add-remove-forms-views-dashboards)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-add-remove-forms-views-dashboards.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/create-add-remove-forms-views-dashboards.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **emcoope**

**Comment by Mattp123** [comment]
@Niels-SL - Believe what you are asking for is a feature change. For product-related feedback, visit [Power Apps community ideas](https://ideas.powerapps.com). 
Closing this issue.
