### ISSUE TITLE
Viewing row level permissions in Dataverse

### ISSUE THREAD

**Issue by colesn** [MicrosoftDocs/powerapps-docs#3492]
With the updates to Dataverse, the check access option is no longer visible. Could you advise how to access it now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de11005e-a133-9ad8-52c8-5fcfc8cd1dd0
* Version Independent ID: ab774e6b-fbe3-123a-7e08-9721deca8c21
* Content: [Check your user access and permissions - Power Apps](https://docs.microsoft.com/en-us/power-apps/user/access-checker)
* Content Source: [powerapps-docs/user/access-checker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/access-checker.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @colesn. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/

Closing this issue.
