### ISSUE TITLE
Organization service assemblies

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3497]
The documentation references the nuget package Microsoft.CrmSdk.CoreAssemblies. We use this for plugins and our own external tools.
What about the package Microsoft.PowerPlatform.Dataverse.Client? It doesn't seem to be a replacement for the other package regarding plugins. But could this be used for external tools? This would mean we could get rid of the old .NET Framework 4.6.2 and move on to .NET 6.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cec6222-fd2e-a7f5-6bb1-86a2deefb5b4
* Version Independent ID: 8ef3b618-c9e0-b0a5-8b83-cbffccbba70b
* Content: [Use the Microsoft Dataverse Organization Service (Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/org-service/overview)
* Content Source: [powerapps-docs/developer/data-platform/org-service/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@darshSWL Plug-ins are only supported with a .NET Framework 4.6.2 build target. You can use Microsoft.PowerPlatform.Dataverse.Client instead of Microsoft.CrmSdk.CoreAssemblies. Microsoft.PowerPlatform.Dataverse.Client is newer and includes build targets for .NET Framework 4.6.2 and .NET Core (.NET 6).
