### ISSUE TITLE
Dicrepancies in data model picture eand ensuing text

### ISSUE THREAD

**Issue by mslavoie** [MicrosoftDocs/powerapps-docs#3498]
There are some discrepancies between the current solution (as of 2022-07-09) data tables and the diagrams in the web page. The rest of the page should be updated accordingly.  For instance the first diagram as a reference to the Inscpection app (this is minor) and the ERD has tables that are not in the current data model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85d7e47-b42e-5216-079f-58e4c11ae55d
* Version Independent ID: c7cb9444-9541-7166-5612-33e7497bfccb
* Content: [Understand Issue Reporting sample app architecture - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/issue-reporting-architecture)
* Content Source: [powerapps-docs/teams/issue-reporting-architecture.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/issue-reporting-architecture.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **saperlmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mslavoie. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please use the latest version of the app templates, and if the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
