### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DannyK91** [MicrosoftDocs/powerapps-docs#3499]
[Enter feedback here]

Hi, I've tried editing the Employee Idea app via the Power App but the following error occurs...

microsoftteams.postmessagetochannelv3 failed: the method 'postmessagetochannelv3' has invalid value for parameter 'groupid'

Could anyone help me out?

![Screenshot 2022-07-11 142045](https://user-images.githubusercontent.com/109048131/178189551-8ac4be3c-b63c-42c7-a88b-91932d8de328.png)

![Screenshot 2022-07-11 141458](https://user-images.githubusercontent.com/109048131/178189565-e21e919c-bf9f-4a6d-a5b4-459a7d056d17.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ad672d-aff1-cde7-079f-54b81b00e013
* Version Independent ID: a6965ad7-43ad-6c6b-916b-6481640660d8
* Content: [Enable users to discuss ideas (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/extend-ideas-discussions)
* Content Source: [powerapps-docs/teams/extend-ideas-discussions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/extend-ideas-discussions.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **saperlmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DannyK91. This issue has been assigned to the doc author for review.

**Comment by DannyK91** [comment]
any update on this issue?

**Comment by Dav75ky** [comment]
I'm curious about updates on this, as well.  I have a similar issue with the Inspection app.  After following the customization guide https://learn.microsoft.com/en-us/power-apps/teams/notify-manager-inspections the Manage Inspection app breaks after modifying the canvas app for the "responsible user" fields with the invalid parameter for groupID error.

**Comment by tapanm-MSFT** [comment]
The sample app templates for Power Apps in Teams are now available in the [Power Apps Teams Sample App Templates repository](https://github.com/microsoft/teams-powerapps-app-templates). Please use the latest version of the app templates, and if the problem persists, [create a new issue](https://github.com/microsoft/teams-powerapps-app-templates/issues).
