### ISSUE TITLE
App Designer doesn’t refresh entity metadata on save and close of new entity create

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#350]
Hi Team,

Unable to create, then add new Entity using Model Driven App Designer.

 Steps to repro:

1. Create new Model Driven App
2. From App Designer Create New Entity
3. Add the Entity information in the new entity create form, then Save & Close
4. Search for new Entity. It does not Appear in the New App Designer, but does appear in the list of all Entities from System Customization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf4cad7-a8cd-c1cc-1122-3db6c858b307
* Version Independent ID: 64f2be57-f3c7-595b-b3d7-63621fe4ad81
* Content: [Build your first model-driven app from scratch with PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/build-first-model-driven-app)
* Content Source: [powerapps-docs/maker/model-driven-apps/build-first-model-driven-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/build-first-model-driven-app.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@gregdegruy - if this is still an issue please contact Support. More information: https://powerapps.microsoft.com/support/ 

Closing this issue.
