### ISSUE TITLE
Dataverse Synapse Link - ALM - unable to configure the destination storage account

### ISSUE THREAD

**Issue by pieterh** [MicrosoftDocs/powerapps-docs#3503]
In the ALM section it is mentioned you can move configuration between environments (from dev, to test, to acc to prd). What I have seen for our customers, they have created an synapse workspace, storage account etc for each step in the DTAP. Sop each dataverse environment has a corresponding environment within Azure. As a result I should be possible to deploy the configuration in the next environment and configure what datalake will be used as a target. At this moment this is not possible and you can only deploy the link to the same storage account. It is nice that it will be in a different datalake, but this is not enough segregation. 
It would be best to mention this in the features/ limitations. Otherwise you have to install a perform all steps until you find out it will not work for your specific scenario.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eaf46c4-e66c-96c6-e780-42ed464a6db3
* Version Independent ID: 5eaf46c4-e66c-96c6-e780-42ed464a6db3
* Content: [Transport Azure Synapse Link for Dataverse configuration - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-solution)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-solution.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-solution.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by JasonHQX** [comment]
Hi [pieterh](https://github.com/pieterh), you are right. ALM approach only applies to Dataverse setting and brings no impact on Azure side. I will update the doc accordingly

**Comment by melody-universe** [comment]
Hoping the product group can improved this functionality. In the meantime, my team has created a CLI tool that you can install in your pipelines / workflows to configure environment-level settings prior to importing a solution:

https://github.com/oops-i-git-it-again/dsyn-cli

**Comment by JasonHQX** [comment]
We are planning to do ALM enhancement around Apr 23 to allow user update Azure side configuration before importing solution. Thanks

**Comment by Mattp123** [comment]
Closing issue.
