### ISSUE TITLE
This whole section needs to specify when to use LogicalCollectionName and LogicalName

### ISSUE THREAD

**Issue by jsh121988** [MicrosoftDocs/powerapps-docs#3504]
Throughout this section of docs there are references to 'Table Name'. These references need to be more specific to either LogicalCollectionName or LogicalName. Without this explicit reference, I was running in circles trying to figure out what I was doing wrong.

I found that any reference to permissions or enabling the WebApi in Site settings, LogicalName is used. However, when actually querying the api, the endpoint uses LogicalCollectionName. It's subtle in the docs, but using the contacts table as an example: 'contact' is used for permissions, and 'contacts' is the webapi endpoint.

**Full Example:**

1. Site Settings:
    1. Webapi/**contact**/enabled
    2. Webapi/**contact**/fields
2. Table permissions uses '**contact**' as the table name.
3. Api endpoint: /_api/**contacts**

**Here is a Powershell script** I wrote to get these names from entities using the Dataverse API:

```Powershell
Connect-AzAccount;
$Org = "MyOrg";
$Resource =  "https://$($Org).crm.dynamics.com/";
$ApiUri =  "https://$($Org).crm.dynamics.com/api/data/v9.0";
$token = Get-AzAccessToken -Resource $Resource;
$headers = @{"Authorization" = "bearer $($token.Token)";};
$EntitiesData = Invoke-RestMethod -Method Get -Headers $headers -Uri "$ApiUri/EntityDefinitions";
$Entities = $EntitiesData.value;
$Entities | Where-Object {$_.LogicalName -like 'contact*'} | Select-Object -Property LogicalName,LogicalCollectionName

```

**Users can also use the UI:**
1. Navigate to the table in Dataverse
2. Dropdown 'Tools'
3. Select
    1. 'Copy Set Name', this is your LogicalCollectionName 
    2. 'Copy Logical Name', this is your LogicalName 

![image](https://user-images.githubusercontent.com/11296487/178570726-ebf1cb79-db23-43b0-9b40-dabb60d87cd8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6bd0a4-3034-2d8b-4b92-2f1404042d27
* Version Independent ID: 4816c6b6-9a69-c0fd-799a-6c7eaa19fb5d
* Content: [Overview of portals Web API - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/web-api-overview)
* Content Source: [powerapps-docs/maker/portals/web-api-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/web-api-overview.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by RedsGT** [comment]
@jsh121988 If you have the DV org already loaded in a browser, https://<org>.crm.dynamics.com/.  You can also use the existing authentication to query WebAPI info: https://<org>.crm.dynamics.com/api/data/v9.0/EntityDefinitions(LogicalName='contact')?$select=LogicalCollectionName,LogicalName

**Comment by jsh121988** [comment]
@RedsGT That's cool, but it doesn't address the documentation issue about when to use which name of an entity.

**Comment by nickdoelman** [comment]
Thank you for your feedback. We have updated the topic to provide this information. https://docs.microsoft.com/en-us/power-apps/maker/portals/web-api-overview#using-entitysetname

**Comment by jsh121988** [comment]
Thanks for adding this. I think there should be a sentence saying that this is for accessing the API endpoint, but you use logical name for permissions and settings

**Comment by nickdoelman** [comment]
Noted, updated. Thank you!
