### ISSUE TITLE
$Expand needs more specific documentation for the related table

### ISSUE THREAD

**Issue by jsh121988** [MicrosoftDocs/powerapps-docs#3507]
This section related to $expand 'Retrieve related table records with a query' need to have a note or something that the destination table uses the Lookup column **SchemaName** on the source table, and the it's **case sensitive**. For some reason, the example provided works even though the proper case is PrimaryContactId. I'm assuming it has something to do with custom tables, but I'm not sure. This may or may not be a bug.

**Doesn't work using Logical Name:**
GET https://redacted.powerappsportals.com/_api/okr_okrintakes?$expand=**okr_krtargetunit**
Error 9004010A: An unexpected error occurred while processing the request

**Works using Schema Name:**
GET https://redacted.powerappsportals.com/_api/okr_okrintakes?$expand=**okr_KRTargetunit**

**Here is a script to output schema name for a lookup field.**

```Powershell
Connect-AzAccount;# | Out-Null;
$Org = "MyOrg";

$Resource =  "https://$($Org).crm.dynamics.com/";
$ApiUri =  "https://$($Org).crm.dynamics.com/api/data/v9.0";
$token = Get-AzAccessToken -Resource $Resource;
$headers = @{"Authorization" = "bearer $($token.Token)";};

$Entities = Invoke-RestMethod -Method Get -Headers $headers -Uri "$ApiUri/EntityDefinitions";
$Entity = $Entities.value | Where-Object {$_.LogicalName -eq 'account'} | Select-Object -First 1
$Fields = Invoke-RestMethod -Method Get -Headers $headers -Uri "$ApiUri/EntityDefinitions(LogicalName='$($Entity.LogicalName)')/Attributes";
$Fields.value | Where-Object {$_.AttributeType -eq "Lookup"} | Select-Object -Property LogicalName, SchemaName;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8c4f16-4467-9735-7c8c-b983cd0d4787
* Version Independent ID: 9a8c4f16-4467-9735-7c8c-b983cd0d4787
* Content: [Portals read operations using the Web API - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/read-operations)
* Content Source: [powerapps-docs/maker/portals/read-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/read-operations.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jsh121988. This issue has been assigned to the doc author for review.

**Comment by jsh121988** [comment]
Actually, I found that in the response there are the below values, and people should use @Microsoft.Dynamics.CRM.associatednavigationproperty to expand a related table.

**Example Response:**
```JSON
"_okr_fiscalyear_value@OData.Community.Display.V1.FormattedValue": "FY23",
"_okr_fiscalyear_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "okr_FiscalYear", <---- USE THIS -----
"_okr_fiscalyear_value@Microsoft.Dynamics.CRM.lookuplogicalname": "okr_iteration",
"_okr_fiscalyear_value": "a204f8fe-fbae-ec11-9840-00224805ffcb",
```

**Comment by jsh121988** [comment]
Another thing I found is that in this section 'Retrieve related tables by expanding collection-valued navigation properties' it needs to be specified that you $expand the relationship name for 1 to many relationships, and it is case sensitive.

This works:
redacted.powerappsportals.com/_api/okr_okrintakes?$expand=**okr_KRCustomTarget_KRName_okr_OKRIntake**

![image](https://user-images.githubusercontent.com/11296487/179265198-06c7b4c0-efbe-4d7f-b403-e33cf3c1352c.png)

**Comment by nickdoelman** [comment]
Thank you for your feedback. We have updated the documentation to include information on determining the [lookup associated navigation property](https://docs.microsoft.com/en-us/power-apps/maker/portals/read-operations#lookup-associated-navigation-property) to better explain what is required for the $expand property.
