### ISSUE TITLE
Manage invalid characters Html encode doesn't work with \v 

### ISSUE THREAD

**Issue by nvigne** [MicrosoftDocs/powerapps-docs#3512]
The documentation mentioned that some characters are invalid and cannot be saved in Dataverse which are verified through the `XmlConvert.VerifyXmlChars` method. It is suggested to use either one of the two methods: Html encode or strip special characters.

The first method Html encode works well with well-known html characters (<, >, &, \' and \"), however it does not cover all the special characters that are not accepted by Dataverse (and XML), including for example the \v (or 0x0B) characters, which isn't encoded by this method.

Is there a technical solution to encode such a character without stripping it completely?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87d112d-621b-5ca9-97f5-f3d959e24a96
* Version Independent ID: 430d8e31-3041-e93a-4315-ffb9bf04874c
* Content: [Manage invalid characters - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/work-with-data/invalidcharactersinfield)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/work-with-data/invalidcharactersinfield.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/best-practices/work-with-data/invalidcharactersinfield.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **pehecke**

**Comment by JimDaly** [comment]
@nvigne 

I take your feedback to be that you feel the content would be complete if it included information about how to manage encoding and not removing the characters beyond the ones which can be HTML encoded.

Your question is:

> Is there a technical solution to encode such a character without stripping it completely?

My question to you is: Why not just remove them? What do you feel that they should be encoded as?
Are any of these characters printable/visible? If not, why keep them?

**Comment by JimDaly** [comment]
@nvigne 
I'm going to close this as I haven't heard back from you.
I think the point is, these characters are not visible, so there is no known reason for preserving them.
If you have some scenario where this is important, please re-open this.

Thanks
