### ISSUE TITLE
create additional portals

### ISSUE THREAD

**Issue by PranjaliShetty** [MicrosoftDocs/powerapps-docs#3519]
upto 50 starter portals can be created for any languages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0f78157-6d85-d438-2dd3-deeded19612b
* Version Independent ID: 9c08bf4d-ca4f-0055-dfcb-042b26efa9cb
* Content: [Create a Dataverse starter portal - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/create-portal)
* Content Source: [powerapps-docs/maker/portals/create-portal.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/create-portal.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PranjaliShetty. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback. The topic has been updated.
