### ISSUE TITLE
Examples of using the Content ID variable $1, $2 etc.

### ISSUE THREAD

**Issue by brendanarnold** [MicrosoftDocs/powerapps-docs#352]
Can we see an example of how we use $1 to reference a URI in an earlier changeset? I have tried a couple of variations trying to guess its usage but so far no luck.

In addition it's probably worth documenting if there is a way to escape '$1' that I may have in my payload so that it does not get expanded into a variable. This is not an issue for me at the moment but is something that would definitely cuase me a lot of headaches if I didn't know about this feature!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af14071e-83a5-8dde-6346-d158b4d5d66a
* Version Independent ID: 8fb0f4fb-17ff-7491-d057-a1edf9242bc8
* Content: [Execute batch operations using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by brendanarnold** [comment]
I am looking btw the include the $1 reference in the payload, not the header, similar to this example in the oData client library https://github.com/simple-odata-client/Simple.OData.Client/wiki/Batch-requests#dynamic-syntax-1

**Comment by AleksandrRogov** [comment]
@brendanarnold , The following worked for me, not sure if you are trying to achieve the same:
```
--batch_2570c4ff-263d-4e75-8487-d74067e41b6e
Content-Type: multipart/mixed;boundary=changeset_4fe6a060-16af-4d77-b7df-2a4a6d0c669c

--changeset_4fe6a060-16af-4d77-b7df-2a4a6d0c669c
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST https://orgname.api.crm3.dynamics.com/api/data/v9.1/salesorders HTTP/1.1
Content-Type: application/json

{"name":"test contact id order"}

--changeset_4fe6a060-16af-4d77-b7df-2a4a6d0c669c
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

POST $1/customerid_contact HTTP/1.1
Content-Type: application/json

{"firstname":"test content","lastname":"id"}

--changeset_4fe6a060-16af-4d77-b7df-2a4a6d0c669c--

--batch_2570c4ff-263d-4e75-8487-d74067e41b6e--
```
I hope this helps.

**Comment by brendanarnold** [comment]
I am trying to use the feature in the payload, not the headers, is this possible? e.g.

`--batch_AAA123
Content-Type: multipart/mixed;boundary=changeset_2394872394 

--changeset_2394872394
Content-Type: application/http
Content-Transfer-Encoding:binary
Content-ID: 1

POST https://myinstance.api.crm4.dynamics.com/api/data/v9.0/contacts HTTP/1.1
Content-Type: application/json;type=entry
Prefer: odata.maxpagesize=500, odata.include-annotations="*", return=representation

{ 
     "firstname": "asd",
     "lastname": "asd"
}

--changeset_2394872394
Content-Type: application/http
Content-Transfer-Encoding:binary
Content-ID: 2

POST https://myinstance.api.crm4.dynamics.com/api/data/v9.0/accounts HTTP/1.1
Content-Type: application/json;type=entry
Prefer: odata.maxpagesize=500, odata.include-annotations="*", return=representation

{
	"name":"SOLE TRADER ORG",
	"emailaddress1":"otbpostman1@post.com",
	"telephone1":"07188888"
}

--changeset_2394872394
Content-Type: application/http
Content-Transfer-Encoding:binary
Content-ID: 3

POST https://myinstance.api.crm4.dynamics.com/api/data/v9.0/connections HTTP/1.1
Content-Type: application/json;type=entry
Prefer: odata.maxpagesize=500, odata.include-annotations="*", return=representation

{
	"record1roleid@odata.bind":"/connectionroles(1EB54AB1-58B7-4D14-BF39-4F3E402616E8)",
	"record2roleid@odata.bind":"/connectionroles(35A23B91-EC62-41EA-B5E5-C59B689FF0B4)",
	"record1id_contact@odata.bind": "$1",
	"record2id_account@odata.bind": "$2"
}

--changeset_2394872394--
--batch_AAA123--
`

**Comment by AleksandrRogov** [comment]
@brendanarnold that's strange. the following worked for me with no problem:
```
--batch_be2c38fe-fb56-4edf-9923-8b5443f8f1c9
Content-Type: multipart/mixed;boundary=changeset_d9099880-8065-46b2-9f35-fa01aa4006b6

--changeset_d9099880-8065-46b2-9f35-fa01aa4006b6
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST https://yourorg.api.crm3.dynamics.com/api/data/v8.2/contacts HTTP/1.1
Content-Type: application/json

{"firstname":"John","lastname":"Doe"}

--changeset_d9099880-8065-46b2-9f35-fa01aa4006b6
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 100001

POST https://yourorg.api.crm3.dynamics.com/api/data/v8.2/salesorders HTTP/1.1
Content-Type: application/json

{"name":"order","customerid_contact@odata.bind":"$1"}

--changeset_d9099880-8065-46b2-9f35-fa01aa4006b6--

--batch_be2c38fe-fb56-4edf-9923-8b5443f8f1c9--
```

**Comment by AleksandrRogov** [comment]
@brendanarnold , I think I have figured it out. The request fails if you add "return=representation" in the header for the two "post" requests. I think it's related to responses such requests return. Those responses do not have `odata-entityid` header.
If you still need to retrieve those records in a single request, you can use `expand` in the last "post" request:

```
--dwa_batch_ae8b244a-a886-4a38-b017-0c2b4fd7772e
Content-Type: multipart/mixed;boundary=changeset_913fb521-fc04-46e0-96db-769d6e317ae0

--changeset_913fb521-fc04-46e0-96db-769d6e317ae0
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST https://yourorg.api.crm3.dynamics.com/api/data/v8.2/contacts HTTP/1.1
Content-Type: application/json

{"firstname":"John","lastname":"Doe"}

--changeset_913fb521-fc04-46e0-96db-769d6e317ae0
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

POST https://yourorg.api.crm3.dynamics.com/api/data/v8.2/quotes HTTP/1.1
Content-Type: application/json

{"name":"test content id"}

--changeset_913fb521-fc04-46e0-96db-769d6e317ae0
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 100001

POST https://yourorg.api.crm3.dynamics.com/api/data/v8.2/salesorders?$expand=customerid_contact,quoteid HTTP/1.1
Content-Type: application/json
Prefer: return=representation,odata.include-annotations="*"

{"name":"1 year membership","customerid_contact@odata.bind":"$1","quoteid@odata.bind":"$2"}

--changeset_913fb521-fc04-46e0-96db-769d6e317ae0--

--dwa_batch_ae8b244a-a886-4a38-b017-0c2b4fd7772e--
```

**Comment by susikka** [comment]
@brendanarnold and @AleksandrRogov I think these will make great examples in our batch operations documentation. We are currently in process of updating the doc to add an example on how to use `$parameter` to reference a URI in a batch operation; the updated doc will be published soon.

**Comment by brendanarnold** [comment]
@AleksandrRogov Yes that's amazing thanks! 

it works if you remove the `return=representation` on all but the final call. Using `$expand` gives the created entities on the final call.

**Comment by susikka** [comment]
@brendanarnold @AleksandrRogov A new section has been added to the doc that provides info on how you can reference URIs using $parameters. Please see: [Reference URIs in an operation](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api#reference-uris-in-an-operation).

If you have any feedback about this newly added documentation, would be glad to hear.

Closing this issue now.
