### ISSUE TITLE
Grammatical error in first note section 

### ISSUE THREAD

**Issue by Jucci16** [MicrosoftDocs/powerapps-docs#3520]
Hello,

In the first Note section of this document there is a missing word. In it's current state it reads as:

 "This is a very simple example to show how to get connected with a minimum of code. The [Enhanced quickstart](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/enhanced-quick-start) will build upon this sample to apply better design patterns."

In the first sentence I believe the author intended to put the word "amount" between "minimum" and "of." This would change the sentence to "This is a very simple example to show how to get connected with a minimum amount of code."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db187af-a897-e8df-f587-4b9763e0bf27
* Version Independent ID: b7446e9a-88eb-f6de-5d11-3f2e0489249a
* Content: [Quickstart: Blazor Server Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/quick-start-blazor-server-app?source=docs)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-blazor-server-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-blazor-server-app.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Jucci16. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@Jucci16 Thanks for the feedback, but I feel the current wording is understandable by most people.
