### ISSUE TITLE
When it will be release?

### ISSUE THREAD

**Issue by HammedAbdulazeez** [MicrosoftDocs/powerapps-docs#3523]
[Enter feedback here]
This is nice function.

When will this be release in the environment as i cant find it yet in the data type of the column

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f7d49a-1fb0-ffba-779d-9c8b6d055d15
* Version Independent ID: d6f7d49a-1fb0-ffba-779d-9c8b6d055d15
* Content: [Work with Dataverse formula columns - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/formula-columns)
* Content Source: [powerapps-docs/maker/data-platform/formula-columns.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/formula-columns.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @matp
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HammedAbdulazeez. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@HammedAbdulazeez - Release information is covered in the release plans for each feature. Formula columns release details are available from the link below. The feature is currently available in preview environments. GA has not been determined.
https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/data-platform/enable-power-fx-formula-columns-inside-dataverse-tables

For information about the preview program for model-driven apps and Dataverse, go to https://docs.microsoft.com/en-us/power-apps/maker/powerapps-preview-program#portals-model-driven-apps-and-app-management.

Closing issue.

**Comment by aledoy** [comment]
> @HammedAbdulazeez - Release information is covered in the release plans for each feature. Formula columns release details are available from the link below. The feature is currently available in preview environments. GA has not been determined. https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/data-platform/enable-power-fx-formula-columns-inside-dataverse-tables
> 
> For information about the preview program for model-driven apps and Dataverse, go to https://docs.microsoft.com/en-us/power-apps/maker/powerapps-preview-program#portals-model-driven-apps-and-app-management.
> 
> Closing issue.

able to create a preview environment but it doesn't allow database to be created, how can we test this column preview if a database cant be created?
