### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by JackWatson-1** [MicrosoftDocs/powerapps-docs#3524]
[Enter feedback here]
When saying how to create a online record the documentation omits what happens when using a custom lookup column. This is causing confusion as it implies that you need to refence the logical name when using odata.bind when in fact you need to use the scheme name. I recommend changing the section: 

To associate new table records to existing table records, set the value of single-valued navigation properties using the @odata.bind annotation. However, for mobile clients in the offline mode, you cannot use the @odata.bind annotation, and instead have to pass a lookup object (logicalname and id) pointing to the target record.

to

To associate new table records to existing table records, set the value of single-valued navigation properties using the @odata.bind annotation. However, for mobile clients in the offline mode, you cannot use the @odata.bind annotation, and instead have to pass a lookup object (logicalname and id or shemename and id for custom lookups) pointing to the target record. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f70840-ac77-de34-b797-233a4ff56d37
* Version Independent ID: e6b3d742-fe79-7442-0cae-d5dcba71f55f
* Content: [createRecord (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/createrecord)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/createRecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/createRecord.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JackWatson-1. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@JackWatson-1 
Thanks for your feedback.

If I'm understanding correctly, it seems that your feedback is specific to use with the offline client API.

You want to change this:

> ... and instead have to pass a lookup object (logicalname and id) pointing to the target record.

To this:

> ... and instead have to pass a lookup object (logicalname and id **or schemename and id for custom lookups**) pointing to the target record.


This example is provided for offline:

```
var data =
    {
        "name": "Sample Account",
        "primarycontactid":
        {
            "logicalname": "contact",
            "id": "465b158c-541c-e511-80d3-3863bb347ba8"
        } 
    }
```

Are you saying that you need to use something like this instead for custom lookups?

```
var data =
    {
        "name": "Sample Account",
        "primarycontactid":
        {
            "schemaname": "Contact",
            "id": "465b158c-541c-e511-80d3-3863bb347ba8"
        } 
    }
```

Perhaps you can provide an example of what you mean? 
I think that might help clarify.

Thanks

**Comment by JackWatson-1** [comment]
Hi Jim

My feedback was for the online client API

As the examples in the documentation shows

var data =
    {
        "name": "Sample Account",
        ***@***.***": "/contacts(465b158c-541c-e511-80d3-3863bb347ba8)"
    }

With the primarycontactid being the logical name, this example works perfectly but if I was to have a custom lookup that looks up to the for-example the opportunity entity and the field is call “My field” with the logical name cr000_myfield and the schema name cr000_MyField

If you were to use the code:

var data =
    {
        "name": "Sample Account",
        ***@***.***: "/ opportunities (465b158c-541c-e511-80d3-3863bb347ba8)"
    }

The function will not work, you must use:

var data =
    {
        "name": "Sample Account",
        ***@***.*** : "/ opportunities (465b158c-541c-e511-80d3-3863bb347ba8)"
    }

So, for custom lookup fields you must use:
var data =
    {
        "name": "Sample Account",
        ***@***.*** : "/ opportunities (465b158c-541c-e511-80d3-3863bb347ba8)"
    }
Instead of:
var data =
    {
        "name": "Sample Account",
        ***@***.***: "/ opportunities (465b158c-541c-e511-80d3-3863bb347ba8)"
    }

Please let me know if you have any further questions or feedback

Many Thanks
Jack Watson / Software Developer
***@***.***

Monpellier
0191 500 8150
Evolve Business Centre, Rainton Bridge South Business Park, Cygnet Way, Houghton-le-Spring, Tyne & Wear, DH4 5QY
www.monpellier.co.uk<http://www.monpellier.co.uk/>

[Email footer 2019]

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Monpellier Ltd. is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company

**Comment by JimDaly** [comment]
@JackWatson-1 
Can I ask that you go to GitHub and enter your comments there rather than responding via email?
Your examples using `@odata.bind` seem to have been obfuscated to prevent including email addresses when you respond via email.

[this link](https://github.com/MicrosoftDocs/powerapps-docs/issues/3524) Should take you directly to the issue.

Thanks,

**Comment by JimDaly** [comment]
I would propose that we update the document with a note calling out something like this:

> The names of single-valued navigation properties is not always the same as the LogicalName for the lookup attribute. You should make sure you are using the name of the `NavigationProperty` element in the Web API $metadata service document. More information: [Web API Navigation Properties](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-navigation-properties)

Do you think this will help?

**Comment by JackWatson-1** [comment]
I think that change would be good to further clarify things

**Comment by JimDaly** [comment]
I've added the note. Closing.
