### ISSUE TITLE
Powerapps Visual- No Data in PowerBIIntergation.Data

### ISSUE THREAD

**Issue by wizardball** [MicrosoftDocs/powerapps-docs#3526]
There are no data available in PowerBIIntergation.Data
Here are my steps:

1. drag a powerapps visual in Power BI

2. put some field in it

3. Navigate to the power app canvas

4.Click "generate gallery" 

5. modify the "item"of gallery as "PowerBIIntegration.Data"

![image](https://user-images.githubusercontent.com/92194779/180910207-64261e04-42b2-488c-a1e9-2646f57e31bc.png)
![image](https://user-images.githubusercontent.com/92194779/180910224-1f83d10c-bfbb-4368-a0a2-1c711b474093.png)
![image](https://user-images.githubusercontent.com/92194779/180910241-b9d6c637-2af1-4896-b6a6-458fd07836ee.png)

**Comment by phecke** [comment]
@wizardball If you have a question or issue with our documentation, please provide a link to the topic in question.

**Comment by phecke** [comment]
@wizardball Closing this issue due to no response. If you have a question or issue about our documentation, please file a new issue.
