### ISSUE TITLE
Please specify How alternate key and duplicate detection work during import

### ISSUE THREAD

**Issue by YoshikaSuzuki** [MicrosoftDocs/powerapps-docs#3527]
The Marketing page clearly states How alternate key and duplicate detection work during import.
https://docs.microsoft.com/en-us/dynamics365/marketing/import-data#how-alternate-key-and-duplicate-detection-work-during-import

This is common not only to Marketing but also to Power Apps, so please specify it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46209bf7-62b7-f424-f749-f297c8847e35
* Version Independent ID: ffef7489-39b8-60dd-299b-367e3b694843
* Content: [Import data in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/user/import-data)
* Content Source: [powerapps-docs/user/import-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/import-data.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @YoshikaSuzuki. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thank you for the feedback. I'm going to verify this with our internal team and will update the topic if needed.

Thanks,
Mints

**Comment by mduelae** [comment]
Hi Yoshika,

Lets work on this internally to verify the information. Closing this for now.
