### ISSUE TITLE
File size limit not honored 

### ISSUE THREAD

**Issue by tianhliu** [MicrosoftDocs/powerapps-docs#3528]
This article says the maximum file size on a file column is 10GB, but I'm getting an error message trying to set it to 500MB.
![image](https://user-images.githubusercontent.com/110071076/181133672-ca806df6-659e-4df0-aada-ebec78d10ec6.png)

This limitation is driving us away from using the file column in our module. Since this is urgent for us, could you confirm whether the max limit has changed on a file column, or we might have hit some glitch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8f3598c-cd0e-2cd8-fa6b-5663f63c36bf
* Version Independent ID: 656dca2a-e65d-fdb9-545e-b73d906ce4f1
* Content: [Column data types in Microsoft Dataverse (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/types-of-fields)
* Content Source: [powerapps-docs/maker/data-platform/types-of-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tianhliu. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@tianhliu - Thank you for bringing this to my attention. I've confirmed that the max file size you can set is 131072 KB (131 MB) and correct in the UI when you attempt to exceed the limit. The article has been updated to reflect the correct maximum.

Closing issue.

**Comment by tianhliu** [comment]
Minor correction: 131072 KB = 128 MB
