### ISSUE TITLE
Specify required organization version

### ISSUE THREAD

**Issue by nicknow** [MicrosoftDocs/powerapps-docs#3530]
In the PluginRegistrationTool it appears to require the organization version to be at least 9.2.22064.00044. This should be listed in the documentation as the option to upload register a package will not be displayed until the organization is updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e36fcc6-5be1-4f03-1201-35a093caf9dd
* Version Independent ID: 7e36fcc6-5be1-4f03-1201-35a093caf9dd
* Content: [Dependent Assembly plug-ins (preview) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins)
* Content Source: [powerapps-docs/developer/data-platform/dependent-assembly-plugins.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dependent-assembly-plugins.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nicknow. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@nicknow 
Thanks for your feedback.
I have a meeting with the dev team tomorrow. I'll confirm with them and get the docs updated.

**Comment by JimDaly** [comment]
@nicknow

The version you mention is currently the required Dataverse version.
The Dataverse updates roll out across regions, and the docs acknowledge this with the line:

> This feature is being gradually rolled out across regions and might not be available yet in your region.

But the version may still change. The decision was to not document the specific version. This should be sorted out within a few days as the Dataverse updates get deployed.

Sorry that this didn't give you a great first impression. Please be patient and try again later.
