### ISSUE TITLE
Unable to share connection for PowerApp

### ISSUE THREAD

**Issue by cagepeh** [MicrosoftDocs/powerapps-docs#3531]
I am able to share the App created in PowerApp, but the connection used by the App is not able to share.

Below is the error msg shown.

> The permission with id '/providers/Microsoft.PowerApps/apis//connections//permissions/' in the put collection requires either the id or the email for the principal.

Any ways to enable sharing of connection?

Thanks.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b711e6-1d3d-c493-437e-9bbdde8e62aa
* Version Independent ID: f41539e7-988d-b302-72f0-450e5c446811
* Content: [Share resources used by canvas apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/share-app-resources)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app-resources.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/share-app-resources.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cagepeh. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please create a [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to work with support teams for help with this problem investigation and solution.
