### ISSUE TITLE
Nonsense text describing custom processing step types.

### ISSUE THREAD

**Issue by guyrt** [MicrosoftDocs/powerapps-docs#3536]
This text is nonsense:
"When the plug-in type set for this Custom API will the only logic that occurs when this operation executes."

In first row of table in Select a Custom Processing Step Type section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd53494-e9ff-33b0-d857-bcd235233aa5
* Version Independent ID: a362d3d7-3d5c-9222-39e6-dd426f96c4a4
* Content: [Create and use Custom APIs (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/custom-api#select-a-custom-processing-step-type)
* Content Source: [powerapps-docs/developer/data-platform/custom-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/custom-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@guyrt 
Tommy, thanks for your feedback.

Changing this to :

When the plug-in set for this Custom API using [CustomAPI.PluginTypeId](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/customapi.md#BKMK_PluginTypeId) will the only logic that occurs when this operation executes.

Does this help clarify?

**Comment by JimDaly** [comment]
@guyrt
I'm going to close this. I hope the change makes this clearer.
