### ISSUE TITLE
Code check - Believe some of it is incorrect in document

### ISSUE THREAD

**Issue by CynCity561** [MicrosoftDocs/powerapps-docs#3537]
I believe this line of code on the page is incorrect:

Group #1: {{ group1 | join: ', ' }}
Group #2: {{ group2 | join: ', ' }}
Group #1 + Group #2: {{ group1 | concat: group2 | join: ', ' }}
**Group #1 + Leslie: {{ group1 | concat: 'Leslie' | join: ', ' }}** (incorrect use)

Concat is used to join 2 arrays together. However, it appears this is a line of text 'Leslie' vs an array. The output would not be  what the document states:

Group #1: John, Pete, Hannah
Group #2: Joan, Bill
Group #1 + Group #2: John, Pete, Hannah, Joan, Bill
**Group #1 + Leslie: John, Pete, Hannah, Leslie**  (incorrect)

Output would actually be: 
Group #1 + Leslie: John, Pete, Hannah, L, e, s, l, i, e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f21735f3-2a17-cfdc-71e7-f920fbf6749d
* Version Independent ID: c2fa90c4-0815-6617-358e-915dd3b76e24
* Content: [Available Liquid filters - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/liquid/liquid-filters)
* Content Source: [powerapps-docs/maker/portals/liquid/liquid-filters.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/liquid/liquid-filters.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CynCity561. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback. We have confirmed the issue and removed the line from the sample code to remove confusion.
