### ISSUE TITLE
Alt key use

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#354]
A few times in the article it refers to holding down the Alt key to see control names. I'm a bit confused by this as I thought the Alt key was used in the design tool to interact with the form to test features in situ.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f886011-a79a-8fa9-bb7c-f0adbb61b8d3
* Version Independent ID: 997f29d5-e836-fc31-647e-eb6a916afae4
* Content: [Understand data cards - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-cards#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-cards.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-cards.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
@biterbit, thanks for pointing this out.  We changed the behavior of Alt sometime last year from showing the control names to in situ activation and these docs had not been updated.  They have been updated now.
