### ISSUE TITLE
Missing getEventArgs method of the execution context object for PostSave Event

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#3543]
The table on this page is missing the getEventArgs method of the execution context object for [PostSave Event](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/postsave?WT.mc_id=DX-MVP-5003873).
- getEntityReference
- getIsSaveSuccess
- getSaveErrorInfo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4002c71b-8028-5b57-0452-7f5af46f4643
* Version Independent ID: 84f64a55-e97d-6b86-ccf8-04bc9db5d419
* Content: [getEventArgs (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/executioncontext/geteventargs)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/executioncontext/getEventArgs.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/executioncontext/getEventArgs.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LinnZawWin. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Discussion with dev team

**Comment by JimDaly** [comment]
Updated topic
