### ISSUE TITLE
Confusing code sample

### ISSUE THREAD

**Issue by vlele** [MicrosoftDocs/powerapps-docs#3545]
The following code appears in both code samples (under problematic patterns)
 
//The violation
        this.service = factory.CreateOrganizationService(this.context.UserId);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46aca615-520e-aa4d-22a4-62a7c3c18db8
* Version Independent ID: b812c8cf-a8d4-153d-5e81-c4b83e14d637
* Content: [Develop IPlugin implementations as stateless - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vlele. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@vlele One example sets a plug-in class field member and the other sets the class property. Yes, they are similar with those subtle changes.

**Comment by vlele** [comment]
Sorry to bother you about @phecke  I do have a follow-on question - Is platform caching pointer to instance of the class (that is implementing the IPlugin)? Is that why it is violation to access a field or a property?
