### ISSUE TITLE
Virtual Connector Provider OptionSet mapping

### ISSUE THREAD

**Issue by viacheslav-protsenko** [MicrosoftDocs/powerapps-docs#3547]
Hello. I have a problem with the mapping of option sets. What type of field should be in the SQL so that the Virtual Connector Provider does not issue errors. I tried several types of int and number, the error is always the same:

Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: Cannot access child value on Newtonsoft.Json.Linq.JValue.Detail:
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
<ActivityId>4f4ae041-2ef2-4959-987b-efea371a26fb</ActivityId>
<ErrorCode>-2147220956</ErrorCode>
<ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
<HelpLink>http://go.microsoft.com/fwlink/?LinkID=398563&amp;error=Microsoft.Crm.CrmException%3a80040224&amp;client=platform</HelpLink>
<Message>Cannot access child value on Newtonsoft.Json.Linq.JValue.</Message>
<Timestamp>2022-08-03T11:32:27.7479091Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource>PluginExecution</ExceptionSource>
<InnerFault i:nil="true" />
<OriginalException>PluginExecution</OriginalException>
<TraceText i:nil="true" />
</OrganizationServiceFault>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b64c8d-3c3d-4e4d-afb1-5e0a54c84046
* Version Independent ID: 8180bdbe-ec98-642e-b7ee-1f57954ee502
* Content: [Create virtual tables using virtual connectors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors?tabs=sql)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @viacheslav-protsenko. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@NHelgren Do you have any guidance that could be added to this topic?

From my reading, the entity catalog is generated and should pick up any fields that align to columns in Dataverse. If it is valid, it should be detected and appear in the UI. 

But this is a preview feature and some issues are expected. @viacheslav-protsenko, my recommendation would be to contact technical support.

**Comment by NHelgren** [comment]
@viacheslav-protsenko at this time option sets (both single select and multi-select) are not able to be supported through a virtual table. This is on our list of known issues and we are investigating a fix for this. I do not have a specific date for a solution at this time.

**Comment by phecke** [comment]
Response to the customer provided, closing.
