### ISSUE TITLE
Roles needed for user in pipeline

### ISSUE THREAD

**Issue by larhem** [MicrosoftDocs/powerapps-docs#3549]
I suggest that you have some information about what roles the user you configure in the pipeline variable  needs to execute the tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 513096fe-dce9-70cc-4891-13ffdf2447ca
* Version Independent ID: 29cdb9ce-32e4-2cc5-522b-76587872d8ab
* Content: [Automate tests with Azure Pipelines using classic editor - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/test-studio-classic-pipeline-editor)
* Content Source: [powerapps-docs/maker/canvas-apps/test-studio-classic-pipeline-editor.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/test-studio-classic-pipeline-editor.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @maustinjones
* Microsoft Alias: **austinj**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @larhem. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Ensure this user has the ability to run the app and connect to any data sources the app might connect to. Documentation is updated and the changes will be reflected soon.
