### ISSUE TITLE
Error property

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#355]
Referring to the inheritance of parent properties from the card to the contained controls (next to last table): although I can see card properties for 'Required', 'DisplayName' and 'Default', I cannot see one for 'Error'. Has something changed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f886011-a79a-8fa9-bb7c-f0adbb61b8d3
* Version Independent ID: 997f29d5-e836-fc31-647e-eb6a916afae4
* Content: [Understand data cards - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-cards#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-cards.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-cards.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
@biterbit, you are probably looking at the list of properties available in the drop down at the left end of the formula bar.  These are only properties that can have a formula attached to them - they are input 
and input/output properties.  Parent.Error for a data card is an output only property and cannot be set to a formula so it does not appear in this list.  While editing a formula for a property within the data card, Parent.Error is available.

**Comment by biterbit** [comment]
Thanks for the clarification on the property drop-down list for formula input. What I found confusing was not only that I could not see an Error property in that drop-down list, but also that I could not see it in the right-hand Properties or Advanced tabs either. For the other examples in the list (eg, TextFieldDisplayName.Textbeing inherited from Parent.DisplayName) I could find the parent card property (eg, DisplayName) and thereby the value that would be inherited.

**Comment by gregli-msft** [comment]
@biterbit, we have added a note to the article that Parent.Error is an output only property and therefore won't appear in the formula bar drop down and other locations.  

@AFTOwen, please close this issue.
