### ISSUE TITLE
Menu link is broken - https://docs.microsoft.com/en-us/powerapps-docs/canvas-apps/connections-list

### ISSUE THREAD

**Issue by philipverlinden** [MicrosoftDocs/powerapps-docs#3550]
The link https://docs.microsoft.com/en-us/powerapps-docs/canvas-apps/connections-list below in the menu seems to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee9ae7f-1ef2-5158-40c8-205d019ca50d
* Version Independent ID: fa81251b-6a9a-d444-a212-2c7293d7b7d4
* Content: [Design a custom page for your model-driven app - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/design-page-for-model-app?source=docs)
* Content Source: [powerapps-docs/maker/model-driven-apps/design-page-for-model-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/design-page-for-model-app.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @aorth
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Closing issue.

**Comment by philipverlinden** [comment]
It was in the menu links at the bottom of the page, it was removed or updated in the meanwhile.
