### ISSUE TITLE
Typo or extra word

### ISSUE THREAD

**Issue by steve-parker-by** [MicrosoftDocs/powerapps-docs#3551]
Looks like the "and" is not needed for this sentence from this page ( or something is missing after the and):

**The Get connected sample app for Microsoft Teams provides a simple way to connect _and_ with people in your organization with similar skills.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc9f873e-6664-108b-4183-6e931cd42678
* Version Independent ID: 01593f9a-1ecb-a451-ceff-7f8a094eae27
* Content: [Get connected sample app (preview) - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/get-connected)
* Content Source: [powerapps-docs/teams/get-connected.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/get-connected.md)
* Service: **powerapps**
* GitHub Login: @msftsamperl
* Microsoft Alias: **saperlmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @steve-parker-by. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been fixed, and the changes will be visible soon.
