### ISSUE TITLE
Clarify Table Column Update PUT Operation

### ISSUE THREAD

**Issue by hofmanniac** [MicrosoftDocs/powerapps-docs#3553]
The section on Table Column Updates using the PUT operation could use an example, including that you have to use the Attributes path and ID. It took a while to figure this path out:

PUT [Organization URI]/api/data/v9.0/EntityDefinitions(ENTITY_ID)/Attributes(ATT_ID]

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa97977e-5a9a-fcdf-1610-f6ed6570dd2e
* Version Independent ID: 893c9f21-e784-13aa-28ce-1d2d5e941e47
* Content: [Create and update table definitions using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-update-entity-definitions-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/create-update-entity-definitions-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/create-update-entity-definitions-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hofmanniac. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@hofmanniac 
Thanks for your feedback. 

Agree that this needs to be made clearer, there is only a single section at the bottom of this page that mentions it [Update a column](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-update-entity-definitions-using-web-api#update-a-column). Very easy to miss and as you say, no example.

I added an example to create a boolean column and an example updating it in the **Update a column** section.

It should be published tonight if I meet the 5PM PST deadline.
I hope this helps.
