### ISSUE TITLE
Add Save and Close instruction

### ISSUE THREAD

**Issue by Dlutchy** [MicrosoftDocs/powerapps-docs#3554]
Under section **Defining relationships in virtual tables** After number 8 add instruction to Save and Close Relationship definition.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5490be6b-9f4c-6425-d232-e89e542e40dd
* Version Independent ID: 5490be6b-9f4c-6425-d232-e89e542e40dd
* Content: [Create virtual tables using virtual connectors (preview) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/create-virtual-tables-using-connectors?tabs=sql#setting-up-virtual-table-relationship)
* Content Source: [powerapps-docs/maker/data-platform/create-virtual-tables-using-connectors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-virtual-tables-using-connectors.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Dlutchy. This issue has been assigned to the doc author for review.

**Comment by NHelgren** [comment]
Thank you @Dlutchy   I have added the save and close step, it should be published soon.
