### ISSUE TITLE
UNPIVOT listed as not supported

### ISSUE THREAD

**Issue by cameron-interactive** [MicrosoftDocs/powerapps-docs#3555]
I've been studying this document to figure out what functionality is and isn't supported in the TDS endpoint, UNPIVOT is listed as unsupported, but in reality it works. Would be good to get this document updated with the actual supported functionality so we know what we can use in our migration from DES.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c8687f6-52bf-533a-0b77-cdd99433375b
* Version Independent ID: f9c5f9ca-372a-1b87-6faf-aa354aeda81b
* Content: [How Dataverse SQL Differs from Transact-SQL - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/how-dataverse-sql-differs-from-transact-sql?tabs=supported)
* Content Source: [powerapps-docs/developer/data-platform/how-dataverse-sql-differs-from-transact-sql.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/how-dataverse-sql-differs-from-transact-sql.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cameron-interactive. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@cameron-interactive Checking with the feature PM about new command support.

**Comment by phecke** [comment]
@cameron-interactive Still waiting on PM. He is looking into it.

**Comment by phecke** [comment]
@cameron-interactive PIVOT and UNPIVOT are supported. Will update the doc soon. Thanks for pointing this out :)
