### ISSUE TITLE
Still recommending using DES

### ISSUE THREAD

**Issue by cameron-interactive** [MicrosoftDocs/powerapps-docs#3556]
This document still recommends using DES to export data from the dataverse. This is being decommissioned in November this year, it would be ill advised to use it, and certainly not recommended. This document should be updated to list replacement technologies for exporting to SQL server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf7655c-2fd9-3937-95d7-35d8d1dd4d52
* Version Independent ID: e432c020-de5b-ae94-b42d-e406dd5539ff
* Content: [Importing and exporting data - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/import-export-data)
* Content Source: [powerapps-docs/maker/data-platform/import-export-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/import-export-data.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @mmercuri
* Microsoft Alias: **kvivek**

**Comment by Mattp123** [comment]
@cameron-interactive - Thank you for your feedback. The article has been revised to replace the mention of data export service with Azure Synapse Analytics for Dataverse. The image will be updated shortly to also reflect the current service to use for data export with Dataverse.

Closing issue.
