### ISSUE TITLE
database creations not available to preview environment

### ISSUE THREAD

**Issue by aledoy** [MicrosoftDocs/powerapps-docs#3557]
able to create a preview environment but it doesn't allow database to be created, how can we test powerfx in column preview if a database cant be created?

**Comment by phecke** [comment]
@aledoy  Please provide a link to the related documentation so that we can assign the appropriate writer to answer.

**Comment by aledoy** [comment]
@phecke , sorry about that, this [one](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/formula-columns)

**Comment by Mattp123** [comment]
@aledoy - According to this article: https://learn.microsoft.com/en-us/power-platform/admin/regions-overview#who-can-create-environments-in-these-regions

you can't create a database in the US preview regions. If you want to preview try using the make.preview.powerapps.com URL. 

Closing issue.
