### ISSUE TITLE
Incorrect Example

### ISSUE THREAD

**Issue by anbhar** [MicrosoftDocs/powerapps-docs#3558]
The example for the "The Entity name area" uses "App name" in the below paragraph as an example.

Please update with a proper, valid example for "Entity name". How will customers reading this page find out what to enter in the "Entity Name" field?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d72044c0-7486-402e-4ad0-cd488f6356e0
* Version Independent ID: 3b762213-c234-14b3-7f11-cde507cced78
* Content: [Add an embedded canvas app on a model-driven form - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/embedded-canvas-app-add-classic-designer)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @anbhar. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@anbhar - Thank you for your feedback. The article has been updated to reflect the correct properties for the example and will be published live shortly. 

Closing issue.
