### ISSUE TITLE
Missing Lists: OpenReports, PendingReports, ApprovedReports

### ISSUE THREAD

**Issue by Azurstreams** [MicrosoftDocs/powerapps-docs#356]
I followed the tutorial, and I am using the provided sample.
In the sample App, in the "Collection and Variables" Screen it is written: 
"PendingReports - List of pending expenses and used to count costs of them" 
"ApprovedReports - List of approved expenses and used to count costs of them" 
"OpenReports - List of open expenses and used to count costs of them" 
These are used in the Home Screen of the App "My Expenses" however, your tutorial is missing the creation & integration of these, to enable a fully functioning sample app.

For Example:
If I go (In powerapps) to [My Expenses]>[Expense Summary Group]>[Label Open Value] ---TEXT FIELD ///// **I find the following:**
"$" & If(Sum(Filter(LineItems,ReportID.Id in OpenReports.ID),Cost)>0,Text(Sum(Filter(LineItems,ReportID.Id in OpenReports.ID),Cost),"[$-en-US]#,###.00"),0)
In which OpenReports.ID used twice is not functioning.

**Comment by Azurstreams** [comment]
"29fc7f25-b6b5-26d2-69f3-eada7fff64b3"
For the PowerApp Sample: EXPENSE REPORT
https://github.com/MicrosoftDocs/powerapps-docs/issues?utf8=%E2%9C%93&q=%2229fc7f25-b6b5-26d2-69f3-eada7fff64b3%22&in=body

**Comment by yijw2017** [comment]
We are about to retire this Template app. Will retire this doc accordingly.
Will follow up with time line.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The [expense report sample tutorial](https://docs.microsoft.com/powerapps/maker/canvas-apps/expense-report-install) works as expected with the sample. For any environmental issues, please reach out to the [support teams](https://admin.powerplatform.microsoft.com/support) that can help you investigate the issue and fix.
