### ISSUE TITLE
Missing oData Snippet

### ISSUE THREAD

**Issue by DREWLFE** [MicrosoftDocs/powerapps-docs#3560]
[Enter feedback here]
The last consideration on the page says "following sample ODATA snippet" but there isn't an oData snippet following that item, just a link to give feedback

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94615c16-c84d-0308-171f-d09f3deaaa3b
* Version Independent ID: 94615c16-c84d-0308-171f-d09f3deaaa3b
* Content: [Add canvas apps to solution by default (preview) - Power Apps](https://docs.microsoft.com/en-gb/power-apps/maker/canvas-apps/add-app-solution-default)
* Content Source: [powerapps-docs/maker/canvas-apps/add-app-solution-default.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/add-app-solution-default.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **hasharaf**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DREWLFE. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been updated, and the changes will be reflected soon.
