### ISSUE TITLE
Alternate keys on virtual tables

### ISSUE THREAD

**Issue by SusanneWindfeldPedersen** [MicrosoftDocs/powerapps-docs#3561]
Hello,

Would it make sense to create a note in this topic that alternate keys are not supported on virtual tables? We've gotten the request to add this to our documentation on a product (Business Central) integrating with Dataverse. I think it makes sense to add it here instead of in all integration documentation. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0559ee14-7bd2-07a7-c75b-e7fbca33771b
* Version Independent ID: f7bb342c-1441-5ae7-281a-943c98a68252
* Content: [Work with alternate keys (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/define-alternate-keys-entity)
* Content Source: [powerapps-docs/developer/data-platform/define-alternate-keys-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/define-alternate-keys-entity.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **mayadu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SusanneWindfeldPedersen. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@SusanneWindfeldPedersen  Checking with PM to verify.

**Comment by phecke** [comment]
@SusanneWindfeldPedersen  A topic update will be published later today.
[Work with alternate keys](https://docs.microsoft.com/power-apps/developer/data-platform/define-alternate-keys-entity#:~:text=Alternate%20keys%20are%20not%20supported%20in%20virtual%20tables)

The change is already in the main branch.
