### ISSUE TITLE
Are Ad notes (annotations/attacments) supported?

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/powerapps-docs#3562]
Hello! It looks like adx_ad record attachments such as pictures are not downloaded or uploaded with CLI. At the same time it works with annotations to adx_webfile. Is it a product defect or documentation defect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fffb76-5378-fe8a-62fc-0c82a6d03d6d
* Version Independent ID: 102ff357-ae01-8222-8c14-64e2a5e78a0b
* Content: [Portals support for Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/power-apps-cli)
* Content Source: [powerapps-docs/maker/portals/power-apps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/power-apps-cli.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FixRM. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback. Image file attachments to ad records are not downloaded using the [Power Platform CLI](https://learn.microsoft.com/power-apps/maker/portals/power-apps-cli). As a workaround, use the Image URL field, or by adding an HTML reference in the Copy field to a [web file](https://learn.microsoft.com/web-files.md) record containing an image file. Documentation has been updated.

**Comment by FixRM** [comment]
I know that they don't. Is it a bug?
