### ISSUE TITLE
Question/remark regarding table structure changes

### ISSUE THREAD

**Issue by youritorchalski** [MicrosoftDocs/powerapps-docs#3564]
Hi,

I have questions about the following FAQ topics. Can you enrich the answers based on my questions? In my opinion this essential information is missing from the answers.

1. [What happens when I add a column?](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/export-data-lake-faq#what-happens-when-i-add-a-column)
   - What happens to the CDM related model.json file for the updated entity in Azure Synapse Link for Dataverse?
     - Is the model.json file updated and will the new column always be added at the end of the attribute part of the file even if the column might be added in between columns in the actual source system?
	 - Is the model.json file updated and will the new column be added at the same ordinal position (as it is located in the source system) of the attribute part of the file?
   - **_The questions below assume that the entity related model.json file is updated after each table structure change._**
   - What happens to the exported partitioned files for the updated entity in Azure Synapse Link for Dataverse?
     - Does the table structure change causes the data file for each partition to be updated REGARDLESS if there are any CUD related actions happening on the data that is part of that partition?
     - Does the table structure change causes the data file for each partition to be updated ONLY if there are any CUD related actions happening on the data that is part of that partition?
	   - If this is the case it would create a mismatch between the entity related model.json file and the partitioned files that are not updated.
     - In addition to the above.
       - Does the table structure change causes the creation of a new snapshot file for each partition REGARDLESS if there are any CUD related actions happening on the data that is part of that partition?
       - Does the table structure change causes the creation of a new snapshot file for each partition ONLY if there are any CUD related actions happening on the data that is part of that partition?
	     - If this is the case it would create a mismatch between the entity related model.json file and the partitioned snapshots that are not updated.
     - How are the data and snapshot files updated?
	   - Will new columns always be added at the end of the file or match the ordinal position as the column has in the source system and/or the assosicated model.json file for the entity?
	     - If the ordinal position is matched with the associated entity model.json file the structure of each partitioned data file reflects the attribute structure of the CDM related model.json file which would be good.
		 - If the ordinal position is NOT matched with the associated entity model.json file it would be bad in my opinion as it will jeopardize the output that you want to base on these partitions, especially because the files do not contain any column headers so the only way of properly matching is done by ordinal position.
2. [What happens when I delete a column?](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/export-data-lake-faq#what-happens-when-i-delete-a-column)
   - What happens to the CDM related model.json file for the updated entity in Azure Synapse Link for Dataverse?
     - Is the model.json file updated and will the column be deleted from the file?
	   - If this is the case it means that the ordinal position of all attributes after the deleted column will change which will have effect on the exported dataverse table files and snapshots if they are not updated, which the description states.
   - **_The questions below assume that the entity related model.json file is updated after each table structure change._**
   - If the exported dataverse table files and snapshots are not updated but the entity related model.json file is updated there is a mismatch between the ordinal positions of the attributes in the model.json file and the columns in the associated table and snapshot files. It takes away the possibility to match columns with attributes and any potential automation around that matching process.
3. [What happens if I change the data type of a column?](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/export-data-lake-faq#what-happens-if-i-change-the-data-type-of-a-column)
   - The answer states "Changing the data type of a column is a breaking change and you will need to unlink and relink."
   - Can you provide more information on what the process of unlinking and relinking actually causes. E.g., are exported dataverse files and snapshots deleted from the associated Azure Data Lake Gen 2 storage when unlinking occurs and will they be automatically regenerated when relinking occurs?

Hope to get more clarity on these topics. Thanks in advance.

Kind regards,

Youri Torchalski

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd9eb58e-fa75-d6ad-e1d6-a3c4242b1157
* Version Independent ID: c103e157-e34a-b636-8132-52c760f67e75
* Content: [Frequently asked questions about exporting Microsoft Dataverse table data to Azure Synapse Analytics and Azure Data Lake - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/export-data-lake-faq)
* Content Source: [powerapps-docs/maker/data-platform/export-data-lake-faq.yml](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/export-data-lake-faq.yml)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @youritorchalski. This issue has been assigned to the doc author for review.

**Comment by youritorchalski** [comment]
Thanks a lot @bishalgoswami.

**Comment by youritorchalski** [comment]
Hi @sabinn-msft,

Can you already share an update on these questions?

Thanks.

Kind regards,

Youri

**Comment by JasonHQX** [comment]
1.That is right: entity related model.json file is updated after each table structure change. 
2. The partitioned table is a snapshot of the near real time data so partitioned table does not read from Dataverse directly: https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-synapse#access-near-real-time-data-and-read-only-snapshot-data-preview
3. More information about unlinking and relinking: https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-synapse#unlinking-an-azure-synapse-link

**Comment by youritorchalski** [comment]
Hi @JasonHQX,

Thanks for the reply. This doesn't answer my questions though. I read extensively about the functionality multiple times and I would not ask these questions if the documentation would supply the answers to them.

Will you provide more detailed answers to questions 1 and 2 based on what I am actually asking or leave it like this? I had hoped you could contact MS Azure Synapse Link dev team to see how it is designed or perhaps do tests and see what the outcome is but that is not the case?

**Comment by youritorchalski** [comment]
Hi @JasonHQX. Hope you can get back to my question if it stops here or you will do additional investigation and come back with more input based on my questions?

Thank you.

Kind regards,

Youri

**Comment by anjaredbit** [comment]
We recently ran into a scenario where a roll-up field was attempted to be added to an entity that already had 10 roll-up fields. The solution gave an error saying "you cannot add any more roll-up fields" so we exited out of the field creation process, and to our knowledge, the field never was added to the solution or published. It does not appear anywhere in the entity, not can it be found via the REST API. See error below when searching by that field. 


```
    "error": {
        "code": "0x0",
        "message": "Could not find a property named 'sh_confirmeddonationsdonor' on type 'Microsoft.Dynamics.CRM.sh_frlocation'."
    }
}
```

However, we noticed this field was added in the `model.json` of the storage account associated with our azure synapse link to dataverse, which caused copy issues from our source to sink database. That surprised us 

How could it be that the azure synapse analytic link for dataverse picked up a field which was never saved, or created? I do feel that a better understanding of exactly how the `model.json` is updated would be helpful and I would also benefit from some of @youritorchalski's questions being answered. 

Thank you,
Anja

**Comment by youritorchalski** [comment]
Thank you @anjaredbit for your support. Let's hope we get more answers soon.

@JasonHQX can you follow up on this ticket and come back on the questions I asked. As you can see more companies are running into the same issues as there is still much unclarity around it.

Thank you.

Kind regards,
Youri

**Comment by JasonHQX** [comment]
Hi @youritorchalski, can you send the email with questions to SynapseLinkforDataverse@service.microsoft.com? We can loop dev team in through email thread.

**Comment by Mattp123** [comment]
Closing issue.

**Comment by youritorchalski** [comment]
Hej @JasonHQX,

Thanks for the reply! Awesome that we can continue with this with the support of Dev team, thanks a lot, I highly appreciate it! I will send the information somewhere this week!

Kind regards,

Youri

**Comment by youritorchalski** [comment]
@JasonHQX: Email sent just now at 20221027 at 14:46 CEST.
