### ISSUE TITLE
Azure Database pour MySQL - Série Débutants | Microsoft Docs/Se familiariser au concept clé débutant 1ere création

### ISSUE THREAD

**Issue by tmamb** [MicrosoftDocs/powerapps-docs#3570]
"Azure Database pour MySQL - Série Débutants | Microsoft Docs" https://docs.microsoft.com/fr-fr/shows/azure-database-for-mysql-beginners-series/

**Comment by phecke** [comment]
@tmamb Sorry, but please state your documentation issue in English, state your question or issue, and provide a link to the article in question. Thanks
