### ISSUE TITLE
custom connectors CAN now be added to solutions

### ISSUE THREAD

**Issue by robdawsoncranhillinsight** [MicrosoftDocs/powerapps-docs#3572]
[Enter feedback here]
Please confirm that my testing is correct. Custom Connectors can now be added to Dataverse solutions. IF so, please update this limitation article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba673f56-d0c1-6795-c028-5e121fe3cfeb
* Version Independent ID: bb0c60db-d75b-c470-81f9-3414e9b863d5
* Content: [Solutions in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/solutions-overview#known-limitations)
* Content Source: [powerapps-docs/maker/data-platform/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/solutions-overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robdawsoncranhillinsight. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@robdawsoncranhillinsight - Thank you for your feedback. You're correct. The article has been revised to remove that limitation.

Closing issue.
