### ISSUE TITLE
Associate multiple records with one request?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3573]
Is it possible to associate multiple records with one request for a many-to-many relationship?

Similar to the RelatedEntities of the AssociateRequest:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.messages.associaterequest.relatedentities?view=dataverse-sdk-latest#microsoft-xrm-sdk-messages-associaterequest-relatedentities

I'm not thinking about the batch operations:
https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/execute-batch-operations-using-web-api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce0b1cd-e7ce-a9b8-6b51-37be0a4dd848
* Version Independent ID: 54eecc75-29fe-29ba-94c9-0ad0b8694d69
* Content: [Associate and disassociate table rows using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/associate-disassociate-entities-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Interesting question.
It doesn't seem to be possible. 

OData spec says [11.4.6.1 Add a Reference to a Collection-Valued Navigation Property](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Create_a_New)

> A successful POST request to a navigation property's references collection adds a relationship to an existing entity. The request body MUST contain **a single entity reference** that identifies the entity to be added. See the appropriate format document for details.
> 
> On successful completion, the response MUST be [204 No Content](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Response_Code_204) and contain an empty body.
> 
> Note that if the two entities are already related prior to the request, the request is completed successfully.

But I tried this anyway:

**Request**
```
POST [Organization URI]/api/data/v9.2/systemusers(a9789cf9-3c0a-ed11-b83c-002248deb11e)/systemuserroles_association/$ref HTTP/1.1
Content-Type: application/json

[
        {
            "@odata.id": "[Organization URI]/api/data/v9.2/roles(e0d2794e-82f3-e811-a951-000d3a1bcf17)"
        },
        {
            "@odata.id": "[Organization URI]/api/data/v9.2/roles(e05075eb-9d74-e811-a95c-000d3a1c53e4)"
        }
]
```

**Response**

```
HTTP/1.1 400 Bad Request

{"error":{"code":"0x0","message":"Error identified in Payload provided by the user for Entity :'', For more information on this error please follow this help link https://go.microsoft.com/fwlink/?linkid=2195293  ---->  InnerException : Microsoft.OData.ODataException: Invalid JSON. More than one value was found at the root of the JSON content. JSON content can only have one value at the root level, which is an array, an object or a primitive value.
```
Many-to-Many or One-to-Many operations should be the same when dealing with a collection-valued navigation property.

But you can associate multiple records to a collection-valued navigation property on create, see [Associate table rows on create](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-entity-web-api#associate-table-rows-on-create)
