### ISSUE TITLE
The Power Fxs written over this document have typos ..

### ISSUE THREAD

**Issue by dora-taco** [MicrosoftDocs/powerapps-docs#3574]
https://docs.microsoft.com/en-us/power-apps/teams/localizing-sample-apps

The Power Fxs written over here have typos, please fix the document accordingly. 

### Issue no.1

https://docs.microsoft.com/en-us/power-apps/teams/localizing-sample-apps#adding-a-new-language-to-your-app

- “ru-RU” should be "ru-RU".
- and might be here to remove. because there is no mention of 'staticLocalizationsNewMessages'. 

```cmd
Collect(colLocalization,Filter(staticLocalizationsNewMessages,LanguageTag = gblUserLanguage));
```

```cmd
//user language
Set(gblUserLanguage,Switch(Left(Language(),2),"de","de-DE","en","en-US","es","es-ES","fr","fr-FR","it","it-IT","ja","ja-JP","nl","nl-NL",
"pt","pt-BR",“ru-RU”,
//default
"en-US"));
//build localization collection, with user's language
ClearCollect(colLocalization,Filter(staticLocalizations,LanguageTag = gblUserLanguage));
Collect(colLocalization,Filter(staticLocalizations,LanguageTag = gblUserLanguage));
```

### Issue no.2

https://docs.microsoft.com/en-us/power-apps/teams/localizing-sample-apps#adding-and-localizing-a-new-label

All Semicolons should be modified as a comma.

```cmd
With({varDefault: "Welcome to the app";varOOBTextId: "lblLoadingText_Welcome_locText"};With({varLocalizedText: LookUp(colLocalization;OOBTextID = varOOBTextId;LocalizedText)};Coalesce(varLocalizedText;varDefault)))
```

After modifying, that should be the following.

```
With(
    {
        varDefault: "Welcome to the app",
        varOOBTextId: "lblLoadingText_Welcome_locText"
    },
    With(
        {
            varLocalizedText: LookUp(
                colLocalization,
                OOBTextID = varOOBTextId,
                LocalizedText
            )
        },
        Coalesce(
            varLocalizedText,
            varDefault
        )
    )
)
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40e1d02-821c-372a-6470-4850b5d04417
* Version Independent ID: b7bd4543-5eba-c2b8-944e-be285f4455dc
* Content: [Localize sample apps (contains video) - Power Apps](https://docs.microsoft.com/en-us/power-apps/teams/localizing-sample-apps)
* Content Source: [powerapps-docs/teams/localizing-sample-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/localizing-sample-apps.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **saperlmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dora-taco. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. Documentation has been fixed. The changes will be reflected soon.
