### ISSUE TITLE
DisableFormCommandbar Code example is missing "Form" in the flag

### ISSUE THREAD

**Issue by logandersen** [MicrosoftDocs/powerapps-docs#3577]
DisableFormCommandbar Code example is missing "Form" in the flag

current example shows &flags=DisableCommandbar=true

I had to use &flags=DisableFormCommandbar=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262039c0-f604-e17c-04e0-22d2de423637
* Version Independent ID: 371d5907-0b52-33e1-dabb-b8210fea68fa
* Content: [Troubleshoot form issues in model-driven apps (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/troubleshoot-forms)
* Content Source: [powerapps-docs/developer/model-driven-apps/troubleshoot-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/troubleshoot-forms.md)
* Service: **powerapps**
* Sub-service: **troubleshoot**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by JimDaly** [comment]
@logandersen 
Thank you for your feedback.

It seems reasonable that the example should follow the naming convention.
I've applied this change depending on the assertion of @logandersen

@HemantGaur or @caburk 
Please advise if you feel this is not correct.
