### ISSUE TITLE
Power BI Dashboard and Report with RLS in Portal

### ISSUE THREAD

**Issue by iChrisJ** [MicrosoftDocs/powerapps-docs#3579]
Is Power BI Dashboard and Report with Row Level Security (RLS) fully supported in Portal? If yes, may I know whether we have any samples to show how it is supported in Portal? If not, what does it mean of the highlight?
![image](https://user-images.githubusercontent.com/6956871/185021118-86772f0b-dcc9-4faf-b53a-2515b02de3a3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15411392-e791-a6f2-990e-e46f07c2c7cd
* Version Independent ID: 929a4c75-03be-5125-369d-9a36aae92d09
* Content: [Set up Power BI integration - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/admin/set-up-power-bi-integration#considerations-and-limitations)
* Content Source: [powerapps-docs/maker/portals/admin/set-up-power-bi-integration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/set-up-power-bi-integration.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @iChrisJ. This issue has been assigned to the doc author for review.

**Comment by AVAagerosa** [comment]
Hey @iChrisJ you can achieve this, is you user within your AD with a Power BI license or not ?
If not, you could generate a Power BI embed token through an Azure function and passing a custom parameter, this custom parameter would then be passed to RLS. Then you can apply your RLS rules based on your custom parameters.

**Comment by iChrisJ** [comment]
Portal doesn't support Power BI with Row Level Security as the behaviors in Power BI client, but Role-Based security.
