### ISSUE TITLE
Use PowerApps Portal Web API authentication settings

### ISSUE THREAD

**Issue by AVAagerosa** [MicrosoftDocs/powerapps-docs#3581]
Hello,

I'm reaching you as I would like more information regarding how to authenticate on the PowerApps Portal Web API, the official documentation only mention that the presence of CSRF token is required (https://docs.microsoft.com/en-us/power-apps/maker/portals/web-api-overview#authenticating-portals-web-api-requests) but this is not true.

It seems the web api requires some cookies to be present in the request as well, could we have more information on that ?

The main purpose is to be able to call the web api of Portal 1 from Portal 2.

Thank you,

**Comment by AVAagerosa** [comment]
@nickdoelman and @neerajnandwana-msft any news on this ?

**Comment by nickdoelman** [comment]
Thank you for your feedback but using the Portal Web API to communicate from one portal to another is not supported. You can log this as an idea on https://aka.ms/mpp_ideas
