### ISSUE TITLE
when Git is used to manage projects, some items of combobox cannot be synchronized into the warehouse after being changed. Could you please solve this problem? Thank you

### ISSUE THREAD

**Issue by usenameW** [MicrosoftDocs/powerapps-docs#3582]
Hello, when Git is used to manage projects, some items of combobox cannot be synchronized into the warehouse after being changed. Could you please solve this problem? Thank you

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3bde1a13-d236-9d44-8b79-bc8916c8b537
* Version Independent ID: 7e41ba3e-befb-f016-ad5d-0a7ce4971333
* Content: [Power Apps 中的 Combo box 控件 - Power Apps](https://docs.microsoft.com/zh-cn/power-apps/maker/canvas-apps/controls/control-combo-box)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @usenameW. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please submit a [support request](https://docs.microsoft.com/power-platform/admin/get-help-support) for help with the problem investigation with the support team.
