### ISSUE TITLE
Not able to access an existing code component

### ISSUE THREAD

**Issue by PowerDashDash** [MicrosoftDocs/powerapps-docs#3587]
Hi, 

I used a code component in my app, which worked just fine until a couple of days ago. 
Now I face issues:
-  I cannot find this component under the "code" section in my canvas apps anymore
-  I cannot access existing apps that already had this code component implemented

**Link to the used code component:** 
https://github.com/OOlashyn/PCF-RangeSliderControl/releases
See also my post about the issue here:
https://powerusers.microsoft.com/t5/Power-Apps-Experimental-Features/Help-to-restore-an-app-with-git-integration-and-a-Custom-Code/td-p/1726313

**Comment by phecke** [comment]
@PowerDashDash If you have a question or issue with our documentation, please provide a link to the doc page.

**Comment by KumarVivek** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.
 
Closing this issue.
