### ISSUE TITLE
Could use Dataverse Connector instead of Dataverse OData API?

### ISSUE THREAD

**Issue by femo1de** [MicrosoftDocs/powerapps-docs#3588]
This article describes how to connect to the Dataverse OData API. I think this can be accomplished more easily by using the Dataverse Connector for Dataflow. This would simplify the process because users wouldnt have to get the odata endpoint first

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2f8a4d-5b76-0fed-c0cb-6e2f06a4240e
* Version Independent ID: 6b6cf6ec-87c8-f109-98ce-9181cbfb736e
* Content: [Migrate data between Microsoft Dataverse environments using the dataflows OData connector - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-odata-dataflows-migration)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-odata-dataflows-migration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-odata-dataflows-migration.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @femo1de. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@femo1de 
Thanks for your feedback.

Looks like this topic was originally written a couple of years ago. Perhaps the Dataverse Connector didn't exist at that time?
I will reach out to the Dataverse Connector for Dataflow team to ask that they provide some documentation showing how to use their connector.
