### ISSUE TITLE
Dashboard and Workspace [Power BI tile]

### ISSUE THREAD

**Issue by Paul-Lees** [MicrosoftDocs/powerapps-docs#359]
This will only work for a Tile that is on a Dashboard on a personal workspace. This will not work for a group workspace dashboard/tile.

the only place i have been able to find this information on the internet is a youtube video comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9804ada3-9503-a2de-5239-540d5e702e36
* Version Independent ID: 8bf085bb-bd86-3a79-4758-d40d99ba0cc6
* Content: [Power BI tile control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. It works for shared workspaces as well; it appears this needs an investigation as a support issue. Please reach out to support team via a [support service](https://admin.powerplatform.microsoft.com/support) request to troubleshoot.
