### ISSUE TITLE
Delete duplicate default command library

### ISSUE THREAD

**Issue by daniel-alifano** [MicrosoftDocs/powerapps-docs#3591]
In the docs it suggests:
Data > Tables, select the Model-driven app element table, select the Data tab, select the record, and then select Delete record on the command bar. Wait a few minutes for the deletion to propagate.

However the table is now read-only

The resulting issue is that there are two default component libraries in model driven apps not allowing me to add additional buttons to the command bar.

![image](https://user-images.githubusercontent.com/31948694/186298234-11d2a33f-ac0c-44e7-aadd-8e9fb025a044.png)

![image](https://user-images.githubusercontent.com/31948694/186298316-0d2aa1e8-65df-4303-833e-2dccadd20515.png)

**Comment by phecke** [comment]
@daniel-alifano Please provide a link to the documentation page that you are talking about. Thanks

**Comment by daniel-alifano** [comment]
https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/command-designer-limitations.md
7th point down

However i fixed the issue using this guide:
https://taerimhan.com/quick-fix-cant-delete-command-library-component/

no idea how a second default command library got created

**Comment by Mattp123** [comment]
@daniel-alifano - The article has been updated with new instructions for removing the command component library.
To delete command component libraries, you must delete the app. Alternatively, you can delete the associated record within the model-driven app element table, then delete the component library. The model-driven app element record exists in Dataverse but isn't exposed in solutions. More information: [Delete a Model-Driven App Element record](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/command-designer-limitations#delete-a-model-driven-app-element-record)
