### ISSUE TITLE
Spelling Mistake 

### ISSUE THREAD

**Issue by dubeyneeraj22** [MicrosoftDocs/powerapps-docs#3592]
The datetimeOffset is typed as "dataTimeoffset"

![image](https://user-images.githubusercontent.com/53667390/186332074-0e72a4f8-f495-4a75-b663-e05b18cf5d1e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd9eb58e-fa75-d6ad-e1d6-a3c4242b1157
* Version Independent ID: c103e157-e34a-b636-8132-52c760f67e75
* Content: [Frequently asked questions about exporting Microsoft Dataverse table data to Azure Synapse Analytics and Azure Data Lake - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/export-data-lake-faq)
* Content Source: [powerapps-docs/maker/data-platform/export-data-lake-faq.yml](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/export-data-lake-faq.yml)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dubeyneeraj22. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@dubeyneeraj22 - Thank you for your feedback. The article has been updated to reflect the correct data type syntax.

Closing issue.
