### ISSUE TITLE
Custom Certificate tab breaks portal that had code pushed from earlier portal versions 

### ISSUE THREAD

**Issue by CynCity561** [MicrosoftDocs/powerapps-docs#3596]
[Hello, letting you know we came across an issue with using custom certificates. The page indicates to use the "Custom Certificate" tab, but anytime a certificate was uploaded here the portal would break. Instead we used a self-signed certificate and uploaded to "SSL Certificate" tab and it worked for enabling OAuth 2.0 to make client-side calls to our customer APIs. 

The portal that would break when uploading to "Custom Certificate" tab was newly created as a portal from Blank and had our previous portal code (in PROD env) pushed to it via the CLI tool. The portal for our PROD instance was a portal from Blank too before they got rid of the public key. Hence the difference is that one is a CDSStarterPortal (newer) and the other StarterPortal (older).

To further test - I made a portal from Blank (CDSStarterPortal) and uploaded a custom certificate under the "custom certificate" tab. That portal does not break when uploading underneath this tab and works. I think there might be a bug when using the Custom Certificate tab on portals that had their portal code pushed from earlier portal versions. 

I spent a week troubleshooting this with 3 internal Microsoft Support Desks, so please look into it because no one seems to know why this happens. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c569345a-740f-f09b-efdc-01bc0a2d99e4
* Version Independent ID: c569345a-740f-f09b-efdc-01bc0a2d99e4
* Content: [Add custom certificates - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/admin/manage-custom-certificates)
* Content Source: [powerapps-docs/maker/portals/admin/manage-custom-certificates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/manage-custom-certificates.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CynCity561. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for this feedback. The team is aware of the issue and working on a resolution. In the meantime, continue to work with the support team to update the custom certificate for your site.
