### ISSUE TITLE
Page needs to be updated with correct information

### ISSUE THREAD

**Issue by CynCity561** [MicrosoftDocs/powerapps-docs#3597]
[Hi there,
The public keys for power apps portals are no longer available for newly created portals. The deprecation of them happened in June and here is that article link - https://powerpages.microsoft.com/en-gb/blog/upcoming-deprecations-in-power-apps-portals/.

Old portals that rely on public keys to make client-side APIs call will cease to work sometime soon (not sure what their timeline is for that), so customers need to switch to using a custom certificate. 
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9354910f-4fcd-2ba1-8978-c4d40dece85b
* Version Independent ID: 28acb897-4130-2bfd-f86e-2fbbb6b0026a
* Content: [Download public key of a portal - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/admin/get-public-key)
* Content Source: [powerapps-docs/maker/portals/admin/get-public-key.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/get-public-key.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CynCity561. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
The documentation has been updated to reflect this.
