### ISSUE TITLE
Incorrect plugin link in "Rich text editor properties" section

### ISSUE THREAD

**Issue by Hisol-mlund** [MicrosoftDocs/powerapps-docs#3598]
"Rich text editor properties" section

References extensibility through plugins, presumable meaning CKEditor plugins, but link points to Dataverse plugins article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ecdffd-f6c2-4fc2-2d74-94d16c18108c
* Version Independent ID: cb939451-df9d-23b2-5e98-e2519c3b90db
* Content: [Use the rich text editor control in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/rich-text-editor-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/rich-text-editor-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/rich-text-editor-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **craigm**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Hisol-mlund. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@Hisol-mlund - Thank you for your feedback. You're correct and the article has been updated to send readers to the CKEditor list of available plugins (add-ons). 

Closing issue.
