### ISSUE TITLE
Premium capacity [Power BI tile]

### ISSUE THREAD

**Issue by Paul-Lees** [MicrosoftDocs/powerapps-docs#360]
Moving the workspace that a report is published to into a Premium Capacity prevents this functionality working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9804ada3-9503-a2de-5239-540d5e702e36
* Version Independent ID: 8bf085bb-bd86-3a79-4758-d40d99ba0cc6
* Content: [Power BI tile control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. Please raise a support [service request](https://admin.powerplatform.microsoft.com/support) to investigate the issue.
