### ISSUE TITLE
#Avepoint Pipeline for Microsoft® Dynamics CRM

### ISSUE THREAD

**Issue by tmamb** [MicrosoftDocs/powerapps-docs#3605]
Avepoint Pipeline for Microsoft® Dynamics CRM https://apps.microsoft.com/store/detail/avepoint-pipeline-for-microsoft%C2%AE-dynamics-crm/9WZDNCRDGF1K

**Comment by phecke** [comment]
@tmamb Closing. Open a new issue and describe the question or problem you are having with our product documentation, and include a link to the doc page.
