### ISSUE TITLE
The instructions are wrong here

### ISSUE THREAD

**Issue by BossBabyIrish** [MicrosoftDocs/powerapps-docs#3611]
Using these instructions exactly and they simply result in a pipeline failure every time. The instructions for the trigger say to put /model.json but doing so returns nothing. When you put model.json it finds the files in the trickle feed service that end in that but can't find the model.json file because it doesn't exist there, it exists one folder up and there doesn't appear any way to get to that folder.

Operation on target LookupModelJson failed: ErrorCode=UserErrorFileNotFound,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=ADLS Gen2 operation failed for: Operation returned an invalid status code 'NotFound'. Account: 'xxx'. FileSystem: 'xxx'. Path: 'Microsoft.Athena.TrickleFeedService/model.json'. ErrorCode: 'PathNotFound'. Message: 'The specified path does not exist.'. RequestId: 'aa6cd79f-c01f-0030-4679-b9d7e1000000'. TimeStamp: 'Fri, 26 Aug 2022 18:23:57 GMT'.,Source=Microsoft.DataTransfer.ClientLibrary,''Type=Microsoft.Azure.Storage.Data.Models.ErrorSchemaException,Message=Operation returned an invalid status code 'NotFound',Source=Microsoft.DataTransfer.ClientLibrary,'
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a8d324c-cc14-c8f9-8adf-4b9af10f55ce
* Version Independent ID: 7a8d324c-cc14-c8f9-8adf-4b9af10f55ce
* Content: [Copy Dataverse data into Azure SQL - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-pipelines)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-pipelines.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-pipelines.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @JasonHQX
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BossBabyIrish. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@BossBabyIrish - The article has recently had significant changes to it. Make sure you are using the latest version and let me know if you still experience an issue by reopening this issue.

**Comment by WPelserDatacom** [comment]
I experienced the same issue as @BossBabyIrish - but managed to pick up the model.json file when I set the "Blob path begins with" and "Blob path ends with" to model.json
![image](https://user-images.githubusercontent.com/107005677/187578479-507d81bc-ee1f-4940-a394-3938f1583dd8.png)
![image](https://user-images.githubusercontent.com/107005677/187578686-8c590d3c-0040-4b8d-b8f2-97addf20afe6.png)

"
