### ISSUE TITLE
As of 14 August Pre Create Step is not working anymore

### ISSUE THREAD

**Issue by ChrisAt2at** [MicrosoftDocs/powerapps-docs#3614]
We have a process in place where we create a mail from a template containing a placeholder (e.g. [link]).
Next to that we have a Pre Create operation on the email entity that will replace that placeholder text with actual values (e.g. <a href="link">Text</a>).
It has always worked, but somewhere between 10:06 CET and 22:06 CET on the 14th of august it does not work anymore.

We've enabled the audith history and there are some strange things:
- When performing a new test case, the audit history actually shows the correct mail contents on the Create entry (<a href="link">Text</a>).
- When we then change the (incorrect) mail contents from within the form and save it, it adds an update audit history entry where it displays the value changed from the incorrect value ([link]) to the new value (so not from the value it displays in the create audit history entry)
- When debugging through the plugin using the plugin tool we do see that the plugin changes the value to the correct value.
- When debugging thought the new post create plugin while the pre create is not disabled we see that the post plugin does not do anything as it already has the correct value (it cannot find the placeholder text)
- When we disable the pre create plugin and add a new the plugin to be run from the Post Create message instead we see it is working correctly: There is a create entry with the placeholder ([link]) and then an update entry from [link] to <a href="link">Text</a>.

Was there an update to the platform on 14th of August that could have triggered this? Or am I missing something.

**Comment by phecke** [comment]
@ChrisAt2at Sorry to hear about your troubles. The platform does get periodic updates, but we have no way to know when that happens or what has changed.

If you need help, you should contact Microsoft Support.

We handle documentation questions and issues here.
