### ISSUE TITLE
Link to example file is broken (missing branch)

### ISSUE THREAD

**Issue by skfd** [MicrosoftDocs/powerapps-docs#3616]
Link to example file [SimpleActivities.cs](https://github.com/microsoft/PowerApps-Samples/blob/master/cds/orgsvc/C%23/WorkflowActivities/WorkflowActivities/SimpleActivities.cs) is broken (missing git branch)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1653ada3-4097-2ed2-cc2f-00fc3e6a88ef
* Version Independent ID: df966534-1a8b-e483-2943-eec0212732d4
* Content: [Sample: Create a custom workflow activity (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/workflow/sample-create-custom-workflow-activity?source=recommendations)
* Content Source: [powerapps-docs/developer/data-platform/workflow/sample-create-custom-workflow-activity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/workflow/sample-create-custom-workflow-activity.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @skfd. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@skfd Try again. We had renamed the parent folder and that may have caused temporary problems. Seems to work for me.
