### ISSUE TITLE
Not working for existing records

### ISSUE THREAD

**Issue by EricBos** [MicrosoftDocs/powerapps-docs#3618]
Why does this not work on existing records, just like in any other database?

Who comes up with these solutions?

(sorry, extremely frustrated with dataverse)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3df80b-f571-21e7-b622-33ebc6926c7d
* Version Independent ID: bee61c6a-753e-09f8-31c6-5c8dd0cec95f
* Content: [Autonumber columns in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/autonumber-fields)
* Content Source: [powerapps-docs/maker/data-platform/autonumber-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/autonumber-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @daemelia
* Microsoft Alias: **kvivek**

**Comment by Mattp123** [comment]
@EricBos - What you're asking for is a feature request that can't be addressed in the Power Apps documentation. You can submit a new feature request or vote for an existing one here: [Power Apps community ideas](https://ideas.powerapps.microsoft.com)

Closing issue.
