### ISSUE TITLE
OptionSetMetadata is missing

### ISSUE THREAD

**Issue by acieslik** [MicrosoftDocs/powerapps-docs#3619]
Its nice to have this new feature, but what is completely missing with incremental folder option is the extraction of the Global/OptionSetMetadata or State and StatusMetadata.

Is there a workaround for that? Or this this part really completely skipped in this export method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb9c8f3-c785-1dec-26a0-380e11df5fd0
* Version Independent ID: 7cb9c8f3-c785-1dec-26a0-380e11df5fd0
* Content: [Query and analyze the incremental updates - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-incremental-updates)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-incremental-updates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-incremental-updates.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @JasonHQX
* Microsoft Alias: **jasonhuang**

**Comment by JasonHQX** [comment]
Hi @acieslik, we are currently working on supporting reading option set data through ADF template to replace numerical number with text label before exporting to Azure SQL

**Comment by bishalgoswami** [comment]
Thanks for your comment, @acieslik. This issue has been assigned to the doc author for review.

**Comment by JasonHQX** [comment]
Hi @acieslik, it should be supported now. Optionset metadata should be under one of the timestamp folders. Besides that, the workaround is: https://learn.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-choices-adf

**Comment by Mattp123** [comment]
Closing issue.
