### ISSUE TITLE
Known issue [Date picker]

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#362]
There is a known limitation with Date Picker which should be highlighted here: there is no way to clear a saved value. See discussion here: https://powerusers.microsoft.com/t5/General-Discussion/Clear-Data-Values-leaving-them-blank/m-p/5721#M2586

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4fb137e-6a79-e538-a90a-0d17c5cfb8f7
* Version Independent ID: 3d725d06-378d-4540-4fc4-6959d00eaf9e
* Content: [Date Picker control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-date-picker)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-date-picker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-date-picker.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by dawidvanheerden** [comment]
Hello everyone. The IsEditable property is not in the docs. This allows for the date to be entered, instead of having to select is from the calendar control.

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. The doc references IsEditable property that can be used to edit the text inside control. Please use this property to edit.
