### ISSUE TITLE
Are Forwarded or X-Forwarded headers supported?

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/powerapps-docs#3621]
Hello,

My company uses Api Managment system to control API access for D365 but it looks like any combination of `Forwarded` headers is ignored. As the result all links that are returned by API are referring to original org address, not to API Manager address.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c228177-ace4-9ffc-d8db-1251cc98d228
* Version Independent ID: 864e7cde-7176-241c-992d-9e421bf4d6d3
* Content: [Compose HTTP requests and handle errors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/compose-http-requests-handle-errors)
* Content Source: [powerapps-docs/developer/data-platform/webapi/compose-http-requests-handle-errors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/compose-http-requests-handle-errors.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FixRM. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@FixRM 
This seems like a feature request ask. 

We don't document any behavior about [Forwarded headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded), and you should not expect any special behavior for them. 

We also don't have any documentation that speaks to using API Management with Dataverse Web API at all.  I'm not clear on the use case. Can you speak to why this would be valuable or expected?

**Comment by JimDaly** [comment]
Accidentally closed, waiting for response from @FixRM.

**Comment by FixRM** [comment]
Hi @JimDaly, thanks for the answer. It does matter because OData use absolute URLs in results. For example:

json
```
{  
   "@odata.context":"https://orgname.crm.dynamics.com/api/data/v9.2/$metadata#accounts(name)",
   "value":[  
      {  
         "@odata.etag":"W/\"468026\"",
         "name":"Adventure Works (sample)",
         "accountid":"8151925c-cde2-e411-80db-00155d2a68cb"
      }
   ],
   "@odata.nextLink":"https://orgname.crm.dynamics.com/api/data/v9.2/accounts?$select=name&$skiptoken=%3Ccookie%20pagenumber=%222%22%20pagingcookie=%22%253ccookie%2520page%253d%25221%2522%253e%253caccountid%2520last%253d%2522%257b8151925C-CDE2-E411-80DB-00155D2A68CB%257d%2522%2520first%253d%2522%257b7D51925C-CDE2-E411-80DB-00155D2A68CB%257d%2522%2520%252f%253e%253c%252fcookie%253e%22%20/%3E"
}
```
Same problem with some headers like `location`. We want to hide API address behind proxy, but API disclose it's real address itself.

**Comment by JimDaly** [comment]
Hmm...

I must admit I don't know much about API management, but I think the idea is that it allows you to manage any number of APIs you create or use so that can control who can access them.

Dataverse already has a mechanism to control who can access the APIs. I'm not aware of any documentation or guidance we provide that recommends using Dataverse APIs with API Management.  If we are sending a conflicting message somewhere, please let us know.

It seems like if you want to hide the details of the Dataverse APIs, you would need to create a wrapper service to hide those details and then register the APIs for that service using API Management...?

So, I'm going to close this as a feature request. You can post this as an idea on the [ideas site](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) if you feel it is a gap.

**Comment by FixRM** [comment]
Thanks

**Comment by RedsGT** [comment]
I think we might just be able to use the APIM here to do what you need with a [Mask URLs in content](https://docs.microsoft.com/en-us/azure/api-management/api-management-transformation-policies#MaskURLSContent) transformation policy. 

If you've been in the Dataverse world a bit, you might see that example 4 has API versions that look very familiar for some reason:

![image](https://user-images.githubusercontent.com/1190796/189037558-c148ca1c-c5b9-43eb-a3c7-4655d63b1036.png)

**Comment by FixRM** [comment]
Thanks @RedsGT. I've been in CRM/D365/Dataflex/Dataverse world for more than ten years. Customer use other API management solution with similar option but they are not happy with that due to some performance reasons.
