### ISSUE TITLE
Not Working as expected for Asynchronous logics

### ISSUE THREAD

**Issue by allandecastro** [MicrosoftDocs/powerapps-docs#3622]
Hello,

According to the documentation, "Asynchronous logic is not bypassed" but it's not the case.
I opened a MS Support ticket, and they reproduced the bug.

Regard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6a47f7d-d05b-f22c-bb31-d27ea0675128
* Version Independent ID: ad3a29a3-7e39-693a-7e9f-8fe313433bcd
* Content: [Bypass Custom Business Logic (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/bypass-custom-business-logic?tabs=webapi)
* Content Source: [powerapps-docs/developer/data-platform/bypass-custom-business-logic.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/bypass-custom-business-logic.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @allandecastro. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@allandecastro 
Thanks for your feedback.
I'll reach out to you via email to get details.

**Comment by JimDaly** [comment]
@allandecastro 
This was escalated to the dev team and they have taken an action item to fix the behavior to align with the design which was documented.

**Comment by allandecastro** [comment]
@JimDaly : Thanks a lot ! :)
I think maybe we can reopen this as a bug to make sure other people are aware of this problem.
