### ISSUE TITLE
DataverseToSQL Template issue - Lookup size exceeded

### ISSUE THREAD

**Issue by WPelserDatacom** [MicrosoftDocs/powerapps-docs#3625]
Hi.
Following this documentation: https://docs.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-pipelines
There is an error on the Lookup activity (LookupModelJson) when I run the Pipeline. The error reads: 
**Operation on target LookupModelJson failed: ErrorCode=UserErrorComputePluginFailure,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=The size of lookup activity result exceeds the limitation 4194304.,Source=,''Type=Microsoft.DataTransfer.Execution.Core.ExecutionException,Message=The size of lookup activity result exceeds the limitation 4194304.,Source=Microsoft.DataTransfer.TransferTask,'**
The Issue I have is that it seems the Lookup activity has a limit of 
1. 5000 rows (not applicable in this instance as only 1 row is returned)
2. supports up to 4 MB in size (our file is 4.12MB)
![image](https://user-images.githubusercontent.com/107005677/188269041-bbda7298-e326-48b2-aceb-f1ae4c312621.png)

In my case the data is from D365 and we will be loading 500+ tables so I don't see how we can use this pipeline activity as is.
The suggested workaround for the pipeline activity limitation is to batch the records - but it won't work in this case because it is a JSON blob failing on size rather than #records.

Side note: My workaround, for now, is to use a Copy activity(which does not have the size limit of 4mb) and move the model.json file into an Azure SQL database table, interrogate the data using OPENJSON, JSON_VALUE, JSON_QUERY and FOR JSON PATH to produce the same output required for this template, but filtered with a TOP X command. (I will use OFFSET and FETCH later on once I'm happy the solution works to batch load it). 
My current working SQL query is this one (without the OFFSET and FETCH) - hope it helps someone with the same issue until it's resolved:

--
`  DECLARE @modelJson  varchar(max);
  DECLARE @SQL2  varchar(max);
  DECLARE @SQL3  varchar(max);

 SELECT @modelJson = [ModelJson] FROM [Config].[CDMModelData] --New table created to store json data "as is" into 1 column called ModelJson.
 SELECT @SQL2 = [value] FROM  OPENJSON(@modelJson) e WHERE [key] = 'entities'
 SELECT @SQL3= (SELECT TOP 5  --top 5 was added in just to test the Output and filters, but needed in this instance to overcome the size limitation of the lookup activity
							   JSON_VALUE(e.value,'$.name')  as name
							  ,JSON_QUERY(e.value,'$.attributes')  as attributes
							  ,JSON_QUERY(e.value,'$.partitions')  as [partitions]
					  FROM OPENJSON(@SQL2) e  
					FOR JSON PATH )

 SELECT @SQL3 AS JSONfile --this is to avoid random output column name`
--
![image](https://user-images.githubusercontent.com/107005677/188268469-ca447e8f-307e-4fef-bb3f-7259b6ec675c.png)
![image](https://user-images.githubusercontent.com/107005677/188268647-a6c6e422-9614-4a15-9c20-90a878fca424.png)
![image](https://user-images.githubusercontent.com/107005677/188268780-96c4d669-5285-4017-8b78-59396798e983.png)  
![image](https://user-images.githubusercontent.com/107005677/188269152-bb231b7a-3138-4bc3-9b98-b58329784ccb.png)

**Comment by JasonHQX** [comment]
Hi @WPelserDatacom 

Large model.json can cause failure [https://docs.microsoft.com/en-us/azure/data-factory/control-flow-lookup-activity#supported-capabilities](https://docs.microsoft.com/en-us/azure/data-factory/control-flow-lookup-activity)
 **Work around:** 
1. Use separate Synapse Links for different set of entities/tables. ADF pipelines should point to same destination Azure SQL DB. 
2. Copy model.json to SQL DB. https://github.com/MicrosoftDocs/powerapps-docs/issues/3625

**Comment by Mattp123** [comment]
Closing issue.
