### ISSUE TITLE
Typos of 'Screnarios' instead of 'Scenarios'

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#3626]
There are two instances of this typo on the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd6b9d7-4668-e08b-3796-2241351d80ff
* Version Independent ID: 7dd6b9d7-4668-e08b-3796-2241351d80ff
* Content: [Understand Power Apps Studio - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/power-apps-studio)
* Content Source: [powerapps-docs/maker/canvas-apps/power-apps-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/power-apps-studio.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @biterbit. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thank you for the feedback. I fixed the typos and republished the topic. You should see the changes in about an hour.

Thanks,
Mints
