### ISSUE TITLE
Correct terminology used?

### ISSUE THREAD

**Issue by m-bae** [MicrosoftDocs/powerapps-docs#3627]
Hi. I've read the page (linked below), and in the following section. Should it state "ROW" as well? as I don't think the whole table would be deleted if a row in the parent is deleted.

e.g. (I've inserted where I think a reference to rows might need to be inserted....)

1. "prevent deleting the ROW in the primary table, so that the related table rows can be....." and 
2. "Allow the related table ROWS to be deleted automatically with the deletion of the primary table row" and
3. "If the related table doesn't support a primary table, you can allow the primary table ROW to be deleted and the value of the lookup will be cleared IN THE RELATED TABLE ROWS."

---section start-------
Preserve data integrity
Some tables exist to support other tables. They don't make sense on their own. They will typically have a required lookup column to link to the primary table they support. What should happen when the primary row is deleted?

You can use the relationship behavior to define this according to the rules for your business. Two options are:

Prevent deleting the **primary table** so that the related table rows can be reconciled, perhaps by associating them with a different primary table.
Allow the **related tables** to be deleted automatically with the deletion of the primary table row.
If the related table doesn't support a primary table, you can allow the **primary table** to be deleted and the value of the **lookup will be cleared**.
------section end----------

Thanks :)

M

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db73658-557a-e0a1-a7d5-90000fa5540e
* Version Independent ID: 3f1e141d-33ec-88ae-d511-93f2eadcdd76
* Content: [About table relationships for Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-entity-relationships)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-entity-relationships.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-entity-relationships.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @m-bae. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@m-bae - Thank you for your feedback. The article has been updated to link to the article that discusses in specific detail each of the relationship behaviors since the article alludes to controlling the behavior but isn't specific in what the options are. 
Closing issue.
