### ISSUE TITLE
Improvement needed

### ISSUE THREAD

**Issue by MahdiSheikhi** [MicrosoftDocs/powerapps-docs#3628]
In Note box 

**System Customer security role**
need to update with
**System Customizer security role**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a00b4a6-c147-cffa-92c9-5cb183c4ea67
* Version Independent ID: 83d7d42c-71f3-1138-318f-5bd252a2ab3b
* Content: [Import solutions - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/import-update-export-solutions)
* Content Source: [powerapps-docs/maker/data-platform/import-update-export-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/import-update-export-solutions.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MahdiSheikhi. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@MahdiSheikhi - Thank you for your feedback. The article has been revised to reflect the correct security role name and will be published live in a couple of hours.

Closing issue.
