### ISSUE TITLE
Trivial typo

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#363]
Greetings,
This is rather trivial and insignificant.

In "Authoring environment" / "Formula separators and chaining operator"
(right below the "dot" vs "comma" table...)

"The change in the PowerApps list separator is consistent with that happens to the Excel list separator."
&gt;&gt; should be " [...] consistent with what happens to [...] "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 864e69eb-925d-45a3-e79e-0356ee826ad9
* Version Independent ID: 1833ba5a-da61-7c5a-c4b2-2a7c6d983494
* Content: [Build global support into canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/global-apps#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/global-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/global-apps.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @a-zaf!
