### ISSUE TITLE
Missing tables - limitation

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/powerapps-docs#3631]
There are some tables that are not available

| # | LogicalName | IsPrivate | DataProviderId | IntroducedVersion | IsChildEntity | IsCustomEntity | IsIntersect | IsManaged | IsValidForAdvancedFind |
| - | - | - | - | - | - | - | - | - | - |
| 1 | aaduser | false | 54629ed7-0cd3-4c85-9b6c-ea5f8548a9aa | 9.1.0.0 | false | true | false | true | true |
| 2 | aciviewmapper | false | null | 8.2.0.0 | false | false | false | true | false |
| 3 | appaction | false | null | 9.1.0.0 | false | true | false | true | true |
| 4 | appactionmigration | false | null | 9.1.0.13 | false | true | false | true | true |
| 5 | appactionrule | false | null | 9.1.0.10 | false | true | false | true | true |
| 6 | attribute | false | null | 9.1.0.0 | false | false | false | true | false |
| 7 | audit | false | null | 5.0.0.0 | false | false | false | true | false |
| 8 | category | false | null | 8.1.0.0 | false | false | false | true | true |
| 9 | channelaccessprofileentityaccesslevel | false | null | 8.0.0.0 | false | false | true | true | false |
| 10 | chat | false | null | 1 | false | true | false | true | false |
| 11 | columnmapping | false | null | 5.0.0.0 | false | false | false | true | false |
| 12 | complexcontrol | false | null | 5.0.0.0 | false | false | false | true | false |
| 13 | customcontrol | false | null | 8.0.0.0 | false | false | false | true | false |
| 14 | customcontroldefaultconfig | false | null | 8.0.0.0 | false | false | false | true | false |
| 15 | customcontrolresource | false | null | 8.0.0.0 | false | false | false | true | false |
| 16 | dataperformance | false | null | 7.1.0.0 | false | false | false | true | false |
| 17 | dependency | false | null | 5.0.0.0 | false | false | false | true | false |
| 18 | displaystring | false | null | 5.0.0.0 | false | false | false | true | false |
| 19 | entity | false | null | 9.1.0.0 | false | false | false | true | false |
| 20 | entitydataprovider | false | null | 9.0.0.0 | false | false | false | true | false |
| 21 | entityindex | false | null | 9.2.0.0 | false | false | false | true | false |
| 22 | entitykey | false | null | 9.1.0.0 | false | false | false | true | false |
| 23 | entityrelationship | false | null | 9.1.0.0 | false | false | false | true | false |
| 24 | exchangesyncidmapping | false | null | 6.0.0.0 | false | false | false | true | false |
| 25 | flowmachineimage | false | null | 1.3.0.0 | false | true | false | true | true |
| 26 | importdata | false | null | 5.0.0.0 | false | false | false | true | false |
| 27 | importentitymapping | false | null | 5.0.0.0 | false | false | false | true | false |
| 28 | importjob | false | null | 5.0.0.0 | false | false | false | true | true |
| 29 | indexattributes | false | null | 9.2.0.0 | false | false | false | true | false |
| 30 | invaliddependency | false | null | 5.0.0.0 | false | false | false | true | false |
| 31 | languagelocale | false | null | 8.0.0.0 | false | false | false | true | false |
| 32 | languageprovisioningstate | false | null | 9.1.0.0 | false | false | false | true | false |
| 33 | lookupmapping | false | null | 5.0.0.0 | false | false | false | true | false |
| 34 | mailboxtrackingfolder | false | null | 7.1.0.0 | false | false | false | true | false |
| 35 | managedproperty | false | null | 9.1.0.0 | false | false | false | true | false |
| 36 | msgraphresourcetosubscription | false | null | 9.2.0.23 | false | true | false | true | false |
| 37 | optionset | false | null | 9.1.0.0 | false | false | false | true | false |
| 38 | owner | false | null | 5.0.0.0 | false | false | false | true | false |
| 39 | ownermapping | false | null | 5.0.0.0 | false | false | false | true | false |
| 40 | picklistmapping | false | null | 5.0.0.0 | false | false | false | true | false |
| 41 | pluginpackage | false | null | 9.1.0.0 | false | true | false | true | true |
| 42 | plugintracelog | false | null | 7.1.0.0 | false | false | false | true | true |
| 43 | postregarding | false | null | 5.0.0.0 | false | false | false | true | false |
| 44 | principalentitybusinessunitmap | false | null | 9.1.0.0 | false | false | false | true | false |
| 45 | principalobjectaccess | false | null | 5.0.0.0 | false | false | false | true | false |
| 46 | principalobjectattributeaccess | false | null | 5.0.0.0 | false | false | false | true | false |
| 47 | recurrencerule | false | null | 5.0.0.0 | false | false | false | true | false |
| 48 | relationship | false | null | 9.1.0.0 | false | false | false | true | false |
| 49 | ribbonmetadatatoprocess | false | null | 9.1.0.0 | false | false | false | true | false |
| 50 | roletemplate | false | null | 5.0.0.0 | false | false | false | true | false |
| 51 | roletemplateprivileges | false | null | 5.0.0.0 | false | false | true | true | false |
| 52 | runtimedependency | false | null | 9.0.0.0 | false | false | false | true | false |
| 53 | savedqueryvisualization | false | null | 5.0.0.0 | false | false | false | true | false |
| 54 | serviceplanmapping | false | null | 2.4.0.0 | false | true | false | true | true |
| 55 | sharedobject | false | null | 1.0.0.0 | false | true | false | true | true |
| 56 | sharedworkspace | false | null | 1.0.0.0 | false | true | false | true | true |
| 57 | sitemap | false | null | 5.0.0.0 | false | false | false | true | false |
| 58 | solutionhistorydata | false | null | 9.1.0.0 | false | false | false | true | false |
| 59 | subscriptionmanuallytrackedobject | false | null | 5.0.0.0 | false | false | true | true | false |
| 60 | subscriptionstatisticsoffline | false | null | 8.0.0.0 | false | false | false | true | false |
| 61 | subscriptionstatisticsoutlook | false | null | 8.0.0.0 | false | false | false | true | false |
| 62 | subscriptionsyncentryoffline | false | null | 8.0.0.0 | false | false | false | true | false |
| 63 | subscriptionsyncentryoutlook | false | null | 8.0.0.0 | false | false | false | true | false |
| 64 | syncerror | false | null | 8.1.0.0 | false | false | false | true | true |
| 65 | systemuserlicenses | false | null | 5.0.0.0 | false | false | true | true | false |
| 66 | teamtemplate | false | null | 6.0.0.0 | false | false | false | true | false |
| 67 | timestampdatemapping | false | null | 7.1.0.0 | false | false | false | true | false |
| 68 | timezonedefinition | false | null | 5.0.0.0 | false | false | false | true | false |
| 69 | timezonelocalizedname | false | null | 5.0.0.0 | false | false | false | true | false |
| 70 | timezonerule | false | null | 5.0.0.0 | false | false | false | true | false |
| 71 | tracelog | false | null | 6.0.0.0 | false | false | false | true | true |
| 72 | transformationmapping | false | null | 5.0.0.0 | false | false | false | true | false |
| 73 | transformationparametermapping | false | null | 5.0.0.0 | false | false | false | true | false |
| 74 | userform | false | null | 5.0.0.0 | false | false | false | true | false |
| 75 | usermapping | false | null | 7.1.0.0 | false | false | false | true | false |
| 76 | userqueryvisualization | false | null | 5.0.0.0 | false | false | false | true | false |
| 77 | webwizard | false | null | 5.0.0.0 | false | false | false | true | false |

I would like to use some of these tables (aaduser, customcontrol, entity, attribute) in Power BI using [Dataverse connector](https://docs.microsoft.com/en-us/power-query/connectors/dataverse). So, can you please document the unavailability of these system tables, or if there is a specific metadata rule for these to show up? I have only heard that audit is not available as it is a special table,but I cannot locate any official documentation about it. If virtual tables like aaduser will not be available in TDS and if that is a limitation, please document that as well. I tried searching, but I am unable to find it in docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ead09d9-3e51-04ce-dc6e-ac9bb59816ec
* Version Independent ID: 94d19f8d-3c5e-8ed9-53ee-4b6173f49144
* Content: [Use SQL to query data (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-sql-query.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rajyraman. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@rajyraman  Asking PM for clarification.

**Comment by phecke** [comment]
@rajyraman 
Here is text from the SQL [topic](https://docs.microsoft.com/power-apps/developer/data-platform/dataverse-sql-query#supported-operations-and-data-types):

_The following Dataverse datatypes are not supported with the SQL connection: binary, image, sql_variant, varbinary, virtual, HierarchyId, managedproperty, file, xml, partylist, timestamp, choices. In addition, tables types '**virtual**' and '**audit**' are not supported at this time._

So any tables that are virtual in your table list (above) are not supported.

@RichdiMSFT Want to add anything else?

[Get started with virtual tables (entities)](https://docs.microsoft.com/power-apps/developer/data-platform/virtual-entities/get-started-ve)

**Comment by phecke** [comment]
@rajyraman That is all I have to provide on this subject. I did let the PM know.
