### ISSUE TITLE
Deprecating weak cryptographic standards (TLS 1.0 and 1.1) in

#Azure DevOps Services - Azure DevOps Blog

### ISSUE THREAD

**Issue by tmamb** [MicrosoftDocs/powerapps-docs#3633]
https://devblogs.microsoft.com/devops/deprecating-weak-cryptographic-standards-tls-1-0-and-1-1-in-azure-devops-services/

**Comment by Mattp123** [comment]
@tmamb - What Docs article is your issue related to? Please add a link to it in this issue.

**Comment by phecke** [comment]
@tmamb We respond to Power Apps documentation questions and issues here. We do not handle Azure DevOps questions or issues unless it is related to Power Apps.
