### ISSUE TITLE
Static value is too long (the forms property cannot be more than 100 characters)

### ISSUE THREAD

**Issue by EricBos** [MicrosoftDocs/powerapps-docs#3637]
comment can be deleted
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385e47fe-5e1a-edb0-6932-408621881a80
* Version Independent ID: 0f3d2630-2e3e-e194-de9f-b4314e444694
* Content: [Edit table records directly from another table’s main form - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/form-component-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/form-component-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/form-component-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **mspilde**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @EricBos. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
Closing issue.
