### ISSUE TITLE
Needs reference for "the app form also has a setting of UTC or Local"

### ISSUE THREAD

**Issue by xairrick** [MicrosoftDocs/powerapps-docs#3638]
The document continually states "_the app form also has a setting of UTC or Local_" but there are no links to where to get more information about this.  And as far as I know (12 years of working with CRM/Dynamics 365 CE/Power Apps), I'm unaware of any form setting like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7267ae82-4d15-035f-fe93-cc66469d3b58
* Version Independent ID: 63c7e837-14dd-d199-9dc9-27cd81fd4050
* Content: [Behavior and format of the Date and Time column in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/behavior-format-date-time-field)
* Content Source: [powerapps-docs/maker/data-platform/behavior-format-date-time-field.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/behavior-format-date-time-field.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @xairrick. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@xairrick - Thanks for your feedback. Apparently this conflict occurs in canvas app forms not model-driven app forms. I've revised the article to state this.
Closing issue.
