### ISSUE TITLE
TOC partially disconnected

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#364]
Hello again,
The connection between this page and the TOC tree is incomplete.
The TOC entry for this page does exist: under "Canvas apps / Design and build an app"
(it is the last entry in the list, below "Make an app accessible")
However:
&gt; Clicking on the tree entry "Experimental and preview features" does navigate to this page,
&gt; But then, the location in the TOC tree is lost

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50ea9a7f-3003-294c-dd52-40d4a14ed206
* Version Independent ID: 86ece656-e8cb-c535-bb25-b22b5bee5237
* Content: [Understand preview and experimental features - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-experimental)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-experimental.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-experimental.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @a-zaf!
