### ISSUE TITLE
Incorrect steps for accessing Setting > Features

### ISSUE THREAD

**Issue by aprilspeight** [MicrosoftDocs/powerapps-docs#3640]
In the section **Enable the Power Apps component framework feature**, it states that after you select the environment, to then select **Feature** on the **Products** tab. The current UI does not reflect this. Instead, I followed the following to access **Features**.

1. Sign in to PowerApps
2. Select **Settings** and then select **Admin Center**
3. On the left plane, select **Environments**
4. Click the triple dots next to the environment where you want to enable this feature and select **Settings**
5. On the **Settings** page, expand the **Product** category and select **Features**
6. From the list of available features, turn on **Power Apps component framework for canvas apps**, and then select **Save**

Sharing in case someone is available to update the docs. The current image on the page is also outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8124234-fccb-85af-9ee8-13729326c727
* Version Independent ID: d53c2fc1-dd63-eee4-26a7-22715f27b943
* Content: [Code components for canvas apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/component-framework/component-framework-for-canvas-apps#enable-the-power-apps-component-framework-feature)
* Content Source: [powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @aprilspeight. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
As discussed, the docs are correct.
