### ISSUE TITLE
Inaccurate and misleading description regarding sharing a model-driven app

### ISSUE THREAD

**Issue by SkippingAdi** [MicrosoftDocs/powerapps-docs#3641]
The description, regarding sharing a model-driven app, is inaccurate and misleading. The article does not distinguish precisely enough between model-driven app and canvas app. 
For sharing model-driven apps, only the predefined security roles Basic User, System Customizer, and System Administrator are available. Custom roles cannot be selected. If they are, the article is not clear about this either. In this case, how must a custom security role be configured so that it can be used to share a model-driven app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4549b49b-30e8-c879-39a4-dab18142c213
* Version Independent ID: 8a4a64ea-979f-c4e2-94f0-dd7311b660a4
* Content: [Share a model-driven app using Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/share-model-driven-app)
* Content Source: [powerapps-docs/maker/model-driven-apps/share-model-driven-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/share-model-driven-app.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SkippingAdi. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@SkippingAdi - Most security roles can be assigned to a model-driven app including custom roles. Both the pet schedulers and copy of basic user are custom security roles that can be assigned to the model-driven app in this screenshot. Closing issue.
![image](https://user-images.githubusercontent.com/21203819/200697702-74eef466-4070-4fd0-a9e9-792e05a41e02.png)
