### ISSUE TITLE
Associated dynamics crm table rows through API Many-Many Missing PATCH Request

### ISSUE THREAD

**Issue by pk5280** [MicrosoftDocs/powerapps-docs#3643]
**Taken from powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md**
I noticed there is information of how to POST and DELETE but no PATCH or Update Request. Was this intentionally left out because it is not a capability?

---

The following example shows how to add a <xref:Microsoft.Dynamics.CRM.role?text=role> record to the <xref:Microsoft.Dynamics.CRM.systemuser?text=systemuser> `systemuserroles_association` collection which is a many-to-many relationship.

**Request**

```http
POST [Organization Uri]/api/data/v9.2/systemusers(34dcbaf5-f718-ed11-b83e-00224837179f)/systemuserroles_association/$ref HTTP/1.1
OData-MaxVersion: 4.0
OData-Version: 4.0
If-None-Match: null
Accept: application/json

{
  "@odata.id": "[Organization URI]/api/data/v9.2/roles(886b280c-6396-4d56-a0a3-2c1b0a50ceb0)"
}
```

**Response**

```http
HTTP/1.1 204 NoContent
OData-Version: 4.0
```
---

## \*Inserted\* Update a record from a collection
**Request**

```http
UPDATE [Organization Uri]/api/data/v9.2/... HTTP/1.1
```
---
## Remove a record from a collection

The following example shows how to remove a <xref:Microsoft.Dynamics.CRM.contact?text=contact> record to the <xref:Microsoft.Dynamics.CRM.account?text=account> `contact_customer_accounts` collection where the contact `contactid` value is `cf9eaaef-f718-ed11-b83e-00224837179f`.

**Request**

```http
DELETE [Organization Uri]/api/data/v9.2/accounts(ce9eaaef-f718-ed11-b83e-00224837179f)/contact_customer_accounts(cf9eaaef-f718-ed11-b83e-00224837179f)/$ref HTTP/1.1
OData-MaxVersion: 4.0
OData-Version: 4.0
If-None-Match: null
Accept: application/json
```

**Response**

```http
HTTP/1.1 204 NoContent
OData-Version: 4.0
```

The following also works:

**Request**

```http
DELETE [Organization Uri]/api/data/v9.2/accounts(ce9eaaef-f718-ed11-b83e-00224837179f)/contact_customer_accounts/$ref?$id=[Organization URI]/api/data/v9.2/contacts(cf9eaaef-f718-ed11-b83e-00224837179f) HTTP/1.1
OData-MaxVersion: 4.0
OData-Version: 4.0
If-None-Match: null
Accept: application/json
```

**Response**

```http
HTTP/1.1 204 NoContent
OData-Version: 4.0
```

<!-- 

The code snippet in the following section doesn't work, so removing this section until the correct request can be added.

<a name="bkmk_Associaterowsonupdate_multi"></a>

## Associate table rows on update using collection-valued navigation property

The following example shows how to associate multiple existing [ActivityParty](../reference/entities/activityparty.md) with an [Email](../reference/entities/email.md) using collection-valued navigation property `email_activity_parties`.

> [!NOTE]
> Associating multiple tables with a table on update is a special scenario that is possible only with <xref:Microsoft.Dynamics.CRM.activityparty?text=activityparty EntityType>.

**Request**

```HTTP
PUT [Organization URI]/api/data/v9.0/emails(2479d20d-3a39-e711-8145-e0071b6a2001)/email_activity_parties
Content-Type: application/json  
Accept: application/json  
OData-MaxVersion: 4.0  
OData-Version: 4.0

{
   "value": [
      {
         "partyid_contact@odata.bind":"contacts(a30d4045-fc46-e711-8115-e0071b66df51)",
         "participationtypemask":3
         
      },
      {
         "partyid_contact@odata.bind":"contacts(1dcdda07-3a39-e711-8145-e0071b6a2001)",
         "participationtypemask":2
         
      }
      ]
}
```

**Response**

```HTTP
HTTP/1.1 204 No Content  
OData-Version: 4.0 
``` -->

**Comment by JimDaly** [comment]
@pk5280 
As mentioned in [Using collection-valued navigation properties](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/associate-disassociate-entities-using-web-api#using-collection-valued-navigation-properties), 

> With OData, both sides of a many-to-many relationship will have collection-valued navigation properties. For one-to-many and many-to-one relationships, the table one the 'One' side will have a collection-valued navigation property. There is no difference how you work with any of these types of relationships while using collection-valued navigation properties. This section will describe how to work with collection-valued navigation properties with any type of relationship.

When working with existing records, you can add (POST) or remove (DELETE) items from the collection. With the version of OData that we are using, there is currently no capability to perform multiple operations against a collection.

However, when you create a record, you can associate existing records to the record you are creating, including those related through a collection-valued navigation property using _deep insert_. See [Associate table rows on create](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-entity-web-api#associate-table-rows-on-create) 

The example we have here is for a 1:N relationship `Account_Tasks`. But in theory this should work for a N:N relationship as well. I've not tried it. But only or the create operation.

Does this address your question?

**Comment by JimDaly** [comment]
closing this since it isn't clear what is actionable.
