### ISSUE TITLE
Screen shots and steps need updating

### ISSUE THREAD

**Issue by InformDyn365** [MicrosoftDocs/powerapps-docs#3646]
Screen shots and steps on this page need to be updated to reflect the changes in the latest make.powerapps.com tool. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd626b7-e922-eecd-983c-3823afff4e04
* Version Independent ID: 376d0fc1-294a-660a-ea09-7de12f6dbe18
* Content: [Tutorial: Write your first client script in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script?tabs=unified-interface%2Cunified-add-web-resource#step-2-add-your-javascript-code-in-a-script-web-resource)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @InformDyn365. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@InformDyn365 
Thanks for your feedback.
I've created a workitem to review this topic.
