### ISSUE TITLE
erreur dans le descriptif one to many

### ISSUE THREAD

**Issue by Thibaut303** [MicrosoftDocs/powerapps-docs#3647]
[Tapez vos commentaires ici]
Bonjour Microsoft, 
dans le descriptif one to many ( début de la page),
Vous écrivez:
Une-à-plusieurs – Dans ce type de relation, chaque ligne dans la table B peut correspondre à plus d'une ligne dans la table B, mais chaque ligne dans la table B peut correspondre à une seule ligne dans la table B. Par exemple, une classe a une salle de classe unique.
Or c'est
Une-à-plusieurs – Dans ce type de relation, chaque ligne dans la table A peut correspondre à plus d'une ligne dans la table B, mais chaque ligne dans la table B peut correspondre à une seule ligne dans la table A. Par exemple, une classe a une salle de classe unique.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des défis GitHub.*

* ID: 54ae0d11-d8f2-be75-a4a2-137f528308c0
* Version Independent ID: 212142bb-4e2a-ee94-66f3-880ae676a45c
* Content: [Créer une relation entre des tables en utilisant une colonne de recherche - Power Apps](https://docs.microsoft.com/fr-fr/power-apps/maker/data-platform/data-platform-entity-lookup)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-entity-lookup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-entity-lookup.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Thibaut303. This issue has been assigned to the doc author for review.

**Comment by Bernadette2022** [comment]
Investigating feedback

**Comment by Bernadette2022** [comment]
The feedback has been addressed

**Comment by v-aangie** [comment]
Localization updated by Bernadette Pinpin.
