### ISSUE TITLE
Article Title Misleading

### ISSUE THREAD

**Issue by galactic-plane** [MicrosoftDocs/powerapps-docs#3648]
I never comment on this type of stuff, but the article title had my hopes up until I read the article and realized this wasn't setting the default view for the model-driven app.  I have two model-driven apps that share the same table and its in the sitemap for each app, and I wanted a different default view for each app, but that's not possible.  The title should be "Specify a Dataverse table default view."

Ref: https://experience.dynamics.com/ideas/idea/?ideaid=74bf3b2e-bc7e-ea11-99e5-0003ff68be05

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b14b6f0f-9034-aacc-085b-3e90593967a9
* Version Independent ID: 52f7a3f7-5c23-aaa4-39fe-3fc3926d8f88
* Content: [Specify a model-driven app default view in Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/specify-default-views)
* Content Source: [powerapps-docs/maker/model-driven-apps/specify-default-views.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/specify-default-views.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @galactic-plane. This issue has been assigned to the doc author for review.

**Comment by galactic-plane** [comment]
Ok, I was able to figure out how to do this in the new edit model driven application experience.  You click pages, add a table based view and form and then you can select the view and explicitly add the view you want the model driven application to use.  If no views have been explicitly selected, all views will be available by default.

Maybe this approach can be added to the article.

**Comment by Mattp123** [comment]
@galactic-plane - Thanks for your feedback. The article has been updated to both change the title and also to add a link for the method to manage views via the model-driven app designer. Closing issue.
