### ISSUE TITLE
Broken link in CDS OAuth doc

### ISSUE THREAD

**Issue by navzam** [MicrosoftDocs/powerapps-docs#365]
The "Connect as an app" section contains this link to a non-existent page: [Create or configure a custom security role](https://docs.microsoft.com/power-platform/admin/database-security.md#create-or-configure-a-custom-security-role)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62419bb8-985c-cb11-ac8d-2d018868c2a6
* Version Independent ID: db669ed7-d87b-c359-f5fb-3f2f1052281d
* Content: [Use OAuth with Common Data Service (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth#connect-as-an-app)
* Content Source: [powerapps-docs/developer/common-data-service/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/authenticate-oauth.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
@phecke Can you please look into this issue?

**Comment by phecke** [comment]
@navzam Thanks for the feedback. The broken link has been fixed and will be available after the documentation is published to the site.
