### ISSUE TITLE
Deceiving Title

### ISSUE THREAD

**Issue by Deb3000** [MicrosoftDocs/powerapps-docs#3650]
The title, Transform your InfoPath form to Power Apps is very deceiving. You cannot "Transform" your InfoPath form to Power Apps. You need to recreate it. InfoPath was very good at what it did. I agree the experience for mobile devices is lacking, but using Power Apps, is nowhere near being able to quickly build and deploy the same type of form. 
I have a dynamic InfoPath form that has been WONDERFUL for years, that I need to recreate in PowerApps. It would have been so much simpler to "Transform" it. But here I am spending hours that I don't have trying to recreate something that was great for what needed to be done, figuring out all the ins and outs of PowerApps. So disappointing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce87949-54e8-f4ed-5d49-e11758e582b8
* Version Independent ID: 31d52576-021f-cdcf-bb49-c1c5d7ed85b2
* Content: [Transform your InfoPath form to Power Apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/transform-infopath)
* Content Source: [powerapps-docs/maker/canvas-apps/transform-infopath.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/transform-infopath.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Deb3000. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This article explains the benefits of using Power Apps to achieve capabilities of InfoPath form conceptually and explains how an InfoPath form can be transformed into multiple apps. To share your product feedback and ideas for new features, please visit [Power Apps Ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
