### ISSUE TITLE
Dataverse to SQL pipeline error

### ISSUE THREAD

**Issue by GitSheva** [MicrosoftDocs/powerapps-docs#3651]
Hi,

this file:

https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-pipelines.md

in section 10 it has parameters for Container and Folder when configuring the Trigger

```
In the Trigger Run Parameter section, enter the below parameters, and then select OK.

    Container: @split(triggerBody().folderPath,'/')[0]
    Folder: @split(triggerBody().folderPath,'/')[1]

```

when we run the pipeline we got this error:

Operation on target LookupModelJson failed: ErrorCode=AdlsGen2OperationFailed,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=ADLS Gen2 operation failed for: 'filesystem' does not match expected pattern '^[$a-z0-9](?!.*--)[-a-z0-9]{1,61}[a-z0-9]$'.. Account: 'dverep00test02'. FileSystem: '@split(triggerBody().folderPath,''. Path: '')[0]/@split(triggerBody().folderPath,'/')[1]/model.json'..,Source=Microsoft.DataTransfer.ClientLibrary,''Type=Microsoft.Rest.ValidationException,Message='filesystem' does not match expected pattern '^[$a-z0-9](?!.*--)[-a-z0-9]{1,61}[a-z0-9]$'.,Source=Microsoft.DataTransfer.ClientLibrary,'

I tried to google this error everywhere for few days now and no luck

Please help. What is the problem? Do we have to setup these two parameters as document says and if so, what is the problem with the format?

We have followed this document 100% and re-created the pipeline several times. We've got the same result every time.

Thanks.

**Comment by GitSheva** [comment]
Hi, any updates on this documentation? I see that I'm not the only one following this documentation getting errors with the pipeline. Thanks.

**Comment by Mattp123** [comment]
@GitSheva - Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Microsoft Customer Support, go to: https://powerapps.microsoft.com/support/

Closing this issue.
