### ISSUE TITLE
Work with Microsoft.Xrm.Sdk.Data.Expressions

### ISSUE THREAD

**Issue by AndrewTheWild** [MicrosoftDocs/powerapps-docs#3652]
Hello guys, could you provide few examples , how we can use class FilterExpressionTransform for transforming FilterExpression or for other classes?

Thanks for attention!

**Comment by phecke** [comment]
@AndrewTheWild I have never used that API. What are you trying to do?

**Comment by AndrewTheWild** [comment]
@phecke  According to this article ,this library helps with transformation QuerryExpression. I am working with Virual Entity.
https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/custom-ve-data-providers.md

**Comment by rajyraman** [comment]
@AndrewTheWild - I have never used this library before, but I found a blog post that explains how to use this https://gaborg.dev/dataverse-virtual-entities-queryexpressions-to-linq-expressions/

**Comment by phecke** [comment]
@AndrewTheWild I can pass your request for documentation/code on to the PM.

**Comment by phecke** [comment]
@AndrewTheWild I sent an email to the PM including your request for sample code and the online article. If I do get any info on the API, I can work on getting it published.
