### ISSUE TITLE
Sample Path for Plugins no longer valid

### ISSUE THREAD

**Issue by Dedme** [MicrosoftDocs/powerapps-docs#3655]
[Enter feedback here]
Samples path is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6569655b-b25e-856d-de2d-20d48438024f
* Version Independent ID: 523e9955-043e-a219-8ee4-dc6c21b41d43
* Content: [Sample: Create a basic plug-in (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/basic-followup-plugin#what-this-sample-does)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/basic-followup-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/basic-followup-plugin.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Dedme. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@Dedme 
Thank you for your feedback. I've fixed this.
The link to the sample in the doc works. We changed the path from `master\cds\orgsvc\C#\FollowupPlugin` to `master\dataverse\orgsvc\C#\FollowupPlugin`
