### ISSUE TITLE
Entity Name & Grid name need modification but not highlighted

### ISSUE THREAD

**Issue by danosagi** [MicrosoftDocs/powerapps-docs#3658]
**Location="Mscrm.**SubGrid**.**contact**.MainTab.Management.Controls._children"**

Above "contact" & "SubGrid" need to be updated if on different entity or different control.  This should be highlighted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55cb1b78-70a4-a97a-c1d3-48ab8efd6c32
* Version Independent ID: cdd45300-f7e1-c515-92a5-d0c31aca3212
* Content: [Override the default open behavior of data rows in grids (model-driven apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/override-default-open-behavior-grids)
* Content Source: [powerapps-docs/developer/model-driven-apps/override-default-open-behavior-grids.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/override-default-open-behavior-grids.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @danosagi. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Added this to the note below the xml

```
     > 
     > This example is to change the button for a button for a subgrid on the accounts form that displays contact records in the subgrid. Therefore the `Location` is `Location="Mscrm.SubGrid.contact.MainTab.Management.Controls._children"`. You will need to change this to have this apply to a different button. 
```
