### ISSUE TITLE
Incorrect path-based imports for ChoiceGroup

### ISSUE THREAD

**Issue by rolf-stifter** [MicrosoftDocs/powerapps-docs#3659]
The path-based imports of the ChoiceGroup are not correct.

`import { ChoiceGroup } from "@fluentui/react/lib/components/ChoiceGroup/ChoiceGroup";
import { IChoiceGroupOption } from "@fluentui/react/lib/components/ChoiceGroup/ChoiceGroup.types";`

should be changed to

`import { ChoiceGroup } from '@fluentui/react/lib/ChoiceGroup';
import { IChoiceGroupOption } from '@fluentui/react/lib/components/ChoiceGroup/ChoiceGroup.types';`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5338bf6-f6c2-fcf9-394f-e30871437de3
* Version Independent ID: 03fed979-b86f-d08b-d0ee-3b83b39c0966
* Content: [Create a model-driven app field component in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/tutorial-create-model-driven-field-component)
* Content Source: [powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rolf-stifter. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@rolf-stifter 
Thanks for you feedback.

Notes:
- This applies to the code in the section titled [Choices picker Fluent UI React component](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/tutorial-create-model-driven-field-component#choices-picker-fluent-ui-react-component)
- This Tutorial points to this sample [PowerApps-Samples/component-framework/ChoicesPickerControl/ChoicesPicker/ChoicesPickerComponent.tsx](https://github.com/microsoft/PowerApps-Samples/blob/master/component-framework/ChoicesPickerControl/ChoicesPicker/ChoicesPickerComponent.tsx) which uses yet a different way:

   ```
   import { ChoiceGroup, IChoiceGroupOption } from '@fluentui/react/lib/ChoiceGroup';
   ```

So, the whole tutorial should be reviewed to make sure it is in sync with the sample.

**Comment by JimDaly** [comment]
fixed.
