### ISSUE TITLE
Minor correction

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#366]
Greetings,
This is fairly obvious.

In "Use formulas for dynamic layout",
in the last table ("Relationship between C and D" [...])
in this specific row: "C positioned to the right of D with a gap of N"

&gt;&gt; The formula should be:  D.X + D.Width + N

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @a-zaf!
