### ISSUE TITLE
Documented Roles alone may not be sufficient - CE license needed to renew portal authentication key

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#3662]
Customer feedback:

It was only possible to renew the portal authentication key after giving the user a CRM / CE license.

If the license is a requirement, this should also be documented here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff0331e6-6c2b-4728-4c3b-3e141c285dc7
* Version Independent ID: 936bdd2f-3b1e-45d9-ed1a-c2c13e45ba46
* Content: [Roles required for portal administration - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/admin/portal-admin-roles)
* Content Source: [powerapps-docs/maker/portals/admin/portal-admin-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/portal-admin-roles.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CarstenMS. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thanks for your feedback. There is no licensing requirement for an administrator to renew the portal authentication key. It might be possible there may be some unique circumstances/custom policies where an administrator does not have automatic access to Microsoft Dataverse and is blocked from renewing the portal authentication key unless a license is assigned as a workaround.
