### ISSUE TITLE
Portals Lifecycle Document Production vs Sandbox Environment?

### ISSUE THREAD

**Issue by rentianxiang** [MicrosoftDocs/powerapps-docs#3663]
Document reference:  https://learn.microsoft.com/en-us/power-apps/maker/portals/admin/portal-lifecycle

Hi team, in this document, the highlighted sentence below creates confusion to me and I need clarifications regarding it.

**When converting a portal from trial to production, you must ensure that the environment is also a production environment.**

From the testing, not only production type environment can convert portal from trial to production, but also in sandbox type environment.
Could you please clarify what is the "production environment" in this sentence? is this doc needs to be upgraded?
Environment definition document: https://learn.microsoft.com/en-us/power-platform/admin/environments-overview#types-of-environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7444d166-6678-7ecc-2c33-4c54d4d67ac3
* Version Independent ID: a815c5f8-3ab4-d30a-5098-0d865947bdbb
* Content: [Power Apps portals lifecycle - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/admin/portal-lifecycle)
* Content Source: [powerapps-docs/maker/portals/admin/portal-lifecycle.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/portal-lifecycle.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rentianxiang. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
You can convert a trial to production website on a sandbox or production Power Platform environment.
