### ISSUE TITLE
Please clarify what exact role is needed - we don't have a Portal Administrator one, and portal owner can't access

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#3665]
regarding
"You need to be a portal administrator to enable Content Delivery Network."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a40721fb-181c-12a7-4db6-196ed6e30290
* Version Independent ID: a40721fb-181c-12a7-4db6-196ed6e30290
* Content: [Configure a site with Content Delivery Network (preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/configure-cdn)
* Content Source: [powerapps-docs/maker/portals/configure/configure-cdn.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-cdn.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @nageshbhat-msft
* Microsoft Alias: **nabha**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CarstenMS. This issue has been assigned to the doc author for review.

**Comment by ProfessorKendrick** [comment]
@CarstenMS, thank you for raising this issue.  The content has been updated and it will be LIVE shortly.
