### ISSUE TITLE
Managing security for notifications issue

### ISSUE THREAD

**Issue by anasufovic** [MicrosoftDocs/powerapps-docs#3668]
For the section Managing security for notifications

It says "Basic: Read privilege on the app notification table." This also should say delete, because when a user presses the X button on an individual notification it tries to delete it from the system. This should also be updated in the other rows in this table as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f495f03e-28c9-0ebb-ef03-72e16b267b3a
* Version Independent ID: a9dcec59-8b72-966e-fa53-f4b2e42d325e
* Content: [Send in-app notifications within model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi#managing-security-for-notifications)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @anasufovic. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Looks like we need another row in the table here https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi#managing-security-for-notifications about deleting notifications.

**Comment by JimDaly** [comment]
This has been addressed in [Managing security for notifications](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi#managing-security-for-notifications)
