### ISSUE TITLE
Information of maximum size of dataverse is not correct in Japanese docs

### ISSUE THREAD

**Issue by kosukehara** [MicrosoftDocs/powerapps-docs#3669]
[フィードバックをこちらに入力してください]
In the Japanese Docs, the maximum size of dataverse is mentioned as "4 GB or more", which totally differs from the information 
in the English docs. (English docs is mentioned as "4TB or more")
Please kindly correct the Japanese information.

https://learn.microsoft.com/ja-jp/power-apps/teams/data-platform-compare#environments

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f16e0d50-176d-2c1c-7821-a806efd079e3
* Version Independent ID: d8dc6656-383d-6f1e-8e47-350e4c206d7c
* Content: [Dataverse for Teams vs Dataverse - Power Apps](https://learn.microsoft.com/ja-jp/power-apps/teams/data-platform-compare#environments)
* Content Source: [powerapps-docs/teams/data-platform-compare.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/data-platform-compare.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @Mattp123
* Microsoft Alias: **olegov**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kosukehara. This issue has been assigned to the doc author for review.

**Comment by Dealgan12** [comment]
@Bernadette2022 can you follow up with the supplier on this. It looks to be a typo in Japanese. The other languages look to have it correct.

**Comment by Bernadette2022** [comment]
The feedback is shared with localization supplier to resolve

**Comment by Mattp123** [comment]
@kosukehara - Thank you for helping improve the documentation. I believe this has been fixed in the article. Closing issue.
