### ISSUE TITLE
Tiny adjustment [SharePoint list form]

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#367]
Hello again,
This is pretty futile (sorry to bother for so little)

"Set conditional formatting", Step 2, should be: "Set the Visible property [...] "
(instead of "Visibility")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @a-zaf!
