### ISSUE TITLE
Is this page valid?

### ISSUE THREAD

**Issue by anskanth** [MicrosoftDocs/powerapps-docs#3670]
Is this page still valid, now that component fields are not part of the UCI ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 311625ab-808d-b022-28c4-303f52511e8b
* Version Independent ID: c75c36f4-17b2-f75e-d4a9-708cfc007836
* Content: [Composite columns in model-driven apps in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/composite-attributes)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/composite-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/composite-attributes.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @anskanth. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@anskanth 
Can you elaborate a bit more? I'm not clear on what 'component fields' are.
Is it related to anything returned in these search results? [Search documentation for "component fields"](https://learn.microsoft.com/en-us/search/?scope=Power%20Apps&terms=%22component%20fields%22)

**Comment by anskanth** [comment]
Sorry, did I mention component fields? My bad then, I mean to composit
fields. In the new UCI world, there won't be any composite field (like
showing it as a one field and pop-up box to edit the field values), right?

Clients are looking into this article and are under impression that
something wrong with their setup causing the first name and last name are
not showing as one.

Thanks
-Srikanth

**Comment by JimDaly** [comment]
@anskanth 
No worries. I figure out what you meant.

I'm waiting for some input from @HemantGaur or @adrianorth  about what should change.

**Comment by JimDaly** [comment]
Waiting for response from @chmoncay or @miglisic

**Comment by chmoncay** [comment]
Hi there, this documentation only applies to Web Client.  These composite controls are no longer available.

**Comment by JimDaly** [comment]
Will remove this article since it isn't valid anymore.

**Comment by JimDaly** [comment]
Article was removed and redirected to legacy page: https://learn.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/dn481581(v=crm.8)
