### ISSUE TITLE
addOnPostSave in wrong hierarchy

### ISSUE THREAD

**Issue by Kunter-Bunt** [MicrosoftDocs/powerapps-docs#3675]
addOnPostSave is entered under Controls, but based on its namespace `formContext.data.entity.addOnPostSave(myFunction);` it belongs to formContext.data.entity right along the `formContext.data.entity.addOnSave(myFunction);` function.
addOnPostSave:
![image](https://user-images.githubusercontent.com/9168648/191689784-bb796e27-50b4-4ecf-a498-1fa6233e4d0c.png)
addOnSave:
![image](https://user-images.githubusercontent.com/9168648/191690219-76882354-1ee2-4258-ad89-faf145eed21f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b18afb70-3a3c-1fc8-7adf-27c430c6001a
* Version Independent ID: 8eaae86e-6f4b-15db-44d8-1b0b3a9bb4cd
* Content: [addOnPostSave (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/addonpostsave)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOnPostSave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOnPostSave.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Kunter-Bunt. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@Kunter-Bunt 
This makes perfect sense to me.
I created a workitem to change this.

2932135
