### ISSUE TITLE
407 Error when using who am I function

### ISSUE THREAD

**Issue by ElijahMansur** [MicrosoftDocs/powerapps-docs#3676]
Hello, I was testing out this link: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/use-postman-web-api. My goal is to use the REST API for Dataverse to be able to update and manage tables. Whenever I make a WhoAmI call in postman, I get a 407 error. The error is as follows
<img width="872" alt="image" src="https://user-images.githubusercontent.com/76127050/191767055-718f6ea2-97a3-4878-bbf8-8757ce87eec7.png">

I configured postman correctly and recieved a bearer token: 
![image](https://user-images.githubusercontent.com/76127050/191767244-f411de3b-d789-4c09-bd0a-527559a87ff4.png)

<img width="501" alt="image" src="https://user-images.githubusercontent.com/76127050/191767353-6a82e255-a0b2-4e96-9d55-9a2ecc2a17b9.png">

I believe I followed the tutorial for the environment correctly. What might this bug be? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Set up a Postman environment (Microsoft Dataverse for Apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ElijahMansur. This issue has been assigned to the doc author for review.

**Comment by ElijahMansur** [comment]
@JimDaly the stack exchange didn't work when I tried it. Maybe my computer has a network restriction that causes this error? I'm not entirely sure. What else should I check?

**Comment by JimDaly** [comment]
You should be able to send the GET request via your browser and it should work. Have you tried that?

I'm not a network security expert, but the error seems to be coming from a proxy server managed by honda.com. Is that your domain? You may want to check with your network administrator to understand if this is intentionally added to control access.

**Comment by ElijahMansur** [comment]
Yeah, when I try using the generic get request by using the browser, I get this window.

**Comment by JimDaly** [comment]
@ElijahMansur 
I'm going to assume that this works on your personal network like #3678
