### ISSUE TITLE
'svc.CurrentAccessToken' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by ElijahMansur** [MicrosoftDocs/powerapps-docs#3678]
I am following the tutorial at the link https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/quick-start-org-service-console-app. 

I am trying to use the WhoAmI function to get my userId following the tutorial. I found a null reference error at line 37 when I ran the code with the credentials so I debugged the program and found the below error for the svc vairable of type CrmServiceClient(conn). As you can see, there is no current access token injected into svc. To replicate my issue, follow the tutorial and put in your credentials and see what happens. I do not know if the error is repeatable. 

![image](https://user-images.githubusercontent.com/76127050/191779173-c75bb727-15fb-400a-93c9-f766fdf3dc27.png)

Do I need to add an access token to conn? 

Thank you for the help!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8916bbc-6834-44e1-1354-92ba60eacd0c
* Version Independent ID: ce53ff38-bf6a-9659-5834-aca6a7446cdd
* Content: [Quickstart: Organization service sample (C#) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/quick-start-org-service-console-app)
* Content Source: [powerapps-docs/developer/data-platform/org-service/quick-start-org-service-console-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/quick-start-org-service-console-app.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ElijahMansur. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@ElijahMansur 
Thanks for reporting this. I can't help but wonder if this is somehow connected to the issue you experienced using Postman #3676 

That issue seems to be related to network proxy configuration and I hope you can address it by changing settings in Postman. Please let us know.

But you don't have the same settings with CrmServiceClient.

@phecke  I know we have content to configure tracing for Xrm Tooling here: [Configure tracing for XRM tooling](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/xrm-tooling/configure-tracing-xrm-tooling)

Perhaps some troubleshooting content could be added here to emit more detailed logs to determine the source of the issue?

@ElijahMansur 
If you edit the App.config file in your project and add this to the `<configuration>` node:

```xml
<system.diagnostics>
		<trace autoflush="true" />
		<sources>
			<source name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient"
					switchName="Microsoft.Xrm.Tooling.Connector.CrmServiceClient"
					switchType="System.Diagnostics.SourceSwitch">
				<listeners>
					<add name="console"
						 type="System.Diagnostics.DefaultTraceListener" />
					<remove name="Default"/>
					<add name ="fileListener"/>
				</listeners>
			</source>
		</sources>
		<switches>
	<!--   
            Possible values for switches: Off, Error, Warning, Info, Verbose  
                Verbose:    includes Error, Warning, Info, Trace levels  
                Info:       includes Error, Warning, Info levels  
                Warning:    includes Error, Warning levels  
                Error:      includes Error level  
        -->
			<add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient"
				 value="Verbose" />

		</switches>
		<sharedListeners>
			<add name="fileListener"
				 type="System.Diagnostics.TextWriterTraceListener"
				 initializeData="XRMToolingLogs.log"/>
			<add name="eventLogListener"
				 type="System.Diagnostics.EventLogTraceListener"
				 initializeData="XRMTooling" />
		</sharedListeners>
	</system.diagnostics>
```

Then try again. When successful, the Output window of Visual Studio you should see logs like this:

```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Initialize CRM connection Started - AuthType: OAuth
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Direct Login Process Started
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Attempting to Connect to Uri [Organization URI]/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoveryServer indicated organization service location = [Organization URI]/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Organization Service URI is = [Organization URI]/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : ConnectAndInitCrmOrgService - Initializing Organization Service Object
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : ConnectAndInitCrmOrgService - Requesting connection to Organization with CRM Version: No organization data available
'NetFrameworkTestProject.exe' (CLR v4.0.30319: NetFrameworkTestProject.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : AuthenticateService - found authority with name https://login.microsoftonline.com/[Tenant Id]/oauth2/authorize
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : AuthenticateService - found resource with name [Organization URI]/
'NetFrameworkTestProject.exe' (CLR v4.0.30319: NetFrameworkTestProject.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Security\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Security.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : ObtainAccessToken - CRED
'NetFrameworkTestProject.exe' (CLR v4.0.30319: NetFrameworkTestProject.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'NetFrameworkTestProject.exe' (CLR v4.0.30319: NetFrameworkTestProject.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualStudio.Diagnostics.ServiceModelSink\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Added WebClient Header Hooks to the Request object.
'NetFrameworkTestProject.exe' (CLR v4.0.30319: NetFrameworkTestProject.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : ConnectAndInitCrmOrgService - Proxy created, total elapsed time: 00:00:01.1104686
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Querying Organization Instance Details. Request ID: 98dff72a-7bcd-4a03-9b9b-fb831b3158b2
'NetFrameworkTestProject.exe' (CLR v4.0.30319: NetFrameworkTestProject.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Completed Querying Organization Instance Details, total duration: 00:00:00.7800119
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Completed Parsing Organization Instance Details
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Connected to User Organization (crmue version: 9.2.22083.172)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Direct Login Process Succeeded - duration 00:00:01.9107510
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Beginning Validation of CRM Connection. RequestID: 4f2a7fba-7cf7-441b-be4d-830f240e7d68
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Executed Command - WhoAmIRequest : RequestId=4f2a7fba-7cf7-441b-be4d-830f240e7d68 : total duration: 00:00:00.1550853
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Validation of CRM Connection Complete, total duration: 00:00:00.1574086
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : New Batch Manager Created, Max #of Batches:50000, Max #of RequestsPerBatch:5000
```

Except yours should include some detail about why it fails.

**Comment by ElijahMansur** [comment]
Okay, great! I did that and I get a lot of exceptions, one of which was a 407 exception. Here is what it says on the screen. I know I am using a company laptop for the company I work at. Are there any possibilities that a network restriction could cause the 407 issues? 


`'Dataverse Web API project.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\v0072973\source\repos\Dataverse Web API project\Dataverse Web API project\bin\Debug\Dataverse Web API project.exe'. Symbols loaded.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\Users\v0072973\source\repos\Dataverse Web API project\Dataverse Web API project\bin\Debug\Microsoft.Xrm.Tooling.Connector.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\Users\v0072973\source\repos\Dataverse Web API project\Dataverse Web API project\bin\Debug\Microsoft.Xrm.Sdk.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\Users\v0072973\source\repos\Dataverse Web API project\Dataverse Web API project\bin\Debug\Microsoft.Crm.Sdk.Proxy.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\Users\v0072973\source\repos\Dataverse Web API project\Dataverse Web API project\bin\Debug\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Initialize CRM connection Started - AuthType: OAuth
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Direct Login Process Started
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Attempting to Connect to Uri https://org040c6598.api.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoveryServer indicated organization service location = https://org040c6598.api.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Organization Service URI is = https://org040c6598.api.crm.dynamics.com/XRMServices/2011/Organization.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : ConnectAndInitCrmOrgService - Initializing Organization Service Object
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : ConnectAndInitCrmOrgService - Requesting connection to Organization with CRM Version: No organization data available
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Dataverse Web API project.exe' (CLR v4.0.30319: Dataverse Web API project.exe): Loaded 'C:\Users\v0072973\source\repos\Dataverse Web API project\Dataverse Web API project\bin\Debug\Microsoft.Xrm.Sdk.Deployment.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: mscorlib
Method	: ThrowIfExceptional
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: One or more errors occurred.
Stack Trace	: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateFromResourceUrlAsync(Uri targetServiceUrl)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetAuthorityFromTargetService(Uri targetServiceUrl, CrmLogEntry logSink)
======================================================================================================================
Inner Exception Level 1	: 
Source	: mscorlib
Method	: ThrowForNonSuccess
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: An error occurred while sending the request.
Stack Trace	: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlCommonAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlAsync>d__12.MoveNext()
======================================================================================================================
Inner Exception Level 2	: 
Source	: System
Method	: EndGetResponse
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: The remote server returned an error: (407) Proxy Authentication Required.
Stack Trace	: at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : ERROR REQUESTING Token FROM THE Authentication context - General ADAL Error
Source	: mscorlib
Method	: ThrowIfExceptional
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: One or more errors occurred.
Stack Trace	: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateFromResourceUrlAsync(Uri targetServiceUrl)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetAuthorityFromTargetService(Uri targetServiceUrl, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
======================================================================================================================
Inner Exception Level 1	: 
Source	: mscorlib
Method	: ThrowForNonSuccess
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: An error occurred while sending the request.
Stack Trace	: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlCommonAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlAsync>d__12.MoveNext()
======================================================================================================================
Inner Exception Level 2	: 
Source	: System
Method	: EndGetResponse
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: The remote server returned an error: (407) Proxy Authentication Required.
Stack Trace	: at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: mscorlib
Method	: ThrowIfExceptional
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: One or more errors occurred.
Stack Trace	: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateFromResourceUrlAsync(Uri targetServiceUrl)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetAuthorityFromTargetService(Uri targetServiceUrl, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
======================================================================================================================
Inner Exception Level 1	: 
Source	: mscorlib
Method	: ThrowForNonSuccess
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: An error occurred while sending the request.
Stack Trace	: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlCommonAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlAsync>d__12.MoveNext()
======================================================================================================================
Inner Exception Level 2	: 
Source	: System
Method	: EndGetResponse
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: The remote server returned an error: (407) Proxy Authentication Required.
Stack Trace	: at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to connect to CRM: An error occurred while sending the request.
Source	: mscorlib
Method	: ThrowIfExceptional
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: One or more errors occurred.
Stack Trace	: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateFromResourceUrlAsync(Uri targetServiceUrl)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetAuthorityFromTargetService(Uri targetServiceUrl, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ConnectAndInitCrmOrgService(OrganizationDetail orgdata, Boolean IsOnPrem, Uri homeRealmUri)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DoDirectLogin(Boolean IsOnPrem)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: mscorlib
Method	: ThrowForNonSuccess
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: An error occurred while sending the request.
Stack Trace	: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlCommonAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlAsync>d__12.MoveNext()
======================================================================================================================
Inner Exception Level 2	: 
Source	: System
Method	: EndGetResponse
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: The remote server returned an error: (407) Proxy Authentication Required.
Stack Trace	: at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 9/22/2022
Time	: 12:51:11 PM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

The thread 0x7a3c has exited with code 0 (0x0).
The thread 0x7734 has exited with code 0 (0x0).
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Execute Command - WhoAmI : Execute (WhoAmI) request to CRM from IOrganizationService : RequestID=c6a2a128-cbbc-4126-9717-8c6eae53843f 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : No retry attempted for Command WhoAmI
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : ************ NullReferenceException - WhoAmI : Execute (WhoAmI) request to CRM from IOrganizationService |=> Object reference not set to an instance of an object.
Source	: Microsoft.Xrm.Tooling.Connector
Method	: CrmCommand_Execute
Date	: 9/22/2022
Time	: 12:52:31 PM
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : [TerminalFailure] Failed to Execute Command - WhoAmI : RequestID=c6a2a128-cbbc-4126-9717-8c6eae53843f : Execute (WhoAmI) request to CRM from IOrganizationService duration=00:00:00.0096691 ExceptionMessage = Object reference not set to an instance of an object.
Source	: Microsoft.Xrm.Tooling.Connector
Method	: CrmCommand_Execute
Date	: 9/22/2022
Time	: 12:52:31 PM
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================

Exception thrown: 'System.NullReferenceException' in Microsoft.Xrm.Tooling.Connector.dll
Object reference not set to an instance of an object.`

**Comment by phecke** [comment]
@ElijahMansur Seems there is something wrong with your login credentials or endpoint URL. The WhoAmI sample is short and sweet showing minimum code. In general, it is better to check that svc.IsReady is true before executing message requests.

What URL are you using? https://org040c6598.api.crm.dynamics.com?

The error indicates that the call cannot connect/login to the service. Verify you are using the correct URL. You can find it in  make.powerapps.com for your environment under Settings > Developer resources.

(407) Proxy Authentication

You could also try removing the username and password parameters from the 'conn' string in the code to force the interactive login prompt to show. Then try to login there.

string conn = $@"
    Url = {url};
    AuthType = OAuth;
    AppId = 51f81489-12ee-4a9e-aaae-a2591f45987d;
    RedirectUri = app://58145B91-0C36-4500-8554-080854F2AC97;
    LoginPrompt=Auto;
    RequireNewInstance = True";

**Comment by phecke** [comment]
@ElijahMansur Try https://org040c6598.api.crm.dynamics.com/ for the URL.

**Comment by ElijahMansur** [comment]
Hello, I got it work. When I ran my computer on my personal network, the code ran with any issues. Thus, the bug isn't with this code but the network I was on before. Thank you so much for the help!
