### ISSUE TITLE
Please also add requirement to add Data Factory resource provider to subscription

### ISSUE THREAD

**Issue by ChrisAt2at** [MicrosoftDocs/powerapps-docs#3684]
The document states with the Prerequisites that the Microsoft.EventGrid provider needs to be registered, but when following the steps you get an error when publishing all items in the Synapse Analytics workspace that a certain client "does not have authorization to perform action 'Microsoft.EventGrid/eventSubscriptions/write'".
When looking at the documentation on https://learn.microsoft.com/en-us/azure/data-factory/how-to-create-event-trigger?tabs=data-factory there is an additional 'Important' note that "If you are using this feature in Azure Synapse Analytics, please ensure that your subscription is also registered with Data Factory resource provider, or otherwise you will get an error stating that the creation of an "Event Subscription" failed."
It would be great if all pre-reqs were listed at one place.

**Comment by phecke** [comment]
@ChrisAt2at Please provide a link to the documentation page you are talking about so that I can assigned the correct writer to assist.

**Comment by ChrisAt2at** [comment]
Hi @phecke,

Sorry, I thought that was automatically added.
The documentation where the pre-req is not mentioned is at https://learn.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-pipelines#use-the-solution-template-in-synapse-workspace

**Comment by JasonHQX** [comment]
Hi @ChrisAt2at 
Thanks for pointing this out: We have updated the doc accordingly: https://github.com/MicrosoftDocs/powerapps-docs-pr/pull/7186

**Comment by Mattp123** [comment]
Pull request merged. Closing issue.
