### ISSUE TITLE
Error message: Unable to persist the profile.

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3686]
I've installed the plugin profiler, started profiling and while executing the plugin, I got the exception "Unable to persist the profile".
The exception details didn't contain any specific details. The exeception was thrown while the profiled plugin was executed.

Any idea how this can be solved?

During the plugin execution, there is also a synchronous workflow starting and the plugin is triggered multiple times. Could this be an issue?

I've switched from "Persist to Entity" to "Exception". I get the expected exception and I can attach the debugger to the plugin registration tool. This way I can debug the first(?) execution. At least partially.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae2a5dc-346e-f0fc-f03a-07aed9fd37c4
* Version Independent ID: 2e757865-4955-8bde-7e1b-55c87a8c3ad3
* Content: [Tutorial: Debug a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/tutorial-debug-plug-in?tabs=prt)
* Content Source: [powerapps-docs/developer/data-platform/tutorial-debug-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tutorial-debug-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@darshSWL The profiler persists the profiling data to an entity row in Dataverse. Is the plug-in registered in an environment that has an associated database? I am asking because it is possible to create an environment without a database.

Also, are you profiling when logged into a system user account with a System Customizer role?

**Comment by darshSWL** [comment]
@phecke There is a database for this environment. I'm logged in with a user account which has the system administrator security role assigned. I think I'll open a support ticket about this next week.

I'm trying to debug a plugin which runs in a "create" pipeline with several other plugins. The plugin tries to retrieve a record, which was created in this pipeline earlier, but fails with with "record with id ... does not exist". Since I don't know how the plugin replay works, I guess the IOrganizationService communicates with the real environment and does not have any data the IOrganizationService exchanged with Dataverse while the plugin was executed?

**Comment by phecke** [comment]
@darshSWL The retrieve plug-in is registered to run after the core operation (stage 30), right?

**Comment by darshSWL** [comment]
@phecke Yes. It runs in stage 40.
The plugin has no problems to retrieve the record while it is executed in Dataverse. The problem with the missing record only pops up in the replay using the debugger.

**Comment by phecke** [comment]
@darshSWL Sorry I could not be of help, but Support is the way to go.
