### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/powerapps-docs#3688]
[Enter feedback here]

Under the heading, Get started with creating apps in Teams, there are two paragraphs that both start with:

"When you create an app in Teams with the Power Apps app for the first time, or ....."

Although the paragraphs are not identical, the content appears to be a duplicate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cad7c743-0979-ff80-f4c1-9b2dc5707efe
* Version Independent ID: 0fb8c02d-e6d4-c4fb-f04c-e7ebeeda0a2f
* Content: [Create apps in Microsoft Teams by using Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/teams/create-apps-overview)
* Content Source: [powerapps-docs/teams/create-apps-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/create-apps-overview.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @feridunkadir. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
We checked the content and it's not duplicate. Closing the issue.
