### ISSUE TITLE
Outdated link ?

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#369]
Hello again,

In section "Step 7: Run the app", at the end of the intro paragraph, it seems that the "Share your apps" link is outdated:
it is not leading to a specifically relevant page.
Maybe it should be updated to link to the following page?
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292984fb-ba15-c478-de19-e1b8976f35c0
* Version Independent ID: b94044cb-12a7-6926-fdc7-9b626ad7a6e1
* Content: [Create a canvas app to manage projects - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-scenario-build-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-build-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sharepoint-scenario-build-app.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is being updated, please allow some time to reflect the change.
