### ISSUE TITLE
Power Apps Studio modern command bar

### ISSUE THREAD

**Issue by Daisuke84** [MicrosoftDocs/powerapps-docs#3691]
A new modern command bar has been added in preview to Power Apps Studio, I want to continue to use the old command bar in the future, and I want you to keep the settings so that you can switch between them in the future.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 learn.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7dd6b9d7-4668-e08b-3796-2241351d80ff
* Version Independent ID: 7dd6b9d7-4668-e08b-3796-2241351d80ff
* Content: [Power Apps Studio を理解する - Power Apps](https://learn.microsoft.com/ja-jp/power-apps/maker/canvas-apps/power-apps-studio#modern-command-bar-preview)
* Content Source: [powerapps-docs/maker/canvas-apps/power-apps-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/power-apps-studio.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Daisuke84. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@Daisuke84 The modern command bar is on by default. The only way to turn it back on is through the settings in the canvas apps studio. 

I will pass your feedback to our product team. 

Thanks,
Mints
