### ISSUE TITLE
More recommendations regarding the OperationStatus?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3692]
The documention mentions the possibility to retry failed asynch operations. To do this, the InvalidPluginExecutionException should be thrown with the OperationStatus Retry.

I've never used the OperationStatus and I'm not sure what exactly the consequences and use-cases are.

Is the OperationStatus also usable for synchronous plugins?
Why should I throw an exception with OperationStatus Succeeded or Suspended? What are the consequences?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a26bcc37-d8d9-ee18-6c2e-0824aca609d5
* Version Independent ID: e2b6035c-4546-e079-dffc-db43115cbfd2
* Content: [Handle exceptions in a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/handle-exceptions#cancelling-an-operation)
* Content Source: [powerapps-docs/developer/data-platform/handle-exceptions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/handle-exceptions.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@darshSWL 

Thank you for your feedback.

The content you are asking about is this:

> ### Retry an asynchronous plug-in
> With an asynchronous plug-in step, you can re-try when a plug-in fails. This may be due to a network error or some other re-triable error calling an external resource.
> 
> To retry your plug-in, use the [InvalidPluginExecutionException(OperationStatus, Int32, String)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.invalidpluginexecutionexception.-ctor#microsoft-xrm-sdk-invalidpluginexecutionexception-ctor(microsoft-xrm-sdk-operationstatus-system-int32-system-string)) constructor using the [OperationStatus Enum](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.operationstatus) `Retry` member value.
> 
> When your plug-in throws this type of exception, the asynchronous service will attempt to run your plug-in four times. If it doesn't succeed within four attempts it will fail.

Your questions are:

> I've never used the OperationStatus and I'm not sure what exactly the consequences and use-cases are.

Use cases are calling an external resource. As stated, "...due to a network error or some other re-triable error". Perhaps you get throttled by the other service?

> Is the OperationStatus also usable for synchronous plugins?

No. As stated, this is for asynchronous plugins.

> Why should I throw an exception with OperationStatus Succeeded or Suspended? What are the consequences?

You shouldn't. As stated, to retry you must use the `Retry` value only.


This content is focused on what developers can do to handle exceptions in plug-ins. It provides the scenario and what options are available to developers.  We don't discuss invalid options, only the steps that people should take to re-try an asynchronous plug-in.

How do you feel this could be improved?

**Comment by darshSWL** [comment]
Since this page is about handling exceptions in plugins, I didn't realize that "retry an asynch plugin" is the _only_ scenario where this enum is actually useful (and supported?). I've never seen the OperationStatus used in any example or anywhere else in the documentation. Maybe this documentation exists and I didn't find it? I'm not thinking about the exception constructor or the enum documentation which only lists the possible values.

I've also seen that the Plugin Profiler plugin throws an InvalidPluginExecutionException with OperationStatus Suspended. Reading about the "retry an asynch plugin" scenario here and seeing the Plugin Profiler throwing with OperationStatus Suspended made me wonder, what else could be possible with this enum? Seems like nothing else should be done with it?

**Comment by JimDaly** [comment]
I'm not aware of any other use case for OperationStatus enum. It appears to be a sub-set of the [AsyncOperation.StatusCode](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/asyncoperation#BKMK_StatusCode) options that are valid while the operation is running.

Plug-in Profiler is taking the serialized execution context and allowing you to debug your code locally, simulating the runtime environment found in the sandbox. I can't say that the OperationStatus value included with the exception in that case matches exactly what would occur at runtime in the sandbox. Unless it is blocking you somehow, I wouldn't be too concerned about it.

We aren't trying to document everything, only things that are important. There are things which are interesting but not important. Inner workings of OperationStatus may be interesting to some, but unless it is directly related to helping you achieve a specific outcome, we probably will not document it. 

Does that make sense?

**Comment by darshSWL** [comment]
Yes, this makes sense.

We have an open support ticket about the Plug-In Profiler. I think I will ask the support team on that ticket why it throws the exception with "Suspended" (the plugin is not running async). Maybe that's the reason why the pipeline goes crazy after the exception.

I think I learned everything I wanted to know. Thanks a lot.
