### ISSUE TITLE
A function to call when the user cancels the lookup dialog or the operation fails.

### ISSUE THREAD

**Issue by sora1inr26** [MicrosoftDocs/powerapps-docs#3697]
[Enter feedback here]
`                    //define data for lookupOptions
                    var lookupOptions =
                    {
                        defaultEntityType: "msdyn_workorderservicetask",
                        entityTypes: ["msdyn_workorderservicetask"],
                        allowMultiSelect: false
                    };

                    // Get account records based on the lookup Options
                    Xrm.Utility.lookupObjects(lookupOptions).then(
                        function (success) {
                            console.log('success');
                            console.log(success);
                        },
                        function (error) {
                            console.log('fail');
                            console.log(error);
                        }
                    );`
I write the code like this , when i do the cancel operation,the console always output the 'success' result. The enviroment is Online Version of the CRM.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sora1inr26. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@sora1inr26

Issues in this repo are for the documentation.

I'm looking for what part of the documentation could be improved to help unblock you?

If you are looking for technical support, or want to report a bug, please contact technical support [Get Help + Support](https://learn.microsoft.com/en-us/power-platform/admin/get-help-support).

From what you have explained, you use the `lookupObjects` function to open a lookup control.

You mention:

> when i do the cancel operation

...but you don't mention how you do that.

Typically, operations that can be cancelled have a corresponding event, i.e. _OnSave_ where you can add an event handler to cancel the operation. I'm not familiar with any event like 'OnLookupOpen' that would allow you to cancel the operation you just initiated. The only events I see related to lookup controls are `OnLookupTagClick` or `PreSearch`, and I don't think they would cancel the operation to open the lookup dialog. See [Lookup control event](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events#lookup-control-event)

The only potentially actionable item I see in the documentation is that we could change the description of the **errorCallback**.

Today it is this:

> A function to call when you cancel the lookup control or the operation fails.

But if there is no way to cancel this lookup dialog, perhaps the description could be modified to remove mention of that option:

> A function to call when the operation fails.

Can you provide more information about how you are cancelling the operation?

**Comment by sora1inr26** [comment]
![image](https://user-images.githubusercontent.com/26737473/192923054-f8555ed8-9f30-44a2-a0fc-80135ad30dfc.png)

I clicked the cancel button ,then console shows the wrong result

**Comment by ranistar** [comment]
@sora1inr26  I think uploading the console log with screenshots would be more helpful.

**Comment by sora1inr26** [comment]
![1664438164852](https://user-images.githubusercontent.com/26737473/192974135-6be52c26-c1bd-4655-a225-01e4416c7ba8.png)
![1664438212293](https://user-images.githubusercontent.com/26737473/192974149-ba12e865-c7b1-43de-b61f-8d2fc5fd4c32.png)

These two pictures above is the situation 1 , I select 1 record and click the confirm button. The success object have value.

![1664438476728](https://user-images.githubusercontent.com/26737473/192975185-0ff99d4f-ac56-43b7-b4a9-be0317e3dd0c.jpg)
![1664438589543](https://user-images.githubusercontent.com/26737473/192975384-ec158ce1-a777-49e2-991e-84ff0524b088.png)
These two pictures above is the situation 2 , I didn't select any record and clicked the confirm button. The success object don't have any value.

![1664438864096](https://user-images.githubusercontent.com/26737473/192976410-e7f6aedf-1762-4908-873e-3bb46d929054.png)
![1664438899951](https://user-images.githubusercontent.com/26737473/192976524-a6b42ee7-caf0-4adc-9ce5-4754a1bb0c9b.png)
These two pictures above is the situation 3 ,  I just clicked the cancel button.  The success object also don't have any value.

My porblem is that i can't figure the difference between situation 2 and situation 3,because i want to do the clear data request when i do operations like situation 2 , and change any data  when i do operations like situation 3.

**Comment by JimDaly** [comment]
@sora1inr26 
Thanks for the explanation.

Based on the docs, this method provides the ability to open a lookup control.
User has options:
 - Select records using the lookup (situation 1 above).
    - In this case the **successCallback** should provide you with information about the selected record(s).
 - Select no records but click the confirm button (situation 2 above)
    - I'm not clear why the **Confirm** button would be enabled when no records are selected.   This seems like a UI bug to me. I think the **Cancel** button should be the only available option. But since they clicked **Confirm**, it is reasonable to consider this to be 'success' and that there is no data passed back. If I'm understanding you correctly, this might be a 'gotcha' worth documenting, but that doesn't seem to be your primary concern.
- Cancel the lookup (situation 3 above)
    - In this case, according to the documentation, the **errorCallback** should be invoked.
    - Seems like you are reporting that the **successCallback** is being called. Is this correct? 

Afraid I don't have the resources to troubleshoot with you. But it seems you ought to contact technical support to report the issue of the **successCallback** being invoked when the user cancels the operation. The documentation describes how it is supposed to behave. I will need confirmation from the dev team before I can change this description. I will make them aware of this issue, but if you seek a resolution, you should call technical support.

The only actionable item I see in this is perhaps we should change the description for the **errorCallback**
Today:

> A function to call when you cancel the lookup control or the operation fails.

I think it should be:

> A function to call when the user cancels the lookup dialog or the operation fails.

Am I understanding correctly?

**Comment by sora1inr26** [comment]
Thanks, your understand is right, i also think that select no records and shows the confirm buttom at the same time is wrong.I will contract technical team to report the issue.

**Comment by JimDaly** [comment]
Need to change the errorcallback description to 'A function to call when the user cancels the lookup dialog or the operation fails.'
