### ISSUE TITLE
What about unrated?

### ISSUE THREAD

**Issue by YahyaManasrah** [MicrosoftDocs/powerapps-docs#37]
I have added in CDS SupplierEntity a Whole Number (0 to 5) rating field, that works well but in the rating control, it shows 3 stars for Suppliers those unrated yet, while their numeric rating value is blank. It remains 3 stars even I set their numeric value 0. It starts working when I set their numeric value as 1. But 1 is a rating not unrated.

I think rating control needs to deal with unrated (0 numeric value) scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ce9f69-404e-ba75-154e-ac12a69194f0
* Version Independent ID: a03bcf39-f04e-3b15-0137-59270377501e
* Content: [Rating control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-rating)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-rating.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-rating.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
That's a good point, I agree with you.

Unfortunately this cannot be done today.  We are currently reimplementing this control and will look to introduce this feature.

**Comment by AFTOwen** [comment]
@YahyaManasrah Thanks for your feedback! Closing this issue.

cc: @fikaradz
