### ISSUE TITLE
Trivial edit

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#370]
Again, this is quite negligible and unimportant.

In "Step 2: Connect to a SharePoint list", first sentence:
"In this step, we'll connect to the Product Details SharePoint list."
&gt;&gt; should be "Project Details"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292984fb-ba15-c478-de19-e1b8976f35c0
* Version Independent ID: b94044cb-12a7-6926-fdc7-9b626ad7a6e1
* Content: [Create a canvas app to manage projects - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-scenario-build-app)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-build-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sharepoint-scenario-build-app.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by AFTOwen** [comment]
Fixed. Thanks, @a-zaf!
