### ISSUE TITLE
Power Apps Cards Tutorial

### ISSUE THREAD

**Issue by Diego1135** [MicrosoftDocs/powerapps-docs#3701]
Hello!
This comments are in reference to https://learn.microsoft.com/en-us/power-apps/cards/tutorials/simple-shopping-list
Following the instructions things didn't work for me as expected. If I do Collect(myGroceryList, theNewItem), I get an error that Text is not allowed. And it seems logical for me.
I used this instead: Collect(myGroceryList, {'Item': TheNewItem})
But before that, I have to write the default for the variable myGroceryList table, like this, in order for the Collect recognize the 'Item' column.
Default:
[
  {
    "Item": ""
  }
]
With that, the Collection was updated, but in order to show the list with new items I have to change the Text property with:
Text: ThisItem.Item

Doing all this I did the Card work as expected.

I hope I was doing right. 

Thank you.
Diego.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 223a0c37-a1f5-6bfe-1730-2b4d2a47a455
* Version Independent ID: 223a0c37-a1f5-6bfe-1730-2b4d2a47a455
* Content: [Create a shopping list card (Preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/cards/tutorials/simple-shopping-list)
* Content Source: [powerapps-docs/cards/tutorials/simple-shopping-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/cards/tutorials/simple-shopping-list.md)
* Service: **powerapps**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Diego1135. This issue has been assigned to the doc author for review.

**Comment by nyoung30** [comment]
Thanks for the additional info @Diego1135. 

To get the tutorial to work on my end I had to ensure that variable **Title** was also included. This is different from the variable Name. Code snippet below, see **title**.

"variables": {
    "myGroceryList": {
      "type": "array",
      "title": "myGroceryList",
      "description": "",
      "default": [
        {
          "Item": ""
        }
      ],
      "x-ms-cardapp": {
        "scope": "session"
      }
    }
  }

**Comment by iaanw** [comment]
We've updated the documentation with this information, thanks all.
