### ISSUE TITLE
Alternate Keys aren't supported in the Target of a Pre-Validation/Operation Plugin

### ISSUE THREAD

**Issue by daryllabar** [MicrosoftDocs/powerapps-docs#3703]
It should probably called out that attempting to set a lookup attribute to an EntityReference for the target in the Pre-Operation or Pre-Validation of a plugin is not supported.  It will error in the Pre-Validation, and create a reference to 00000000-0000-0000-0000-000000000000 in the Pre-Operation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd844db9-ff8f-0573-1596-bb31d6d4609a
* Version Independent ID: cd844db9-ff8f-0573-1596-bb31d6d4609a
* Content: [Use an alternate key to reference a record (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-alternate-key-reference-record?tabs=webapi)
* Content Source: [powerapps-docs/developer/data-platform/use-alternate-key-reference-record.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-alternate-key-reference-record.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @daryllabar. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@daryllabar 
This seems like issue that needs to be examined by the dev team.
I see you have opened a support case. Let's see how that gets resolved and whether we need to add a note to it in the docs.
Closing this.
