### ISSUE TITLE
Overview missing 7 in screenshot

### ISSUE THREAD

**Issue by VeeRochet** [MicrosoftDocs/powerapps-docs#3706]
In the overview section the 7. Fit to screen is not indicated on the screenshot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3e180de-c847-fdbf-8f42-818d2e1f3a5c
* Version Independent ID: 7b74f600-eee6-e337-a0e1-b8fc676fd001
* Content: [Overview of the model-driven app designer - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/app-designer-overview)
* Content Source: [powerapps-docs/maker/model-driven-apps/app-designer-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/app-designer-overview.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **emcoope**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VeeRochet. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@VeeRochet - Thank you for your feedback. The diagram in the article has been updated to include the number 7 fit to screen command.

Closing issue.
