### ISSUE TITLE
Can you specify if the SharePoint access will work for end users/customers outside the organization to upload/download from cases view when the portal is configured with the Azure Active Directory B2C provider 

### ISSUE THREAD

**Issue by vikramhn** [MicrosoftDocs/powerapps-docs#3707]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd70bb46-8651-365b-7a25-215b921f55b6
* Version Independent ID: f628a69a-04c8-901a-832f-b867aff68603
* Content: [Manage SharePoint documents - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/manage-sharepoint-documents?source=recommendations)
* Content Source: [powerapps-docs/maker/portals/manage-sharepoint-documents.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/manage-sharepoint-documents.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by vikramhn** [comment]
Can you specify if the SharePoint access will work for end users/customers outside the organization to upload/download from cases view when the portal is configured with the Azure Active Directory B2C program ?
https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/configure-azure-ad-b2c-provider

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vikramhn. This issue has been assigned to the doc author for review.

**Comment by vikramhn** [comment]
Any update on this?

**Comment by nickdoelman** [comment]
Thank you for your feedback! I am waiting on confirmation from our product team, but this should be a supported scenario (Power Pages SharePoint integration and using Azure B2C identity provider). If you are having issues, please open a support ticket at https://admin.powerplatform.microsoft.com/support

**Comment by nickdoelman** [comment]
I have confirmation. Irrespective of the auth provider the SharePoint functionality works as documented. Security is provided to users as per our documentation [here](https://learn.microsoft.com/power-apps/maker/portals/manage-sharepoint-documents#step-5-create-appropriate-table-permission-and-assign-it-to-the-appropriate-web-role). Closing this issue.
