### ISSUE TITLE
The source code of this Data-set page does not match the objective. Can someone please check?

### ISSUE THREAD

**Issue by MannyGrewal** [MicrosoftDocs/powerapps-docs#371]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4c9824-7fe7-269c-eae6-0d4ca3b8ecf1
* Version Independent ID: 73044005-f1a8-94ba-c746-5569943d9886
* Content: [DataSet Grid component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/data-set-grid-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/data-set-grid-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/data-set-grid-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@MannyGrewal Thanks for the feedback. We have updated the docs and pushed live. closing this issue
