### ISSUE TITLE
Document is misleading, showing deprecated controls as examples to follow. 

### ISSUE THREAD

**Issue by iozm** [MicrosoftDocs/powerapps-docs#3710]
Document needs to be updated to reflect actual active controls, the guide shows the usage of deprecated controls no longer available. We follow these steps believing they are up to date and end up wasting time and effort troubleshooting for something that has already been deprecated. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5435ffcb-2f82-7513-7ffc-d5ae6529512a
* Version Independent ID: 6e4f6d2a-0ed9-84c9-d680-1c1ddc732454
* Content: [Use controls for model-driven app data visualizations in Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/use-custom-controls-data-visualizations)
* Content Source: [powerapps-docs/maker/model-driven-apps/use-custom-controls-data-visualizations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/use-custom-controls-data-visualizations.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @iozm. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@iozm - Thank you for your feedback. An alert has been added at the top with links to articles that cover the modern form designer and modern controls list.
Closing issue.
