### ISSUE TITLE
Odd behavior of security roles privileges "Append" and "Append to" when using Multi-table lookups

### ISSUE THREAD

**Issue by dcastell1** [MicrosoftDocs/powerapps-docs#3711]
I think this article needs to cover some issues that my team is experiencing related to security roles and privileges "Append" and "Append to" with tables that have a Multi-table lookup. It seems that these privileges only work properly in the first table included in the lookup, but do not work for the next ones. I have conducted some tests and users do not have access to related records of a self owned record if that relation is made through a multi-table lookup field and the related table is not the first one included in the lookup definition. 

This issue should be documented.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52939b82-7a1e-7320-c0a4-be2ea7f59724
* Version Independent ID: c67af10a-57f8-b450-5e0f-6c3f7d22079a
* Content: [Use multi-table lookup columns (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/multitable-lookup)
* Content Source: [powerapps-docs/developer/data-platform/webapi/multitable-lookup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/multitable-lookup.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dcastell1. This issue has been assigned to the doc author for review.

**Comment by NHelgren** [comment]
Thank you @dcastell1, I will review this behavior.

**Comment by dcastell1** [comment]
My team is still experiencing this issue, we have found a workaround using the share functionality, but this is not appropiate. Any news regarding this issue?

Thank you.

**Comment by JimDaly** [comment]
Thanks for your feedback. We are closing this issue because we are haven't gotten feedback from the feature team. If you're still experiencing the issue described here, please reopen or create a new issue.
