### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by pvanroos** [MicrosoftDocs/powerapps-docs#3712]
The following section needs to be updated for the recent version of Blazor Server:

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/quick-start-blazor-server-app#prepare-the-app-to-use-azure-ad-tokens

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4db187af-a897-e8df-f587-4b9763e0bf27
* Version Independent ID: b7446e9a-88eb-f6de-5d11-3f2e0489249a
* Content: [Quickstart: Blazor Server Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/quick-start-blazor-server-app#prepare-the-app-to-use-azure-ad-tokens)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-blazor-server-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-blazor-server-app.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pvanroos. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@pvanroos 
Thanks for your feedback.

Can you be more specific about what needs to change?
We also accept pull requests if you want to apply the changes you feel are needed.

**Comment by JimDaly** [comment]
I've updated the Quickstart instructions with new design based on VS 2022 patterns with .NET 7.0
