### ISSUE TITLE
Mime type restrictions need to be made on the "Basic Form Metadata", not on Additional Settings of the Form

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#3714]
[Enter feedback here]
This is regarding the "Accept	The accept attribute specifies the MIME types of files that the server accepts through file upload. To specify more than one value, separate the values with a comma (e.g. audio/,video/,image/*)."
information.

it turns out that this needs to be set in the
"Basic Form Metadata" to become effective,
NOT in the "Additional Settings" of the basic form
to become effective

so please confirm and add this information,
ideally with a few more examples how mime types could be used to restrict only upload of
.docx or .xlsx files

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4c99d3-65e9-9be5-70af-9cb9d3fcda29
* Version Independent ID: cedbcc2e-1cf8-7397-ac76-1324d0b8a735
* Content: [About basic forms - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/entity-forms)
* Content Source: [powerapps-docs/maker/portals/configure/entity-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/entity-forms.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CarstenMS. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
The configuration in the “Additional Settings” area relates to the file upload control that can be enabled on a form either using the Portal Management app or through the design studio. The mime type specification on the additional settings tab is related to that control.
The configuration in the basic form metadata relates to the file upload control that is part of the timeline control that can be added to a Dataverse form that can also be used to view the files attached to the form, the mime type configuration relates to that control.
While similar, these are two different controls.
The documentation has been updated to alleviate the confusion.
