### ISSUE TITLE
Override Column Attributes does not support for Multilanguage

### ISSUE THREAD

**Issue by AshokG9888** [MicrosoftDocs/powerapps-docs#3716]
Hi Team,

Is there any possibility for providing multi language support for override column attribute names in the EntityList in Power apps portals.

Currently it is taking only one value for all languages.

![image](https://user-images.githubusercontent.com/46023343/194025996-4a8fb195-84e3-46c5-bb9d-caed4c8d37c1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcfa5717-8a12-c671-c732-d480114e5c88
* Version Independent ID: e66c1fb1-1867-0dcc-6960-22720cf41e01
* Content: [Configure Advanced form subgrids for portals - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/configure-web-form-subgrid)
* Content Source: [powerapps-docs/maker/portals/configure/configure-web-form-subgrid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-web-form-subgrid.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AshokG9888. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thanks for your feedback. For product-related feedback, visit [https://aka.ms/MPP_ideas](https://aka.ms/MPP_ideas)

Closing this issue.
