### ISSUE TITLE
Microsoft Personal Account identity provider documentation

### ISSUE THREAD

**Issue by Sirgoodman1234** [MicrosoftDocs/powerapps-docs#3717]
Need a screen shot in the doc to make it clear what option is need for success. there are two option that mention "personal"

![image](https://user-images.githubusercontent.com/61255271/194146528-d03f0f2f-28ee-4ba3-9dd4-b9ae8d56389c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 975beece-88e5-4564-5c5f-0d9df65b28c5
* Version Independent ID: b8e55d34-624f-b847-75f3-18977ff83bc2
* Content: [Configure the Microsoft provider for portals - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/configure-oauth2-microsoft?source=recommendations)
* Content Source: [powerapps-docs/maker/portals/configure/configure-oauth2-microsoft.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-oauth2-microsoft.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Sirgoodman1234. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thanks for your feedback. You can pick either option to allow personal Microsoft accounts depending on your requirements. The last option will only allow personal accounts (not accounts from your work or school) and option selected in your screen shot will allow both personal accounts and accounts from your work or school. For more information, please see [https://learn.microsoft.com/azure/active-directory/develop/quickstart-register-app](https://learn.microsoft.com/azure/active-directory/develop/quickstart-register-app)
