### ISSUE TITLE
Sharing component libraries differs from canvas apps.

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/powerapps-docs#3723]
This issue has been reported but closed before: https://github.com/MicrosoftDocs/powerapps-docs/issues/1455

The section [Compoent library permissions](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/component-library#component-library-permissions) says that it can be shared like other apps, but it appears that it is not possible to share it with everyone or groups. It seems to only be visible in the studio by other makers in the environment if it is shared with them individually. 

https://github.com/MicrosoftDocs/powerapps-docs/issues/1455#issuecomment-646432089
Hopefully this is a limitation/bug, but until this is fixed the documentation should mention it as a limitation or a note in this section. It should not be necessary to discover limitations like this by sifting through closed github-issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0224ad-fdbb-c741-98a7-3ec0764b10cf
* Version Independent ID: dfbaaa9e-b902-70de-49d8-9d6c5328b6d2
* Content: [Component library - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/component-library#component-library-permissions)
* Content Source: [powerapps-docs/maker/canvas-apps/component-library.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/component-library.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Hjaf. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. Documentation has been updated, and will reflect the changes soon.
