### ISSUE TITLE
Issue Reporting - application to be configure with task 

### ISSUE THREAD

**Issue by mct8638Get** [MicrosoftDocs/powerapps-docs#3724]
Issue reporting is not loading, see screen shot error below

<img width="893" alt="Screenshot 2022-10-07 083922_IssueReporting" src="https://user-images.githubusercontent.com/115269459/194594924-c63f663c-b233-41c4-93cb-d621fb828bd8.png">

**Comment by phecke** [comment]
@mct8638Get Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support.

Closing this issue.
