### ISSUE TITLE
Adding resource to the plugin package is not fully documented

### ISSUE THREAD

**Issue by malaker** [MicrosoftDocs/powerapps-docs#3727]
Hey I walkthroughed this documentation and I tried to add resource file to plugin package but after following all the steps here resource file has not been added to the nuget package. I try other options and after configuring build action to content then resource file has been added to the package.

Another question is how to load in runtime this file. I tried to get location of the executing assembly and then I tried to find the proper resource but with no success.

Could you elaborate documentation about this part adding resource to the plugin package?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e36fcc6-5be1-4f03-1201-35a093caf9dd
* Version Independent ID: 7e36fcc6-5be1-4f03-1201-35a093caf9dd
* Content: [Dependent Assembly plug-ins (preview) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins)
* Content Source: [powerapps-docs/developer/data-platform/dependent-assembly-plugins.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dependent-assembly-plugins.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @malaker. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@malaker 
Thanks for your feedback.

Are you saying that the steps describe here for PAC CLI: [Add a file resource](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins#add-a-file-resource)

Or here using Power Platform tools: [Add a file resource with Power Platform Tools](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins#add-a-file-resource-with-power-platform-tools)

Didn't work for you?
These steps, using a JSON file, work and you should be able to verify this by using the NuGet Package Explorer.

It is essential that you choose the **Copy To Output Directory** option to **Copy if newer** and you should see the changes in the .csproj file, i.e.

```xml
<ItemGroup>
  <None Update="strings.localized.json">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>
```
Do you not see this?

The goal is to add these to the NuGet Package (not into the assembly itself). When the NuGet Package is extracted at runtime, the file resource will be in the same directory, so you should be able to access it by name.

I'm not clear about what you mean by this:

> I try other options and after configuring build action to content then resource file has been added to the package.

Can you be more specific about exactly what you were trying to do and what ultimately worked for you?

**Comment by malaker** [comment]
- I see this in documentation however after doing this file is not included to the nuget package

**Comment by malaker** [comment]
I tried to include different file than JSON. For testing this feature I had idea to develop plugin that produces pdf documents and it has built in some custom fonts. I wanted to include some ttf files but this below does not work in that case. 

<ItemGroup>
  <None Update="someFont.ttf">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>

**Comment by malaker** [comment]
I gave couple of shots and I managed to include ttf file to nuget package by doing this 

i)
![image](https://user-images.githubusercontent.com/1746427/194804756-41d2886d-d867-4ebc-ad60-ec75f7010e48.png)
II)
![image](https://user-images.githubusercontent.com/1746427/194804820-3ed50de2-d0cd-416f-9933-1b7e3d1efb52.png)
III)
![image](https://user-images.githubusercontent.com/1746427/194804858-5de70252-b578-4d62-8fae-a3e2f57d4ca7.png)

In vs project this file looks like below
```
 <ItemGroup>
    <Content Include="helvetica.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```
In that case nuget spec looks as following

`<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>DataverseUtilities.DataversePdfEngine</id>
    <version>1.0.0</version>
    <authors>Krzysztof Balcerowski</authors>
    <description>Custom API that allows to convert html content to pdf</description>
    <dependencies>
      <group targetFramework=".NETFramework4.6.2">
        <dependency id="Common" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="13.0.1" exclude="Build,Analyzers" />
        <dependency id="itext7" version="7.2.3" exclude="Build,Analyzers" />
        <dependency id="itext7.pdfhtml" version="4.0.3" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <contentFiles>
      <files include="any/net462/helvetica.ttf" buildAction="Content" />
    </contentFiles>
  </metadata>
</package>`

**Comment by JimDaly** [comment]
@malaker 

Can you try using `Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)` which should provide the root location for the files?

**Comment by malaker** [comment]
@JimDaly  Thanks, it works. Finally in sandbox plugin we can load some additional resources.

**Comment by JimDaly** [comment]
@malaker 
Thanks for confirming. Working with dev team on guidance for use in the doc. Should know more this week if this will be our guidance or there is some other recommendation.

**Comment by JimDaly** [comment]
@malaker

The dev team discussed this today and the decision was to remove support for including additional files with the assembly.
I will update the docs to remove the existing instructions and add content about this change.

The guidance going forward is to include such items as resources. I think this topic will be our guidance going forward: [Create resource files for .NET apps](https://learn.microsoft.com/en-us/dotnet/core/extensions/create-resource-files)

I hope this will work for you.

**Comment by malaker** [comment]
@JimDaly I think still it would be good to have possibility to embed some file as resource into assembly. Initially I thought you would extend IPluginExecution Interface so there will be some dictionary of resources or something like that. Showing people loading resource from Assembly may create confusion since many operation on assembly in the past are/were protected by code access security.

**Comment by JimDaly** [comment]
@malaker

I agree. We have to remove support for this until we can guarantee it will be a good solution or if we need to provide something else.

Your scenario is having access to .tff files to support a custom font for PDF generation. Will you be able to achieve this using the strategy described in [https://learn.microsoft.com/en-us/dotnet/core/extensions/resources](https://learn.microsoft.com/en-us/dotnet/core/extensions/resources)?

**Comment by malaker** [comment]
@JimDaly yes it works as well

**Comment by malaker** [comment]
@JimDaly you know in my case I could have ttf file loaded in dataverse in file column and my plugin could retrieve it. My purpose by raising this ticket was to check out this previev feature.

Embedding resource into assembly sometimes makes sense to gain some miliseconds in processing but nowadays in many corporates heavy Logic is offloaded and people use az functions. 


I wanted build ligtweight plugin that can generate simple PDF documents and thanks to this preview feature it is possible without using ilmerge/ilrepack. I think this feature -using external libs is game changer for sure.

**Comment by JimDaly** [comment]
OK . Thanks.
I'm going to close this issue.
