### ISSUE TITLE
Link broken: 404

### ISSUE THREAD

**Issue by hermit99** [MicrosoftDocs/powerapps-docs#3729]
[Enter feedback here]
More information: [Developer documentation: Choices columns](https://learn.microsoft.com/en-us/developer/data-platform/multi-select-picklist).
The above link returns 404
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44b550ae-be95-2d7d-669b-009cf0fe2bf6
* Version Independent ID: cd0f7c13-290a-d9c3-fd08-565d953b78f1
* Content: [Create and edit choices (picklists) overview for Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-global-option-sets)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-global-option-sets.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-global-option-sets.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hermit99. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
Fixed; should be live shortly.
