### ISSUE TITLE
VS2017+ support for cdsproj and pcfproj

### ISSUE THREAD

**Issue by BetimBeja** [MicrosoftDocs/powerapps-docs#373]
Hello,
when you are creating a custom component with the CLI you get the [name].pcfproj but VS2017 does not recognize it as a valid project file. Will the project support be made public? or does it work only with MSBuild?

Best regards,
Betim.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4b9e58-d9d3-c387-fe6a-258ebe78516d
* Version Independent ID: 22d89b45-e427-1ab9-b456-7d7750585b52
* Content: [Create custom component using PowerApp Component Framework Tooling - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/create-custom-controls-using-pcf#feedback)
* Content Source: [powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by pvayner** [comment]
We are working to enable support in Visual Studio but this capability is not currently available. For now you can use the pcfproj file primarily for building the project using MSbuild.

**Comment by Nkrb** [comment]
@BetimBeja Closing this issue.

**Comment by jsuddsjr** [comment]
Any updates on your progress?

**Comment by SolidSoils** [comment]
What is the status of pcfproj projects as of 2021?

**Comment by rohit-kumar-github** [comment]
Is there any update on supporting .cdsproj and .pcfproj files in Visual Studio 2017 or 2019 or 2022 ?

**Comment by thalluripk** [comment]
Eagerly waiting for the VS support for PCF projects

**Comment by zhufamily** [comment]
Still no support yet from Visual Studio 2022?
