### ISSUE TITLE
Dataverse search not supported

### ISSUE THREAD

**Issue by shammyowens** [MicrosoftDocs/powerapps-docs#3730]
Hi Team

We have a support call open 2208170030000831 where we cannot get dataverse search working in Power Apps Portals and the support team have told us that this is by design.  This is very strange as it renders this page completely incorrect.  Can someone come back to me and tell me if this is supported or not.

Thanks
Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0bbd9e69-0cd9-79c4-bd91-2d71e1cc0131
* Version Independent ID: b2719404-110d-0982-28e6-5e99cf329c92
* Content: [Search - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/search)
* Content Source: [powerapps-docs/maker/portals/configure/search.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/search.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @shammyowens. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback. Our understanding is the issue was related to intelligent search not working when a complex Lucene syntax is used. The resolution is to clear the value in Search/Query site setting to resolve the issue. We have updated the documentation. Closing the issue.

**Comment by shammyowens** [comment]
Thank you for the quick response.
