### ISSUE TITLE
Delay in provisioning the development environment

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerapps-docs#3732]
There is apparently a delay (sometimes in double-digit minutes) between requesting the development environment and having it appear in the list of environments. 

This important aspect does not appear to be mentioned in neither the UI nor in this documentation page. It thus appears to many users that the development environment provisioning process is broken.

Can the documentation please be updated to provide clarity around this latency?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa958930-fb79-62a4-3f46-c1adf9f8349a
* Version Independent ID: e2f2d173-ca57-6f83-a2d6-ab381846e5b6
* Content: [Sign up for Power Apps Developer Plan - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/developer-plan)
* Content Source: [powerapps-docs/maker/developer-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/developer-plan.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @marcelbf
* Microsoft Alias: **marcelbf**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. Documentation has been updated and will reflect the changes soon.
