### ISSUE TITLE
Incorrect Step 5 to Enable/Disable CDN on Portal

### ISSUE THREAD

**Issue by Swappy** [MicrosoftDocs/powerapps-docs#3733]
The Step 5 asks to click on Manage, but Manage takes us to Portal Admin page.
Instead We should click on ths portal link on the grid which takes us to the screen showed on step 6.
![image](https://user-images.githubusercontent.com/1185336/195056277-8fd5d278-fd8d-40f9-9d9f-5fb0032b9544.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a40721fb-181c-12a7-4db6-196ed6e30290
* Version Independent ID: a40721fb-181c-12a7-4db6-196ed6e30290
* Content: [Configure a site with Content Delivery Network - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/configure-cdn)
* Content Source: [powerapps-docs/maker/portals/configure/configure-cdn.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-cdn.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @nageshbhat-msft
* Microsoft Alias: **nabha**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Swappy. This issue has been assigned to the doc author for review.

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.
We've been unable to replicate this issue.  If these steps are not working in your solution, please create a support ticket. To contact Support, see here: https://admin.powerplatform.microsoft.com/support.  Closing this issue.
