### ISSUE TITLE
Typo in french

### ISSUE THREAD

**Issue by xguitoux** [MicrosoftDocs/powerapps-docs#3739]
est appeler ==> est appelé

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d2fd3427-3ef2-8c97-6126-63ebb0c6b961
* Version Independent ID: 8aa107b0-eeea-c907-d232-7bd0c330922b
* Content: [Créer un composant de jeu de données d′application canevas dans Microsoft Dataverse - Power Apps](https://learn.microsoft.com/fr-fr/power-apps/developer/component-framework/tutorial-create-canvas-dataset-component)
* Content Source: [powerapps-docs/developer/component-framework/tutorial-create-canvas-dataset-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/tutorial-create-canvas-dataset-component.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @xguitoux. This issue has been assigned to the doc author for review.

**Comment by Bernadette2022** [comment]
This is fixed

**Comment by bishalgoswami** [comment]
Thanks for your comment, @xguitoux. This issue has been assigned to the doc author for review.
