### ISSUE TITLE
Test Studio: This test didn't save properly. Please try again.

### ISSUE THREAD

**Issue by jordyatvalcon** [MicrosoftDocs/powerapps-docs#3740]
I am having the following issue: 
When trying to save a test scenario, I get the following error message:
_This test didn't save properly. Please try again._

![image](https://user-images.githubusercontent.com/115697678/195547353-5327593c-322b-459f-af42-4aa39fb5537e.png)

Additional information: Formula level error experimental feature is on. Also, git version control is on.
It also happens when saving an empty test scenario. There are no errors in the app itself.

**Comment by phecke** [comment]
@jordyatvalcon Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/

If you have a question about our documentation, please provide a link to the related article. Closing this issue.
