### ISSUE TITLE
CDN out of preview?

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/powerapps-docs#3741]
The page is still showing "(preview)".

However, preview tags are now removed on the UI.

PowerPages (including CDN) is now GA, if I understood correctly from Ignite announcements yesterday.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a40721fb-181c-12a7-4db6-196ed6e30290
* Version Independent ID: a40721fb-181c-12a7-4db6-196ed6e30290
* Content: [Configure a site with Content Delivery Network - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/configure-cdn)
* Content Source: [powerapps-docs/maker/portals/configure/configure-cdn.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/configure-cdn.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @nageshbhat-msft
* Microsoft Alias: **nabha**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JMCA2. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for catching that! We have updated the documentation. Closing the issue.
