### ISSUE TITLE
dataverse table: change data types after column creation

### ISSUE THREAD

**Issue by justgivemeanumber** [MicrosoftDocs/powerapps-docs#3742]
why isn't it possible to change data types after the column was created? such a nuisance -.-

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 933ab4a6-2cf0-a627-5443-55c590b3ea7c
* Version Independent ID: 2e01f1bc-3f57-deae-4588-4017173fe3df
* Content: [Create and edit columns in Dataverse using Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-field-portal)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-field-portal.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-field-portal.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@justgivemeanumber - You've reached the Power Platform documentation team. For feature requests, visit the [Power Apps ideas page](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) to submit or vote on an existing feature idea. 

Closing issue.
