### ISSUE TITLE
InitialState is null

### ISSUE THREAD

**Issue by ziron999** [MicrosoftDocs/powerapps-docs#3743]
Documentation followed 100%
Here is the code with the issue:

_Host.cshtml:
@namespace DataverseAPI.Pages

@using DataverseAPI.Data
@using Microsoft.AspNetCore.Authentication

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}
<component type="typeof(App)" render-mode="ServerPrerendered" />

@{
    var token = new TokenProvider
            {
                AccessToken = await HttpContext.GetTokenAsync("access_token")
            };
}
<app>
    <component type="typeof(App)" param-InitialState="token" render-mode="ServerPrerendered" />
</app>

App.razor:
@using DataverseAPI.Data
@inject TokenProvider Service

<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(App).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
        <NotFound>
            <PageTitle>Not found</PageTitle>
            <LayoutView Layout="@typeof(MainLayout)">
                <p role="alert">Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>

@code{
[Parameter]
------------> public TokenProvider InitialState { get; set; } <------------- null

protected override void OnInitialized()
{
    Service.AccessToken = InitialState.AccessToken;
    base.OnInitialized();
}
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4db187af-a897-e8df-f587-4b9763e0bf27
* Version Independent ID: b7446e9a-88eb-f6de-5d11-3f2e0489249a
* Content: [Quickstart: Blazor Server Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/quick-start-blazor-server-app)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-blazor-server-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-blazor-server-app.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ziron999. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
I've updated the Quickstart instructions with new design based on VS 2022 patterns with .NET 7.0
