### ISSUE TITLE
Please mention somewhere in the docs that POST operations are only permissible within Change Set

### ISSUE THREAD

**Issue by MateRadz** [MicrosoftDocs/powerapps-docs#3744]
[Enter feedback here]

.... or maybe it is a bug in product not a feature. The truth is that batch without change set can only execute GET commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6db53047-327d-6eec-e6a8-4d9dae98f362
* Version Independent ID: 31b3ebbd-9070-db30-cc4e-cec4b41373b8
* Content: [Execute batch operations using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/execute-batch-operations-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MateRadz. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@MateRadz 
Thanks for your feedback.

You are saying:

>  ...batch without change set can only execute GET commands

This isn't true.

You can't use a `GET` request inside of a changeset, but you can send `POST`, `PATCH`, `DELETE`, and `PUT` requests outside of a changeset.

Here is an example:

**Request**
```
POST [Organization URI]/api/data/v9.2/$batch HTTP/1.1

OData-MaxVersion: 4.0
OData-Version: 4.0
If-None-Match: null
Accept: application/json
Content-Type: multipart/mixed; boundary="batch_04fb0926-918b-4fbb-aadc-4105e4e02803"
Content-Length: 574

--batch_04fb0926-918b-4fbb-aadc-4105e4e02803
Content-Type: application/http
Content-Transfer-Encoding: binary

POST /api/data/v9.2/accounts HTTP/1.1
Content-Type: application/json; type=entry

{
  "name": "account 1"
}
--batch_04fb0926-918b-4fbb-aadc-4105e4e02803
Content-Type: application/http
Content-Transfer-Encoding: binary

POST /api/data/v9.2/accounts HTTP/1.1
Content-Type: application/json; type=entry

{
  "name": "account 2"
}
--batch_04fb0926-918b-4fbb-aadc-4105e4e02803--
```

**Response**
```
HTTP/1.1 200 OK

Content-Type: multipart/mixed; boundary=batchresponse_cd089f57-e599-4628-b655-db0cda5c34f7

--batchresponse_cd089f57-e599-4628-b655-db0cda5c34f7
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 204 No Content
OData-Version: 4.0
Location: [Organization URI]/api/data/v9.2/accounts(0d374653-314b-ed11-bba1-0022482624f0)
OData-EntityId: [Organization URI]/api/data/v9.2/accounts(0d374653-314b-ed11-bba1-0022482624f0)


--batchresponse_cd089f57-e599-4628-b655-db0cda5c34f7
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 204 No Content
OData-Version: 4.0
Location: [Organization URI]/api/data/v9.2/accounts(33374653-314b-ed11-bba1-0022482624f0)
OData-EntityId: [Organization URI]/api/data/v9.2/accounts(33374653-314b-ed11-bba1-0022482624f0)


--batchresponse_cd089f57-e599-4628-b655-db0cda5c34f7--
```

**Comment by MateRadz** [comment]
Nope it is not working. I just tried to replicate:

POST /api/data/v9.1/$batch HTTP/1.1
Host: andupmidsb.crm4.dynamics.com
Authorization: Bearer ******
OData-MaxVersion: 4.0
OData-Version: 4.0
If-None-Match: null
Content-Length: 556

--batch_04fb0926-918b-4fbb-aadc-4105e4e02803
Content-Type: application/http
Content-Transfer-Encoding: binary

POST https://andupmidsb.crm4.dynamics.com/api/data/v9.2/accounts HTTP/1.1
Content-Type: application/json; type=entry

{
  "name": "account 1"
}
--batch_04fb0926-918b-4fbb-aadc-4105e4e02803
Content-Type: application/http
Content-Transfer-Encoding: binary

POST https://andupmidsb.crm4.dynamics.com/api/data/v9.2/accounts HTTP/1.1
Content-Type: application/json; type=entry

{
  "name": "account 2"
}
--batch_04fb0926-918b-4fbb-aadc-4105e4e02803--

And Response is:

--batchresponse_d2b26f89-9458-44fa-8b52-4561cc865fd0
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 204 No Content
OData-Version: 4.0
Location: https://andupmidsb.crm4.dynamics.com/api/data/v9.2/accounts(0798e9a2-404d-ed11-bba3-0022489e2bce)
OData-EntityId: https://andupmidsb.crm4.dynamics.com/api/data/v9.2/accounts(0798e9a2-404d-ed11-bba3-0022489e2bce)


--batchresponse_d2b26f89-9458-44fa-8b52-4561cc865fd0
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 400 Bad Request
REQ_ID: 471a9777-5f4b-45d0-9fa2-0b8e21695c07
Content-Type: application/json; odata.metadata=minimal
OData-Version: 4.0

{"error":{"code":"0x0","message":"Error identified in Payload provided by the user for Entity :'accounts', For more information on this error please follow this help link https://go.microsoft.com/fwlink/?linkid=2195293  ---->  InnerException : System.ArgumentException: Stream was not readable.\r\n   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)\r\n   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightInputContext.CreateTextReader(Stream messageStream, Encoding encoding)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightInputContext..ctor(ODataMessageInfo messageInfo, ODataMessageReaderSettings messageReaderSettings)\r\n   at Microsoft.OData.Json.ODataJsonFormat.CreateInputContext(ODataMessageInfo messageInfo, ODataMessageReaderSettings messageReaderSettings)\r\n   at Microsoft.OData.ODataMessageReader.ReadFromInput[T](Func`2 readFunc, ODataPayloadKind[] payloadKinds)\r\n   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)."}}
--batchresponse_d2b26f89-9458-44fa-8b52-4561cc865fd0--

Which indicates that the first POST from your example works the second does not. And they do not differ. So either the product is broken or documentation is not detailed enough to cover this scenario.

**Comment by MateRadz** [comment]
Thanks. Indeed. It works. Maybe this is obvious but it would not hurt to stress in the documentation that POST Requests inside the batch do not require [organization URI] after "POST" and before "/api/data/v9.2/accounts HTTP/1.1".

**Comment by JimDaly** [comment]
@MateRadz 
Thanks for letting us know.
Refreshing this content is on my TODO list.

Do you think that adding a link to the OData specification at [11.7 Batch Requests](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752313) might help? Ultimately, this is where all the information comes from.

Do you mind if I ask what language you are using? JavaScript? Python?, C#? something else?

For C# .NET 6.0 we added a new helper library that includes $batch capabilities about 2 months ago. See [WebAPIService class library (C#)](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx/WebAPIService) and the classes within the [Batch](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx/WebAPIService/Batch) folder are the ones I used to write the sample I sent you. Details are here [Batch documentation](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx/WebAPIService#batch). The key for .NET was understanding how to use the [MultipartContent Class](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.multipartcontent?view=net-6.0).

**Comment by MateRadz** [comment]
Yes. It would definitely help. After your suggestion I also checked that. I use Node.js in Azure Functions. For the call I am using client_credentials to connect to D365.
