### ISSUE TITLE
Permissions or Security Role needed to create tests

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/powerapps-docs#3745]
What security roles or permissions are needed for creating and running Test Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b15deb16-02e4-9005-2dbd-917f8308b47d
* Version Independent ID: 51cc413b-0fd1-5a63-ddfa-16b3fb4c9e88
* Content: [Working with Test Studio (contains video) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-test-studio)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-test-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/working-with-test-studio.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @aengusheaney
* Microsoft Alias: **aheaney**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @samadane. This issue has been assigned to the doc author for review.

**Comment by samadane** [comment]
Any update on this one?  Is it looking for named security role or the privileges underneath?

**Comment by ChrisBal-MSFT** [comment]
Hello, the rights to create and edit tests with Test Studio are equal to the rights needed to edit and update the app itself.  So, as long as the maker has the ability to open an app for editing, then they will also have all the rights necessary to use Test Studio.

**Comment by tapanm-MSFT** [comment]
Documentation will be updated soon to reflect this information.
