### ISSUE TITLE
How to handle updates through solution deployments

### ISSUE THREAD

**Issue by melody-universe** [MicrosoftDocs/powerapps-docs#3747]
This documentation outlines the steps to import Synapse Link configurations from a solution. However, from our observations, if you deploy a new version of that solution with changes to the Synapse Link configuration component, regardless of whether the deployment is managed or unmanaged, those changes are not made to the Synapse Link configuration. The only way we've been able to get the configuration to synchronize with the updated component is to unlink and re-import the configuration.

Is this the intended functionality? If so, can it be documented? Our goal with ALM is to establish fully automated deployments, so I am hoping this is a temporary limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5eaf46c4-e66c-96c6-e780-42ed464a6db3
* Version Independent ID: 5eaf46c4-e66c-96c6-e780-42ed464a6db3
* Content: [Transport Azure Synapse Link for Dataverse configuration - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-solution)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-solution.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-solution.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @melody-universe. This issue has been assigned to the doc author for review.

**Comment by JasonHQX** [comment]
We are planning to do ALM enhancement around Apr 23 to allow user update Azure side configuration before importing solution. Thanks

**Comment by Mattp123** [comment]
Closing issue.

**Comment by melody-universe** [comment]
@JasonHQX This is a separate issue from #3503 and is unrelated to configuration in Azure. This is a problem with solution deployments on the Dataverse side. Steps are as follows:

1. Set up Synapse Link configuration in a development environment.
2. Add the Synapse Link configuration to a solution in the development environment.
3. Export the solution from the development environment.
4. Import the solution (same behavior for both managed and unmanaged) into a downstream environment, such as production.
5. Import the Synapse Link configuration from the solution into the Synapse section from the maker portal.
   - **Note:** The Synapse Link configuration will point to the same Storage Account / Synapse Workspace as the development environment, per #3503, which is a problem for customers, but this is a separate issue.
6. Go back to the development environment and make a change to the Synapse Link configuration.
7. Export a new version of the solution with the updated Synapse Link configuration.
8. Import the new solution into the downstream environment.
   - The Synapse Link configuration will be updated in the solution component, but not in the active configuration.
   - In order to activate the changes, the configuration needs to be unlinked and then re-linked.
   - This will delete the container on the storage account and re-create it, causing all configured tables to need to be re-synced.
   - This will also force any downstream services to need to re-sync as well.

Not only does this add a manual step to any deployment that includes changes to Synapse Link, but it consumes unnecessary resources, and will force us to bring down our services to our customers as well, as we were using Data Export Service to expose data to external customers through our own API's, but will need to bring down those API's while all data re-syncs.

Will this also be addressed in the Apr 23 update?

@Mattp123 Please re-open this issue.
