### ISSUE TITLE
Question regarding "success" or "failure"

### ISSUE THREAD

**Issue by temmyraharjo** [MicrosoftDocs/powerapps-docs#3748]
Hey Team, I'm testing below scenario:

1. Create Javascript and add event on the formOnLoad to call method formContext.data.entity.addOnPostSave(callDemoApi)
2. Create a Plugin that will always throw error

The callDemoApi will not triggered. Only if I disabled the plugin it will go there (there is no error happening). While the definition on the page is "Adds an event handler to be called after the record is saved with success or failure.". What is the definition of "failure" here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b18afb70-3a3c-1fc8-7adf-27c430c6001a
* Version Independent ID: 8eaae86e-6f4b-15db-44d8-1b0b3a9bb4cd
* Content: [addOnPostSave (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/addonpostsave)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOnPostSave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOnPostSave.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @temmyraharjo. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
I understand that this is a known issue. Looking for confirmation before closing. @fafuxa-ms Can you confirm?

**Comment by JimDaly** [comment]
Confirmed.
