### ISSUE TITLE
Please document how to specify 'minimum', 'maximum' and 'precision' for appropriate data types

### ISSUE THREAD

**Issue by StevenRasmussen** [MicrosoftDocs/powerapps-docs#3749]
In the documentation it states that you can specify 'minimum', 'maximum' and 'precision' for several of the different types.  I don't see this documented anywhere and I have no idea how to do this. Are you able to document this for the future but in the meantime, how is this accomplished?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3b2e635-6c60-0efc-d894-e43216dca90e
* Version Independent ID: 9828125d-c061-465e-d486-b4ea609190e1
* Content: [Property Element - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/manifest-schema-reference/property)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/manifest-schema-reference/property.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @StevenRasmussen. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@StevenRasmussen 
Thanks for your feedback.

I believe you are referring to the descriptions in the [Remarks](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/manifest-schema-reference/property#remarks) section of this doc where the following can be found:

|Value|Description|
|---|---|
|Decimal|Up to 10 decimal points of precision can be used for values between -100,000,000,000 and -100,000,000,000 can be in this column. You can specify the level of precision and the maximum and minimum values.|
|FP|Up to 5 decimal points of precision can be used for values between -100,000,000,000 and -100,000,000,000 can be in this column. You can specify the level of precision and the maximum and minimum values.|

I don't see any attributes in the XML to set min or max values for a given property in the manifest.

I suspect that these descriptions come from cases where you are defining columns/attributes in Dataverse.
In this case, we should remove this part of the description: `You can specify the level of precision and the maximum and minimum values.`

@noazarur-microsoft 
Can you verify?

**Comment by JimDaly** [comment]
@StevenRasmussen 
Spoke with the dev team about this today. 
I think this might be an issue where the docs introduced confusion.

The descriptions for different types mentioned above do include the text _"You can specify the level of precision and the maximum and minimum values."_ within the definitions of the type. But this means these min, max, and precision values are customizable within the column (attribute) definition.

You can specify these values for the column, but not within the pcf control.
Were you looking for links to how to define columns? Like this [How to create and edit columns](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-fields)?

**Comment by JimDaly** [comment]
Removed the language talking about specifying max, min, & precision values since it might be confusing.
