### ISSUE TITLE
Choose one of the two :-)

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#375]
In section "Dynamics 365 and the Common Data Service",
then in "Manage reusable Business logic and rules" :
"Business Rules and logic already defined in on your Dynamics 365 entities [...] "

&gt;&gt; should be either "defined in your Dynamics 365 entities"
or "defined on your Dynamics 365 entities"
My personal preference is the first option :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab497f2-57e7-2992-7286-d8032b6308ea
* Version Independent ID: 276b8930-20f7-8157-a983-5d0bfb6c302b
* Content: [What is Common Data Service? - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-intro.md)
* Service: **powerapps**
* GitHub Login: @clwesene
* Microsoft Alias: **matp**

**Comment by KumarVivek** [comment]
@a-zaf This is fixed now. Thanks for reporting it.
