### ISSUE TITLE
Co-presence out of preview

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/powerapps-docs#3750]
This page describes co-presense has the preview tag.

Co-presence it's GA since September for Dynamics apps.
Source:
https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave1/sales/dynamics365-sales/start-linked-chat-co-presence-record

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3483fba6-5fd9-b14c-07ad-bdcb0cea575e
* Version Independent ID: 3483fba6-5fd9-b14c-07ad-bdcb0cea575e
* Content: [Collaborate with others in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/user/collaboration)
* Content Source: [powerapps-docs/user/collaboration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/collaboration.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by JMCA2** [comment]
@alejaraz

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JMCA2. This issue has been assigned to the doc author for review.

**Comment by sericks007** [comment]
@JMCA2, thank you for bringing this to our attention.  [Collaborate with others in model-driven apps](https://learn.microsoft.com/en-us/power-apps/user/collaboration) refers to **Power Apps**, while the [Start a linked chat from co-presence in a record](https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave1/sales/dynamics365-sales/start-linked-chat-co-presence-record) article is specifically for **Dynamics 365**.
