### ISSUE TITLE
Outdated terminology in the paragraph: "Dataverse".

### ISSUE THREAD

**Issue by MaciejPokrzywinski** [MicrosoftDocs/powerapps-docs#3755]
In the paragraph Dataverse appears: "Common Data Service" instead of: "Dataverse". This can be confusing for users who have not worked with older versions of Dataverse, or are not familiar with the history of terminology changes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2adb9b7d-1922-2d8f-11db-eaa4e6b22547
* Version Independent ID: 03ebcdf5-c4c4-a6e2-7abd-ed168b08d48c
* Content: [Power Apps architectural design - Where to place logic - Power Apps](https://learn.microsoft.com/en-us/power-apps/guidance/planning/logic)
* Content Source: [powerapps-docs/guidance/planning/logic.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/guidance/planning/logic.md)
* Service: **powerapps**
* Sub-service: **guidance**
* GitHub Login: @taiki-yoshida
* Microsoft Alias: **tayoshi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MaciejPokrzywinski. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@MaciejPokrzywinski - Thank you for your feedback. The article has been updated to reflect the correct platform name.
Closing issue.
