### ISSUE TITLE
Personal Views

### ISSUE THREAD

**Issue by ryanwga** [MicrosoftDocs/powerapps-docs#3758]
How do you add personal views after the 2022 Wave 2 update with Dataverse search enabled?  The advanced find is removed and the view dropdown doesn't appear to have the option to add a new personal view anymore either.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd37c514-610f-6c2b-be8e-80aff48dac6b
* Version Independent ID: 08ccf432-bc24-a306-5bef-83bca8563e18
* Content: [Create and manage personal views on a grid page - Power Apps](https://learn.microsoft.com/en-us/power-apps/user/grid-filters-advanced#create-personal-views)
* Content Source: [powerapps-docs/user/grid-filters-advanced.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/grid-filters-advanced.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ryanwga. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Follow these step to save a view: https://learn.microsoft.com/en-us/power-apps/user/grid-filters-advanced#save-changes-to-views-in-modern-advanced-find 

Thanks,
Mints

**Comment by ryanwga** [comment]
Hi Manjinder,

I'm not sure why you closed the case.  It isn't resolved.  I don't have the option to add personal views anymore after 2022 wave 2 update, see screenshots below.

With "Modern advanced find in model-driven apps" set to ON:

***@***.***



With "Modern advanced find in model-driven apps" set to OFF:

***@***.***

Advanced Find ***@***.*** missing from top ribbon:

***@***.***

How do we allow users to add personal view again after 2022 Wave 2 update?

Thanks,
Ryan

**Comment by ryanwga** [comment]
With Modern advanced find.... option set to off, we have a work around by using the Advanced Find pop-up. I'd like to know how to create personal views with it turned on. Or is Microsoft removing the personal views option moving forward?

With "Modern advanced find in model-driven apps" set to OFF:

***@***.***

***@***.***

Thanks,
Ryan

**Comment by ryanwga** [comment]
Regarding "Modern advanced find in model-driven apps": Seems to be an odd way to handle this, but after further digging, it appears that you have to edit an existing view first, then in the views dropdown I get the "Save as new view" option.  Why not add a "Create new view" option?


Where is the "Create new view" option????

***@***.***

After editing an existing view:

***@***.***


Thanks,
Ryan

From: Ryan Williams
Sent: Wednesday, October 19, 2022 8:59 AM
To: MicrosoftDocs/powerapps-docs ***@***.***>; MicrosoftDocs/powerapps-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/powerapps-docs] Personal Views (Issue #3758)

With Modern advanced find.... option set to off, we have a work around by using the Advanced Find pop-up. I'd like to know how to create personal views with it turned on. Or is Microsoft removing the personal views option moving forward?

With "Modern advanced find in model-driven apps" set to OFF:

***@***.***

***@***.***

Thanks,
Ryan
