### ISSUE TITLE
Changing PowerApps CLI installation directory

### ISSUE THREAD

**Issue by anique9999** [MicrosoftDocs/powerapps-docs#3759]
Hi,

I'm trying change the installation directory of Microsoft PowerApps CLI from %APPDATA%\Microsoft\PowerAppsCLI to C:\ProgramFiles or C:\ProgramsFiles(x86). 

I'm using ` /INSTALLDIR` command-line to change the directory but the application is still installing in %APPDATA%.

Can you please tell me how can I change the installation directory via command-line?

Thanks,
Anique

**Comment by JimDaly** [comment]
@anique9999 
Thanks for your feedback.

The documentation about installing PAC CLI is here: [Install Microsoft Power Platform CLI](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction#install-microsoft-power-platform-cli).

I don't see that `INSTALLDIR` is mentioned anywhere in that topic, or any content that describes how the location of the installation can be modified.

So, this sounds like a feature request. If we have this capability but it isn't documented, I'll ask @kkanakas to update the doc.

**Comment by JimDaly** [comment]
Information was forwarded to @kkanakas. As mentioned before, this sounds like a feature request. Closing this.
