### ISSUE TITLE
The link "Cross-geo operations" is broken

### ISSUE THREAD

**Issue by rezanid** [MicrosoftDocs/powerapps-docs#3760]
The "[Cross-geo operations](https://learn.microsoft.com/en-us/power-bi/collaborate-share/power-bi/collaborate-share/power-apps-power-bi-integration-considerations#cross-geo-operations)" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ee54c44-ed0c-87b5-c9dd-88976667517f
* Version Independent ID: 5ee54c44-ed0c-87b5-c9dd-88976667517f
* Content: [Create Power BI report and dataset components (preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/create-edit-powerbi-report-dataset-components)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-edit-powerbi-report-dataset-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/create-edit-powerbi-report-dataset-components.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rezanid. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Thanks for pointing this out @rezanid. I have made a correction and hopefully it will be online soon.

**Comment by Mattp123** [comment]
@rezanid - Thank you for your feedback. Link has been fixed and will be published shortly.
Closing issue.
