### ISSUE TITLE
Suggestions for clight adjustments to the instructions

### ISSUE THREAD

**Issue by jdballard** [MicrosoftDocs/powerapps-docs#3761]
I'm learning, or maybe I missed a step, but I noticed several things:

In Step 5 under "Creating a new component project", it says "the above command also runs the npm install command for you..." It did not automatically run it, but there was output after the first command that said "Be sure to run npm install or equivalent in this directory to install project dependencies." So that was easy to figure out it hadn't run, but the instruction _is_ incorrect.

In step 3 under "Implementing manifest", it provides an example of what the XML file should look like after the changes. The file, as originally generated, though, contained two properties. It would be helpful to call out that one of the properties should be deleted. The second property already had the "of-type-group", whereas the first one didn't. I adjusted the properties on the second prroperty, and everything worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by JimDaly** [comment]
@jdballard 
Thank you for your feedback. 
I'm glad you were able to complete the steps despite some of the distractions.

I have a workitem to review this content to catch these things. I hope to get to it soon.
