### ISSUE TITLE
'Download the Northwind Traders Solution File' button doesn't work

### ISSUE THREAD

**Issue by hedmon** [MicrosoftDocs/powerapps-docs#3764]
Hello,
'Download the Northwind Traders Solution File' button doesn't work. There is an error:
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:417c39ab-601e-0008-7950-e5eb95000000 Time:2022-10-21T13:23:45.5912698Z</Message>
</Error>

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5475653-e112-f407-b0de-ecad06bac5bf
* Version Independent ID: 9f109131-06e3-5f88-1205-233d2b6c4bf0
* Content: [Install Northwind Traders database and apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/northwind-install)
* Content Source: [powerapps-docs/maker/canvas-apps/northwind-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/northwind-install.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hedmon. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@hedmon Thank you for your feedback. I have fixed the download link. It's working now.

Thanks,
Mints
