### ISSUE TITLE
Async plugin steps fail

### ISSUE THREAD

**Issue by dmognaschi** [MicrosoftDocs/powerapps-docs#3765]
[Enter feedback here]
Dear,
I have to report an issue about the new (great!) feature:
on version 1710 (9.2.22092.190) online,  each async plugin steps of plugintypes belonging to pluginassembly of a pluginpackage fails with this exception:

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Expected non-empty Guid. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040203
Message: Expected non-empty Guid.
TimeStamp: 2022-10-21T16:32:58.8829373Z
--
Exception details: 
ErrorCode: 0x80040216
Message: System.ArgumentException: Expected non-empty Guid.
Parameter name: user
TimeStamp: 2022-10-21T16:32:58.8829373Z
--
).

Here is a sample plugin:
public class VanillaPlugin : IPlugin
    {
        public void Execute(IServiceProvider serviceProvider)
        {
            var tracingService = (ITracingService)serviceProvider.GetService(typeof(ITracingService));
            var pluginTelemetry = (ILogger)serviceProvider.GetService(typeof(ILogger));
            tracingService.Trace("TracingService: hello world!");
            pluginTelemetry.LogTrace("PluginTelemetry: hello world!");
        }
    }

Can you forward to the product team?
Ty,
Davide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e36fcc6-5be1-4f03-1201-35a093caf9dd
* Version Independent ID: 7e36fcc6-5be1-4f03-1201-35a093caf9dd
* Content: [Dependent Assembly plug-ins (preview) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins?source=docs)
* Content Source: [powerapps-docs/developer/data-platform/dependent-assembly-plugins.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dependent-assembly-plugins.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dmognaschi. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@dmognaschi 
This looks like one of the current known issues: 
See [Asynchronous plug-in steps do not work](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins?source=docs#asynchronous-plug-in-steps-do-not-work)

> **Asynchronous plug-in steps do not work**
> If you use dependent assemblies for a plug-in registered for an asynchronous step an error with the message `Expected non-empty Guid`. will occur.

If this is something different, please update this issue.
