### ISSUE TITLE
Custom Workflow Activities not being registered

### ISSUE THREAD

**Issue by dmognaschi** [MicrosoftDocs/powerapps-docs#3766]
Dear,
registering a package, all assemblies that expose at least one plugin type are correctly registered;
all public types that implement IPlugin are also correctly registered;
however, any custom workflow activities exposed by the assembly are not registered.

If it is a desired behavior (to push the adoption of the most modern CustomAPI) perhaps it would be better to explain it.

Ty,
Davide

**Comment by dmognaschi** [comment]
Duplicate of #3767

**Comment by phecke** [comment]
Duplicate of #3767
