### ISSUE TITLE
Custom Workflow Activities not being registered

### ISSUE THREAD

**Issue by dmognaschi** [MicrosoftDocs/powerapps-docs#3767]
[Enter feedback here]
Dear,
registering a package, all assemblies that expose at least one plugin type are correctly registered;
all public types that implement IPlugin are also correctly registered;
however, any custom workflow activities exposed by the assembly are not registered.

If it is a desired behavior (to push the adoption of the most modern CustomAPI) perhaps it would be better to explain it.

Ty,
Davide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad2eb047-525a-63b7-2d6e-1536a374d688
* Version Independent ID: 2b8e3e9d-c957-d43e-ceeb-c75da0857d2d
* Content: [Tutorial: Write and register a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tutorial-write-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dmognaschi. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@dmognaschi Let me see if I understand the issue.

You created a plug-in package composed of assemblies that contain types derived from IPlugin and CodeActivity. Only the types derived from IPlugin are registered. Is that correct?

**Comment by phecke** [comment]
@dmognaschi According to the [documentation](https://learn.microsoft.com/power-apps/developer/data-platform/dependent-assembly-plugins#limitations):

The following limitations apply to dependent assembly plug-ins.

A plugin package is limited to 16 MB in size or 50 assemblies.
**Workflow extensions, also known as workflow assemblies, workflow activities or custom workflow activities are not supported.**
On-premises environments are not supported.

**Comment by dmognaschi** [comment]
Thank you @phecke , I missed the limitations!
