### ISSUE TITLE
Access to the comment feature

### ISSUE THREAD

**Issue by yosoyx** [MicrosoftDocs/powerapps-docs#3773]
I assume that one does make those who can comment, co-owners of the app.  If this is the case, it would help to so specify at the beginning of the document

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8fb9993-5a6f-b624-75df-3be9ae44d969
* Version Independent ID: d8fb9993-5a6f-b624-75df-3be9ae44d969
* Content: [Add comments when you're buiding a canvas app - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/comments)
* Content Source: [powerapps-docs/maker/canvas-apps/comments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/comments.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @mkaur
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @yosoyx. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@yosoyx Thank you for the feedback. I added the following line in the first paragraph:

**To allow other makers to add comments, make sure to share the app with them.**

Thanks,
Mints
