### ISSUE TITLE
Change wording

### ISSUE THREAD

**Issue by jondoesflow** [MicrosoftDocs/powerapps-docs#3776]
Hi,

In this section - https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-virtual-tables-using-connectors?tabs=sql#create-the-data-source at Step 5, the field referred to in the screenshot is Data source, I thiunk the wording should be more explicit and it should say "Dataset value"?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5490be6b-9f4c-6425-d232-e89e542e40dd
* Version Independent ID: 5490be6b-9f4c-6425-d232-e89e542e40dd
* Content: [Create virtual tables using virtual connectors (preview) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-virtual-tables-using-connectors?tabs=sql)
* Content Source: [powerapps-docs/maker/data-platform/create-virtual-tables-using-connectors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-virtual-tables-using-connectors.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jondoesflow. This issue has been assigned to the doc author for review.

**Comment by NHelgren** [comment]
Thanks for the feedback @jondoesflow, I updated the sections in step 5 to reverence the Dataset Value field where appropriate.
