### ISSUE TITLE
Please rephrase paragraph Completing Solution Upgrade

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/powerapps-docs#3779]
I am currently studying the update solutions documentation. One paragraph is quite a heavy lifting for my brain because it mentions `solutions` quite often and with varying syntax, e.g.:
- original solution
- new solution
- same solution (name)
- base solution suffixed with _Upgrade
- base solution
- solution list
- _Upgrade solution

Is it possible to rephrase this paragraph or illustrate it in a more hands-on way by means of images or an example, e.g. adding a exemplary solution name to follow along, e.g. `Solution1` (or base solution) and `Solution1_Upgrade`.

Moreover, I not fully understood what is exactly meant with these two sentences:

> This will uninstall _all previous patches_ and the base solution then rename the _Upgrade solution to be the same name as the previous base solution. Any components that were in the original solution and patches that are not present in the _Upgrade solution will be deleted as part of this process.

The first sentence may require some proof reading?

What exactly is meant with _`uninstall all previous patches`_ ? 
Does that mean all modifications / components (=patches) that were added by the specific solution `Solution1_Upgrade` I imported to upgrade a base solution `Solution1` will be removed from the `Solution1`? -- some kind of a role back to a previous version (e.g. v1.0.0.9 --> v1.0.0.8) and re-trying to apply the modifications from scratch?

Or will the **Apply Solution Upgrade** step remove and re-apply all the modifications that had been applied to a base solution since its creation (v1.0.0.0)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1dda8ad9-01d8-aa29-704a-c8f13868a350
* Version Independent ID: ef98dcae-9534-425c-1e27-7255228af17f
* Content: [Update a solution - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/update-solutions)
* Content Source: [powerapps-docs/maker/data-platform/update-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/update-solutions.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Markus-Hanisch. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@Markus-Hanisch - Explaining solution layering in detail is beyond the scope of the article. For a more detailed explanation, see the article below in the Power Platform ALM guide. I've added a link to the article in the See also section as well.
https://learn.microsoft.com/power-platform/alm/solution-layers-alm#layering-within-a-managed-solution

Closing issue.
