### ISSUE TITLE
Datepicker format in PowerApps web part

### ISSUE THREAD

**Issue by paylord** [MicrosoftDocs/powerapps-docs#378]
A PowerApp with a datepicker is showing the correct AU date format when developing (in Chrome) and when testing in browser, iPad or smartphone.  However, when added to a modern SharePoint page through a web part the date defaults to US format.  I have confirmed that the browser default is enAU.

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. Please raise a support [service request](https://admin.powerplatform.microsoft.com/support) to investigate the issue.
