### ISSUE TITLE
https://learn.microsoft.com/en-us/power-apps/maker/common/wrap/code-sign-android

### ISSUE THREAD

**Issue by Erica0214** [MicrosoftDocs/powerapps-docs#3781]
There is a documentation error in page https://learn.microsoft.com/en-us/power-apps/maker/common/wrap/code-sign-android

The example of generate keys, text and the code doesn't match

<img width="654" alt="image" src="https://user-images.githubusercontent.com/63276075/198189026-95ee2d1d-b92d-463c-acad-02eae39ad56f.png">

**Comment by mduelae** [comment]
Closing. Duplicate issue of - https://github.com/MicrosoftDocs/powerapps-docs/issues/3782.
