### ISSUE TITLE
In example of generate keys, text and the code doesn't match

### ISSUE THREAD

**Issue by Erica0214** [MicrosoftDocs/powerapps-docs#3782]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/63276075/198191357-8ea31399-6318-4f39-b6f4-5036575e9065.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54afc67b-546e-0024-4c28-9068d6a6dc2b
* Version Independent ID: 54afc67b-546e-0024-4c28-9068d6a6dc2b
* Content: [Code sign for Android - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/common/wrap/code-sign-android#generate-keys)
* Content Source: [powerapps-docs/maker/common/wrap/code-sign-android.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/common/wrap/code-sign-android.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @larryk78
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Erica0214. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@Erica0214 Thank you for the feedback. I'm verifying this information with our internal team. Once I hear back from them I will send you an update.

Thanks,
Mints

**Comment by mduelae** [comment]
@Erica0214 I fixed the error. You should see the updates publish to our site by 6pm PST.
