### ISSUE TITLE
JavaScript Icons on CRM Dashboard

### ISSUE THREAD

**Issue by Regal92** [MicrosoftDocs/powerapps-docs#3783]
Good Day and thank for the article. 

We are looking to implement this in CRM Dashboards which is where majority of the business users interact with CRM. Is the script tested and extendable for CRM Dashboards, or is it pretty much limited to the main CRM View?

Best, 
Arslan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f595b311-6f09-8fb8-1a6e-1927f15e4561
* Version Independent ID: eb5a82d9-cb30-2d89-baec-8d917bd2a81e
* Content: [Display custom icons alongside values in list views with Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/display-custom-icons-instead)
* Content Source: [powerapps-docs/maker/data-platform/display-custom-icons-instead.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/display-custom-icons-instead.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Regal92. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@Regal92 - Since you can add views to personal dashboards in either model-driven apps or Dynamics 365 customer engagement apps, the dashboard should be able to display the icons on the dashboard when the view is added to it.

Closing issue.
