### ISSUE TITLE
Make Tabs addressable

### ISSUE THREAD

**Issue by Sinha-Abhisek** [MicrosoftDocs/powerapps-docs#3785]
It has been an ask for a long time to make Tabs addressable, like:

https://myorg.crm.dynamics.com/main.aspx?etn=account&pagetype=entityrecord&id=%7B91330924-802A-4B0D-A900-34FD9D790829%7D#Details

should take the user to the **Details** Tab within the Account record directly and not on the first tab. This will help with sharing URLs to external apps and also enhance the experience as we bring in Outlook/Teams together with PowerApps. Direct link to a Tab can help users share the link more easily within Teams or Outlook as the recipient know where to look for directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0987eb9-274b-1f4a-f46f-36466e81c119
* Version Independent ID: 8531f5bc-fcf6-ce36-209e-e0dd4137de31
* Content: [Open apps, forms, views, dialogs, and reports with a URL (model-driven apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/open-forms-views-dialogs-reports-url)
* Content Source: [powerapps-docs/developer/model-driven-apps/open-forms-views-dialogs-reports-url.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/open-forms-views-dialogs-reports-url.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Sinha-Abhisek. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@Sinha-Abhisek 
Thanks for your feedback.

Issues created here are to provide feedback about the documentation. Your suggestion is a feature request. Recommend that you offer it here [Power Apps Ideas](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas)

If the feature becomes available, you should find documentation about it.

Best regards
