### ISSUE TITLE
It's very hard to find doc what I need. Very poor and not-organized document

### ISSUE THREAD

**Issue by full-devfun** [MicrosoftDocs/powerapps-docs#3786]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b341204a-75e0-2439-f4fa-b62d2e64fee9
* Version Independent ID: 82b48d34-c96d-6508-36fe-7bcb5870b52f
* Content: [Impersonate another user using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/impersonate-another-user-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/impersonate-another-user-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/impersonate-another-user-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @full-devfun. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@full-devfun 
Thanks for your feedback.
Sorry to hear that this content isn't meeting your expectations.

Is your feedback about the Web API content in general or this specific topic?
Can you provide any specific items that you feel would help?

**Comment by JimDaly** [comment]
@full-devfun 
I haven't heard back from you with any specific, actionable feedback. So closing this.
