### ISSUE TITLE
Just a note/suggestion

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#379]
Greetings,
This is just an observation...

Definitions:
"this page" refers to:
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/entity-relationship-behavior
"the larger page" refers to:
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-edit-entity-relationships
"the source page" refers to:
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-entity-lookup

I reached "this page" from "the source page":
specifically, from the link at the end of the "Add advanced relationship behavior" section.

Observations:
&gt; "this page" does not exist in the TOC
&gt; the complete content of "this page" is available within "the larger page"

In case "this page" is planned for removal, I believe that links to "this page" will be gradually replaced with links to "the larger page"?
If yes, then the link in "the source page" (indicated above) is a candidate:
instead of leading to "this page" the link could/should possibly lead to:
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-edit-entity-relationships#entity-relationship-behavior

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89438e2d-ba6c-b275-ba64-f30530f1f3a1
* Version Independent ID: ff3add84-438e-ef30-9107-c311d8316844
* Content: [Entity relationship behavior (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/entity-relationship-behavior#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/entity-relationship-behavior.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/entity-relationship-behavior.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@a-zaf - Thank you for your feedback. You suggestions have been incorporated and the entity-relationship-behavior topic being removed and a redirect in place to the section in the create-edit-entity-relationships topic. 
Closing issue.
