### ISSUE TITLE
One important limitation is not mentioned

### ISSUE THREAD

**Issue by rezanid** [MicrosoftDocs/powerapps-docs#3799]
One important limitation is not mentioned in the limitation section. Dataflows do not support state and status fields. Lack of support for these two very important columns will render dataflow useless for majority of data migration/ integrations and better be mentioned here in this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2f8a4d-5b76-0fed-c0cb-6e2f06a4240e
* Version Independent ID: 6b6cf6ec-87c8-f109-98ce-9181cbfb736e
* Content: [Migrate data between Microsoft Dataverse environments using the dataflows OData connector - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-odata-dataflows-migration)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-odata-dataflows-migration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-odata-dataflows-migration.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @denisem-msft
* Microsoft Alias: **demora**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rezanid. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@rezanid 
Thanks for your feedback.

I expect that you are referring to this [Field mapping considerations for standard dataflows > Known Limitations](https://learn.microsoft.com/en-us/power-query/dataflows/get-best-of-standard-dataflows#known-limitations)

> Mapping to Status and Status Reason [fields](https://learn.microsoft.com/en-us/powerapps/developer/data-platform/define-custom-state-model-transitions#what-is-the-state-model) is currently not supported.

There are several other limitations also included there.

@denisem-msft 
Will you update this topic with the limitations?

**Comment by JimDaly** [comment]
Added this limitation and link to other field mapping limitations.
