### ISSUE TITLE
Trivial edit/typo

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#380]
Hello again,
This is almost nothing (sorry to bother for so little)

Top of the page, second paragraph, last sentence:
"The icon is shown for the records that have are related using the hierarchical relationship."
&gt;&gt; should delete "have" , 
to become: " [...] the records that are related [...] " 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97939d77-ee12-f8d2-8904-822c8130f303
* Version Independent ID: 863d3744-d5a0-6bd4-ab0d-03aeb66dabab
* Content: [Visualize hierarchical data with model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/visualize-hierarchical-data)
* Content Source: [powerapps-docs/maker/common-data-service/visualize-hierarchical-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/visualize-hierarchical-data.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@a-zaf - Thank you for your feedback. You suggestion has been incorporated into the topic.
