### ISSUE TITLE
Options and screenshot has changed

### ISSUE THREAD

**Issue by shammyowens** [MicrosoftDocs/powerapps-docs#3800]
The settings button is now "properties" and the fly out menu screenshot is different e.g. enable connections is now "Can have connections" in the "Rows in this table" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 366b3b87-1b29-ddef-5060-ea189a480bda
* Version Independent ID: fd970513-3ef5-7fd8-fa20-f02ca7c76ebc
* Content: [Configure connection roles - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/configure-connection-roles)
* Content Source: [powerapps-docs/maker/data-platform/configure-connection-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/configure-connection-roles.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @shammyowens. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@shammyowens - Thanks for your feedback. The article has been revised to reflect the current experience and will be published live in a few hours.

Closing issue.
