### ISSUE TITLE
Mention using TDS endpoint from other apps created with tools such as C# and ADO.NET

### ISSUE THREAD

**Issue by jrichview** [MicrosoftDocs/powerapps-docs#3803]
This page REALLY needs to say something about making SQL queries from a non-power platform application such as C# and ADO.NET or whatever else.  Can it be done? If so, link to explanation? If not, clearly state that it's NOT supported.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ead09d9-3e51-04ce-dc6e-ac9bb59816ec
* Version Independent ID: 94d19f8d-3c5e-8ed9-53ee-4b6173f49144
* Content: [Use SQL to query data (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-sql-query.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jrichview. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@jrichview We intentionally state just what is supported. Thanks for the feedback.
