### ISSUE TITLE
sharing account / opportunity?

### ISSUE THREAD

**Issue by ToshiakiKa** [MicrosoftDocs/powerapps-docs#3804]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/92855459/200172730-c158f6e4-8451-4e1a-a0fd-a1c48b4f9e41.png)

For example, in an organization that gives salespeople Basic read and write access to accounts, **a salesperson can share an opportunity** with another salesperson so that they can both track the progress of an important sale.

It is an account instead of opportunity? 
It doesn't make sense for me if it is regarding to opportunity.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 507f3fb4-078a-fa09-cc1b-b10b2097c7c0
* Version Independent ID: 00b1b2e4-55e5-6cce-6943-63ca584dce34
* Content: [Sharing and assigning (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/security-sharing-assigning)
* Content Source: [powerapps-docs/developer/data-platform/security-sharing-assigning.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/security-sharing-assigning.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ToshiakiKa. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@ToshiakiKa The point being made in the article is that sharing table data (i.e., an opportunity) gives access of that data to users who would not normally have access to that data due to their security role.
