### ISSUE TITLE
Spelling error: "to" is spelled as "tor"

### ISSUE THREAD

**Issue by akankshagupta28** [MicrosoftDocs/powerapps-docs#3805]
Hi,

There is a spelling mistake: "to" is spelled as "tor" in
"Collaborate – Allows end users to see all records and create new records. But they can only edit or delete their own records. An example for when you want to use collaborate is "up votes" in the Ideas the Perspectives app. You want each user of the app to view the up-votes of other users. But they shouldn't be able **tor** change the votes for any users other than their own."

Thanks & Regards, Akanksha Gupta

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3a31b46-1ff1-ca57-eb2f-613fea8e7cbe
* Version Independent ID: 9e4785b8-c7f4-46f8-e0e0-43962eec6e8a
* Content: [Granting permission to tables in Dataverse for Microsoft Teams (contains video) - Power Apps](https://learn.microsoft.com/en-us/power-apps/teams/dataverse-for-teams-table-permissions)
* Content Source: [powerapps-docs/teams/dataverse-for-teams-table-permissions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/dataverse-for-teams-table-permissions.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **saperlmu**

**Comment by KumarVivek** [comment]
This is fixed now.
