### ISSUE TITLE
Error in documentation "Tutorial: Create an ASP.NET Core Blazor WebAssembly app using Microsoft Dataverse"

### ISSUE THREAD

**Issue by jfremmegaard** [MicrosoftDocs/powerapps-docs#3807]
If you follow the documentation you get error when you try to log on via AAD. The guide shows how to create an app registration with web type, but I had to change this to SPA in Azure AD to get it working.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf9c66a-0722-7548-84d4-8d1e6771c8b7
* Version Independent ID: c66f2f97-f263-8e88-1277-e23ed81b84f3
* Content: [Tutorial: Create an ASP.NET Core Blazor WebAssembly app using Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/walkthrough-blazor-webassembly-single-tenant)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-blazor-webassembly-single-tenant.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/walkthrough-blazor-webassembly-single-tenant.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jfremmegaard. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
I have updated and tested the tutorial to verify it works. 
Some things changed and I've removed unnecessary steps.
