### ISSUE TITLE
Certified Visual

### ISSUE THREAD

**Issue by JoeChamp** [MicrosoftDocs/powerapps-docs#381]
When will this be a certified visual? We don't allow use of uncertified custom visuals. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f94c3-694a-6d09-3a4f-e4b741684822
* Version Independent ID: c952e698-a2bf-a47d-acbd-a96a8a922636
* Content: [PowerApps custom visual for Power BI - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by zavaschi** [comment]
With July 2019 release, it is now certified. https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-july-2019-feature-summary/#powerapps

**Comment by tapanm-MSFT** [comment]
https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-july-2019-feature-summary/#powerapps

PowerApps visual is now certified
The PowerApps marketplace visual is now certified. This means you can now see the PowerApps visual when exporting to PowerPoint and when you get report subscription emails.
