### ISSUE TITLE
Incorrect image for column edit page.

### ISSUE THREAD

**Issue by mgowing** [MicrosoftDocs/powerapps-docs#3815]
This page has incorrect screenshots for how the new column editing experience looks for calculated fields.

![image](https://user-images.githubusercontent.com/68403079/200887636-1c6e2c54-cfb4-4c66-92e1-c19f56e78c1b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f212137-6b88-c06c-025d-c05e6b74c10f
* Version Independent ID: 61abe448-2b0d-29bd-90bb-63899f0f92dc
* Content: [Define calculated columns in Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/define-calculated-fields)
* Content Source: [powerapps-docs/maker/data-platform/define-calculated-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/define-calculated-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mgowing. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@mgowing - Thank you for your feedback. The article has been updated to reflect the current experience and will be published in a few hours. 
Closing issue.
