### ISSUE TITLE
I can't get the timeline to show appointments and task for a custom entity in Power Pages (not Portal)

### ISSUE THREAD

**Issue by 2ATCaroline** [MicrosoftDocs/powerapps-docs#3818]
Hi,

I have changed the setting 'CustomerSupport/DisplayAllUserActivitiesOnTimeline' to true.
I have changed the view 'Portal Timeline' on Activities to include Tasks and Appointments.

I have created a listview and form to view appointments in powerpages and there I see the appointment where my custom entity is set as regarding and the power page contact (with a username and password) as the required attendee.

However, I also have a timeline on my custom entity and there I do not see this appointment. I added table permissions through both main and subpermissions on the custom entity and appointments. The timeline is set to show appointments and in the model driven app I see them. But I don't see the appointment in the timeline in the power page app. 

What am I missing? Is this possible at all? 

Edit: I also added sub permissions to the acitvitypointer and ofcourse synced the site several times. But I still don't see the appointment in the timeline on the custom entity form view in Power Pages.

**Comment by 2ATCaroline** [comment]
Aha, in classic mode the timeline control has tab: webclient properties
There you have an option: Default tab
If I change that to Activities I see the activities on the power page from the custom entity.
However, then I don't see the Notes anymore... nor the uploaded attachments.
Is there any way to see both? 
I tried adding a second timeline control (which is only possible in the modern view, but then you can switch back to classic and change the properties) but then I get the following message (Dutch) in the portal:
notescontrol veld komt meerdere keren voor op dit formulier. Alleen het eerste veld wordt weergegeven in de gebruikersinterface
which translates to something like:
notescontrol field is set multiple times on this form. Only the first field will be shown in the userinterface.

Is there a way to show both notes and activities in the timeline on the powerpage or should you then use acitvities and use the portal reactions as a way to show notes and upload attachments?

**Comment by 2ATCaroline** [comment]
Also if I give rights on the acitvity pointer as a subright from my custom entity I see all related activities, even if I didn't give permissions for appointments (for example) specifically. Plus I also see the appointments where the external user is not an activity party. If I give rights to the activity pointer as a subright of activity parties related to the external user I don't see anything in my timeline. Am I missing something here? Please advice.

**Comment by nickdoelman** [comment]
Thank you for your feedback. The ability to show both notes and activities on the same form for a custom table is currently not supported with configuration. Please log this as an idea on https://aka.ms/MPP_ideas 
Also note that security is applied to the activity table, and not to the activity types themselves. See https://learn.microsoft.com/power-apps/developer/data-platform/activity-entities for more information.
