### ISSUE TITLE
HTTP Header  settings for Power Pages does not explain where exactly are the settings.

### ISSUE THREAD

**Issue by skfd** [MicrosoftDocs/powerapps-docs#3819]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 443edf18-65c5-7984-1ff5-172b15462980
* Version Independent ID: df150eb3-67ca-b3cb-37ab-7be1a3823cc0
* Content: [Set up HTTP headers in portals - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/cors-support)
* Content Source: [powerapps-docs/maker/portals/configure/cors-support.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/cors-support.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @skfd. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback. The Http headers are configured by using [site settings](https://learn.microsoft.com/power-apps/maker/portals/configure/configure-site-settings).
