### ISSUE TITLE
React components inside index.ts

### ISSUE THREAD

**Issue by jordimontana82** [MicrosoftDocs/powerapps-docs#382]
Hi,

I was trying to setup a very basic sample component based on the Angular flip component example, but using React components instead. Given ControlHost is already using react to render the component's HTML,  how is the best way to include our React component into the main ComponentHost via the init method? 

Thanks!

**Comment by jordimontana82** [comment]
Example I want to include this very simple example: 

![image](https://user-images.githubusercontent.com/3968950/57587838-f3fc5080-750b-11e9-8e2b-7614585a8197.png)


To be rendered inside the container parameter we get from the init method?

**Comment by jordimontana82** [comment]
When I try to render that component inside the container like  this:

![image](https://user-images.githubusercontent.com/3968950/57588044-a59c8100-750e-11e9-8552-7f4cb139706d.png)

![image](https://user-images.githubusercontent.com/3968950/57588046-adf4bc00-750e-11e9-98a8-535b94d0e892.png)

it just can't find the Component namespace (it fails in the harness.js main eval() function) 

So  how to achieve this, if possible?

**Comment by jordimontana82** [comment]
Also, was using that ReactDomRenderer class as I couldn't use it direclty in the main index.ts file, given the manifest fiel doesn't support .tsx files, just .ts?

**Comment by Nkrb** [comment]
@jordimontana82 Please add your issues [here](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Closing this issue.
