### ISSUE TITLE
The "Create your first component" -> "Implementing manifest" documentation section is incomplete

### ISSUE THREAD

**Issue by LozzieDuff** [MicrosoftDocs/powerapps-docs#3823]
In the "Create your first component" documentation -> "Implementing manifest" section ...

https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript#implementing-manifest

The steps do not describe that you must add the type-group element ...

      <type-group name="numbers">
         <type>Whole.None</type>
         <type>Currency</type>
         <type>FP</type>
         <type>Decimal</type>
      </type-group>

This causes an error when running "npm run build":  "<property> element with name 'controlValue' references a non-existent <type-group>".

But, in the summary where it says: "The overall manifest file should look something like this:" it does include this element.

For newbies this is annoying, as they might have followed the steps rather than simply copy pasting the "overall manifest file"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript#implementing-manifest)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LozzieDuff. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@LozzieDuff 
Thanks for the specific, actionable feedback.
I've created a workitem to review this topic with an eye on the specific issue you raised.

If you wish, we do accept contributions to the repo.

Workitem: 3034672
