### ISSUE TITLE
Three small edits

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/powerapps-docs#383]
Greetings,

(Edit 1: little typo)
In "How solutions are applied" / "Unmanaged Customizations", last sentence:
"You can customize any of the solution components that do not have managed properties that prevent you from customization them."
&gt;&gt; should be: " [...] that prevent you from customizing them."

(Edit 2: tiny suggestion/improvement)
In "Solution dependencies", first paragraph, first sentence:
"Because of the way that managed solutions are layered some managed solutions can be dependent on solution components in other managed solutions."
&gt;&gt; a comma would be useful after "layered"

(Edit 3: missing word)
Same paragraph, third sentence:
"You may need to install a “base” managed solution first and then you can install a second managed () that will further customize the components in the base managed solution."
() missing: "solution"
should be: " [...] install a second managed solution that will further customize [...] "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a7715a-2b1b-29ed-99ac-0003429d5b4d
* Version Independent ID: be31d36c-9be0-cc62-1ea3-b8514fe569d9
* Content: [Work with solutions in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/solutions-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/solutions-overview.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by a-zaf** [comment]
Please note: I did not "strike-through" that text.
I just put a tilda between those parenthesis. Apparently, it got interpreted as a strike-through. This was not my intention.
Thank you.

**Comment by Mattp123** [comment]
@a-zaf - Thank you for your feedback. You suggestion has been incorporated into the topic.
