### ISSUE TITLE
addOnPostSave not being added to the navigation menu

### ISSUE THREAD

**Issue by ThreeTen22** [MicrosoftDocs/powerapps-docs#3833]
Mainly just:
[addOnPostSave](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/postsave)

does not appear under the formContext.data.entity dropdown:
![image](https://user-images.githubusercontent.com/10577809/202336502-43dee8ed-c4ae-4199-a81e-63729a03cfdf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5249188f-b583-4adc-4987-af5fe42e880a
* Version Independent ID: fba77804-3237-c925-0aa4-84eea18da1a8
* Content: [formContext.data.entity (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-data-entity)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ThreeTen22. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@ThreeTen22 
Thanks for your feedback.
I've fixed this. removeOnPostSave was also not included.
Change should go live after noon PST.

Note: PR 7330
