### ISSUE TITLE
Soluzione NorthWind Error

### ISSUE THREAD

**Issue by SilvioVicentini** [MicrosoftDocs/powerapps-docs#3838]
![Cattura](https://user-images.githubusercontent.com/118532282/202695315-b491a0f4-a77c-4df3-948b-23cc9331954a.JPG)
La soluzione mi da questo errore
Sono molto interessato per provarla

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5475653-e112-f407-b0de-ecad06bac5bf
* Version Independent ID: 9f109131-06e3-5f88-1205-233d2b6c4bf0
* Content: [Install Northwind Traders database and apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/northwind-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/northwind-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/northwind-install.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SilvioVicentini. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/

Closing this issue.
