### ISSUE TITLE
Performant is not a word

### ISSUE THREAD

**Issue by hzigli** [MicrosoftDocs/powerapps-docs#384]
The red squiggly lines should have been an indicator. (from the first sentence on the page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58ecc49-fb0d-9b63-ad2b-fd2134e7bd72
* Version Independent ID: 6f1a2c83-46b7-e8d8-4057-fa9660c9eef6
* Content: [Use change tracking to synchronize data with external systems (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-change-tracking-synchronize-data-external-systems#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/use-change-tracking-synchronize-data-external-systems.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-change-tracking-synchronize-data-external-systems.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by hzigli** [comment]
Apparently it is just not a word in American English (found it in the Oxford dictionary).

**Comment by susikka** [comment]
@hzigli **Performant** has been changed to **efficient** in the doc. Updated doc will be published soon.

Thanks @brandonsimons for resolving this.

Closing this issue now.
