### ISSUE TITLE
.getVisible() and .setVisible method pages are titled incorrectly; documentation should be improved re: visibility behavior

### ISSUE THREAD

**Issue by lmastin** [MicrosoftDocs/powerapps-docs#3841]
Hi there!

1. The page title is "formContext.getVisible"; which implies that that the .getVisible() method belongs to the formContext object. This is inaccurate; the method belongs to the Control object. (Other method pages in the "Control" section are simply titled with the name of method; in this case, it would be "getVisible".)

2. The page title for the corresponding .setVisible() method is also inconsistent. (Here, it reads "control.setVisible".)

3. It would be helpful if the page might mention how visibility actually works. Testing would seem to suggest, for instance, that if a Control is contained within a Section, and that Section is hidden, then the Control will still return a .getVisible() result of "True" (which will be unintuitive for many developers).

Thanks in advance!
Lauren

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a513e870-1b4e-3c1f-c562-2812c3b5b06f
* Version Independent ID: f2244b31-644a-42a0-ac36-0f52e7816240
* Content: [formContext.getVisible (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/getvisible)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getVisible.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getVisible.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@adrianorth  & @HemantGaur 
Based on @lmastin testing report, I've added a note to call out: 

> `getVisible` only returns whether the control is configured to be visible. `getVisible` will return true when the control is within a section or tab that is hidden.

I think this is correct. Can you confirm?

**Comment by lmastin** [comment]
@JimDaly - at least from my testing, it might be more accurate to say:

> `getVisible` only returns whether the control itself is configured to be visible; and not its parent objects (such as section or tab). As such, `getvisible` may return 'true' even if the control is de facto hidden. If you need to determine whether the control is visible to the user or not, call `getVisible` for the control, and all parent objects.'

**Comment by JimDaly** [comment]
@lmastin 
I've updated the topic with a note to call out the behavior as it is and that it doesn't include whether the parent control is hidden or not. It contains the same information in fewer words.

I think this is a good opportunity to include a small sample function. My JavaScript is a little rusty, but something like this:

```
function isControlReallyVisible(control){
  
	var sectionIsVisible = control.getParent().isVisible();
	var tabIsVisible = control.getParent().getParent().isVisible();

	return control.isVisible() && sectionIsVisible && tabIsVisible;
}
```

It would demonstrate the problem and provide a way to resolve it.
If you have written and tested a function like this, please provide it and I can add it to this topic.

**Comment by lmastin** [comment]
@JimDaly - your example function looks good! The only improvements I can think of are:

1. The `.isVisible()` method calls should be changed to `.getVisible()`.
2. Can `.GetParent()` return null / undefined / otherwise fail (and cause an exception)?

**Comment by JimDaly** [comment]
I think we have addressed the main issue. There is always room for improvement, such as adding a sample.
