### ISSUE TITLE
Calling .setNotification() on a hidden control

### ISSUE THREAD

**Issue by lmastin** [MicrosoftDocs/powerapps-docs#3842]
Hi there!

There is a lack of intuitive behavior on the part of the .setNotification() method; which should be documented. Specifically:

If you call .setNotification() on a Control that is itself visible, but is the child of a Section or Tab that isn't visible, then the call will succeed. If this occurs while saving, it will result in a situation where a message will be shown at the top of the form (showing that the save operation cannot be completed, because there are validation errors present); but the Control in question will remain hidden (as will the validation message that would normally be shown underneath it).

As such, the user will be unable to save, and unable to correct the validation error.

The solution to this problem would either be to test for the visibility of the Control and any parent objects (if possible) prior to calling .setNotification(); or noting that when hiding Tabs or Sections, that all child Controls should also have their visibility set to false, too.

Thanks and kind regards,
Lauren

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc26bb9c-dde5-cf97-9ea0-2d6940299088
* Version Independent ID: 944219c6-532e-ed19-3e05-d012e3b716c7
* Content: [setNotification (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/setnotification)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setNotification.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setNotification.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@lmastin 
Thanks for your feedback. 
We are making changes to address this.

**Comment by lmastin** [comment]
@JimDaly - You're welcome! Thanks for looking into this.

Obviously this is outside of the purview of documentation; but if you talk to the dev team directly, you might want to bring up with them that the core behavior here (that parent objects may be hidden; that this defacto hides child objects; but .getVisible() can still return 'true' for said child objects) is both unintuitive, and requires client API users to check three objects for visibility (the child, parent section, and parent tab) rather than just the child.

(How they might want to solve that is up to them - maybe they should add an overload to the method with a flag specifying whether to check the visibility of just the child object, or the visibility of all objects in the chain? Anyhow.)

**Comment by JimDaly** [comment]
Added this content:

```
> [!NOTE]
> Always make sure that the control you are using `setNotification` with is visible on the form.
>
>`setNotification` will not return an error if you use it on a control that is visible but is within a section or tab that isn't visible. When saving a record `setNotification` will display a message at the top of the form as a validation error. If the control is not visible because it is within a hidden parent section or tab, the user cannot fix this.
```
