### ISSUE TITLE
Title reads "formContext.ui Tab Sections", when object is named "Section"

### ISSUE THREAD

**Issue by lmastin** [MicrosoftDocs/powerapps-docs#3843]
Hi there!

The title of this page is somewhat confusing - the subject is the Section object (or 'sectionObj'); but the title refers to these as "Tab Sections". (Additionally, other pages are titled using namespace format; so in this case, it should read "formContext.ui.sections".)

Thanks and kind regards,
Lauren

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04427101-255e-12cb-b895-1748adff5106
* Version Independent ID: 04427101-255e-12cb-b895-1748adff5106
* Content: [formContext.ui Tab Sections (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-ui-tab-sections)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-tab-sections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-tab-sections.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lmastin. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@lmastin 
Thanks for your feedback. Discussing this with the dev team.

**Comment by JimDaly** [comment]
We renamed the topic and re-organized the table of contents to better represent the hierarchy.
Let's see if this helps.
