### ISSUE TITLE
Save/publish actions not where this article describes

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/powerapps-docs#3844]
This page no longer seems to represent what's going on in the UI. I finally found the save/publish actions in the upper right of the page:
![image](https://user-images.githubusercontent.com/1295627/203369465-0e44bcd9-81cd-4512-845b-8a12e7fef825.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1580f2c-28f4-b295-df77-9a43ef5ed0f1
* Version Independent ID: 96e5ed45-be60-cd80-26f6-fe07e7adb118
* Content: [Save and publish canvas apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/save-publish-app)
* Content Source: [powerapps-docs/maker/canvas-apps/save-publish-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/save-publish-app.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @amchern
* Microsoft Alias: **emcoope**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sympmarc. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@sympmarc - Thank you for the feedback. I'm working on updating this help topic with the latest information. Stay tuned for updates.

Thanks,
Mints

**Comment by mduelae** [comment]
@sympmarc The topic has been updated to reflect the latest information.
