### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by LindaCicero** [MicrosoftDocs/powerapps-docs#3847]
[Enter feedback here]
There is a typo in this sentence (I've bolded it below):
"Code components can be **including into** a solution..."
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 709f9e54-c965-5dc4-b64f-3d90037626be
* Version Independent ID: 45011eec-04a4-01b4-2ab8-70677e910f3b
* Content: [What are code components? - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/custom-controls-overview?source=recommendations)
* Content Source: [powerapps-docs/developer/component-framework/custom-controls-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/custom-controls-overview.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LindaCicero. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@LindaCicero 
Thanks for your feedback. I've fixed the sentence.
