### ISSUE TITLE
Regarding "Arabic and Hebrew languages are not supported on the Power Pages preview."

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#3859]
can you please clarify/correct where exactly Hebrew is not supported?
With Power Portals being renamed to Power Pages, this is difficult to follow
but
a) Power Pages is no longer in preview
b) on make.powerpages Hebrew is not offered as a language, even if Hebrew is installed on the org,
so the "not supported" statement should probably be

"Arabic and Hebrew languages are not supported on make.powerpages yet"

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  

We have recently updated our documentation to indicate that Arabic and Hebrew languages are not supported when creating a site using [Power Pages](https://learn.microsoft.com/en-us/power-pages/getting-started/create-manage) or using the Power Pages [design studio](https://learn.microsoft.com/en-us/power-pages/getting-started/use-design-studio). 

You will need to create and edit Arabic and Hebrew language sites using [Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/create-portal) and the legacy [portals Studio](https://learn.microsoft.com/en-us/power-apps/maker/portals/portal-designer-anatomy).

See https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/enable-multiple-language-support#supported-languages

Closing this issue.
