### ISSUE TITLE
API reference links are broken

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerapps-docs#386]
Somehow, API Refernece links under "Related Topics" is bringing me to the page that does not exist:

https://docs.microsoft.com/en-ca/powerapps/developer/control-framework/overview

Looks like those links should be pointing to this url instead:

https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/index

It seems to be the same for all samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae37cba-3abf-4174-2797-2bd6d73d3440
* Version Independent ID: 6d73415a-7e52-e23e-40df-5958620811db
* Content: [Increment component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/increment-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/increment-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/increment-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ashlega Thanks for the feedback. We have updated the docs and pushed to live. Closing this issue.
