### ISSUE TITLE
dependency table unproperly documented

### ISSUE THREAD

**Issue by felipe-molina-cashme** [MicrosoftDocs/powerapps-docs#3863]
Why document a table without actually documenting it?

For example, the columns

[DependentComponentObjectId](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/dependency#BKMK_DependentComponentObjectId)
[RequiredComponentObjectId](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/dependency#BKMK_RequiredComponentObjectId)

Are GUIDS.. great!

but what is the table they refer to? What do does guids mean? Why is it so hard to document the table properly?
There is not even a brief description of the table purpose and what it represents.

When will Microsoft document this table?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3392fc7-273a-9b89-dc1a-2b3753fe9569
* Version Independent ID: b3e009d5-19ca-67c5-86a6-18bbdd2a97fc
* Content: [Dependency table/entity reference (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/dependency)
* Content Source: [powerapps-docs/developer/data-platform/reference/entities/dependency.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/reference/entities/dependency.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment]
@felipe-molina-cashme Thanks for pointing out the missing column descriptions on the page. The table reference pages are generated from the web service metadata and are not written by hand. I will contact the engineering team to get the missing descriptions added to the metadata. This may take a few months to get resolved.

Thanks for the feedback.
