### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by gjbundy** [MicrosoftDocs/powerapps-docs#3865]
In the opening sentence: This sample shows how to send an email using [SendEmailRequest](https://learn.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.sendemailrequest) message. You can download the sample from [here](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/orgsvc/C%23/**SenEmail**). 

The download the sample from here link needs to be updated (it's missing the d in SendEmail, currently reads C%23/**SenEmail**)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 538f3a1a-423a-8b79-3eea-69edb9f5c65f
* Version Independent ID: 0dcb5000-3722-8894-7135-36300f8bce06
* Content: [Sample: Send an email (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/send-email)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/send-email.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/send-email.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gjbundy. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@gjbundy 
Thank you for reporting this. I've fixed it.
Change should be applied around 5PM PST.
