### ISSUE TITLE
Missing the definition of filter h (| h }}>)

### ISSUE THREAD

**Issue by lyg3010** [MicrosoftDocs/powerapps-docs#3868]
Here are some liquid code with the filter 'h' in section metafilters
https://learn.microsoft.com/en-us/power-apps/maker/portals/liquid/liquid-filters#metafilters

for example:
                  <label>
                    <input
                      type={{ type | h }}
                      name={{ filter.id | h }}
                      value={{ option.id | h }}
                      {% if option.checked %}
                        checked=checked
                        data-checked=true{% endif %}
                      />
                    {{ option.label | h }}
                  </label>

What is the function of filter 'h'?
Since I can't find the definition of filter h in the 'Available Liquid filters' section, is the filter 'h' missing in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f21735f3-2a17-cfdc-71e7-f920fbf6749d
* Version Independent ID: c2fa90c4-0815-6617-358e-915dd3b76e24
* Content: [Available Liquid filters - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/liquid/liquid-filters#array-filters)
* Content Source: [powerapps-docs/maker/portals/liquid/liquid-filters.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/liquid/liquid-filters.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lyg3010. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback. This will provide an HTML representation of an attribute. In most cases, this will be simply a string. Documentation updated. [h filter](https://learn.microsoft.com/power-pages/configure/liquid/liquid-filters#h)
