### ISSUE TITLE
Prefix Space while setting Look Up in Example 4  

### ISSUE THREAD

**Issue by Rahulpaithane** [MicrosoftDocs/powerapps-docs#3869]
In The "Example 4: Open a quick create form" on this page there's a space in prefix, while setting up the look up "preferredsystemuseridname"  key, it should be `formParameters["preferredsystemuseridname"] = "Admin user"; // Name of the user.`
![image](https://user-images.githubusercontent.com/51539313/205062426-f9600abe-7df1-4597-a667-64bc07b0fbde.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b204ee0a-69a2-e52d-f110-2291be66c1af
* Version Independent ID: 8ac980df-6b5f-2b33-707f-11efb597ba6a
* Content: [openForm (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openform)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Rahulpaithane. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@Rahulpaithane 
Thanks for your feedback.
I've removed the space.
