### ISSUE TITLE
instructions are missing a step for configuring id_token

### ISSUE THREAD

**Issue by MikeStall** [MicrosoftDocs/powerapps-docs#387]
Following instructions will get you this error:
    AADSTS700054: response_type 'id_token' is not enabled for the application.  

You must also follow steps here: https://stackoverflow.com/a/53063247/534514 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f1b8580-0f68-7d02-fd19-4c087e6659b9
* Version Independent ID: 3b74fd46-f2af-e44d-1199-6e2494669576
* Content: [Walkthrough: Registering and configuring SimpleSPA application with adal.js (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-registering-configuring-simplespa-application-adal-js#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/walkthrough-registering-configuring-simplespa-application-adal-js.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/walkthrough-registering-configuring-simplespa-application-adal-js.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by doriyoutse** [comment]
if you're getting the error mentioned above, you may subsequently face this error: “AADSTS50011: The reply address does not match the reply addresses configured”

adding the redirect uri for the registered app as suggested in this article will resolve the issue: https://www.koskila.net/how-to-fix-aadsts500113-no-reply-address-is-registered-for-the-application-error/

**Comment by noorrocks** [comment]
This won't be an issue if instructions are followed properly

**Comment by phecke** [comment]
@MikeStall

Issue resolved.
