### ISSUE TITLE
Incorrect link for Quick Create

### ISSUE THREAD

**Issue by julians1966** [MicrosoftDocs/powerapps-docs#3870]
The link for Quick Create forms is incorrect and take you to the page for Quick View forms

[Create and edit quick create forms](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/create-edit-quick-view-forms)

It should be https://learn.microsoft.com/power-apps/maker/model-driven-apps/create-edit-quick-create-forms

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1d2def2-a04e-6f5d-3c59-41ac8a441130
* Version Independent ID: 966fe318-daea-a28a-5f1e-e95233c48ff0
* Content: [Type of model-driven app forms in Power Apps - Power Apps](https://learn.microsoft.com/en-gb/power-apps/maker/model-driven-apps/types-forms)
* Content Source: [powerapps-docs/maker/model-driven-apps/types-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/types-forms.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @julians1966. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@julians1966 - Thank you for helping improved the Power Apps documentation. The article has been updated to direct to the correct article.
Closing issue.
