### ISSUE TITLE
Global Choices can now be done in the modern interface

### ISSUE THREAD

**Issue by rcatbp** [MicrosoftDocs/powerapps-docs#3873]
Not sure if I'm missing something, the text reads they can't.

![choice-list](https://user-images.githubusercontent.com/96841324/205363243-f6483a05-72ac-455f-a0ab-d20984539dce.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ebc5ae1-357e-f9d1-ded9-a9794a8ccc6c
* Version Independent ID: 2fa245cd-9457-66f0-428e-34dcc585f2b4
* Content: [Create and edit global choices for Microsoft Dataverse using solution explorer - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-global-option-sets-solution-explorer)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-global-option-sets-solution-explorer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-global-option-sets-solution-explorer.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rcatbp. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@rcatbp - Thank you for helping improve the documentation. The article has been updated to remove any make.powerapps.com limitations for global choices column creation and a link has been added to the article that covers the feature.
Closing issue.
