### ISSUE TITLE
Where is the "Component Pane" in Step 6

### ISSUE THREAD

**Issue by ablockmedt** [MicrosoftDocs/powerapps-docs#3874]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e65187d6-12e3-8244-e6fc-a82cef869bf9
* Version Independent ID: 54f6c6fa-00c7-8ab9-f1a7-02517b1c3601
* Content: [Manage page permissions - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/webpage-access-control)
* Content Source: [powerapps-docs/maker/portals/configure/webpage-access-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/webpage-access-control.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ablockmedt. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
The component panel is what appears on the right side of the screen when a page is selected.
