### ISSUE TITLE
XRM.WebAPI doesn't actually exist as far as I can tell

### ISSUE THREAD

**Issue by peteravila** [MicrosoftDocs/powerapps-docs#3877]
[Enter feedback here]
Don't talk about stuff that obviously doesn't exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02f0fc25-caf0-55f7-c18a-163abc84cf0f
* Version Independent ID: ef16aa0d-a64b-db11-8967-1a7c917814f9
* Content: [Client API Xrm object for model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/clientapi-xrm)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/clientapi-xrm.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/clientapi-xrm.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @peteravila. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@peteravila 

Thanks for your feedback. I note that you also opened issue 3878 for this topic as well.
How can we make the documentation better so that this isn't frustrating for you?

Client API is available through form scripts. We have a walkthrough to get started here : [Walkthrough: Write your first client script](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script)

In 3878 you say:

> Every time I try to use Xrm in code it doesn't know what the hell it is and I cannot find an iota of information on why

Can you be more specific about how you are trying to use [Xrm.WebApi](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi) and what you want to do with it?

**Comment by peteravila** [comment]
Yeah, sure, thanks for the help

I’m simply trying to reference it in Visual Studio Code in a .js file. It doesn’t let me get past the first period:

Xrm.WebApi.retrievRecord(…

I can’t find any info on how this becomes available. Is there a library, dll, etc I have to import or something else?...

**Comment by JimDaly** [comment]
@peteravila 

Visual Studio can only provide IntelliSense if there some class or class or library. The Xrm objects exist in the runtime of the page, there is no static class or library to reference. 

There are samples for Xrm.WebApi function here, for example: [retrieveRecord](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/retrieverecord).

The community have created TypeScript definitions that help provide auto-completion at design time. These, together with the debugging and Fiddler intercept links I sent can help make you more productive. For example, here is one post by an MVP: [Dynamics CRM Model-Driven Apps: Developing Frontend Code with Typescript, @types/xrm and webpack](https://temmyraharjo.wordpress.com/2020/12/11/dynamics-crm-model-driven-apps-developing-frontend-code-with-typescript-types-xrm-and-webpack/)

These can help with the development experience but aren't technically required. They are not created by or supported by Microsoft, so we don't provide documentation about using them.

Looking back on your experience, what change could we make to the docs that would have helped?

**Comment by peteravila** [comment]
OMG, so all I have to do is hit esc to dismiss the intelliSense? Amazing.

Thanks! I wish there were mention of that in the documents I read, and if there is, I never saw anything about that. What a curve ball, but thank you! I appreciate you contacting me and helping me understand what’s going on.

**Comment by JimDaly** [comment]
Seems like this is a case where Visual Studio was overly aggressive in trying to help us. Perhaps it is the [AI-assisted IntelliSense](https://learn.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio)? I didn't know that pressing Esc would cancel it. 

Thanks for reporting this. I'll try it out and keep an eye out for others experiencing similar issues. But I'm going to close this for now.

**Comment by peteravila** [comment]
Thanks, Jim. I sincerely appreciate your prompt reply and resolution to this. I was very frustrated when I reported the issue but now regret the sarcasm. You did a great job here. Very candid and straightforward.

Peter
