### ISSUE TITLE
How can we retrieve audit changes for a field using REST Web API? 

### ISSUE THREAD

**Issue by GeorgianaMihaela** [MicrosoftDocs/powerapps-docs#388]
Hello, 

Could you, please, provide an example on how to retrieve audit changes:
- who changed the record 
- when 
using REST?

We can do this with the SDK https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/sample-audit-entity-data-changes. 
But how can we achieve a similar result using web API? 

Thank you.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ce7ab1-bb27-0213-cf85-5b0a794b6365
* Version Independent ID: 9f3c5bf2-b35f-b391-1ede-8abbc7a87836
* Content: [Audit Entity Reference (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/reference/entities/audit)
* Content Source: [powerapps-docs/developer/common-data-service/reference/entities/audit.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/reference/entities/audit.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by GeorgianaMihaela** [comment]
Hi, is it possible to have an example? Thank you.

**Comment by iangpgh** [comment]
@GeorgianaMihaela In looking into this, I notice **audit EntityType** in the Web API Reference.
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/audit?view=dynamics-ce-odata-9
There isn't a sample, but System Solution includes the audit entity type.
Let me know if this helps at all. Otherwise, I will pass along this product feedback to the PM.

**Comment by iangpgh** [comment]
in-progress

**Comment by iangpgh** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.  
Closing this issue.

**Comment by iangpgh** [comment]
@Mattp123 - Closes #388
