### ISSUE TITLE
Customizing the Editable grid

### ISSUE THREAD

**Issue by gvc55** [MicrosoftDocs/powerapps-docs#3881]
The current page talks about the CellRederrerOverrides but nothing about the CellEditorOverrides. It will be great if the samples/document were complete since the CellEditors are a bit more involved.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 225f1305-7aea-3fdd-9a46-e0f258c670ff
* Version Independent ID: 225f1305-7aea-3fdd-9a46-e0f258c670ff
* Content: [Customized editable grid - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/sample-controls/customized-editable-grid-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/customized-editable-grid-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/sample-controls/customized-editable-grid-control.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gvc55. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@gvc55 
Thanks for your feedback.
As you said, this sample only provides example for customizing the rendering of cells, but nothing about cell editors.
Is there a particular scenario that you would like to see?

**Comment by JimDaly** [comment]
@jasongre  FYI

**Comment by JimDaly** [comment]
Thanks for your feedback. We are closing this issue because we are haven't gotten feedback from the feature team. If you're still experiencing the issue described here, please reopen or create a new issue.
