### ISSUE TITLE
Change tracking with non global permission

### ISSUE THREAD

**Issue by Glideh** [MicrosoftDocs/powerapps-docs#3883]
Tracking changes on an entity seems to be possible only for a user having the `prvReadEntity` with a **global** level. I think it should be mentioned in this page.

A user with limited `prvReadEntity`, even with business unit level does not allow `track-changes`, returning this message:

> SecLib::CheckPrivilege failed. User: xxxxxxxxxxxxxxxxxxxxxxxxxxx, PrivilegeName: prvReadAccount, PrivilegeId: xxxxxxxxxxxxxxxxxxxxxxxxxxx, Required Depth: Global, BusinessUnitId: xxxxxxxxxxxxxxxxxxxxxxxxxxx, MetadataCache Privileges Count: 7356, User Privileges Count: 586

_If there is a way to track changes on a limited scope (ie. user's scope), I'd be happy to know_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae183946-fb2a-1b2f-e199-273eb9a68d54
* Version Independent ID: 0cf78a90-f63b-af43-8075-c1cd4e934e7d
* Content: [Use change tracking to synchronize data with external systems (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-change-tracking-synchronize-data-external-systems)
* Content Source: [powerapps-docs/developer/data-platform/use-change-tracking-synchronize-data-external-systems.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-change-tracking-synchronize-data-external-systems.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Glideh. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@Glideh 
Thanks for your feedback.

To confirm my understanding, in other words:

If the type of record being tracked is for the account table, the user calling the SDK RetrieveEntityChanges message or using the Web API with `Prefer: odata.track-changes` request header applied must have global read access to the account table, otherwise the error you describe occurs.

I never tested this. I would have expected that items that the user does not have access to would never be returned, and therefore not tracked. But after thinking about it, records shared to that user would suddenly appear after they were created, and records where access was revoked would seem to just disappear without an actual deletion that could be tracked. So, I think it makes sense.

Looking to @Peakerbl for confirmation.

**Comment by Glideh** [comment]
That's exactly what happens (though I'm directly using the API without any SDK).
I was also expecting user's records to be returned, but I'm guessing Dynamics [Change Tracking](https://learn.microsoft.com/en-us/sql/relational-databases/system-functions/change-tracking-functions-transact-sql?view=sql-server-ver16) implementation only allows that for entire table context, which would explain why we can't `$filter` it.

I opened a [thread in the Dynamics community forum](https://community.dynamics.com/365/f/dynamics-365-general-forum/473391/web-api---change-tracking-a-subset-of-data) about it for more detail, because I think we should be able to combine any filter with Change Tracking.

**Comment by Peakerbl** [comment]
We have now checked in code and it is true that the user must have global access level, We will update the content.

**Comment by Glideh** [comment]
Thanks for your answer, do you know if there is any plan to allow that ?
This native SQLServer feature would seem to me that it could do (by joining the `CHANGETABLE()` result).

**Comment by JimDaly** [comment]
The topic has been updated to say:

> The calling user must have organization level read access to the table. If the user has limited read access, the system will throw a privilege check error. 

@Glideh 
We appreciate your feedback to help improve the documentation. 
I can't comment on future plans. You might try to reach out to @Peakerbl for a discussion on that.
Now that the docs have been updated, I will close this issue.
