### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by t9sgit** [MicrosoftDocs/powerapps-docs#3884]
Just a minor spelling mistake, or well missed letter.

#17 under "Create a translation Component"

listed as "copy and pate" instead of "copy and paste"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70b557d3-7967-698e-38e0-e28ad06df9df
* Version Independent ID: 55105264-7746-12ac-b3db-c34eb96b429f
* Content: [Build a multi-language app - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/multi-language-apps)
* Content Source: [powerapps-docs/maker/canvas-apps/multi-language-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/multi-language-apps.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **lunune**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Documentation has been fixed and the change will be visible soon.
