### ISSUE TITLE
Page lacks clarity and contains mistakes

### ISSUE THREAD

**Issue by nkatz01** [MicrosoftDocs/powerapps-docs#3886]
E.g. 
![image](https://user-images.githubusercontent.com/55924227/206263975-259565b1-f645-4921-952b-dcdfcc9a1e25.png)
 and 
![image](https://user-images.githubusercontent.com/55924227/206263448-a4cb1a7e-141e-4179-86fc-972b64efa32a.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c77997bb-3f55-7f7c-d041-b00f4d3af93e
* Version Independent ID: c77997bb-3f55-7f7c-d041-b00f4d3af93e
* Content: [Retrieve the history of audited data changes (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/auditing/retrieve-audit-data?tabs=sdk)
* Content Source: [powerapps-docs/developer/data-platform/auditing/retrieve-audit-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/auditing/retrieve-audit-data.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nkatz01. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@nkatz01 
Thanks for your feedback.
I've corrected the typos.
If there is anything else that is not clear, please feel free to re-open this and let me know what specific part is not clear.

**Comment by nkatz01** [comment]
Thanks for correcting. 

From memory there were more. 

My main difficulty was being able to distinguish when you were talking about [retrieving] a record in the Audit table\entity and when you were talking about [retrieving] the history of a record (where auditing is enabled and running) in **any** table.

**Comment by JimDaly** [comment]
I've asked for an editorial review of the topics in this area.
