### ISSUE TITLE
Use of "TeamOwned"

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#3888]
This page mentions `TeamOwned`:
> Records can be owned by users or teams. Set the [OwnershipType](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.entitymetadata.ownershiptype#microsoft-xrm-sdk-metadata-entitymetadata-ownershiptype) to [OwnershipTypes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.ownershiptypes).UserOwned or [OwnershipTypes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.ownershiptypes).TeamOwned to enable ownership

But the [reference docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.ownershiptypes?view=dataverse-sdk-latest) indicate this is for internal use only.

TeamOwned | 2 | The entity is owned by a team. For internal use only.Value = 2.
-- | -- | --

Could this be clarified and one of the documents updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe988d76-22ac-10a1-d2e7-90f4944956a8
* Version Independent ID: e2939916-9861-3660-ebeb-b79035072691
* Content: [User and team tables (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/user-team-entities)
* Content Source: [powerapps-docs/developer/data-platform/user-team-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/user-team-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@fowl2 Some classes/members of our APIs are public but not for general customer use. For those APIs, we mark them as 'Internal use only'. Those APIs may be used by Microsoft apps (1st party).

Thanks for the feedback.

**Comment by fowl2** [comment]
@phecke I understand "internal use only", I'm just pointing out the potential for confusion caused by the inconsistency in the docs where members are labeled as internal in one place but not in another.

**Comment by phecke** [comment]
@fowl2 Thanks for the feedback.
