### ISSUE TITLE
It seems that the order is performed in pairs.

### ISSUE THREAD

**Issue by elear9** [MicrosoftDocs/powerapps-docs#389]
I have Formula-level error management feature turned on., and created a button with the formula Set(tester, IfError( "a" , "b", "c" )).  The variable is set to "c" even though I can't see why there would be an error on either of the first two.  My tests show that:
IfError( "a" , "b" ) = "a"
IfError( "a" , "b", "c", "d" ) = "c"
IfError( "a" , "b", "c", "d", "e" ) = "e"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e0983e-5863-d1eb-43e5-e6e9546c4e2b
* Version Independent ID: cc7abb21-14fd-04de-e1bd-2605697adcd3
* Content: [IfError function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-iferror#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-iferror.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-iferror.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
@elear9, yes we recently changed how IfError worked to be more like the If function than Coalesce.  This facilitated use in behavior formulas where you want to catch an error and stop execution of work that comes after it.  The [IfError docs have now been updated](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-iferror).  As this is still an experimental feature, we are continuing to make improvements as we gain more experience.

For two arguments, the most common usage pattern, the behavior is unchanged and continues to match what Excel's IfError function does.  If you have scenarios where the Coalesce style was better please let me know, I'd like to understand your scenarios better.

**Comment by gregli-msft** [comment]
@AFTOwen, please close this issue.

**Comment by elear9** [comment]
After considering the normal 'if' function, I agree with this approach as being more intuitive than a coalesce approach. I'll be using iferror extensively soon! 
My test scenario was to attempt to pull an email address from an unreliable source (SharePoint list), then from a reliable source (a global variable) and hard-coding the third option as a fail-safe. The fail-safe is not necessary...
