### ISSUE TITLE
Provide further clarification on this page

### ISSUE THREAD

**Issue by mattmblackmore** [MicrosoftDocs/powerapps-docs#3890]
In step 12 B of this document the following instruction does not seem clear to me.

"b. Create a globally unique identifier (guid) and replace the existing uniqueid guid located in the control element pasted in the previous step while preserving the curly braces {}."

Are we able to provide more details about where the GUID referred to is obtained from? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 772dad73-84e3-4afb-ed0f-7937aa0771e2
* Version Independent ID: 5136382e-ef93-f0bf-5e9c-595b935909b7
* Content: [Add the Documents tab to the main form for a table - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/add-documents-tab-entity-main-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-documents-tab-entity-main-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/add-documents-tab-entity-main-form.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mattmblackmore. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@mattmblackmore - I believe you just need a globally unique identifier (guid) that's different than the existing one. There are several internet sites that will generate a guid for you. You can also generate one from a PowerShell window by entering `[guid]::NewGuid()` at the command line and then press enter. Copy the guid that is on your screen. For more information about PowerShell, go to [What is PowerShell?](https://learn.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.3).
