### ISSUE TITLE
Is this Article Still Valid?

### ISSUE THREAD

**Issue by mjvisintin** [MicrosoftDocs/powerapps-docs#3892]
[This is a great article.  It is dated 12/08/2022. But I am reading this in the Admin center for crm online:  The use of Dynamics 365 (deprecated), Salesforce, and SQL Server Data Integration connections is being deprecated. Users will be able to continue to use existing connections, but no new connections can be created after April 29 2022. For Dynamics 365 (deprecated) connections, please update your data integration projects to use the Dataverse (Legacy) connector. For SQL Server and Salesforce, please use Dataflows to replace the data integration projects. All Data Integration connections that use Dynamics 365 (deprecated), Salesforce, or SQL Server connectors will be disabled on July 28th 2022.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ead09d9-3e51-04ce-dc6e-ac9bb59816ec
* Version Independent ID: 94d19f8d-3c5e-8ed9-53ee-4b6173f49144
* Content: [Use SQL to query data (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-sql-query.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **richdi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mjvisintin. This issue has been assigned to the doc author for review.

**Comment by RichdiMSFT** [comment]
@mjvisintin Thanks for your comment. The Admin center notice is for Power Automate, Power Apps and Logic Apps. 
For the Power BI and Power Query connectors people should use the Dataverse or Dynamics 365 (Dataverse) connectors. The two legacy connectors ( Common Data Service (legacy) and Dynamics 365 online (legacy)) Power BI and Power Query connectors will continue to be available for now. When a deprecation has been determined they will be communicated in the connector documentation with time lines specified. 
Sorry for the confusion. 
Rich
