### ISSUE TITLE
Typo specialist vs manager

### ISSUE THREAD

**Issue by DuncanGardner** [MicrosoftDocs/powerapps-docs#3895]
contacts?$select=fullname,jobtitle,annualincome&$filter=contains(fullname,'(sample)') and (contains(jobtitle, 'senior') or contains(jobtitle,'manager')) and annualincome gt 55000

Description is

contacts?$select=fullname,jobtitle,annualincome&$filter=contains(fullname,'(sample)') and (contains(jobtitle, 'senior') or contains(jobtitle,'specialist')) and annualincome gt 55000

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65612608-d80d-d51e-6a74-d2120b6fa7f4
* Version Independent ID: 0b0f4bad-88a6-3afd-25e4-bc50dc1cf257
* Content: [Web API Query Data Sample (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-query-data-sample?view=dataverse-latest)
* Content Source: [powerapps-docs/developer/data-platform/webapi/web-api-query-data-sample.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/web-api-query-data-sample.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by JimDaly** [comment]
@DuncanGardner 
Thank you. I've fixed it.

PR 7436
