### ISSUE TITLE
Postman can't get token for Dataverse because of device management policy

### ISSUE THREAD

**Issue by mattdot** [MicrosoftDocs/powerapps-docs#3898]
This guidance doesn't work in a tenant where admins have locked down the client app's that can authenticate.  Get the following error when clicking "Get New Access Token"

![image](https://user-images.githubusercontent.com/266258/207245244-ca4687fe-46ce-4800-a072-7c9eeac61fb5.png)

I think that adding the following callback urls to the AAD application would allow users to click "Authorize using browser" button and complete the authentication in a secure browser.

* https://oauth.pstmn.io/v1/callback
* https://oauth.pstmn.io/v1/browser-callback

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Set up a Postman environment (Microsoft Dataverse for Apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mattdot. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@mattdot 
I responded via email one 12/13.
