### ISSUE TITLE
Setting 'Item' property

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerapps-docs#39]
Besides using the 'SelectedItem' property of a gallery control, it would be useful to include in this documentation other mechanisms of defining the Item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff0a7da6-b4ea-bc58-efff-ab3016765dd1
* Version Independent ID: 8993631e-75eb-4685-936c-f1c10df6e4dd
* Content: [Display form and Edit form controls: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-form-detail)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-form-detail.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-form-detail.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
@aneesmsft Do you have any ideas here? Thanks.

**Comment by AFTOwen** [comment]
@HairyDrumroll You can also set that property to the selected value of a drop-down control (as described in the procedure topic for adding a form) or by using the **First** and **Lookup** functions. We expect to add more information soon, but I wanted to let you know that we added a link from this reference topic to that procedure topic. Thanks!

cc @aneesmsft
