### ISSUE TITLE
Malicious client script

### ISSUE THREAD

**Issue by mzoomers** [MicrosoftDocs/powerapps-docs#390]
Is there a potential risk of users inserting malicious client script in their model-driven apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec9a4374-a9fc-5cc2-b5a7-137c769eff07
* Version Independent ID: d5c3c8d0-33b5-2101-c7b9-ae0b8d909285
* Content: [Script (JScript) web resources (model-driven apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/script-jscript-web-resources)
* Content Source: [powerapps-docs/developer/model-driven-apps/script-jscript-web-resources.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/script-jscript-web-resources.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@mzoomers Yes, malicious script can be introduced. However, we make the assumption that customizers are trusted.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
