### ISSUE TITLE
Incorrect step on "Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps"

### ISSUE THREAD

**Issue by ambroseya** [MicrosoftDocs/powerapps-docs#3903]
![image](https://user-images.githubusercontent.com/5581188/207703905-6df02a84-11f5-430f-9631-a55106b45a14.png)
Numbers 4-5 are incorrect. 

The actual result was telling me to run npm install, not automatically doing it. 
![image](https://user-images.githubusercontent.com/5581188/207704029-1c64d0a2-4785-4673-bca9-19c5b5bac983.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ambroseya. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@ambroseya 
Thanks for reporting this.
I fixed this yesterday because others had reported it as well.

Step 4 now includes the `--run-npm-install` optional parameter.

```
pac pcf init --namespace SampleNamespace --name LinearInputControl --template field --run-npm-install
```
