### ISSUE TITLE
Edit columns, Edit filters are not supported in model driven app

### ISSUE THREAD

**Issue by sanjeev-k** [MicrosoftDocs/powerapps-docs#3904]
Below is not accurate since functionality for editing columns & filters is not supported, yet. This has been confirmed by PM Srihari (Srihari.Srinivasa@microsoft.com)
Image in the section also needs to be updated

Commands such as **Edit columns, Edit filters**, and Show Chart have been moved from the main set of commands to overflow menu. This gives priority to other commands including custom commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04331e2e-36e7-6aef-bfcb-819f13aa72ac
* Version Independent ID: a0ede5be-9a93-c761-d2f1-196df127008f
* Content: [How to use a model-driven app on a mobile device - Power Apps](https://learn.microsoft.com/en-us/power-apps/mobile/use-custom-model-driven-app-on-mobile#commanding-improvements)
* Content Source: [powerapps-docs/mobile/use-custom-model-driven-app-on-mobile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/mobile/use-custom-model-driven-app-on-mobile.md)
* Service: **powerapps**
* Sub-service: **mobile**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sanjeev-k. This issue has been assigned to the doc author for review.

**Comment by sericks007** [comment]
@sanjeev-k, thank you for letting us know about this!  The [Use model-driven apps on Power Apps mobile](https://learn.microsoft.com/power-apps/mobile/use-custom-model-driven-app-on-mobile#commanding-improvements) article has been updated and will be published later today.
