### ISSUE TITLE
Remove the unnecessary 'Others are not convinced' sentence

### ISSUE THREAD

**Issue by bwmodular** [MicrosoftDocs/powerapps-docs#3907]
I think it's great that you say that 'Unit Testing is strongly recommended' and list some of the benefits of Unit Testing.

I think that it's a real shame that you have added that 'Others are not convinced.' sentence before you actually get to your reccomendation. It seems unnecessary on a page where you reccomend something strongly and it kind of dilutes the strength of the message before the reader even gets to the reccomendation. I think those four words could be removed without any loss of meaning or impact of this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bef4aa1-2ff6-9782-4c55-f18ad45cbfac
* Version Independent ID: bae51041-b5fa-a9ae-8f63-60464adc80fa
* Content: [Testing tools for server-side development (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/testing-tools-server)
* Content Source: [powerapps-docs/developer/data-platform/testing-tools-server.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/testing-tools-server.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @marcelbf
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bwmodular. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@bwmodular Statement removed. Thanks for the feedback.

**Comment by jordimontana82** [comment]
Thank you @phecke for removing it. I'm still seeing it on that page after Ctrl + F5 though, is there a sync job / build process or similar pending to run?

![imagen](https://user-images.githubusercontent.com/3968950/208221403-e855d87f-6c19-4341-93ed-0b8961f7da48.png)

**Comment by jordimontana82** [comment]
I see it now, thx @phecke
