### ISSUE TITLE
Typos in https://learn.microsoft.com/en-us/power-apps/maker/portals/power-apps-cli

### ISSUE THREAD

**Issue by ToddShelton** [MicrosoftDocs/powerapps-docs#3908]
[Enter feedback here]
With this feature, Microsoft Power Apps portals supports [the?] Microsoft Power Platform CLI 
You can now check in the portal configuration to source control and move [the] portal configuration 
After every download, [the] PAC CLI tool 
This file is not deleted, and it get[s] used regardless which environment 
and interact with [the] Microsoft Power Platform CLI using [the] VS Code Integrated Terminal

(not a typo, but what does this nean? )
Before using Microsoft Power Platform CLI commands for portals, ensure your *portal is configured to enable support for this feature*

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39fffb76-5378-fe8a-62fc-0c82a6d03d6d
* Version Independent ID: 102ff357-ae01-8222-8c14-64e2a5e78a0b
* Content: [Portals support for Power Platform CLI - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/power-apps-cli)
* Content Source: [powerapps-docs/maker/portals/power-apps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/power-apps-cli.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ToddShelton. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thank you for your feedback. Typos fixed. The statement "portal is configured to enable support for this feature" refers back to earlier versions of the portal. All sites are now enabled to use the PAC CLI. (Document updated).
