### ISSUE TITLE
Where is that toolbar?

### ISSUE THREAD

**Issue by jpaugh** [MicrosoftDocs/powerapps-docs#391]
This doc does not mention which page the screenshot appears on, so it's difficult to find the toolbar it's referring to. I did eventually find it, but it turns out the screen shot is out of date, as well, since the toolbar has moved to the left side of the application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b3baf4-907e-e339-cf46-ee9956b02f21
* Version Independent ID: c9175439-12e4-ee22-932d-a55301e6b14c
* Content: [Use Microsoft Flow to automate processes in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/use-flows#feedback)
* Content Source: [powerapps-docs/user/use-flows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/use-flows.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@jpaugh Thank you for your feedback. I will update screenshot in the topic by end of day today.

Thank you,
MInts

**Comment by mduelae** [comment]
@jpaugh I just tested this out and for model-driven PowerApps the command bar is at the top where you see an option for "Flow". Also the screen is correct.

Thanks,
MInts

**Comment by jpaugh** [comment]
That's good news. However, this page does not describe the correct context to context, nor does it show how to see that screenshot in the PowerApps application.

I should mention that I'm looking at this page with fresh eyes. I don't know the difference between a model-driven PowerApp and a different kind. If this only works for model-driven apps, shouldn't that be mentioned somewhere?

Thanks!

**Comment by mduelae** [comment]
This content is only for model-driven PowerApps. If you look at the table of contents on the right, you can see that it is under "Use model-driven apps".  The command bar where you can get to the "Flow" menu is always at the top (at the highest level by default). Apps can be customized in many different ways. Our content always describes the default behavior. Are you the admin or end-user?

**Comment by mduelae** [comment]
@jpaugh do have an additional questions?
