### ISSUE TITLE
Content is not up to date

### ISSUE THREAD

**Issue by rezanid** [MicrosoftDocs/powerapps-docs#3914]
the 'pac pcf init' command does not automatically run 'npm install'. In fact it suggest the following.
```
Be sure to run 'npm install' or equivalent in this directory to install project dependencies.
```
I think the documentation is not up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5338bf6-f6c2-fcf9-394f-e30871437de3
* Version Independent ID: 03fed979-b86f-d08b-d0ee-3b83b39c0966
* Content: [Create a model-driven app field component in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/tutorial-create-model-driven-field-component)
* Content Source: [powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rezanid. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@rezanid 
Thanks for your feedback.
Updating this to use the [--run-npm-install](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/pcf#--run-npm-install--npm) parameter so that it will run npm automatically as advertised.
