### ISSUE TITLE
Is the logic on ctor field correct on Valid_ClassFieldConfigMember ?

### ISSUE THREAD

**Issue by ChrisAt2at** [MicrosoftDocs/powerapps-docs#3916]
The `Valid_ClassFieldConfigMember` example class had the following code in it:
`this.validConfigField = !String.IsNullOrEmpty(secure)
            ? unsecure
            : secure;`
But I find it unlogical that you would store the `unsecure` argument when the `secure` field has a value and store the `secure` field when it's empty.
Copy paste of the If logic of the `Execute` method? Guess it should be:
`this.validConfigField = String.IsNullOrEmpty(secure)
            ? unsecure
            : secure;`
(For me personally using a negative condition in a ternary conditional operator is a no-go...)

**Comment by phecke** [comment]
@ChrisAt2at Can you please provide a link to the example or API reference that you are referring to? Thanks

**Comment by ChrisAt2at** [comment]
Hi,
Sorry forgot to mention that...

It's on https://learn.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless#guidance

**Comment by phecke** [comment]
@ChrisAt2at Doc update will be published later today. Thanks for the feedback.
