### ISSUE TITLE
Missing integration info

### ISSUE THREAD

**Issue by jpaugh** [MicrosoftDocs/powerapps-docs#392]
&gt; TLDR; What's missing?
&gt;
&gt; This page talks a bit about Flows, but fails to mention anything specific to PowerApps.

I expected this page to contain information about how to integrate a flow with a PowerApp. For example, I expected to learn [how to pass parameters from PowerApps into a flow](https://powerusers.microsoft.com/t5/Building-Flows/Pass-variable-from-powerapps-to-flow/m-p/66781/highlight/true#M6292)

I also expected to learn broadly what kind of integrations are possible. Can a flow trigger an action in a PowerApp? How can you trigger a flow from a PowerApp?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b3baf4-907e-e339-cf46-ee9956b02f21
* Version Independent ID: c9175439-12e4-ee22-932d-a55301e6b14c
* Content: [Use Microsoft Flow to automate processes in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/use-flows#feedback)
* Content Source: [powerapps-docs/user/use-flows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/use-flows.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by jpaugh** [comment]
I found the specific information I needed, on a different page, [Add a flow][add-flow]. Adding the following text to the "use-flows" page would have helped me:

> To learn how to trigger a flow from PowerApps and pass data to it, please see [Add a flow][add-flow].

These two pages would describe their content better if they swapped names. (Since I already had a flow in place that I wanted to learn how to use, I did not expect "Add a flow" to provide useful information.)

[add-flow]: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/using-logic-flows#create-a-flow

**Comment by mduelae** [comment]
@jpaugh Thank you for the feedback. I will update this page and the links you suggested.

Thank you,
Mints

**Comment by mduelae** [comment]
I updated the topic added the suggested link. The page will update by end of day today.
