### ISSUE TITLE
Plugin triggered by a custom action with "Enable rollback" disabled running inside transaction

### ISSUE THREAD

**Issue by robertoilidio** [MicrosoftDocs/powerapps-docs#3922]
Regarding _Custom Action's_ section:  https://learn.microsoft.com/en-us/power-apps/developer/data-platform/scalable-customization-design/database-transactions#custom-actions

The behavior is not fully documented.

Documentation says:
"_Enable Rollback not set
The custom action won’t act within a transaction._"

However, it not totally true. There is a exception scenario if call this Custom Action from a async Workflow.  Suggestion is to add the scenario to this part of documentation, like this:

There is an exception when the Custom Action is called from an async Workflow

How to test it:

+ Create a custom action with "_Enable rollback_" disabled
![image](https://user-images.githubusercontent.com/10701939/209989830-5c3a3929-4095-4521-b84b-4193ac15851a.png)

+ Create and Register a Synchronous  plugin, Pre Operation stage, on the previous Custom Action message

+ Create an Asynchronous Workflow with a step to run the custom action

![image](https://user-images.githubusercontent.com/10701939/209990867-164ada65-ecbd-48ab-855e-46c582c22474.png)

**Scenario 1)**  Not documented
The Async Workflow runs a call to the custom action (with "Enable rollback" disable), which triggers the pre-operation sync plugin.

**Result:** plugin runs inside transaction, different from what is documented

**Scenario 2)** Properly documented
Instead of an Async Workflow as described above, if a **Cloud Flow or External application** runs a web api call to the same custom action (with "Enable rollback" disable), which triggers same pre-operation sync plugin
**Result:** plugin runs outside transaction, as documented

![image](https://user-images.githubusercontent.com/10701939/209990834-7271241b-0b4f-46c2-b010-19ae8c55b210.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75ddb79a-82d5-611f-787d-72a2294614ff
* Version Independent ID: 876520c5-b0e2-4874-f815-f42d0e2fd611
* Content: [Scalable Customization Design: Database Transactions (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/scalable-customization-design/database-transactions#custom-actions)
* Content Source: [powerapps-docs/developer/data-platform/scalable-customization-design/database-transactions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/scalable-customization-design/database-transactions.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @rogergilchrist
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robertoilidio. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@robertoilidio I believe the documentation is correct, but... 

If a transaction has started from which the custom action was called, then the custom action and any plug-in invoked by the action will be in-transaction.

In your scenario, the async workflow started the transaction that invoked the custom action.

If the caller of the custom action is not in transaction, then what is stated in the documentation is correct.

**Comment by phecke** [comment]
@robertoilidio Thanks for the feedback.
