### ISSUE TITLE
What is "CalculateMatchCodeSynchronously " ?

### ISSUE THREAD

**Issue by allandecastro** [MicrosoftDocs/powerapps-docs#3924]
Hello,

It's mentioned that there is an existing CalculateMatchCodeSynchronously  parameter but can't find any mention in the doc ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a48217ac-43b9-cefb-70bf-163c82175080
* Version Independent ID: 70af49c3-2b41-bbde-235c-d348b2f47a2d
* Content: [Detect duplicate data using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/manage-duplicate-detection-create-update)
* Content Source: [powerapps-docs/developer/data-platform/webapi/manage-duplicate-detection-create-update.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/manage-duplicate-detection-create-update.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divka78
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @allandecastro. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@allandecastro 
Thanks for pointing this out.

This is an old optional parameter for Create and Update. This is the only place it is mentioned in the docs.
It used to be mentioned on older versions of the docs, as far back as CRM 2013 [Use messages (request and response classes) with the Execute method > Pass optional parameters in messages](https://learn.microsoft.com/en-us/previous-versions/dynamicscrm-2013/developers-guide/gg328075(v=crm.6)#pass-optional-parameters-in-messages), but even then the guidance was to not use it.

It is noise now, so I'll remove the note.
