### ISSUE TITLE
Instructions are out of date

### ISSUE THREAD

**Issue by agbeaton** [MicrosoftDocs/powerapps-docs#3927]
I'm looking for current instructions for importing data using the name/alternate key for lookup values, rather then having to first determine their GUID. These instructions appear to be out of date.  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46209bf7-62b7-f424-f749-f297c8847e35
* Version Independent ID: ffef7489-39b8-60dd-299b-367e3b694843
* Content: [Import data in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/user/import-data)
* Content Source: [powerapps-docs/user/import-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/import-data.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @agbeaton. This issue has been assigned to the doc author for review.

**Comment by sericks007** [comment]
@agbeaton, this article does contain the following information:

For CSV or XML file: If you have an alternate key defined, select it from the alternate Key drop-down list. The alternate key is used to uniquely identify and update rows during import. More information: [Define alternate keys to reference rows](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/define-alternate-keys-reference-records).

Does this resolve the issue?

**Comment by sericks007** [comment]
Closing based on review from product manager.
