### ISSUE TITLE
Step 3 of instructions "Set the Redirect URI." needs more meaningful guidance.

### ISSUE THREAD

**Issue by davecatt** [MicrosoftDocs/powerapps-docs#3929]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11caa291-2e98-ac3a-d5d1-ecd416b93bdf
* Version Independent ID: 4f30cddd-8849-1887-ada0-a83a3d2a0027
* Content: [Tutorial: Register an app with Azure Active Directory (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/walkthrough-register-app-azure-active-directory#create-an-application-registration)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @davecatt. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@davecatt There is documentation for that value in the Azure app registration form. It states:

_Redirect URI (optional)
We’ll return the authentication response to this URI after successfully authenticating the user. Providing this now is optional and it can be changed later, but a value is required for most authentication scenarios._

You have to provide a valid URL, but the URL target does not need to exist.

Thanks for the feedback.
