### ISSUE TITLE
Super Helpful! How do I refresh the captured schema

### ISSUE THREAD

**Issue by alexeisenhart** [MicrosoftDocs/powerapps-docs#3931]
[Enter feedback here]
This documentation is VERY helpful and I love this feature. I captured the schema and then I added a new column to the query. How can I capture the schema again? I've tried reloading the app, changing the formula, but I can't get the option to capture the schema to become enabled again.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63db588b-6046-b03a-d679-7035374f7353
* Version Independent ID: 63db588b-6046-b03a-d679-7035374f7353
* Content: [Working with dynamic schema data sources in Power Apps (experimental) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-dynamic-schema)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-dynamic-schema.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/working-with-dynamic-schema.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **tapanm**

**Comment by alexeisenhart** [comment]
I used the Inspect feature in the browser to remove the Disabled tag on the Capture Schema button, and then clicked it again. This worked.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alexeisenhart. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@alexeisenhart looks you figured it out so I'm closing the issue. Feel free to reopen it if you still have questions. 

Thanks,
Mints

**Comment by lancedMicrosoft** [comment]
You just reedit the formula again.


Note: My working hours may not coincide with your working hours.  Please do not feel compelled to respond right away if you receive mail from me outside of your normal working hours.
