### ISSUE TITLE
Broken link in 'See also' section

### ISSUE THREAD

**Issue by tcvdw1605** [MicrosoftDocs/powerapps-docs#3933]
Broken link: 

See also link item: [Blog: Working with time zones in the Dataverse](https://powerapps.microsoft.com/en-us/blog/working-with-time-zones-in-the-data-platform/)

Should link to:
https://powerapps.microsoft.com/en-us/blog/working-with-time-zones-in-the-common-data-service/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7267ae82-4d15-035f-fe93-cc66469d3b58
* Version Independent ID: 63c7e837-14dd-d199-9dc9-27cd81fd4050
* Content: [Behavior and format of the Date and Time column in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/behavior-format-date-time-field)
* Content Source: [powerapps-docs/maker/data-platform/behavior-format-date-time-field.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/behavior-format-date-time-field.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tcvdw1605. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@tcvdw1605 - Thank you for helping improve the Power Apps documentation. The article has been updated with the correct link.
Closing issue.
