### ISSUE TITLE
365

### ISSUE THREAD

**Issue by bacmodung** [MicrosoftDocs/powerapps-docs#3934]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58cefba9-39c7-a589-2910-624ce74ecb4b
* Version Independent ID: e5ee4404-faa8-b382-7ff3-bcbafa4248f7
* Content: [Power Apps projects - Feedback and telemetry - Power Apps](https://learn.microsoft.com/en-us/power-apps/guidance/planning/feedback-telemetry)
* Content Source: [powerapps-docs/guidance/planning/feedback-telemetry.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/guidance/planning/feedback-telemetry.md)
* Service: **powerapps**
* Sub-service: **guidance**
* GitHub Login: @taiki-yoshida
* Microsoft Alias: **tayoshi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bacmodung. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
Closing this issue because no feedback was provided.
