### ISSUE TITLE
is Search delegatable?

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/powerapps-docs#3935]
the Search function is not listed in the table of delegatable functions like in other connector documentation, but it seems to delegate to data verse tables.  wondering if docs need updating

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6ef9b3a-5d99-1ca0-0e7f-80c2de740313
* Version Independent ID: 80900e35-c8da-10a1-9902-343e84d823d0
* Content: [Connect to Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/connections/connection-common-data-service)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-common-data-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/connections/connection-common-data-service.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @drdamour. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@drdamour I'm looking into this and will get back to you as soon as I hear back.

Thanks,
Mints

**Comment by Danielx64** [comment]
I'm not the author here but has there been any updates on this?

**Comment by mduelae** [comment]
@drdamour 

The table has been updated for delegation of sort by columns, sort, and in membership.

Thanks you,
Mints

**Comment by drdamour** [comment]
@mduelae but nothing was added about the search function which is why this was opened in the first place, can you please explain

**Comment by lancedMicrosoft** [comment]
Search is delegable to both Dataverse and SQL Server.  Both are documented.  Search is basically an in / contains operation on multiple fields.  Not all data sources support the Or'ing necessary to support this properly.

**Comment by lancedMicrosoft** [comment]
See here:  https://learn.microsoft.com/en-us/connectors/sql/#power-apps-functions-and-operations-delegable-to-sql-server  for SQL Server and here for Dataverse: https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/connections/connection-common-data-service

**Comment by mduelae** [comment]
@drdamour - sorry about the confusion. Now the table has been updated with the search function.

https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/connections/connection-common-data-service#power-apps-delegable-functions-and-operations-for-dataverse

Thanks.

**Comment by drdamour** [comment]
Looks good now, thanks
