### ISSUE TITLE
Incorrect section and drop-down list name referenced

### ISSUE THREAD

**Issue by robyyo** [MicrosoftDocs/powerapps-docs#3939]
On the Types of tables - Power Apps page there is an incorrect section and drop-down list reference in the instructions for creating an Activity type table.

> To create a custom activity table, open the More settings section in the New table panel, select Activity table option from the Choose table type drop-down list.

It should say:
To create a custom activity table, open the Advanced options section in the New table panel, select Activity table option from the Type drop-down list.

![image](https://user-images.githubusercontent.com/90076535/211932676-01f75fe9-2e07-4eef-b12c-ea988297607c.png)

![image](https://user-images.githubusercontent.com/90076535/211932695-d5720746-b41e-43c1-aeb6-85cd0b02258e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59399824-5817-ef45-209d-35dab587a406
* Version Independent ID: 322b5820-c559-9a0b-ef66-1c31945ead2e
* Content: [Types of tables - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/types-of-entities)
* Content Source: [powerapps-docs/maker/data-platform/types-of-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robyyo. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@robyyo - Thank you for your feedback. The article has been updated to reflect the current UI experience. Closing issue.
