### ISSUE TITLE
Error loading control

### ISSUE THREAD

**Issue by stelianrusu** [MicrosoftDocs/powerapps-docs#394]
While running  this sample, after npm start, I get a javascript error:
Cannot read property 'LogicalName' of undefined in index.ts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa8d8a05-5c10-ff85-f918-df07db18b72c
* Version Independent ID: 6bad6d9b-312e-0d7d-1259-9946d2b30020
* Content: [Flip component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/angular-flip-control#feedback)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/angular-flip-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/angular-flip-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@stelianrusu Thanks for the feedback. Please raise the issue in the [forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Closing this issue for now. Please reopen the issue if didn't get required information.
