### ISSUE TITLE
Connect as an app documentation

### ISSUE THREAD

**Issue by valkko** [MicrosoftDocs/powerapps-docs#3942]
This page has example code how to use Client ID & secret from Azure AD to connect, but only for C#. Would be helpful to have examples for other languages or show the request itsef to implement the connection yourself in other languages.

Eventually I figured out that I need to do the OAuth2 client_credentials flow to get an access token I can use, but the page makes no mention of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7f57df6-59af-6e22-44d2-bc9bb1ee69c7
* Version Independent ID: fdce23ee-733d-bf3a-25c8-2ca6bfa8c852
* Content: [Use OAuth authentication with Microsoft Dataverse (Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/authenticate-oauth)
* Content Source: [powerapps-docs/developer/data-platform/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/authenticate-oauth.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @ritesp
* Microsoft Alias: **ritesp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @valkko. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@valkko Thanks for the feedback. We are trying to add support for both the SDK and Web APIs to our pages. It is a big task as we do have a lot of documentation.
