### ISSUE TITLE
It doesn't work and the template doesn't exist

### ISSUE THREAD

**Issue by froyanita** [MicrosoftDocs/powerapps-docs#3943]
I've spent a long time on it, and it doesn't work. Can't find the template for it either. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 620aee88-efbc-394f-0cbb-79be3f4a6bd2
* Version Independent ID: 632dd319-a22f-a4b7-a2da-f60538b1e4e6
* Content: [How to export Ideas data for reporting (contains video) - Power Apps](https://learn.microsoft.com/en-us/power-apps/teams/export-employee-ideas-for-reporting)
* Content Source: [powerapps-docs/teams/export-employee-ideas-for-reporting.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/export-employee-ideas-for-reporting.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sbahl10
* Microsoft Alias: **saperlmu**

**Comment by mduelae** [comment]
@froyanita Can you provide more details about your issue? Did you find an issue with the documentation? Or, if this a technical issues please contact support, here: here: https://powerapps.microsoft.com/support/

Thanks,
Mints

**Comment by froyanita** [comment]
Sure..
I'm following this tutorial:
https://learn.microsoft.com/en-us/power-apps/teams/export-employee-ideas-for-reporting

1) "My flows" doesn't exist
[image: image.png]
2) Instant cloud flow?
[image: image.png]
3) I select manually trigger a flow, but there's no "create" function
[image: image.png]

So.. whatever .. I tried picking functions that look like the ones in the
guide, and the next problems arise.
[image: image.png]

So I've fumbled my way and I get to the "add a row into table"
[image: image.png]
It's blank btw.. or maybe it's an error when I have my Teams dark..
[image: image.png]
Then I get THIS error
[image: image.png]

So I can't get any further.

It would be perfect if someone could invite me to a Teams meeting and help
me figure it out.
Otherwise we'll have to use another platform.


Den ons. 18. jan. 2023 kl. 01.03 skrev Manjinder (Mints) <
***@***.***>:

**Comment by mduelae** [comment]
I can't see any of the screenshots that you added. Try this and let me know if it works:

On the top menu, select **New flow** then select **Instant cloud flow**. 
Enter a **Flow name** and then under **Choose how to trigger this flow** select **Manually Trigger a flow**.
Select **Create**.

Do you see these options?

**Comment by froyanita** [comment]
New flow = create from blank?
There’s no instant cloud flow.

None of the titles or names of functions you are referring to are there. Or
at least not it that order or term. Is there any way that a teams meeting
could be set up, so I could get some help? Or if you can’t receive photos,
can I send another file to demonstrate it.. a zipped video?

We really want to use it, but if we can’t extract the ideas to excel or
txt, it looses its value.

fre. 20. jan. 2023 kl. 00.17 skrev Manjinder (Mints) <
***@***.***>:

**Comment by mduelae** [comment]
@froyanita This seems to be a technical issue and not an issue - please contact support: https://powerapps.microsoft.com/support/

Thanks,
Mints
