### ISSUE TITLE
page property of Context is missing

### ISSUE THREAD

**Issue by keijimscom** [MicrosoftDocs/powerapps-docs#3945]
[Enter feedback here]
Though the "page" property of Context is used in lots of controls which would work in a form of model-driven app, there is no description of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f219919-646d-18e5-2766-365f34aea315
* Version Independent ID: de311f39-0493-955f-d3fb-7b38071b5ab9
* Content: [Context - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/context)
* Content Source: [powerapps-docs/developer/component-framework/reference/context.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/context.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @keijimscom. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@keijimscom 
Can you point to an example where this property is used?

**Comment by keijimscom** [comment]
> @keijimscom Can you point to an example where this property is used?

For example, at line 97 of https://github.com/BenLBartle/PCF-AttachmentsGrid/blob/master/AttachmentsGrid/index.ts

**Comment by keijimscom** [comment]
> @keijimscom Can you point to an example where this property is used?

I found another one
At line 79 of https://github.com/walcivar/PCFFileUploader/blob/master/PCFFileUploader/index.ts which is linked to this control https://pcf.gallery/pcf-file-uploader/

**Comment by keijimscom** [comment]
> @keijimscom Can you point to an example where this property is used?

Someone is using undocumented "mode " property of Context in order to retrieve entityId shown in the form of model-driven app instead of using undocuented "page property of Context at line 49 of https://github.com/OOlashyn/PCF-WebFormStepVisualizer/blob/master/WebFormStepsVisualizer/index.ts which is linked to this control https://pcf.gallery/web-form-steps-visualizer/

Poeple seems to like to find undocumented property to retrieve entityId.

**Comment by keijimscom** [comment]
> @keijimscom Can you point to an example where this property is used?

Another example of using undocumented "mode" property of Context to retrieve entityId is at line 42 of https://github.com/scottdurow/NetworkViewPCF/blob/master/NetworkViewPCF/NetworkView/index.ts which is linked to this control https://pcf.gallery/network-view/

**Comment by keijimscom** [comment]
> @keijimscom Can you point to an example where this property is used?

The other example of using "page" at line 59 of https://github.com/ramarao9/AttachmentUploader/blob/master/AttachmentUpload/index.ts which is linked to this control https://pcf.gallery/attachment-uploader/

**Comment by JimDaly** [comment]
@keijimscom 
Thanks for all the examples showing developers who have taken a dependency on this property.

There are properties we don't document because we don't support using them. People who use undocumented properties do so at their own risk. 

But I think that is your point. If this is a property we support people using, we should document it.

@kaushikkaul can you comment on whether the context page property should be documented or not?

**Comment by keijimscom** [comment]
@kaushikkaul 
Please consider whether PCF developers can retrieve the entityId for the dataverse record shown on a form of model-driven app, or not.

**Comment by keijimscom** [comment]
Let me add a comment regarding retrieving the entityId for the dataverse record shown on a form of model-driven app.
There is a control as the following:
- Customer Card Add-in for Dynamics 365 apps (preview)
    - https://learn.microsoft.com/en-us/dynamics365/customer-insights/customer-card-add-in

I believe the it is a PCF control made by Microsoft.
It can be appried to any field in the Contact or Account form of model-driven app.
In this chat, I focus on Contact form for easy explanation.
In runtime, it searches id of contact in Customer Insights's Customer entity which administrator configured in the configuration page of the solution for **entityId** which is named as "contactid" on a contact form.
So I could find that the control above is able to  retrieve  the entityId for the dataverse record shown on a form of model-driven app.

If there is any supported way to retrieve  the entityId for the dataverse record shown on a form of model-driven app, this issue I created could be closed. If not, it seems that the above control which Microsoft created uses unsupported method of API.

**Comment by JimDaly** [comment]
Adding @HemantGaur 

@keijimscom 

If I'm understanding you correctly, you are looking for the supported way to access the primary key value for a record within a form where that record is being viewed/edited. Is this correct?

You have provided many examples where PCF controls are using a `page` property of the [Context](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/context), but we do not have documentation about this property.

@HemantGaur : This seems like essential information that a PCF control needs. Is there any other way to get it?

**Comment by JimDaly** [comment]
@keijimscom 

@HemantGaur  informs me that this blog post describes the supported way to get this information: [Supported way to get Entity Id and Logical Name in PCF](https://www.dancingwithcrm.com/pcf-entity-id-supported-way/)

I've created a workitem to update the docs with this information. 
Does this answer your question?

**Comment by keijimscom** [comment]
Let me tell you two points:
First, I recognized that entityID and entityName (or entity logical name) were the set which I should have to discus on this issue. Several samples I picked up above actually uses the set. And the control which I am currently developing should retrieve the both of entityID and entityName (or entity logical name) in order to express my logic and UI on a form of model-driven app.
When I used Web resources, I could retrieve the set within JavaScript code.

> The supported method using explicit property definition and configuration provides a metadata driven way to configure the entityID and entityName.

Second, though I tried to go through [the blog article](https://www.dancingwithcrm.com/pcf-entity-id-supported-way/), I could not find "entitylogicalname". (I tried in an Account form.)

So, I'd like to find a supported way to retrieve the set of entityID and entityName.

**Comment by JimDaly** [comment]
@keijimscom 

I tested this using the instructions in the blog post.
 - I couldn't set the entityname property using the modern form designer, but it was available to set in the 'classic' designer.
 
![image](https://user-images.githubusercontent.com/6353736/217354508-3ceff03a-f5d4-4bcb-8017-d1c337bea203.png)

 - However, when I tried to save the form, I got an error: `Property entityId is required, but the declaration is missing.`
 
 So, I don't think the end-to-end solution described in the blog post is working. I'll follow up with @HemantGaur to see if there is a workaround.

**Comment by JimDaly** [comment]
@keijimscom & @HemantGaur 

Update on the issue above. I was able to save the form. 

Close inspection of the error returned showed that it was referring to _other controls_ in the form which were also configured to use the linear input control I updated.

I got this error:

`Property entityId is required, but the declaration is missing. More Details:Parent Type:SystemForm;SubType:main;Parent Id:8448b78f-8f42-454e-8e2a-f8196b0419af;Associated entity:Account;Control Description Xml:<controlDescription forControl="{85988e2f-3f6c-4b3c-ba40-f34563f5bc15}"><customControl id="{C6D124CA-7EDA-4A60-AEA9-7FB8D318B68F}" formFactor="2"><parameters><datafieldname>sharesoutstanding</datafieldname></parameters></customControl><customControl id="{C6D124CA-7EDA-4A60-AEA9-7FB8D318B68F}" formFactor="0"><parameters><datafieldname>sharesoutstanding</datafieldname></parameters></customControl><customControl id="{C6D124CA-7EDA-4A60-AEA9-7FB8D318B68F}" formFactor="1"><parameters><datafieldname>sharesoutstanding</datafieldname></parameters></customControl><customControl name="samples_SampleNamespace.LinearInputControl"><parameters><controlValue type="Currency">sharesoutstanding</controlValue></parameters></customControl></controlDescription>;Control Reference Xml:<control id="sharesoutstanding" classid="{F9A8A302-114E-466A-B582-6771B2AE0D92}" datafieldname="sharesoutstanding" disabled="false" uniqueid="{85988e2f-3f6c-4b3c-ba40-f34563f5bc15}" />;Error Message:-2146041806;Additional Information:;Detail: `

This was referring to the `sharesoutstanding` field, which isn't one I had configured.
I had to go through all the fields on the form that were using the custom control I updated and configure them individually.

@keijimscom 
I think this should work.

These are the properties I added to the ControlManifest.Input.xml:

```
      <property name="entityId"
         display-name-key="Entity Id"
         description-key="The id of the current record."
         of-type="SingleLine.Text"
         usage="input"
         required="true" />
      <property name="entityName"
         display-name-key="Entity Name"
         description-key="The logical of the type of the current record."
         of-type="SingleLine.Text"
         usage="input"
         required="true" />
```
This added these properties to the IInputs interface:

```
export interface IInputs {
    controlValue: ComponentFramework.PropertyTypes.NumberProperty;
    entityId: ComponentFramework.PropertyTypes.StringProperty;
    entityName: ComponentFramework.PropertyTypes.StringProperty;
}
export interface IOutputs {
    controlValue?: number;
}
```
I should be able to access these values in the control code.

**Comment by keijimscom** [comment]
@JimDaly Thank you for testing the blog post.
In my last post, I forgot to set usage="input" in manifest file.
I just create a new control which has properties for both of entityId and entityName which has attribute usage="input" by referencing your comment.
So I could go through all steps in the blog post.
**But** the control never receives the value from context.
I wrote such like the following codes in both of init() and updateView:
```javascript
this._entityId = context.parameters.entityId.formatted ? context.parameters.entityId.formatted : "";
this._entityName = context.parameters.entityName.formatted ? context.parameters.entityName.formatted : "";
```
The values from both of above variables was empty. I tested it in local with PCF Control Sandbox and also in a model-driven app in cloud.

I hope to find the way to receive entityId and entityName in PCF control.

**Comment by JimDaly** [comment]
I was able to confirm that I could get the values configured in the test harness with this code in the `init` function:

```
   this._entityId = context.parameters.entityId.raw!;
   this._entityName = context.parameters.entityName.raw!;
```
But the formatted property was undefined in the debugger.

**Comment by keijimscom** [comment]
@JimDaly Thank you very much.
I just confirmed your code worked fine. Now I found the way.

> I've created a workitem to update the docs with this information.

I appreciate your comment above.
I look forward to seeing the docs with this information.

Thank you

**Comment by JimDaly** [comment]
@keijimscom 
We published this in the FAQ topic: [How can I access the record id or table name?](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/faq#how-can-i-access-the-record-id-or-table-name) and I also added a link to this FAQ in the [Context](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/context) reference topic.

I'm going to close this issue. 
Thanks for your detailed explanation and persistence in helping to make our docs better.

**Comment by keijimscom** [comment]
@JimDaly It's so great. Thank you.
