### ISSUE TITLE
Limitation if Power BI is not in same Region as Power Automate?

### ISSUE THREAD

**Issue by LauWagFelix** [MicrosoftDocs/powerapps-docs#3952]
In our environment the Power BI is in Switzerland North but Power Automate needs to be in Europe North (as it is not supportet in CH). If i insert a Power BI Tile i can select the Workspaces but don't get shown any Report published there.

Regards
Laurent
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen auf learn.microsoft.com ➟ GitHub erforderlich.*

* ID: 551096c3-6bef-bd2b-9254-4fceac6315da
* Version Independent ID: 6aaee99a-f244-17ca-cb48-408436a2ad92
* Content: [Power BI tile-Steuerelement in Power Apps - Power Apps](https://learn.microsoft.com/de-ch/power-apps/maker/canvas-apps/controls/control-power-bi-tile#key-properties)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LauWagFelix. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@LauWagFelix 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/.

If there is an issue with documentation please provide more details as to what information is incorrect.

Thanks,
Mints
