### ISSUE TITLE
How to create a new custom Virtual Entity Data Provider?

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#3962]
In the Plug-in registration section, it says, `Instead of registering steps, you will configure your data provider using the following tables.` Then lists a single table: `Virtual Entity Data Provider (EntityDataProvider)` However, there are no instructions on how to create one.

There's a section in the Administration Settings for creating new Virtual Entity Data Sources (EntityDataSource), but there doesn't seem to be any mechanism available to create the Provider.

Please provide details on how these records are created/maintained.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9554515-4047-ebbd-04a1-31f8c38db2d2
* Version Independent ID: b602c13a-4b14-e41f-5ab6-a591bcadfd84
* Content: [Custom virtual table data providers (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/custom-ve-data-providers)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/custom-ve-data-providers.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/custom-ve-data-providers.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @devlinl. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@devlinl You are to create a row in the EntityDataProvider table. You can use the Web API or SDK Create [message](https://learn.microsoft.com/power-apps/developer/data-platform/reference/entities/entitydataprovider#messages) to do that.

In the table row, set the columns for (at a minimum) CreatePlugin, RetrievePlugin, RetrieveMultiplePlugin, UpdatePlugin, and DeletePlugin columns. These should correspond to the plug-ins in the assembly that you registered with the PRT.

What I do not know is:
1. How to associate the value (GUID) for each *Plugin column to the registered plug-in in the assembly. Does the PRT provide the GUIDs when you register the assembly or do we need to generate and provide the GUIDS to the PRT during assembly registration?
2. How to create the EntityDataProvider table row without having to write code. I would assume you simply go into PowerApps and add a row to the EntityDataProvider table specifying the GUIDS of your plug-ins.

I am looking into this. Yes, the documentation on that subject is lacking. I will fix this once we get this all figured out.

**Comment by devlinl** [comment]
I was able to find some additional information via another channel... There is information about creating the data provider in the documentation, but it is buried inside a "Sample": [Sample: Custom virtual table provider with CRUD operations, Step 2: Creating data provider and adding plug-ins to the provider](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/sample-ve-provider-crud-operations#step-2-creating-data-provider-and-adding-plug-ins-to-the-provider)

In that document, it is shown that you can register the Data Provider using the Plugin Registration Tool.
![image](https://user-images.githubusercontent.com/45976800/214211808-fa720ed7-4d69-469b-8e74-5969022b947e.png)
It's worth noting that this currently only works with the classic Plugin Registration Tool, not the version in the Xrm Toolbox.

I didn't notice this earlier, because I typically don't look at documents labeld "Sample" unless there is very specific code that I am looking for. In this case, there was no indication from the main documentation that code would be required, so I didn't go looking for "Samples". Perhpas documents like this, which contain a mix of code samples and instructions could be split up into differnt documents that appear in the nav-bar on the left, which would make discovering relevant sections easier. Or perhaps there could be a distinction between "Samples" and "Tutorials" to indicate that a document includes relevant instructions that might be missing from the main documentation pages.

If nothing else, a link in the section I originally left a comment for, pointing to the Sample would be a big help.

**Comment by phecke** [comment]
@devlinl I will update the data providers topic to include the missing information or at least a link to it. Thanks for pointing this omission out.

**Comment by phecke** [comment]
@devlinl The topic update is finished and will be published in about one hour.
