### ISSUE TITLE
So small amount if information in your documentation. Hardly any examples how to use. Very disappointing user experience... Why I have to create account on this site to give feedback regarding information on your site?

### ISSUE THREAD

**Issue by Olena7477** [MicrosoftDocs/powerapps-docs#3966]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 776f1f0f-826d-f77f-1a18-69da27fbb361
* Version Independent ID: 2e532983-8a9d-82ec-7db3-70328b462a36
* Content: [Text input control in Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-text-input)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-text-input.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-text-input.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Olena7477. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@Olena7477 - What can I  help you with? Can you provide more details about the issue you have with this topic: [Text input control in Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-text-input).

Thank you,
Mints

**Comment by mduelae** [comment]
@Olena7477 Since I haven't heard back, I'm closing the issue. Feel free to reopen the issue if you find issues with our documentation. 

Thanks,
Mints
