### ISSUE TITLE
Click on Power Apps menu item fails reporting schema reading error

### ISSUE THREAD

**Issue by CalvinQuark** [MicrosoftDocs/powerapps-docs#3967]
I am attempting to follow the instructions in this article:

https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/app-from-azure-sql-database

When I click on the Power Apps menu item, I encounter `Cannot read properties of undefined (reading 'schemas')` error with no Error Code specified.

Here are the details:

{  "shellProps": {    "sessionId": "b591beb5cabd414dbefe4028d9585adf",    "extName": "SqlAzureExtension",    "contentName": "PowerAppsBlade"  },  "error": {    "message": "Cannot read properties of undefined (reading 'schemas')",    "error": {      "message": "FetchDataError: data set DataCache:11:44",      "name": "FetchDataError",      "stack": "FetchDataError: FetchDataError: data set DataCache:11:44\n    at r.t (https://portal.azure.com/Content/Dynamic/-mPDykxZ7mlI.js:73:895)\n    at r (https://portal.azure.com/Content/Dynamic/fK4AzoLEiM2h.js:18:248)\n    at new r (https://portal.azure.com/Content/Dynamic/fK4AzoLEiM2h.js:18:469)\n    at yt (https://portal.azure.com/Content/Dynamic/fK4AzoLEiM2h.js:99:817)\n    at https://portal.azure.com/Content/Dynamic/fK4AzoLEiM2h.js:99:6772",      "extension": "SqlAzureExtension",      "type": "MsPortalFx.Errors.FetchDataError",      "baseTypes": [        "MsPortalFx.Errors.FetchDataError",        "MsPortalFx.Errors.DataError",        "MsPortalFx.Errors.Error"      ],      "errorLevel": 2,      "timestamp": 2229797.200000018,      "innerErrors": [],      "dataSetName": "DataCache:11:44"    },    "code": null  }}

Note that I do have the `Allow Azure services and resources to access this server` checked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2ad0f97-4d2f-394b-cab8-d0e831649104
* Version Independent ID: 2f0646ab-720f-c62f-be54-f10eb6002da9
* Content: [Create a canvas app from Azure SQL Database - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/app-from-azure-sql-database)
* Content Source: [powerapps-docs/maker/canvas-apps/app-from-azure-sql-database.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/app-from-azure-sql-database.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **hahuber**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CalvinQuark. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, this look like a support issue and we're unable to handle Support requests for the product here. 

To contact Support, see here: https://powerapps.microsoft.com/support/ Closing this issue.
