### ISSUE TITLE
Unable to Access Actual Screen Size

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#397]
Hello,
No matter which property I use, I cannot get the actual screensize. 
When using:
ScreenName.Width, Parent.Width, App.Width or App.DesignWidth, all of them show `1366` no matter which device I open the app on. 
I've even tried spinning up a Preview environment but the issue still persists. 
Am I missing something? It appears from Hiro's video here (https://youtu.be/VDmVw7IEFP8?t=406) that ScreenName.Width should be dynamic.
Thoughts?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by SeaDude** [comment]
I figured out my problem. Pretty embarassed to say it but...
I Collect'ed the values at the start of my app (which means they're static from that point). Then visualizing them on the screen did nothing... SHEESH! 
Sorry for the bother.

**Comment by AFTOwen** [comment]
@SeaDude: Thanks for letting us know! :-)
