### ISSUE TITLE
Notification polling - Long duration

### ISSUE THREAD

**Issue by fmarcellino** [MicrosoftDocs/powerapps-docs#3973]
The section that refers to "Notification polling" states that "_if a user stays on a page for a long duration, new notifications will be retrieved._"
"Long duration", here, is not precise and I received a call with a customer that had a different expectation. They're creating in-app notifications through SDK and setting ttlinseconds to 60, and they could not see notifications toasting while remaining on the same page. If they refreshed or opened a different page, then it worked, so the request here is just to clarify in the documentation how long the user should be on a page for getting the notifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f495f03e-28c9-0ebb-ef03-72e16b267b3a
* Version Independent ID: a9dcec59-8b72-966e-fa53-f4b2e42d325e
* Content: [Send in-app notifications within model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by adrianorth** [comment]
This needs to be changed to say that new notifications will not be received until the page navigation happens.  Setting ttlseconds to 60 is not recommended because that will delete the notification in 60 seconds and likely will not be seen by the user.  Default ttlseconds setting is 14 days so suggest a value measured in days.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @fmarcellino. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
The doc has been updated with to call out new notifications won't be available until page navigation happens.
