### ISSUE TITLE
Typo in "Limitations of Virtual Tables"

### ISSUE THREAD

**Issue by NotExZACKly-MSFT** [MicrosoftDocs/powerapps-docs#3982]
The limitation "Search functionality is not support for virtual tables as they do not persist data" needs to "support" updated to "supported".

**Comment by phecke** [comment]
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/get-started-ve

**Comment by phecke** [comment]
@NotExZACKly-MSFT Fixed. Thanks for the feedback.
