### ISSUE TITLE
What does this even mean?

### ISSUE THREAD

**Issue by zephaewryn** [MicrosoftDocs/powerapps-docs#3989]
[

What does this sentence mean?  

"The name given to the app designers make edits to solution. "]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6153e15f-0c35-1456-5e12-dc6a9d30e216
* Version Independent ID: 6153e15f-0c35-1456-5e12-dc6a9d30e216
* Content: [Model-driven app glossary of terms - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/model-driven-app-glossary#solution)
* Content Source: [powerapps-docs/maker/model-driven-apps/model-driven-app-glossary.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/model-driven-app-glossary.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @zephaewryn. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@zephaewryn - Thank you for your feedback. The article has been updated to clarify the description for solution explorer.
Closing issue.
