### ISSUE TITLE
Error in text on the page

### ISSUE THREAD

**Issue by nkatz01** [MicrosoftDocs/powerapps-docs#4000]
_Enter an expression or formula in the action input to [Trace](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/functions/function-trace) and write the kudosBeforeTest value **to the test results record**._

The words in bold don't make sense. The intention was probably to say, 'to the Action field' OSLT

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b15deb16-02e4-9005-2dbd-917f8308b47d
* Version Independent ID: 51cc413b-0fd1-5a63-ddfa-16b3fb4c9e88
* Content: [Working with Test Studio (contains video) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-test-studio)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-test-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/working-with-test-studio.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @aengusheaney
* Microsoft Alias: **aheaney**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nkatz01. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
The step has been updated. You should see the published changes by the end of day.

Thanks,
Mints
