### ISSUE TITLE
No link to download tools from Nuget

### ISSUE THREAD

**Issue by michaelmmcrae1** [MicrosoftDocs/powerapps-docs#4003]
This page is described as the place to find out where to download the Configuration Migration Tool, from Nuget.
But it only talks about PAC CLI
If you follow links, you end up in a circular loop of "Click here to find out where to download things from Nuget"
These pages lead to circular path, nowhere actually showing where to get these things from Nuget:

https://learn.microsoft.com/en-us/power-platform/alm/configure-and-deploy-tools -- links to this for more download info:

https://learn.microsoft.com/en-us/power-platform/admin/manage-configuration-data -- says "For information on downloading the Configuration Migration tool, see Download tools from NuGet" and links to:

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/download-tools-nuget -- gives no description or link to get these tools from Nuget. Most it does is link BACK to https://learn.microsoft.com/en-us/power-platform/alm/configure-and-deploy-tools -- back to the top link. Circular.

Nowhere in the docs does it say where to get these things from Nuget...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 099cc915-21d6-ca85-ecd6-c788c632b172
* Version Independent ID: 5d57e6cd-4f77-7775-83a7-621ae32134dc
* Content: [Dataverse development tools (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/download-tools-nuget)
* Content Source: [powerapps-docs/developer/data-platform/download-tools-nuget.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/download-tools-nuget.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @davidjenni
* Microsoft Alias: **davidjen**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @michaelmmcrae1. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@michaelmmcrae1 You now use the CLI to download the CMT from NuGet and install it. I will look into the looping of the content.

Thanks for your feedback.

**Comment by phecke** [comment]
@michaelmmcrae1 If you want to do it manually, first download the NuGet
[package](https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.ConfigurationMigration.Wpf). Next, rename the file from .nupkg to .zip. Extract the contents and run the application in tools/DataMigrationUtility.exe.

However, the new method using PAC CLI is much better as it does the installation and update work for you.
