### ISSUE TITLE
Include product addition on this page

### ISSUE THREAD

**Issue by sapanwar** [MicrosoftDocs/powerapps-docs#4009]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]
Shouldn't this page also be applicable for Dynamics 365 project operations as it's built on top of dataverse. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 228fe864-af1c-34bb-c6d5-7507055ff26f
* Version Independent ID: a0b7352d-86a6-b85d-2c3a-93f93f6cd3ef
* Content: [API limits overview (Microsoft Dataverse) - Power Apps](https://review.learn.microsoft.com/en-us/power-apps/maker/data-platform/api-limits-overview)
* Content Source: [powerapps-docs/maker/data-platform/api-limits-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/api-limits-overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sapanwar. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Taking this to email.
