### ISSUE TITLE
Azure App Registration Updates Required

### ISSUE THREAD

**Issue by shkama** [MicrosoftDocs/powerapps-docs#4013]
[Enter feedback here]
When trying to connect using the configuration mentioned in the page, Postman always gives "Error: [object Object]". 

There are some modifications required on the Azure App Registration to make it work as suggested in https://softchief.com/2021/08/18/solved-response_type-token-is-not-enabled-for-the-application-in-dynamics-365-and-postman-connection/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Set up a Postman environment (Microsoft Dataverse for Apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @shkama. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@shkama 
Thanks for your feedback.

_The configuration mentioned in the page_ is about how to use the `clientid` we provide: `51f81489-12ee-4a9e-aaae-a2591f45987d`, and as far as I know, it works fine for most scenarios. 

We don't include any instructions about creating your own azure app registration for Postman. Is that what you are doing?

Why not use the `clientid` we provide?

**Comment by JimDaly** [comment]
@shkama 
Closing this and following up in email.
