### ISSUE TITLE
"pac solution add-reference --path ..\" does not work

### ISSUE THREAD

**Issue by keijimscom** [MicrosoftDocs/powerapps-docs#4020]
[Enter feedback here]
The following command on the page does not work.
```pwsh
pac solution add-reference --path ..\
```
The following works.
```pwsh
pac solution add-reference --path ..\..\
```

Needs correction.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @keijimscom. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
I have fixed this.
Thanks

**Comment by keijimscom** [comment]
@JimDaly  Thank you very much.
I just checked it was fixed on the released document page.
