### ISSUE TITLE
Mixing connector versions

### ISSUE THREAD

**Issue by JSpradlinZF** [MicrosoftDocs/powerapps-docs#4021]
The "Specify A Calendar" section specifies V3 of the Office365Outlook.GetEventsCalendarView connector, however the iconNextMonth and iconPrevMonth controls in the template page use V2. This breaks functionality, as the event properties have changed. For example:

.Subject → .subject
.Body → .body
.Location → .location

For the filtered event gallery to work, Start will need to be changed to startWithTimeZone, as converting start, which is now in UTC format, to ShortDate doesn't work. Here's the new Items property:

`SortByColumns(Filter(MyCalendarEvents, Text(startWithTimeZone,ShortDate) = Text(_dateSelected,ShortDate)), "start")`

Various properties elsewhere will need to be changed as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9451acad-432a-1f11-8204-238de8655846
* Version Independent ID: 16134a5a-2880-4221-32b9-256f0573620b
* Content: [Calendar-screen template in canvas apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/screen-templates/calendar-screen-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JSpradlinZF. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@JSpradlinZF thank you for the feedback. I am will waiting on internal feedback to see if the V3 action for the connector.

Thanks,
Mints

**Comment by mduelae** [comment]
@JSpradlinZF I spoke with my internal team and this is a know issue. For now, they are working on fixing this. 

Thank you,
Mints
