### ISSUE TITLE
Dissociate request returns 500 error

### ISSUE THREAD

**Issue by abigailpham** [MicrosoftDocs/powerapps-docs#4028]
Hi! I have tried to use the first example WebAPI PATCH request for "Disassociate with a single-valued navigation property", but it has returned an HTTP 500 error every time.

![image](https://user-images.githubusercontent.com/101664027/217337589-fa5ab9b9-34de-4eab-a016-d9a3e2fa3564.png)

Here is one of the errors we've received:
![image](https://user-images.githubusercontent.com/101664027/217337846-6eea0b3e-3e05-4c6c-9ec9-2ef14057bbaf.png)

Our workaround includes using a DELETE operation instead. Also, taking out the "@odata.bind" works (which is documented on the page as well).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce0b1cd-e7ce-a9b8-6b51-37be0a4dd848
* Version Independent ID: 54eecc75-29fe-29ba-94c9-0ad0b8694d69
* Content: [Associate and disassociate table rows using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/associate-disassociate-entities-using-web-api#associate-and-disassociate-table-rows-on-update)
* Content Source: [powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by JimDaly** [comment]
@abigailpham 

Thanks for your feedback.

I tested this using the example from the docs.

**Request**

```
PATCH https://myorg.api.crm.dynamics.com/api/data/v9.2/contacts(e9e32a7f-b91c-ed11-b83e-000d3a572421) HTTP/1.1
Authorization: Bearer [Redacted]
Content-Type: application/json
User-Agent: PostmanRuntime/7.30.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 93879f01-6f4c-4c4d-b5af-e2ec61743fdd
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 51

{
  "parentcustomerid_account@odata.bind": null
}
```

**Response**

`HTTP/1.1 204 No Content`

And I confirmed that it works as expected for that relationship at least. It _should_ work for all. I can't explain why it isn't for you.

Sounds like you have a workaround, by not using `@odata.bind`.

If you want to use the documented syntax, or just raise this as a potential bug, you need to contact technical support.

@divkamath  FYI
