### ISSUE TITLE
Update the page

### ISSUE THREAD

**Issue by exchangeranger** [MicrosoftDocs/powerapps-docs#403]
Update the step screenshots, its been two years ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5df5f2bb-1e4d-ce52-0478-19fc7a16f9b3
* Version Independent ID: fc072fdb-3e49-5e12-e8ce-ddfebca0963f
* Content: [Add and manage connections from canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-manage-connections#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/add-manage-connections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-manage-connections.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. They're updated, please allow some time for changes to take effect.
