### ISSUE TITLE
Incorrect icons

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/powerapps-docs#4032]
Some of the product icons in the Popular Connectors section look to be out of date or incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7c89a8f-b16f-2896-faae-efbb438c7a89
* Version Independent ID: 8ce453b3-7e57-c80a-7ca0-9b122ad4796b
* Content: [Overview of connectors for canvas apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/connections-list)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Beschorr. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@Beschorr Thank you for the feedback. I updated the topic and removed the icons. The changes will reflect on our site by tomorrow morning. 

Thanks,
Mints
