### ISSUE TITLE
Invalid links to Learning Paths

### ISSUE THREAD

**Issue by marinaradckeJM** [MicrosoftDocs/powerapps-docs#4035]
The links to the Learning Paths are invalid / do not return the desired results.

For Power Automate, use:

https://learn.microsoft.com/en-us/training/browse/?terms=power%20apps&levels=beginner&expanded=power-platform&products=power-automate&resource_type=learning%20path

For Power Apps, use:

https://learn.microsoft.com/en-us/training/browse/?terms=power%20apps&levels=beginner&expanded=power-platform&resource_type=learning%20path&products=power-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afbd516b-05bb-575f-93fa-59f1fe5f57ff
* Version Independent ID: c2181b3d-e0b3-a263-d9df-0d46b9ed7b59
* Content: [Integrate Power Apps, Power Automate, and Power BI with SharePoint Online - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/sharepoint-scenario-intro)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-scenario-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/sharepoint-scenario-intro.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @marinaradckeJM. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@marinaradckeJM - Thank you for the feedback. I've fixed the links to the learning paths. You should see the changes go live by 5pm Pacific Time.

Thanks,
Mints
