### ISSUE TITLE
Recommended way to convert PowerApps Form to a PowerApps App?

### ISSUE THREAD

**Issue by bubbleswap** [MicrosoftDocs/powerapps-docs#404]
- [X]  Question
- [ ]  Bug
- [ ] Enhancement

We have several lists created as a PowerApps Form, but want some to be an App also, as the list is used to gather from both browser users and for convenience, making it available on mobile devices. 

Currently it seems that the method would be to create two separate tools, one is PA Form and one is PA App, and when edits occur, both will need to be updated. Any suggestions on maintaining or converting PS Forms to PA App with minimal disruption and effort?

TIA!

**Comment by AFTOwen** [comment]
From @emcoope-msft:
Currently there is no easy way to "duplicate" custom forms as apps. The integration object has special properties for its embedding scenario that isn't applicable for a standalone app. The other suggestion is to use copy (Ctrl + c) and paste (Ctrl+v) on the controls in your form to move them over to the new app at authoring time. You will still have to fix up items with the new data source, but you are able to carry forward the form to some amount. 

Another different option is you can embed custom forms further in sharepoint pages by taking the url in PowerApps Studio to embed the form as a web part in a SharePoint page if that suits the scenario in mind.

Packaging and reuse of custom forms is something that the PowerApps and SharePoint teams are looking to improve.

**Comment by AFTOwen** [comment]
Thanks, @bubbleswap for your feedback. Please see the previous comment for an explanation.
