### ISSUE TITLE
Link : `Data types in Power Apps` is giving 404 - Page not found error

### ISSUE THREAD

**Issue by prabdeb** [MicrosoftDocs/powerapps-docs#4044]
On click of `Data types in Power Apps` under section https://learn.microsoft.com/en-us/power-apps/limits-and-config#data-types-size-limits the following URL got opened https://learn.microsoft.com/en-us/power-platform/power-fx/reference/power-platform/power-fx/data-types.md#text-hyperlink-image-and-media

Where I am getting 404 - Page not found error, Please check and provide the right URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdf0872-929b-e44a-dedd-eb6a759915f2
* Version Independent ID: 0b65b025-62f8-fc2a-0026-3cb96b7b4554
* Content: [Power Apps system requirements and limits - Power Apps](https://learn.microsoft.com/en-us/power-apps/limits-and-config)
* Content Source: [powerapps-docs/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/limits-and-config.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **gregli**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @prabdeb. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@prabdeb Thanks for the feedback. The link should point to: https://learn.microsoft.com/en-us/power-platform/power-fx/data-types#text-hyperlink-image-and-media 

I fixed the link in the help topic and the changes will go live by 5PM Pacific Time.

Thanks,
Mints
