### ISSUE TITLE
Error en ejemplo del manual.

### ISSUE THREAD

**Issue by c6j6g7g7** [MicrosoftDocs/powerapps-docs#4047]
Error en ejemplo:  Calcular tiempos basándose en horas, minutos y segundos

Numeral 4. 

Text(Time(Value(Hour.Selected.Value), Value(Minute.Selected.Value), 0), DateTimeFormat.ShortTime)

Debe cambiarse por:

Text(Time(Value(Hour.SelectedText.Value), Value(Minute.SelectedText.Value),0), DateTimeFormat.ShortTime)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2548fd17-5e1c-99d3-b7f7-a0b48c56c2bf
* Version Independent ID: f645f526-3e2c-ae5f-965d-a64c6a9094df
* Content: [Mostrar texto, fechas y horas en aplicaciones de lienzo - Power Apps](https://learn.microsoft.com/es-es/power-apps/maker/canvas-apps/show-text-dates-times)
* Content Source: [powerapps-docs/maker/canvas-apps/show-text-dates-times.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/show-text-dates-times.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @c6j6g7g7. This issue has been assigned to the doc author for review.

**Comment by Bernadette2022** [comment]
The feedback exist in the english .md file and not specific to the localize file.  According to the feedback, the following :

Text(Time(Value(Hour.Selected.Value), Value(Minute.Selected.Value), 0), DateTimeFormat.ShortTime)

Should be changed to 
Text(Time(Value(Hour.SelectedText.Value), Value(Minute.SelectedText.Value),0), DateTimeFormat.ShortTime)

**Comment by mduelae** [comment]
Thank you for the feedback. The typo in the formula has been fixed. You will see the changes in the English version of this topic:
https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/show-text-dates-times

It will take a few weeks for the updates to reflect in your local language. 

Thank you,
Mints
