### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by rswafford** [MicrosoftDocs/powerapps-docs#405]
All Swagger documentation links are broken, and additionally, the Metadata endpoint returns a 404 (https://discovery.crmreplication.azure.net/crm/exporter/metadata/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b78e7a4-a539-c230-0a8c-454f1f69201a
* Version Independent ID: 777f3fea-cd80-9233-715f-4947cb1077f9
* Content: [Data export service (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/data-export-service#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/data-export-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/data-export-service.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
@rswafford Thanks for reporting this. We are aware of this issue, and working with the product team to resolve it soon. I'll keep this issue open until we fix it.

**Comment by KumarVivek** [comment]
@rswafford The links are fixed now. Thanks for reporting it.
