### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by bronsonacoutts** [MicrosoftDocs/powerapps-docs#4055]
The link to the Inspection/Audit app documentation is broken.

URL looks to point to a GitHub page, but returns a 404 from GitHub.

https://learn.microsoft.com/en-us/powerapps/teams/inspection

Bronson
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ddea684-3144-f89e-96f2-9f565084e8aa
* Version Independent ID: f9143285-9077-b66c-2a2e-b07bb69ad573
* Content: [Power Apps pattern: Inspection - Power Apps](https://learn.microsoft.com/en-us/power-apps/guidance/patterns/inspection-pattern#template-inspection-solution-for-microsoft-teams)
* Content Source: [powerapps-docs/guidance/patterns/inspection-pattern.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/guidance/patterns/inspection-pattern.md)
* Service: **powerapps**
* Sub-service: **guidance**
* GitHub Login: @kathyos
* Microsoft Alias: **kathyos**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bronsonacoutts. This issue has been assigned to the doc author for review.

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Link is fixed and the topic will reflect the changes soon.
