### ISSUE TITLE
Work-around for Excel connection via SharePoint

### ISSUE THREAD

**Issue by mvance-lumen** [MicrosoftDocs/powerapps-docs#4059]
What is the work-around for this "The ability to connect to Excel files on SharePoint sites is still in Preview. Connecting to Excel files on OneDrive is supported."? And when will sharepoint sites be out of Preview? I have a file I want to connect to via Sharepoint where it is "public" within my company, so I cannot use OneDrive which is personal to my account.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b719e1a-4f88-b73c-69c0-8165490916ff
* Version Independent ID: 9f348a2d-9909-a832-0269-6ddddd3b14e5
* Content: [Connect to Excel from Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/connections/connection-excel)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-excel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/connections/connection-excel.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mvance-lumen. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@mvance-lumen I have send your feedback to our internal team. You can also submit product feedback here:  https://ideas.powerapps.com.

If you're something isn't working correct please contact support: https://powerapps.microsoft.com/support/

Thanks,
Mints
