### ISSUE TITLE
"Update admin list" paragraph has a small mistake

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerapps-docs#406]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/powerapps-docs.it-it/issues/2

@francescozitelli commented 4 hours ago
OnStart dropdown is included in App selector, and not in LoginScreen container.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @yijw2017
* Microsoft Alias: **yijw**

**Comment by wajji93** [comment]
I keep getting an invalid connection error even though my connections are connected. Can someone help me with this?

**Comment by HED-vmedvedev** [comment]
Have the same connection problem. Any idea how to fix it?

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback, doc is updated. 

@wajji93 , @HED-vmedvedev Please contact [support team](https://powerapps.microsoft.com/en-us/support/pro/) for help with resolving environmental issues.
