### ISSUE TITLE
Could you tell me sync interval about access to dataverse?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/powerapps-docs#4062]
[Enter feedback here]

Hi, team. One customer want know sync interval about access to dataverse, but this information was not written on docs. 

Question1：Could you tell me sync interval about access to dataverse?   I want know correct specification.

Question 2：If synchronization stops, the system sends alert for dataverse's owner? 

Best regards,
Daishi.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0371ed0e-974c-5a94-0ba4-f7f1aee43deb
* Version Independent ID: 0371ed0e-974c-5a94-0ba4-f7f1aee43deb
* Content: [Migrate Microsoft Access data to Microsoft Dataverse (contains video) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/migrate-access-to-dataverse?source=docs)
* Content Source: [powerapps-docs/maker/data-platform/migrate-access-to-dataverse.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/migrate-access-to-dataverse.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by dshimogawa** [comment]
Please allow me to send you a gentle reminder.
I want your reply by the end of Tuesday.

I'm afraid you are busy, but we look forward to your reply.

Thank you.

Best regards,
Daishi

**Comment by NHelgren** [comment]
@dshimogawa When data is migrated from Access to Dataverse there is no synchronization. post migration all data lives in Dataverse for the migrated tables. Whenever you use an Access form or open the table you are looking at the data in Dataverse. If there are updates in Dataverse while Access is currently open, right now a manual refresh is needed to see the changes (if looking at a table view or a report or query). But all other data is pulled live.

**Comment by dshimogawa** [comment]
Hi, @NHelgren.
Sorry for replying late. I could understand specification about access to dataverse. Thank you for your help.

Best regards,
Daishi
