### ISSUE TITLE
Needs `props` description

### ISSUE THREAD

**Issue by RickyRoeslerMS** [MicrosoftDocs/powerapps-docs#407]
This page needs a description of the popup properties that can be set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c47b28-b5c1-d534-66d2-8a6f2100ff01
* Version Independent ID: f277b3f7-cbcd-2db8-3b3a-742c3f9b2f64
* Content: [createPopup - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/popupservice/createpopup)
* Content Source: [powerapps-docs/developer/component-framework/reference/popupservice/createpopup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/popupservice/createpopup.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by ghurlman** [comment]
@RickyRoeslerMS As you can see on the page, the param is of type `Popup`, which is defined here in the docs: https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/popup

**Comment by RickyRoeslerMS** [comment]
Ah ok, I misunderstood what that was saying. Thank you!

**Comment by Nkrb** [comment]
@RickyRoeslerMS Closing the issue
