### ISSUE TITLE
Missing space in documentation text

### ISSUE THREAD

**Issue by bambooch** [MicrosoftDocs/powerapps-docs#4074]
Need a space between words 'Key' and 'dialog' on the following page https://learn.microsoft.com/en-us/power-apps/developer/data-platform/tutorial-write-plug-in#sign-the-plug-in

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/22875244/220353718-29e5b796-70e0-47e4-aca6-010f3f2c2b8b.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad2eb047-525a-63b7-2d6e-1536a374d688
* Version Independent ID: 2b8e3e9d-c957-d43e-ceeb-c75da0857d2d
* Content: [Tutorial: Write and register a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tutorial-write-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bambooch. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@bambooch Fixed. Thanks.
