### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by AndrewYueLiu** [MicrosoftDocs/powerapps-docs#4078]
[Enter feedback here]
Please update this line 
"Open Settings and switch to Upcoming", the 'In-app notifications' is under Features now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f495f03e-28c9-0ebb-ef03-72e16b267b3a
* Version Independent ID: a9dcec59-8b72-966e-fa53-f4b2e42d325e
* Content: [Send in-app notifications within model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AndrewYueLiu. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@AndrewYueLiu 
Thanks for calling this out. I have verified and fixed this.
