### ISSUE TITLE
Shift+Enter to move to next line

### ISSUE THREAD

**Issue by thatapiguy** [MicrosoftDocs/powerapps-docs#408]
Shift + Enter should be added in this list for the editing/authoring experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955cb34a-35ce-b369-a83b-b68195de2a63
* Version Independent ID: e7503f23-33ab-2a1a-6796-ea6d96b64146
* Content: [Keyboard shortcuts for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/keyboard-shortcuts?WT.mc_id=twitter#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Added. Thanks, @thatapiguy! Closing issue.
