### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/powerapps-docs#4086]
There appears to be a minor typo in sentence: "For a reliable security, use more secure connection such as [Azure AD Integrated](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/connections-list#azure-ad-integrated)."

Perhaps it should read "For reliable security, use a more ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7c89a8f-b16f-2896-faae-efbb438c7a89
* Version Independent ID: 8ce453b3-7e57-c80a-7ca0-9b122ad4796b
* Content: [Overview of connectors for canvas apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/connections-list#security-and-types-of-authentication)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HandyAndyOnGitHub. This issue has been assigned to the doc author for review.

**Comment by ProfessorKendrick** [comment]
Thanks for identifying this typo.  I've made the corrections. Closing the issue.
