### ISSUE TITLE
Barcode scanner not reading PDF417 codes

### ISSUE THREAD

**Issue by rodolfo1860** [MicrosoftDocs/powerapps-docs#409]
The barcode scanner control cannot read PDF 417 codes on my Android 8.0 mobile.  

Could you pls verify it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7944b4d0-c3be-afa0-4af1-21c9c27b56e2
* Version Independent ID: c2ca93fd-9817-8300-fcc4-a6999659e0a2
* Content: [Barcode-scanner control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-new-barcode-scanner#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by jerict** [comment]
The same problem here. PDF 417 codes are not readable using barcode scanner. 

Hardware: Samsung J7 Pro 
OS: Android Version 9
PowerApps: 3.19072.11  (mobile app)

**Comment by jerict** [comment]
https://play.google.com/store/apps/details?id=com.pnn.scankeyboard&hl=en_SG


This app works  best so far. It scans really fast. Hope Microsoft can make one of these. It is just that it's too sensitive to take the value of the other barcodes near the target.

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. Please use the [BarcodeType](https://docs.microsoft.com/powerapps/maker/canvas-apps/controls/control-new-barcode-scanner#additional-properties) property with other than Auto. Note that the property defaults to **Auto** and *PDF_417* is [not supported](https://docs.microsoft.com/powerapps/maker/canvas-apps/controls/control-new-barcode-scanner#barcode-availability-by-device) in auto mode.
