### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#4090]
in
https://learn.microsoft.com/en-us/power-apps/maker/portals/admin/portal-admin-roles#system-customizer

To assign a user the System administrator Power Platform role
should be
To assign a user the System **customizer** Power Platform role

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff0331e6-6c2b-4728-4c3b-3e141c285dc7
* Version Independent ID: 936bdd2f-3b1e-45d9-ed1a-c2c13e45ba46
* Content: [Roles required for portal administration - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/admin/portal-admin-roles#system-customizer)
* Content Source: [powerapps-docs/maker/portals/admin/portal-admin-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/admin/portal-admin-roles.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CarstenMS. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment]
Thanks for catching that. Typo fixed and will be live in a few hours.
