### ISSUE TITLE
Offline Sync Icon - does it work for both offline first and classic?

### ISSUE THREAD

**Issue by seanscotty** [MicrosoftDocs/powerapps-docs#4093]
Does new offline status indicator apply only to classic offline or offline-first as well?

The below quoted known issue for switching between online/offline modes only applies to classic.  So curious if this feature only applies to classic.... which would be disappointing

"The first time the app syncs, the offline sync icon continues to spin until the user switches from online mode to offline mode."

if you feel like letting me know the answer directly as well sscott@firstkeyhomes.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c10aad2-780a-c081-4514-0ac81562a1b5
* Version Independent ID: 8c10aad2-780a-c081-4514-0ac81562a1b5
* Content: [View offline sync status (preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/mobile/offline-sync-icon)
* Content Source: [powerapps-docs/mobile/offline-sync-icon.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/mobile/offline-sync-icon.md)
* Service: **powerapps**
* Sub-service: **mobile**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @seanscotty. This issue has been assigned to the doc author for review.

**Comment by sericks007** [comment]
@seanscotty, thank you for your feedback.  The offline sync icon applies to both offline classic and offline first.
