### ISSUE TITLE
Edit and Display Forms do not appear as above

### ISSUE THREAD

**Issue by CFarinha** [MicrosoftDocs/powerapps-docs#410]
When I create an Edit or Display form and then set the data source and fields the way the form displays is not at all like in the above images. Instead it just displays the field names. How do I get these forms to display properly like at the top of this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 280091f4-274b-32f9-eaac-d526c8851404
* Version Independent ID: f55d8425-89dd-ea1b-e556-f17ded9acd56
* Content: [Display form and Edit form controls: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-form-detail#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-form-detail.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-form-detail.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **aneesa**

**Comment by KeoiMadBro** [comment]
You need to modify the properties of the fields.

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. You can adjust the position and size properties from right side property dialog box, or using the drop down on upper navigation. Position is also explained in the article as X and Y properties.
