### ISSUE TITLE
Please add information about naming restriction

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/powerapps-docs#4100]
[Enter feedback here]
Please consider following error, I've got for an return parameter with its unique name "Sales.Opportunity.RetrieveOpportunityPDFs.Response.Error":

The property name 'Sales.Opportunity.RetrieveOpportunityPDFs.Response.Error' is invalid; property names must not contain any of the reserved characters ':', '.', '@'.

It's important to document the restriction about usage of special characters.

Thanks,
Alexander
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbd53494-e9ff-33b0-d857-bcd235233aa5
* Version Independent ID: a362d3d7-3d5c-9222-39e6-dd426f96c4a4
* Content: [Create and use Custom APIs (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/custom-api)
* Content Source: [powerapps-docs/developer/data-platform/custom-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/custom-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @soutchilin. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@soutchilin 
Thanks for your feedback. I've added information regarding the `UniqueName` attribute for all the custom api tables to call out that special characters are not allowed.  This information will be in the [CustomAPI tables](https://learn.microsoft.com/power-apps/developer/data-platform/custom-api-tables) article.
