### ISSUE TITLE
Display Name field character limits

### ISSUE THREAD

**Issue by cwanja-msft** [MicrosoftDocs/powerapps-docs#4108]
Is there a way to add character limits on Display Name somewhere in the documentation? Looks like it is set to 50 characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b79b18b-5e43-83dd-3b80-d350809252a8
* Version Independent ID: fe217d23-b87b-a02e-315c-a1648a9df898
* Content: [Fields overview in Power Apps (contains video) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/fields-overview)
* Content Source: [powerapps-docs/maker/data-platform/fields-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/fields-overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cwanja-msft. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@cwanja-msft - Thank you for your feedback. Your comment is a feature request that's outside the scope of the documentation. You can submit your feature request here: https://ideas.powerapps.com
Closing issue.
