### ISSUE TITLE
Link to registration form should be updated

### ISSUE THREAD

**Issue by qianw211** [MicrosoftDocs/powerapps-docs#411]
The link points to the nomination form. It should point instead to https://partner.microsoft.com/en-us/dashboard/account/v3/enrollment/introduction/azureisv

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a771ce0b-c24d-d9e1-c7bd-8aba7c77e3c1
* Version Independent ID: 16927105-150c-cd9f-3b82-9e1d0125b54d
* Content: [Step 1: Fill the app submission form on AppSource (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/fill-app-submission-form-appsource#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/fill-app-submission-form-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/fill-app-submission-form-appsource.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@qianw211 Fixed. Thanks
