### ISSUE TITLE
Missing entry for Vertical Container and Horizontal Container

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/powerapps-docs#4128]
[Enter feedback here]
The list of controls on this overview/listing page doesn't seem to have a reference to the Vertical Container or the Horizontal Container, though both control types do have pages:

https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-vertical-container

https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-horizontal-container

Ideally, it would also be nice to have some mention of those controls and/or "Recommended content" entries for those controls' pages from the Container control's page ( https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-container ) as currently there is only an entry for the Horizontal Container from that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8befb37d-cf89-671a-84e1-88615258ad2f
* Version Independent ID: dc4bc297-e51a-3d6f-a8d9-36be050416d8
* Content: [Controls and properties in canvas apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/reference-properties)
* Content Source: [powerapps-docs/maker/canvas-apps/reference-properties.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/reference-properties.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DTronD. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@DTronD thank you for the feedback. I have added links to Vertical Container or the Horizontal Container control to the main topic. Thank you for pointing this out. You should see the updates by the end of day today on our website.

Thanks,
Mints
