### ISSUE TITLE
Example App.ActiveScreen incomplete

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerapps-docs#413]
Hi team, 
I'm copying this from here: https://github.com/MicrosoftDocs/powerapps-docs.nl-nl/issues/6

@roccobogers commented 4 hours ago 
&gt; The Example App.ActiveScreen = PlayBall does not work
&gt; It Should be: App.ActiveScree.Name = Playball

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68490e51-ae25-ff32-0dd7-9eaf1f5f81d5
* Version Independent ID: 7389a5be-5e77-7238-7eaa-13380ce3908a
* Content: [Acceleration, App, Compass, Connection, and Location signals - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/signals#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/signals.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/signals.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
@CeciAc.  Actually either approach will work.  With App.ActiveScreen = PlayBall, we are comparing screen control objects; with App.ActiveScreen.Name = "PlayBall", we are comparing strings for the name (note it needs to be a string).  Both should give the same answer and I just verified that in an app (see screenshots below. first 3 are from screen Screen1, second 3 from screen PlayBall).  

Working with just the ActiveScreen object is a little more concise and direct.

![2019-05-25_12h00_51](https://user-images.githubusercontent.com/15149773/58373555-dc966d80-7ee4-11e9-8962-13a1bebd2b00.png)
![2019-05-25_12h00_57](https://user-images.githubusercontent.com/15149773/58373556-dc966d80-7ee4-11e9-85e4-a4ab6f588bc4.png)
![2019-05-25_12h00_59](https://user-images.githubusercontent.com/15149773/58373557-dc966d80-7ee4-11e9-99ff-00b00331dbd6.png)
![2019-05-25_12h01_05](https://user-images.githubusercontent.com/15149773/58373558-dc966d80-7ee4-11e9-9cba-667e62acc50a.png)
![2019-05-25_12h01_08](https://user-images.githubusercontent.com/15149773/58373559-dc966d80-7ee4-11e9-8edd-28d053b8cc48.png)
![2019-05-25_12h01_11](https://user-images.githubusercontent.com/15149773/58373560-dc966d80-7ee4-11e9-91e5-cc5150e1b9e7.png)

**Comment by gregli-msft** [comment]
@AFTOwen, please close this issue.
