### ISSUE TITLE
in the article it says, click data, then click connections. I don't see the connections tab

### ISSUE THREAD

**Issue by justgivemeanumber** [MicrosoftDocs/powerapps-docs#4133]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b116f6be-9483-b253-71cc-4fe72e86f934
* Version Independent ID: 5b342fc5-9fdb-a81e-2792-06c800a28d2b
* Content: [Add data connections to canvas apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/add-data-connection)
* Content Source: [powerapps-docs/maker/canvas-apps/add-data-connection.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/add-data-connection.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @justgivemeanumber. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
Thank you for the feedback. The topic has been updated and you should see the updates on our site in 24 hours.

Thanks,
Mints
