### ISSUE TITLE
Great documentation but not easily to maintain.

### ISSUE THREAD

**Issue by vincentnoiset** [MicrosoftDocs/powerapps-docs#4138]
Great documentation but not easily to maintain.

Generally apps are done by IT or citizen developer in his own language.  Then he ask business user (because often terms used are business oriented) to translate terms.
This solution as import excel table uses static data.  And Excel is easier to maintain than json file.
Now, if we want business user to translate, either we give them excel file or we pull all translation in SharePoint list.

Do you see another way to easily maintain translations ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70b557d3-7967-698e-38e0-e28ad06df9df
* Version Independent ID: 55105264-7746-12ac-b3db-c34eb96b429f
* Content: [Build a multi-language app - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/multi-language-apps)
* Content Source: [powerapps-docs/maker/canvas-apps/multi-language-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/multi-language-apps.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @mduelae
* Microsoft Alias: **lunune**

**Comment by mduelae** [comment]
@vincentnoiset This is a great question. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support.

Thanks,
Mints
