### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by anbhar** [MicrosoftDocs/powerapps-docs#4148]
What do notifications look like in an actual app? Can you please add a screenshot so users know what to expect?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f495f03e-28c9-0ebb-ef03-72e16b267b3a
* Version Independent ID: a9dcec59-8b72-966e-fa53-f4b2e42d325e
* Content: [Send in-app notifications within model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by JimDaly** [comment]
@anbhar 

Thanks for your feedback.

This article is for developers who will create in-app notifications using code. The [Examples section](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi#examples) includes screenshots for all the examples provided, but the general experience that users will have is documented elsewhere. We don't want to repeat it here.

@adrianorth added a sentence to the introduction that should help direct people to where this information is provided.

> To see how these notifications appear in applications, see [In-app notifications in model-driven apps](https://learn.microsoft.com/en-us/power-apps/user/notifications).

I hope this helps address this issue.
