### ISSUE TITLE
Error when using calendar template.

### ISSUE THREAD

**Issue by lukascaplikas** [MicrosoftDocs/powerapps-docs#4151]
If you receive a lot of errors when using calendar template just change Days to TimeUnit.Days. All error will be gone.
Please update code accordingly:

Instead of 
DateAdd(_firstDayInView,ThisItem.Value,Days)
It should use:
DateAdd(_firstDayInView,ThisItem.Value,TimeUnit.Days)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9451acad-432a-1f11-8204-238de8655846
* Version Independent ID: 16134a5a-2880-4221-32b9-256f0573620b
* Content: [Calendar-screen template in canvas apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/screen-templates/calendar-screen-overview)
* Content Source: [powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-overview.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lukascaplikas. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment]
@lukascaplikas Thanks for your feedback. I'm confirming the information with our internal team. When I hear back from them I will send you an update.

Thanks,
Mints

**Comment by mduelae** [comment]
@lukascaplikas I've updated the topic with the correct information. You will see the updated content by the end of day today.

Thanks,
Mints
