### ISSUE TITLE
.net 6 way to do Microsoft.CrmSdk.CoreAssemblies?

### ISSUE THREAD

**Issue by wrharper-AASP** [MicrosoftDocs/powerapps-docs#4152]
Is there an alternative new way to do this? 4.8 is really out of date these days.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08cd0714-ecf3-a37e-32da-a336f5402fb6
* Version Independent ID: 9d7be299-ec79-62fd-c3e7-48f6bc23069b
* Content: [Register a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/register-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/register-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/register-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @wrharper-AASP. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@wrharper-AASP You must use .NET Framework 4.6.2 for plug-in development. That is the only build target supported (for plug-ins) on the Dataverse servers. For application development you can use .NET 6+ with the Microsoft.PowerPlatform.Dataverse.Client NuGet package.
