### ISSUE TITLE
Typo in page

### ISSUE THREAD

**Issue by gjbundy** [MicrosoftDocs/powerapps-docs#4158]
[Package and distribute Eetensions with solutions](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/introduction-solutions).

should say Extensions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 055d79cf-cde8-11b5-0ec8-874a753f7d7e
* Version Independent ID: 7a7ee69d-a3a7-bced-b2cd-8d7da292424a
* Content: [Ribbon types schema (model-driven apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/ribbon-types-schema)
* Content Source: [powerapps-docs/developer/model-driven-apps/ribbon-types-schema.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/ribbon-types-schema.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gjbundy. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@gjbundy 
Thanks for catching this. I've fixed it.
