### ISSUE TITLE
Info in document doesn't match with UI

### ISSUE THREAD

**Issue by omarjimz** [MicrosoftDocs/powerapps-docs#4162]
[Enter feedback here]
The document says "Enable SDK messages and flows included in the solution" but the UI currently says " Enable Plugin steps and flows included in the solution"

---
#### Document Details

⚠ *Do not edit this section. It is required for lear
![OneNote (Business) and 14 more pages - Testing - Microsoft​ Edge-000631](https://user-images.githubusercontent.com/12615758/224260981-35b79501-ebe0-42db-b3a3-be083e65dc47.png)
n.microsoft.com ➟ GitHub issue linking.*

* ID: 5a00b4a6-c147-cffa-92c9-5cb183c4ea67
* Version Independent ID: 83d7d42c-71f3-1138-318f-5bd252a2ab3b
* Content: [Import solutions - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/import-update-export-solutions?source=docs)
* Content Source: [powerapps-docs/maker/data-platform/import-update-export-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/import-update-export-solutions.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @omarjimz. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@omarjimz - Thank you for your feedback. You're correct and the article has been updated to reflect the current import UI.

Closing issue.
