### ISSUE TITLE
OnTestSuiteComplete - Send mail Step not working 

### ISSUE THREAD

**Issue by xguitoux** [MicrosoftDocs/powerapps-docs#4163]
[Tapez vos commentaires ici]
The Office365.SendMailV2 is not working (on my interface in french) , I found that Office365Outlook.SendEmailV2 is the right syntax

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b15deb16-02e4-9005-2dbd-917f8308b47d
* Version Independent ID: 51cc413b-0fd1-5a63-ddfa-16b3fb4c9e88
* Content: [Utilisation de Test Studio (contient une vidéo) - Power Apps](https://learn.microsoft.com/fr-fr/power-apps/maker/canvas-apps/working-with-test-studio#processing-test-results)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-test-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/working-with-test-studio.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @aengusheaney
* Microsoft Alias: **aheaney**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @xguitoux. This issue has been assigned to the doc author for review.

**Comment by Bernadette2022** [comment]
@mduelae can you please take a look at the comment. The feedback is not specific to translation but applies to english content. 

Per user:
Office365.SendMailV2("someone@example.com", "Test case results", JSON(TestCaseResult, JSONFormat.IndentFour))

should be 
Office365Outlook.SendEmailV2("someone@example.com", "Test case results", JSON(TestCaseResult, JSONFormat.IndentFour))

**Comment by mduelae** [comment]
@TashasEv is this something you can validate?

**Comment by mduelae** [comment]
@xguitoux The is a bug in the product. Our internal team is aware of this and is working on the issue.

Thank you,
Mints
