### ISSUE TITLE
Xrm.App.sidePanes is undefined

### ISSUE THREAD

**Issue by GameWhisper** [MicrosoftDocs/powerapps-docs#4168]
Our CRM is Dynamics 365 On-Premises(9.1.0015.0032) but I used Xrm.App.sidePanes , It's undefined.
I installed 'CRM9.1-Server-KB5021375-ENU-amd64.exe', It's show again, I lost something?
![image](https://user-images.githubusercontent.com/19793691/224618326-a9e34b00-4d6f-48b3-93ec-73128bc5c6a8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1195d85-d0c1-da87-c015-206fc72e94dd
* Version Independent ID: 51bfed40-9fee-e31e-3935-d69d217c5c9c
* Content: [createPane (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-app/xrm-app-sidepanes/createpane)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-App/Xrm-App-sidePanes/createPane.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-App/Xrm-App-sidePanes/createPane.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GameWhisper. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@GameWhisper

Thanks for your feedback. Sorry for the late response.

In [Client API Reference for model-driven apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference) we call out:

> Most of the client scripting APIs available in this documentation also apply to Dynamics 365 Customer Engagement (on-premises). For a list of client scripting APIs not available for Customer Engagement (on-premises), see [Client scripting reference for Dynamics 365 Customer Engagement (on-premises)](https://learn.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/clientapi/reference).

That page was updated to reflect that `Xrm.App.sidePanes` are not supported for on-premises deployments.

[Client APIs not supported in Customer Engagement (on-premises)](https://learn.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/clientapi/reference?view=op-9-1#client-apis-not-supported-in-customer-engagement-on-premises)

I hope this addresses your question.
