### ISSUE TITLE
Step 3: switch to classic, option is not available

### ISSUE THREAD

**Issue by mvdvook** [MicrosoftDocs/powerapps-docs#4169]
[Enter feedback here]
Hi,

I don't see the option 'Switch to Classic mode'  anywhere.
I am creating a canvas app based on a dataverse table.

Regards,
Maaike van der Veen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c77405e5-5eb7-d734-8908-7ac93082a306
* Version Independent ID: c77405e5-5eb7-d734-8908-7ac93082a306
* Content: [Set up mobile offline (classic) - Power Apps](https://learn.microsoft.com/en-us/power-apps/mobile/setup-mobile-offline-classic)
* Content Source: [powerapps-docs/mobile/setup-mobile-offline-classic.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/mobile/setup-mobile-offline-classic.md)
* Service: **powerapps**
* Sub-service: **mobile**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mvdvook. This issue has been assigned to the doc author for review.

**Comment by mvdvook** [comment]
Hi,

 

This is not an issue, the page is about Model Driven apps apparently, not for canvas apps. 

Sorry!

Regards,

Maaike van der Veen

 

Van: Bishal Goswami ***@***.***> 
Verzonden: Monday, March 13, 2023 11:01 AM
Aan: MicrosoftDocs/powerapps-docs ***@***.***>
CC: mvdvook ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MicrosoftDocs/powerapps-docs] Step 3: switch to classic, option is not available (Issue #4169)

 

Thanks for your comment, @mvdvook <https://github.com/mvdvook> . This issue has been assigned to the doc author for review.

**Comment by sericks007** [comment]
Closing, per previous comment.
