### ISSUE TITLE
Please add a note that Polymorphic lookups can't be used as relations on parent (child) scope

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#4177]
[Enter feedback here]
PowerApps now support Polymorphic lookups for relationships per
https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-references#polymorphic-lookups

(where the parent can be one of multiple different entities)

Parent/Child scope for Portal Table permissions currently only handles "classic" / non polymorphic links to SINGLE entities correctly
so only these relations can be used for the Parent scope

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 149a494d-d9a5-8202-f8cd-b362cd7116f8
* Version Independent ID: 581f8b23-7a63-a132-d1c0-ed76527291f0
* Content: [Configure table permissions using portals Studio - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/entity-permissions-studio#configure-table-permissions-using-portals-studio)
* Content Source: [powerapps-docs/maker/portals/configure/entity-permissions-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/entity-permissions-studio.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @ckwan-ms
* Microsoft Alias: **ckwan**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CarstenMS. This issue has been assigned to the doc author for review.

**Comment by ProfessorKendrick** [comment]
Thank you for your comment.  I've added a note to our docs.
Closing this issue.
