### ISSUE TITLE
Please add a note that Polymorphic lookups can't be used as relations on parent scope

### ISSUE THREAD

**Issue by CarstenMS** [MicrosoftDocs/powerapps-docs#4178]
[Enter feedback here]

PowerApps now support Polymorphic lookups for relationships per
https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/working-with-references#polymorphic-lookups

(where the parent can be one of multiple different entities)

in section
https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/assign-entity-permissions#parental-access-type
please add a note that

Parent scope for Portal Table permissions currently only handles "classic" / non polymorphic links to SINGLE entities correctly
so only these relations can be used for the Parent scope

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a998-e70b-5947-ce64-0502f8941aba
* Version Independent ID: a22d0f82-a52b-78c1-f90a-796e5797c84b
* Content: [Set up security in portals with table permissions - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/configure/assign-entity-permissions)
* Content Source: [powerapps-docs/maker/portals/configure/assign-entity-permissions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/assign-entity-permissions.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @GitanjaliSingh33msft
* Microsoft Alias: **gisingh**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CarstenMS. This issue has been assigned to the doc author for review.

**Comment by ProfessorKendrick** [comment]
Thank you for your feedback.  We've added a note to our docs.

Closing this issue.
