### ISSUE TITLE
Keyboard languages affecting shortcuts

### ISSUE THREAD

**Issue by Eickhel** [MicrosoftDocs/powerapps-docs#418]
Hi,

Keyboard shortcuts don't work on all keyboard languages. For example, these shortcuts don't work correctly in Spanish keyboards:

Ctrl+]	Bring a control forward.
Ctrl+[	Send a control backward.
Ctrl+Shift+]	Bring to front.
Ctrl+Shift+[	Send to back.

But if I select US keyboard they do work correctly.

**Comment by AFTOwen** [comment]
Added note to at the top of the topic. Thanks, @Eickhel! Closing issue.
