### ISSUE TITLE
Create record offline error when setting value to multi-select (Choices) 

### ISSUE THREAD

**Issue by WhiteyC** [MicrosoftDocs/powerapps-docs#4180]
This is not documented as unsupported so assume this is a bug.
When setting string value "1" or "1,2,3" as an example to a multiselect option set attribute using Xrm.WebApi.offline.createRecord, the below error is presented. Note, createRecord works fine in online mode.

Error:
[ModernDataSource] remote data source is not available and error in local data source GCM
0x8005f211

If this is not supported, why is it not documented anywhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75f70840-ac77-de34-b797-233a4ff56d37
* Version Independent ID: e6b3d742-fe79-7442-0cae-d5dcba71f55f
* Content: [createRecord (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/createrecord)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/createRecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/createRecord.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @WhiteyC. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@lancedMicrosoft 
This seems to be about a difference of behavior between the Xrm.WebApi.offline and Xrm.WebApi.online clients when create a record with a 'Choices' column.

**Comment by JimDaly** [comment]
I found a workitem to fix this issue. Looks like it was a known issue and fixed now. No doc update needed.
Closing this.
