### ISSUE TITLE
Getting passed company internet log in page

### ISSUE THREAD

**Issue by PesceJonathan** [MicrosoftDocs/powerapps-docs#419]
I am currently building a Power App for Power BI using the custom visual. The issue I am running into comes due to the internet with the company I am with. The connection forces you to log in by bringing you to a log in page. The log in page will not load in the Power Apps causing it to simply not connect to the internet. The visualization works when I am on another network that does not require any credentials. Any ideas how to get around this problem? 
Thanks in advance for any help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f94c3-694a-6d09-3a4f-e4b741684822
* Version Independent ID: c952e698-a2bf-a47d-acbd-a96a8a922636
* Content: [PowerApps custom visual for Power BI - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual)
* Content Source: [powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/powerapps-custom-visual.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi, Sorry you're having difficulties logging in.  The fact that it works on other networks and not in your corporate network would lead me to believe this is an issue with the corporate network.  Can you elaborate what kind of device / app you're using and your current use case?

**Comment by PesceJonathan** [comment]
I can confirm that the issue comes from the network, since I see the logging in page for a sec, before it disapears. I wanted to know if their is a way to set as a cookie or as a parameter, such as in Google chrome which requires me to only log in once to the network, so that it can log in automatically and be able to connect to the web.

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. It appears there may be issues with browser or difference in zones (intranet, internet, trusted sites). If the issue still persists, please reach out for further assistance to investigate the issue via a [support service request](https://powerapps.microsoft.com/support/pro/).
