### ISSUE TITLE
Missing Terminologies like Tenant vs Org, Instance vs Environment

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/powerapps-docs#4195]
Missing Terminologies like Tenant vs Org, Instance vs Environment

Either update this page or give a direction to know more about replacement of terminologies for Tenant, Environment  vs Org, Instances. Devops too using organization, but not sure the org in PowerApps and Org in Devops are one and the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c1d9080-c711-ca93-f375-a918c42fcb80
* Version Independent ID: 5a07a012-10f6-604c-9668-8f322e2f56d1
* Content: [What is Microsoft Dataverse? - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-intro)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-intro.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sing-ideas. This issue has been assigned to the doc author for review.
