### ISSUE TITLE
Formula reference [examples of Collect function]

### ISSUE THREAD

**Issue by chalvares** [MicrosoftDocs/powerapps-docs#42]
It would be great if you could give more complex examples, for example when using a SharePoint list and working with choice fields, date pickers, people pickers etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c49101-d089-7743-582f-d44973632751
* Version Independent ID: ec080088-0d3f-f9fe-7090-c140bacfc07b
* Content: [Collect, Clear, and ClearCollect functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-clear-collect-clearcollect)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
@chalvares Thanks for your feedback! We're looking into this.

**Comment by savannahp** [comment]
Yes I am also looking for that as well! List and drop down menu

**Comment by AFTOwen** [comment]
@chalvares and @savannahp I've added a procedure and a couple of links that should help. Check it out! Thanks for your patience.
