### ISSUE TITLE
How to get sounds out?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#420]
Hello,
How do we get sounds OUT of PowerApps? I have the above example in an app; sounds are collected, displayed in a gallery, able to be played back. 

But how can I save them to a data source or send them through an API?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 258f140b-bc82-47a7-e915-79bebbd9b3b9
* Version Independent ID: d8a732b6-53b4-b161-3ff8-14de5fda89b3
* Content: [Microphone control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-microphone)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-microphone.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-microphone.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. Please use a [connector](docs.microsoft.com/connectors/) to connect to a data source to save files. You can also reach out to [Power Apps Community Forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1) for community discussions.

**Comment by SeaDude** [comment]
Thanks for the response. Your link 404's...
![image](https://user-images.githubusercontent.com/8636973/75086887-28b32480-54ee-11ea-8af5-04f8e194a3ed.png)

**Comment by tapanm-MSFT** [comment]
Connector reference: https://docs.microsoft.com/connectors/ - apologies for earlier hyperlink. Somehow it didn't grab https:// prefix.
