### ISSUE TITLE
Power Platform Tools - VS2019 extension

### ISSUE THREAD

**Issue by CatalinNTT** [MicrosoftDocs/powerapps-docs#4200]
When using the shortcut to "Open solution" (from Power Platform Explorer) this opens in the old UI:
**dynamics.com//tools/solution/edit.asp**x?id=

Instead, I would expect the modern extension to open the solution on **make.powerapps.com** domain.

**Comment by phecke** [comment]
@CatalinNTT Thanks for the feedback. I have passed your issue to the tool's engineering team.
