### ISSUE TITLE
Updating the data platform of Model-driven apps?

### ISSUE THREAD

**Issue by waygong** [MicrosoftDocs/powerapps-docs#4204]
Is it necessary to update the data platform of Model-driven apps from “Dataverse only” to something like Canvas that uses other connectors?

Here is the link that I think has a problem: https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/model-driven-app-overview#model-driven-and-canvas-apps-compared

You can refer to the following link for more information: https://learn.microsoft.com/en-us/power-apps/user/export-to-excel-online

**Comment by Mattp123** [comment]
@waygong - Canvas apps use connectors that are used as the app's data source. There are over 400 of them, including Dataverse. Model-driven apps _only connect and use Dataverse_ (as a matter of fact, it's a requirement). This is why the table states "Dataverse only" with model-driven apps.

Closing issue.
