### ISSUE TITLE
why is SelectedItems not listed?

### ISSUE THREAD

**Issue by fxvn78** [MicrosoftDocs/powerapps-docs#421]
lists support more than one item as shown by the example but documentation does not tell the reader, that the selected items property exists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d88b0533-cc96-d278-7cbe-49c525242460
* Version Independent ID: 9c30e215-917d-f14b-81b1-bb6fed445cd1
* Content: [List Box control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-list-box#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-list-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-list-box.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by Geradav** [comment]
Indeed "SelectedItems" and "SelectedItemsText" are missing in the list of properties

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The documentation has been updated.
