### ISSUE TITLE
I want you to write more about cascade processing

### ISSUE THREAD

**Issue by YoshikaSuzuki** [MicrosoftDocs/powerapps-docs#4214]
I received some request from a customer about this page, so I'd like to give you some feedback.

-Please clarify what happens when each option is selected for the question described in the action
-If user was the owner of the parent record, when the Repairment is cascaded, they have the same operational privileges as the parent record, even if the child record is not shared.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9db73658-557a-e0a1-a7d5-90000fa5540e
* Version Independent ID: 3f1e141d-33ec-88ae-d511-93f2eadcdd76
* Content: [About table relationships for Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-entity-relationships#table-relationship-behavior)
* Content Source: [powerapps-docs/maker/data-platform/create-edit-entity-relationships.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/create-edit-entity-relationships.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @YoshikaSuzuki. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@YoshikaSuzuki - The article has been updated to link to the article section (below) that explains relationship behavior options in more detail.
https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-entity-lookup#add-advanced-relationship-behavior

Closing issue.
