### ISSUE TITLE
Markdown links are invalid

### ISSUE THREAD

**Issue by sheilagithub** [MicrosoftDocs/powerapps-docs#422]
Links to other markdown pages are invalid on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c35ea8-593c-3a84-5a72-26814efe3190
* Version Independent ID: 7ad9e59d-7d7f-3f9f-529b-b651c743e832
* Content: [Attributes in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@sheilagithub Thanks for reporting this issue; its resolved now and changes should be live shortly.

Closing the issue.
