### ISSUE TITLE
Regarding BPF Forms issues while including a Form Component Control.

### ISSUE THREAD

**Issue by krnaryal** [MicrosoftDocs/powerapps-docs#4227]
Hi,
I wanted to know when will the next update come regarding this new feature.
I have to include a Form Component control in a form where BPF is used and is currently showing unexpected behaviors as mentioned in the document.
Is work going on on this issue of BPF and when can I expect the nearest update?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 385e47fe-5e1a-edb0-6932-408621881a80
* Version Independent ID: 0f3d2630-2e3e-e194-de9f-b4314e444694
* Content: [Edit table records directly from another table’s main form - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/form-component-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/form-component-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/form-component-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **mspilde**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @krnaryal. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@krnaryal - Thanks for your feedback. For product-related feedback, visit [Power Apps Ideas](https://ideas.powerapps.com). 

Vote for an existing request or submit a new one.

Closing this issue.
