### ISSUE TITLE
Not using the BPF feature provide by powerapps and creating a custom BPF using HTML?

### ISSUE THREAD

**Issue by krnaryal** [MicrosoftDocs/powerapps-docs#4229]
- How feasible is it to remove the BPF provided by powerapps and create a new one using HTML?

- what are the issues that I might face if I remove my current BPF and create a  new BPF using HTML webresources?

**Comment by Mattp123** [comment]
@krnaryal - Removing a business process flow from a model-driven apps is easy. From the app designer, select **Automation** from the left navigation pane, select **...** next to the business process flow you want to remove, and then select **Remove [bpf name**]. 

To develop custom logic can't be done with only HTML. To do it you'd have to create a plug-in. You can accomplish workflow type behavior or extend an existing business process flow this way but business process flows have UI (steps) that can't be created using just code.

Closing issue.

**Comment by Mattp123** [comment]
Also, see this: [Use plug-ins to extend business logic](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/plug-ins)

**Comment by krnaryal** [comment]
Thank you @Mattp123
