### ISSUE TITLE
Heading needs to be updated

### ISSUE THREAD

**Issue by pard68** [MicrosoftDocs/powerapps-docs#423]
The heading "Hpw to run this sample" has a typo. Should be "how" now "hpw"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c1cb6f-a374-79b1-e8b6-8f1f9a868245
* Version Independent ID: 9789741c-9d55-fdf8-1704-209010b16ecf
* Content: [Web API Query Data Sample (C#) (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/samples/query-data-csharp#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/samples/query-data-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/samples/query-data-csharp.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by pard68** [comment]
Didn't realize this was hosted on Github. I created a PR:
#424

**Comment by susikka** [comment]
@pard68 Thanks for correcting the typo. PR #424 has been merged.
