### ISSUE TITLE
How to match individual responses to requests within a batch?

### ISSUE THREAD

**Issue by JandosHk** [MicrosoftDocs/powerapps-docs#4234]
It would be very helpful to show how individual responses can be matched to their corresponding requests.
Does the order of requests match to the order of responses? Should we use other means such such Request-ID header?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6db53047-327d-6eec-e6a8-4d9dae98f362
* Version Independent ID: 31b3ebbd-9070-db30-cc4e-cec4b41373b8
* Content: [Execute batch operations using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/execute-batch-operations-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JandosHk. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@JandosHk 

Thanks for your feedback.

The second sentence of the article is:

> These operations will be performed sequentially in the order they're specified.

How can we make this clearer?

**Comment by JandosHk** [comment]
"The order of the responses matches the order of the requests" looks more explicit to me.

**Comment by JimDaly** [comment]
@JandosHk 

Thanks. I've updated the first paragraph to be:

> You can group multiple operations into a single HTTP request using a batch operation. These operations will be performed sequentially in the order they're specified. The order of the responses will match the order of the requests in the batch operation.
