### ISSUE TITLE
Authorize conditions in Power App Process

### ISSUE THREAD

**Issue by tranvanhau0907** [MicrosoftDocs/powerapps-docs#4247]
"Hello everyone, I am currently developing an app for the company, which includes an Approval feature under the Condition on Process. Specifically, when the User presses the first Stage, the next Stage is in the form of Condition, and only Ad has permission to press it on a different interface in another app. More specifically, there are 2 apps: 1 App AD and 1 App User (both apps use the same table and process). However, I want only App AD to have the right to control the Condition on Process, but I do not want to apply the role systemadmin to App AD. So, which role on Basic User has the permission to assign this right? Thank you very much! Good luck!"

**Comment by phecke** [comment]
@tranvanhau0907 Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ Closing this issue.

You could also post your issue to a public developer forum such as stackoverflow.com.
