### ISSUE TITLE
Guidance on how to use this  (eg code example)

### ISSUE THREAD

**Issue by xairrick** [MicrosoftDocs/powerapps-docs#4252]
1) There should be a code example on how this can be used.  it  should explicitly show what the callback function looks like.
2) There should be a note in there about how this might now work as expected if you call addCustomView() in the callback function.  I've seen instances where if this gets called multiple times, you will get difference results when you click on the magnifying glass (this could also be an platform bug)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b467682f-01ec-4b4f-7949-9119d4c5c3da
* Version Independent ID: bd678329-b0c1-a298-0597-efa3d18bd849
* Content: [addPreSearch (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/addpresearch)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addPreSearch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addPreSearch.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @xairrick. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@xairrick 
Eric -

Thanks for your feedback. I agree with you. We can add it to our backlog.

I do want to point out that we also accept contributions.  If you have used this successfully and have an example, this could help speed up getting an example added here.

@chmoncay 
Chris please review

**Comment by xairrick** [comment]
@JimDaly,
I could definitely write up an example for item 1)   

As far as 2) is concern I would need to know more about the internal design and how it was indented on working.  (ie it might just be a platform bug i'm seeing)

**Comment by JimDaly** [comment]
@xairrick 
That would be great. I need to get all samples reviewed by dev team. Much easier to ask them to review a sample than write one from scratch.

@chmoncay  will need to speak to how it should work and any guidance we ought to provide to mitigate the issue you have seen. We can't provide technical support here, but you can also open a support case to get clarity.

**Comment by xairrick** [comment]
@JimDaly here is a sample of usage.  NOTE: a lot of developers might not realize there could be multiple controls for the same attribute on a form, so it's always safest to start with attribute and add the preSearch to all of them.
```
function onLoad(executionContext) {
   var fromContext = executionContext.getFormContext()
   var attribute = fromContext.getAttribute("primarycontactid") 
   attribute.controls.forEach(control => control.addPreSearch(myPreSearchCallBack))
}
function myPreSearchCallBack (executionContext){
   var control = executionContext.getEventSource();
   var filter = "<filter><condition attribute='firstname' operator='eq' value='Eric' /></filter>";
   control.addCustomFilter(filter);
}
```

**Comment by JimDaly** [comment]
@xairrick 
Thanks I need to loop in dev team for review and will get back to this.

**Comment by JimDaly** [comment]
@xairrick 

Eric -
Apologize for the delay in responding. 
I finally added your Example to https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/addpresearch

Please take a look.

Thanks for contributing and helping make our docs better.

BTW: You can also contribute directly. See https://learn.microsoft.com/en-us/contribute/content/
