### ISSUE TITLE
Unable to authenticate postman for Dataverse

### ISSUE THREAD

**Issue by y0geshdev** [MicrosoftDocs/powerapps-docs#4259]
Hi,

I tried following the documentation linked below but I am not able to configure the postman to authenticate and get token.

When I click on **Get New Access Token** at step #6 then Postman asks me to login. Once I login, I get below screen and the authentication fails.

![image](https://user-images.githubusercontent.com/5191515/229558564-5d687d44-53a5-4dbc-a8d0-3079f4d140e5.png)

Please let me know if you need further details.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Set up a Postman environment (Microsoft Dataverse for Apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @y0geshdev. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@y0geshdev 

Responding via Teams.
