### ISSUE TITLE
Screenshot needs update

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#426]
The Visual Studio new project dialog under Create a Visual Studio Activity Library project still shows .NET Framework 4.5.2 but the instructions say 4.6.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb46fb23-01b2-e7f4-f89a-fa222ea40a8a
* Version Independent ID: 32b849a9-178c-0907-6bb3-23f61c1cd415
* Content: [Tutorial: Create workflow extension (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/workflow/tutorial-create-workflow-extension)
* Content Source: [powerapps-docs/developer/common-data-service/workflow/tutorial-create-workflow-extension.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/workflow/tutorial-create-workflow-extension.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
Screenshots are updated and doc is live.

Closing this issue now.
