### ISSUE TITLE
How does one find the Plugin Registration Tool in Nuget? Docs don't say

### ISSUE THREAD

**Issue by michaelmmcrae1** [MicrosoftDocs/powerapps-docs#4263]
This documentation page:
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/register-plug-in

Contains this text:
"
PRT is one of the tools available for download from NuGet. Follow the instructions in [Dataverse development tools](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/download-tools-nuget). That topic includes instructions to use a PowerShell script to download the latest tools from NuGet.
"

But that is incorrect. There is nothing about PowerShell downloading something from Nuget. As far as I can find, the documentation only describes using pac cli to launch the Plugin Registration Tool. And pac cli entirely hides how/where the PRT comes from which Nuget package. So it really does NOT show how one would get the Plugin Registration Tool from Nuget. Only shows how to open it from pac cli, which is not an option for everyone (some orgs have strict policies around CLI).

Luckily I happen to *just know* that I can google "Plugin Registration Tool Nuget package" and find what I believe looks right/I can trust: https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.PluginRegistrationTool

But the documentation does not state this Nuget package anywhere, and new-comers will never know of it.

The documentation needs to connect these dots, it's lacking a crucial helpful detail which seems barely out of reach. Why do I have to *just know* where to get the PRT from Nuget? Or rely on forums of people asking this question 100x already.
Why can't the documentation be transparent and just tell me the Nuget packages that contain which tools? (and help new-comers, or forgetful people :D)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08cd0714-ecf3-a37e-32da-a336f5402fb6
* Version Independent ID: 9d7be299-ec79-62fd-c3e7-48f6bc23069b
* Content: [Register a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/register-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/register-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/register-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @michaelmmcrae1. This issue has been assigned to the doc author for review.

**Comment by michaelmmcrae1** [comment]
Here is an example of Docs doing a good job being clear about where in Nuget something can be found. For CrmSvcUtil: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/generate-early-bound-classes

It says about this Tool:
"
The code generation tool (CrmSvcUtil.exe) is distributed as part of the [Microsoft.CrmSdk.CoreTools](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools) NuGet package. You can download the NuGet package, rename the file's extension .nupkg to .zip, and extract the files. You may also need to unblock the file in the Properties dialog of File Explorer.
"

Which is great. It has info about pac cli approach AND straight to Nuget approach.

Similar good job here for SolutionPackager https://learn.microsoft.com/en-us/power-platform/alm/solution-packager-tool
See section "Where to find the SolutionPackager tool"

**Comment by phecke** [comment]
@michaelmmcrae1 Sorry for the confusion. The instructions to download the PRT changed from using PowerShell to using the Power Platform CLI. Just follow the instructions provided in [Dataverse development tools](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/download-tools-nuget). We have changed the tool installation so that you do not need to deal with downloading, uncompressing, and navigating the contents of the NuGet package. The CLI makes this much easier.

I will remove mention of PowerShell from the plug-in registration topic.

**Comment by phecke** [comment]
@michaelmmcrae1 The plug-in article has been updated and will be published in a couple hours.
