### ISSUE TITLE
Which format type is used for images, .png/.jpeg/base64/etc.?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#427]
Hello,
Will you elaborate a little bit on what type of image the Camera control captures? I'm unclear whether I should save files with a concatenated ".png" or ".jpg" or ".jpeg" etc. 
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b98c28-54c3-b8ab-bd42-0db8f4892b66
* Version Independent ID: 6eb48d98-df3a-f208-936a-b2003a542ab0
* Content: [Camera control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-camera)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-camera.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-camera.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by chmoncay** [comment]
Hi there, the image control outputs a base64 blob, which is a jpg.
