### ISSUE TITLE
Mention about special characters in the API Query documentation

### ISSUE THREAD

**Issue by jpereiro18** [MicrosoftDocs/powerapps-docs#4279]
There are no mentions about the fact that special characters have to be encoded in order to use them.

For example, if a string that you want to filter contains a +, the contains(column, "+123") does not work.

Instead, you need to encode it to %2B, and use contains(column, "%2B123") to make it work.

I think it would be a wonderful addition to the documentation to mention that.

If there is any way I can help you update that, I'll be happy to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5424f5-e734-423d-2baf-d7f82d500c96
* Version Independent ID: 4c1116df-37f5-0be4-6c94-3e3939e4cdb2
* Content: [Query data using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/query-data-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jpereiro18. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@jpereiro18 

Thanks for your feedback and apologies for the delay in responding.

We have some content today with guidance about [filter using string values](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query-data-web-api#filter-using-string-values)

I think we could have a note there. But I hate to mention special characters without a complete list of those characters.

Here is a list I found online
|Character|Encoded Character|
|---|---|
|`$`|`%24`|
|`&`|`%26`|
|`+`|`%2b`|
|`,`|`%2c`|
|`/`|`%2f`|
|`:`|`%3a`|
|`;`|`%3b`|
|`=`|`%3d`|
|`?`|`%3f`|
|`@`|`%40`|

But I want to confirm whether it is complete.

**Comment by jpereiro18** [comment]
Hi Jim,

Thank you for your response.

I don't think that a list of them is the best thing to do since there are so many, however, a list with some of the most common ones like the one you sent me could be fine.

To be more specific, you can have a link to a tool like this [HTTP Encoder](https://meyerweb.com/eric/tools/dencoder/) that allows the user to encode their query so that they won't have any issues with the special characters.

Let me know if there is any other way I can help you.

Looking forward to hearing from you.

Kind regards,
Juan
------- Original Message -------

**Comment by JimDaly** [comment]
Added this [URL encode special characters](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query-data-web-api#url-encode-special-characters)

Thanks for your feedback @jpereiro18
