### ISSUE TITLE
Path to sample code is wrong

### ISSUE THREAD

**Issue by peter-hallock** [MicrosoftDocs/powerapps-docs#4284]
The path to the sample code is wrong. 
In the document it has: "PowerApps-Samples-master\cds\orgsvc\C#\WebAccessPlugin".
The actual path is: "PowerApps-Samples-master\dataverse\orgsvc\C#\WebAccessPlugin"
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e40287f8-6fe2-70ef-1143-2d0c039b049d
* Version Independent ID: 3d8970b6-d835-19af-c0f4-232323b552eb
* Content: [Sample: Web access from a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/web-access-plugin)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/web-access-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/web-access-plugin.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @peter-hallock. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@peter-hallock 

Thanks for pointing this out.
I've fixed it.
