### ISSUE TITLE
Launching other apps from within an app

### ISSUE THREAD

**Issue by appmbld** [MicrosoftDocs/powerapps-docs#429]
Make sure you are using this format to properly launch apps across platforms: Launch("/providers/Microsoft.PowerApps/apps/&lt;app ID&gt;")

E.g. Launch("/providers/Microsoft.PowerApps/apps/e22f2402-cc8a-46e5-8289-ae5744e503be")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edbd7c88-66b5-0776-251e-49293324b930
* Version Independent ID: 4364fe0e-c13d-afaa-a0b3-1e5803e1d9e8
* Content: [Download, Launch, and Param functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-param#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-param.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-param.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It is unclear which scenario or app does the given example launch, but for using any address to launch using the Launch() function, please follow the documented syntax. In other words, the address or the URL that can be launched in a browser - specified within quotes and parenthesis.

For example, button OnSelect value can be:
Launch("apps.powerapps.com/play/appID") 
Or
Launch("https://apps.powerapps.com/play/appID?tenantId=tenantID&source=portal&screenColor=rgba(colorID)") 

The first one is shortened version of app launch address and latter is the address used when launching app from list of apps on make.powerapps.com. 

If you need any further help with an issue, please raise a [support service request](admin.powerplatform.microsoft.com/support) for assistance.

**Comment by fmoghaddampoor** [comment]
Well, I am a newbie in powerapps. Recently I had this task to run an external Android application (A type of NFC reader) which is currently not supported on powerapps.

So I researched and understood there is a method for lunching in powerapps: You can launch a url like this:

Launch("https://www.bing.com")

You can launch skype like this:

Launch("skype:")

The syntax is like this: Launch( Address [, ParameterName1, ParameterValue1, ... ] )

Address - Required. The address of a webpage or the ID of an app to launch.

ParameterName(s) - Optional. Parameter name.

ParameterValue(s) - Optional. Corresponding parameter values to pass to the app or the webpage.

But how about a specific unknown application?

I want to for example load app at address below in google play:

https://play.google.com/store/apps/details?id=com.ssaurel.nfcreader&hl=en

I know that I can navigate user to address below, but Is there a way to run application directly? Launch("https://play.google.com/store/apps/details?id=com.ssaurel.nfcreader&hl=en")

**Comment by gregli-msft** [comment]
There is no way to directly launch another app on the device from the Launch function.  

Launch just opens a URL like a browser would with a bypass if the target is a Power App.  As such, both Android and iOS support the notion of a universal link, which is effectively what you are using when you launched skype with a URL scheme.  For more details, I'd look into the docs for iOS https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html and the Android docs https://developer.android.com/training/app-links.
