### ISSUE TITLE
Advanced Find Search

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/powerapps-docs#4298]
Hello,

Please try out on a system and correct description: Advanced Find in Lookups supports leading wildcards. (Currently it is documented in the table "Not supported")

Thanks,
Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e53b21b6-a371-2b0d-0fee-2f77fa645b66
* Version Independent ID: 55864e5c-128a-ccbd-10bc-84daf3c847bb
* Content: [Search options in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/user/search)
* Content Source: [powerapps-docs/user/search.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/search.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @sericks
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@soutchilin, thank you for your post. This article has now been updated.
