### ISSUE TITLE
The link to SolutionImportWizard is wrong

### ISSUE THREAD

**Issue by davidyack** [MicrosoftDocs/powerapps-docs#43]
Doc has
https://{orguniquename}.crm.dynamics.com/tools/solution/SolutionImportWizard.aspx

Should be (with import in the url)
https://{orguniquename}.crm.dynamics.com/tools/solution/import/SolutionImportWizard.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29c5da4-511c-c13f-6c98-c3ad07a389e7
* Version Independent ID: d83ac9f1-3c07-3a15-f212-df944f769d30
* Content: [Migrate apps between environments and tenants - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/environment-and-tenant-migration)
* Content Source: [powerapps-docs/administrator/environment-and-tenant-migration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/environment-and-tenant-migration.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
@davidyack 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. I've updated the topic and will publish to live. Thanks for the fix!
