### ISSUE TITLE
Support for Mac

### ISSUE THREAD

**Issue by cweems** [MicrosoftDocs/powerapps-docs#430]
Is there any support for Mac if I'd like to install the Plug-In registration tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c604f69e-7f7c-c499-47b1-fe9c3036af95
* Version Independent ID: 267fd327-1d25-ac85-1790-6faea6e9659f
* Content: [Download tools from NuGet (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/download-tools-nuget)
* Content Source: [powerapps-docs/developer/common-data-service/download-tools-nuget.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/download-tools-nuget.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by shmcarth** [comment]
The plugin registration tool requires Windows 7 or later.  It is built on the Dynamics 365 SDK.  It is not available for the Mac.  See here for the detailed system requirements of the previous version of the SDK which included the tool:  https://www.microsoft.com/en-in/download/details.aspx?id=50032
