### ISSUE TITLE
Seems like the power platform explorer has moved in the menu

### ISSUE THREAD

**Issue by EricBos** [MicrosoftDocs/powerapps-docs#4304]
[Enter feedback here]

In the documentation the Power Platform Explorer should be under View in the menu. 
In my VS, it sits under Tools -> Connect to Dataverse

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae2a5dc-346e-f0fc-f03a-07aed9fd37c4
* Version Independent ID: 2e757865-4955-8bde-7e1b-55c87a8c3ad3
* Content: [Tutorial: Debug a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/tutorial-debug-plug-in?tabs=pptools)
* Content Source: [powerapps-docs/developer/data-platform/tutorial-debug-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tutorial-debug-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @EricBos. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@EricBos What version of Visual Studio and the PP Tools extension are you using?
