### ISSUE TITLE
It is not clear how to use this function in a project.

### ISSUE THREAD

**Issue by felipebdasilva** [MicrosoftDocs/powerapps-docs#4305]
Hello,

Documentation reference: https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord/save

I have been trying to understand how to make a record save function work. Basically, when creating a new dataset PCF (react) project (Using the latest version of the Power Platform CLI - 1.21.13), the option to save the record does not appear. 
Could you include in the documentation, what are the requirements to get this function? The same I have to say about the setValue function of this documentation section.
Thank you
Felipe Silva,

**Comment by JimDaly** [comment]
@HemantGaur  & @lesyk 
Please see this feedback related to PCF EntityRecord.Save and setValue methods.
There is little guidance for use here.

**Comment by lesyk** [comment]
@felipebdasilva we have a bit older types included in the CLI tool.
If you would look into how entity record object looks at the runtime inside of the JS debugging tool, you can see available methods (that should be the same as in the documentation).

Next snippet should make a change of the record and then save it:
```
datasetRecord.setValue("columnNameString", "value");
datasetRecord.setValue("columnNameNumber", 12);
datasetRecord.save();
```

**Comment by felipebdasilva** [comment]
@lesyk, @JimDaly
Is there a PCF Dataset Control that uses this function in the Power Apps Samples area? 
We really would like to apply this approach to a customer solution, but we are getting an error message when calling the save function.

**Comment by felipebdasilva** [comment]
Uncaught (in promise) UciError: Invalid snapshot with id undefined
    at s (app.591f98abfa983098bae2e58cf5d0c184.js:33:886518)
    at new h (app.591f98abfa983098bae2e58cf5d0c184.js:28:140742)
    at Object.execute (app.591f98abfa983098bae2e58cf5d0c184.js:28:290254)
    at Object.execute (app.591f98abfa983098bae2e58cf5d0c184.js:33:292142)
    at app.591f98abfa983098bae2e58cf5d0c184.js:14:562065
    at new Promise (<anonymous>)
    at N._executeAsyncAction (app.591f98abfa983098bae2e58cf5d0c184.js:14:561766)
    at N._executeAsync (app.591f98abfa983098bae2e58cf5d0c184.js:14:561610)
    at N.executeAction (app.591f98abfa983098bae2e58cf5d0c184.js:14:560875)
    at t.dispatch (app.591f98abfa983098bae2e58cf5d0c184.js:14:566236)
    at Object.dispatch (app.591f98abfa983098bae2e58cf5d0c184.js:14:822115)
    at Object.dispatch (app.591f98abfa983098bae2e58cf5d0c184.js:14:565725)
    at dispatch (app.591f98abfa983098bae2e58cf5d0c184.js:14:561933)
    at Object.execute (app.591f98abfa983098bae2e58cf5d0c184.js:33:1222)

![image](https://user-images.githubusercontent.com/13945615/233416056-d285aa2d-2ee4-4764-8e42-13a58515e939.png)

**Comment by lesyk** [comment]
What is the field type?
May you share code that does `.setValue(` ?

**Comment by lesyk** [comment]
what is the output of `dataset.columns` is your column comes there as `InputDecimal`?

**Comment by felipebdasilva** [comment]
It worked! 👍 
I just find it interesting that the function `.getValue("InputDecimal")` works.

**Comment by lesyk** [comment]
In our docs: https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord/setvalue
We have `setValue(columnName, value)`, **columnName**. 

Happy that we were able to find the problem.

**Comment by felipebdasilva** [comment]
Yes... As the `getValue(columnName)` (https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord/getvalue)
Thank you very much for the help!

**Comment by JimDaly** [comment]
@felipebdasilva  & @lesyk 

I'm glad you got it worked out, but this isn't a forum for technical support.

How could the documentation be improved so that others don't have these same challenges?

**Comment by felipebdasilva** [comment]
@JimDaly 
That is correct! We actually have a support ticket with the Support team.
To me, it would be nice to have described in the documentation that the column name referred to in the syntax and parameters is the Dataverse logical name and not the name defined in the manifest. It sounds inconsistent that in the function `getValue` works with the name defined in the manifest and the `setValue` don't.
This difference actually misleads to the use of the property-set name and maybe the colleagues in the community would not fall into the same problem with such a clarification.

**Comment by JimDaly** [comment]
@felipebdasilva 
In other words, these changes would help?

1. Update [getValue](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord/getvalue)
  This `columnName` is the name defined in the manifest.
2. Update [setValue](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord/setvalue)
   This `columnName` is the logical name of the Dataverse column
3. [save](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord/save)
   If **setValue** doesn't use the logical name of the column, this error can occur when saving:
	`Uncaught (in promise) UciError: Invalid snapshot with id undefined`

**Comment by felipebdasilva** [comment]
Hi @JimDaly,
Yes, these changes look good.
The getValue working with the name in the manifest was a distraction for me. In my opinion, it could happen with others.
