### ISSUE TITLE
The 'width' property of the 'createPane' function does not work

### ISSUE THREAD

**Issue by keijimscom** [MicrosoftDocs/powerapps-docs#4308]
[Enter feedback here]
The 'width' property of the 'createPane' function does not work. No matter what number you set the 'width' property to, the actual width of the displayed side panel remains constant.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1195d85-d0c1-da87-c015-206fc72e94dd
* Version Independent ID: 51bfed40-9fee-e31e-3935-d69d217c5c9c
* Content: [createPane (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-app/xrm-app-sidepanes/createpane)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-App/Xrm-App-sidePanes/createPane.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-App/Xrm-App-sidePanes/createPane.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @keijimscom. This issue has been assigned to the doc author for review.

**Comment by adrianorth** [comment]
Thanks for reporting this. We will look at this more.

**Comment by JimDaly** [comment]
@adrianorth 
Please let us know what you find and update the docs.
I'm going to close this for now.
