### ISSUE TITLE
this documentation page still uses CDS term

### ISSUE THREAD

**Issue by niagrawal-microsoft** [MicrosoftDocs/powerapps-docs#4309]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6e0ff75-b45a-7d58-5289-3b98cdf7c178
* Version Independent ID: 09b05c5b-1387-2a98-3f61-b47f6519b44a
* Content: [Sample: Use QueryExpresion with a paging cookie (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/use-queryexpression-with-a-paging-cookie)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/use-queryexpression-with-a-paging-cookie.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/use-queryexpression-with-a-paging-cookie.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @niagrawal-microsoft. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@niagrawal-microsoft 
Thanks. I've fixed this.
