### ISSUE TITLE
Max code snippet is wrong!

### ISSUE THREAD

**Issue by shahab1363** [MicrosoftDocs/powerapps-docs#431]
You forgot to update Max code snippet, it's just a copy of ``countcolumn`` snippet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ecff437-8817-c280-5a07-021e43696586
* Version Independent ID: 27d8ed68-21c5-90bf-3334-682479645c95
* Content: [Use FetchXML aggregation (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-fetchxml-aggregation#count)
* Content Source: [powerapps-docs/developer/common-data-service/use-fetchxml-aggregation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-fetchxml-aggregation.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
Fixed
