### ISSUE TITLE
Unable to access dataverse tables using registered app

### ISSUE THREAD

**Issue by y0geshdev** [MicrosoftDocs/powerapps-docs#4321]
Hi, 
I registered the app as shown in the documentation and when I tried to access it through postman client then I got 401 Unauthorized as response.

![image](https://user-images.githubusercontent.com/5191515/233416735-945f4d02-9938-42be-809e-7ea56e3e8726.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7f57df6-59af-6e22-44d2-bc9bb1ee69c7
* Version Independent ID: fdce23ee-733d-bf3a-25c8-2ca6bfa8c852
* Content: [Use OAuth authentication with Microsoft Dataverse (Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/authenticate-oauth)
* Content Source: [powerapps-docs/developer/data-platform/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/authenticate-oauth.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @ritesp
* Microsoft Alias: **ritesp**

**Comment by JimDaly** [comment]
Responding via teams
