### ISSUE TITLE
Push environment variable updates into flows changes

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#4322]
The answer to the question "[If a value is changed, when does the new value get used in canvas apps and cloud flows?](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/environmentvariables#if-a-value-is-changed-when-does-the-new-value-get-used-in-canvas-apps-and-cloud-flows)" needs to be updated based on the [Push environment variable updates into flows asynchronously](https://learn.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-automate/push-environment-variable-updates-into-flows-asynchronously) change in 2022 Wave 1 update.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba670cf8-5810-79c4-7a2a-101099ffe1d7
* Version Independent ID: 69b7e1fb-9f56-8c07-b1d5-8480fe6d8e1a
* Content: [Use environment variables in solutions - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/environmentvariables#if-a-value-is-changed-when-does-the-new-value-get-used-in-canvas-apps-and-cloud-flows)
* Content Source: [powerapps-docs/maker/data-platform/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/EnvironmentVariables.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LinnZawWin. This issue has been assigned to the doc author for review.

**Comment by LinnZawWin** [comment]
The answer has been modified with the updated information.
Thanks, team.
