### ISSUE TITLE
Connection Reference is missing in the list of components that can be added to a solution.

### ISSUE THREAD

**Issue by tdutch1** [MicrosoftDocs/powerapps-docs#4326]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e1e8f25-292b-5871-1b09-4ac146dfad50
* Version Independent ID: a0a91141-af1c-e5ca-2181-3f82a172eeb5
* Content: [SolutionComponent table/entity reference (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/solutioncomponent#componenttype-options)
* Content Source: [powerapps-docs/developer/data-platform/reference/entities/solutioncomponent.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/reference/entities/solutioncomponent.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by JimDaly** [comment]
@tdutch1 

Hi Tim.
Thanks for your feedback.

This is a reference topic that simply reflects the current schema definition for the SolutionComponent table.

I'm aware that the solution system has moved away from the static list of ComponentType values, but they are still part of the metadata.

Perhaps @shmcarth can speak to this?
How is one to find the correct solution component type value if it isn't defined in the metadata?

**Comment by shmcarth** [comment]
As Jim has mentioned, the platform has moved to dynamic component types as we are adding new components to the platform via solutions and they are no longer statically defined.  This page is not a list of all components that can be added to the solution.  I will review the content on that page to ensure that this meaning is not contrived.  It is still helpful for legacy usage but is not an entire list of components.
