### ISSUE TITLE
Where are the available functions

### ISSUE THREAD

**Issue by felipe-molina-cashme** [MicrosoftDocs/powerapps-docs#4330]
This page should teach everything there is to know about how to use calculated columns.. but it FAILS to show the list of functions.. Microsoft did not document the NOW() function in this page.. what other functions are available that you are not telling us? I'd like to have all the functions listed here.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f212137-6b88-c06c-025d-c05e6b74c10f
* Version Independent ID: 61abe448-2b0d-29bd-90bb-63899f0f92dc
* Content: [Define calculated columns in Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/define-calculated-fields)
* Content Source: [powerapps-docs/maker/data-platform/define-calculated-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/define-calculated-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@felipe-molina-cashme - Thank you for your feedback. I recommend you consider using formula columns since that's the direction the functionality is headed.
https://learn.microsoft.com/en-us/power-apps/maker/data-platform/formula-columns
Closing issue.
