### ISSUE TITLE
RootComponent type "80" and Model-driven App is missing in the list of components that can be added to a solution. 

### ISSUE THREAD

**Issue by roopekorpela** [MicrosoftDocs/powerapps-docs#4338]
This page need information what is model-driven app RootComponent type value.

I noticed that the solution.xml can contain  `<RootComponent type="80" ` this is not in the documentation table so could it be the model-driven app?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e1e8f25-292b-5871-1b09-4ac146dfad50
* Version Independent ID: a0a91141-af1c-e5ca-2181-3f82a172eeb5
* Content: [SolutionComponent table/entity reference (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/solutioncomponent#componenttype-options)
* Content Source: [powerapps-docs/developer/data-platform/reference/entities/solutioncomponent.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/reference/entities/solutioncomponent.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by roopekorpela** [comment]
#4326 issue also notes that the connection reference is not listed on this page.

**Comment by JimDaly** [comment]
@roopekorpela 
Thanks for your feedback.

This is a generated reference topic based on the schema design of the Solution Component table.

I'm aware that solution framework has moved away from using a defined list that can be described by the ComponentType optionset. But this is still part of the metadata.

Perhaps @shmcarth can speak to this and understand what people are expecting.

**Comment by shmcarth** [comment]
The platform is adding new solution aware entities all the time.  New components get dynamic type codes and the legacy meaning of this static list has been lost.  Most new components don't even show up in this node in the solution file.  Perhaps I should add a note to indicate this in the documentation page that lists many of the legacy components to avoid confusion.

**Comment by JimDaly** [comment]
@roopekorpela 
Thanks for your feedback. We will need to figure out a way for people to get a list of componentype values for the environment.
