### ISSUE TITLE
pcf-scripts does not support live reload / change detection

### ISSUE THREAD

**Issue by jjohnsen** [MicrosoftDocs/powerapps-docs#434]
The local server that is started with `npm start` does not support live reload.

If you change line 39 in .\node_modules\pcf-scripts\bin\pcf-scripts.js, from:
```
38        case 'start':
39            return buildTask(false).then(startHarness);
```
to:
```
38        case 'start':
39            return buildTask(true).then(startHarness);
```
watch mode is enabled, and live reload works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4b9e58-d9d3-c387-fe6a-258ebe78516d
* Version Independent ID: 22d89b45-e427-1ab9-b456-7d7750585b52
* Content: [Create custom component using PowerApp Component Framework Tooling - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/create-custom-controls-using-pcf)
* Content Source: [powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by pvayner** [comment]
Thank you very much for the suggestion! We are looking at a couple of other avenues for enabling change detection. I've also noticed that you are looking at some older scripts. Please take a moment to grab the latest.

**Comment by Nkrb** [comment]
@jjohnsen Thanks for the feedback. Please open the issue again if you feel the information provided is not sufficient.
