### ISSUE TITLE
An example would help here please

### ISSUE THREAD

**Issue by ML1961** [MicrosoftDocs/powerapps-docs#4342]
What does    context.formatting.formatCurrency(value, precision, symbol)    mean?
An example would really help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6177bef8-f131-b67e-9fb6-c156f505937d
* Version Independent ID: c75d8772-62ea-ae72-4698-3f21c7f90c6e
* Content: [FormatCurrency - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/formatting/formatcurrency)
* Content Source: [powerapps-docs/developer/component-framework/reference/formatting/formatcurrency.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/formatting/formatcurrency.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by JimDaly** [comment]
@ML1961 

Thanks for your feedback.
Were you able to get this working?

The method takes three parameters:

I expect you could use `FormatCurrency(2.0,2,'$')`

And the result should be "$2.00".

Is this the kind of example you are looking for?

**Comment by ML1961** [comment]
Thanks Jim
Appreciate your reply.
I find that so many of the MS documents do not have a working example - so unless you are a seasoned programmer, you have no idea how to use the functions.
Having said that, I am equally frustrated when articles that do have examples, do present them in a way that I am trying to use them.

And finally - Microsoft have a nasty habit of using a name for multiple purposes, so when I am searching for information I always have be extremely specific in search criteria.
Eg: Looking for help re  'TEAMS' and  'PowerApps' are a nightmare to find.
Invariably, I get suggestions for Dataverse solutions when I really need a Canvas app solution ETC
...and I gave up learning 'Microsoft .NET Core ASP' because it became impossible to know what technology I was needing.

Sorry - rant over.
Thanks again for your assistance.
Regards

**Comment by JimDaly** [comment]
@ML1961 

I appreciate your rant.  Doing the best we can.

I'm curious though. This particular API is used for developing [Power Apps Component Framework](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/overview) controls.

For our low-code/no-code platform, this is pretty deep into the 'pro-code' side of things. From your response, I'm not sure if that is where you are coming from.

Are you working on a PCF control? Or were you looking for something else?
Understanding what leads people into a frustrating place can help us improve our information architecture.

Or would simply adding a sample to the page be the best thing?

**Comment by ML1961** [comment]
Hi Jim
I am completely self taught, so I consider myself a true (golf) hacker.
Although I been writing code for a very long time, a lot of it is still all 'smoke and mirrors' to me.
Most experience has been in VBA (MS Access and Excel),  SQL and also did some Flash Action Script back in the day.

As mentioned, I tried going down the 'ASP .NET Core2' route a few years back, but I think it was still in its infancy, so documentation was scant and seemed to be a version or 3 behind the actual product that was in the wild. (Identifying the Version in my searches just added to the complexity)

I am the first to acknowledge that I have clearly missed some fundamental concepts - which is why I struggle when there are no examples.
But I have to wonder how a young student starts to learn.

I'm just starting to get my head around the Power Suite as I believe that it is the way of the future.

While Model-Driven apps are awesome and have great potential, I find that they have some limitations. (I do understand why that is.)
I believe that to REALLY get value out of a Model-Driven App, one needs to have VERY solid understanding of the underlying data schema.
Planning takes (me) much longer and seems to have more rigid requirements re constraints, biz rules, relationships etc. And all this is 'clunky' in the dataverse.

Consequently, I prefer to dive in and develop canvas apps with a SQL back-end.
In my planning, I often define the schema in excel and then write formulae that generates the CREATE TABLE scripts for me.

If I could script the schema for dataverse tables (with constraints and biz rules) - that might be a motive to consider using the dataverse.

And if I could script templates for Canvas apps screens - that would also be 'AMAZING'.
I know that I could define a CSS-type template for Canvas Apps, but every time that I create a new screen, I have link each of the object properties back to the 'CSS'.
If there were something like the ability to create templates (Like there are in PowerPoint) - That would be great.
I have been looking into components - so that may be the solution?   I'm just not there yet.

Ultimately, I would LOVE to be able to teach small business owners how to use the Power suite and integrate with Office suite - but I still have a way to go.

I realize that I have gone off at a tangent, but I hope that it gives you some insight into where I am coming from.
Regards
Mark

**Comment by JimDaly** [comment]
@ML1961 

Thanks for sharing. It just goes to show we can't make any assumptions about background or skills people have when they come to our developer documentation.

Every API should have an example. 
Adding examples for all the APIs in this space is on my 'TODO' list, but it is a long list.

Please continue to send us feedback. We are looking for any inaccuracies or things that can be explained more simply.

I'm going to close this since adding an example to all APIs is something we seek to do.
