### ISSUE TITLE
I think you have a mistake in the async plugin documentation

### ISSUE THREAD

**Issue by orshir** [MicrosoftDocs/powerapps-docs#4344]
[Enter feedback here]
The text about async plugins made me thing that async plugins that make several changes to several records will do that without a transaction, but I think each plugin run has a single context and transaction, so if my async plugin creates a contact and an account but the account creation fails it will roll back the contact creation. The changes made by each async plugin execution are still an atomic unit.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75ddb79a-82d5-611f-787d-72a2294614ff
* Version Independent ID: 876520c5-b0e2-4874-f815-f42d0e2fd611
* Content: [Scalable Customization Design: Database Transactions (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/scalable-customization-design/database-transactions)
* Content Source: [powerapps-docs/developer/data-platform/scalable-customization-design/database-transactions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/scalable-customization-design/database-transactions.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @rogergilchrist
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@orshir 
Hi Oren -

Thanks for your feedback.
Can you call out what specific part of the document you think is not correct?

And you can reach me via email too.

**Comment by JimDaly** [comment]
We have verified that the content is correct.
