### ISSUE TITLE
EventListenerOrEventListenerObject is not defined

### ISSUE THREAD

**Issue by zhufamily** [MicrosoftDocs/powerapps-docs#4347]
Clearly there is a bug for the sample code provided.
EventListenerOrEventListenerObject is not defined, and I believe that is due to TypeScript version update.
Please provide the correct object type.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript?tabs=before)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by JimDaly** [comment]
I think you will find that the sample code has been updated so that this error should not occur.

In the .eslintrc.json file, this was added:

```
 "rules": {
    "no-unused-vars": "off",
    "no-undef": "off"
  }
```

This should suppress the undefined error.

If not, please create a new issue.
