### ISSUE TITLE
Broken GitHub link

### ISSUE THREAD

**Issue by rajrao** [MicrosoftDocs/powerapps-docs#435]
Should point to https://github.com/microsoft/PowerApps-Samples/tree/master/cds/Xrm%20Tooling/Quick%20start%20for%20XRM%20Tooling%20API/C%23

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5df702-cd2a-fa01-f391-024b0012d2d1
* Version Independent ID: 4aa1b284-7e3b-1b89-d8b2-2e0f0cadb2e0
* Content: [Sample: Quick start for XRM Tooling API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/sample-quick-start-xrm-tooling-api#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/sample-quick-start-xrm-tooling-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/sample-quick-start-xrm-tooling-api.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by susikka** [comment]
@rajrao Thanks for highlighting this. The link has been fixed and updated doc is live.

Closing this issue now.
