### ISSUE TITLE
click on button change the field value "true" using javascript

### ISSUE THREAD

**Issue by GokulpriyaD** [MicrosoftDocs/powerapps-docs#4357]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25c896b1-85b8-9abe-c79a-880e764e30b9
* Version Independent ID: 21a4ff22-6afb-ae7a-99c5-8b8cc5342c3b
* Content: [Define ribbon actions (model-driven apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/define-ribbon-actions)
* Content Source: [powerapps-docs/developer/model-driven-apps/define-ribbon-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/define-ribbon-actions.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by JimDaly** [comment]
@GokulpriyaD 

Thanks for your feedback. I'm afraid I don't know what to do with it.

Is there some part of the document that isn't clear, or are you requesting an example?

Thanks

**Comment by JimDaly** [comment]
Closing since no response.
