### ISSUE TITLE
RefreshForm isn't working for me

### ISSUE THREAD

**Issue by brendon-colburn** [MicrosoftDocs/powerapps-docs#436]
I've attempted to use RefreshForm on a button's OnSelect Event on an embedded Canvas app and the hosting model driven form does not refresh. I do have access to the model driven data and can perform a quick create on the form so it seems this specific feature may be broken.  I can provide what I'm working with if more detail is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5033427-7b31-0b45-784e-1c90b5cfb559
* Version Independent ID: 99e40bcc-943e-2ebe-bb20-61cc5ddd2ce3
* Content: [Perform actions on the host form from within an embedded canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-actions#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-actions.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by aneesmsft** [comment]
@brendon-colburn, are you still not seeing this work? I will be happy to setup time and see what might be going on.

**Comment by iangpgh** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by iangpgh** [comment]
@mattp123 - Closes #436

**Comment by iangpgh** [comment]
@brendon-colburn Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
