### ISSUE TITLE
Issue a Production build

### ISSUE THREAD

**Issue by iwaldman** [MicrosoftDocs/powerapps-docs#437]
To issue a production build, you can set the msbuild configuration to Release.  For example:

msbuild /p:configuration=Release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0d7d11-7d9d-0da4-f636-b74b1888f785
* Version Independent ID: ad58f888-55d3-45b9-838d-5c3d563824d8
* Content: [Updating PowerApps CLI - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/updating-tooling#feedback)
* Content Source: [powerapps-docs/developer/component-framework/updating-tooling.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/updating-tooling.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@iwaldman Thanks for the feedback. We have updated the docs and published to live. Closing the issue.
