### ISSUE TITLE
Navigation for "Customize the editable grid control" still shows "(Preview)"

### ISSUE THREAD

**Issue by ChrisGrohHS** [MicrosoftDocs/powerapps-docs#4370]
The preview markings were removed from this page but the left hand navigation menu still has "(Preview)" in the navigation link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2ffbcf6-d43d-df59-3222-0bf5cb09b9d4
* Version Independent ID: a2ffbcf6-d43d-df59-3222-0bf5cb09b9d4
* Content: [Customize the editable grid control - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/customize-editable-grid-control)
* Content Source: [powerapps-docs/developer/component-framework/customize-editable-grid-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/customize-editable-grid-control.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by JimDaly** [comment]
@ChrisGrohHS 
Thanks for pointing this out. I've fixed it.
