### ISSUE TITLE
We are utilizing numerous npm libraries, how can we exclude from bundle.js

### ISSUE THREAD

**Issue by fullstack-raj** [MicrosoftDocs/powerapps-docs#4371]
[Enter feedback here]

We are utilizing numerous npm libraries, and these packages are included in the bundle.js. How can we exclude them?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e32fb155-ff17-ca62-1aae-e58b5101a155
* Version Independent ID: e32fb155-ff17-ca62-1aae-e58b5101a155
* Content: [React controls & platform libraries (Preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/react-controls-platform-libraries)
* Content Source: [powerapps-docs/developer/component-framework/react-controls-platform-libraries.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/react-controls-platform-libraries.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by JimDaly** [comment]
@fullstack-raj 
The benefit of React controls & Platform libraries feature offers is:

> React and Fluent libraries are not included in the package because they are shared, therefore the size of bundle.js is significantly smaller.

But it won't make bundle.js smaller due to any other npm libraries smaller.

Is your question about the React controls & Platform libraries feature?

Or is this a general question about web packaging?

**Comment by JimDaly** [comment]
I believe this may be something that can be addressed using [webpack](https://webpack.js.org) configuration. Seeking confirmation.

**Comment by fullstack-raj** [comment]
i have setup pcf with react version 16
installed the react-icons package and its node_modules are included in the bundle.js file. How can I exclude it from the bundle.js file to reduce its size?
 
In my research and development, I discovered the pcf-script library, which contains a file named PlatformLibraryVersions.json. I would like to customize this file to extend its functionality. Currently, the pcf-script library supports React version 16, as declared in the ControlManifest.Input.xml file under the platform-library section. However, when we remove this declaration from the manifest file, both the react and fluent node modules are added to the bundle.js file.

 How to exclude the installed node_module packages from the bundle.js file?

**Comment by JimDaly** [comment]
@fullstack-raj 

Unless @fafuxa-ms , @jopursle , or @HemantGaur  can offer more suggestions, I think you can minimize the bundle size by being careful about the import statements.

In our tutorials for example, see [Minimize bundle.js size](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/tutorial-create-model-driven-field-component?tabs=before#minimize-bundlejs-size)

Apparently this:

```
import { ChoiceGroup, IChoiceGroupOption } from '@fluentui/react/lib/ChoiceGroup';
```
Is better than this:
```
import { ChoiceGroup, IChoiceGroupOption } from '@fluentui/react';
```

As far as I know, this is not part of the PCF feature, but in how the code is written.

**Comment by fullstack-raj** [comment]
@JimDaly 

We are using a better approach. call url's

Please refer to the screenshot below to understand the example we provided. We are using React-icons, and the size is being added to the bundle.js file. Please see the attached screenshot for reference.

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/29478647/e5162a0e-cdfd-4b79-8ecd-d0be761b11b2)

how can we exclude ` node_modules/react-icons` from the bundle.js

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/29478647/c49826a6-58c7-4cc8-9ee9-428797543133)

**Comment by fullstack-raj** [comment]
@JimDaly, the problem with PCF React is that there is no documentation on how to exclude the node_modules in bundle.js, except for Fluent UI and React. This is a significant issue that I have clearly explained with an example. I would greatly appreciate it if someone could assist me with this matter. Please don't close this request.

**Comment by fullstack-raj** [comment]
> @fullstack-raj
> 
> Issues in this repo are about the content we publish. Afraid I can't provide technical support to guide you here. I'm trying to understand whether there is anything actionable we can provide in our docs to help people be more successful using the features we document.
> 
> While minimizing bundle.js size is important, I don't see that it is directly related to the features we document. If I could provide a better way to do it, I would add it as a best practice in the docs. Unless @fafuxa-ms , @jopursle , or @HemantGaur can offer more suggestions, I have to recommend you look at other documentation, perhaps related to webpack or the fluent ui libraries.
> 
> Closing this.

@JimDaly, the problem with PCF React is that there is no documentation on how to exclude the node_modules in bundle.js, except for Fluent UI and React. This is a significant issue that I have clearly explained with an example. I would greatly appreciate it if someone could assist me with this matter. Please don't close this request.

**Comment by JimDaly** [comment]
@fullstack-raj 

The PCF feature depends on common TypeScript/JavaScript technologies. We can't provide guidance for every possibility.  I think you should be able to find the answer elsewhere. Searching for [how to exclude the node_modules in bundle.js](https://www.bing.com/search?q=how+to+exclude+the+node_modules+in+bundle.js) returns results that look promising and aren't related specifically to PCF components.
