### ISSUE TITLE
Screenshots refresh

### ISSUE THREAD

**Issue by moliveirapinto** [MicrosoftDocs/powerapps-docs#4375]
Hey guys.
This page needs a refresh, the screenshots are a bit old and different from the current UI

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11caa291-2e98-ac3a-d5d1-ecd416b93bdf
* Version Independent ID: 4f30cddd-8849-1887-ada0-a83a3d2a0027
* Content: [Tutorial: Register an app with Azure Active Directory (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/walkthrough-register-app-azure-active-directory#create-an-application-registration)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by phecke** [comment]
@moliveirapinto Thanks for pointing this out. I will take a look.

**Comment by phecke** [comment]
@moliveirapinto I have updated the page and removed most of the screenshots which tend to get outdated regularly. I have a significant update to the page coming in mid-December. 

Thanks for the feedback.
