### ISSUE TITLE
user privs missing Delete of appnotification

### ISSUE THREAD

**Issue by robdawsoncranhillinsight** [MicrosoftDocs/powerapps-docs#4377]
[Enter feedback here]
The table of privs is missing Delete over appnotification if users are to be able to remove the notification from their Notification centre. Otherwise they will just accumulate over time. In the UI, when clicking the X on the notification, it deletes the row from the appnotification table.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f495f03e-28c9-0ebb-ef03-72e16b267b3a
* Version Independent ID: a9dcec59-8b72-966e-fa53-f4b2e42d325e
* Content: [Send in-app notifications within model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/send-in-app-notifications?tabs=clientapi#managing-security-for-notifications)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/send-in-app-notifications.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by JimDaly** [comment]
I know @jaredha is making some updates to this article. 
Can we include these privileges?

**Comment by JimDaly** [comment]
@jaredha Can you look at this?

**Comment by JimDaly** [comment]
The table has been updated to include the Delete privilege.
Thanks @jaredha  and @robdawsoncranhillinsight
