### ISSUE TITLE
Missing file ManifestTypes.d.ts

### ISSUE THREAD

**Issue by Geradav** [MicrosoftDocs/powerapps-docs#4378]
It seems the solution can't be created as the ManifestTypes.d.ts is missing in the generated folder.
the index.ts is referencing this file for IInputs and IOutput, which throws an error as the file is missing.

Thanks for clarifying if (and what) an extra step is necessary to generate that file.

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b01e51-8d80-08b1-2bd5-564c4756ad8a
* Version Independent ID: 750ea5e8-1325-2593-024d-68e926488076
* Content: [How to use the sample components that are built using Power Apps component framework in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/use-sample-components)
* Content Source: [powerapps-docs/developer/component-framework/use-sample-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/use-sample-components.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by JimDaly** [comment]
@Geradav 

After you clone the repo, for each project you may need to run these commands:

- `npm install`
- `npm run refreshTypes`
- `npm run build`

I have a workitem to update these instructions.

**Comment by Geradav** [comment]
Thanks @JimDaly 
I now get the following error

```
PS C:\Users\<...>\source\repos\PowerApps-IFrame-Control> npm run refreshTypes
npm ERR! Missing script: "refreshTypes"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```
So the package.json needs also to be updated
More details can be found with the [issue 4382](https://github.com/MicrosoftDocs/powerapps-docs/issues/4382)

Thanks a lot for the help and guidance
