### ISSUE TITLE
AuthenticationContext.AcquireToken() method does not exist

### ISSUE THREAD

**Issue by blzrdphoto** [MicrosoftDocs/powerapps-docs#438]
The code snippets provided do not work.  The AuthenticationContext.AcquireToken()class no longer exists.  You have to use AuthenticationContext.AcquireTokenAsync() which fundamentally needs to be handled differently so these code snippets will not compile.  These snippets need to be updated to use valid methods.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext?view=azure-dotnet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62419bb8-985c-cb11-ac8d-2d018868c2a6
* Version Independent ID: db669ed7-d87b-c359-f5fb-3f2f1052281d
* Content: [Use OAuth with Common Data Service (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/authenticate-oauth.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/authenticate-oauth.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@blzrdphoto Yes, there is an Azure ADAL API breaking change. If you use ADAL v3 or greater, you will run into this. We are updating our code samples. See:

https://github.com/microsoft/PowerApps-Samples/tree/master/cds/webapi/C%23/ADALV3WhoAmI
