### ISSUE TITLE
TypeError: Cannot create property 'pos' on string 'IInputs'

### ISSUE THREAD

**Issue by Geradav** [MicrosoftDocs/powerapps-docs#4382]
Hello

I have tried several times following the steps to generate a solution package out of the provided sample component (IFrameControl for instance)
but when running msbuild I keep having this error coming up

**TypeError: Cannot create property 'pos' on string 'IInputs'**

Also, when instructing " _...you need to cd into your solution project directory..._", does it mean the directory where the ".pcfproj" resides or the directory where the ".cdsproj" resides?

Any help will be appreciated
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b01e51-8d80-08b1-2bd5-564c4756ad8a
* Version Independent ID: 750ea5e8-1325-2593-024d-68e926488076
* Content: [How to use the sample components that are built using Power Apps component framework in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/use-sample-components)
* Content Source: [powerapps-docs/developer/component-framework/use-sample-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/use-sample-components.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by rramoscabral** [comment]
It has to do with the typescript version.

You can use the following `npm install --save-dev typescript@4`.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Geradav. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@Geradav  Thanks for raising this.
@rramoscabral  Thanks for suggesting a fix.

@Geradav Did the suggestion to run `npm install --save-dev typescript@4` resolve the issue for you?

**Comment by Geradav** [comment]
Thanks @rramoscabral

Yes @JimDaly it has worked but the package.json needs also to be updated

So in order

- running `npm install --save-dev typescript@4` to update the TypeScript version
- Then adding `"refreshTypes": "pcf-scripts refreshTypes"` to the package.json file within the scripts section

Then running the following commands
- `npm install`
- `npm run refreshTypes`
- `npm run build`

Thanks a lot!
