### ISSUE TITLE
JDBC connection to TDS

### ISSUE THREAD

**Issue by thuanvan** [MicrosoftDocs/powerapps-docs#4386]
Hi 
We are trying to configure a JDBC to access TDS

Which version of MS JDBC is needed?
What additional library are required?

Is there any sample JDBC connectionstring out there?

**Comment by phecke** [comment]
@thuanvan  We only support the interfaces as described in our TDS [documentation](https://learn.microsoft.com/power-apps/developer/data-platform/dataverse-sql-query).

@RichdiMSFT Any other comments?

**Comment by phecke** [comment]
@thuanvan I am waiting on internal feedback from our product team in case they have more to add.

**Comment by phecke** [comment]
@thuanvan We only support the interfaces as described in our TDS [documentation](https://learn.microsoft.com/power-apps/developer/data-platform/dataverse-sql-query). I have not been able to get any additional information from the product team.
