### ISSUE TITLE
Enabled for Activities And Collaboration Section Missing from Current Table Properties

### ISSUE THREAD

**Issue by tsileo-wdi** [MicrosoftDocs/powerapps-docs#4393]
The current Power Apps designer doesn't match this page. I don't see a "Collaboration" section, and there is no option to "Enable for activities".  Does the documentation need to be updated? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59399824-5817-ef45-209d-35dab587a406
* Version Independent ID: 322b5820-c559-9a0b-ef66-1c31945ead2e
* Content: [Types of tables - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/types-of-entities)
* Content Source: [powerapps-docs/maker/data-platform/types-of-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tsileo-wdi. This issue has been assigned to the doc author for review.

**Comment by danorthogonal** [comment]
I am seeing this as well:

> To create a custom activity table, open the Advanced options section in the New table panel, select the Activity option from the Type drop-down list. After you select this, you’ll see that Display in Activity menus is selected. This setting allows people to create this type of activity in the activity menus. This isn’t selected for activities that are typically associated with specific events and created behind using code or by a workflow. After you save the table, you can’t change these settings.

This is no longer accurate. "Display in Activity" is not an option to select.

**Comment by Mattp123** [comment]
@tsileo-wdi - The article has been updated to reflect the current experience.

Closing issue.
