### ISSUE TITLE
Types of tables

### ISSUE THREAD

**Issue by aitortema** [MicrosoftDocs/powerapps-docs#4394]
Hi,
I´m missing activity, virtual and elastic tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59399824-5817-ef45-209d-35dab587a406
* Version Independent ID: 322b5820-c559-9a0b-ef66-1c31945ead2e
* Content: [Types of tables - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/types-of-entities)
* Content Source: [powerapps-docs/maker/data-platform/types-of-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @aitortema. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@aitortema - The article was updated some time ago to briefly mention those table types with links to more information.
Closing issue.
