### ISSUE TITLE
What about Elastic tables?

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/powerapps-docs#4397]
What about Elastic tables?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59399824-5817-ef45-209d-35dab587a406
* Version Independent ID: 322b5820-c559-9a0b-ef66-1c31945ead2e
* Content: [Types of tables - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/types-of-entities)
* Content Source: [powerapps-docs/maker/data-platform/types-of-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dombat. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@dombat - Yes, was updated a while ago to briefly mention elastic tables with a link to more information. https://learn.microsoft.com/en-us/power-apps/maker/data-platform/types-of-entities#elastic-tables
Closing issue.
