### ISSUE TITLE
Missing the step to configure the Resource Instance on the Storage Account Firewall

### ISSUE THREAD

**Issue by luke-aanensen** [MicrosoftDocs/powerapps-docs#4398]
Instructions Step "Configure network access to the Azure Data Lake Storage Gen2" A step is missing to allow the enterprisepolicy msi access through the firewall via Resource Instances. 

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/108710710/e67f091d-c3a7-481f-ba41-2586d8e88e65)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27e52c30-3d07-248e-d188-92ff021c5e5d
* Version Independent ID: 27e52c30-3d07-248e-d188-92ff021c5e5d
* Content: [Use managed identities for Azure with your Azure data lake storage - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-msi)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-msi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-msi.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @JasonHQX
* Microsoft Alias: **jasonhuang**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @luke-aanensen. This issue has been assigned to the doc author for review.

**Comment by JasonHQX** [comment]
Hi Luke, this step is not required. You only need to **select Allow Azure services on the trusted services list to access this storage account** under Resource Instances, 
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/102614732/07649f2c-3bff-481a-a4ca-8bbac7e31dd3)

**Comment by Mattp123** [comment]
@luke-aanensen - You issue has been responded to. 
Closing issue.
