### ISSUE TITLE
Add photos [Help Desk sample]

### ISSUE THREAD

**Issue by Hazzeo** [MicrosoftDocs/powerapps-docs#44]
Good app as far as submitting tickets, but missing the possibility to add user photos to individual tickets. Is there a way to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by caburk** [comment]
The simplest way to do this is adding the "Attachments" field to the form. This will add an attachment control to upload images and save them to the SharePoint list. 
Here are step by step instructions to do this: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install

**Comment by caburk** [comment]
Sorry pasted the wrong link. Use this one: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-forms#create-a-record
