### ISSUE TITLE
Article date

### ISSUE THREAD

**Issue by jwrocko** [MicrosoftDocs/powerapps-docs#440]
The date on this article is 9/20/2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45af718e-2094-01d1-9426-2d7403c59e1c
* Version Independent ID: 0d934f65-03ec-eb9d-9154-b66930166d33
* Content: [Create a canvas app from scratch using Common Data Service - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/data-platform-create-app-scratch#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/data-platform-create-app-scratch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/data-platform-create-app-scratch.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by thegongben** [comment]
Yeah I saw the date of 9/20/2019 too. I was trying to follow the tutorial but I cannot find "in the middle of the screen select to connect to data". Was this from a few years ago and things have changed quite a bit?
Thanks.

**Comment by phecke** [comment]
@jwrocko The correct article date is 5/21/2019. I will update the article. I will leave this issue open since @thegongben indicates one or more screen images/instructions may need to be updated.
