### ISSUE TITLE
Elastic table: What is the consumption model, benefit?

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/powerapps-docs#4401]
The doc page says that _Dataverse elastic tables are powered by Azure Cosmos DB_. There is no FAQ at the moment on this page. Can some Q&A be added to clarify what kind of consumption this uses? Is this some sort of managed virtual table, in which case no database consumption is being used, or is this still going to use database storage? Why would I use Elastic Table if it is still going to use database storage vs dumping that data in Cosmos DB directly and surfacing this as virtual table? I am not clear on what the benefit of elastic table, IF it uses database storage.

A comparison table along the likes of Virtual Table vs Normal Table would be good for Elastic Table vs Normal table, so that people can decide what the benefits and pitfalls are - especially from capacity, cost, entitlement limits and licensing perspective.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0bb9fd94-483d-1d6a-6c60-7b79c8a45d26
* Version Independent ID: 0bb9fd94-483d-1d6a-6c60-7b79c8a45d26
* Content: [Elastic tables (Preview) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/elastic-tables)
* Content Source: [powerapps-docs/developer/data-platform/elastic-tables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/elastic-tables.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rajyraman. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Hi @rajyraman 

Thanks for the feedback.

There is another article that has more information: [Create and edit elastic tables (preview)](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-elastic-tables)

**Comment by rajyraman** [comment]
@JimDaly - Thank you for the link. Is Elastic table still consuming Database storage though?

**Comment by rajyraman** [comment]
@JimDaly - The document says _elastic tables are included with your Dataverse database_, so that is pretty much dead in the water for me, because the cost implications of storing millions of records in Dataverse and paying 1000s per month overweighs any performance benefits that I can get out of elastic tables. I would rather dump it in ADX and analyse it there.

**Comment by JimDaly** [comment]
Hi @rajyraman 
I'm going to defer to @pnghub to answer that one.

**Comment by pnghub** [comment]
https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-elastic-tables has considerations for elastic tables.

In terms of user/enterprise security and Dataverse feature set, Elastic Tables is closer to Standard tables. Makers can build apps  apps that leverage both standard and elastic tables within the context of DV security and goverance.

With Virtual Tables, one would need to manage storage, security and also pay for it.

We take your feedback on a table for the 3 types and will look to add it.

**Comment by rajyraman** [comment]
@pnghub - My only issue is cost. We are already have so many issues trying to bring the cost down for database capacity consumption. If elastic tables are also charged in the same database tier, I don't think it would be cost effective to store "tens of millions of rows" like the docs say.

**Comment by pnghub** [comment]
Hi @rajyraman - Fair point. The scenarios/apps for Elastic tables are more large scale and options include time to live which allow auto deletion of data. We have some of the Microsoft apps use ET currently and happy to discuss more on a callm if you are thinking of anything specific and have thoughts to share.
 
Regarding DB capacity: We have some features for immediate and longer term relief. 
Moving email body to Azure blobs - Refer to "Email Storage" section in https://learn.microsoft.com/en-us/power-apps/developer/data-platform/email-activity-entities

Dataverse long term data retention in preview - https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-retention-overview 

Thx.
