### ISSUE TITLE
Star Rating is getting deprecated

### ISSUE THREAD

**Issue by carterbarry** [MicrosoftDocs/powerapps-docs#4402]
[Enter feedback here]
You should update the page to inform the community not to use Star Rating as it is getting deprecated. https://learn.microsoft.com/en-us/power-platform/important-changes-coming#model-driven-app-controls-deprecation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f70da457-fe92-f053-5608-a3ee60519e78
* Version Independent ID: cf8b0038-9d27-3ff3-2a7d-45730daec893
* Content: [List of controls available for model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/additional-controls-for-dynamics-365-for-phones-and-tablets)
* Content Source: [powerapps-docs/maker/model-driven-apps/additional-controls-for-dynamics-365-for-phones-and-tablets.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/additional-controls-for-dynamics-365-for-phones-and-tablets.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @carterbarry. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@carterbarry - Thank you for your feedback. The article has been updated to reflect that it's been deprecated. Will be published live in about 6 hours.

Closing issue.
