### ISSUE TITLE
Background Operations timeout

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/powerapps-docs#4420]
Are [background operations](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/background-operations) subject to 2 minute timeout? Please add if this is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a67c1820-c820-3b5e-8151-f564e3aa71cc
* Version Independent ID: a693b922-04ad-71fa-341e-3db815c15d9e
* Content: [Scalable Customization Design: Overview (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/scalable-customization-design/overview)
* Content Source: [powerapps-docs/developer/data-platform/scalable-customization-design/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/scalable-customization-design/overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @rogergilchrist
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rajyraman. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@rajyraman Background operations are not subject to the 2-minute time limit that applies to plug-in execution.

**Comment by JimDaly** [comment]
@rajyraman 
Background operations execute a Custom API asynchronously.
The Custom API the plug-in that runs the Custom API main operation is limited to 2 minutes.

For Questions related to background operations, it would be best to open doc feedback issues on the article related to background operations. [Background operations (Preview)](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/background-operations?tabs=sdk)

**Comment by JimDaly** [comment]
I added this sentence to clarify:

> Custom APIs use plug-ins to perform the data operations. Like all Dataverse plug-ins, these plug-ins have a two-minute execution time out. Sending the request asynchronously doesn't provide more execution time.
