### ISSUE TITLE
Misleading step to query retained data

### ISSUE THREAD

**Issue by adekola** [MicrosoftDocs/powerapps-docs#4421]
In the steps to query retained data, user is told to open the Dynamics Settings page, then select Advanced Find in the command bar. What the user should do is click on "Edit Filters" on a view of the table with retained data and then click on "Change to retained data"
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f214df6-a230-96b6-25f4-bbed1e3d8cd0
* Version Independent ID: 5f214df6-a230-96b6-25f4-bbed1e3d8cd0
* Content: [View long term retained data in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-retention-view)
* Content Source: [powerapps-docs/maker/data-platform/data-retention-view.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-retention-view.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @adekola. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@adekola - Thank you for your feedback! The article has been revised to use the correct steps to open a model-driven app that contains the table and then use Edit filters to be able to make the switch to view retained data.
Closing issue.
