### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#443]
These instructions are no longer applicable, there is ability to Export Resources on the Environment pages in the admin center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb5095de-43d8-bb9e-2cda-09db4402a678
* Version Independent ID: 52bca204-da0a-5e7c-bb37-fe1ea14d772d
* Content: [Export and import resources - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/export-import-packages)
* Content Source: [powerapps-docs/administrator/export-import-packages.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/export-import-packages.md)
* Service: **powerapps**
* GitHub Login: @nimakms
* Microsoft Alias: **nimak**

**Comment by jimholtz** [comment]
@DeanGross 
Sorry for the delayed response. I'm working with the product team to get free cycles to get this content updated for the Power Platform admin center.
