### ISSUE TITLE
Example Create Picklist column

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/powerapps-docs#4432]
Docs currently show how to add columns of type:
string
money
datetime
boolean
Lookup

Please add example how to add a Picklist

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa97977e-5a9a-fcdf-1610-f6ed6570dd2e
* Version Independent ID: 893c9f21-e784-13aa-28ce-1d2d5e941e47
* Content: [Create and update table definitions using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-update-entity-definitions-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/create-update-entity-definitions-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/create-update-entity-definitions-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by JimDaly** [comment]
@mores 
Thanks for your feedback.
I happen to have some examples that I can add here.
I'll add them.

**Comment by JimDaly** [comment]
@mores 
This new article should be published by noon today PST:
https://learn.microsoft.com/power-apps/developer/data-platform/webapi/create-update-column-definitions-using-web-api

It includes the following examples:

- Create a string column
- Create a money column
- Create a datetime column
- Create a boolean column
- Create a customer lookup column
- Create a decimal column
- Create an integer column
- Create a memo column
- Create a choice column <-- A picklist example
- Create a multi-select choice column
