### ISSUE TITLE
'Enable Status Tag' option does not show up in Timeline Control

### ISSUE THREAD

**Issue by alexanstree** [MicrosoftDocs/powerapps-docs#4442]
When I navigate to the Contact form, select the Timeline control and then select a specific Activity type, I do not see the option to enable/disable the Status Tag.  

These are the options I see:
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/136510084/f547401e-4d19-4f3d-95ff-b3f0a5fabce2)

This is what the documentation states I should see:
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/136510084/2ab468f3-5f1a-46ce-9f2c-e3de66b4aa5a)

Please advise,

**Comment by Mattp123** [comment]
@alexanstree - The UI has changed and the article has been updated to reflect the change.
https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/set-up-timeline-control#show-status-tags-on-activity-record-types

Closing issue.
