### ISSUE TITLE
Need to create a Postman account to be able to use environments

### ISSUE THREAD

**Issue by julians1966** [MicrosoftDocs/powerapps-docs#4445]
Latest version of Postman requires you to sign in to Postman account to be able to create and use an environment

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Set up a Postman environment (Microsoft Dataverse for Apps) - Power Apps](https://learn.microsoft.com/en-gb/power-apps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @julians1966. This issue has been assigned to the doc author for review.

**Comment by julians1966** [comment]
PR #4559 raised
