### ISSUE TITLE
Virtual Entities. Can update fields but relationships fail on custom plugin not allowed. 

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/powerapps-docs#4446]
![VE-table-row-example-image](https://github.com/MicrosoftDocs/powerapps-docs/assets/19391937/88277920-c026-444d-b93a-51487b01394f)
![VE-adding-relationship-failure-image](https://github.com/MicrosoftDocs/powerapps-docs/assets/19391937/e978b7ab-4074-45d0-a801-3d60a22a401a)
![VE-automate-relate-code-image](https://github.com/MicrosoftDocs/powerapps-docs/assets/19391937/1359c4ae-bd65-43ec-b882-a4f2dc8b2f31)
Accessing mserp_(various) virtual entity from F&O.
Can update fields from Power Automate, Model and Canvas Apps. 
Creating relationships fails on various tables all with this error: 
"Custom plugin execution is not allowed in nested pipeline for Virtual Entity.  

Is it me or what else could I try?

Driving me bonkers. Thanks. Richard U.K

![VE-updated-from-Model-App-okay](https://github.com/MicrosoftDocs/powerapps-docs/assets/19391937/d7718087-564c-49bb-aecf-d11dde5b2f5c)
![VE-table-in-solution](https://github.com/MicrosoftDocs/powerapps-docs/assets/19391937/292cb03b-b013-490b-a3bf-10e4862c615b)
[VE-power-automate-relate-code.txt](https://github.com/MicrosoftDocs/powerapps-docs/files/11745193/VE-power-automate-relate-code.txt)
[VE-adding-relationship-failure.txt](https://github.com/MicrosoftDocs/powerapps-docs/files/11745194/VE-adding-relationship-failure.txt)
[VE-table-row-example.txt](https://github.com/MicrosoftDocs/powerapps-docs/files/11745195/VE-table-row-example.txt)
![VE-project-contract-entity](https://github.com/MicrosoftDocs/powerapps-docs/assets/19391937/8447aba9-c37c-4b4b-a545-c4db14551d2d)

**Comment by phecke** [comment]
@tacklers Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/.

Closing this issue.
