### ISSUE TITLE
Is it the Logical Table Name at the end of the Url for this API call?

### ISSUE THREAD

**Issue by CmdrBeavis** [MicrosoftDocs/powerapps-docs#4448]
I sure wish that SOMEWHERE in this post/article it would specify what `accounts` actually is at the end of the Url. (`POST [Organization URI]/api/data/v9.0/accounts HTTP/1.1`)

I'm ASSUMING it's the logical table name, but for people who've not done a ton of Dataverse API stuff, it would be nice if it was STATED, SPECIFICALLY. Plskthx.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73bddced-c6d4-2563-25ea-48a6e6305077
* Version Independent ID: 8e78d9f5-d35c-aae7-ed30-9599fb567433
* Content: [Create a table row using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-entity-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/create-entity-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/create-entity-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by JimDaly** [comment]
@CmdrBeavis 
Scott -

Right below the first example you can find this:

> To create a new entity record you must identify the valid property names and types. For all system tables and attributes (table columns), you can find this information in the topic for that entity in the [Dataverse table/entity reference](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/about-entity-reference). For custom tables or columns, refer to the definition of that table in the [CSDL $metadata document](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-service-documents#csdl-metadata-document). More information: [Web API EntityTypes](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-entitytypes)

Please also note that the introductory page [Perform operations using the Web API](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/perform-operations-web-api) guides you to other pages that explain the concepts you need to know to get started.

But I'm glad to accept your feedback. People come to our content from search results and may not have read all the supporting content.

I can update the content to clearly specify that in the example `accounts` is the is the [Entity set name](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-service-documents#entity-set-name) for the [account EntityType](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/account).

**Comment by CmdrBeavis** [comment]
Wow. Isn't all this just violently complicated.

Just looked at my table's properties and don't see a darn thing about its
EntityType. Obviously I've got a frustratingly large amount of reading to
do... just to add a row to a table. : (


Thanks and best regards,
Scott K. Fraley

**Comment by JimDaly** [comment]
I noticed that recently PowerApps has added some tools to make this easier.

Looking at the Table definition, you can expand Tools and choose **Copy set name**.

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/6353736/1d3dd9c8-7f7d-4721-85ea-eb250d40be8a)

But I still recommend becoming familiar with the $metadata service document.

I've updated the article with changes to clarify. These should be visible in the public document this afternoon.

**Comment by CmdrBeavis** [comment]
I am working in .Net, and so this is great news! I'll happily interact with
a library / class over an API call!

I've got a BFF Web API that's called by an Angular app, which was then
going to make the API call, but this lib probably makes it even easier! So,
yeah, cool!!


Thanks and best regards,
Scott K. Fraley
