### ISSUE TITLE
Name isn't valid. This identifier isn't recognized.

### ISSUE THREAD

**Issue by dmtk41** [MicrosoftDocs/powerapps-docs#445]
Following the tutorial I have cascading selection work fine. Department choices is filtered depend on Location selected. However, App checker shows the same error of Location Card and Department Card: "Name isn't valid. This identifier isn't recognized."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by dmtk41** [comment]
Solved by Change the "Location DataCard" and "Department DataCard".  
1/ Select the Location_DataCard on the left hand panel-> Go to the Advanced tab on the right hand panel-> Change the "Update" property to DataCardValue17.Selected.Result and " AllowedValue" to Distinct(Locations,
Location)
2/ Select the Department_DataCard on the left hand panel-> Go to the Advanced tab on the right hand panel-> Change the "Update" property to DataCardValue18.Selected.Result and " AllowedValue" to Distinct(Filter(Locations, Location = DataCardValue17.Selected.Result),Department)

**Comment by doctorhummus** [comment]
Thank you for these solutions; this problem had been bothering me for days, but now it is all sorted.
