### ISSUE TITLE
Primary Name Field: length

### ISSUE THREAD

**Issue by judema70** [MicrosoftDocs/powerapps-docs#4451]
Maybe you can warn people that the length of the primary name field cannot be increased after the creation of a table...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8f3598c-cd0e-2cd8-fa6b-5663f63c36bf
* Version Independent ID: 656dca2a-e65d-fdb9-545e-b73d906ce4f1
* Content: [Column data types in Microsoft Dataverse (contains video) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/types-of-fields)
* Content Source: [powerapps-docs/maker/data-platform/types-of-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/types-of-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@judema70 - The article you referenced in this issue doesn't explain the primary column name. However, the below article does so I've added a sentence to explain that once you save a table, you can't edit the name or description for the primary column: https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-entities-portal

Closing issue.
