### ISSUE TITLE
Function example showcases a function that isn't available for Formula columns

### ISSUE THREAD

**Issue by maatetoth** [MicrosoftDocs/powerapps-docs#4453]
The Now() function is not available for the Formula columns, and the example shows it, which could be confusing.
UTCNow() could be a better function to showcase.

Description | Example
-- | --
Retrieve a date value. | DateAdd(Now(), -1, TimeUnit.Year)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6f7d49a-1fb0-ffba-779d-9c8b6d055d15
* Version Independent ID: d6f7d49a-1fb0-ffba-779d-9c8b6d055d15
* Content: [Work with Dataverse formula columns - Power Apps](https://learn.microsoft.com/en-gb/power-apps/maker/data-platform/formula-columns#functions)
* Content Source: [powerapps-docs/maker/data-platform/formula-columns.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/formula-columns.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @matp
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @maatetoth. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@maatetoth - Thank you for your feedback. The article has been updated to use a working example.
Closing issue.
