### ISSUE TITLE
What the requirement Character code for import CSV file?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/powerapps-docs#4458]
[Enter feedback here]
I'm planning CSV data import from 3rd party app to dataverse. In this case, I have to make CSV file according to system specification's Character code? (ex. I must use UTF8.) 3rd party app CSV data contains Japanese. I am afraid of text garbling and import fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91aa21d9-0e21-b87a-4439-cfa800c9210c
* Version Independent ID: 25f91d7a-2fb6-06f4-4ab2-705ce6ea7986
* Content: [Import Data (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/import-data)
* Content Source: [powerapps-docs/developer/data-platform/import-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/import-data.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dshimogawa. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@bishalgoswami 

I looked at our documentation and could not find anywhere the character format was mentioned.
There is more information in this article: https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-import-export, but it does not mention the character code. I would assume UTF8, but I could be wrong.

I would recommend that you create one or more trial environments and test the import using your CSV file.
