### ISSUE TITLE
Very incomplete instructions

### ISSUE THREAD

**Issue by ClintWoods** [MicrosoftDocs/powerapps-docs#4459]
On this page it says "Open the sample solution in Visual Studio and sign the assembly with a key". I downloaded the project and am browsing the folder structure. I see folders named ai-builder, build-tools, component-framework, dataverse, model-driven-apps, portals, and powershell. Do any of them say anything that indicate what sample solution you are referring to? Please be more clear. Your documentation here and elsewhere is very frustrating.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5854b846-b90f-3aed-15ab-6eb2d75ce848
* Version Independent ID: 5dce093e-6b93-21e0-58fb-8cdc2b316c7c
* Content: [Azure aware custom plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/azure-aware-custom-plugin?view=op-9-1)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/azure-aware-custom-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/azure-aware-custom-plugin.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ClintWoods. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@ClintWoods 

Thanks for your feedback.

I've updated this article to clearly specify which solution file to open and where it exists in the repo.
Change should be published afternoon today.

PR 8353
