### ISSUE TITLE
The 2 fields " Location" and " Department" of the "Incidents" on Sharepoint not be updated

### ISSUE THREAD

**Issue by dmtk41** [MicrosoftDocs/powerapps-docs#446]
Cascading selection work fine. However, when I add " Submit" button to update the form, the 2 fields " Location" and " Department" is updated as blank, the other fields is updated as my input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by OmarSeri** [comment]
I'm having the same issue.

**Comment by dmtk41** [comment]
Solved by Change the "Location DataCard" and "Department DataCard".
1/ Select the Location_DataCard on the left hand panel-> Go to the Advanced tab on the right hand panel-> Change the "Update" property to DataCardValue17.Selected.Result and " AllowedValue" to Distinct(Locations,
Location)
2/ Select the Department_DataCard on the left hand panel-> Go to the Advanced tab on the right hand panel-> Change the "Update" property to DataCardValue18.Selected.Result and " AllowedValue" to Distinct(Filter(Locations, Location = DataCardValue17.Selected.Result),Department)

**Comment by jennparker2001** [comment]
Hi, I'm new to powerapps and I can't seem to find where to make the above correction.  Where do I find the location to change the "update" property?
