### ISSUE TITLE
Open form for a retained record?

### ISSUE THREAD

**Issue by Patrick-Fraenkel** [MicrosoftDocs/powerapps-docs#4464]
This question is about the long term data retention preview feature. If you retain a record, you are able to view it in a read-only grid view. You are not able to click on the record to open a read-only form. Is it possible to view retained records in a read-only form? And if not, is it planned for the future? It would be really important to know, if you can open the form of a retained record. As this is not mentioned in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f214df6-a230-96b6-25f4-bbed1e3d8cd0
* Version Independent ID: 5f214df6-a230-96b6-25f4-bbed1e3d8cd0
* Content: [View long term retained data in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-retention-view)
* Content Source: [powerapps-docs/maker/data-platform/data-retention-view.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-retention-view.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Patrick-Fraenkel. This issue has been assigned to the doc author for review.
