### ISSUE TITLE
Security for "Invoke a WebHook from a plug-in or workflow activity"

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/powerapps-docs#4469]
Hi,

I'd like to see in this article information about which plugins can have access to that existing webhook. To describe my data protection concern, as a rough idea: The client creates a webhook configuration to some own backend service to retrieve sensitive data. Then the client installs a 3d party managed solution with malicious code, that iterates through all available service endpoints and tries them to get data out of connected services.
I'd like to see in the documentation, if there is a possibility to configure a webhook in that way, that not any plugin can use it. Alternatively would be good to have a notion to make readers aware about webhook being available for any Azure-aware plugin of the Dataverse environment.

Kind regards,
Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6a3364c-df99-19a8-ecfe-cc209eab50f2
* Version Independent ID: 61fd6597-0d6b-e2f0-01c6-fc8659621062
* Content: [Use Webhooks to create external handlers for server events (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-webhooks#invoke-a-webhook-from-a-plug-in-or-workflow-activity)
* Content Source: [powerapps-docs/developer/data-platform/use-webhooks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-webhooks.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @jaredha
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@soutchilin 

Thanks for your feedback. I'll forward this on to the team and ask for a response.

**Comment by JimDaly** [comment]
@soutchilin 

I can address this concern:

> The client creates a webhook configuration to some own backend service to retrieve sensitive data. 

A Service Endpoint configured for a web hook doesn't return data. Only a Service Endpoint configured for a Service Bus two-way or REST listener can return data back to the plug-in.

While this means that the Service Endpoints configured for Web Hooks aren't vulnerable to this, those configured for Service Bus using two-way or REST listeners could be.

Service Endpoint configuration data is available to any plug-in that runs in the environment.

**Comment by phecke** [comment]
@soutchilin Thanks for the feedback.

**Comment by soutchilin** [comment]
Thanks!
