### ISSUE TITLE
COUNTIF

### ISSUE THREAD

**Issue by l3mm0n** [MicrosoftDocs/powerapps-docs#447]
Looks like the function countif no longer exists in PowerBI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba03a60-32b8-89a7-e0fd-ea66e3375e16
* Version Independent ID: 0b91dbe0-d729-4bed-3e55-37705cfb12b1
* Content: [Count, CountA, CountIf, and CountRows functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-table-counts#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-table-counts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-table-counts.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
This is the documentation for PowerApps which continues to support CountIf.
