### ISSUE TITLE
Missing msdyn_dualwriteentitymaps in CusomizationsSolutions.xsd

### ISSUE THREAD

**Issue by jrg999999** [MicrosoftDocs/powerapps-docs#4474]
Schema CustomizationsSolutions.xsd (9.0.0.2090) is missing msdyn_dualwriteentitymaps as a child of ImportExportXML

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8396f7-c76f-ec02-38f3-a04c1bed1a91
* Version Independent ID: 28486176-2a12-872e-7de1-d2a36f5b11a1
* Content: [Edit the customizations XML file with schema validation (model-driven apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/edit-customizations-xml-file-schema-validation)
* Content Source: [powerapps-docs/developer/model-driven-apps/edit-customizations-xml-file-schema-validation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/edit-customizations-xml-file-schema-validation.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jrg999999. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Closing this since no response.
