### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by mAbusetteh** [MicrosoftDocs/powerapps-docs#4475]
[Enter feedback here]

Outdated interface as usual 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d26c501-923d-a61e-d1d2-8d76e79f5d8b
* Version Independent ID: 09594e35-bcde-d0f8-c42c-a740c5541449
* Content: [Create and design model-driven app forms - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/create-design-forms)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-design-forms.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/create-design-forms.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mAbusetteh. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@mAbusetteh - Thank you for your feedback. The article has been revised to link to the recently updated article that shows how to add/remove forms from a model-driven app via the modern app designer.
Closing issue.
