### ISSUE TITLE
Profiler Registers against wrong workflow activity.

### ISSUE THREAD

**Issue by ryanperrymba** [MicrosoftDocs/powerapps-docs#448]
When registering the profiler against a workflow activity the profiler step shows under the profiler, and the subject is named after the target workflow, but no profile traces / profiles appear to be created.  Double clicking the new profiler to view the settings opens the settings box, but with the target workflow set incorrectly. Have tried multiple times and the subject is correct each time, but the target workflow is wrong. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae2bca0-76de-3f98-b0e7-65a137baafa2
* Version Independent ID: eb803d04-bddc-0c43-3dcb-110187fbf379
* Content: [Debug Workflow Activities (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/workflow/debug-workflow-activites#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/workflow/debug-workflow-activites.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/workflow/debug-workflow-activites.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Issues reported for this repository are about the content of the documentation. If you require technical support, you should go to [https://admin.powerplatform.microsoft.com/support](https://admin.powerplatform.microsoft.com/support) and open a support request.
