### ISSUE TITLE
Dataverse Synapse Link - ALM - unable to update the configuration

### ISSUE THREAD

**Issue by mdeheer-crmp** [MicrosoftDocs/powerapps-docs#4480]
The initial transport of the Azure Synapse Link for Dataverse configuration from my dev to my test environment works fine, with the use of the tooling and description. However, when I want to transport an update of the configuration (e.g. adding new tables to my configuration), the configuration in my target environment won’t be changed. The only way I was able to load the new configuration, was to delete the old configuration transport solution, unlink the Azure Synapse Link for Dataverse configuration, load the new transport solution and then import from solution. That is not what I want, because it will delete all data from the storage account first and then reload it.

**Comment by phecke** [comment]
@mdeheer-crmp 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ Closing this issue.

If you have a question or issue with the documentation, let us know.
