### ISSUE TITLE
Tables for Retention Policies are demonstrated on this page but appear not selectable for our Dutch environments

### ISSUE THREAD

**Issue by befaes** [MicrosoftDocs/powerapps-docs#4488]
The demonstrated and understood as in preview Retention Policies are visible on our environment. However when creating a new policy no tables are displayed in the list and as such not selectable, although mandatory for a policy.

Also: The en version of the below resource refers to current page. The nl version as below seems outdates and does not seem to include latest details and expected reference yet.
https://learn.microsoft.com/nl-nl/power-platform/release-plan/2023wave1/data-platform/dataverse-long-term-data-retention

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist voor de koppeling learn.microsoft.com ➟ GitHub-probleem.*

* ID: 34a539e8-087d-24b6-b403-122169491914
* Version Independent ID: 34a539e8-087d-24b6-b403-122169491914
* Content: [Overzicht van langetermijnretentie van gegevens in Dataverse - Power Apps](https://learn.microsoft.com/nl-nl/power-apps/maker/data-platform/data-retention-overview)
* Content Source: [powerapps-docs/maker/data-platform/data-retention-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-retention-overview.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @befaes. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @befaes. This issue has been assigned to the doc author for review.

**Comment by Dealgan12** [comment]
Dutch release plan was recently updated and fixed this feedback.  The inconsistency is likely due to the the updated localized content was not available yet.
