### ISSUE TITLE
Dataverse PowerFX ^ operator

### ISSUE THREAD

**Issue by toyranni** [MicrosoftDocs/powerapps-docs#4489]
Hi I have been working with the Formula columns in  Microsoft Dataverse (preview). I have been trying to create a column that is using the ^ operator or equivalent Power function but its not working. It seems that it's not supported yet, according to this link: [https://learn.microsoft.com/en-gb/power-apps/maker/data-platform/formula-columns#functions](url)
![Screenshot 2023-06-26 124656](https://github.com/MicrosoftDocs/powerapps-docs/assets/38291470/d3e08dea-0703-4b1c-bc33-2420a00886bc)

When will this feature be released?

**Comment by Mattp123** [comment]
@toyranni - Release plans are published separately from the core technical documentation that you are referencing. Information for release plans about formula columns are published here: https://learn.microsoft.com/en-us/power-platform-release-plan/2022wave1/data-platform/enable-power-fx-formula-columns-inside-dataverse-tables.

Closing issue.
