### ISSUE TITLE
Exciting

### ISSUE THREAD

**Issue by thegongben** [MicrosoftDocs/powerapps-docs#449]
This is exciting. The scripts look exactly like the same as in other old tools like PowerBuilder's datawindow scripts. This is very helpful for older folks who started with PowerBuilder or VB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce87949-54e8-f4ed-5d49-e11758e582b8
* Version Independent ID: 31d52576-021f-cdcf-bb49-c1c5d7ed85b2
* Content: [Transform your InfoPath form to a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/transform-infopath)
* Content Source: [powerapps-docs/maker/canvas-apps/transform-infopath.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/transform-infopath.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback, and glad to know this was helpful.
