### ISSUE TITLE
PowerApps

### ISSUE THREAD

**Issue by lopsact** [MicrosoftDocs/powerapps-docs#45]
Excellent !!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dca84a9-627d-45ce-b69c-5a377d290d4a
* Version Independent ID: 98fa778e-0b3d-dfb7-0db5-00bf87bbd4cf
* Content: [Getting started - PowerApps](https://docs.microsoft.com/en-us/powerapps/guided-learning/get-started?tutorial-step=7#step-1)
* Content Source: [powerapps-docs/guided-learning/get-started.yml](https://github.com/MicrosoftDocs/powerapps-docs-pr/blob/live/powerapps-docs/guided-learning/get-started.yml)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@lopsact Thanks!
