### ISSUE TITLE
Assembly update issues when adding new Plugin types.

### ISSUE THREAD

**Issue by frederickm13** [MicrosoftDocs/powerapps-docs#450]
When attempting to update a currently registered assembly to add new plugin types (as performed in this step: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-update-plug-in#update-the-plug-in-assembly-registration), the following error message is thrown in the Plugin Registration Tool:
"Plug-in assembly does not contain the required types or assembly content cannot be updated."

This error only occurs using the most recent version of the Plugin Registration Tool. If I downgrade and use version 9.0.2.5 of the Plugin Registration Tool, then I am able to update the assembly and add the new plugin type successfully. Also, the error only seems to occur when there are steps already registered under the current assembly. If no steps are registered, then I am able to update and add new plugin type just fine.

From my understanding, this error is shown because the updated assembly contains a new plugin type that is not contained in the current assembly. However, even when I change one of the build/revision numbers of the assembly, the error is not resolved. 

Can we please receive some additional documentation or guidance regarding assembly versioning and how to go about adding new plugin types to current assemblies? 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3158b76f-111a-5bf0-26e4-cef8c12191b9
* Version Independent ID: cf6051a8-6e6f-efb8-5809-5a314274221c
* Content: [Tutorial: Update a plug-in (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-update-plug-in#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/tutorial-update-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/tutorial-update-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Agree that there is more information related to this that can be presented.
Adding it to my TODO list.

**Comment by JimDaly** [comment]
We fixed a bug that was causing this behavior. Should be working as expected now.
