### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by anotherRedbeard** [MicrosoftDocs/powerapps-docs#451]
It would be very helpful to show an example of collecting a table.  I'm not sure what is meant by 'To accomplish this, wrap the table in a record first.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c8e63a-856f-c7f7-9553-d2564c1e25e4
* Version Independent ID: 29037222-286c-8fc0-79e5-4bb599ad7c70
* Content: [Collect, Clear, and ClearCollect functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-clear-collect-clearcollect#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the suggestion.  I added some examples for collecting records and tables.
