### ISSUE TITLE
Typo elimiar

### ISSUE THREAD

**Issue by fhunth** [MicrosoftDocs/powerapps-docs#4516]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 507f3fb4-078a-fa09-cc1b-b10b2097c7c0
* Version Independent ID: 00b1b2e4-55e5-6cce-6943-63ca584dce34
* Content: [Compartir y asignar (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/es-es/power-apps/developer/data-platform/security-sharing-assigning?tabs=sdk)
* Content Source: [powerapps-docs/developer/data-platform/security-sharing-assigning.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/security-sharing-assigning.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by Bernadette2022** [comment]
@fhunth, I don't see any feedback. Can you please provide us your specidfic feedback.

**Comment by phecke** [comment]
@fhunth Insufficient information provided. Closing this issue.
