### ISSUE TITLE
GA release date for Power Apps formula columns

### ISSUE THREAD

**Issue by a-deo** [MicrosoftDocs/powerapps-docs#4521]
Hello there, is there any update on the GA release date?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6f7d49a-1fb0-ffba-779d-9c8b6d055d15
* Version Independent ID: d6f7d49a-1fb0-ffba-779d-9c8b6d055d15
* Content: [Work with Dataverse formula columns - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/formula-columns)
* Content Source: [powerapps-docs/maker/data-platform/formula-columns.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/formula-columns.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @matp
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @a-deo. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@a-deo - The general availability (GA) date is not yet determined. When the feature does move to GA, it will be published in the release plan for the feature here: https://learn.microsoft.com/en-us/power-platform-release-plan/2022wave1/data-platform/enable-power-fx-formula-columns-inside-dataverse-tables

Closing issue.
