### ISSUE TITLE
Plugin Registration Tool Configuration

### ISSUE THREAD

**Issue by robertmaraan** [MicrosoftDocs/powerapps-docs#4533]
[Enter feedback here]
Can you put the actual PRT configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08de6800-4dd9-aa6c-a1b4-7691e94b33f5
* Version Independent ID: df6cbdc4-1a2e-09ad-9807-ad3ad8bccf56
* Content: [Sample: One-way listener (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/one-way-listener?source=recommendations)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/one-way-listener.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/one-way-listener.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robertmaraan. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@robertmaraan To register the service endpoint step, see [Tutorial: Register an Azure-aware plug-in using the Plug-in Registration tool](https://learn.microsoft.com/power-apps/developer/data-platform/walkthrough-register-azure-aware-plug-in-using-plug-in-registration-tool).
