### ISSUE TITLE
Does environment is also considered when enforcing service limits?

### ISSUE THREAD

**Issue by y0geshdev** [MicrosoftDocs/powerapps-docs#4540]
Are these service limits enforced to per user per web server (across all environments) or per user per dataverse environment?

For example - can a single use having access to 2 dataverse environment make total 4000 requests (2000/environment) in 5 minute window where both the environment are hosted on same web server?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6c11a1-c9f6-a904-f49a-0fedbe9f511f
* Version Independent ID: 7db20846-7922-23d4-f261-4c54e61b6913
* Content: [Service protection API limits (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/api-limits?tabs=sdk)
* Content Source: [powerapps-docs/developer/data-platform/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/api-limits.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by JimDaly** [comment]
@y0geshdev 

The limits are per Dataverse environment.

As stated:

> _Each web server available to your environment will enforce these limits independently._

Each Dataverse environment will usually have more than one web server supporting it. Two different Dataverse environments will not share servers.

This is not possible:

> _both the environment are hosted on same web server_
