### ISSUE TITLE
Issue with example code in Patch statement

### ISSUE THREAD

**Issue by debajdu** [MicrosoftDocs/powerapps-docs#4549]
The provided example code does not seem to work. As already mentioned in the limitation, tables have to accessed using the @ operator,
Patch(Faxes,
    Collect(Faxes, { Subject : "Sub1" } ),
    { Regarding : First(Accounts) }
)

Faxes here need to be likely replaced by [@Faxes]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc051e7-945b-0af9-1304-d3c0531fbbff
* Version Independent ID: 6dc051e7-945b-0af9-1304-d3c0531fbbff
* Content: [Use Dataverse low-code plug-ins - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/low-code-plug-ins)
* Content Source: [powerapps-docs/maker/data-platform/low-code-plug-ins.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/low-code-plug-ins.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @debajdu. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@debajdu - The @ operator is only required for automated plug-ins as the formula sample works for instance plug-ins. I've added the following sentence to the limitation:
If you're creating an automated plug-in, prepend @ to each table referenced in the Power Fx formula.

Closing issue.
