### ISSUE TITLE
EntityRecord.{getNamedReference,getRecordId} are listed for Canvas apps only

### ISSUE THREAD

**Issue by janis-veinbergs** [MicrosoftDocs/powerapps-docs#4555]
These methods are listed as Available For canvas apps only. Really? One should double check are they really unsupported for MDA?

- getNamedReference 
- getRecordId

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00fdf657-b577-7af2-59a9-5c5d8b247013
* Version Independent ID: 70de8ba9-5f63-b451-41ac-c9e66076f9e0
* Content: [EntityRecord in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord)
* Content Source: [powerapps-docs/developer/component-framework/reference/entityrecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/entityrecord.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**[getNamedReference](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord/getnamedreference)	Gets the object that encapsulates an EntityReference as a plain object.	Canvas apps
[getRecordId](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/entityrecord/getrecordid)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @janis-veinbergs. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@janis-veinbergs 

Thanks for your feedback. Sorry for the delay in responding.

Are you saying that these are available in MDA? You have used them there?

Docs say that they aren't available, so they shouldn't be available.
If you are asserting that the docs are wrong, and they are available: I can ask someone to investigate this.

**Comment by JimDaly** [comment]
@janis-veinbergs 

Janis
Since I haven't heard back from you, I'm going to close this. 
If you are saying they **are available** in MDA, then I'd take this up with the dev team.
You can respond to this or create a new issue.

**Comment by janis-veinbergs** [comment]
@JimDaly yes they are available in MDA. Even MS provided sample control "ModelDrivenGrid" uses one of those: https://github.com/microsoft/PowerApps-Samples/blob/b7bf8a41efe4eda7c3d978af082f59a64b34db18/component-framework/ModelDrivenGridControl/ModelDrivenGrid/Grid.tsx#L109

If those methods wouldn't be available, there wouldn't be a way to get grid row entity id.

**Comment by JimDaly** [comment]
Thanks @janis-veinbergs 
I also found an example using `getNamedReference` in the ModelDrivenGrid sample.
That is all the evidence I needed. I've made this change.
