### ISSUE TITLE
the description of ChangeData in Audit table is not updated

### ISSUE THREAD

**Issue by iChrisJ** [MicrosoftDocs/powerapps-docs#4558]
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/audit#BKMK_ChangeData 

In the latest version, whether the ChangeData attribute in Audit table is still "Contains a CSV of old values of all the attributes"? Or it's json of old values and new values?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb1ee93d-6704-4e15-bb22-dbe911853dab
* Version Independent ID: a232bffe-6351-c1c2-16c3-7b180a4bbd15
* Content: [Auditing (Audit)  table/entity reference (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/audit#BKMK_ChangeData)
* Content Source: [powerapps-docs/developer/data-platform/reference/entities/audit.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/reference/entities/audit.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@iChrisJ Are you seeing something different in the ChangeData attribute value that has caused you to question the data format description?

I did find this note in the topic [Retrieve the history of audited data changes](https://learn.microsoft.com/power-apps/developer/data-platform/auditing/retrieve-audit-data?tabs=sdk):

_The ChangeData Column isn't included in the Web API audit EntityType. Don't use this data. Instead, use the messages to [retrieve audit change history](https://learn.microsoft.com/power-apps/developer/data-platform/auditing/retrieve-audit-data?tabs=sdk#retrieve-audit-change-history).

Seems like that column may no longer contain valid values.

@JimDaly Any feedback from you on this question?

**Comment by JimDaly** [comment]
Adding @kalavany, @paulliew, & @sumantb-msft 

The reference documentation uses the descriptions in the AttributeMetadata.Description for the column.
I'm aware that the dev team made changes to the way this ChangeData column works, but the description in the metadata needs to be updated to reflect this.

We can't override this manually. It needs to be changed in the metadata definition for the column.

**Comment by phecke** [comment]
@iChrisJ Closing this issue. If you still have questions, open a new issue.
