### ISSUE TITLE
no details about virtual table permisisons

### ISSUE THREAD

**Issue by FintanGuihen** [MicrosoftDocs/powerapps-docs#4564]
It appears users of apps with virtual tables require additional permissions but these are not documented in the page. 
IT would save a massive amount of troubleshooting time to include information on necessary permissions for using virtual tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42ae2cb6-ce2a-21c7-cb81-b60e7b026753
* Version Independent ID: 5a3cb7c0-6881-1d96-0dc3-639324a4568c
* Content: [Get started with virtual tables (entities) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/get-started-ve)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FintanGuihen. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@FintanGuihen 
Thanks for your feedback.
This article is within our content for developers and focuses on how developers can create their own data providers.

Did you find this more general article [Create and edit virtual tables that contain data from an external data source](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-virtual-entities)?

I think your question applies to virtual tables in general, and the other topic would be the place where the information you are looking for should be found. Do you feel this information should be presented only for developers?

**Comment by phecke** [comment]
@FintanGuihen Closing this issue. If you still have questions, open a new issue.
