### ISSUE TITLE
Elastic tables and Synapse Link for Dataverse record deletion / TTL

### ISSUE THREAD

**Issue by pieterh** [MicrosoftDocs/powerapps-docs#4566]
Hi,

When I add a Elastic  table (using overwrite mode) to the Synapse Link for Dataverse, the data is properly exported to the data lake. Performing creates, updates and deletes work as expected.
However, when I set the time to live for a record in the elastic table, the record that expires and is deleted from the database, the record is not removed from the data lake.

This is not what I expected. I expected the same behavior as when a record is deleted from the UI. Could you have a look at this to see if this behavior is as designed or not. If this is by design, could you make sure this is clear from the documentation?

Kind Regards,
Pieter Hilkemeijer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0bb9fd94-483d-1d6a-6c60-7b79c8a45d26
* Version Independent ID: 0bb9fd94-483d-1d6a-6c60-7b79c8a45d26
* Content: [Elastic tables for developers (preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/elastic-tables)
* Content Source: [powerapps-docs/developer/data-platform/elastic-tables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/elastic-tables.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pieterh. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@sabinn-msft Can you also look at this question?

This seems more like a question for [What is Azure Synapse Link for Dataverse?](https://learn.microsoft.com/power-apps/maker/data-platform/export-to-data-lake) or possibly [Create and edit elastic tables (preview)](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-elastic-tables) since the scope of this article is to use Dataverse APIs to work with elastic tables.

**Comment by pnghub** [comment]
Hi @pieterh - Thanks for reporting this.

This is a known gap that requires to be fixed (ETA TBD) - "When time to live (TTL) is used on a row, the row will get deleted from the elastic table when TTL has expired. If it's synchronized to a data lake using Synapse Link for Dataverse before TTL expiry, it won't be deleted from the data lake"

It has documented now in the public doc.

Best, girish

**Comment by pieterh** [comment]
thank you
