### ISSUE TITLE
Create Workflow in the new experience screen

### ISSUE THREAD

**Issue by robertmaraan** [MicrosoftDocs/powerapps-docs#4570]
[Enter feedback here]
Why not make use of the new Experience for creating custom workflows?
See reference link.

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/workflow/tutorial-create-workflow-extension#test-your-assembly

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7be9b760-822d-33a4-2ac2-ed3f654e614e
* Version Independent ID: 11c0c3ed-ca7f-3bc3-63f6-80e123d9e133
* Content: [Tutorial: Create workflow extension (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/workflow/tutorial-create-workflow-extension)
* Content Source: [powerapps-docs/developer/data-platform/workflow/tutorial-create-workflow-extension.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/workflow/tutorial-create-workflow-extension.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @robertmaraan. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@robertmaraan

Thanks for your feedback. What new experience are you referring to?

**Comment by robertmaraan** [comment]
Hi,

It would be better if you can do all configurations from Power Apps not in
Dynamics 365.

Thanks

**Comment by JimDaly** [comment]
@robertmaraan 

I agree. When that becomes possible, we need to update this.
