### ISSUE TITLE
DisableAsyncTimeout() silently fails if called after an await in a custom OnSave Handler event

### ISSUE THREAD

**Issue by daryllabar** [MicrosoftDocs/powerapps-docs#4574]
It isn't documented, but it should be that the call to disableAsyncTimeout must be done before any async statement.  Ideally the system should throw an error if you call disableAsyncTimeout, after the 10 seconds timeout race promise is started.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c3168e3-774b-aad1-0cd2-d7e6eb487088
* Version Independent ID: 2fb2edc5-b09d-bfaa-0644-675d29e00598
* Content: [Form OnSave event (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/form-onsave?source=docs#async-onsave-timeouts)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by JimDaly** [comment]
@daryllabar 

Thanks for your feedback.

I see two things here:

1. Update docs to explicitly call out that the `disableAsyncTimeout` function be called before any async statement.
2. A feature request to: "_...throw an error if you call disableAsyncTimeout, after the 10 seconds timeout race promise is started._"

I can't help with the second one, but @HemantGaur might want to comment.

For the first one, I want to encourage everyone, especially our MVPs, that they can directly add these kinds of enhancements.

For this page: You can edit this file to add it: [https://github.com/MicrosoftDocs/powerapps-docs/edit/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md](https://github.com/MicrosoftDocs/powerapps-docs/edit/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/form-onsave.md)

I need to get the feature team to approve changes. It is generally easier to get approval of an actual change than the suggestion that a change be made.

**Comment by daryllabar** [comment]
Dang it Jim!  I'm a complainer, not a fixer!  In all serious, I couldn't find the link to edit on my phone, so thank you for that.  Would it be helpful if I edited it now?

And if there is anything I can do to help with the request to the feature team, let me know.

**Comment by JimDaly** [comment]
LOL

Please feel free to edit. If you don't, I'll eventually get to it.

@HemantGaur also gets these notifications, so he may comment.

**Comment by JimDaly** [comment]
@daryllabar 

I integrated your change in our internal branch. Thanks for that.

As for the feature request, this isn't the forum for that.

I looked to see if there were any existing feature request on the ideas site [Search for ideas with disableAsyncTimeout](https://ideas.powerapps.com/d365community/search/f1458c72-ae29-ed11-9db2-000d3a8c451e?q=disableAsyncTimeout), but I didn't find any. You may want to create one.

**Comment by daryllabar** [comment]
Idea created: https://ideas.powerapps.com/d365community/idea/4763dca4-1c2c-ee11-a81c-6045bdbc3dcf
