### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by joannachongshen** [MicrosoftDocs/powerapps-docs#4578]
Broken link for Advanced lookup. 
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/115131497/864bdf00-28aa-4ff9-9eca-11184bcba033)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb3dd507-6444-aac3-f6ac-78d87edbce76
* Version Independent ID: fb3dd507-6444-aac3-f6ac-78d87edbce76
* Content: [Mobile offline capabilities and limitations - Power Apps](https://learn.microsoft.com/en-us/power-apps/mobile/offline-capabilities)
* Content Source: [powerapps-docs/mobile/offline-capabilities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/mobile/offline-capabilities.md)
* Service: **powerapps**
* Sub-service: **mobile**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by sericks007** [comment]
@joannachongshen, thanks for letting us know about this! I've fixed the link.  The updated content will be published later today.
