### ISSUE TITLE
formContext.getControl error in code

### ISSUE THREAD

**Issue by RRamdewar** [MicrosoftDocs/powerapps-docs#4583]
This line should use the control name on the form which is prefixed with "WebResource_"
var wrControl = formContext.getControl("WebResource_CustomName");

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4c796e-ad9f-1929-f530-f088462522f9
* Version Independent ID: 40e67735-ac26-30a4-3191-0a86fd7b4b50
* Content: [getContentWindow (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/getcontentwindow)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RRamdewar. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@fafuxa-ms 
Can you look at this sample and the suggested change?

**Comment by JimDaly** [comment]
I've applied the change.
Thanks @fafuxa-ms  & @RRamdewar
