### ISSUE TITLE
I wish you would explain what the terms mean

### ISSUE THREAD

**Issue by RegalMushrooms** [MicrosoftDocs/powerapps-docs#4585]
This page is completely useless, i need an explination on how to build the link not an example of some stupid fields. give me the data model so i can see what goes where

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35dbaa64-a9f3-5e29-4d2f-1e5c36de6f32
* Version Independent ID: 4e73174f-6bd7-ba2c-30f7-d9036c27ea62
* Content: [Use FetchXML to query data (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-fetchxml-construct-query)
* Content Source: [powerapps-docs/developer/data-platform/use-fetchxml-construct-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-fetchxml-construct-query.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@RegalMushrooms You can find the FetchXml schema here: [schema](https://learn.microsoft.com/power-apps/developer/data-platform/fetchxml-schema)
