### ISSUE TITLE
Link to the actual sample

### ISSUE THREAD

**Issue by JohnDoeKyrgyz** [MicrosoftDocs/powerapps-docs#4587]
It would be much more useful if these documents actually linked to the sample code instead of directing the reader to download it. Most of the time people just want an example to reference and follow. They don't want to go through the hassle of downloading the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93fafd80-a6b8-4423-30fc-2f6234234166
* Version Independent ID: 03c2d8a2-dd70-eedd-99d3-d40f5e00b290
* Content: [Sample: Convert queries between Fetch and QueryExpression (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/convert-queries-fetch-queryexpression)
* Content Source: [powerapps-docs/developer/data-platform/org-service/samples/convert-queries-fetch-queryexpression.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/samples/convert-queries-fetch-queryexpression.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JohnDoeKyrgyz. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@JohnDoeKyrgyz 

Thanks for your feedback. 

I think this is a problem in the first sentence which says:

> This sample shows how to convert queries between FetchXML and QueryExpression. You can download the sample from [here](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/orgsvc/C%23/Convertqueriesfetchqueryexpressions).

I think the link you are looking for is at the end of the sentence, but it isn't visible enough. Instead, your attention is drawn to the first instruction that says:

> Download or clone the [Samples](https://github.com/Microsoft/PowerApps-Samples) repo so that you have a local copy.

For some newer sample pages, we have been trying something different. Please see:

- [Sample: SDK for .NET Use CreateMultiple and UpdateMultiple (preview)](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/create-update-multiple)
- [Sample: Web API Use CreateMultiple and UpdateMultiple (preview)](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/samples/create-update-multiple)
- [Elastic table sample code (preview)](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/elastic-table-samples)

I'd love to get your thoughts on whether this new design addresses this problem.
