### ISSUE TITLE
Update content to reflect latest updates for solution aware Power BI components.

### ISSUE THREAD

**Issue by aliyoussefi** [MicrosoftDocs/powerapps-docs#4593]
The following verbiage should be updated to reflect the solution aware Power BI components which could make this process much more streamlined.

"Unlike some of the other techniques suggested, Power BI reports are not solution aware. So there are more tasks required to ensure that development, test, and production scenarios are maintained."

Reference:
https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/create-edit-powerbi-report-dataset-components

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8ebec23-6a6e-6989-038c-268774144c50
* Version Independent ID: f8ebec23-6a6e-6989-038c-268774144c50
* Content: [Reporting overview for model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/reporting-overview)
* Content Source: [powerapps-docs/maker/model-driven-apps/reporting-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/reporting-overview.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @aliyoussefi. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@aliyoussefi - Thank you for your feedback. The article has been updated to reflect the current solution aware capabilities of Power BI components.
Closing issue.
