### ISSUE TITLE
Unapproved verbs [PowerShell]

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#46]
Please follow the powershell naming conventions so that we don't get the following 
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of  approved verbs, type Get-Verb.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
@DeanGross 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Please reopen if this issue still exists.
