### ISSUE TITLE
Trigger doesn't seem to work and SQL script in first pipeline fails if triggered manually

### ISSUE THREAD

**Issue by DDRus** [MicrosoftDocs/powerapps-docs#4604]
The trigger when set up like in the documentation doesn't trigger by itself even though I can see that the model.json has been updated. Triggering the process manually fails at the first step which is the SQL script. Help?
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/141430914/66ad7be7-3148-4120-9ad6-76beb937d7e7)
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/141430914/8e590c09-80ea-4aef-b1ee-f27031230f60)

**Comment by Mattp123** [comment]
@DDRus - Please add a link to the article you're referencing so we can process your idea.

**Comment by phecke** [comment]
@DDRus No response from the customer, closing issue.
