### ISSUE TITLE
System.Text.Json and plugins - Clarification

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/powerapps-docs#4611]
The latest change says

> Because the [Microsoft.CrmSdk.CoreAssemblies NuGet package has a dependency on System.Text.Json](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreAssemblies#dependencies-body-tab), **you're able to refer to [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json) types at design time**. However, the System.Text.Json.dll file in the sandbox run-time can't be guaranteed to be the same version that you reference in your project. If you need to use System.Text.Json, you should use the dependent assembly feature and explicitly include it in your NuGet package

Does this means that I can use System.Text.Json as long as the version matches to what is in CoreAssemblies, or I cannot use it at all? Worst case scenario is that what is in the Sandbox will be newer that what is referenced in the plugins.

Can you please clarify @JimDaly?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec7e9cc6-a519-7fdb-b4ea-ddf6264be0db
* Version Independent ID: ca85afa4-dd67-d413-a0c4-5de79fb9f0b5
* Content: [Write a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/write-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/write-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rajyraman. This issue has been assigned to the doc author for review.

**Comment by rajyraman** [comment]
@JimDaly - I got hopeful for a second that I can use System.Text.Json because CoreAssemblies uses it anyway. Json processing is a common requirement most of the time, so it would be good if it is possible to do this without dependant assembly.

**Comment by JimDaly** [comment]
@rajyraman 

Sorry to crush your hopes. The sandbox team asked me to add this because the change to the CoreAssemblies NuGet package makes it seem like that assumption could be made. They are trying to anticipate potential issues.

I'm going to close this. If you have any suggestions for better communicating this message, I'd be happy to hear them.

**Comment by rajyraman** [comment]
@JimDaly - The Hope crusher 🤣. I guess I'll have to wait for dependent assembly to be GA then.
