### ISSUE TITLE
Please include the registration project in the solution

### ISSUE THREAD

**Issue by KarloS206** [MicrosoftDocs/powerapps-docs#4627]
I ran **pac plugin init** in order to create the project. After I opened the project, the following dialog box appeared which rendered Visual Studio 2019 unresponsive. "Please include the registration project in the solution"

Mostly replicated as soon as I tried to right click on a .cs file.

**Comment by phecke** [comment]
@KarloS206 Is this a general comment about the command or are you following some instructions in one ofour articles? If so, please provide the link.

**Comment by JimDaly** [comment]
@KarloS206 

Issues in this repository are about the documentation of features. We can't offer technical support. You should contact support to report this issue.

While @petrochuk might be interested to hear about this error, there isn't anything we can do in the documentation to fix it.

**Comment by petrochuk** [comment]
PAC CLI, or other build tools issues can be reported here: https://github.com/microsoft/powerplatform-build-tools

**Comment by KarloS206** [comment]
Thanks Gents,

I'll report at Github. Thanks for the hard work.

Regards,
Karlo
