### ISSUE TITLE
Description for navigate

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4629]
Would it be possible to get a more specific description for the method "navigate"

It seems the parameter "formId" for an entity record is ignored. I'm not sure if this is intended or if I'm doing something wrong, because the description just says "This is similar to the [navigateTo](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto) method." I guess "similar" means, that it is not the same. What is the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ade424d-c9be-9c91-e40f-f1f0a1900572
* Version Independent ID: 0e680fea-adb3-f241-61ab-c320759344b1
* Content: [AppSidePane (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-app-appsidepane)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-app-appsidepane.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-app-appsidepane.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@darshSWL 

Thanks for your feedback.

The full description is: _Opens a page within the selected pane. This is similar to the [navigateTo](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto) method._

And there is an article about it linked below [Creating side panes by using a client API](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/create-app-side-panes)

_similar_ means it can achieve a similar outcome, but clearly it is different. It has a different set of parameters, none of which seems to use `formid`. I'm not clear about why you think `formid` can be used when it isn't listed as a parameter for this method.

**Comment by darshSWL** [comment]
@JimDaly 

Thank your for your reply.

> I'm not clear about why you think `formid` can be used when it isn't listed as a parameter for this method.

I'm failing to see the list of parameters for the navigate method.
Could you please tell me where the parameters for the navigate method are listed? I still can't find them and a colleague of mine can't find them either. [Creating side panes by using a client API](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/create-app-side-panes) contains just examples. but not a list of parameters.

**Comment by JimDaly** [comment]
@darshSWL 

OK. I think I understand your question now.

In [Creating side panes by using a client API](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/create-app-side-panes) we can see examples of the `navigate` method accepting parameters like `pageType`, `entityName`, `entityId`, and `webresourceName`.

But in [AppSidePane (Client API reference)](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-app-appsidepane) we only see the list of method names: `close`, `select`, and `navigate`. But the list of parameters below isn't about these methods.  They seem to be the properties for the [paneOptions object](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-app/xrm-app-sidepanes/createpane#paneoptions-object)

I think we are missing details for those three methods entirely.
Does this sound right?

I'll follow up with @adrianorth 

Thanks

**Comment by JimDaly** [comment]
@darshSWL 

Looks like **navigate** is supposed to take the same parameters as **navigateTo**. 
Agree that isn't clear at all.
But there may be some differences of behavior, potentially like ignoring the `formid` value that you mention.

And the heading of **Parameters** for AppSidePane s/b **Properties**
