### ISSUE TITLE
Typo in german translation

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4643]
The german translation uses the word "gird" instead of "grid".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 287c2340-0062-0bdd-0d96-7ef9102bd925
* Version Independent ID: 287c2340-0062-0bdd-0d96-7ef9102bd925
* Content: [Power Apps gird-Steuerelement - Power Apps](https://learn.microsoft.com/de-de/power-apps/maker/model-driven-apps/the-power-apps-grid-control)
* Content Source: [powerapps-docs/maker/model-driven-apps/the-power-apps-grid-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/the-power-apps-grid-control.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @jasongre
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by Dealgan12** [comment]
We have assigned to our Loc supplier to review

cc @Bernadette2022

**Comment by Bernadette2022** [comment]
This feedback  fixed.
