### ISSUE TITLE
getPane returns null instead of undefined

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4648]
The description for the method `getPane` is _Returns the pane corresponding to the input ID. If pane doesn't exist, undefined is returned._ The return value is `null`, not `undefined`.

This code fails:
```javascript
        const existingPane = Xrm.App.sidePanes.getPane(reference.Id);
        if (existingPane !== undefined) {
            existingPane.select();
            continue;
        }
``` 

This code works as expected:
```javascript
        const existingPane = Xrm.App.sidePanes.getPane(reference.Id);
        if (existingPane !== null) {
            existingPane.select();
            continue;
        }
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9e45cbb-17fa-138c-3364-f4d6b69512fd
* Version Independent ID: 8134beb8-9321-59bc-399b-f24ff75153ab
* Content: [sidePanes (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-app-sidepanes)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-app-sidepanes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-app-sidepanes.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@darshSWL 

Thanks again for your feedback.

But I'm not sure that the examples you provide prove the point. 

 - You aren't using [strict equality operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness)
 - You don't have code to catch when the pane doesn't exist.
 
 Looking at [Strict equality and undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined#strict_equality_and_undefined)
 
 I think a more convincing test would be this:
 
 ```
         const existingPane = Xrm.App.sidePanes.getPane(reference.Id);
        if (existingPane !=== undefined) {
            existingPane.select();
            continue;
        }
        else{
         console.log("There is no pane with id "+ reference.Id);
        }
 ```
 
 Can you confirm the behavior using strict equality operators?

**Comment by darshSWL** [comment]
I'm already using the strict equality operators.

This image is taken from the browser console and should prove the point without any additional custom javascript checks.

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/30015318/5edccad6-a812-4510-863d-65153f421ee1)

I'm only mentioning the return type, because the solution checker has a [use-strict-equality-operators](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/use-powerapps-checker#best-practice-rules-used-by-solution-checker) rule as best practice. That's why I would expected the correct return type in the documentation. I'd like to use the loose equality operator for undefined/null checks, but then I will get a "medium" warning in the solution checker results.

**Comment by JimDaly** [comment]
@darshSWL 

I'm sorry about that.  You are using [strict inequality operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_inequality), which should be the same result. Clearly, my JavaScript is rusty.

I'll get someone better versed in modern JavaScript to take a look.

**Comment by JimDaly** [comment]
Confirmed and fixed.
