### ISSUE TITLE
Deprecated feature - what then?

### ISSUE THREAD

**Issue by fonsell** [MicrosoftDocs/powerapps-docs#4656]
It would be beneficial to have guidance what to use if this documented feature is (going to be) deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b32a192-1de7-1c9d-3602-d6e732c8f7a6
* Version Independent ID: d0cb1601-9f48-5ef6-6919-ad3d4e9ee042
* Content: [Data export service (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/data-export-service)
* Content Source: [powerapps-docs/developer/data-platform/data-export-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/data-export-service.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by phecke** [comment]
@fonsell The information you are asking for is in the linked blog article. Is that not enough? The replacement is Azure Synapse Link for Dataverse.

**Comment by phecke** [comment]
@fonsell See above reply. Closing this issue.
