### ISSUE TITLE
SharedVariables only work across Plugin steps tied to the SAME message and entity

### ISSUE THREAD

**Issue by michaelmmcrae1** [MicrosoftDocs/powerapps-docs#4675]
This MS Docs page:
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/understand-the-data-context#shared-variables

Is missing critical information/context about SharedVariables. What's written heavily implies SharedVariables can be used and accessed by any Plugin at any time. Some caveat about when to use ParentContext.

But that's not the case at all that I've seen in practice. I've found SharedVariables only work for Plugin code that triggers off the SAME message/entity combo.

Example where it does NOT carry through:
Plugin A is triggered. It sets a SharedVariable "abc"=true. It gets a list of Accounts and Deletes them.
Plugin B is triggered by Delete of Account. It tries to read SharedVariable "abc" in the direct context or parentContext, but no "abc" can be found, it was not carried through.

Can you confirm this is the intended product behavior? If so the documentation must make this gap more clear.

Thank you for your time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4922340f-b68f-187f-8eab-6c9c065847b8
* Version Independent ID: f683b1c6-b4ef-d0f0-4bc0-f42b854a7d13
* Content: [Understand the execution context (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/understand-the-data-context#shared-variables)
* Content Source: [powerapps-docs/developer/data-platform/understand-the-data-context.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/understand-the-data-context.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @michaelmmcrae1. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@michaelmmcrae1 

Shared variable values are only available to plug-ins executing in the same event execution pipeline - meaning plug-ins registered on the same message/entity combination. They are part of the execution context which is specific to a pipeline and not available across execution pipelines.
