### ISSUE TITLE
Customize the editable grid control (Preview)

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4680]
The link [Customize the editable grid control (Preview)](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/customize-editable-grid-control) in the first paragraph is marked as preview. The linked page is not marked as preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 225f1305-7aea-3fdd-9a46-e0f258c670ff
* Version Independent ID: 225f1305-7aea-3fdd-9a46-e0f258c670ff
* Content: [Customized editable grid - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/sample-controls/customized-editable-grid-control#code)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/customized-editable-grid-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/sample-controls/customized-editable-grid-control.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@darshSWL 

Thanks for your feedback. 

I removed the `(Preview)` text from the link.
