### ISSUE TITLE
Bug in harness control on String format for demimal numbers

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/powerapps-docs#4688]
Hi Team,

The webpack mentioned [harnesswebpack] (https://learn.microsoft.com/en-us/power-apps/developer/component-framework/debugging-custom-controls#using-developer-tools-with-code-components) is having a FormatterUtils.js as mentioned below is having an invalid method usage.

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/49693916/0dc64e24-958e-4d0a-8a18-53dd00df561d)

<img width="309" alt="image" src="https://github.com/MicrosoftDocs/powerapps-docs/assets/49693916/506c412c-4fe3-448c-abad-c4efb929896f">

As you can see there is no method or property inside String object to make the return statement. Because of this we are not able to use negative numbers as input/output fields for PCF controls.

However the same is working properly after deployment. Not sure where to raise this one. Hence raising here.

Regards
Pavan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72e8bfe3-1fdf-56d7-caa1-1a0d31b149ea
* Version Independent ID: 5940a498-af09-d3e3-4987-7e2a03268305
* Content: [Debug code components - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/debugging-custom-controls)
* Content Source: [powerapps-docs/developer/component-framework/debugging-custom-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/debugging-custom-controls.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by pavansarma93** [comment]
@JimDaly @Nkrb @noazarur-microsoft : this is a major bug for harness control. Let me know if this is supposed to reported somewhere else

**Comment by JimDaly** [comment]
@pavansarma93 
Issues in this repo need to be related to the documentation. 
For this, you should contact technical support and report it.

**Comment by pavansarma93** [comment]
@JimDaly where would it be ? Is this a product support on MS Powerplatform or GitHub issue on some package ? Harness is part of [pcf-start](https://www.npmjs.com/package/pcf-start) however no repository mentioned to raise GitHub issues and documentation is redirected to MS Docs. 

Please guide.

**Comment by JimDaly** [comment]
Please use https://github.com/microsoft/powerplatform-build-tools/discussions to provide feedback on PAC CLI.
