### ISSUE TITLE
typo "datavases"

### ISSUE THREAD

**Issue by andrewviren** [MicrosoftDocs/powerapps-docs#4701]
Typo in this sentence with --strike-- and **replacement**

"The Access migration tool allows users to choose if they wish to export their Access databases directly into a solution. Access 
--datavases-- **databases** in solutions..."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0371ed0e-974c-5a94-0ba4-f7f1aee43deb
* Version Independent ID: 0371ed0e-974c-5a94-0ba4-f7f1aee43deb
* Content: [Migrate Microsoft Access data to Microsoft Dataverse (contains video) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/migrate-access-to-dataverse#migrating-access-databases-into-dataverse-solutions)
* Content Source: [powerapps-docs/maker/data-platform/migrate-access-to-dataverse.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/migrate-access-to-dataverse.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @andrewviren. This issue has been assigned to the doc author for review.

**Comment by KumarVivek** [comment]
Fixed; should be reflected shortly in the public site.
