### ISSUE TITLE
How to download Microsoft Power Apps single developer plan??

### ISSUE THREAD

**Issue by hhoque1790** [MicrosoftDocs/powerapps-docs#4706]
[Enter feedback here]
Websites are all slow to load. Instructions are unclear in given articles as to how to access Power Apps as a 
developer. Mentioned that no work account is needed to get Power Apps but apparently had to get one to get 
Microsoft Dynamic Sales to then get Power Apps. Even after getting a work account through Microsoft still 
CAN'T access Power Apps. Also, there is over-the-top-security in making a work account. Password length 
minimum was 15 characters which I will definitely forget in the near future. The recommended amount is usually 
8 characters. Overall very bad experience. Massive waste of time and have a thumping headache from dealing 
with this service.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9b93e14-db84-7fa2-01a2-c96740882aa2
* Version Independent ID: c9b93e14-db84-7fa2-01a2-c96740882aa2
* Content: [Sign in to Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/sign-in-to-power-apps#sign-in-using-microsoft-account-preview)
* Content Source: [powerapps-docs/maker/canvas-apps/sign-in-to-power-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/sign-in-to-power-apps.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @alaug
* Microsoft Alias: **alaug**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hhoque1790. This issue has been assigned to the doc author for review.
