### ISSUE TITLE
Typo in typescript remark

### ISSUE THREAD

**Issue by Drout** [MicrosoftDocs/powerapps-docs#4711]
This line in the typescript code is wrong:
 // Render the cell value in green when the value is blue than $100,000 and red otherwise

The correct text should be
 // Render the cell value in blue when the value is more than $100,000 and red otherwise

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 225f1305-7aea-3fdd-9a46-e0f258c670ff
* Version Independent ID: 225f1305-7aea-3fdd-9a46-e0f258c670ff
* Content: [Customized editable grid - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/sample-controls/customized-editable-grid-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/customized-editable-grid-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/sample-controls/customized-editable-grid-control.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by JimDaly** [comment]
@Drout 
Thanks for your feedback.
I've fixed this.
