### ISSUE TITLE
Set keep alive for HttpClient

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4714]
It is recommended to use HttpClient instead of the WebClient for new plugins. See https://learn.microsoft.com/en-us/power-apps/developer/data-platform/access-web-services#how-to-access-external-web-services

The next topic on the above linked page is Best practices, which links to [Set KeepAlive to false when interacting with external hosts in a plug-in](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/business-logic/set-keepalive-false-interacting-external-hosts-plugin)

That page does not show how to set keep alive for HttpClient, but for the WebClient and other possibilities to send requests.

Then there is the page [Set Timeout when making external calls in a plug-in](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/business-logic/set-timeout-for-external-calls-from-plug-ins)
On that page we can see how to set the keep alive for the HttpClient. Would it be possible to add this example to the page [Set KeepAlive to false when interacting with external hosts in a plug-in](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/business-logic/set-keepalive-false-interacting-external-hosts-plugin) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5d0f7db-45db-df08-7ca4-ae032450da15
* Version Independent ID: 7ba3256d-8240-8bda-8fd4-7ac001f6ae63
* Content: [Set KeepAlive to false when interacting with external hosts in a plug-in - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/business-logic/set-keepalive-false-interacting-external-hosts-plugin)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/business-logic/set-keepalive-false-interacting-external-hosts-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/best-practices/business-logic/set-keepalive-false-interacting-external-hosts-plugin.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@darshSWL Since this is standard .NET programming and not specific to Dataverse, we would not typically write a plug-in sample for it. However, from looking at the HttpClient .NET documentation, it looks like that property is surfaced in the handler. See SocketsHttpHandler.KeepAlivePingPolicy Property. I expect the HttpWebRequest just surfaces that property of the handler directly whereas HttpClient does not.

**Comment by phecke** [comment]
@darshSWL Also see the HttpClientHandler Class.
