### ISSUE TITLE
Edit

### ISSUE THREAD

**Issue by nstratton-srx** [MicrosoftDocs/powerapps-docs#4730]
I think that
RetrieveMultiple calls from different application display different results.
should be
RetrieveMultiple calls from different applications display different results.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b54cb800-4b48-efb9-4814-593e0fe5ec0c
* Version Independent ID: da105e17-7d8c-4970-38e8-31820eae2391
* Content: [Implement all types of queries when filtering results using PreOperation RetrieveMultiple - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/best-practices/business-logic/implement-all-types-of-queries-when-filtering-preoperation-retrievemultiple)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/business-logic/implement-all-types-of-queries-when-filtering-preoperation-retrievemultiple.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/best-practices/business-logic/implement-all-types-of-queries-when-filtering-preoperation-retrievemultiple.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nstratton-srx. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@nstratton-srx 

Thank you for helping make our docs better. 
I've applied this change.
