### ISSUE TITLE
Parameters are translated in german

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4734]
The first two parameters are translated to german. This should not be the case.

Current translation:

> immer: Die Daten werden immer beim Speichern gesendet.
> nie: Die Daten werden niemals beim Speichern gesendet. Wenn dieser Wert verwendet wird, kann die Spalte/die Spalten im Formular für dieses Attribut nicht bearbeitet werden.
> dirty: Standardverhalten. Die Daten werden beim Speichern gesendet, wenn sie geändert wurden.

Suggested translation:

> always: Die Daten werden immer beim Speichern gesendet.
> never: Die Daten werden niemals beim Speichern gesendet. Wenn dieser Wert verwendet wird, kann die Spalte/die Spalten im Formular für dieses Attribut nicht bearbeitet werden.
> dirty: Standardverhalten. Die Daten werden beim Speichern gesendet, wenn sie geändert wurden.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 3951c8a6-3e52-08a3-2563-77e327a43142
* Version Independent ID: d8110610-337e-ef59-a675-30d78cb739da
* Content: [setSubmitMode (Client API-Referenz) - Power Apps](https://learn.microsoft.com/de-de/power-apps/developer/model-driven-apps/clientapi/reference/attributes/setsubmitmode)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/setSubmitMode.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/setSubmitMode.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@darshSWL 
Thanks for calling this out.
I've updated the article so that `always`, `never`, and `dirty` are formatted as code elements. This should stop them from being localized.

**Comment by JimDaly** [comment]
Looks like this is fixed.
