### ISSUE TITLE
Translated parameters in german translation

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4739]
errorOptions parameters in en-us:
- **details**
- **errorCode**
- **message**

You must set either the **errorCode** or **message** value.

errorOptions parameters in de-de:
- **Details**
- **errorCode**
- **Meldung**

Sie müssen entweder den Wert **Fehlercode** oder **Meldung** festlegen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: ea3c9c94-1f26-c3a4-8789-3b0cef9f1e6b
* Version Independent ID: fe0311f8-20c5-5ddb-a618-2ead070afb80
* Content: [openErrorDialog (Client-API-Referenz) in modellgestützten Apps - Power Apps](https://learn.microsoft.com/de-de/power-apps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openerrordialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openErrorDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openErrorDialog.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@darshSWL 
Thanks again for your feedback.
There appears to be a pattern where these terms should be formatted as code, but were not.

Rather than:

- **details**
- **errorCode**
- **message**

They should be:

- `details`
- `errorCode`
- `message`

This way they won't get localized.
Looks like I need to scan the whole set of docs for this.

**Comment by JimDaly** [comment]
Applied changes in this PR to address this issue:
https://github.com/MicrosoftDocs/powerapps-docs-pr/pull/8696

**Comment by JimDaly** [comment]
The changes in the en-us content will be applied to other languages over time. 
Closing this.

**Comment by Bernadette2022** [comment]
@JimDaly  verified that these parameters reverted back to english since they are now in a code block.
