### ISSUE TITLE
Proper Encoding is mentioned but encoding type is not documented

### ISSUE THREAD

**Issue by seanmcne** [MicrosoftDocs/powerapps-docs#4741]
This article specifically warns the reader _"When you use the paging cookie with FetchXML, make sure that you use the correct encoding."_ however, it doesn't actually document what the proper encoding is (which I believe is uri encoding).  It would be helpful to readers of the article to specifically document what type of encoding to use to avoid errors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d867a76b-03c7-c4a3-313f-ee642b5f0bde
* Version Independent ID: 371fff7e-205d-4a9f-b790-5537d3113770
* Content: [Page large result sets with FetchXML (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/page-large-result-sets-with-fetchxml)
* Content Source: [powerapps-docs/developer/data-platform/org-service/page-large-result-sets-with-fetchxml.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/page-large-result-sets-with-fetchxml.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @seanmcne. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@seanmcne 
Thanks for your feedback. 
I've updated the current article to mention it needs to be XML encoded.
