### ISSUE TITLE
Postman guide doesn't work, I can't pass step 5 to get the User Auth.

### ISSUE THREAD

**Issue by eduardodfmex** [MicrosoftDocs/powerapps-docs#4744]
[Postman guide doesn't work; I can't pass step 5 to get the User Auth.]

I follow all the steps and create my auth configuration to point #5, when I click on the "Get New Access Token" the pop-up window asking for AD user auth came, I fill User and Password, but I never receive the token, the postman auth window can run for ever but the process never ends.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Set up a Postman environment (Microsoft Dataverse for Apps) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @eduardodfmex. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Contacted Eduardo offline.
