### ISSUE TITLE
FetchXml response changed the behaviour from 8 to 9 for linked entities attributes

### ISSUE THREAD

**Issue by MadalinaTomaD365** [MicrosoftDocs/powerapps-docs#476]
Hello team,

One of our customers reported a couple of weeks back the encoding for version 9.0 linked entities has changed the response while performing a fetch query against the organization Web API endpoint, in current version we will display the following for linked entities attributes Account.name while in the old version we had the following account_x002e_name

“ Note
Response of FetchXML queries containing link-entities and their attributes contains Unicode special characters such that '.' becomes '_x002e_' and '@' becomes '_x0040_'.
”
https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/mt607533(v=crm.8)#use-custom-fetchxml

For version 9.0 documentation we did not include that specific note and also the behaviour changed.

Our customer has integration with third party systems and those integrations do not work anymore as the symbol for linked entity fields changed.

Is it possible to explain to our customer in the existing documentation about the symbol change?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d385e93-d443-f848-05f6-bdcd6585a9d7
* Version Independent ID: c8fe3dc4-7155-9078-0cf2-383adfcdc6a4
* Content: [Retrieve and execute predefined queries (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/retrieve-and-execute-predefined-queries.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
There is a topic that is not present in the Table of contents:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/web-api-versions

The purpose of this topic is to cover different behavior in versions.
I recommend:
 - This topic be added to the table of contents so it is discoverable
 - This all differences in behavior between v8 & v9 be included here
 - https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/issues/244 also mentions this and another change.

This topic also states that there can be differences between minor versions - but I'm not aware any changes of this nature have occurred yet. If any are introduced, they should be covered here as well.

**Comment by susikka** [comment]
@MadalinaTomaD365 The differences between Web API for Dynamics 365 v8.*x* and v9.*x* are documented here: [Web API version specific differences](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/web-api-versions#web-api-version-specific-differences).

There it mentions that in FetchXML response for v8.*x*, '.' becomes 'x002e' and '@' becomes 'x0040'. This encoding for special characters is not present in response of FetchXML queries for v9.x release.

Closing this issue now.
