### ISSUE TITLE
Height not working per article, seems to always be the same size even if you update it to 200px for example.

### ISSUE THREAD

**Issue by jsdanie1** [MicrosoftDocs/powerapps-docs#4763]
When I configure a custom height like 200px instead of 120px, the form dialog doesn't appear to change. It seems to always stay the same size no matter what I call out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d991c0b4-ff31-84e2-4084-f2ef82d77588
* Version Independent ID: ad7a366f-8d17-82f5-ea6e-c5feee2545cf
* Content: [openAlertDialog (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openalertdialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openAlertDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openAlertDialog.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jsdanie1. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@jsdanie1 

Thanks for your feedback.

I believe the article is correct. Here is what I tested:

1. Open a model-driven app form
2. Open browser developer tools console
3. Use sample from article specifying height as 500

```JavaScript
var alertStrings = { confirmButtonLabel: "Yes", text: "This is an alert.", title: "Sample title" };
var alertOptions = { height: 500, width: 260 };
Xrm.Navigation.openAlertDialog(alertStrings, alertOptions).then(
    function (success) {
        console.log("Alert dialog closed");
    },
    function (error) {
        console.log(error.message);
    }
);
```

Result: It is taller.

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/6353736/a2e24b49-6b43-48c3-bbe0-75688f77d372)

Maybe don't use `px` when setting the value?

**Comment by jsdanie1** [comment]
I'm not using px, I basically copied and pasted the default script as well, left out button label and tried to adjust the height is all. 

```js
var alertStrings = {
    title: "Warning: Incorrect Quantity (Term)",
    text: "The term does not match minimum required term length on the product"
};
var alertOptions = { height: 250, width: 260 };
Xrm.Navigation.openAlertDialog(alertStrings, alertOptions).then(
    function (success) {
        formContext.data.entity.attributes.get('quantity').setValue(getTermRequired);
    },
    function (error) { console.log(error.message); }
);
```


![2023-09-26 20 24 49](https://github.com/MicrosoftDocs/powerapps-docs/assets/32203517/8dcb0f28-e2b3-4498-8daa-997efdaef244)


but now that I'm looking at it again, its not cut off like it use to. It seems coming back to this maybe cache or something cleared out and now its displaying the proper windows lol
