### ISSUE TITLE
Failure case not specified.

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#4764]
Please supply information on what this function does if the specified key is not present in the RESX file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8beea3a1-0b75-8b1a-cf5e-40dbcdd3dc02
* Version Independent ID: f2284eff-2afa-a63a-d8db-c151a90471e8
* Content: [getString (Power Apps component framework API reference) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/resources/getstring)
* Content Source: [powerapps-docs/developer/component-framework/reference/resources/getstring.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/resources/getstring.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @devlinl. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@devlinl 
Thanks for your feedback.

I expect that it should be one of these:

- **Best**: It throws an error such as key not found. 
- **Otherwise**: It will return null or an empty string. 

I hope that some kind of error is thrown.

If you have first-hand experience with this, we can update the docs with that. I'll get the dev team to review it.
Otherwise, I will ask for clarification from the dev team.

**Comment by devlinl** [comment]
I don't have first-hand experience... I came here to find out what it did so that I wouldn't have to deploy and debug our control just to find out.

Honeslty, I'm hoping it just returns null... that way we can just do something simple like `displayValue = context.resources.getString(key) ?? someDefaultString;`

I have asked the developer actually building the control if he knows what it does when the key is not present... I'll update this thread if I hear back from him before you get the answer.

**Comment by JimDaly** [comment]
@devlinl

Response from the dev team is:

> If the `id` parameter isn’t found, this method returns the `id` parameter value.

I'll update the article with this information.

**Comment by devlinl** [comment]
That's frustrating... I can see why they did it... they are using it for the Control Manifest, where you can either supply a key to a RESX file, or just put in whatever text you want... So they just call this method, and if it happens to be a key, they get a new value, but if not, they get the "default" value that the user supplied.

Good for static values in XML, but not great for developers working with dynamic content.

Now I basically have to put a bunch of these kinds of checks if I have something dynamic that may or may not be in the RESX:

`var localizedValue = context.resources.getString(key);`
`if (localizedValue === key)`
`    localizedValue = defaultValue;`

Anyway, thanks for the info.

**Comment by HemantGaur** [comment]
Many of the localization APIs use this pattern to be more resilient and enable incremental addition of the localization content. You can check for the specific language once and make a decision on if the localization exists or not. Not sure what is the usecase when some of the keys would have values ?
________________________________

**Comment by devlinl** [comment]
@HemantGaur, in our case, we are creating a control which will show data based on a configuration provided by the end-user. We don't know at design-time which specific fields/entities will be shown. For most items, we will pull the relevant Display Names from the system's metadata. However, visual real estate is limited in this particular control, and we are allowing users to optionally provide alternate "Short Names" for entities and fields that are specific to this control.

A common example would be shortening "Appointment" to "Appt". But just because the word "Appointment" is long in English, doesn't mean it is long in another language. For example, Arabic "موعد" is short enough not to need a shortened version. So the key "appointment_shortname" might exist in the english RESX file, but not in the Arabic one.

**Comment by HemantGaur** [comment]
Very specialized behavior I would say. One option can be adding a wrapper helper function to inform about the key -> value being the same.

Thanks,
Hemant
________________________________

**Comment by JimDaly** [comment]
I'm adding this note to the article:

> [!NOTE]
> If the `id` parameter doesn't match a given key associated with the specified resource (resx) defined in the manifest file, this method returns the `id` parameter value.
