### ISSUE TITLE
Configuration for Quick find section should be moved

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#477]
This random fact shouldn't be in this topic. It has nothing to do with Building queries with QueryExpression.
The Configuration for Quick find section should be moved into content for Model-driven app configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20495c2a-f987-dab0-3f75-3afab1ff72ea
* Version Independent ID: 586e0e80-33b0-ce49-b515-b718ea4507a7
* Content: [Build queries with QueryExpression (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/build-queries-with-queryexpression#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/build-queries-with-queryexpression.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/build-queries-with-queryexpression.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
There is a mention of Quick Find properties at the child topic: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/use-filterexpression-class#about-the-isquickfindfilter-property

**Comment by phecke** [comment]
@JimDaly There is no existing topic in model-driven app content where such info would be appropriate. If you feel strongly about this, then open a new issue.
