### ISSUE TITLE
Change in Prerequisites for using the Data Export Service

### ISSUE THREAD

**Issue by aaronkroontje** [MicrosoftDocs/powerapps-docs#478]
The SQL for database and schema permissions above was very helpful however there is now an additional DB permission required for the keyvault that had me scratching my head for a good while... VIEW DATABASE STATE

Without it, when trying to validate to the Data Export Service it will tell you that you have insufficient write privileges. 

Per:  https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/replicate-data-microsoft-azure-sql-database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b78e7a4-a539-c230-0a8c-454f1f69201a
* Version Independent ID: 777f3fea-cd80-9233-715f-4947cb1077f9
* Content: [Data export service (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/data-export-service#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/data-export-service.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/data-export-service.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@aaronkroontje Thanks for the info. Documentation updated.
