### ISSUE TITLE
How can I get the SDK templates in VS?

### ISSUE THREAD

**Issue by RickardNo** [MicrosoftDocs/powerapps-docs#479]
In the beginning of the tutorial you have CRM SDK Templates in the projects, where can I install these from? I've found some vsix file but it's for VS 2015 and not the required VS 2017

/Rickard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62e76f4-65f7-052a-79cb-d6381c7424f2
* Version Independent ID: 462fa6bc-8277-9b09-3516-52bdce21f8d3
* Content: [Use the XRM tooling common login control in your client applications (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-xrm-tooling-common-login-control-client-applications#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-xrm-tooling-common-login-control-client-applications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-xrm-tooling-common-login-control-client-applications.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@RickardNo Here is the link to download the template https://marketplace.visualstudio.com/items?itemName=DynamicsCRMPG.MicrosoftDynamicsCRMSDKTemplates. It should work with VS 2017 version too. But there is no newer version released version after this.

**Comment by Nkrb** [comment]
@RickardNo Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
