### ISSUE TITLE
Help File for Get-PowerApp

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#48]
the help file for get-powerapp has some problems, Example 3 and 4 show up multiple times. It looks like there might be an issue with formatting in the cmdlet file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
Closing given the age of this comment. Please reopen if this remains an issue.
