### ISSUE TITLE
Need to document limit on number of link entities in a fetch xml query

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#480]
There is a good forum post (from 2011) that describes this issue and has a response from a MSFT employee on the product team:
https://social.microsoft.com/Forums/en-US/b3978065-7215-4643-a9e8-e9b388f44814/limit-on-quantity-of-ltlinkentitygt-in-fetch-xml-is-10?forum=crm 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55426bf-e3ed-2d4f-d2e9-1edf60ebe6c6
* Version Independent ID: d26739ec-4b1e-77da-7ba3-fa87e7723300
* Content: [Use FetchXML to query data (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-fetchxml-construct-query)
* Content Source: [powerapps-docs/developer/common-data-service/use-fetchxml-construct-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-fetchxml-construct-query.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
This info has been added as a note in [Use FetchXML to query data](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-fetchxml-construct-query).

![image](https://user-images.githubusercontent.com/28051062/61930372-24944800-af9b-11e9-87a6-ba2660ca747c.png)

Closing this issue now.
