### ISSUE TITLE
Invalid code on page

### ISSUE THREAD

**Issue by dbdrivenadmin** [MicrosoftDocs/powerapps-docs#4807]
[Enter feedback here]
The code on this page does not name sense:

//For early bound types to work correctly, they have to be enabled on the proxy.  
_serviceProxy.EnableProxyTypes();  
AdventureWorksCycleServiceContext context = new AdventureWorksCycleServiceContext(_service);

I am not sure if _service or _serviceProxy is correct, but the code appears to be disconnected.  This is supposed to be on using an OrganizationServiceContext not OrganizationServiceContextProxy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5debe4e-24e5-358d-342b-1be662e42ede
* Version Independent ID: fcc82cd2-79a5-ea5a-2090-2e104be1cdad
* Content: [Use OrganizationServiceContext (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/organizationservicecontext)
* Content Source: [powerapps-docs/developer/data-platform/org-service/organizationservicecontext.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/organizationservicecontext.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dbdrivenadmin. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@dbdrivenadmin 

There is an organization service connection and an organization service context. You have to enable proxy types on the connection to use organization's strong-types in your code. The service context can use that connection that you enabled proxy types on.

So the code should read:

```
_service.EnableProxyTypes();  
AdventureWorksCycleServiceContext context = new AdventureWorksCycleServiceContext(_service);
```
Where _service is a service connection created using one of our clients such as `ServiceClient` or `CrmServiceClient`. Those clients implement `IOrganizationService` which `AdventureWorksCycleServiceContext` requires for initialization.

I will update the doc's code snippet. Thanks for the feedback.
