### ISSUE TITLE
poor phrasing

### ISSUE THREAD

**Issue by KittyDreadful** [MicrosoftDocs/powerapps-docs#4814]
"every other table" - this is a confusing phrase for non-native English speakers.  

It could be taken as every second table and is not clear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48a7a557-9e77-3981-e59d-aaf76dc05ea9
* Version Independent ID: 531ecc9e-c765-07fe-bea4-1b9ce9c2c9c0
* Content: [Customer tables (account, contact, customeraddress) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/customer-entities-account-contact)
* Content Source: [powerapps-docs/developer/data-platform/customer-entities-account-contact.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/customer-entities-account-contact.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mayadumesh
* Microsoft Alias: **mayadu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KittyDreadful. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@KittyDreadful Thanks for pointing that out. I will fix the doc language today.
