### ISSUE TITLE
Changed behaviour?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4817]
The (!) Note mentions, that unsaved data will be lost. 

I've used `setActiveProcess` today and it triggers a save. No changes were lost.
Is this a new feature of this method?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71065911-65c7-1464-97f9-d5c6a673c808
* Version Independent ID: 6573c9a2-6933-a8fe-eb70-a047990e3312
* Content: [setActiveProcess (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/activeprocess/setactiveprocess)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/activeprocess/setActiveProcess.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/activeprocess/setActiveProcess.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by JimDaly** [comment]
I've not heard of any intentional changes to the behavior here.

@HemantGaur  How about you?

I recommend that you try this in isolation from any other customizations and make sure that the save isn't triggered by something else.

If it still happens: It isn't aligned with the documented behavior, it would be a bug. You should contact technical support.

**Comment by darshSWL** [comment]
It also happens in an other environment on a form without other customizations.

I'm not available next week, so I'll contact support later.

**Comment by JimDaly** [comment]
I don't see anything actionable for documentation here. Closing.
