### ISSUE TITLE
language specific Dataverse search api

### ISSUE THREAD

**Issue by SweetsNSavories** [MicrosoftDocs/powerapps-docs#4819]
Given multi language Dataverse org with Knowledge Articles published in all selected languages, how do we search KA specific to a language via Dataverse Search API i.e., how do i use filter params to restrict search to a language.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2524b4fe-020f-5067-97c9-2cf440281838
* Version Independent ID: 134dc37f-d1cf-7c65-b1cd-aadeb4463acd
* Content: [Search across table data using Dataverse search - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/relevance-search)
* Content Source: [powerapps-docs/developer/data-platform/webapi/relevance-search.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/relevance-search.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @mspilde
* Microsoft Alias: **mspilde**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SweetsNSavories. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@SweetsNSavories 

Can you clarify which table you want to search?

There are two tables that appear to contain knowledge articles:

- [Article (KbArticle) table/entity reference (Microsoft Dataverse) - Power Apps | Microsoft Learn](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/kbarticle)
- [KnowledgeArticle table/entity reference (Microsoft Dataverse) - Power Apps | Microsoft Learn](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/knowledgearticle)

But both seem to have a separate record for each language, and the language is stored in one of the columns:

- ⁠[KbArticle.LanguageCode](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/kbarticle#BKMK_LanguageCode)
- ⁠[KnowledgeArticle.LanguageLocaleId](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/knowledgearticle#BKMK_LanguageLocaleId)

These are [LCID values](https://learn.microsoft.com/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a): For example, English is 1033, and Japanese is 1041.

So, I think you need to filter based on the respective value. Is that your question? Or are you asking how to filter by that column value?

**Comment by SweetsNSavories** [comment]
Its for knowledgearticl entity, how do we add languagelocaleid in the filter clause make it succeed. currently it throws an error

POST /api/search/v1.0/query/
Body
{
  "returntotalrecordcount": true,
  "entities": [ "knowledgearticle" ],
  "orderby": [ "@search.score desc" ],
  "filter": "knowledgearticle:(description ne null and statecode eq 3)",
  "searchtype": "full",
  "search": "test string for search"
}

**Comment by SweetsNSavories** [comment]
with the  knowledgearticle:(description ne null and statecode eq 3 and languagelocaleid eq 1033) it returns zero results. the language filter appears to work l in advanced find D365 app, However the implementation tried out here is Dataverse search api , which does not appear to be supporting multilanguage search properly. In fact it appears to be not able to search non-latin languages like arabic but able to pickup a language a spanish, when tested without having mentioned languaglocaleid filter.

**Comment by AnimeshAngrish** [comment]
@SweetsNSavories we do not support <EntityName>: <AttributeName> pattern. Can you try JSON like below with just the attribute name. Also as pointed out by Jim above please make sure attribute's metadata property is set IsFilterable=True using Quick Find View.

{
"returntotalrecordcount": true,
"entities": [ "knowledgearticle" ],
"orderby": [ "@search.score desc" ],
"filter": "description ne null and statecode eq 3 and languagelocaleid eq 1033",
"searchtype": "full",
"search": "test string for search"
}

**Comment by SweetsNSavories** [comment]
this is how it worked, We had to mention the entityname: but subsequesnt filter conditions should not be wrapped in parenthesis  as given in this search api documentation, however languagelocaleid is a guid inside knowledgearticle and it had to be of small case , thanks this can be archived
{
  "returntotalrecordcount": "true",
  "entities": [
    "knowledgearticle"
  ],
  "filter": "knowledgearticle:statecode eq 3 and languagelocaleid eq 'd026c011-4c03-4bfd-93d7-017f480ed54d'",
  "searchtype": "full",
  "search": "आप यात्रा करना चाहते"
}

**Comment by SweetsNSavories** [comment]
this is how it worked, We had to mention the entityname: but subsequesnt filter conditions should not be wrapped in parenthesis as given in this search api documentation, however languagelocaleid is a guid inside knowledgearticle and it had to be of small case , thanks this can be archived
{
"returntotalrecordcount": "true",
"entities": [
"knowledgearticle"
],
"filter": "knowledgearticle:statecode eq 3 and languagelocaleid eq 'd026c011-4c03-4bfd-93d7-017f480ed54d'",
"searchtype": "full",
"search": "आप यात्रा करना चाहते"
}

**Comment by JimDaly** [comment]
Is there anything actionable here?

You say:

> ...but subsequesnt filter conditions should not be wrapped in parenthesis as given in this search api documentation,

In [filter=[string] (optional)](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/knowledgearticle#BKMK_LanguageLocaleId)

Our example is:

```
POST [Organization URI]/api/search/v1.0/query
{  
  "search": "maria",

  "filter": "account: modifiedon ge 2020-04-27T00:00:00,
    activities: regardingobjecttypecode eq 'account', 
    annotation: objecttypecode eq 'account',
    incident: (prioritycode eq 1 or prioritycode eq 2)"
}
```

I think the example that uses parentheses is to demonstrate using `or`.

Is there something we should change here?

**Comment by SweetsNSavories** [comment]
I do not think any thing needs a change here in the documentation..

**Comment by JimDaly** [comment]
Thanks
