### ISSUE TITLE
Invalid feature listing

### ISSUE THREAD

**Issue by AlexAddison** [MicrosoftDocs/powerapps-docs#482]
The following section no longer works due to changes in the current version of the program. 

3. Click Data in the Properties tab in the options panel on the right.

4. Under Fields, enable the Attachments field. The Attachments field associated with the SharePoint list will appear in the form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e663e437-2bc9-980f-9ba6-6eeab01ee9a4
* Version Independent ID: ae7da14b-2234-2815-9fd1-272a0984f129
* Content: [Attachments control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-attachments#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-attachments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-attachments.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by bkpearson** [comment]
How does the Reset property work with this control? Default is false

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content is updated to reflect updated behavior. Please allow some time to reflect changes.
