### ISSUE TITLE
Missing windowOptions = { openInNewWindow: true };

### ISSUE THREAD

**Issue by easybeat** [MicrosoftDocs/powerapps-docs#4825]
Hi

in sample 4 you missing to pass windowOptions (const windowOptions = { openInNewWindow: true };

Without this the quick create form does not open but the normal main form opens.

cheers

Beat

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: b204ee0a-69a2-e52d-f110-2291be66c1af
* Version Independent ID: 8ac980df-6b5f-2b33-707f-11efb597ba6a
* Content: [openForm (Client-API-Referenz) in modellgestützten Apps - Power Apps](https://learn.microsoft.com/de-de/power-apps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openform)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @easybeat. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@easybeat 
Thanks for your feedback.

If I understand you correctly, you are saying that [Example 4: Open a quick create form](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openform#example-4-open-a-quick-create-form) does not actually open a quick create form. Is that right?

I note that the English description for the `entityFormOptions.openInNewWindow` property says: 

> Indicates whether to display form in a new window or a new tab. If you specify true and do not specify values for height or width, the form will display in a new tab. Opening a form in a new window or a new tab makes the rendering of the form slow compared to opening the form on the same tab; consider opening a form in the main form dialog instead. This property is currently not supported for Quick Create forms, as they can not be opened in a new window or tab.

Note the last line:

>This property is currently not supported for Quick Create forms, as they can not be opened in a new window or tab.

Therefore, why would someone add the `entityFormOptions.openInNewWindow` property values?

Yet, without this data, you are telling us it doesn't open the quick create form even when the `entityFormOptions.useQuickCreateForm` is true. Is that right?

Can you repro this behavior consistently?

**Comment by Bernadette2022** [comment]
The translation seems to be consistent with the English content, hence not a localization issue. Looks like the feedback is for the English content.  @jimdaly should this be assign to you

**Comment by easybeat** [comment]
Hi,
sorry my mistake. I did tests again and it works without entityFormOptions.openInNewWindow.

I close this issue.

Thanks for your help.

Kind regards
