### ISSUE TITLE
Clarification about usage of Xrm.Navigation or Xrm.Utility in HTML WebResources

### ISSUE THREAD

**Issue by neronotte** [MicrosoftDocs/powerapps-docs#4827]
Hello,
I've seen in a previously resolved issue that deprecation of ClientGlobalContext.js.aspx has been posponed (warning is no longer present [in the HTML WebResource article](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/webpage-html-web-resources).

In [this other article](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx?WT.mc_id=BA-MVP-5004107) it is stated that ClientGlobalContext.js.aspx can be referenced to get access to the `GetGlobalContext()` function and [its returned value](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext).

What's the right approach to follow if we have the need of using one of the Xrm.Navigation, Xrm.Utility, or Xrm.WebApi objects in our custom webresources?

Example scenario: I want to create a custom home page as an HTML WebResource, that shows in a box, a set of news, a custom diagram aggregating a few info on the opportunities assigned to the current user, and some more stuff.
Security Model of the objects shown in the webresource (news, opportunities...) is managed via standard dynamics security model.
I need to execute queries against the system to get the data in the context of the current user, I need to be able to call custom actions from that page, and I need to be able to navigate to a given news/opportunity record from within the Home Page (perhaps opening the record form on the side of the current page). Moreover I want to be able to use that page in mobile offline.

All that stuff is quite easy to do using plain old Dynamics CRM 2013 WebResources. With the current, supported, features, what's the correct approach to achieve that goal?

**Comment by JimDaly** [comment]
@neronotte 
Sorry for the delay in responding. Feedback system works best when you use the Feedback button at the bottom of an article. This connects the issue to a specific article and assigns the author of the article. 

Regarding your question: Please look at [Mobile offline capabilities and limitations](https://learn.microsoft.com/power-apps/mobile/offline-capabilities#limitations). Seems like there are quite a lot of limitations with web resources while working offline.

With all the investment in PCF component framework, I think that is a better approach than web resources.
