### ISSUE TITLE
Select() in a data card

### ISSUE THREAD

**Issue by codepounder** [MicrosoftDocs/powerapps-docs#483]
Does the Select() function not work within a data card of a form? I understand that it can't cross the boundaries of a container, but I'm finding that selecting one button in a card cannot fire the OnSelect of another button in the same card container. Is this not supported or is it a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582a8f8d-1f70-b2f8-cdcd-2c4f03b82ca8
* Version Independent ID: b8dbb751-54db-efbb-0de3-ed5d006c0d97
* Content: [Select function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-select)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-select.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-select.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Ballzer0** [comment]
It would be really cool if you could use this with a ForAll to click all buttons in a gallery that meets a condition. Would be really powerful for bulk update tasks

**Comment by harp365** [comment]
I would second this as a bug as I have found that it can work when a button calls the select of another button once and then it will not work again in design studio but then I stumbled on this moved the level of some of the buttons and it worked again. This is not great as it means an app that was in a working situation, now no longer is and you will only know about it when you come to edit.

**Comment by gregli-msft** [comment]
I was unable to replicate this issue - I could create two buttons within a data card and have one Select the other without a problem, both when authoring and in the iOS player.  We did recently make some changes to the Select function that may have impacted the behavior.  Please try again and let me know if there is still an issue here.

For the comment about selecting controls within a Gallery with ForAll, [check out the enhancements to Select that allow for this](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-select#syntax).
