### ISSUE TITLE
More explanation around Team Administrator

### ISSUE THREAD

**Issue by lambeaulady** [MicrosoftDocs/powerapps-docs#4830]
I want the Administrator of a Team to be able to add and remove members, do they have to be a member of the Team? That seems to be the only way I have found that works.
Documentation needs to be updated for this use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e79dc75-29c6-2f8b-1860-1110fc2e6fbf
* Version Independent ID: 8992a69b-30d7-222b-41ee-06ccd0aba949
* Content: [Use access teams and owner teams to collaborate and share information (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information)
* Content Source: [powerapps-docs/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-access-teams-owner-teams-collaborate-share-information.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lambeaulady. This issue has been assigned to the doc author for review.

**Comment by paulliew** [comment]
The administrator field is called out in this doc https://learn.microsoft.com/en-us/power-platform/admin/manage-teams 

Note

The Administrator field is only for reference and it doesn't have any special processing. You can use this field to restrict who can add and remove team members by registering a [plug-in](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/plug-ins) on the [associate and disassociate](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/associate-disassociate-entities-using-web-api) APIs for the teammembership_association relationship. These actions can be enforced when the user is the administrator of the team. For more information, see the community [sample code](https://community.dynamics.com/crm/b/mylifemicrosoftdynamiccrm/posts/ms-dynamics-crm-associate-disassociate-message-plugin).

**Comment by phecke** [comment]
@lambeaulady As your issue has been responded to by Paul, I am closing this issue.
