### ISSUE TITLE
Did not see any data in the Sample App

### ISSUE THREAD

**Issue by thegongben** [MicrosoftDocs/powerapps-docs#484]
The flow run failed with the error "badrequest". When I played the app, I did not see any data. It did not allow me to do anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @yijw2017
* Microsoft Alias: **yijw**

**Comment by thegongben** [comment]
Never mind. I made a mistake: I forgot to create some new expense report and line items! Once I did that, now I see the data!
Thank you.

**Comment by KumarVivek** [comment]
Closing the issue as this is resolved.
