### ISSUE TITLE
To debug,Clicking on debug button/replay plug in execuetion button doesn't open any window. tried with multiple nuget packages of Plugin reg tool

### ISSUE THREAD

**Issue by Kaviarasi** [MicrosoftDocs/powerapps-docs#485]
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-debug-plug-in#debug-your-plug-in 
To debug,Clicking on debug button/replay plug in execuetion button doesn't open any window. tried with multiple nuget packages of Plugin reg tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ea8845-2c70-6649-dbc6-247df34bc40c
* Version Independent ID: 1a61874a-6698-5e53-5e46-923aa8b550ff
* Content: [Tutorial: Debug a plug-in (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/tutorial-debug-plug-in#debug-your-plug-in)
* Content Source: [powerapps-docs/developer/common-data-service/tutorial-debug-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/tutorial-debug-plug-in.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by MOHAMMEDFAKHRI** [comment]
Hi i am facing the same issue. UPDATE DEBUG buttons not reponding on the latest versions on the PRT downloaded through the NUGET

**Comment by JimDaly** [comment]
I just tested this with the latest version downloaded from NuGet (9.0.0.9503)
All the steps in the tutorial worked as expected. I cannot repro what you report.

If you are still experiencing this issue, recommend you go to [https://admin.powerplatform.microsoft.com/support](https://admin.powerplatform.microsoft.com/support) to open a support request.

**Comment by MOHAMMEDFAKHRI** [comment]
Hi It worked after clearing out the tools cache.
