### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/powerapps-docs#486]
What permission do you need to call this api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e24482-2754-9237-6c76-9d8683b74b9b
* Version Independent ID: 0c19232c-4c8a-d962-f700-4225c3782ae2
* Content: [Create and update entity definitions using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/create-update-entity-definitions-using-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/create-update-entity-definitions-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/create-update-entity-definitions-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
@Ballzer0 You should be able to use the entity definitions Web API request like any other Web API request. Please try following the steps mentioned in [Setup a Postman environment](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/setup-postman-environment) to use Postman to execute the Entity definitions requests.

Closing this issue now. Please reopen if this does not solve your problem.
