### ISSUE TITLE
Support of "virtual" components in Power Pages portals

### ISSUE THREAD

**Issue by jsnl85** [MicrosoftDocs/powerapps-docs#4862]
I believe "virtual" components with "React controls & platform libraries" ARE supported in Power Pages portals.
I've been using it so far with no issues.

The section "Q: Can I use React controls & platform libraries with portals?" seems to say otherwise.
https://learn.microsoft.com/en-us/power-apps/developer/component-framework/react-controls-platform-libraries#q-can-i-use-react-controls--platform-libraries-with-portals

Is this page up-to-date?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e32fb155-ff17-ca62-1aae-e58b5101a155
* Version Independent ID: e32fb155-ff17-ca62-1aae-e58b5101a155
* Content: [React controls & platform libraries (Preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/react-controls-platform-libraries#q-can-i-use-react-controls--platform-libraries-with-portals)
* Content Source: [powerapps-docs/developer/component-framework/react-controls-platform-libraries.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/react-controls-platform-libraries.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jsnl85. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@HemantGaur 
Any comment about this?
[Q: Can I use React controls & platform libraries with portals?](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/react-controls-platform-libraries#q-can-i-use-react-controls--platform-libraries-with-portals)

> A: No. React controls & platform libraries are currently only available for canvas and model-driven apps.

The article hasn't been updated since last February.

**Comment by JimDaly** [comment]
@jsnl85 

I checked with the dev team and updated the page. It now says this:

> ### Q: Can I use React controls & platform libraries with Power Pages?
> 
> A: No. React controls & platform libraries are currently only supported for canvas and model-driven apps. In Power Pages, React controls don't update based on changes in other fields.

While they are 'available', they aren't supported.
