### ISSUE TITLE
I would like to use the graph API from Power Automate to interact with Outlook 365

### ISSUE THREAD

**Issue by torevor** [MicrosoftDocs/powerapps-docs#4866]
It's kind of funny how there are about 5000 versions of THIS partially complete information on the internet (and MULTIPLE copies on Microsoft sites), but there is none, that go into depth on the individual settings, or simply explains in pain English how a reasonably technical person using Power Automate who needs to write to the Microsoft Graph to interact with Outlook (for example).

You write all this software, the marketers are out there trying to sell it, but it's like no one cares if customers can actually figure out how to use these things.  Perhaps this seems petty, but keep in mind we are SIMULTANEOUSLY trying to figure out hundreds of other things that are changing each day.  Having ONE person at Microsoft putting a little bit more effort into actually useful documentation would save millions of dollars of wasted time among your customers, and it would perhaps reduce the likelihood of the non-trivial number of people like me who trash Azure in technical forums like Hacker News every single time someone is asking for advice - I think your company should be punished for your laziness.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11caa291-2e98-ac3a-d5d1-ecd416b93bdf
* Version Independent ID: 4f30cddd-8849-1887-ada0-a83a3d2a0027
* Content: [Tutorial: Register an app with Microsoft Entra ID (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/walkthrough-register-app-azure-active-directory)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @paulliew
* Microsoft Alias: **paulliew**

**Comment by phecke** [comment]
@torevor Our Dataverse developer documentation does not cover that specific scenario. However, I will forward your issue to our Power Automate writer for consideration.

You can also file a new GitHub issue on the Power Automate documentation yourself.

Thank you for the feedback.
