### ISSUE TITLE
Name of "AAD User" virtual table...

### ISSUE THREAD

**Issue by leekester** [MicrosoftDocs/powerapps-docs#4871]
Hi,

It looks like the table has been renamed as "Microsoft Entra Identity" within dataverse. Would you be able to update the docs/screenshots to reflect please?

Thanks,

Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc2e3627-c28e-9baa-61f6-6353b52f81a4
* Version Independent ID: bc2e3627-c28e-9baa-61f6-6353b52f81a4
* Content: [Azure Active Directory user (AADUser) table (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/aaduser-entity)
* Content Source: [powerapps-docs/developer/data-platform/aaduser-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/aaduser-entity.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by phecke** [comment]
@leekester We have updated our documentation to reflect the new name "Microsoft Entra ID" except for the one article you pointed out. the name AADuser refers to Azure Active Directory user table (the old anme) so we are keeping the content as is for now. However, we did add a note about the name change. Thanks for the feedback.
