### ISSUE TITLE
Canvas App field Component 

### ISSUE THREAD

**Issue by randolphnz** [MicrosoftDocs/powerapps-docs#4875]
Hi there,

Is able to have a tutorial how to apply field PCF control to Canvas App?

Currently we have a field PCF control working against a text field in Model-driven App.

However, it's showing 'error loading control' when we apply the same control to Canvas App.

Any suggestion will be appreciated.

Regards,
Randy 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5338bf6-f6c2-fcf9-394f-e30871437de3
* Version Independent ID: 03fed979-b86f-d08b-d0ee-3b83b39c0966
* Content: [Create a model-driven app field component in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/tutorial-create-model-driven-field-component?tabs=before)
* Content Source: [powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/tutorial-create-model-driven-field-component.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @randolphnz. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@randolphnz 
We have a tutorial about a canvas _dataset_ component:[Tutorial: Creating a canvas app dataset component](https://learn.microsoft.com/power-apps/developer/component-framework/tutorial-create-canvas-dataset-component).

We do not have a similar _field_ component tutorial for canvas apps like we do for model-driven apps: [Tutorial: Creating a model-driven app field component](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/tutorial-create-model-driven-field-component).

The ask is for parity between field and dataset component tutorials with both canvas and model-driven apps.
I understand you feel this will help you better understand the error you are getting.

@HemantGaur  &  @kaushikkaul 

Do we have any canvas field components that would be good foundation for a tutorial?

**Comment by JimDaly** [comment]
@randolphnz 

Information I received is that field components are very similar between model and canvas, so a separate tutorial isn't a high priority.

Regarding the generic 'error loading control'. The recommendation is to add a try/catch block in your `init`/`updateView `methods to catch and log any errors before they get thrown to the framework.

I'll look to add this to the existing tutorial.
