### ISSUE TITLE
Xrm.Navigation.openWebResource window position property missing

### ISSUE THREAD

**Issue by amnajalal** [MicrosoftDocs/powerapps-docs#488]
Currently there is no option to open html webresource in the center of the screen. windowOptions only have height and width available. By default it opens in the corner of the screen. Kindly provide the position option too, it is already there for Xrm.Navigation.openForm() as 1:center 2:side. It should be available for Xrm.Navigation.openWebResource too.
![popup](https://user-images.githubusercontent.com/20602679/60398946-6f2acc00-9b77-11e9-956c-3c39d81656f6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef001b56-f366-7866-693b-c403f84dbab3
* Version Independent ID: e3d1fbdc-84a5-ce3c-af1e-11e98b14418f
* Content: [openWebResource (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.

**Comment by sudipmandal** [comment]
A workaround for this would be to add the following JS in header section of the web resource being loaded
This would re-position the webresource window position to the center of the screen immediately after it is opened.

window.top.moveTo((screen.width / 2) - (window.self.innerWidth/2),(screen.height / 2)-(window.self.innerHeight/2));
