### ISSUE TITLE
Add quotation 

### ISSUE THREAD

**Issue by AbdulWahabWarind** [MicrosoftDocs/powerapps-docs#489]
Add quotation (;) in GUID of an example 1.
quotation is missing in this line: entityFormOptions["entityId"] = "8DA6E5B9-88DF-E311-B8E5-6C3BE5A8B200";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b204ee0a-69a2-e52d-f110-2291be66c1af
* Version Independent ID: 8ac980df-6b5f-2b33-707f-11efb597ba6a
* Content: [openForm (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by dplotnikov** [comment]
Hi @AbdulWahabWarind I've made a pull request with a suggested updated and it will be live as soon as @KumarVivek will merge it into master branch

**Comment by Nkrb** [comment]
@AbdulWahabWarind Thanks for the feedback. We have updated our docs and published it live. Closing the issue.
