### ISSUE TITLE
Typo mistake appeares instead of appears

### ISSUE THREAD

**Issue by yernaidu** [MicrosoftDocs/powerapps-docs#49]
Dear Team,
typo mistake correction in the section, 'Administration of PowerApps' and sub heading 'Why has the PowerApps icon appeared in the Office 365 app launcher?'

Microsoft PowerApps is a fundamental part of the Office 365 suite and is enabled as a service as a part of existing Office 365 SKU's. As users everywhere in the world can now use Microsoft PowerApps, it appeares in 'All apps' in the app launcher screen. See Licensing overview to understand which Office 365 SKUs now include PowerApps.

URL: https://docs.microsoft.com/en-us/powerapps/administrator/signup-question-and-answer

Topic heading: Manage PowerApps licenses in your organization
With my best regards,
Yernaidu Chalumuri.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f579a8f8-188d-1a39-becc-f4548da6aae6
* Version Independent ID: 5f8f561e-9bce-e0ae-450d-aaa04665b9e6
* Content: [Manage licenses in your organization - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/signup-question-and-answer)
* Content Source: [powerapps-docs/administrator/signup-question-and-answer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/signup-question-and-answer.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
Fixed and took to live via my working branch.
