### ISSUE TITLE
Clarification on user credentials used

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/powerapps-docs#490]
I believe the SQL Server connector creates a connection that caches the user accounts provided when the account is setup.  If that is correct, this is UNLIKE the other commonly used connectors such as SharePoint and OneDrive which the PowerApps user must authorize the first time they run the app and THUS end up being the user account used for authentication via the (ShPt/OneDrive) connector.  In other words, please note on this page that the SQL Connector will impersonate the user account provided when a Connection is created FOR ALL USERS WHO USE AN APP THAT LEVERAGES A SQL SERVER CONNECTOR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbcbf308-e9b9-d59d-5b1b-ba224dcc1aa9
* Version Independent ID: 5959353c-ab28-1bc6-8c21-3b186c1bf61d
* Content: [Overview of the SQL Server connection - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-azure-sqldatabase#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-azure-sqldatabase.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-azure-sqldatabase.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. You can read more about sharing resources & connections at [share app resources - connections](https://docs.microsoft.com/powerapps/maker/canvas-apps/share-app-resources#connections) section.
