### ISSUE TITLE
Transport of a Dynamics CRM solution containing embedded PowerApps controls between different environments

### ISSUE THREAD

**Issue by fmarto** [MicrosoftDocs/powerapps-docs#491]
In a solution of our Dynamics CRM DEV environment I embedded a PowerApp canvas using a subgrid on the form of the account entity.
If I export this solution and import it in our TEST environment, what will happen?
Do I have to change something to make it work in TEST?
If yes, will the version in DEV still work as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d72044c0-7486-402e-4ad0-cd488f6356e0
* Version Independent ID: 3b762213-c234-14b3-7f11-cde507cced78
* Content: [Add an embedded canvas app on a model-driven form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-add-classic-designer#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-add-classic-designer.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by iangpgh** [comment]
in-progress

**Comment by iangpgh** [comment]
@fmarto Let me know if you were you not able to resolve these questions. If you have additional or further questions, open a new issue.

**Comment by iangpgh** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue. To contact Support, https://powerapps.microsoft.com/support/

**Comment by iangpgh** [comment]
@Mattp123 - Closes #491
