### ISSUE TITLE
Filtering doesnot work on Mobile App & UCI

### ISSUE THREAD

**Issue by awadbensaleh** [MicrosoftDocs/powerapps-docs#492]
[Enter feedback here]

Hi team,

Xrm.Utility.lookupObjects(lookupOptions).then(successCallback, errorCallback) filtering doesnot work on Mobile App / Model Driven Power Apps & UCI. it works well on the normal CRM. Specially if does not work on the n :n relationship  when we apply the filter on the Add Existing lookup. 

Thanks  &Regards,
Awad.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Sagar486** [comment]
Hi,

How do we hide the link (+New) to create a new record. We need to restrict the user from creating a new record when the lookup window is opened.

Thanks,
Sag

**Comment by JamesHorsley** [comment]
@Sagar486 from https://butenko.pro/2017/11/22/microsoft-dynamics-365-v9-0-lookupobjects-closer-look/ it looks like there is a showNew boolean propertry that can be set in the lookupOptions

**Comment by Nkrb** [comment]
@awadbensaleh Filtering property should work on UCI too. I am closing this issue. If you need further help, please reopen the issue or open a new issue.
