### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#4920]
This link leads to a 404 page:

"You can enable [Dataverse search](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/relevance-search) on email descriptions to search email descriptions."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a85f605d-b018-72d0-5316-8d6e5056d9ca
* Version Independent ID: b1a95941-e2f4-ea50-d79b-f951209957aa
* Content: [Email activity tables (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/email-activity-entities)
* Content Source: [powerapps-docs/developer/data-platform/email-activity-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/email-activity-entities.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @DanaMartens
* Microsoft Alias: **dmartens**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@darshSWL Thanks for pointing this out. The link will be fixed sometime today.
