### ISSUE TITLE
AssignedTo list

### ISSUE THREAD

**Issue by Brian-704** [MicrosoftDocs/powerapps-docs#493]
The assign to dropdown is fed from the SP list. The list column is a "Person" field. I have that column set to use the group owners. There are three owners, but nothing shows in the dropdown. Is there a way to check to see if the list is populated? Can I just make that a choice field and set the technician names there instead?

**Comment by Brian-704** [comment]
I just tried to add myself in the "Assigned to column of the sharepoint list. It found me, but then gave an error:
Your organization's policies don't allow you to share with these users. 
Also - in the app the "Update" button is disabled even after I make changes
Maybe this will help in trouble shooting.

**Comment by phecke** [comment]
@Brian-704 Sorry to hear about your trouble with the PowerApps software. We maintain the documentation for PowerApps. If there is a problem with the documentation, let us know. Otherwise, you should contact your PowerApps support representative. Thanks.

**Comment by Brian-704** [comment]
Unfortunately I'm the PowerApps rep!
I'm not sure if the documentation is wrong or not. But it seems that the Help desk powerapp may be lacking a critical component. The "Assign to" field picks from anyone in the organization. I can't imagine any scenario where that would be desired. I have been unable to find a way to limit that field to the small group of people that would be responding to the issues. Wouldn't it make more sense to treat that field more the "Admin" list? The problem I'm having trying to reverse engineer that solution is that a record is expected in that field. I tried using the owners of the list as the group of people, but evidently that is not supported in Powerapps.

**Comment by yijw2017** [comment]
Hi @Brian-704,
    I have checked the formula for AssignedTo in EditTicketScreen:
**If(Not(IsBlank(EditTicketScreenAssignedToSearchInput.Text)),Office365Users.SearchUser({searchTerm:EditTicketScreenAssignedToSearchInput.Text}))** 

    As you have said above, the AssignedTo field is populated with the name you search within your organization. I believe the intent is to make it as generic as possible in case some orgs want to use this template want it that way.

    You definitely have the freedom to make AssignedTo list a dropdown sourcing from an "Admin" list you define in App OnStart or even from any data connections (SharePoint List or Excel file on OneDrive, etc.). If that's the type of customization your version of app need, then suggestion could be changing it to a dropdown list to replace the current input field and delete the gallery showing the search result, if the list has a very limited personnel.

    Thank you.
