### ISSUE TITLE
4 moderate severity vulnerabilities in the latest pcf-start 1.11.3

### ISSUE THREAD

**Issue by keijiinoue** [MicrosoftDocs/powerapps-docs#4936]
[Enter feedback here]
There are 4 moderate severity vulnerabilities in the latest pcf-start 1.11.3.
```bash
$ npm audit report
# npm audit report

axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix`
node_modules/axios
  localtunnel  >=1.9.0
  Depends on vulnerable versions of axios
  node_modules/localtunnel
    browser-sync  >=2.24.0-rc1
    Depends on vulnerable versions of localtunnel
    node_modules/browser-sync
      pcf-start  >=1.11.3
      Depends on vulnerable versions of browser-sync
      node_modules/pcf-start

4 moderate severity vulnerabilities
```

Please address it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4b9e58-d9d3-c387-fe6a-258ebe78516d
* Version Independent ID: 22d89b45-e427-1ab9-b456-7d7750585b52
* Content: [Create and build a code component - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/create-custom-controls-using-pcf)
* Content Source: [powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/create-custom-controls-using-pcf.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @keijiinoue. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@keijiinoue 
Thanks for your feedback. I don't think we can address this via documentation, so I've looped you in with some other MSFT folks to discuss via email. Closing this.
