### ISSUE TITLE
More information needed for web exceptions

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#494]
If the error is due to a failed call from an external web call, a developer could use a try/catch with WebException and check the status returned. If it is a re-tryable error, they may try again.
But, if they get a WebException, they should not include it as the inner exception with InvalidPluginExecutionException  because that exception type is not serializeable, so the error data doesn't match the actual error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd08e90-9746-075f-d2af-15c11da72f26
* Version Independent ID: 4e666a00-98c8-dcc2-e90f-7cc4c8d0b6d9
* Content: [Use InvalidPluginExecutionException in plug-ins and workflow activities - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/business-logic/use-invalidpluginexecutionexception-plugin-workflow-activities)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/business-logic/use-invalidpluginexecutionexception-plugin-workflow-activities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/business-logic/use-invalidpluginexecutionexception-plugin-workflow-activities.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment]
@JimDaly WebException is now serializable.
