### ISSUE TITLE
Sample code error

### ISSUE THREAD

**Issue by jrg999999** [MicrosoftDocs/powerapps-docs#4942]
Section: Use the IOrganizationService interface methods
4. Replace the Main method in your program with this:
 The code sample includes the line: 
`WhoAmIExample(service: serviceClient);`
This should be:
`WhoAmIExample(service);`
or
`WhoAmIExample(service: service);`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8916bbc-6834-44e1-1354-92ba60eacd0c
* Version Independent ID: ce53ff38-bf6a-9659-5834-aca6a7446cdd
* Content: [Quickstart: Execute an SDK for .NET request (C#) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-gb/power-apps/developer/data-platform/org-service/quick-start-org-service-console-app)
* Content Source: [powerapps-docs/developer/data-platform/org-service/quick-start-org-service-console-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/quick-start-org-service-console-app.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by JimDaly** [comment]
@jrg999999 
Thanks for letting us know.
I've fixed this.
