### ISSUE TITLE
Discrepancy in parameter name

### ISSUE THREAD

**Issue by skovlund** [MicrosoftDocs/powerapps-docs#4943]
The syntax calls the third parameter `closeCallback` but in the parameter list it is called `successCallback`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d991c0b4-ff31-84e2-4084-f2ef82d77588
* Version Independent ID: ad7a366f-8d17-82f5-ea6e-c5feee2545cf
* Content: [openAlertDialog (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openalertdialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openAlertDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openAlertDialog.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @skovlund. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@skovlund 
Thanks for letting us know.
I made it consistent by using `successCallback` in both places.
