### ISSUE TITLE
Is the dependent assembly capability feature GA? Difference between English and German documentation

### ISSUE THREAD

**Issue by ckl-bso** [MicrosoftDocs/powerapps-docs#4953]
The [English version of this document](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/build-and-package) does not mention any preview state concerning the dependent assembly capability.

In the [German documentation](https://learn.microsoft.com/de-de/power-apps/developer/data-platform/dependent-assembly-plugins) another article located under a different url still lists this as a preview functionality.

The release wave documentation wasn't updated concerning a GA date.

Which information is valid? Is this still a preview feature and not properly marked, or is the German documentation outdated on that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 648b28bc-55c8-91a4-0c5b-f942db4eaeb8
* Version Independent ID: 648b28bc-55c8-91a4-0c5b-f942db4eaeb8
* Content: [Build and package plug-in code - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/build-and-package)
* Content Source: [powerapps-docs/developer/data-platform/build-and-package.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/build-and-package.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ckl-bso. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@ckl-bso 

There is some delay in localizing the English source content into other languages. You can expect that the German content will reflect the changes soon.

**Comment by ckl-bso** [comment]
It looks that at least the page structure was updated in the meantime, but the translation is still not available.

I didn't find any hint concerning the GA state of this feature as neither the documentation does include that, nor the latest release wave documentation, which includes this feature, was updated https://learn.microsoft.com/en-us/power-platform/release-plan/2023wave1/data-platform/include-dependent-assemblies-plug-ins. 

Is this feature GA?

**Comment by JimDaly** [comment]
It is. 
I understand that @divkamath will publish a blog post for a more visible announcement.
