### ISSUE TITLE
VS2022 Arm64 support for the Power Platform Tools

### ISSUE THREAD

**Issue by mbertrand2023** [MicrosoftDocs/powerapps-docs#4959]
Hello, I am on a Mac with Apple Silicon and Windows 11 installed via Parallels.  When I attempted to install the power platform tools for D365 Finance and Operations development purposes, it failed due to incompatible VS22 versioning.  When I looked into the logs, it appears only AMD64 is supported by this tool and I am on Arm64.  Anyway to add support for Arm64 support soon?

This is where I downloaded the tools from:
https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatformToolsVS2022

This is the guide i'm following for local x++ development setup:
https://learn.microsoft.com/en-us/power-platform/developer/unified-experience/finance-operations-install-config-tools

Thanks,
Matt Bertrand
Asurion

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e62a44ee-80f5-ed50-eb2f-b56877aa5979
* Version Independent ID: 98af6033-4378-88a9-0a1d-c878d37fc3e3
* Content: [Quickstart: Create a plug-in using Power Platform Tools - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/tools/devtools-create-plugin#providing-tool-feedback)
* Content Source: [powerapps-docs/developer/data-platform/tools/devtools-create-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tools/devtools-create-plugin.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mbertrand2023. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@mbertrand2023 I will ask the product team.

**Comment by phecke** [comment]
@mbertrand2023  The product team has a work item for Arm64 support in the Power Platform Tools extension. However, the required Arm64 device support in Visual Studio 2022 is not available at this time.
