### ISSUE TITLE
Provide more details about how this compares to ExecuteMultiple

### ISSUE THREAD

**Issue by altmank** [MicrosoftDocs/powerapps-docs#4962]
Can you please provide more details about how these new bulk operations function in contrast to ExecuteMultiple? I'd like to make decisions about when to use which but the details are sparse on how these two approaches to executing messages in bulk compare to each other. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 239d0af2-9299-6eb1-6dfd-17232545898d
* Version Independent ID: 239d0af2-9299-6eb1-6dfd-17232545898d
* Content: [Use bulk operation messages - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/bulk-operations?tabs=sdk#on-error-behavior)
* Content Source: [powerapps-docs/developer/data-platform/bulk-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/bulk-operations.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @altmank. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@altmank 

Does this article provide the information you are looking for [Optimize performance for bulk operations](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/optimize-performance-create-update)

It is included in the **See Also** section at the bottom of the doc, but we could raise the visibility of it and included a section near the top for better discoverability, as long as it provides the kind of information you are looking for.

Looking forward to your response.

**Comment by altmank** [comment]
@JimDaly Thanks Jim for linking that. After reading it, I would infer the new bulk operations are expected to perform better than ExecuteMultiple, but it doesn't really say that explicitly. 

It also doesn't really tell me anything about expected performance gains of the new bulk operation apis vs execute multiple, but if that is super variable, I could understand why that might be omitted. That rollback on error in standard tables is generally a problem for our use cases, so I was looking to see if there were any benchmarks or notes about performance to help me understand if it was really that much better than ExecuteMultiple to justify that trade-off.

**Comment by JimDaly** [comment]
There are a lot of factors, so there isn't an easily reproducible set of benchmarks to publish. There is a lot of variability in environment resourcing which makes a big difference. The production environment for an enterprise level deployment will have a lot more resources that can be use, especially with parallel requests. 

We don't want to give people the idea that this solves all performance problems. These APIs have their own challenges, especially when dealing with imperfect data that could cause errors. But they can have significant benefit, and with elastic tables in particular, the difference can be quite dramatic.

And if you have plug-ins on individual operations, which is the norm today, you won't get maximum throughput.

We have C# sample code that includes different projects that you can configure and modify to compare results. See [Sample: SDK for .NET Use bulk operations](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/create-update-multiple) and [Sample: Web API Use bulk operations](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/samples/create-update-multiple)

From a documentation standpoint, I can add a section and link to the [Optimize performance for bulk operations](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/optimize-performance-create-update) article to guide people to the larger issue of deciding which approach to use.

**Comment by altmank** [comment]
Thanks @JimDaly !
