### ISSUE TITLE
Add explanation for the differences between Execute multiple and Create Multiple or Update Multiple

### ISSUE THREAD

**Issue by pavanmanideep** [MicrosoftDocs/powerapps-docs#4964]
Hi Team,

Please add explanation on how Create Multiple/Update Multiple can handle and how it was different than adding the create requests to execute multiple which everyone is doing currently. 

Thank you for your input in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 239d0af2-9299-6eb1-6dfd-17232545898d
* Version Independent ID: 239d0af2-9299-6eb1-6dfd-17232545898d
* Content: [Use bulk operation messages - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/bulk-operations?tabs=sdk)
* Content Source: [powerapps-docs/developer/data-platform/bulk-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/bulk-operations.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pavanmanideep. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
I added this note near the top of the article


> [!NOTE]
> For guidance about options when performing bulk operations, such when to use these APIs compared to batch APIs like `ExecuteMultiple`, see [Optimize performance for bulk operations](optimize-performance-create-update.md).
