### ISSUE TITLE
When using "Download" the file in question is opened in a new tab

### ISSUE THREAD

**Issue by Arefu** [MicrosoftDocs/powerapps-docs#497]
I've tried using the Download a function to download a Word document from a OneDrive and it opens the link in a new tab, I thought this may be because the link used to get the document is the view link not the direct file link, I tried using a hosted file's direct link and it still opened it in a new tab instead of prompting to save.

I've tried this in Chrome and Edge with the same result

**Comment by phecke** [comment]
@Arefu Can you please provide the URL to the PowerApps documentation that you are following for this download issue?

**Comment by Arefu** [comment]
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-param

**Comment by phecke** [comment]
@Arefu I forwarded your comment to the topic's author for review.

**Comment by Arefu** [comment]
Thanks @phecke we shall see when he chimed in what is going on 👍

**Comment by Arefu** [comment]
One week later, I have more grays and less answers.

Is there any hope for an update?

**Comment by Arefu** [comment]
Talk about fast escalation..

**Comment by tapanm-MSFT** [comment]
@Arefu Thank you for reaching out for help and apologies for delayed response. When *OneDrive document link* is used with **Download()** function, the document by default opens in the Word online. Hence, the file opens in a new tab. To get a link for download, use the **Details** option in OneDrive for the given Word document and then from **Details** pane, copy/use the **Path** link. **Path** link is for a direct document and not a Word online link that lets you download the file without opening in new tab. **Please note that this is not a canvas app feature but rather, OneDrive behavior for Office documents.** If you still have additional issues, please feel free to raise a [support service request](https://support.office.com/home/contact?contactUsExperienceEntryPointAssetId=S.HP.onedrive) for technical assistance.
