### ISSUE TITLE
Using Elastic Tables with Power Automate

### ISSUE THREAD

**Issue by hamzaanjum** [MicrosoftDocs/powerapps-docs#4976]
Please also add a section about how to use the queries with Power Automate.
When I am try to update using Power Automate, all my data vanishes altogether.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 430deb7b-cad7-a516-222d-d3507b6912b9
* Version Independent ID: 430deb7b-cad7-a516-222d-d3507b6912b9
* Content: [Use elastic tables using code (preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-elastic-tables?tabs=sdk)
* Content Source: [powerapps-docs/developer/data-platform/use-elastic-tables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-elastic-tables.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hamzaanjum. This issue has been assigned to the doc author for review.
