### ISSUE TITLE
Make it possible to find information about change tracking on this page

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#498]
This topic should include a prominent link or mention to discover this: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-change-tracking-synchronize-data-external-systems

That concept is about querying data and getting the delta of changes between each query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
Added a new section on how to [Use change tracking to synchronize data with external systems](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#use-change-tracking-to-synchronize-data-with-external-systems) in **Query data** topic.

Closing this issue now.
