### ISSUE TITLE
Need examples

### ISSUE THREAD

**Issue by MajorPatrickW** [MicrosoftDocs/powerapps-docs#4982]
I'm new to PCF controls and need to fire off the UpdateView, but having all kinds of trouble getting it to work.  I understand requestRender can be used, but without examples, I'm scrambling the internet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5569219f-3a3c-6b62-1bbf-2a61988ec7e2
* Version Independent ID: 6f5d57c9-0555-413a-18c9-7d7fbe22c425
* Content: [requestRender (Power Apps component framework API reference) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/factory/requestrender)
* Content Source: [powerapps-docs/developer/component-framework/reference/factory/requestrender.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/factory/requestrender.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MajorPatrickW. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@MajorPatrickW 

Thanks for your feedback.

Does your comment apply specifically to the `context.factory.requestRender()` method? Or are you looking for more examples in general?

There are a lot of APIs, so we can't provide examples for all. But we can target those which would benefit most.

We have many [sample components](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/use-sample-components) on GitHub that you can look at for examples. But I searched the repo and couldn't find any use the `requestRender` method.

**Comment by JimDaly** [comment]
The `context.factory.requestRender()` method is pretty straightforward. It doesn't return a value or take any parameters. Not clear about what kind of sample would help here.

Closing b/c I don't see anything actionable here.
