### ISSUE TITLE
Deep Insert Sample returns Error

### ISSUE THREAD

**Issue by DeanD84** [MicrosoftDocs/powerapps-docs#4988]
After copy and pasting the sample ODATA / WEB API request for a deep insert it works fine.

When doing deep inserts on elastic tables I get the below error. I am not sure if this is an elastic table limitation or a different error,

{"error":{"code":"0x80040265","message":"Cannot create related entities. Create has to be called individually for each entity."}}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a78e7ae-d181-4bf5-3257-6ab4f9fecca8
* Version Independent ID: dedf3b5a-6f2d-95c2-0dc8-7ccfe7ef1e3f
* Content: [Web API basic operations sample (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-basic-operations-sample)
* Content Source: [powerapps-docs/developer/data-platform/webapi/web-api-basic-operations-sample.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/web-api-basic-operations-sample.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DeanD84. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@DeanD84 
Thanks for your feedback. 
This sample code was written to use _standard_ tables. Elastic tables are a preview feature at the moment.

For standard tables our documentation is here; [Create related table rows in one operation](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-entity-web-api#create-related-table-rows-in-one-operation)

[Elastic tables documentation](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/elastic-tables) doesn't call out this limitation. Will assign this issue to Elastic tables team.

**Comment by JimDaly** [comment]
[Elastic tables for developers](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/elastic-tables) now says:

> Elastic tables don't support deep insert as standard tables do. You will get this error: `Cannot create related entities. Create has to be called individually for each entity`.

[Web API Create related table rows in one operation](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-entity-web-api#create-related-table-rows-in-one-operation) now says:

>With standard tables, you can create entities related to each other by defining them as navigation properties values. This pattern is known as deep insert.

[ SDK Create related entities in one operation](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/entity-operations-create?tabs=late#create-related-entities-in-one-operation) now says:

> For standard tables, when you create a new table row, you can also create related rows in the same operation. This is called deep insert.
