### ISSUE TITLE
Common Data Model IP Protection

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#50]
I am contemplating building IP based on CDS. This message "By choosing Create instance, you agree Microsoft can use entity and field names that you create (but not content in the database tables) to help improve our common data model. These names may be stored in our diagnostic systems and copied across regions. Learn more" caused me to pause a bit and I was wondering if you can help with understanding how we protect our IP on CDS. It seems like we are assigning a right to MS to use our IP in future products? Is this applicable only to the definition of the data entries? What about the associated business logic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7beb8fea-5fe3-ecf5-1c63-505c697cf20f
* Version Independent ID: 3c413776-1458-a725-d868-a9c63f849cec
* Content: [Create a Common Data Service (CDS) for Apps database - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/create-database)
* Content Source: [powerapps-docs/administrator/create-database.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/create-database.md)
* Service: **powerapps**
* GitHub Login: @manasmams
* Microsoft Alias: **manasma**

**Comment by jimholtz** [comment]
@gregdegruy 
Sorry for the delay. I just had this topic feedback assigned to me. If this is still an issue, please let me know and I'll reopen.

**Comment by gregdegruy** [comment]
@jimholtz no worries and yes it is and any feedback you can share here would be very helpful.
