### ISSUE TITLE
securityRolePrivileges is undefined

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#500]
userSettings.securityRoles works, but userSettings.securityRolePrivileges is undefined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999537e5-d7fd-6e16-207a-b7c7c31fdc9e
* Version Independent ID: 48ac9b62-a8b5-3bab-11b5-c0bbc5fde88c
* Content: [getGlobalContext.userSettings (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings#securityroleprivileges)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/userSettings.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@devlinl Xrm.Utility.getGlobalContext.userSettings.securityRolePrivileges method only works on UCI. 
I have verified that the method return array of strings that represent the GUID values of each of the security role privilege that the user is associated with or any teams that the user is associated with.

**Comment by devlinl** [comment]
@Nkrb, Ok, yes, I was probably looking for this in the old interface. Since that's going away, I suppose this is not an issue anymore.
