### ISSUE TITLE
Components added to form do not display

### ISSUE THREAD

**Issue by jazmatician** [MicrosoftDocs/powerapps-docs#501]
Built custom component & solution, installed in crm online sandbox, but when I add it to the form & selct the "Web" (or even all three) platform to display it, the original UI still displays.
To make sure this wasn't something in what I was doing, I tried adding an "OOTB" custom field (LinearSlider), and it doesn't display either. Is there something that needs to be done to make the components display on the form?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34647a0-dfdf-23da-c656-158a1eae14f9
* Version Independent ID: e2a795ee-c8ba-b757-194b-19ecf4b6d398
* Content: [Add Custom Components to a field or entity - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/add-custom-controls-to-a-field-or-entity)
* Content Source: [powerapps-docs/developer/component-framework/add-custom-controls-to-a-field-or-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/add-custom-controls-to-a-field-or-entity.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by S00083446** [comment]
Did you save & Publish both your form changes and your Solution changes.  I had this issuer where it did not display straight away

**Comment by S00083446** [comment]
Also ensure you are adding the control to a field on the '**Main**' form.

**Comment by jazmatician** [comment]
I publish the solution when I import and I've published and republished the
form (where is my long-promised "save and publish" button?).
There's only one main form, the other forms are the mobile and quick-add
forms.

**Comment by S00083446** [comment]
Yes I understand, it's frustrating. I had the exact same issue. Trying to remember how I fixed it.  I can try help if you want to forward on your instance details.

**Comment by Nkrb** [comment]
@jazmatician If you are still facing the issue with displaying the component on the form, raise your concern in the community forum [here](https://powerusers.microsoft.com/t5/Professional-Developer-Tooling/bd-p/pa_component_framework), development team will help you solving the issue. Closing the issue
