### ISSUE TITLE
Updated Instructions

### ISSUE THREAD

**Issue by jsdanie1** [MicrosoftDocs/powerapps-docs#5012]
Visual Code 2022 is considerably different looking now. Would be nice if instructions showed updated screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad2eb047-525a-63b7-2d6e-1536a374d688
* Version Independent ID: 2b8e3e9d-c957-d43e-ceeb-c75da0857d2d
* Content: [Tutorial: Write and register a plug-in (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/tutorial-write-plug-in)
* Content Source: [powerapps-docs/developer/data-platform/tutorial-write-plug-in.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/tutorial-write-plug-in.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jsdanie1. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@jsdanie1 Yes, thanks for pointing that out. I will get to work on updating the screenshots.
