### ISSUE TITLE
Is there a Similar Example for Lead Qualify

### ISSUE THREAD

**Issue by jsdanie1** [MicrosoftDocs/powerapps-docs#5014]
Is there an example of this but for LeadQualify? I can't seem to find anything that supports this in the Microsoft Learn Doc. Alot of older articles back from 2016 supposedly show this working using Xrm.Web.Api.online.excute but I can't seem to find anything for the newer Dynamics.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: badde453-a02f-72e1-22dd-3be9ed53a4c0
* Version Independent ID: 1904f78b-93c7-86f8-d6f2-96c4e6041f11
* Content: [Xrm.WebApi.online.execute (Client API reference) in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online/execute)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jsdanie1. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@jsdanie1 
Thanks for your feedback.

`QualifyLead` is not an action provided by Dataverse. It is only available if you have the Dynamics 365 for sales module installed. We won't add an example for that action here. Any examples should be part of the [Developer Guide for Dynamics 365 Sales](https://learn.microsoft.com/en-us/dynamics365/sales/developer/developer-guide) content.  I only find an SDK example there [Sample: Qualify a lead](https://learn.microsoft.com/en-us/dynamics365/sales/developer/sample-qualify-lead)

The key point of the documentation here is to understand how to use the **execute** method and pass parameters to invoke any Dataverse Function or Action. To do this, you need to understand how to call the action. 

See these articles for general information about using the Dataverse Web API to call an action:

- [Web API Action definitions](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/web-api-actions)
- [Using Web API actions](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/use-web-api-actions)

Having this knowledge will help in the long run. But for something easier, I recommend you try this [Dataverse REST Builder](https://www.xrmtoolbox.com/plugins/GuidoPreite.DRB/). It will generate code for you.  This is recommended in this forum post [Create request object to call an action with Xrm.WebApi from Javascript](https://community.dynamics.com/forums/thread/details/?threadid=ec30f349-2e00-4df2-a653-84e5148c82de)
