### ISSUE TITLE
Modification to live docs page publish-app-appsource

### ISSUE THREAD

**Issue by dustindonahue** [MicrosoftDocs/powerapps-docs#502]
Hi,

Please modify the https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/publish-app-appsource.md page which will modify the https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/publish-app-appsource with the attached changes which are highlighted. 

[publish-app-appsource.docx](https://github.com/MicrosoftDocs/powerapps-docs/files/3370468/publish-app-appsource.docx)

Please let me know if this isn't the correct way to ask for modifications or if I can email direct. Our team will have a good number of modifications to docs.microsoft.com pages coming up. 

Thank you,
Dustin

**Comment by dustindonahue** [comment]
Hello, can you provide an ETA on this edit please?

**Comment by phecke** [comment]
@dustindonahue I can help with this change.

**Comment by phecke** [comment]
Completed.
