### ISSUE TITLE
 formula columns have limitations when using Power Apps in Browser with German language

### ISSUE THREAD

**Issue by olli4711** [MicrosoftDocs/powerapps-docs#5037]
working in a browser with German language I am not able to create a formula column that references another formula column.
with English language settings it works.
Microsoft Alias: owende

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6f7d49a-1fb0-ffba-779d-9c8b6d055d15
* Version Independent ID: d6f7d49a-1fb0-ffba-779d-9c8b6d055d15
* Content: [Work with Dataverse formula columns - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/formula-columns?tabs=type-or-paste#formula-column-usage-in-rollup-fields)
* Content Source: [powerapps-docs/maker/data-platform/formula-columns.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/formula-columns.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @sanjeevgoyalmsft
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @olli4711. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Responded via email.
