### ISSUE TITLE
Modification to live docs page next-steps-submit-app-cloud-partner-portal

### ISSUE THREAD

**Issue by dustindonahue** [MicrosoftDocs/powerapps-docs#504]
Hi,

Can you modify the page with the attached modifications which are highlighted yellow in the Word document?

I am hoping you can modify the page name as well replacing the Cloud Partner portal with Partner Center as modified in the document. I would also like to keep the existing URL with an auto redirect to the new page if possible. 

[next-steps-submit-app-cloud-partner-portal.docx](https://github.com/MicrosoftDocs/powerapps-docs/files/3370496/next-steps-submit-app-cloud-partner-portal.docx)

Thank you,
Dustin

**Comment by dustindonahue** [comment]
Hi can you provide an ETA on this edit please?

**Comment by phecke** [comment]
@dustindonahue Sorry for the delay. I just saw your issue. I can help with this change.

**Comment by phecke** [comment]
Done.
