### ISSUE TITLE
Known issue -  Error using Array data with Web API

### ISSUE THREAD

**Issue by wanyu3966** [MicrosoftDocs/powerapps-docs#5044]
Any workaround or ETA for this to be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2cf1411-6789-cd07-2676-290fdbeb6946
* Version Independent ID: f2cf1411-6789-cd07-2676-290fdbeb6946
* Content: [Use open types with custom APIs - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-open-types?tabs=sdk)
* Content Source: [powerapps-docs/developer/data-platform/use-open-types.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-open-types.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @wanyu3966. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@wanyu3966 
Unfortunately, no workaround or ETA.
I pinged the dev that this bug is assigned to and added a link to this issue.

**Comment by tims205** [comment]
Would be great to get some info on this issue, the custom closed types pattern is proving to be really useful.
