### ISSUE TITLE
Minor error in the provided sample code 'IsMessageAvailable' method

### ISSUE THREAD

**Issue by vaibhav21791** [MicrosoftDocs/powerapps-docs#5045]
[Enter feedback here]

I would like to bring to your attention a minor error in the provided sample code used to check message availability for any entity. 

QueryExpression is missing in the instantiation of this class. 

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/8400108/7e186a7b-d45a-449d-bdc6-088303ea01cc)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 239d0af2-9299-6eb1-6dfd-17232545898d
* Version Independent ID: 239d0af2-9299-6eb1-6dfd-17232545898d
* Content: [Use bulk operation messages - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/bulk-operations?tabs=sdk#availability)
* Content Source: [powerapps-docs/developer/data-platform/bulk-operations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/bulk-operations.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vaibhav21791. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@vaibhav21791 
Thanks for your feedback.

This sample code is using .NET 6.0, with C# 9.0 which means we can use [Target-typed new expressions](https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new)

This is recommended style: [Simplify new expression (IDE0090)](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0090)

I understand this won't work in a plug-in, which is limited to .NET Framework 4.6.2, but we want to keep our samples up-to-date with .NET.
