### ISSUE TITLE
Is there any plan for Not yet available features?

### ISSUE THREAD

**Issue by KannanVenkat20** [MicrosoftDocs/powerapps-docs#505]
It would be great if the future plan for not yet available features can be published in this page. Or even a link to the future road map or status of the progress if it is already in plan/implementation.

I am looking for the following feature "Change the height of all rows" in data table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94785ec1-e3da-4ff2-59b6-19bd28bb8680
* Version Independent ID: 4b3e4efa-1d15-2a71-fe61-ee949c54279c
* Content: [Data table control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-data-table#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-data-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-data-table.md)
* Service: **powerapps**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by VFXpro** [comment]
How do you manage you backlogs?  3 years ago, select multiple rows, etc... are still not completed :(

Not yet available
Customize the styling of individual columns.
Add a Data table control in a form control.
Change the height of all rows.
Show images in a Data table control.
Show fields from related entities.
Use built-in functionality to filter and sort data by column heading.
Add a Data table control in a Gallery control.
Edit data in the Data table control.
Select multiple rows.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out with your feedback and feature asks. Please review the feature updates and release plans at https://docs.microsoft.com/dynamics365/release-plans/. For feature ideas, please submit or vote for feature asks at https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas.
