### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by mherzog01** [MicrosoftDocs/powerapps-docs#506]
This page refers to the settings "Scale to fit" and "Lock Aspect Ratio".  These are no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by neversleepz** [comment]
@mherzog01 
I still see "Scale to fit" and "Lock Aspect Ratio" in the application settings in the powerapps builder.
![image](https://user-images.githubusercontent.com/1033439/70469959-26ac0d00-1b1e-11ea-8e3b-5e75dda6073a.png)
Could this be closed?

**Comment by mherzog01** [comment]
A screen shot shows these setting in Advanced Settings, whereas the screen shot above has them in a different heading.  Are these not different?
![image](https://user-images.githubusercontent.com/51552337/70564277-de144400-1b5d-11ea-9da9-ffa638fdcc11.png)

**Comment by neversleepz** [comment]
I think I see where the confusion is.

The top of the doc says that these settings live in File -> App Settings -> Screen Size + Orientation, which happens to have a subheading 'Advanced Settings'.

But you can see from the previous screenshot that there is also a File -> App Settings -> Advanced Settings, which is a different set of settings to do with delegation and experimental powerapps features.  

The use of Advanced Settings in two places itself is confusing, but this doc itself references the two areas distinctly (eg later on it mentions about going to File -> App Settings -> Advanced' to switch on the component feature

**Comment by mherzog01** [comment]
Yes, makes sense.  Thanks for all your work and clear explanations on this.  You can close the issue.
