### ISSUE TITLE
Exceptionally poor documentation

### ISSUE THREAD

**Issue by nikirikitiki** [MicrosoftDocs/powerapps-docs#5068]
Besides the fact the Canvas App are unstable and has an abysmal implementation, there is zero proper documentation.

The parts that are documented are done in a poor manner with no real clarity, no proper screenshots and circular references.

An example is the implementation of the components. Any respectable framework is based on the components and their interaction. It is my great pleasure, to tell you that your MS team messed up the whole implementation. 

This technology is suitable for Excel users at best, and 20 years working in the same company analyst at worst.

0 out of 10 stars. The worst! If not for the circumstances, I would never, in a millennia, use PA.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9376d7b7-981d-44ec-66d7-efb2c3d512d4
* Version Independent ID: 9376d7b7-981d-44ec-66d7-efb2c3d512d4
* Content: [Canvas component properties (experimental) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/component-properties)
* Content Source: [powerapps-docs/maker/canvas-apps/component-properties.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/component-properties.md)
* Service: **powerapps**
* Sub-service: **canvas-developer**
* GitHub Login: @jorisdg
* Microsoft Alias: **jorisde**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nikirikitiki. This issue has been assigned to the doc author for review.

**Comment by jorisdg** [comment]
Thanks for your feedback.
Once components go into preview and the UI is settled we will consider adding screenshots.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nikirikitiki. This issue has been assigned to the doc author for review.
