### ISSUE TITLE
Automated low code plugin not triggered when automatic email record is created

### ISSUE THREAD

**Issue by gon1099** [MicrosoftDocs/powerapps-docs#5072]
Using Collect i am trying to create case record using automated low code plugin from email, if the incoming email created automatically it should create Case record automatically. In my case this process of creating Case is not working, but if I creating the Email record manually in the D365 it is working. 
This is my setup. 
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/142960859/b4e1de85-fd49-4756-b395-61e100fe020f)

**Comment by gon1099** [comment]
This is my sample setup. 
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/142960859/295bfda6-4768-4d10-8b7b-3d09768e3ffe)

**Comment by phecke** [comment]
@gon1099 Sorry, but we do not provide support here. Issues filed here are for problems or suggested improvements with our documentation.

You can try to contact MS Support or post your question in a Power Apps forum.
