### ISSUE TITLE
I agree incomplete documentation 

### ISSUE THREAD

**Issue by fxvn78** [MicrosoftDocs/powerapps-docs#508]
Trying to use the combo box as a people picker but there is no information on how to do this. After figuring out, I need to manually set the items to property, I am able to set the display properties which is not even listed in the documentation.  Then there's an undocumented property call searchText that is needed in order for this to work as a people picker. Also for unknown reasons there is now "value" property in the advanced property pane so I am not sure if that is in error or expected when using the people picker.
Also a main problem in using the people picker is that there may be multiple email entries for a given display name.  Once I pick one there seems to be no way to show in the selected text which entry (by email address was selected).  This page and/or control should be updated to properly reflect the properties especially when being used as a people picker. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8bf3d3-12e3-5b55-8713-221cf5f5a30c
* Version Independent ID: 5a050d01-6ef6-97d6-07de-d5cac82dea06
* Content: [Combo box control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-combo-box)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-combo-box.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-combo-box.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. We're in the process of updating documentation soon.
