### ISSUE TITLE
Typo and Unclear Sentence.

### ISSUE THREAD

**Issue by Nobodyworld** [MicrosoftDocs/powerapps-docs#5082]
Unclear: "As a step towards achieving this goal, **[it}** possible to add Power BI reports and datasets as components in Power Apps solutions."

Suggested Correction assuming **[it is]**:
"As a step towards achieving this goal, it is possible to add Power BI reports and datasets as components in Power Apps solutions."

I could also mention my hesitation with "towards" vs "toward", but as a preview it makes more sense. After reconfirming it is somewhat arbitrary to argue the 's', I would still reconsider, at least as a fun exercise, the use of a plural singular adverb. As an example, I would not say, "I took a step 'ups' the stairs." To put it another way, "I went in the 'directions' of my goal." Like I mentioned prior, this argument has somewhat slipped into preference, but I think it is out of loss of incentive to think about correctly.

Happy Days,
Nobody J.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ee54c44-ed0c-87b5-c9dd-88976667517f
* Version Independent ID: 5ee54c44-ed0c-87b5-c9dd-88976667517f
* Content: [Create Power BI report and dataset components (preview) - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/create-edit-powerbi-report-dataset-components)
* Content Source: [powerapps-docs/maker/model-driven-apps/create-edit-powerbi-report-dataset-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/create-edit-powerbi-report-dataset-components.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @Nobodyworld, thanks for reaching out about the missed word there. Sharp eyes! :) As for toward versus towards, both are prepositions and it's not a question of plural/singular - it's more a matter of dialect. I think "toward" is more common in Britain, while "towards" is quite widespread in the States.  In any event, thanks for helping to improving our documentation! I'll make the correction!

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Nobodyworld. This issue has been assigned to the doc author for review.

**Comment by Nobodyworld** [comment]
Prepositions. . Huh . That sounds vaguely familiar. I will look it up, Hahaha. Thanks for the knowledge!

Sent via the Samsung Galaxy A32 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by paulinbar** [comment]
#please-close

**Comment by Nobodyworld** [comment]
Sorry . . I just made the transition to feedback on GitHub. I will be more expedient in the future.
