### ISSUE TITLE
Unclear, might need a comma. (',')

### ISSUE THREAD

**Issue by Nobodyworld** [MicrosoftDocs/powerapps-docs#5087]
<h2> Link existing Azure Synapse Link for Dataverse profiles to Fabric</h2>

...

"Link to Fabric feature enables direct connectivity between your data in Dataverse with Microsoft Fabric**[,]** without data export**[,]** enabling low code makers to easily work with their data."

--
I am not sure the best approach but here are a couple suggestions...

(This makes more sense to me)
Suggested edit v.1: 
"Link to Fabric feature enables direct connectivity between your data in Dataverse with Microsoft Fabric without data export, enabling low code makers to easily work with their data."

Suggested edit v.2: 
"Link to Fabric feature enables direct connectivity between your data in Dataverse with Microsoft Fabric, without data export, enabling low code makers to easily work with their data."

Happy Days,
Nobody J.

**Comment by phecke** [comment]
@Nobodyworld Please provide a link to the article where this text exists.

**Comment by Nobodyworld** [comment]
https://learn.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-view-in-fabric#link-existing-azure-synapse-link-for-dataverse-profiles-to-fabric

Sorry about that. I thought I had left feedback directly on the page.
