### ISSUE TITLE
Cautionary Note: Confirm you are passing function names or declarations, and not function Expressions

### ISSUE THREAD

**Issue by ryanperrymba** [MicrosoftDocs/powerapps-docs#509]
If it your callbacks are running immediately, or are both running, it is likely that you passed function expressions / function calls, which are evaluated immediately. 

Bad Example: 
Xrm.Page.data.save().then(alert("Record Saved"), alert("Record Not Saved."));
//This does not work because the alert functions are evaluated immediately.

Good Example: 
Xrm.Page.data.save()then(alertSaved, alertNotSaved);
function () alertSaved { alert("Record Saved");}
function () alertNotSaved {alert("Record Not Saved");}
//This does work because the alertSaved, alertNotSaved functions are passed as function objects. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d00568ac-9426-75f7-1662-7e6083f31c64
* Version Independent ID: 491a98a2-f216-8c6e-75fb-a8a64452c9ff
* Content: [save (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data/save#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/save.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/save.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Triangle333** [comment]
Both callbacks aren't invoked when formContext.data.save is called from ribbon function...

**Comment by sanjeev40084** [comment]
we are running into similar issue where successCallBack gets executed even though when data is not saved. We have a custom button in the ribbon and when clicked we are updating status field. We even tried function declarations instead of function expressions as mentioned [here ](https://www.crmug.com/crmug/communities/community-home/digestviewer/viewthread?MessageKey=22ff1d3f-5ebb-44f4-8120-6921c05bee56) but still no luck.

We do get 'saved' alert message but when we  look at the bottom of the page it shows 'unsaved changes'. Funny thing, once we refresh the page (displays message saying there are unsaved change), and try again, it will save the changes.

```
formContext.getAttribute("statuscode").setValue(803750000);
formContext.data.save().then(function(){
     //success logic
    alert("saved");
  },
  function(error){
    Xrm.Navigation.openAlertDialog({ text: error.message });
  }
)
```

Any suggestion?

**Comment by clintolin** [comment]
I am seeing the same thing when creating a new record.

formContext.data.save().then(savedActivity(formContext, globalContext), function () { alert(message); });

I am looking for the Guid in the success callback function. You can put a stop in the debugger in that function and wait all day to verify with Advanced Find that the Activity does NOT get created until the rest of the JavaScript runs.

**Comment by ryanperrymba** [comment]
@clintolin, your first argument is an expression, not a declaration, and will be evaluated immediately as written. If  you put it inside of a declarartion, like so, it should work. 

formContext.data.save().then(function () {savedActivity(formContext, globalContext);}, function () { alert(message); });

**Comment by clintolin** [comment]
Ah yes... @ranperrymba, you are correct. Thanks for pointing that out.

**Comment by Nkrb** [comment]
@sanjeev40084 @ryanperrymba Can you confirm if this still happening from your end.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
