### ISSUE TITLE
The "Form" tab is missing!

### ISSUE THREAD

**Issue by Farzad-Jalali** [MicrosoftDocs/powerapps-docs#51]
I'm following the tutorial until "Model-driven apps only: Customize the main form"

now I have two problems:
1. I can't see any option for selecting "Model-driven."
2. even if I get into the entity, still I can't see the "form" tab.

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100f0400-e497-ef15-158e-358d71d00819
* Version Independent ID: c7018831-b0ac-7baf-0715-e11082fb67ad
* Content: [Tutorial for creating a custom entity that has components with PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-custom-entity)
* Content Source: [powerapps-docs/maker/common-data-service/create-custom-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-custom-entity.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Thank you for your feedback. Issue #1 has been fixed by removing the first step due to the maker portal UI changes. Not sure why you aren't seeing a Forms tab though. This update has been checked in to our master branch pending live publish.
