### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Heatherladue1** [MicrosoftDocs/powerapps-docs#5101]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffddfc22-4030-baeb-7e0e-dd83d982a90b
* Version Independent ID: 8da908d8-04f0-db2f-c4d9-1f9487476303
* Content: [Introduction to solutions - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/introduction-solutions)
* Content Source: [powerapps-docs/developer/data-platform/introduction-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/introduction-solutions.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @shmcarth
* Microsoft Alias: **shmcarth**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Heatherladue1. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@Heatherladue1 If you have a question or concern with our documentation, file a new issue and state your question. Closing this empty issue.
