### ISSUE TITLE
Error in Javascript: gridContext.getFetchXML is not a function

### ISSUE THREAD

**Issue by rameshmukka** [MicrosoftDocs/powerapps-docs#5102]
I am trying to get a reference to my Main Grid through a JS script written on a new command of the Main Grid command bar. "SelectedControl" is the parameter I am passing to JS. I got the below code for this.

`function ExportWithLogos(gridContext){
    var grid = gridContext.getGrid();
    var fetchXMLStr = gridContext.getFetchXML();
    console.log(fetchXMLStr);`

Somehow it doesn't work throw error **"gridContext.getFetchXML is not a function"**. Any thoughts?

**Comment by JimDaly** [comment]
@rameshmukka 
Sorry for the delay in responding. The documentation feedback issues system work best you create them using the link at the bottom of the page. This associates your issue with the article so we can notify the author. 

The purpose for the issues in this repository are for us to improve documentation. If the issue doesn't describe some specific action we can take to improve the documentation, I need to direct you to reach out to the community or contact technical support.

If you notice something wrong, or if there could be a better example that will help you, please reopen this.
