### ISSUE TITLE
Virtual Table Limitations list should be expanded and/or clarified

### ISSUE THREAD

**Issue by gregboyko** [MicrosoftDocs/powerapps-docs#5111]
We had a team member test registering a plugin against a virtual table/entity, and it seems it's not supported. Please add this limitation to the list of limitations for virtual tables:

![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/47670747/e5b14351-bccb-4c1f-8d3e-ebd618a2135e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42ae2cb6-ce2a-21c7-cb81-b60e7b026753
* Version Independent ID: 5a3cb7c0-6881-1d96-0dc3-639324a4568c
* Content: [Get started with virtual tables (entities) (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/virtual-entities/get-started-ve)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gregboyko. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Taking this offline with Greg.
