### ISSUE TITLE
Postman access token Doku falsch

### ISSUE THREAD

**Issue by boernard** [MicrosoftDocs/powerapps-docs#5140]
Die beschriebenen Parameter für Postman sind nicht korrekt, man bekommt einen Error. Diese Seite hat die richtigen Parameter für Postman: https://liupeirong.github.io/postmanAzureFunctions/

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: d25c7db3-badf-d848-1cca-9e5fe3390504
* Version Independent ID: 70c9e985-9dbc-6415-5983-c551b05b0c87
* Content: [Einrichten einer Postman-Umgebung (Microsoft Dataverse für Apps) - Power Apps](https://learn.microsoft.com/de-de/power-apps/developer/data-platform/webapi/setup-postman-environment)
* Content Source: [powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/setup-postman-environment.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @boernard. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Translation of the comment:

> The parameters described for Postman are not correct, you get an error. This page has the correct parameters for Postman:

@boernard 
Thanks for your feedback.

As far as I can tell, this translated page has the same parameters described in the English article:
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/setup-postman-environment

These parameters work when using the `clientid` provided in the article. You aren't expected to generate your own, and using a client secret is out of scope for this article.

**Comment by Bernadette2022** [comment]
This is not a localization issue.  Removing assignment to me.
