### ISSUE TITLE
Retrieve PostMesage from embedded PowerApp

### ISSUE THREAD

**Issue by araver** [MicrosoftDocs/powerapps-docs#516]
When a user clicks on a button such as save or cancel in a PowerApp, the PowerApp sends a PostMessage to some parents. This can be useful if the developer would like to hide the frame after a form was submitted. SharePoint makes use of this in the list form functionality. As a developer, how can I access these messages?

**Comment by phecke** [comment]
@araver How are you doing the embedding (via iframe URL embedding?

What topic (provide URL) in the PowerApps documentation are you following?

**Comment by phecke** [comment]
@araver It has been 10 days since I sent you a response asking for additional information. I am closing this issue. If you wish to discuss this issue further, feel free to open a new issue. Thanks.
