### ISSUE TITLE
Flow run data missing

### ISSUE THREAD

**Issue by AutoMationTimeNow** [MicrosoftDocs/powerapps-docs#5160]
There is no data in the flowrun Dataverse table. When will the data be there? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa7c18e4-aa17-d894-8e46-a845c353fc82
* Version Independent ID: fa7c18e4-aa17-d894-8e46-a845c353fc82
* Content: [flowrun table/entity reference (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/flowrun)
* Content Source: [powerapps-docs/developer/data-platform/reference/entities/flowrun.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/reference/entities/flowrun.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AutoMationTimeNow. This issue has been assigned to the doc author for review.

**Comment by phecke** [comment]
@AutoMationTimeNow I do not know. Perhaps the entity was created for an upcoming product feature.
