### ISSUE TITLE
How to get the passed data?

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#5162]
As already asked in late 2022, I'm also trying to get the parameters. We now have early 2024. I'm referencing this feedback: https://github.com/MicrosoftDocs/powerapps-docs/issues/3453

I've already done this in CRM 2011 and later versions by reading the query string parameters. This is not possible anymore.

The data would be available in Xrm.Utility.getPageContext().input.data, but for some reasons the developers decided it's better to hide this custom data and keep it to themselves? They can't even do anything with custom data. What's the point of hiding it?

**Comment by JimDaly** [comment]
@darshSWL 

Thanks for your feedback. In #3453, we had the engineering team respond with:

> Currently the method to collect the URL parameters is not exposed (and hence supported). With the converged app and custom pages we expect a more mature PowerFx based model to be utilized for these use cases.

We document what we support. This isn't supported, so there is nothing actionable to address in this issue.

Closing this.
