### ISSUE TITLE
Unclear text, please make it easy to understand or have some images

### ISSUE THREAD

**Issue by zoh-akh** [MicrosoftDocs/powerapps-docs#5167]
[Enter feedback here]
If the setting is Overridable and Value can be overridden is set to Environment and app the setting app value is returned.

This statement is so unclear and may be grammatically incorrect making it hard to understand. Please correct it and may be add images to make the point clear. Thanks
<img width="667" alt="Screenshot 2024-02-02 at 8 24 21 PM" src="https://github.com/MicrosoftDocs/powerapps-docs/assets/36782624/67fc3599-41d0-4272-90fa-9b65e2a316aa">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1feb676-9456-117a-1462-2fb0a6d1562c
* Version Independent ID: f1feb676-9456-117a-1462-2fb0a6d1562c
* Content: [Get or update setting value using client API - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/get-update-setting-value-using-code)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/get-update-setting-value-using-code.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/get-update-setting-value-using-code.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by JimDaly** [comment]
@zoh-akh 

Thanks for your feedback.  That dense text packed together is hard to read.

I've split it out into nested bullet points and presented the values as bold text consistently.
|OLD|NEW|
|---|---|
|![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/6353736/b04456f8-1cf0-458c-b401-8ee1bf6de4b8)|![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/6353736/07e6ab18-2659-4f17-b36d-f0e3f6fd0503)|


I hope this helps.
