### ISSUE TITLE
Please change the Syntax to tabObj instead of contextObj

### ISSUE THREAD

**Issue by sathiskumarr** [MicrosoftDocs/powerapps-docs#517]
Documentation is really confusing mentioned as contextObj where the example is related to tabObj
Hope the above changes will changed soon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98294b27-f102-432d-cf96-6d32099e5bce
* Version Independent ID: 06226482-c953-650d-8492-b5fa195e4118
* Content: [setDisplayState (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-tabs/setdisplaystate#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-tabs/setDisplayState.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-tabs/setDisplayState.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@sathiskumarr Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
