### ISSUE TITLE
"Export" Button Missing, even in blank environment with no customizations

### ISSUE THREAD

**Issue by BrainSlugs83** [MicrosoftDocs/powerapps-docs#5175]
When reading the documentation at [https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-import-export#export-data](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-import-export#export-data), it implies that selecting Tables from the left hand navigation should give us an "Export" button on the top ribbon,  But that button does not exist.

I tried it even on a brand new environment (on a non-empty table), where I am an admin, so I don't believe that it is due to some customization in my environment.

This is in GCC (low) if that helps.

Would like to see the documentation get updated, because -- I'm sure the option used to be there, but for the life of me, I can't find it now. 😕

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67d61b22-c901-ad09-b9bb-ecfb2bb12f9d
* Version Independent ID: fa41e5c6-8deb-7a92-2699-42db23d1a85c
* Content: [Import or export data from Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-import-export#export-data)
* Content Source: [powerapps-docs/maker/data-platform/data-platform-import-export.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/data-platform-import-export.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BrainSlugs83. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@BrainSlugs83 - The command is there and should be available. 
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/21203819/d7608af6-4b56-4355-985f-2a10a6fed113)
