### ISSUE TITLE
How can I display images stored on a file share in my PowerApps app?

### ISSUE THREAD

**Issue by thegongben** [MicrosoftDocs/powerapps-docs#518]
Is there a way to display the images that are stored on a file share on premise? I am able to create the File System connection in my PowerApps app but there is NO way for me to use it to display the images in my PowerApps! I have been googling about this and some say I have to use a Flow app. I have created a flow app and I am able to use the Get File Content action from the on-premise file share and able to create a new file with that content on to my OneDrive for business. But I still cannot use the Flow app in my PowerApps app to display the images! 
Thank you.

Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc4ce6c-c2be-df55-445b-d1a2c7c62dac
* Version Independent ID: feb3e0d2-e8a7-8d5f-4078-1f1a420887ac
* Content: [Visual properties - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/properties-visual)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/properties-visual.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/properties-visual.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please see [file system connector reference](https://docs.microsoft.com/connectors/filesystem/). You can also use [OneDrive for Business connector](https://docs.microsoft.com/connectors/onedriveforbusiness/). There are also other [cloud storage related connectors](https://docs.microsoft.com/powerapps/maker/canvas-apps/connections/cloud-storage-blob-connections) that can be used.
