### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerapps-docs#5181]
"inlcuding " should be "including "

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4738c129-9cd7-0874-e04c-fae18c36e47a
* Version Independent ID: 07aa2fbe-ae0e-e8db-86cf-473a1128fe12
* Content: [Use keyboard shortcuts in Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/user/keyboard-shortcuts)
* Content Source: [powerapps-docs/user/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/user/keyboard-shortcuts.md)
* Service: **powerapps**
* Sub-service: **end-user**
* GitHub Login: @sericks007
* Microsoft Alias: **sericks**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @biterbit. This issue has been assigned to the doc author for review.

**Comment by sericks007** [comment]
@biterbit, thanks for letting us know! This should be fixed in a few hours.
