### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by alexwarbs** [MicrosoftDocs/powerapps-docs#52]
I love this idea of this and something that could work for us internally. However, is there any way that you could add attachments to when you submit an expense? i.e. Upload a picture of your receipt? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install#play-the-powerapp)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by caburk** [comment]
The simplest way to do this is adding the "Attachments" field to the form. This will add an attachment control to upload images and save them to the SharePoint list.
Here are step by step instructions to do this: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-forms#create-a-record

**Comment by KumarVivek** [comment]
Closing the issue.
