### ISSUE TITLE
PowerApps set solution version - Incorrect documentation?

### ISSUE THREAD

**Issue by smgtreker** [MicrosoftDocs/powerapps-docs#520]
The documentation for the "PowerApps set solution version" task looks incorrect; it makes no mention of the parameter "Solution Version Number".
For the Solution Version Number parameter documentation (when it is added) it would be helpful if the documentation states whether or not the version number parameter is static, e.g. "1.0.0.0" or if it can include dynamic logic. E.g. "1.0.0.x" would take the previous version and automatically increment the "x" part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e92c215-b337-b864-3fee-b9542e4e30c8
* Version Independent ID: 8f26538c-5863-6746-8c2c-ee4438165da4
* Content: [Build tools tasks - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tasks#powerapps-set-solution-version)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tasks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by AymericM78** [comment]
@smgtreker : You can use $(Build.BuildId) instead of "x", this will use the build number. This will help to track correllation between build and CRM solutions.
