### ISSUE TITLE
Instruction at Configure network access to the Azure Synapse Workspace is unclear

### ISSUE THREAD

**Issue by V4A001** [MicrosoftDocs/powerapps-docs#5206]
[Enter feedback here]
The instruction under Configure network access to the Azure Synapse Workspace is unclear. Must IP client added, and the red boxes be deleted?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27e52c30-3d07-248e-d188-92ff021c5e5d
* Version Independent ID: 27e52c30-3d07-248e-d188-92ff021c5e5d
* Content: [Use managed identities for Azure with your Azure data lake storage - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-msi)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-msi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-msi.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @JasonHQX
* Microsoft Alias: **jasonhuang**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @V4A001. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@V4A001 - As per the article you need to remove any existing IP rules that might exist. Then add a new IP rule based on the client IP address. For more information on creating the rule, go to https://learn.microsoft.com/en-us/azure/synapse-analytics/security/synapse-workspace-ip-firewall#ip-firewall-rules
