### ISSUE TITLE
Calculated Columns will eventually be discontinued?

### ISSUE THREAD

**Issue by ruskh** [MicrosoftDocs/powerapps-docs#5208]
While creating a new calculated column, there is a notification that calculated columns will eventually be discontinued. What happens to the calculated columns already in production, some of which are chained over tables. Will they automatically be converted to formula columns? Will they simply stop working ? What is period over which they are planned to continue working?

And what should we use in their place while creating new columns? Because formula columns have the notification that they are in preview and should not be used in production

Can the docs be updated with this information ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f212137-6b88-c06c-025d-c05e6b74c10f
* Version Independent ID: 61abe448-2b0d-29bd-90bb-63899f0f92dc
* Content: [Define calculated columns in Power Apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/define-calculated-fields)
* Content Source: [powerapps-docs/maker/data-platform/define-calculated-fields.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/define-calculated-fields.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ruskh. This issue has been assigned to the doc author for review.

**Comment by ruskh** [comment]
Also, could you please let us know if Choice columns support in formula columns is on the roadmap, if it's not will have to convert many Choice columns to Lookups , Text(ChoiceColumn) does not always work.

**Comment by Mattp123** [comment]
@ruskh - When calculated columns are deprecated that information will be most likely published here: https://learn.microsoft.com/en-us/power-platform/important-changes-coming
For future plans, go to the release plans here: https://learn.microsoft.com/en-us/dynamics365/release-plans/

Closing issue.
