### ISSUE TITLE
Localizied return values

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#5217]
The three return values none, required and recommended are translated on the german version.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7908fd27-a946-6225-4adf-a1cd632a0e13
* Version Independent ID: e98c413b-d5e6-ac14-d461-eb689ed26cef
* Content: [getRequiredLevel (Client API reference) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/attributes/getrequiredlevel)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getRequiredLevel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getRequiredLevel.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@darshSWL 

Thanks for pointing this out. I've fixed this so the German content will not localize the values in the future.
