### ISSUE TITLE
Timer duration empty

### ISSUE THREAD

**Issue by Ajaxsoap** [MicrosoftDocs/powerapps-docs#522]
Is the duration property is required? Is it possible to have no duration or infinite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11a9f1d-da5c-f25b-2b48-eddc4c4a6cc5
* Version Independent ID: 1c0f1c98-8bf0-320d-74e8-434e816a4222
* Content: [Timer control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-timer#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-timer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-timer.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by chmoncay** [comment]
Hi there, Duration is required.  The maximum duration time is 24 hours (expressed as ms).  The default is 60s.
