### ISSUE TITLE
misspelled word

### ISSUE THREAD

**Issue by IonutGhetau** [MicrosoftDocs/powerapps-docs#5220]
[Just a misspelled word in the page "Sutdio"]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5c733e4-5a8c-56a3-ff18-b5e589ac6d91
* Version Independent ID: aba35600-3d59-5751-2072-33cc24ec5601
* Content: [Power Apps portals Studio - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/portal-designer-anatomy)
* Content Source: [powerapps-docs/maker/portals/portal-designer-anatomy.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/portal-designer-anatomy.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @IonutGhetau. This issue has been assigned to the doc author for review.

**Comment by ProfessorKendrick** [comment]
Thanks for bringing this to our attention.  The typo is fixed. Closing the issue.
