### ISSUE TITLE
Typos in mark down not showing proper information

### ISSUE THREAD

**Issue by V4A001** [MicrosoftDocs/powerapps-docs#5223]
There are two typos regarding the links []() is a link in markdown..the opposite not :-). Second is referring wrong section.

If your environment is linked to a Dynamics 365 finance and operations environment, the add tables option enables you to include tables from finance and operations apps. Learn more: (Choose finance and operations data in Azure Synapse Link for Dataverse)[azure-synapse-link-select-FnO-data.md]

All Dataverse tables where "Change tracking" property is enabled are linked to Fabric. If this environment is linked to Finance Operations, you can add Finance and operations tables later. See [manage links section](## Manage link to Fabric).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdebe533-0103-bcf1-edea-47198c7284a9
* Version Independent ID: bdebe533-0103-bcf1-edea-47198c7284a9
* Content: [Link your Dataverse environment to Microsoft Fabric and unlock deep insights - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/azure-synapse-link-view-in-fabric)
* Content Source: [powerapps-docs/maker/data-platform/azure-synapse-link-view-in-fabric.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/azure-synapse-link-view-in-fabric.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @MilindaV2
* Microsoft Alias: **Milindav**

**Comment by Mattp123** [comment]
@V4A001 - Thank you for your feedback. The links in the article have been fixed and will be published today.
Closing issue.
