### ISSUE TITLE
Restricted Table Information

### ISSUE THREAD

**Issue by benopax8apac** [MicrosoftDocs/powerapps-docs#5224]
Can you please make this section a little more clear.

What are the concerns when cititzen developers develop an app that may need to integrate with a D365 App

Can you break down the list of restricted tables into D365 workloads

Can you explain more about what each of these entities do?

More information is always appreciated. And remember that end users read these documents not just techno consultants

**Comment by phecke** [comment]
@benopax8apac We need a link to the article in question.

**Comment by phecke** [comment]
No response from customer. Closing this issue.

**Comment by benopax8apac** [comment]
Sorry for delay. 
I think I was referring to this https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-complex-entities and https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-restricted-entities

However, my question was relating to using the restricted tables in power platform, so I presume whoever looks after MS Learn for the Power Platform would be able to guide you on this question. 
All I can share is that the details on Restricted tables is extremly hard to understand.
