### ISSUE TITLE
Create my own case/incident table table

### ISSUE THREAD

**Issue by CRMDude** [MicrosoftDocs/powerapps-docs#5225]
I am sure I read earlier that there might be restrictions on replicating existing tables within PowerApps, such as the Case table from Dataverse, which could potentially circumvent licensing requirements. This notion seemed plausible as it would offer a means to bypass significant costs associated with licensing. However, I am unable to locate any current references or guidelines that confirm this restriction. Should this no longer be a constraint, it raises the possibility of developing a fully functional CRM system at a fraction of the usual cost. I would greatly appreciate any insights or clarifications on this matter.

**Comment by phecke** [comment]
@CRMDude Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/.

If you have questions or issues about our documentation, let us know.

Closing this issue.
