### ISSUE TITLE
Typo in reference to _refreshData

### ISSUE THREAD

**Issue by vieil-in** [MicrosoftDocs/powerapps-docs#5228]
I suspect "this._refreshData = this.refreshData.bind(this);" should be "this._refreshData = this._refreshData.bind(this);"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Create your first component using Power Apps Component Framework in Microsoft Dataverse - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript?tabs=before)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @HemantGaur
* Microsoft Alias: **hemantg**

**Comment by JimDaly** [comment]
@vieil-in 
Thanks for your feedback.

This sample code has been tested and the published code matches the code in the sample [index.ts](https://github.com/microsoft/PowerApps-Samples/blob/2d8e9d642df0c7090ba5b2772b960bed8689f9fc/component-framework/LinearInputControl/LinearInputControl/index.ts#L56) file.

I'm going to need a bit more than a suspicion to change something that I've previously tested and know to work.
