### ISSUE TITLE
Pass timer data to a sharepoint list column - 2228715

### ISSUE THREAD

**Issue by Ajaxsoap** [MicrosoftDocs/powerapps-docs#523]
How do you pass the timers data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11a9f1d-da5c-f25b-2b48-eddc4c4a6cc5
* Version Independent ID: 1c0f1c98-8bf0-320d-74e8-434e816a4222
* Content: [Timer control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-timer#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-timer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-timer.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by chmoncay** [comment]
Hi there, sorry for the late reply.  What are you trying to do?

**Comment by chmoncay** [comment]
Hi there, I don't understand the use case.  Can you explain what you're trying to do here?
