### ISSUE TITLE
Not able to generate PDF

### ISSUE THREAD

**Issue by AhmedSyeda** [MicrosoftDocs/powerapps-docs#5230]
![Screenshot 2024-02-20 193635](https://github.com/MicrosoftDocs/powerapps-docs/assets/110947965/24d3a33f-f643-48db-8a06-209c0e146dfa)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 782ca112-0ce4-83d9-019d-bf5cdc9e5eeb
* Version Independent ID: 782ca112-0ce4-83d9-019d-bf5cdc9e5eeb
* Content: [Add copilot for app users in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/add-ai-copilot)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-ai-copilot.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/add-ai-copilot.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **mijosh**

**Comment by AhmedSyeda** [comment]
After refreshing several times also doc fails to build.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AhmedSyeda. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment]
@AhmedSyeda - Are you trying to build a PDF from the Download PDF available from the Learn articles? I was able to successfully create the PDF via the site. If you're still experiencing the issue, reopen this issue or create a new one.
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/21203819/45c3a987-76f5-4b44-98fd-51bafd88046b)

**Comment by AhmedSyeda** [comment]
Still same behavior - download fails.
![image](https://github.com/MicrosoftDocs/powerapps-docs/assets/110947965/7a0c82b7-041c-4cff-ae80-b8deb406d6a7)
 
[steps4PDFDNLD.zip](https://github.com/MicrosoftDocs/powerapps-docs/files/14440601/steps4PDFDNLD.zip)

**Comment by AhmedSyeda** [comment]
Hello Matt.

The issue is with our internal firewall setup. We figured out and fixed the issue. Could you close the ticket? since the issue is resolved now.
Just so you know, if any of you are facing the same issue check your AI extensions and modify access. This helped us.
