### ISSUE TITLE
PowerApps checker service docs unavailable

### ISSUE THREAD

**Issue by rappen** [MicrosoftDocs/powerapps-docs#525]
Clicking the link to the docs https://aka.ms/buildtoolsconnection takes me to @mikkelsen2000 personal OneDrive, that does not seem to be shared with the public.
I would really like to read that documentation! :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e92c215-b337-b864-3fee-b9542e4e30c8
* Version Independent ID: 8f26538c-5863-6746-8c2c-ee4438165da4
* Content: [Build tools tasks - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tasks#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tasks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by JimDaly** [comment]
Looks like the link is pointing to https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tasks#configure-service-connection-for-powerapps-checker now

**Comment by rappen** [comment]
Yes, great to see it fixed! 😊
