### ISSUE TITLE
Import Solutions timing out

### ISSUE THREAD

**Issue by yohanosullivan** [MicrosoftDocs/powerapps-docs#526]
Doesn't appear to be a way to import asynchronously for larger imports. Is there a way around the 2 minute timeout? 

Setting the timeout parameter in the task does not stop the timeout of the environment, just the timeout of the task.

**Comment by phecke** [comment]
@yohanosullivan How are you doing the import - through the web app UI, SDK/WebAPI calls, or through PowerShell code?

**Comment by yohanosullivan** [comment]
@phecke I am using the DevOps task PowerApps Import Solution found at https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-overview
Below is the Powershell command the task uses 
Import-Solution -ApiUrl $EnvironmentURL -Credential $PSCredential -Verbose @Parameters

**Comment by phecke** [comment]
@yohanosullivan  The asynchronous capability is in development and is planned for release sometime from late August or in the Fall. You will not need to change your existing Azure task as it will just work.

**Comment by phecke** [comment]
There is no way currently to increase the 2 minute timeout.

**Comment by phecke** [comment]
@yohanosullivan  We pushed an update yesterday that addresses the timeout issue. Let us know if this works for you.
