### ISSUE TITLE
Very helpful page!  

### ISSUE THREAD

**Issue by cztop54** [MicrosoftDocs/powerapps-docs#528]
Gotta say -- most of the time these pages are not helpful to me -- but this one gives me hope there may be more help.  The examples and walk-through manner are excellent. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cf200f9-bbdc-edb4-79e2-f08839d2457b
* Version Independent ID: ca13a0df-20a7-c0f5-9597-1be7c2c7b042
* Content: [Show text, dates, and times in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/show-text-dates-times#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/show-text-dates-times.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/show-text-dates-times.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by phecke** [comment]
@cztop54 Thanks for the feedback :)
