### ISSUE TITLE
Unclear instructions. 

### ISSUE THREAD

**Issue by KittyDreadful** [MicrosoftDocs/powerapps-docs#5280]
To enable trace logging you can programmatically update this value or in the web application navigate to Settings > Administration > System Settings. In the Customization tab, locate the drop-down menu labeled Enable logging to plug-in trace log and select one of the available options.

This instruction is unclear.  For example, there should be a reference to: https://admin.powerplatform.microsoft.com/ or wherever one would find the Settings.   

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43ba8078-5ca8-ccff-3d6b-3e89d111ba99
* Version Independent ID: f87c4c4f-389d-6241-be70-23cbb0c904d1
* Content: [Logging and tracing (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/logging-tracing)
* Content Source: [powerapps-docs/developer/data-platform/logging-tracing.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/logging-tracing.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KittyDreadful. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@KittyDreadful 

Thanks for your feedback. I think we should just remove these instructions to try to find this setting in the app, and instead guide people to the next paragraph, which provides a better experience IMHO

> You may find it easier to view this data by using the Web API in your browser using the example shown in [Use Tracing](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/debug-plug-in#use-tracing) or by using the [Plug-in trace viewer](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/logging-tracing#plug-in-trace-viewer) community tool.

**Comment by KittyDreadful** [comment]
I would disagree.  The community tools are not Microsoft products. 

Adding a few lines and a screen shot would help:
From the main application URL , which will look something like: https://XXXXXXX.crm.dynamics.com/main.aspx, select the cog icon in the upper right of the window to activate the Settings menu.  
Select Advanced Setting, which will take you to the legacy Setting screen (include a screen shot for reference). 
Select Administration and the Customization tab.  (include screen shot) 

I know that screenshots are hard to keep up to date, but this would have saved several hours trying to find where this setting was configured.  These screens haven't been updated in many years, so the changes that you'd have to maintain the screenshots seems small to me.

**Comment by phecke** [comment]
@KittyDreadful I just recently updated the instructions.

[Enable trace logging](https://learn.microsoft.com/power-apps/developer/data-platform/logging-tracing#enable-trace-logging)

You say that the instructions are unclear, yet you know how to get to the legacy Settings page? I assume you are suggesting steps be added so that other people can find it easier? I can see your point and will consider including instructions to the legacy Settings page.

**Comment by KittyDreadful** [comment]
Of course I know how to get to the legacy screens.   They are the same since v3.0.

**Comment by phecke** [comment]
@KittyDreadful Yes, but users new to the product may not know how to navigate there.
