### ISSUE TITLE
IPluginExecutionContext4 is returning as null for custom entities as well in Plugins

### ISSUE THREAD

**Issue by pavanmanideep** [MicrosoftDocs/powerapps-docs#5288]
I used below code using Bulk Operation Messages in Plugins, IPluginExecutionContext4 returns null for custom entity plugins. Currently using the latest version of CRMSdkCoreAssemblies. As Microsoft Documentation says to use IPluginExecutionContext4 for this
 IPluginExecutionContext4 context4 = (IPluginExecutionContext4)serviceProvider.GetService(typeof(IPluginExecutionContext4)); 

I was able to get the context information from IPluginExecutionContext only.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd4cb2f-c1e8-b741-98b2-229f5952b5da
* Version Independent ID: 8dd4cb2f-c1e8-b741-98b2-229f5952b5da
* Content: [Write plug-ins for CreateMultiple and UpdateMultiple - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/write-plugin-multiple-operation?tabs=single)
* Content Source: [powerapps-docs/developer/data-platform/write-plugin-multiple-operation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/write-plugin-multiple-operation.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pavanmanideep. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
Issues for this repository must address the documentation content or functionality. 

This issue seems to be a request for technical support. We do not have the resources to troubleshoot issues. If you need help, please contact technical support.
