### ISSUE TITLE
Does this apply to tooltip text?

### ISSUE THREAD

**Issue by codepounder** [MicrosoftDocs/powerapps-docs#529]
The introductory sentence says that these text properties apply to tooltips as well as other text displays, but I don't see that any of these properties affect the tooltip formatting. Tooltip text is always very small. If any of these properties would allow formatting of tooltip text, please specify how that is done. Otherwise, state that these don't apply to tooltips.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79f9892-7269-14e6-9220-5d667c23f964
* Version Independent ID: e7d4f058-db72-0772-6e8c-9c394ed22721
* Content: [Text properties - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/properties-text)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/properties-text.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/properties-text.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content is updated since it doesn't apply to tooltips. Please allow some time for changes to reflect.
