### ISSUE TITLE
Radio control Value property

### ISSUE THREAD

**Issue by AlexZhidkov** [MicrosoftDocs/powerapps-docs#53]
Does Radio control have Value property? I'm not able to access it. Only Selected.Value works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff9e431-4f75-a61c-bacc-fd904bf5bdde
* Version Independent ID: 3f88278f-a036-882f-f520-853ebca1bbff
* Content: [Radio control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-radio)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-radio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-radio.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
That is correct, you can only get the value of the selected item via Selected.Value

**Comment by AFTOwen** [comment]
@AlexZhidkov Thanks for your feedback. If we haven't answered your question, please reopen this issue, and specify more details about what you're looking for. Cheers!

cc: @fikaradz
