### ISSUE TITLE
This topic doesn't belong in this area of the table of contents

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#530]
This topic is about creating attributes, not auditing data changes.
It should be moved to this area: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/entity-attribute-metadata

Please edit the table of contents to include this topic with related content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ed5d32-c7ea-cf1b-4b67-42d220bced10
* Version Independent ID: 809601df-9094-fa16-2aba-f8941c2fd1db
* Content: [Create auto-number attributes (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-auto-number-attributes)
* Content Source: [powerapps-docs/developer/common-data-service/create-auto-number-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/create-auto-number-attributes.md)
* Service: **powerapps**
* GitHub Login: @MicroSri
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
The [Create auto-number attributes](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-auto-number-attributes) topic now appears under **Attribute metadata** node in TOC.

![image](https://user-images.githubusercontent.com/28051062/61930106-725c8080-af9a-11e9-80c2-0efff3a11e0d.png)

Closing this issue now.
