### ISSUE TITLE
broken English translation

### ISSUE THREAD

**Issue by CodeResearcher** [MicrosoftDocs/powerapps-docs#5303]
this site does not work for English language:
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/paging-behaviors-and-ordering

but it works e.g. for German language:
https://learn.microsoft.com/de-de/power-apps/developer/data-platform/org-service/paging-behaviors-and-ordering

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 47cd3c66-2e9b-5983-2cdb-b09d1f04d397
* Version Independent ID: e22d2bab-b8f4-6105-faec-e6dabfe952b7
* Content: [Auslagerungsverhalten und Sortierung (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/de-de/power-apps/developer/data-platform/org-service/paging-behaviors-and-ordering)
* Content Source: [powerapps-docs/developer/data-platform/org-service/paging-behaviors-and-ordering.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/org-service/paging-behaviors-and-ordering.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by phecke** [comment]
@CodeResearcher The querying articles were updated. Looks like we are missing a redirect to the new page.

Here are the new articles for paging:
[Page large result sets with QueryExpression](https://learn.microsoft.com/power-apps/developer/data-platform/org-service/page-large-result-sets-with-queryexpression)
[Page results using FetchXml](https://learn.microsoft.com/power-apps/developer/data-platform/fetchxml/page-results)
