### ISSUE TITLE
Another example to add: extract string

### ISSUE THREAD

**Issue by ChrisGarty** [MicrosoftDocs/powerapps-docs#532]
It would be helpful to have an example of extracting a string out from within a larger string. It is really simple once you figure it out, but I spent more than a couple of hours trawling through forum topics and experimenting to figure it out.
Example: first(split(last(split('Joe Smith &lt;joe.smith@acme.com&gt;', '&lt;')), '&gt;'))
Or as I used it: first(split(last(split(actionOutputs('InitialValue'), '&lt;')), '&gt;'))

Also, you should have advice somewhere about the best way to experiment with expressions. What I found to be ideal is to use the "Manually trigger a flow" trigger then a couple of Compose actions and then use the "Test" capability. That also took some time to figure out...

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c28165a-b79a-d821-5260-bdb2baaa8ca0
* Version Independent ID: da9f62f6-e30d-7617-a418-a45357b75f35
* Content: [Split function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-split)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-split.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-split.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the suggestion.  I added some additional information and examples on extracting substrings with Split.  I also made a note about using Match for substring extraction.
