### ISSUE TITLE
How to handle Lookup as a passed property

### ISSUE THREAD

**Issue by davallen** [MicrosoftDocs/powerapps-docs#535]
I am trying to pass a lookup into my PCF component but do not see any property for lookups. Help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b2e635-6c60-0efc-d894-e43216dca90e
* Version Independent ID: 9828125d-c061-465e-d486-b4ea609190e1
* Content: [Property Element - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property#feedback)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/property.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@davallen Please raise your concerns [here](https://powerusers.microsoft.com/t5/PowerApps-component-framework/bd-p/pa_component_framework). Our development team will help you with the issue.
