### ISSUE TITLE
Cannot place PCF component on a section.

### ISSUE THREAD

**Issue by davallen** [MicrosoftDocs/powerapps-docs#536]
Trying to place a PCF component on an entire section, but it will not let me. Will this be supported?

Also, when I place a control over a field it leaves the line below the field. Can I remove this line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34647a0-dfdf-23da-c656-158a1eae14f9
* Version Independent ID: e2a795ee-c8ba-b757-194b-19ecf4b6d398
* Content: [Add Custom Components to a field or entity - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/add-custom-controls-to-a-field-or-entity#feedback)
* Content Source: [powerapps-docs/developer/component-framework/add-custom-controls-to-a-field-or-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/add-custom-controls-to-a-field-or-entity.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@davallen Please raise your concerns [here](https://powerusers.microsoft.com/t5/PowerApps-component-framework/bd-p/pa_component_framework). Over development team will help you with the issues
