### ISSUE TITLE
Specifying date formats

### ISSUE THREAD

**Issue by pconnell99** [MicrosoftDocs/powerapps-docs#537]
I embedded an app inside a page in SharePoint that was MM/DD/YYYY and created a date string that was DD/MM/YYYY and it was completely misinterpreted.

How do we specify WHICH ONE is being used? YYYYMMDD would be unambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fda4c41-0a11-d2f5-8424-d79fa32c6103
* Version Independent ID: 5b21c7e2-cd5a-0d81-e9a3-97a65266aa17
* Content: [DateValue, TimeValue, and DateTimeValue functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-datevalue-timevalue)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-datevalue-timevalue.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-datevalue-timevalue.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Use the final optional argument to each function to specify the correct interpretation.  The docs include this passage:
 
By default, the language used is that of the current user, but you can override this to ensure that strings are interpreted properly. For example, "10/1/1920" is interpreted as October 1st in "en" and as January 10th in "fr".
