### ISSUE TITLE
Doesn't work with latest Postman

### ISSUE THREAD

**Issue by yan0lovesha** [MicrosoftDocs/powerapps-docs#538]
Shows error "unsupported_response_type" after input username/password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80534df2-e9da-fd0a-80bf-4bfc0dbb2fcc
* Version Independent ID: b8053ca7-e385-2f0b-06af-81b908f345a1
* Content: [Set up a Postman environment (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/setup-postman-environment#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/setup-postman-environment.md)
* Service: **powerapps**
* GitHub Login: @susikka
* Microsoft Alias: **susikka**

**Comment by acornsoft** [comment]
Have the same error, "unsupported_response_type"

**Comment by acornsoft** [comment]
I tracked it down to the following article, https://docs.microsoft.com/en-us/skype-sdk/websdk/docs/troubleshooting/auth/aadauth-enableimplicitoauth, which tells you to re-configure the Manifest with implicot flow for your application.

So I changed the following line in my Application manifest:
	**"oauth2AllowImplicitFlow": true,**

**Comment by susikka** [comment]
@acornsoft Yes, we need to set `oauth2AllowImplicitFlow` to `true` in the Application manifest file. This topic provides information on how to get started with using Postman. The Postman topic provides a link to [Walkthrough: Register an app with Azure Active Directory](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-register-app-azure-active-directory) that provides information on how to register your Azure AD application.

Closing this issue now.
