### ISSUE TITLE
Missing multiselectoptionset

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#539]
This page should describe the return value of Attributes of type multiselectoptionset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae10e81-fc06-bb27-708c-71082460571a
* Version Independent ID: ecf78692-311d-c121-faf7-aaed40f46c6a
* Content: [getValue (Client API reference) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/getvalue#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getValue.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getValue.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@devlinl Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
