### ISSUE TITLE
Ne fonctionne pas [Button reference]

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/powerapps-docs#54]
@sergepayeur commented on [Thu Sep 06 2018](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/issues/2)

Vous mettez : Ajoutez un contrôle Label, définissez sa propriété Text sur Total, puis appuyez sur F5.
Si je nomme mon champ Total, j'ai des erreurs partout dans toutes les propriétés, Total étant un clé.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 84199ba6-6ce9-803f-91c9-f8ce7665c4c6
* Version Independent ID: 2c2bdb7f-c2a4-809f-0819-762ea95bc838
* Content: [Contrôle Button : référence - PowerApps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/controls/control-button)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-button.md](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/blob/live/powerapps-docs/maker/canvas-apps/controls/control-button.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
@LisandroSu I've just tried this in English, and it works as written. Might the French translation be flawed(either in that step or an earlier one), or might the French product work differently? Cheers.

cc: @fikaradz

**Comment by AFTOwen** [comment]
@LisandroSu Closing for now. Please reopen if you get more information. Thanks!

cc: @fikaradz
