### ISSUE TITLE
cannot bind to FP (latitude/longitude) for account 

### ISSUE THREAD

**Issue by kenakamu** [MicrosoftDocs/powerapps-docs#540]
I take the example solution and deploy. I could bind the control to text field, but cannot find any floating point fields to set lat/lon. It seems like the FP cannot match to the existing floating point fields?

I thought it worked before but when i recreate yesterday, it didnt work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ba395c-fd91-a615-6ac2-37163bd7c42c
* Version Independent ID: 59311ece-00da-1243-625a-59165868f329
* Content: [IFRAME component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/iframe-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/iframe-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/iframe-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@kenakamu Thanks for the feedback. Please raise your issues [here](https://powerusers.microsoft.com/t5/PowerApps-component-framework/bd-p/pa_component_framework), the development team will look into the issue and help you. Closing the issue.
