### ISSUE TITLE
need uses-feature for manifest to work

### ISSUE THREAD

**Issue by kenakamu** [MicrosoftDocs/powerapps-docs#541]
&lt;feature-usage&gt;
      &lt;uses-feature name="Device.pickFile" required="true" /&gt;
    &lt;/feature-usage&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27dc0672-cb23-c1c6-9501-b1ad78a6390d
* Version Independent ID: 0a3d4a2c-33fa-4098-bd49-50456b00bcce
* Content: [Image Upload component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/image-upload-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/image-upload-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/image-upload-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nkrb**

**Comment by Nkrb** [comment]
@kenakamu Thanks for the feedback. The docs are updated with the latest information and pushed to live. Closing the issue.
