### ISSUE TITLE
Discrepancies in getEntityMetadata vs access via web api 

### ISSUE THREAD

**Issue by imranakram** [MicrosoftDocs/powerapps-docs#542]
The metadata fields Description, IconSmallName, IconMediumName, IconLargeName Image contains empty string when I tried using `getEntityMetadata` but if I try to access the same via web api it shows data. I have multi lingual environment. On top of that the system entities like Account does not show data for Icon fields but works for custom entities.

https://&lt;MyOrganizationName&gt;.api.crm4.dynamics.com/api/data/v9.1/EntityDefinitions(LogicalName='account')?$select=DisplayName,EntitySetName,IconMediumName,IconLargeName,IconSmallName,Description

It's very confusing and extremely hard to work with. Please take this as a matter of priority. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf6143f9-6760-18c0-a08f-196c8bce8c2f
* Version Independent ID: 74a79a52-be75-ad56-642c-8a3aa6b5ab0d
* Content: [getEntityMetadata (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getentitymetadata#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getEntityMetadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getEntityMetadata.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by scottdurow** [comment]
getEntityMetadata does seem to return only a subset of the metadata that is returned via the raw WebApi request. In particular, it does not return the Attributes collection. Can this behaviour be documented?

**Comment by Nkrb** [comment]
@imranakram Thanks for the feedback. The description field should return the text as it does with the web API request. When tested, we got the text from the description field. The icon fields are not supported in UCI.

**Comment by imranakram** [comment]
@Nkrb Thanks for the update. Do you have something to add regarding the comment by @scottdurow?

**Comment by Nkrb** [comment]
@scottdurow Do you have any specific case where you only get a subset of the metadata. `getEntityMetadata` should return the metadata for everything requested.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by scottdurow** [comment]
@Nkrb - The use case for returning partial metadata is for performance reasons only - but the OP on this issue is regarding the fact that not all items are currently returned.

My comment was about the Attributes collection being completely missing - which makes it hard to create metadata driven UIs that need info on the Attributes.
