### ISSUE TITLE
Error response body is not parsed when API returns HTTP 400

### ISSUE THREAD

**Issue by nicolausdewitt** [MicrosoftDocs/powerapps-docs#543]
As in my question at https://stackoverflow.com/questions/57272980/response-body-not-parsed-when-api-returns-http-400 the error response does not seem to get parsed when you get a 400

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8601a9f-ca1e-49e0-bdf8-383431829997
* Version Independent ID: 488d4db7-a2de-b47e-5c1c-a28a5f8e046f
* Content: [Xrm.WebApi (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-webapi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-webapi.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by EkoZuluDev** [comment]
Any updates on this one? I would like to present the enduser the useable error message which you can see in the response.

Error function on XRM.WebApi. Returns an empty string as message.

**Comment by Nkrb** [comment]
@nicolausdewitt @EkoZuluDev Thanks for the feedback. We have fixed the issue and pushed it live. Closing the issue. If you need further help, please reopen the issue or create a new issue.
