### ISSUE TITLE
No Size property on customized SharePoint form 

### ISSUE THREAD

**Issue by kayleeg00se** [MicrosoftDocs/powerapps-docs#544]
Not sure if this works differently for SharePoint forms customized in PowerApps, but I am looking to make a form responsive to different sized devices and don't see the Size property on the form screen. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by schneika** [comment]
Is it not planned to make SharePoint Forms Canvas Apps Responsive. There are no Screen-Properties für SharePoint Canvas Apps?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Scale to fit and Size property are not yet available for SharePoint forms using canvas app. For future updates, refer to [What's new in Power Apps](https://docs.microsoft.com/powerapps/whats-new) that includes weekly releases and release notes. You can also submit and vote for feature ideas at [Power Apps Ideas](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
