### ISSUE TITLE
Quote Products?

### ISSUE THREAD

**Issue by crmj** [MicrosoftDocs/powerapps-docs#545]
I tried following these instructions, but instead of passing a list of related Contacts for an Account, I tried Quote Products related to a Quote.

The "Canvas app" option does not appear in the "Controls" tab of the Quote Products subgrid on the Quote form, even when I try re-creating the subgrid from scratch. Is this ModelDrivenFormIntegration feature not supported for Quote Products subgrids?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77eb7373-53da-5bc2-eef6-ac67fc20fcb7
* Version Independent ID: 7e5b6c54-898f-8bca-57af-5dd3922320a7
* Content: [Pass a list of related records as data context with an embedded canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/pass-related-embedded-canvas-app#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/pass-related-embedded-canvas-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/pass-related-embedded-canvas-app.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by iangpgh** [comment]
in-progress

**Comment by iangpgh** [comment]
@crmj Let me know if you were you not able to resolve this question. If you have additional or further questions, please open a new issue.

**Comment by iangpgh** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue. To contact Support, https://powerapps.microsoft.com/support/

**Comment by iangpgh** [comment]
@Mattp123 - Closes #545
