### ISSUE TITLE
Extended language support

### ISSUE THREAD

**Issue by Panoone** [MicrosoftDocs/powerapps-docs#546]
"If this property isn't specified, the user's device setting determines the language."
This has not been our experience. It would seem to default to EN-US when the forms are viewed in SharePoint, despite displaying correctly in PowerApps.

Has language support increased beyond just "EN-us" and "FR"? Applying "EN-AU" appears to work as expected.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c73d9b9-7cb5-f7ee-8c70-227309c9b18b
* Version Independent ID: 5276fa3a-3cf9-70e5-5324-85e0ebc24c56
* Content: [Date Picker control: reference - PowerApps](https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/controls/control-date-picker#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-date-picker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-date-picker.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. Please create a [support service request](https://admin.powerplatform.microsoft.com/support) to investigate the issue.
