### ISSUE TITLE
Manifest requires uses-feature

### ISSUE THREAD

**Issue by kenakamu** [MicrosoftDocs/powerapps-docs#547]
&lt;feature-usage&gt;
         &lt;uses-feature name="WebAPI" required="true" /&gt;
      &lt;/feature-usage&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b78efa0d-09e0-ebac-cce2-19362bdfb602
* Version Independent ID: 000cbd45-8d9a-bb1e-8d9a-a685fe9907b2
* Content: [Web API component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/webapi-control#manifest)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/webapi-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/webapi-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by kenakamu** [comment]
And <uses-feature name="Utility" required="true" />

**Comment by Nkrb** [comment]
@kenakamu Thanks for the feedback. The docs are updated with the latest information and pushed to live. Closing the issue.
