### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by DavidTuke** [MicrosoftDocs/powerapps-docs#548]
This sample needs to be updated - relies on old version of Identity Framework; 

As noted the version above required is old; will be autoupdated (if settings indicate).  Nor is this old version available in nuget; only the current version.

Confusing and wft for everyone who lands on this page.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3da25ded-6c89-69ba-7351-0f04f1c07f79
* Version Independent ID: 6923f7c2-0856-f91f-b17e-e1bef131c5f3
* Content: [Quick Start: Web API sample (C#) (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/quick-start-console-app-csharp#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by takayakawano** [comment]
Requirement of using ADAL ver 2.29 is equal using .NET Framework. It should be apply to .NET Core base technology. Using MSAL instead of ADAL is the best. I'd to get how to call to D365 API from .NET Core Application.

**Comment by rappen** [comment]
Sample and text references the use of ADAL 2.29, but SDK is updated to use later versions.
Ping @JimDaly @MattB-msft

**Comment by Nkrb** [comment]
@DavidTuke Thanks for the feedback. You can find the updated samples for web API [here](https://github.com/microsoft/PowerApps-Samples/tree/master/cds/webapi/C%23/ADALV3WhoAmI) which uses latest ADAL versions. We are in the process of updating the docs with the latest code changes. Closing the issue. If you need further help, please reopen the issue or open a new issue
