### ISSUE TITLE
Missing Strokes & image in the properties

### ISSUE THREAD

**Issue by mosharafMS** [MicrosoftDocs/powerapps-docs#55]
This doc is missing two important properties, Strokes & image. Both are not listed. Also a common request is how to check if there's input on the control. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5eb8d62-9cf6-89e1-1dd3-9557e7318926
* Version Independent ID: 22d7d65c-e91b-e094-5d3a-b91e5741d7a6
* Content: [Pen input control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-pen-input)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-pen-input.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-pen-input.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
Good point, we'll add the documentation for the Image property.  The Strokes property is not well supported (it only works in Internet Explorer and contains the vector representation of the use input) so we are looking to deprecate it.

Currently the best way to find out if there is actual user input is to do something in its OnSelect method.  It is not ideal though as a user can delete the signature and the event would still fire.  We can look to improve this functionality.
