### ISSUE TITLE
Optimising Collections

### ISSUE THREAD

**Issue by ChrisBenJohnson** [MicrosoftDocs/powerapps-docs#550]
I've been wondering if there is any performance improvement from isolating columns in collections using ShowColumns? A typical SharePoint list will have ~18 columns in the background that are pulled into the collection unless ShowColumns is used to exclude them. As collections are stored on the local machine while in use, could this have an impact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7d6ebf-7d17-44ef-4348-354a8332081b
* Version Independent ID: 8427e65c-bf62-86c4-89b8-ecf5f59a890e
* Content: [Optimize canvas-app performance - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/performance-tips#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/performance-tips.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/performance-tips.md)
* Service: **powerapps**
* GitHub Login: @yingchin
* Microsoft Alias: **yingchin**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This would depend on whether functions used with ShowColumns use delegation or not. For more information, please refer to [AddColumns, DropColumns, RenameColumns, and ShowColumns functions in Power Apps](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-table-shaping). You can also each out to the [community forum](https://powerusers.microsoft.com/t5/Forums/ct-p/PA_Comm_Forums) for consultation, or [support teams](https://admin.powerplatform.microsoft.com/support) for any issue.
