### ISSUE TITLE
What is the supported way to access to form's context from a Web Resource HTML

### ISSUE THREAD

**Issue by eduardorivas9** [MicrosoftDocs/powerapps-docs#552]
What is the supported way to access to form's context from a Web Resource HTML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f2e23f-87e2-62be-f107-08c2e99b97e5
* Version Independent ID: 03aa8ec3-a827-95cf-d7cf-f0a014c3484b
* Content: [GetGlobalContext function and ClientGlobalContext.js.aspx in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/GetGlobalContext-ClientGlobalContext.js.aspx.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by DigitalFlow** [comment]
@KumarVivek / @bishalgoswami:
With the deprecation already being public and scheduled in Octobre this year (https://docs.microsoft.com/en-us/power-platform/important-changes-coming), some response in here would be highly appreciated.

How are we supposed to interact with CRM in custom webresources once ClientGlobalContext is gone? 
window.parent.Xrm will not work in cases where the web page also has a button to open the page in a new tab.

**Comment by nzkelvin** [comment]
@DigitalFlow, getContentWindow(), according to the document https://docs.microsoft.com/en-us/power-platform/important-changes-coming

**Comment by nzkelvin** [comment]
> @KumarVivek / @bishalgoswami:
> With the deprecation already being public and scheduled in Octobre this year (https://docs.microsoft.com/en-us/power-platform/important-changes-coming), some response in here would be highly appreciated.
> 
> How are we supposed to interact with CRM in custom webresources once ClientGlobalContext is gone?
> window.parent.Xrm will not work in cases where the web page also has a button to open the page in a new tab.

Use Xrm.Utility.getGlobalContext()?

**Comment by DigitalFlow** [comment]
@nzkelvin:

But where from?
Once ClientGlobalContext is gone, there will be no Xrm namespace in my webresource iframe.
And window.parent.Xrm.Utility.getGlobalContext is not guaranteed to work in webresources that are not on a form, as described in the changes document:

> parent.Xrm.* will work if the HTML web resource is loaded in a form container. It won't work for HTML web resources that are stand alone, or referenced from the site map or any other places

**Comment by Nkrb** [comment]
@eduardorivas9 @nzkelvin @DigitalFlow Thanks for the feedback. We can achieve this using the [getContentWindow](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getcontentwindow) method. We are working on more simplified way to do this, but for now we can use the `getContentWindow` method.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by potsiemj** [comment]
Hi, getContentWindow does work fine for Form contained web resources, but what about for stand alone web resources?  Will parent.xrm continue to work even after the legacy web client is disabled?
