### ISSUE TITLE
getObject of an web resource returns null on UCI

### ISSUE THREAD

**Issue by Sagar486** [MicrosoftDocs/powerapps-docs#554]
Hi,

I am trying to get the Iframe of the webresource which is on the form, on click of a custom ribbon button. I am using the below code. While the below code works as expected on Web client, it is returning null on UCI. Is there any alternate way to do this in UCI? 

`formContext.getControl("WebResourceName").getObject()`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad2ba9f-7a58-1d0b-c71b-917584de5e55
* Version Independent ID: 1f8ac141-53af-a3c9-b5cb-4307f1d20d17
* Content: [getObject (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getobject)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getObject.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getObject.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Sagar486** [comment]
Hi,
Got from feedback from MS.
The Webresource which we are using is in another tab (tab which is not selected when the form loads). So when the form load is completed, we need to switch to the tab where the webresource is placed, then click the ribbon button for the code to work. 

So the solution is either we need to switch to the tab where the webresource is placed before clicking the ribbon button or insert the webresource in the tab which gets selected by default when form gets loaded.
Thanks,
Sagar

**Comment by retthom** [comment]
So has MS come up with a better solution on how to handle this issue.
