### ISSUE TITLE
Refresh Canvas App on Change of a Field

### ISSUE THREAD

**Issue by PoorneshYH** [MicrosoftDocs/powerapps-docs#555]
On Change of a field's value on a D365 Form, we can invoke JavaScript functions. Similarly, if we are allowed to flow some Values to Canvas App, on change of a Field, we can achieve much more functionalities.
I want to build a Duplicate Detection app, which while typing the Company Name, must give them suggestions. But, that is not possible currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84750f73-6dbe-48ed-fd08-10ae6bbb0b9a
* Version Independent ID: 34c48c4a-e8af-c5ff-41dd-95c767ee3e77
* Content: [ModelDrivenFormIntegration control properties and actions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-properties-actions#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-properties-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-properties-actions.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by iangpgh** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.  
Closing this issue.

**Comment by iangpgh** [comment]
@mattp123 - Closes #555
