### ISSUE TITLE
Link 'Chapter 2: Explore' not working

### ISSUE THREAD

**Issue by KVerstuyft** [MicrosoftDocs/powerapps-docs#558]
Hi,

I get a '404'-error when opening the link to 'Chapter 2: Explore'. Can you please fix it? Thank you in advance!

Kind Regards,
Kasper

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce885f5-df3a-127c-3474-b0d1ac7509b4
* Version Independent ID: 8031dba0-83ed-e625-e3ca-c8227c688bc4
* Content: [Unified Interface Playbook - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/unified-interface-playbook#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/unified-interface-playbook.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/unified-interface-playbook.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by KumarVivek** [comment]
@KVerstuyft Thanks for reporting this; this is fixed now. Closing the issue.
