### ISSUE TITLE
Possible inconsistency in folder naming

### ISSUE THREAD

**Issue by denisem-msft** [MicrosoftDocs/powerapps-docs#559]
In the "Packaging your custom components" section, it mentions to create a new folder called Solutions in "the LinearComponent"  folder. However, the beginning of the article tells the user to create a folder called "LinearControl". Are both created, or is this a typo? Also, in step 3 of the same section, it says to use C:\users\LinearComponent, is that assuming the user did create the directory in users folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Implementing Custom Components using TypeScript - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript#feedback)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@denisem-msft Thanks for the feedback. The docs are updated with latest information and pushed to live. Closing the issue.
