### ISSUE TITLE
Great introduction! Some suggestions for improvements...

### ISSUE THREAD

**Issue by sandranz** [MicrosoftDocs/powerapps-docs#56]
A great introduction to PowerApps, looking forward to the rest of the learning. 

It would be great to be able to post questions on the course content on the pages. For example, I would like to know why creating a new app from ShraePoint data only provides a phone layout and not a tablet layout.

It would also be useful to have a Last Modified date stamp on each page. I'm sure PowerApps, like most Office services, will continue to evolve and I think it would be very useful for future readers of these pages to be able to tell if the content is up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dca84a9-627d-45ce-b69c-5a377d290d4a
* Version Independent ID: 98fa778e-0b3d-dfb7-0db5-00bf87bbd4cf
* Content: [Getting started - PowerApps](https://docs.microsoft.com/en-us/powerapps/guided-learning/get-started?tutorial-step=7)
* Content Source: [powerapps-docs/guided-learning/get-started.yml](https://github.com/MicrosoftDocs/powerapps-docs-pr/blob/live/powerapps-docs/guided-learning/get-started.yml)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@sandranz Thanks for your feedback!

- You can create a tablet app from SharePoint data if you start from a blank screen, as [this procedure](https://docs.microsoft.com/powerapps/maker/canvas-apps/data-platform-create-app-scratch#open-a-blank-app) describes.
- Our [documentation topics](https://docs.microsoft.com/en-us/powerapps/maker/index) show when they were most recently updated, but our Guided Learning topics don't. We're still experimenting with what makes the most sense; thanks for telling us that you appreciate that data!
- Issues such as these do appear in the content. For example, feedback on Guided Learning appear at the end of each module. To see this comment, scroll to the bottom of [this page](https://docs.microsoft.com/en-us/powerapps/guided-learning/get-started?tutorial-step=7).
