### ISSUE TITLE
[BUG] entityName doesn't return the name of the entity reference

### ISSUE THREAD

**Issue by allandecastro** [MicrosoftDocs/powerapps-docs#560]
This is not true:  entityName: string. Logical name of the entity to display the form for.

When we use this, entityReference.name is equal to the name of the entity reference.(ex for opportunity : it return the name field (Topic) and not the logical name).

let entityReference = context.parameters.dataSet.records[currentRecordId].getNamedReference();
								let entityFormOptions = {
									entityName: entityReference.name,
									entityId: entityReference.id,
								}
								context.navigation.openForm(entityFormOptions)

So, it will try to open this : https://org.crm.dynamics.com/main.aspx?app=d365default&pagetype=entityrecord&etn=OpportunityName&id=022231a3-5db7-e911-a82e-000d3a365fc2

We can see the "etn=" parameters is not equal to the logical name of the entity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1584e4c-abec-d444-2fa5-cf84dc3b33fe
* Version Independent ID: 89452bfa-cd47-879c-90f5-64e327942b27
* Content: [openForm - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/navigation/openform#feedback)
* Content Source: [powerapps-docs/developer/component-framework/reference/navigation/openform.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/navigation/openform.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by allandecastro** [comment]
Solution : 

								let entityReference = context.parameters.dataSet.records[currentRecordId].getNamedReference();
								let entityFormOptions = {
									entityName: targetEntityLogicalName,
									entityId: entityReference.id,
									openInNewWindow:true
								}						
								context.navigation.openForm(entityFormOptions);

**Comment by ghurlman** [comment]
The docs state that you must pass in the entity logical name, not the display name. As such, try using the `entityRefrence.etn`, rather than `entityReference.Name`. You can see the [updated documentation for `EntityReference` for details](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/entityreference). To get the new PowerApps component framework typing files, update the version for `powerapps-component-framework` in your project's package.json file to `"^1.2.0"`.

**Comment by Nkrb** [comment]
@allandecastro Thanks for the feedback. Closing the issue. Please reopen the issue, if you didn't get the information you are looking for.
