### ISSUE TITLE
Incomplete Content

### ISSUE THREAD

**Issue by bkpearson** [MicrosoftDocs/powerapps-docs#561]
[Learn how to add and configure a control].(../add-configure-controls.md)

Appears to be a bad link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c68b4c33-12f9-3b26-5508-7173fe207ada
* Version Independent ID: 0451a3c0-7d56-63b3-e8ff-acc33d6c5daf
* Content: [Attachments control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-attachments#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-attachments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-attachments.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. The link is functional.
