### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by highpowerxh** [MicrosoftDocs/powerapps-docs#563]
>The following examples show how you can use connection strings for connecting to **on-ine** deployments and authentication scenarios. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8213b8-93bc-dee0-5b82-973db16f03fa
* Version Independent ID: 161512ac-81c1-4163-20e1-e440497d2e24
* Content: [Use connection strings in XRM tooling to connect to Common Data Service (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by KumarVivek** [comment]
@highpowerxh Thanks for reporting this issue. It's fixed now, and will be updated in our next daily live publish. Please check back in a day.
Closing the issue.
