### ISSUE TITLE
Reset Property - 2228723

### ISSUE THREAD

**Issue by bkpearson** [MicrosoftDocs/powerapps-docs#564]
The Reset property is not referenced here. Should it be? If so, what is the behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e663e437-2bc9-980f-9ba6-6eeab01ee9a4
* Version Independent ID: ae7da14b-2234-2815-9fd1-272a0984f129
* Content: [Attachments control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-attachments)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-attachments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-attachments.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by chmoncay** [comment]
Hi there, sorry for that.  I've updated the documentation.  The attachments control is resettable.  You can use a variable to flip a boolean property against the Attachments Reset property, or use the Reset function : _Reset(AttachmentsControlId)_ to reset the control.  Resetting the control reverts all changes to the attachments control returning it to the previously saved state.
