### ISSUE TITLE
multiselect entities for export no longer available?

### ISSUE THREAD

**Issue by svendeco** [MicrosoftDocs/powerapps-docs#565]
2 weeks ago the procedure for bulk export was still available, today the multiselect option for entitities seems gone (tried in edge and chrome, on 2 different tenants). That is very annoying as it will require more manual work to export data from CDS!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d19d1c-c40c-93ad-53d6-f1b7a7415978
* Version Independent ID: a5d8f682-b541-5dde-c882-1461cc9d5ecb
* Content: [Import or export data from Common Data Service - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-import-export#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-import-export.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-import-export.md)
* Service: **powerapps**
* GitHub Login: @sabinn-msft
* Microsoft Alias: **sabinn**

**Comment by iangpgh** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.  
Closing this issue.

**Comment by iangpgh** [comment]
@mattp123 - Closes #565
