### ISSUE TITLE
No syntax highlighting in "Example: Use window.open to open a new window"

### ISSUE THREAD

**Issue by CarlosZaldivar** [MicrosoftDocs/powerapps-docs#566]
The language should be probably set to JavaScript, not jscript

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92166951-1f53-3590-79f6-addfa14027b4
* Version Independent ID: e5509479-c394-fe54-2c51-b8c2b8c53dac
* Content: [Set field values using parameters passed to a form (model-driven apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/set-field-values-using-parameters-passed-form#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/set-field-values-using-parameters-passed-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/set-field-values-using-parameters-passed-form.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@CarlosZaldivar Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
