### ISSUE TITLE
TimeZoneOffset

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/powerapps-docs#568]
This page mentions you can use TimeZoneOffset and points you to a link that has more info, but that page doesn't seem to have much info on TimeZoneOffset either.  Would be good to have some examples for converting UTC to Local Time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198e7d8c-10ac-b34c-62e5-e9255fec5f77
* Version Independent ID: d47a7435-58fa-7493-82f2-66fba23ba501
* Content: [DateAdd, DateDiff, and TimeZoneOffset functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-dateadd-datediff)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-dateadd-datediff.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-dateadd-datediff.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
I have update the article to point to the data types page as well which has more information in general on date/times including time zones.  There is an example at the bottom of this article that shows the conversion.
