### ISSUE TITLE
SQL and guest access?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#569]
I don't see "SQL" shown in the connector list in regards to Guest Access. How is this handled?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fb8dba-da1c-6845-d301-c3b18a6b98ef
* Version Independent ID: a5d1fd66-fe5b-f52d-47de-6af3c71928f7
* Content: [Share a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#share-with-guests)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by tapanm-MSFT** [comment]
@SeaDude  All connectors that do not perform Azure AD authentication of any type supports guest access. 
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#share-with-guests
The SQL connector and authentication types are listed in https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-azure-sqldatabase that explains authentication for cloud (SQL authentication) and on-premises (Windowsor or Basic). The guest access documentation in https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#share-with-guests explains how apps can be shared with guests. 

It might also be useful to read https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/app-from-azure-sql-database regarding authentication and implicit access.
