### ISSUE TITLE
Lots of typos

### ISSUE THREAD

**Issue by aecarr2** [MicrosoftDocs/powerapps-docs#570]
Ex. Code in this sections
Ex. Remember that we have three functions in our JavaScript code to be associated with approprite events in the form.
Ex. You will see a notification conytaining your user name that will automatically disappear in 5 seconds.

Please check entire page for typos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd626b7-e922-eecd-983c-3823afff4e04
* Version Independent ID: 376d0fc1-294a-660a-ea09-7de12f6dbe18
* Content: [Tutorial: Write your first client script in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@aecarr2 Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
