### ISSUE TITLE
SharePointIntegration control for OnPremise version of SharePoint

### ISSUE THREAD

**Issue by iamguptarishi** [MicrosoftDocs/powerapps-docs#571]
The article states that SharePointIntegration control is available if form is running in SharePoint. Is it available for On premise version of SharePoint 2019 as well? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2000b4-4917-deb6-148f-98c97691f4fb
* Version Independent ID: 241ca44d-5ed2-335a-ae0e-78c3d90b27e2
* Content: [Understand SharePoint forms integration - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-form-integration#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-form-integration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sharepoint-form-integration.md)
* Service: **powerapps**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can use the gateway to connect to on-premises sources for this. More information: [On-premises data gateway](https://docs.microsoft.com/powerapps/maker/canvas-apps/gateway-management)
