### ISSUE TITLE
Documentation for Plugin C# handlers

### ISSUE THREAD

**Issue by michaelmmcrae1** [MicrosoftDocs/powerapps-docs#573]
Where is this answered in Microsoft documentation, or any similar question:

- If I want to register against SetStateDynamicEntity of CRM entity Account, what will be contained in the Dynamics-provided plugin context InputParameters? What type will the "Target" be? (or will "Target" be empty? and instead need to look for a "EntityMoniker"?) Where do I get the newly-set State field?

Is there a reason there's no documentation in the form "if doing this message/event in the pipeline, here's what the context gives you"?

**Comment by JimDaly** [comment]
Your feedback can be routed if opened in the context of a specific topic. It is always best to open an issue in the context of a specific topic.


The answer is that it depends on the message. You need to understand how the input parameters are included within the OrganizationRequest class and how they are defined within the various *Request classes that inherit from OrganizationRequest.


The information you are looking for can be found here: [Understand the execution context > InputParameters](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/understand-the-data-context#inputparameters) and follow the link there to [Use messages with the Organization service](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/use-messages)


Generally, they are the same as the names of the properties of the derived classes. There are some variations for the Output parameters and they are described here: [OutputParameters > Understand the execution context](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/understand-the-data-context#outputparameters)
