### ISSUE TITLE
Page typo

### ISSUE THREAD

**Issue by tw1tch01** [MicrosoftDocs/powerapps-docs#574]
Second paragraph, "...can use templates to create a canvas app],..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be6dda1c-852e-7f8b-48b5-e0c2a6e6711a
* Version Independent ID: 19b9ed6c-04dc-5e44-48a6-75ef12f91028
* Content: [How do I find and run apps in PowerApps? - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/#feedback)
* Content Source: [powerapps-docs/user/index.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/index.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mkaur**

**Comment by mduelae** [comment]
@tw1tch01 than you for your feedback. I fixed the typo. The topic will republish and go live by end of day today.

Thanks,
Mints
