### ISSUE TITLE
Issue with Location sharepoint list column type?

### ISSUE THREAD

**Issue by adsi4nt** [MicrosoftDocs/powerapps-docs#576]
Is there an issue when using a location column type? (https://techcommunity.microsoft.com/t5/SharePoint/Add-Location-Details-to-SharePoint-Data-and-Content/m-p/284875) I am testing an app that ties to a sharepoint online list which has the location, and also displays the street, city, state & zip. The main location isn't showing up on the 'add item' default screen. It shows up on the display and even when marked as editable, it isn't. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f32ea1-9e25-c4db-b8c8-df8194517bee
* Version Independent ID: c040bfac-c0df-e1d9-70da-39be48c79209
* Content: [Overview of the SharePoint connection - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-sharepoint-online#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-sharepoint-online.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-sharepoint-online.md)
* Service: **powerapps**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please work with the support teams for any issue using a [support ticket](https://admin.powerplatform.microsoft.com/support).
