### ISSUE TITLE
Can't get token with ADAL

### ISSUE THREAD

**Issue by EthanWang90** [MicrosoftDocs/powerapps-docs#578]
[Your official doc](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth) uses this UserCredential with userName and Password:
![image](https://user-images.githubusercontent.com/40749902/63148317-ed263200-c054-11e9-9f31-598d4ac288ec.png)
However, the actual class doesn't have this overload no matter in v5+ or v3+, well, the closest is in v3, but is not receive string password. I tried to only pass userName, error:
![image](https://user-images.githubusercontent.com/40749902/63148669-08457180-c056-11e9-87b0-3712b4808a1a.png)

**Comment by phecke** [comment]
@EthanWang90 The topic was updated to use MSAL and is now correct. Thanks for the feedback.
