### ISSUE TITLE
Question about multi-tenancy S2S auth docs

### ISSUE THREAD

**Issue by dazhao-msft** [MicrosoftDocs/powerapps-docs#581]
Hi there,

I notice that there are two series of docs about multi-tenancy S2S auth:

1. https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-multi-tenant-server-server-authentication.md

1. https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/blob/master/ce/developer/use-multi-tenant-server-server-authentication.md

I have a few questions about the docs:

1. The contents seem to be almost the same. I guess it's because both PowerApps and Dynamics Customer Engagement are powered by CDS, and this topic is actually about CDS, so they are almost the same. Can you please confirm?

1. Although the contents are close enough, is there any subtle difference I should pay attention to? We're building an application targeting the users who have data in CDS, no matter the data is created by Dynamics or PowerApps.

1. Is there any plan to consolidate these two series of docs into one?

Thanks in advance.

**Comment by phecke** [comment]
@dazhao-msft Yes, the two topics should be the same. We are migrating the content to CDS under PowerApps. I expect the migration effort from Customer Engagement to PowerApps/CDS to complete near the first half of October.

I would recommend that you follow and develop a single-tenant application and upgrade it to multi-tenancy. For more info see [https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication). This is a simpler approach for app development.
