### ISSUE TITLE
Excel Data Connection

### ISSUE THREAD

**Issue by SamEakin** [MicrosoftDocs/powerapps-docs#584]
If you are using an Excel table as a data source;
make sure you don't have the source excel file open when connecting to your app or it will not connect properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ceef3b9-3d95-1e2d-8331-503d63df7eed
* Version Independent ID: 5f8fc1bc-e453-0c5e-aa05-eddb56587912
* Content: [Overview of the cloud-storage connection - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/cloud-storage-blob-connections)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/cloud-storage-blob-connections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/cloud-storage-blob-connections.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. That is correct, if an Excel file is open for editing, app using the file may not be able to save due to file being locked. This also results in an error message within the app explaining the scenario.
