### ISSUE TITLE
Some of the data types are not available when a New Field is being created from Form Designer

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#585]
The following data types are not available when a New Field is being created from Form Designer
- Autonumber
- Customer
- Image
- Lookup
- Mulit Select Option Set
- Option Set
- Two Options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63ad3991-5f3a-4349-6974-9306225a4090
* Version Independent ID: 61ef62e7-9623-e0d4-cb8d-9733549a8744
* Content: [Add, move or delete fields on a form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-move-or-delete-fields-on-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-move-or-delete-fields-on-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/add-move-or-delete-fields-on-form.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by iangpgh** [comment]
In _Create a new field on the entity when editing a form_ section, a Note was added to address this behavior and inform user that some field types are not available when you create a field from within the form designer. If a field type you want is not available, you can follow the steps outlined in **Create and edit fields for Common Data Service using Power Apps portal**.

**Comment by iangpgh** [comment]
Thanks for your feedback. For product-related feedback, visit https://experience.dynamics.com/ideas/.  
Closing this issue.

**Comment by iangpgh** [comment]
@mattp123 - Closes #585
