### ISSUE TITLE
When will this be supported in web browser

### ISSUE THREAD

**Issue by DavidBurela** [MicrosoftDocs/powerapps-docs#587]
Not having this control work in the web browser limits the capabilities of apps.
But importantly it makes it much more difficult to develop an app, as you can not test on your desktop as you built.  For every change you need to save, deploy, reload on a device to test.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7944b4d0-c3be-afa0-4af1-21c9c27b56e2
* Version Independent ID: c2ca93fd-9817-8300-fcc4-a6999659e0a2
* Content: [Barcode-scanner control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-new-barcode-scanner)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. You can check the upcoming [release plans](https://docs.microsoft.com/power-platform-release-plan) for feature updates. For new updates to features, you can also submit the idea or vote for one using the [Power Platform Community Ideas](https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas).
