### ISSUE TITLE
Broken "Sample: Azure aware custom plug-in" link

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerapps-docs#588]
Under the "See also", a link to "Sample: Azure aware custom plug-in" leads nowhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4dfc2a3-e9b6-7c53-5bc9-a7e9eda29618
* Version Independent ID: 1f4b68f8-704a-7c6a-fc2b-2cee577d8e70
* Content: [Use webhooks to create external handlers for server events (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-webhooks#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/use-webhooks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-webhooks.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
@ashlega Thanks for creating this issue. The broken link will be fixed soon.

Closing this issue now.
