### ISSUE TITLE
Add Attachments with camera

### ISSUE THREAD

**Issue by hassannawaz1** [MicrosoftDocs/powerapps-docs#591]
i have a problem is that when i add attachment using camera  from new form of app the app navigates on my main screen and new form screen closed the issue from new release of powerapps Moblie App version. i am uisng i phone 8s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b83052-49f1-5a09-7aba-9f0d5046d850
* Version Independent ID: 0289a85b-fc50-bf14-4474-31d434e16e20
* Content: [Common issues and resolutions for PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/common-issues-and-resolutions#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/common-issues-and-resolutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/common-issues-and-resolutions.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@hassannawaz1  Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ 

Closing this issue.
