### ISSUE TITLE
IP Address in South Ameriaca is not correct

### ISSUE THREAD

**Issue by mengpl-msft** [MicrosoftDocs/powerapps-docs#593]
The list of IP addresses PowerApps in South America connects to is not correct. From my measurement, there is at least

- 13.68.31.193
- 13.68.137.177
- 13.68.137.177
- 52.114.74.45
- 104.65.177.20
- 191.239.250.16

that are not reflected on that list. Please update that list.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, the IP addresses have recently been updated. Please use the latest documentation.
