### ISSUE TITLE
Property not return in JSON response unless explicitly specified in $select.

### ISSUE THREAD

**Issue by chanhlonglu** [MicrosoftDocs/powerapps-docs#594]
In [**Incident**] entity, there's a field called [**responsiblecontactid**], this field/property does not appear in JSON response when call to [Organization URI]/api/data/v9.1/incidents.
The [responsiblecontactid] property **only appear in JSON response when explicitly specified in $select=_responsiblecontactid_value**.

I thought **not using $select should return ALL fields/properties**.  But the [responsiblecontactid] property in [incident] entity is not return in the response unless explicitly specified in $select.  
Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#apply-system-query-options)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
@chanhlonglu Thanks for creating this issue. I have asked the feature team to look into this and will get back to you as soon as I hear from them.

**Comment by susikka** [comment]
@chanhlonglu `responsiblecontactid` attribute is deprecated. Please use `primarycontactid` in its place.

Closing this issue now.
