### ISSUE TITLE
Unicode for diacritical character.

### ISSUE THREAD

**Issue by chanhlonglu** [MicrosoftDocs/powerapps-docs#595]
Is there an explanation why JSON response return unicode for non-English alphabet instead of actual diacritical character?

For example: JSON return **Bob Pal\u010di\u010d** instead **Bob Palčič**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#apply-system-query-options)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
@chanhlonglu Thanks for creating this issue. Will reach out to the feature dev team to know why this is and let you know.

**Comment by susikka** [comment]
@chanhlonglu I'm not able to repro this behavior in my instance. Would it be possible for you to share the exact query you are using and the response you see ?

**Comment by JimDaly** [comment]
Also, Please try to reproduce using the instructions here: [Set up a Postman environment](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/setup-postman-environment)

It sounds like an encoding issue. How are you seeing this?
Postman should show the actual text values sent and returned.

**Comment by chanhlonglu** [comment]
You can close this issue.  As the application I worked on doesn't have encoding feature that's why I have this issue.

If interested to seen this encoding issue in Postman, choose the **raw** response instead of json.  The raw response will show unencoded character.
