### ISSUE TITLE
What CSS library is used to display the powerapps homepage?

### ISSUE THREAD

**Issue by Joaveinz** [MicrosoftDocs/powerapps-docs#598]
Hello everyone,

As the title says, I am looking for the css library that has been used to show the cards on the powerapps docs starting page.

I tried to start this page up in Localhost, but it shows very differently:

![image](https://user-images.githubusercontent.com/54300414/63731518-1f8d2600-c8c4-11e9-86aa-12df49628711.png)

Please let me know, we are looking at implementing a similar documentation system for our documentation.

Also let me know if this needs to be discussed elsewhere, as this is technically not an "issue" in the Github sense.

Thanks in advance

**Comment by ragavanrajan** [comment]
@Joaveinz . Based on the docs site. Docs are using https://github.com/necolas/normalize.css and customized CSS.

**Comment by Joaveinz** [comment]
Thanks @ragavanrajan 

I ended up scrapping the idea of directly copying this. I am working with the docfx-seed instead and getting inspiration from other implementations of this.
