### ISSUE TITLE
Many-to-Many relationship, how to work with in Canvas and Excel add in?

### ISSUE THREAD

**Issue by YahyaManasrah** [MicrosoftDocs/powerapps-docs#60]
Many-to-Many relationship works fine with Model Driven Apps, but it is not accessible in Canvas Apps or via Excel add in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 527811f6-98e9-d6fd-ea85-5936f9a3cfaa
* Version Independent ID: be8bb009-0e42-fecc-38f4-f73a4746d088
* Content: [Create a relationship between entities by using a lookup field - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-entity-lookup)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-entity-lookup.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-entity-lookup.md)
* Service: **powerapps**
* GitHub Login: @clwesene
* Microsoft Alias: **clwesene**

**Comment by lancedMicrosoft** [comment]
Many to Many relationships are a built-in Common Data Service (CDS) feature.  Excel does not support this feature.  If you would like to use the many to many feature you can move / import your data from Excel into CDS and take advantage of it there.

**Comment by lancedMicrosoft** [comment]
You can read more about it here.  https://powerapps.microsoft.com/en-us/blog/new-cds-capabilities-for-canvas-apps-enter-preview/

**Comment by Mattp123** [comment]
@YahyaManasrah  Thanks for your feedback. Since this feature isn't available and subsequently not an issue with the topic, you can visit https://powerusers.microsoft.com/t5/PowerApps-Ideas/idb-p/PowerAppsIdeas to make a suggestion to add it.
Closing issue.
