### ISSUE TITLE
What are normal/valid options for the "parameters" param object?

### ISSUE THREAD

**Issue by michaelmmcrae1** [MicrosoftDocs/powerapps-docs#600]
For example... if I want to call a CRM Action for the Opportunity entity. How do I pass the Opportunity/target to that CRM Action? I assume it has to go inside "parameters" object, but what should the property key be, and what's the value's data type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a261db5-f03e-8100-f9b9-592ba9a34cea
* Version Independent ID: 281480d2-01b3-1488-9f00-9e82fd6d93ef
* Content: [invokeProcessAction (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/Xrm-Utility/invokeProcessAction#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/invokeProcessAction.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/invokeProcessAction.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by sudipmandal** [comment]
Any updates on this?

**Comment by Nkrb** [comment]
@michaelmmcrae1 @sudipmandal Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue.
