### ISSUE TITLE
Examples needed: CRUD operations using execute

### ISSUE THREAD

**Issue by bananamufu** [MicrosoftDocs/powerapps-docs#602]
Please provide examples on each CRUD operation and how to perform them using the execute method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: badde453-a02f-72e1-22dd-3be9ed53a4c0
* Version Independent ID: 1904f78b-93c7-86f8-d6f2-96c4e6041f11
* Content: [Xrm.WebApi.online.execute (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online/execute#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@bananamufu We now have CRUD samples; thanks to a submission from @mehmetseckin .

Closing the issues now.

**Comment by nerdifand** [comment]
crud example not working for me:

i get: Cannot read property 'account' of null
maybe because i have my html in the configuration page of the solution:
however, <script src="ClientGlobalContext.js.aspx" type="text/javascript"></script> is included
i have no more ideas
