### ISSUE TITLE
No Required Properties

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#603]
The above documentation makes it appear as though there are no required properties of the lookupOptions object. However, in my experience, both allowMultiSelect and entityTypes must have values in order for the call to Xrm.Utility.lookupObjects to function properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by NathanSushi** [comment]
Agreed, I've run in to the same issue using the UCI.

**Comment by Nkrb** [comment]
@devlinl Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
