### ISSUE TITLE
Getting -60 error in request.response.body when exporting millions of records through batch operation

### ISSUE THREAD

**Issue by anandkgpt03** [MicrosoftDocs/powerapps-docs#608]
I have a query @susikka
Suppose I am executing long-running two or more parallel batch request exporting millions of records through each of them.
Is it necessary to provide unique_identifier to all the parallel request or they can use same unique_identifier?
What's the possible problem can occur? 
And sometimes I am getting -60 as request.response.body. What does this error mean?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please raise a support [service request](https://admin.powerplatform.microsoft.com/support) for this issue and to investigate.
