### ISSUE TITLE
issue with setTimeout in the example

### ISSUE THREAD

**Issue by gilmeyer** [MicrosoftDocs/powerapps-docs#609]
I have tested this sample on my vanilla, but it only worked fine when using the setTimeout like setTimeout(getAttributeValue, 1000,executionContext);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6410f3ff-5919-8af3-6529-33f4d2bc8a37
* Version Independent ID: d4da4fce-f866-f543-866f-49be97ad2cce
* Content: [isLoaded (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-quickforms/isloaded)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-quickForms/isLoaded.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-quickForms/isLoaded.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@gilmeyer Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
