### ISSUE TITLE
DEscription Column is the same for validate with single column and validate a compl;ete record

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/powerapps-docs#61]
Hi

The Description for Validate with a single column and Validate with a complete Record are the same.

Should thye be ?

Regards

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b8ddae-5537-900d-7800-77badbb3486f
* Version Independent ID: 40400e75-73fe-31a8-0a7b-bd55c4fe3f2d
* Content: [Validate function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-validate)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-validate.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-validate.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
@NPrice99 We've updated the doc. Thanks for the heads up!
