### ISSUE TITLE
Success Callback Object is incorrect

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#612]
The documentation above, indicates that the Success Callback is passed an array of objects containing "entityType", "id", and "name"... However, this is incorrect.

The objects in the array have the following properties:
activityPartyId
ambiguousRecordsXml
category
data
displayClass
effort
exchangeEntryId
id
keyValues
name
onclick
processId
processTimestamp
resourceSpecId
selected
type
typename
values

Even if using some of these unspecified properties is unsupported, there is no property called entityType. The documentation above should be changed to "typename".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by devlinl** [comment]
An update: The above is true for the classic Web Client, not the Unified Interface. The Unified Interface has the return object described by this documentation.

**Comment by Nkrb** [comment]
@devlinl Thanks for the update. Closing the issue.
