### ISSUE TITLE
See Promise and File link incorrect

### ISSUE THREAD

**Issue by davidyack** [MicrosoftDocs/powerapps-docs#613]
File links to Mozilla's site - this returns an array of ComponentFramework.FileObject[] and that doesn't appear to be documented anywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bbfa764-a342-a043-c087-6b1817df5631
* Version Independent ID: cb452a40-83e1-fbc6-253e-c2af20cb4257
* Content: [PickFile - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/device/pickfile#feedback)
* Content Source: [powerapps-docs/developer/component-framework/reference/device/pickfile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/device/pickfile.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@davidyack Thanks for the feedback. We have updated the docs and published to live. Closing the issue.
