### ISSUE TITLE
Use a filtered list view for the Gallery screen

### ISSUE THREAD

**Issue by Benzin42** [MicrosoftDocs/powerapps-docs#614]
On my SharePoint List, I have created a view which excludes the closed issues in my list.
I would like to use that filtered list for the Gallery, rather than the complete list.
I have not managed to find instructions for how, being new to this PowerApps tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db3abb67-d86b-af45-96d7-31e0629be635
* Version Independent ID: 86df1289-efd8-8792-9514-5284ebcb88d8
* Content: [Tutorial - Customize a gallery in a generated app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-layout-sharepoint#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-layout-sharepoint.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-layout-sharepoint.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by Benzin42** [comment]
I have also tried to use the function field on the Canvas of the Gallery, but as soon as I add a filter criteria, it fails to show anything at all...
Perhaps it's not possible to filter on columns not visible in the Gallery?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can use [filter function](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-filter-lookup) with formula such as the following example: <br>
```Filter(Issues, 'Issue Status' = "Active")``` <br>
In this example, the 'Issues' is the data source connecting to a SharePoint list, 'Issue Status' is the column name and 'Active' is the status of an issue (for example, other status' are Closed, or Inactive).  <br>
If there are any issues, please reach out to support teams with a [support service request](https://admin.powerplatform.microsoft.com/support) to investigate and help you fix.
