### ISSUE TITLE
Download the app - link not working

### ISSUE THREAD

**Issue by birchenall** [MicrosoftDocs/powerapps-docs#616]
The link seems to go to an inactive page, do you have the file for the download?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @yijw2017
* Microsoft Alias: **yijw**

**Comment by yijw2017** [comment]
Hi, I just tested the link for downloading the app package, it works fine for me. Could you please try with a different browser to see if the issue is still reproducible?
Thank you.

**Comment by birchenall** [comment]
Might have been an issue with my workplace firewalls.
