### ISSUE TITLE
list emails in a conversation view does not work

### ISSUE THREAD

**Issue by timothybohte** [MicrosoftDocs/powerapps-docs#617]
We're on the Early opt-in to 2019 release wave 2 and were looking forward to that this feature is also added to Unified Interface. Unfortunately it doesn't work after following the instructions on this page. I can select the box on personal settings, but al e-mail threads (I've checked replies and forwards) are still listed as seperate e-mails in UI, while they are listed as a thread in classic interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa09a110-d91d-b551-3cc8-5c6885857e65
* Version Independent ID: 3e787680-48f9-a3c6-73be-667be545e562
* Content: [Add an appointment, email, phone call, notes or task activity to the Timeline in a Model-driven app - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/add-activities#add-an-email)
* Content Source: [powerapps-docs/user/add-activities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/add-activities.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
@timothybohte thank you for the feedback. This seems like a support issue. Please contact the support team for further assistance on this issue.

Thank you,
Mints
