### ISSUE TITLE
Admin list error [Help Desk sample] 

### ISSUE THREAD

**Issue by GPZAR** [MicrosoftDocs/powerapps-docs#62]
Hi I am struggling to login as admin, ever after updating the admin list as set out in this guide. Please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by caburk** [comment]
Can you provide more detail? One possibility is often companies have two email formats for the same user, where one is an alias. For example, firstName.lastName@companyName.com and firstNameLastInitial@companyName.com. If this is true for you, try adding both. Also check for letter capitalization.

**Comment by GPZAR** [comment]
Thanks for the feedback, is there any way I could confirm if I am using the correct format?

**Comment by caburk** [comment]
It's using the MyProfile.Mail function to check your email matches one from the admin list. To check what is returned by the connector, simply insert a label on any screen, then set the "Text" property to "MyProfile.Mail." This will return the proper email to set on the Admin list.

**Comment by GPZAR** [comment]
Thanks it worked
