### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by BrianLevenson** [MicrosoftDocs/powerapps-docs#620]
This is no longer the publication process and should be updated to reflect the current state. Partners sign up through Partner Center, and the AppSource form has been retired. Registration happens here: aka.ms/joinmarketplace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a771ce0b-c24d-d9e1-c7bd-8aba7c77e3c1
* Version Independent ID: 16927105-150c-cd9f-3b82-9e1d0125b54d
* Content: [Step 1: Fill the app submission form on AppSource (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/fill-app-submission-form-appsource)
* Content Source: [powerapps-docs/developer/common-data-service/fill-app-submission-form-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/fill-app-submission-form-appsource.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@BrianLevenson Content updated. Thanks.
