### ISSUE TITLE
Only the creator of the powerapps & flow receives mail notification

### ISSUE THREAD

**Issue by ayoakpata** [MicrosoftDocs/powerapps-docs#621]
How to give admin rights to another user and enable them to receive an email notification?
when a new user submits a ticket, the user does not receive a mail notification and is been notified of the processes

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please raise a support [service request](https://admin.powerplatform.microsoft.com/support) to investigate notification issue.
