### ISSUE TITLE
Help desk not sending email from case not started notification

### ISSUE THREAD

**Issue by speakerjunky** [MicrosoftDocs/powerapps-docs#622]
When logging in as a user and creating a ticket, emails aren't sending to the email specified in the "to" field in case not started notification.  It worked the first time under the it email, but when I changed the email to my email it didn't work.  I changed it back to the it email and it's still not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @yijw2017
* Microsoft Alias: **yijw**

**Comment by speakerjunky** [comment]
Ok nevermind.  It starting working.

**Comment by ayoakpata** [comment]
Hi Will Van Usey, how were you able to solve this issue please? Other users
do not get meals when they log their complains but I do get mail when I log
a complain, as the owner...

**Comment by speakerjunky** [comment]
I noticed you have to click the check mark once you submit the ticket.  So in the message that pop's up at the end I included "Please click the check mark to continue".

**Comment by ayoakpata** [comment]
Will look into it and revert back as soon as possible. Thank you so much

**Comment by ayoakpata** [comment]
Hi Will Van Usey,

I've looked into it, all users receive emails now. But I noticed the Assign
to field in

the Admin View is not dropping down for the Admin to edit, any help, thanks

**Comment by ayoakpata** [comment]
I just had to refresh the data source for it to work...

Thank you for your time

**Comment by j0hnnyma** [comment]
im having the same issue but it seems that the flow isnt running right. Under advanced settings for sharepoint  get items there is an id eq "get items" and that is asking for a query in order to run. Anyone have any insight ?
