### ISSUE TITLE
API Limit

### ISSUE THREAD

**Issue by jsullboy** [MicrosoftDocs/powerapps-docs#624]
Since there is an API limit on the Web API it should say in this documentation if the S2S account is subject to this restriction or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e78807-9882-0dfd-932d-02c41cc9c239
* Version Independent ID: 43f5abc9-9852-1195-9b7f-8ea90a64128c
* Content: [Build web applications using Server-to-Server (S2S) authentication (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-web-applications-server-server-s2s-authentication#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/build-web-applications-server-server-s2s-authentication.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-web-applications-server-server-s2s-authentication.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by paulliew** [comment]
There are limits to the number of requests the application user account can call - please see https://docs.microsoft.com/en-ca/power-platform/admin/api-request-limits-allocations#non-licensed-usersapplication-users  
S2S doc is updated to reflect this limit.
