### ISSUE TITLE
Date picker resizing problem

### ISSUE THREAD

**Issue by hpkeong** [MicrosoftDocs/powerapps-docs#63]
When you drag the date picker box to the right to reduce the input area, the picker will become smaller. It happened only last week.
Please verify. Tq

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4fb137e-6a79-e538-a90a-0d17c5cfb8f7
* Version Independent ID: 3d725d06-378d-4540-4fc4-6959d00eaf9e
* Content: [Date Picker control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-date-picker)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-date-picker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-date-picker.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
@hpkeong Thanks for your feedback!
@fikaradz Any ideas?

**Comment by fikaradz** [comment]
This is a bug which we have fixed.  We expect it to roll out to production in about 3 weeks.

**Comment by hpkeong** [comment]
Thanks so much for the quick fix. Appreciate
