### ISSUE TITLE
Distinct().Result

### ISSUE THREAD

**Issue by dmypstl** [MicrosoftDocs/powerapps-docs#630]
Make it clear that Distinct() returns a one-column table with column named "Result". 

Your example on this page should say:
Distinct(Employees, Department).Result

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cd6eb9-a7fe-aac7-ac9b-ab7430d57a8f
* Version Independent ID: cd91bd3a-e580-1204-3ed5-2c429bce0c6f
* Content: [Distinct function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-distinct#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-distinct.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-distinct.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the suggestion.  I took the opportunity to expand the examples as well.
