### ISSUE TITLE
Format error in index.ts file

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/powerapps-docs#631]
The _value property is declard as a number : 
`private _value: number;`
But then, it is defined using the context, that can be null : 
`context.parameters.sliderValue.raw;`
As a result, an error is displayed  "number | null" is not assignable to type number

**Comment by Nkrb** [comment]
@Nicokirr Thanks for the feedback. You can use the following line of code to get rid of the issue. 
this._value = context.parameters.sliderValue.raw ? context.parameters.sliderValue.raw : 0;
