### ISSUE TITLE
OAuth/Certificate Based Generic Service Connections

### ISSUE THREAD

**Issue by TclasenITVT** [MicrosoftDocs/powerapps-docs#632]
Hello Microsoft,

could you explain how to use a non-interactive User to connect to the CRM? Just replacing the username with the clientId and the password with a clientSecret inside the Generic Service Connection does not seem to work.
P.S. Maybe you should define a Dynamics 365 CDS/PowerApps/CRM Service Endpoint Type to allow you to switch on the different types OAuth/Certificate/Office365. Then proceed and use that instead of the generic one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e92c215-b337-b864-3fee-b9542e4e30c8
* Version Independent ID: 8f26538c-5863-6746-8c2c-ee4438165da4
* Content: [Build tools tasks - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tasks)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tasks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by lokiRT** [comment]
This doesn't appear to be an option currently to use an application user.  With the recent updates in the SDK, is this support coming soon?

**Comment by mikkelsen2000** [comment]
Correct, there is no option to use an application user currently. We are planning on shipping an update to support this later in the year (October/November timeframe)

**Comment by vcbblog** [comment]
Any update on this, it seems that a new version have been released but I didn't find any way to make it work with oAuth

**Comment by mathiasbl** [comment]
Any news?

**Comment by lokiRT** [comment]
Has there been an update on when S2S auth will be supported?

**Comment by rappen** [comment]
@mikkelsen2000 I think an update to this question would be appreciated :)

**Comment by mikkelsen2000** [comment]
Thanks for help getting my attention on this - much appreciated! S2S based auth didn't make it into the release earlier this year. Is slated for June 1
