### ISSUE TITLE
allowMultipleFiles does not let you pick multiple files

### ISSUE THREAD

**Issue by alano444** [MicrosoftDocs/powerapps-docs#633]
Using the mobile/tablet app, I have Xrm.Device.pickFile working fine for a single file, but when I use the pickFileOptions for allowMultipleFiles, I cannot choose multiple files (I can still only choose I file).

Code
var pickFileOptions = {};
pickFileOptions.allowMultipleFiles = true;

Xrm.Device.pickFile(pickFileOptions).then( ...

Please note that you can pick multiple files if you use the web client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79ed47be-b625-a433-4456-3251de4bf7c6
* Version Independent ID: 16728e22-98b9-6ce3-bdbc-5d68f50cfb20
* Content: [pickFile - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-device/pickfile#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Device/pickFile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Device/pickFile.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@alano444 Can you confirm if you are still facing the issue.

**Comment by Nkrb** [comment]
@alano444 
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
