### ISSUE TITLE
Does not work from within Xrm.Device.pickFile

### ISSUE THREAD

**Issue by alano444** [MicrosoftDocs/powerapps-docs#634]
I have used the Xrm.Utility.showProgressIndicator many times and it is a great addition.  But it does not get displayed if I call it from within Xrm.Device.pickFile.  My scenario, I want the user to be able to select multiple files and have them attached as notes to an entity.  While the X files are being uploaded I would like to be able to use the Xrm.Utility.showProgressIndicator to show the user how many of the X files have been uploaded.
Indicator not working:
var pickFileOptions = {};
pickFileOptions.allowMultipleFiles = true;
Xrm.Device.pickFile(pickFileOptions).then(
            function (result) {
                        Xrm.Utility.showProgressIndicator("Uploading files");
                        //do loads of file manipulation
                        Xrm.Utility.closeProgressIndicator();
             }
});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17c2eaa5-824d-3237-e4fd-9d8eef5a463b
* Version Independent ID: 2b343f3e-fc08-3f06-0a5f-ad61cdcd9e23
* Content: [showProgressIndicator (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/showprogressindicator)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/showProgressIndicator.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/showProgressIndicator.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Prashant4787** [comment]
Does not work from html child pop-up window - to stop progress bar running in parent window.

I was also trying to use this function when opening html web resource ( pop-up window) using java-script. There is no way to close progress bar opened in parent window when closing html pop-up (child window ).

Xrm.Navigation.openWebResource() function doesn't have success and failure callbacks to capture.

If I'm closing html pop-up window then the progress bar started on parent should be stopped and page should be refreshed.

Any idea or plan for including this ?

**Comment by nzkelvin** [comment]
This function doesn't seem to work on Dynamics 365 for phones.

**Comment by mnavarrofelix** [comment]
This function doesn't not work if called from ribbon js function on Home entity grid :(

**Comment by Nkrb** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
