### ISSUE TITLE
Barcode Scan button not doing anything

### ISSUE THREAD

**Issue by Benjathing** [MicrosoftDocs/powerapps-docs#635]
Button on core Android is flashing, but not opening any device.
Button on IOS (iPad A1460, iPhone X) does not even flash on press. 
In either case, the camera isn't activating, and the Barcode reader is not showing up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7944b4d0-c3be-afa0-4af1-21c9c27b56e2
* Version Independent ID: c2ca93fd-9817-8300-fcc4-a6999659e0a2
* Content: [Barcode-scanner control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-new-barcode-scanner)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-new-barcode-scanner.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by genloz** [comment]
Hi! Just wondering if there's been any progress on this? I've tried to access on iOS using Edge but nothing happens when you press the barcode scanner.

**Comment by JoostVeldhuis** [comment]
Hi, This control isn't functioning in any web browser, even if you would use it on a mobile device. It is only supported through the native "Power Apps" app from the App store or Google Play store.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please ensure the device is in the device list with for this feature availability, including not supported references for auto mode. If the issue persists, please reach out to the [support teams](https://admin.powerplatform.microsoft.com/support) for issue investigation.
