### ISSUE TITLE
Limitations is misspelled

### ISSUE THREAD

**Issue by lukemctc** [MicrosoftDocs/powerapps-docs#639]
Limitations is misspelled, both on the right-hand navigation and inside of the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073de527-a32b-8d1d-05d5-d3fd629008cd
* Version Independent ID: 6137f8a6-7d45-67f2-5d59-02e3d12ff5ed
* Content: [SetFocus function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-setfocus#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-setfocus.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-setfocus.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the report, the issue has been fixed.
