### ISSUE TITLE
PowerApps Expense Report sample is not working

### ISSUE THREAD

**Issue by tlewing** [MicrosoftDocs/powerapps-docs#64]
This app would be a great tool for my organization except I cannot get the flow to run successfully.  It is not updating the SharePoint Expenses list to the "Approved" or "Open" status.
It appears to be the same issue that @Thonner has been dealing with, but I have been unable to find the solution.  Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by caburk** [comment]
There's a bug with the Flow trying to re-connect to a different data source, which is related to it being exported from a different environment. Until this is fixed, the best option is to create the Flow from scratch using the same steps.

**Comment by AFTOwen** [comment]
@tlewing Thanks for your feedback! I'm closing this issue, but please let us know if the problem persists.

cc: @caburk
