### ISSUE TITLE
How to develop Model Driven App Test Drives

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#642]
Any docs for this?

This [blog ](https://appsource.microsoft.com/blogs/are-you-a-dynamics-365-isv-why-not-set-up-a-test-drive-it-s-never-been-easier-with-hosted-test-drives) from June 2018 points to a link in the Cloud Partner Portal that reviews how to develop these for existing offers. I can not access this as we don't have access to Cloud Partner / Partner Center Portals and assuming this will redirect an ISV to Partner Center now?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b172713b-379d-351c-78ec-386b5a4564fd
* Version Independent ID: 974003c1-0b11-9f1e-916c-1b1b2f86459f
* Content: [Let customers test drive your canvas app on AppSource - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dev-appsource-test-drive#what-is-a-test-drive-solution)
* Content Source: [powerapps-docs/maker/canvas-apps/dev-appsource-test-drive.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dev-appsource-test-drive.md)
* Service: **powerapps**
* GitHub Login: @linhtranms
* Microsoft Alias: **litran**

**Comment by dialedin2014** [comment]
I would also like to know why this article specifies canvas apps and not model driven apps.

**Comment by tapanm-MSFT** [comment]
Please reach out to [model-driven app content](https://docs.microsoft.com/powerapps/maker/model-driven-apps/) for this question.
