### ISSUE TITLE
You can use a Timer as well.

### ISSUE THREAD

**Issue by GitThatWorkDone** [MicrosoftDocs/powerapps-docs#644]
For the SetFocus work around that gets triggered by a button, you can also have a screen with a timer that has a duration of 1 to perform a Navigate to the next page where the SetFocus is. This makes it look like the app is just loading and avoids any extra legwork of pushing a button. I use this for an app on its startup and also to circle back to the its "Start screen" after form submission and it works for having the SetFocus automatically selecting a text input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073de527-a32b-8d1d-05d5-d3fd629008cd
* Version Independent ID: 6137f8a6-7d45-67f2-5d59-02e3d12ff5ed
* Content: [SetFocus function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-setfocus#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-setfocus.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-setfocus.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and sharing your findings. Please feel free to share such findings, ideas and solutions with rest of the community using [Power Apps community forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1).
