### ISSUE TITLE
Does not work for Unified Interface

### ISSUE THREAD

**Issue by timothybohte** [MicrosoftDocs/powerapps-docs#645]
This code works fine for the classis interface, but not for Unified Interface. Could you please provide the code with examples for Unified Interface?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006a1fa1-4229-036d-c756-78ce341ae39d
* Version Independent ID: 324740b1-606b-7481-1568-fc2c577ace30
* Content: [formContext.ui.sections (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formContext-ui-sections)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-sections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-sections.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by LinnZawWin** [comment]
I am not sure if It is working in Unified Interface when you raised this issue but it is working now.
This is the sample code that I tested on my Unified Interface form.
var sectionName = formContext.ui.tabs.get("tab_General").sections.get("tab_General_section_AllFields").getName();

**Comment by Nkrb** [comment]
@timothybohte Can you please verify it again and let us know if it is working or not.

**Comment by Nkrb** [comment]
@timothybohte 
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
