### ISSUE TITLE
How to add a version note

### ISSUE THREAD

**Issue by harzicn** [MicrosoftDocs/powerapps-docs#646]
I can see there is a field for version comments (the version note column is blank and cannot be edited). I would like to add and amend these but cannot see any way to add or update version notes. How can I do that? Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c73b33f-c31c-429a-6adb-2613991a6469
* Version Independent ID: 31c8663c-72ba-b474-67fa-d5ca56e985ba
* Content: [Save and publish a canvas app - PowerApps](https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/save-publish-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/save-publish-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/save-publish-app.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The [content](https://docs.microsoft.com/powerapps/maker/canvas-apps/save-publish-app) has been updated with steps to add version specific notes when saving the version. Please allow some time to view updated content.
