### ISSUE TITLE
Custom Parameters added to the end of the URI

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerapps-docs#647]
Should be 
`[AppID]?param1=value1 `
instead of 
`[AppID]&amp;param1=value1`
Even better would be
`[AppID]?param1=value1&param2=value2`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 559b4613-fbe0-45dc-f8bf-ff3a70b5f66e
* Version Independent ID: 36921b82-2295-8d26-9be0-d2d23ee11ab7
* Content: [Integrate canvas apps into websites and other services - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-apps-dev#set-uri-parameters-for-your-app)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-apps-dev.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/embed-apps-dev.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by RichdiMSFT** [comment]
I have made updates to the article where I include the source parameter and an example with to custom parameters.

**Comment by HairyDrumroll** [comment]
I don't think that was done correctly, or maybe your change didn't come through?
I created a [new pull request](https://github.com/MicrosoftDocs/powerapps-docs/pull/785) on the content source with the change.

**Comment by RichdiMSFT** [comment]
The PR is still pending. Will close the comment once it is published. Thanks for checking so quickly.

Rich

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, since PR is already approved and content updated, closing this issue.
