### ISSUE TITLE
Delegation of 'in' for SQL Server

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerapps-docs#65]
The table suggests that the 'in' function can be delegated in SQL Server. 
My experience suggests that this doesn't work, and there is some discussion on the forums page along these lines also. (see: https://powerusers.microsoft.com/t5/General-Discussion/quot-in-quot-operator-as-test-of-membership-and-its-delegation/td-p/22507)
Curiously, the 'StartsWith' function is listed above as not being able to be delegated for SQL Server, although I am not getting the blue underlining warning of a possible issue when using it in my app.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f7e4f2-fe68-0e4b-9cfd-a303abaa0fd6
* Version Independent ID: f0708033-e29d-5321-0da0-e2c1c2130008
* Content: [Delegable data sources in canvas apps - PowerApps](https://docs.microsoft.com/en-au/powerapps/maker/canvas-apps/delegation-list)
* Content Source: [powerapps-docs/maker/canvas-apps/delegation-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delegation-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by thien7** [comment]
gôg

**Comment by HairyDrumroll** [comment]
Could it be an On-Prem vs Azure thing?

**Comment by manjotsingh057** [comment]
Yes. I also faced same issue. "In" operator is not delegable for SQL Server On-premise.

**Comment by lancedMicrosoft** [comment]
Sameer?

**Comment by lancedMicrosoft** [comment]
Pretty sure it resolves to SQL DISTINCT.

From: Sameer Chabungbam
Sent: Thursday, October 4, 2018 1:24 PM
To: Lance Delano <lanced@microsoft.com>; MicrosoftDocs/powerapps-docs <reply@reply.github.com>; MicrosoftDocs/powerapps-docs <powerapps-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerapps-docs] Delegation of 'in' for SQL Server (#65)


No idea, really.  What does Distinct() map to?

From: Lance Delano
Sent: Thursday, October 4, 2018 1:11 PM
To: MicrosoftDocs/powerapps-docs <reply@reply.github.com>; MicrosoftDocs/powerapps-docs <powerapps-docs@noreply.github.com<mailto:powerapps-docs@noreply.github.com>>; Sameer Chabungbam <sameerch@microsoft.com<mailto:sameerch@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/powerapps-docs] Delegation of 'in' for SQL Server (#65)

Sameer?

**Comment by HairyDrumroll** [comment]
3 Weeks on and I still don't seem to have an answer on the original question. Any updates?

**Comment by HairyDrumroll** [comment]
> The table (in the documentation) suggests that the 'in' function can be delegated in SQL Server.
> My experience suggests that this doesn't work.

2 months on, any update to the original question?
(@malkhawaja, the 'Distinct' question should be opened as a separate issue.)

@AFTOwen @lancedMicrosoft

**Comment by fclinton** [comment]
@HairyDrumroll @AFTOwen @lancedMicrosoft I too am having the same issue with Azure SQL server

**Comment by lancedMicrosoft** [comment]
See the discussion here:  https://docs.microsoft.com/en-us/connectors/sql/  and then note #6.   The table you are currently looking at will be replaced as soon as we have the SharePoint doc ( currently has a pull request out ) and the CDS docs updated for a similar level of detail around delegation.

**Comment by lancedMicrosoft** [comment]
Sorry, note #2.

**Comment by flax41** [comment]
This still doesn't seem to work. The table you linked to for SQL Server indicates that "in" should be delegable for text, so as a workaround I created an SQL view that cast the ID value I need to reference as a varchar(50) and rewrote my filter function:

Filter('[dbo].[View_StringID]', Text(_StrVariable) in '[dbo].[View_StringID]'.ID_Str)

I have verified that the data type in the server is varchar(50), but I'm still getting the delegation warning.

**Comment by flax41** [comment]
I take it back. I had to remove the '[dbo].[View_StringID]' from my function, but then it worked perfectly!

**Comment by AFTOwen** [comment]
@HairyDrumroll Please let us know if you have further questions about the docs. Otherwise, I'll close this issue. Thanks.

**Comment by HairyDrumroll** [comment]
Looks like the [original document](https://docs.microsoft.com/en-au/powerapps/maker/canvas-apps/delegation-list) should be updated to include a note saying something like:
"The 'in' (substring) operator. Supported for ("string value" in <column>), but not for (<column> in "string value")."

Or at the very least a link to: https://docs.microsoft.com/en-us/connectors/sql/#powerapps-delegable-functions-and-operations-for-sql-server.

At the moment, it just says "Yes" for Delegation of "In" which isn't really correct.
So no, not yet ok to close.

**Comment by lancedMicrosoft** [comment]
We’re in the process of removing the “original document” because it’s ambiguous.  It has unfortunately taken waay longer than it should.   We have SQL Server documented and SharePoint and CDS’s documentation is done.  Internal issues getting it out.  Apologies.

Lance

**Comment by AFTOwen** [comment]
@HairyDrumroll Closing this issue because we've now removed the topic to which it relates and moved the information that's still relevant to the [delegation overview](https://docs.microsoft.com/powerapps/maker/canvas-apps/delegation-overview#delegable-data-sources).
