### ISSUE TITLE
PowerApps is not listed.

### ISSUE THREAD

**Issue by mitulsuthar** [MicrosoftDocs/powerapps-docs#650]
I have create 4 apps and I am the owner of the application but when I try to add a new tab and try to find PowerApps I cannot see it. The docs says that default apps are shared automatically. So there are many apps but the Powerapps icon is not being shown. We also have Office 365 License. The documentation is not clear on the pre-requisites for the PowerApps icon to show.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db05e68d-8708-9ed3-53bc-da3f1781def5
* Version Independent ID: f550b297-89a5-98c0-2fd6-0e6a95204436
* Content: [Add an app to Microsoft Teams - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/open-app-embedded-in-teams)
* Content Source: [powerapps-docs/user/open-app-embedded-in-teams.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/open-app-embedded-in-teams.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
@mitulsuthar thank you for your feedback. I am working with our internal team to verify the info in the doc. 

In the meantime, do you have any new updates on this?

Thanks,
Mints

**Comment by mduelae** [comment]
@mitulsuthar - I am still waiting for our internal team to review your issue to see how we can update our content. As soon as I hear back, I will update you.

Thanks,
Mints

**Comment by matthewbolanos** [comment]
Hey @mitulsuthar,

I apologize for the wait. There is a construct in Teams called permission policies which decide which apps Teams users can see when they click on the add a Tab button.
 
If the Teams admin for your Tenant has assigned you a permission policy that does not give you access to the PowerApps app, then you will not see the app in the add a tab modal.
 
Can you please confirm that this is not the case? If not, then we can explore other solutions.

**Comment by mduelae** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerapps.microsoft.com/support/ 

Closing this issue.

Thanks,
Mints
