### ISSUE TITLE
Should be context.utils and return type

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#652]
The utility object is in fact named 'utils' on the context, so ths should be ```context.utils.lookupObjects(lookupOptions)```

Also, the return type of this call is a Promise of EntityReference[] - but the interface isn't as documented! It is actually

```
interface EntityReference{
     entityType:string
     id:string
     name:string
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adb7aec-f488-0653-4b0e-2793d9b75509
* Version Independent ID: aa79b169-3a80-1a06-dba3-d173d8e22aa0
* Content: [lookupObjects - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/utility/lookupobjects#feedback)
* Content Source: [powerapps-docs/developer/component-framework/reference/utility/lookupobjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/utility/lookupobjects.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@scottdurow Thanks for the feedback. We have updated our docs and published to live. Closing the issue.
