### ISSUE TITLE
Mention that Connections need to be enabled in the Entity Settings

### ISSUE THREAD

**Issue by AleksandrRogov** [MicrosoftDocs/powerapps-docs#653]
It would be great if you mention that Connections need to be enabled in the settings of an entity, otherwise entities that have that option disabled will not be visible in "Select record types" list on the Connection Role form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7eaa696-c958-2ba4-c3e5-1390c09326d4
* Version Independent ID: a3d1e8de-b634-b5a2-b13d-8fd0f3ab1b86
* Content: [Configure connection roles - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/configure-connection-roles)
* Content Source: [powerapps-docs/maker/common-data-service/configure-connection-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/configure-connection-roles.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@AleksandrRogov - Thank you for your feedback. The topic has been updated to alert the reader of the Enable connections setting following the procedure to do so. https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/configure-connection-roles#enable-connection-roles-for-an-entity
Closing issue.
