### ISSUE TITLE
Range of Longitude values in documentation

### ISSUE THREAD

**Issue by johnstonbrendan** [MicrosoftDocs/powerapps-docs#654]
The range for the longitude values seems to have changed from 0 to 180 and is now from -90 to 90 degrees.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36bd3668-825f-c74e-073f-ab85c85fa505
* Version Independent ID: 1da8478d-d315-311c-dea5-53bad4790496
* Content: [Acceleration, App, Compass, Connection, and Location signals - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/signals#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/signals.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/signals.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the bug report!  Longitude should have been listed in the docs in the range -180 to 180 degrees.  Living in Seattle, it correctly gives a value of approximately -122 degrees.  I don't believe the behavior has changed, just that the documentation had it listed wrong.
