### ISSUE TITLE
How to delete an app if you are not the owner?

### ISSUE THREAD

**Issue by DS2019** [MicrosoftDocs/powerapps-docs#655]
I've been searching and searching!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7874276c-511b-487b-ae04-41177088e68f
* Version Independent ID: fa9093d6-5fa9-12f8-8ad3-e6c8fdc8e552
* Content: [Delete a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delete-app)
* Content Source: [powerapps-docs/maker/canvas-apps/delete-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/delete-app.md)
* Service: **powerapps**
* GitHub Login: @linhtranms
* Microsoft Alias: **litran**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. As listed in [documentation](https://docs.microsoft.com/powerapps/maker/canvas-apps/delete-app), *You must have the Contributor permission for an app before you can delete it.* The app is deleted from all accounts that the app is shared with.

**Comment by DS2019** [comment]
Where do you see the Contributor Permissions for a powerapp? When you go to Sharing, you can add people as users or co-owners. Thanks!

**Comment by tapanm-MSFT** [comment]
Thank you for the follow up, content is updated including deletion of an app when owner is unavailable and share permission. Please allow some time for the content to reflect the changes.
