### ISSUE TITLE
TableName.Selected

### ISSUE THREAD

**Issue by CarlWilliams254** [MicrosoftDocs/powerapps-docs#656]
Doesn't work. Selected is expecting a field name (?????) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94785ec1-e3da-4ff2-59b6-19bd28bb8680
* Version Independent ID: 4b3e4efa-1d15-2a71-fe61-ee949c54279c
* Content: [Data table control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-data-table#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-data-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-data-table.md)
* Service: **powerapps**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by tapanm-MSFT** [comment]
Please reach out to the [support team](https://admin.powerplatform.microsoft.com/support) for further investigation with this issue.
