### ISSUE TITLE
Logic section missing plugins/CWA

### ISSUE THREAD

**Issue by jasonaalmeida** [MicrosoftDocs/powerapps-docs#657]
Plugins and Custom Workflow Activities are really useful pro-developer options for implementing complex business logic. They should be included in the Logic section to provide a full overview of the capabilities of the platform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa788547-0b4a-7c36-8035-95a0c0386927
* Version Independent ID: bd9e046d-a255-c965-6356-84508141ff61
* Content: [Understand model-driven app components in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/model-driven-app-components#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/model-driven-app-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/model-driven-app-components.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@jasonaalmeida - Thank you for your feedback. Added a subsection titled "Additional options for adding custom business logic" under the Logic section with links to Plugins and Workflow extensions topics for developers. 
Closing issue.
