### ISSUE TITLE
Replace \n in JSON Response from Flow using Functions

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#66]
Let's say I have a field in my JSON response like
```
"flavor_text": "BULBASAUR can be seen napping in\nbright sunlight.\nThere is a seed on its back.\fBy soaking up the sun\u2019s rays, the seed\ngrows progressively larger.",
```
How can I find and replace the `\n` character with just empty white space using any of the functions here https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-filter-lookup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130e07ac-d3c6-9d10-bd7c-bb1f8c4ff2ab
* Version Independent ID: b25a9a60-1319-1e05-8c53-ca135523b6ca
* Content: [EncodeUrl and PlainText functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-encode-decode)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-encode-decode.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-encode-decode.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Hey, @gregdegruy: The [Substitute](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-replace-substitute) function might help.
