### ISSUE TITLE
Need to add documentation for LoadingSpinner

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerapps-docs#660]
Need to add documentation for LoadingSpinner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e39cd04-aed7-f85c-52cc-7db8ad277f2b
* Version Independent ID: a6d85143-d08b-5746-1d45-9f23ff62e2f0
* Content: [Screen control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-screen)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-screen.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-screen.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Description of *LoadingSpinner* property is available. Can you please elaborate on any additional detail needed?

**Comment by HairyDrumroll** [comment]
Yes, I see the documentation for LoadingSpinner was [added](https://github.com/MicrosoftDocs/powerapps-docs/commit/c7a7de0a18779e7c498d0b962c727754b7ff254a#diff-40a2e1408a07f4a9e7248ecf0f32b602) just over two weeks ago. Thanks @chmoncay.
