### ISSUE TITLE
Add Notes and Pen control 

### ISSUE THREAD

**Issue by ppei2012** [MicrosoftDocs/powerapps-docs#665]
I cannot find Add Note and Pen control. Has the feature been removed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17809aa6-f7cf-6b61-61b0-8559b751609f
* Version Independent ID: f4977a5a-f7ed-4813-3d31-aac4c0927e33
* Content: [Add images to Excel - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-images-to-excel#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/add-images-to-excel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-images-to-excel.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **aorth**

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. The content for this scenario has been retired with [updated content](https://docs.microsoft.com/powerapps/maker/canvas-apps/add-images-pictures-audio-video). Pen Input control is available from Input drop down menu under Insert option when you edit canvas app.
