### ISSUE TITLE
Stage Methods section table did not render

### ISSUE THREAD

**Issue by MitchMilam** [MicrosoftDocs/powerapps-docs#667]
The markup on the Stage Methods section is still in place so the markup is most likely incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbe78b3-42e2-0de5-4ed3-f6fc30cfce73
* Version Independent ID: 935a611c-7154-8122-1765-f50144a62bd3
* Content: [formContext.data.process (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-process#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by MitchMilam** [comment]
MAN this is silly. Here is the solution:

You need to have a blank line before the table begins. In this case, the line with **Name and Description**.

Here is the corrected code.

## Stage methods 

A stage contains the data for a stage in a business process flow. Use the methods to access properties of the stage.

|Name | Description|
|--|--|
|[getCategory](formcontext-data-process/stage/getCategory.md)|[!INCLUDE[formcontext-data-process/stage/includes/getCategory-description.md](formcontext-data-process/stage/includes/getCategory-description.md)]|
|[getEntityName](formcontext-data-process/stage/getEntityName.md)|[!INCLUDE[formcontext-data-process/stage/includes/getEntityName-description.md](formcontext-data-process/stage/includes/getEntityName-description.md)]|
|[getId](formcontext-data-process/stage/getId.md)|[!INCLUDE[formcontext-data-process/stage/includes/getId-description.md](formcontext-data-process/stage/includes/getId-description.md)]|
|[getName](formcontext-data-process/stage/getName.md)|[!INCLUDE[formcontext-data-process/stage/includes/getName-description.md](formcontext-data-process/stage/includes/getName-description.md)]|
|[getNavigationBehavior](formcontext-data-process/stage/getNavigationBehavior.md)|[!INCLUDE[formcontext-data-process/stage/includes/getNavigationBehavior-description.md](formcontext-data-process/stage/includes/getNavigationBehavior-description.md)]|
|[getStatus](formcontext-data-process/stage/getStatus.md)|[!INCLUDE[formcontext-data-process/stage/includes/getStatus-description.md](formcontext-data-process/stage/includes/getStatus-description.md)]|
|[getSteps](formcontext-data-process/stage/getSteps.md)|[!INCLUDE[formcontext-data-process/stage/includes/getSteps-description.md](formcontext-data-process/stage/includes/getSteps-description.md)]|

**Comment by Nkrb** [comment]
@MitchMilam Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
