### ISSUE TITLE
Really these functions are helpful. It would be helpful if we can have an example on creating records with polymorphic lookup

### ISSUE THREAD

**Issue by saikrishnasgit** [MicrosoftDocs/powerapps-docs#668]
Hi,

Thank you for these functions to read the data [polymorphic lookup]. But I am looking for an example on how to use this polymorphic lookup in creating a record.

Eg: I am trying to create a case record and referencing an account to it's customer lookup, but somehow I'm failing.

So, thought of putting it here, probably I may get some helpful insights/inputs from you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9f9b1b9-dca2-1c08-fede-af21520c13cf
* Version Independent ID: 00ed57b8-11aa-81b5-3abe-a31a8d5bdc62
* Content: [AsType and IsType functions in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-astype-istype)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-astype-istype.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-astype-istype.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
There are additional details for working with polymoprhic lookups [in this article](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-references#update-the-owner-by-using-patch).  This link will take you to the section on using Patch to set a lookup value, in the example setting the Owner field of an Account to either a Team or a User.  There is not yet great support in the Form control.
