### ISSUE TITLE
External Users/Guests

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#67]
Please add information about how guest user/external users/b2b partner accounts can use PowerApps. Does a license need to be assigned? It does not for the other O365 services, and it is not clear how this works for PowerApps and Flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243af97b-f47b-f3dd-dcf6-701f4d364831
* Version Independent ID: 8934d558-7c51-d5ee-597b-d986e84d683c
* Content: [Licensing overview - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/pricing-billing-skus)
* Content Source: [powerapps-docs/administrator/pricing-billing-skus.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/pricing-billing-skus.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by SeaDude** [comment]
The only way I've heard about to share PowerApps with external users is: 
1. Create a Sharepoint Custom List in a site that allows External Access
2. Create a PowerApp that connects to this Sharepoint list
3. Export your app and import it to the external users O365 tenant
    a. NOTE: The external user must have O365 and PowerApps plans setup for all their folks
    b. Also NOTE: good luck with updates!
4. From what I hear, this will work, but its a heck of a hack. 

Another option I've heard is to publish your app on AppSource then have the external user "buy it". I don't see how this could connect to a db in your company's realm though. 

If you hear other methods please share. We really need this functionality too.

**Comment by mzoomers** [comment]
This is not supported (yet), see https://powerusers.microsoft.com/t5/PowerApps-Ideas/Share-with-external-users/idi-p/4114 for more information.
