### ISSUE TITLE
Square brackets vs angle brackets

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerapps-docs#670]
Just noticed that you are using square brackets where I would normally expect to see angle brackets:

new ["namespace on manifest"].["constructor on manifest"]();

Could be a bit confusing since square brackets usually imply it's a collection element. Would not it be more common to write it this way instead?

new &lt;namespace on manifest&gt;.&lt;constructor on manifest&gt;();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709f9e54-c965-5dc4-b64f-3d90037626be
* Version Independent ID: 45011eec-04a4-01b4-2ab8-70677e910f3b
* Content: [What are code components? - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/custom-controls-overview)
* Content Source: [powerapps-docs/developer/component-framework/custom-controls-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/custom-controls-overview.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ashlega Thank you for the feedback. We have updated the docs and pushed to live. Closing the issue.
