### ISSUE TITLE
Provide more information about the types of errors

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#671]
There are two types of errors that can be thrown from code running in a plugin in the sandbox:

1.	IsvAborted
If an error is caught in the plug-in code, the developer can throw an InvalidPluginExecutionException which will return error

Name: IsvAborted
Hex: 80040265
Number:-2147220891	
Message: ISV code aborted the operation.

When this error is thrown, the message that the developer sets with the exception will be displayed in a dialog in model driven apps. 

2.	IsvUnExpected
If the plug-in developer doesn’t catch the error and it just bubbles up, this error will be returned:
Name: IsvUnExpected
Hex: 80040224
Number: -2147220956	
Message: An unexpected error occurred from ISV code.

This just indicates that the error came from the plug-in code, but didn't use the InvalidPluginExecutionException class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 815578b5-5528-7cdd-4af4-ac007fa6a180
* Version Independent ID: e96d1e22-b572-afd8-c1a6-13d84424024e
* Content: [Handle exceptions in a plug-in (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/handle-exceptions)
* Content Source: [powerapps-docs/developer/common-data-service/handle-exceptions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/handle-exceptions.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@JimDaly This is documented.
