### ISSUE TITLE
Incomplete: "C fills space between D and bottom edge of parent"

### ISSUE THREAD

**Issue by oliviadudley** [MicrosoftDocs/powerapps-docs#672]
"C fills space between D and bottom edge of parent" should read...

Y:	D.Y + D.Height
Height:	Parent.Height - D.Y

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73233c3d-8bfe-eadc-5b8a-264742ec7045
* Version Independent ID: a34dc40d-9d6e-33b2-7e61-0c46a71d3608
* Content: [Create responsive layouts in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-responsive-layout)
* Content Source: [powerapps-docs/maker/canvas-apps/create-responsive-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/create-responsive-layout.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is being updated.
