### ISSUE TITLE
You tube Video

### ISSUE THREAD

**Issue by rriggstx** [MicrosoftDocs/powerapps-docs#674]
"Watch this video to see how to use the Expense Report sample."

Video is marked as private.  Unable to view even after signing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @yijw2017
* Microsoft Alias: **yijw**

**Comment by yijw2017** [comment]
YouTube link is updated. :)
