### ISSUE TITLE
Wrong link - points to PowerBI hub instead on Maker/Common-data-service

### ISSUE THREAD

**Issue by AndreiPanko** [MicrosoftDocs/powerapps-docs#676]
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/self-service-data-prep-with-dataflows#extend-your-capabilities-with-azure-data-and-ai-services
For more information about Azure Data Lake Storage Gen2 and dataflows integration, including how to create dataflows that reside in your organization's **Azure Data Lake, see Dataflows and Azure Data Lake integration (Preview).**

Currently points to: https://docs.microsoft.com/en-us/**power-bi**/service-dataflows-azure-data-lake-integration
Expected: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/connect-azure-data-lake-storage-for-dataflow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3abf73d-60b9-675f-61e7-1c2dc622d055
* Version Independent ID: 352c1196-0631-9f40-e382-bba13d5e27e9
* Content: [Create and use dataflows in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-and-use-dataflows)
* Content Source: [powerapps-docs/maker/common-data-service/create-and-use-dataflows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-and-use-dataflows.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@AndreiPanko -  Thank you for your feedback. The link has been changed per your issue.
Closing issue.
