### ISSUE TITLE
"Max age" setting of the CORS menu expects integer as input, not "*"

### ISSUE THREAD

**Issue by AndreiPanko** [MicrosoftDocs/powerapps-docs#677]
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/connect-azure-data-lake-storage-for-dataflow#create-a-cross-origin-resource-sharing-cors-rule-for-the-athena-service

In the CORS menu item, select the Blob service section and enter these details.
Setting | Value
-- | --
Allowed origins | https://athena-ui-prod.trafficmanager.net
Allowed methods | DELETE, GET, HEAD, MERGE, POST, OPTIONS, PUT, PATCH
Allowed headers | *
Exposed headers | *
Max age | *          <<===

Current: Suggested value for "Max Age" setting is  "*"
Expected: Value must be a valid number. The value must not be empty. The value must be at least 0. The value must be at most 2147483647.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130571e4-3c4a-b532-4ae0-57213fcac6a7
* Version Independent ID: 12df49dc-280f-bd38-e883-ba3d70c1f2b3
* Content: [Connect Azure Data Lake Storage Gen2 for dataflow storage - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/connect-azure-data-lake-storage-for-dataflow#create-a-cross-origin-resource-sharing-cors-rule-for-the-athena-service)
* Content Source: [powerapps-docs/maker/common-data-service/connect-azure-data-lake-storage-for-dataflow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/connect-azure-data-lake-storage-for-dataflow.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bensack** [comment]
Good and appreciated feedback. However, we removed the requirement to configure CORS on the storage account so that whole section of the documentation will be removed. Thank you!

**Comment by Mattp123** [comment]
Section has been removed per bensack comment. Closing issue.
