### ISSUE TITLE
Change Gateway Contact Information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#68]
On the PowerApps Gateway admin page, there is a Contact Information field that shows an email address for each gateway. How can this be changed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c103d76-66ed-dcb3-4b6c-904e59143932
* Version Independent ID: fccd2495-7ac4-d2ab-dc8e-c08992a6af12
* Content: [Understand on-premises data gateways for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-reference)
* Content Source: [powerapps-docs/maker/canvas-apps/gateway-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/gateway-reference.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
@DeanGross Do you want to take over the gateway, as step 6 in the procedure above for installing a gateway describes?

**Comment by DeanGross** [comment]
I don't really want to take over the gateway, I just want to change the display name to a Support team because the Consultant that installed the Gateway is no longer under contract. Is taking over the gateway the only way to change the Contact Name value?
