### ISSUE TITLE
Suggested Related Topic

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#681]
Opening Views, Dialogs, Reports:

https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/open-forms-views-dialogs-reports-url

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db17acbe-9556-ab39-0963-b3d3856714de
* Version Independent ID: 569f08a4-26d1-696b-cdd0-822ffa948f17
* Content: [openUrl (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openurl)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openUrl.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openUrl.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@devlinl 
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.

**Comment by devlinl** [comment]
@Nkrb,
Thanks for the follow up, but it looks like you did the reverse of what I was looking for...

You've added a link to "Xrm.Navigation.openUrl" on the page for "Open forms, views, dialogs, and reports with a URL".

What I was looking for was a link to "Open forms, views, dialogs, and reports with a URL" on the page for "Xrm.Navigation.openUrl".

**Comment by Nkrb** [comment]
@devlinl Thanks again. I will make those changes and push it live.
