### ISSUE TITLE
TODO text 

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#683]
There is the text "&lt;!-- TODO need to update the relevant link from the powerapps repo&gt;" under the &lt;CrmParameter&gt; section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25c896b1-85b8-9abe-c79a-880e764e30b9
* Version Independent ID: 21a4ff22-6afb-ae7a-99c5-8b8cc5342c3b
* Content: [Define ribbon actions (model-driven apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/define-ribbon-actions)
* Content Source: [powerapps-docs/developer/model-driven-apps/define-ribbon-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/define-ribbon-actions.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by Nkrb** [comment]
@scottdurow Thanks for the feedback. we have updated the docs and pushed to live. Closing the issue.
