### ISSUE TITLE
Incorrect information about pac telemetry

### ISSUE THREAD

**Issue by BetimBeja** [MicrosoftDocs/powerapps-docs#684]
Hello, 
I just installed the latest version of PowerApps CLI and the note you have on disabling telemetry seems incorrect.

You suggest using `pac telemetry --enable false` instead of `pac telemetry [enable] [disable] [status]`

Best regards,
Betim.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49dacb11-ddd9-9d58-333c-b9e7feecf0d3
* Version Independent ID: 32b7cc6e-c726-2212-5e15-a26c321dd86c
* Content: [Get tooling for PowerApps component framework - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/get-powerapps-cli#feedback)
* Content Source: [powerapps-docs/developer/component-framework/get-powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/get-powerapps-cli.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@BetimBeja Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
