### ISSUE TITLE
roles object 

### ISSUE THREAD

**Issue by Nianwei** [MicrosoftDocs/powerapps-docs#685]
The user setting object contains a "roles" object. Typically, if something starts with an underscore _, it implies private or internal. However this "roles" does not, and it has something the developers need: the names of the roles, not just GUID of roles. 
It will save an extra trip to server to query names based on role id. 
Is this just a documentation miss, or Dynamics not ready to expose this property? Does not seems have much side effects.

**Comment by Nkrb** [comment]
@ Can you point us to the doc page that you're talking about to better understand the issue.

**Comment by Nianwei** [comment]
@Nkrb  I am referring to https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings 
Basically the object populated an property with name "roles" (not "_roles"), but the documentation for object "usersettings" does not describe that property. I'd like to see it becomes a documented property because this is highly used information, without it been documented, the developers who wanted to stay on the supported/documented side have to make a fetchXml or odata query to server to retrieve those information, which is inefficient and error prone.  Hope this make sense.

**Comment by Nkrb** [comment]
@Nianwei The userSettings.roles method returns  a collection of lookup objects containing the GUID and display name of each of the security role or teams that the user is associated with. Closing the issue. Please reopen the issue if you're not happy with the information provided.

![image](https://user-images.githubusercontent.com/34038327/84197489-db37d480-aa56-11ea-8439-b3d9d9cbab78.png)
