### ISSUE TITLE
limit to # of records passed? - 2228720

### ISSUE THREAD

**Issue by briangre** [MicrosoftDocs/powerapps-docs#687]
Under the limitations section it doesn't reference a limit to the amount of data or number of records that can be passed from PowerBI to the PowerApp via the PowerBIIntegration object. It appears from minimal testing that the limit is 1000 records.

Can we:
1. edit this doc to state the limitation
2. modify the object to (at the very least) honor the "data row limit for non-delegable queries"  setting in the PowerApp Advanced Settings?

I just realized this isn't attached to the doc page I'm referencing..   https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/powerapps-custom-visual#limitations-of-the-powerapps-custom-visual

**Comment by tapanm-MSFT** [comment]
@briangre thanks for your feedback. Looking into it.

**Comment by tapanm-MSFT** [comment]
Documentation has been updated with the limitation, may take sometime to reflect the changes. For change in behavior or to modify the object, the feedback has been considered internally for a review. For any product-related feedback and improvements, please submit feedback through [Power Apps ideas forum](https://ideas.powerapps.com/).
