### ISSUE TITLE
Group type clarification [share apps]

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#69]
The statements above refer to a "security group", I think that this should really state Office 365 group, but I'm not sure. Could you please clarify which type of group can be assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fb8dba-da1c-6845-d301-c3b18a6b98ef
* Version Independent ID: a5d1fd66-fe5b-f52d-47de-6af3c71928f7
* Content: [Share a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Hey, @DeanGross: the first two references to security groups specify Azure Active Directory. Does that help?

**Comment by DeanGross** [comment]
@AFTOwen  in Azure AD, we have a choice to create a Security Group or an Office 365 Group. In Office 365 we are typically sharing SPO sites, Teams, Stream videos and other objects with Office 365 Groups, and sharing does not work if we try to use an AAD Security Group. Are saying that the statement in the first paragraph of https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app is correct and the we cannot share a Canvas app with an Office 365 Group?
