### ISSUE TITLE
The unique name for the sub-grid cannot be edited

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#691]
When the user updates the unique name for the sub-grid and saves the form, the changes do not reflect in the system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cb9e79-5d53-a1b0-3b9b-9c726cc94227
* Version Independent ID: 932868d3-c5b6-5b38-0cf6-77d0bf4750b2
* Content: [Add and configure a sub-grid component on a form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/form-designer-add-configure-subgrid#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/form-designer-add-configure-subgrid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/form-designer-add-configure-subgrid.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by iangpgh** [comment]
@LinnZawWin Did you receive a response to your report, or is the issue otherwise resolved?

**Comment by iangpgh** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue. 

@Mattp123 - Closes #691

**Comment by LinnZawWin** [comment]
@iangpgh  Apologies for the late reply. I've just tested and the issue has been resolved in the new form designer.
