### ISSUE TITLE
Small grammar mistake

### ISSUE THREAD

**Issue by iflyadesk** [MicrosoftDocs/powerapps-docs#692]
"However, you can continue editing rest of the components as usual." 
should be 
"However, you can continue editing the rest of the components as usual."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6275ab57-197d-4871-7003-9d5dddc0caa2
* Version Independent ID: c2a49e45-ba1d-f1d4-ff52-b9d1fd4466fe
* Content: [Portal templates available in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/portal-templates)
* Content Source: [powerapps-docs/maker/portals/portal-templates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/portal-templates.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by rostyslav-diakiv** [comment]
@sbmjais

I have submitted a PR to fix this issue: PR #706 to fix grammar issue.
Please review.

**Comment by KumarVivek** [comment]
@rostyslav-diakiv This is done; closing the issue.
