### ISSUE TITLE
Trigger Barcode Scanner with an icon/different control, OnSelect

### ISSUE THREAD

**Issue by haifoo** [MicrosoftDocs/powerapps-docs#693]
I cannot find a way to trigger the barcode control using OnSelect of another control, for example an icon. ScanBarcode() is no longer supported. 

Is there another way? If not, then I hope this gets added back. 
Use-case: I have a few buttons that navigate to a screen, and a barcode scanner button. all actions are triggered on button and icon click (OnSelect), except for the Scan button. 

![image](https://user-images.githubusercontent.com/14801586/66279391-beee0180-e8e3-11e9-9dbc-4a87ddad3b10.png)

**Comment by chmoncay** [comment]
Hi there, you can hide the barcode button then in your OnSelect for the "Scan QR Code" use the Select function.

`Select(BarcodeScanner1)` or equivalent button name.
