### ISSUE TITLE
Restriction in older Dynamics versions (NAV2017)

### ISSUE THREAD

**Issue by MartijnElfers** [MicrosoftDocs/powerapps-docs#697]
Are there also restrictions regarding NAV2017 implementations and using PowerApps? Or do all users always require a NAV2017 license next to PowerApps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted entities requiring Dynamics 365 licenses - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by iangpgh** [comment]
@MartijnElfers Has your question been answered or is the issue otherwise resolved?

**Comment by MartijnElfers** [comment]
Unfortunately haven't received an answer yet, also via other channels. Customer has moved to a different partner, but would still be interesting to know the answer for future cases :)

**Comment by iangpgh** [comment]
@MartijnElfers NAV support with model-driven apps, there’s one listed under Dynamics NAV (Preview) - https://docs.microsoft.com/en-us/connectors/dynamicsnavision/. We don’t have any such content in model-driven or canvas apps documentation for this connector though. 
If this question arises again and you need further information, open a new issue and I'll see if there's any new pertinent info or doc regarding this question.

**Comment by iangpgh** [comment]
@MartijnElfers Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.  
Closing this issue.

**Comment by iangpgh** [comment]
@Mattp123 - Closes #697
