### ISSUE TITLE
Please add documentation on how to define a Personal Tab 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/powerapps-docs#698]
- Entry-ID = &lt;PA GUID&gt;
- content URL = &lt;PA weburl&gt;?source=teamstab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db05e68d-8708-9ed3-53bc-da3f1781def5
* Version Independent ID: f550b297-89a5-98c0-2fd6-0e6a95204436
* Content: [Add an app to Microsoft Teams - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/open-app-embedded-in-teams#feedback)
* Content Source: [powerapps-docs/user/open-app-embedded-in-teams.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/open-app-embedded-in-teams.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
@Josverl Thanks for the feedback. I am working with our internal team to get this added to our docs. I will update you once the content has been added.

Thanks,
Mints

**Comment by tapanm-MSFT** [comment]
@Josverl  please review updated https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/embed-teams-app for embedding app in Teams.
