### ISSUE TITLE
Storage Capacity Information Missing

### ISSUE THREAD

**Issue by jemsjose** [MicrosoftDocs/powerapps-docs#70]
The "PowerApps pricing page" refers to this page for Storage Capacity Information and this page refers back. So currently it is a bit hard to get those details. The additional storage cost details are equally hard to find. For Enterprises, this information is key for adoption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243af97b-f47b-f3dd-dcf6-701f4d364831
* Version Independent ID: 8934d558-7c51-d5ee-597b-d986e84d683c
* Content: [Licensing overview - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/pricing-billing-skus#licenses)
* Content Source: [powerapps-docs/administrator/pricing-billing-skus.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/pricing-billing-skus.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
@jemsjose 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. The topic has been significantly rewritten. Please reopen if the updated content or links do not answer your question.
