### ISSUE TITLE
Cannot edit SingleLine.Text in CRM

### ISSUE THREAD

**Issue by tomkan08** [MicrosoftDocs/powerapps-docs#700]
In CRM, when editing the PCF's SingleLine.Text or SingleLine.TextArea default value, cannot edit anything beyond 100chars.  Should reflect length of what is being edited (TextArea = 4000 chars)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b2e635-6c60-0efc-d894-e43216dca90e
* Version Independent ID: 9828125d-c061-465e-d486-b4ea609190e1
* Content: [Property Element - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/property.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@tomkan08 Thanks for the feedback. Do you want us to reflect the max character length in the doc or in Dynamics 365.

**Comment by tomkan08** [comment]
HI, I meant D365 should allow editing up to the length of the data type.  So SingleLine.Text would be 256 chars and SingleLine.TextArea should allow editing up to 4000 chars.

**Comment by Nkrb** [comment]
@tomkan08 Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
