### ISSUE TITLE
Xrm.Navigation.openWebResource data parameter encoding issue

### ISSUE THREAD

**Issue by mangesh236** [MicrosoftDocs/powerapps-docs#701]
as per [document ](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/sample-pass-multiple-values-web-resource-through-data-parameter) to pass data to HTML web resource we need to encode the data and pass to 
	`var accountIdParameter = encodeURIComponent("objectid="+ id);
        Xrm.Navigation.openWebResource("html_page.html",null, accountIdParameter);` 

But from now in the online CRM version v9.1 the data parameter is being encoded.
![ms crm version](https://user-images.githubusercontent.com/31954693/66473716-76823f80-eaad-11e9-883b-26f6cf199a98.png)
![openRSUrl](https://user-images.githubusercontent.com/31954693/66473751-8732b580-eaad-11e9-96e4-73676895c18d.png)

**Comment by Nkrb** [comment]
@mangesh236 Can you confirm if you are still facing this issue.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
