### ISSUE TITLE
formContext getControl/getAttribute are not documented

### ISSUE THREAD

**Issue by ChrisGrohHS** [MicrosoftDocs/powerapps-docs#702]
getAttribute is used in a sample but isn't documented. getControl isn't documented on this page at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27005d75-5062-c4cf-bfa8-bee6f0aeb28c
* Version Independent ID: a3ce8627-2cf4-9eb6-8e36-f304c012b05c
* Content: [Client API form context in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/clientapi-form-context)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/clientapi-form-context.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/clientapi-form-context.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@ChrisGrohHS 
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
