### ISSUE TITLE
This document up-to-date in respect to PowerApps visual limitations regarding PowerBI Report Server?

### ISSUE THREAD

**Issue by arherva** [MicrosoftDocs/powerapps-docs#703]
Is this document up-to-date in the sense that it is still not possible to include powerapps visuals to reports deployed via Report Server?

**Comment by Nkrb** [comment]
@arherva Can you please post the link to the document you're talking about.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The [documented limitation](https://docs.microsoft.com/powerapps/maker/canvas-apps/powerapps-custom-visual#limitations-of-the-power-apps-custom-visual) for Power Apps visual with regards to Power BI Report Server is at this moment still applicable:

*Power BI Report Server does not support the Power Apps visual.*
