### ISSUE TITLE
Custom Entity

### ISSUE THREAD

**Issue by renusuri** [MicrosoftDocs/powerapps-docs#704]
Can we have documentation on configuring Bing maps for a custom entity in Model Driven App

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f65617f-1ab4-7a7f-658a-e37a8fce5485
* Version Independent ID: afb226a3-5c56-5e8c-48dc-cb29ab2b6650
* Content: [Configure Bing maps in a model-driven app with PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/configure-bing-maps-legacy#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/configure-bing-maps-legacy.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/configure-bing-maps-legacy.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@renusuri - Thank you for your feedback. Bing maps aren't supported with custom entities. The topic referenced in this issue has been expanded including details about what entities are supported for use with the map control. 
Closing issue.
