### ISSUE TITLE
Get rid of time

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#705]
Please show how to execute these commands with date only.
with time only too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be232ee1-0a4d-3521-5eab-7cdc7f6f74ae
* Version Independent ID: 4e17d0af-bcde-853b-fe5c-32b7261519e2
* Content: [DateAdd, DateDiff, and TimeZoneOffset functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-dateadd-datediff)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-dateadd-datediff.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-dateadd-datediff.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
These functions can be used on Date, Time, or DateTIme values.  As per our[ data types documentation](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/data-types#mixing-date-and-time-information), Date, Time, and DateTime are effectively the same thing.   For example, Today() returns a value with no time, and yet you can use DateAdd( Today(), 4, Hours ) to add 4 hours to it.  To keep a Date pure, only add or subtract time units or a day or greater. 

If you are looking to strip the Time from a Date, let's say it is in the variable x, I would look at Date( Year( x ), Month( x ), Day( x ) ) and something similar for times.

I may have misinterpreted your question.  If this didn't answer it, please leave a comment with more details and we'll get to the bottom of it.
