### ISSUE TITLE
Error in guidance text in step 2

### ISSUE THREAD

**Issue by HilaryStoupa** [MicrosoftDocs/powerapps-docs#707]
I think:
pac solution init --publisher-name &lt;enter your publisher name&gt; --publisher-prefix &lt;enter your publisher name&gt;
Should be:
 --publisher-prefix &lt;enter your publisher prefix&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700c487a-6048-5ed1-d3b3-f15756f0f953
* Version Independent ID: 35502302-bdf4-6a02-11cb-dea21d9fa7ff
* Content: [Import components - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls)
* Content Source: [powerapps-docs/developer/component-framework/import-custom-controls.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/import-custom-controls.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@HilaryStoupa Thanks for the feedback. We have updated the docs and published live. Closing the issue.
