### ISSUE TITLE
Expand instructions to include updating data source

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#709]
Title pretty much covers it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eca9b750-b686-4eea-009e-90f7d7a88f8f
* Version Independent ID: 47f0ff15-5438-d8f8-80e7-31739748e2a5
* Content: [Add a list box, a drop-down list, or radio buttons to a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-list-box-drop-down-list-radio-button)
* Content Source: [powerapps-docs/maker/canvas-apps/add-list-box-drop-down-list-radio-button.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-list-box-drop-down-list-radio-button.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
You can select **Refresh** to refresh the data source from the data pane.
