### ISSUE TITLE
Color of text for today's date

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#710]
Seems like this documentation should include what controls color of text (day of month) for the highlighted day.

Also, the function of the Theme on the calendar should probably be in here too(?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95dceb94-5142-17e4-ef8a-53fab1966ece
* Version Independent ID: a2c84e18-8581-6816-bc01-3f5761c92021
* Content: [Reference for the calendar-screen template for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/screen-templates/calendar-screen-reference)
* Content Source: [powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/screen-templates/calendar-screen-reference.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated, please allow some time to reflect the changes.
