### ISSUE TITLE
multiple and

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#711]
Looks like And(a,b,c) is allowable, would be good to have an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5531db91-b241-6c4b-54c1-4c21c75c9769
* Version Independent ID: b6b489a8-0389-5243-6788-7c7f54f99f0a
* Content: [And, Or, and Not functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-logicals)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-logicals.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-logicals.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and suggestion. Please note the syntax already explains multiple logical formulas to achieve this - **And( LogicalFormula1, LogicalFormula2 [, LogicalFormula3, ... ] )**.
