### ISSUE TITLE
match field in table

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#712]
Seems like examples should include how to match a field in a table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c394b4cd-a8bf-c167-86f7-3a3690a78ba7
* Version Independent ID: 1c106efe-e4b2-f296-9caf-c372aab3b2d7
* Content: [IsMatch, Match, and MatchAll functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-ismatch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-ismatch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-ismatch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the feedback.  The Match functions work on a single string at a time using regular expressions; they are not table aware.  The Search and Filter functions can be used to search for a string in a field, but don't work with regular expressions.  If I misunderstood your comment please reply with more details on what you have in mind.  Thanks!
