### ISSUE TITLE
vertical align?

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#713]
needs to be called out, even if not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776f1f0f-826d-f77f-1a18-69da27fbb361
* Version Independent ID: 2e532983-8a9d-82ec-7db3-70328b462a36
* Content: [Text-input control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-text-input)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-text-input.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-text-input.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Align has properties of Left, Right, Center and Justify.
