### ISSUE TITLE
Could use first day of...

### ISSUE THREAD

**Issue by akmiecik** [MicrosoftDocs/powerapps-docs#714]
Would be good to see examples of :
First day of week
First day of month
First day of year

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afda392a-4ba8-8b8e-692b-6a5e9b73a331
* Version Independent ID: de050707-0454-e57e-78f7-7aa5ed506a48
* Content: [Now, Today, and IsToday functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-now-today-istoday)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-now-today-istoday.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-now-today-istoday.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
@akmiecik thanks for the ask. Looking into it.

**Comment by tapanm-MSFT** [comment]
@akmiecik  can you please clarify if the ask is for a Boolean true/false output for given input, or should return actual day, month or year? 

e.g. are you asking for Boolean check IsTodayFirstDayOfWeek(), IsTodayFirstDayOfMonth() or IsTodayFirstDayOfYear()  or are you asking for a function to return day corresponding to first day of this week, this month and this year?

In general,you can use samples like below for Boolean check - e.g. returns true when value matches that of Today() and false when doesn't match:

Weekday(Today()) = 3
Month(Today()) = 10
Year(Today()) = 2019

**Comment by akmiecik** [comment]
The original help screen was "Now, Today, and IsToday functions in PowerApps"

I'm thinking it should include Week, Month, Year examples too (or at least a link to the proper place)

I don't remember how I got it working but here are some examples from my code, pardon if they are not syntactically correct:

Beginning of week:  Weekday(Today(), Sunday
Beginning of year:  Date(Year(Now()),Month(Now()),1))

thanks.

**Comment by tapanm-MSFT** [comment]
Thanks. The examples are in respective function documentation:

Year: https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-datetime-parts 
e.g. Weekday( Now(), StartOfWeek.Wednesday )	

Month: https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-datetime-parts

Date: https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-date-time

Please use examples from respective function documentation to build business logic. 
Closing the comment with above documentation links, please feel free to reach out if more questions.
