### ISSUE TITLE
Does not work from html child pop-up window - to stop progress bar running in parent window.

### ISSUE THREAD

**Issue by Prashant4787** [MicrosoftDocs/powerapps-docs#715]
I was also trying to use this function when opening html web resource ( pop-up window) using java-script. There is no way to close progress bar opened in parent window when closing html pop-up (child window ).

Xrm.Navigation.openWebResource() function doesn't have success and failure callbacks to capture.

If I'm closing html pop-up window then the progress bar started on parent should be stopped and page should be refreshed.

Any idea or plan for including this ?

**Comment by Nkrb** [comment]
@Prashant4787 Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
