### ISSUE TITLE
Assignment Operator (=) used where Equality Operator (==) Expected in Code Sample

### ISSUE THREAD

**Issue by krouskop** [MicrosoftDocs/powerapps-docs#722]
In the if statements in the 'Read the data context in multiple data formats' section, a single equals sign is used where you'd want double-equals.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7c20d03-ebbc-b2a5-90ab-f1a9d7d0e930
* Version Independent ID: fda909a6-3de9-243c-5466-c9f11ff8e810
* Content: [Write a listener application for a Microsoft Azure solution (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/write-listener-application-azure-solution#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/write-listener-application-azure-solution.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/write-listener-application-azure-solution.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@krouskop Thanks for catching that. Topic updated.
