### ISSUE TITLE
The Page on Restricted Entitiies reference the PowerApps Licences Guide which References the same page!!! Circular Hell

### ISSUE THREAD

**Issue by richardamajor** [MicrosoftDocs/powerapps-docs#726]
The Page "https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities" states it is out of date and to consult the page "Microsoft PowerApps and Microsoft Flow Licensing Guide" which when defining Restricted Entities refers page to the orginal page.

Please resolve.

**Comment by KumarVivek** [comment]
@richardamajor We are aware of the issue, and working to get the updates published soon. Thanks for your patience!

**Comment by iangpgh** [comment]
@richardamajor Article is recently updated with the list of restricted entities. 

[Restricted entities requiring Dynamics 365 licenses](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)

**Comment by KumarVivek** [comment]
The article is up-to-date; closing the issue.
