### ISSUE TITLE
Unable to Set Text Value of TextInput

### ISSUE THREAD

**Issue by daryllabar** [MicrosoftDocs/powerapps-docs#728]
Maybe I'm just not understanding the Docs and I'm confused as to what the Default value is vs the Text Value.  Can the Text Property not be set to a formula?  It's not in my drop down: https://www.screencast.com/t/eV5JEcKqvb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede0c713-e3ec-b9b6-d631-63eb148e73c9
* Version Independent ID: 591b57c7-decf-d71d-957b-4298e436f9b0
* Content: [Text-input control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-text-input)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-text-input.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-text-input.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by hpkeong** [comment]
I have watched your video. 
TextInput only has Default Value, but
Label has Text Value.
Both are interchangeable.

TextInput = Default can be set to "" (Blank) initially if you wish to a "Default" value before typing anything.
but if you are editing, you can use IF.
E.g.:
You have a Gallery and inside the gallery you have record.
Let say you have one field, called : ThisItem.myname
Add a Button.OnSelect = UpdateContext({editrecord: ThisItem])
in the TextInput box, set as following
TextInput.Defaults = If(!IsBlank(editrecord.myname), editrecord,myname, "")

Hope u understand.

PK Hong

**Comment by chmoncay** [comment]
Hi there,

Default is the input value of the textbox, Text is the output.   So if you're looking to use the value of the textbox named txtMyTextBox, you would reference it **txtMyTextBox.Text**

Hope this helps.
