### ISSUE TITLE
Microsoft Flow connectors

### ISSUE THREAD

**Issue by ugreg** [MicrosoftDocs/powerapps-docs#729]
Are Microsoft Flow connectors submitted to AppSource? Where is this documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2af3070-30b8-395e-ea51-86e954e3b006
* Version Independent ID: c1e95af9-6261-7da1-07ce-1b8986ef3738
* Content: [Step 4: Create an AppSource package for your app (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-package-app-appsource)
* Content Source: [powerapps-docs/developer/common-data-service/create-package-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/create-package-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please see https://learn.microsoft.com/power-automate/developer/dev-appsource-test-drive
