### ISSUE TITLE
row limits

### ISSUE THREAD

**Issue by rvaldivia001** [MicrosoftDocs/powerapps-docs#73]
seems as if the drop down list box has a hard row limit.  would save a lot of time if you would post the limit in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57642536-b4f2-4a73-4fbf-a6e084aaf4bd
* Version Independent ID: 946306ff-1045-052e-6ec0-5df3cef4a236
* Content: [Drop down control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-drop-down)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-drop-down.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-drop-down.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
There are no hard limits on the control.  However if the data source does not support delegation, there is an app-level limit.  Default is 500 rows, but it can be increased by going to File, Advanced setting, Data row limit, when editing the app.  Max value is 2000.

**Comment by fikaradz** [comment]
I take that back.  There is a hard limit of 500 records for Dropdown and Listbox controls.  This is for performance issues, but also those controls are not really usable with that many items.  If you have a large number of items, we recommend using Combo box control, which supports searching.   Good point about publishing this limit, I'll update the docs.
