### ISSUE TITLE
Cannot use literal 0 in Text() replacement formula syntax

### ISSUE THREAD

**Issue by plmcgrn** [MicrosoftDocs/powerapps-docs#730]
It seems you can't use a literal zero, for instance, when trying to format phone numbers properly for local users.

**Example**
```Text(Value("+442012345678"),"+## (0)## #### ####")```
Expected output ```+44 (0)20 1234 5678```
Actual output ```+4 (4)20 1234 5678```

It's fairly common to format international phone numbers with an optional ```(0)``` to indicate long distance prefix, similar to how ```1``` precedes phone numbers in North America.

I tried using a standard ```\``` as an escape character, but I don't think this was planned for in this function.

```Text(Value("+12345678910"),"+# (###) ###-####")``` outputs ```+1 (234) 567-8910``` as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f30da2a-1b9d-9d31-c59e-494314144b2f
* Version Independent ID: abe8de4e-2ed5-aedc-d2b3-a819bdf40587
* Content: [Text function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-text#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-text.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-text.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Literal 0 is a special character in a Text format specification.  [From the docs](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-text#number-placeholders): 0 - Displays insignificant zeros if a number has fewer digits than there are zeros in the format. For example, use the format #.00 if you want to display 8.9 as 8.90.

There is no way to directly insert the 0.  However, you could indirectly insert it by concatenating parts together after using Text, perhaps something like this (but sure to take into account variability in the format of the input string): 
```
With( { PhoneNumber: "+442012345678" }, 
Left( PhoneNumber, 3 ) & " (0)" & Text( Value(Mid( PhoneNumber, 3)),"## #### ####" ) 
)
```
results in
```
+44 (0)420 1234 5678
```
