### ISSUE TITLE
Proper Xrm.Navigation.openWebResource() syntax to open HTML WebResource

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#731]
What is the proper syntax to open a WebResoruce using this API? 

All of the syntax variants I tried resulted in a HTTP Error 404 - Not Found. So close, just need this pop up window to display a page.
 
```
"use strict";

var DynamicsClientApi = DynamicsClientApi || {};


DynamicsClientApi.openDashboard = function() {
    var windowOptions = { openInNewWindow: true, height: 900, width: 1200 };
    
    // All of these variants result in 404 not found, need to get a working api call
    // Xrm.Navigation.openWebResource("$webresource:greg_DemoDashboard", windowOptions);
    // Xrm.Navigation.openWebResource("greg_/DemoDashboard.html", windowOptions);
    // Xrm.Navigation.openWebResource("greg_/html/DemoDashboard.html", windowOptions);
    // Xrm.Navigation.openWebResource("greg_/DemoDashboard.html", windowOptions);
    // Xrm.Navigation.openWebResource("greg_/html/DemoDashboard.htm", windowOptions);
    // Xrm.Navigation.openWebResource("greg_/DemoDashboard.htm", windowOptions);
    // Xrm.Navigation.openWebResource("greg_/html/DemoDashboard.htm", windowOptions);
    // Xrm.Navigation.openWebResource("greg_/DemoDashboard.htm", windowOptions);
    Xrm.Navigation.openWebResource("greg_/html/DemoDashboard.htm", windowOptions);
    
    // Don't want this, opens uri in new tab
    // var openUrlOptions = { height: 800, width: 800 };
    // Xrm.Navigation.openUrl("https://app.five9.com/clients//index.html?role=Domain", openUrlOptions)
}

function MainDashboard() {
    DynamicsClientApi.openDashboard();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef001b56-f366-7866-693b-c403f84dbab3
* Version Independent ID: e3d1fbdc-84a5-ce3c-af1e-11e98b14418f
* Content: [openWebResource (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openwebresource)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@gregdegruy Closing this issue as I believe you are unblocked now.

**Comment by gregdegruy** [comment]
Yes thank you, adding the proper syntax for reference:
```
"use strict";

var DynamicsClientApi = DynamicsClientApi || {};

DynamicsClientApi.openDashboard = function() {
    var windowOptions = { openInNewWindow: true, height: 900, width: 1200 };   
    Xrm.Navigation.openWebResource("greg_DemoDashboard", windowOptions);    
}

function MainDashboard() {
    DynamicsClientApi.openDashboard();
}
```
