### ISSUE TITLE
 XXX no longer present in the operation schema. It should be removed before the workflow is re-saved.

### ISSUE THREAD

**Issue by omsblackelf** [MicrosoftDocs/powerapps-docs#733]
Hi there,

followed the guide by the letter in order to quickly check this out for our company, however I am unable to get over the last step:

Errors in "Change item status to Approve":  "xxx no longer present in the operation schema. It should be removed before the workflow is re-saved."

For the following fields:

-Comments
-Startdate
-Enddate
-DateSubmitted

Correct site and list selected.
Not really familiar with flow/power apps yet (that's why I wanted to check this out), short search suggests this may be a bug - anyone else getting the same issue, any resolutions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @yijw2017
* Microsoft Alias: **yijw**

**Comment by kcnighsurf** [comment]
Same Error

**Comment by kcnighsurf** [comment]
looks like a common issue https://powerusers.microsoft.com/t5/Power-Automate-Ideas/When-Site-Address-and-List-Name-of-the-quot-Update-item-quot/idi-p/348996

**Comment by Wrensummerset** [comment]
so, what's the solution?

**Comment by maheshkhiste** [comment]
Any update on this issue, we are having exact same issue. Suddenly production flow when edited started throwing the error. Its very big WF , not sure if there's other solution than recreating it. 
MS guys please fix this , its affecting business process.

**Comment by BerndKroon** [comment]
I had the same problem, and solved it: in my case the cause for this error was that I first selected the LineItems list. You can't correct to the Expenses list. So... escape out, don't save, go back to editing the flow, and at the end, do select the right list (Expenses).  All runs smooth there after.

**Comment by robertafreese** [comment]
I just created a list and connected a WF to it. The fields Backup_x0020_Status and 'Reviewed' are being added and have this error. I did not create these columns and I don't see them in SharePoint Online, I only see the columns I created. 

I cannot use SP Designer due to the custom scripts being disabled. I need to get a new workflow working, and I can't connect to a PowerApp WF to Sharepoint to add a list item. Please fix this. If I can't support my existing flows by making edits, this will be a problem for processes depending on them.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please ensure the steps are followed correctly with connections created before import and flow created during import. And the connection names, flow name and list names are correct. If the issue persists, it needs investigation as part of incident based support. Please reach out to support teams using a [support service request](https://admin.powerplatform.microsoft.com/support).

**Comment by andresgd7** [comment]
try changing the external name of variable in power automate desktop, that helped me
