### ISSUE TITLE
StorePrice value

### ISSUE THREAD

**Issue by aiiitm** [MicrosoftDocs/powerapps-docs#738]
Can this method be used to get the numeric value of StorePrice.FormattedPrice
https://docs.microsoft.com/en-gb/uwp/api/windows.services.store.storeprice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e86293c2-5e54-8fe5-0e6b-74c355e50e61
* Version Independent ID: c5c800a3-1f7d-5da7-9bb7-f0e23ec2e601
* Content: [Value function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-value)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-value.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-value.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by aiiitm** [comment]
@gregli-msft any updates on the query?

**Comment by gregli-msft** [comment]
Perhaps.  The Value function will ignore some formatting as described in the documentation but it may not ignore everything that this API may return.  You'd need to test it out.  Alternatively to be safe, you could extract the numbers and decimal point using a regular expression with the Match function expression and then pass that result to Value.
