### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by scottdurow** [MicrosoftDocs/powerapps-docs#739]
The description is incorrect for this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c452bd86-fa35-a48e-b5d5-9d8b91148fc6
* Version Independent ID: ec5aa21c-9691-5ff9-799f-7f0fa1be8572
* Content: [setFilter - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/filtering/setfilter)
* Content Source: [powerapps-docs/developer/component-framework/reference/filtering/setfilter.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/filtering/setfilter.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@scottdurow Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
