### ISSUE TITLE
The output format is not clear

### ISSUE THREAD

**Issue by dariuszbz** [MicrosoftDocs/powerapps-docs#74]
Despite you said it's 3gp or aac .... IT'S NOT. i recorded, save, try to play (outside of powerapps) and none of well know players can play the audio. Any feed back ?
Btw. what is the format if i run in my browser on windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 258f140b-bc82-47a7-e915-79bebbd9b3b9
* Version Independent ID: d8a732b6-53b4-b161-3ff8-14de5fda89b3
* Content: [Microphone control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-microphone)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-microphone.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-microphone.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by fikaradz** [comment]
Thank for pointing this out.  The output format for web browsers (Chrome and Firefox, where the feature is supported) is OGG.  I'll update the docs.
