### ISSUE TITLE
Images show only classic interface

### ISSUE THREAD

**Issue by RebekkaAalbers** [MicrosoftDocs/powerapps-docs#740]
The images on this page show only how to edit managed properties from the classic CE interface. This functionality is also available in the PowerApps / Flow interface of solutions.
Please also add images what it looks like in that interface. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be3213e-522f-c910-7f65-65dc99ff6275
* Version Independent ID: 5ababa76-d4f4-928b-2803-09354caa7e58
* Content: [Set managed properties in Common Data Service metadata - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/set-managed-properties-metadata)
* Content Source: [powerapps-docs/maker/common-data-service/set-managed-properties-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/set-managed-properties-metadata.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@RebekkaAalbers - thank you for your feedback. The topic has been updated in the entity managed properties section to reflect the newer maker portal UI. However, I don't see full access for the field and relationship managed properties so those remain as-is using the classic experience. 
Closing issue.
