### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by JamesHorsley** [MicrosoftDocs/powerapps-docs#744]
This call seems quite quirky - it really needs some example code - especially of e.g. how to select and set the view and how to apply a filter.  Also it would help to have sepcific details about the differences in behavbiour between classic web UI and UUI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@JamesHorsley Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
