### ISSUE TITLE
Still preview? 

### ISSUE THREAD

**Issue by sideshowbob** [MicrosoftDocs/powerapps-docs#746]
This page was last modified a year ago. Is this feature still in preview state? When can it be expected to be released? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f91d68-45fa-eef7-08ac-851260b60a16
* Version Independent ID: 6af4ea74-75be-9450-e25f-34ad05a919e3
* Content: [Xrm.Panel - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-panel#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-panel.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/xrm-panel.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by DHubbert** [comment]
I've got the same question - I've got a customer requirement this would be good for that I need to preview now - is this going to be make it out of preview status any time soon?

**Comment by namurdock** [comment]
Please can you also add an unload function? And perhaps an isLoaded function. It would be good to be able to get rid of it when not appropriate.

**Comment by avanticsolutions** [comment]
> Please can you also add an unload function? And perhaps an isLoaded function. It would be good to be able to get rid of it when not appropriate.

loadPanel("") will close the panel:

https://www.magnetismsolutions.com/blog/dominicjarvis/2018/02/28/introducing-xrm-panel-for-microsoft-dynamics-365

**Comment by Nkrb** [comment]
@sideshowbob Yes, this feature is still in preview.

**Comment by Nkrb** [comment]
@namurdock Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.

**Comment by MaTeMaTuK** [comment]
@Nkrb, Could you please ask crm team about some, even approximately, estimate?

**Comment by Nkrb** [comment]
@MaTeMaTuK They are trying to take this up in the coming months, not sure about when this will be GA.

**Comment by Nkrb** [comment]
@MaTeMaTuK Closing the issue.
