### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by roshangautam** [MicrosoftDocs/powerapps-docs#748]
Learn More link for "Build Azure Functions" is resulting in a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5900fe4-4399-9b09-3e42-4ff71f3a8fb9
* Version Independent ID: 16e8e4eb-6e63-620e-3811-cd6265aca1fa
* Content: [PowerApps for enterprise developers, partners, and ISVs - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dev-enterprise-intro)
* Content Source: [powerapps-docs/maker/canvas-apps/dev-enterprise-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dev-enterprise-intro.md)
* Service: **powerapps**
* GitHub Login: @ImadYanni
* Microsoft Alias: **iyanni**

**Comment by KumarVivek** [comment]
@roshangautam Thanks for reporting this. The link is fixed now, and will be updated in our next daily live update. Please check back in a day. Closing this issue.
