### ISSUE TITLE
What license must be assigned to my guest needs updating

### ISSUE THREAD

**Issue by davidyack** [MicrosoftDocs/powerapps-docs#749]
This does not reflect the new licensing plans

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fb8dba-da1c-6845-d301-c3b18a6b98ef
* Version Independent ID: a5d1fd66-fe5b-f52d-47de-6af3c71928f7
* Content: [Share a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
@davidyack thanks for the feedback. Looking into it.

**Comment by tapanm-MSFT** [comment]
@davidyack https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app#what-license-must-be-assigned-to-my-guest-so-they-can-run-an-app-shared-with-them lists license requirement for guest and https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#what-will-happen-to-the-powerapps-p1p2-and-microsoft-flow-plan-1-and-plan-2-plans-on-october-1-2019 explains license changes. The guest license table also includes licensing options - https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#how-is-microsoft-powerapps-and-microsoft-flow-licensed. With this, closing the comment but please feel free to reach out if any further questions.
