### ISSUE TITLE
O365 Business Premium User use PowerApp with premium connector?

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#75]
> Premium connectors require PowerApps Plan 1 or Plan 2. For more information, see PowerApps Plans.

Once I viewed PowerApps plans I read the following for Plan 1

> Create and run canvas apps that connect to a wide range of data sources using premium connectors

Suppose we design a PowerApps app with a premium connector (MySQL), do we need every user who uses the app to have a PowerApps Plan 1 license or will one for the designer of the app suffice and everyone else can use the PowerApps plan from O365 Business Premium?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df61b9fd-18b0-49c7-03f3-8b97aa67a601
* Version Independent ID: cc848247-8142-08bc-08c7-9ee11b55face
* Content: [Connectors overview for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list)
* Content Source: [powerapps-docs/maker/canvas-apps/connections-list.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections-list.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by gregdegruy** [comment]
Hello Team, 

Thank for taking a look into my request.
@lancedMicrosoft @bishalgoswami @AFTOwen @chad any updates that can be shared on this?

**Comment by lancedMicrosoft** [comment]
If you use a premium connector as part of your app.  Then, users who will use your app will need the same rights to the same premium connector you have.
