### ISSUE TITLE
Approver Field don't read data from ApproverName (Person or Group) in SharePoint

### ISSUE THREAD

**Issue by MrFearLess98** [MicrosoftDocs/powerapps-docs#751]
After installing the app and trying to test it, the field Approver didn't find any data from the column ApproverName in SharePoint while the type of this column in the list is Person or Group.
By default the function of this field is Choices(Expenses, ApproverName).
I have invited all the users to whom will use the lists in the site. Also the users already exist in Azure Active Directory.

So what should be the function to read data from the ApproverName column in the list ?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @yijw2017
* Microsoft Alias: **yijw**

**Comment by tapanm-MSFT** [comment]
@MrFearLess98 Please contact [support team](https://powerapps.microsoft.com/en-us/support/pro/) for help with resolving environmental issues.
