### ISSUE TITLE
Create a File Attribute

### ISSUE THREAD

**Issue by mathiasbl** [MicrosoftDocs/powerapps-docs#753]
How can we create this type of attribute? It's not possible through the SDK. 
Is it still preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c3eac9-b083-b974-0938-3e8fd19bbb58
* Version Independent ID: 2c6dfac6-25b8-876c-2b94-fa9d466007df
* Content: [File attributes (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/file-attributes)
* Content Source: [powerapps-docs/developer/common-data-service/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/file-attributes.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
@mathiasbl The new File attribute and updated Image attribute feature is rolling out to Microsoft data-centers over time. Your organization may not have received the update yet. You can periodically check your org for the File attribute by adding a new field to a customizable or custom entity and checking if "File" is available in the list of supported field data types. Do this in PowerApps under **Data** > **Entites** or in the classic web application under **Customizations**. I am working on adding a note about this to the developer documentation.
