### ISSUE TITLE
Wrong type for callbacks

### ISSUE THREAD

**Issue by fberasategui** [MicrosoftDocs/powerapps-docs#754]
success and failure parameters are of type function, not string.

Also, if you ask me, I'd like to see actual signatures for functions instead of just "function", for instance `() => string` or `unit -> string` a-la F#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c746abe6-1150-a2ce-521d-6e0796a532b5
* Version Independent ID: 46ca0562-758f-6d29-1784-060f56484904
* Content: [getResource - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/resources/getresource#feedback)
* Content Source: [powerapps-docs/developer/component-framework/reference/resources/getresource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/resources/getresource.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@fberasategui 
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
