### ISSUE TITLE
Please add a usage example

### ISSUE THREAD

**Issue by fberasategui** [MicrosoftDocs/powerapps-docs#755]
As per https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/Load-HTML-from-file-inside-PCF-Component/m-p/393852#M1135, the most obvious way to use this function is not working for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c746abe6-1150-a2ce-521d-6e0796a532b5
* Version Independent ID: 46ca0562-758f-6d29-1784-060f56484904
* Content: [getResource - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/resources/getresource#feedback)
* Content Source: [powerapps-docs/developer/component-framework/reference/resources/getresource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/resources/getresource.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@fberasategui Thanks for the feedback. Hope you have got enough information from the community thread. Closing the issue. Please reopen the issue if you have any further issues with the same.
