### ISSUE TITLE
'pcf-scripts' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#756]
My error message, for some reason this `pcf-script` comment is not being found.

```
C:\pac\LinearInputComponent>npm run build

> pcf-project@1.0.0 build C:\pac\LinearInputComponent
> pcf-scripts build

'pcf-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcf-project@1.0.0 build: `pcf-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcf-project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-10-31T06_33_25_716Z-debug.log
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Implementing code components using TypeScript - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by gregdegruy** [comment]
Was able to resolve running by running `npm i -g` to install my `devDependencies` globally. Not sure if this is the best practice solution and will wait for feedback.

my package.json devDependencies
```
"devDependencies": {
    "pcf-scripts": "^1",
    "pcf-start": "^1"
}
```

**Comment by Nkrb** [comment]
@gregdegruy Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.

**Comment by eromerof** [comment]
Hi @Nkrb 
In the community forum.. Where is the solution for this issue?

Thanks!

**Comment by Nkrb** [comment]
@eromerof I think the guy who had the issue never posted it in the forum. Please follow the steps as mentioned above and see if you can resolve the issue. If nothing works please raise the issue in the community forum, our developers are happy to help you resolve the issue.

**Comment by gregdegruy** [comment]
@eromerof  Was able to resolve running by running npm i -g to install my devDependencies globally. Not sure if this is the best practice solution and will wait for feedback.

my package.json devDependencies
```
"devDependencies": {
    "pcf-scripts": "^1",
    "pcf-start": "^1"
}
```

**Comment by sumitthakran** [comment]
hi guys,

i am also facing same issue . i tried running npm i -g command to install devDependencies.
but still my issue is not resolved.

Any help

Thanks

**Comment by Nkrb** [comment]
@sumitthakran Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.

**Comment by shalabhgupta1985** [comment]
Hi All,

Is there an update or a solution on this issue? I have started facing this issue since yesterday.

**Comment by sumitthakran** [comment]
hi shalab,

just check your folder directory is correct when you are running command :- npm install
also do not forgot to include below node in your package.json file
"devDependencies": {
    "pcf-scripts": "^1",
    "pcf-start": "^1"
}

my issue got resolved , i was running npm command in wrong folder. just remember that project which you created , only in that folder you run this command and add json change too in that project.
This json file is not your c:\windows\system32\package.json. 

Hope i am to explain to you.

Thanks

**Comment by Ale-Cesetti** [comment]
In my case I was able to fix this following step 4 of this link https://docs.microsoft.com/en-us/powerapps/developer/component-framework/create-custom-controls-using-pcf#create-a-new-component

npm install on your control folder :grinning:
