### ISSUE TITLE
Implement setFormType for read only and disable state

### ISSUE THREAD

**Issue by Miccomicc** [MicrosoftDocs/powerapps-docs#757]
Would be great to be able to set the entire form as read only or disabled, programmatically by client API or by a business rule.

Don't get why this is not available yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e7128f-8c02-38ef-60cd-df48cbd7894a
* Version Independent ID: b3a92845-c46b-165e-4021-d449f39689bd
* Content: [getFormType (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui/getformtype#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui/getFormType.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui/getFormType.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.
