### ISSUE TITLE
Deploy an PCF to an D365 on-premise with IFD

### ISSUE THREAD

**Issue by nzkelvin** [MicrosoftDocs/powerapps-docs#758]
Currently, I have a Dynamics 365 CE on-premise (latest version) setup with IFD. The users of the system also use the "Dynamics 365 for phones" app (model driven app) on their mobile phones. Can you please specify if I can deploy a PCF control to a Dynamics 365 CE on-premise instance with IFD? Thanks

**Comment by HemantGaur** [comment]
PCF is not available for on-prem yet and can only be used with the online instances. At this point on-prem support release date is not available.

**Comment by KumarVivek** [comment]
Thanks @HemantGaur!

@nzkelvin Closing the issue.
