### ISSUE TITLE
Note on Featured Apps [notifications]

### ISSUE THREAD

**Issue by TBag** [MicrosoftDocs/powerapps-docs#76]
The first note say "To receive push notifications, each user must have opened the app in PowerApps Mobile once or gotten the app from AppSource in Dynamics 365.",

Suggest adding that if the PowerApp is a Featured app then the app does not have to be previously opened to enable notifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f754f6-4b2b-b1c8-6b84-f74f578821c8
* Version Independent ID: 20df624c-87eb-0347-89f5-ef1d84b395af
* Content: [Send a push notification - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-notifications)
* Content Source: [powerapps-docs/maker/canvas-apps/add-notifications.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-notifications.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by AFTOwen** [comment]
Thanks, @TBag. The PM for that feature says that the current messaging is fine. Closing the issue.
