### ISSUE TITLE
Misleading link titles

### ISSUE THREAD

**Issue by pritchie99** [MicrosoftDocs/powerapps-docs#762]
This page contains 2 links that appear to link Flow with classic Workflows and Actions respectively, however these are simply legacy pages on Workflows and Actions.  They make no mention eg on how to trigger these from Microsoft Flows which would be great, or any other connection between the old and the shiny and new?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac15942-ff9e-f1f9-341f-09457dc15d2a
* Version Independent ID: ddc76673-c9d0-1bd3-0040-764380fa6e5e
* Content: [Apply business logic in Common Data Service - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/cds-processes#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/cds-processes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/cds-processes.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@pritchie99 - All the legacy workflow functionality from Dynamics 365 Customer Engagement apps (workflows and actions) have been moved under Power Automate. However, nothing has really changes with those legacy features as they still require Model-driven apps and Common Data Service to function and as such, use the same legacy tools to create and configure. 
Closing issue.
