### ISSUE TITLE
Error on uploading images from app downloaded from windows store.

### ISSUE THREAD

**Issue by totallyxtreme** [MicrosoftDocs/powerapps-docs#763]
I have created an app where I upload photos to onedrive store photo information into excel spreadsheet using this and a patch command on a button. The app and upload functionality works fine in powerapp on Ipads, Android phones but throws me 'Unknown error' on windows tablets for powerapp downloaded from windows store.
is there any setting that Iam missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158a7bb6-99a9-f3d3-a31b-a9ed075e4627
* Version Independent ID: f6fd9679-bd5b-3699-b8b6-a7a697041199
* Content: [Add picture control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-add-picture#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-add-picture.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-add-picture.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by chmoncay** [comment]
Hi there,
I want to make sure I get the scenario correct.  Was this One Drive (hotmail.com/outlook.com) or One Drive for Business?

**Comment by totallyxtreme** [comment]
Hi,
It is OneDrive for Business. But I think the problem is on both.

**Comment by totallyxtreme** [comment]
Just got a response on the powerusers community saying that some features like this one is not supported by Powerapps on windows.
https://powerusers.microsoft.com/t5/Building-Power-Apps-Formerly/unknown-error-while-uploading-photos-on-windows-tablets/m-p/396190#M115825

**Comment by tapanm-MSFT** [comment]
Hello, thanks for reaching out. Please note the system requirements for canvas apps when using Power Apps mobile app: 

https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#supported-platforms-for-running-canvas-apps-using-the-power-apps-mobile-app
