### ISSUE TITLE
The event tab is not available on the model-driven form editor

### ISSUE THREAD

**Issue by cleitonsantos** [MicrosoftDocs/powerapps-docs#764]
Either for forms or fields, the event tab is not available on the model-driven form editor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a6d58d-c41d-e5a2-ebbd-3882f74acba8
* Version Independent ID: fc616581-407a-7ee5-fe51-57a86679737d
* Content: [Events in forms and grids in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/events-forms-grids#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/events-forms-grids.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/events-forms-grids.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
You need to go into **Customizations > Entities > Forms > Select the form > Click on Form Properties**.

**Comment by Nkrb** [comment]
@cleitonsantos 
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by cleitonsantos** [comment]
Hi Nkrb, I followed your instructions but there is no Form Properties option anywhere on the screen
![image](https://user-images.githubusercontent.com/1679998/76247537-16d3c000-6216-11ea-8f28-b8a2e89b6477.png)

**Comment by cleitonsantos** [comment]
Hi Nkrb, I followed your instructions but there is no Form Properties option anywhere on the screen

![image](https://user-images.githubusercontent.com/1679998/76250731-31109c80-621c-11ea-80fc-633c2f2696b2.png)

**Comment by Nkrb** [comment]
@cleitonsantos Open the form and click on the button **Switch to classic**  and the form opens up in the classic editor. Some of the features are still not available in the modern editor. 
![image](https://user-images.githubusercontent.com/34038327/76255649-c7889200-620b-11ea-9792-0aa22a829219.png)
