### ISSUE TITLE
roles is undefined

### ISSUE THREAD

**Issue by aliyoussefi** [MicrosoftDocs/powerapps-docs#767]
This document is missing the roles property of the userSettings object. This is useful to show the combination of both the ID and Name of the current user's security roles. This will impact performance and maintainability by reducing calls back to the API to determine name for roles.

**Comment by Nkrb** [comment]
@aliyoussefi Can you point us to the docs that you're talking about.

**Comment by tapanm-MSFT** [comment]
Hello, https://docs.microsoft.com/powerapps/developer/component-framework/reference/usersettings references securityRoles property. If this is for a different docs article, please reopen or submit a docs issue on the respective page.
