### ISSUE TITLE
What is the benefit and impact of changing domains of portal?

### ISSUE THREAD

**Issue by Prashant4787** [MicrosoftDocs/powerapps-docs#768]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2444609-ebf1-87a2-0f77-5c2fecb2f7cd
* Version Independent ID: 79c5d468-c817-a153-3353-7fd93edd8817
* Content: [Update from Dynamics 365 domain to PowerApps portals domain - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/update-portal-domain)
* Content Source: [powerapps-docs/maker/portals/admin/update-portal-domain.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/update-portal-domain.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please review note regarding [deprecation](https://docs.microsoft.com/powerapps/maker/portals/admin/update-portal-domain) of microsoftcrmportals.com which is also in line with [the branding change](https://docs.microsoft.com/powerapps/maker/portals/faq#what-is-the-difference-between-power-apps-portals-dynamics-365-portals-and-add-on-portals).
