### ISSUE TITLE
A known bug in Patch mentioned in this page would have saved me a bunch of time when building an offline app

### ISSUE THREAD

**Issue by ShawnPOWER** [MicrosoftDocs/powerapps-docs#769]
It would be great if this page mentioned something about the bug in Patch when updating a SharePoint list column which is empty. Then a solution to use UpdateIf to work around it. Explained in more depth here: https://powerusers.microsoft.com/t5/Building-Power-Apps-Formerly/Unable-to-Patch-Empty-Fields-in-Collection-created-from-a/m-p/266837#M77970

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5786697f-ee29-1b61-c59a-955086201d55
* Version Independent ID: d2130620-9767-c72f-5bd7-8417e48cf65d
* Content: [Patch function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by KumarVivek** [comment]
@tapanm-MSFT Can you please take of this issue.

**Comment by tapanm-MSFT** [comment]
@ShawnPOWER acknowledged and will go through. Thank you for your feedback.

**Comment by gregli-msft** [comment]
Thanks for raising this.  The bug in the product has been fixed with version 3.20051.16, available with the Frequent cadence in some regions (I tested in Canada).  Please give it a try and let us know if it is not working properly.  Much better than adding a workaround to the docs.
