### ISSUE TITLE
Non-Visual Studio PCF development?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#770]
Hello,
I'd like to develop custom components using linux. Is Visual Studio a requirement for PCF development? At a cursory glance, it appears that as long as `npm` and `PowerApps CLI` are installed on my system I should be good to go. 
Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Implementing code components using TypeScript - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@SeaDude Visual Studio is required for MS Build. You can also install MSBuild as a standalone application, but we recommend you to have Visual Studio installed.

**Comment by Nkrb** [comment]
Closing the issue.
