### ISSUE TITLE
No data source providedfor Help Desk canvas help

### ISSUE THREAD

**Issue by mando211** [MicrosoftDocs/powerapps-docs#771]
Ive followed the steps for the Help Desk Canvas Apps but when i wanted to create the ticket, its shows "No data source provided"

Can anyone help me

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please make sure to follow documented steps for [creating connections](https://docs.microsoft.com/powerapps/maker/canvas-apps/help-desk-install#create-connections). If problem persists, the issue needs investigation as an incident. Please reach out to via a [support service request](https://powerapps.microsoft.com/support/pro/) for further help.
