### ISSUE TITLE
"App settings" is now "Settings"

### ISSUE THREAD

**Issue by KoBe321** [MicrosoftDocs/powerapps-docs#772]
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/component-framework-for-canvas-apps#enable-powerapps-component-framework-feature

At step 6, "App settings" is now "Settings" on the UI.
![settings](https://user-images.githubusercontent.com/8909363/68475131-8ebdb980-0227-11ea-9a85-e4980acfe8ca.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8124234-fccb-85af-9ee8-13729326c727
* Version Independent ID: d53c2fc1-dd63-eee4-26a7-22715f27b943
* Content: [PowerApps component framework for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/component-framework-for-canvas-apps)
* Content Source: [powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@KoBe321  Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
