### ISSUE TITLE
Outdated version recommendations for Node.js

### ISSUE THREAD

**Issue by KoBe321** [MicrosoftDocs/powerapps-docs#773]
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/get-powerapps-cli#install-microsoft-powerapps-cli

Latest LTS of Node is now 12.13.0, not 10.15.3 (maybe version info could be removed?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49dacb11-ddd9-9d58-333c-b9e7feecf0d3
* Version Independent ID: 32b7cc6e-c726-2212-5e15-a26c321dd86c
* Content: [Get tooling for PowerApps component framework - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/get-powerapps-cli)
* Content Source: [powerapps-docs/developer/component-framework/get-powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/get-powerapps-cli.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@KoBe321 Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
