### ISSUE TITLE
Instruction is not clear

### ISSUE THREAD

**Issue by KoBe321** [MicrosoftDocs/powerapps-docs#774]
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript#packaging-your-code-components

1. Create a new folder **Solutions** inside the LinearComponent folder and **navigate into** the folder.
2. Create a new solution project **in the LinearComponent** folder using the following command: `...`

It's not clear whether I should run the command given in step 2, in the Solutions or int the LinearComponent folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Implementing code components using TypeScript - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@KoBe321 Thanks for the feedback. You need to create the project inside the solutions folder. Actually it doesnt matter where you create the solution project, cause you will need to add a reference path to the actual sample project location inorder to create a solution zip file.

**Comment by Nkrb** [comment]
Closing the issue.
