### ISSUE TITLE
Components is now Custom

### ISSUE THREAD

**Issue by KoBe321** [MicrosoftDocs/powerapps-docs#775]
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/component-framework-for-canvas-apps#add-components-to-a-canvas-app

At step 3, Components is now Custom.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8124234-fccb-85af-9ee8-13729326c727
* Version Independent ID: d53c2fc1-dd63-eee4-26a7-22715f27b943
* Content: [PowerApps component framework for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/component-framework-for-canvas-apps#add-components-to-a-canvas-app)
* Content Source: [powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/component-framework-for-canvas-apps.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@KoBe321 
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
