### ISSUE TITLE
Input binding is broken

### ISSUE THREAD

**Issue by KoBe321** [MicrosoftDocs/powerapps-docs#776]
Create a component based on the docs but use an input text instead of the slider.
Modify the value of the input using 'Data Inputs'.
![1](https://user-images.githubusercontent.com/8909363/68589788-2c65f280-048d-11ea-8920-7de5bd00f19d.PNG)
The value is updated in the input field.
Modify the value in the input field.
![2](https://user-images.githubusercontent.com/8909363/68589851-4f90a200-048d-11ea-95d3-ca052794339e.PNG)
The new value is reflected in the 'Data Inputs' and 'Data Outputs' appear with the correct value.
Modify the value again from the 'Data Inputs'.
![3](https://user-images.githubusercontent.com/8909363/68589896-6fc06100-048d-11ea-81ce-d05504c8d7f3.PNG)
The value is not reflected in the input field, not in the 'Data Outputs', but the value of the input field is set correctly.
The situation is the same for the slider when following the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc8bc19-4e5e-b6f4-34ef-77b004c2afd6
* Version Independent ID: 847c467c-0015-1eb9-bdc7-720a40f1cdba
* Content: [Implementing code components using TypeScript - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/implementing-controls-using-typescript)
* Content Source: [powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/implementing-controls-using-typescript.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@KoBe321 
Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue.

**Comment by KoBe321** [comment]
In this docs, the value of the input field is set by
` this.inputElement.setAttribute( "value", newValue);`
but in the example components this is used
`this.label.value = newValue;`
and correctly triggers the change detection.
