### ISSUE TITLE
The Patch Function returns the created or updated item. 

### ISSUE THREAD

**Issue by Pieter-Veenstra** [MicrosoftDocs/powerapps-docs#777]
The Patch Function returns the created or updated item. Making it possible to get the ID of the created item. 

This should be documented.

I've created a blog post to cover the issue:
https://veenstra.me.uk/2019/11/11/using-patch-to-create-a-sharepoint-list-item-in-power-apps/

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. Patch function [documentation](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-patch#merge-records-outside-of-a-data-source) mentions the relevant content: 
*Patch returns the merged record*
