### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerapps-docs#78]
The choice to use get/set-admin* is not consistent with other powershell modules and is not intuitive. We are not trying to set an admin object, we are trying to set a flow or PowerApp object. The role of the person executing the cmdlet should be included in the cmdlet name. If absolutely necessary, the role of person running the cmd should be included as a parameter, but ideally the role should be determined automatically by the context of the account.  I'm not aware of any other powershell modules that require this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a682d40-fb0d-4938-b1ac-cee291c2bbff
* Version Independent ID: c7fdffb8-c6b7-f02b-a5e0-6787218978c6
* Content: [PowerShell support (preview) - PowerApps](https://docs.microsoft.com/en-us/powerapps/administrator/powerapps-powershell#powerapps-cmdlets-for-administrators-preview)
* Content Source: [powerapps-docs/administrator/powerapps-powershell.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/administrator/powerapps-powershell.md)
* Service: **powerapps**
* GitHub Login: @jamesol-msft
* Microsoft Alias: **jamesol**

**Comment by jimholtz** [comment]
@DeanGross 
Sorry for the much delayed response. Clearing a backlog, we noticed this hadn't be resolved. Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.
