### ISSUE TITLE
Incorrect Instruction on #14

### ISSUE THREAD

**Issue by nsearle97** [MicrosoftDocs/powerapps-docs#780]
Instruction number 14 says to find the line "oauth2AllowImplicitFlow", however the screenshot below is highlighting a line called "oauth2AllowUrlPathMatching". It isn't clear whether the screenshot is correct or the written instruction

**Comment by Nkrb** [comment]
@nsearle97 Can you point us to the doc that you're talking about.

**Comment by nsearle97** [comment]
@Nkrb Sorry I clicked through from the docs site and thought it was linked. It was this one here: [https://docs.microsoft.com/en-gb/powerapps/developer/common-data-service/walkthrough-registering-configuring-simplespa-application-adal-js](url)

**Comment by Nkrb** [comment]
@nsearle97 Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
