### ISSUE TITLE
UCI parameter to MyFunction is different than described.

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#782]
In the classic UI, the parameter passed into the MyFunction reference is the object described in the linked "execution context" page. You can use that object to call getFormContext(), and the object returned by that call has .data and .ui properties as expected.

However, in the UCI, while the object passed into MyFunction does have a "getFormContext" method, the object returned by this method does not have .data and .ui properties. Instead, this object has itself a .formContext property which is an object with .data and .ui properties.

So, for example, if I needed to get the current record's ID inside the onLoad event of a sub-grid, I would first have to determine which UI is being loaded, then call the correct sequence:

executionContext.getFormContext().formContext.data.entity.getId() //UCI
executionContext.getFormContext().data.entity.getId() //Classic

This discrepancy should be noted in the documentation until it is fixed in the platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16f277f8-bbb2-c3d4-5b7f-67dd9b3d591c
* Version Independent ID: 4f45ed87-b1ff-94e6-d4a7-521f32db8138
* Content: [addOnLoad (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/grids/gridcontrol/addonload)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridcontrol/addOnLoad.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/grids/gridcontrol/addOnLoad.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@devlinl Can you confirm if this still happening.

**Comment by devlinl** [comment]
It appears to be fixed.

Thanks,

Liam Devlin
Senior Architect, Microsoft Dynamics Higher Education
Liam@xRM.com<mailto:Liam@xRM.com>
725-696-7234
xRM<xrm.com> | NexGen Advancement Solutions

**Comment by Nkrb** [comment]
@devlinl Thanks for the update. Closing the issue. If you need further help, please reopen or create a new issue.
