### ISSUE TITLE
PDF link not working

### ISSUE THREAD

**Issue by houstonbrooke** [MicrosoftDocs/powerapps-docs#783]
The link to the PDF playbook doesn't do anything, it's like it's an empty link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce885f5-df3a-127c-3474-b0d1ac7509b4
* Version Independent ID: 8031dba0-83ed-e625-e3ca-c8227c688bc4
* Content: [Unified Interface Playbook - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/unified-interface-playbook#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/unified-interface-playbook.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/unified-interface-playbook.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by KumarVivek** [comment]
@houstonbrooke The link to the PDF handbook prompts you to download the PDF file. Here is the actual link that it points to: https://download.microsoft.com/download/A/F/3/AF3D45A7-4F38-41BE-8956-1DF7A4A5AFDB/dynamics365unifiedinterfaceplaybook.pdf

Closing the issue.
