### ISSUE TITLE
Dead links in article

### ISSUE THREAD

**Issue by bhall999** [MicrosoftDocs/powerapps-docs#788]
6th Paragraph of article includes dead links.  I'm not sure where they should point to, so can't recommend edits.
Article:
[powerapps-docs/powerapps-docs/maker/canvas-apps/functions/function-dateadd-datediff.md](powerapps-docs/powerapps-docs/maker/canvas-apps/functions/function-dateadd-datediff.md)

Text excerpt:

> Also see Date, Time, and DateTime data types

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The content link is fixed.
