### ISSUE TITLE
Why is this page dated 03/26/2019 

### ISSUE THREAD

**Issue by xairrick** [MicrosoftDocs/powerapps-docs#790]
It doesn't appear that 03/26/19 is the created date nor last modified date.  So where did this date come from.   It should have a created date and last updated date,  so it's clear to people that changes have been made.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8213b8-93bc-dee0-5b82-973db16f03fa
* Version Independent ID: 161512ac-81c1-4163-20e1-e440497d2e24
* Content: [Use connection strings in XRM tooling to connect to Common Data Service (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md)
* Service: **powerapps**
* GitHub Login: @MattB-msft
* Microsoft Alias: **nabuthuk**

**Comment by KumarVivek** [comment]
@xairrick We'll update the date based on the latest updates to the topic. Closing the issue.

**Comment by xairrick** [comment]
The page was updated Oct 2nd (had to dig through github to find it), but the date shows March.   Anyone who read/review the page recently would awesome there is nothing new to read and skip over it.
