### ISSUE TITLE
Closing dialog through custom button

### ISSUE THREAD

**Issue by mathiasbl** [MicrosoftDocs/powerapps-docs#791]
Hi,

Is there any way we can create our own button which will close the dialog like the default one provided?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@mathiasbl No, there isn't any provided as part of this API. Closing the issue.

**Comment by mathiasbl** [comment]
@KumarVivek Can you check with the technical team? Why allow us to spawn a modal dialog when we can't even close it through a custom button. Forcing a user to click the default one isn't user friendly at all!

**Comment by abdelaziz-benelfakir** [comment]
You can try this 
$("button[data-id='dialogCloseIconButton']", parent.document).click();

That's working for me

**Comment by vaughn-pworx** [comment]
> @mathiasbl No, there isn't any provided as part of this API. Closing the issue.

If anyone ever wonders why people don't much care for developing on Dynamics/PowerApps, this is a key reason right here. Great potential to add a useful feature to the system, but closed without a good reason. I would recommend better coordination between teams, this type of feature would be extremely strategic for those of us that are attempting (and frustrated) with product development on dynamics. Good dialog support is simply not available in the platform right now.

**Comment by Usmankhan10** [comment]
**self.close()** 
works you can try that.
