### ISSUE TITLE
Instructions refer to "oauth2AllowImplicitFlow," but the screenshot shows "oauth2AllowUrlPathMatching."

### ISSUE THREAD

**Issue by HarryGifford** [MicrosoftDocs/powerapps-docs#792]
In Step 14 the text refers to "oauth2AllowImplicitFlow," but the screenshot shows "oauth2AllowUrlPathMatching." Please could you update the docs with whichever one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f1b8580-0f68-7d02-fd19-4c087e6659b9
* Version Independent ID: 3b74fd46-f2af-e44d-1199-6e2494669576
* Content: [Walkthrough: Registering and configuring SimpleSPA application with adal.js (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-registering-configuring-simplespa-application-adal-js)
* Content Source: [powerapps-docs/developer/common-data-service/walkthrough-registering-configuring-simplespa-application-adal-js.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/walkthrough-registering-configuring-simplespa-application-adal-js.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **nabuthuk**

**Comment by paulliew** [comment]
@Jim Daly to review

**Comment by paulliew** [comment]
@Jim Daly<mailto:Jim.Daly@microsoft.com> (or Peter) to review
Thanks
Paul

**Comment by KumarVivek** [comment]
@phecke Can you please review this.

**Comment by phecke** [comment]
This has been fixed, and the updates are live.

**Comment by phecke** [comment]
@HarryGifford Thanks for catching this.
