### ISSUE TITLE
How to change the color of the row based on data inside a column

### ISSUE THREAD

**Issue by SwamyNallamalli** [MicrosoftDocs/powerapps-docs#794]
Is there a way to show different color for the row inside the grid based on a condition on a column value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94785ec1-e3da-4ff2-59b6-19bd28bb8680
* Version Independent ID: 4b3e4efa-1d15-2a71-fe61-ee949c54279c
* Content: [Data table control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-data-table#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-data-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-data-table.md)
* Service: **powerapps**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by Rizver** [comment]
I would like to know if and when we will be able to customize (color code) columns and/or rows based on the data in a record?

Thanks!

**Comment by tapanm-MSFT** [comment]
Please reach out to the [Power Apps Ideas Forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) with the feature ask and vote for existing ideas.
