### ISSUE TITLE
Provide a usefull example of executing requests using WebApi

### ISSUE THREAD

**Issue by zhaparoff** [MicrosoftDocs/powerapps-docs#795]
I think WhoAmI request example is too simple. No parameters are passed, no entity is bound.

Can you please provide example of more complicated request. For example, ExecuteWorkflow - I can see a whole dozen of requests in the web looking for such example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: badde453-a02f-72e1-22dd-3be9ed53a4c0
* Version Independent ID: 1904f78b-93c7-86f8-d6f2-96c4e6041f11
* Content: [Xrm.WebApi.online.execute (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online/execute#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/online/execute.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by EHulburd** [comment]
Yes please add an example with a bound custom action.

**Comment by Nkrb** [comment]
@zhaparoff Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
