### ISSUE TITLE
Add features to existing portal

### ISSUE THREAD

**Issue by valdik5379455** [MicrosoftDocs/powerapps-docs#798]
After creating a PowerApps portal using one of templates, is it possible to add features from a different template? (e.g. Ideas feature to Customer self-service portal)?

If it's possible, then this page should describe how to do it (or link to relevant doc page).
If it's not possible, then it should be included as a note, because it's important to know that you'll be stuck with features of a template you pick.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6275ab57-197d-4871-7003-9d5dddc0caa2
* Version Independent ID: c2a49e45-ba1d-f1d4-ff52-b9d1fd4466fe
* Content: [Portal templates available in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/portal-templates)
* Content Source: [powerapps-docs/maker/portals/portal-templates.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/portal-templates.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This is being considered for future review. You can also submit this as an idea and vote for it at [Power Apps Ideas](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
