### ISSUE TITLE
"Turning off Snap to columns" Alt Key

### ISSUE THREAD

**Issue by kucster** [MicrosoftDocs/powerapps-docs#799]
In the paragraph "Turning off Snap to columns" you reference using the Alt key to do a few things but this does not seem to work as the Alt key is now for running the commands for testing. I'm sorry I don't know what replaced it thought to help with the update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e4a709-4cf4-5e0a-fafd-d6e531cdfba2
* Version Independent ID: d68ff8b8-3694-a8a7-2ad9-9119f7666167
* Content: [Understand data-form layout for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-form-layout#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-form-layout.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-form-layout.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by MellowYellow85** [comment]
Ctrl works for me. Although you seemingly can't reposition cards with drag & drop. It still says snapped in some form.

**Comment by kucster** [comment]
I can't seem to get it to un snap either. I had to work around it by adjusting the content.

**Comment by gregli-msft** [comment]
Thanks for the bug report!  The secret answer is to hold down Alt key *after* initiating the resize or reposition of the data card or control.   We have not been advertising this fact adequately, so I've updated both this article and the [keyboard shortcuts for canvas apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/keyboard-shortcuts) which has an animation of using this method to resize a data card.

**Comment by rjgeeky** [comment]
There's now an orphaned 'For' at the end of the second paragraph in the 'Turning off Snap to columns' section. I presume this happened while editing to add the clarifying instructions with the Alt key.

**Comment by tapanm-MSFT** [comment]
Thank you, content is updated. Please allow some time to reflect the changes.
