### ISSUE TITLE
Generate favicons and mobile icons

### ISSUE THREAD

**Issue by mblase75** [MicrosoftDocs/powerapps-docs#80]
It would be ideal if this custom icon was used to generate a favicon and/or apple-touch-icon for the app as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08212b0e-7ebe-9189-4de6-b64812f85911
* Version Independent ID: a5509a57-698d-9d9e-eea7-a433a31c22b7
* Content: [Change app name and icon for a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/set-name-tile)
* Content Source: [powerapps-docs/maker/canvas-apps/set-name-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/set-name-tile.md)
* Service: **powerapps**
* GitHub Login: @lonu
* Microsoft Alias: **lonu**

**Comment by AFTOwen** [comment]
Hey, @mblase75! This repo is for the PowerApps documentation. If you want to make a product suggestion, you can post it [here](https://powerusers.microsoft.com/t5/PowerApps-Ideas/idb-p/PowerAppsIdeas). Cheers,
AFO
