### ISSUE TITLE
What is the difference between PowerApps Portals and D365 CE Add-on portals?

### ISSUE THREAD

**Issue by Prashant4787** [MicrosoftDocs/powerapps-docs#801]
Please explain in-depth difference in PowerApps Portals and Add-on portal with respective of various factors like licensing ,solutioning , installation and user experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca7cc650-6182-0bdf-2bfb-68e09b3e7a2b
* Version Independent ID: 90672b02-94cd-b93b-adb3-9e57aace8c3b
* Content: [What is PowerApps portals? - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/overview#feedback)
* Content Source: [powerapps-docs/maker/portals/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/overview.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by ZohaibUddinKhan** [comment]
I also have the same question as Prashant4787 asked. Plus, when portal is getting compatible with Bootstrap 4? Thanks.

**Comment by ehandani** [comment]
it's the same exact thing.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please read the updated [Power Apps portals FAQ](https://docs.microsoft.com/powerapps/maker/portals/faq)  to learn more regarding portal differences including licensing, portal creation and features. At present, Power Apps portals does not support Bootstrap 4. You can submit your feedback on [Power Apps Ideas](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Update-the-portal-to-Bootstrap-4/idi-p/225373) for consideration.
