### ISSUE TITLE
Missing filter example with number values

### ISSUE THREAD

**Issue by boltlol** [MicrosoftDocs/powerapps-docs#803]
I am looking for an example with a filter for numbers such as accountnumbers. A query with numbers as an example with just numbers would be awesome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715bc26c-2ccd-a040-3c96-d73cde4b982b
* Version Independent ID: c793e872-29e4-2e04-b9f4-973c01d4a123
* Content: [Embed a Power BI report in a model-driven system form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embed-powerbi-report-in-system-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md)
* Service: **crm-online**
* GitHub Login: @prsi-msft
* Microsoft Alias: **prsi**

**Comment by Mattp123** [comment]
@boltlol - Thank you for your request to enhance the documentation. This request has been recorded and it will be considered for a future update to the documentation.
Closing issue.
