### ISSUE TITLE
How it relates to "Requests limits and allocations" article

### ISSUE THREAD

**Issue by marcuss75** [MicrosoftDocs/powerapps-docs#804]
How this article, and the described limits, relate to what described in the following one?

https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#non-licensed-usersapplication-users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd657fb-b2cb-a85a-7243-41d7cc30dc87
* Version Independent ID: 4ed6833a-668b-ff05-97da-286fb6d68394
* Content: [API Limits (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits)
* Content Source: [powerapps-docs/developer/common-data-service/api-limits.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/api-limits.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **bsimons**

**Comment by JimDaly** [comment]
The link you mention is about _Entitlement_ limits and how they apply to Non-licensed users/application users/Users with special free licenses.

This topic is specifically about how _Service Protection_ limits are applied and how developers writing code can deal with them.  I've re-titled this topic to make that clearer.

I also added this new topic [Power Platform / PowerApps / Create apps / Common Data Service / API limits overview
](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview)

This new topic should help clarify how Entitlement and Service Protection limits are different.
Service Protection limits apply to all users regardless of the request allocation entitlement.

One analogy could be that Entitlement describes how many miles you can drive in a rented car. Service Protection describes how fast you can drive. I hope this helps.

**Comment by marcuss75** [comment]
Hi Jim, thanks for clarification!
