### ISSUE TITLE
setValue issue for string field with AutoComplete control

### ISSUE THREAD

**Issue by jaimieji** [MicrosoftDocs/powerapps-docs#805]
I think there is an issue with string field. If the field is applied with a auto complete control, the setValue seems not working. This is from the latest version of Unified Interface. Can someone please check and provide a response?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2713f7a-1bb6-ded7-82dc-70c9ce517a49
* Version Independent ID: 14c24456-b266-9407-975d-d83062765ff9
* Content: [setValue (Client API reference) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/setvalue#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/setValue.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/setValue.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@jaimieji I tried to create a single line of text field and add a Auto-complete control with option set assigned to it. When i try to `setValue`, I'm able to do that in the atleast UCI. Can you confirm if you're still facing the issue.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
