### ISSUE TITLE
Cannot import the app because the cannot select Office 365 outlook connection

### ISSUE THREAD

**Issue by distinctapp** [MicrosoftDocs/powerapps-docs#807]
I am currently stuck on step 14 under "Import the app". I have added the connection as directed in the previous steps but still it doesn't show up for selection. I have repeatedly clicked the "Refresh list" button which doesn't seem to do anything. I have also clicked the "Create New" button and created the connection multiple times but still, it doesn't show up for selection. I don't know if this is a bug with PowerApps as a whole or with the app package itself. Because of not being able to get past this step, I cannot import the package and make use of the app sample. I have tried this from multiple browsers and even from another machine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
@distinctapp Thank you for reaching out. This is not an issue with the feature or the package but appears to be environmental issue. Please contact [support team](https://powerapps.microsoft.com/en-us/support/pro/) for help with resolving environmental issues.
