### ISSUE TITLE
Assertion operator for the latitudeValue.raw is missing

### ISSUE THREAD

**Issue by shunkino** [MicrosoftDocs/powerapps-docs#808]
Sample code in "Code" section will fail to build, since the assertion operator is missing.

Downloadable sample code (https://go.microsoft.com/fwlink/?linkid=2088525) has correct assertion for latitudeValue.raw and buildable.

Small modification to the code will fix the problem in the sample code on this page.

**Current code:**
```
let latitude: number = context.parameters.latitudeValue.raw;
let longitude: number = context.parameters.longitudeValue.raw;
```

**Fixed code with assertion operator:**
```
let latitude: number = context.parameters.latitudeValue.raw!;
let longitude: number = context.parameters.longitudeValue.raw!;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ba395c-fd91-a615-6ac2-37163bd7c42c
* Version Independent ID: 59311ece-00da-1243-625a-59165868f329
* Content: [IFRAME component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/iframe-control#feedback)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/iframe-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/iframe-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@shunkino 
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.

**Comment by shunkino** [comment]
@Nkrb 
Thank you for the fix :)

I should've commented earlier, but I've also noticed,  probably, the sentence below is also outdated.
Could not find ```ControlFramework.d.ts``` generated in latest CLI environment.

```
ControlFramework.d.ts needs to be updated to add two fields to IInputs interface. This is the format the PowerApps component framework passes the field values. Adding these values to the IInputs interface allows your TypeScript file to reference the values and compile successfully.

    export interface IInputs 
    { latitudeValue: ControlFramework.PropertyTypes.NumberProperty;  
        longitudeValue: ControlFramework.PropertyTypes.NumberProperty;  
    }  
```

Instead, file ```ManifestTypes.d.ts``` is generated and interface IInputs is defined there. I Also found some other samples also has reference to  ```ManifestTypes.d.ts```. https://github.com/MicrosoftDocs/powerapps-docs/search?q=ControlFramework&unscoped_q=ControlFramework

As I'm pretty new to the Power Apps platform, I might be wrong. Could you please take a look?

**Comment by Nkrb** [comment]
@shunkino Thanks again for the feedback. Fixed the issues that you have mentioned
