### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerapps-docs#81]
"and the ability create custom option sets"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e07e18b-2d86-02be-9b86-1532b4c7b6e3
* Version Independent ID: aa956ed2-4021-f337-5a39-b99d816b07e0
* Content: [Create an Option set - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/custom-picklists)
* Content Source: [powerapps-docs/maker/common-data-service/custom-picklists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/custom-picklists.md)
* Service: **powerapps**
* GitHub Login: @clwesene
* Microsoft Alias: **clwesene**

**Comment by Mattp123** [comment]
@chrisweis - thank you for your feedback. This has been fixed in our publishing master branch  via the commit below pending publish. https://github.com/MicrosoftDocs/powerapps-docs-pr/commit/b568c58a254dc18247f20732de8c3a2f6504f612
Closing issue.
