### ISSUE TITLE
Component not showing up in `Custom` tab after attempting to import it

### ISSUE THREAD

**Issue by tim-de-wilde** [MicrosoftDocs/powerapps-docs#811]
When I try to import my custom component into a canvas app, it simply doesn't show up in de `Custom` tab (`Aangepast` in my language). After clicking `import`, the loading pop-up will appear as usual and after a second or two it has appeared to have finished loading. The component doesn't show up though.

I've imported components in the exact same way in the past week (and it worked), but somehow it stopped working today. Any ideas?

![img1](https://user-images.githubusercontent.com/40461212/69423540-a9fbef00-0d26-11ea-93e7-8e0d6d3d27b5.PNG)
![img2](https://user-images.githubusercontent.com/40461212/69423541-a9fbef00-0d26-11ea-915e-936a72301f59.PNG)

**Comment by Nkrb** [comment]
@tim-de-wilde Thanks for the feedback. New changes have been rolled out on how to add components to an app. We are updating the docs with the latest changes.

**Comment by Nkrb** [comment]
@tim-de-wilde 
Thanks for the feedback. We have updated the docs with the correct information and pushed to live. Closing the issue.
