### ISSUE TITLE
Remove the ODCA tool link

### ISSUE THREAD

**Issue by RajyashreeSingh** [MicrosoftDocs/powerapps-docs#819]
Hi there,

This doc site has the mention of ODCA (On-Demand Code Analysis tool) and it's hyperlinked. Since we are in the process of removing partner's access to this tool, could you please remove the hyperlink and keep it flat without any URL attached.

Thanks,
Rajyashree

**Comment by RajyashreeSingh** [comment]
Hi there,
Just wanted to follow up on this request. Could you please give me an ETA on this?

Thank you,
Rajyashree

**Comment by tapanm-MSFT** [comment]
Can you please share the docs URL that you refer to here? [App certification checklist](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/appendix-app-certification-checklist) doesn't seem to list it; if it was for this URL.

**Comment by tapanm-MSFT** [comment]
Closing due to no response.
