### ISSUE TITLE
Specific documentation for each sample app

### ISSUE THREAD

**Issue by sagostini** [MicrosoftDocs/powerapps-docs#82]
"Be sure to check out documentation specific to each sample app for more details." but I wasn't able to find any specific documentations for Innovation Challenge sample app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecbf56cc-ec02-2294-f98e-ade06b4fc3ec
* Version Independent ID: 7baf1d08-8689-1965-83cf-9c2a3615693f
* Content: [Model-driven sample apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/overview-model-driven-samples#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/overview-model-driven-samples.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/overview-model-driven-samples.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by Mattp123** [comment]
Closing.
