### ISSUE TITLE
Reset Property Is Missing

### ISSUE THREAD

**Issue by yourekittenme** [MicrosoftDocs/powerapps-docs#820]
Reset Property Is Missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51b1efea-d75c-b595-a9a1-14dec901ab48
* Version Independent ID: 9b1b0a35-35ad-8359-e1ab-daa80ab58c19
* Content: [Gallery control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-gallery#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-gallery.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-gallery.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
Hi there, you can use the Reset() function to reset your gallery back to it's initial state. Initial state includes scrolling to the first item and selecting the first item or default if present. 
Usage: Reset(GalleryInstanceName). 
**Note:** Will not recursively reset all the children of gallery.

Hope this helps.  I noticed this isn't listed in the document, I will add it.

**Comment by tapanm-MSFT** [comment]
https://docs.microsoft.com/powerapps/maker/canvas-apps/controls/control-gallery#related-functions lists reset function.
