### ISSUE TITLE
NavigateTo Dialog buttons - any plan to add them?

### ISSUE THREAD

**Issue by captjoemcd** [MicrosoftDocs/powerapps-docs#826]
As the previous commenter mentioned, without close and cancel buttons, this is pretty worthless to us, whereas with them it will be exceptionally good.  Is there any plan to add them?

**Comment by mathiasbl** [comment]
Mentioning the other issue: https://github.com/MicrosoftDocs/powerapps-docs/issues/791

**Comment by skoofy5** [comment]
+1 to this... Great feature, but without the ability to go to the next step of my process it's hard. I can't expect users to close out the dialog to get the next step happening.

**Comment by Nkrb** [comment]
@captjoemcd @skoofy5 Thanks for your feedback. Please visit https://ideas.powerapps.com to enter your ideas or feature requests. Closing this issue.
