### ISSUE TITLE
Global variable syntax @[Radius] vs [@Radius]

### ISSUE THREAD

**Issue by amqureshi** [MicrosoftDocs/powerapps-docs#827]
Little error in https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-variables#reading-variables

Instead of @[Radius] it should be [@Radius]

From https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/operators#disambiguation-operator 

To access global values, such as data sources, collections, and context variables, use the pattern [@ObjectName] (without a table designation).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f93a150-c9c8-9795-60ea-5888ae895e50
* Version Independent ID: 905345c4-35e1-d37f-12b3-3881f00591e0
* Content: [Understand variables in canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-variables#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-variables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-variables.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the bug report!  The article has been fixed.
