### ISSUE TITLE
Can I create Web Application in On-Premise with Common Data Service as backend to it ?

### ISSUE THREAD

**Issue by Jayesh040** [MicrosoftDocs/powerapps-docs#829]
Can we create Web Application with any language in On-Premise with Common Data Service as backend to it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2684981b-c955-e943-8415-d03ca0634671
* Version Independent ID: cd351e6c-68d0-58ec-e97a-c7ed64365902
* Content: [What is Common Data Service? - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-intro.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-intro.md)
* Service: **powerapps**
* GitHub Login: @clwesene
* Microsoft Alias: **matp**

**Comment by chucheliu** [comment]
No, you cannot integrate your on-premise application with the Common Data Service, and you can also find the official document to support this as below:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/overview

**Comment by iangpgh** [comment]
@Mattp123 - Closes #829

**Comment by iangpgh** [comment]
@Jayesh040 Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.  
Closing this issue.
