### ISSUE TITLE
Broken link: "From a SharePoint list"

### ISSUE THREAD

**Issue by ianbruckner** [MicrosoftDocs/powerapps-docs#83]
Broken link: "From a SharePoint list"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd466cfc-002f-eba5-da1a-a82ddad5fea5
* Version Independent ID: 5313c975-6848-3d03-9a18-a5ed0cb07149
* Content: [Overview of creating apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/index)
* Content Source: [powerapps-docs/maker/index.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/index.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Thanks, @ianbruckner! That link is fixed.
