### ISSUE TITLE
Powerapps : Launch not working for Bots for Microsoft Teams Mobile App

### ISSUE THREAD

**Issue by satyansh-sagar** [MicrosoftDocs/powerapps-docs#830]
Hi All,
I am creating a button in canvas app of PowerApps and using Launch function to open MS teams app with direct link to user and then with a bot.

For users i'm using : Launch("https://teams.microsoft.com/l/chat/0/0?users=username@tenantname.onmicrosoft.com")

Above function is working fine and I am directly being redirected to teams app on the chat page for that user.
How to do the same thing for a chat bot?
@msdmaguire  @msebolt  Please help.

**Comment by satyansh-sagar** [comment]
For Bots I used below:

Launch("https://teams.microsoft.com/dl/launcher/launcher.html?url=%2f_%23%2fl%2fchat%2f0%2f0%3fusers%3d28%3BOTID&type=chat&deeplinkId=SOMEID&directDl=true&msLaunch=true&suppressPrompt=false")

Above link is working for bots where we need to pass the bot ID, but the problem now is from powerapps its being redirected to mobile browser first then a pop-up is prompting to open MS Teams Apps. 
But the requirement is to move seamlessly to MS Teams from Powerapps.

**Comment by satyansh-sagar** [comment]
Can someone help me resolving this issue? 
@srivatsn @davide-rota  @duncan  @dlapiduz  @lancedMicrosoft  @msft-jinayoon @MSFTMan

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This probably needs review of authentication flow as documented in [Teams documentation](https://docs.microsoft.com/microsoftteams/platform/bots/how-to/authentication/auth-flow-bot). Launch function works as expected and [documented](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-param). You may also consider Power Virtual Agent [integration](https://docs.microsoft.com/power-virtual-agents/publication-connect-bot-to-web-channels#custom-website) with Power Apps portals. Canvas app also allows [embedding app inside Teams](https://docs.microsoft.com/powerapps/maker/canvas-apps/embed-teams-app) if that helps. If this does not help, please reach out to via a [support service request](https://powerapps.microsoft.com/support/pro/) for further help.
