### ISSUE TITLE
How to Open Power Apps Portals admin center?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/powerapps-docs#831]
I searched and reached this page to know how to login in to Power Apps Portal Admin. Any content or link to that page at the beginning of the doc would be useful.

thanks in advance.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c33206-a8f7-cce4-d663-894874c0ae98
* Version Independent ID: 72de507b-3eec-6433-1c0a-462b98ef1a91
* Content: [Overview of Power Apps Portals admin center - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/admin-overview#feedback)
* Content Source: [powerapps-docs/maker/portals/admin/admin-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/admin-overview.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by MoranBarzilay** [comment]
https://admin.powerapps.com/environments

**Comment by KumarVivek** [comment]
@tapanm-MSFT Can you please take care of this?

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The [overview page](https://docs.microsoft.com/powerapps/maker/portals/overview) is updated with relevant links.
