### ISSUE TITLE
What happens after I click the button "Confirm" button?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/powerapps-docs#832]
Our system admin got terrified about additional billing, after clicking the confirm button, and got message "This Portal is currently being configured and updates are not allowed. Please try again later." He doesn't have any permission to increase the expense for D365. He was hoping to get navigated some approval dialog or license requirement to finally approve the Convert this Trail Power Portal to Production Power Portal.

We searched and reach this page after the incident, here too it stops at the last confirm dialog box. Clarify here about the billing, will it be automatically added or included.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7444d166-6678-7ecc-2c33-4c54d4d67ac3
* Version Independent ID: a815c5f8-3ab4-d30a-5098-0d865947bdbb
* Content: [About Power Apps portals lifecycle - PowerApps](https://docs.microsoft.com/en-gb/powerapps/maker/portals/admin/portal-lifecycle)
* Content Source: [powerapps-docs/maker/portals/admin/portal-lifecycle.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/portal-lifecycle.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. Please read the [Power Apps portals licensing FAQ](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#portals) for licensing information.
