### ISSUE TITLE
openWebresource is not working

### ISSUE THREAD

**Issue by GauravKatariya** [MicrosoftDocs/powerapps-docs#835]
Hi,
I am trying to use openWebResource as suggested in the below link to open a webresource 
`https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openwebresource`

But, the following code is not working for me. It is always opening a webresource in a new window but, I want it to open in the same window.
```
var windowOptions = { openInNewWindow: false, height: 400, width: 400 }
Xrm.Navigation.openWebResource("new_webResource.htm",windowOptions);
```

**Comment by Nkrb** [comment]
@GauravKatariya `openInNewWindow` is not a supported parameter - it always opens web resouce  in a new window. Use the new  [XrmNavigation.navigateTo](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto) API to open the HTML web resource inline. Closing the issue.
