### ISSUE TITLE
Sample Components needs uses-feature section for manifest

### ISSUE THREAD

**Issue by ryanspain** [MicrosoftDocs/powerapps-docs#836]
The downloadable sample for this example is missing the below in the manifest XML. Docs static code snippet has been corrected as per issue #541 by kenakamu, but this is not reflected in the ZIP linked in the related topics section of this page (https://go.microsoft.com/fwlink/?linkid=2088525)

&lt;feature-usage&gt;
	&lt;uses-feature name="Device.pickFile" required="true" /&gt;
&lt;/feature-usage&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27dc0672-cb23-c1c6-9501-b1ad78a6390d
* Version Independent ID: 0a3d4a2c-33fa-4098-bd49-50456b00bcce
* Content: [Image Upload component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/image-upload-control#feedback)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/image-upload-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/image-upload-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@ryanspain Thanks for the feedback. We are now uploading the sample components [here](https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework). The download zip may not be up to date. Closing the issue.
