### ISSUE TITLE
Example appears to have logical error

### ISSUE THREAD

**Issue by HilaryStoupa** [MicrosoftDocs/powerapps-docs#837]
Formula:
UpdateIf( IceCream, Quantity &gt; 175, { Quantity: Quantity + 10 } )	

Description:
Modifies records that have a Quantity that is greater than 150. The Quantity field is incremented by 10, and no other fields are modified.

The formula says "Quantity &gt; 175" but the description says that the formula will modify records with a Quantity &gt; 150.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e8711d7-85d7-6d03-6c0c-a27b9b1f4540
* Version Independent ID: 0aa23b15-71a9-9fd4-77a9-cafc41f8c69a
* Content: [Update and UpdateIf functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-update-updateif)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-update-updateif.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-update-updateif.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by rishi1212** [comment]
yes i noticed that too

**Comment by gregli-msft** [comment]
Thanks for the bug report!  The article has been fixed.
