### ISSUE TITLE
Can't find Developer Resources

### ISSUE THREAD

**Issue by xygon** [MicrosoftDocs/powerapps-docs#839]
Following the instructions to `get the url value` I go to https://make.powerapps.com/, appropriate environment and then select *Settings* button - there is no *Advanced Customizations* option. How so I get to the *Developer Resources*?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3da25ded-6c89-69ba-7351-0f04f1c07f79
* Version Independent ID: 6923f7c2-0856-f91f-b17e-e1bef131c5f3
* Content: [Quick Start: Web API sample (C#) (Common Data Service) - PowerApps](https://docs.microsoft.com/en-gb/powerapps/developer/common-data-service/webapi/quick-start-console-app-csharp)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/quick-start-console-app-csharp.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/quick-start-console-app-csharp.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment]
@xygon Can you please try out these instructions and see if you can find the `Instance Web API` URL ?

1. You should be able to see **Advanced settings** option in one of the apps pages.

![1](https://user-images.githubusercontent.com/28051062/70225184-931cba00-1774-11ea-8470-c93f41c4e8c5.png)

2. Select **Customizations** as shown below.

![2](https://user-images.githubusercontent.com/28051062/70225386-f1499d00-1774-11ea-8e23-3a992bf8ef58.png)

3. Here you will see the **Developer resources** option.

![3](https://user-images.githubusercontent.com/28051062/70225448-12aa8900-1775-11ea-8153-9a64ce4de068.PNG)

Click on it to find your `Instance Web API` URL.

Please let me know if these instructions do not work for you.

**Comment by xygon** [comment]
I found it that way – thanks.

Will

**Comment by susikka** [comment]
Closing this issue now.
