### ISSUE TITLE
How to replace Dynamics 365 with our brand logo in Model Driven Apps?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/powerapps-docs#84]
I cloned the themes in Settings&gt; Customizations &gt; Themes and the logo filed could not be edited. Is there any issues related to the role, because, I am a global admin or am I looking at wrong place to change the logo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa788547-0b4a-7c36-8035-95a0c0386927
* Version Independent ID: bd9e046d-a255-c965-6356-84508141ff61
* Content: [Understand model-driven app components in PowerApps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/model-driven-app-components)
* Content Source: [powerapps-docs/maker/model-driven-apps/model-driven-app-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/model-driven-app-components.md)
* Service: **crm-online**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
Thanks for your feedback. Your request is for product-related feedback. I contacted the program manager for the feature and she has indicated that this is a known issue that has been fixed and should be deployed to Dynamics 365 for Customer Engagement instances soon. If this continues to be an issue you can submit your feedback here: https://experience.dynamics.com/ideas/. 
Closing this issue.
