### ISSUE TITLE
JSON needed instead of XML

### ISSUE THREAD

**Issue by axtain** [MicrosoftDocs/powerapps-docs#842]
In Dynamics 365 v9.1, create and update requests are sent as JSON objects. It would be better to provide a method to get the JSON object instead of XML

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb6e91f-c124-de50-e61d-277ef168ba5b
* Version Independent ID: 7715b9f3-3655-5e45-b7cb-c86695e0babd
* Content: [getDataXml (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-entity/getdataxml#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/getDataXml.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-entity/getDataXml.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@axtain Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue.
