### ISSUE TITLE
errorCallback function not called when lookup is cancelled

### ISSUE THREAD

**Issue by Tim-Townsend** [MicrosoftDocs/powerapps-docs#843]
Per the description, the errorCallback function is not being called when the lookup is cancelled in UCI. It still falls into the successCallback the object array being passed as undefined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by polshgiant** [comment]
This feels like the appropriate behavior.  Guessing it is by design.

**Comment by Tim-Townsend** [comment]
> This feels like the appropriate behavior. Guessing it is by design.

I agree, seems the documentation just needs updating.

**Comment by WayneM-dev** [comment]
If this is by design then pressing either button results in a successCallback so how would you determine which button was pressed?

**Comment by manuelwaldner** [comment]
I need to determine if pressing cancel or the add button. I want to clear the lookup if `Add` is pressed but no record is selected.
As it is now, you cannot do that, as cancel results in an empty array and add also...

**Comment by KumarVivek** [comment]
@JimDaly Can you pls review and update the doc if required. Thanks.

**Comment by JimDaly** [comment]
@Tim-Townsend 
This issue has been open for a long time. I note that there have been a number of issues raised for the documentation of this control over the years. I'm reaching out to the dev team to review all of them.
