### ISSUE TITLE
Promise Support?

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#844]
Please indicate whether or not myFunction can return a promise that will be respected by the calling function.

Presumably, one purpose of a Pre-change event is to be able to prevent the stage change from occurring. And in fact, setting Prevent Default in the Event Args of the Execution Context passed in does prevent the stage change. However, if determining whether or not the stage change should be allowed requires calls to Xrm.WebApi, then a promise is needed to delay the save from occurring while async calls are being made.

This documentation makes no mention of whether or not Promises are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d250b4c-307e-a982-91d8-fb24a87f4cc5
* Version Independent ID: 3d0b43af-f41f-ad13-1a12-88a0693fe9f7
* Content: [addOnPreStageChange (Client API reference) in model-driven apps in Power Apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/eventhandlers/addonprestagechange)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/eventhandlers/addOnPreStageChange.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/eventhandlers/addOnPreStageChange.md)
* Service: **crm-online**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KumarVivek** [comment]
@JimDaly Can you pls look at this.
