### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by ZaarourOmar** [MicrosoftDocs/powerapps-docs#845]
In number 5 you say "Perform an operation in Azure that would cause the plug-in or workflow containing the custom workflow activity to execute. " , do we perform the operation in Azure or CDS? Because the whole point of this is to post the event data in CDS to an Azure event hub.

In Number 6, you say "check the related system job in the Azure web application", do we do that in CDS or Azure? To my understanding, this needs to be done in CDS and not in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e0454f-eecc-73f6-6ff2-3af1c8b27976
* Version Independent ID: d0fe6532-f23f-f7cd-3653-cc58b36b1251
* Content: [Work with Dynamics 365 event data in your Azure Event Hub solution (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/work-event-data-azure-event-hub-solution#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/work-event-data-azure-event-hub-solution.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/work-event-data-azure-event-hub-solution.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Looks like this got transformed during the migration from the CE content.
This was the original: https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/work-event-data-azure-event-hub-solution and it has "Customer Engagement' rather than 'Azure'.

Needs to be fixed.

**Comment by JimDaly** [comment]
Fixed. pushed to master should be live in  an hour or so.
