### ISSUE TITLE
Powerbi Embedded RLS

### ISSUE THREAD

**Issue by ctevrizci** [MicrosoftDocs/powerapps-docs#846]
Could you shed some light on passing username parameter when using powerbiembedded on Dynamics 365 CE Portals? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b917299d-2bb0-bbe2-b052-490877a59309
* Version Independent ID: 22d617bd-974d-09f7-4a0f-baca751dcd24
* Content: [Use Power Apps Common Data Service entity tags for a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/portals-entity-tags#powerbi)
* Content Source: [powerapps-docs/maker/portals/liquid/portals-entity-tags.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/liquid/portals-entity-tags.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Unfortunately, username and password for authentication type *powerbiembedded* is not supported. You can also reach out to [Power Apps Ideas](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas) and submit this idea for future consideration that others can vote for.
