### ISSUE TITLE
Multiple orders on link-entity

### ISSUE THREAD

**Issue by MarkMpn** [MicrosoftDocs/powerapps-docs#847]
This schema shows that a `<link-entity>` element can have only one `<order>` applied to it, but in practise any number of orders can be applied.

I believe the line:

```xml
<xs:element name="order" type="FetchOrderType" minOccurs="0" maxOccurs="1" />
```

should be updated to:

```xml
<xs:element name="order" type="FetchOrderType" minOccurs="0" maxOccurs="unbounded" />
```

both in the documentation and in the schemas zip file linked to from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dedee74-443a-b719-11f5-1280f47b942b
* Version Independent ID: c0d5e4ac-31e0-957b-6d3a-35506425072a
* Content: [FetchXML schema (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/fetchxml-schema#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/fetchxml-schema.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/fetchxml-schema.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by mayadumesh** [comment]
Yes, please change per above discovery.

thanks
Maya

**Comment by phecke** [comment]
@MarkMpn I can only publish the schema that I am given by the product team. I checked a newer version of the schema, and it is the same as the published version.
