### ISSUE TITLE
Updated list

### ISSUE THREAD

**Issue by thomassandsor** [MicrosoftDocs/powerapps-docs#849]
When can we expect an update of the restricted entities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted entities requiring Dynamics 365 licenses - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by iangpgh** [comment]
@thomassandsor Article is recently updated with the list of restricted entities. 

[Restricted entities requiring Dynamics 365 licenses](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)

**Comment by iangpgh** [comment]
@thomassandsor Correction: the list of restricted entities was not updated in this article. We are working on updating these soon.

**Comment by tapanm-MSFT** [comment]
Hello, thank you for reaching out. Since this issue has been open for long, and the topic has been updated several times, closing this issue for now. If your ask isn't addressed, please feel free to reach out by opening a new documentation issue.
