### ISSUE TITLE
The Data Table control doesn't expose its items as an output property

### ISSUE THREAD

**Issue by naphiri** [MicrosoftDocs/powerapps-docs#85]
If you want to use the Table data with something like LookUP or CountIF or any, Table will not work. You will get an "invalid argument type" error, you must create a collection if you want to get the output data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e90f79-1bc4-c93f-921f-d5cbae4de28b
* Version Independent ID: 2a9ddf0f-7676-190b-768d-f553f8e7b61c
* Content: [Table function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-table)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-table.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by AFTOwen** [comment]
Hi, @naphiri! Thanks for your feedback; this appears to be a report about the product, not the documentation. Therefore, I'm closing this issue, but please feel free to raise your concern [here](https://powerusers.microsoft.com/t5/PowerApps-Ideas/idb-p/PowerAppsIdeas). Cheers!
