### ISSUE TITLE
Poor Communication

### ISSUE THREAD

**Issue by DerekHAu** [MicrosoftDocs/powerapps-docs#852]
Could this also say when the notifications are coming out? The only reason we even know this is happening is a tweet from @jukkan, and most of our clients are in February or March, not October, giving us at most 3 months, especially with Australian Christmas Holidays & New Year knocking out about a month in most businesses... The communication direct from Microsoft to customers and partners about this has been non-existent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6baca2c-2716-dab9-da1f-9290d5c94d5f
* Version Independent ID: 081682e5-b125-22fc-04c9-1e784ea306f5
* Content: [FAQs: Unified Interface transition - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/faqs-transition-unified-interface#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/faqs-transition-unified-interface.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/faqs-transition-unified-interface.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **haybass**

**Comment by KumarVivek** [comment]
@DerekHAu Thank you for your comments; we have adjusted the FAQ to include the communication timeframe. Following a series of briefing sessions with MVPs, selected partners and customers we now have posted a live blog communication with the finalized transition details available here:  https://powerapps.microsoft.com/en-us/blog/moving-forward-with-your-transition-to-unified-interface/. 

Hopefully, this should address your concerns on the timeframe for your clients as the suggested dates will only be transitioned prior to October 1, 2020 if an admin explicitly approves the date. Customers can reschedule or manually make the switch right up to October 1st 2020 but we hope that customers see the benefits of the Unified Interface and make the move as soon as they are able.

Closing the issue.
