### ISSUE TITLE
Liquid tag to display "Export To Excel" OOB button in Custm page Template

### ISSUE THREAD

**Issue by devtestworkp** [MicrosoftDocs/powerapps-docs#853]
There OOB option for Entity List to export data by adding OOB button "Export To Excel". But for same reason I have to use custom "Web Template", for custom web template. Even this functionalty is enable this button is not getting displayed.

Note : We user provided Liquid template design in doc to create new Entity List form, we did not find any tag in Liquid, which can add this button on Entity List.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340faef4-cbf8-d938-8a10-230149b8a591
* Version Independent ID: 88a56df4-b670-4954-832b-955ae94a6501
* Content: [Use Liquid objects for a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/liquid-objects#feedback)
* Content Source: [powerapps-docs/maker/portals/liquid/liquid-objects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/liquid/liquid-objects.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. There is no liquid tag to display 'Export to Excel'. If you have a specific business requirement for this ask, please add a feature request to the [Power Apps community idea forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
