### ISSUE TITLE
Incomplete Content

### ISSUE THREAD

**Issue by eliasm3075** [MicrosoftDocs/powerapps-docs#854]
Missing content where there is "[Learn how to add and configure a control].(../add-configure-controls.md)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c68b4c33-12f9-3b26-5508-7173fe207ada
* Version Independent ID: 0451a3c0-7d56-63b3-e8ff-acc33d6c5daf
* Content: [Attachments control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-attachments#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-attachments.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-attachments.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by chmoncay** [comment]
I just updated the document, it should be fixed soon.  In the mean time, here is the link if you need it : [https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-configure-controls](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-configure-controls)
