### ISSUE TITLE
Do not translate features

### ISSUE THREAD

**Issue by github129** [MicrosoftDocs/powerapps-docs#855]
en-us
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-text
![image](https://user-images.githubusercontent.com/25972825/70581567-e79fb980-1bfa-11ea-98b1-81582be5bddc.png)

ja-jp
https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/function-text
![image](https://user-images.githubusercontent.com/25972825/70581598-03a35b00-1bfb-11ea-97c8-b8e2360fbe8c.png)

Do not translate features and results.
Check the red line.

`
テキスト ( 1234567.89 ) → Text( 1234567.89 )
`
`
本来 → "true"
`

**Comment by KumarVivek** [comment]
@github129 Thanks for providing the feedback; I have passed this on to my localization team for a fix.

Closing the issue.

**Comment by Alisha-Acharya** [comment]
@DavidPrio Can you please take a look at it
