### ISSUE TITLE
All Control Type Supported

### ISSUE THREAD

**Issue by AbdulWahabWarind** [MicrosoftDocs/powerapps-docs#856]
You write it here that all controla types are supported nut in my case all controls are not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393f8dbe-1366-98ab-7acd-80bc431530fc
* Version Independent ID: 9e84bf7c-465c-c233-6fd7-acf6ae972458
* Content: [setFocus (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setfocus#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setFocus.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setFocus.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@AbdulWahabWarind Can you please let us know which type of controls are not working for you. For now component framework controls will not be supported.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by AbdulWahabWarind** [comment]
Why you need to early response? I forgot what was the issue because of the late response from your side. Give me a week so that I am able to remember it again.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
