### ISSUE TITLE
Is WebAPI supported in offline mode?

### ISSUE THREAD

**Issue by pablolaurin** [MicrosoftDocs/powerapps-docs#857]
Is it supported in offline mode like Xrm.WebApi.offline?

More info:
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/offline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647866b2-563e-ffdd-ce84-f20feb839ca8
* Version Independent ID: 2397c27b-056e-de5b-0195-defdeff90718
* Content: [WebAPI - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/webapi#feedback)
* Content Source: [powerapps-docs/developer/component-framework/reference/webapi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/webapi.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@pablolaurin Yes, the Power Apps component framework Web API method supports the offline mode to the same extent that XRM does.

**Comment by pablolaurin** [comment]
Thanks Nkrb!

**Comment by mmcguinness** [comment]
Can you elaborate on how?  When I call retrieveMultipleRecords in a PCF in D365 for phones while offline, I get "UciError: This operation failed because you're offline. Reconnect and try again."

**Comment by Suxsem** [comment]
It may be related to #1885
