### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gsimardnet** [MicrosoftDocs/powerapps-docs#858]
The following two links are broken. Please update them to their new address.
- Build a multi-tenant SaaS web application using Azure AD & OpenID Connect
- Build a multi-tenant SaaS web application that calls a web API using Azure AD

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb3f9201-d1a8-3fc8-f327-6ab2cb51b8c7
* Version Independent ID: 197edb93-bf8f-c2ff-1635-90c38ca84d07
* Content: [Use Multi-Tenant Server-to-server authentication (Common Data Service) - PowerApps](https://docs.microsoft.com/en-ca/powerapps/developer/common-data-service/use-multi-tenant-server-server-authentication#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/use-multi-tenant-server-server-authentication.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-multi-tenant-server-server-authentication.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by carltoncolter** [comment]
Te url for the multi-tenant sample on github is: https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-multitenant-openidconnect

**Comment by sing-ideas** [comment]
When both the URLs will be updated?
