### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by Illeris** [MicrosoftDocs/powerapps-docs#859]
Link under 'Sample: Set and retrieve entity images File attributes' is dead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce5339c-4c9c-dd5f-9e9f-749c07bb084a
* Version Independent ID: 260d4b6d-b764-272a-8af9-7e5d2dada0f0
* Content: [Image attributes (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/image-attributes)
* Content Source: [powerapps-docs/developer/common-data-service/image-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/image-attributes.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by mayadumesh** [comment]
I think you meant the Sample: Set and retrieve entity images link.  Please assign to @Nathan Helgren for Image sample.

**Comment by KumarVivek** [comment]
@phecke Can you please take care of this issue.

**Comment by phecke** [comment]
Fixed, change is live.

**Comment by phecke** [comment]
@Illeris Thanks for pointing it out.
