### ISSUE TITLE
US API IPv4 address missing?

### ISSUE THREAD

**Issue by ParaGlideRocks-zz** [MicrosoftDocs/powerapps-docs#860]
Hi Team,
it looks like we are missing the following IP address.

------------
Nome:    prod-parpfe-eastus.cloudapp.net
Address:  13.68.137.177
Aliases:  unitedstates.api.powerapps.com
          powerappsfe-prod-unitedstates.trafficmanager.net

Could you check, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdf0872-929b-e44a-dedd-eb6a759915f2
* Version Independent ID: 0b65b025-62f8-fc2a-0026-3cb96b7b4554
* Content: [System requirements, limits, and configuration values for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config)
* Content Source: [powerapps-docs/maker/canvas-apps/limits-and-config.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/limits-and-config.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by DTronD** [comment]
The lack of full documentation and FQDN's for PApps service endpoints is putting our PApps deployment to our userbase at serious risk.  E.g. #1006

**Comment by tapanm-MSFT** [comment]
Please refer to the updated documentation with the recent changes.
