### ISSUE TITLE
Map the Parent name of the Primary entity when creating a new record

### ISSUE THREAD

**Issue by vernetmatias** [MicrosoftDocs/powerapps-docs#861]
Hello, when I create a new Record using Power APP property OpenQuickCreateForm (ModelDrivenFormIntegration.OpenQuickCreateForm) the lookup field form the parent entity it's not being mapped on the related entity record. But when I use the Quick Create Form native form with the related Sub-grid on the form the parent lookup its being mapped correctly.

new record using powerapps (ModelDrivenFormIntegration.OpenQuickCreateForm)
![powerAppsQuickCreate](https://user-images.githubusercontent.com/36961292/70722639-64ec2c80-1cd6-11ea-9649-b41f7c95e12e.png)

new record using sub-grid working fine:
![image](https://user-images.githubusercontent.com/36961292/70722774-a2e95080-1cd6-11ea-9897-30ccf2241073.png)

**Comment by iangpgh** [comment]
@vernetmatias Have you contacted Support regarding this issue you're experiencing? Did you receive a response to your report, or is the issue otherwise resolved? To contact Support: https://powerapps.microsoft.com/support/

**Comment by iangpgh** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue. 

@Mattp123 - Closes #861
