### ISSUE TITLE
The link to webapi FileAttributeMetadata is broken. 

### ISSUE THREAD

**Issue by ChrisGrohHS** [MicrosoftDocs/powerapps-docs#863]
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/fileattributemetadata gives a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c3eac9-b083-b974-0938-3e8fd19bbb58
* Version Independent ID: 2c6dfac6-25b8-876c-2b94-fa9d466007df
* Content: [File attributes (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/file-attributes)
* Content Source: [powerapps-docs/developer/common-data-service/file-attributes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/file-attributes.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment]
The link is correct but the content is not yet available. The Web API documentation must be re-generated for the new entitytypes (including FileAttributeMetadata) to show up in the Web API reference. This is planned to happen soon.

**Comment by phecke** [comment]
The link has been removed until the Web API reference documentation is updated. At that time, the link should be re-instated.

**Comment by phecke** [comment]
@ChrisGrohHS Fixed.
