### ISSUE TITLE
Service protection limits in plugins

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerapps-docs#864]
The "Note" there might be confusing. There might be technical nuances of how telemetry works, but sure you know which user account is associated with a plugin/workflow run? At least that information is readily available to the plugin developers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b61960df-dcdc-d4e5-749b-0f55e22a385d
* Version Independent ID: baddf389-6252-fe30-1a60-48c18f256ed8
* Content: [API limits overview (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/api-limits-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/api-limits-overview.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by iangpgh** [comment]
Thanks for your feedback. I will pass this feedback along to the feature PM. For product-related feedback, visit https://ideas.powerapps.com.  
Closing this issue.

**Comment by iangpgh** [comment]
@Mattp123 - Closes #864

**Comment by JimDaly** [comment]
@ashlega 
Sorry for the delay to respond. Yes, the note may be challenging for people without knowledge of plug-ins or custom workflow activities to understand this, but the note isn't for them. It is for people who do know and will ask the question. And since service protection limits don't apply, what difference does it make which user account is running the plug-in?

Are you asking about entitlement limits?

**Comment by ashlega** [comment]
It's just that this: "Since plug-ins and custom workflow activities execute on the server independent of a logged on user"

goes against my understanding of the plugins. 

Why do you need to explain/justify the statement that API limits don't apply to the calls from the plugins with a confusing reason? All those calls from the plugins are still happening in the context of some user account, but, if the framework is not ready/does not find it necessary to track such calls against API limits... that still does not mean the calls are made independent of the user account (otherwise, the next question we'll be getting from the picky clients when they read this is "and what about security and audit logs? Which user account is showing up there for the update made from the plugin and if that's even correct?")

**Comment by JimDaly** [comment]
@ashlega 

We don't want this to be confusing. :-)

Let me make sure I understand you.
The issue you are raising is about this:

> _Since plug-ins and custom workflow activities execute on the server independent of a logged on user_, service protection API limits are not applied against API calls made from plug-in code.

You don't like the text _Since plug-ins and custom workflow activities execute on the server independent of a logged on user_.
You are saying that perhaps we should just simply say:

> Service protection API limits are not applied against API calls made from code in plug-in and custom workflow activities.

Is that it?

**Comment by ashlega** [comment]
Sounds good to me :)

**Comment by JimDaly** [comment]
I fixed this a while back and just saw this is still open. Closing
