### ISSUE TITLE
Delegation

### ISSUE THREAD

**Issue by hpkeong** [MicrosoftDocs/powerapps-docs#865]
This is the best formula for data analysis so far. But due to delegation it becomes useless. Please kindly resolve this issue at least for CDS and SPL. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736d5662-8c1a-7654-a624-7b3d3cfc60cc
* Version Independent ID: ea32ff2a-f54c-3d37-dbef-c32bd449d704
* Content: [GroupBy and Ungroup functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-groupby)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-groupby.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-groupby.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
GroupBy and Ungroup are powerful functions, but they were designed to be used only on in-memory tables and not delegated.  No database system I am aware of, including SQL server, does grouping in the way these functions do.  

A better answer would be to offer a grouping argument to the aggregate functions such as Sum, Average, and CountRows.  For this I have added an [idea to the Power Apps community idea forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Group-by-for-Sum-Average-CountRows-and-other-aggregate-functions/idi-p/463850#M29501).  If that would fill your needs, please vote for that idea, or offer a different idea that would fit your scenario.
