### ISSUE TITLE
Error "no data available" when opening webresource with data parameters.

### ISSUE THREAD

**Issue by Paca** [MicrosoftDocs/powerapps-docs#867]
Hello,

I am facing in 4 instances DEV, TEST, PREPROD and PROD! :/
This error: "no data available" when opening webresource with data parameters.
I didn't find a real sure step to reproduce always the issues.

here the code i used:

```javascript
var _openWebResource = function (idOpportunity, idAccount, nameAccount) {
    var windowOptions = { openInNewWindow: true, height: 500, width: 500 }
    var data = encodeURIComponent("OpportunityId=" + idOpportunity + "&AccountId=" + idAccount + "&AccountName=" + nameAccount);
    Xrm.Navigation.openWebResource("pw_CopyOpportunity.html", windowOptions, data);
};
```
I open it from a ribbon button like this:

```javascript
var runCopyRibbon = function (selectedItems) {
        if (selectedItems !== null && selectedItems.length == 1) {
            var selectedItem = selectedItems[0];
            var parentXrm = _getXrm();        
            if (parentXrm != null) {
                parentXrm.WebApi.online.retrieveRecord("opportunity", selectedItem, "?$select=name&$expand=parentaccountid($select=accountid,name)").then(
                    function success(result) {
                        var lkAccount = result.parentaccountid;
                        if (lkAccount !== null) {
                            _openWebResource(selectedItem, lkAccount.accountid, lkAccount.name);
                        }
                        else
                        {
                            _openWebResource(selectedItem, "", "");
                        }
                    },
                    function (error) {
                        console.log(error.message);
                        parentXrm.Utility.alertDialog(error.message);
                    }
                );
               
            }
        }
        
    };
```
Any help will be appreciated :)

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef001b56-f366-7866-693b-c403f84dbab3
* Version Independent ID: e3d1fbdc-84a5-ce3c-af1e-11e98b14418f
* Content: [openWebResource (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openwebresource)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Paca** [comment]
Hi all,

Any one else are facing this problems ? If no answer end of week I must open a ms support request. I really don't understand why sometimes it works and sometimes not....

Best regards,
Nicolas.

**Comment by mtnmuncher** [comment]
Yes, exact same issue. Here is what my HTML web resource looks like.
In my case, the call to 
var Parameters = GetGlobalContext().getQueryStringParameters();
returns an empty object.

<html>
<head>
    <title> </title>
    <meta charset="utf-8">
    <script type="text/javascript" src="ClientGlobalContext.js.aspx "></script>
    <script type="text/javascript">
        var CRMCustomParameters = [];
        var getParameters = function () {
            debugger;
        try {
            var Parameters = GetGlobalContext().getQueryStringParameters();
            console.log('parms ' + GetGlobalContext().getQueryStringParameters());
            console.log('(Parameters && Parameters.Data)' + (Parameters && Parameters.Data));
            if (Parameters && Parameters.Data) {
                console.log('Parameters.Data' + Parameters.Data);
                
                //                location.href = Parameters.Data;
                alert('hello world');
            }
        } catch(e) {
            console.log('error ' + e);
        }
    }
    </script>
    <meta>
</head>
<body onload="getParameters()">
</body>
</html>

Here is where call is made from ribbon.
function programClicked(commandProperties)
{
    console.log(" id " + commandProperties.SourceControlId + " selected.");    
    Xrm.WebApi.retrieveRecord("custom_entity", commandProperties.SourceControlId, "?$select=custom_field1").then(
        function success(result) {
            console.log("Retrieved values: Url: " + result.custom_field1);
            var customParameters = encodeURIComponent(result.custom_field1);
            Xrm.Navigation.openWebResource("new_webcontainer.html", null, customParameters);
        },
        function (error) {
            console.log(error.message);
            // handle error conditions
        });
}

According to this blog, https://exptechsolutions.blogspot.com/2017/06/know-howmscrm-open-external-url-using.html, see last comment (04/2019) "This does not work in UCI". So, this issue may not be new.
Cheers,
Mark

**Comment by Paca** [comment]
Any new from Microsoft team will be appreciate. We had lot of users still complaining about that bug, and the more strange is that if you try several time to refresh you can get the web resource loading properly but it's random ....

@KumarVivek your help will be appreciate ;)

Regards,

**Comment by Nkrb** [comment]
@Paca @mtnmuncher Thanks for contacting us. Can you confirm if you still see the issue.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by jalley3** [comment]
Still having this issue for our team. Sometimes it renders the form, sometimes it says "no data available" with 0 difference in the process involved in opening the web resource
