### ISSUE TITLE
Script code missed in Image.

### ISSUE THREAD

**Issue by ShinjiFunabiki** [MicrosoftDocs/powerapps-docs#871]
https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/entity-lists#add-custom-javascript
Script code missed in Image.

![image](https://user-images.githubusercontent.com/41189220/70885546-802fa280-201c-11ea-92b8-fccb7e118895.png)

") }"  They are opposite.
}) is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eb3ed13-9665-518f-7cc5-eec5e279708f
* Version Independent ID: 8a7aefa4-b9e0-ef52-7832-83c23cc790b1
* Content: [Add a webpage to render a list of records on a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/entity-lists#feedback)
* Content Source: [powerapps-docs/maker/portals/configure/entity-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/entity-lists.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The image script code is fixed. Please allow some time for the updated image to be available.
