### ISSUE TITLE
ja-jpのページにて、製品名が機械翻訳されてしまっています。

### ISSUE THREAD

**Issue by MakotoMaeda-ZEE** [MicrosoftDocs/powerapps-docs#872]
小見出しの修正をお願いします。

アプリメーカー/作成者向けのパワーアプリ
→アプリメーカー/作成者向けのPower Apps

アプリユーザー向けのパワーアプリ
→アプリユーザー向けのPower Apps

管理者向けのパワーアプリ
→管理者向けのPower Apps

開発者向けのパワーアプリ
→開発者向けのPower Apps

パワーアプリを無料で試す
→Power Apps を無料で試す

電力アプリを購入する
→Power Apps を購入する

といった内容が正しいと思われます。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a87d70-1f25-0a75-bc11-f2c079f2083c
* Version Independent ID: 7b1e729a-d4b6-2786-2ac7-c9e1c516a815
* Content: [What is Power Apps? - PowerApps](https://docs.microsoft.com/en-us/powerapps/powerapps-overview)
* Content Source: [powerapps-docs/powerapps-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/powerapps-overview.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@MakotoMaeda-ZEE Can you please create an issue in the English language. The documentation team does not have the ability to read messages in the localized languages.
