### ISSUE TITLE
ja-jpページにて、「祭」が表示されている

### ISSUE THREAD

**Issue by MakotoMaeda-ZEE** [MicrosoftDocs/powerapps-docs#873]
Jの項目が何故か「祭」になっています。
修正をお願いします。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59975a54-2a0b-0148-0fd1-a4ffd51c8d5a
* Version Independent ID: d3faf9fc-d312-db0b-1369-d72c3bd47fd3
* Content: [Functions, signals, and enumerations - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/formula-reference#j)
* Content Source: [powerapps-docs/maker/canvas-apps/formula-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/formula-reference.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by KumarVivek** [comment]
@MakotoMaeda-ZEE  Can you please create an issue in the English language. The documentation team does not have the ability to read messages in the localized languages.
