### ISSUE TITLE
ja-jpページにて、数式（Formula）まで翻訳されてしまっている

### ISSUE THREAD

**Issue by MakotoMaeda-ZEE** [MicrosoftDocs/powerapps-docs#874]
数式（Formula）まで日本語翻訳されてしまっています。
修正をお願いします。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3666a6f7-9f0b-a723-9b74-949b3b8623e7
* Version Independent ID: f3969083-de51-f0fd-a67e-b60f25b29c94
* Content: [And, Or, and Not functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-logicals#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-logicals.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-logicals.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by KumarVivek** [comment]
@MakotoMaeda-ZEE Can you please create an issue in the English language. The documentation team does not have the ability to read messages in the localized languages.
