### ISSUE TITLE
Mobile app support

### ISSUE THREAD

**Issue by KimBon** [MicrosoftDocs/powerapps-docs#875]
This method seems to return null when using the mobile app for Windows 10. Is this expected behavior? If so, docs should reflect this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdf2dc1e-072c-c9b6-6683-752a51e5f3fb
* Version Independent ID: 2ccbc4d8-5d4e-bf93-c6a4-5f32e52ef4ec
* Content: [getCurrentAppUrl (Client API reference) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/getcurrentappurl)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/getCurrentAppUrl.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/getCurrentAppUrl.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@KimBon Thanks for the feedback. Yes this is the expected behavior in mobile client, we will update the docs and publish it live. Closing the issue.
