### ISSUE TITLE
Cannot set callback Result

### ISSUE THREAD

**Issue by abdelaziz-benelfakir** [MicrosoftDocs/powerapps-docs#876]
I open an html Webresoource using ` Xrm.Navigation.navigateTo(pageInput, navigationOptions).then(Callback,Error)` .Before the new UCI I used this to Set the callback result : 
` Mscrm.Utilities.setReturnValue(result);`

Now this is not working anymore, what's the alternative ?

**Comment by KumarVivek** [comment]
@abdelaziz-benelfakir Thanks for contacting us. Unfortunately, we're unable to handle support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.
 
Closing this issue.
