### ISSUE TITLE
Defining namespace differs from tutorial page

### ISSUE THREAD

**Issue by rappen** [MicrosoftDocs/powerapps-docs#877]
The method on this page for defining namespace and implementation of it differs between this page and the tutorial found here: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script

It would be nice if they aligned with each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe35465-7772-fa9a-d673-c23fc76b4c97
* Version Independent ID: b971957c-5466-bc1f-9671-735532a5ee57
* Content: [Best practices: Client scripting in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/client-scripting-best-practices)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/client-scripting-best-practices.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/client-scripting-best-practices.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by roryd** [comment]
Totally agree with the OP. This version of how to do it in Javascript is older than the one in the tutorial.

**Comment by Nkrb** [comment]
Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Comment by rappen** [comment]
@Nkrb could you point me to the updated info?
Neither of the pages I reference seem to have been updated since 2018-10-31.
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/client-scripting-best-practices
