### ISSUE TITLE
GCC Tenants Missing

### ISSUE THREAD

**Issue by packman83** [MicrosoftDocs/powerapps-docs#879]
The documentation and communications do not mention how GCC tenants are being handled. The transition portal only lists our commercial tenant, not any of our GCC tenants. Is there a separate portal or do we not get any visibility into the transition timing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6baca2c-2716-dab9-da1f-9290d5c94d5f
* Version Independent ID: 081682e5-b125-22fc-04c9-1e784ea306f5
* Content: [FAQs: Transition to Unified Interface - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/faqs-transition-unified-interface#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/faqs-transition-unified-interface.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/faqs-transition-unified-interface.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **haybass**

**Comment by KumarVivek** [comment]
@packman83 Thanks for your feedback; we have updated the FAQ to add this info:

**Are environments from all data centers included within this transition service?**

At present, environments from specific data centers, such as Government Community Cloud (GCC), have not been included within the portal. We'll provide suggested transition dates for these environments by June, 2020. Customers who want to make the move to Unified Interface can always switch manually at any time before October 1, 2020.
