### ISSUE TITLE
Elaboration [Timer control]

### ISSUE THREAD

**Issue by hpkeong** [MicrosoftDocs/powerapps-docs#88]
Detail example and one of the best in the documentation so far. Will be good to guide newbies how to use this to make a clock. It is simple but one might not aware of using OnTimerEnd to make clock, my suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11a9f1d-da5c-f25b-2b48-eddc4c4a6cc5
* Version Independent ID: 1c0f1c98-8bf0-320d-74e8-434e816a4222
* Content: [Timer control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-timer)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-timer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-timer.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by AFTOwen** [comment]
Thanks, @hpkeong! Anyone can find information about how to make a clock in [this forum post] (https://powerusers.microsoft.com/t5/General-Discussion/How-to-create-a-clock-in-Powerapps/td-p/76671).
