### ISSUE TITLE
This updates all the controls

### ISSUE THREAD

**Issue by fhburney** [MicrosoftDocs/powerapps-docs#884]
Can you please update the documentation. If you have an attribute, with multiple controls, if you removeOption on a single control, it removes from all the controls of that attribute. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2fd88e-934d-9bfc-9888-9d15b97e8e4d
* Version Independent ID: 5a98fca8-60c7-ccc1-6edc-2ef16d2ebf8c
* Content: [addOption (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addoption#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOption.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addOption.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@fhburney Thanks for contacting us. Can you confirm if you're still facing the issue.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
