### ISSUE TITLE
"Power Apps Included w/ Office" ?

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerapps-docs#889]
What does "Power Apps Included w/ Office" actually mean? Please list the Office product SKUs that provide this license.  

Also as the section "What license must be assigned to my guest ..." is actually not specific to guests at all, it would be better moved up and to it's own major section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60fb8dba-da1c-6845-d301-c3b18a6b98ef
* Version Independent ID: a5d1fd66-fe5b-f52d-47de-6af3c71928f7
* Content: [Share a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/share-app?irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=(ir__ap6s1bkjigkftl9rkk0sohzw0e2xgaum3dqzlks200)(7593)(1243925)(je6NUbpObpQ-IQvznF2VrTqtqG.Fpugo2w)()&irclickid=_ap6s1bkjigkftl9rkk0sohzw0e2xgaum3dqzlks200#share-with-guests)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Looking into it.

**Comment by tapanm-MSFT** [comment]
The doc is updated with additional reference below the table that lists details regarding SKU details as well as all other licensing related information. The section is an answer as part of FAQ explaining difference between guest and non-guest users for licensing requirements as listed, hence part of the FAQ. 

Thank you again for your feedback. Closing this issue.

**Comment by eschrader** [comment]
Thanks, sounds like Power Apps Included w/ Office covers guest users.
