### ISSUE TITLE
More info on viewing issues with "Multiple Forms"

### ISSUE THREAD

**Issue by adamajm** [MicrosoftDocs/powerapps-docs#890]
This is my first time customizing a form and I want a separate form for Editing a list item and creating a new item. However, the UI seems to call up both forms despite having set up the Sharepoint Integration setting to call a different form for New and Edit modes......Not sure how to troubleshoot this although it seems like something simple...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2000b4-4917-deb6-148f-98c97691f4fb
* Version Independent ID: 241ca44d-5ed2-335a-ae0e-78c3d90b27e2
* Content: [Understand SharePoint forms integration - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-form-integration)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-form-integration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sharepoint-form-integration.md)
* Service: **powerapps**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Hello, please reach out to support team for additional troubleshooting of the issue with a [support ticket](https://powerapps.microsoft.com/support/pro/).
