### ISSUE TITLE
Reference for DatePicker / "Date Picker" control missing info on DateTimeZone property

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/powerapps-docs#891]
I don't see any mention of the DatePicker's DateTimeZone property on this page of the docs:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-date-picker 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4fb137e-6a79-e538-a90a-0d17c5cfb8f7
* Version Independent ID: 3d725d06-378d-4540-4fc4-6959d00eaf9e
* Content: [Date Picker control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-date-picker)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-date-picker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-date-picker.md)
* Service: **powerapps**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by tapanm-MSFT** [comment]
Hello, it's listed in additional properties list between 'Color' and 'DisplayMode':

**DateTimeZone – Whether to display the date in UTC or the user's Local time.**
