### ISSUE TITLE
Information on BPF Cient API Reference outdated?

### ISSUE THREAD

**Issue by alvarezskinner** [MicrosoftDocs/powerapps-docs#892]
Hi,

I'm using this method and I'm seeing different strings being passed to the callback function that are not documented, is there any chance we can get this updated?

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef925b43-e949-4239-9ae8-caeee63499d8
* Version Independent ID: 24be0bd5-4b43-b439-32df-22a3cf32c24e
* Content: [moveNext (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/navigation/movenext#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/navigation/moveNext.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/navigation/moveNext.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by mannybellas** [comment]
Yes, one of those strings is stageGate

**Comment by Nkrb** [comment]
@alvarezskinner 
Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
