### ISSUE TITLE
Dialog expand issues

### ISSUE THREAD

**Issue by Jdawg20** [MicrosoftDocs/powerapps-docs#893]
When you select the expand button the iframe size stays the same size even though the wrapper of the iframe grows to use the whole page.  This doesn't allow the webresource to occupy the additional space and is completely wasted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Thanks for your feedback. For product-related feedback, visit <https://ideas.powerapps.com>.  

Closing this issue.
