### ISSUE TITLE
Multiples

### ISSUE THREAD

**Issue by MrKirtley** [MicrosoftDocs/powerapps-docs#894]
How does the find function respond if a string contains multiple substrings, does it take the first result?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 280f200b-30e6-5e03-ab16-bc695acce5cd
* Version Independent ID: dff474b4-29da-9cde-b57d-7cd55e53ba4f
* Content: [Find function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-find#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-find.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-find.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Hello, when there are multiple occurrences found, the starting position of first occurrence is returned. 

Consider following examples for a quick demo with an app having Label1 and Label2:

If:

Label1.Text: "Lorem ipsum dolor sit amet"
Label2.Text: If(Find("amet",Label1.Text)>0,"Found","Not found")

Conclusion: Label2.Text = "Found"

If:

Label1.Text: "Lorem ipsum dolor sit amet"
Label2.Text: If(Find("elit",Label1.Text)>0,"Found","Not found")

Conclusion: Label2.Text = "Not found"

If:

Label1.Text: "Lorem ipsum dolor sit amet"
Label2.Text: Find("amet",Label1.Text)

Conclusion: Label2.Text = 23

If:

Label1.Text: "Lorem ipsum dolor sit amet"
Label2.Text: Find("ipsum",Label1.Text)

Conclusion: Label2.Text = 7

If:

Label1.Text: "Lorem ipsum dolor sit amet"
Label2.Text: Find("elit",Label1.Text)

Conclusion: Label2.Text = 
I.e. Label2.Text is blank. No value returned.

Repeat all above tests with Label1.Text as:
"Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet"

Result: Same as above tests.
