### ISSUE TITLE
Specify viewIds requirements.

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#895]
In the classic UI, viewIds accepts an Array of Strings, but the id strings must be in the format "{0D5D377B-5E7C-47B5-BAB1-A5CB8B4AC105}". Lowercase letters or omitting the curly braces will cause the lookup dialog to not display that view.

In the UCI, it's even worse, the lookup dialog seems to ignore all viewIds specified in an Array of Strings, regardless of the format (uppercase, lowercase, with curly braces, without curly braces).

Please specify the correct format of ids or the structure of objects that need to be passed into viewIds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@devlinl I tried defining like this and worked for me on UCI 
viewIds:["65FFAF9A-E8C5-432D-860B-32F841B00D87","00000000-0000-0000-00AA-000010001001"]

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
