### ISSUE TITLE
On the ja-jp page, the function has been translated and it is quite difficult to read

### ISSUE THREAD

**Issue by MakotoMaeda-ZEE** [MicrosoftDocs/powerapps-docs#896]
The function has been translated and it is quite difficult to read.
Please fix it because it is very useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe9fac7-f56e-31c7-ef09-bc0baa5570ea
* Version Independent ID: 2025e0c3-918e-612a-3138-ae5617adb809
* Content: [Blank, Coalesce, IsBlank, and IsEmpty functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-isblank-isempty)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-isblank-isempty.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-isblank-isempty.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by KumarVivek** [comment]
@MakotoMaeda-ZEE I have passed this feedback to the LOC team. Closing this issue.

**Comment by Alisha-Acharya** [comment]
@DavidPrio Can you please take a look at it.
