### ISSUE TITLE
Small typo in the sample HTML code

### ISSUE THREAD

**Issue by 0x4kgi** [MicrosoftDocs/powerapps-docs#897]
Currently the HTML code is:

```html
<p>We have [ ... ] localization.<p>
```

Notice the ending `p` tag is opened twice and the second tag should be closed. Like so:

```html
<p>We have [ ... ] localization.</p>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130e07ac-d3c6-9d10-bd7c-bb1f8c4ff2ab
* Version Independent ID: b25a9a60-1319-1e05-8c53-ca135523b6ca
* Content: [EncodeUrl and PlainText functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-encode-decode#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-encode-decode.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-encode-decode.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the bug report!  It has been fixed.
