### ISSUE TITLE
Doesn't work when component is inside Gallery control

### ISSUE THREAD

**Issue by tchagan** [MicrosoftDocs/powerapps-docs#898]
Hi, doesn't appear to work when the component is embedded in a Gallery control. Using a button to trigger a Reset using the Reset function raises an error that the control does not exist.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb241fc7-9d0b-29d9-532a-ab6d6929f457
* Version Independent ID: abdb307e-e024-17fc-7b1b-5479139fcfc5
* Content: [Behavior formulas for components - PowerApps](https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/component-behavior?source=docs#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/component-behavior.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/component-behavior.md)
* Service: **powerapps**
* GitHub Login: @yifwang
* Microsoft Alias: **yifwang**

**Comment by yifwang** [comment]
Hi @tchagan , embedding a component inside a gallery is not fully supported and we are working to enable this scenario.  Thanks for the feedback. Embedding is a popular and useful scenario and it's one of our top priority to enable.
