### ISSUE TITLE
Portal Admin URL is missing 

### ISSUE THREAD

**Issue by johnmsaxton** [MicrosoftDocs/powerapps-docs#899]
It would helpful if the URL for the Portal Admin Portal was somewhere on this page. There are more than a few admin pages for Power Platform (which is another problem) so it would be helpful to direct user to the correct admin page for portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c33206-a8f7-cce4-d663-894874c0ae98
* Version Independent ID: 72de507b-3eec-6433-1c0a-462b98ef1a91
* Content: [Overview of Power Apps Portals admin center - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/admin-overview#feedback)
* Content Source: [powerapps-docs/maker/portals/admin/admin-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/admin-overview.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Portal links for administration are different with each portal. Hence, we recommend to use the documented steps. Please use make.powerapps.com or the [Power Platform admin center](https://docs.microsoft.com/power-platform/admin/admin-guide).

**Comment by KittyDreadful** [comment]
You should just put make.powerapps.com in the instructions then.
