### ISSUE TITLE
Missing info about appropriate licensing

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/powerapps-docs#900]
The Power Apps Admin Portal links to this page when an admin clicks Confirm to convert --&gt; if licensing is not correct it notifies "You can’t convert your trial portal to production as you don’t have an appropriate license.". On this page should be a link to the licensing info page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7444d166-6678-7ecc-2c33-4c54d4d67ac3
* Version Independent ID: a815c5f8-3ab4-d30a-5098-0d865947bdbb
* Content: [About Power Apps portals lifecycle - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/portal-lifecycle#feedback)
* Content Source: [powerapps-docs/maker/portals/admin/portal-lifecycle.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/portal-lifecycle.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out and your feedback. This feedback is being considered for future updates.
