### ISSUE TITLE
Missing verb?

### ISSUE THREAD

**Issue by PathToSharePoint** [MicrosoftDocs/powerapps-docs#901]
The following sentence is not clear:
You use the ThisItem operator to specify the column of data that each card or control within the outer control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3b10c1-cea3-aeef-133c-4973fe1fd8de
* Version Independent ID: f42816ff-c29b-d046-5cc7-4a541ec3e117
* Content: [Operators - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/operators#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/operators.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/operators.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the bug report!  The offending line has been reworded: Use the ThisItem operator to specify the column of data to be displayed in each card or control within the outer control.
