### ISSUE TITLE
Language code not supported "HE" for Hebrew

### ISSUE THREAD

**Issue by yarix** [MicrosoftDocs/powerapps-docs#902]
the IETF BCP-47 language tag supports "he" and "iw" for Hebrew. however, power apps raise an error saying: "Language code not supported"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ac8a6c-92a3-d450-106b-d5626cfe5a04
* Version Independent ID: 912a7b8e-32f9-b380-5596-47afe4dde554
* Content: [Language function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-language#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-language.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-language.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by yarix** [comment]
for example: `Text(DateAdd( ThisItem.StartTime, -TimeZoneOffset(ThisItem.StartTime), Minutes ), "[$-he]HH:mm")`

**Comment by gregli-msft** [comment]
Unfortunately we do not support right-to-left languages in canvas apps today, such as Hebrew. There is a feature idea tracking it in the [Power Apps community idea forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/RTL-Support/idi-p/412402).
