### ISSUE TITLE
Items formula is not working

### ISSUE THREAD

**Issue by aakashjaiswal47** [MicrosoftDocs/powerapps-docs#903]
I followed the exact same steps as mentioned in the tutorial but unfortunately after I copy paste this formula First(Filter(FlooringEstimates, Name=ChooseProduct.Selected.Value)) in the items property, it is showing 2 errors

Name isn't valid. The identifier isn't recognized. ( ....Selected.value)

Invalid argument type. (...=...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462f00a6-6f9a-8c56-4725-d0ce504c0d24
* Version Independent ID: 06203633-aa23-b7eb-0093-cf50ea49b617
* Content: [Show, edit, or add a record in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/add-form#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/add-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/add-form.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by stokes776** [comment]
I get the same error 'Name isn't valid' This causes the guide to break down pretty early on.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please use *ChooseProduct.Selected* instead. Will update documentation.
