### ISSUE TITLE
setIsValid is undefined (v9.0.9.4, on-premise)

### ISSUE THREAD

**Issue by zhaparoff** [MicrosoftDocs/powerapps-docs#907]
There is no such method for on-premise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75c3ab6-9669-f00c-e1a0-187886a74497
* Version Independent ID: 925c9e10-8206-caf8-9713-37cace17fa12
* Content: [setIsValid (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/setisvalid#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/setIsValid.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/setIsValid.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@zhaparoff Thanks for the feedbacl .Please update the instance to the latest version and see if you can find the method.

**Comment by zhaparoff** [comment]
@Nkrb, the problem is that I cannot update the instance.
Although I can instal the update to environment, I cannot update the organization with the latest version - update fails with error related to some OOTB ribbon customizations on Opportunity entity.
So 9.0.9.4 is the latest that I can use for now.

**Comment by Nkrb** [comment]
@zhaparoff Looks like you have trouble with updating the organization. Please raise a support issue. To contact Support, consider one of the options described here: https://docs.microsoft.com/dynamics365/get-started/support/
