### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by bguidinger** [MicrosoftDocs/powerapps-docs#908]
The NuGet package link goes to the "Microsoft.CrmSdk.XrmTooling.PackageDeployment" NuGet package instead of the "Microsoft.CrmSdk.XrmTooling.PackageDeployment.WPF" package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b0e3a7-a385-942e-1261-53d1aeac1673
* Version Independent ID: 95ad8dd4-3458-8fb2-9e1f-8780fea5853a
* Content: [Create packages for the Package Deployer (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/package-deployer/create-packages-package-deployer)
* Content Source: [powerapps-docs/developer/common-data-service/package-deployer/create-packages-package-deployer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/package-deployer/create-packages-package-deployer.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@bguidinger That page is being updated in a few days. We are no longer pointing people to the NuGet packages for tools. Rather, the Power Platform CLI tool will be used to install the tools going forward and for creating packages.
