### ISSUE TITLE
pcf-scripts is not recognized as an internal or external command

### ISSUE THREAD

**Issue by dkrishnap** [MicrosoftDocs/powerapps-docs#909]
Hello ,

Trying to build new pcf control and getting below error on build and test . Please suggest how to fix.
i have installed node.js 12.6.0
![Capture](https://user-images.githubusercontent.com/20661289/71459152-19547b00-27cc-11ea-9dbb-624cd5b9edc7.PNG)

**Comment by Nkrb** [comment]
@dkrishnap Thanks for the feedback. Please follow the instructions mentioned [here](https://github.com/MicrosoftDocs/powerapps-docs/issues/756#issuecomment-571334776) and let us know if that workaround has helped.

**Comment by Nkrb** [comment]
Closing the issue.
