### ISSUE TITLE
Could support for these offline features be further clarified in this document?

### ISSUE THREAD

**Issue by ShawnPOWER** [MicrosoftDocs/powerapps-docs#910]
For example, is the Windows 10 Power Apps app supported fully when offline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ea2a5e-9757-462d-dff8-d2764bd34dcc
* Version Independent ID: d7bd25f9-7acb-12b2-0134-81ccfc7b4c3a
* Content: [Develop offline-capable canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/offline-apps#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/offline-apps.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/offline-apps.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. As the article explains, you can use offline capability for Power Apps mobile app. However, there are [limitations](https://docs.microsoft.com/powerapps/maker/canvas-apps/offline-apps#limitations) as described in the limitations section. Please review storage and merge conflict related limitations mentioned while using offline capability.
