### ISSUE TITLE
Sections collection isn't accessed as shown.

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#911]
In the above "Collections in the formContext object model" table, the final entry is formContext.ui.tabs.sections. This makes it appear that a developer can reach a collection of all sections on a form by accessing formContext.ui.tabs.sections. However, this is not the case. formContext.ui.tabs is a generic Collection just like any of the other collections (attributes, controls, etc) and does not itself contain a collection called "sections".

It should be noted that a developer must either provide the tab which contains the desired section (formContext.ui.tabs.get("tabName").sections.get("sectionName")), or iterate through each tab in order to find the relevant section (formContext.ui.tabs.forEach(function (t){t.sections.get("sectionName")})).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27005d75-5062-c4cf-bfa8-bee6f0aeb28c
* Version Independent ID: a3ce8627-2cf4-9eb6-8e36-f304c012b05c
* Content: [Client API form context in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/clientapi-form-context)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/clientapi-form-context.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/clientapi-form-context.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@devlinl Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.  If you need further help, please reopen the issue or open a new issue.
