### ISSUE TITLE
The link to the complete sample is broken

### ISSUE THREAD

**Issue by pablolaurin** [MicrosoftDocs/powerapps-docs#912]
This page https://code.msdn.microsoft.com/Custom-Workflow-Activities-eee57285
doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f8c953-e241-4365-cf8c-c3ca2f2e0136
* Version Independent ID: 00d03966-ebbe-9a48-c5fd-15759ecf586e
* Content: [Sample: Create a custom workflow activity (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/workflow/sample-create-custom-workflow-activity)
* Content Source: [powerapps-docs/developer/common-data-service/workflow/sample-create-custom-workflow-activity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/workflow/sample-create-custom-workflow-activity.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@pablolaurin  Sorry about the broken link. We are in transition of moving samples to a new GitHub repo. The link is fixed now, and the sample has been updated to use our newer helper code. Enjoy!
