### ISSUE TITLE
Xrm.Navigation.openAlertDialog display issues (popup)

### ISSUE THREAD

**Issue by sowka1995** [MicrosoftDocs/powerapps-docs#913]
When working with a **CRM 365 v9 Online with Unified Interface**, we often need to display various types of information to users. Information is sometimes short and sometimes longer (3-4 lines). 
We use the **Xrm.Navigation.openAlertDialog** method for this and we noticed various kinds of problems displaying the popup.

1. If we do not pass the width and height parameters to the method, a horizontal scrollbar appears
`Xrm.Navigation.openAlertDialog({ text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.' });`
![image](https://user-images.githubusercontent.com/18213521/71599471-51044f80-2b4b-11ea-988d-d21445f2c7c4.png)
even if I pass a specific width the horizontal scrollbar does not disappear.
`Xrm.Navigation.openAlertDialog({ text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.' }, { width: 600 });`
![image](https://user-images.githubusercontent.com/18213521/71599689-32528880-2b4c-11ea-84fb-448e4d1451e6.png)

2. If the text is longer, an additional vertical scrollbar appears
![image](https://user-images.githubusercontent.com/18213521/71599533-7d1fd080-2b4b-11ea-939d-cdd7e246c402.png)
if I set height parameter to 'auto' (I know this is incompatible with the documentation) vertical scrollbar disappears, but for the horizontal scrollbar this hack doesn't work.
`Xrm.Navigation.openAlertDialog({ text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book" }, { height: 'auto' })`
![image](https://user-images.githubusercontent.com/18213521/71600053-ae010500-2b4d-11ea-872c-ddac86930d97.png)

**Comment by Nkrb** [comment]
@sowka1995 I tried steps to reproduce the issue, but i dont see any scroll bar when i use the navigation method.
![image](https://user-images.githubusercontent.com/34038327/75279188-03f5d000-57c0-11ea-899a-3e5cd53a65de.png)

Here is the code i have used to check the functionality 
```JavaScript
var alertStrings = { confirmButtonLabel: "Yes", text: "This is an alert.", title: "Sample title" };
var alertOptions = { height: 120, width: 260 };
Xrm.Navigation.openAlertDialog(alertStrings, alertOptions).then(
    function success(result) {
        console.log("Alert dialog closed");
    },
    function (error) {
        console.log(error.message);
    }
);
```

**Comment by Nkrb** [comment]
@sowka1995 If i increase the height and width of the window, i don't see any scroll bars. 
![image](https://user-images.githubusercontent.com/34038327/75279743-fbea6000-57c0-11ea-93a3-23d2b718c9dc.png)

**Comment by Nkrb** [comment]
@sowka1995 
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
