### ISSUE TITLE
Create a dataflow, Step 4: There is no "Select load target" page, probably renamed into New Dataflow

### ISSUE THREAD

**Issue by AndreiPanko** [MicrosoftDocs/powerapps-docs#914]
Article: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-and-use-dataflows#create-a-dataflow

As is:
4. On the Select load target page, select the destination storage where you want entities to be stored. Dataflows can store entities in Common Data Service or in your organization's Azure Data Lake storage account. Once you select a destination to load data to, enter a Name for the dataflow, and then select Create.

Suggestion:
4. On the New Dataflow page enter a Name for the dataflow. By default dataflows store entities in Common Data Service. Select **Analytical entries only** if you want entities to be stored in your organization's Azure Data Lake storage account. Select Create.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3abf73d-60b9-675f-61e7-1c2dc622d055
* Version Independent ID: 352c1196-0631-9f40-e382-bba13d5e27e9
* Content: [Create and use dataflows in Power Apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-and-use-dataflows#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/create-and-use-dataflows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-and-use-dataflows.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@AndreiPanko - thank you for your feedback. The article has been updated per your suggestion and to reflect the current feature UI. Closing issue.
