### ISSUE TITLE
This does not close the window when form opened via Xrm.Navigation.openForm

### ISSUE THREAD

**Issue by Tim-Townsend** [MicrosoftDocs/powerapps-docs#916]
Title, this does not close the window. The window acts as if a save action occurred. 
The console output states "Offset supplied makes index less than zero."

Code to open a form where Save & Close does not close the window:

```
                var entityFormOptions = {};
                entityFormOptions["entityName"] = "crm_entitylogicalname";
                entityFormOptions["formId"] = "5C50977D-9654-4DBF-A3B7-3E2F523142FA";
                entityFormOptions["openInNewWindow"] = true;
                entityFormOptions["navbar"] = "off";
                entityFormOptions["cmdbar"] = true;
                entityFormOptions["createFromEntity"] = formContext.data.entity.getEntityReference()

                var formParameters = {};

                // Open the form.
                Xrm.Navigation.openForm(entityFormOptions, formParameters).then(

                function (success)
                {
                    console.log(success);
                },

                function (error)
                {
                    console.log(error);
                });
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b662c9e4-9905-b2bb-96eb-55093a371f80
* Version Independent ID: 1569aa19-e370-40af-6238-469ab1a988a8
* Content: [close (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui/close)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui/close.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui/close.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@Tim-Townsend Can you confirm if you still see this issue?

**Comment by Tim-Townsend** [comment]
@Nkrb Issue no longer occurs, thank you.
