### ISSUE TITLE
PowerApps Studio Deprecation

### ISSUE THREAD

**Issue by HoloBeard** [MicrosoftDocs/powerapps-docs#917]
I think the mention of PowerApps Studio needs to be removed or at least acknowledged that it has be deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047b94ce-db9f-ad01-5a62-b0539f2433cc
* Version Independent ID: 1a8a9d3c-2d8b-e13c-042b-0a48fc444956
* Content: [Guidelines on working with embedded canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-guidelines#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Since this issue has been open for long, closing it for now as the article has been updated several times . If your ask isn't addressed, please feel free to report a new documentation issue for the given article.
