### ISSUE TITLE
Integrated Security Parameter missing from Listing of Parameters

### ISSUE THREAD

**Issue by TclasenITVT** [MicrosoftDocs/powerapps-docs#918]
Hi D365 Docs Team,

in the 'OAuth using current logged in user with fall back UX to prompt for authentication' Chapter inside the Example Connectionstring is a 'Integrated Security=true;' This is not described on this page. My guess is that this is one of the additional parameters from the 'Azure Active Directory Conditional Access and Multi-Factor authentication' - Features that are supported. Could you include a Link in this page that leads one to the proper page describing the function of this parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8213b8-93bc-dee0-5b82-973db16f03fa
* Version Independent ID: 161512ac-81c1-4163-20e1-e440497d2e24
* Content: [Use connection strings in XRM tooling to connect to Common Data Service (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect)
* Content Source: [powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@TclasenITVT Thanks for the feedback. Please read the topic [here](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-string-syntax#windows-authentication). we will be updating the docs accordingly.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by TclasenITVT** [comment]
As you haven't updated the article I would like to have you link the PR or Issue where this improvement is tracked?

**Comment by Nkrb** [comment]
@TclasenITVT Sorry for the confusion. The updated docs are pushed out and will be live after 5 PM PST today. Please check back tomorrow and see if you can find the information.
