### ISSUE TITLE
New licensing option vs. Dynamics 365 Team Member

### ISSUE THREAD

**Issue by vitlachner** [MicrosoftDocs/powerapps-docs#919]
Hi, 
in documentation and Power Apps licensing guide is still missing information about "Entities with complex business logic" vs Dynamics 365 Team Member license. My question is about using plugins with Dynamics 365 Team Member license - execute. I know that for development we need Enterprise licese. 
In Power Apps licensing guide is section "Power Apps use rights with Dynamics 365 applications" where Team Member is in column (1) "Dynamics 365 Applications". There is information about "(Classic CDS) Non real-time and real-time workflows" that allows use Real-time/Non real-time workflows, but no information about plugins. Could you refine if plugins are allowed to be used with Dynamics 365 Team Member license?

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87257a9a-36dd-e791-8240-c52f35e9f44d
* Version Independent ID: fee3775a-17ff-2d33-dd05-ba385360515d
* Content: [Complex entities requiring Power Apps Plan 2 licenses - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-complex-entities#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-complex-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-complex-entities.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by vitlachner** [comment]
Hello, do you have any update for my question?

**Comment by KendalBond007** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com. Closing this issue
