### ISSUE TITLE
AssignedTo

### ISSUE THREAD

**Issue by ahillr14** [MicrosoftDocs/powerapps-docs#92]
I love this app and have been able to adjust it to my needs with some other columns.  However, I'm struggling with the AssignedTo column.  I need it to be able to be assigned to only 2 people, but I can't figure out how/where to set up that group that would only include my maintenance personnel.  Can you help me with that?

**Comment by AFTOwen** [comment]
@ahillr14 Hi! Is this feedback about a sample app (perhaps Helpdesk)?
