### ISSUE TITLE
Value( "24e3" )'s description is wrong

### ISSUE THREAD

**Issue by 0x4kgi** [MicrosoftDocs/powerapps-docs#921]
>Scientific notation for **12** x 10<sup>3</sup>.

Should be:

>Scientific notation for **24** x 10<sup>3</sup>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c65abb-171c-138b-5b4b-94fe7060d89d
* Version Independent ID: 11829360-5040-f615-fa07-87d16f6dbcd3
* Content: [Value function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-value)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-value.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-value.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the bug report!  It has been fixed.
