### ISSUE TITLE
Question: Do invitations automatically expire at some point if I don´t explicitly specify an expiry date?

### ISSUE THREAD

**Issue by latsyn** [MicrosoftDocs/powerapps-docs#922]
Do invitations automatically expire at some point if I don´t explicitly specify an expiry date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97927ddf-353e-98e9-8e30-f1f2267c6f0b
* Version Independent ID: d728ae3e-9b17-8254-3e72-4cda2a006c1d
* Content: [Invite contacts to your portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/invite-contacts)
* Content Source: [powerapps-docs/maker/portals/configure/invite-contacts.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/invite-contacts.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Hi @latsyn, no; they don't.
