### ISSUE TITLE
IfError and Remove() not working for SharePoint Lookup columns where restrict delete is turned on

### ISSUE THREAD

**Issue by zshane15** [MicrosoftDocs/powerapps-docs#923]
I have a SharePoint lists (List A) that is being used as a Lookup column in List B. I have turned on the feature to "Enforce relationship behavior > Restrict delete" in the lookup column. 

In PowerApps I have a gallery which is connected to List A. Then I have populated a few list items in List B, setting the lookup column to various values.

When I try to use `IfError()` and `Remove()` to remove a list item in List A that is being used in List B nothing happens:

`IfError(
    Remove(
        'List A',
        {ID: ThisItem.ID}
    ),
    Notify("Sorry that item is being used in List B!")
)`

There is no error that appears, no message and the item remains in the list and gallery. For other items which are not being used in List B, they are removed as normal.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. It appears that the issue needs investigation as an incident. Please reach out to via a [support service request](https://powerapps.microsoft.com/support/pro/) for further help.
