### ISSUE TITLE
Broken on Bulk Edit forms. 

### ISSUE THREAD

**Issue by Tim-Townsend** [MicrosoftDocs/powerapps-docs#925]
formContext.ui.tabs.get(arg) does not work on bulk edit forms, but Xrm.Page.ui.tabs.get(arg) does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f809d12-c4b6-ffb1-998d-1e09963e8acd
* Version Independent ID: b7c89fde-afe9-6858-93f7-6a72f3ba4cd9
* Content: [formContext.ui.tabs (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-tabs)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-tabs.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-tabs.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@Tim-Townsend Can you confirm if this still happening. It should work as described in the doc.
