### ISSUE TITLE
Using `@` symbol not allowed in collections?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#926]
Hello,
I'm unable to use the `@` symbol when creating a collection. Is there a way to escape this character?

**Example of error:**

```
ClearCollect(colJSON,
    {
        @context: "https://schema.org"
    }
)
```

**Whereas this works fine:**

```
ClearCollect(colJSON,
    {
        context: "https://schema.org"
    }
)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c8e63a-856f-c7f7-9553-d2564c1e25e4
* Version Independent ID: 29037222-286c-8fc0-79e5-4bb599ad7c70
* Content: [Collect, Clear, and ClearCollect functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-clear-collect-clearcollect#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-clear-collect-clearcollect.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Special characters, such as @, can be used in the names of columns if enclosed in single quotes.  I've added [a new section to the docs](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/operators#identifier-names) to explain this more fully.

**Comment by SeaDude** [comment]
Thanks for the clarification @gregli-msft !
