### ISSUE TITLE
'setDisabled' is not available for web resource control type, although documentation says that it should be.

### ISSUE THREAD

**Issue by zhaparoff** [MicrosoftDocs/powerapps-docs#928]
On-premise, v 9.0.9.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ffa99f-1dd7-d3c7-766c-f388056d83cb
* Version Independent ID: 632db3ab-cb34-7b34-1c6b-01febf9432a1
* Content: [setDisabled (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setdisabled)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setDisabled.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setDisabled.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@zhaparoff Thanks for contacting us. Can you confirm if you are still facing the issue.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
