### ISSUE TITLE
Outdated .NET Core 2.2 SDK?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#929]
The .NET Core 2.2 SDK website (https://dotnet.microsoft.com/download/dotnet-core/2.2) has a warning banner stating: 

"This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as .NET Core 3.1. See our support policy for more details."

Does the link on this page need to be updated or...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49dacb11-ddd9-9d58-333c-b9e7feecf0d3
* Version Independent ID: 32b7cc6e-c726-2212-5e15-a26c321dd86c
* Content: [Get tooling for Power Apps component framework - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/get-powerapps-cli#feedback)
* Content Source: [powerapps-docs/developer/component-framework/get-powerapps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/get-powerapps-cli.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@SeaDude Thanks for the feedback. We have updated the docs and pushed to live. Closing the issue.
