### ISSUE TITLE
Show "my help desk tickets" for particular technician

### ISSUE THREAD

**Issue by tonygpperez** [MicrosoftDocs/powerapps-docs#93]
If I have two technicians working on issues is it possible for each of the technicians to log in and only see the tickets assigned to them? Thanks for a great app!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by AFTOwen** [comment]
Thanks @tonygpperez for the feedback and @cid109 for redirecting!
