### ISSUE TITLE
Only possible if owner of AD - work around

### ISSUE THREAD

**Issue by svdoever** [MicrosoftDocs/powerapps-docs#932]
The solution described in this article seems only to be possible if you are the owner of the AD the PowerApps Portal is connected to. The article https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/admin-overview#add-yourself-as-an-owner-of-the-azure-ad-application describes this. If this is NOT possible in your case, see the article https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/admin-overview#open-power-apps-portals-admin-center how to open the portals admin center, change portal state to off, select update, end then to on again and update. It will take a while, but the portal is reset and the server cache is cleared.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5bd87e4-5fa8-0822-2dd8-989e453f2558
* Version Independent ID: 42963b75-3c09-223c-241d-9bc56154ba47
* Content: [Clear the server-side cache for a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/admin/clear-server-side-cache#feedback)
* Content Source: [powerapps-docs/maker/portals/admin/clear-server-side-cache.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/admin/clear-server-side-cache.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. In order to provide access to a user for clearing cache, please go to contacts, select the required contact. In related records for this contact, go to web roles and ensure contact is associated to 'Administrator' web role for clearing cache. After a few minutes you can clear the cache.
