### ISSUE TITLE
Create a component to be a container for other components

### ISSUE THREAD

**Issue by TheWebartist** [MicrosoftDocs/powerapps-docs#933]
Hi, I wasn't found an information about the capability of a custom component to be a container for others components.

My way is to create a wrapper component and I have the impression that you can't do this with the PowerApps Component Framework. Am I right ?

**Comment by Nkrb** [comment]
Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
