### ISSUE TITLE
Filter Completed

### ISSUE THREAD

**Issue by RKC123** [MicrosoftDocs/powerapps-docs#934]
Really great PowerApp! 
*Question - I've been searching high and low, trying to create a filter to hide completed tickets. Only able to get arranging alphabetically... Any thoughts?

Also would like to add a (time stamped) comments section (But admittedly I haven't really tried just yet)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879fd196-a46f-9f5d-f33b-b5ae9db14b58
* Version Independent ID: 67642cb3-92aa-9340-0dff-3786d0672779
* Content: [Install and configure the Help Desk sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/help-desk-install#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/help-desk-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/help-desk-install.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **mabolan**

**Comment by tapanm-MSFT** [comment]
@RKC123 Thank you for reaching out. For filtering, please consider [filter function](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-filter-lookup). 

Regarding comments section with time stamps, an app with separate data source can be created to attain similar functionality. In case if we have any issues, please contact [support team](https://powerapps.microsoft.com/en-us/support/pro/) for help with resolving environmental issues.
