### ISSUE TITLE
Buttons covered and Horizontal Scroll bar appears on Edge

### ISSUE THREAD

**Issue by kishored4** [MicrosoftDocs/powerapps-docs#935]
Confirm buttons are covered by the horizontal scroll bar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77b84ce4-88fc-464e-4105-5cb9dde039ca
* Version Independent ID: 89d24260-1a80-e032-702e-b5ffa46d76af
* Content: [openConfirmDialog (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openconfirmdialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openConfirmDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openConfirmDialog.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment]
@kishored4 Did you change the height and width options of the dialog and see if you can still see the issue. We don't see any buttons covered with the scrollbar.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
