### ISSUE TITLE
When will this control be available? 

### ISSUE THREAD

**Issue by DS2019** [MicrosoftDocs/powerapps-docs#936]
It shows that it was supposed to go to General Availability Sept 2019 here: https://docs.microsoft.com/en-us/business-applications-release-notes/April19/microsoft-powerapps/planned-features 
Any word?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9192dd77-30e7-4ef4-dbd0-ffcc643747c7
* Version Independent ID: 2d09703c-828f-a8d8-7f3e-4fa9b9f10186
* Content: [Microsoft Stream video control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-stream-video)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-stream-video.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-stream-video.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by tapanm-MSFT** [comment]
If this is for [Microsoft Stream](https://docs.microsoft.com/powerapps/maker/canvas-apps/controls/control-stream-video) control, it's already available.
