### ISSUE TITLE
Too much white-space in the very first $batch "changeset" example of this doc

### ISSUE THREAD

**Issue by aecarr2** [MicrosoftDocs/powerapps-docs#938]
In the first example of this doc, there are two extra spaces of whitespace on every line, in each 'copy-text' box, all the way down to the title 'Reference URIs in an operation'. This seems to be the only example with too much whitespace as the rest of the document looks fine. This seems to have been caused by unnecessary formatting. This is a problem because with this extra whitespace, you are unable to copy the text as-is, replace what is necessary and execute the code as it will result in an error. This is because $batch executions need to be very exact.

If you compare the above text in this doc with my edit down below, you will see there is a difference in whitespace:

POST[Organization URI]/api/data/v9.1/$batch HTTP/1.1
Content-Type: multipart/mixed;boundary=batch_AAA123
Accept: application/json
OData-MaxVersion: 4.0
OData-Version: 4.0

--batch_AAA123
Content-Type: multipart/mixed;boundary=changeset_BBB456

--changeset_BBB456
Content-Type: application/http
Content-Transfer-Encoding:binary
Content-ID: 1

POST[Organization URI]/api/data/v9.1/tasks HTTP/1.1
Content-Type: application/json;type=entry

{"subject":"Task 1 in batch","regardingobjectid_account_task@odata.bind":"[Organization URI]/api/data/v9.1/accounts(00000000-0000-0000-000000000001)"}
--changeset_BBB456
Content-Type: application/http
Content-Transfer-Encoding:binary
Content-ID: 2

POST[Organization URI]/api/data/v9.1/tasks HTTP/1.1
Content-Type: application/json;type=entry

{"subject":"Task 2 in batch","regardingobjectid_account_task@odata.bind":"[Organization URI]/api/data/v9.1/accounts(00000000-0000-0000-000000000001)"}
--changeset_BBB456--

--batch_AAA123
Content-Type: application/http
Content-Transfer-Encoding:binary

GET[Organization URI]/api/data/v9.1/accounts(00000000-0000-0000-000000000001)/Account_Tasks?$select=subject HTTP/1.1
Accept: application/json

--batch_AAA123--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af14071e-83a5-8dde-6346-d158b4d5d66a
* Version Independent ID: 8fb0f4fb-17ff-7491-d057-a1edf9242bc8
* Content: [Execute batch operations using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Thank you for your testing and contribution. 

All the samples here are copied from requests and responses that worked.
The only manual editing was using the `[Organization URI]` placeholder.

But it seems like the additional white space added in the publishing process can break this if people are expecting to just copy and paste it into Postman.

@phecke Can you try and do something with the whitespace issue?

I think we should leave this open until we address that.

**Comment by phecke** [comment]
@aecarr2 @JimDaly Removed all double spaces at the end of code lines.
