### ISSUE TITLE
The Related tab is not shown in the editor

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/powerapps-docs#939]
Dynamic's Contact form, for example, has Summary, Detail, and Conflicts tabs when viewed in the designer.  But when viewed published, it has an additional Related tab with a very long list of related entities.  How can the related tab be modified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca1991d-eb16-375f-173b-bf832dd1d0e6
* Version Independent ID: 4f0e60b5-2861-7701-ed56-6c523696e3ca
* Content: [Add, configure, move, or delete tabs on a form using the form designer - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-move-or-delete-tabs-on-form)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-move-or-delete-tabs-on-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/add-move-or-delete-tabs-on-form.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by iangpgh** [comment]
@dialedin2014 Have you contacted Support regarding this issue you're experiencing? To contact Support: https://powerapps.microsoft.com/support. Let me know if you're not able to resolve this question.

**Comment by iangpgh** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

@Mattp123 - Closes #939
