### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by lfinman** [MicrosoftDocs/powerapps-docs#940]
There is no longer an 'info icon' as shown above.  To find versions, you now have to select [...] for 'More Commands', then 'Details', which brings you to the screen with a [Versions] tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 794c3fe7-3e7f-6ee0-4b17-5d39d73c72e5
* Version Independent ID: f5a1cb86-f877-7049-46a2-86a6000a7e85
* Content: [Restore your canvas app to a previous version - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/restore-an-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/restore-an-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/restore-an-app.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The documentation is being updated with changes.
