### ISSUE TITLE
Help building component

### ISSUE THREAD

**Issue by atfernando** [MicrosoftDocs/powerapps-docs#942]
Thanks for providing the sample code. I've been using PowerApps for about 2 years now but new to pro-code. 
I downloaded the sample component files and PowerApps CLI. Can someone please tell me how to use this sample code and export it as a component? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 981881ff-889a-2b0c-515e-c0e2af8e4357
* Version Independent ID: 9e9eaa4b-0743-eb5c-2e23-2bd437de733c
* Content: [Map component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/map-control#feedback)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/map-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/map-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@atfernando Thanks for the feedback. Please find the instructions [here](https://docs.microsoft.com/powerapps/developer/component-framework/use-sample-components). Closing the issue.

**Comment by atfernando** [comment]
@Nkrb I followed the instructions but the build fails with error - ' The target "CreateManifestResourceNames" does not exist in the project.'
Any thoughts?

**Comment by Nkrb** [comment]
Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
