### ISSUE TITLE
MSBuild Error

### ISSUE THREAD

**Issue by atfernando** [MicrosoftDocs/powerapps-docs#943]
Hi,

I'm getting an error "error MSB4057: The target "CreateManifestResourceNames" does not exist in the project." when I try to run the msbuild command. It would be appreciated if anyone can shed some light.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b01e51-8d80-08b1-2bd5-564c4756ad8a
* Version Independent ID: 750ea5e8-1325-2593-024d-68e926488076
* Content: [How to use the sample components? (Power Apps Component Framework) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/use-sample-components#feedback)
* Content Source: [powerapps-docs/developer/component-framework/use-sample-components.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/use-sample-components.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@atfernando Closing the issue.
