### ISSUE TITLE
Conditional Retrievals while Retrieving Multiple Records

### ISSUE THREAD

**Issue by AshV** [MicrosoftDocs/powerapps-docs#944]
Can Etag be utilized while Retrieving Multiple Records? 
As in that response also Etag value is always included.

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/perform-conditional-operations-using-web-api#conditional-retrievals

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aefa7028-b364-aa1e-a122-361277f4aa91
* Version Independent ID: aca6ac35-ec53-711f-eea0-0d238f1ec645
* Content: [Perform conditional operations using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/perform-conditional-operations-using-web-api##apply-optimistic-concurrency)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/perform-conditional-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/perform-conditional-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
No. Only one ETag can be set in the header. It is for individual retrievals only.
