### ISSUE TITLE
Still waiting for GA with Azure Key Vault integration and Caching

### ISSUE THREAD

**Issue by AgileXRM** [MicrosoftDocs/powerapps-docs#945]
We love this feature but it is still in Preview after 3 months and missing these 2 identified improvements. 
Please push to make it Generally Available.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad70fa7e-a9df-e2c0-4482-a140ca1c4b4f
* Version Independent ID: 8071aca4-f51a-a53e-0e04-c2a64164eb32
* Content: [Preview: Use environment variables in solutions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/environmentvariables#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/EnvironmentVariables.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/EnvironmentVariables.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by caburk** [comment]
Thanks for your feedback. The feature will GA in 2020 Release Wave 1 with several enhancements. However, Key Vault integration and caching have several dependencies are likely further out.

**Comment by iangpgh** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.  
Closing this issue.”

**Comment by iangpgh** [comment]
@Mattp123 - Closes #945
