### ISSUE TITLE
Something missing from this page?

### ISSUE THREAD

**Issue by ghdunn** [MicrosoftDocs/powerapps-docs#946]
This page refers to guidance articles and refers to the standard format of those articles, but I can't seem to find the link to the articles themselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af6c10f2-9207-25f6-1a32-a50c82698c3b
* Version Independent ID: 5a29feb2-950c-f914-cb86-e38a70033b45
* Content: [Developers: Best practices and guidance for model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/best-practices/#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/best-practices/index.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/best-practices/index.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by Nkrb** [comment]
@ghdunn The document is talking about the structure of the article. You can find all the details in the [Apply business logic using client scripting](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/best-practices/business-logic/).

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Comment by denisem-msft** [comment]
The sections structure is misleading. Is there any reason why basic best practices are not provided?

**Comment by Nkrb** [comment]
@denisem-msft We are working on restructuring the TOC. Will update it when done.
