### ISSUE TITLE
Create an AppSource account for testing without MPN ID

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#947]
Is there a way?

[Enter feedback here]
![image](https://user-images.githubusercontent.com/8151045/72359998-4f936500-36bd-11ea-966f-3bf6f4f503b5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b172713b-379d-351c-78ec-386b5a4564fd
* Version Independent ID: 974003c1-0b11-9f1e-916c-1b1b2f86459f
* Content: [Let customers test drive your canvas app on AppSource - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dev-appsource-test-drive)
* Content Source: [powerapps-docs/maker/canvas-apps/dev-appsource-test-drive.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dev-appsource-test-drive.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **litran**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. The content has been updated, please review updated content and reach out for the applicable content if the question still needs an answer. More: [MPN ID](https://docs.microsoft.com/partner-center/mpn-create-a-partner-center-account#view-mpn-account-details)
