### ISSUE TITLE
filtering on emum fields

### ISSUE THREAD

**Issue by jac-rod** [MicrosoftDocs/powerapps-docs#949]
Please add some standard documentation on filtering enum fields.  See link here for additional info: http://dev.goshoom.net/en/2017/04/filter-for-enum-fields-in-odata-service/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
The link you reference is for the AX Operations product. I can't speak to their data model, but Common Data Service (CDS) doesn't have any enums defined in the data model outside of metadata.

We **do** have content related to using enum types when querying metadata. This is the only place it is relevant in CDS.
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-metadata-web-api#use-enum-types-in-filter-operations
