### ISSUE TITLE
The example regular expression has a syntax typo on it

### ISSUE THREAD

**Issue by 0x4kgi** [MicrosoftDocs/powerapps-docs#951]
The regex code in the example does not work:
```powerapps-dot
With( 
    Match( "PT2H1M39S", "PT(?:<hours>\d+)H)?(?:(?<minutes>\d+)M)?(?:(?<seconds>\d+)S)?" ),
    Time( Value( hours ), Value( minutes ), Value( seconds ) )
)
// Result: 2:01 AM (as shown in a label control, use the Text function to see the seconds)
```

Verified within Power Apps:
![image](https://user-images.githubusercontent.com/17591127/72486871-243c8180-3847-11ea-862a-e84f3f05fb36.png)

The parenthesis is mismatched.

Changing `PT(?:<hours>\d+)H)` to `PT(?:(?<hours>\d+)H)` would fix this syntax error.

The final code should look like this:
```powerapps-dot
With( 
    Match( "PT2H1M39S", "PT(?:(?<hours>\d+)H)?(?:(?<minutes>\d+)M)?(?:(?<seconds>\d+)S)?" ),
    Time( Value( hours ), Value( minutes ), Value( seconds ) )
)
// Result: 2:01 AM (as shown in a label control, use the Text function to see the seconds)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfbafa61-3cfe-9895-2d63-26584e60df05
* Version Independent ID: ac3bad74-443d-e429-4925-fe0eb6da8b32
* Content: [With function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-with)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-with.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-with.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the report.  However, the code you suggest is already in the documentation and has been for six months.  Can you check again and see if you still see this?  If it is still there for you, let us know and which language you are using, it is possible something is broken in one of the localizations.

**Comment by 0x4kgi** [comment]
The regex syntax is still wrong. I am currently reading the `en-US` locale of the documentation.

![image](https://user-images.githubusercontent.com/17591127/74008546-1bf5e300-49bc-11ea-803c-ee74c3f513da.png)

I also checked with web.archive.org to see if the problem is only on my end, it isnt. You can take a look at [the snapshot of the page](http://web.archive.org/web/20200207071212/https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-with).

**Comment by gregli-msft** [comment]
Aha!  Got it, thanks for the reply.  There is the same code snippet in the Match function documentation, that's what I was checking, and in that article it was correct.  I'll update it for With shortly.  Thanks again!

**Comment by gregli-msft** [comment]
Thanks again for the bug report.  The With function article has been fixed.
