### ISSUE TITLE
Error associating activityparty

### ISSUE THREAD

**Issue by peteaxtell** [MicrosoftDocs/powerapps-docs#952]
The above example for 

PUT [Organization URI]/api/data/v9.0/emails(2479d20d-3a39-e711-8145-e0071b6a2001)/appointment_activity_parties

fails with

An error occurred while validating input parameters: System.InvalidCastException: Unable to cast object of type 'System.Web.OData.Formatter.Deserialization.ODataResourceWrapper' to type 'System.Web.OData.Formatter.Deserialization.ODataNestedResourceInfoWrapper'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6444b56-0e82-a336-244d-67e4c3aeed05
* Version Independent ID: cb15df8b-5ef7-25b4-24cb-a48a4ec14e9d
* Content: [Associate and disassociate entities using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
@peteaxtell Have you substituted all the unique identifiers with valid values in your system?
 - The email and the contacts?

**Comment by peteaxtell** [comment]
Yes. 

https://<orgurl>/api/data/v9.0/appointments(36ed357e-6331-ea11-a810-000d3a86ad30)/appointment_activity_parties

{
    "value":  [
                  {
                      "participationtypemask":  5,
                      "partyid_systemuser@odata.bind":  "systemusers(8ab6ef8f-9033-ea11-a812-000d3a86acda)"
                  }
              ]
}

If I use POST, I get:
Invoke-RestMethod : {"error":{"code":"0x0","message":"An error occurred while validating input 
parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type

If I use PUT, I get:
Invoke-RestMethod : {"error":{"code":"0x0","message":"An error occurred while validating input 
parameters: System.InvalidCastException: Unable to cast object of type 
'System.Web.OData.Formatter.Deserialization.ODataResourceWrapper' to type 
'System.Web.OData.Formatter.Deserialization.ODataNestedResourceInfoWrapper'

**Comment by JimDaly** [comment]
This sample was removed.
