### ISSUE TITLE
More explanation on the tip please

### ISSUE THREAD

**Issue by adamajm** [MicrosoftDocs/powerapps-docs#953]
I'm trying to have 2 different forms, one for editing, one for creating a new form. I dont' know what this means in the "tip" to set and use "a variable" .... 'Set different values for a variable in the OnNew, OnView, and OnEdit formulas. You can use this variable in the OnSave formula to determine which form is being used." Do i need to create a variable first to point to my different forms? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2000b4-4917-deb6-148f-98c97691f4fb
* Version Independent ID: 241ca44d-5ed2-335a-ae0e-78c3d90b27e2
* Content: [Understand SharePoint forms integration - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sharepoint-form-integration#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/sharepoint-form-integration.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/sharepoint-form-integration.md)
* Service: **powerapps**
* GitHub Login: @NickWaggoner
* Microsoft Alias: **niwaggon**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. You can create variables with the formulas. However, for additional information regarding any specific scenarios, please reach out to support teams with a [support ticket](https://admin.powerplatform.microsoft.com/support). You can also reach out to the [Power Apps community forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1) for general discussions.
