### ISSUE TITLE
Prerequisites are no longer valid. 

### ISSUE THREAD

**Issue by Dekard** [MicrosoftDocs/powerapps-docs#954]
The pricing page was updated in Oct for the license changes and there is no longer a 'connectivity' section. Also there is nowhere in the MS documentation stating that On-Premise Data Gateway is a Premium offering. (That was changed from standard to Premium in Feb 2019.)

Prerequisites
The user name and password that you used to sign up for Power Apps.
Administrative permissions on a gateway. (You have these permissions by default for each gateway that you install, and an administrator of another gateway can grant you these permissions for that gateway.)
**_A license that supports accessing on-premises data using an on-premises gateway. For more information, see the “Connectivity” section of the pricing page._**
Gateways and on-premises connections can only be created and used in the user's default environment.

**Comment by Nkrb** [comment]
@Dekard Can you add the page details you're specifically talking bout. This helps us to assign the issue to right people.

**Comment by Dekard** [comment]
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-management#prerequisites

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Documentation has been corrected. For more information about specifically on-premises data gateway, please refer to the [gateway](https://docs.microsoft.com/data-integration/gateway/) documentation.
