### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/powerapps-docs#955]
There appears to be missing steps/information.  Or perhaps PowerApps/Sharepoint has changed so much since this article was written, that it is no longer valid?  

As mentioned in previously closed feedbacks, you get errors if following the directions here.  While kmtk41's solution to update the DataCards works for getting rid of the "Name isn't valid" error (why isn't this required information included in the article??), it doesn't resolve the failure of SharePoint to save both fields in the Incidents list.

In my testing, I was able to get Department to cascade correctly based on Location selected but only with dmtk41's added settings.  However, when I publish and go back to SharePoint, only Location actually saves to Incidents list when adding a new item.  

In addition, this article only explains a one level cascade.  What about multi-tiered cascades?  For example, what about a cascade where Team is based on Department which is based on Location?  Do I need to add a Team column to Locations list? Or do I need to create a new list that maps Team t o Department?  And how will all this work in PowerApps with items from one list being based on the selection of an item in another list which is, in turn, based on the selection of an item in another list?  And how to you get all the selections to save correctly as fields in the main (Incidents) list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Create a dependent drop-down list in a canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/dependent-drop-down-lists)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by BlipBox** [comment]
I was able to get this working by using dkmt41's method with this adjustment:
In step 2 Instead of 
"Change the "Update" property to DataCardValue18.Selected.Result" 
use 
"Change the "Update" property to DataCardValue18.Selected.Department"

**Comment by jmbriffard** [comment]
That work well. Thanks a lot BlipBox
