### ISSUE TITLE
"Containers do not work with canvas components or within forms" ??

### ISSUE THREAD

**Issue by LenCardinal** [MicrosoftDocs/powerapps-docs#957]
Is there more explanation of the Known limitation "Containers do not work with canvas components or within forms"? At face value, that statement suggests that Containers should not even be part of this documentation!

I want to make a form with data cards that hide or show based on other card selections. Some kind of container would help. 

Maybe 'authoring groups' would work fine here? Where is the documentation on those?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 245db0a5-35a8-ea41-7680-1f041dbff03b
* Version Independent ID: 66aa308d-a4e9-3124-1b30-7686d94cd65a
* Content: [Container control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-container#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-container.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-container.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Container control is an experimental feature and doesn't work with components or forms. Currently we do not have authoring groups documentation though you can read [FAQ](https://docs.microsoft.com/powerapps/maker/canvas-apps/controls/control-container#frequently-asked-questions) about container and group for more details.
