### ISSUE TITLE
Column description 

### ISSUE THREAD

**Issue by LeonidAnishchenko** [MicrosoftDocs/powerapps-docs#958]
Can you please provide an example how to obtain  column description from  DataSourceInfo? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3184818-d8e7-0d02-924f-55f8a7a34110
* Version Independent ID: 61267e2c-bfb1-9bda-d728-62329f3f535b
* Content: [DataSourceInfo function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-datasourceinfo)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-datasourceinfo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-datasourceinfo.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
There is no way to obtain the column description from the DataSourceInfo function, nor are there any plans to add this functionality.  If you have a specific scenario in mind, please add a feature request to the [Power Apps community idea forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas).
