### ISSUE TITLE
Leaves us hanging

### ISSUE THREAD

**Issue by lfinman** [MicrosoftDocs/powerapps-docs#959]
The steps have us create a new screen, add a data table, ... then nothing.  How is the new screen used/related to the combo box we were working with in the previous step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70491d54-3aae-1104-bbe2-4162b34e4fb2
* Version Independent ID: 52ed1d09-e95f-4bb4-ac9e-cc3481cb7c93
* Content: [Choices function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-choices#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-choices.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-choices.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment]
Thanks for the bug report.  You are right, the two parts are not directly related.  I've added text to the passage that explains that what comes next is for illustration purposes only.
