### ISSUE TITLE
Sharepoint list in PowerAPP

### ISSUE THREAD

**Issue by Luanpires** [MicrosoftDocs/powerapps-docs#960]
Helo, Mr (a),

I am encountering difficulties with a SharePoint list. I have a list of SharePoint that obtained an application via PowerAPP, to reference the fields.

So, you can only get an APP directly from SharePoint, to get a nomenclature of fields from the sharePoint list.

However, some fields may have errors within PowerAPP, it says that the field does not exist and I have not found another way to reference the fields within PowerAPP.

can anybody help me? another type of SharePoint field reference in PowerAPP?

Bom Dia Sr (a),

Estou encontrando dificuldades com uma lista do SharePoint. Tenho uma lista do SharePoint que obteve um aplicativo via PowerAPP, para referenciar os campos.

Então, você só pode obter um APP diretamente do SharePoint, para pegar uma nomenclatura de campos da lista do sharePoint.

Contudo, alguns campos podem ter erros dentro do PowerAPP, diz que não existe o campo e eu não encontrei outra forma de referenciar os campos dentro do PowerAPP.

Alguém poderia me ajudar? outro tipo de referência dos campos da lista do SharePoint no PowerAPP?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please raise a support [service request](https://admin.powerplatform.microsoft.com/support) to investigate this issue.
