### ISSUE TITLE
SaveMode.SaveAndNew does not open new form

### ISSUE THREAD

**Issue by MaTeMaTuK** [MicrosoftDocs/powerapps-docs#963]
formContext.data.save(options) does not work with SaveMode.SaveAndNew.
Save works only, without new form. 

`function saveAndNew(formContext) {
    var options = {
      saveMode: 59
      /* SaveAndNew */
      ,
      UseSchedulingEngine: false
    };
    formContext.data.save(options);
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d00568ac-9426-75f7-1662-7e6083f31c64
* Version Independent ID: 491a98a2-f216-8c6e-75fb-a8a64452c9ff
* Content: [save (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data/save#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/save.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/save.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by clurdish** [comment]
The document states that setting the saveMode doesn't actually do anything other than inform event handlers. Though this isn't a "bug", I do agree that it would be a great feature to add. Replicating out of the box functionality such as "Save and New" or "Save and Close" should not be something that admins have to even worry about.

**Comment by MaTeMaTuK** [comment]
I see, Thank you for your description.
