### ISSUE TITLE
The title has a typo

### ISSUE THREAD

**Issue by jorgemorenog** [MicrosoftDocs/powerapps-docs#964]
Just a minor issue: title points at "getMax" while content is related to "getMin".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c91246-1c9a-ae4a-085c-00cfc7e30cda
* Version Independent ID: 32648f91-c7cf-b1b4-f199-b1485ed2bf09
* Content: [getMax (Client API reference) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/getmin#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getMin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getMin.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
@jorgemorenog Thanks for your feedback. This is fixed now in our publishing system, and will be live by EOD Pacific time.

Closing the issue.
