### ISSUE TITLE
Add clarification to site setting "Authentication/Registration/TermsPublicationDate"

### ISSUE THREAD

**Issue by james-reinhardt** [MicrosoftDocs/powerapps-docs#965]
This is confusing, GMT is not a format. Would be helpful to document the appropriate value to put in this field (eg. 2020-01-01T03:00:00.000Z)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a0d1d5-ea28-298e-82fb-4a1de921787d
* Version Independent ID: 789bac5b-047c-9299-25f8-25d7822b6a34
* Content: [Implement General Data Protection Regulations in Power Apps portals - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/implement-gdpr#feedback)
* Content Source: [powerapps-docs/maker/portals/configure/implement-gdpr.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/implement-gdpr.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. The documentation has been updated. Please allow some time to reflect the changes.
