### ISSUE TITLE
Dynamics CRM Application Permissions without signed-in user

### ISSUE THREAD

**Issue by ugreg** [MicrosoftDocs/powerapps-docs#967]
Does the Dynamics CRM or CDS API support this? We have several use cases following the code given in this [Python sample showcasing this](https://github.com/Azure-Samples/ms-identity-python-daemon/tree/master/1-Call-MsGraph-WithSecret) that interacts with the Microsoft Graph without a signed-in user.

We wish to do the same with a Dynamics CRM, Power Apps, CDS, but it appears there's no way to authenticate against either of these APIs unless a interactive auth is involved with a user as seen with Postman.

![image](https://user-images.githubusercontent.com/8151045/73210159-8bd3b600-40fe-11ea-8455-26d401ef5b9f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80534df2-e9da-fd0a-80bf-4bfc0dbb2fcc
* Version Independent ID: b8053ca7-e385-2f0b-06af-81b908f345a1
* Content: [Set up a Postman environment (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/setup-postman-environment?view=dynamics-ce-odata-9)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/setup-postman-environment.md)
* Service: **powerapps**
* GitHub Login: @susikka
* Microsoft Alias: **susikka**

**Comment by phecke** [comment]
@ugreg You can use a certificate or client secret instead of username/password. Create the client secret when registering the app in Azure AD.

See options available in the connection string: https://review.docs.microsoft.com/power-apps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect?branch=main#connection-string-parameters

**Comment by daniellapZ** [comment]
Hello,
@ugreg We encountered the same problem you described. Can you share how you solved it eventually? 
@phecke I can't access the link you provided, can you paste as a comment the explanation? Also, we already tried to authenticate through a client secret as we want to access those APIs without a signed-in user.
