### ISSUE TITLE
Stored Procs are supported now

### ISSUE THREAD

**Issue by willdrobins** [MicrosoftDocs/powerapps-docs#968]
The link about Oracle DB changes that brought me to this page stated Stored Procedures are supported as of 2018. Please update number 4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: defc3bb5-b886-2a70-5c7d-0e6a93587076
* Version Independent ID: aafb3d5c-7768-ca8b-043b-d2d00d04c148
* Content: [Connect to Oracle Database - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections/connection-oracledb#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-oracledb.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-oracledb.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by tapanm-MSFT** [comment]
Documentation is updated, please allow some time for changes to take effect.
