### ISSUE TITLE
Sample links are Null - samples for this detail is required

### ISSUE THREAD

**Issue by SledgeWA** [MicrosoftDocs/powerapps-docs#970]
Links leed nowhere - samples for this detail is required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e76bee5-960a-099d-e44b-20c6b50a8a46
* Version Independent ID: 6f571239-4f24-9f82-6613-5ec2a598702a
* Content: [Audit user access (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/audit-user-access#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/audit-user-access.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/audit-user-access.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by KumarVivek** [comment]
@SledgeWA Thanks for the feedback; links are fixed now.
Closing the issue.
