### ISSUE TITLE
LoadData collection confusion

### ISSUE THREAD

**Issue by Slaverty6** [MicrosoftDocs/powerapps-docs#972]
Could do with a bit of clarification on the requirements of LoadData pertaining to collections.  This page states LoadData can't create collections, they must be created first, but then in the example there's no mention of creating the collection.  Also, on the "Develop offline-capable canvas apps" page, again there is no mention of creating the collection prior to using LoadData.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ae4fe7-8801-18c4-7313-af44ffd22f75
* Version Independent ID: 32e03bf6-cbe4-70c9-7d4f-54cd2efbc583
* Content: [SaveData and LoadData functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-savedata-loaddata#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-savedata-loaddata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-savedata-loaddata.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please read [collect, clear and clearcollect functions](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-clear-collect-clearcollect) to understand and use examples for creating a collection. The current documentation is specific to SaveData/LoadData and hence creating collection examples is out of scope for this article. The first example also uses ClearCollect that creates collection.

The [Develop offline-capable canvas apps](https://docs.microsoft.com/powerapps/maker/canvas-apps/offline-apps) article mentions following bullet with link to [collections](https://docs.microsoft.com/powerapps/maker/canvas-apps/create-update-collection) article:

**Use [collections](https://docs.microsoft.com/powerapps/maker/canvas-apps/create-update-collection) and leverage functions such as LoadData and SaveData for basic data storage when offline.**
