### ISSUE TITLE
Text fields containing only number ammendment

### ISSUE THREAD

**Issue by MJBoes** [MicrosoftDocs/powerapps-docs#973]
\"values\":[$a] is imho misleadingly implicit if the joined field types are string. In the case that the joined field type is text but the content of the fields are numbers, the join fails. I suggest to explicitly distinct number joins (the current example) and text joins.
In the latter case \"values\":[\"$a\"] works for all strings, even when the joined text field contains numbers.
Cheers, Marc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715bc26c-2ccd-a040-3c96-d73cde4b982b
* Version Independent ID: c793e872-29e4-2e04-b9f4-973c01d4a123
* Content: [Embed a Power BI report in a model-driven system form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embed-powerbi-report-in-system-form#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embed-powerbi-report-in-system-form.md)
* Service: **crm-online**
* GitHub Login: @prsi-msft
* Microsoft Alias: **prsi**

**Comment by MJBoes** [comment]
Please note that the \\ (slashes) where removed from my comment. Second attempt: \\"values\\":[\\"$a\\"]

**Comment by prsi-msft** [comment]
please assign to @adrian orth

**Comment by prsi-msft** [comment]
please assign to @adrian<https://github.com/adrian> orth
Top of Form
Bottom of Form


Thanks,
Praveen

**Comment by prsi-msft** [comment]
Hey Renee, can you please get this assigned to the right owner as mentioned below? I asked @Bishal Goswami<mailto:Bishal.Goswami@microsoft.com> but he reassigned to me.

Thanks,
Praveen

From: Praveen Kumar Singh
Sent: Wednesday, January 29, 2020 2:26 PM
To: MicrosoftDocs/powerapps-docs <reply@reply.github.com>; MicrosoftDocs/powerapps-docs <powerapps-docs@noreply.github.com>; Bishal Goswami <Bishal.Goswami@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerapps-docs] Text fields containing only number ammendment (#973)

please assign to @adrian<https://github.com/adrian> orth
Top of Form
Bottom of Form


Thanks,
Praveen

**Comment by iangpgh** [comment]
@MJBoes  Thanks for your feedback. For product-related feedback, visit https://ideas.powerapps.com.  
I have forwarded to product management this suggestion for improving the documentation and the examples used.  Closing this issue.

**Comment by iangpgh** [comment]
@Mattp123 - Closes #973
