### ISSUE TITLE
Reflow description

### ISSUE THREAD

**Issue by logandersen** [MicrosoftDocs/powerapps-docs#974]
What does it mean to "reflow" a business process control?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c2d033-e865-6f35-f80e-170cc5412ae7
* Version Independent ID: 9dc26b99-18c9-5127-5990-fd1fce2c1234
* Content: [reflow (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-process/reflow#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-process/reflow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-process/reflow.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by LinnZawWin** [comment]
@logandersen based on my understanding it is refreshing the BPF control.

**Comment by Nkrb** [comment]
@logandersen Reflow of BPF means refreshing the BPF control. Let me know if this is still confusing.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
