### ISSUE TITLE
Power Apps use rights - Team Member

### ISSUE THREAD

**Issue by vitlachner** [MicrosoftDocs/powerapps-docs#977]
In PowerApps Licensing Guide is this information:
![image](https://user-images.githubusercontent.com/18088886/73402165-ee8aa480-42ec-11ea-90d2-81f931fe0af5.png)

Does it means:
1) Only 15 custom entities can be added to application?
2) 15 custom entities can be added with CRUD permissions. Next 5 custom entities can be added with Read only permisssions? Totally 20 custom enitites will exists in application.

**Comment by jimholtz** [comment]
@vitlachner 
Here's the response from licensing:
Power Apps use rights that are provided with Dynamics 365 apps only allow up to 15 custom entities per application.
For example:
•	For Sales Application; customer can have up to 15 custom entities 
•	For Customer Service Application; customer can have up to 15 custom entities, etc.
