### ISSUE TITLE
Can I connect another entity and Portal User?

### ISSUE THREAD

**Issue by devbbin** [MicrosoftDocs/powerapps-docs#980]
Can I connect another entity and Portal User?
I know that user of the portal is connected to the contact entity.
I want to connect user of the portal and another entity.
Is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb232c20-8b53-8134-efa6-17578a6a03bd
* Version Independent ID: 6036aeff-77be-903a-bb3f-be2858a47e4b
* Content: [Create web roles for a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/create-web-roles)
* Content Source: [powerapps-docs/maker/portals/configure/create-web-roles.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/create-web-roles.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Hi @devbbin, not directly. But, you can create a new entity with relationship with the Contact entity. For example, you can add different 'types' of contacts to signify the difference.
