### ISSUE TITLE
Entity List View-select dropdown display name/translations not working

### ISSUE THREAD

**Issue by Edwin-VC** [MicrosoftDocs/powerapps-docs#981]
I'n been working with ADX/MicrosoftCRMPortals for a long time already and this is been an issue for quite some time.

When configuring the Entity List you add on or more predefined views to be available in the portal. In doing you, when you choose 'advanced' it will allow for a 'Display Name' for each pre-configured portal language to mask the default 'View' name from CRM. I'd like to give these CRM Views dedicated for the portal a name that will allow the  CRM users and system admins to easily recognize the purpose of that specific view, like 'PORTAL: My open ...; . This advanced but readily available configuration feature would allow me to do so without the Portal users being able to see this Portal-prefix.

But for this feature is not working at this time (and as long as I can remember)

![image](https://user-images.githubusercontent.com/41291991/73526488-a31de680-4411-11ea-9542-6d20537ea574.png)

![image](https://user-images.githubusercontent.com/41291991/73526690-0576e700-4412-11ea-9eb8-6851896d112e.png)

What is it I am missing about this feature?

**Comment by tapanm-MSFT** [comment]
Hi @Edwin-VC, please reach out to support team with a [service request](https://admin.powerplatform.microsoft.com/support) for investigation on this issue.
