### ISSUE TITLE
Accessing property-set values from index.ts

### ISSUE THREAD

**Issue by kanivalanr** [MicrosoftDocs/powerapps-docs#982]
Hey, could you help me with how to access these property-set values in index.ts
I 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf0a2b0-63d8-ab62-e8a4-f383344e779c
* Version Independent ID: 4093dc5b-4cb7-b3f8-5bfa-7d40e02eafa9
* Content: [Property Set Element - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/property-set#feedback)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property-set.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/property-set.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment]
@kanivalanr Please look into one of the sample components and see how the property set values are called in index.ts file.

**Comment by kanivalanr** [comment]
I couldn't find any sample component that shows usage of <property-set> in <data-set>. All of that data-set sample components are having empty <data-set>.

Below is the link I am referring for the sample components
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/use-sample-components

**Comment by Nkrb** [comment]
@kanivalanr 
Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
