### ISSUE TITLE
PreventDefault is not working in UUI anymore.

### ISSUE THREAD

**Issue by serifogluseren** [MicrosoftDocs/powerapps-docs#983]
Preventdefault is not working as expected anymore. Has something changed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1e3c66-2860-086a-d0ef-a5c4e50acae5
* Version Independent ID: 73f1c360-b1d1-4524-4656-b5352522a783
* Content: [preventDefault (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/save-event-arguments/preventdefault?source=docs#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/save-event-arguments/preventDefault.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/save-event-arguments/preventDefault.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by polshgiant** [comment]
Running into the same issue

**Comment by Miesjh** [comment]
Works just fine here with Unified Interface.

**Comment by serifogluseren** [comment]
No, definitely not working in our region. The topic has additionally reported to the support and they accepted as a bug. They said **"newly identified bug"** but it is fact that we have reported this in January! We have never heard anything from @KumarVivek !

**Comment by AzmatMahsood** [comment]
For me its working on the Main form but not on the quick create form anybody else having this problem

**Comment by dmac1108** [comment]
I am also having a problem with the quick create form, @AzmatMahsood.

**Comment by dmac1108** [comment]
This is working for me on a quick create form.

**Comment by AzmatMahsood** [comment]
I used "setNotification" on a field which prevents the save and works on quick create

**Comment by Nkrb** [comment]
preventdefault() doesn't work on Appointments, it should work on other things in UCI.

**Comment by Nkrb** [comment]
@dmac1108 @serifogluseren Can you confirm if this method is still not working as expected?

**Comment by serifogluseren** [comment]
> @dmac1108 @serifogluseren Can you confirm if this method is still not working as expected?

Yes, it has been now working as expected.
