### ISSUE TITLE
code doesn't work

### ISSUE THREAD

**Issue by GoCloudHub** [MicrosoftDocs/powerapps-docs#984]
basic html errors no /tr, /th instead of /tr
Liquid error: Exception has been thrown by the target of an invocation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46dc750-10f1-6755-5ff0-86156b9db110
* Version Independent ID: d1335f42-fabb-61c0-5d38-a718b28d7a65
* Content: [Render the entity list associated with the current page in a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/render-entity-list-current-page#feedback)
* Content Source: [powerapps-docs/maker/portals/liquid/render-entity-list-current-page.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/liquid/render-entity-list-current-page.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Thank you for your feedback. Content is updated. Please allow some time to reflect the changes.
