### ISSUE TITLE
Missing Web Service Error Code

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#985]
Error for saving appointment with invalid email attendee
Hex: 80040b0b
Number: -2147748619

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223aafba-8d35-a232-ab10-d3aac99d85f2
* Version Independent ID: 2ec5626c-56f5-abd6-d458-1d8f9e33b4b0
* Content: [Web service error codes (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/web-service-error-codes#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/web-service-error-codes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/web-service-error-codes.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment]
@LinnZawWin 
Thanks for pointing this out. The table has been updated to the latest list of error codes.
