### ISSUE TITLE
Not seeing Attachments Control in Model apps

### ISSUE THREAD

**Issue by bpasham** [MicrosoftDocs/powerapps-docs#988]
Even after enabling SharePoint integration .. adding attachments to entities seems to be missing

**Comment by Mattp123** [comment]
@bpasham - Thanks for your feedback. Make sure the entity has the attachments option selected in the entity definition per the screenshot. If you still experience issues, consider contacting support. For information see: https://powerapps.microsoft.com/support/
Closing issue.
![image](https://user-images.githubusercontent.com/21203819/84690147-de1f4300-aef6-11ea-8f8a-9f8119e5093f.png)
