### ISSUE TITLE
Preventing user from accessing specific page

### ISSUE THREAD

**Issue by MaikelW** [MicrosoftDocs/powerapps-docs#989]
Hi,
I'm trying to restrict access to a specific page for a specific user. Is it possible to accomplish this?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e65187d6-12e3-8244-e6fc-a82cef869bf9
* Version Independent ID: 54f6c6fa-00c7-8ab9-f1a7-02517b1c3601
* Content: [Control webpage access for a portal - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/webpage-access-control)
* Content Source: [powerapps-docs/maker/portals/configure/webpage-access-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/configure/webpage-access-control.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Please use [Restrict Read](https://docs.microsoft.com/powerapps/maker/portals/configure/webpage-access-control#restrict-read) right.
