### ISSUE TITLE
Form Fields | Field Types Gone

### ISSUE THREAD

**Issue by JBubs** [MicrosoftDocs/powerapps-docs#99]
A bunch of field types in my list were defined as "Choice" and radio button. When I customize the form the radio buttons disappear and the fields turn into dropdowns. How do I get them back to radio buttons?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eacf34e-9ae6-5c64-5fec-c250fc9986d1
* Version Independent ID: 7d248abd-225e-c914-e871-f8d2424ed8c0
* Content: [Customize a SharePoint list form - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form)
* Content Source: [powerapps-docs/maker/canvas-apps/customize-list-form.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/customize-list-form.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by AFTOwen** [comment]
Hi, @JBubs! Thanks for your question. You need to unlock the card and replace the dropdowns with radio buttons. For information about how to customize a card, see [Understanding cards](https://docs.microsoft.com/powerapps/maker/canvas-apps/working-with-cards).
