### ISSUE TITLE
AppTestResults Entity

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#991]
Is there an AppTestResults entity in CDS? I do not see it when I browser the data in CDS from make.powerapps.com &gt; Data &gt; Entities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b15deb16-02e4-9005-2dbd-917f8308b47d
* Version Independent ID: 51cc413b-0fd1-5a63-ddfa-16b3fb4c9e88
* Content: [Working with Test Studio for testing canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/working-with-test-studio#processing-test-results)
* Content Source: [powerapps-docs/maker/canvas-apps/working-with-test-studio.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/working-with-test-studio.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **aheaney**

**Comment by tapanm-MSFT** [comment]
Thanks for reaching out. It's a sample: 
*The following sample saves each test case results to the custom AppTestResults entity in Common Data Service.*
You can use an entity of your choice.
