### ISSUE TITLE
Associate Example

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#992]
This page shows how to associate two records using a Single-Value Navigation property (a lookup). However, there is no information on associating two records using a Multi-Value Navigation Property (N:N relationship).

Please either add an N:N example to this page, if the updateRecord method can be used to perform the association. Or provide a link to another page regarding how to associate two records in an N:N relationship using the Xrm.WebApi namespace. Or add a note indicating that such an action is not possible using the Xrm.WebApi namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736633bc-d0f6-0665-c487-dab6c36a677f
* Version Independent ID: b83eba0e-908d-a1bc-5e81-a642afb9276c
* Content: [updateRecord (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/updaterecord)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/updateRecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-WebApi/updateRecord.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by srikanth-paladugula** [comment]
In case of entities of type Activity( ex: task,email.. )/ Custom Activity(ex:cust_event) the @odata.bind formation is different than given in above example of associations to the related entities.

Example : Consider we have a custom lookup field to opportunity on task entity. 
Entity: Task
	DisplayName  : Task
	SchemaName : Task
	LogicalName  : task
Custom field(on Task):
	DisplayName   : Parent Opportunity
	LogicalName   :  hsl_parentopportunityid
	SchemaName  : hsl_ParentOpportunityId
	Type                 : Lookup to opportunity

To update Parent Opportunity field on task, the format should be like below
    var data={};
    data["{LookupField.SchemaName}_{Task.SchemaName}@odata.bind"] = 
            "/opportunities(216d7c95-5d3c-ea11-a812-000d3a3ab486)";
In our case, it should be like
     data["hsl_ParentOpportunityId_Task"]="/opportunities(216d7c95-5d3c-ea11-a812-000d3a3ab486)";

To update Regarding on task, the format should be like below
    var data={};
data["{regardingobjectid}_{TargetEntity.LogicalName}_{Task.LogicalName}@odata.bind"] = 
"/TargetEntityPluralName(216d7c95-5d3c-ea11-a812-000d3a3ab486)";
    Support if our target is account, it should be like
data["regardingobjectid_account_task@odata.bind"]="/accounts(316a7c95-5d3c-ea11-a812-000d3a3ab486)";

**Comment by Nkrb** [comment]
@devlinl Thanks for contacting us. We have updated the docs with the examples. Closing the issue. 

https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online/execute
