### ISSUE TITLE
openInNewWindow Window Option has no effect in UCI

### ISSUE THREAD

**Issue by anasufovic** [MicrosoftDocs/powerapps-docs#994]
This doc should specify what the valid windowOptions are. The "openInNewWindow" option doesn't have any impact when set to true or false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef001b56-f366-7866-693b-c403f84dbab3
* Version Independent ID: e3d1fbdc-84a5-ce3c-af1e-11e98b14418f
* Content: [openWebResource (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openwebresource#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Phrozt** [comment]
There is no openInNewWindow option, at least not how I read it.  Looks like the only options are height and width.

**Comment by anasufovic** [comment]
Hello @Phrozt thanks for the reply. What is the difference between this method and this one? 

https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/navigation/openwebresource

I understand that this is documentation from the component framework but generally speaking this should be the same API it seems, it's just used in a different place in powerapps.

Also please take a look at the type definitions that we use when writing this in TypeScript
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e1f3734de2cae97483360528115559fda78c88b3/types/xrm/index.d.ts#L4475
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e1f3734de2cae97483360528115559fda78c88b3/types/xrm/index.d.ts#L4261

**Comment by Phrozt** [comment]
I grant that they look very similar, but I'm just going by the documentation listed on docs.

If you look at the deprecated method that Xrm.Navigation.openWebResource replaces, height/width were their own separate options, and there were no other options to be set.

https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/jj602956(v=crm.8)?redirectedfrom=MSDN#openwebresource
