### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by jsprehe** [MicrosoftDocs/powerapps-docs#995]
The link and text on the very last line points to Business Rules. Clearly it should be Business Process Flows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483698a2-15df-b321-a08b-aa3fef646f94
* Version Independent ID: d7ad68ec-6c4e-2880-f7f1-21c5af670307
* Content: [Work with business processes in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/user/work-with-business-processes#feedback)
* Content Source: [powerapps-docs/user/work-with-business-processes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/user/work-with-business-processes.md)
* Service: **powerapps**
* GitHub Login: @mduelae
* Microsoft Alias: **mduelae**

**Comment by mduelae** [comment]
@jsprehe thanks for the feedback. I have updated the link and republished the topic. You should see the changes in the next hour or so. 

Thanks,
Mints
