### ISSUE TITLE
No operator for "does not contain data"

### ISSUE THREAD

**Issue by stevenfayers** [MicrosoftDocs/powerapps-docs#996]
There is no operator to query on fields that do not contain data, or if there is, it's not clear on this page what the operator is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
There are several examples where the `null` keyword is used to determine when a field contains no data. Is that different from what you are looking for?

**Comment by stevenfayers** [comment]
Thanks for your reply.  I can now see null in the examples but there wasn't
a specific mention of it outside of the examples so wasn't immediately
obvious.

But thanks for responding. I have the answer I need.
Cheers
Steven

**Comment by phecke** [comment]
@stevenfayers  Thanks for the feedback,.
