### ISSUE TITLE
Customer Self Service Portals

### ISSUE THREAD

**Issue by samikshashetty** [MicrosoftDocs/powerapps-docs#998]
I need to edit the web form of case creation by deleting and adding new fields, I created a new web form and web form steps in them but nothing is reflecting in the portals ? Is there step I missed? Do I need some extra configuration?

Could you guide through some steps for setting up account  scope and  scope for a particular customer or any related docs related to this would be a big help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0f78157-6d85-d438-2dd3-deeded19612b
* Version Independent ID: 9c08bf4d-ca4f-0055-dfcb-042b26efa9cb
* Content: [Create a portal in Power Apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/portals/create-portal#feedback)
* Content Source: [powerapps-docs/maker/portals/create-portal.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/portals/create-portal.md)
* Service: **powerapps**
* GitHub Login: @tapanm-MSFT
* Microsoft Alias: **tapanm**

**Comment by tapanm-MSFT** [comment]
Hi @samikshashetty, thank you for reaching out. Please check case [entity permissions](https://docs.microsoft.com/powerapps/maker/portals/configure/assign-entity-permissions) and see if [clearing the cache](https://docs.microsoft.com/powerapps/maker/portals/admin/clear-server-side-cache) helps. If the problem persists, suggest to please work with the support team by creating a [service request](https://admin.powerplatform.microsoft.com/support) for further investigation.
