### ISSUE TITLE
"NavigateTo" dialog successCallback Issue 

### ISSUE THREAD

**Issue by abdelaziz-benelfakir** [MicrosoftDocs/powerapps-docs#999]
The callback function is called when navigating to dialog not on clonsing it

**Comment by Nkrb** [comment]
@abdelaziz-benelfakir Can you give us more details about the issue.

**Comment by abdelaziz-benelfakir** [comment]
When I use the function "NavigateTo" to open a webressource the callback function is called when the webressource is Opend not on close

**Comment by Nkrb** [comment]
@abdelaziz-benelfakir This issue is fixed, can you verify and let us know if this is still happening with you.

**Comment by Nkrb** [comment]
@abdelaziz-benelfakir Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
